### ISSUE TITLE
Sound Blaster PCI 128 - Intel Celeron 466

### ISSUE THREAD

**Issue by DimMan88** [86Box/86Box#1006]
Any chance to add again the Sound Blaster PCI 128 and the Celeron 466?

**Comment by anabate123** [comment]
@DimMan88 Well, this might be your somewhat lucky day for you, because I opened this pull request for you.
https://github.com/86Box/86Box/pull/1007

**Comment by DimMan88** [comment]
@anabate123 Awesome! Thanks!

Now all I need is the Blaster PCI 128.

*By the way. Is there a way to start automatically the VMs fullscreen from the Manager?

**Comment by anabate123** [comment]
@DimMan88 @OBattler actually re-added the Sound Blaster PCI 128.

**Comment by DimMan88** [comment]
@anabate123 Yes, I saw that. Cool! 

I will check all these tomorrow.

I'm new to 86box and GitHub and I want to contribute as well.

**Comment by OBattler** [comment]
Closing this issues because it's already fixed.

**Comment by jadasse** [comment]
For some reason I don't see the sound blaster pci 128

**Comment by JustinJ553** [comment]
> 
> 
> For some reason I don't see the sound blaster pci 128

Its ES1371

**Comment by jadasse** [comment]
I KNEW IT
(thanks tho)> > 
> 
> > 
> 
> > For some reason I don't see the sound blaster pci 128
> 
> 
> 
> Its ES1371
