### ISSUE TITLE
INPUT LIMIT on Console

### ISSUE THREAD

**Issue by leesa49** [86Box/86Box#1011]
Hello~

Real Machine can input long character. but 86box can not......

in programming.... make a batch file

tlink -m -f -Lc:\language\bcpp31\~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~

but follwing problem... can not launch command

![limit_input](https://user-images.githubusercontent.com/55971868/94095448-b8da9300-fe5c-11ea-99c0-55ea2c1a463f.png)

**Comment by OBattler** [comment]
Are you even using the same DOS version on 86Box that you did on the real machine?
