### ISSUE TITLE
CD Audio doesn't handle pregap properly if tracks are in separate files

### ISSUE THREAD

**Issue by NicknineTheEagle** [86Box/86Box#1035]
If you mount a CUE/BIN image where every track is in a separate file (which is Redump's standard way of storing images), track pregap is not handled properly resulting in silence being played before the actual audio track. Normally, pregap is skipped. Example cue sheet: http://redump.org/disc/2251/cue/

**Comment by OBattler** [comment]
Coincidentally enough, I fixed just this bug later after someone else also happened to report it on IRC.
