### ISSUE TITLE
Hard disk geometry is lost in build 2580

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1040]
**Describe the bug**
In build 2580, ATAPI is set by default in the menu for selecting an existing HDD:

![2020-10-24_221414](https://user-images.githubusercontent.com/58270614/97091846-8aacc680-1647-11eb-8f2b-566217137ad0.jpg)

If you select an existing hard disk image and then switch to IDE, then the geometry (CHS & Size) of the hard disk is lost.
Build 2579 did not have this bug: SCSI is set by default in the existing HDD selection menu:

![2020-10-24_221502](https://user-images.githubusercontent.com/58270614/97091931-2cccae80-1648-11eb-82a5-e86c65fb71b3.jpg)
If you select an existing hard disk image and then switch to IDE, then the geometry (CHS & Size) of the hard disk is fine.

![2020-10-24_223222](https://user-images.githubusercontent.com/58270614/97092003-d744d180-1648-11eb-9d97-5ac5c7465aa8.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise x64 v1909
 - 86Box version: v2.10 build 2580
 - Build type: Optimized Skylake

Also in build 2580 there is a new bug with 808x emulation, which is described in detail here: https://github.com/86Box/86Box/issues/705

**Comment by Winins0** [comment]
Use the newest build if you can.

**Comment by maximus105** [comment]
Both of these bugs (HDD geometry bug and 808x emulation bug) are still present in the latest build. I mean both of these bugs have appeared since build 2580.

**Comment by OBattler** [comment]
This has now been fixed.
