### ISSUE TITLE
133MHz Pentium on Socket 5 Emulation

### ISSUE THREAD

**Issue by CRTRevivalDreamer** [86Box/86Box#1043]
**Is your feature request related to a problem? Please describe.**
Some Socket 5 motherboards also supported the 133 MHz Intel Pentium processor,
but 86Box can't have such a configuration now.

**Describe the solution you'd like**
I would like 86Box to be able to emulate a Socket 5 PC with a 133 MHz Intel Pentium processor.

**Describe alternatives you've considered**
None.

**Additional context**
[The Apollo by American Megatrends is an example of a motherboard that supported the processor configuration I'm talking about.](https://stason.org/TULARC/pc/motherboards/A/AMERICAN-MEGATRENDS-INC-Pentium-APOLLO.html)

**Comment by anabate123** [comment]
Well CRTRevivalDreamer, today's your lucky day, because I've opened this pull request right here...
https://github.com/86Box/86Box/pull/1044

**Comment by OBattler** [comment]
Yes, Socket 5 indeed supported the Pentium 133, evidence here: https://www.vogons.org/viewtopic.php?t=49306 . As such, I have merged anabate123's pull request and am closing this issue.
