### ISSUE TITLE
Second Reality demo is broken

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#1050]
**Describe the bug**
The Second Reality demo refuses to start after the sound card selection screen and just hangs on a black screen while the sound freezes.

**To Reproduce**
1. Run the demo EXE as normal
2. Select sound card, sound quality and loop settings
3. Start the demo

**Expected behavior**
Demo should start properly, no hangs or crashes.

**Screenshots**
![86box_14](https://user-images.githubusercontent.com/29031916/98119283-5d81d300-1ee7-11eb-86d7-f6017f86ef98.PNG)

**Desktop (please complete the following information):**
 - OS: Win10 2004 build 19041.572
 - 86Box version: Custom (cfb559de13b08b1412ecbf0ff88d1c9e4ab4f898)
 - Build type: Dev

**Additional context**
Demo run on a mostly clean MS-DOS 6.22 system with EMM386 added to config.sys.

**Comment by OBattler** [comment]
I'm quite sure the demo has to be run without EMM386.

**Comment by ppgrainbow** [comment]
Did you try running the game without EMM386 (or any other expanded memory manager) REM'd out in the CONFIG.SYS file?

**Comment by WinFutureX** [comment]
Disabling emm386 doesn't change anything
![86box_15](https://user-images.githubusercontent.com/29031916/98810224-d807a100-2459-11eb-9aa4-5475593709a0.PNG)

**Comment by OBattler** [comment]
It turns out it's a problem with the PIT - the fix I did to fix the MR BIOS'es, broke Second Reality.

**Comment by mr-falafel** [comment]
Wasn't sure whether to open a new issue or just to add to this one, so feel free to correct me and I'll move this elsewhere.

Second Reality freezes for me on the setup screen, here:
<img width="620" alt="2024-09-14 17_27_54-" src="https://github.com/user-attachments/assets/1da27585-79c2-426d-a531-13798888d07f">

I am using the files available at: https://www.pouet.net/prod.php?which=63

My DOS configuration:
<img width="618" alt="2024-09-14 17_26_45-" src="https://github.com/user-attachments/assets/ef0052e4-a9e3-4818-ae8f-5898c492b361">
<img width="617" alt="2024-09-14 17_27_01-" src="https://github.com/user-attachments/assets/a2eab59a-ee4c-467c-a772-fe03740b997b">

Here are some of my guest specifications:
```
[General]
vid_renderer = qt_software
confirm_exit = 0
video_fullscreen_first = 0
confirm_reset = 0
language = system
open_dir_usr_path = 1
video_gl_vsync = 1
sound_gain = 9
force_43 = 1
hide_status_bar = 1
vid_resize = 2
window_fixed_res = 800x600

[Machine]
machine = ms4144
cpu_family = i486dx2
cpu_speed = 66666666
cpu_multi = 2
cpu_use_dynarec = 1
time_sync = local
fpu_type = internal
fpu_softfloat = 0
mem_size = 8192

[Video]
gfxcard = stealth64v_pci
video_fullscreen_scale_maximized = 1

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sb16
fm_driver = nuked
```

Here are some of my host specifications:
```
OS: Windows 11 23H2
OS Build: 22631.3880
CPU: AMD Ryzen 9 5900X
86Box build: 86Box-Windows-32-b5634
```

**Comment by eddmanx** [comment]
That's unrelated to the original problem. It's caused by the mainboard for some reason.

**Comment by mr-falafel** [comment]
> That's unrelated to the original problem. It's caused by the mainboard for some reason.

Right you are! I changed over to the ASUS PVI-486SP3C and it runs great. Thank you for that information! Do you know if it is just the MSI MS-4144 that has this issue or if other motherboards are also affected? Is there an open issue about this?
