### ISSUE TITLE
Add support for emulating a motherboard (Tyan Trinity 371 is chosen)

### ISSUE THREAD

**Issue by Raulonthetest** [86Box/86Box#1051]
**Is your feature request related to a problem? Please describe.**
No. My mind has this idea for some reason 😂.

**Describe the solution you'd like**
Add emulation for RC440BX. I tried to do it but start up hangs at D3 D1 (POST card code). Something related to missing SIO emulation, PCI configuration error or bad BIOS combining?
BTW, The BIOS link is: http://cwcyrix.duckdns.org/intel-legacy-files-archive/Motherboards/Desktop/1990s/Intel%20RC440BX/BIOS/rcbios14.exe (the BIOS is AMI and not Phoenix, because Intel AMI BIOS updates have boot block file) 
Specifications: http://www.edstrainsonline.com/support/pdf/rc440bx.pdf
Missing SIO to be emulated (FDC37M707): http://pdf1.datasheet.su/smsc/fdc37m707-ms.pdf

**Describe alternatives you've considered**
If it can't be emulated, then one of the following could be emulated:
-Intel Pocono: Socket 7, BIOS: http://cwcyrix.duckdns.org/intel-legacy-files-archive/Motherboards/Desktop/1990s/Intel%20-%20Unknown%20%5bPocono%5d%20(OEM)/BIOS/10002cj0.zip, Specifications: missing as this is an OEM-only board
-Tyan Trinity 371: Slot 1/Socket 370, SIO: Winbond '977 EF Super I/O, System Management: Winbond W83783S, Chipset: Intel 440BX, BIOS: https://www.infania.net/misc/moboarchive/Tyan/bios/bx/Bx57200a.exe

**Additional context**
No additional context.

**Comment by amdk6** [comment]
Unfortunately, the RC440BX seems to use the Intel 28F004S5 flash chip which is a 4 Mbit flash chip.

**Comment by Raulonthetest** [comment]
Maybe the Tyan Trinity 371 could be emulated instead. 🤔

**Comment by amdk6** [comment]
Well, the W83783S seems to be based on the W83782D.
But I think it has a Winbond flash chip which isn't implemented.

**Comment by Raulonthetest** [comment]
> Well, the W83783S seems to be based on the W83782D.
> But I think it has a Winbond flash chip which isn't implemented.

To me it seems the BIOS support many different flash chips.
The ones that I found are:
Am29F002
Intel 28F002BX-T
SST 29EE020
SST 39SF020
ATMEL 29C020
Winbond W29C020
SyncMOS F29C51002
I also found an eBay listing picture that was a Trinity 371 with an SST chip (
![image](https://user-images.githubusercontent.com/64203039/98135186-3962c980-1ec8-11eb-8d18-1f57919e1f83.png).

**Comment by tiseno100** [comment]
Tyan Trinity 371 uses the AMI EASY BIOS. We already have a Tyan board with the same BIOS Implemented. I don't think we need any more except if the board comes from another chipset(VIA)

**Comment by Raulonthetest** [comment]
Testing will be done.
Case closed
