### ISSUE TITLE
OS/2 2.11 Crashing Issue

### ISSUE THREAD

**Issue by thunderbird32** [86Box/86Box#1055]
**Describe the bug**
When attempting to run either DeScribe 4.0 I'm received the following error, and I'm not sure if it's an 86box bug, or a program error:

The first time I try to run DeScribe I get a pop-up from the operating system that says there's been an "access violation"
![001](https://user-images.githubusercontent.com/35811767/98432660-0f570600-2086-11eb-8684-836e42f87775.png)
I can click OK and the program never opens. The next time I try to open the application it kernel panics (I think that's the correct terminology on OS/2) and the system must be rebooted.
![002](https://user-images.githubusercontent.com/35811767/98432674-301f5b80-2086-11eb-845b-1ba92cd3954e.png)

I'm running OS/2 2.11 with all fixpaks. Here is the VM: https://mega.nz/file/hwsiiaqY#NyCARVoGCHt04zTpbMoG1cAQfzmr9Pg3WY7QNoLCREU

**To Reproduce**
1. Install DeScribe 4.0 (already done in uploaded file)
2. Run application
3. Error 1 occurs and program crashes
4. Run application a second time
5. Error 2 occurs and system crashes

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 20H2
 - 86Box version: v3.0 build 2625
 - Build type: Regular

**Comment by thunderbird32** [comment]
More information for you. I decided to try this in OS/2 Warp to see if it behaved any differently. When starting the installer I got the following error:
![image](https://user-images.githubusercontent.com/35811767/99742406-00664f80-2a99-11eb-907f-2db32f01b645.png)
Clicking "Cancel" does progress on to the installer (which seems to complete correctly), but then the program behaves the same way following the install.

**Comment by OBattler** [comment]
Could this bug be related to the SCSI controller?

**Comment by thunderbird32** [comment]
I suppose that is possible. If so, it is an issue that occurs with both the AHA-154xC and the AHA-154xCF. I suppose it's possible that the application just doesn't like SCSI disks/controllers. That said, as the error in my second post comes up *before* the installer even opens, the issue would occur even if you were booting from IDE. Just having a SCSI card in the system might be enough to cause the error. I will spin up an OS/2 system with no SCSI card at all to see if that makes a difference.

**Comment by thunderbird32** [comment]
I get the same error as the second screenshot on a machine with no emulated SCSI card. **However**, the application otherwise works correctly. So, I suppose the issue is fixed in as much as the application works, but something still seems to be **off**.

**Comment by TC1995** [comment]
Well, on Warp here it installs fine and works too.
Let me try on OS/2 2.1x.

**Comment by thunderbird32** [comment]
Seems to work fine on build 3777 now. Something must have changed that resolved the issue in the intervening time.
