### ISSUE TITLE
Add host command line option to mount a floppy

### ISSUE THREAD

**Issue by Altheos** [86Box/86Box#1060]
**Is your feature request related to a problem? Please describe.**
It could be useful for a frontend. For instance it would be possible to launch a pc booter game directly from command line.
Also, floppy could be mounted directly in a VM : no need to search for img file path.

**Describe the solution you'd like**
Add a switch like "fd0: c:\xxxxx\xxx.img"

**Describe alternatives you've considered**
None

Regards.

**Comment by dhrdlicka** [comment]
What makes this approach better than simply having a config file for each booter game? You would still have to search for the image file, except in a command prompt rather than a GUI.

**Comment by Altheos** [comment]
You have the answer in your own question : using multiple configuration files is tedious.
Using a simple "game" frontend (Launchbox or one of many others) where the full game path is stored, it would be possible to launch emulator , automatically mount the floppy image and even boot it directly (in case of a booter game).
By the way : adding an option to enable read-write on command line would be userfull too.
Thanks.

**Comment by OBattler** [comment]
It would really be that simple since the emulator has no way to guarantee the floppy drive is configured correctly in either the configuration file/Settings or in the emulated machine's CMOS Setup.

**Comment by Altheos** [comment]
Maybe as a start, let user have the responsability to correctly configure guest and do nothing if it's not the case ?

**Comment by OBattler** [comment]
> You have the answer in your own question : using multiple configuration files is tedious.
Using a simple "game" frontend (Launchbox or one of many others) where the full game path is stored, it would be possible to launch emulator , automatically mount the floppy image and even boot it directly (in case of a booter game).

It's not really tedious. Yes, you have to manually create them but only one. After that, you just set your launcher to use them by passing them as a parameter to 86Box, for example: 86Box kings_quest.cfg .

But I could cobble together some parameter to do this.

**Comment by OBattler** [comment]
This is now done. Example usage: 86Box -I A:c:\86box\kings_quest.img . You can also use --image instead of -I .
