### ISSUE TITLE
IBM PS/1 2121+isa floppy issues

### ISSUE THREAD

**Issue by Altheos** [86Box/86Box#1061]
**Describe the bug**
Can't use floppy images on PS/1 2121+isa without errors.

**To Reproduce**
1. Configure IBM PS/1 2121, PS/2 mouse, internal video, internal HDD controller, internal FDD controller, 3,5 inches floppy drive
2. Insert a floppy image as img.
3. On standard 3,5 inches drive : floppy won't boot. This is probably expected. ![floppy ps1 PNG](https://user-images.githubusercontent.com/29195397/98530166-d9c93d00-227e-11eb-8f23-17eb6e93c5d1.jpg)
But using a PS/2 3,5 inches drive : floppy boot but errors with "Invalid drive specification"
![floppy ps1-2](https://user-images.githubusercontent.com/29195397/98530194-e64d9580-227e-11eb-9bd4-fedc810bb971.jpg)

**Expected behavior**
PS/1 should gives no errors using PS/2 drive.
Besides, maybe it's related or not, the bios configuration utility "CONFIGUR.EXE" doesn't seem to keep configuration.
![floppy ps1-3](https://user-images.githubusercontent.com/29195397/98530564-5f4ced00-227f-11eb-81a2-098fe0b52e15.jpg)

**Desktop (please complete the following information):**
 - 86Box version: 2625
 - Build type: dev

**Comment by OBattler** [comment]
The invalid drive specification is actually more likely to be for C:. Did you partition and format the drive?

**Comment by Altheos** [comment]
Sorry, hard Drive was broken and I did not notice it.
