### ISSUE TITLE
8088 emulation issue

### ISSUE THREAD

**Issue by doomgod** [86Box/86Box#1062]
**Describe the bug**
Cannot execute 'basica samples.bas' or 'basic music.bas' from the PC DOS 1.0 image. It hangs on the BASIC screen or immediately reboots. Happens with both 1981 and 1982 ROMs.

**To Reproduce**
1. Use the very default 86Box configuration
2. Boot from the genuine PC DOS 1.0 image ( MD5 = 73c919cecadf002a7124b7e8bfe3b5ba )
3. Enter 01-01-90 as date
4. Execute 'basic music.bas' or 'basic', then LOAD"music.bas"
5. System hangs on BASIC screen or reboots

**Expected behavior**
The program should be loaded and run

**Screenshots**
![20201110-211645-714](https://user-images.githubusercontent.com/1215088/98735300-39753480-23b4-11eb-8e45-1abdce51d0ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - 86Box version: v3.00 build 2580 and up to current
 - Build type: Skylake optimized

**Additional context**
Introduced in build 2580. Tested 2579 with no issue.

**Comment by maximus105** [comment]
I confirm this bug. It appeared in build 2580 and persists until the last build 2627. In build 2579 everything works fine.
