### ISSUE TITLE
Windows NT 3.51 Setup freeze

### ISSUE THREAD

**Issue by Winins0** [86Box/86Box#1078]
**Describe the bug**
On the latest build, on the TXT phase the Windows NT 3.51 Setup freezes with no disk activity.

**To Reproduce**
1. Start Windows NT Setup
2. Get to the file copy phase

**Expected behavior**
The setup should not freeze.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - 86Box version: 3.0 build 2636
 - Build type: Dev

**Additional context**
The setup freezes at a random point during the file copy operation. This problem does not occur on build 2633.
[86box.txt](https://github.com/86Box/86Box/files/5545477/86box.txt) Here is my config file.

**Comment by ppgrainbow** [comment]
What configuration did you use when you attempted to install Windows NT 3.51?

**Comment by Winins0** [comment]
@ppgrainbow : I posted the config in the "Additional context" part.

A bit of a followup, seems like 2634 really broke NT 3.51 as when it boots, it stays at the login background with no input accepted. When I hard reset, you get this.
![photo_2020-11-16_13-03-45](https://user-images.githubusercontent.com/65453129/99351806-778dbf00-28b2-11eb-9f22-2d36689962f3.jpg)

Don't really know what change in 2634 broke NT 3.51 so bad. Either way, I am staying on 2633 until this bug is fixed.

**Comment by OBattler** [comment]
Can you post your 86box.cfg?

**Comment by Winins0** [comment]
It is already on the main post. I uploaded as a .txt as GitHub didn't let me upload it normally.

**Comment by OBattler** [comment]
This is now fixed.
