### ISSUE TITLE
[i440BX] machines hang in build 2640

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1091]
**Describe the bug**
In build 2640, these machines freeze during the MS-DOS 6.22 boot phase. In build 2639, everything loads properly.
[i440FX] ASUS P/I-P65UP5
[i440FX] ASUS KN97
[i440BX] ASUS P2B-LS
[i440BX] ASUS P3B-F
This bug appeared in build 2640 and persists until the last build.

**Screenshots**
![2020-11-17_121030](https://user-images.githubusercontent.com/58270614/99380646-e9760080-28d2-11eb-8e6d-497e147b8177.jpg)

**Desktop (please complete the following information):**
 OS: Windows 10 Pro x64 v2009
86Box v3.00 build 2640
Build type: Optimized Skylake

**Comment by OBattler** [comment]
This is now fixed.
