### ISSUE TITLE
When another drive is selected, the cursor stays highlighted on the previously selected drive

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1092]
**Describe the bug**
In the menu for selecting HDD, FDD & CD-ROM drives, and other removable devices, when another drive is selected, the cursor remains highlighted on the previously selected drive. This bug appeared in build 2635 and persists until the last build. In build 2633, everything works fine.

**Expected behavior**
When drive is selected, the cursor should remain highlighted only on that drive. But not simultaneously on two disks.

**Screenshots**
![2020-11-17_121941](https://user-images.githubusercontent.com/58270614/99383273-4c1ccb80-28d6-11eb-8a90-13c15e3545cc.jpg)

![2020-11-17_121958](https://user-images.githubusercontent.com/58270614/99383292-5212ac80-28d6-11eb-9f71-40fc8a11e909.jpg)

![2020-11-17_122014](https://user-images.githubusercontent.com/58270614/99383309-56d76080-28d6-11eb-84d5-dd6fdcfe057a.jpg)

**Desktop (please complete the following information):**
 OS: Windows 10 Pro x64 v2009
86Box v3.00 build 2635
Build type: Optimized Skylake

**Comment by JoshuaMaitland** [comment]
That has happened to me as well.

**Comment by OBattler** [comment]
Closing because this is fixed.
