### ISSUE TITLE
OS/2 Warp 3 won't boot on Jetaway 486 since build #2631

### ISSUE THREAD

**Issue by mph2016** [86Box/86Box#1094]
**Describe the bug**
Upon booting, the jetway 486 will get to the bootloader screen, and then the os/2 splash screen, but before the desktop can appear the screen will go blank and the CPU rate drops to the upper teens and the boot process does not go any further.

**To Reproduce**
1. Install a recent (since #2631) build of 86box
2. Select a working os2/warp install (tested with jetway 486) and click "start"
3. Press "enter" on the boot manager screen
4. Watch the splash screen until the machine (appears to ) switches graphic modes
5. Enjoy your new black screen, notice that the cpu numbers are down from 98%/102% to 16%/20%

**Expected behavior**
On earlier builds (build #2630 and before) this machine goes through the normal boot process. and I get a normal, functional os/2 install. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: #2631 and later
 - Build type: regular

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

86box.cfg is here: https://pastebin.com/GksNNU4U

**Comment by mph2016** [comment]
Tested in builds up to #2645, reverting to #2630 for the time being

**Comment by OBattler** [comment]
Without the actual VM, I can't test this as none of my OS/2 Warp installs are on the Jetway 486.

**Comment by OBattler** [comment]
Ah, you did say it's 3.0. Well, my copy of 3.0 works even when switched to the Jetway 486. So I need your VM as whatever is causing the problem, is not present in mine.

**Comment by OBattler** [comment]
Also, are you sure it's #2631 that broke it? Because none of the commits in #2631 changed anything that would affect OS/2 Warp 3.0 on the Jetway 486.

**Comment by mph2016** [comment]
Hi
This morning (PST) I worked back from 2642 until I got to a version that booted the VM successfully, which for me was 2630. 

Looking at it now, 2642 freezes but 2631 doesn't freeze. I'll try to fetch and test the versions going back from 2642 to 2432 and try to see where it stops working.

I have two VMs; one is a post-install vm (with nothing added) and one has misc stuff added to it.. I have the same result in both so I'm adding a link to the post install VM here:

zip (32mb): https://drive.google.com/file/d/1wOq-Tci89hzQRyJrJ7Dj4i8RwUx67O4G/view?usp=sharing

**Comment by mph2016** [comment]
I tried each of the builds (that there were artifacts for) between 2631 and 2650, and all of the ones from 2632 and 2650 hung on my computer. (windows 10 home edition, i5-7400 cpu, 16gb of ram, nvidia 450 )

2631 consistently works as expected. 

There's a mistake in the copy I archived: I set the b drive to 360kb in the vm but 1.2m in the bios. Changing that to match (1.2 in both) didn't change anything -the VM still hangs for me.

**Comment by mph2016** [comment]
Ok, I hopped into discord and was told to use a cirrus logic card, which fixed the problem and now I'm able to use the current builds with os/2 again.

So the problem's not resolved, but identified and can be worked around. 

I'll keep an eye on what happens with the S3 code (I think some guides I read recommended S3, but I can't remember offhand). 
![OS/2 with Cirrus Logic card](https://user-images.githubusercontent.com/17302103/99478949-cb73c480-2901-11eb-876d-30edd9caad3e.png)
