### ISSUE TITLE
Windows NT 3.5 breaks on boot on a 486

### ISSUE THREAD

**Issue by Winins0** [86Box/86Box#1105]
**Describe the bug**
When you boot Windows NT 3.5, the machine crashes with broken/garbled characters.

**Expected behavior**
Windows NT 3.5 should not crash and boot succesfully.

**Screenshots**
![20201118-120812-489](https://user-images.githubusercontent.com/65453129/99634287-44cdfd00-2a51-11eb-9c7a-ab4e7c08d199.png)

**Desktop (please complete the following information):**
 - OS: Wİndows 10 1909
 - 86Box version: latest from jenkins
 - Build type: Dev

**Additional context**
[86box.cfg.txt](https://github.com/86Box/86Box/files/5565058/86box.cfg.txt) Here is my 86box.cfg file.

**Comment by Winins0** [comment]
For some reason, this does not happen on a Pentium.

**Comment by qeeg** [comment]
Can't reproduce this.

**Comment by Winins0** [comment]
Did you use the config I posted above?

**Comment by qeeg** [comment]
No, but I matched up the settings the exact same in 86Box's settings, save the Postscript printer. Still can't reproduce.

**Comment by Winins0** [comment]
Huh, now it works on a 486. Don't know how and why it happened. Anyway, I am now closing this.
