### ISSUE TITLE
Unable to use hard drive images located on NAS

### ISSUE THREAD

**Issue by solskogen** [86Box/86Box#1116]
Hard disk images located on a nas (\\server)  are not saved

**To Reproduce**
1. Add hard disk image located on NAS. Disk image looks like it was added successfully.
2. Press OK
3. Configure VM and go to Hard Disks. The list is now empty.

**Expected behavior**
That the list is not empty :-)

**Environment (please complete the following information):**
 - Host OS: WIndows 10 version 2004
 - 86Box-Optimized-Zen2-32-b83a32cc
 - 86Box Manager Version 1.7.2

CDROM images does indeed work.

**Comment by qeeg** [comment]
I haven't had issues with using HDD images on network drives in 86Box for a long time now.

**Comment by solskogen** [comment]
This is almost first time I'm using 86Box, so I wouldn't know.

**Comment by daviunic** [comment]
@qeeg there's a difference between using a UNC path (e.g. \\\\server, which is what he appears to be using), and mapping a shared folder as a network drive (e.g. Z:\\). The latter looks much more transparent (as a regular drive), while the former could easily trip programs that don't know what a UNC path is.

@solskogen have you tried using the later option, maping your shared folder as a network drive in Windows and using disk image paths that point to that?

**Comment by solskogen** [comment]
Same thing happens with both UNC and mapped drive.

**Comment by daviunic** [comment]
I tried both UNC and network drive paths in latest regular build (2681) and both paths persisted. But I see you're using an optimized build 2674, so please test this with latest regular and optimized build.

**Comment by daviunic** [comment]
I'd also be interested in the following:
* do you run 86Box as an administrator, by any chance?
* the path where your config file that displays this problem is located
* any other information about your particular setup that might be relevant (NAS type, file system, permissions for the target folder, etc.)

**Comment by solskogen** [comment]
With the regular build it works! With both UNC and mapped drives. 
Aaand, the latest optimized zen 2 also seem to work.

86Box was not run as administrator. 
D:\86Box\VM\fjas is where the config file is. D:\86Box is where 86Box is installed.

**Comment by daviunic** [comment]
I guess we can chuck it down as another optimization bug then.

**Comment by solskogen** [comment]
Agreed. Thanks for your interest!
