### ISSUE TITLE
Bus type missing in HD controller selection list

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1119]
**Describe the bug**
Bus type missing in HD controller selection list for PS/2 AT XTIDE (1.1.5).

**Expected behavior**
The bus type should be displayed, as in other controllers.

**Screenshots**
![1-1](https://user-images.githubusercontent.com/58270614/99901840-4b16e000-2cc2-11eb-9d96-9c87eeb9ac38.png)

**Desktop (please complete the following information):**
OS: Windows 10 Pro x64 v2009
86Box v3.00 build 2681
Build type: Optimized Skylake

**Comment by maximus105** [comment]
Also in the names of the controllers, the types of controllers MFM/RLL, XTA, ESDI, IDE, ATAPI, SCSI disappeared. Previously, they were displayed.

**Screenshots**
![Безымянный1](https://user-images.githubusercontent.com/58270614/99993370-3e78b180-2dc0-11eb-9764-439a9b6d3af7.png)

**Comment by Winins0** [comment]
The first one is fixed, the second one isn't really needed.

**Comment by maximus105** [comment]
> The first one is fixed, the second one isn't really needed.

This is required as it is important information about the controller type.

**Comment by Winins0** [comment]
The controller type is literally listed on the controller name... Not all of them but still.

**Comment by maximus105** [comment]
This is important information in square brackets to indicate the type of controller. In any case, this bug is present and needs to be fixed.
