### ISSUE TITLE
The WD 1003 hard disk controller is wrongly defined  as MFM/RLL

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1120]
**Describe the bug**

According the data [here](http://www.minuszerodegrees.net/manuals/Western%20Digital/wdcontr.txt), The WD 1003 controller can be MFM or RLL but not both at the same time. In addition to that is the only controller supporting to different standards.

**Expected behavior**
May be two differents WD 1003 controllers should be emulated. One for MFM and other for RLL hard disks.

**Screenshots**
![Hard Disk Contoller](https://user-images.githubusercontent.com/31600563/99908227-2d487b80-2cc0-11eb-885b-18de6622e782.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - 86Box version: Latest commit
 - Build type: Regular

**Comment by OBattler** [comment]
The difference is in the number of sectors, but unlike the XT controllers, this one does not require a BIOS of its own, and machine BIOS'es usually allow you to specify the number of sector. So the implementation would be 100% identical for both.

**Comment by qeeg** [comment]
Can this be closed?

**Comment by OBattler** [comment]
Yes, it can be.
