### ISSUE TITLE
HiDPI and settings dialog

### ISSUE THREAD

**Issue by doomgod** [86Box/86Box#1121]
**Describe the bug**
Rendering of the settings dialog is broken since build 2666.

**To Reproduce**
1. Set display scale to 125% or higher in Windows
2. Launch a VM settings dialog
3. The text doesn't fit the box

**Expected behavior**
![86box1](https://user-images.githubusercontent.com/1215088/100107418-a8ee2800-2e7a-11eb-8675-6f0ad6da8a77.png)

**Screenshots**
![86box2](https://user-images.githubusercontent.com/1215088/100107440-b0adcc80-2e7a-11eb-9681-119c2e96274f.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1 x64
 - 86Box version: v3.00 build 2666 or higher
 - Build type: optimized

**Additional context**
4K, 216 dpi (225%)

**Comment by OBattler** [comment]
Well, here is where Windows' math ceases making sense. Base DPI is supposedly 96 dpi, so 216 is indeed 225% of that... but measuring the pixels in the window, the new column size would have to be only 216% of the old one, which indicates that, if you're truly using 216 dpi, then the base dpi is not 96, but 100. I need to investigate this further.

**Comment by daviunic** [comment]
This has been fixed.

**Comment by doomgod** [comment]
![af76c4d08165ee69d97b797cc85df9f3](https://user-images.githubusercontent.com/1215088/152704588-7d3988c3-2dcd-4d5b-bcf1-76d346a4f5dd.png)
Now wrong elements alignment. I can't click on the comboboxes.
