### ISSUE TITLE
Internal HD controller not detected in several 386 systems

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1125]
**Describe the bug**
I tested a 100 mb hard disk with a geometry C/H/S 755/16/17. The hard disk icon does not appears when the internal hard disk option is selected. Seems to work with MR 386 BIOS, but not the others 386 SX/DX including SiS 310 or KMX-C-02 or intel 82335, etc.

**To Reproduce**
The internal controller is inside the options. But it has same as effect as selecting 'none'

**Screenshots**
![Hard disk controler not detected](https://user-images.githubusercontent.com/31600563/100293982-35284a00-2f64-11eb-8a87-13c1da713b6d.png)

**Desktop (please complete the following information):**
 - OS: Win 10 ver 2004
 - 86Box version: Latest commit
 - Build type: Regular

**Comment by daviunic** [comment]
This machine does not have an internal hard disk controller. It still showed up as an option until recently due to a bug that's now fixed (build 2686/commit 01b413110abc263678d5e36c5788d2cf267b1072), so please update to the latest build or select an appropriate controller from the list.
