### ISSUE TITLE
Windows 95 post-setup phase not working

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#1126]
At the https://youtu.be/PgMKUezEEqk?t=579 mark, it boots the cd, so I exit the setup, typed c:\windows\win, and every time I type so,  it gives me a BSOD saying: [VFAT Device Initialization Failed] A device or resource required by VFAT is not present or is unavailable. VFAT cannot continue loading. System halted. What did I do wrong?
![20201126-075300-390](https://user-images.githubusercontent.com/71288109/100322664-99620280-2f92-11eb-8f7b-e2289abbb7c6.png)

**Comment by qeeg** [comment]
You're supposed to change the boot order in the BIOS to HDD first before CD-ROM so you can do the setup from the HDD properly.

**Comment by jadasse** [comment]
Thanks, I'll try it out

**Comment by jadasse** [comment]
I don't see an option for HDD then cd rom, so I put in HDD only, and it worked! Thanks :)
