### ISSUE TITLE
Windows 3.0 does not start in enhanced mode

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1128]
**Describe the bug**
I tested the OPTI 291 chipset with a 386 SX/20. After typing "Win" at DOS prompt Windows 3.0 reboots automatically the system. Windows works right in standard mode typing "Win /S"

**To Reproduce**
Just type "Win" at DOS prompt and Windows will try the 386 enhanced mode and will reboot the machine

Here is the Hard Disk Image
[386 SX.zip](https://github.com/86Box/86Box/files/5605356/386.SX.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: Latest
 - Build type:  Regular

**Additional context**
I found similar bugs with 386 machines and Win 3.1 in PCem. (It locks up after exiting Win 3.1)

**Comment by ppgrainbow** [comment]
Do you have any idea which 86Box build is causing Windows 3.0 to not start in 386 Enhanced Mode?

**Comment by OBattler** [comment]
Fenix770> Could you please upload the 86box.cfg file and the NVR?
