### ISSUE TITLE
OpenGL render does not work in full screen mode

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1129]
**Describe the bug**
OpenGL render in full screen mode 4:3 (possibly in other aspects too) shows a white screen, while switching to windowed mode shows a black screen. And when switching back to the Hardware render, the image does not appear. It's the same in the regular build.

**Desktop (please complete the following information):**
OS: Windows 10 Pro x64 v2009
86Box v3.00 build 2689
Build type: Optimized Skylake

**Comment by maximus105** [comment]
In build 2690, when switching back from fullscreen to windowed mode, the image is corrupted (it is cropped and looks like part of the fullscreen image).

**Comment by OBattler** [comment]
This is probably cause by the high DPI mode or something, because I don't have this on my end.

**Comment by dhrdlicka** [comment]
OP appears to be using 100% scaling though. Look at the taskbar.

**Comment by OBattler** [comment]
Then I have no idea. I just tried it on my end, and I can't reproduce it at all, at least with my old compile. Let me try Jenkins #2690.

**Comment by maximus105** [comment]
Tested on regular build 2693. OpenGL renderer is already working (switching from full screen to windowed mode). But the bug with cropped image after switching from full screen to windowed mode is still present. This bug is present in all renders: SDL, Hardware, OpenGL.

**Comment by OBattler** [comment]
I can't reproduce it at all.

**Comment by maximus105** [comment]
Checked on regular build 2697. Bug with image cropping after switching from fullscreen to windowed mode is present if the "resizeable window" checkbox is checked. Here is my config file:
[86box.zip](https://github.com/86Box/86Box/files/5621094/86box.zip)

**Comment by maximus105** [comment]
I checked on regular build 2699. The bug with cropping the image after switching from full screen to windowed mode has already been fixed, but the window size is reset to the default value. I always have "window_coordinates = 1600, 1200" in 86Box.cfg and the "resizeable window" checkbox checked. But when I switch from fullscreen to windowed mode, the "window_coordinates =" parameters are permanently reset to their default. And I have to re-set them to "window_coordinates = 1600, 1200" on each machine. Can this be fixed? And make sure that these window size parameters are saved after switching from full-screen mode to windowed mode (as it was in build 2684).

**Comment by maximus105** [comment]
And also check the following: in build 2699, if you switch from full screen to windowed mode several times, a black screen will appear and the machine will freeze. It looks like this is a bug that was not in build 2684.

**Comment by maximus105** [comment]
After closing this issue, did you see that I left a message saying that the bug was not fully fixed? Or do I need to post a new issue about an unpatched bug?

**Comment by Winins0** [comment]
Post a new issue.
