### ISSUE TITLE
Most SCAT machines hang on soft reboot (CTRL+ALT+DEL)

### ISSUE THREAD

**Issue by daviunic** [86Box/86Box#1130]
**Describe the bug**
Since build 2514, which changed the AT keyboard code, most SCAT machines (except the Samsungs) fail to soft reboot when CTRL+ALT+DEL is pressed. They hang in various ways:
* Award 286 clone hangs on a blinking cursor after the screen is cleared. 
* GW-286CT GEAR beeps, clears the screen and prints "014"
* Goldstar GDC-212M clears the screen and then hangs while the window is being resized
* Hyundai Super-286TR does the same as the Award 286

**To Reproduce**
1. Select any of the affected machines in the Settings and save
2. Wait for the machine to start, the send the CTRL+ALT+DEL keystroke to attempt a soft reboot
3. Observe the hang

**Expected behavior**
Machine soft reboots normally, like it did in build 2513 and older.

**Desktop (please complete the following information):**
 - OS: Windows 10 version 20H2
 - 86Box version: 2.10/3.0 build 2514 or later
 - Build type: regular

**Comment by OBattler** [comment]
This is now fixed.
