### ISSUE TITLE
Windows 95 printing

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#1131]
Is it possible to print with Windows 95 in 86box? If so, how do I do it?

**Comment by TC1995** [comment]
It is possible, just use Ghostscript (in the 86box settings), in the guest (Windows 95), pick a Postscript capable printer and you're on the way :).

**Comment by jadasse** [comment]
![psp](https://user-images.githubusercontent.com/71288109/100523301-7cd5ee00-317d-11eb-9cee-31ef22fd85e6.png)

You mean like this?

**Comment by TC1995** [comment]
yes, that.

**Comment by jadasse** [comment]
![20201128-183325-435](https://user-images.githubusercontent.com/71288109/100523410-55335580-317e-11eb-8727-d202f8aa8e27.png)

I'm at this screen, what now?

**Comment by TC1995** [comment]
Install the driver, print a test page (when prompted so), and check the printer folder in your host (outside the emulator), you'll see a PDF which contains the print test.

**Comment by jadasse** [comment]
[20201128-183609-713.pdf](https://github.com/86Box/86Box/files/5611060/20201128-183609-713.pdf)

Thanks! It works; I assume 86box emulates the Apple LaserWriter in Windows 9x by default.

**Comment by dhrdlicka** [comment]
It doesn't emulate a specific printer, the implementation on the 86Box is a generic LPT driver that writes the data to a text file and then calls Ghostscript to convert it to PDF.

**Comment by jadasse** [comment]
oh ok thx
