### ISSUE TITLE
386 SCAMPsx machine posts, but reboots several times until it freezes

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1133]
**Describe the bug**
The SCAMP 386sx machine starts, but an error says it will clear the CMOS and restarts several times and stop responding.
There is no time to go to the setup BIOS.

**To Reproduce**
1. Simply start the machine
2. The bug shows itself

**Expected behavior**
It should at least give an option to enter in the setup options at boot time.

**Screenshots**
![SCAMPsx bug](https://user-images.githubusercontent.com/31600563/100526413-7d837a00-31a7-11eb-96dc-10a7dd952a23.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: Latest commit
 - Build type: Regular

**Comment by tiseno100** [comment]
That's a flaw caused by the bad SCAMP implementation. It's on plan to get fixed.

**Comment by OBattler** [comment]
This was actually the wrong BIOS altogether - this BIOS is for the SL386SX-16 which uses the NEAT chipset, the SL386SX-25 with the SCAMP chipset uses Award BIOS v4.20. This is now sorted out (and the SCAMP chipset fixed as well).
