### ISSUE TITLE
OpenBSD 6.8

### ISSUE THREAD

**Issue by qeeg** [86Box/86Box#1135]
**Describe the bug**
OpenBSD 6.8 won't boot, possibly due to inaccuracies in our bus-master DMA IDE emulation.

**To Reproduce**
1. Boot off the CD
2. Type `boot /6.8/i386/bsd` at the prompt.
3. Kernel panic.

**Expected behavior**
A successful boot.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - 86Box version: 3.0 build 2692
 - Build type: Regular

**Additional context**
This is the install CD I used. https://cdn.openbsd.org/pub/OpenBSD/6.8/i386/install68.iso

**Comment by qeeg** [comment]
Here's the VM.

[openbsd.zip](https://github.com/86Box/86Box/files/5613347/openbsd.zip)

**Comment by OBattler** [comment]
A screenshot of the Kernel panic?

**Comment by natee22** [comment]
Reproduction on build 2765
![image](https://user-images.githubusercontent.com/5056538/103487254-fb9ff580-4dd1-11eb-99fd-d3d785fe6768.png)

**Comment by qeeg** [comment]
A slightly different error followed very quickly by a triple fault occurs when just hitting Enter at the boot prompt instead of typing anything.

**Comment by OBattler** [comment]
I'm closing this as out of scope for 86Box - it's way too modern, so it might be require a much newer IDE drive than what is emulated.
