### ISSUE TITLE
The window size is reset to default

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1142]
**Describe the bug**
After switching from full screen mode to windowed window size, 86Box resets to default values ​​(it does not retain the previously configured window sizes, possibly also window coordinates). I always have the window sizes "window_coordinates = 1600, 1200" set in 86Box.cfg and the "resizable window" checkbox is checked. But when I switch from full screen to windowed mode, the "window_coordinates" parameters are always reset to their defaults. And I need to reinstall them again to "window_coordinates = 1600, 1200" on each machine. In build 2684, the window size settings persisted after switching from full screen to windowed mode. Also, if you switch from full screen to windowed mode and back several times, a black screen will appear and the machine will freeze. This is a bug that was not in build 2684.

**To Reproduce**
1. Start any created machine in 86Box with a preset window size (not default)
2. Switch to full screen mode and back
3. See error (window size will be reset to default)

**Expected behavior**
The window size should be maintained (as configured early) after switching from full screen mode to windowed mode

**Desktop (please complete the following information):**
OS: Windows 10 Pro x64 v2009
86Box v3.00 build 2702
Build type: regular

**Additional context**
Here is my config file with customized window size:
[86box.zip](https://github.com/86Box/86Box/files/5637035/86box.zip)

**Comment by maximus105** [comment]
Why are you closing the issue if it is not fully fixed? Do you actually test every possible behavior of 86Box after making corrections for a specific issue? After switching the window to full-screen mode and back, the window not only does not retain its previous dimensions and coordinates, but also constantly moves downward along the diagonal, while the window's dimensions increase. This is a bug that was not in build 2684. So the issue remains open!

**Comment by dgurney** [comment]
> Why are you closing the issue if it is not fully fixed? Do you actually test every possible behavior of 86Box after making corrections for a specific issue? After switching the window to full-screen mode and back, the window not only does not retain its previous dimensions and coordinates, but also constantly moves downward along the diagonal, while the window's dimensions increase. This is a bug that was not in build 2684. Also, if you switch from full screen to windowed mode and back several times, a black screen will appear and the machine will freeze. So the issue remains open!

I understand it is frustrating when a fix doesn't work right, but mind your tone. Whether you intended it or not, this message makes you sound incredibly entitled. Nobody here intentionally breaks anything, but it still happens to the best of us sometimes.
 
Next time, just reopen the issue and say the fix didn't work without all the dramatics.

**Comment by OBattler** [comment]
> After switching the window to full-screen mode and back, the window not only does not retain its previous dimensions and coordinates,
I tested this, and it definitely retains its deimensions. Are you sure you got the correct build of 86Box?

> Also, if you switch from full screen to windowed mode and back several times, a black screen will appear and the machine will freeze.
The black screen issue is known and is completely unrelated to this issue. The renderer still has bugs, I have no idea how to fix this one. Consider not switching back and forth too much.

**Comment by OBattler** [comment]
See if the position and size are correct after returning from full screen in the latest build.

**Comment by maximus105** [comment]
I checked build 2751. After switching the window to full screen mode and back, the window does not retain its previous dimensions and coordinates. Run build 2684, in which, after switching the window to full screen mode and back, the window retains its size and remains in the same place where it was before. Look at my 86Box.cfg file added above and use it in build 2684: the window_coordinates = 1600, 1200, 508, 74 parameter remains unchanged after switching the window to full screen mode and back (the window retains dimensions and coordinates after switching to full screen mode and back, then there is no bug). Then run the latest build 2751 with my 86Box.cfg file and switch the window from full screen mode and back: window_coordinates = 1616, 1282, 508, 74 has already changed. That is, this is a bug and the window does not keep the same dimensions and coordinates.

**Comment by OBattler** [comment]
2751 doesn't have my latest fix, 2752 does but is not yet compiled.

**Comment by OBattler** [comment]
OK, 2752 is compiled now. See if it fixes the problem correctly.

**Comment by maximus105** [comment]
I checked build 2752. Yes. The problem has been fixed. Thanks!
