### ISSUE TITLE
Port Samsung SPC-6033P and SPC-6000A machines to 86box

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1148]
**Is your feature request related to a problem? Please describe.**

No. I write to ask if these two machines can be ported from PCem. The SPC-6033P, is a 386 SX machine is based on SCAMP chipset (like The Commodore SL386sx), I know the emulation of this chipset is not complete, but when finished this one may be added. The SPC-6000A is a 386 DX based on the CS8230 chipset like the ECS 386/32 which is fully emulated.

**Other machine (Emulation not complete)**

Also, emulation of Amstrad 5086 was added.  I don't know if worth to add this one at the moment because of the not emulated parts.

**Interesting Points:** This machine has 8086/8 CPU, but has 'AT-like' C&T BIOS (similar to the GEAR-286) and supports High Density floppy drives natively. 

**Drawbacks: 
Hardware not emulated:**

a. It has a 82C100 chipset, which supports up to 2.560KB of total RAM 640KB soldered on the board and the rest can be added and used as LIM EMS RAM.
b. An internal C&T VGA chipset, unlike the older Amstrad 2086/3086, which has and Paradise VGA chip.
c. An internal XTA-IDE controller (I don't know if it has a proprietary design like in the IBM PS/1 2011)

**Comment by OBattler** [comment]
I have in my plans to port the two Samsungs (will be adding them when I get around to fixing the SCAMP chipset). As for the 5086, I have decided not to add it to v3.0 because it's not complete yet. Also, what C&T VGA chipset does it have?

**Comment by OBattler** [comment]
This is now done.
