### ISSUE TITLE
Amstrad PC3086 memory amount bug

### ISSUE THREAD

**Issue by ToMi8088** [86Box/86Box#1157]
When starting the Amstrad PC3086, the memory amount is set 0MB. When setting it to 1MB, it sets it to 0MB again.

**Screenshots**
![Výstřižek](https://user-images.githubusercontent.com/64270858/101280125-8687d300-37c7-11eb-954d-4a5c7c5a82dc.PNG)

**Desktop:**
 - OS: [Windows 10 Pro x64]
 - 86Box version: [v3.0, compiled through VS2019 from the latest GitHub source code]

**Comment by daviunic** [comment]
I can confirm this happens in official build 2710 too.

**Comment by ToMi8088** [comment]
It seems this bug also happens when running the Amstrad PC1640 and PC2086.
