### ISSUE TITLE
Strange bugs in Olivetti machines

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1160]
**Describe the bug**
I found three bugs in the three different Olivetti machines.

1.The M19 8088 model does not boot.

2. The M24 machine works, but I cannot use the standard serial mouse even if I specify it in the input options. I tested it with Windows 1.03. Works with the M240.

3. The M240 machine works right, but detect the hard disk drive C as E. It occurs on Olivetti M240 with Olivetti MS-DOS 3.20, but it detects correctly as C drive on the M24.
I tried to add Lastdrive=C  line inside CONFIG.SYS without avail.

Geoworks Detects the B,C, and D drives as 3.5 floppies even but they do not exist, as the only drives configured are a 5.25 360 KB (as A drive) and a 20mb hard disk (in this case E drive, but it should be C).

**To Reproduce**

1.Mount the 20MB hard disk C/H/S 615/4/17 with IBM PC (Xebec) or DTC-5150X controller
2. Execute the Win command in C:\Windows directory

On M24:
3. Windows 1.03 is configured with the Olivetti CGA 640x400 2 color mode and a standard serial mouse but, it is not detected on this machine.

On M240:
3.Windows 1.03 works but, detects drive B,C and D and they should not exist.
4. Start GeoWorks. From C:\geoworks directory, type PCGEOS,
5. Select professional mode
6. Drive letters B,C and D appears as 3.5 floppy drives.

**Screenshots**
![BUG 001](https://user-images.githubusercontent.com/31600563/101413753-9553b000-38c3-11eb-93aa-80525ad23488.png)

The M240 boot with E drive
![BUG 002](https://user-images.githubusercontent.com/31600563/101413793-a7cde980-38c3-11eb-9fc0-494b00d8b3d3.png)

The M240 running GwoWorks
![BUG 003](https://user-images.githubusercontent.com/31600563/101413842-c338f480-38c3-11eb-98bf-7cf2beaebd6b.png)

Here is the Hard Disk image:
[Olivetti 615-4-17.zip](https://github.com/86Box/86Box/files/5655647/Olivetti.615-4-17.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version:  7e96d5e8 
 - Build type: Regular

**Additional context**
The M24 mouse setting (Serial mouse) works right in PCem. The other machines were not implemented.

**Comment by Fenix770** [comment]
PD: I also tried to use the DTC-5150X controller with a different BIOS address, but always detects it at C800 region. May be it's a limitation of the Olivetti BIOS itself.

**Comment by TC1995** [comment]
I believe the standard serial mouse is not supported on the M24 on real hardware as it uses its own mouse handling.

**Comment by ToMi8088** [comment]
Well, the M19 one works fine on my side.

**Comment by Fenix770** [comment]
I recently discovered that the M19 model works, but only with a frequency of 7.16 Mhz. Any other configuration speed throws the "Fail:82" error. According the description given by Ollivetti (added by EngiNerd89) this model should support 4.77 and 8 Mhz frequencies.
The pull rweuest with  documentation added by the author:
[https://github.com/86Box/86Box/pull/1155](url)
The description of the M19 machine:
[https://www.sba.unipi.it/sites/default/files/10.pdf]

**Comment by EngiNerd89** [comment]
I did some tests and obtained the following results:
- Olivetti M24 mouse issues: I tested the mouse driver with a real Olivetti M21 (portable version of the M24) and a Genius serial mouse (both with Microsoft and Mouse Systems emulation), and I experienced the same issues. Thus, it appears that serial mice are not supported on this machine. 
- Olivetti M240 incorrect drive letters: there was a bug in the dip-switch settings handling code. I fixed it, and it will be available in my next pull request.
- Olivetti M19 CPU speed: as found out by Fenix770, setting CPU speed beyond 7.16 MHz always causes a timer error. Instead, when setting CPU speed at 4.77 MHz, the timer error occurs only sporadically or at cold-boot. When it happens, a hard-reset is sufficient for the emulated machine to start working again. That said, I found out that other XT-class machines have sporadic timer-related issues, so this issues appears to be related to the way the CPU clock is handled in 86box. By now, I have limited the maximum CPU speed to 7.16 MHz. As for M240, this fix will be available in my next pull request.

**Comment by Fenix770** [comment]
Hello!
The drive letter bug seems to been fixed,  however I found random lockups, when ussing Geoworks. I found this same problem with Philiphs XT machines.

**Comment by ruudi2021** [comment]
M24 has a Z8530 based serial interface (common in CP/M Z80 computers) despite the i8250 Standard in "normal" PCs. So you have to use either a matching driver for the mouse (as mouse-devices "abuse" the serial communication a bit), or insert a standard serial-interface card with 8250 or later 16450/16550 devices as COM2: or upwards.

**Comment by Fenix770** [comment]
I changed the port to COM2 as you suggested and there is no more lock ups. Thanks!
Maybe that it´s the real behavior of this XT machine and also the emulated machine, but I didn't know that.

**Comment by OBattler** [comment]
I think this can be closed now.
