### ISSUE TITLE
Unable To Boot IBM OS/2 Warp 4.52 Installer

### ISSUE THREAD

**Issue by mforan26** [86Box/86Box#1162]
**Describe the bug**
I'm unable to launch the IBM OS/2 Warp 4.52 Installer. I get the same result no matter what machine is selected.

**To Reproduce**
1. Create any machine configuration that meets OS/2's system requirements
2. Insert the 1st cd image. Should be labeled something like "ibm_warpclient_cp2_v4_52_boot.iso"
3. Wait until the cd loads.
4. Insert the second disc image. It should have "client" in the file name.
5. No keyboard input is accepted at this point

**Expected behavior**
The installer launches and allows you to prepare the disc for partitioning

**Screenshots**
![freeze](https://user-images.githubusercontent.com/20382449/101533339-44e65c00-3970-11eb-9ca8-ecaf1ccc7334.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home [Build 19042.630]
 - 86Box version: 3.0 Build 2689
 - Build type: Optimized

**Comment by OBattler** [comment]
Is this bug still present?

**Comment by OBattler** [comment]
I just realized that people have successfully installed OS/2 Warp 4.52 on 86Box recently, so this is fixed.
