### ISSUE TITLE
Screenshots working?

### ISSUE THREAD

**Issue by bengarrett** [86Box/86Box#1163]
**Describe the bug**
When I search the docs for _screenshot_.

> Take screenshot: take a screenshot of the emulated display. Screenshots are saved as PNG images in the screenshots directory.
https://86box.readthedocs.io/en/latest/usage/menubar.html?highlight=screenshot#tools

As there is no `screenshots` directory, I assume a `screenshots` directory goes into the root of `86Box.exe`?

![Capture](https://user-images.githubusercontent.com/513842/101541316-6b9aa600-39f5-11eb-83b0-d70461153ef8.PNG)

**To Reproduce**

When I select the **Tools** > **Take a screenshot** menu item, nothing happens. The same happens when tapping <kbd>Ctrl F11</kbd>.

**Desktop (please complete the following information):**
 - OS: Windows 10, 2004
 - 86Box version: v3 7e96d5e8
 - Build type: Optimized-Skylake

**Comment by daviunic** [comment]
The screenshots directory is created in the config path you provided (either manually or via the Manager). If you run 86Box.exe without the -P argument, the config folder is where 86Box.exe is.

**Comment by bengarrett** [comment]
Thanks, now I see, each virtual machine config has its own screenshot sub-directory. I was using the Manager exclusively so there has never been a need to look at the config subdirectories.

As the docs were not clear on that, I'll do a small PR.
