### ISSUE TITLE
Compaq portable no video display

### ISSUE THREAD

**Issue by Altheos** [86Box/86Box#1164]
**Describe the bug**
8088 Compaq portable internal video adapter doesn't display anything (using any SDL renderer).
Nonetheless, machine seems to boot 

**To Reproduce**
1. Configure 8088 - Compaq Portable
2. Select any CPU speed
3. Select "Internal video" controller or any other (compaq CGA crashes emulator)

**Expected behavior**
Machine should display screen

**Screenshots**
![Capture](https://user-images.githubusercontent.com/29195397/101632176-cea43100-3a25-11eb-9f52-e3b242051bb8.JPG)

**Desktop:**
 - OS: Windows 7
 - 86Box version: v3.00 build 2712

 - Build type: DEV

**Additional context**
I also tested different DEV builds (1860 / 1830 / 1375 / 1073) and none of them display anything. It seems that compaq portable never worked.

**Comment by Winins0** [comment]
Can confirm the internal display not working, but the Compaq CGA does not crash the emulator on my end.
