### ISSUE TITLE
Generic Text Printer doesn't work correctly

### ISSUE THREAD

**Issue by seal331** [86Box/86Box#1166]
**Describe the bug**
Generic Text Printer doesn't work correctly, prints only a part of the text sent

**To Reproduce**
1. Install MS-DOS 3.30 and Windows/286 2.11 on an AMI WinBIOS 486
2. Install the Generic/Text Only printer driver
3. Open up Write and type the following:
hey

i am a seal

i like to chonk
4. Print the file
5. Take a look at the printer output

**Expected behavior**
All the text will be printed.

**Actual behavior**
The last line isn't printed.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - 86Box version: v3.0 build 2689
 - Build type: Regular

**Comment by OBattler** [comment]
See if the latest build fixes it.

**Comment by OBattler** [comment]
Going to close it due to no feedback.
