### ISSUE TITLE
Windows 3.0 Multimedia do not start on 386 SX with a SB sound card.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1178]
**Describe the bug**

The Bug happens when I try to start Windows 3.0 Multimedia with a SB sound card. Windows does return to the DOS prompt after typing 'WIN' command. Windows starts normally in Real and Standard modes. Enhanced mode works if the SB sound card is disabled. I'm using the AMA-932J 386SX machine.

(By the way: This bug is similar to another I reported earlier, but this time the enhanced mode does not work only if the SB card is present)

**To Reproduce**

1. Type Win at DOS prompt

**Expected behavior**
This bug did not exist when I installed Windows 3.0 multimedia with older 86box commits. But I don't remember when was the last time I used it.

Here is the hard disk image and the nvr and cfg files:

[Win 30 dos 40 type 35.zip](https://github.com/86Box/86Box/files/5706936/Win.30.dos.40.type.35.zip)

[AMAJ-386-SX NVR and CFG file.zip](https://github.com/86Box/86Box/files/5706942/AMAJ-386-SX.NVR.and.CFG.file.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: commit 86Box-32-a81703a4 (Version 3.0.0.2723)
 - Build type: Regular.

**Additional context**
I also have a question unrelated to this bug: I don't know which model is the OAK integrated video chip on AMA-932J. The OTI-067 driver does not work.

**Comment by ppgrainbow** [comment]
Do you have any idea which build this was tested on and what was the most recent build that worked before the changes were made?

**Comment by OBattler** [comment]
Could you please bisect and find which build broke it?

**Comment by Fenix770** [comment]
I did not find the reason for this issue. However, I created a new disk image And installed all again, and now works flawlessly. 
The old disc image has the same problem even with 86box 2.07 and PCem versions as old as v14, I don not know what caused it.

I'm closing this thread since I think it is not an emulator bug as I first thought.
