### ISSUE TITLE
86Box crashes on hard reset

### ISSUE THREAD

**Issue by Raulonthetest** [86Box/86Box#1179]
**Describe the bug**
When the machine is rebooted through Hard Reset, 86Box will crash.

**To Reproduce**
1. Go to 'Action'.
2. Click on 'Hard Reset'.
3. Select 'Reset' on hard reset confirmation dialog.

**Expected behavior**
The machine should reset as it should.

**Screenshots**
*not applicable*

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909
 - 86Box version: 3.10 build 2725
 - Build type: Regular

**Additional context**
*not applicable*

**Comment by ppgrainbow** [comment]
Uh oh! This doesn't sound too good. :(

Did 86Box crash on hard reset in earlier builds or just on Build 2725?

**Comment by Raulonthetest** [comment]
I didn't test the others. In an earlier build (2624 - 2625?) it didn't happen.

**Comment by dhrdlicka** [comment]
Can you provide more relevant information about the crash, such as what specific build introduced the crash, your configuration and exact reproduction steps?

**Comment by Raulonthetest** [comment]
Every configuration will cause this. 
The crash also happens when 86Box is closed and opened again, hardware is changed...
Well it was my fault, it is not the emulator but the building.
Problem solved.

**Comment by Raulonthetest** [comment]
You are right about the invalid label,
I didn't know how to describe the issue.
