### ISSUE TITLE
I cannot configure a new machine on 86box Manager

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1182]
**Describe the bug**

I discovered the bug today in the commit 76d38b26 (ver 3.0.0.2730). It did not happen in commit bf4c6274 (ver 3.0.0.2726)

**To Reproduce**

1. Open 86box manager
2. Create a new Machine, and mark "Configure this virtual machine now"
3. Then this error appears:

**Screenshots**
![Fatal error 001](https://user-images.githubusercontent.com/31600563/102677204-25c1a880-4180-11eb-90e0-46519d80e15a.png)

![Fatal error 002](https://user-images.githubusercontent.com/31600563/102677207-2b1ef300-4180-11eb-990d-f1e67be80eb8.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 2004
 - 86Box version:  76d38b26 (ver 3.0.0.2730)
 - Build type: Regular

**Comment by qeeg** [comment]
Can you retest this please? This should be fixed now.

**Comment by Fenix770** [comment]
This bug was solved in newer commits. I'm closing this thread.

**Comment by daviunic** [comment]
Should be pointed out that this wasn't a Manager issue either.
