### ISSUE TITLE
Reading Failures of IMD floppy image files

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1188]
**Describe the bug**
86box cannot read properly the IMD disk format. At first I suspected the disk image was bad. Later I converted the IMD file format to IMG with Imd118 utility and the resulting IMG files is completely readable.

The machine I use is the Eagle Spirit XT with it's OEM MS-DOS 2.11.

**To Reproduce**
1.  Simply load the DOS 2.11 disk in an IMD format on drive A (360kb floppy)
2.  An error saying "Bad or missing interpreter" appears.
3. If you try to load a program file, at DOS prompt, on the disk a reading error appears.

To convert the ima file:

1.A copied the imd file to hard disk on another machine
2. With the IMDU program, included inside the IMD118 software package, converted the file to IMG
(For example, type: Type IMDU EAGLE.IMD EAGLE.IMG /B)
3. Extracted the IMG file with Winimage. 

Here I add the software to test:

The image file in IMD format,  

[Eagle_Computer_DOS20.zip](https://github.com/86Box/86Box/files/5727121/Eagle_Computer_DOS20.zip)
the IMD118 package
[imd118.zip](https://github.com/86Box/86Box/files/5727122/imd118.zip)
and the resulting IMG file.
[EAGLE.zip](https://github.com/86Box/86Box/files/5727123/EAGLE.zip)

**Screenshots**
Errors: 
![Eagle DOS 2 11 IMD](https://user-images.githubusercontent.com/31600563/102834749-b2b07000-43d3-11eb-8cc1-1789762ceb2b.png)

![Image 3](https://user-images.githubusercontent.com/31600563/102834758-b80dba80-43d3-11eb-8f0b-aa82ab4b9648.png)

I managed to create a 10mb partition and install DOS on it  with the converted file:
![Image 2](https://user-images.githubusercontent.com/31600563/102834831-da073d00-43d3-11eb-871b-76cc68b6a8d5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: Build 3.0.0.2737
 - Build type: Regular

**Comment by OBattler** [comment]
Sounds like 86Box is not correctly recognizing the geometry of the IMD file.
