### ISSUE TITLE
CD Audio is unaffected by in-app volume slider

### ISSUE THREAD

**Issue by NicknineTheEagle** [86Box/86Box#1191]
**Describe the bug**
DOS version of Quake has a CD Audio volume slider in options but it doesn't work under 86Box.

**To Reproduce**
1. Start MS-DOS 6.22 with Sound Blaster 16, as well as OAKCDROM.SYS driver and MSCDEX loaded.
2. Start Quake with Quake CD inserted.
3. Go to the options menu and play with CD Audio volume slider. It has no effect on music volume.

**Expected behavior**
CD Audio volume changes.

**Additional context**
SB16 mixer app does seem to work properly.

**Comment by OBattler** [comment]
What build of 86Box does this occur on?

**Comment by NicknineTheEagle** [comment]
Build 2742.

**Comment by OBattler** [comment]
Is Quake's CD audio slider known to work on a real Sound Blaster 16?

**Comment by NicknineTheEagle** [comment]
I cannot verify but it does work on SB Live which emulates SB 16 in software under DOS.

**Comment by OBattler** [comment]
Fixed this now, it wasn't the Sound Blaster 16's found but an ATAPI/SCSI CD-ROM command being partially broken, which was breaking drive-side CD Audio volume (and channel select) control.
