### ISSUE TITLE
Erratic window scaling

### ISSUE THREAD

**Issue by DDXofficial** [86Box/86Box#1196]
**[Windows 10 Enterprise x64 (20H2) / 86Box-Dev, build 2750]**

I noticed a strange issue while attempting to resize a window by changing its scale factor: it didn't respond to any changes. Sometimes, changing the scale to 2x would make the window bigger, but half the time changing it back to something else to such as 1.5x or 1x did not change anything.

Linked [here](https://mega.nz/file/z5MATZyY#S2c74DSqnQ81wLY0zJs9JYI9YMsoXdG_VKqn365XYIQ) is a Windows 98 SE machine on which I particularly experienced this issue. Basic specifications are listed below:
- ASUS P/I-P65UP5 (C-P55T2D)
- Intel Pentium MMX @ 166 MHz
- 64 MB RAM
- Phoenix S3 Trio64V+

Also worth noting here is that I am currently using the SDL (Hardware) renderer.

I will also take the liberty to link [another machine](https://mega.nz/file/H1tBEAiJ#yh51nguNpi61R28tVLrnVl6elC8r1M3Ha_Zb86T0w0E) where the scaling issues were somehow less frequent.
- Award 386DX clone
- Intel i386DX @ 16 MHz
- 4 MB RAM
- Tseng ET4000AX

In build 2700 (the earliest build I was able to test while bisecting), the 386DX machine was able to be resized without any issues, unlike the ASUS 430HX machine, which may lead to a few conclusions: this is either a machine- or GPU-specific bug and/or this issue may have arisen sometime between late 25xx and 27xx builds.

**Comment by OBattler** [comment]
I'm quite sure this has long been fixed now.
