### ISSUE TITLE
Openstep 4.2 Display Issues

### ISSUE THREAD

**Issue by mforan26** [86Box/86Box#1204]
**Describe the bug**
Openstep installs fine but upon selecting a video driver and rebooting the fonts are messed up and unreadable in places. 

**To Reproduce**
1. Select any video card in 86Box's options
2. Install as normal
3. Select video driver during setup.
4. Reboot machine
5. See messed up fonts

**Expected behavior**
Readable text

**Screenshots**
![font](https://user-images.githubusercontent.com/20382449/103598816-18295400-4ede-11eb-927e-1271fa3aa8da.png)

Desktop
 - OS: Windows 10 Build 19042.685
 - 86Box version: 86Box 3.0 Build 2759
 - Build type: Optimized

**Additional context**
It doesn't seem to matter what graphics card you choose, the problem still persists. Although the text that is messed up seems to change on each boot.

**Comment by TC1995** [comment]
That's an issue with the FPU in the old dynarec.

**Comment by kelp** [comment]
I'm running into this issue also. Using today's build of 86Box with Openstep 4.2.

**Comment by kelp** [comment]
@mforan26 I've had much better results with a recent Dev/Experimental build. Someone correct me if I'm wrong, but *think* that enables the new dynarec from PCem v15, and perhaps resolves the issue @TC1995 was mentioning.

I made a few screenshots to show the difference.

- OS: Windows 10 Build 19042.906

- 86Box version: 86Box 3.0 Build 2869
- Build type: Regular
![NEXTSTEP-4 2-86Box](https://user-images.githubusercontent.com/11240/113213066-7b502b80-922c-11eb-958d-49a41a0815f8.png)

- 86Box version: 86Box 3.0 Build 2869
- Build type: Experimental
![NEXTSTEP-4 2-86Box-Dev](https://user-images.githubusercontent.com/11240/113213122-8efb9200-922c-11eb-81fd-5db2ab8a812f.png)

And for a control comparison:

- VirtualBox 6.1.18 r142142
![NEXTSTEP-4 2-Virtualbox-6 1](https://user-images.githubusercontent.com/11240/113213235-bce0d680-922c-11eb-82d3-cbf828a3ed80.png)

**Comment by OBattler** [comment]
Yes, one of the recompiled instructions on the new recompiler is clearly the one responsible for this and fixes this.
