### ISSUE TITLE
Implement the Compaq Presario 2240 series

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#1207]
**Is your feature request related to a problem? Please describe.**
Not a problem; just a new machine.

**Describe the solution you'd like**
The Compaq Presario 2240 series was a commonplace computer in the late 90s. It featured:

- A Socket 7 motherboard with an Intel 430VX chipset
- An SMC FDC37C932QF Super I/O
- An on-board S3 Trio64V2/DX graphics chipset
- An on-board ESS AudioDrive ES1888F audio chipset (not yet implemented, doesn't necessarily have to be at this time)
- An on-board IDE and floppy controller
- A 256 KB BIOS ROM (latest I can find is called B0184008.ROM, from a Softpaq found on an archive of Compaq's FTP)

I would very much like to see this machine be implemented. Please let me know if there is any additional detail needed for the motherboard.

**Describe alternatives you've considered**
It's very exciting to see the 4500 series; this is what inspired me to request the 2240 series in the first place. For now, if I want my retro Compaq fix, I can easily emulate a 4500 series.

**Additional context**
Datasheet for the ES1888F (optional) is attached. Link to ROM file: https://mega.nz/file/T4An1aYR#8RuNH4AgRaMk-o3ZzzOPr8sliWtw2Xe2Z4AM5O-IIkE
[DSA-151117.pdf](https://github.com/86Box/86Box/files/5768493/DSA-151117.pdf)

**Comment by tiseno100** [comment]
I'm working on another machine at the moment. I'll take this board into consideration though. The 4500 series was added as they had Phoenix BIOSes. Compaq's own BIOS have a weird bug where they reboot by themselves, still has to be figured out.
