### ISSUE TITLE
The keyboard does not respond after loading DOS on KMX-C-02 386SX

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1208]
**Describe the bug**
The keyboard works on the setup BIOS but does not respond after loading DOS at DOS prompt.
This occurs only on this specific machine.
Tested two hard disk images with DOS 4.0 and 5.0 with the same result.

**To Reproduce**
1. Configure the virtual machine
2. Boot the machine
3. At either DOS 4.0 Doshell or DOS prompt the keyboard does not respond.

Here I upload the HD image files:
[386 SX.zip](https://github.com/86Box/86Box/files/5773208/386.SX.zip)
[AWARD 286 DOS 5.zip](https://github.com/86Box/86Box/files/5773214/AWARD.286.DOS.5.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: 3.0.0.2761
 - Build type: Regular 
 - 
**Additional context**
This machine works on PCEM. About two years ago, a patch has made  to fix the keyboard problems of this machine on PCEM.
(Before that patch was problems such as if keys were held)

**Comment by OBattler** [comment]
I know of these keyboard problems, they are being fixed by the rewrite.

**Comment by OBattler** [comment]
Since this is basically solved, I'm going close this.
