### ISSUE TITLE
MR 486 clone doesn't reboot properly with Ctrl-Alt-Del

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#1216]
**Describe the bug**
The MR 486 clone machine will not reboot properly and output beep codes instead when Ctrl-Alt-Delete is pressed.

**To Reproduce**
1. Boot MS-DOS from floppy or HDD
2. Once booted, press Ctrl-Alt-Del
3. Machine will reboot to a blank screen and play POST beeps

**Expected behavior**
The machine should reboot normally.

**Screenshots**
<img width="241" alt="86box_1" src="https://user-images.githubusercontent.com/29031916/104299160-d2811280-54ff-11eb-96e4-a16c514b0bab.PNG">

**Desktop (please complete the following information):**
 - OS: Win10 20H2 19042.685
 - 86Box version: e659fa77ff2018c0bed8bf70365ef7edf1592edd
 - Build type: Custom optimized 32-bit

**Additional context**
None.

**Comment by OBattler** [comment]
This is now fixed.
