### ISSUE TITLE
Save file dialogs don't append any extension to file names without one

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#122]
When the user saves a config or a hard disk image and enter a file name without an extension, 86box should append a default extension that corresponds to the chosen file type. To create a file without an extension, the user would have to choose `All files (*.*)` in the file type listbox. This is the consistent and expected behavior in any Windows program, therefore 86box should follow this guideline as well.

**Comment by OBattler** [comment]
I am going to look at this. I recently found out that Windows does update the FilterIndex field according to the extension filter the user chose from the combo box, so I can at least know what the user has chosen.

**Comment by OBattler** [comment]
This is now done.
