### ISSUE TITLE
Implementation of Texas instrument 486  8Kb cache upgrade CPUs for 386 mainboards

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1226]
Hello!

I found that some Texas Instruments 486 upgrade CPUs for 386 boards. They are similar to Cyrix 486 SLC/DLC but have 8kb, and unlike the IBM 486 SLC/DLC some they have the same socket that 386 SX and DX CPUs.

TI486SXLC -> Similar to Cyrix 486 SLC, has 16-bit bus, but have 8kb of L1 cache instead of 1kb.
TI486SXL->Similar to Cyrix 486 DLC, has 32-bit bus, but have 8kb of L1 cache instead of 1kb.

There are variants with 40 MHz and 50 MHz. Some support two voltages 3.3v and 5v and other 3.3v only.

I think The SXL may have a similar performance to 486 DX, but they lack the FPU. So a 387 FPU must be installed if needed.

Here is the site with the info:
[http://dosdays.co.uk/topics/cpus.php]

I have not found a datasheet yet, but I think they support the same 486 instructions set that the 1kb cache models.

**Comment by nerd73** [comment]
86Box does not emulate cache at this time, so I don't see why this should be added.

**Comment by Fenix770** [comment]
I thought the performance difference may be emulated. Since the Cyrix 486 SLC/DLC CPUs are much faster than their 386 SX/DX counterparts. I don't know if benchkmarks of these CPUs exist, but they should be close to the IBM SLC/DLC, at the same clock frequency.

**Comment by OBattler** [comment]
The performance would basically the same as the emulated Cyrix 486 SLC and DLC CPU's, so I don't really any point for these.
