### ISSUE TITLE
Crashes after exiting fullscreen

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#1227]
When I exit fullscreen, the VM crashes every time/mostly; what's going on?

**Comment by daviunic** [comment]
I'm afraid we can't help you when you don't use the issue template and provide all the relevant info.

**Comment by jadasse** [comment]
Should i close this and try again?

**Comment by daviunic** [comment]
You can just provide the information now, but next time please use the templates and do it from the start.

**Comment by jadasse** [comment]
Screw it ill start over
