### ISSUE TITLE
Crashes after exiting fullscreen

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#1231]
**Describe the bug**
86box crashes every time I try to exit fullscreen

**To Reproduce**
1. Go to 'View'
2. Click on 'fullscreen'
3. Ctrl+Alt+PgDown to exit

**Expected behavior**
It's supposed to exit fullscreen alike so, but it just freezes and Windows 10 says 86box has crashed, and I have no choice but to close it.

**Desktop:**
 - OS: Windows 10
 - 86Box version: v3.0 build 2771
 - Build type: optimized

**Comment by jadasse** [comment]
(@daviunic forced me to use the template and wouldn't help me directly)

**Comment by daviunic** [comment]
Try switching the renderer and using the regular.

**Comment by jadasse** [comment]
switching the renderer worked, thanks! (i tried it on my optimized build)

**Comment by jadasse** [comment]
I switched it to opengl
