### ISSUE TITLE
Cogent EM960 Emulation

### ISSUE THREAD

**Issue by CRTRevivalDreamer** [86Box/86Box#1235]
**Is your feature request related to a problem? Please describe.**
86Box can't even seem to emulate a full-duplex-compatible LAN Adapter at this time.

**Describe the solution you'd like**
I would like to see the Cogent Data Technologies EM960 PCI Network Card emulable on 86Box.

**Describe alternatives you've considered**
None.

**Additional context**
[Here's the datasheet for the chip that fueled that NIC.](https://archive.org/download/TulipManual/ec-n0752-72.pdf)

**Comment by tiseno100** [comment]
Will be considered. NIC's are sorta difficult to implement.

**Comment by OBattler** [comment]
It appears this is based on the DEC 21040. We now emulate the 21140 and the 21143 so the 21040 shouldn't be that difficult to add.
