### ISSUE TITLE
Optical Disc Drive Door/Tray Status Emulation

### ISSUE THREAD

**Issue by CRTRevivalDreamer** [86Box/86Box#1236]
**Is your feature request related to a problem? Please describe.**
86Box only opens and closes a virtual machine's optical disc drive door/tray for inserting, swapping and removing virtual media... which I don't like too much.

**Describe the solution you'd like**
I would like 86Box to allow the opening and closing of a virtual machine's optical disc drive door/tray at its users' will.
Furthermore, a virtual machine's optical drive door/tray should also be openable and closable by software - just like on a real PC!

**Describe alternatives you've considered**
None.

**Additional context**
This is mostly for nostalgia purposes.

**Comment by explorerdotexe** [comment]
I guess you could say "Reload previous image" is kind of like closing the disc drive, although it's more like taking the disc out and back in, but i see where you're coming from

**Comment by tiseno100** [comment]
There's no instruction in software that tells when the tray is opened or closed. This is done mechanically. Just unmount and mount new images. The eject instruction exists however so you can unmount/eject a CD Image via the guest.

**Comment by dhrdlicka** [comment]
This "feature" might be trivial to add, but would be practically useless and confusing when added to the existing user interface. No other emulator that uses a similar hypervisor-like user experience emulates an optical drive tray or any other mechanical aspects that don't feel natural in a functional GUI.

It might not be so terribly out of place in a more skeuomorphic UI, though. However, we don't currently have any plans to introduce one, although we wouldn't be terribly opposed to including such frontend as an option.

It might be worth mentioning that slot loading drives also do exist, so the current behavior isn't terribly unrealistic either.

**Comment by CRTRevivalDreamer** [comment]
TBH, I'd like to have the option to emulate tray-loading optical drives on 86Box.

**Comment by OBattler** [comment]
This is not going to happen, sorry, for the reasons dhrdlicka gave you.
