### ISSUE TITLE
OpenXT add support for other bioses from the project & Basic from PC-DOS not working

### ISSUE THREAD

**Issue by telanus** [86Box/86Box#1241]
Wonder if this could be added, as it offers less bugs than the plain Anonymous Generic Turbo XT and offers more features.

> Besides fixing several bugs from the Generic BIOS, many additional features have been added, including CPU/FPU detection, fast memory checking, UMB initialization, expansion ROMs in the F000-FE00 region, ROM BASIC boot option, 101-key enhanced keyboard support, and more.

Download location: https://www.phatcode.net/downloads.php?id=101 (it's freeware, so no copyright)

**Comment by jvernet** [comment]
I think it's the OpenXT entry in 86Box. Isn'it ?

**Comment by telanus** [comment]
> I think it's the OpenXT entry in 86Box. Isn'it ?

Yip it is. Seems I was using the IBMXT 64kb (2x32kb) roms and not the 8kb one

**Comment by jvernet** [comment]
Using IBM PC DOS 2.11 with this ROM, nor BASIC nor BASICA will run . Is it normal ?

**Comment by telanus** [comment]
> Using IBM PC DOS 2.11 with this ROM, nor BASIC nor BASICA will run . Is it normal ?

also found, after testing that Basic and Basica refuses to run using PC-DOS 2.10 also tried PC-DOS 3.0 and 3.30 and both of them fail to start Basic. MS-DOS 2.11 Basic works (as it's GW-BASIC)

**Comment by jvernet** [comment]
BASIC or BASICA seems to work only with genuine IBM BIOS. Even built with BASIC option,it do not work with OPENXT BIOS

**Comment by telanus** [comment]
> BASIC or BASICA seems to work only with genuine IBM BIOS. Even built with BASIC option,it do not work with OPENXT BIOS

PC-DOS Basic works great, using the 2x32kb OpenXT Bioses. Think it's freezing on the 8kb bios, as it doesn't contain Basic in the rom, something that the 2x32kb bios does contain.

**Comment by jvernet** [comment]
How can you use a different ROM with BASIC included ? OpenXT can include the XTIDE ROM, BASIC ROM or not, but 86Box the 8192 bytes one
ret = bios_load_linear(L"roms/machines/open_xt/pcxt31.bin",
			   0x000fe000, 8192, 0);

**Comment by telanus** [comment]
> How can you use a different ROM with BASIC included ? OpenXT can include the XTIDE ROM, BASIC ROM or not, but 86Box the 8192 bytes one

I have it running in PCem. I created a patch for PCem about two years ago, but so far it didn't get added to PCem: http://pcem-emulator.co.uk/phpBB3/viewtopic.php?f=4&t=3273 (my patch)

**Comment by jvernet** [comment]
Wich ROM dou you use ? It should be at least 16k or 32k. It should be easy to add this rom with BIOS and BASIC include to 86Box.
Using the tool porovided with pcxtibios31, I only got a 8k binary file...

**Comment by telanus** [comment]
When using the tool they provide the 8kb one is left at the root of the folder, but it creates an eproms dir, in it you'll find ibmxt, and the roms I use is in there, but added them here for reference:

[ibmxt.zip](https://github.com/86Box/86Box/files/5862969/ibmxt.zip)

**Comment by OBattler** [comment]
We don't load the BASIC ROM for the OpenXT, only the machine BIOS.

**Comment by OBattler** [comment]
This is now added.

**Comment by waltje** [comment]
That's kinda my bad.  I initially set up BASIC for just the IBM machine,then tried which of the clones would run it.  I should have removed that,because, erm, running an IBM Basic ROM on a clone, is, ern.. well...
--fred

    On Tuesday, April 6, 2021, 12:25:58 AM EDT, Miran Grča ***@***.***> wrote:  
 
 


We don't load the BASIC ROM for the OpenXT, only the machine BIOS.
