### ISSUE TITLE
3-D Helicopter Simulator td0 disk not reading

### ISSUE THREAD

**Issue by telanus** [86Box/86Box#1242]
**Describe the bug**
3-D Helicopter Simulator's disk file in td0 format won't read under 86box, but works perfectly with PCE

**To Reproduce**
Boot using IBM PC (1982)
[Heli.td0.zip](https://github.com/86Box/86Box/files/5855426/Heli.td0.zip)

When booting it claims it's not a bootable disk, and using a bootdisk, and running dir on it gives garbage:

![20210122-090846-619](https://user-images.githubusercontent.com/19357986/105485341-65b30880-5cb5-11eb-8a1c-517b8ce75428.png)

**Expected behavior**
It boots and is playable, as it works on PCE

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Wine
 - 86Box version: 86Box-Optimized-Core2-32-ea0cd5e7

**Comment by telanus** [comment]
> Is the floppy drive type configured correctly in 86Box settings?

Yes it is :D

**Comment by OBattler** [comment]
OK, this appears to be a 720k TD0 image, so I don't think the IBM BIOS'es are going to support it correctly as they only support up to 360k floppies. It might need a FDC controller card such as the DTK 5150 (see under Storage controllers in Settings).

**Comment by OBattler** [comment]
So, this is not bootable at all (has an IBM DOS 3.3 boot sector but no corresponding boot files), but on the Advanced/EV, DIR shows valid directory contents, same on an IBM PC (1982) with a Magictronic FDC card with FDC BIOS at CC00, in both cases with a 3.5" 720k floppy drive.

As such, I'm closing this for not being a bug at all -  just 86Box emulating the IBM PC using the actual IBM BIOS that does not of itself support floppies above 5.25" 360k, therefore requiring a FDC card with its own BIOS to support the 3.5" 720k drive required by this image.
