### ISSUE TITLE
86box Optimized Crashes on Intel Pentium G645 - SandyBridge Codename

### ISSUE THREAD

**Issue by RiskerDegree87** [86Box/86Box#1243]
I got an intel pentium G645, with haxm installed, but when i open 86box Sandybridge optimized, it will pops up in background, then crashes.

OS: Windows 10 64-bit
Memory: 8Gb DDR3
Graphics: nVIDIA Geforce GT 730 4Gbs 2.5Ghz DDR3
CPU: Intel Pentium G645

**Comment by dhrdlicka** [comment]
Can you confirm that the crash does not happen with the regular build? Also, what 86Box build are you using?

Also please use the "bug report" template in the future, as it asks you for this crucial information so we don't have to.

**Comment by RiskerDegree87** [comment]
> Can you confirm that the crash does not happen with the regular build? Also, what 86Box build are you using?
> 
> Also please use the "bug report" template in the future, as it asks you for this crucial information so we don't have to.

I confirm it's a bug, however it works on regular builds but slowly, I am using the latest version. Haxm installed, but optimized sandy bridge jumps off memory after running that (crashes)

**Comment by OBattler** [comment]
While being a Sandy Bridge CPU, the Pentium G645 might not have all the features that a Core i5 of the same generation has, and therefore, I can not guarantee that a Sandy Bridge optimized version is going to work on it. Try a Nehalem or Core2 optimized build.

**Comment by RiskerDegree87** [comment]
> While being a Sandy Bridge CPU, the Pentium G645 might not have all the features that a Core i5 of the same generation has, and therefore, I can not guarantee that a Sandy Bridge optimized version is going to work on it. Try a Nehalem or Core2 optimized build.

Thanks, core2 build works fine!
