### ISSUE TITLE
NVRAM Does not save bios changes it resets when closing program

### ISSUE THREAD

**Issue by RiskerDegree87** [86Box/86Box#1257]
Simply, whatever you do to bios settings such as "disk configurations, floppy, ports, etc." then when you try to hard reset or close the program, it simply crashes. then you try to open it, all the changes you made was reset back to BIOS factory

This is what i do:

I downloaded latest ROMS from your official GitHub page.
then I put them into "roms" folder. then I decided to make a windows 3.1 emulation, when I do CTRL+ALT+DEL for reset/soft-reset works fine, but when I try to close the program or hard reset it simply fails at boot then I noticed the hard drive was not detected I tried to set it up again, but its pretty annoying I want my changes saved into bios it works with older versions of 86box "regular build". :(

Expected behavior:
BIOS/Motherboard settings never saves.

Screenshots:
I can make a clip but it takes some time.

Desktop:
 - OS: Windows 10 64-bit Enterprise Edition
 - 86Box version: Latest from jenkins, Optimized-2Cores
 - Build type: optimized, latest-jenkins

**Comment by dhrdlicka** [comment]
Let me get this straight - this works on the regular build but doesn't work on the optimized build? Please do check the latest regular build too.

Also could you upload your 86box.cfg?

**Comment by OBattler** [comment]
What emulated machine is this on?

**Comment by RiskerDegree87** [comment]
> What emulated machine is this on?

this problem happened to all machines.

**Comment by RiskerDegree87** [comment]
> Let me get this straight - this works on the regular build but doesn't work on the optimized build? Please do check the latest regular build too.
> 
> Also could you upload your 86box.cfg?

1- i have tested latest regular build works fine however this issue happening on latest optimized build

2- 86box.cfg: https://pastebin.pl/view/9fbf0423

**Comment by OBattler** [comment]
The config file shows you're using the Generic XT Clone, which does not have NVRAM at all.

**Comment by RiskerDegree87** [comment]
> The config file shows you're using the Generic XT Clone, which does not have NVRAM at all.

I said older machines had no problem with that, but if I use AMI AOpen 53 socket 7 for example nvram does not work for some reason.

**Comment by OBattler** [comment]
It appears to be a bug with optimized builds. We are considering removing those since evidently something is getting mis-optimized and causing bugs.

**Comment by RiskerDegree87** [comment]
> It appears to be a bug with optimized builds. We are considering removing those since evidently something is getting mis-optimized and causing bugs.

Thanks for checking optimized builds, I hope if nvram get up and running on socket 5+ :)
