### ISSUE TITLE
86Box updater

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#1260]
**Is your feature request related to a problem? Please describe.**
I notice that 86box gets a new build every few hours in/according to the Jenkins website

**Describe the solution you would like**
I would like it if there was an updater that updates one's build of 86box to the latest version of the same build (e.g., Standard, Dev, Optimized, Debug)

**Describe alternatives you have considered**
The Dolphin Emulator (emulates GCN/WII (though off-topic)) can perform something similar to what I am talking about.

**Additional context**
Please?

**Comment by OBattler** [comment]
Shouldn't this be done by the 86Box Manager instead?

**Comment by jadasse** [comment]
tbh I don't care which program does it

**Comment by jadasse** [comment]
I just ported my request to 86box manager, you're welcome
