### ISSUE TITLE
Support for real drives

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#1262]
**Is your feature request related to a problem? Please describe.**
I want to play a DVD inside one of my VMs.

**Describe the solution you would like**
I would be grateful if there were a feature where one can emulate real drives on their computer.

**Describe alternatives you have considered**
DOSBox-X does something similar to what I am describing.

**Additional context**
I do not want to rip the DVD to an ISO/BIN/CUE for safety.

**Comment by OBattler** [comment]
This will be looked into after v3.0.

**Comment by jadasse** [comment]
Neato!

**Comment by OBattler** [comment]
This is now done. Currently Windows only but *nix and Mac support are in the works.
