### ISSUE TITLE
[BUG] Build 2734 (4CB2F96D): Selecting Cyrix Cx486S crashes the 86Box emulator

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#1266]
I can confirm a bug that was introduced in Build 2734 (4CB2F96D) that causes 86Box to crash when the Cyrix Cx486S processor is used.

In the 86Box Settings > Machine > CPU type (found in Tools > Settings) when I select Cyrix Cx486S from the drop down menu box, 86Box crashes:
![bug](https://user-images.githubusercontent.com/32658796/106947112-d2c79480-66de-11eb-8960-033e00b522ab.png)
Can someone look into this bug to see what is causing it to crash and fix the issue?

Here is a list of changes in build 2734 that caused this bug: https://ci.86box.net/job/86Box/2734/

Thank you for your time. ^_^

**Comment by tiseno100** [comment]
Have you tested that processor in other machines too? Did the PB410A worked with the Cyrix in first place?

**Comment by ppgrainbow** [comment]
> 
> 
> Have you tested that processor in other machines too? Did the PB410A worked with the Cyrix in first place?
> 
> If the second answer answer is yes, a bisection which will give what build caused that issue might be helpful.

The process on other 486-based machines have been tested and I will bisect which build caused this issue.

**Comment by ppgrainbow** [comment]
> 
> 
> Have you tested that processor in other machines too? Did the PB410A worked with the Cyrix in first place?
> 
> If the second answer answer is yes, a bisection which will give what build caused that issue might be helpful.

@tiseno100 I can confirm that Build 2734 caused 86Box to crash when the Cyrix Cx486S CPU is selected on a 486-based emulated motherboard. Build 2733 was the last version that work before the changes were made.

**Comment by tiseno100** [comment]
I can't seem to reproduce the issue by my side 
![image](https://user-images.githubusercontent.com/58827426/107208497-5a2c4500-6a0a-11eb-9b93-e7b5e6631a38.png)

**Comment by ppgrainbow** [comment]
> 
> 
> I can't seem to reproduce the issue by my side
> ![image](https://user-images.githubusercontent.com/58827426/107208497-5a2c4500-6a0a-11eb-9b93-e7b5e6631a38.png)

That's weird. Are you on the latest build? I might want to double check to see what is wrong here. :)

**Comment by ppgrainbow** [comment]
Updated to build 2798 (regular build) and terminating the Cx486S CPU table didn't fix the crash on my end. :(

**Comment by dhrdlicka** [comment]
Build 2798 doesn't include the fix. Wait for build 2799.
