### ISSUE TITLE
MSVC2019 ARM64 build fails with LNK1322

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#1268]
**Describe the bug**
The ARM64 debug build fails with the following message when using the v142 toolchain (2019). Clang build is not affected.
```
386_dynarec.obj : fatal error LNK1322: cannot avoid potential ARM hazard (Cortex-A53 MPCore processor bug #843419) in section #3; please consider using compiler option /Gy if it was not used [D:\a\86Box\86Box\build\src\86Box.vcxproj]
```

**Expected behavior**
Build should succeed.

**Additional context**
This is likely a MSVC compiler bug introduced in the v142 toolset. The issue didn't happen with the v141 toolset (2017) nor does it happen with v142 _release_ builds (likely because they enable the suggested optimization).

**Comment by dhrdlicka** [comment]
I implemented the obvious fix, which is simply adding the suggested compiler flag to the affected builds. Keeping this issue open as it's clearly not a definite fix.

**Comment by OBattler** [comment]
Closing this issue because we have since dropped MSVC support.
