### ISSUE TITLE
Samsung SPC-6000A hangs on soft reset

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#1270]
I have found a bug regarding the keyboard controller (KBC) and when trying to invoke CTRL + F12, the key to perform a CTRL + ALT + DEL soft reset, the emulated Samsung SPC-6000A hangs and a hard reset needs to be performed to fix this issue.

Here's a screenshot of where the hang is occurring
![bug](https://user-images.githubusercontent.com/32658796/107131905-b454cb00-688f-11eb-8021-2286a8253c79.png)
:
This issue occurs since the Samsung SPC-6000A was introduced in build 2757. Build 2758 didn't do anything to fix the soft reset bug.

Please investigate this issue on what is causing the KBC to fail on soft reset.

Thank you for your time. :)

**Comment by OBattler** [comment]
This is now fixed.
