### ISSUE TITLE
MIDI sound not working with Gravis Ultrasound in Windows 3.11

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1274]
**Describe the bug**
I installed the Gravis Ultrasound card with it's original drivers (ver 4.11) under DOS 6/Windows 3.11. The sound card seems to works fine
and reproduce the MIDI files under Windows Media Player. 
The issue is games cannot detect the MIDI interface even when seem to be correctly installed.

I tested the games: 

* Even more Incredible machine for Windows
* Super Tetris for Windows:

The games are installed on the hard disk.

Here is the CFG, NVR and hard disk image
[NVR-CFG.zip](https://github.com/86Box/86Box/files/5955632/NVR-CFG.zip)

[486 Gravis Test.zip](https://github.com/86Box/86Box/files/5955633/486.Gravis.Test.zip)

Here are the game codes for Tetris, if are needed:
[codes.txt](https://github.com/86Box/86Box/files/5955646/codes.txt)

The Incredible machine also asks for the codes, but music should be heard at the beginning of the game. (I can send it if needed).

**To Reproduce**
1. Configure the machine (Jetway J-403TG, Cyrix 486S/33, 8mb RAM, Cirrus Logic 5422, IDE HD C=684/H=16/S=38 203mb)
2. Boot up the machine
2. Type 'WIN' to start Windows
3. Start the game from the shortcuts

**Expected behavior**
The MIDI interface should be detected by software applications in the same way than Windows Media Player.

**Screenshots**

![MIDI error](https://user-images.githubusercontent.com/31600563/107460707-63ff9680-6b37-11eb-96c8-0e785e4d607d.png)

![MIDI mapper](https://user-images.githubusercontent.com/31600563/107460731-6eba2b80-6b37-11eb-822d-2f679d672629.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 2004
 - 86Box version: 3.0.0.2799
 - Build type: regular

**Additional context**

An interesting point although is unrelated to the GUS MIDI bug. The Cyrix 486S/33 is detected by the machine as TI486SXL-S. That is the Texas Instruments 486, which like the Cyrix DLC 486, is an upgrade for 386 DX motherboards, but it has 8kb L1 cache instead 1kb.

![TI486SXL-S](https://user-images.githubusercontent.com/31600563/107461216-51399180-6b38-11eb-8daa-54b1226ef598.png)

**Comment by TC1995** [comment]
does it work on dosbox-x by any chance? I mean, midi on those games within win3.1x.

**Comment by TC1995** [comment]
Ok, happens on dosbox-x as well.

**Comment by TC1995** [comment]
Hmm, I think it's because you're using the wave device for both wave and midi (ultrasnd.drv), causing a conflict.

**Comment by OBattler** [comment]
Then I'd say this is NOTABUG - just a Windows 3.1 limitation.
