### ISSUE TITLE
Adding Multitech ACER 500+

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1275]
**Is your feature request related to a problem? Please describe.**
Not a problem
Want to add the Multitech Acer 500+ 8088 system, a curious system with all system on boards.
Simple IBM XT system, 512 or 640k RAM, CGA, 2 360K drive, Hard Disk.
Rom: Seems to be a32k ROM (may be 16k)
[rom404.zip](https://github.com/86Box/86Box/files/5960044/rom404.zip)
**Describe the solution you'd like**

Diff below. Note that CGA or hercule card do not work (may be the system expect to use only internal CGA card).

Add this to machine.h:
`extern int	machine_xt_multitechpc500_init(const machine_t*);`

Add this to m_xt.c:
`int
machine_xt_multitechpc500_init(const machine_t* model)
{
	int ret;

	ret = bios_load_linear(L"roms/machines/multitech_pc500/rom404.bin",
		0x000f8000, 32768, 0);

	if (bios_only || !ret)
		return ret;

	device_add(&keyboard_pc_device);

	machine_xt_common_init(model);

	return ret;
}`

Add this to machine_table.c:
`    { "[8088] Multitech PC-500",		"multitech_pc500",	MACHINE_TYPE_8088,		CPU_PKG_8088, 0, 0, 0, 0, 0, 0, 0,										MACHINE_PC,									   128,  640,  64,    0,       machine_xt_multitechpc500_init, NULL			},
`
![Capture 1](https://user-images.githubusercontent.com/16312616/107546214-695af080-6bcc-11eb-8e0e-f6c53759b5fe.PNG)
![Capture 2](https://user-images.githubusercontent.com/16312616/107546224-6c55e100-6bcc-11eb-834d-e3d02ed84bc9.PNG)

**Comment by tiseno100** [comment]
As you added it yourself. Feel free to provide a pull request containing it :b
