### ISSUE TITLE
Soft reset broken on Packard Bell PB410

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#1278]
I'm currently emulating the Packard Bell PB410 and since the rewrite of the AT keyboard controller (KBC) polling, Build #2514 (949e145b) broke the soft reset capability completely on the Packard Bell PB410 along with a beep before halting.

Here's a screenshot of the issue and the 86Box.cfg file:
![20210213-040502-988](https://user-images.githubusercontent.com/32658796/107845115-ff8a4480-6d8d-11eb-83b1-22908dddfba4.png)

https://pastebin.com/pDkUCWvr

Build #2513 was the last build that work, although not 100% all the way.

Please look into this issue and fix it if you can. Thanks. :)

**Comment by OBattler** [comment]
This is now fixed.
