### ISSUE TITLE
Quadtel 286 (GC103) does not work with MFM/IDE type 5 hard disk

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1281]
**Describe the bug**
I created a  type 5 hard disk (46MB,C/H/S 940/6/17). I configured the Quadtel 286 (GC103) machine correctly as type 5 in the setup BIOS. 

1. If the disk/ controller is MFM (ISA 16 WD1003)

The FDISK utility included in MS-DOS 3.31 detects the hard disk, but it freezes when I attempt to create a partition

2. If I define it as an IDE (ISA 16 IDE) (It throws same error with WD-1002A-WX1, with the BIOS disabled, since the AT machines have their own)

It throws an error saying "Hard disk controller error"

I created the hard disk image (with the IDE controller) with the Trigem 286 machine successfully.

Here is the HD image and the CFG/NVR of both machines

[Quadtel Trigem.zip](https://github.com/86Box/86Box/files/5989818/Quadtel.Trigem.zip)

And the NVR/CFG:

[286 Trigem Quadtel.zip](https://github.com/86Box/86Box/files/5989819/286.Trigem.Quadtel.zip)

**Screenshots**
![Hard disk controller failure](https://user-images.githubusercontent.com/31600563/108086283-f7175f80-7054-11eb-9f19-7367bfe28d6e.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10  ver 2004
 - 86Box version: 3.0.0.2803
 - Build type: regular

**Comment by OBattler** [comment]
That simply mean this BIOS doesn't like this hard disk type, which might simply mean that its type 5 has different CHS parameters. There's nothing I can do about that.

**Comment by Fenix770** [comment]
No, both machines support the same Hard disk type with the same parameters, the Quadtel 286 GC103 and the Trigem.
Here are the screenshots.

This is The Quadtel 286 
![BIOS SETUP HD 002](https://user-images.githubusercontent.com/31600563/108429513-d995f180-721e-11eb-908a-370b3ab59657.png)

The Trigem 286
![SETUP HD Trigem](https://user-images.githubusercontent.com/31600563/108429649-077b3600-721f-11eb-9ae8-be9c9edbbb58.png)

And the 86box configuration
![BIOS SETUP HD 001](https://user-images.githubusercontent.com/31600563/108429715-1eba2380-721f-11eb-9468-b7c7aa291c4f.png)

**Comment by overthetop78** [comment]
same problem with 386SX and 386DX. The drives created, no matter what type (and even with a personal type 47), the BIOS indicates a disk controller error.
With the new Flytech 386 motherboard and its "recent" BIOS, no problem, the hard drive is well recognized, no matter which one. But there is a keyboard problem (the arrow keys do their job but do in addition to the numeric keypad keys (Left arrow can sometimes write a 4, Down arrow a 2, and so on).
The problem on BIOS 286 (for my neighbor above) and 386SX / DX (I did not test for 486 or 8086/88) did not exist on older versions of 86Box with AMI / AWARD clone BIOS in ISA)

"Sorry if I write poorly English, I am French and I use the machine translation"

**Comment by Fenix770** [comment]
Update: I managed to boot from this machine with MFM WD 1003 AT controller. **But** It cannot write to disk, can only read. I created the HD image with the 286 Trigem machine. 

Here is the screenshot
![Quadtel 286 bug](https://user-images.githubusercontent.com/31600563/112791082-23040880-9037-11eb-9bd0-8f50e6fa6a47.png)
 
I used the same hard disk I previously uploaded in this thread.
