### ISSUE TITLE
Host CPU and GPU usage problem when emulation is only 39%

### ISSUE THREAD

**Issue by overthetop78** [86Box/86Box#1282]
**Describe the bug**
86Box [Zen Build] does not seem to use my processor much yet the virtual machine runs between 30% -40% on the "Age Of Empire" game under Windows 95 with a 133 Mhz CPU with an S3 Virge GPU.

**To Reproduce**
Start Age Of Empire under Windows 95 with a machine:
- CPU WinChip 133 Mhz
- Epox P55 Motherboard [i430VX]
- Socket 7 (Dual Voltage)
- 32 MB
- Dynamic Recompiler
- PCI S3 Virge / DX (VBE 2.0)
- 3DFX Voodoo 1
- Aztec Sound Galaxy Nova 16 Extra
Host configuration:
MSI x470 + AMD Ryzen 7 1800x + GTX 1080 Ti + 32GB DDR4

**Expected behavior**
Increased CPU and GPU usage to keep emulation at 100%. A function to use the processor at a higher percentage or at the percentage required for 100% emulation

**Screenshots**
Emulation is 39% 
<img width="1257" alt="86Box_AOE_CPU_Emul_Percent" src="https://user-images.githubusercontent.com/37494719/108290609-0ac7e080-7191-11eb-8cd6-3b1287830933.png">

CPU Host : 7.8% Use, GPU Host : 1.2% Use
<img width="661" alt="86Box_CPU_Use" src="https://user-images.githubusercontent.com/37494719/108290570-f71c7a00-7190-11eb-8ce2-3a68d59c4c65.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - 86Box version: V3.0 c65777c3, build 2799
 - Build type: Optimized Zen (For Ryzen 1800X)

**Additional context**
The test with the latest build 86Box (Version without optimization) gives a 10% lower emulation speed (25% instead of 39% with Zen optimization) The processor and the host graphics card still run at the same percentage.

**Comment by explorerdotexe** [comment]
I think this might be because 86box is a single core process.

**Comment by overthetop78** [comment]
> I think this might be because 86box is a single core process.

But in one core it is only used at 7%. My CPU is 4.0Ghz .. It should use a lot more than 7% of the CPU. Having a core at least over 7% usage
I think 86Box is not fully utilizing the available CPU resources.
Moreover, under Windows 95 I am at 100% in emulation, when I run certain games, it remains at 100% but for Age Of Empire, it drops directly to less than 40%.
I think using emulated GPU is using host CPU poorly and maybe not using Host GPU and using host CPU.
The advanced graphics (3D) functions may need to be redirected to DirectX Host.

**Comment by explorerdotexe** [comment]
> 
> 
> > I think this might be because 86box is a single core process.
> 
> But in one core it is only used at 7%. My CPU is 4.0Ghz .. It should use a lot more than 7% of the CPU. Having a core at least over 7% usage
> I think 86Box is not fully utilizing the available CPU resources.
> Moreover, under Windows 95 I am at 100% in emulation, when I run certain games, it remains at 100% but for Age Of Empire, it drops directly to less than 40%.
> I think using emulated GPU is using host CPU poorly and maybe not using Host GPU and using host CPU.
> The advanced graphics (3D) functions may need to be redirected to DirectX Host.

It could be that, but i'm not a dev so you'll have to ask them.

**Comment by overthetop78** [comment]
By using a Socket 7 motherboard (single voltage) always with an IDT Winchip 133Mhz, by changing graphics card for an ATI Mach64, by reducing the Voodoo 1 card (not used for the AOE game) to 2MB instead of 4MB ( I don't think it changes anything but I still specify) "Age Of Empire" is running well at 100%, my CPU is at 2% and my GPU at 4%.
The problem would therefore come from the S3 Virge / DX (VBE 2.0)

**Comment by dhrdlicka** [comment]
Hello, this is by design -- emulators like 86Box generally profit more from single thread performance rather than the number of cores. There is no easy way to run a single stream of instructions, executed by the single CPU core, parallelly.

**Comment by ppgrainbow** [comment]
No matter how fast your PC is (new or not), this behaviour is by design due to the fact that 86Box and other emulators profit from the use of a single core part of the processor as dhrdlicka said. And a single core processor can never exceed a 32-bit value, putting it at 4.295 GHz per core maximum: https://forum.hothardware.com/posts/t16005findunread-32-bit-LIMIT

Emulated processor speeds faster than 33MHz will start experiencing slow downs of the emulated CPU speed and it will not always be at 100%.

If you would like to run 86Box at 100%, please use a 33 MHz processor or slower and don't open more than one instance of 86Box.

**Comment by OBattler** [comment]
Why on Earth would frequency be limited to 32 bits?

**Comment by dhrdlicka** [comment]
> Emulated processor speeds faster than 33MHz will start experiencing slow downs of the emulated CPU speed and it will not always be at 100%.
> 
> If you would like to run 86Box at 100%, please use a 33 MHz processor or slower and don't open more than one instance of 86Box.

This is highly dependent on the host CPU. A system with better single thread performance (instructions per clock) will have less problems with emulating higher clock speeds. 33 MHz is absolutely not a hard limit.

**Comment by overthetop78** [comment]
> No matter how fast your PC is (new or not), this behaviour is by design due to the fact that 86Box and other emulators profit from the use of a single core part of the processor as dhrdlicka said. And a single core processor can never exceed a 32-bit value, putting it at 4.295 GHz per core maximum: https://forum.hothardware.com/posts/t16005findunread-32-bit-LIMIT
> 
> Emulated processor speeds faster than 33MHz will start experiencing slow downs of the emulated CPU speed and it will not always be at 100%.
> 
> If you would like to run 86Box at 100%, please use a 33 MHz processor or slower and don't open more than one instance of 86Box.

Please say anything.
I am currently using 86Box on my Ryzen 7 1800x. I changed the socket (Socket 7 (single voltage)) kept the same IDT Winchip 133Mhz CPU and I changed the S3 Virge / DX (VBE 2.0) By the ATI Mach64 and under windows 95, Age Of Empire runs well at 100% without slowing down. (unlike 40% with S3 Virge / DX (VBE 2.0)) Host CPU runs at around 2% (instead of 7%) and GPU at 4% (instead of 1.2%)
So my PC is not involved, and apparently it's the S3 Virge / DX (VBE 2.0) that is causing the problem (since with the ATI Mach64 it works perfectly)
I found a solution, but it is good to be able to show that there is a problem with the S3 Virge / DX (VBE 2.0)

**Comment by ppgrainbow** [comment]
Hmm...something could be amiss with the S3 Virge / DX (VBE 2.0). :|

**Comment by dgurney** [comment]
> And a single core processor can never exceed a 32-bit value, putting it at 4.295 GHz per core maximum: https://forum.hothardware.com/posts/t16005findunread-32-bit-LIMIT

Your forum thread is from *2004*... Even back then it was a visual bug which has been fixed for well over a decade at this point.

> Emulated processor speeds faster than 33MHz will start experiencing slow downs of the emulated CPU speed and it will not always be at 100%.
> If you would like to run 86Box at 100%, please use a 33 MHz processor or slower and don't open more than one instance of 86Box.

What? The reporter's CPU can easily handle more than 33MHz, as stated by them in this thread. Also, on a multi-core processors more than 1 86Box instance is not an issue.

@ppgrainbow, please do better next time.

**Comment by ppgrainbow** [comment]
Oh, okay. Sorry for the misinformation then.

**Comment by OBattler** [comment]
It could be that the S3 ViRGE driver simply does things that the dynamic recompiler doesn't like, hence the performance disparity between it and the Mach64. Could you try both cards on the interpreter to see if the disparity remains?

**Comment by OBattler** [comment]
At this point, I conclude that that particular BIOS is most likely for a variant of the ViRGE with higher refresh rates, hence the emulator slowdown.
