### ISSUE TITLE
Keyboard issues again

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1287]
**Describe the bug**
Again, I'm experiencing difficulties with the keyboard emulation in 8088/8086,802086 or 80386 mode under dos, and with the mous eemulation under AMSTRAD PC.
Directionnal keys sendings numbers instead, DEL key sending a dot, etc.
Under PC 1512, again, mouse and directionnal keys are matched.... So, if you move the mouse, the keyboard react as if you hit directionnel keys...

**To Reproduce**
Any machine under MSDOS.

**Screenshots**

![image](https://user-images.githubusercontent.com/16312616/108744296-12450c00-753a-11eb-9baf-d103080fb830.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x68 20H2
 - 86Box version: 2807.
 - Build type: regular

**Additional context**

**Comment by jvernet** [comment]
I also experience some complete crash, or keyboard stoping working.
More over, Ctrl-Alt-Del only work 1 time over 10... if not less.

**Comment by OBattler** [comment]
See if these issues still occur, since there have been numerous changes since.

**Comment by jvernet** [comment]
Seems to be ok for 286/386. 
Ctrl-Alt-Del via Menu do not always work, anyway, but case are difficult to find.
