### ISSUE TITLE
RTC, HD and mouse on Amstrad machines

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1296]
**Is your feature request related to a problem? Please describe.**
This request is about the Amstrad RTC controller and I have other questions about the 3086 model. 

1.I'd like to ask if it is possible to implement the onboard RTC controller on Amstrad XT machine.
I configured the 3086 with the Everex I/O RTC clock and I'm using a shareware clock device driver. It works flawlessly except it throws a **"Please set the time and date"** when, the Everex I/O card, is already correctly configured. (Conflict with BIOS and Everex card?). 

![Time and Date](https://user-images.githubusercontent.com/31600563/110179178-5fe93080-7de6-11eb-8077-4ff8512c386b.png)

2. According the Retroisle site only the OEM XT mouse interface is used only in the 1512,1640 and 2086 models. The latter models use a regular serial mouse. In 86box, at least, the Internal mouse option is available.
link [http://www.retroisle.com/amstrad/pcs/software.php](url)

3. There is a contradictory information about the 3086 model between Retroisle and the John Elliot site. According Retroisle the some 3086 models had an optional RLL controller and Windows 2.1 installed. According the John Ellitot site  the 3086  has an 
internal XTA interface and only MS-DOS 3.30 (no Windows).
However, I believe that the John Elliot information is more reliable. After all he implemented the Toshiba Laptop machines, and some non standard pre-VGA video cards.
link [https://www.seasip.info/AmstradXT/models.html#pc2086](url)

**Describe the solution you'd like**
All Amstrad machines seem to have an integrated RTC clock. It tells the time and date of the last boot at every startup, but does not retain the time or date at the DOS prompt or any other application. I didn't find  a device driver on any OEM Amstrad DOS I checked (PPC models and 1512/1640/2086) 

Check, if it is possible, if the internal XT mouse exist in the real 3086 hardware, and implement the XTA controller, again, if information about it exist.

**Additional context**

The build of 86box is: 3.0.0.2813

Here is the HD image. I installed the Amstrad Windows 2.1/286, but does not start and I suspect it was designed for 286 based Amstrad models.

[Amstrad 3086 RLL 615-4-26-.zip](https://github.com/86Box/86Box/files/6093672/Amstrad.3086.RLL.615-4-26-.zip)

**Comment by Fenix770** [comment]
I tested the Amstrad 1512 and 1640 yesterday and on both machines the onboard RTC works flawlessly.

**Comment by Fenix770** [comment]
I have tested the Amstrad 2086 and 3086 and on both machines the clock now works!. 
However, I found that the Olivetti M24/240 machines also have an onboard RTC, and don't seem to work correctly. 
(I add this in this thread because is also related to the RTC).

![Olivetti clock](https://user-images.githubusercontent.com/31600563/111568859-46e66500-8780-11eb-8126-048280934e6b.png)

I'm using the Dev version 3.0.0.2827 of 86box.

**Comment by OBattler** [comment]
For the Olivetti M24, we currently use the AT RTC, but I have no idea whether or not that is correct. Given that it's not working for you, it seems to not be correct all, so I'm going to tag this as "Some day in the future", as this is going to have to be implemented at some point (but not right now).

**Comment by javi-s** [comment]
The Olivetti M24 uses a MM58174 4-bit BDC RTC. I have been working on an initial implementation of this RTC. What is the best way to contribute it?

**Comment by Cacodemon345** [comment]
We accept Pull Requests as a way of contributing code.

**Comment by javi-s** [comment]
Great, I will create one.  Thank you.

**Comment by OBattler** [comment]
Since the original issue is fixed, this should be closed.
