### ISSUE TITLE
TANDY 1000HX issue

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1305]
**Describe the bug**
Tandy 1000Hx issue: message "WARNING BAD EEPROM record found" when usinh SETUPHX

**To Reproduce**
Start new 1000hx system, use SETUPHX to try to configure. Message above, change aren't saved.
One more thing: direction keys do not work as attended (garbage sent to screen)

**Expected behavior**
SETUPHX should work... PCEM does.

**Screenshots**

**Desktop (please complete the following information):**
W10 20H2
 - 86Box version: build 2778 regular

**Comment by OBattler** [comment]
Where do I get SETUPHX?

**Comment by OBattler** [comment]
You need to specifically press F1 to update the EEPROM. The EEPROM record is by definition bad before it's configured.

**Comment by OBattler** [comment]
OK, can I have the specific version of SETUPHX you're using? I'm getting "WARNING: Invalid EEPROM record found." instead.

**Comment by OBattler** [comment]
OK, the direction/arrow keys are now working on all three Tandy machines, at least in Norton Commander and in the version of SETUPHX I have.

**Comment by jvernet** [comment]
I'm using SETUPHX from here:
ftp://ftp.oldskool.org/pub/tvdog/tandy1000/system/hxdisks.zip

**Comment by jvernet** [comment]
arrow keys working now.
I created and successfully booted on a Hard Disk under PCEM, but the same Hardisk image do not work under 86Box (XTiDE emulation). Is it normal ?
Here is the HD image: 
[TANDY 1000 20 Mo 615 17 4.zip](https://github.com/86Box/86Box/files/6156651/TANDY.1000.20.Mo.615.17.4.zip)-

**Comment by OBattler** [comment]
Yes, that's normal. XTIDE is IDE over XT and as such, subject to the same caveats as AT IDE. PCem marks all IDE hard disks as having LBA support, while 86Box marks hard disks within the CHS limits (so < 503 MB) as being CHS only. As such, some PCem images may not directly work in 86Box due to CHS translation differences.

**Comment by Fenix770** [comment]
I've found some information (Don't know if it is relevant): I read on Tvdog site that EX and HX models have a non-standard ISA slots. To install a standard IBM PC ISA an adapter was required. 
Here is the document: [http://www.oldskool.org/guides/tvdog/1kfaq.html](url) _( where says "The 1000EX and HX have Plus-type")_

**Comment by jvernet** [comment]
The connector is physically different, but it's a plain ISA bus. There is a sort of riser card that allow to install ISA card. People are using XTIDE in 1000hx.

There is something wrong with Tandy HX emulation in 86Box using XTIDE. I can't make it working correctly. I can format the disk (using the disk below, with fdisk I picked elsewhere, FORMAT the disk, SYS it, but I cannot make le emulated 100Hx boot.

Using the above generic 2.11 boot disk, it work, but do not recognize 720k drives. You need to use TANDY OEM version.
PCEM deal without any problem with it.

[DISK1.zip](https://github.com/86Box/86Box/files/6157688/DISK1.zip)
[MS-DOS 2.11.img.zip](https://github.com/86Box/86Box/files/6157695/MS-DOS.2.11.img.zip)

**Comment by Fenix770** [comment]
I was able to create a 10mb HD image using the IBM (Xebec) controller. I used regular MS-DOS 2.11 FDISK to create the partition and then booted from Tandy DOS 2.11.24 and used SYS C: command to make bootable the hard disk. It reads 720kb floppy flawlessly.

Here is the image file: 
[Tandy 1000 original 10mb.zip](https://github.com/86Box/86Box/files/6158139/Tandy.1000.original.10mb.zip).

MS-DOS 2.11 is limited to 16mb for hard disk. Altough some special versions support bigger disk. Compaq DOS 2.12 includes an enhdisk.sys to create/read disks up to 32mb. I also know, but not used, a software called OnTrack. It can created much bigger disk using non-standard cluster sizes. 128mb on DOS 2.x 939mb on DOS 3.x and 1gb on DOS 4.x

![Ontrack 430 DOS 2x](https://user-images.githubusercontent.com/31600563/111506902-dd873780-8728-11eb-9843-5666a8145fb3.png)

**Comment by jvernet** [comment]
New issues: 
* under DOS 3.30 with french keyboard (keyb fr), arrows keys do not work. Numpad arrow key works.
* ctrl-alt-del leave emulated Tandy 1000 unstable

**Comment by jvernet** [comment]
@Fenix770 so PCEM do not mimic exactly, because it work with a 20Mb Hard Disk

**Comment by jvernet** [comment]
Another thing, about the display: here is a real screen vs emulated screen. Why is there some space between lines ?

![](https://system-cfg.com/photosforum/tandy_1000hx_4.jpg)

![20210317-210231-461](https://user-images.githubusercontent.com/16312616/111538872-835c9580-876d-11eb-9ed0-1470393d4901.png)

**Comment by OBattler** [comment]
If KEYBFR is for the normal XT keyboard, it might break the arrow keys on the Tandy 1000 HX. I know the arrow keys weren't working on MS-DOS 5.00 with no driver, either, and I'm not quire sure why that is.

**Comment by OBattler** [comment]
OK, so it actually seems to be setting an 8x9 font size. Maybe the Tandy 1000 HX has special circuity for vertically duplicating the last row?

**Comment by jvernet** [comment]
I'm using only the Tandy tools for keyboard. It seems that there is also things like KEYBTFR, KEYBTUK KEYBTDE.COM but can't find them.

Will have soon a real Tandy 1000HX to go further. People use MSDOS 5.0, I'm not sur it's a good choice.

**Comment by OBattler** [comment]
I fixed the floppy drives problem on the Tandy machines.
