### ISSUE TITLE
Sound blaster cannot be initialized when running 8088 domination demo

### ISSUE THREAD

**Issue by ffuentese** [86Box/86Box#1315]
I'm talking about this demo http://www.pouet.net/prod.php?which=63591 

When I try to initlialize it it complains that **Sound Blaster couldn't be initialized**. Everything else seems to be correctly set. The machine does have sound working with other applications.

Build: 2829

Machine: 8088 Generic XT Clone (but also  both IBM XT)

Memory: 640 KB

Video [ISA] CGA

Sound: Sound Blaster (tried 1.5, 2 and Pro 1 and 2)

**Comment by OBattler** [comment]
Try the original Sound Blaster.

**Comment by ffuentese** [comment]
> 
> 
> Try the original Sound Blaster.

I assume you mean the Sound Blaster 1.0? I didn't include it because it's not supposed to work with it and indeed the error is the same.

**Comment by OBattler** [comment]
What IRQ is your Sound Blaster set to? And is there anything else on that IRQ?

**Comment by ffuentese** [comment]
The default:

IRQ 7

DMA 1

Nothing else set up.

**Comment by OBattler** [comment]
Does the issue still occur?

**Comment by OBattler** [comment]
Closing for lack of feedback, so I'm assume it's fixed (since there's been numerous Sound Blaster-related fixes since, anyway). If it  hasn't been, it can be reopened.
