### ISSUE TITLE
SINCLAIR PC200 arrow keys

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1317]
**Describe the bug**
Same as it was for Amstrad, arrow keys and keyboars INS, SUPR, etc are messed up as long as you start AMSTRAD MOUSE.COM.
Arrows send number, Insert keys send a dot. NUM Block do not work.
The SINCLAIR nomal mouse.com simply throw a DIVIDE ERROR when launched from command line, or CANNOT WRITE TO AUX then crash when in a BAT commend files.

**To Reproduce**
Configure a SINCLAIR PC200 system, use SINCALIR PC 200 SYSTEM DISK (or AMSTRAD SYSTEM DISK).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: Build 2825
 - Build type: regular

**Additional context**

**Comment by OBattler** [comment]
This is going to be very difficult to fix unless someone is able to provide Amstrad keyboard documentation.

**Comment by incognitte** [comment]
Not sure if SINCLAIR PC200 has the same keyboard as [SINCLAIR PC2386](https://oldcrap.org/2019/06/27/amstrad-2386-keyboard/) but it may worth taking a look at that page. It has a lot of details including keyboard com timing and protocol.

![Amstrad 2386 Scan codes](https://oldcraporg.files.wordpress.com/2019/06/amstrad-2386-3386-keyboard-scan-codes-2.png)

**Comment by OBattler** [comment]
> it seems that Amstrad PC20 and Sinclair PC200

They are the same machine. It was an Amstrad machine that Sinclair then sold under a different name.

**Comment by OBattler** [comment]
OK, it apparently uses AT-like scan codes.
