### ISSUE TITLE
Keyboard problems on i386 machines

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1333]
**Describe the bug**
After loading MS-DOS v6.22 and the Volkov Commander file manager, when you press the arrow keys to move the cursor up/down through the panels, the numbers 8 or 2 are randomly typed in the Volkov Commander command line (just as they look and would be pressed on the numeric keypad). This happens on all i386 machines with different types of processors and their frequencies. Enabling or disabling Num Lock in the bios of these machines does not help. While on other machines: i486, Pentium this bug is not present. In addition, on a real PC in MS-DOS v6.22 and Volkov Commander this bug is not present. In addition, DOSBox-X does not have this bug.

**To Reproduce**
1. Create any i386 machine and install MS-DOS v6.22.
2. Also install the file manager Volkov Commander.
3. Press and hold the up/down arrow keys to move the cursor in the panels.
4. See error.

**Expected behavior**
As you move the cursor across the panels, the keyboard should work fine (no accidental duplicate numeric key presses).

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v1909
 - 86Box v3.00 build 2847
 - Build type: regular

**Comment by maximus105** [comment]
This bug occurs even without starting Volkov Commander. That is, in pure DOS v6.22 with the NUMLOCK=ON parameter set in CONFIG.SYS. This bug was also seen on machines 286 and 486. In most cases, if you set NUMLOCK=OFF in CONFIG.SYS, then the bug is absent, but it can still appear on some machines.

**Comment by OBattler** [comment]
Does this problem still occur?

**Comment by maximus105** [comment]
Yes. [Citygate D30 XT] Hedaka HED-919 had this bug in DOS v6.22 when setting NUMLOCK = ON or NUMLOCK = OFF in CONFIG.SYS

**Comment by OBattler** [comment]
That machine is not even 386, but a pseudo-XT that's highly non-standard, who knows what keyboard it even wants. It's Dev branched for a reason.
