### ISSUE TITLE
Display not correct in a CGA game

### ISSUE THREAD

**Issue by Altheos** [86Box/86Box#1336]
**Describe the bug**
DOS game Prohibition (Infogrames) is the only one that use a CGA trick to do a smooth scroll screen.
This trick ("drawing new information into the section that is about to wrap around in CGA memory, and then scrolls anyway, bringing that new information into place") is correctly emulated using Dosbox (CGA card) or Mame.

1. Launch game choosing "Other" as video adapter and slow as speed
2. Launch game using spacebar then see error
3. it's easier to see error when on start screen.

**Expected behavior**
Smooth scroll like dosbox or mame.

**Screenshots**
Corruption using 86Box
![Capture](https://user-images.githubusercontent.com/29195397/112665868-cd273900-8e5b-11eb-8da5-e2e1338be708.JPG)
Correct display using dosbox-x (works also using dosbox vanilla)
![Capture_dosbox](https://user-images.githubusercontent.com/29195397/112665928-e03a0900-8e5b-11eb-898c-bae1d3909e25.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 or 7
 - 86Box version: 2854
 - Build type: regular

**Comment by OBattler** [comment]
Can you upload the VM please so I can reproduce the bug?

**Comment by Altheos** [comment]
VM uploaded on 86Box FTP in "Uploads" directory. It's name is dos.7z.
Thanks.

**Comment by Altheos** [comment]
I can confirm that this is fixed in build 2991.
Thanks !
