### ISSUE TITLE
Tandy 1000 SL/2  Issues

### ISSUE THREAD

**Issue by greyhairedoldbadger** [86Box/86Box#1340]
**Describe the bug**
Drive A: can no longer be accessed after writing changes to EEPROM.

**To Reproduce**
1. Create aTandy 1000 SL/2 machine with a 720k DD 3.5'' Floppy (and optionally a second floppy)  
2. Boot from functional A: drive and run setupsl2.exe from floppy.
3. Optionally make changes and press F1 to update EEPROM.
4. Exit 86Box. tandy1000sl2.bin is saved to \nvr\
5. Restart 86Box. A: drive no longer accessible.

**Expected behavior**
A: drive accessible after writing sane changes to EEPROM

**Screenshots**
![Functional_Floppy](https://user-images.githubusercontent.com/63615420/112766844-8d06b880-900b-11eb-8a47-aac7bf528812.png)
![setupsl2_1](https://user-images.githubusercontent.com/63615420/112766848-92640300-900b-11eb-8ddf-8522a1c9166f.png)
![setupsl2_2](https://user-images.githubusercontent.com/63615420/112766853-955ef380-900b-11eb-882a-2021e8076831.png)
![setupsl2_3](https://user-images.githubusercontent.com/63615420/112767008-4d8c9c00-900c-11eb-925c-c6cee57ecc38.png)
![EEPROM](https://user-images.githubusercontent.com/63615420/112766860-998b1100-900b-11eb-963a-7a91b066a708.png)
![Error](https://user-images.githubusercontent.com/63615420/112766866-9c860180-900b-11eb-9ade-24f9693e936d.png)

**Desktop (please complete the following information):**
 - Virtual Windows 10
 - 86Box version: 86Box v3.0.0.02857
 - Build type: Regular

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by OBattler** [comment]
See if the latest BIOS fixes this.

**Comment by greyhairedoldbadger** [comment]
No change in behaviour observed with Build v3.0.0.2866.
Using ROM Repository cloned 30/03/2021,

**Comment by OBattler** [comment]
Are you sure the DOS version you're using, is recognizing the drive type reported by the BIOS correctly?

**Comment by greyhairedoldbadger** [comment]
> Are you sure the DOS version you're using, is recognizing the drive type reported by the BIOS correctly?

Frankly, I'm not sure. I'm using the disc images available at https://winworldpc.com/product/ms-dos/3x. These are the Tandy 1000SL/2 OEM Disk images, reporting a DOS version of 3.30.22. This is the same version reported by the ROM.

Some observations and assumptions, please correct me where I am wrong!

After initially creating a Tandy 1000 SL/2 machine and subsequently shutting down, tandy1000sl2.bin is saved in \nvr\
This file consists of 128 bytes each of a value 00, and represents the contents of the machine's EEPROM:
![Initial](https://user-images.githubusercontent.com/63615420/113510486-ff6b2180-9552-11eb-87f2-abf5f540d05e.png)
After writing factory default settings to the EEPROM, the file looks like this:
![Factory](https://user-images.githubusercontent.com/63615420/113510668-d0a17b00-9553-11eb-8802-3b72ed440709.png)
At this point, A: can still be accessed.
After updating the EEPROM manually by pressing F1, the file looks like this:
![Floppy](https://user-images.githubusercontent.com/63615420/113511437-a18d0880-9557-11eb-97c6-d99d8b1cc072.png)
The only difference I can see is the bytes circled in red. From experimentation, I note the bytes seems to represent the following:

00 00 - 1 drive installed, drive 1=none, drive 2=none, drive 3=none.
00 30 - 1 drive installed, drive 1=3-1/2, drive 2=none, drive 3=none.
00 10 - 1 drive installed, drive 1=5-1/4, drive 2=none, drive 3=none.
01 31 - 2 drives installed, drive 1=3-1/2, drive 2=5-1/4, drive 3=none.
03 31 - 2 drives installed, drive 1=3-1/2, drive 2=3-1/2, drive 3=none.
03 11 - 2 drives installed, drive 1=5-1/4, drive 2= 3-1/2, drive 3=none.
01 11 - 2 drives installed, drive 1=5-1/4, drive 2=5-1/4, drive 3=none.

As far as I can tell, I can only get a floppy drive working when the value of these two bytes is 00 00.

**Comment by OBattler** [comment]
Any drive set to 5.25" works, but any drive set to 3.5" does not for some reason.

**Comment by OBattler** [comment]
Fixed it! Turns out it needs port 3F7 with the disk change line read out.
