### ISSUE TITLE
Medal of Honor: Allied Assault won't run under 98SE.

### ISSUE THREAD

**Issue by qeeg** [86Box/86Box#1341]
**Describe the bug**
When you install the game, and then attempt to run it, even with disc 1 inserted, it won't see the CD and will exit.

**To Reproduce**
1. Install Windows 98 SE
2. Install Voodoo 3 drivers
3. Install the game
4. Attempt to run the game with disc 1 inserted.

**Expected behavior**
I expected the game to run like it does on real hardware. This game is known to support Voodoo 3 and Windows 98 SE.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - 86Box version: self-compiled from git
 - Build type: self-compiled

**Additional context**
The disc images I'm using can be found here: https://archive.org/details/medalofhonoralliedassaultcd1
My VM has been uploaded here: https://mega.nz/file/Mk0zjKJA#6urV8NWTTSMNCIyh0TpLw_1jnQ9w09ROYAKLbMYC90g

**Comment by qeeg** [comment]
Checked to see if the CPU I was using was the problem and it's not... Reproduced this on a Celeron 466, which exceeds the minimum specified requirements.

**Comment by OBattler** [comment]
The disc is most likely copy-protected, which is not going to work in 86Box, especially if it relies on stuff like Data Position Measurement which we do not emulate at all (yet). As such, I'm closing this with NOTABUG.
