### ISSUE TITLE
S3 864 video bug on Windows 3.1

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1344]
**Describe the bug**
A distorted color and duplicated screen appears at Windows 3.1 startup. I'm using the S3 864 v1.41 drivers. This driver works fine with S3 Trio 32. The screen resolution is 1024x768 256 colors.

**To Reproduce**
1. Boot machine
2. type "win" at DOS prompt

Here is the CFG and NVR files:
[486 GRAVIS.zip](https://github.com/86Box/86Box/files/6237735/486.GRAVIS.zip)

Here is a link to google drive with the disk image (is ~300mb in size).
[https://drive.google.com/file/d/1c7uGSkF7HOhirly4IJFefn-GAzZw4CAz/view?usp=sharing](url)

**Screenshots**
![S3 864 Video Bug](https://user-images.githubusercontent.com/31600563/113170972-720b9280-921d-11eb-9811-d56c1bbfc3bc.png)

**Desktop (please complete the following information):**
 - OS: Win 10 ver 2004
 - 86Box version: 3.0.0.2866
 - Build type: Dev

Additional context:

This hard disk has Stacker 4.1 disk compressor software and QEMM 386 version 8.0 installed. I don't know if it affects this video mode in some way.

**Comment by TC1995** [comment]
Most likely SDAC bpp issue.
