### ISSUE TITLE
Processor and new machine (please add)

### ISSUE THREAD

**Issue by IAW9927** [86Box/86Box#1345]
I want Pentium III 733Mhz with Gateway 2000 Machine and 512MB ram.
Can you search the ROM configuration and it? If you could add it, please send it to me in a package!!!
Thanks!

**Comment by dgurney** [comment]
Unfortunately what you're asking isn't possible, as we don't emulate Pentium IIIs of any sort.

In any case, in future machine requests, please provide exact model numbers and links to ROMs yourself.

**Comment by tiseno100** [comment]
Well Pentium III is not possible atm while we don't know what Gateway 2000 you want.

**Comment by ppgrainbow** [comment]
> 
> 
> I want Pentium III 733Mhz with Gateway 2000 Machine and 512MB ram.
> Can you search the ROM configuration and it? If you could add it, please send it to me in a package!!!
> Thanks!

Pentium III emulation is not possible at this time. No host PC will able to handle 100% emulation at 450 MHz minimum.
