### ISSUE TITLE
Windows 95 doesn't boot any more (Dev build)

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1351]
**Describe the bug**

I experienced some random lock ups on Windows 95 on Build 3.0.0.2874. But on Build 3.0.0.2877 I always get a blue screen error
with a fatal exception.
I checked again on the 2874 build and boots normally except for  the random lock ups. 
**(For some reason, the blue screen error only happens with the DEV build)**

The emulated machine configuration is:

Board: i430VX Shuttle HOT 557, 
RAM:32MB, 
CPU:IDT Winchip/100
Video card: S3 Virge DX and Voodoo 1

Here is the CFG and NVR files: (the hard disk image file is 2gb in size it would be difficult to upload).
[Pentium Audio PCI.zip](https://github.com/86Box/86Box/files/6251994/Pentium.Audio.PCI.zip)

**To Reproduce**
1. Configure and start the machine
2. See the error

**Screenshots**
Here Is the screenshot of the two 86box builds.

![Windows 95 2874 build](https://user-images.githubusercontent.com/31600563/113469363-4e199e00-9423-11eb-9dfd-deae12b129f0.png)

![Windows 95 Bug](https://user-images.githubusercontent.com/31600563/113469366-540f7f00-9423-11eb-8f82-ced36e09b105.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: Build 3.0.0.2877
 - Build type: Dev **(seems to work on regular build)**

**Additional context**
An additional configuration bug: the machine can boot even the HD controller option is set to 'none', I don't remember having changed it from 'internal controller'

**Comment by OBattler** [comment]
Does it work on the Debug build?
