### ISSUE TITLE
XP install fails during GUI stage

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#1353]
**Describe the bug**
Windows XP will encounter a fatal error during the 2nd stage of setup before it detects hardware.

**To Reproduce**
1. Format HD and install XP as you normally would
2. Reboot
3. See error

**Expected behavior**
Setup should proceed properly to the "installing devices" part.

**Screenshots**
![20210404-085754-608](https://user-images.githubusercontent.com/29031916/113504033-24b65a80-9568-11eb-910a-dc02cffbe4f5.png)
![20210404-085808-304](https://user-images.githubusercontent.com/29031916/113504037-2a13a500-9568-11eb-93d5-ab35b5a7101d.png)
![20210404-085830-649](https://user-images.githubusercontent.com/29031916/113504039-2c75ff00-9568-11eb-8647-8401f60b0693.png)

**Desktop (please complete the following information):**
 - OS: Win10 20H2 19042.906
 - 86Box version: 39f98cd063ec907f35cb60cbf4f075e98898b357
 - Build type: custom self-built

**Additional context**
Workaround is to use an older build. This bug happens on both old and new dynarec builds so it's probably not related to #1335.

**Comment by OBattler** [comment]
Which is the last build in which this worked?

**Comment by dhrdlicka** [comment]
> * Build type: custom self-built
Please check if this happens on Jenkins builds.

**Comment by OBattler** [comment]
Alsom, what Service Pack level of XP is this? SP0, SP1, SP2, or SP3?

**Comment by WinFutureX** [comment]
> Which is the last build in which this worked?

I don't really update or keep track of builds that much so I can't figure out exactly which commit broke it, but the oldest build I have that works fine is dated 5th Feb. (probably b377927f9cf9a0160d0586f06a95308d6224298f?) I think I may have had later builds that worked fine too, but I overwrote them with newer ones.

> Please check if this happens on Jenkins builds.

Happens there too. Tested with regular:
<img width="481" alt="86box_7" src="https://user-images.githubusercontent.com/29031916/113516007-88fa0e00-95aa-11eb-887a-2e511993309a.PNG">

> Alsom, what Service Pack level of XP is this? SP0, SP1, SP2, or SP3?

SP0 VLK, grabbed off the BA FTP, verified matching SHA-1

**Comment by OBattler** [comment]
That would correspond to this Jenkins build: https://ci.86box.net/job/86Box/2797/ . It's going to be fun bisecting to find what exactly broke it.

**Comment by OBattler** [comment]
Could you upload 86box.cfg and the nvr folder please? So I can attempt to bisect this. I do have a suspicion that it was build 2842 that introduced this.

**Comment by WinFutureX** [comment]
VM files:
[winxp_v2.zip](https://github.com/86Box/86Box/files/6255146/winxp_v2.zip)

**Comment by OBattler** [comment]
Thanks!

Anyway, I have determined that it's build 2842 that broke it. It works fine in 2841, but breaks in 2842.

**Comment by OBattler** [comment]
It appears to work fine on my local build, are you sure you still have the problem on the latest Jenkins build?

**Comment by OBattler** [comment]
It appears to work fine on build 2883 for me, so you may have to repeat the installation process from the beginning because it must have permanently broken something when it showed that error.

**Comment by dgurney** [comment]
This bug seems to be triggered randomly. I tried regular build 2883, and at first it got to the installing devices stage without errors, but when I interrupted it, replaced the disk image with a copy that I made before it booted to the GUI phase, and restarted 86box, it errored out. I repeated the replacement several times, and after a couple of tries it didn't error out again.

**Comment by OBattler** [comment]
Then the bug could have already been present in build 2797 and we were both simply lucky. For all we know of, this could be a very old bug.

**Comment by WinFutureX** [comment]
Used a different board this time, bug doesn't happen after reboot. A-Trend ATC7020BXII, Cyrix 3, interpreter mode. Could be a chipset problem.
<img width="481" alt="86box_10" src="https://user-images.githubusercontent.com/29031916/113552262-7c1bff80-9628-11eb-8550-b2903bb9b4e1.PNG">

**Comment by OBattler** [comment]
The northbridge is the same (Intel 440BX), so this would indicate a southbridge problem, as this has a SMSC Victory-66 southbridge, while the other machine has an Intel PIIX4E.

**Comment by OBattler** [comment]
But, did you try this repeatedly? Because as we know, the bug is intermittent, so you might have had yet another false negative.

**Comment by WinFutureX** [comment]
Ok, I went and did some testing and I believe that it's not a chipset problem.

> the bug is intermittent

You're probably right.

**Results (all with dynarec on, build is custom 5ebb6caf3f1736941872d417b65fe5c6a225a0e0 with debug):**
Aewin WCF-681 (Apollo Pro 133):
| CPU | Tested | Failed | Notes |
| --- | --- | --- | --- |
| Celeron 300A | 5 | 5 | |
| Celeron 233 | 5 | 5 | |
| Celeron 133 | 5 | 0 | |
| Celeron 66 | 5 | 0 | |
| Cyrix 3 300 | 5 | 2 | |
| Cyrix 3 233 | 5 | 1 | |
| Cyrix 3 133 | 5 | 0 | |
| Cyrix 3 66 | 5 | 0 | |

Supermicro S370SLM (440LX):
| CPU | Tested | Failed | Notes |
| --- | --- | --- | --- |
| Celeron 300A | 5 | 4 | |
| Celeron 233 | 5 | 5 | |
| Celeron 133 | 5 | 1 | |
| Celeron 66 | 5 | 0 | |
| Cyrix 3 300 | 5 | 0 | Way too slow (40-50% speed) |
| Cyrix 3 233 |  |  | Not tested |
| Cyrix 3 133 |  |  | Ditto |
| Cyrix 3 66 |  |  | Ditto |

I also tried it with the ATC7020BXII starting with the Celeron 300A, but the install completely broke on the 4th try (the first 3 tries all failed) and crashed the emulator, even after restarting several times. I think it's dead for good.

My new hypothesis is that this is a CPU timing-related bug, and the faster the CPU speed, the more likely the bug will trigger.

**Comment by OBattler** [comment]
What is the maximum CPU you can run at 100%? I'm starting to believe there's some timing breakdown when the emulator goes sufficiently below 100%.

**Comment by OBattler** [comment]
I just realized... we have a very similar bug with floppies in Windows 3.1x, which is also intermittent... sometmes, but not always, when accessing a floppy in Windows 3.1x, it's going to time out and error.
However, that error doesn't happen on interpreter, but only on both recompilers. I do notice that this seems to occur less on the interpreter than on the recompiler, so the same might be true for the other error.
The other error was introduced when the new timer code came about. Given that all the timings specified in milliseconds remained the same, the big difference is that a part of the code used relative timings back then, which were then converted to absolute timings. If I can find out how to properly convert the relative timings to milliseconds, I might attempt to reintroduce them.

**Comment by WinFutureX** [comment]
> What is the maximum CPU you can run at 100%? I'm starting to believe there's some timing breakdown when the emulator goes sufficiently below 100%.

Celeron 100MHz, but 66MHz is a safer option

**Comment by OBattler** [comment]
Well, there is certainly a correlation there then - the more a CPU goes below 100%, the higher the likelihood of XP erroring. That definitely sounds like a timing breakdown somewhere.

**Comment by OBattler** [comment]
This is now fixed.

**Comment by dgurney** [comment]
It still fails under the new dynarec.

**Comment by dgurney** [comment]
Under the old dynarec too... It just took more tries.

Here is the exact VM (and ISO) I'm using for the testing: https://gurney.dev/files/failingxp.7z

**Comment by dgurney** [comment]
never mind, it seems I mixed up self-built binaries...
