### ISSUE TITLE
S3 Trio64V+ breaks in 9x with release MSVC builds

### ISSUE THREAD

**Issue by dgurney** [86Box/86Box#1358]
![image](https://user-images.githubusercontent.com/12816807/113757783-aef2f000-971b-11eb-94cf-b8e0d80cb409.png)
A picture is worth a 1000 words. NT-based Windows does not appear to be affected, at least not with the inbox driver. Regular Trio64 is also unaffected.

This appears to be an optimization issue, as building the video code without optimization makes the bug "go away". Naturally debug-only builds are also unaffected.

[VM for testing](https://gurney.dev/files/win98test.7z)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10 21343
 - 86Box commit: 5686b189b37cfb10c1c09fde822ffd1a36bcade6
 - Build type: Custom
 - MSVC 19.28.29913

**Comment by OBattler** [comment]
Closing this since we dropped MSVC.

**Comment by dhrdlicka** [comment]
lol
