### ISSUE TITLE
Add the Amstrad 5x86 PC machines

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1360]
**Is your feature request related to a problem? Please describe.**

I have found a site with the system and video ROM bios of Amstrad 5286. I'm not sure if the VGA BIOS is from a Cirrus Logic card, but the Amstrad 5000 series system disk contains an SCATEMM.SYS EMS driver, so I suspect it uses the SCAT 82c235 which is already emulated in 86box

**Edit:** : I was wrong, the VGA chipset seems to be C&T 452, not Cirrus Logic.

Here is the link:
[https://banjosmods.wordpress.com/2021/03/18/amstrad-pc5286-bios-dump/](url)

Here is the link with Amstrad DOS for 5000 series machines
[https://banjosmods.wordpress.com/category/software/](url)

As for the 5086, I'm not sure about the video chip, but uses the 82c100 chipset like the Victor V86 Laptop. So if some day the one of these machines is added will be useful for the other.

Here is the 5086 BIOS (But I suspect the VGA chip is not included)
[pc5086.zip](https://github.com/86Box/86Box/files/6272948/pc5086.zip)

**Describe the solution you'd like**
Consider if it is possible to add the emulation of the Amstrad 5286 machine to 86box.

**Comment by tiseno100** [comment]
I've used an Amstrad PC7286. Well it's the only real 286 I've used. 7286 was Quadtel while 5286 is C&T.

5826 will need it's C&T 452 emulated for sure in order to have proper implementation of that machine. May be considered in the future maybe.

**Comment by Banjo-Oz** [comment]
That's my blog! I actually posted that bios in the vain hope somebody would one day use it to add emulation for that machine to PCem or 86Box! :)

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.

**Comment by OBattler** [comment]
> That's my blog! I actually posted that bios in the vain hope somebody would one day use it to add emulation for that machine to PCem or 86Box! :)

Question - what chipset does the Amstrad PC5286 have?

**Comment by OBattler** [comment]
Ahhh OK, it's SCAT. Then it just needs the graphics card.

**Comment by OBattler** [comment]
The F82C710 I/O controller is already emulated, so that's good.

**Comment by OBattler** [comment]
To expedite things, I may add the PC5086 and PC5286 now without their graphics chips (C&T 451 and 452, respectively), then implement the graphics chips in 6.0.

**Comment by OBattler** [comment]
Unfortunately, the provided dump of the PC5286 BIOS from the above site is bad - it hangs at POST code 03 which is ROM checksum.

**Comment by OBattler** [comment]
It turns out changing the 2C in the end to 2B was enough.
