### ISSUE TITLE
[ISSUE] Can't partition MFM/RLL hard disk using FDISK beyond 1,024 cylinders if type 46 in the CMOS setup is selected

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#1361]
Okay, I managed to create two 152 MB MFM hard disks for use on the emulated Elitegroup ECS 386/32 (80386/20) and using type 46 in the CMOS setup (largest predefined hard disk available on the AMI BIOS):

![20210407-213546-101](https://user-images.githubusercontent.com/32658796/113938641-ba8ff680-97af-11eb-9df7-6f43b3b28006.png)

However, when I'm trying to partition the hard disks using MS-DOS 4.01 FDISK and the BIOS, the utility will only recognise up to 128 MB:

![20210407-213713-994](https://user-images.githubusercontent.com/32658796/113938671-c24f9b00-97af-11eb-92ac-001242a311f8.png)

The hard disk controller that I'm using is the 16-bit ISA Western Digital WD-1003 MFM/RLL controller. According to this page here: https://ibm.retropc.se/manuals/Western%20Digital/wdcontr.txt

All of the Western Digital 1003 MFM/RLL sub-models support up to 2,048 cylinders and 16 heads at 17 sectors per track for MFM and 26 sectors per track for RLL, providing a maximum of 272 MB for a MFM hard drive and up to 416 MB for a RLL hard drive.

Can you look into this issue to see how this can be fixed?

Here's the 86Box.cfg file: https://pastebin.com/B2h6xV8P

Thanks.

**Comment by OBattler** [comment]
Not a bug - the emulator does not, in any way, limit the maximum cylinder number, so this looks like an incompatibility between that particular BIOS setting and DOS (or the BIOS limiting the usable area to 1024 cylindres out of 1224).
