### ISSUE TITLE
Being able to size the screen to a specific resolution

### ISSUE THREAD

**Issue by TheFlyingScotsman** [86Box/86Box#1362]
In PCem you can resize the screen on your emulated machine to a specific resolution, and no matter the resolution of the machine in question, the window will stay at that resolution on the host.  this is perfect for me as I am visual impaired.

I would like this feature to be introduced into 86box, because I am wanting to potentially make the switch from PCem.

I have been able do this myself in the window_coordinates portion of the .cfg file for the emulated machine in question, but I have to take into account the size of the 86box's Window elements like the title bar and the menu bar.   Also it's quite easy to undo the settings once they've been made if you hit the wrong option by accident in the View menu.  I would like to be able to resize the viewing area by way of an option in 86box's GUI.  I enclose screenshots of how it works in [PCem]([url](url))

**Additional context**
Add any other context or screenshots about the
![Screen Shot 21-04-08 at 10 55 PM](https://user-images.githubusercontent.com/31542162/114101897-4f811580-98be-11eb-86f5-d8064bf4f1ef.PNG)
![Screen Shot 21-04-08 at 10 56 PM](https://user-images.githubusercontent.com/31542162/114101904-51e36f80-98be-11eb-865f-722871ed787b.PNG)
![Screen Shot 21-04-08 at 10 57 PM 001](https://user-images.githubusercontent.com/31542162/114101907-527c0600-98be-11eb-8236-e61e09fe093b.PNG)
![Screen Shot 21-04-08 at 10 57 PM 002](https://user-images.githubusercontent.com/31542162/114101910-53149c80-98be-11eb-8f4c-cf48d0559c9b.PNG)
![Screen Shot 21-04-08 at 10 57 PM](https://user-images.githubusercontent.com/31542162/114101916-5445c980-98be-11eb-90ae-13c4cc870044.PNG)
![Screen Shot 21-04-08 at 10 58 PM](https://user-images.githubusercontent.com/31542162/114101918-54de6000-98be-11eb-8a01-533801da275d.PNG)

 feature request here.

**Comment by ppgrainbow** [comment]
I would love to see this feature ported to 86Box! :)

**Comment by qeeg** [comment]
This may not be satisfactory, but you can turn on the Resizable window option to do something similar, albeit without the same precision. :P

**Comment by OBattler** [comment]
I'm going to add this as soon as I'm done with this MMU bug I'm currently fixing (well, probably fixed, I'm testing now to make sure).

**Comment by OBattler** [comment]
I have now begun implementing this. I'm going to continue later today, but it shouldn't take much.
