### ISSUE TITLE
[BUG] Build 2900 (B931E814): Display corruption issues with a expanded memory manager loaded in CONFIG.SYS

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#1366]
I have recently updated to build 2900 of 86Box (B931E814) and I found a lot of adverse changes after the PIT bug was fixed. When a expanded memory manager (such as QEMM386 or EMM386) gets loaded, the display does NOT scroll down and to some extent, display corruption occurs or goes blank.

Here are a couple of screenshots of this issue below.

Fifth Generation Systems Direct Access menu screen display corruption on the emulated Dataexpert SX495 r1.0:

![20210410-055436-786](https://user-images.githubusercontent.com/32658796/114260456-d2bb6d80-9989-11eb-9990-7bacf6b26c6c.png)

No display at all on the emulated Samsung SPC-6000A:
![20210410-061251-570](https://user-images.githubusercontent.com/32658796/114260499-157d4580-998a-11eb-9fb9-9fd8f4b3f94e.png)

Here's the 86Box.cfg configuration file for the Samsung SPC-6000A: https://pastebin.com/4Kuw5Kd1

It appears that it is happening in a lot of 386(DX)-based machines or faster and here is the link to the problematic bug fix:

https://ci.86box.net/job/86Box/2900/

Build 2899 was the last build that didn't have this problem.

Please look into this issue and fix this display corruption bug as soon as possible! Thanks. :)

**Comment by OBattler** [comment]
Yes, the emulator as a whole is completely screwed up right now. I have a tentative fix ready, but I'm testing it first.

**Comment by ppgrainbow** [comment]
> 
> 
> Yes, the emulator as a whole is completely screwed up right now. I have a tentative fix ready, but I'm testing it first.

Thank you for fixing the screwed-up emulator in build 2901 and 2902 respectively! I appreciate it! :)
