### ISSUE TITLE
[FEATURE] Make 86Box display screen non-resizable on specific display resolution

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#1370]
You may have already noticed that 86Box now had the ability to set the size of the emulator screen to a specific resolution: https://github.com/86Box/86Box/issues/1362

In the latest release of PCem, when you set the size of the 86box display screen, the size of the emulation window is non-resizable.

Now, since build 2910, 86Box now has the capability to set the size of the screen to a specific resolution. However, when you set the emulation screen site to a screen resolution, the "Resizable window" gets check marked in the View menu screen:
![1](https://user-images.githubusercontent.com/32658796/114332222-9fe4b700-9afa-11eb-80f5-18d3f21c5d72.png)

If the "Resizable window" option gets unchecked, the size of the main 86Box emulation screen shrinks back to where it was:
![20210412-021119-095](https://user-images.githubusercontent.com/32658796/114332071-51371d00-9afa-11eb-8a35-455656c05c94.png)

My suggest is that if a specific screen resolution size is set, there should be a option to make the emulated display window non-resizable if it's on a fixed resolution size.

Also, an option to reset the size of the emulator display window should be added in the Specific Main Window Dimensions window box.

If you have evidence to back this up, please let me know.

**Comment by OBattler** [comment]
This is now implemented.

**Comment by maximus105** [comment]
When the "Lock to this size" option is activated, the window coordinates are not saved (the window is displaced on the screen the next time 86Box starts), if you completely close 86Box and then start 86Box again. Can this bug be fixed?

**Comment by dhrdlicka** [comment]
That's by design, the window location and size is not saved if the appropriate option is not enabled in the View menu.

**Comment by maximus105** [comment]
Just the opposite. When the "Resizable window" option is activated, and the window size and coordinates are set, for example, "window_coordinates = 1600, 1200, 390, 20", but the "Lock to this size" option is not enabled, then these window size and coordinates are saved when switching to full screen mode and back and when the 86Box is completely closed and the 86Box is restarted. If you enable the "Lock to this size" option, the window size is preserved, but the window coordinates will constantly change when the 86Box is completely closed and the 86Box is restarted
