### ISSUE TITLE
volume control for pc speaker

### ISSUE THREAD

**Issue by honx4amiga** [86Box/86Box#1371]
**Is your feature request related to a problem? Please describe.**
not a problem, just a feature request.

**Describe the solution you'd like**
is it possible to add some kind of volume control for pc speaker sound?

while soundcard volume can be controlled from within emulation (at least for most software/games), pc speaker sound is always 100% loud. would be nice having the ability to reduce pc speaker sound. and for those games which don't support volume control (like xargon for instance) an additional volume control for soundcard (in my case: soundblaster 16) would be nice too!

**Comment by ts-korhonen** [comment]
There exists a gain control (double click speaker icon in status bar). It can increase both sound card and pc speaker volume. Seperate volume controls with both increase and decrease would be nice.

**Comment by OBattler** [comment]
I tried to do separate controls, to no avail - they still affected everything.

**Comment by tiseno100** [comment]
Real speakers(or beepers) didn't have any volume control really. It surely can't be changed that easily.

**Comment by honx4amiga** [comment]
i know that speakers/beepers didn't have any volume control on real hardware. but speekers/beepers also weren't that loud on real hardware. in emulation this is extremely loud especially when using headphones!

**Comment by OBattler** [comment]
If someone can provide me maximum amplitude measurements from a real period speakers (not one of those modern Piezo speakers), I can then change the emulator's values to that. Until then, there's nothing I can do.

**Comment by OBattler** [comment]
Closing this because it's not feasible.
