### ISSUE TITLE
Wavetable sound missing on awe32

### ISSUE THREAD

**Issue by ThatRetroGuy** [86Box/86Box#1374]
Hello there dev-team!
For a while now the AWE32 card has been only outputting OPL in either functions when testing the emulated card thou creatives daginose program or in windows, are there being looked into the issue at hand? 

ThatRetroGuy.

**Comment by OBattler** [comment]
Two people have now reported this issue, you and gogo, and both of you have been asking to bisect it, and so far, neither of you have done it. As such, I have no idea what's causing this issue.

**Comment by ThatRetroGuy** [comment]
I have to admit im not really a coder and is not sure where to start, had plenty of old versions before my old 2TB broke due to wear and tear, it had plenty of old versions of the emulator but as said, drive failed due to frequent use, it was a mechanical type.

**Comment by dhrdlicka** [comment]
Pick a known working build and then work through the range between it and the latest build by picking the middle build of the range. If it works, do the same for the upper half, otherwise do the same for the lower half of the range.

**Comment by OBattler** [comment]
I'm marking this as solved, per request from the person that opened it.
