### ISSUE TITLE
PCjr machine does not seem to work

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#1379]
**Describe the bug**
I have tested booters and none of them load. The bios gives out "Error C" and then goes to black screen when there is no disk.

**To Reproduce**
Configure the machine to pcjr. I would recommend removing the hard drives too.

**Expected behavior**
Booters should load.  When there is no disk, bios should jump to a BASIC screen.
What the BASIC screen looks like:
![Screenshot from 2021-04-15 19-29-28](https://user-images.githubusercontent.com/68984176/114963164-f581d200-9e20-11eb-93e4-2d29469b7b97.png)
Here's some booters to test:
[KQ1PCJR.zip](https://github.com/86Box/86Box/files/6322472/KQ1PCJR.zip)
[Boulder Dash.zip](https://github.com/86Box/86Box/files/6322474/Boulder.Dash.zip)

**Screenshots**
![20210416-021401-983](https://user-images.githubusercontent.com/68984176/114962714-1269d580-9e20-11eb-8166-9d7e409ea9f5.png)

**Desktop (please complete the following information):**
Window 10, tested on regular build 2923

**Additional context**
PCem seems to do PCjr behavior correctly (loads booters, boots to BASIC screen if no disk)

**Comment by OBattler** [comment]
I recommend not using XTIDE with PCjr - I just tested it that way, and King's Quest boots correctly.

**Comment by OBattler** [comment]
BASIC also works fine.

**Comment by OBattler** [comment]
OK, I can reproduce error C now - it happens if I tried to use a 10 MHz or faster 8088. The list should not even have such CPU's - the PCjr is supposed to be limited to 4.77 MHz.

**Comment by Fenix770** [comment]
There is a patch that fix Boulder Dash. Is called FIXSBD, in the vogons site. I didn't test recently but woked on PCEM and DosBox, with 3-voice sound and PCjr graphics.
Link here: https://www.vogons.org/viewtopic.php?f=41&t=12319&p=301104&hilit=boulder%20dash%20patch#p301104
