### ISSUE TITLE
OTI 67/77: Corrupted display on 1024x768 16 color video mode.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1393]
**Describe the bug**
All video modes tested on OTI 67/77 works except the 1024x768 16 color video mode. The 1024x768 256 color mode works fine with OTI-77 with 1mb. 
On both video cards the screen is divided by half when the 1024x768 16 color mode is selected.

**To Reproduce**

1. Start the machine
2. Run Win.com form the DOS prompt or Norton commander
3. Select any of the OAK 1024x768 video mode, (except the 256 color mode which works) 

**Screenshots**

1024x768 16 colors:
![OTI 1024-2](https://user-images.githubusercontent.com/31600563/115964882-e2e05a80-a4fc-11eb-97d0-565d31ba2743.png)

1024x768 256 colors on OTI-77 (works fine)

![OTI 1024](https://user-images.githubusercontent.com/31600563/115964910-fd1a3880-a4fc-11eb-8ccf-d21d00f818f7.png)

Hard disk image and CFG+NVR:
HD:
[Flytech 386-SX HD-25 OTI-77.zip](https://github.com/86Box/86Box/files/6370095/Flytech.386-SX.HD-25.OTI-77.zip)

NVR and CFG:
[OTI-77 Experiment.zip](https://github.com/86Box/86Box/files/6370097/OTI-77.Experiment.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 2004
 - 86Box version: 3.0.0.2942
 - Build type: Dev

**Comment by OBattler** [comment]
This is now fixed.

**Comment by dhrdlicka** [comment]
> I tested the OTI-077 under Windows 3.0 with 1024x768 16 colors teh bug is still present. I think the recent fix works under Win 3.1 but not under Win 3.0.
> 
> This bug happens on the 3 modes: Rea, standard and 386 enhanced.
> 
> The hd and config files are uploaded on the issue #1393
> 
> **Screenshots**
> 
> OTI-077
> 
> ![OTI-077 bug](https://user-images.githubusercontent.com/31600563/116014285-f548ba00-a60a-11eb-99c0-28f62ace32dd.png)
> 
> OTI-067 (using HT18 AMAJ 386 SX with onboard OTI-067)
> 
> ![OTI-67](https://user-images.githubusercontent.com/31600563/116014286-f7ab1400-a60a-11eb-9ff4-209da975ade3.png)

_Posted by @Fenix770 in #1403_

**Comment by OBattler** [comment]
It's #2951 that fixes it, not #2950. Please read the description of the changes on Jenkins.
