### ISSUE TITLE
X & Y axes are confused in the joystick settings window

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1395]
**Describe the bug**
In the joystick settings window, the X & Y axes are confused. When the joystick is selected, opposite the X axis is set by default to Y, and opposite to the Y axis is set by default to X:

![2021-04-03_200412](https://user-images.githubusercontent.com/58270614/115965766-58671d80-a533-11eb-9dce-5a73f35f3636.png)

![Joystick](https://user-images.githubusercontent.com/58270614/115966090-d37d0380-a534-11eb-97e9-a1da662985e3.png)

And each time after turning off and then selecting the joystick, these axes will be confused by default. Because of this, I did not immediately understand why the joystick does not work correctly in my games.

**To Reproduce**
1. In Windows 10, connect a joystick (for example, XBOX 360 Controller)
2. Start 86Box and on the running machine select Input devices > Joystick 1 and select your joystick (for example, XBOX 360 Controller) 
3. See error

**Expected behavior**
The X-axis must correspond by default to the X-axis and the Y-axis must correspond by default to the Y-axis:

![2021-04-03_200440](https://user-images.githubusercontent.com/58270614/115966085-ca8c3200-a534-11eb-9811-5e3fc5282c00.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v1909
 - 86Box v3.00 build 2942
 - Build type: regular

**Comment by OBattler** [comment]
That's a problem with your controller, the emulator just gets the defaults from it. On my end, with vJoy, I get sane defaults. As such, I'm closing this issue.

**Comment by maximus105** [comment]
I have a Dualshock 4 connected via DS4WINDOWS and working as an XBOX 360 Controller on Windows 10.

**Comment by maximus105** [comment]
@OBattler Have you tried deleting 86Box.cfg and then opening the joystick settings window? I mean, if you set the X and Y axes correctly at least once in the 86Box joystick settings window, they will be configured correctly, even the next time you start this machine in the 86Box. And if you delete 86Box.cfg from this configured machine, and then open the joystick settings window the next time this machine is started, then the X and Y axes will be confused by default.

**Comment by maximus105** [comment]
I tested Dualshock 4 in PCem v17. When connecting for the first time, the X and Y axes in the PCem machine are displayed correctly (not confused) by default. I think there is a bug with confused X and Y axes in 86Box. I think the problem was closed prematurely and needs to be reopened.
