### ISSUE TITLE
OTI-067/077 1024x768 bug still present under Windows 3.0

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1403]
**Describe the bug**
I tested the OTI-077 under Windows 3.0 with 1024x768 16 colors teh bug is still present. I think the recent fix works under Win 3.1 but not under Win 3.0. 

This bug happens on the 3 modes: Rea, standard and 386 enhanced.

The hd and config files are uploaded on the issue #1393

**Screenshots**

OTI-077

![OTI-077 bug](https://user-images.githubusercontent.com/31600563/116014285-f548ba00-a60a-11eb-99c0-28f62ace32dd.png)

OTI-067 (using HT18 AMAJ 386 SX with onboard OTI-067)

![OTI-67](https://user-images.githubusercontent.com/31600563/116014286-f7ab1400-a60a-11eb-9ff4-209da975ade3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: 3.0.0.2950
 - Build type: Dev

**Comment by dhrdlicka** [comment]
Just reopen the old issue (or ask for someone to reopen it if you're not the original poster) next time if you believe that a bug still occurs even after a fix.

Duplicate of #1393.
