### ISSUE TITLE
SiS 310 and SiS 401 chipset and UMB memory

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1408]
**Describe the bug**
I tested both SiS 310 386 DX machine and SiS 401 Asus 486 machine. 

Bug:

 UMB_DRVR software:
1. The UMB_DRVR.SYS program freezes when the SiS 310, on CONFIG.SYS file.
2. On the SiS 401 does not freeze but does not recognizes it either.

The Lastbyte Manager:
1. The SiS 310 is not supported on this software.
2. The SiS 401 works perfectly.

DOS 6.0 Memmaker
1. The SiS 310 crash after the first reboot, however after rebooting Memmaker allows to do a "consevartive configuration" which works. (did not test on the SiS 401 with this software)
I'm also using the S3 86c924 video card.
I don't know if some detection scheme, not emulated, may be responsible for this.

**To Reproduce**
1. Start the machine with the Floppy disk on drive A, maybe either the TLB or the disk with UMB_DRVR
2. See the screen

Note:
1. add DEVICE=A:\UMB_DRVR.SYS /C=17 for the SiS 310 and /C=18 for SiS 401 on the CONFIG.SYS file.
2. The Last Byte Manager is configured for SiS 410, the 310 is not listed as supported chipset.

Here is the hard disk, floppy disk, nvr and cfg files and the UMB_DRVR documentation. 
Note I use same hard disk and video card on both machines

HD:
[SiS 386DX.zip](https://github.com/86Box/86Box/files/6381187/SiS.386DX.zip)

Floppy:

[Umb_drvr-dos5.zip](https://github.com/86Box/86Box/files/6381189/Umb_drvr-dos5.zip)

[Lastbyte manager 253.zip](https://github.com/86Box/86Box/files/6381190/Lastbyte.manager.253.zip)

UMB_DRVR documentation:

[UMB_DRVR.txt](https://github.com/86Box/86Box/files/6381203/UMB_DRVR.txt)

NVR and CFG files: 

[SiS 386.zip](https://github.com/86Box/86Box/files/6381218/SiS.386.zip)

[SiS 486 (401).zip](https://github.com/86Box/86Box/files/6381219/SiS.486.401.zip)

**Screenshots**

![UMB_DRVR SiS 310](https://user-images.githubusercontent.com/31600563/116169892-1200f280-a6dc-11eb-9976-9591b7e92828.png)

![UMB_DRVR SiS 410](https://user-images.githubusercontent.com/31600563/116169902-15947980-a6dc-11eb-9bb0-5bc8a934fc41.png)

![TLB](https://user-images.githubusercontent.com/31600563/116169862-044b6d00-a6dc-11eb-9ed0-8e4c216c1161.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: 3.0.0.2955
 - Build type:  Dev

**Comment by OBattler** [comment]
The UMB driver should support SiS 401, so I'm going to have to look at both these chipsets.
