### ISSUE TITLE
Can't boot from floppy on XTIDE Controller on 386 machines

### ISSUE THREAD

**Issue by winexe0** [86Box/86Box#1411]
**Describe the bug**
When I select XTIDE (XT or AT) as an HD controller and boot, I get NO ROM BASIC when booting from floppy.

**To Reproduce**
1. Go to HD Controller and select XTIDE (XT or AT)
2. Enable floppy controller and select bootable floppy image.
3. Make a blank HD image.
4. Start the machine.
5. See error

**Expected behavior**
Machine boots from floppy.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v20H2
 - 86Box version: 86box v3.0 build 2955
 - Build type: regular

**Additional context**
This issue doesn't happen on the [8088] Generic XT clone. Selecting the Internal controller on the 386 machines and configuring it in the BIOS seems to work.

**Comment by OBattler** [comment]
Why would you even ust XTIDE on a 386? Most 386 machines support IDE natively.

**Comment by winexe0** [comment]
The Native IDE on 386s requires setting it in the BIOS. The XTIDE doesn't require any additional setup, It also has a Boot Menu

**Comment by OBattler** [comment]
Yes, but because of the native IDE support, XTIDE isn't really going to work because it's going to conflict with the machine BIOS. XTIDE is designed for XT's and early AT-style 286 which didn't have native IDE support.

**Comment by OBattler** [comment]
Try the new 386 XTIDE that was just added.

**Comment by winexe0** [comment]
I tested the XTIDE BIOS and it boots from floppy without any issues now. I think it's time to close this issue.
