### ISSUE TITLE
Mouse and graphics problems with the Packard Bell 410A

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1412]
**Describe the bug**
I found graphics glitches with the HT 216-32 onboard video chip on the PB 410A and mouse. Mouse works on Serial port at COM 2 only, on build 2964. But PS/2 mouse worked fine and, also the 256 colors modes on build 2945. 
Also on the 2964 build there is a black screen on other hadr disk with diffrenet drivers.
**(I downloaded it from discord)**

Here I upload the HDs, the NVR and CFG fles, and HT-216-32 installation disk:

The first hard disk has Windows 3.1:

[486 Packard Bell type 10 Hard disk.zip](https://github.com/86Box/86Box/files/6395790/486.Packard.Bell.type.10.Hard.disk.zip)

The second has Windoes 3.11 for workgroups installed:
[Packard Bell 410A.zip](https://github.com/86Box/86Box/files/6395791/Packard.Bell.410A.zip)

And the Installation files on a 1.44mb floppy:
[Video 7 HT 216-32.zip](https://github.com/86Box/86Box/files/6395793/Video.7.HT.216-32.zip)

The i420EX with HT-216-32 HD:
[win3.10_v7_ht216_cpl.zip](https://github.com/86Box/86Box/files/6395857/win3.10_v7_ht216_cpl.zip)

CFG and NVR:

[Packard Bell 486 Win 3.1.zip](https://github.com/86Box/86Box/files/6395799/Packard.Bell.486.Win.3.1.zip)

[Packard Bell 486.zip](https://github.com/86Box/86Box/files/6395800/Packard.Bell.486.zip)

The i420EX with SCSI and HT 216-32:

[486 Packard Bell SCI.zip](https://github.com/86Box/86Box/files/6395836/486.Packard.Bell.SCI.zip)

**To Reproduce**
1. Start the machine
2. Type Win
3. See the screen

**Expected behavior**

**Screenshots**

Windows 3.11:

![Packarbell 410 001](https://user-images.githubusercontent.com/31600563/116492457-b1f08480-a872-11eb-8974-71b157fabe15.png)

Windows 3.1:

![Packarbell 410 002](https://user-images.githubusercontent.com/31600563/116492485-c03ea080-a872-11eb-9e80-e61f8527ec80.png)

Lock Up on 2959:
![Packarbell 410 003](https://user-images.githubusercontent.com/31600563/116492531-da787e80-a872-11eb-975a-458889f4a302.png)

Build 2945:

![Packarbell 410 004](https://user-images.githubusercontent.com/31600563/116492561-ebc18b00-a872-11eb-9eb0-b5103e4599f6.png)

Here A screenshot of  th i420EX with a external HT-216-32, SCSI HD and 1024x768 small fonts:
Ii freezes with a black screen. (this hd image I didn't created myself, I downloaded it from discord forum)
![i420EX](https://user-images.githubusercontent.com/31600563/116493070-4effed00-a874-11eb-9381-2ae8f1bcaf68.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: 3.0.0.2964
 - Build type: Dev

**Additional context**
If there is a better drivers I would like to test it, however it seems to be an emulator bug.

**Comment by OBattler** [comment]
The colors have since been fixed.

> Mouse works on Serial port at COM 2 only, on build 2964.

Yes, the BIOS reserves COM1 for a modem of some kind.

> But PS/2 mouse worked fine

It always had problems on the first start of Windows (but not on the second or further starts) when cache is enabled, but none when cache is disabled. It needs a PhoenixKey keyboard controller that is currently not emulated.

As such, I'm closing this issue.
