### ISSUE TITLE
Issues on Olivetti M300 machines

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1418]
**Describe the bug**

1,On the Olivetti M300-8 and M300-15 the internal onboard video cards are not recognized. So I utilize other external VGA cards.

2. On the M300-08, the Setup disk always throws error when attempting to configure the clock/calendar.

3. The setup disk of the M300-08 model has an option to configure the sound volume (so maybe, this model has an onboard sound card?)

4. Also on the M300-08 there are utilities to configure CPU speed (Gofast, Goslow, and Goauto) 

The setup disk works fine, except for time/date option.

**To Reproduce**

On M300-08
1. Start the machine.
2. Insert the setup disk
3. Go to system setup and configure the hardware
4. All except the clock configuration works!

On M300-08/-15
1. Both machines does not work with their internal onboard video chips.

Here is the HD image file and setup disk:

[Olivetti M300-8 762-8-39 type 13.zip](https://github.com/86Box/86Box/files/6410371/Olivetti.M300-8.762-8-39.type.13.zip)

Here is the setup boot disk in both IMD and IMG format:

[M300-08.zip](https://github.com/86Box/86Box/files/6410372/M300-08.zip)
[M300-08-img.zip](https://github.com/86Box/86Box/files/6410373/M300-08-img.zip)

**Screenshots**

![Image 1](https://user-images.githubusercontent.com/31600563/116796270-932c0100-aab1-11eb-818f-91817207f151.png)

![Image 2](https://user-images.githubusercontent.com/31600563/116796276-a2ab4a00-aab1-11eb-997a-2f93a73e7052.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 ver 2004
 - 86Box version: 3.0.0.2980
 - Build type: Dev

**Additional context**
I converted the IMD to IMG format to see if there was a problem with the image format, but i found none.

**Comment by OBattler** [comment]
Closing these since they are getting removed.

**Comment by EngiNerd89** [comment]
I made some tests and discovered the following:
- The SETCLOCK file in the M300-08 reference disk appears to be corrupted. Conversely, the same utility in the M300-15 reference disk works fine also on the M300-08.
- Sound volume simply adjusts the volume of the internal PC speeker. According to the service guide, no on-board sound card option exists for this model.
- GOFAST/GOSLOW utilities enable Turbo mode in the OPTi 82C283 chipset (reg 14h, bit 1). However, turbo mode has not been implemented yet in that chipset.
- I was unable to recreate the bug where the onboard video card doesn't work. In my setup, on-board video works fine and also the CMOS checksum is ok.
- If the time is synchronized with the host machine, a CMOS checksum error is displayed. Such behavior does not occur when time synchronization is disabled.

**Comment by paarati** [comment]
Hi Guys, Not exactly this topic, but I am searching for a setup disk, or "Customer Utilities" disk for my M300-01 (386-SX16) machine, to be able to modify anything in bios, etc. Does anyone have any idea, where to find it? 
Thanks a lot for Your help! :)

**Comment by Fenix770** [comment]
The site [https://olivrea.de/software/](url) have a collection of Olivetti reference disks for different machines.
I don't know if they have the M300-01 model. The site is in German language. You need to fill a contact form and they will
send you the disk via e-mail.

**Comment by EngiNerd89** [comment]
Also, note that if the nvram gets corrupted (e.g., if the CMOS battery is low or has been disconnected) you should enter the built-in setup program once you turn on the PC. There you should be able to set disks, memory etc and eventually start the PC.

Another aspect worth noting is that the M300-01 shares the same custom chipset (NORD/SUD) with the M300-05 and M300-10, so you may have luck with a setup disk from these models. Unfortunately, I have none of them, only BIOS dumps from these two models.
