### ISSUE TITLE
Radius SVGA multiview does not support 720x540 and 1024x768 in 256 colors

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1422]
**Describe the bug**
I tested the HT209 Radius video card on Windows 3.0. The 800x600 at 256 color works, but the 720x540 custom resolution and 1024x768 does not work.

Tested on the Samsung SPC-6000A machine with PC-DOS 4.0. Also, I used two different versions of the drivers. One Which supports about five models of V7 cards including the VRAM-II (I think it is the Radius) And the proper radius drivers.

The radius drivers have also 6-bit and 8-bit modes. The 8-bit mode does not look right.

![386 Extended mode with 8-bit option](https://user-images.githubusercontent.com/31600563/116852508-cf06b980-abca-11eb-852d-16b2b70704cf.png)

Another bug is the when I installed RADIUS.SYS utility which claims to give better performance if copy the video ROM to RAM, in fact inverts the screen an is not readable.

![Config-sys](https://user-images.githubusercontent.com/31600563/116852616-08d7c000-abcb-11eb-95ad-4570392ca271.jpg)

![Inverted text](https://user-images.githubusercontent.com/31600563/116852628-0d03dd80-abcb-11eb-838a-8f5d4835ca08.jpg)

**Additional question:** This video card was launched in 1991, like the OTI-77, so it's possible that this ISA card to support 8-bit transfers modes on 8088/86 machines?. Even the latter OTI-87 claims to be compatible with 8-bit transfer in their ISA version.

**PD**:Also the 800x600 works in real mode, although it would be very slow on an XT based machine.
![Real mode](https://user-images.githubusercontent.com/31600563/116852520-d332d700-abca-11eb-8d19-c75da73c2acd.png)

Here is the Hard disk image and drivers:

[Samsung SPC-6000A 900-15-17 type 9.zip](https://github.com/86Box/86Box/files/6413527/Samsung.SPC-6000A.900-15-17.type.9.zip)

Radius drivers: 
[Radius HT209 Windows Driver.zip](https://github.com/86Box/86Box/files/6413529/Radius.HT209.Windows.Driver.zip)
[Radius HT209 Utilities disk.zip](https://github.com/86Box/86Box/files/6413530/Radius.HT209.Utilities.disk.zip)

Other V7 generic drivers which mentions the VRAM-II in the OEMSETUP.INF

[VIDEO 7 WIN 31.zip](https://github.com/86Box/86Box/files/6413536/VIDEO.7.WIN.31.zip)

**To Reproduce**

1. Start the emlated machine
2. Type "WIN"
3. Change the VGA resulution with the VGA radius utility
4. Restart. Windows will not start if the 1024x768 resulution is specified.

**Desktop (please complete the following information):**
 - OS: Windows 10 ver2004
 - 86Box version: 3.0.02982
 - Build type: Dev

**Comment by OBattler** [comment]
The 8-bit problem is the emulated RAMDAC not supporting 8-bit mode, but only 6-bit mode, I need to look into that.

**Comment by TC1995** [comment]
1024x768 works fine here...

**Comment by Fenix770** [comment]
Did you test it, with same drivers?. I'm using Windows 3.0a and Samsung SPC-6000A (386SX). May be works fine under Win 3.1

**Comment by TC1995** [comment]
for the left screen repeated bug, I know that one, most likely the fonts use the 3.1 version. (Since large fonts employ the use of the 8514*.fon ones which probably expect version 3.10.

**Comment by TC1995** [comment]
> The 8-bit problem is the emulated RAMDAC not supporting 8-bit mode, but only 6-bit mode, I need to look into that.

Well, the radius uses the Sierra 11484, which also has a 8-bit ramdac option through a pin.

**Comment by OBattler** [comment]
> for the left screen repeated bug, I know that one,
It's most likely because of the skew. I have a pending and unfinished reimplementation of that stuff that's actually implemented correctly instead of adding the horizontal retrace skew to the horizontal size, which I'm eventually going to return to.

> Well, the radius uses the Sierra 11484, which also has a 8-bit ramdac option through a pin.
If I find out how the HT209 can set it to 8-bit mode, I'm going to implement that.

**Comment by OBattler** [comment]
The 8-bit mode has been since fix. The other issue should have a new report opened, should it presist after I'm done with the horizontal skew and retrace rework.

**Comment by Fenix770** [comment]
Hard disk image file:
[Samsung SPC-6000A 900-15-17 type 9.zip](https://github.com/86Box/86Box/files/7290166/Samsung.SPC-6000A.900-15-17.type.9.zip)

Config File:
[Samsung SPC-6000A.zip](https://github.com/86Box/86Box/files/7290171/Samsung.SPC-6000A.zip)
