### ISSUE TITLE
Olivetti M21/M24 Amber Mode do not work

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1423]
**Describe the bug**
Selecting "Amber" in the configure box in the Machine Tab do not work. This setting should be in the Display Tab, when selecting "Internal controller" as display card.
More over, moving the windows make the windows size change for no reason. There is some problems with the windows size handling in the lastest build, as it do not always work as expected (size, aspect ratio sometime wrong, size change when you open the Dsic OPen Dialog, etc).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10, Regular build 2982

**Additional context**

**Comment by EngiNerd89** [comment]
I made some tests and found out that this issue occurs with any machine that uses an internal graphics adapter. Basically, the property rgb_type is ignored by the UI rendering routines if the graphics controller is internal. Conversely, if an external graphics adapter (e.g., the Olivetti OGC, identical to the internal one used in M24/M21 machines) is selected, the screen is correctly rendered.
