### ISSUE TITLE
Olivetti PCS-46C does not initialize

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1427]
**Describe the bug**
Right after the start, the machine shows "Timer Error: 1" and keeps rebooting in a loop.

**To Reproduce**
1. Simply start the machine
2. See the error

**Screenshots**
The reboot loop is too fast to capture a screenshot

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 2004
 - 86Box version: 3.0.0.2983
 - Build type: Tested both regular and dev

**Comment by tiseno100** [comment]
This is mostly an experiment replacement for the unfixable PS/2 Model 70 type 4. The error is potentially PIT related. The machine may get dev branched in the upcoming builds.

**Comment by waltje** [comment]
> Panagiotis ***@***.***> wrote: >This is mostly an experiment replacement for the unfixable PS/2 Model 70 type 4.> The error is potentially PIT related. The machine may get dev branched in the upcoming builds.So, one erroring machine is replaced with another one. And this wasnt checked before releasing it?
THIS is how and why you'll never get v3.0 done, Daniel...
--Fred.

**Comment by tiseno100** [comment]
THIS is how and why you'll never get v3.0 done, Daniel... --Fred.

Your message has been fully recieved and appreciated 😘. Freely replace it back by the way.

**Comment by dhrdlicka** [comment]
I must have forgotten when was the last time anyone actually cared about 86Box releases.

With that being said, let's stay on topic, gentlemen.

**Comment by OBattler** [comment]
I have this already fixed on my end by giving the machine its own variant of the 8254 PIT, as it might well be that whatever variant it uses, behaves slightly differently with regards to timings.

**Comment by OBattler** [comment]
Turns out, the fix was improper. The machine has since be removed on my end.
