### ISSUE TITLE
IBM XT286 SETUP do not work

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1434]
**Describe the bug**
I'm trying to setup an IBM XT286 virtual machine. At boot, have a 161-System Options not set.
I tried all kinf of diagnostic disk (http://ibm-pc.org/diagnostic/ibm/ibm.htm). never succeed (message 0152-ERROR SYSTEM BOARD)
Also tried this: http://www.minuszerodegrees.net/5162/setup/5162_basic.htm
Ended with a 1791 Controller failure.

**To Reproduce**
Setup a IBM XT Model 286 with 2048 Kb, AT MFM Controller.
Use AT Diag 1 to 2.07, same thing

**Expected behavior**
A working machine !

**Screenshots**
![image](https://user-images.githubusercontent.com/16312616/117567786-13f48980-b0be-11eb-9c5c-de98bc996b95.png)

**Desktop (please complete the following information):**
Build 2985, Dev build.

**Comment by OBattler** [comment]
Did you disable time sync and then clear the NVR?

**Comment by OBattler** [comment]
I'm closing it for being known behavior we can't fix (the diagnotics diskette not liking the idea of the century register reporting the 21st century), will reopen if I'm told it doesn't work even with time sync disabled.
