### ISSUE TITLE
SCO Unixware 7.1.1 Hangs On Boot

### ISSUE THREAD

**Issue by mforan26** [86Box/86Box#1438]
**Describe the bug**
As the title says when booting from the install cdrom the splash screen appears then it freezes at the screen with the copyright info.

**To Reproduce**
1. Create a configuration with a machine capable of booting from cdrom
2. Insert the 1st disk. Mine is labelled SCO_UnixWare711.iso
3. Start machine from cdrom
4. Machine hangs after spash screen

**Expected behavior**
Machine boots into installer

**Screenshots**
![sco](https://user-images.githubusercontent.com/20382449/117864197-1cd88d00-b26f-11eb-9d85-47aadbee4880.png)

**Desktop** 
 - OS: Windows 10]
 - 86Box version: v3.00 build 2983
 - Build type: Regular

**Comment by win2kgamer** [comment]
I just tested booting the UnixWare 7.1.1 install CD on the CUBX in build 5429 and it no longer freezes:
![Monitor_1_20240127-221148-876](https://github.com/86Box/86Box/assets/47463859/b0c77444-ae86-495d-aa07-e3002816c410)

**Comment by OBattler** [comment]
Then this can be closed now.
