### ISSUE TITLE
Cirrus Logic 5420/5422 graphics issues under Windows 3.0a

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1442]
**Describe the bug**

1. The 16 and 24 bit video modes work, but the mouse does not appear. The 16/256 color video modes work just fine
2. The CL 5420 has 1MB of VRAM as option on 86box, but the drivers do not support the 1024x768 resolution with 256 colors, only 16 colors with this card. The 5422 on the other hand supports the 1024x768 256 colors just fine.

Here is the screenshot, at 1024x768 only the 16 color option is available on the 5420 even with 1mb of RAM, so I suspect this card supports only 512kb.

![CL 5420](https://user-images.githubusercontent.com/31600563/118550339-f022ea80-b732-11eb-8d97-71c2b0adb0fa.png)

The HD and NVR files are the same than issue #1441

Here is the VGA driver disk:

[AVGA3 Drivers (5.25).zip](https://github.com/86Box/86Box/files/6496688/AVGA3.Drivers.5.25.zip)

**To Reproduce**
1. Configure the VM 
2. Boot DOS and type Win at prompt

**Expected behavior**
The  16/24 bits video modes should be fixed and (I'm not sure, but I suspect) the CL 5420 video card should have 512kb of RAM as limit.

**Desktop (please complete the following information):**
 - OS: Win 10 ver 2004
 - 86Box version: 3.0.0.2988
 - Build type: Dev

**Comment by TC1995** [comment]
I think the 5420 is limited to just 512k modes despite 1MB.

**Comment by Fenix770** [comment]
I've found another bug with 800x600 16 bit video mode: 

An unrecoverable error appears when loading Paint, and when changing the card backs in Solitario.

![16 bit bug](https://user-images.githubusercontent.com/31600563/118736472-115e0680-b819-11eb-9658-9215691e46c4.png)

**Comment by TC1995** [comment]
That may be just some incompatibility on the driver end.

**Comment by Fenix770** [comment]
I have not tested Win 3.1 yet.

**Comment by Fenix770** [comment]
It seems to work fine under Win 3.1.

**Comment by Fenix770** [comment]
I found a small glitch. After opening Paint in 800x600 16-bit resolution, with CL-5422, the mouse moves very slowly during several seconds then works normally.

Here is the HD and NVR+CFG files:

[386 SX Cirrus Logic 5420 Win 3.1 HD-203.zip](https://github.com/86Box/86Box/files/6505314/386.SX.Cirrus.Logic.5420.Win.3.1.HD-203.zip)

[386-SX Win 3.1 Cirrus Logic 5422.zip](https://github.com/86Box/86Box/files/6505316/386-SX.Win.3.1.Cirrus.Logic.5422.zip)

**Comment by Fenix770** [comment]
I finally found the reason of the bug in Windows 3.0. The 16/24 bit color drivers are present but works only under Windows 3.1.
This information is inside the the readme fine insidie A:\WIN30 directory of the Windows drivers.
Here is the file and info:
[README.zip](https://github.com/86Box/86Box/files/6505338/README.zip)


CIRRUS LOGIC GD542x Windows 3.0 Drivers
-------------------------

Name                                    Resolution
----------------------------------      -----------------------------
16_1024.DRV		 Multi-Resolution       640x480, 16 Colors
                                        800x600, 16 Colors
                                        1024x768, 16 Colors
256_1024.DRV     Multi-Resolution       640x480, 256 Colors
                                        800x600, 256 Colors
                                        1024x768, 256 Colors

NOTE:
The 64K_800.DRV and 16M_640.DRV are Windows 3.1 only drivers
and do not operate under Windows 3.0.

**Comment by OBattler** [comment]
> I found a small glitch. After opening Paint in 800x600 16-bit resolution, with CL-5422, the mouse moves very slowly during several seconds then works normally.

That could be the driver not having set up the clocks yet.
