### ISSUE TITLE
Emulated machine doesn't restart properly (among other problems)

### ISSUE THREAD

**Issue by randomtechkid** [86Box/86Box#1448]
I run an emulated machine with Windows 98 installed (Intel Celeron 300A) and almost every time I issue a restart (not hard reset), the emulator shuts down instead. It looks like that this only happens with the AOpen AX6BC motherboard.

Also if I choose any CPU faster than 533MHz, 86Box shows only a black screen.

86Box build 2992.

**Comment by OBattler** [comment]
I have the latter issue fixed on my end now, but the former has yet to be debugged.

**Comment by OBattler** [comment]
I think this can be closed now since the fix for the latter has been committed and the former has been fixed by means of RichardG implementing the SMI# traps.
