### ISSUE TITLE
IBM PS/2 55SX issues

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1450]
**Describe the bug**
I found a RAM memory errors on the PS/2 55SX and also a slow screen update under Windows 3.0 with the Tseng ET4000 video card.

Here is HDD, NVR and the setup disk for this machine:

[Win 30 PS2.zip](https://github.com/86Box/86Box/files/6550029/Win.30.PS2.zip)

NVR+CFG

[IBM PS-2 386 Win 3.0.zip](https://github.com/86Box/86Box/files/6549857/IBM.PS-2.386.Win.3.0.zip)

Setup disk images:

[rf5565a.zip](https://github.com/86Box/86Box/files/6549858/rf5565a.zip)

[rf5055pu.zip](https://github.com/86Box/86Box/files/6549859/rf5055pu.zip)

**To Reproduce**
1. Boot the machine 
2. Errors 201 and 164 appears after the RAM memory check
3. Press F1, The machine starts and boots Windows 3.0
4. Start one of the demo apps of the Excel 3.0 Package.

**Screenshots**

Setup errors on the update disk:

![Image 001](https://user-images.githubusercontent.com/31600563/119735261-738abd00-be52-11eb-83e7-457d138f2bc2.png)
![Image 002](https://user-images.githubusercontent.com/31600563/119735281-784f7100-be52-11eb-8a75-5cb7dae69598.png)
![Image 003](https://user-images.githubusercontent.com/31600563/119735285-79809e00-be52-11eb-9642-54154c01b021.png)

Data displayed by the update disk:

![Image 004](https://user-images.githubusercontent.com/31600563/119736045-8ea9fc80-be53-11eb-8b6d-e78a6e8a96b6.png)

![Image 005](https://user-images.githubusercontent.com/31600563/119737316-73d88780-be55-11eb-8c13-fc59d11075bb.png)

![Image 005](https://user-images.githubusercontent.com/31600563/119737323-776c0e80-be55-11eb-9ebd-e2bc30a111a9.png)

![Image 006](https://user-images.githubusercontent.com/31600563/119737332-7aff9580-be55-11eb-9ce2-ddcb975297b9.png)

![Image 007](https://user-images.githubusercontent.com/31600563/119736021-8782ee80-be53-11eb-9461-64da8e52ff98.png)

Slow screen update on the ET4000 video card:
![Slow screen Update](https://user-images.githubusercontent.com/31600563/119737453-b306d880-be55-11eb-8976-a5147a816363.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: ver 3.0.0.2990
 - Build type:  dev

**Comment by OBattler** [comment]
The PS/2 Model 55SX RAM expansion is not currently emulated, so you're limited to planar RAM.
