### ISSUE TITLE
Cirus Logic VLV CL-GD5429/5434 bug

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1452]
**Describe the bug**
VLB Cirus Logic graphic do not work properly under Windows 3.1 with lates drivers.
5429=>Graphical artifacts, see below, in any mode 
5434=>do not work at all for resolution > 800x100 106 colors. Windows resize multitime then guest crash.

Pretty sure it was working a while back, because my main 486 use a GD5434 and the same Windows image, and it was working

**To Reproduce**
486 with VLB, Intel DX4/100, Windows FW3.11, Cirus Logic drivers
**Expected behavior**

**Screenshots**
![20210527-172007-390](https://user-images.githubusercontent.com/16312616/119869586-b1eead80-bf20-11eb-93e5-e35bc326dee2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: [e.g. v2.06 build 2993
 - Build type: [dev]

**Comment by TC1995** [comment]
Well, what kind of drivers are you using? I mean, version of them?

**Comment by jvernet** [comment]
V1.24
[http://vogonsdrivers.com/getfile.php?fileid=864&menustate=9,1](url)

**Comment by TC1995** [comment]
I used v1.25, which honestly does a better job (even in its Win-OS/2 compatible drivers).

**Comment by jvernet** [comment]
Can't find a link for 1.25 version :(.

**Comment by TC1995** [comment]
For a first, the 5429 needs its own drivers, different than the 5434.

**Comment by OBattler** [comment]
Looks like when the pattern is blitted, the text mode stuff is kept in memory for some reason. Which 86Box build broke it?

**Comment by OBattler** [comment]
Closing this because this is 2 years old and needs to be retested because it may not even be present anymore.
