### ISSUE TITLE
Windows 98SE setup hangs early on on 64-bit new dynarec builds

### ISSUE THREAD

**Issue by qeeg** [86Box/86Box#1455]
**Describe the bug**
I attempted to install Windows 98SE, and it hangs on the Copying files needed for Windows Setup part VERY early on in the install. I was using the latest git compiled for 64-bit using the new dynarec.

**To Reproduce**
1. Attempt to install Windows 98 SE
2. See error

**Expected behavior**
Installing correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Insider Preview
 - 86Box version: Latest from Git
 - Build type: Self-compiled 64-bit new dynarec build.

**Comment by OBattler** [comment]
Self-compiled builds are not supported.

**Comment by qeeg** [comment]
There are no 64-bit official builds.
