### ISSUE TITLE
Strange Issues on 486 and Pentium machines

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1457]
**Describe the bug**
I found several strange errors:

1. An error reading the disk 2 of the Aztech sound drivers under Win 3.11. But DOS 6.22 scandisk does not find any error even after a surface test. (I managed to install the sound drivers from CD-ROM, this error happened before the QEMM installation.
2. A protected Error N°6 happens after running QEMM 7.5 manifest Windows application. Manifest for DOS works, but after starting random warm reboots may happen.

Configuration:

Machines: 
486: Rise 418 PCI

Pentium:
Socket 4: AMBRA DP60, Excalibur VLB
Socket 5: AMBRA DP90.

SOUND: AZTECH Whasington

VIDEO; ATI MACH 64 4mb PCI and VLB.

Software: MS-DOS 6.22 and Windows 3.11 for Workgroups

**To Reproduce**
1.Start the VM
2. Type WIN
3. Try to reproduce the errors

Hard disks and NVR files: 

This HD has all drivers installed:
[AMBRA PC60 with Aztech sound and QEMM 7.5.zip](https://github.com/86Box/86Box/files/6565601/AMBRA.PC60.with.Aztech.sound.and.QEMM.7.5.zip)

This HD has only the Video drivers: (IF you want to test the floppy disk bug)

[AMBRA PC60.zip](https://github.com/86Box/86Box/files/6565602/AMBRA.PC60.zip)

NVR and CFG files:
[AMBRA PD60.zip](https://github.com/86Box/86Box/files/6565614/AMBRA.PD60.zip)

Sound Drivers:

Floppy:
[Aztech Floppy disk drivers.zip](https://github.com/86Box/86Box/files/6565604/Aztech.Floppy.disk.drivers.zip)

CD-ROM:
[AZT 2316 Drivers CD-ROM.zip](https://github.com/86Box/86Box/files/6565607/AZT.2316.Drivers.CD-ROM.zip)

**Expected behavior**
These errors should not happen. I don't know what is the cause.

**Screenshots**
Note this is the Windows mouse cursor is on MS-DOS, and is permanent (do not disappear after scrolling) Ex: typing DIR command.
![Error](https://user-images.githubusercontent.com/31600563/120090351-1869fc00-c0d8-11eb-9949-3e6adc8b664a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: 3.0.0.2993
 - Build type: Regular and Dev

*Additional Context*

Installation order:

1. MS-DOS and Windows 3.11
2. Video drivers (ATI Mach 64)
3. Sound Drivers (Aztech Washington)
4. QEMM 7.5

**Comment by ppgrainbow** [comment]
Do you have any idea which build of 86Box caused this and can I have a look at your 86Box.cfg file?

**Comment by Fenix770** [comment]
I have no idea. I created the VM machines recently. But the Dev version contains more errors. 

1. QEMM 7.5 setup utility works on regular version.
2. The warm reboot on DOS manifest happens only on Dev version.
3. But the Manifest for windows, generate the Protection error N° 6 on both builds.

**Comment by ppgrainbow** [comment]
I can assume that the dev relesae builds of 86Box has some bugs with the new dynarec that might need to be worked out.

Is dynarec enabled on the dev release that you're trying on?

**Comment by Fenix770** [comment]
I checked again with The Rise 486 DX/2 50 Mhz. Works just fine with dynamic recompiler disabled.

On Pentium machines it can be disabled.
![Quarterdec Manifest 486 without dynamic recompiler ](https://user-images.githubusercontent.com/31600563/120120682-46e9e480-c175-11eb-9fd0-2a0cdb5b24c0.png)

**Comment by ppgrainbow** [comment]
That's weird. I'm wondering if there is anything wrong with the dynamic compiler on certain emulated late 486 and Pentium machines.

**Comment by OBattler** [comment]
> An error reading the disk 2 of the Aztech sound drivers under Win 3.11. But DOS 6.22 scandisk does not find any error even after a surface test. (I managed to install the sound drivers from CD-ROM, this error happened before the QEMM installation.

This is a known problem - on some machines, when using the dynamic recompiler, floppy reads will randonly time out inside Windows 3.x or 9x. I've looked into this twice now, and it seems to me like there's an IRQ loss due to the unfortunate combination of IRQ's only being processed at the end of a block and the timeout occurring within the block. I'm not sure how to fix this.

As for that protection error #06 - that's an illegal instruction error, what CPU does this occur on?

**Comment by Fenix770** [comment]
The nvr, cfg and hd image is in the beginning of this thread.

**Comment by Fenix770** [comment]
I tested the Asus SiS 85C50x ASUS PCI with Pentium 60. While may have random errors reading floppy disks, the Protection error N° 6 does not appear with this machine when loading QEMM Manifest and works just fine with it, while on AMBRA DP60 the bug is still present, so I think it's not only a recompile error but a chipset error as well, since both machines has different chipsets.

**Comment by OBattler** [comment]
Who knows what the Ambra BIOS is doing there. And the emulator's own
illegal instruction log line would help. Start 86Box with logging
redirected to a file.

Il Lun 21 Giu 2021, 20:43 Fenix770 ***@***.***> ha scritto:

**Comment by OBattler** [comment]
Closing because it's being tracked in #4482 .

**Comment by OBattler** [comment]
It appears such protection errors can also happen on real hardware: https://www.vogons.org/viewtopic.php?t=66498 . So I'm going to conclude QEMM is just not compatible with some BIOS'es.
