### ISSUE TITLE
Cirrus Logic 5422 16-bit video mode bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1461]
**Describe the bug**
On the Lastest commint 3.0.0.2996 the emulation of the 800x600 16bit video mode is broken on Windows 3.1. But works just fine on the build 3.0.0.2993.

The hard disk image is on the closed issue #1442.

**To Reproduce**
1. Download the Windows 3.1 HD image and nvr/cfg files from closed commit #1442. (Not the Win 3.0 image)
2. Start the VM
3. Type Win 
4. Configure the screen resolution to 800x600 65.536 colors

**Screenshots**
This is the screen on the 3.0.0.2996 commit:
![Cirrus bug](https://user-images.githubusercontent.com/31600563/120124504-11e88c80-c18b-11eb-870b-f2aff9fc4c13.png)

This is the screen on the 3.0.0.2993 commit:

![Cirrus Logic 5420 on 2993 commit](https://user-images.githubusercontent.com/31600563/120124517-1c0a8b00-c18b-11eb-88d0-18bea9b31e34.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 ver 2004
 - 86Box version: 3.0.0.2996
 - Build type: Dev

**Comment by TC1995** [comment]
should be fixed in the next commit in the queue.

**Comment by OBattler** [comment]
I confirm that this is now fixed.
