### ISSUE TITLE
Some Phoenix BIOS boards fail to boot DOS/Win9x after creating a partition on large disks

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#1465]
**Describe the bug**
DOS will refuse to boot on some Phoenix boards after creating a partition and rebooting. During startup, the HDD activity light will come on for a split second and then go away, while the system freezes indefinitely on a blinking cursor screen.

**To Reproduce**
1. Create large HDD image (e.g. CHS 8320/16/63)
2. Insert DOS/Win9x boot disk
3. Start fdisk
4. Create normal DOS partition, reboot

**Expected behavior**
DOS should continue to boot as normal instead of freezing.

**Screenshots**
<img width="541" alt="86box_11" src="https://user-images.githubusercontent.com/29031916/120511333-e66cd880-c3fc-11eb-8ea9-ef16ee962b00.PNG">
<img width="541" alt="86box_12" src="https://user-images.githubusercontent.com/29031916/120511344-e8cf3280-c3fc-11eb-8b60-ed929f75f0a9.PNG">

**Desktop (please complete the following information):**
 - OS: Win10 21H1 19043.985
 - 86Box version: 2a023aaf04cbd1d94a17295a1d7fbd3752d4c80b
 - Build type: Custom dev optimized

**Additional context**
DOS boots fine if the disks have 1024 cylinders or less (<= 504MB).

**Comment by OBattler** [comment]
BIOS'es from that period don't always support hard disk images that big. At least the Intel Premiere/PCI II hangs if given a hard disk that supports LBA, so this might be the case here as well.

**Comment by WinFutureX** [comment]
I should also note that NT4 works fine on these boards.
