### ISSUE TITLE
SPEA Mirage V7 video bugs.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1467]
**Describe the bug**
I tested The SPEA Mirage V7 VGA card on Windows 3.1. It has display bugs on 16, 256 and 65.536 (64k) colors which renders it unusable.
The drivers were launched in 1993. Latter drivers launched in 1995 exist, but I think they are for VLB and PCI variants of the card.
I tested with different 386 DX machines and Whit 1mb/2mn of VRAM and I got the same result.

Hard disk and drivers
HD:
[386 DOS 5.0+WIN 31.zip](https://github.com/86Box/86Box/files/6587654/386.DOS.5.0%2BWIN.31.zip)

Floppy disk with SPEA V7 drivers:

[S3 V7 Mirage VGA.zip](https://github.com/86Box/86Box/files/6587658/S3.V7.Mirage.VGA.zip)

**To Reproduce**
1. Start the VM 
2. Type Win at DOS prompt
3. On the SPEA V7 icon the screen resulution can be changed.
4. The are are different video bugs on 16, 256 and 64k color modes.

**Screenshots**

1024x768 at 16 colors:
![SPEA V7 16 colors](https://user-images.githubusercontent.com/31600563/120558203-83b41680-c3d5-11eb-85ee-808c1f1d611b.png)

800x600 64k colors
![SPEA V7 Mirage Bugs 002](https://user-images.githubusercontent.com/31600563/120558310-a5150280-c3d5-11eb-930a-ca2cec96bf7f.png)

1024x768 256 colors:

![SPEA V7 Mirage Bugs 001](https://user-images.githubusercontent.com/31600563/120558369-b9f19600-c3d5-11eb-92d2-7a24cc43915d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: 3.0.0.2997
 - Build type: Dev

**Comment by TC1995** [comment]
Known bugs.

**Comment by TC1995** [comment]
In the meantime, use the standard drivers (S3 2.50-06 for both 801/805 and 928), as a rewrite of the s3 accel and pix trans is planned.

**Comment by TC1995** [comment]
I've solved these bugs now, but the 16bpp one appears to be a video bios bug.

**Comment by Fenix770** [comment]
With the latest commit (build 3142), only 640x480 and 800x600 in 256 colors works, with minor glitches. The most afected video mode is 1024x768. I don't know if it's a driver issue.

![SPEA V7](https://user-images.githubusercontent.com/31600563/131780822-0b6e4cdf-df9a-4463-a839-befc0c0eaa73.png)

![Spea v7 64k](https://user-images.githubusercontent.com/31600563/131780828-e2f3af3e-d15f-4261-aa56-a0a6175634ed.png)

**Comment by OBattler** [comment]
Closing the issue because it's now fixed.
