### ISSUE TITLE
 Add IDT WinChip CPUs and Pentiums without MMX to the Super Socket 7 machines

### ISSUE THREAD

**Issue by winexe0** [86Box/86Box#1471]
**Describe the solution you'd like**
Can you add IDT WinChip CPUs and Pentiums without MMX to the Super Socket 7 machines?

**Describe alternatives you've considered**
PCem already has this.

**Comment by nerd73** [comment]
The real FIC VA-503+ and VA-503A machines lack single-rail support, making them incompatible with classic Pentiums and earlier WinChips. This is not a fault of 86box.

If you desire a Super Socket 7 board compatible with early Pentiums & WinChips, the AOpen AX59 Pro is emulated.

**Comment by winexe0** [comment]
Does the AOpen AX59 Pro support ACPI?

**Comment by nerd73** [comment]
Yes, it does.
