### ISSUE TITLE
OTI-67/77 256 color bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1474]
**Describe the bug**
1. A new bug appeared on the OTI 67 and 77 with the 256 color video modes. I tested the most recent build and the 3.0.0.2996 and latter does not work, but the build 3.0.0.2993 works fine. (Tested 640x480 and 800x600 video modes)
2. I also found a small glitch on the OTI-67 768x1024 4 color video modes: It is red and black instead black and white. (It's older than the 256 color bug, but this resolution only available with the OTI-67 under Win 3.0

EDIT: I think I provided a VM on previous threads (One with OTI-77  #1393)

**To Reproduce**
1. Start the VM
2. Type Win to start Windows at DOS prompt

**Screenshots**
256 color bug:
![OTI-67 256 color bug](https://user-images.githubusercontent.com/31600563/120863847-affc9e00-c561-11eb-80ea-f434e469bbb6.png)

768x1024 4 color, red video mode:

![768x1024-4_color](https://user-images.githubusercontent.com/31600563/120864409-8ee87d00-c562-11eb-82a0-70ca7d20c2d3.png)

**Desktop (please complete the following information):**
 OS: Windows 10 ver 2004
 86Box version: 3.0.0.2966 and latter
 Build type: Dev

**Comment by TC1995** [comment]
the 256 color one is because of the packed chain4 part not being set in the oak.

**Comment by OBattler** [comment]
Are we sure the red video is not intentional? Remember that the 4 colors are not fixed.

**Comment by OBattler** [comment]
Closing this until evidence emerges about the redness of the 4-color mode being a bug.
