### ISSUE TITLE
Keyboard & Mouse bug

### ISSUE THREAD

**Issue by Spicytin** [86Box/86Box#1475]
**Describe the bug**
Keyboard & PS/2 mouse stop working after playing DOS games for a min in Windows 95 or exiting Half-Life after playing Hazard-Course in Windows 98.

**To Reproduce**
1. Play any DOS or few Win9x games:
   * -for a minute
   * -then exit the game (if it doesn't happen for a minute then try this)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - 86Box version: 3.0 3004
 - Build type: Dev

**Additional Context**
Win 95 was run on AP5S SiS machine while Win 98 was run on Tsunami ATX machine.

Edit: Updated to 3006. Pausing HL to Main Menu on 400x300 would stop the input devices too.
Edit 2: Now the dos games problem occurred again on that game. Probably its caused by pressing spacebar many times or moving your mouse. Before that i switched to Stable/Release build.

**Comment by JustinJ553** [comment]
https://youtu.be/NEM_BGg5R7A

**Comment by JustinJ553** [comment]
Actually, rebooting the machine like 3x times would stop the input devices too after booting into OS

**Comment by JustinJ553** [comment]
I realized this has to do with mouse accel. If you move your camera very fast then the bug will be triggered.

**Comment by OBattler** [comment]
Are you using PS/2 mouse?

**Comment by JustinJ553** [comment]
I think you deleted you "are you using PS/2 mouse" because my mail says that. Yes im using PS/2 mouse but on my Packard Bell its Microsoft Serial because of annoying vxd driver before i deleted it.

**Comment by OBattler** [comment]
Yes, I did because I then read your first post again and saw that you already stated you're using a PS/2 mouse.

**Comment by JustinJ553** [comment]
When you wake up the monitor and pc after stand by mode in windows 98 it will stop the input devices too, too...

**Comment by OBattler** [comment]
Does this still happen?

**Comment by JustinJ553** [comment]
yes

**Comment by Spicytin** [comment]
@OBattler can you extend the milestone to 86Box v4.0? The issue also still exists on v3.6 stable build.

**Comment by OBattler** [comment]
Yes, that is known.

PSA: Closing these keyboard PS/2 issues and mentioning them in the issue opened for the keyboard controller rewrite as that's poised to fix them.
