### ISSUE TITLE
Sound Blaster 1.0:  A220 port not recognized by the SB setup disks.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1476]
**Describe the bug**

I tested the SB 1.0 sound card for the first time. I found that the origional setup disk for the card, it inlcudes some utilities to test the sound, but they do not recognize the presence of the SB card.

I found games (Starfire) works perfectly with sound and music with this card. I also added the "SET BLASTER=" variable in the AUTOEXEC.BAT file.

The interesting thing about the setup disk includes a driver for CMS/Game Blaster too. The SB 1.0 and 1.5 supported CMS/ Game Blasters chips. I think they were included in SB 1.0, then Creative Labs made  them optional and CMS support was removed in latter SB models.

Here is the VM and CFG files: (This VM uses a 286 SCAT  82C235 machine with QRAM)

[286 Goldstar HDD type 9.zip](https://github.com/86Box/86Box/files/6602785/286.Goldstar.HDD.type.9.zip)
[CFG 286 Goldastar HDD type 9.zip](https://github.com/86Box/86Box/files/6602788/CFG.286.Goldastar.HDD.type.9.zip)

**To Reproduce**
1. Start the Machine
2. Type CD SB at DOS prompt
3. Try to run the VoxKit software or SB utility TEST-SBC.EXE.

**Screenshots**
![Error 001](https://user-images.githubusercontent.com/31600563/120896971-5300f680-c5fa-11eb-94d8-d6189045a4dc.png)
![Error 002](https://user-images.githubusercontent.com/31600563/120896972-54322380-c5fa-11eb-81c0-5278dfe378fc.png)
![Error 003](https://user-images.githubusercontent.com/31600563/120896973-54322380-c5fa-11eb-977a-adb91d4f8656.png)

additional questions:

1. May be possible to make the SB 1.0 sound card to emulate CMS/ Game Blaster at the same time?
2. May be possible to add a SB 1.5 sound card option with the emulation of the CMS chips.

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 2004
 - 86Box version: 3.0.0.2996
 - Build type: Dev

**Comment by TC1995** [comment]
I think it's normal, as you're assigning both CMS/Game Blaster and SB1.0 the same port (0x220).

**Comment by OBattler** [comment]
It's not a bug but a conflict with the Game Blaster.

> May be possible to make the SB 1.0 sound card to emulate CMS/ Game Blaster at the same time?
I would have to look into why the conflict happens.

> May be possible to add a SB 1.5 sound card option with the emulation of the CMS chips.
I believe the SB 1.5 is already there.

**Comment by Fenix770** [comment]
I tried both SB 1.0 with and without CMS emulation, but that bug is still present.

I think if both devices try to access the same port it would generate a conflict. So the emulator might think two different cards are accessing the same port instead of being an only one SB 1.0 with the CMS chips.
As for the SB 1.5 my question is if an option on sound devices called "SB 1.5 with CMS" (or something like that can be added).

1. I asked this because I believe if the CMS and SB 1.0/1.5 are emulated as different sound cards, both of the might try to access the same A220 port.
2. Unfortunately, I never seen any real SB 1.0/1.5 to see if different ports are needed or not.
