### ISSUE TITLE
Games for Tandy 1000 either too slow in playing music, or are unplayably-broken.

### ISSUE THREAD

**Issue by NightSprinter** [86Box/86Box#1480]
I know the slowness can be alleviated by setting the CPU speed to faster than 7.16MHz, but why is it even on later Tandy 1000 configurations set to faster processor speeds (such as the Tandy 1000SL/2 as fast as 16MHz speed), music plays way too slowly (for example:  the 1988/1989 release of Bubble Bobble, despite non-Tandy 8088 configs with a CMS runs the music at proper speed), or are completely-broken?
![20210609-174530-696](https://user-images.githubusercontent.com/52381903/121403531-ff0f4e00-c928-11eb-9f7d-02f7f2e6e5ff.png)

As you can see in this screenshot, the enemy shouldn't just keep going through the floors.  As a result, we have at least one game unplayable in any Tandy configuration.

**Comment by OBattler** [comment]
There's likely a bug somewhere either in the 808x CPU emulation, the PIT emulation, or both.

**Comment by NightSprinter** [comment]
My guess is PIT?  I had tried the game in a clone 8088 and 8086 config, and the game functioned fine.  It seems to ONLY occur in the Tandy configs

**Comment by qeeg** [comment]
PIT is common between those so, I doubt it would be that in that case...

**Comment by mgtroyas** [comment]
Hello, I noticed that bug on PCem v17, I see it also happens to 86box. It's not only the music, it's all the gameplay: if you run Indianapolis 500 the cronograph runs at half speed than realtime, no matter what CPU clock you assign.
https://www.youtube.com/watch?v=TvyAr-bZjs8

**Comment by OBattler** [comment]
It's either a PIT bug or an 808x bug, I'm going to look at this for v4.0.

**Comment by ualaa1** [comment]
Hi I previously tested Indianapolis 500 and it seems to be running normally on Tandy mode in 86-Box???
https://streamable.com/h8jj7y

But yeah, lots of games have speed issues on 86-Box. Games like Bubble Bobble, Civilization, Champions of the Raj, Ski or Die, 688  Attack Sub and many more have speed issues on Tandy mode

**Comment by mgtroyas** [comment]
Take a look on your video to the "CURR 0:00.00" cronograph on the center of the top of the screen. Each second ingame takes more than three seconds to pass on real time.

Now run this game on a 8088 non-Tandy machine (I used an 8088 AMI clone), the chronograph will run at real time speed indeed.

**Comment by OBattler** [comment]
Closing this because it's going to be traced here: https://github.com/86Box/86Box/issues/4044 .
I'm 100% convinced this is because the current CPU timings are still imprecise and evidently, those games do something that trips the imprecision.
