### ISSUE TITLE
ReactOS 0.2.x VGA issue in 86Box 3.0

### ISSUE THREAD

**Issue by retrospot** [86Box/86Box#1482]
**Describe the bug**
I have tried to install ReactOS 0.2.x in PCI VGA and different GPUs but the problem is, it does have buggy/glitchy screens after booting freeloader. im sure this bug will get valid. i'll post screenshot below.

**To Reproduce**
Unsure. 

**Expected behavior**
Unsure. we expect to fix this coding or suggest me with BIOS/GPU Details.

**Screenshots**
https://i.imgur.com/G9Wv3ds.png < This is what i've tried to set GPU and this is what happends

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 (Over my own cloud computing)
 - 86Box version: v3.0 
 - Build type: 73bdd27b, build 3013

**Additional context**
That's all.
![G9Wv3ds](https://user-images.githubusercontent.com/85839780/121814530-6c232c00-cc26-11eb-94e2-fab03cb03a6f.png)

**Comment by maximus105** [comment]
Have you tried installing newer versions of ReactOS? There is already version 0.4.15:
https://reactos.org/getbuilds/

**Comment by OBattler** [comment]
I think this is Award BIOS' VGA POST screen conflicting with ReactOS' splash screen - I think their loader likely just assumes it's been started from text mode.

**Comment by OBattler** [comment]
Closing this because it's more likely than not a ReactOS bug.
