### ISSUE TITLE
Interlacing artifacts but no interlacing with Phoenix S3 Trio64

### ISSUE THREAD

**Issue by orbitron507** [86Box/86Box#1484]
**Describe the bug**
Any movement of objects makes artifacts of interlacing, but I am using 800x600x32bpp which doesn't do interlacing. The card I'm using is Phoenix S3 Trio64.

**To Reproduce**
1. Install Windows 95
2. Move the mouse or open the start menu

**Expected behavior**
Fluid mouse movement

**Screenshots**
![20210614-143835-768](https://user-images.githubusercontent.com/76504299/121910381-a7376500-cce3-11eb-927a-ff5629dd2851.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 build 19043.1052
 - 86Box version: 3.0 build 3013
 - Build type: Regular

**Comment by TC1995** [comment]
I think it has to do with the dword modes, I have a temporary fix on my local queue.

**Comment by OBattler** [comment]
Since I was told this is now fixed, I can close this.
