### ISSUE TITLE
Ubisoft POD 2.0 hangs the system when run with Voodoo1 on Glide or D3D acceleration

### ISSUE THREAD

**Issue by MrQueeba** [86Box/86Box#1493]
**Describe the bug**
Ubisoft's POD (tested with version 2.0) does not run properly with a Voodoo1 graphics accelerator on either the 3dfx (Glide) or D3D accelerated modes. When attempting to run the game, the system will hang after generating the game window and becomes unresponsive including to Ctrl+Alt+Del. The system requires a hard reset to return to Windows.

**To Reproduce**
1. Install POD 2.0 with any installation size and either the "3dfx Card" or "D3D Card" versions.
2. Run the game.

**Expected behavior**
The game should run as normal. It shows a series of logos, then an FMV intro, and then the main menu in which a game can be created.

**Screenshots**
[https://i.imgur.com/h0p2Kd4.gif](https://i.imgur.com/h0p2Kd4.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1 x64
 - 86Box version: v3.0 a389e298 build 3017
 - Build type: Regular

**Additional context**
The emulated system has an AMD K6 running at 166MHz, 64MB RAM, Shuttle HOT-557 board, S3 ViRGE graphics, Voodoo1 with 4MB of memory, and Windows 95 OSR2 patched with DirectX 8 and IE 5.5. The game functions normally in the MMX only and MMX+ViRGE modes. The latest official 3dfx driver is installed.

**Comment by qeeg** [comment]
Can you please upload your VM files including HDD image so someone can properly debug this?

**Comment by MrQueeba** [comment]
> Can you please upload your VM files including HDD image so someone can properly debug this?

Sure. I've included both the 86Box config and the drive image compressed into a 7Z file.
[Google Drive](https://drive.google.com/file/d/1Qne4XpBi34uL5aO_dL65do5BfwoXoCJD/view?usp=sharing)

**Comment by OBattler** [comment]
Closing this since I received a report that the bug is now fixed.
