### ISSUE TITLE
Add the Cyrix 6x86-P90 CPU

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1503]
**Is your feature request related to a problem? Please describe.**

No. I'd like the addition of the Cyrix 6x86-P90 CPU to the emulated socket 5 motherboards. 

The reason for this is my i5 4210U CPU cannot emulate any 120 mhz CPU at 100% (except for 486 based CPUs)
My limit is Pentium 75 or IDT Winchip 100. On PCem I can emulate Pentium 100, altough it may have less acurate CPU emulation.

Here are some screenshots with the CPU lists:

![Cyrix 6x86 on 86box](https://user-images.githubusercontent.com/31600563/122686829-b76ea900-d1e9-11eb-85b1-0af22c65d79e.png)

![Cyrix 6x86-P90](https://user-images.githubusercontent.com/31600563/122686831-b89fd600-d1e9-11eb-9ae4-56b52a7a422d.png)

**Comment by OBattler** [comment]
Given that thee CPU's are Dev branched because of how poorly emulated they are (they are even missing some features), is there any point in adding yet another such CPU?

**Comment by OBattler** [comment]
As such, I'm closing this issue since the CPU in question is already there, just being blocked by the machines due to the unsupported (by any currently emulated chipset) bus speed.
