### ISSUE TITLE
ATI mach 64 graphics glitch

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1505]
**Describe the bug**

With the ATI Mach64 video card, If an animated icon is open and a new windows is open upon it part of the icon is visible in the new window and it should be not visible. The animated icon is from the Cache86 software.

The HD and CFG files are the same as the uploaded on issue #1457

**Screenshots**

![ATI Mach 64 bug 001](https://user-images.githubusercontent.com/31600563/122812300-e3e8fa80-d2a7-11eb-9043-1d47c960cdea.png)

![ATI Mach 64 bug 002](https://user-images.githubusercontent.com/31600563/122812304-e5b2be00-d2a7-11eb-942d-59c941eb09ff.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 2004
 - 86Box version: 3.0.0.3023
 - Build type: Dev

**Comment by TC1995** [comment]
the Mach64 is gonna need some rework in its acceleration.

**Comment by TC1995** [comment]
Ok so, I don't know if it's a driver bug or something, because I tried earlier drivers and this didn't happen at all.

**Comment by JimboMumbo** [comment]
Ya'll need to double check this: https://gona.mactar.hu/ATI3DCIF/

**Comment by OBattler** [comment]
Closing this as a driver bug, will require evidence of this specific driver functioning correctly on real hardware to be reopened.
