### ISSUE TITLE
ELSA Winner 2000 Pro/X bugs

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1506]
**Describe the bug**
I recently tested the ELSA Winner 2000 Pro/X under Windows 3.11 for workgroups.

1. I found the Video card crash when attempting to start Windows with the drivers if it's VLB version.
2. The PCI version works with S3 868/968 drivers and the S3 968 drivers. But does not with ELSA Winner 2000/x proper drivers,
(Wrong color and size appears)

The machine I use to test it is the Shuttle HOT-543 basen on the Opti 597 chipset.

**To Reproduce**
1. Start the VM
2. Type Win at DOS Prompt
3. See the bug

**Screenshots**
![S3 968 Graphics bug](https://user-images.githubusercontent.com/31600563/122816300-edc12c80-d2ac-11eb-9715-0b026b323bcc.png)

Here is the CFG/NVR files, the HD image file and the 3 different drivers I tested:

NVR and CFG file:
[Pentium-60 + S3 968.zip](https://github.com/86Box/86Box/files/6689016/Pentium-60.%2B.S3.968.zip)

HD image file:
[Peintium-60 S3 968 Win 311.zip](https://github.com/86Box/86Box/files/6689007/Peintium-60.S3.968.Win.311.zip)

Floppy disk with the Win 3.x drivers:

[Elsa Winner Pro 2000.zip](https://github.com/86Box/86Box/files/6689019/Elsa.Winner.Pro.2000.zip)
[S3 868-968 1.5B4 Win3.x.zip](https://github.com/86Box/86Box/files/6689020/S3.868-968.1.5B4.Win3.x.zip)
[S3 968 1.41B5 Win3x.zip](https://github.com/86Box/86Box/files/6689021/S3.968.1.41B5.Win3x.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 2004
 - 86Box version: 3.0.0.3023
 - Build type: Dev

**Comment by TC1995** [comment]
I don't know much of the elsa specific stuff and that graphics bug can be worked around with bus-throttle=yes, I saw some reports of it as a glitch due to bandwidth issues on real hardware, but I have to confirm.
I need to confirm if the 968 graphics engine under win3.1 is meant only for the PCI version or not.

**Comment by OBattler** [comment]
Did VLB Vision 868/968 even exist?

Il Lun 21 Giu 2021, 21:31 TC1995 ***@***.***> ha scritto:

**Comment by TC1995** [comment]
http://www.vgamuseum.info/index.php/cards/item/355-s3-vision968

**Comment by Fenix770** [comment]
Changing the option  "bus-throttle" to "on" seem to solve the problem with the PCI card. but VLB, still does not work.
I don't know, but maybe a different ROM BIOS might be helpful for VLB?.
This card is very strange in a sense it supports 8 MB of video RAM, which is a lot for 1995.
In fact, that size of memory was not common until the 3D video cards were launched around 1998.

**Comment by Fenix770** [comment]
Well works at 1024x768 32k. But with 1280x1024 32k the problem is still present even with the "bus-throttle=on" option

![S3 968 1280](https://user-images.githubusercontent.com/31600563/122839432-67b5dd80-d2ce-11eb-8cad-d7c3174b2331.png)

**Comment by TC1995** [comment]
I used 1.70.04

**Comment by OBattler** [comment]
Is the CRTC linear mapping base address correctly masked?

Il Mar 22 Giu 2021, 06:57 TC1995 ***@***.***> ha scritto:

**Comment by OBattler** [comment]
Closing this because the issue now appears to be fixed.
