### ISSUE TITLE
Compaq Presario 2240 and 4500 bugs

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1515]
**Describe the bug**
I recently recreated a Compaq Presario 2240 machine. I recreated the HD image from the QuickRestore 2240 CD-RM ver 3.05.

BUGs
1. With both machines the internal graphics chipset does not work. Also, I don't know if there external compatible card to configure
2. Both machine have Internal Audio Chipset (There are options the BIOS setup) as well, but there is any "internal Sound" option in the Audio Settings on 86box

The Compaq Presario 2240 boot just fine, but only the Standard VGA mode works since there is a conflict between the S3 VGA and other hardware that I don't know what it does.

**EDIT**: Someone created a HD image of this machine here: (using a S3 Trio64V+) 
Here is the link: https://archive.org/details/compaq-presario-2240

**Screenshots**
![Presario 2240 bug001](https://user-images.githubusercontent.com/31600563/123561941-d9d06b80-d781-11eb-95d9-b13803de2bf3.png)

![Presario 2240 bug002](https://user-images.githubusercontent.com/31600563/123561945-dfc64c80-d781-11eb-8ab4-c384f6531996.png)

**Desktop 
 - OS: Windows 10 ver 2004
 - 86Box version: Build 3.0.0.3028
 - Build type: Dev

**Comment by OBattler** [comment]
I need to see if there's a way to disabl ethat (not emulated) Cyrix GX on-board graphics card.

**Comment by OBattler** [comment]
I believe the internal graphics are now implemented on the feature/machine_and_kb branch so I consider that part solved.
