### ISSUE TITLE
WDXT-150 XTA HD controller bug.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1518]
**Describe the bug**

I tried to create an 30mb XTA-IDE hard disk according to the specs of the XTA WD93038-X (C/H/S 615,6,17) hard disk with WDXT-150 XTA HD controller. The problem is the disk is only recognized as 781/2/17. The HD controller should support this CHS configuration according this site [https://www.vcfed.org/forum/forum/genres/pcs-and-clones/40100-hard-drive-interfaces-xt-ide-vs-at-ide](url).

According to this site [https://forum.system-cfg.com/viewtopic.php?t=8293](url)  the XTA WD93038-X hard disk was included with the Amstrad 3086

Also tried with other XT 8088 machines and I obtained the same result.

**To Reproduce**
1. Create a VM with the Amstrad 3086 and WDXTA-150 controller
2. Start with the DOS floppy disk. (use the DOS 3.30 floppy disk provided in issue #1516 )
3. type "CD HD" and type HDINIT.BAT It will create the partition and copy the files to the HD drive.
4. It creates a 12.9 MB partition 781/2/17. I also tried the DOS FDISK command but has the same result

**Screenshots**
![WDXTA-150 controller](https://user-images.githubusercontent.com/31600563/124205845-7f544980-dab8-11eb-85af-9a11bf1ce986.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 2004
 - 86Box version: 3.0.0.3028
 - Build type: Dev

**Comment by OBattler** [comment]
Closing because it has been solved by low-level formatting the hard disk.
