### ISSUE TITLE
Hiding the bottom bar (useful for recording) in 86box window

### ISSUE THREAD

**Issue by JustinJ553** [86Box/86Box#1530]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add an option to hide the bottom 86box window bar, where the cd icons and others are placed there. Its useful for video recording like OBS. Anyone would have to load disk images through media menu in the top bar instead.

**Describe alternatives you've considered**
If you're using OBS then you can use Crop/Pad filter. Yet you can still see the bar in some cases when the window resizes.

**Additional context**
None.

**Comment by dhrdlicka** [comment]
There is still functionality only accessible from the status bar, plus if a toolbar (#827) gets added then that's going to be affected as well.

**Comment by dhrdlicka** [comment]
On a second glance, #827 actually mentions the ability to hide both the status bar and toolbar. This is a duplicate.
