### ISSUE TITLE
Crash on reset with build 3053

### ISSUE THREAD

**Issue by Dizzy611** [86Box/86Box#1552]
**Describe the bug**
Resetting causes a crash on build 3053. This includes saving settings, and causes settings to not be saved. However, this is not the case when 86Box first starts up with default settings. The settings can successfully be changed the first time. This does not happen on 3052.

I have experienced this when trying to emulate a Pentium Pro as well as a Pentium II.

**To Reproduce**
Steps to reproduce:
1. Configure 86box build 3053
2. Allow machine to run for a bit.
3. Reset, either by hitting "Hard Reset" in the menu or by changing settings.
4. 86box freezes

**Expected behavior**
Expected 86box to reset without freezing, as it does on 3052.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.0 [78c3f675, build 3053]
 - Build type: regular
 
**Additional context**
As mentioned a couple times, this does not happen with the just-previous build, 3052. I suspect this may be due to the thread changes in 3053.

**Comment by OBattler** [comment]
This is now fixed.
