### ISSUE TITLE
Hang/crash on exit in build 3053

### ISSUE THREAD

**Issue by daviunic** [86Box/86Box#1553]
**Describe the bug**
Trying to close the emulator causes the window to hang, at which point you have to kill the process.

**To Reproduce**
1. Start the emulator.
2. Click on Exit menu item or the window close button.
3. Confirm the exit if asked.
4. Observe that the window doesn't actually close, but is instead now entirely unresponsive and the process needs to be killed.

**Expected behavior**
The emulators exits normally like it used to.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 x64
 - 86Box version: build 3053
 - Build type: regular

**Additional context**
Does not happen with build 3052 and earlier, so it's possibly related to the threading changes introduced by 3053.

**Comment by OBattler** [comment]
This is now fixed.
