### ISSUE TITLE
Windows Defender reports latest build binary as malicious

### ISSUE THREAD

**Issue by randomtechkid** [86Box/86Box#1554]
Exactly what the title says.
Windows Defender detects the malware as "Trojan:Script/Wacatac.B!ml".
VirusTotal says there is nothing of concern.

**Comment by JustinJ553** [comment]
false positive.

**Comment by OBattler** [comment]
This is a false positive that I can't do anything about. Here's hoping GCC 11, when it comes out for MinGW/MSYS2, improves that situation.
