### ISSUE TITLE
Add support for GLSLP screen shaders

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1556]
**Is your feature request related to a problem? Please describe.**
No. I'd like to ask if it is possible to add support for GLSLP shaders. 86box support GLSL only at the moment.

I found  some interesting shaders in GLSLP format, it resembles the old amber phosphor screen I had on my XT machine  back in the day as a kid.
This is the monitor-crt-mono.glslp shader:
![Geoworks hercules](https://user-images.githubusercontent.com/31600563/126051786-0aede57a-9f57-4017-809e-80f2fa4f892a.png)
![MDA screen emulation](https://user-images.githubusercontent.com/31600563/126051790-01e0bb98-b007-48d8-8538-6806d52425eb.png)

**Additional context**
Here is the shader folder with GLSLP and GLSL files. (this version is from 2017)
[llshader.zip](https://github.com/86Box/86Box/files/6835448/llshader.zip)

Here is the link with the updated shaders but the "monitor-crt-mono.glslp"  of this version does not works:
https://github.com/leilei-/someshaders

**Comment by OBattler** [comment]
This feature is already labeled as a TODO in the relevant code file, so I'm closing this issue as it's already planned by the author.
