### ISSUE TITLE
Enhance Pcjr composite video mode

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1559]
**Is your feature request related to a problem? Please describe.**

1. I'd like to ask if it's possible to port an IBM PCjr composite patch from DOSBox. It allows to emulate the PCjr colors with composite monitor more accurately.

2. Also, if it's possible to port Hue +/- controls for both CGA and PCjr composite modes. (I'm not sure about Composite on Tandy machine as its present different colors)

Some games may require it to present the colors accurately. For example the 16 color version of Battle Chess can use 16 colors CGA composite mode when typed "chess /comp" at DOS prompt, but the colors need to be changed to present the red and blue pieces correctly.

Here is the patch created for Dosbox, but it was never merged to the regular DOSbox 0.74. The patch was recently merged to DOSbox-X branch.

Here is the patch:
[r4000-PCjrComposite.zip](https://github.com/86Box/86Box/files/6849798/r4000-PCjrComposite.zip)

Here is the source:
[https://www.vogons.org/viewtopic.php?f=41&t=12319&start=680](url)

Here is the link to the code added to DOSBox-X
[https://github.com/joncampbell123/dosbox-x/commit/846d7ed14c5e30e788bfe148db83c1ddf5531926](url)

And an the disk image  "Below the Root" game that supports the PCjr composite
[BELOWROT.zip](https://github.com/86Box/86Box/files/6849854/BELOWROT.zip)

Screenshot of 86box and patched DOSBox svn 4000:
![Brot 86box](https://user-images.githubusercontent.com/31600563/126360598-8788ae95-35f0-4dd8-a55d-2c234a9ea38f.png)
![brot Dosbox svn4000](https://user-images.githubusercontent.com/31600563/126360616-0ffe4c27-7a07-4888-8eba-05e225395c4c.png)

Also here is the link to Mobygames that compares CGA RGB, CGA composite and PCjr Comoposite. (There is not RGB 16 colors support in this game)
[https://www.mobygames.com/game/pc-booter/below-the-root/screenshots](url)

**Comment by OBattler** [comment]
I can do this at all, because the patch is intended for DOSBox's old composite code, not for reenigne's improved code that we use. And so far, noone has written a PCjr handler for reenigne's code, or a Tandy handler for that matter.
