### ISSUE TITLE
86box fails to detect display adaptor

### ISSUE THREAD

**Issue by Olddantrucker** [86Box/86Box#1565]
Doesn't matter which one I choose. Even S3Virge it fails to detect it on Windows 98 SE.  Yet on PCEM the same hard drive I can use it just fine. I was going to give 86 box a go hoping it fixed itself after a year as I tried it earlier with same results but now PCEM support is toast since she freaked out on everybody going nuts.  I'm kinda in a world of hurt now that this avenue is closing fast.

86box looks like it wants to be great but has a LOT of hiccups so far!  Edit: I was going to upload my HDD here to prove it but it's wrong file type.

**Comment by Olddantrucker** [comment]
> What emulated machine are you using?
> 
> In any case, start Windows 98 SE in safe mode, go to device manager, and delete everything you possibly can. Then restart the OS.

The usual Shuttle Hot and it works fine on Optimized Ken so that's what I am using. No issues here using my existing HD and including creating new ones.  :)  Fun fact: Did you know you can boot Windows98 OEM directly from CD by changing the boot order to where it says CDROM on the BIOS?

**Comment by OBattler** [comment]
Yes, some Windows 98 OEM CD's were indeed bootable. That was around the time when CD booting was becoming a thing, though NT 4.0 beat it by 2 years as its CD was always bootable.

Anyway, since the issue appears to have been resolved, I'm closing this.
