### ISSUE TITLE
Interrupt table maybe corrupted around INT 0xE7

### ISSUE THREAD

**Issue by saintfrater** [86Box/86Box#1568]
**Describe the bug**
For some purpose I need to "install" interrupt vector for new interrupt service, I usually use INT above 0xF0 because it's marked as 
"reserved for user interrupt" in Ralf Brown's list.
To be certain to not load twice my code, I do check if target interrupt vector is free (NULL) 
I'll poke the Interrupt table and match return with NULL pointer (which seems to be the normal beavior ?).
In the 86Box, I've been bambozeled to get random pointer back.

But in 86Box (and also in PCEm) I do get garbage addresses....
I'll get the same result by using int 0x21 also.

in my case, this should not be a big deal (I usually don't callback old vector since, it should not be used), other software can be "poke" the interrupt table and check if they are already set or not...

**To Reproduce**
I've writed small C code for demonstration purpose.

```CPP
void main()
{
  int iseg,iofs;
  for (int dintid=0xE0;dintid<=0xFF;dintid++){
    asm {
          mov   ax,dintid
          shl   ax,2
          mov   si,ax
          push  ds
          xor   ax,ax
          mov   ds,ax
          lodsw
          mov   bx,ax
          lodsw
          mov   cx,ax
          pop   ds
          mov   iseg,bx
          mov   iofs,cx }
    printf("INT %02X - %04X:%04X\n",dintid,iseg,iofs);
  }
}
```
When runing this, I get:

```
INT E0 - 0000:0000
INT E1 - 0000:0000
INT E2 - 0000:0000
INT E3 - 0000:0000
INT E4 - 0000:0000
INT E5 - 0000:0000
INT E6 - 0000:0000
INT E7 - 0000:9100
INT E8 - C503:00BE
INT E9 - 9100:E863
INT EA - F000:0202
INT EB - 003C:9100
INT EC - C503:00CE
INT ED - 9100:E863
INT EE - F000:0202
INT EF - 002C:E7C0
INT F0 - F000:0246
[SNIP]
INT FC - EC33:B60A
INT FD - 0C8D:EC0D
INT FE - 87BF:FA3D
INT FF - F000:0006
```

**Expected behavior**

A long and beautifull list of NULL prt
```
INT E0 - 0000:0000
INT E1 - 0000:0000
[SNIP]
INT FD - 0000:0000
INT FE - 0000:0000
INT FF - 0000:0000
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.0 [026bed4e]
 - Build type: [nightly 3082]

**Additional context**
When running the same code on DOSBOX, I'll get a list of NULL prt, I do not have access to real hardware for now, so I cannot test it on real 486...

**Comment by OBattler** [comment]
The interrupt table is filled in by the BIOS, and a lot of them fill unused interrupt vectors with garbage. I actually ran into that with an earlier project of mine where it took me a while to find a good interrupt to use for some custom DOS API I create, because so many of the unused vectors were garbage.
