### ISSUE TITLE
Hercules text mode problems

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1570]
**Describe the bug**
Sorry for bothering you again!. I found yet another bug with the Hercules fonts.
I use another CGA emulator this time. MONO.COM to run QIX in Hercules mode. The game works fine once it starts, but the configuration screen, which is in text mode cannot be seen. 
As a workaround I can configure it with a CGA card and start the with Hercules card run the MONO.COM program and typing
QIX /C /I /K (CGA, Internal speaker, Keyboard), in that way it can skip the text configuration, however to change the default keys the text menu is required.

As additional context: 

1.I tested two different versiones of the game. One of the them have a crack notice and the other do not.
2. Tested on the latest verion of DOSBox-X and the text mode works fine on the Hercules mode after running the MONO.COM utility.  
3. The version of MONO.COM that works with this game has 975 bytes in size and is included in both Qix floppies. 

The floppies:
[Qix original.zip](https://github.com/86Box/86Box/files/6910475/Qix.original.zip)

[qix.zip](https://github.com/86Box/86Box/files/6910476/qix.zip)

**To Reproduce**
1. Start the VM
2. Run MONO.COM from the QIX floppy disk. 
3. Then you can run "QIX /C /I /K" to avoid the text configuration or run "QIX /R" to force the reconfiguration
4. If QIX /R is used or the program detects a different configuration it starts the text mode, but cannot be seen in Hercules mode on 86Box.

**Expected behavior**
The text mode should works as in DOSBox-X

**Screenshots**
Qix on DOSBox-X after running MONO.COM
![QIX](https://user-images.githubusercontent.com/31600563/127724669-41b78133-4120-49f1-8328-87c4be0e5289.png)

The game works in 86Box if the text mode configuration is skipped.
![Qix 1](https://user-images.githubusercontent.com/31600563/127724699-2c9b1d09-438d-4502-b483-cc8dcde31784.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Ver 2004
 - 86Box version: 3.0.0.3089
 - Build type: Dev

**Additional context**

There is other problem with the 8086/88 emulation. Maybe I'll open other report for this. The game music  at first screen is to fast and paradoxically the game is too slow during the game play.
On DOSBox-X the same happens if I select '8086' as CPU, if I select 'auto' it does not happen. 
_Interestingly_ it afecctes both Tandy 1000 video mode on Tandy machines, and Hercules with CGA emulation but **not** the CGA card with an 8086/88 CPU. Also Bubble Bobble game does not work in these XT machines in Tandy and the CGA emulation with Hercules, but works in regular CGA.

To test Bubble Bobble in Hercules modemust first run MONO2.COM which has 1.2KB or BBSIMCGA.COM which is the same program with a different name.

**Comment by OBattler** [comment]
I'm quite sure the Bubble Bobble problem is already reported in another issue. Or better, problems. I might eventually rewrite the 808x emulation again, if I can ever decipher the microcode disassemblies. That should fix things. But not for v3.0 in any case.

I'm going to look into the QIX problem.

**Comment by OBattler** [comment]
Closing this now because it's been discovered to be a problem with some BIOS'es' INT 10h handlers. It appears to work fine on AMI BIOS'es, for example.
