### ISSUE TITLE
Add updated BIOS for XTA-IDE controller and "Super" EGA

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1579]
**Is your feature request related to a problem? Please describe.**
No. 

1.I'd like to ask if a latter BIOS for EGA-CT P82C435 and IDE XTA controller can be added 
2.Make an option to select the BIOS version like the Segate HD controller MFM/RLL has.

Here are the ROM BIOS:

[EGA-CT P82C435.zip](https://github.com/86Box/86Box/files/6925730/EGA-CT.P82C435.zip)

[infowdbios.zip](https://github.com/86Box/86Box/files/6925731/infowdbios.zip)
The infowdbios is dated 06/28/89.

Here is a link wich contains a latter BIOS  version 1.02.01 from 1989. The used in 86Box is 1.00 from 1987
https://www.vogons.org/viewtopic.php?f=46&t=76185&p=887911 (the site contains the file I uploaded)

Thanks!

**Comment by Cacodemon345** [comment]
https://github.com/86Box/roms is the correct place for this issue.

**Comment by OBattler** [comment]
The 1989 WD BIOS I already have, just never remembered to add it as an option.

**Comment by OBattler** [comment]
Closing this since the new XTA-IDE BIOS is now a choice in device configuration. I have also downloaded this SuperEGA BIOS.
