### ISSUE TITLE
In Quake, an image flickers on the screen

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1585]
**Describe the bug**
On video cards [PCI] S3 Trio3D/2X; [PCI] S3 ViRGE/DX (VBE 2.0) in the game Quake image flickers on the screen when setting the screen resolution in the game: 512x384; 640x400; 640x480; 720x480; 720x576; 800x600; 1152x864
This bug appeared in build 3045 and is present until the last build. In build 3044, everything works fine.

**To Reproduce**
1. Create a machine with MS-DOS v6.22 and video card [PCI] S3 Trio3D/2X or [PCI] S3 ViRGE/DX (VBE 2.0)
2. Start Quake
3. Set the screen resolution in the game: 512x384; 640x400; 640x480; 720x480; 720x576; 800x600; 1152x864

**Expected behavior**
The image on the screen in the game Quake should not flicker.

**Screenshots**
![2021-08-04_191207](https://user-images.githubusercontent.com/58270614/128219052-58e6eed5-1ed3-45aa-8450-be55b4c91d05.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H1
 - 86Box v3.00 build 3101
 - Build type: dev

**Comment by Cacodemon345** [comment]
Probably worth looking at the source code of Quake 1 for this bug.

**Comment by maximus105** [comment]
This bug appeared in 86Box build 3045 and is present until the last build. In build 3044, everything works fine.

**Comment by TC1995** [comment]
does it happen on other video cards?

**Comment by maximus105** [comment]
The bug is present only on video cards:
[PCI] S3 Trio3D/2X,
[PCI] S3 Trio64V2/DX,
[PCI] S3 ViRGE/DX (VBE 2.0).
And only at these screen resolutions in the Quake game: 512x384; 640x400; 640x480; 720x480; 720x576; 800x600; 1152x864.
