### ISSUE TITLE
Windows 98 cd rom drive

### ISSUE THREAD

**Issue by Mechanical-sanity** [86Box/86Box#1591]
windows 98 se does not properly recognize the cd rom drive if the harddrive is greater than 8gb

**Comment by ppgrainbow** [comment]
Can I have more information on this bug as well as screenshots of the issue as well as your 86Box.cfg file?

**Comment by Mechanical-sanity** [comment]
> Can I have more information on this bug as well as screenshots of the issue as well as your 86Box.cfg file?

Well, I'm pretty sure this is a problem with windows 98, since the same thing happened to me in dosbox-x. A yellow error icon shows up in device manager next to the cd rom drive controller. There's a github issue thread that I was on, and there is a fix, but it was specific to dosbox

**Comment by OBattler** [comment]
It makes sense, most emulated machines are limited by the BIOS to 8 GB maximum.

**Comment by OBattler** [comment]
OK, I saw the fix. It applies to 86Box as well - go to Settings and change the CD-ROM to 1:0 (= secondary master).

**Comment by Mechanical-sanity** [comment]
> OK, I saw the fix. It applies to 86Box as well - go to Settings and change the CD-ROM to 1:0 (= secondary master).

thanks
