### ISSUE TITLE
Windows 2000 beta crashes when booting from CD-ROM

### ISSUE THREAD

**Issue by BurnedPinguin** [86Box/86Box#1601]
**Describe the bug**
Windows 2000 build 1691 does not enter NT kernel in first phase of setup, BSOD: "STOP: 0x0000006B, PROCESS1_INITIALIZATION_FAILED"

**To Reproduce**
1. Obtain Windows 2000 build 1691 installation medium
2. Boot it
3. After the "Microsoft (R) Windows NT (R) Version 5.0 (Build 1691)" screen, the BSOD appears.

**Expected behavior**
The first stage of setup starts and prompts you that it's a BETA version of the operating system.

**Screenshots**
"Microsoft (R) Windows NT (R) Version 5.0 (Build 1691)" screen:![image](https://user-images.githubusercontent.com/77156464/128896364-ec5437e1-eff8-4b7c-b923-578ebddc88d9.png)
BSOD (right after "Microsoft (R) Windows NT (R) Version 5.0 (Build 1691)" screen):![image](https://user-images.githubusercontent.com/77156464/128896410-6d089d24-d8eb-4235-9d81-922d527f1be4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - 86Box version: 86Box v3.0 build 3103
 - Build type: Dev

**Additional context**
N/A

**Comment by TC1995** [comment]
If you're booting from CD, that's why (maybe).

**Comment by OBattler** [comment]
I'm closing this, because it turns out this was a bad ISO.
