### ISSUE TITLE
Speed-accurate hard disk emulation

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#1602]
It would require to emulate the right read/write speeds of these different hard disks, because the sound must represent the disk activity correctly. I think the proper speed emulation is more important than sound, because when I defrag a disk with NU on XT machines with MFM controllers, the hard disk speed is very close to a RAM drive.
I believe It would be possible only for XTA-IDE and very early IDE hard disks, like in the machine PS/1 2011 and 2121 implemented in IBMulator. 

Here is some comparison of the read/write speed of floppy drives according the 2M format software:
![2M disk speeds](https://user-images.githubusercontent.com/31600563/128944370-8072be93-c583-460e-bd92-8055ee7fa852.png)

_Originally posted by @Fenix770 in https://github.com/86Box/86Box/issues/901#issuecomment-896356994_

**Comment by OBattler** [comment]
Closing this as a duplicate of this previous issue: https://github.com/86Box/86Box/issues/524 .
