### ISSUE TITLE
Voxkit software included in Sound Blaster installation disks does not works.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1605]
**Describe the bug**
The Voxkit software included in SB 1.0 setup disk does not works. It complains about a jumper problem. 
Tested on 286 Goldtstar, SCAT machine with SB 1.0.

Here are the floppy disk:

The Sound Blaster 1.0 disks I use are in The WinwordPC site (I have an internet connection problem right now)
Site: https://winworldpc.com/product/sound-blaster-drivers/sound-blaster-10

The hard disk and CFG files are the same that included in the closed issue #1476

**To Reproduce**
1. Boot the VM
2. Put the SB driver disk N°1
3. Type Voxkit and press enter
4. See the screen error "Wrong interrupt setting or interrupt error"

**Desktop (please complete the following information):**
 - OS: Win 10 21H1
 - 86Box version: 3.0.0.3119
 - Build type: Dev

**Comment by lemondrops** [comment]
This is not a bug in 86Box, but rather a peculiarity of Creative's Voice driver (CT-VOICE.DRV). The CT-VOICE.DRV file supplied on the disk you have linked to is hard-coded to use the IRQ 3 no matter the BLASTER= environment variable settings. Changing the emulated Sound Blaster's IRQ to 3 will resolve this issue.
The alternatives are to use a different version of CT-VOICE.DRV which uses a a different IRQ (for example, one from the [Sound Blaster 1.5's driver disks](http://www.vogonsdrivers.com/getfile.php?fileid=7&menustate=45,38) is hardcoded to the more common IRQ of 7) or to hex-edit the driver file by changing the byte at offset 0x32 to the desired IRQ number out of 3, 5, or 7.
