### ISSUE TITLE
Distributed DMA missing from VIA VT82C586B, 596A, 596B, 686A, 686B and VT8231 southbridges

### ISSUE THREAD

**Issue by Ompronce** [86Box/86Box#1613]
**Is your feature request related to a problem? Please describe.**
The Distributed DMA support is missing from the VIA VT82C586B, VT82C596A, VT82C596B, VT82C686A, VT82C686B and VT8231 southbridges.

**Describe the solution you'd like**
I would like for Distributed DMA emulation added to these chipsets, as the datasheets for these southbridges lists Distributed DMA registers.

**Describe alternatives you've considered**
I have seen that Distributed DMA is emulated on the PIIX4 and PIIX4E southbridges, which could provide the potential for adding it to the aforementioned VIA southbridges.

**Additional context**
Some PCI sound cards (which are not emulated here yet) used Distributed DMA signals (when available) to enable a more compatible emulation of an ISA Sound Blaster card via their emulation drivers without using EMM386.

**Comment by richardg867** [comment]
This is planned. It is worth noting the VT8231 implementation is very incomplete, because a final datasheet is nowhere to be found, just a preliminary one which is mostly copy-pasted from the 686A. An inactive Vogons user claims to have the final datasheet, and that the DDMA registers were removed and repurposed there.

**Comment by Ompronce** [comment]
I see that it has now been implemented, I highly appreciate your efforts and I thank you as well.

I noticed there appears to be references in the code to the VT82C586A device, its differences and common code but the device selector towards the end of the code for this model appears to be missing, leaving only the VT82C586B, 596A, 686A, 686B and VT8231 as selectable southbridges from this series.
