### ISSUE TITLE
MS-DOS boot from HDD is broken in build 3117

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1621]
**Describe the bug**
In build 3117, MS-DOS loading from HDD is broken on some machines: [i430TX] ASUS TX97; [i440FX] ASUS P/I-P65UP5 (C-P6ND); [i440BX] ASUS P3B-F (possibly broken on other machines as well). In build 3116 everything works fine.

**To Reproduce**
1. Create a machine with MS-DOS 6.22 listed above.
2. When loading MS-DOS 6.22 from the HDD, a bug occurs or the HDD is not detected.

**Expected behavior**
Booting MS-DOS 6.22 from the HDD should proceed normally

**Screenshots**
![2021-08-20_190053](https://user-images.githubusercontent.com/58270614/130262671-df8e07f8-3883-4d70-a115-ac1d4f3c5f92.png)
![2021-08-20_185111](https://user-images.githubusercontent.com/58270614/130262693-4a2e6c53-4f0c-4ef8-98e5-cc6f8809aaaf.png)
![2021-08-20_185035](https://user-images.githubusercontent.com/58270614/130262705-8018d529-dd70-4b13-a6e3-15a58d1368cf.png)
![2021-08-20_190916](https://user-images.githubusercontent.com/58270614/130262717-460b6a31-1012-4a95-9695-6aa50ba51d02.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H1
 - 86Box v3.00 build 3117
 - Build type: dev

**Additional context**
HDD parameters are shown in the screenshot

**Comment by zynjec** [comment]
Fixed in 3118 probably, #1619

**Comment by OBattler** [comment]
Yes, it was an IRQ mess-up that is now fixed.
