### ISSUE TITLE
Handle CD Audio de-emphasizing

### ISSUE THREAD

**Issue by NicknineTheEagle** [86Box/86Box#1623]
**Is your feature request related to a problem? Please describe.**
Some old PC games have CD Audio with pre-emphasis flag (saved as FLAGS PRE in .cue file). Such tracks have de-emphasis filter applied by CD drive when played via analog output which is a sort of a low-pass filter that is supposed to restore original frequencies. This is described in detail here: https://wiki.hydrogenaud.io/index.php?title=Pre-emphasis
Some example discs with pre-emphasis flag on Redump:
http://redump.org/disc/2251/
http://redump.org/disc/10332/
http://redump.org/disc/10093/
http://redump.org/disc/1947/
http://redump.org/disc/6015/

**Describe the solution you'd like**
Check for PRE flag in cue sheet when playing a CD Audio track and apply de-emphasis filter in real time if needed.

**Additional context**
It's worth noting that some discs erroneously have pre-emphasis flag set when they shouldn't have it so this feature should be optional.

**Comment by OBattler** [comment]
Is there any C code available for de-emphasizing? I only found C++ code.

**Comment by NicknineTheEagle** [comment]
I don't have any C examples, unfortunately.

**Comment by OBattler** [comment]
OK, I found some C code in the source code of the SoX players, it's not that hard to understand. I'm going to base my code off that.

**Comment by NicknineTheEagle** [comment]
Thanks, this appears to be working. Will you add an option to this off, though? Aside from already mentioned reason, de-emphasis may or may not be performed depending on the drive and analog vs digital mode.
