### ISSUE TITLE
Add emulation of the 3Dfx Velocity 100 graphics card

### ISSUE THREAD

**Issue by Ompronce** [86Box/86Box#1628]
**Is your feature request related to a problem? Please describe.**
Is it possible to add emulation of the 3Dfx Velocity 100 graphics card (which is a successor to the Voodoo Banshee)? It is basically  a Voodoo 3 2000 AGP, except with 8MB of SGRAM memory and only 1 TMU enabled in OpenGL and Glide games. In Direct3D games both TMUs work. It has the same 143/143 clock speed as a Voodoo 3 2000 as well. The second TMU can be reenabled for OpenGL and Glide games by changing a key in the Windows Registry (the core config is 1:0:1:1 compared to 1:0:2:1 on a Voodoo 3 2000). The disabled TMUs are a driver-imposed limitation and the other TMU can be also be reenabled by using standard Voodoo 3 2000 drivers and replacing the INF file with the Velocity 100 specific version.

**Describe the solution you'd like**
I would like for the 3Dfx Velocity 100 graphics card to be emulated. In terms of implementation work, it should be straightforward, as the base card is already emulated. These cards were only available in AGP with SGRAM memory.

**Describe alternatives you've considered**
I haven't seen any alternative implementation as of the time of writing.

**Additional context**
The BIOS ROM from the real card is located here -
http://www.vgamuseum.info/index.php/cpu/item/9-3dfx-velocity-100
http://www.vgamuseum.info/index.php/cpu/item/download/1552_341a1e9c05e03eaab01c2c4fcd728702

The original driver installation CD is located here (useful for testing things like the TMU restriction) -
https://www.vogons.org/viewtopic.php?t=64488
http://hw-museum.cz/data/vga/pic/3dfx_Velocity_100_rev._A1_1.jpg
http://hw-museum.cz/data/vogons/Velocity-100.iso

A Vogons forum thread describing things such as how to bypass the TMU restriction and more is located here -
https://www.vogons.org/viewtopic.php?p=957079

**Comment by OBattler** [comment]
Closing this because it's now done.
