### ISSUE TITLE
User interface rewrite

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#1641]
This is an epic for an impending user interface rewrite to make it portable to Linux and macOS.

#### Pros
* Small size
* Simpler API

#### Cons
* Lack of native styling
* Large change to the interface layout
* We have to draw the UI ourselves => possible performance issues with the current renderer pipeline?

#### Pros
* Native styling on each supported platform
* Allows us to keep the current interface layout

#### Cons
* Large size
* Known issues with hi-dpi support and Linux toolkits

**Comment by OBattler** [comment]
I'm closing this because the debate has reached its conclusion on Discord.

**Comment by dhrdlicka** [comment]
It should stay opened so there is a single place that tracks progress of the rewrite.

**Comment by brunocastello** [comment]
Does this means that we might some day see a release of 86Box for macOS?

**Comment by kurumushi** [comment]
Is there any reason Qt isn't on this list? It does near native styling on windows and works well on all platforms.

**Comment by dhrdlicka** [comment]
> Is there any reason Qt isn't on this list? It does near native styling on windows and works well on all platforms.

@kurumushi The reason is simple, nobody updated the list. In the beginning, we didn't consider Qt as a viable option due to us being confused by the licensing model, however, we ended up going with it in the end.
