### ISSUE TITLE
Miro 10SD bugs.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1655]
**Describe the bug**
Found some minor issues with the Miro 10 SD utility in 386 enhanced mode under Win 3.1 to change from 800x600 to 640x480.
The utility seems to be in german language.
In standard mode a "PROGMAN" error may appear randomly. Sometimes does not appears and works just fine.

Here are the screenshots:
![MIRO 1](https://user-images.githubusercontent.com/31600563/132067830-6e08db87-c05b-49fc-a965-2c30a5d9eb20.png)

![Miro 2](https://user-images.githubusercontent.com/31600563/132067861-e9516289-4efb-48aa-a505-4996553d2120.png)

Here is the Hard disk image:
[486 Miro Video full.zip](https://github.com/86Box/86Box/files/7108625/486.Miro.Video.full.zip)

The CFG file:
[86box.zip](https://github.com/86Box/86Box/files/7108629/86box.zip)

The drivers installed are these TC1995 uploaded on discord.

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 21H1
 - 86Box version: 3.0.0.3154
 - Build type: Dev

**Comment by TC1995** [comment]
Yeah, I saw that already, most likely some recalctiming wrong.

**Comment by TC1995** [comment]
I solved this.
