### ISSUE TITLE
Hercules Graphics card does not works with Siemens PCD-2L 286

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1656]
**Describe the bug**
The Hercules graphics card does not work with Siemens PCD-2L 286. But works fine with other 286 and XTs.
The machine starts, but it is completely black. The MDA works, but has no graphics capabilities.

**To Reproduce**
1. Create a VM machine With Hercules Monochrome and a Siemens PCD-2L 286.
2. Start the VM
3. The machine starts but nothing can be seen.

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 21H1
 - 86Box version: 3.0.03156
 - Build type: Dev

**Comment by maxdlpee** [comment]
I'm able to replicate this as well.
![pic1](https://user-images.githubusercontent.com/77379259/132100359-16330fdc-4133-4107-99bb-b160afdba012.png)
Something worth mentioning is that the computer beeps twice after startup, which given the context, is quite likely to be a video-related POST error message.
