### ISSUE TITLE
Black screen in Shortline game on [PCI] S3 ViRGE/DX (VBE 2.0) video card

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1671]
**Describe the bug**
After launching the Shortline game, a black screen appears on the [PCI] S3 ViRGE/DX (VBE 2.0) graphics card. On other video cards (eg [PCI] S3 ViRGE/DX) the game starts and runs normally.

**To Reproduce**
1. Download Shortline game: https://dl.old-games.su/get/Ek_r8ehKTp7iujDB5JyF5g==,1631169291/pc/shortline/files/Shortline_v1.1.rar
2. Create a machine with MS-DOS v6.22 and [PCI] S3 ViRGE/DX (VBE 2.0) graphics card
3. Launch the Shortline game

**Expected behavior**
The Shortline game should run fine, just like on other graphics cards

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H1
 - 86Box v3.00 build 3167
 - Build Type: dev

**Comment by TC1995** [comment]
Does this happen on previous 86box builds?

**Comment by maximus105** [comment]
Yes. I have not yet been able to find out in which assembly this bug appeared.

**Comment by OBattler** [comment]
I think this is a BIOS incompatibility and as such, nothing we can fix.
