### ISSUE TITLE
Mouse does not Works on Victor V86P

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1678]
**Describe the bug**
The mouse does not work under MS-DOS using either CTMOUSE or Microsoft Mouse 7.04 but works with Geoworks Lite 1.2.
Geoworks has its own internal mouse driver.
I also tried CTMOUSE with Mouse System Mouse but it does not work either, no matter if I use COM 1 or COM 2

Here are two hd images one contains DOS 4.01 and Geoworks the other has the original french DOS 4.01 and Deskmate.

[Victor V86P.zip](https://github.com/86Box/86Box/files/7125778/Victor.V86P.zip)

[Victor V86P disco original.zip](https://github.com/86Box/86Box/files/7125779/Victor.V86P.disco.original.zip)

**To Reproduce**
1. Start the VM 
2. Run MOUSE or CTMOUSE
3. Run FreeDOS EDIT or Dosshell
4. The mouse cursor is present but does not respond

**Desktop (please complete the following information):**
 - OS: Win 10 21H1
 - 86Box version: 3.0.0.3175
 - Build type: Dev

**Comment by jvernet** [comment]
I confirm that no mouse work.
More over, the screen colors are not accurate. it's more "blue"
![image](https://user-images.githubusercontent.com/16312616/132944231-440db9bb-5e57-470b-bb7e-0504b51b9315.png)

**Comment by jvernet** [comment]
Hum. I'm experiencing crash, using EMS drivers or High mem manager, like SXTEMM, QRAM, DOSMAX. Le V86P stop responding, even Hard Reset do nothing.

**Comment by Fenix770** [comment]
Hello!

The color of the screen may be influenced by enviroment light and the angle from which is being seen. Some other laptops like the T1000/T1200 included blue backlight to avoid this. 

I tested EMS memory and works just fine with SXTEMM driver. DOSMAX have 286 code and will not work on 808x based machines.  DOSMAX provides the same fuction as DOS-UP.SYS inluded in QEMM 7.0 and latter.

QRAM and Last byte Manager may work, but provides only 64kb of UMB memory and disables EMS.
Because this chipset supports only one 64kb segment and is used as 64kb page frame to do EMS memory transfers.

Quarterdeck QRAM was intended as for 286 users with a high end card capable of mapping more that 64kb of upper memory.
For example the SCAT 82C235 can map any unused memory area between A000 to F000. So any unused high memory direction can be filled with RAM and used as UMB.

Explanation

Some high end EMS boards also support the "Large Page Frame".In general, if this feature is available it can move any executable code into the 4000-9FFF memory area (the last 384kb) to EMS, and do some basic of multitasking. I say basic because the 286 and andress only 1MB of RAM in real mode but the EMS board can return any stored data to the 4000-9FFF area, so the same area can be utilized several times. Only Windows 2.0x, Windows 3.0 in real mode and Quarterdeck Deskview can use the "Large Page Frame".

The reason to free more conventional RAM is some device drivers cannot use the "large page frame" and have to use the regular non-swappable conventional memory, so the only solution is to reduce the large page frame size to less than 384kb or load most drivers into upper memory.

All of this was a "stop gap" feature because the 80386 was too expensive in 1988, when these cards were launched. The 82C100 chip has the same features of the early EMS boards launched in 1986-87 and do not provide these features.

Screenshots
QTEST utility shows how useful is QRAM on any tested system:

![Victor V86P 002](https://user-images.githubusercontent.com/31600563/132962172-cddbfe48-9f33-4789-a030-5a12d58946d0.png)
![Victor V86P 001](https://user-images.githubusercontent.com/31600563/132962174-ea833be8-92c1-4a5f-a123-ad59d51779dc.png)

And the Last Byte Manager show similar results:
![Victor V86P 003](https://user-images.githubusercontent.com/31600563/132962193-384be3a6-7e9f-4fe9-a502-8fb5ab8f9b0c.png)

**Comment by Fenix770** [comment]
To test EMS memory can use this disk:

OEMSTEST.EXE shows which LIM 4.0 functions are supported. Only one error is found in Fuction 19. But fractions 1 to 16 which are LIM EMS 3.2 are truly supported by this hardware. The LIM 4.0 fractions 17 to 30 are emulated by software. These functions returns information at the program request about if it is supported or not. And also emulates the alternate register sets by software if it is not implemented by hardware. Some software like Norton Utilities NCACHE included in v6 may require an LIM 4.0 driver even if the hardware is only LIM 3.2 capable.

EMSTEST.EXE utility test the LIM 3.2 fuctions and do transfers between disk and EMS memory. This software didn't show any error.
This other utility also sow the information of the loaded software in EMS memory.
[EMS TEST.zip](https://github.com/86Box/86Box/files/7148565/EMS.TEST.zip)

Here is the EMS disk
[EMS TEST.zip](https://github.com/86Box/86Box/files/7148577/EMS.TEST.zip)


![V86P EMS TEST 005](https://user-images.githubusercontent.com/31600563/132962334-6f6ea4cd-2ace-44ed-ab8c-2b5768fef9d4.png)
![V86P EMS TEST 004](https://user-images.githubusercontent.com/31600563/132962336-f0774634-e5c4-4625-961e-d603cf86cebf.png)

**Comment by jvernet** [comment]
EMS seems to work/ But trying to use this with various program (QRAM, DOSMAX, and some other) sometime fails, or the guest is unstable. 
QRAM 2.01 for example let you use EMS memory as 64k upper RAM to load DEVICE and TSR. Some work, some will hang.
I was trying to replicate on my real V86P, but the PSU died yesterday in an awful noise. Emulators are nice as you do not take risk to start a fire...

For example, Turbo C++ 2 hang when activating EMS memory with the IDE (using SXTEMM.SYS as EMS 3.2 driver).

For the screen color, it's really not acurate, regardless angle of vision or light

**Comment by Fenix770** [comment]
QRAM 2.02 works on my end. 
![VICTOR QRAM 202](https://user-images.githubusercontent.com/31600563/132990921-fd616a6e-b659-4e68-a716-fa66782cbaee.png)

Inside the CONFIG.SYS the EMS driver must be the first device driver and QRAM.SYS the second, then run the OPTIMIZE  utility to load high the device drivers.

Check if the IDE hard disk is using the same memory area as the EMS chipset. That may explain the lock up of the system.

Here is the HD image with QRAM. I'm using a 20mb MFM disk and the Xebec controller.
[Victor V86P QRAM.zip](https://github.com/86Box/86Box/files/7149698/Victor.V86P.QRAM.zip)

According the DOSMAX.DOC file a separate version of it with 8088 code exist (DOSM86.EXE). I'never seen that. The regular DOSMAX.EXE uses 286 code.

[DOSMAX.zip](https://github.com/86Box/86Box/files/7149704/DOSMAX.zip)

Here is part of the readme file 
_"(7) Now supporting separate program DOSM86.EXE.  This program is 
        functionally identical to DOSMAX.EXE, but is compiled to work
        on 8086/8088 processors also.  I have learned that there are
        8086/8088 machines which can be configured with High Memory
        using some High Memory Managers, and this variation will make
        it possible for those users to put DOS in a UMB even though
        there is no HMA.  DOSM86.EXE requires 32 more bytes of memory. "_

**Comment by jvernet** [comment]
here is some tools I tried, included a DOSMAX version for 8086.
[V86EMS.zip](https://github.com/86Box/86Box/files/7149763/V86EMS.zip)
Will try your HD image

**Comment by Fenix770** [comment]
I tried the DOSMAX version you gave me. But I only get 550kb of free conventional RAM. Not very impressive. I have the same result loading FATOPEN  and BUFFERS in EMS memory with the /X parameter in CONFIG.SYS.

However, according the QRAM-TEC.TXT file included on the QRAM installation disk, due to DOS 4.0 limitations QRAM will not load buffers into upper memory. 

This is a screenshoot of QRAM+DOSMAX installed:
![V86P QRAM+DOSMAX](https://user-images.githubusercontent.com/31600563/133000960-532cbbd0-a5bb-4a3c-92b4-7569a23bd65b.png)

This oother screenshoot is the other HD (without QRAM and DOSMAX) with FASTOPEN and BUFFERS loaded in EMS.
![V86P with EMS](https://user-images.githubusercontent.com/31600563/133001011-580ac581-8710-4792-8f55-3fd26df87457.png)

Here is the HD image with QRAM+DOSMAX:
[Victor V86P QRAM+DOSMAX.zip](https://github.com/86Box/86Box/files/7150211/Victor.V86P.QRAM%2BDOSMAX.zip)

**Comment by Fenix770** [comment]
Sorry I forgot to load DOSMAX.EXE which is the main device driver. After loading it I got 565kb of free RAM. Is a bit more, but not very impressive since I, got about 616kb with QRAM and DOSMAX on 286 SCAT 82C235 chipset.
But of course DOS 5.0 can load part of its code in HMA on 286 and latter machines (the first 64kb of extended memory) 

![V86P full](https://user-images.githubusercontent.com/31600563/133001302-029c9782-8c41-4159-abc2-79e3b17164d0.png)

![SCAT 286](https://user-images.githubusercontent.com/31600563/133001346-8f900b30-c2c9-4dad-b302-0052a94878d6.png)

Here is the Image file with DOSMAX+QEMM fully configured:
[Victor V86P QRAM+DOSMAX.zip](https://github.com/86Box/86Box/files/7150222/Victor.V86P.QRAM%2BDOSMAX.zip)

**Comment by Fenix770** [comment]
A possible issue with QRAM is after overriding the EMS page frame the EMS page frame is still visible to DOS MEM command.
So I of two possible reason for the machine crash. 

1. DOS 4.0x the only version that allows to load Buffers in EMS memory, if I recall correctly storing Buffers in EMS memory is considered a violation of the LIM EMS spec. 

I read it on QEMM 7.04 readme file that explains that some Win 2.x applications rely on the buffer management of MS-DOS/PC-DOS, since old DR-DOS versions did not have that capability these programs try to use the EMS page frame to store the buffers.

Another example is Geoworks 1.2 Lite. During the installation, disables FASTOPEN and removes the /X from the Buffers inside CONFIG.SYS. 

2. Some old applications may think the EMS page frame is still available and may try to store data there.

**Comment by jvernet** [comment]
You may have the point, as it's not the memory tools themselves that crash, it's some apps, like TC++2, or Norton Information. Canot try on real hardware though for the moment.

What about the mouse problem ?

**Comment by jvernet** [comment]
Mouse is working and I like the color.
Under MSDOS 5, with CTMOUSE and DOSED loaded, I get 587k of conventionnal RAM free with DOSMAX/QRAM wich is not bad.
You're right about EXE that crash: they seems to try to use EMS memory even if not available. EMSTEST know that there is no EMS available, but Turbo C no, for example.

I like the new screen color.

**Comment by jvernet** [comment]
And with a good OpenGL shader, it's near perfect !
![image](https://user-images.githubusercontent.com/16312616/133475962-15f853a2-0518-4537-94a0-8ff3c3b75062.png)
