### ISSUE TITLE
When the "Lock to this size" option is activated, the window coordinates are not saved

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1683]
**Describe the bug**
When the "Lock to this size" option is activated, the window coordinates are not saved (the window is displaced on the screen the next time 86Box starts), if you completely close 86Box and then start 86Box again.
When the "Resizable window" option is activated, and the window size and coordinates are set, for example, "window_coordinates = 1600, 1200, 390, 20", but the "Lock to this size" option is not enabled, then these window size and coordinates are saved when switching to full screen mode and back and when the 86Box is completely closed and the 86Box is restarted. If you enable the "Lock to this size" option, the window size is preserved, but the window coordinates will constantly change when the 86Box is completely closed and the 86Box is restarted. I do not save the coordinates of the window when the "Lock to this size" option is activated (the window is displaced on the screen next time 86Box starts), if I completely close 86Box, and then start 86Box again. Can this bug be fixed?

**To Reproduce**
1. I initially set the "Remember size & position" option and set window_coordinates = 1800, 1350, 390, 20.
2. Then, when the "Lock to this size" option is activated, the line window_fixed_res = 1784x1268 is added to the 86Box.cfg file, but the window is displaced by screen the next time 86Box starts, and the window_coordinates parameter is constantly changing: for example, window_coordinates = 1790, 1340, 249, 23. If the "Lock to this size" option is turned off, then everything is fine (the window size and window coordinates are saved when switching to full screen mode and back and when 86Box is completely closed and 86Box restarted). Can this bug be fixed? That is, so that, when the "Lock to this size" option is activated, the window size and window coordinates are preserved when switching to full-screen mode and back, as well as when 86Box is completely closed and 86Box is restarted.

**Expected behavior**
When the "Lock to this size" option is activated, the window size and window coordinates should be preserved when switching to full-screen mode and back, as well as when 86Box is completely closed and 86Box is restarted.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H1
 - 86Box v3.00 build 3177
 - Build Type: dev

**Comment by OBattler** [comment]
It's not a bug, I never even claimed that option would preserve the coordinates. And if you look at the coordinates, you'll find why the two options don't go well together - the coordinates are top, bottom, left, and right, so they include the size.

**Comment by maximus105** [comment]
Ok, but is it possible to save the window coordinates when this option "Lock to this size" is enabled? This option makes the window borders more compact, and helps to slightly increase the size of the window on the monitor screen without switching to full screen mode. But due to the fact that after restarting 86Box, the coordinates of the window are constantly changing, the window is shifted on the monitor screen, so it is impossible to use this option normally.

**Comment by maximus105** [comment]
The issue has not been fixed. Checked in build 3197. After restarting 86Box, window coordinates are still not saved when the "Snap to this size" option is enabled. The 86Box.cfg file does not have the "window_coordinates =" parameter at all when the "Snap to this size" option is enabled.

**Comment by maximus105** [comment]
Can you reproduce this issue yourself? I checked again on build 3197. The window coordinates are not saved when you close and then start 86Box when the "Lock to this size" option is enabled. The 86Box.cfg file does not have the "window_coordinates =" parameter at all when the "Lock to this size" option is enabled.

**Comment by maximus105** [comment]
Why did you close the issue? The issue has not been fixed and is present in the latest builds of 86Box.

**Comment by maxdlpee** [comment]
> It's not a bug, I never even claimed that option would preserve the coordinates. And if you look at the coordinates, you'll find why the two options don't go well together - the coordinates are top, bottom, left, and right, so they include the size.

I guess that's your reason.

**Comment by OBattler** [comment]
I did add coordinate preservation. I guess it's broken.

**Comment by OBattler** [comment]
> The issue has not been fixed. Checked in build 3197. After restarting 86Box, window coordinates are still not saved when the "Lock to this size" option is enabled. The 86Box.cfg file does not have the "window_coordinates =" parameter at all when the "Lock to this size" option is enabled.

I can not confirm this. I justed tested and the coordinates are preserved.

**Comment by OBattler** [comment]
OK, it turns out that I can in fact confirm this, and I have now fixed it by using MoveWindow instead of SetWindowPos.
