### ISSUE TITLE
Improvments (NEC V30, HD Speed emulation)

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1692]
Some ehancement I would like to have in 86BOX:

1. 80186 emulation (may be for some curious system like the french Goupil G4)
2. NEC V20/V30 émulation
3. A way to slow down Hard Disk emulation. having a MFM hard disk that deliver 925K/s is not relevant for a 8088 system ;). As for disk drive, user may choose "slow or fast" HD émulation

**Comment by OBattler** [comment]
V20/V30 emulation is going to be done in the version after 3.0.

**Comment by roytam1** [comment]
> V20/V30 emulation is going to be done in the version after 3.0

I wonder if this issue is progressed?

I think it will be nice to have a checkbox to replace 8086/8088 CPU with 80186/80188 in 8086/8088 machines.

**Comment by OBattler** [comment]
You can't use an 8018x in 808x machines, the 8018x is a SoC basically, using an entirely different socket.

**Comment by Cacodemon345** [comment]
By the way, HD speed emulation is already implemented, but as of now it doesn't apply to SCSI.

**Comment by OBattler** [comment]
V20/V30 is now done.

**Comment by OBattler** [comment]
> having a MFM hard disk that deliver 925K/s

If you mean 925 kilobytes a second, then yeah, that's a bit on the high side, but if you mean 925 kilobits a second, then that's within the range of a normal MFM hard disk speed, I'd say - a high density floppy transfers at 500 kilobits a second, an extended density (ED) floppy , ie. 2.88 MB, transfers at 1000 kilobits a second.

In any case, I thik that, given that the main request for this (V20/V30) has been done, this can be closed.
