### ISSUE TITLE
Sid & Al's Incredible Toons - Bottom of the screen is repeated at the top of the screen and flickering on some video cards

### ISSUE THREAD

**Issue by Ompronce** [86Box/86Box#1693]
**Describe the bug**
In the game Sid & Al's Incredible Toons, the bottom of the screen is repeated at the top of the screen.

**To Reproduce**
1. Start the game.
2. After starting the game, the bug should become immediately apparent.
3. On some graphics cards the screen will flicker rapidly. After further investigation, I have determined that this is a BIOS issue with some of the cards (Various PCI and ISA graphics cards were tested)

**Expected behavior**
The bottom of the screen should not be repeated at the top of the screen. The flickering which has been previously mentioned is video card BIOS-dependent, and as such cannot be fixed.

**Screenshots**
![20210915-221903-867](https://user-images.githubusercontent.com/88358700/133517422-a5e8846a-5707-4f91-b0c7-84a28b22997d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 version 2004
 - 86Box version: v3.0 [0e2cf677, build 3197]
 - Build type: Regular

**Additional context**
The specifications of the VM are as follows:

Motherboard: ASUS P/I P55T2P4
CPU: Intel Pentium 75MHz
RAM: 8 MB
Graphics: Diamond Stealth 64 DRAM (S3 Trio64) 1 MB (Flickering issue is apparent on this card)
HDD: 2.1 GB HDD (IDE 0:0)
Floppy: 3.5" 1.44MB
CD-ROM: ATAPI 2x CD-ROM (IDE 1:0)
Sound card: Ensoniq AudioPCI (ES1371)
Operating System: Windows 95 RTM

**Comment by Fenix770** [comment]
Hello!
I had the same problem with the Tseng based card. I found a possible solution in the readme file. I don't know if it will work with other video cards, but checking it won't hurt.

Workaround for Tseng machines, explained in the README file of the DOS version.

_
This file contains last minute updates for Sid & Al's Incredible Toons.

We have discovered that video cards with a TSENG chip set may cause
the screen to flash when the program is running.  If this
happens you will need to add the following line to the RESOURCE.CFG
file in the TOONS directory:
        VIDEO = YES

This line will instruct the program that the video card is present
and prevent the screen from flashing.
_

**Comment by Ompronce** [comment]
> Hello!
> I had the same problem with the Tseng based card. I found a possible solution in the readme file. I don't know if it will work with other video cards, but checking it won't hurt.
> 
> Workaround for Tseng machines, explained in the README file of the DOS version.
> 
> **
> This file contains last minute updates for Sid & Al's Incredible Toons.
> 
> We have discovered that video cards with a TSENG chip set may cause
> the screen to flash when the program is running. If this
> happens you will need to add the following line to the RESOURCE.CFG
> file in the TOONS directory:
> VIDEO = YES
> 
> This line will instruct the program that the video card is present
> and prevent the screen from flashing.
> **
> If I recall correctly, other solution exist for the Windows version of the game.

Yes, I am aware of the RESOURCE.CFG fix mentioned in the Readme file. Cards like the ATI Mach 64 and the S3 Virge/DX work perfectly in this game without any flickering (and without editing the RESOURCE.CFG file as you mentioned), however the screen repeating issue occurs still (even on the [ISA] VGA card, which does not exhibit the flickering, and this is the original IBM VGA card).

**Comment by TC1995** [comment]
Could you kindly send me the game?

**Comment by TC1995** [comment]
OK, could I see your config.sys for emm386_.

**Comment by Ompronce** [comment]
> Could you kindly send me the game?

[TOONS.zip](https://github.com/86Box/86Box/files/7178247/TOONS.zip)

I have attached a copy of the game in question.

**Comment by Ompronce** [comment]
> Would it be possible for you to upload your CONFIG.SYS?

[CONFIG.zip](https://github.com/86Box/86Box/files/7178269/CONFIG.zip)

I have attached a copy of my CONFIG.SYS file.

**Comment by TC1995** [comment]
Hmm, running this under DOS 5.0 has no such issues with the OPTI495-based machines with the EV159 EMS cards, and tested with the cards you had, so it's most likely a problem with either emm386 or win95's dos mode.

**Comment by TC1995** [comment]
![20210916-135718-083](https://user-images.githubusercontent.com/9269715/133627016-a4183940-fc73-44c6-9488-ca6da031a635.png)

**Comment by OBattler** [comment]
It's most likely the game using the A000-BFFF 128k mapping that is getting clobbered by the UMB'a at B000-B7FF. As such, I'm closing this.

**Comment by Ompronce** [comment]
> Hmm, running this under DOS 5.0 has no such issues with the OPTI495-based machines with the EV159 EMS card drivers, and tested with the cards you had, so it's most likely a problem with either emm386 or win95's dos mode.

Is this with the RESOURCE.cfg file fix mentioned earlier in this thread or the default mode that causes the screen repeating? I tested the same configuration under the same machine you used, without the EMS card though, and with DOS 6.22, tried excluding the memory range mentioned by @OBattler, and the game still shows the issue. Only the RESOURCE.cfg edit fixes it.
