### ISSUE TITLE
Victor V86P graphics bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1694]
**Describe the bug**

I discovered a screen bug on the game Battle Chess with the mouse enabled. When I promoted a pawn during the game the screen bug appears. To save time during this test the pieces of the game can be set up to test the bug quickly.

**Screenshots**

![Battle Chess 001](https://user-images.githubusercontent.com/31600563/133531690-85661d39-20a2-46d9-9558-192c3aae4dc7.png)

![Battle Chess 002](https://user-images.githubusercontent.com/31600563/133531683-981f639c-8226-4de7-808f-dc735ca1015a.png)

The V86 hard disk image files is uploaed in the closed issue #1678

Here is the 3.5 720kb image file of the game
[Battle Chess[a2].zip](https://github.com/86Box/86Box/files/7174134/Battle.Chess.a2.zip)

**To Reproduce**
1. Start the VM
2. Load the Mouse.com device driver
3. Type A: and CHESS at DOS prompt
4. Play the a new game or set a custom board with pawns near the promotion line.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 21H1
 - 86Box version: 3.0.0.3193
 - Build type: Dev

**Comment by TC1995** [comment]
This happens with plain CGA too.

**Comment by Fenix770** [comment]
I also found a lockup with the game Solitaire for Deskmate. I'm using the Cute Mouse driver ver 1.9.

![Solitaire](https://user-images.githubusercontent.com/31600563/134695466-c519bb50-5f0c-493a-9cb4-c30f059ae5c7.png)

**Comment by Fenix770** [comment]
I recently discovered that the lock up with Deskmate Solitaire games is related to the IBM PC Xebec hard disk controller.
I started the machine without the HD and the game works fine. I don't know if the BIOS of this machine expects some behavior of the JVC/Ricoh HD controller interface, which is not present.

**Comment by waltje** [comment]
The actual V86P had a very, very weird (and custom) hard disk controller,and is not currently emulated.  I have one (with HD), and am making veryslow progress going through its BIOS to figure out how it talks to the HDC.
In 86Box, it is "replaced" with one of the existing controllers, which indeedcould be breaking something else.
--waltje

    On Tuesday, February 15, 2022, 05:43:32 PM EST, Fenix770 ***@***.***> wrote:  
 
 


I recently discovered that the lock up with Deskmate Solitaire games is related to the IBM PC Xebec hard disk controller.
I started the machine without the HD and the game works fine. I don't know if the BIOS of this machine expects some behavior of the JVC/Ricoh HD controller interface, which is not present.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OBattler** [comment]
Assuming the bus mouse is being used - of course the HDC will break it, as it's going to be sharing IRQ 5 with the mouse.

**Comment by Fenix770** [comment]
This bug only happens on Deskmate Klondike and Battle Chess. Other apps works just fine. Also there is no way to change IRQ on the serial mouse or Xebec controller.

**Comment by OBattler** [comment]
Closing this for NOTBUG - incompatibility between the hard disk controller and the mouse, it's going to need the correct hard disk controller emulated.
