### ISSUE TITLE
86Box with PCjr machine hangs on startup with -f option

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1702]
**Describe the bug**
86Box with PCjr machine hangs on startup with -f option. Other machines start normally (with the -f option) immediately in full screen mode.

**To Reproduce**
1. Create a PCjr machine
2. Start this machine immediately in full screen mode. For example: 86Box.exe -f -p vms/PCjr
3. See error

**Expected behavior**
86Box when starting the PCjr machine right away in full screen mode should start normally.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H1
 - 86Box v3.00 build 3207
 - Build Type: dev

**Comment by maximus105** [comment]
The issue has not been completely fixed. When starting 86Box with the PCjr machine with the -f parameter, a window appears all the time with a message about switching to full-screen mode. Checking the "Don't show this message again" checkbox does not help (the next time you start 86Box with the PCjr machine with the -f parameter, the window with the message about switching to full-screen mode appears again). This also happens on any machine when starting 86Box with the -f option. Also, when starting 86Box of any machines with the -f parameter on the SDL (OpenGL) render, the screen is black (the image is normal on other renders).

**Comment by maximus105** [comment]
This new bug with a window with a message about switching to full screen comes from the recent fixes of PCjr for full screen mode. Checking the "Don't show this message again" checkbox to switch to full screen mode does not help. And now this bug with a non-switchable notification about switching to full-screen mode appears on any machines when switching to full-screen mode.

**Comment by OBattler** [comment]
I fixed this now, but you're going to manually have to delete video_fullscreen_first from the configuration file.

**Comment by maximus105** [comment]
Manually removing video_fullscreen_first from the config file doesn't help. When starting 86Box with any machine with the -f parameter, a window appears all the time with a message about switching to full screen mode. Checking the "Don't show this message again" checkbox does not help (the next time you start 86Box with any machine with the -f parameter, or when you press CTRL + ALT + PAGE DOWN and back, a window appears again with a message about switching to full-screen mode). Build 3207 was fine. When manually removing video_fullscreen_first from the configuration file and then starting 86Box with any machine with the -f parameter, the window appears with a message about switching to fullscreen mode only once. Checking the "Don't show this message again" checkbox helps to disable this window the next time you start 86Box with any machine with the -f option. And in build 3208 and until the last build, this no longer works. Can this bug be fixed?

**Comment by OBattler** [comment]
Do it now. It turns out that, while I committed it last night, I forgot to push it, so there never was a binary with the fix inside.

**Comment by maximus105** [comment]
Thanks. Everything works fine.
