### ISSUE TITLE
Can't boot from 180k/360k images on various XT machines

### ISSUE THREAD

**Issue by laciba96** [86Box/86Box#1704]
**Describe the bug**
Various 8088 and 8086 machines are can't boot from floppies.
Here is an example config with IBM PC/XT.
![86box.cfg.txt](https://github.com/86Box/86Box/files/7190004/86box.cfg.txt)
This config worked flawlessly with 86Box v3.0.0.3189 but not on the recent version which is v3.0.0.3209. 
Both builds are the regular ones, not the -dev versions.

**To Reproduce**
1, Set up the example config
2, Try to boot from PC-DOS 1.x, 2.x, 3.x images. (180k/360k)
3, On the earlier builds they work fine
4, On the newer builds the 1.x, 2.x images starts ROM-BASIC, and the 3.x images says Non-system disk or disk error.

**Expected behavior**
The same behavior as in 86Box v3.0.0.3189.

**Screenshots**
<img width="481" alt="2021-09-18_15h57_50" src="https://user-images.githubusercontent.com/84271678/133891287-4e0f704a-8ce5-43cf-a825-d65d875ef0cc.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - 86Box version: v3.0.0.3209
 - Build type: regular

**Additional context**
The problem affects other machines than IBM PC/XT, such as IBM PC 5150, Compaq Portable, Compaq Deskpro, AMI XT Clone. Probably there is more, but I just tested these ones.

**Comment by OBattler** [comment]
Closing this because it's now fixed.
