### ISSUE TITLE
Floppy disk drives do not work anymore

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1705]
**Describe the bug**
I recentrly discovered that a the emulator cannot read any floppy disk. I tried two machines Goldstar 286 and Award 486 based in the Opti 495 chipset.

For example the Goldstar 286  throws a "disk boot failure" at startup if a 3.5 floppy is in drive A. And The 5.25 1.2Mb drive B cannot read 360kb or 1.2Mb disks.

The commit 3.0.0.3193 works flawlessly

**To Reproduce**
1. Start any of the mentioned machine
2. Try to boot or read a floppy disk

**Screenshots**

![Floppy Bug](https://user-images.githubusercontent.com/31600563/133892543-7db5ce26-7a95-4f1f-9102-b122e75d50d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - 86Box version: 3.0.0.3209/3207
 - Build type: Dev

**Comment by Fenix770** [comment]
Edit: The low density floppies on XT based machines seems to work but not the high density drives on 286 and latter machines.

Another Example:

![Floppy bug 2](https://user-images.githubusercontent.com/31600563/133892975-d0b60e80-745b-429a-a4e0-7ac0edce78db.png)

**Comment by OBattler** [comment]
I can't reproduce this at all. I'm able to boot into MS-DOS 6.0 Setup on an 1.44 MB floppy just fine on the Goldstar: 
![imagem](https://user-images.githubusercontent.com/10365853/133896601-905cbbef-366c-4025-b6b3-11eeecea282c.png)
