### ISSUE TITLE
Windows 95 mouse occasionally disappears

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#1733]
**Describe the bug**
When using Windows 95, the mouse would disappear near the bottom right corner until I move the mouse around a lot.

**To Reproduce**
1. Use Windows 95

**Expected behavior**
The mouse is supposed to stay visible as I move it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x86_64
 - 86Box version: 3.0 build 3221
 - Build type: regular

**Additional context**
I am using S3 Trio64 with 4 MB of VRAM as the video card.

**Comment by OBattler** [comment]
What driver are you uing for the Trio64? Is it the built-in one?

**Comment by jadasse** [comment]
yea

**Comment by jadasse** [comment]
the s3 trio64 (phoenix) one.

**Comment by jadasse** [comment]
The update did not work. The mouse is still clipping.

**Comment by jadasse** [comment]
Another thing I should mention, it is not just the bottom right corner; it is the whole right half where the mouse clips. Also, sub-menus in the Start menu clip, too!

**Comment by jadasse** [comment]
> What driver are you uing for the Trio64? Is it the built-in one?

yea, the s3 trio64 (phoenix) one.

**Comment by jadasse** [comment]
I made a new issue as this is outdated: #1739
