### ISSUE TITLE
Tandy 1000 TL/2 implementation

### ISSUE THREAD

**Issue by anabate123** [86Box/86Box#1736]
**Is your feature request related to a problem? Please describe.**
I saw a shot of Fenix77's screenshot of PCem saying Tandy 1000 SL/2 with 286 next to the title.

**Describe the solution you'd like**
I really would like to see if the Tandy 1000 TL/2 (80286) can be emulated on 86Box.

**Describe alternatives you've considered**
I tried using MAME for emulating it, but it doesn't have hard disk support for that.

**Additional context**
Screenshot: http://adb.arcadeitalia.net/media/mame.current/ingames/t1000tl2.png
ROM File: http://retrograde.inf.ua/files/T1K_02TD.ZIP

**Comment by Ompronce** [comment]
> **Is your feature request related to a problem? Please describe.**
> I saw a shot of Fenix77's screenshot of PCem saying Tandy 1000 SL/2 with 286 next to the title.
> 
> **Describe the solution you'd like**
> I really would like to see if the Tandy 1000 TL/2 (80286) can be emulated on 86Box.
> 
> **Describe alternatives you've considered**
> I tried using MAME for emulating it, but it doesn't have hard disk support for that.
> 
> **Additional context**
> Screenshot: http://adb.arcadeitalia.net/media/mame.current/ingames/t1000tl2.png
> ROM File: http://retrograde.inf.ua/files/T1K_02TD.ZIP

I have made patches for Tandy machines for PCem in the past (latest being in particular the 1000 RSX and others). I have to port them over to 86Box in the near future.

**Comment by OBattler** [comment]
Closing because it's now being tracked here: https://github.com/86Box/86Box/issues/3577 .
