### ISSUE TITLE
Add Nvidia Riva 128 GPU

### ISSUE THREAD

**Issue by AjiKastara** [86Box/86Box#1742]
I would like to have an Nvidia Riva 128/128ZX GPU that matches with a Pentium 2 processor.

**Comment by TC1995** [comment]
Not now.

**Comment by dgurney** [comment]
To expand a bit further, the Riva is complex to emulate, and a previous effort at it did not get very far. So unless someone with the right skill set and time shows up, you'll be waiting for quite a long time.

**Comment by OBattler** [comment]
I'm closing this because of the above and because there's absolutely no documentation of the Riva 128.

**Comment by CRTRevivalDreamer** [comment]
Not so slow! Here are the datasheets of the [RIVA 128](https://github.com/86Box/86Box/files/7681071/RIVA128.pdf) and [RIVA 128ZX](https://github.com/86Box/86Box/files/7681072/RIVA128ZX.pdf).

**Comment by OBattler** [comment]
Do you really think such complex accelerator would be described in only 78 pages? The S3 ViRGE datasheet is quite a big bigger and that's far less complex than the Rivas. Those two datasheets don't describe anything.
