### ISSUE TITLE
Central Point RAMBoost is stuck and keeps restartingthe VM in a loop

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1757]
**Describe the bug**
After running the RAMBoost utility included in PC-DOS 6.30, (similar to MS-DOS Memmaker) it keeps restarting the machine in a loop and never ends it optimization. I found the same bug in other machine when I used the RAMBoost utility inlcuded in PC-TOOLS Gold v 9.0

**To Reproduce**
1. Start the machine and type "Yes" when  ask for memory optimization.
2. The first time, IBM antivirus performs a system checks.. Wait some seconds
3. At the end, the machine restars and performs the same question, again

**Expected behavior**
The machine should perform the memory optimization, like its MS-DOS counterparts do whit Memmaker.
I don't know if the problem is bug in both versions (IBM DOS and PC-TOOLS v 9) of the software or some behavior not emulated during the VM reset

Hard disk and CFG files:
[Pentium 60 to test.zip](https://github.com/86Box/86Box/files/7366781/Pentium.60.to.test.zip)
[Pentium 60 Win 311 Trident 9680.zip](https://github.com/86Box/86Box/files/7366783/Pentium.60.Win.311.Trident.9680.zip)

**Screenshots**
![Ramboost Bugjpg](https://user-images.githubusercontent.com/31600563/137766182-26463cf3-4de0-448d-a72a-d16778d8c24c.jpg)

**Desktop (please complete the following information):**
 - OS: Win 10 ver 21H1
 - 86Box version: 3.0.0.3236
 - Build type: Dev

**Comment by eddmanx** [comment]
Did a test with the CMOS date set to before y2k, per lee4hmz's suggestion, and it works.

**Comment by OBattler** [comment]
Then this can be closed as NOTABUG.
