### ISSUE TITLE
[i440BX] Microsoft Virtual PC 2007 does not work with any AGP video cards

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1760]
**Describe the bug**
[i440BX] Microsoft Virtual PC 2007 does not work with any AGP graphics cards available in 86Box. Black screen appears on startup, although PC Speaker sound is heard during POST. With PCI graphics cards, the [i440BX] Microsoft Virtual PC 2007 starts up and runs normally.

**Expected behavior**
[i440BX] Microsoft Virtual PC 2007 should work fine with any AGP graphics cards available in 86Box.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H1
 - 86Box v3.00 build 3240
 - Build Type: dev

**Comment by OBattler** [comment]
There's no evidence this BIOS supports AGP, and I certainly don't recall Virtual PC 2007 emulating AGP at all. As such, I'm closing this issue with NOTABUG.
