### ISSUE TITLE
Quake freezes on [i440BX] Microsoft Virtual PC 2007

### ISSUE THREAD

**Issue by usergithub64** [86Box/86Box#1763]
**Describe the bug**
Quake freezes on [i440BX] Microsoft Virtual PC 2007. After some time after the start of the game, Quake freezes on [i440BX] Microsoft Virtual PC 2007. The main character of the game spontaneously starts moving until he hits, for example, a wall (as if the keyboard and mouse are stuck). The keyboard does not respond to pressing and the mouse does not respond to movements. You can hear the enemies shooting and the background sounds of the game. But you can't get out of the game. You can only close the 86Box completely. On other machines in 86Box Quake works fine.

**To Reproduce**
1. Create a machine [i440BX] Microsoft Virtual PC 2007 with MS-DOS v6.22
2. Start Quake
3. Play for a while on the first level of episode1, you can even go to the second level of episode1, until Quake stops responding to keyboard and mouse controls

**Expected behavior**
Quake should work fine on [i440BX] Microsoft Virtual PC 2007

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H1
 - 86Box v3.00 build 3244
 - Build Type: dev

**Additional context**
My 86Box.cfg file:
[86box.zip](https://github.com/86Box/86Box/files/7391349/86box.zip)

**Comment by OBattler** [comment]
Keyboard loss is a known problem, the controller is being rewritten also to fix this, that's why the feature/machine_and_kb branch is for, and there's also plenty of other open issues about it already. As such, I'm closing this.
