### ISSUE TITLE
The mouse pointer moves very slowly under Windows 3.1 with Tseng ET4000/w32i

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1773]
**Describe the bug**
The mouse moves very slowly under Windows 3.1 with Tseng ET4000/w32i. I tested both ISA and VLB  versions of the card.
And tested two machines the FIC-VC-HD ISA 486 with the ISA model, and Olistar LiL 1429 with the VLB model.
The mouse type I used is the standard Microsoft Serial Mouse. All video resolutions seem to be affected 256, 32k and 64k video modes. This is the only bug I found so far. 
Another small glitch is the VESA BIOS reports that video modes1024x768 with 32k and 64k  are supported. This can be fixed with TLIVESA DOS driver which removes these video modes of the list of supported modes.

Here is the HD and CFG files:
[486 FIC-ISA.zip](https://github.com/86Box/86Box/files/7441884/486.FIC-ISA.zip)
[486 FIC-ISA-ET4000-W32i.zip](https://github.com/86Box/86Box/files/7441885/486.FIC-ISA-ET4000-W32i.zip)

**To Reproduce**
1. Start the VM
2. Type Win at DOS prompt
3. Move the mouse, is slow even when configured at max speed in mouse settings in the control panel

**Expected behavior**
The mouse speed should not be affected

**Desktop (please complete the following information):**
 - OS: Win 10 v 21H1
 - 86Box version: 3.0.0.3252
 - Build type: Dev

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by OBattler** [comment]
Closing because it's now fixed.
