### ISSUE TITLE
3Com Etherlink II adapter stalls

### ISSUE THREAD

**Issue by Carmina16** [86Box/86Box#1776]
**Describe the bug**
Transferring large amounts of data via TCP is problematic with that adapter.

**To Reproduce**
1. Install that adapter and Windows 95 OSR2 on a "AMI 486" system
2. Download a large (>100kB) file via HTTP or a message via POP3
3. The transfer stalls forever unless other connections are made or ping _remote host_ command is issued, than it proceed normally as long as there is a parallel network activity.

**Expected behavior**
Transfer occurs normally.

**Desktop (please complete the following information):**
 - OS: Windows 8.1 64bit
 - 86Box version: v2.07 245af88d
 - Build type: sandybridge 32

**Additional context**
It happens in all PIO and DMA transfer modes.

**Comment by OBattler** [comment]
I think we're having these stalls with every network adapter currently. It might be the thread causing these problems.

**Comment by OBattler** [comment]
Yes, it *was* the thread. The mutex waiting code was all wrong. A rewrite of that stuff is coming.

**Comment by OBattler** [comment]
This has now been done by elyosh, therefore, I'm closing this.
