### ISSUE TITLE
QEMM bugs with some 486 machines

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1779]
**Describe the bug**
I recently found problems with QEMM software and some 486 chipsets:
Here I upload the VM of Siemens Nixdorff 486 (82C481 chipset).

Nixdorff VM and cfg files:
[486 Siemens Nixdorf -Experimento-.zip](https://github.com/86Box/86Box/files/7449574/486.Siemens.Nixdorf.-Experimento-.zip)
[486 Siemes Nixdorf.zip](https://github.com/86Box/86Box/files/7449575/486.Siemes.Nixdorf.zip)

Bugs:

1.QEMM 7.5 fails to run the optimize program after it instalation, some times generates a crash closes the emulator and others simply undo the changes.

2. The i420 EX and TX chipset crash if the "Stealth" mode is enabled by QEMM v8. Standard mode works, but I have to exclude the F000-F800 region, and the manifest program for DOS generates an exception.

**To Reproduce**
1. Start the VM
2. Type cd qemm
3. type optimize at DOS prompt
4. Either the Vm crash or optimize program undo any changes after several restarts. 

**Expected behavior**
QEMM should work like in the ohrt 386 machines I tested

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - 86Box version: 3.0.0.3252
 - Build type: Dev

**Comment by Fenix770** [comment]
Here is another strange bug I found with QEMM 8 and UMC 486 chipset. I don't know if its a 86box bug or QEMM fault since it maps parts of the F memory area which is reserved to ROM. Other memory managers like 386MAX do not do this but cretes less UMBs as well.

Here is a video that shows it cannot open midi files after running QEMM Manifest for Windows:

[86Box v3.0 [355c26ef, build 3252] - 95% - [UMC 8881] Shuttle HOT-433A - i486DX2_50 - Click to capture mouse 2021-10-31 16-08-25.mp4.zip](https://github.com/86Box/86Box/files/7449594/86Box.v3.0.355c26ef.build.3252.-.95.-.UMC.8881.Shuttle.HOT-433A.-.i486DX2_50.-.Click.to.capture.mouse.2021-10-31.16-08-25.mp4.zip)

**Comment by ppgrainbow** [comment]
Do you have any idea which build of 86Box v3.0 was the last to not cause the hang?

OBattler, has the Shuttle HOT-433A been removed or has it been readded, because I'm still confused to see if it's working or not.

**Comment by OBattler** [comment]
The Shuttle HOT-433A only works properly on the feature/machine_and_kb branch, it's not really usable on master.

**Comment by ppgrainbow** [comment]
> 
> 
> The Shuttle HOT-433A only works properly on the feature/machine_and_kb branch, it's not really usable on master.

Thank you for explaining this. I appreciate it. :)

**Comment by OBattler** [comment]
Closing because it's being tracked in #4482 .

**Comment by OBattler** [comment]
The UMC problem was due to incomplete chipset emulation (and allocating Fxxx to UMB's which is always risky), allocating Fxxx to UMB's likely causes the 420EX problem as well. The VLSI chipset problem I have no idea, The first issue I have no idea, but I'm going to consider it stale since a LOT of things have changed since then.
