### ISSUE TITLE
Screen bugs on Trident 9400/9440

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1795]
**Describe the bug**

I found bugs on the Trident 9400CXi VLB video card on Windows for Workgroups 3.11. 
Also, I found screen garbage, on 9440AGi VLB and PCI with the SVM.EXE utility when testing High/True color modes (32k/64k/16M).

**To Reproduce**

To test Windows 3.11 for Workgroups with the 9400CXi

1. Type "Win" at DOS prompt 
2. Change the screen resolution with Windows setup or Trident display utility
3. See the screen 

To test the SVM.EXE utility on the 9440AGi
1. Type CD C:\tvgautil\utility
2. Type SVM
3. Select high/true video modes on the right part of the screen.

Trident 9400CXi screenshots
![Trident 9400CXi 002](https://user-images.githubusercontent.com/31600563/141206764-e4c5260f-a15b-4226-9424-75bfd55ca103.png)
![Trident 9400CXi 001](https://user-images.githubusercontent.com/31600563/141206769-30da34e1-9d52-4ba6-81b6-c21515e59161.png)

PD: The Trident 9440AGi drivers includes CXi drivers too. But CXi does not works on the 9440AGi mode either.

Hard disk image and CFGs files

HDs:
[486 Win 311 Trident 9400.zip](https://github.com/86Box/86Box/files/7516437/486.Win.311.Trident.9400.zip)
[486 Win 311 Trident 9440.zip](https://github.com/86Box/86Box/files/7516440/486.Win.311.Trident.9440.zip)

CFGs:
[486 Trident 9400.zip](https://github.com/86Box/86Box/files/7516446/486.Trident.9400.zip)
[486 Trident 9440.zip](https://github.com/86Box/86Box/files/7516447/486.Trident.9440.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 21H1
 - 86Box version: 3.0.0.3255
 - Build type: Dev

**Comment by TC1995** [comment]
Well, the 9400cxi doesn't have the same way to initiate the accelerator like the 9440AGi does.

**Comment by robman501a** [comment]
I'm having the same problem as you.
![image](https://user-images.githubusercontent.com/30871515/221051861-df175ac8-d63e-4917-aea8-ab2f759fcf03.png)
![image](https://user-images.githubusercontent.com/30871515/221052005-0232cbce-f5c5-4f05-b5d8-e6934f0a6353.png)

Windows 11 22H2
86Box 3.11 build 4454
Build type: Dev

Is there a fix for this bug?

**Comment by OBattler** [comment]
Closing this with CANTFIX due to no documentation.
