### ISSUE TITLE
86box soundblaster issues

### ISSUE THREAD

**Issue by crlcolunga** [86Box/86Box#1796]
Is in windows 3.11 when it startups it sound like a broken record, but when I close the session the sound hears good. I don't understand it. It's the soundblaster 16.

I don't know it is my computer or the emulator bugs?

This is my pc especifications.
![image](https://user-images.githubusercontent.com/94066997/141212117-7f1b0b81-5ad7-48d9-9ceb-dec8346c4612.png)

**Comment by OBattler** [comment]
Is the emulator always running at 100%?

**Comment by crlcolunga** [comment]
yes and altought not at 100% the issue continues.

**Comment by maxdlpee** [comment]
That explains it

**Comment by OBattler** [comment]
Then I'm closing this with NOTABUG.
