### ISSUE TITLE
Paradise 90C30 1MB video modes do not work

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1797]
**Describe the bug**
I tested the Paradise 90C30. I found the 32k/64k video modes do not work. I first thought that this model lacks the HiColor DAC, but 
I found bugs with 1024x768 256 color video mode. The driver says it supports the 90C30 and 90C31, I don't know what is the difference between these video cards.

**To Reproduce**
1. Start the VM
2. Change the any video mode that require 1mb
3. See the screen 

Here is the HD and CFG of the VM:
[386 DX Windows 3.1.zip](https://github.com/86Box/86Box/files/7521447/386.DX.Windows.3.1.zip)
[386 Win 31 PVGA 90C30.zip](https://github.com/86Box/86Box/files/7521448/386.Win.31.PVGA.90C30.zip)

**Screenshots**
This configuration is 800x600x256 with 512k driver and 512kb of VRAM
![Paradise 90C31 Win31 002](https://user-images.githubusercontent.com/31600563/141323133-46db8197-af99-420c-a6d1-8d98ea960630.png)

Same video mode with 1mb of VRAM
![Paradise 90C30 with 1mb RAM](https://user-images.githubusercontent.com/31600563/141323355-1e31f407-fbcb-4bb0-9160-b13177534c21.png)

1024x768x256 1mb of VRAM
![Paradise 90C31 Win31 001](https://user-images.githubusercontent.com/31600563/141324279-2794b1de-3a2a-4c90-aa8c-bcd1423b8c30.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 
 - 86Box version: 3.0.0.3255
 - Build type: Dev

**Comment by TC1995** [comment]
Yeah, known bug, I tried to solve this though.

**Comment by TC1995** [comment]
Ok, I solved this some days ago.
