### ISSUE TITLE
CBM PC 30 III (286) keyboard doesn't work in BIOS

### ISSUE THREAD

**Issue by Teppic1** [86Box/86Box#1813]
**Describe the bug**
You can enter the BIOS setup with ctrl-alt-esc but then the keyboard does nothing. This works fine on the final PCem release.

**To Reproduce**
Use the PC 30 III with any CPU speed, any memory, any HD controller, etc. always the same.

**Desktop (please complete the following information):**
Win10
86box 3.0 build 3259
regular build

**Comment by TC1995** [comment]
Most likely a kbc issue on our end, pressing ctrl-alt-esc again makes it regain the input, just tested now.

**Comment by Teppic1** [comment]
> Most likely a kbc issue on our end, pressing ctrl-alt-esc again makes it regain the input, just tested now.

If I press ctrl-alt-esc again it refreshes the screen but the keyboard still does nothing (except being able to reload).

**Comment by OBattler** [comment]
It appears to work now, so I'm closing this.
