### ISSUE TITLE
slowdowns in XT machines with DOS games

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#182]
Also I' want to report a bug in the emulation on XT machines. The promblem is a slowdown that happen in certain games with these machines.

Some of them can render the game unplayable.

And it can Lock up the system if VGA card is used.

The games and Machines I Tested:

Whit Vtech Laser Turbo XT and XT 3, Tandy 1000 SL/2 (with tandy 3-voice and DAC) and Amstrad 1640 with EGA graphics.

* Prince of Persia 1.0 and 1.3: The slowdown is more noticeable when the guard or the animation of fire is present. And if VGA is used the system may Lock-up

And whit Laser XT and XT 3 with Hercules And CGA.

* Bubble Bobble: It has a lot of it. (specialy when more than 3 enemies appear)
* Tetris (Spectrum Holobite, 1987): The games run flawlessly, no problem here.
* Tom & Jerry Cat-Astrophe: The slowdown is less noticieble.

Another Problem is that some CGA emulators for the Hercules Card, does not work. (for example the emulator MONO.COM. Back in the day i used it for Bubble Bobble.)

I attach The mono.com file, in case somebody want to see it.
[MONO.zip](https://github.com/OBattler/86Box/files/1275369/MONO.zip)

The problem seem to be solved for the IBM AT 286, which had the same issue with old releases.
I tested Prince of Persia v1.3 with VGA, adlib music and Disney Sound Sorce for sound.

**Comment by Fenix770** [comment]
[MONO.zip](https://github.com/OBattler/86Box/files/1275365/MONO.zip)

**Comment by OBattler** [comment]
This might be caused by the DAC. And to make really sure it doesn't also affect PCem, I'd try on the latest development build of PCem (I'll compile one later), as comparing PCem v12 stable (which is now lots of commits behind) with latest 86Box dev is a bit pointless. :p

**Comment by MoochMcGee** [comment]
Slowdowns are supposed to happen on older machines, they're slow.

**Comment by OBattler** [comment]
This is mainline PCem compiled from code from September 2nd: http://citadel.ringoflightning.net/PCem.exe . See if you can get the same slowdowns on this.

**Comment by Fenix770** [comment]
Thank you!. 
I will test  the 8086/88 machines with the 20mb xebec MFM hard disk  and the 30mb XT IDE hard disk.
Also i found bugs in sound cards like CMS/gameblaster and Adlib gold, but would be better open other  thread later.

**Comment by Fenix770** [comment]
Hello the compiled PCEM, i see it has new configurator manager.

I tested Prince of Persia v1.0. The crash no longer happens in Laser XT system with CGA graphics , but cursor keys right and left, act as if shift were pressed too.( like shift+left or shift+right). and at some point the prince keeps running  to the right side but no key are actually pressed.

I found two new bugs indded. 

1. Both PCEM and 86box  erroneously  detect the MFM hard disk CHS: 306,8,17 as  CHS: 615,4,17 and it cannon boot from it. I can change the option in 86box but not in this svn version of PCEM. (I earlier thought it was a bug in the MFM emulation)

2 I tested  Prince of Persia v1.3  with Tandy 1000 SL/2, usingTandy 3-voice and DAC. The game locks up.
and interestingly it uses a monochrome CGA monitor for its 16 color graphics. (I used it before in the Laser XT emulation)
As fas as i know Radio Shack sold monochrome monitors for its 16 color machines, but seem to be a more a bug than a feature.  
![prince of pesia v1 3 bug](https://user-images.githubusercontent.com/31600563/30143875-592381cc-935e-11e7-8833-06d96077c66f.jpg).

I will report new bugs if i find them. 

Thanks again.

**Comment by Fenix770** [comment]
Update:

Game tested: Prince of Persia v1.3

**In compiled version of PCEM:** Hercules does not work with the XT machines 
_tested:_ Both Laser XT machines, AMI XT 8088 and Generic XT. They can boot (i suppose becase i can hear the beep on the start) but only the cursor can be seen, with a completely black screen.

Hercules does work correctly with IBM AT 286 640kb ram, no problem with this system.  

**In 86box (SVN of September 9, 2017):**
appears "Video error" before the memory check, but otherwise work ok. The XT/3 does not work with Hercules. The remaining XT system appears to work ok with this card.

I Tested Juko XT With CGA, and it has a mix a both problems the shift keyboard need to attack with the sword had a slow response (somethimes prince dies before can attack). The cursor keys works and the slowdown is still there.

(In comparison the compiled PCEM (with CGA) had no speed issues but the problem with the keyboard render the game unplayable). 

Strangely it only affect XT systems. Not 80286 or later machines.

**Comment by OBattler** [comment]
Make sure the renderer is set to Direct3D and then see if the slowdown still happens.

**Comment by OBattler** [comment]
The latest build fixes the video error with Hercules on both the Laser XT machines.

**Comment by OBattler** [comment]
I can not reproduce the problem on the latest 86Box. I see the Prince of Persia intro screen just fine, and there is no apparent slowdown.
