### ISSUE TITLE
PS/2 mouse does not work in build 3255

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1822]
**Describe the bug**
PS/2 mouse does not work on build 3255 on [SiS 496] Zida Tomato 4DP. The CuteMouse mouse driver reports that the device was not found. At the same time, Microsoft Serial Mouse works fine. This bug appeared in build 3255 and is present until the last build. It is likely that other machines that have added a PS/2 mouse also do not work with a PS/2 mouse.

**Expected behavior**
PS/2 mouse should work fine

**Screenshots**
![2021-11-17_193929](https://user-images.githubusercontent.com/58270614/142256403-e0670e4a-7785-4cf2-b97e-d3e38c5e1016.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H1
 - 86Box v3.00 build 3264
 - Build Type: dev

**Comment by TC1995** [comment]
Are you using the machine kb one? if so, patiently wait until the PS/2 is re-implemented properly.

**Comment by jriwanek** [comment]
My screwup, gotta add the kbc to a few, thought I'd checked fully, but apparently not.
