### ISSUE TITLE
Icons not showing in 86Box's machine settings

### ISSUE THREAD

**Issue by antix98** [86Box/86Box#1841]
**Describe the bug**
Icons won't appear in 86Box's machine settings although the icons are set to default.

**To Reproduce**
1. Open/create a machine.
2. Open the machine's settings.

**Expected behavior**
The settings should have the icons shown.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/89010741/142622465-42266822-7a0c-4659-a342-bce7765f8ba5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.0 build 3283
 - Build type: Regular build

**Additional context**
Also tried using other icons provided in the settings. But it's still not working.
EDIT: On build 3287 v3.0 this bug was fixed.

**Comment by maxdlpee** [comment]
Did you try updating the romset? I think the icons are there now.

**Comment by antix98** [comment]
Yes I did

**Comment by maxdlpee** [comment]
Try changing the iconset option in the change program settings option from default to one of the two options. I did that, and icons now show up.

**Comment by antix98** [comment]
Still, it won't show
