### ISSUE TITLE
ESC/P emulation doesn't work

### ISSUE THREAD

**Issue by maxdlpee** [86Box/86Box#1842]
**Describe the bug**
ESC/P printer emulation does not work, giving an "Unable to initialize Freetype" error on bootup, despite the needed file being there.

**To Reproduce**
1. Go to 'Tools-Settings'
2. Click on 'Ports'
3. Select 'Generic ESC/P Printer' on any port
4. Save settings
5. See error

**Expected behavior**
Printing to work as expected, without the error message.

**Screenshots**
![pic1](https://user-images.githubusercontent.com/77379259/142623927-df23a359-65d4-4a40-93dc-a58d7b7739f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.0.0.3284
 - Build type: Regular (although it also happens on Dev as well)

**Additional context**
Using a DLL file from an older build (say, 3255) works fine, so if I have to guess, something's wrong with the DLL distributed on newer builds.

**Comment by maxdlpee** [comment]
It's been almost a month and still no resolution. Anything?

**Comment by maxdlpee** [comment]
Made some advancements on this:
It seems to only be a problem on 32-bit versions, as 64-bit works perfectly fine. Maybe the wrong version of the DLL is being distributed?

**Comment by maxdlpee** [comment]
I can confirm it being fixed on the latest build, now that error doesn't pop up anymore. I'll proceed to close this.

**Comment by jadasse** [comment]
I'm having that issue too

**Comment by jadasse** [comment]
continuing your legacy https://github.com/86Box/86Box/issues/2221
