### ISSUE TITLE
Icons in 86Box Settings window are not displayed in 86Box Manager

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1844]
**Describe the bug**
When you open the 86Box Settings window in 86Box Manager, the icons in the 86Box Settings window are not displayed.

**Expected behavior**
The icons in the 86Box Settings window should display normally in the 86Box Manager. 

**Screenshots**
![2021-11-19_153907](https://user-images.githubusercontent.com/58270614/142631955-86fb3237-bbae-46ee-bd67-d6f8cc83d324.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H1
 - 86Box v3.00 build 3284
 - Build Type: Regular
 - 86Box Manager v1.7.2

**Comment by daviunic** [comment]
I would again like to clarify that 86Box Manager is a separate program and this issue had nothing to do with the Manager.

**Comment by OBattler** [comment]
Yeah, I have no idea why this issue was originally opened on the 86Box Manager repository.
