### ISSUE TITLE
IBM PS/2 model 70 cannot read 2.88MB floppy disks.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1851]
**Describe the bug**
I created a VM with PS/2 Model 70, Tseng ET4000, SB Pro MCV, and Spock SCSI with CD-ROM. 
As software I used an updated Setup disk for the Model 70. The updated disk allows to select 2.88MB floppy disk drive.
The machine cannot boot or read the 2.88mb boot disk after booting, but other machines with 2.88mb can read it.

The downloaded the floppy image file and CD-ROM from the ArtiomWin link:
https://mega.nz/file/tcN0jLIa#N--nfWDr6vFvW5Jeg4zRYd__33s7UlVWgEGF62YNCbw

Updated Floppy disk:
[rf7080a.zip](https://github.com/86Box/86Box/files/7573520/rf7080a.zip)

Disk to update the original floppy:
[xgaopt.zip](https://github.com/86Box/86Box/files/7573521/xgaopt.zip)

Original floppy disk without the patch:
[rf7080a.zip](https://github.com/86Box/86Box/files/7573523/rf7080a.zip)

2.88mb boot disk:
[ulti1001.zip](https://github.com/86Box/86Box/files/7573531/ulti1001.zip)

Hard disk image with PC-DOS 5.02 installed (with 720kb disks) and cfg file:

[IBM PS-2 Win 3.0 Multimedia.zip](https://github.com/86Box/86Box/files/7573526/IBM.PS-2.Win.3.0.Multimedia.zip)

[PS2 Windows 30 Multimedia.zip](https://github.com/86Box/86Box/files/7573528/PS2.Windows.30.Multimedia.zip)

**Screenshots**
![288mb](https://user-images.githubusercontent.com/31600563/142707384-bf7bf265-30f0-4999-872e-0347df1ca87c.png)
![PS2 288 bug](https://user-images.githubusercontent.com/31600563/142707386-a44bff11-ef17-4e24-92ee-1189029474f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - 86Box version: 3.0.0.3287
 - Build type: Regular

**Comment by OBattler** [comment]
Are you sure the specific BIOS we have, supports 2.88 MB floppies?

**Comment by OBattler** [comment]
Closing this issue because ArtiomWin said this generation of PS/2's doesn't actually support 2.88 MB floppies.
