### ISSUE TITLE
OpenBSD crashes on all CPUs (Pentium CPU's and 486's)

### ISSUE THREAD

**Issue by agithubuser444** [86Box/86Box#1853]
![CW4rU1L](https://user-images.githubusercontent.com/84222460/142730154-056aab51-3352-458b-9293-a6e3a5843a9b.png)
Trying to boot OpenBSD from cd or it's boot floppy will result in a Kernel Panic, making installing it impossible, on the Pentium Pros it will show the error, but on 486/Pentium/Pentium MMX/Pentium 2 CPU's it will reboot the emulated machine, i don't know if the same thing happens on the AMD K6 CPU's

**Comment by agithubuser444** [comment]
Oops pressed enter by accident.

**Comment by Cacodemon345** [comment]
Can you use OpenBSD's kernel debugger in such cases?

**Comment by agithubuser444** [comment]
> Can you use OpenBSD's kernel debugger in such cases?
No i can't.

**Comment by dhrdlicka** [comment]
It might be worth noting that OpenBSD does not support the 486:
> All CPUs compatible with the Intel Pentium or later, with Intel-compatible hardware floating point support should work.

**Comment by OBattler** [comment]
The crashes have been reported on the Pentium as well. It is also not limited to OpenBSD - 386BSD currently also causes a triple fault reset on 86Box, while it boots fine on VirtualBox. I have no idea why that happens.

**Comment by agithubuser444** [comment]
> The crashes have been reported on the Pentium as well. It is also not limited to OpenBSD - 386BSD currently also causes a triple fault reset on 86Box, while it boots fine on VirtualBox. I have no idea why that happens.

Weirdly enough, netbsd works fine and boots fine.

**Comment by OBattler** [comment]
Apparently, now, OpenBSD 2.3 does not crash, but instead, encounters an IDE bug: https://github.com/86Box/86Box/issues/2942 .

Makes me wonder if OpenBSD 7.0 still crashes.

**Comment by ImBearChild** [comment]
![image](https://user-images.githubusercontent.com/29907700/234243887-c1fbbcff-305b-40e6-bb2b-eff3542091a2.png)

I've tried OpenBSD 6.9 and OpenBSD 2.9. Both boot fine. And OpenBSD 2.9 seems to be not affected by the IDE bug mentioned above.

**Comment by win2kgamer** [comment]
I did some testing on build 5809 with a few OpenBSD releases and found the following:
- On a Pentium or Pentium MMX CPU: version 6.3 boots successfully while versions 6.4, 6.9, 7.0 and 7.2 reset
- On a WinChip 2A or K6 Model 6 CPU: versions 6.3, 6.4, 6.9, 7.0 and 7.2 successfully boot
- On a Pentium Pro CPU: versions 6.3, 6.4, 6.9, 7.0 and 7.2 panic
- On a Pentium II CPU: version 6.3 boots successfully while versions 6.4, 6.9, 7.0 and 7.2 reset

Socket 7 CPUs were tested with the ASUS P/I-P55T2P4, the Pentium Pro was tested with the ASUS P/I-P65UP5 (C-P6ND) and the Pentium II was tested with the ASUS KN97.

On a real Pentium 166MHz system I was able to successfully boot version 6.4.

Panic screen on Pentium Pro:
![Monitor_1_20240601-163758-413](https://github.com/86Box/86Box/assets/47463859/dbdebe8e-d9ad-4529-b055-b3aa9df8d38e)
