### ISSUE TITLE
Random reboots on Shuttle and ADI 386SX machines with QEMM 5.11 and DOS 4.0 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1864]
**Describe the bug**
I discovered that random reboots can happen whit the ADI and Shuttle 386 SX, machines with DOS 4.0 and QEMM 5.11. 
I don't know what causes it. If I load DOSMAX drivers the reboot may happen after running anything at DOS prompt.
With QEMM alone, (Without DOSMAX and SMARTDRV). The machine works except when I try to install Word for Windows 1.1.
To install it I booted from a DOS 5 floppy. Because the DOS installer crashed.
After I installed it, Word restarts itself when I try to open a DOC file.

Here I upload a video of the problem:

https://user-images.githubusercontent.com/31600563/142954149-765e2e58-2d55-4216-9202-e141ce4d5e06.mp4

Here is the HD and CFG file:
[386 SX Shuttle-ADI.zip](https://github.com/86Box/86Box/files/7585174/386.SX.Shuttle-ADI.zip)
[386 SX shuttle.zip](https://github.com/86Box/86Box/files/7585175/386.SX.shuttle.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - 86Box version: 3.0.0.3294
 - Build type: Regular x86

**Comment by Fenix770** [comment]
For some unknown reason random reboots only happens with QEMM 5.11. DOS 4 works fine with QEMM 6.02.
Shuttle 386 SX and SiS ISA 386 DX works fine with QEMM 6.02. ADI 386 SX has random crashes so the cause may be unrelated.

**Comment by OBattler** [comment]
Closing because it's being tracked in #4482 .

**Comment by OBattler** [comment]
Looks to me like another BIOS incompatibility then.
