### ISSUE TITLE
Mouse sensitivity 

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1868]
**Describe the bug**
Since sometime, I've noticed that the mouse emulation have a sensitivity problem, for guest system with low resolution and slow cpu.
Mouse move move way to fast, with bad resolution, it's nearly impossible to use it under DOS TEXT Mouse apps, like Word 4.
Under GEM, it's impossible to click on certain things too small.
Under Geoworks 1.1, it's even worse.

Changing the drivers sensitivity inside the guest do not help: the mouse will only move with a distrubing 'stepping' effect, not smoothly.

I tried to change the speed of my Windows mouse, without really get things better, or with a so slow host mouse that it's not usable.

More over, I noticed with some guest systems that the mouse do not work at all (like Olivetti M24), whatever the kind of emulated mouse (serial, bus, ....).

Tested on two systems with same behaviour.

**Desktop (please complete the following information):**
 - OS: Windows 10 21h10
 - 86Box version: Latest Dev build from jenkins

**Comment by Fenix770** [comment]
It can be something related to mouse emulation the Olivetti M240, does not recognizes any mouse at Gwoworks 1.0 startup. If I reconfigure the mouse on GEM it starts to work, but if i exit and restart Geoworks the same problem happens again.
This bug may be on commits older than #3066

**Comment by Fenix770** [comment]
It can be something related to mouse emulation the Olivetti M240, does not recognizes any mouse at Gwoworks 1.0 startup. If I reconfigure the mouse on GEM it starts to work, but if i exit and restart Geoworks the same problem happens again.
This bug may be on commits older than #3066.

**Comment by abishur** [comment]
I'm also having this issue.  I've tried it out on a few different configurations (i486, Socket 5, Socket 7).  I'm using MS-DOS 7.1 whenever I load up a dos game that uses the mouse very small adjustments result in it flying across the screen making mouse control unusable.

I am also using Windows 10 as my Host OS and downloaded the latest stable version of 86box as of 4/11/2022

**Comment by Cacodemon345** [comment]
There's an emulator-side mouse sensitivity slider in recent builds. Try and see if it helps.
