### ISSUE TITLE
Choppy Audio

### ISSUE THREAD

**Issue by Annunaki** [86Box/86Box#1879]
Issue is choppy Audio on a Ryzen 5 3800X Machine, CPU usage in the title bar fluctuating between 80 - 100+%.

Steps to reproduce the behaviour:
1. Setup any Machine with SB PCI 128 Sound Card.
2. Install Win 98 SE.
3. Install SB PCI 128 Drivers.
4. Reboot Machine.
5. Hear the choppy Audio
 
 - OS: Windows 11
 - 86Box version: v2.07 build 2008
 - Build type: Zen

The issue persists on the normal build.

**Comment by OBattler** [comment]
The audio is choppy because the % in the title bar is fluctuating. Also, that % is not CPU usage, but how many of the emulated CPU cycles the emulator has been able to perform. It must remain at 100% at all times for sound not to be choppy. Emulate a slower CPU.

**Comment by jadasse** [comment]
Do you mean the Ryzen 5 3600x or the Ryzen 7 3800x? I ask because there is no such thing as the Ryzen 5 3800x.
