### ISSUE TITLE
Siemens 286 starts with a completly black screen if IBM EGA card is selected.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1880]
**Describe the bug**
The Siemens 286 starts with a black screen with no text if a IBM EGA card is selected. Something similar happend before (now solved) with the Hercules monochrome card. The Super EGA and ATI EGA works fine.

**To Reproduce**
1. Start the VM with EGA video card
2. VM starts with a black screen without any text

**Desktop (please complete the following information):**
 - OS: Win 10 21H1
 - 86Box version: 3.0.0.3307
 - Build type: Regular NDR x86

**Comment by OBattler** [comment]
Closing because it has been determined that the IBM EGA and Iskra EGA BIOS'es are simply not fully compatible with this machine.
