### ISSUE TITLE
Leopard 486 SLC locks up with the "WAIT" message at boot time

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1881]
**Describe the bug**
The Leopard IBM 486 SLC does not recognizes any storage device. The Setuo BIOS recognize the standard 127mb HD CHS 1024/15/17, But freezes after the memory check with the "WAIT" message. I don't know if it is related to this bug but I created a dynamic VHD HD, not the regular IMG.

**To Reproduce**
1. create a a 127mb blank HD
2 Run the setup BIOS
3. the machine locks up with the "WAIT" message

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - 86Box version: 3.0.0.3307
 - Build type: NDR, x86

**Comment by headsetguy37** [comment]
Hmm... I tried to reproduce this. I saw an error about the configuration not being correct, and it let me into the BIOS setup, but then it froze _after_ I saved the changes and exited. If you hit DEL immediately when it boots, then you can get into the setup utility. If you can do this, try loading the power-on defaults; that fixed it for me.

**Comment by Fenix770** [comment]
Thanks! It works!. May be some option on the BIOS then.

**Comment by OBattler** [comment]
Turns out it was a bug in the Shadow RAM implementation. Now it works.
