### ISSUE TITLE
Adding Korean resource and Japanese modified.

### ISSUE THREAD

**Issue by basic2004** [86Box/86Box#1894]
Congratulations on the releasing 86Box 3.0!
I downloaded and tested last release, I didn't found Korean language yet.
So I translated Korean resource file and modified some Japanese.

This file based on bc28b5d.
But I did not tested this.
[86Box-KR-JP-bc28b5d.zip](https://github.com/86Box/86Box/files/7641054/86Box-KR-JP-bc28b5d.zip)

**Comment by OBattler** [comment]
This is now committed. Thanks!

**Comment by basic2004** [comment]
Thanks, I tested and fixed some Korean and Japanese translation.
[86box-KR-JP-20211203.zip](https://github.com/86Box/86Box/files/7650848/86box-KR-JP-20211203.zip)
based on d28c9af.

**Comment by OBattler** [comment]
Thanks! Fixes committed.
