### ISSUE TITLE
[BUG] PS/2 Model 80 fails to boot properly if the IBM PS/2 SCSI adapter is selected and more than one SCSI hard disk is present

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#1899]
I would like to report a but involving the IBM PS/2 SCSI adapter and I found that on the emulated IBM PS/2 Model 80 (for example), the machine will fail to boot properly if two or more SCSI hard disks on the IBM PS/2 SCSI adapter are installed.

For example I used two hard disk images (IBM IBM 0663-L12, 1,004 MB). The boot drive is located on device address 0:0 and the data drive is located on device address 1:0. Using the reference disk, slot 2 reserving for the IBM PS/2 SCSI Adapter lists the first SCSI device on 1:0 and the second SCSI device on 0:0.

Here's a screenshot of the issue:
![20211203-051816-794](https://user-images.githubusercontent.com/32658796/144551596-56ba4e07-7ee0-4ac1-b015-9c2679648382.png)

And when I try to boot from device address 1:0 instead of 0:0, the emulated PC fails to either boot properly or goes into ROM BASIC:
![20211203-053948-185](https://user-images.githubusercontent.com/32658796/144551383-195f9c6e-576a-42fa-9d4c-edcad9329bab.png)

And here is the current 86Box.cfg file for the PS/2 Model 80: https://pastebin.com/Z1u9pwv1

If anyone can reproduce the issue, please look into it and find what might be causing it.

Thank you for your time. :)

**Comment by OBattler** [comment]
That's because device 1:0 is SCSI ID 0 on the second SCSI bus. What you want is 0:1 - SCSI ID 1 on the first SCSI bus.

As such, I'm closing this with notabug.

**Comment by ppgrainbow** [comment]
I also notice that the PS/2 SCSI Adapter code name is Spock and it uses SCSI IDs in reverse. As such, the first hard disk would be SCSI ID 6 and the second one would be on SCSI ID 5.

Anyways, thank you for explaining this. I appreciate it. :)
