### ISSUE TITLE
RAM speed emulation for the Everex RAM Deluxe 3000

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1905]
**Is your feature request related to a problem? Please describe.**

The Everex RAM deluxe 3000 is a 16 bit ISA EMS memory board. It  supports both 8 bit and 16 bit transfer modes, but the 16 bit transfers modes are supported on 286 6/8 Mhz and not on 10Mhz or faster. This is due the RAM chip speeds supported.
This card was launched around 1986 with the IBM AT 286.
I don't know if 86box emulates the RAM speeds of these old PCs.

Here is the link to manual: https://ibm.retropc.se/manuals/Everex_RAM_3000_Deluxe_EV-159_Ver_2.1_Nov87.pdf
The information is on page 24.

8-bit transfer mode: Uses 150ns RAM chips and works on all machines XTs and 286.
16-bit transfer modes: Card supports 120ns RAM chips that allows a 286/8 at maximum.

16 bit transfer mode and the relation between CPU clock/RAM speed:
286/6 requires 130ns RAM chips
286/8 requires 120ns RAM chips
286/10 requires 110ns RAM chips (Not supported by RAM Deluxe 3000)
286/12 requires 100ns RAM chips (Not supported by RAM Deluxe 3000)

**Describe the solution you'd like**
If the user selects a 286/10 or faster and the RAM Deluxe 3000 and 16-with transfer mode, make a message warning that let to choose either slow down the CPU clock to 8 Mhz or change to the transfer mode to to 8-bits.

**The real hardware will not work with 286 10Mhz or faster and the 16-bit transfer mode.**

**Comment by OBattler** [comment]
The manual actually says that 8-bit will work for certain with higher speed CPU's, but 16-bit may or may not work. So it's not certain that it won't work.

**Comment by OBattler** [comment]
Closing this until we get better data that shows what does or does not work work with what.
