### ISSUE TITLE
Tie Fighter DOS CD hangs just after DOS4G/W screen

### ISSUE THREAD

**Issue by Danfun64** [86Box/86Box#1912]
**Describe the bug**
I have recently installed WinBox for 86Box and have made a fresh VM using the 486 Multimedia PC template (Lucky Star LS-486E). After making some changes to the system, I formatted the disk and installed DOS 6.22, the OAKCDROM driver, the CTMOUSE driver, and the drivers from the AWE32 CD (whilst disabling the AWE32 specific drivers and I had it set to SoundBlaster 16) and ran Memmeker. With everything set into place, I installed the DOS CD version of Tie Fighter from its disk, set the sound card information, and loaded the game... and it froze on a black screen after DOS4G/W finished loading. I tried various things to get the game to run. I tried installing QEMM, changed the graphics card, changed the memory, turned off the sound support of the game, switched machines to a [ALi M1489] AMI WinBIOS 486 PCI, replaced DOS4G/W with DOS32A, running the Lucasarts Boot Disk, etc. Nothing seemed to work.

**To Reproduce**
1. Have a 486DX/2 DOS 6.22 VM prepared for 86Box
2. Install Tie Fighter CD with Maximum Install
3. Run the game
4. Hang after the DOS4G/W screen

**Expected behavior**
After the DOS4G/W screen, the opening cutscene will load.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H1 64-bit
 - 86Box version: v3.1.0 build 3353
 - Build information: WinBox for 86Box v1.0.0.962. 32-bit 86Box.

**Additional context**
In my attempts to get the game running, I attempted to run the DOS Floppy version of Tie Fighter and the DOS CD version of X-Wing. Both worked fine. Since neither of those ran with DOS4G/W, I tested a DOS4G/W game (Doom 2), which also ran fine.

I have previously discussed this issue on the 86Box Discord server. gogogo did some troubleshooting and was able to get the game to run, albeit inconsistently. I never managed to get the game to run at all.

Attached is my 86box.cfg as well an html file containing a log of the Discord conversation (begins at page 2). If you wish to see my hard drive, I will post it for you
[86box.zip](https://github.com/86Box/86Box/files/7654967/86box.zip)
.

**Comment by Danfun64** [comment]
Another thing worth noting. I honestly thought the game worked in PCem, but with similar settings (486DX2-66, AMI WinBIOS 486 PCI) I get the same result.

**Comment by Danfun64** [comment]
I confirmed that it works in PCem v14 with the v11 roms, but not with the latest 86box... and presumably not the latest PCem either. Strange...

**Comment by Danfun64** [comment]
I was wrong on the PCem front. With PCem it was "AMI WinBIOS 486" that worked, which appears to translate to "Kaimei 486" according to 86Box... except I'm not sure that's working either.

**Comment by Danfun64** [comment]
Whatever the problem is, I think it has to do with hard drive generation. The game refuses to load if I create a hard drive in Winbox (or at least if I try to create a 2gb one in Winbox following the values in https://www.computerhope.com/hdwd.htm) but when I use the 2gb hard drive from https://sites.google.com/site/dotalshoff/games/dosbox it works, even if I format it.

**Comment by OBattler** [comment]
This wouldn't be the only thing affected then. I noticed that Windows 95 OSR 2.x FDISK also creates a complete mess of a FAT16 partition in 86Box (but somehow, has no problem with FAT32), but if I use MS-DOS 6.00 FDISK, it creates a properly working partition.

But, you're using MS-DO 6.22 - I haven't tried that yet. Perhaps the "bad" code is already there.

**Comment by OBattler** [comment]
Could it be a BIOS incompatibility? Since a lot of those 486 BIOS'es didn't really properly support hard disks bigger than 503 MB (the CHS limit).

**Comment by Danfun64** [comment]
When I was experimenting on getting things to work, I was running an old version of PCem (v14) with an even older rom set (v11). PCem v14 and the latest 86box (not sure about PCem v17) seem to handle large hard drives differently. PCem v14 (at least with AMI WinBIOS 486) recognized the large hard drive in the bios and could presumably use all 2GB of the pre formatted Dosbox hard drive file, but fdisk in both the WIN98SE boot disk and the Freedos 1.3 RC5 boot disk only saw 503 MB. Format C: worked with the former but the latter refused to work. In contrast, fdisk recognized the full storage of the hdd-2gb.img file with both boot disks as well as the wiped and reinstalled DOS 6.22 installation, and format C: worked with the Freedos boot disk and presumably works with WIN98SE boot disk as well.

My guess is that the problem might involve however partitions are made. I also had problems with a WinBox 2gb file whether I used win98se's FDISK or let DOS 6.22 configure the unpartitioned space in the installation.

**Comment by OBattler** [comment]
If FDISK only saw 503 MB, it means that while the BIOS saw all the 2 GB, its INT 13h calls only support up to 503 MB. That's exactly what I was talking about above. You need a BIOS with LBA support, try the Zida 4DPS or the Soyo 4SAW2. Yeah, they have Award BIOS instead of AMI, but AMI tended to lag behind Award in terms of support for such stuff back then.

**Comment by Danfun64** [comment]
That was for PCem v14 though. 86box doesn't have that problem... but who knows?

**Comment by OBattler** [comment]
I believe you used a machhine (with, I believe, a later BIOS version) on 86Box, which may explain the difference.

Also, try generating the hard disk image with 86Box itself instead of with WinBox.

**Comment by Danfun64** [comment]
I'm sorry that I haven't tried the "generating the hard disk image with 86Box itself instead of with WinBox." bit yet.

Something new just happened after a recent 86box update using the same hard drive file I was always using. Now 86box crashes to desktop with no error message after the DOS4G/W screen.

**Comment by Danfun64** [comment]
Now having tried X-Wing CD, *that's* crashing as well. What the heck?

**Comment by r3tr0g4m3r** [comment]
I have this problem, TIECD drops dead if installed to any other drive than C, i cloned my WIN95 setup in IMG format into dynamic VHD , back and forth using Norton Ghost (Norton.Ghost.11.5.Corporate.DOS.Boot.CD.iso), but TIE FIGHTER only fails if installed to other than C, in my case D:
![tiecd_installed_in_D](https://user-images.githubusercontent.com/3663416/210280634-33e12c55-6e32-475a-bf8e-0f6af7ee2ffa.png)

Installed to C drive works as intended, both drive C and D in my system are dynamic vhd's:
![TIECD_installed_in_C](https://user-images.githubusercontent.com/3663416/210280901-41ddcbc4-238e-476d-8c66-ba2993a66488.png)
This is my machine configuratión for testing:
[86box.zip](https://github.com/86Box/86Box/files/10333597/86box.zip)

**Comment by OBattler** [comment]
Also reported here, also involves XWINGCD: https://github.com/86Box/86Box/issues/2130 .

**Comment by ualaa1** [comment]
I also had a similar problem with Tie Fighter CD not loading. I installed maximum install with SB32 for sound effects and general midi for music. I used an Asus PCI/I-486 with a i486 DX 2 WB using version 4.0.1 on Windows 10. My HD is configured to LBA mode with 3 GB and uses the dynamic HDs. It also initially went to black screen, although I noticed it was loading off the CD during the black screen before the freeze. When I turned off dynamic recompiler, the game seemed to boot as normal and so far I have not seen any problems with it

**Comment by OBattler** [comment]
So it's a bug with the dynamic recompiler.

**Comment by eddmanx** [comment]
I used the config file posted in the OG and the game works fine with build 5434, with both ODR and NDR.

**Comment by OBattler** [comment]
Then this can be closed.
