### ISSUE TITLE
86Box x64-b3354 Full Screen Problem

### ISSUE THREAD

**Issue by Mast3rBlast3r** [86Box/86Box#1917]
I started EXE from desktop icon, first time.. checked that Action/Keyboard requires Capture thing, then I pressed ALT+CTRL+PageUP and 86Box entered full screen mode, then I came out of full screen mode with ALT+CTRL+PageDown and.. and then I tried to enter full screen mode again, but it couldn't, I just got some flashing on screen, very fast and nothing happened, even after closing and restarting it could not enter full screen mode twice, only once.. this happened to build 86Box-Windows-64-b3354, under Windows 10, with Ryzen 5 and B450 AORUS M motherboard with nVidia GeForce graphics driver version 496.13 

then I also checked the build 86Box-Windows-32-b3336, and it works properly..

**Comment by dhrdlicka** [comment]
Hello, your bug report contains way too many variables that could affect this.

Could you please determine the following:
* Does this work with the latest **32-bit** build?
* If not, does this work with the **64-bit** compile of **build 3336**?

**Comment by Mast3rBlast3r** [comment]
the last 32 build works well, this is all about 64-bit compile x64-b3354.. 64-bit compile can't enter full screen twice..

I haven't tested 64-bit compile 3336, I don't have that version..

**Comment by OBattler** [comment]
Closing this because incomplete bug report, the user hasn't performed the required test, and no feedback in almost a year.
