### ISSUE TITLE
With S3 graphics, garbled screen after I leave MS-DOS prompt

### ISSUE THREAD

**Issue by renanbirck** [86Box/86Box#1922]
**Describe the bug**
After installing Windows 3.1 on an emulated machine with S3 graphics, when I leave the fullscreen MS-DOS prompt, the screen is garbled, as can be seen in the screenshot attached. Even after exiting Windows 3.1 and reentering it, the screen is still garbled.

I used this driver from [vogonsdrivers](http://vogonsdrivers.com/getfile.php?fileid=275&menustate=0).

**To Reproduce**
1. Open a MS-DOS prompt 
2. Exit fullscreen mode.

**Expected behavior**
The Windows desktop should be restored normally.

**Screenshots**
![w311_garbled](https://user-images.githubusercontent.com/553325/145315505-76d51720-0eac-4e83-91fc-d52648fe0399.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: 3.0 build 3366
 - Build information: old recompiler

**Additional context**
[config file](https://github.com/86Box/86Box/files/7681442/86box.cfg.txt)

**Comment by OBattler** [comment]
Which emulated graphics card are you using?

**Comment by renanbirck** [comment]
S3 Trio64 (Phoenix), but still happens with other S3 Trio64 models and at any resolution I use in the guest.

**Comment by renanbirck** [comment]
FWIW, if I change the emulated graphics card to "S3 Trio64V2/DX", the glitches don't seem to happen.

**Comment by TC1995** [comment]
That's weird as I haven't got this issue lately, need to check again.

**Comment by TC1995** [comment]
Hmm, does this also happen with other machines, like, socket 5 or 7? (I see you're using a socket 4 one, just in case)

**Comment by renanbirck** [comment]
With a Socket 5 machine (Intel Premiere/PCI II), but with the same Windows 3.1 disk image I am using, it also happens.

**Comment by OBattler** [comment]
Since the Trio64 accelerator runs in its own thread, could there be a desync occurring on some hosts but not others? Because I remember similar glitches with the Paradise Bahamas 64 (S3 Vision 864) that one user had (but that was on Windows 98 SE) but none of us could reproduce.

**Comment by OBattler** [comment]
But, can you upload the entire VM (ie. 86box.cfg, NVR folder, and the hard disk image) so we can try to reproduce this?

**Comment by renanbirck** [comment]
It is here, as a 7z file about 85 MB: https://drive.google.com/file/d/117vFkezYkClqr1VptB5Eh9g4nTqRsoLb/view?usp=sharing

Password: 86box123

**Comment by TC1995** [comment]
turns out this is fifo related, but I luckily fixed this with threading the fifo again, but with some additional fixes to avoid the Visionx68 and Trio64v+ desktop wallpaper glitches in the video engine.
