### ISSUE TITLE
Add Windows Midi support to the Adlib Gold

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1930]
**Is your feature request related to a problem? Please describe.**
It's not a problem. 86box implementation of the Adlib Gold currently emulates the synth mode and the features needed for the few DOS games that suport it, such as Dune and the Surround module on Dune 2. But the real card can reproduce midi files under Windows 3.1 with both mappers synth and MIDI. But only Synth is supported. Synth mode does not sound as good as MIDI when playing MIDI files or playing Win 3.x games that supports sounds, like The Incredible Machine for Windows.

![Adblib Gold MIDI](https://user-images.githubusercontent.com/31600563/145703554-b3dbdfa5-441e-4716-9872-ac13621f12ed.png)

Here is a Vogons thread with a comparison between Adlib Gold and SB 16. The Gold sounds very good for being a 8-bit ISA card.
https://www.vogons.org/viewtopic.php?f=62&t=40267&p=371436&hilit=adlib%20gold#p371436

**Describe the solution you'd like**
I'd like the implementation of MIDI map support to the Adlib Gold.

**Describe alternatives you've considered**
There are drawbacks, however. The main, is very few DOS games support it. So this enhancement only will affect the Windows games and applications, and of course the documentation and the time to implement it.

**Comment by ts-korhonen** [comment]
I think you are confused about the driver options. The "SYNTH" means it's using OPL to emulate midi instruments like regular adlib and sound blasters. "MIDI" means the midi output of the card. The real card has OPL chip and digital audio sampling as the means to produce sound and music.

Also no sound card processes midi files, midi mapper is software and not something implemented by the emulator.

**Comment by Fenix770** [comment]
But if I select Gold Midi as maper. and play a midi file the emulator crash. I reported this as a bug on PCem in 2017, and Sarah said this was not a bug but a not implemented emulation.

**Comment by OBattler** [comment]
Is there any documentation of this anywhere?
