### ISSUE TITLE
Diablo II Glide Choice Crashed 86Box

### ISSUE THREAD

**Issue by Mast3rBlast3r** [86Box/86Box#1934]
**Describe the bug**

Diablo II has exe module for video driver choice, after launch he will offer 3dx Glide rendering as Default, but you have Direct3D option too.. I tested them both, they work fine, game is playable.. but I noticed something weird, after I confirmed Glide choice, and tried to launch Diablo II from desktop icon, 86Box disappeared from my desktop.. after restart, tried again to change video mode, into Direct3D, then close module, then open again and change into GLide, then to start Diablo.. game crashed again after launch and after first video is played.. game crashed third time after video mode change, so something buggy is there enough powerful to crash emulator..

**To Reproduce**

Install Diablo II and try to change video driver and to launch game immediately thereafter..

**Expected behavior**

to switch between video drivers should be non dangerous operation for emulator, something you can do whenever you want..

**Screenshots**

I have proof, I played Diablo II in Glide and Direct3D mode in 86Box, plus EXTRA, I played successfully Jetboat Superchamps I and II, and Screamer 2, these games never failed..

**Desktop:**
 - OS: Windows 10
 - 86Box version: v3.00 build x32-b3336
 - Build information: My Standard Asus Machine with 2 ATAPI CDROMs

**Additional context**

the best way to play safe Diablo II game is to confirm video choice, then restart Windows, then launch Diablo II
![86box Diablo 01](https://user-images.githubusercontent.com/95438261/145989368-161817d8-a16a-4bca-a674-986430921987.png)
![86box Diablo 02](https://user-images.githubusercontent.com/95438261/145989374-3a575e2e-92d0-41f4-a913-f8ef144d6889.png)
![86box Diablo 03](https://user-images.githubusercontent.com/95438261/145989378-0f45361b-9a64-44ae-a66c-42ac0254bdb1.png)
![86box Diablo 04](https://user-images.githubusercontent.com/95438261/145989388-d9d7a712-9c7d-457b-865d-c25218f3f427.png)
![86box Diablo 05](https://user-images.githubusercontent.com/95438261/145989394-944425a5-94b4-43c0-be08-ee9de702cce8.png)
![86box Diablo 06](https://user-images.githubusercontent.com/95438261/145989403-1dbe9e19-9162-4319-9744-6787e52e2488.png)
..

**Comment by OBattler** [comment]
Does this still occur? I know there was a bug which was causing some games to not start with the Voodoo, that has since been fixed.

**Comment by Krathoon** [comment]
I have been getting blue screens with the Voodoo3. I tried a wide variety of drivers, so I think it is an emulation issue.  I was playing the demo of this old game called Desperadoes and it crashed.
Usually, I don't get the blue screens during games.

**Comment by eddmanx** [comment]
Tested with build 5434 32-bit using the same Asus P55T2P4 board and a V3 3000 PCI, both ODR and NDR, with V3's dynarec enabled, and I can switch between modes and re-launch the game just fine.

**Comment by OBattler** [comment]
Then this can be closed.
