### ISSUE TITLE
Auto redirect the keyboard when navigating the menus

### ISSUE THREAD

**Issue by Dungeonseeker** [86Box/86Box#1935]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem but when using the KB to navigate menus, any menu inputs are also sent to the VM

**Describe the solution you'd like**
An option to have 86Box redirect the KB away from the VM when any menu is clicked

**Comment by OBattler** [comment]
Try the "Keyboard requires capture" option, then the guest will only receive input when the mouse is captured.

**Comment by OBattler** [comment]
I'm closing this since the request is already fulfilled with the "keyboard requires capture" option.
