### ISSUE TITLE
[BUG] Win-OS/2 subsystem problems

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#1939]
I would like to report numerous issues involving the Win-OS/2 subsystem when used under OS/2 2.1x (I have not tested OS/2 2.0 or OS/2 Warp 3 at this time).

Every time I try to run the Win-OS/2 sub-system under OS/2 using the ET4000 large fonts driver, the Win-OS/2 window does not display. All it displays is "Loading, please wait...", the test on the upper portion of the screen turns red and hangs there:
![20211217-053502-976](https://user-images.githubusercontent.com/32658796/146494630-121c1898-cfdb-45b8-a8e6-eca9dbf6692e.png)

The issue pins down to the WSPDRF.DRV full screen display driver located on line 11 of the SYSTEM.INI file in C:\OS2\MDOS\WINOS2 sub-directory.

If I comment out the WASPDRF.DRV full screen display driver and replace it with a standard VGA driver, the screen appears to display normally:
![20211217-054212-810](https://user-images.githubusercontent.com/32658796/146495126-a99e434d-2485-4efd-ac45-9c676527e03e.png)

But when I exit the Win-OS/2 subsystem, the screen turns black and I have to reboot:
![20211217-054316-995](https://user-images.githubusercontent.com/32658796/146495229-1d5405b6-7043-4d2f-bce3-5a131830ecef.png)

Here is the 86Box.cfg file for preference: https://pastebin.com/7hWnZu6s

Can anyone investigate which build caused problems with the Win-OS/2 subsystem under OS/2 2.1 and try to fix this issue? Thank you for your time. ^_^

**Comment by HanHeld** [comment]
I tried to test this out on a HP Vectra 486 (Tseng labs ET4000/w32i Rev. B video card) with OS/2 Warp and got weird, stretched screens -even using both of the included Tseng video drivers. 

I didn't even get to the point where I could try winos/2
![20211217-100545-591](https://user-images.githubusercontent.com/3117821/146528206-25fe01d2-12d6-44f1-9eed-3589e9e69b97.png)
.

**Comment by ppgrainbow** [comment]
Oh dear!

> I tried to test this out on a HP Vectra 486 (Tseng labs ET4000/w32i Rev. B video card) with OS/2 Warp and got weird, stretched screens -even using both of the included Tseng video drivers.
> 
> I didn't even get to the point where I could try winos/2 ![20211217-100545-591](https://user-images.githubusercontent.com/3117821/146528206-25fe01d2-12d6-44f1-9eed-3589e9e69b97.png) .

Oh dear! That doesn't sound good. :(

I'm wondering have you have tested OS/2 2.1x and Win-OS/2 with the SVGA drivers yet?

**Comment by HanHeld** [comment]
Not yet, I mostly chose warp because it's late and I could do it from CD. 
I'll try installing 2.1 on it after I get up and If I have better luck with video, I'll test Win-OS/2 too. I'll post my results when I'm done.

**Comment by TC1995** [comment]
ppgrainbow, why is your video card set to tvga8900d when it should be et4000?

**Comment by HanHeld** [comment]
@ppgrainbow I installed OS/2 2.1 on the same VM and I was able to enter and exit Win-OS/2 just fine. 
https://gyazo.com/b21c474d71e5a249d57e784acbc73b85

**Comment by ppgrainbow** [comment]
@TC1995, apparently, I'm using the SVGA drivers that came with OS/2 2.1 which supports 640 x 480, 800 x 600 or 1024 x 768 8-bit colours. :)

So, something appears to be messed up here. I'll do a test install of OS/2 2.1 either on 86Box or on a different virtualiser and then revert to VGA..

@HanHeld, do you have any idea what graphics card that you used to install OS/2 2.1? I'm just curious.

**Comment by HanHeld** [comment]
@ppgrainbow I used this one:  
![TsengLabsET4000](https://user-images.githubusercontent.com/3117821/146609959-f943c94d-2ec8-449c-9f73-dd4b0adb792f.png)

**Comment by ppgrainbow** [comment]
@HanHeld It looks good so far. Have you been able to enter DOS fullscreen mode and/or Win-OS/2 fullscreen mode and exit?

Also, have you tried running OS/2 2.1 with the Trident 8900D driver yet?

**Comment by HanHeld** [comment]
I'm going to post here what I posted on Discord so it's easier to find. tldr -I can't figure out WTF the procedure to install the driver I found is.
paste begins:
I can't figure out what they want; I have installed the driver to C: (and inserted the display driver disks when prompted) and using both "selective install" and "device driver installation" both fail with this error -both when I point them at a: and when I point them at c:\tros2drv (the folder created by the dos setup program)
![20211217-220050-735](https://user-images.githubusercontent.com/3117821/146613644-7772cce7-7f30-471c-a24e-b7d855f7764e.png)

Alternately -that's an upgrade that requires an already installed Trident driver? That doesn't make sense to me, but it's all I can think of.
paste ends

**Comment by ppgrainbow** [comment]
Have you read the README.TXT file to see how you can install the Trident 8900 drivers under OS/2 2.1 yet?

**Comment by HanHeld** [comment]
I've read the readme.doc (here: https://pastebin.com/2yh9Ezpg ) and tried the procedure again. This time I got the same result as in my last post but I tried running dspinstl and selecting 1024x768 and wound up with this: 
![20211219-072644-441](https://user-images.githubusercontent.com/3117821/146667284-53ea1c02-5cf1-412c-9b35-67618c931b49.png)

I'll try a fresh install and re-copying the drivers and see what I get. 
Before I switched to 1024x768 I was able to do win-os/2 full screen and exit. I'm just not sure if I was using the correct drivers (but at 640x480)

**Comment by HanHeld** [comment]
I tried a reinstall, following the steps in the readme -and still wound up with a garbled screen. Picking the et4000 driver didn't work (it didn't find whatever file it needed) but it would let me pick the trident driver -and get a garbled screen on reboot. 

Sorry, I can't crack this nut.

**Comment by ppgrainbow** [comment]
Good to hear that. I've just uploaded the VM including the hard disk images, CFG file and NVR along with screenshots so that I can have OBattler look into this issue on what could be causing this. :)

**Comment by OBattler** [comment]
Given how much has changed since then, I'm closing this issue as stall.
