### ISSUE TITLE
Freezing in Fire & Ice when choosing Soundblaster sound

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#1942]
**Describe the bug**
This could potentially be my fault as I am using a Soundlaster AWE32 instead of a more period-appropriate Sound Blaster card , but choosing soundblaster as the sound causes it to freeze on the next screen. If it is my fault, please close this issue
**To Reproduce**
In game, choose soundblaster as sound, then it freezes on the next screen. Choosing other sound options do not freeze the game.

**Expected behavior**
Game should not freeze.

**Screenshots**
![20211218-010622-750](https://user-images.githubusercontent.com/68984176/146623992-c2a2b5c4-dd05-4081-8d9e-484c165eaf68.png)
Sound Options
![20211218-010651-549](https://user-images.githubusercontent.com/68984176/146623998-508a03a1-d124-4ad0-a49a-39f8b51a281d.png)
Freeze screen when choosing sound blaster

**Desktop (please complete the following information):**
Windows 10 v.3.00 build 3333 64 bit

**Additional context**
Some audio card information which might help the devs.
![20211218-011509-452](https://user-images.githubusercontent.com/68984176/146624075-f71614d9-9a93-4e22-88e2-d1edc1164d27.png)

 I am also running a 486 Sis 496 at 40 mhz with a S3 virge card.

**Comment by OBattler** [comment]
The same kind of AWE32 problem reported here with another game as well: https://github.com/86Box/86Box/issues/1961 .
