### ISSUE TITLE
XT machines Bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1949]
**Describe the bug**
The XT machines does not work correctly with Geoworks. The hard disk controller is XTA-IDE.

Bugs: 
1. On Amstrad 3086 the keyboard suddenly start to works as if CAPS LOCK keys is always pressed.
2. On Geoworks 1.0 system configuration after installation Functiosn keys F1-F11 and Enter stop wroking.
3. On the Deskpro 8086 and 8088 Super XT an "Bad handler passed to system" appears.

Here is the HD and CFG files:
[Amstrad 3086 XTA-IDE.zip](https://github.com/86Box/86Box/files/7742442/Amstrad.3086.XTA-IDE.zip)
[Amstrad 3086 XTA-IDE-CFG.zip](https://github.com/86Box/86Box/files/7742443/Amstrad.3086.XTA-IDE-CFG.zip)

**To Reproduce**
1.Configure the machine as Amstrad 3086.
2. Start the Machine
3. Type GEOS at DOS prompt

**Expected behavior**

**Screenshots**
![Geoworks 1 XT bug](https://user-images.githubusercontent.com/31600563/146709393-358e6d5c-d628-4254-93f9-d7e06d6dee1d.png)

**Desktop (please complete the following information):**
 - OS: Win 10 21H!
 - 86Box version:  v3.00 build 3333; and 3390
 - Build information: Win32 regular

**Aditional context**
 Geoworks v1.2 crash at DOS prompt after typing "GEOS" so I installed the v1.0 to check if the problem is some 286 real mode code on the v1.2.

**Comment by Fenix770** [comment]
I have discovered that same bug happens with ST-RLL controller. I have two VMs with two different HDs, one with WD XTA-IDE hard disk and other with ST-RLL Seagate. The machine with ST-RLL have the same problems, but they are less noticeable.

With the Amstrad 3086 and the RLL-ST.


1. After starting Norton Commander 3.0 the keys work as if CAPS LOCK were always pressed so the "4" do a #$# symbol.
2. Random crash or screen corrupted, only, when change video driver or mouse type with Geoworks 1.1.

In this screenshot the machine freezes here when changind from video mode from "VGA inverted mono" to VGA mono".

![freeze](https://user-images.githubusercontent.com/31600563/147599538-b1e11a75-f44f-45d5-aa17-e918aa5b60e8.png)

**Comment by OBattler** [comment]
Closing this as CANTFIX until the internal XTA controller is identified and its documentation found.
