### ISSUE TITLE
SCO OpenServer 5.0.7 crashes when you try to start the GUI

### ISSUE THREAD

**Issue by mjkerpan** [86Box/86Box#1951]
**Describe the bug**
The X11 GUI subsystem in OpenServer crashes with the following error when I attempt to launch the GUI: "WARNING: u_trap - Invalid TSS 0x0000000A". I tried to run this with both a Trio64 and an ET4000/w32 selected.

**To Reproduce**
1. Login to an installed SCO OpenServer system
2. Run "startx" or set the system to boot to the graphical login system

**Expected behavior**
The GUI system should start and the desktop should appear.

**Screenshots**
![20211220-020426-517](https://user-images.githubusercontent.com/9254521/146861365-562f6932-4e7e-4a0f-926f-fa82f0ef6e7b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3389
 - Build information: Default build

**Comment by OBattler** [comment]
I think this can now be closed.
