### ISSUE TITLE
Intro cutscene is a bit glitchy in 3 Sisters Story

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#1953]
**Describe the bug**
Intro has flashing lines and flashing garbage when transitioning from one scene to another.

**To Reproduce**
I tried every way to eliminate it, including changing graphic card from virge to normal VGA and other SVGA cards and CPU types and changing mhz, but it still persists. Note that you will need to REM Himem on config.sys, otherwise in-game after intro lags very heavily.  Not sure if that's also an 86-Box bug or not. However, if your not going in-game, then not doing REM to himem is fine also. 

**Expected behavior**
No flashing lines and flashing garbage.

**Screenshots**
See https://imgur.com/a/nbBaoLO for video

**Desktop (please complete the following information):**
Windows 10 v.3.00 build 3333 64 bit

**Additional context**
Ran game from 3sis.bat

**Comment by OBattler** [comment]
Is the emulator always running at 100%?

**Comment by ualaa1** [comment]
The emulator lags heavily when in-game for some reason unless its in 16mhz or the Himem got REM
I believe it runs around 100% during the intro cutscene

**Comment by eddmanx** [comment]
The "glitch" is normal. It's a transitioning pattern and happens on real hardware too.

The black vertical lines do seem to be a glitch but don't happen anymore in my tests with build 5434.

**Comment by OBattler** [comment]
Then this can be closed now.
