### ISSUE TITLE
Memory expansions not working on IBM PC (1981)

### ISSUE THREAD

**Issue by NixieLake** [86Box/86Box#1957]
**Describe the bug**
No matter how many ISA memory expansions I try to enable or disable on the IBM PC (1981) it always registers only the on-board ram.

**To Reproduce**
1. On an IBM PC (1981) machine
2. Enable an IBM PC/XT Memory Expansion peripheral starting at any address, for any size (also happens on all other cards)
3. Run machine in Cassette BASIC or PC Diagnostics diskette (1981)
4. Memory detected will only reflect memory on the system board but not from the expansion card

**Expected behavior**
Should total both system RAM and expansion RAM (i.e. 64k + 64k = 128k)

**Screenshots**
System: 
![pc-sys-mem](https://user-images.githubusercontent.com/31080981/147284195-a6a66daa-679d-4825-bf85-169273f612b7.png)

Memory expansion: 
![pc-mem-exp](https://user-images.githubusercontent.com/31080981/147284209-93ad2cb8-dfea-413a-b090-a22b88dd771d.png)

Cassette BASIC 1.00: 
![pc-cbasic-100](https://user-images.githubusercontent.com/31080981/147284225-992386fe-5aca-437b-a445-4a41c0e3dded.png)

PC Diagnostics 1.00: 
![pc-diag-100](https://user-images.githubusercontent.com/31080981/147284237-e44be433-69f1-4ef1-818d-38060f4fb6a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: v3.00 build 3333
 - Build information: The build from your github. Windows 64-bit zip
 - Host computer is a Dell G7 7700 laptop with GeForce RTX 2070, 32GB RAM, 1TB SSD, if that helps. Running all latest drivers
![host-id](https://user-images.githubusercontent.com/31080981/147284415-9fdc7368-b0dc-4346-b356-3882d665610e.png)

**Additional context**
I don't know if this is something Windows 11 broke, or if this is a known issue. I searched through the open issues and didn't find anything that I thought looked like this.

**Comment by jriwanek** [comment]
Being worked on, for note however IBM Cassette basic will only *ever* show a number lower than 64k as it wasn't ever designed to be able to access more than that.

Can confirm it's otherwise a bug though.
