### ISSUE TITLE
86Box crashes while Windows 95 is installing the AWE32 synthesis driver

### ISSUE THREAD

**Issue by JamieDoesStuff** [86Box/86Box#1958]
I first encountered this bug after upgrading from Windows 3.1 to Windows 95. Windows automatically tried to install the AWE32 driver, but it froze, and the emulator crashed. I should mention the card in question is the non-PnP revision.

**To Reproduce**
1. Install Windows 3.1
2. Upgrade to Windows 95 RTM
3. After the 1st reboot, Windows will attempt to install the AWE32 driver, will fail, and the emulator will crash.

**Expected behavior**
Windows installs the driver correctly, and the emulator doesn't crash.

**Desktop**
 - OS: Windows 10 x64
 - 86Box version: v3.1, build 3400
 - Build information: old dynarec, x64

**Comment by OBattler** [comment]
Since people doing this exact same thing on the 32-bit old recompiler have reported the problem not occurring, this is most likely another (and probably the earliest reported!) instance of the 64-bit old recompiler crash that has recently been fixed. As such, I'm cloisng this.
