### ISSUE TITLE
Windows NT 3.1 errors out about incompatible CPU on compatible hardware during setup

### ISSUE THREAD

**Issue by jdev15** [86Box/86Box#1967]
Windows NT 3.1 has a strict CPU check on the GUI part of setup where it will error out with the message "Setup cannot install on the current processor." if it detects a CPU that is different from the one it's expecting. According to a text file included in the Windows NT 3.1 disc (located in "SUPPORT/MAR94HCL.TXT"), it shows it supports up to the first generation of Pentiums released in 1993 for the Socket 4 platform.
86Box supports the motherboard of one of the OEMs listed in the text file mentioned, the Dell Dimension XPS 60. I tried replicating this PC, more or less as [Wikipedia](https://en.wikipedia.org/wiki/Dell_Dimension) listed it, and tried installing Windows NT 3.1 only for it to error out on the CPU check. I believe 86 Box isn't reporting the correct CPUID to the OS, causing it to error out.

**Steps to reproduce the behavior:**
1. Setup 86Box with a Socket 4 motherboard with a 60Mhz Pentium as the CPU;
2. Use the Adaptec AHA-154xC SCSI controller for the HDD and CD-ROM drive (HDD no bigger than 2GB);
3. Use the Microsoft Serial Mouse as an input device;
3. Boot the Windows NT 3.1 Setup from the Boot Floppy (available on [WinWorldPC](https://winworldpc.com/download/416e2fc2-b818-c39a-11c3-a4e284a2c3a5)) and have the installation CD inserted on the virtual machine;
4. Proceed with the Text Setup until it asks to reboot;
5. When it enters the graphic portion of setup the error message will appear

**Expected behavior**
Since the Socket 4 60Mhz Pentium is a known CPU, setup should proceed without the error message

**Screenshots**
![Captura de ecrã 2021-12-27 164119](https://user-images.githubusercontent.com/11444194/147491080-c15ab2c6-a5e4-456f-a08a-b4975821e28e.png)

**Desktop:**
 - OS: Windows 11 Enterprise
 - 86Box version: v3.00 build 3333;

**Comment by TC1995** [comment]
You most likely have a tampered copy, that is, do your initial.inf and setup.inf files have a date of 2003?

**Comment by jdev15** [comment]
> You most likely have a tampered copy, that is, do your initial.inf and setup.inf files have a date of 2003?

Interesting. Those files you mentioned do have a 2003 date. Never noticed that the WinWorldPC copy of Windows NT 3.1 was tampered with. I'll try using another copy of Windows NT 3.1 I have at hand that I'm positive is untouched and report back.

**Comment by jdev15** [comment]
Ok, can confirm the problem was the tampered WinWorldPC copy. 86Box world as expected with a regular NT 3.1 copy.
