### ISSUE TITLE
Window sizing issue on Bubble Bobble also featuring Rainbow Islands when choosing force 4:3

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#1973]
**Describe the bug**
On Bubble Bobble also featuring Rainbow Islands , which is Acclaim's 1996 port of Bubble Bobble and not the earlier one by Novalogic, when forcing 4:3 on the window on 86-Box settings in order to prevent the window from changing into all sorts of sizes, which this game loves to do.  Anyways, when choosing on the menu to play Bubble Bobble with the force 4:3 enabled, 86-Box's windows shrinks. I thought 4:3 was to prevent the windows from resizing, but I guess not? Not sure if this is a bug or not, but I might as well post.

**To Reproduce**
On View, set force 4:3 display ratio. Run the game. Choose Bubble Bobble.
Watch as 86-Box's windows shrink.

**Expected behavior**
Probably for the windows size to be the same

**Screenshots**

https://user-images.githubusercontent.com/68984176/147845482-8056055b-dfa6-4ee3-a99a-91eb769f7a79.mp4

**Desktop (please complete the following information):**
Windows 10 64 bit build 3333

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by Cacodemon345** [comment]
If you don't want the windows to resize, you either enable Resizable Window option or set the window size explicitly in Specify Dimensions dialog with locking enabled.

**Comment by ualaa1** [comment]
Thanks, resizable window seems to work

**Comment by OBattler** [comment]
I'm closing this because it has been determined to be NOTABUG.
