### ISSUE TITLE
HP Falcon motherboard (Asus MEB-VM)

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#1976]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
The HP Falcon motherboard (HP-branded version of the MEB-VM) was used in several HP Pavilion machines from 1998-1999. It contains an Intel 440ZX-66 chipset, an SMsC FDC37M702 Super I/O, an Award BIOS ROM with an SST chip, support for 2 PCI slots, 1 ISA slot, and 1 AGP slot, and an integrated ATI Rage IIc AGP GPU.

**Describe alternatives you've considered**
No HP Pavilion motherboards are emulated at present.

**Additional context**
FDC37M70x datasheet: 
[fdc37m70x_datasheet.pdf](https://github.com/86Box/86Box/files/7809870/fdc37m70x_datasheet.pdf)

HP BIOS ROM for Falcon 1.11: https://mega.nz/file/DlxQFaTb#B_OLcydObsjCpc3_hj1Ow7U9CXdtPHnU-FGHxuAFcQ0

I have not been able to find a datasheet for the ATI Rage IIc; this will have to be implemented at a later date. Until then, any other AGP graphics card should do the trick, although the restore media for machines that used this board (including the 6475Z and the 6468) do not contain drivers for other graphics cards.

**Comment by dhrdlicka** [comment]
Could you post a legible photo of the motherboard so that all the chips can be identified?

**Comment by headsetguy37** [comment]
As soon as I find one, I will. That might take a while.

**Comment by Evolution0** [comment]
Most legible is:
![s-l1600](https://user-images.githubusercontent.com/1984403/148283487-33c8cd6e-36f2-478a-b9c9-f03a7b343a2a.png)

Some of the finer text is an issue though.

**Comment by OBattler** [comment]
From what I can get, the board as the following:
- SM(S)C FDC 37M707 Super I/O chip with AMI keyboard controller;
- Intel 440 AGPset (440BX maybe?);
- What appears to be Intel PIIX4E;
- ATi 3D Rage;
- ASUS AS97127F Hardware Monitor;
- SST flash (but the sticker is makign it impossible to determine exactly which).

**Comment by atargalore** [comment]
it's a rage pro turbo..... not a rage iic
![Uploading 20220115_163441.jpg…]()

**Comment by atargalore** [comment]
![Uploading 20220115_165433.jpg…]()
![Uploading 20220115_165519.jpg…]()

**Comment by atargalore** [comment]
idk why my pics are not uploading.. here is a link to my google drive with some pics of inside my HP Pavilion 6465  asus MEB-VM

https://drive.google.com/folderview?id=11Es3QtvZwMHmcvI4R6AZWtOx4SDfYlOQ

**Comment by headsetguy37** [comment]
I guess there were two variants, then: One with a Rage IIC, and one with a Rage Pro Turbo. Evolution0's picture listed above definitely says "IIC".
Thanks for the much better pictures!

**Comment by atargalore** [comment]
> I guess there were two variants, then: One with a Rage IIC, and one with a Rage Pro Turbo. Evolution0's picture listed above definitely says "IIC". Thanks for the much better pictures!

if you need I can take more and or better pics.

**Comment by headsetguy37** [comment]
Found another picture online. The BIOS chip model number ends with "020"; I'm guessing it's a 29EE020.

![falcon_with_sst_chip](https://user-images.githubusercontent.com/9204574/166125520-6d8fd695-588f-4877-baff-380732123ce7.jpg)

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.

**Comment by TechGuyC** [comment]
Here is the Documentation for the ATI RAGE 3D 

[3drageprogguidew95.pdf](https://github.com/86Box/86Box/files/12550828/3drageprogguidew95.pdf)
