### ISSUE TITLE
FreeBSD 2.x detects ATAPI CDROM drives as hard disk

### ISSUE THREAD

**Issue by Teppic1** [86Box/86Box#1992]
**Describe the bug**

I tried on a few different machine types and got the same result every time. The CD is treated as a disk drive leaving it unusable and preventing installation.

Under VMware and qemu the CD is detected correctly and can be installed from normally.

**To Reproduce**
1. Boot using the boot image from this release http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/i386/2.2.8-RELEASE/floppies/boot.flp
2. Optionally use a bootable installation CD image http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/i386/ISO-IMAGES/2.2.8/2.2.8-mini.iso
3. Drive is detected as a regular IDE harddrive with a guessed geometry and is unusable by the OS. The BIOS can boot the CD but the OS will still detect it as a hard drive.

**Expected behavior**

Drive should be detected as a CDROM so it can be used to install the OS.

**Screenshots**

https://i.imgur.com/A5wnaDM.png

(wd0 here is an IDE hard drive and is correct, wd2 is the incorrect CD drive)

**Desktop (please complete the following information):**
 - OS: Win 10
 - 86Box version: 3.2 b3437
 - Build information: standard

EDIT:

This also affects FreeBSD 3.x releases.

**Comment by OBattler** [comment]
It says using BIOS values, so you have a misconfiguration in the BIOS. Go to CMOS Setup and reconfigure there.

**Comment by Teppic1** [comment]
> It says using BIOS values, so you have a misconfiguration in the BIOS. Go to CMOS Setup and reconfigure there.

No, that's not it. It's detected as a drive (that's the wrong driver for a CD drive). I tested with multiple machines with the BIOS set as CDROM, even booting as CDROM, and it's the same result.

**Comment by Teppic1** [comment]
Here is a screenshot from qemu using the same files. This is how it's supposed to be, and this works fine.

https://i.imgur.com/5RNsBdI.png

**Comment by OBattler** [comment]
Is the FreeBSD 2.x source code available anywhere? So I can at least attempt to see how it tells a CD-ROM drive apart from a hard disk, since that appears to be where it goes wrong.

**Comment by Teppic1** [comment]
Yeah there's a complete UNIX/FreeBSD repository on github that includes every FreeBSD release:

https://github.com/dspinellis/unix-history-repo/tree/FreeBSD-release/2.2.8

I'm guessing this is the file you need, as wd is the IDE driver:

https://github.com/dspinellis/unix-history-repo/blob/FreeBSD-release/2.2.8/sys/i386/isa/wd.c

**Comment by jv84** [comment]
FreeBSD 2.x is extremely old. Feel free to close this issue.

**Comment by OBattler** [comment]
Committed a tentative fix for this, see if it now works.

**Comment by Teppic1** [comment]
Doesn't seem to have changed anything unfortunately (assuming b3628 has the change):

https://imgur.com/a/vRqxl07

I tried also with pcem 17 and it's detected as a CDROM on that.
