### ISSUE TITLE
Acer V30 BIOS reports incorrect CPU speed

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#1993]
**Describe the bug**
When emulating an Acer V30 motherboard, the emulated CPU speed is reported incorrectly on POST for certain CPUs.

**To Reproduce**
1. Create an Acer V30 machine. Set the CPU to be a Pentium at 75, 90, or 120 MHz.
2. Load the BIOS setup defaults.
3. The POST screen will display the hardware information. The CPU is reported incorrectly as 100 MHz if you set the speed to 75 or 90, and 133 if you set the speed to 120.

**Expected behavior**
The POST screen should report the correct CPU speed.

**Screenshots**

![acer_v30_wrong_speed](https://user-images.githubusercontent.com/9204574/149717493-d5a286b5-fce6-4e21-ac88-852a3547b8b9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, build 21H1
 - 86Box version: 3.2, build 3437.
 - Build information: Regular build, 32-bit.

**Additional context**
I have not tested any non-Intel CPUs to see if their speeds are reported correctly.

**Comment by OBattler** [comment]
This happens because the dynamic recompiler runs the timers after every block of instructions instead of after every instruction like the interpreter does. There is no way I can fix this.
