### ISSUE TITLE
Toolbar not showing after switching from fullscreen to windowed mode

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1994]
**Describe the bug**
Toolbar not showing after switching from fullscreen to windowed mode. This happens on all renders in 86Box. Sometimes the toolbar flickers on the screen (meaning it's on), but still the toolbar doesn't show up.

**To Reproduce**
1. Start the machine in 86Box with toolbar enabled.
2. Switch the 86Box machine to full screen.
3. Switch the 86Box machine to windowed mode.
4. See error.

**Expected behavior**
The toolbar should display normally when switching from fullscreen to windowed mode.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.2 x64 Build 3437
 - Build type: regular, old recompiler.

**Comment by OBattler** [comment]
Closing this because the bug has since been fixed.
