### ISSUE TITLE
Full Screen LED indicators (overlay) for Disk activities (like WinUAE)

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#1996]
Hi, I wonder how many do have interest in this. I always liked to see the disk activities while in full screen in WinUAE. 
![Screenshot_20220118_091316](https://user-images.githubusercontent.com/44859748/149854093-e39926b0-c00f-4bed-aede-c3fa278ae5ec.png)

Is this possible to do in 86Box? Each indicator labelled with Floppy A:, Floppy B:, HDD C:, CDROM D:, and so on, with read activity in green and write activity in red?

Sorry if asking too much, and I can't code, but I thought it would be useful in fullscreen.

Thank you for having a look at this feature request. 

Edit: As an option in the menu, to turn it on or off for personal preference.

**Comment by Mal752** [comment]
Floating the icons set (at the bottom of the 86Box window) in fullscreen will be nice too, since the icons are already in place with disk activity led button already implemented.

**Comment by Mal752** [comment]
Thanks for this!!! The activitiy light is difficult to see in my 1920x1080 laptop screen, but this is a wonderful option to have!

**Comment by OBattler** [comment]
It turns out it's actually not doable because it can't be done with the OpenGL renderer so it will be removed, anwyay. Sorry for that.
