### ISSUE TITLE
Polish language

### ISSUE THREAD

**Issue by Fanta-Shokata** [86Box/86Box#2004]
Please add Polish language to the interface.

**Comment by jriwanek** [comment]
We'll be glad to! just give us a translation, go here to start: https://github.com/86Box/86Box/blob/master/src/win/languages/en-US.rc. filename you'll want to use I believe is pl-PL.rc

**Comment by dhrdlicka** [comment]
Added in https://github.com/86Box/86Box/commit/013b42777b5e76877e80c8f378a27bd328fc316c.
