### ISSUE TITLE
Display surface doesn't get refreshed when setting VGA Color Select Register

### ISSUE THREAD

**Issue by Stellaris-code** [86Box/86Box#2005]
**Describe the bug**
Loading the VGA Attribute Address Register with the Attribute Color Select Register index and the PAS bit set and changing the Color Select Register doesn't appear to refresh the GUI display surface. Forcing a redraw by minimizing and maximizing the window shows that the then framebuffer appears to contain the expected pixels.
Forcing the PAS bit to 0 when writing the Attribute Color Select Register results in the correct behavior.

**To Reproduce**
1. Load a compatible machine with a VGA card set as display.
2. Load a 5.25" 180k floppy drive with the following image : [floppy_image.zip](https://github.com/86Box/86Box/files/7912544/floppy_image.zip)
3. Hard reset the machine and boot

**Expected behavior**

When clearing the PAS bit, the screen is properly refreshed and the expected behavior is observed :

https://user-images.githubusercontent.com/8571612/150513168-6253d479-a44c-4d3e-a912-6aad732cc243.mp4

**Screenshots**
If the PAS bit is set when loading the attribute register address, and only the color select is modify, the screen doesn't get refreshed. Forcing a redraw by minimizing and maximizing the window shows that the code behave correctly, but it appears that 86box doesn't recognize the Color Select Register change alone as a reason to update the display.

https://user-images.githubusercontent.com/8571612/150513402-5231f2f3-62b7-4dde-9e4a-91f9210da093.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: v3.1 [build 3400] [bb0d48f6]
 - Build information: not a custom build

**Additional context**
The code used to trigger the bug and a build script : 
[bug_code.zip](https://github.com/86Box/86Box/files/7912583/bug_code.zip)
The code changing the color page related to the PAS bit is the 'change_color_page:' function, starting from line 131.

I suspect the issue is related to this part of the svga video code:
https://github.com/86Box/86Box/blob/0b78a3941b6fcbd32cb877a0806e509b88be8700/src/video/vid_svga.c#L97-L123
Modifying the Color Select Register at index 0x14 should probably trigger a change to the 'svga->fullchange' variable.

**Comment by OBattler** [comment]
I have just committed a potential fix for this based on your suggestion, see if it truly fixes it.

**Comment by OBattler** [comment]
Closing this beacause it's tentatively fixed, it can be reopened if it's not.

**Comment by Stellaris-code** [comment]
Apologies for the delay, I confirm this commit fixes the issue.
