### ISSUE TITLE
IDE (1,0) can't work on ASUS P/I-P65UP5 (C-P55T2D)

### ISSUE THREAD

**Issue by MyBlueHorizon** [86Box/86Box#2009]
**Describe the bug**
IDE (1,0) can't work on ASUS P/I-P65UP5 (C-P55T2D)

**To Reproduce**
1. Select ASUS P/I-P65UP5 (C-P55T2D) as motherboard
2. Select CD-ROM on IDE (1,0)
3. IDE (1,0) can't work
4. Select CD-ROM on IDE (0,1)
5. Work

**Expected behavior**
IDE (1,0) can work

**Screenshots**
![图片](https://user-images.githubusercontent.com/20754543/151075985-31839071-751f-4e0c-8be1-0c33678e8420.png)
![图片](https://user-images.githubusercontent.com/20754543/151076040-1a9d33b0-6db1-4128-bb3e-5cefa6baf39e.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - 86Box version: v3.1.0.3400
 - Build information: old dynarec, x86

**Comment by TC1995** [comment]
Make sure the secondary IDE controller is enabled in the cmos too.

**Comment by MyBlueHorizon** [comment]
I'm sure that the secondary IDE controller is enabled in the cmos.
![图片](https://user-images.githubusercontent.com/20754543/151082358-0069cb60-04ad-4087-b4c4-51c6b4594e1a.png)

**Comment by MyBlueHorizon** [comment]
I'm sure that the secondary IDE controller is enabled in the cmos.
![图片](https://user-images.githubusercontent.com/20754543/151082358-0069cb60-04ad-4087-b4c4-51c6b4594e1a.png)

**Comment by MyBlueHorizon** [comment]
I'm sure that the secondary IDE controller is enabled in the cmos.
![图片](https://user-images.githubusercontent.com/20754543/151082358-0069cb60-04ad-4087-b4c4-51c6b4594e1a.png)

**Comment by TC1995** [comment]
not only there, but in the drives detection too.

**Comment by TC1995** [comment]
Weird, the secondary IDE controller driver works fine here, at least no code 10.

**Comment by OBattler** [comment]
I did my research on this since it was reported and it turns out that on boards like these that have an I/O APIC (it's not emulated but that's not that relevant here) wire the secondary IDE IRQ directly to legacy IRQ 15 instead of to MIRQ0. I need to add a separate type of PIIX3 that does that.

**Comment by OBattler** [comment]
See if it works now.
