### ISSUE TITLE
Crash after installing SFFT drivers to 3DFX graphics card

### ISSUE THREAD

**Issue by MrPepka** [86Box/86Box#2014]
**Describe the bug**
After installing the SFFT drivers to the 3dfx voodoo 3 graphics card, 86box crashes when starting a virtual machine with the error "Unknown banshee_cmd_read dc080040" and it freezes
Sometimes the system has time to boot, but moments later the 86box crashes

**To Reproduce**
1. Download 3DFX SFFT drivers - http://falconfly.3dfx.pl/voodoo3.htm
2. Install it with Device Manager (use the "Have disk" option)
3. After install drivers reboot virtual machine
4. An error will appear

**Expected behavior**
The system in this program should boot normally

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.1 build 3400

**Comment by MrPepka** [comment]
Oh, I forgot to mention. The system that I run in 86box is Windows XP SP3 Professional PL

**Comment by TC1995** [comment]
Most likely a wrong fatal.

**Comment by Gogo268** [comment]
able to reproduce with Voodoo3 AGP on XP SP1, with SFFT latest drivers from the same page, emulator crashes on both dynarecs when 3D is utilized.

**Comment by Cacodemon345** [comment]
Which error appears?

**Comment by Gogo268** [comment]
userIntrCMD write 00000006 from FIFO

**Comment by MrPepka** [comment]
Even on the latest version of 86box, there is a crash after installing the SFFT drivers. I checked both the latest version and older versions. Is it possible to fix this error?
