### ISSUE TITLE
MS CD-ROM drivers not working with ASUS P/I-P65UP5 (C-P55T2D)

### ISSUE THREAD

**Issue by pgalbraith** [86Box/86Box#2024]
Using WinBox I created a "Pentium PCI" system using all defaults, which chooses the "ASUS P/I-P65UP5 (C-P55T2D)" socket 7 board with internal IDE controllers and a CD-ROM on secondary master.  When booting, the BIOS reports detection of hard drive on primary master and CD-ROM on secondary master, which seems fine.

However, none of the standard MS CD-ROM drivers seem to work with this setup (e.g. trying boot disks from https://www.allbootdisks.com/download/95.html) ... for example, the Oak CD-ROM driver reports "No drives found, aborting installation".

A simple change of board to "ASUS P/I-P55T2P4" fixes things up, and the standard Oak CD-ROM driver works fine.  Am I just missing some necessary setting for the "ASUS P/I-P65UP5 (C-P55T2D)" board & CD-ROM to work properly?

![bios](https://user-images.githubusercontent.com/19995454/151674848-0f562883-5816-4085-8d09-6855a0eb340a.png)
![error](https://user-images.githubusercontent.com/19995454/151674849-ea95d197-9350-44df-accc-77592940091f.png)

**Comment by OBattler** [comment]
See if it works now.

**Comment by pgalbraith** [comment]
Fantastic, yes working now.  Thanks!
