### ISSUE TITLE
8086/8088 emulation fails test provided by Intel to check if an 8086 is present

### ISSUE THREAD

**Issue by shadowofneptune** [86Box/86Box#2037]
**Describe the bug**
In [this document](http://kib.kiev.ua/x86docs/Intel/AppNote485/241618-005-mn.pdf), Intel described a method for a program in real mode to check which processor it is running on. It relies on the fact that the top nibble of the flags register is always set high on the 8086/8088. I wondered if 86box can pass this test, so I compiled this program and tested it on the IBM PC 86box offers. 

**To Reproduce**

- Assemble the source code provided below, or use the binary included.
- Load the program onto a floppy disc image
- Start up an IBM PC emulation inside 86box
- Load the floppy, and run the program
- You should see that it prints this message:
![image](https://user-images.githubusercontent.com/56777828/152225964-eee36b7d-34dd-4bb0-baab-772df1e3ffe1.png)

**Expected behavior**
An IBM PC should be able to pass this test, as it uses an 8088.

**Desktop (please complete the following information):**
 - OS: Wine version 4.0, on Debian 10
 - 86Box version: v3.1 build 3400
 - Build information: N/A

**Additional context**
I built the binary included below with MASM 3.0 inside DOSBox.
[8086CHEK.zip](https://github.com/86Box/86Box/files/7989626/8086CHEK.zip)

**Comment by KeishiX** [comment]
Your code seems to be wrong. In the AP-485 second conditional jump is, as the comment says, jump if processor is 8086/8088. And in yours it is if not 8086.

**Comment by shadowofneptune** [comment]
My mistake, I should have double checked before reporting. With that change the code works as intended.
