### ISSUE TITLE
Wrong RAM size in [GC100A] Philips P3120

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2046]
**Describe the bug**
Wrong RAM size in [GC100A] Philips P3120 in 86Box settings window: 768 KBytes, while in POST it shows 640 KBytes. At the same time, in the 86Box settings window, the memory size cannot be set to 640 KBytes (after 512 KBytes, 768 KBytes is immediately selected).

**To Reproduce**
1. Select the machine [GC100A] Philips P3120
2. Try setting the RAM size to 640 KBytes
3. Start the machine [GC100A] Philips P3120 and see POST
5. Also open the 86Box settings window and you will see that instead of 640 KBytes, the value is set to 768 KBytes

**Expected behavior**
It looks like an error in the settings window 86Box: memory cannot be more than 640 KBytes. That is, the value 768 KBytes should not appear. 

**Screenshots**
![2022-02-04_150022](https://user-images.githubusercontent.com/58270614/152536005-5ba99738-1767-4426-9533-800b6f5df330.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.2 x64 Build 3478
 - Build type: regular, old recompiler.

**Comment by Fenix770** [comment]
I noticed that too. But the problem with XT machine is in most cases they only can "see" 640kb of RAM, there are exceptions like on this machine. To implement more than 640kb the documentation of these particular machines is needed and the "extra" RAM is not used by the 808x CPU but by third party hardware or chipset. 

One example is the Juko XT. This machine supports up to 1024kb on real harrdware. But the extra 384 kb of RAM is only used by a hardware chipset and can be enabled only by specific drivers that can use it as RAM drive, disk cache, or the print spooler.
It cannot be used for anything else. An experimental LIM EMS driver had been written to use it as expanded memory but puts the 64kb page frame on "low" memory (below 640kb) an reduces it on 64kb.

**Comment by OBattler** [comment]
Closing this for NOTABUG then.
