### ISSUE TITLE
Missing Qt libraries

### ISSUE THREAD

**Issue by Adrianwo99** [86Box/86Box#2061]
In the newest builds, I can't start emulator completely, as Windows requires to have three Qt libraries: Qt5Core.dll, Qt5Gui.dll and Qt5Widgets.dll. Libraries included with Qt Creator version 5.12.12 (after copying to 86Box installation folder) are not working. Can someone from emulator's development team include working libraries to Windows builds?

**Comment by dhrdlicka** [comment]
Build 3499 fixes that.
