### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by Fanta-Shokata** [86Box/86Box#2086]
86box CPU usage is very high when it's in idle state (around 50-60%)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H1
 - 86Box version: 3.2 build 3517
 - Build information: old dynarec, from Jenkins.

**Comment by OBattler** [comment]
Install an idle driver in the guest.

**Comment by Fanta-Shokata** [comment]
Already installed an idle driver, but problem still persists

**Comment by Fanta-Shokata** [comment]
386DX 40

**Comment by OBattler** [comment]
Does the latest build (that has switched back to Win32 on Windows) still have the issue?

**Comment by Fanta-Shokata** [comment]
Latest build doesn't have that issue.

**Comment by drfrag666** [comment]
For me it also happens with the latest release (3.2.1). I'm on win10 (AMD E2-9010, Radeon R2).

**Comment by drfrag666** [comment]
Yeah it's between 35 and 45%, a bit higher when idling it seems. Old version was below 10% most of the time. VM is a 386sx-33 with adlib. BTW what was that big blank window in 2.07? I see that the D3D renderer is gone but changing the renderer doesn't help.

**Comment by OBattler** [comment]
Which older version was below 10%?

**Comment by drfrag666** [comment]
2.07, sometimes even around 5% while playing Doom 1.1. BTW graphics card was the trident 8900D.

**Comment by Fanta-Shokata** [comment]
High CPU issue still persists on build 3646

**Comment by OBattler** [comment]
I think this can be closed now since the performance improvements should have reduced CPU usage as well. It can be re-opened if the issue re-appears.
