### ISSUE TITLE
OpenGL 3.0 displays white square at top-right corner

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#2089]
**Describe the bug**
When OpenGL as a renderer is selected, I see a white square on the top-right corner of the screen.

**To Reproduce**
1. Go to 'View'
2. Scroll down to 'Renderer'
3. Click on 'OpenGL (3.0 Core)'

**Expected behavior**
An option is supposed to appear to select my shader, instead, it is not available, and the bug occurs!

**Screenshots**
![20220208-223514-406406](https://user-images.githubusercontent.com/71288109/153117200-37cb83a7-2dea-4fbc-81e5-101f3733a0f3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 20H2
 - 86Box version: v3.2 build 3521
 - Build information: old dynarec, 32 bit and regular

**Additional context**
For some reason, when I take a screenshot, everything seems fine.

**Comment by Cacodemon345** [comment]
The OpenGL 3.0 Core renderer doesn't have shader support since the UI rewrite was merged. It is however in the works.

**Comment by jadasse** [comment]
> The OpenGL 3.0 Core renderer doesn't have shader support since the UI rewrite was merged. It is however in the works.

ok

**Comment by jadasse** [comment]
what about the white square?

**Comment by Cacodemon345** [comment]
We aren't able to reproduce that white square bug.

**Comment by jadasse** [comment]
Probably because it has been fixed
