### ISSUE TITLE
Numeral type selected in Windows region format settings are used instead of Western Arabic in certain areas

### ISSUE THREAD

**Issue by logoffon** [86Box/86Box#2100]
**Describe the bug**
When Windows region format settings is set to the ones where different numeral type is used, 86Box uses that type instead of Western Arabic numerals (1234567890). This is an unexpected behavior as non-Western Arabic numerals are generally used only with their native language, and even then some types are not used outside of official documents or in appropriate contexts.

For reference, build 3415 does not exhibit this behavior, it uses Western Arabic numerals regardless of the region format settings.

**To Reproduce**
1. Open Region settings (Control Panel -> Clock and Region -> Region)
2. In the Format dropdown, select the language that uses different numeral type (such as Arabic, Burmese, Thai) then apply the setting.
3. Run 86Box (or restart if it's already running), then open the settings window. 
4. Notice the numbers in the Memory box.

**Expected behavior**
Western Arabic numerals should be used instead of the one defined in the region format settings.

**Screenshots**
![86Box_2022-02-11_10-05-18](https://user-images.githubusercontent.com/7828523/153532640-da6dec27-0448-4618-8e23-903e39371e9c.png)
_build 3534 with English format, showing Western Arabic numerals being used_

![86Box_2022-02-11_10-20-58](https://user-images.githubusercontent.com/7828523/153534266-ba84a9d1-7cdb-48e6-a07e-1f0e0c19cc50.png)
_build 3534 with Arabic format, showing Eastern Arabic numerals being used_

![86Box_2022-02-11_10-20-13](https://user-images.githubusercontent.com/7828523/153534298-9f9c7172-91c5-4d49-b01f-7738c01af6e3.png)
_build 3534 with Thai format, showing Thai numerals being used_

![86Box_2022-02-11_10-24-31](https://user-images.githubusercontent.com/7828523/153534313-9628d9e5-ab1f-4de4-9ea6-aa9f3a1ffa1b.png)
_build 3415 with Thai format, showing Western Arabic numerals being used_

**Desktop (please complete the following information):**
 - OS: Windows 10 v1909 (build 18363.418)
 - 86Box version: 3.2 build 3534
 - Build information: old dynarec, x64 regular (non-debug)

**Comment by Cacodemon345** [comment]
How does other Qt toolkit applications behave?
