### ISSUE TITLE
Magic carpet loses all input or crashes weirdly

### ISSUE THREAD

**Issue by insanemal** [86Box/86Box#2108]
**Describe the bug**
While playing Magic carpet in Dos 6.22 on a Socket 7 machine the game will be running fine and then suddenly it stops responding to all input. As in mouse doesn't work, keyboard doesn't work and even more critically you can't send a CTRL+ALT+DEL to the machine and have it respond. Otherwise pressing ENTER will crash the game to DOS.

**To Reproduce**
Play magic carpet. 
One of two things will happen. Game will crash when enter is pressed
OR
Game keeps running but all inputs stop responding to the point that even CTRL+ALT+DEL does not work

**Expected behavior**
Game should work correctly as it does on physical hardware. Or in DosBox

**Desktop (please complete the following information):**
 - ArchLinux
 - 86Box version: Built using AUR script @ https://aur.archlinux.org/packages/86box-git 
 One change was to not enable QT6 as it doesn't build with QT6
 Was built with the following commit at HEAD:  https://github.com/86Box/86Box/commit/9cb385454c8199ebbeee0fbb9b19ff3e9df02686
 - Build information: old dynarec, x86_64, production build

**Additional context**
None that I can think of.

**Comment by Cacodemon345** [comment]
There is a KBC rewrite in progress that should fix this when it gets merged into master.

**Comment by OBattler** [comment]
PSA: Closing these keyboard PS/2 issues and mentioning them in the issue opened for the keyboard controller rewrite as that's poised to fix them.
