### ISSUE TITLE
Mouse input desync after a few capture/release cycles on the cursor

### ISSUE THREAD

**Issue by insanemal** [86Box/86Box#2113]
**Describe the bug**
After captureing and releasing the host mouse cursor a few times, the emulated mouse desyncs and starts behaving erratically.
Does it with DOS mouse drivers and in Windows 95/98. VM is using PS2 2 Button Mouse

**To Reproduce**

1. Capture the mouse
2. Uncapture the mouse
3. Repeat the above a few times

**Expected behavior**
Mouse to not go crazy regardless of how many times you capture and release the host cursor. 

Desktop (please complete the following information):
-     ArchLinux
-     86Box version: Built using AUR script @ https://aur.archlinux.org/packages/86box-git
      One change was to not enable QT6 as it doesn't build with QT6
     Was built with the following commit at HEAD: https://github.com/86Box/86Box/commit/9cb385454c8199ebbeee0fbb9b19ff3e9df02686
-     Build information: old dynarec, x86_64, production build

**Comment by insanemal** [comment]
Forgot to say: Issue persists across "Hard Reset"s of the emulated PC. Obviously 'warm' CTRL+ALT+DEL reboots also have no effect. It looks like, based on what the cursor starts doing, something isn't being reset correctly. As the mouse cursor starts flying around vertically as if you are shaking the mouse up and down very rapidly and the left and right values become clamped, so you can only move in from the left about 100 pixels and it goes back to 0.

So yeah it feels like something isn't being reset correctly. Or perhaps it is being reset when it shouldn't

**Comment by Cacodemon345** [comment]
It's due to Qt botching up its X11 input handlers that makes receiving raw motions using Xinput2 impossible.

**Comment by insanemal** [comment]
Ok, is there something I can do or provide to help resolve this issue? I can dig through the public code for VirtualBox's QT GUI to see how they solve it if it's of assistance.

**Comment by Cacodemon345** [comment]
You are free to do so.

**Comment by insanemal** [comment]
If I'm reading this correctly, currently you're processing the evdev events for the mouse movement?
Just so I understand how the pieces fit together. I'm looking at other examples and they appear to do it very differently

**Comment by Cacodemon345** [comment]
libevdev is only used when available; if the mouse devices can't be found it will fall back to mouse leave detection + warping for mouse events on X11.
