### ISSUE TITLE
Direction key not working 

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#2116]
**Describe the bug**
There is again an issue with direction key where they are replaced by number (not always) in XT machines emulation.

**To Reproduce**
1. Configure a Virtual PC like IBM PC, Open XT or Amstrad PC
2. Start MSDSOS
3. Direction key sometime give 6 for left, 4 for right, etc. Sometime it work but send 2 keystroke, sometime it works as expeceted...

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - 86Box version: Build 3544, 64 Bits Windows (not QT)

**Comment by OBattler** [comment]
Press num lock.

**Comment by OBattler** [comment]
Note: The XT and early AT keyboards did not have arrow keys. Here's the picture of a Model F:
https://upload.wikimedia.org/wikipedia/commons/5/56/IBM_Model_F_XT.png .

**Comment by jvernet** [comment]
My problem is that the way it work is not consistent. Sometime it give number, sometime, it give directions. Num Lock activated or not. Sometime, Num Lock is on and I have direction. Or I need to activate/deasactivate Num Lock a couple of time to make it work.
More over, the mouse is now acting under MSDOS like if you press direction keys (with the internal mouse and Amstrad Mouse Driver last version). It should not do that.

Last thing: some keystroke are not taken in account, if you type too fast. Keystroke are lost.

**Comment by jvernet** [comment]
Still have problems with Amstrad PC 1512/1640/2086 Keyboard Emulation. 
Direction key that give numbers, Nums Lock not consistent (sometime, Num Lock ON, directions are working, sometime not, I do not even understand why sometime the Num Lock goes ON or off without any raison. 
Still the internal mouse acting like direction OR typing numbers under MSDOS. So I do not use anymore the Amstrad Mouse Internal emulation.
More over, if you type too quickly, some strokes are missing, as I said in my previous report.

**Comment by BumfuzzledGames** [comment]
I was having this problem, but found that it stopped when I switched to the Qt (Software) rendering mode. I was only able to replicate it in some software, typically Borland Turbo C++ and Borland Turbo Debugger.

**Comment by OBattler** [comment]
> Direction key that give numbers, Nums Lock not consistent (sometime, Num Lock ON, directions are working, sometime not, I do not even understand why sometime the Num Lock goes ON or off without any raison.

That's because the guest Num Lock status is not synchronized with the host.

**Comment by OBattler** [comment]
Shift+arrows was a common way to select multiple lines/items, and still is to this day. So that part is not a bug. And the number 2 is normal when NumLock is pressed - the keys become number keys.

**Comment by OBattler** [comment]
Closing this issue as stale - too many keyboard changes have happened since then + a missing row in the XT etc. keyboard scan code sets was put back, so it could well be fixed now.

**Comment by OBattler** [comment]
I just reproduced this exact issue on a machine I was working on and fixed it.
