### ISSUE TITLE
Capturing mouse causes emulation speed to drop

### ISSUE THREAD

**Issue by greblosdier** [86Box/86Box#2132]
**Describe the bug**
When capturing the mouse pointer, the emulated system speed drops from 100% to 0-10%.  The mouse cursor moves very slowly within the emulated system, and the emulated system becomes unresponsive.  Releasing the mouse results in the emulated system returning to normal speed after a few seconds.  The emulated system doesn't need to have a mouse driver active or installed in order to observe the issue.

**To Reproduce**
1. Launch 86Box from AppImage
2. Click inside emulated system window
3. Note emulated speed has dropped
4. Use Ctrl+End keystroke to release mouse pointer
5. Note emulated speed returns to expected value

**Expected behavior**
Click inside emulated system window.  Mouse cursor moves smoothly and doesn't significantly affect emulation speed or system responsiveness.

**Desktop (please complete the following information):**
 - OS: Chrome OS 98/Debian Bullseye
 - 86Box version: 3.2 release
 - Build information: 86Box 3.2 release x86-64 Linux AppImage

**Additional context**
Replicated this issue with a range of emulated systems including 486DX 33MHz and 286 10MHz.

**Comment by insanemal** [comment]
So is this on a machine running Chrome OS? or Debian? Or did you test both?

I'm on ArchLinux using the AUR built package and I cannot reproduce

**Comment by insanemal** [comment]
Just rebooted into a Wayland Desktop and tried the AppImage and the combo of AppImage build and Wayland reproduces it.

**Comment by insanemal** [comment]
Just tested a few different things. 

compiled from AUR QT6 XWayland. Cannot reproduce
compiled from AUR QT5 XWayland. Cannot reproduce
compiled from AUR QT6 '-platform wayland' Cannot reproduce
compiled from AUR QT5 '-platform wayland' Cannot reproduce
AppIamge XWayland. Reproduced the issue
AppImage `-platform wayland. Cannot run qt[56]-wayland lib not in app image and doesn't seem to fall back to system

**Comment by greblosdier** [comment]
Behavior was in crostini Linux environment (uses Debian Bullseye) on Chrome OS 98.  Confirmed same behavior on a different Debian Bullseye system running Xorg with AppImage build 3600.

**Comment by greblosdier** [comment]
Confirmed issue resolved with AppImage build 3602 (v 3.2.1)
