### ISSUE TITLE
Cirrus GD5446, characters appear garbled

### ISSUE THREAD

**Issue by renanbirck** [86Box/86Box#2134]
**Describe the bug**
When using a machine with Cirrus GD5446 graphics, I used the drivers from [here](http://vogonsdrivers.com/getfile.php?fileid=263&menustate=0), the characters are garbled like in the screenshot.

This looks like an endianness issue somewhere, since the characters appear "swapped".

The machine is [available here](https://drive.google.com/file/d/1GKiaflQLELITKnuh46hzhcmWwu_h2edm/view?usp=sharing)(password: 86box123) - warning: 14 MB file that decompresses to a ~800MB file.

**To Reproduce**
1. Create a Windows 3.1 machine (haven't tested with other OS)
2. Install the drivers I mentioned above.

**Expected behavior**
Readable characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/553325/154557001-77ccfa1f-649a-4108-ae59-46c8129e9cd1.png)

**Desktop (please complete the following information):**
 - OS: Fedora 35 x86-64
 - 86Box version: 3602
 - Build information: AppImage

**Comment by TC1995** [comment]
set the font cache to 0.

**Comment by renanbirck** [comment]
With setting the font cache to 0, it works.
