### ISSUE TITLE
Add Compaq Portable 486

### ISSUE THREAD

**Issue by swordlink1** [86Box/86Box#2135]
**Is your feature request related to a problem? Please describe.**
No, it isn't.

**Describe the solution you'd like**
86Box emulates a great variety of machines, and this can be expanded further more on by adding the the Compaq Portable 486, to allow for emulation under 86Box.

**Describe alternatives you've considered**
None. I can't find an emulator that can emulate this specific machine, which could make 86Box one of the first emulators to emulate this very machine.

**Additional context**
Nothing that I can put here.

**Comment by OBattler** [comment]
Do you know where I could the BIOS of this machine? As well as a picture of the board and/or a manual.

**Comment by telanus** [comment]
For a manual there's https://hp.manualscollection.com/?fid=fe378f6afaa16ce2572be622e58fa6e6 but afaik the bios isn't available

**Comment by swordlink1** [comment]
Found some pictures of the board.
[Imgur Standalone 4000x3000 Image](https://imgur.com/8Wk3SOl)
[Imgur Gallery 4000x3000 Images, keep scrolling down](url)

**Comment by OBattler** [comment]
It currently can not be added because it's EISA.

telanus> I did find the BIOS (and even a full dump of the Compaq keyboard controller (8042)).

**Comment by swordlink1** [comment]
When will EISA machines be supported?

**Comment by ppgrainbow** [comment]
> When will EISA machines be supported?

According to my suggestion to implement EISA: https://github.com/86Box/86Box/issues/1419

We're hoping that it will be available in 86Box v4.0.

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
