### ISSUE TITLE
Legend games e.g. Eric the Unready not detecting MT-32 IRQ 2

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#2138]
I'm  using the current builds of 86Box and testing out Legend Entertainment Company games - Eric the Unready, Superhero League of Hoboken, and noticed that these games cannot play MT-32 music. In Eric the Unready, a message pops up on loading that says it can't detect the MT-32. In Hoboken, there is no such message but there's no music when selecting MT-32 option.

I'm using MUNT installed (standalone Windows install) and point the System MIDI  in 86Box to the MUNT device. 

All other games, especially Sierra games run with MT-32 music just fine.

I don't think it's 86Box problem, but maybe can look into the reason why the Legend games can't detect the MT-32 in these games?

Tested with Commodore SL386 SX-25 and ASUS PVI-486SP3C configurations. 

Haven't tested with older versions of 86Box since I just recently noticed this.

**Comment by Cacodemon345** [comment]
You need to use the built-in MT-32 emulation.

**Comment by Mal752** [comment]
I tried the built-in emulation. The game still shows the same error message.

**Comment by OBattler** [comment]
Enable the MPU-401 on IRQ 9 (the BIOS' IRQ 9 handler calls the IRQ 2 handler), and make sure it's the standalone MPU-401, not the one built into the Sound Blaster 16.

**Comment by Mal752** [comment]
Yes, I have made the above changes before. All other games work without problems. Only Legend based games that I have tried have this difficulty in detecting the MT-32.

**Comment by OBattler** [comment]
Does this still occur?

**Comment by OBattler** [comment]
I'm closing this because it was most likely fixed by the 4.0 fix that fixed Princess Maker 2, if not, it can be reopened.

**Comment by eddmanx** [comment]
> I'm closing this because it was most likely fixed by the 4.0 fix that fixed Princess Maker 2, if not, it can be reopened.

I just tested this and there is no sound with MT-32, using MUNT. It does seem to be getting the commands since it says "ERIC THE UNREADY" in the MUNT's display.
