### ISSUE TITLE
Sound cards not working in [i440BX] Microsoft Virtual PC 2007

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2142]
**Describe the bug**
Sound cards not working in [i440BX] Microsoft Virtual PC 2007.
[ISA16] Sound Blaster 16 PnP & [ISA16] Sound Blaster 32 PnP is not detected and does not work in Wolf3D.
![2022-02-19_110926](https://user-images.githubusercontent.com/58270614/154797175-0a4eb051-12bb-41db-84f0-1d4bbe29bc05.png)

[ISA16] Sound Blaster AWE32 PnP, [ISA16] Sound Blaster AWE64 Value, [ISA16] Sound Blaster AWE64, [ISA16] Sound Blaster AWE64 Gold defined as Adlib and do not work correctly in Wolf3D.
![2022-02-19_111550](https://user-images.githubusercontent.com/58270614/154797178-80eff7e6-ab10-43d7-b381-77813d62dbe5.png)

**To Reproduce**
1. Create a machine [i440BX] Microsoft Virtual PC 2007 with one of the above sound cards
2. Run DOS v6.22 on the [i440BX] Microsoft Virtual PC 2007 machine and install the sound card drivers.
3. Run Wolf3D

**Expected behavior**
These sound cards should work fine in [i440BX] Microsoft Virtual PC 2007

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.3 x64 Build 3609
 - Build type: regular, old recompiler.

**Additional context**
On other 86Box machines these sound cards work fine.

**Comment by dhrdlicka** [comment]
I kinda doubt the Virtual PC 2007 BIOS even _supports_ ISAPnP...

**Comment by OBattler** [comment]
I'm closing this for NOTABUG.
