### ISSUE TITLE
86Box will crash if i change the machine settings after I change the default

### ISSUE THREAD

**Issue by ali123-bug** [86Box/86Box#2143]
So recently 86box 3.2 brought linux support to the mix
and I tried it (I run ubuntu) and I changed the bios of the IBM PC VM it creates on first boot without a manager i changed it to a PS/60 ValuePoint (this bug happens in 3.2.1) when i try to change out of the PS/60 ValuePoint settings I put when i load the changes it just crashes and reverts 

build is 3602
Operating System is Ubuntu 21.10 (Latest Ubuntu Release (non-lts) ) 
CPU is a mobile 8th gen Intel Core i7 8550u
GPU's are Intel UHD Graphics 620 and AMD Radeon R7 m340
Renderer is Qt Software Mode
its a clean install of ubuntu no dual boot
its using my integrated graphics (of course) 
and I just installed 86box hours ago and i still get the issue

**Comment by dhrdlicka** [comment]
Please don't remove the [default bug report template](https://github.com/86Box/86Box/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), as it asks for specific details that you have omitted from your report.

**Comment by ali123-bug** [comment]
oh sorry im new to the 86box issues but i have addressed my hardware and my specific issue

**Comment by insanemal** [comment]
> oh sorry im new to the 86box issues but i have addressed my hardware and my specific issue

No you haven't as you removed the template and left out the answers to questions it asks. They are there on purpose.
Go back, get the template and follow it.

**Comment by OBattler** [comment]
Does the issue still occur?

**Comment by OBattler** [comment]
No feedback provided and I think the user simply put their config in a non-writable path. Closing.
