### ISSUE TITLE
Window title should mention how to release the mouse when the mouse is captured

### ISSUE THREAD

**Issue by Calinou** [86Box/86Box#2145]
**Is your feature request related to a problem? Please describe.**

When I started 86Box 3.2.1 on Linux, I clicked on the main window. This caused my mouse to be captured, I didn't know how to release the mouse. I had to look up [how to release the mouse in 86Box](https://86box.readthedocs.io/en/latest/usage/gettingstarted.html#:~:text=to%20release%20the%20mouse%2C%20press%20f8%20and%20f12%20simultaneously.%20you%20can%20also%20use%20the%20middle%20mouse%20button%20for%20this%20if%20the%20emulated%20mouse%20only%20has%20two%20buttons.) on my phone.

**Describe the solution you'd like**

As is done in other virtual machine software like QEMU/virt-manager, the window title should change when the mouse is captured to mention how to release the mouse (such as pressing <kbd>F8 + F12</kbd> or clicking the middle mouse button if emulating a 2-button mouse).

**Describe alternatives you've considered**

N/A

**Additional context**

By the way, <kbd>F8 + F12</kbd> does not appear to release the mouse capture on Linux. Is this specific to the Qt backend?

**Comment by Calinou** [comment]
Nevermind, this is actually mentioned in the status bar: 

![image](https://user-images.githubusercontent.com/180032/154823570-8a057780-712a-47d2-94e3-bd4504337d7d.png)

It says that <kbd>Ctrl + End</kbd> should be pressed instead of <kbd>F8 + F12</kbd>, so I guess this is a documentation issue.

**Comment by JamieDoesStuff** [comment]
> When the mouse is captured, it says that Ctrl + End should be pressed instead of F8 + F12. Pressing that combination _does_ work, so I guess this is a documentation issue.

Funny thing is, F8+F12 doesn't work for me, and I'm on the same version as you. Possibly this could be an issue with the i3wm, however I haven't bound(ed?) anything to those keys.

**Comment by Calinou** [comment]
> Funny thing is, F8+F12 doesn't work for me, and I'm on the same version as you. Possibly this could be an issue with the i3wm, however I haven't bound(ed?) anything to those keys.

I meant that pressing <kbd>Ctrl + End</kbd> works. I guess the shortcut was changed, or it's different in the Qt UI compared to the Win32 UI.

**Comment by Cacodemon345** [comment]
The shortcut was changed for Qt but it only applies on non-Windows.

**Comment by OBattler** [comment]
I'm closing this since it turns to be NOTABUG.
