### ISSUE TITLE
Fullscreen stretch mode should default to Integer or 4:3

### ISSUE THREAD

**Issue by Calinou** [86Box/86Box#2146]
**Is your feature request related to a problem? Please describe.**

By default, 86Box 3.2.1 allows fullscreen to be freely stretched and scaled. This means that on a 16:9 monitor, 4:3 will look stretched, and pixel art will look uneven if the Nearest filter mode is selected.

**Describe the solution you'd like**

Use the Integer scale mode by default to better support modern aspect ratios (without stretching) and ensure correct display of pixel art:

![image](https://user-images.githubusercontent.com/180032/154823432-e948e313-3749-4531-bccb-bf5fd6909825.png)

Alternatively, the 4:3 aspect ratio option could be made the default, since pretty much every retro PC was intended to be used in 4:3 back in the day (including DOS games that are rendered at 16:10, but with non-square pixels).

**Describe alternatives you've considered**

N/A, as this is about changing a default setting.

**Additional context**

There could also be a way to force the existing aspect ratio (with scaling, but without stretching) when in windowed mode, but I haven't found such an option.

**Comment by elyosh** [comment]
In my opinion 4:3 aspect ratio should be made the default both in windowed and fullscreen mode as this is period-accurate for all the machines in the project's scope.
