### ISSUE TITLE
Road Runner graphics bug with Hercules video card

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2149]
**Describe the bug**

1. The game does not detect autimatically the Hercules video mode
2. After typiying "Road H" ( the H to force the Hercules video mode the graphics does not lock rignt)

**To Reproduce**
1. Start an XT VM with a DOS boot disk
2. Put the Road Runner disk on drive A:
3. Type "Road H", (it won't detect the Hercules card without it)
4. First screen appears duplicated and the menu screen is broken but the demo gameplay worsk fine.

Workaroud to the issue:

1. Put game floppy disk on the drive
2. Run "mono" to enable CGA emulation
3. type "Road C" for the CGA video mode on Hercules.

Floppy disk of the game:
[Road runner.zip](https://github.com/86Box/86Box/files/8104262/Road.runner.zip)

**Screenshots**

Native Hercules video mode:

![Road Runner 003](https://user-images.githubusercontent.com/31600563/154849343-7a9f81c6-3107-479d-b59b-f1b6a8d9713f.png)
![Road Runner 002](https://user-images.githubusercontent.com/31600563/154849347-ec4ec41c-4fbe-4b9d-8c20-3b808e8e5dda.png)
![Road Runner 001](https://user-images.githubusercontent.com/31600563/154849349-0a352f3a-1b78-4184-a1de-052d193f6688.png)

Using CGA emulation (MONO.COM) With the Hercules video card:
![Road Runner 007](https://user-images.githubusercontent.com/31600563/154849474-8e88c488-d3b9-46dc-88be-3881f28914ca.png)
![Road Runner 006](https://user-images.githubusercontent.com/31600563/154849475-ead9f20e-f693-4cdd-b391-7d249afd8faf.png)
![Road Runner 005](https://user-images.githubusercontent.com/31600563/154849476-1e66fbed-1ee0-44ec-affc-41ee9cc64d01.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 21H2
 - 86Box version: 3.2.1.3604
 - Build information: Win 32 old dynamic recompiler 

**Additional context**
I'm not sure if this is an Hercules emulation bug or it is a software bug with Hercules clone cards, back on the day I run this game with a BAT file,and I suspect  the mono.com file was loaded before the ROAD.EXE file.

**Comment by OBattler** [comment]
I think this thing's Hercules support is buggy - I ran it in Hercules mode on the CGA and I saw it change the CGA color palette and stuff.

**Comment by dbalsom** [comment]
Road Runner just appears to be broken. It actually puts the graphics for the screen side by side like that in video memory, but split into the four banks appropriate for Hercules graphics.

I imagine that a lot of titles didn't really give Hercules support much more than an afterthought, if they tested it at all.

**Comment by OBattler** [comment]
Then this can be closed as NOTABUG.
