### ISSUE TITLE
86Box will not run in Wayland on Linux

### ISSUE THREAD

**Issue by ajshell1** [86Box/86Box#2150]
My system is running Arch Linux, with Sway as my window manager. Sway uses Wayland instead of X11/X.org. My CPU is a Ryzen 3700x and my GPU is a Radeon 5700XT.

Expected behavior:

I expected 86box to start without any issues when I simply run "86box" from the command line, or launch it in any other way.

Current behavior:

Launching 86Box 3.2.1 via appimage gives the following output:

```
arch% ./86Box-Linux-x86_64-b3602.AppImage
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

This wasn't the first time I have encountered a QT Appimage that didn't play nice with Wayland, so I then tried to use 86Box from the AUR (specifically, the one that installed with "paru -S 86box 86box-roms"). This produced the following results:

```
arch% 86box
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.

/sbin/86box: line 2: 396823 Aborted                 (core dumped) 86Box -R /usr/share/86box/roms "$@"

```
Next, I tried to use "86box-git" from the AUR.

```

arch% 86box
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.

/sbin/86box: line 2: 542660 Aborted                 (core dumped) 86Box -R /usr/share/86box/roms "$@"
```

Possible solution:

On the user side of things, a current workaround is to run 86box like this: 

`QT_QPA_PLATFORM=xcb 86box`

Setting this environment variable forces 86Box to run in XWayland.

On the development side of things, I believe all that is needed is to add the Wayland QPA plugin when building 86Box. I could be wrong about this, since I'm not a QT developer.

Thanks to all the developers who have already done a lot of work porting 86Box to Linux.

**Comment by Cacodemon345** [comment]
Wayland support isn't included in the AppImage builds. They are however available when building from source with extra-cmake-modules installed with wayland-client and wayland-scanner.

**Comment by ajshell1** [comment]
That's odd. I installed extra-cmake-modules, but it doesn't seem to be building with Wayland support. Is there something else I have to do?

**Comment by Cacodemon345** [comment]
Is Wayland Scanner installed?

**Comment by ajshell1** [comment]
```
arch% pacman -Qo wayland-scanner
/usr/bin/wayland-scanner is owned by wayland 1.20.0-1
```

Yes, but I'm not sure about wayland-client.

```
arch% pacman -Qo wayland-client
error: No package owns wayland-client
```

**Comment by Cacodemon345** [comment]
Looks like the client headers are part of Wayland itself.

What does the CMake logs tell you?

**Comment by ajshell1** [comment]
```
arch% cmake -Bbuild -DCMAKE_INSTALL_PREFIX=/usr -DRELEASE=on -DUSE_QT6=on -DSLIRP_EXTERNAL=on -DNEW_DYNAREC=off | grep ayland
-- Found Wayland_Client: /usr/lib/libwayland-client.so (found version "1.20.0")
-- Found Wayland: /usr/lib/libwayland-client.so (found version "1.20.0") found components: Client
-- Found WaylandScanner: /sbin/wayland-scanner
```

**Comment by Cacodemon345** [comment]
Then it should compile with Wayland support.

**Comment by ajshell1** [comment]
You say that, but it still isn't running:

```
[100%] Built target 86Box
arch% cd build/src
arch% ./86Box
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.

zsh: IOT instruction (core dumped)  ./86Box
```

**Comment by Cacodemon345** [comment]
Install `qt6-wayland`.

**Comment by ajshell1** [comment]
Now it works. Thanks!

I have one more question though.

> Wayland support isn't included in the AppImage builds.

Why is that?

**Comment by Cacodemon345** [comment]
It was because of the potential AppImage size concerns and that it was hard to identify which Debian package contained the library and its dependencies.

**Comment by ajshell1** [comment]
Fair enough. Thanks.
