### ISSUE TITLE
Unstable operation on any kind of emulated machine

### ISSUE THREAD

**Issue by Adrianwo99** [86Box/86Box#2152]
**Describe the bug**
The emulator became buggy on build 3618. It frequently and without any reason stops operating, generating crash dump in AppData/Local/Crashdump folder. Checked on AMI 386DX clone, Cx486DRx2 @ 66 MHz, 12 MB RAM, CL-GD5434 SVGA, AdLib + MPU-401 + UltraSound + Sound Source on LPT1, BusLogic (BusTek in BIOS) SCSI, NE2000 compatible network card (connection using PCap via Npcap), and Microsoft Serial Mouse on COM1. Potentially emulator is unstable on all other available types of machines, needs to be checked.

**To Reproduce**

**Expected behavior**
Some seconds, sometime minutes, later, the emulator stops working, and then closes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: v3.3 build 3618
 - Build information: new dynarec, x64

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by OBattler** [comment]
Does it still happen on the latest build?

**Comment by jvernet** [comment]
Try to check IRQ/DMA of the NE2000 card. If not correctly set (conflict with another card, or not set the same for 86Box and Windows, for example), 86Box will crash randomly.

**Comment by Adrianwo99** [comment]
Newest builds are finally more stable, no huge changes I need to do now. Od: JVernetWysłano: czwartek, 24 lutego 2022 11:52Do: 86Box/86BoxDW: Adrianwo99; AuthorTemat: Re: [86Box/86Box] Unstable operation on any kind of emulated machine (Issue #2152) Try to check IRQ/DMA of the NE2000 card. If not correctly set (conflict with another card, or not set the same for 86Box and Windows, for example), 86Box will crash randomly.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by OBattler** [comment]
Then I guess this issue can be closed.
