### ISSUE TITLE
ELKS not seeing Floppy on an IBM AT

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#2162]
Found another error

**Describe the bug**
ELKS not seeing Floppy on an IBM AT

**To Reproduce**
My config:
[Machine]
machine = ibmat
cpu_family = 286
cpu_speed = 6000000
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = ega

**Expected behavior**
To boot without errors

**Screenshots**
Minix flavour:

![20220222-204754-399399](https://user-images.githubusercontent.com/19357986/155198823-5abfae6e-53f4-42fb-bd9c-0fc8d47ff81a.png)

Fat Flavour:

![20220222-205145-136136](https://user-images.githubusercontent.com/19357986/155199287-c89667ad-c5e2-406b-84ec-4fc6bbc11f38.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - 86Box version: 3.3 Build 3622
 - Build information: x64 Build with gcc 11

**Additional context**
Was using the 360kb version

_Originally posted by @telanus in https://github.com/86Box/86Box/issues/2160#issuecomment-1048109366_

**Comment by Mellvik** [comment]
This may well be a 86box bug, but it would be beneficial if you tested with the most recent build of ELKS.
I'm using the fd1440.img build (as of today) which boots fine.

 -M

**Comment by telanus** [comment]
looks like it works atm

**Comment by OBattler** [comment]
Then this issue can be closed.
