### ISSUE TITLE
Add Amstrad PC5286, PC7486SLC33, PC7486SLC80 and PC9486

### ISSUE THREAD

**Issue by Banjo-Oz** [86Box/86Box#2179]
I have a huge passion for Amstrad PCs and would love to see them emulated. The PC5286 was my childhood computer, and I recently bought a PC7486SLC33.

I have no idea how to submit patches that could make these possible in PCem, but just discovered the alternative of 86Box which seems more open to adding new machines on request, so I thought I'd try asking. :)

Bios dumps for the first two machines are here (hopefully they work!):
https://banjosmods.wordpress.com/2021/03/18/amstrad-pc5286-bios-dump/
https://banjosmods.wordpress.com/2021/04/17/amstrad-pc7486-slc33-bios-dump/

Bios for PC7486SLC80 is here:
https://www.vogons.org/viewtopic.php?p=887671#p887671

Bios for PC9486 is here:
https://www.vogons.org/viewtopic.php?f=46&t=60741&p=953066&hilit=pc9486#p953066

**Comment by TC1995** [comment]
Well, we need to know the chipset and super I/O chips if any.

**Comment by Banjo-Oz** [comment]
Like the info on my blog posts for the first two, you mean? I can try and find out from the dumpers in those threads if so,

**Comment by Banjo-Oz** [comment]
> Well, we need to know the chipset and super I/O chips if any.

Like the info on my blog posts for the first two, you mean? I can try and find out from the dumpers in those threads if so,

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
