### ISSUE TITLE
Windows ARM64 Native support

### ISSUE THREAD

**Issue by gus33000** [86Box/86Box#2195]
**Is your feature request related to a problem? Please describe.**

Windows for ARM64 processors exists since 2017 for the public, if not earlier for other variants other than Desktop. Much earlier than macOS for Apple Silicon. Windows for ARM64 processors has an ever growing userbase, and desperately need optimized versions of software to run properly. Many developers seem to think that because Windows on ARM includes an emulation layer for x86, it is not needed to port software to native arm64 code. Moreover, with apple introduction of apple silicon macs, this thought got even worse. Compared to Apple Silicon macs, Windows on ARM official hardware does not have dedicated instructions baked into the SoC / CPU cores to accelerate dramatically x86 emulation. As a result, emulated software runs very poorly, and this is no exception for 86Box, which ends up being almost unusable on some SoCs. I have troubles understanding how macOS and Linux have arm64 support, but not Windows at this point, especially with such a large userbase, as of today. Is there any reason for this clear omission and lack of ARM64 builds at the moment?

**Describe the solution you'd like**

Please provide ARM64 native versions of 86Box, in order for the emulator to finally be usable across the userbase of Windows on ARM devices. Optionally/Preferably, having CI setup to build ARM64 compiles would be more than welcome for most users.

**Describe alternatives you've considered**

There's honestly none because nothing comes close to what 86Box provides.

**Additional context**

N/A

**Comment by driver1998** [comment]
86Box does have a CI on Github Actions to make sure it builds on Windows ARM64, but no artifacts.
Also it has been broken since the UI rewrite to use Qt (isn't vcpkg have a port of Qt to Windows/ARM64?)
https://github.com/86Box/86Box/runs/5454889439?check_suite_focus=true

**Comment by dhrdlicka** [comment]
> 86Box does have a CI on Github Actions to make sure it builds on Windows ARM64, but no artifacts. Also it has been broken since the UI rewrite to use Qt (isn't vcpkg have a port of Qt to Windows/ARM64?) https://github.com/86Box/86Box/runs/5454889439?check_suite_focus=true

That's a bug in CMakeLists.txt -- the options should be moved above the part that builds `VCPKG_MANIFEST_FEATURES`.

**Comment by dhrdlicka** [comment]
Turns out Qt5 is in fact incompatible with Windows on ARM64. Compiling with Qt6 doesn't quite work yet, so I disabled the new UI for all Windows builds on GitHub actions.

**Comment by driver1998** [comment]
I just added all the 86Box dependencies to the MSYS2 clangarm64 subsystem, should be able to compile 86Box on a ARM64 Windows box in MSYS2 right now. Not sure about cross compiling.

**Comment by Winins0** [comment]
Now with Volterra on the horizon, this is truer than ever.

**Comment by Cacodemon345** [comment]
It still needs to provide actually fast performance, at least enough to rival low-cost x86 platforms.
