### ISSUE TITLE
Fatal error in MS Word 6

### ISSUE THREAD

**Issue by alzneo** [86Box/86Box#2201]
**Describe the bug**
86Box crash in Microsoft Word 6 (6.0a, 6.0c) on Windows 3.11 for Workgroups.

**To Reproduce**
1. Run Microsoft Word
2. Insert table 2x2 
3. Click Autoformat button (sometimes requires 2, 3, 4 clicks)

**Screenshots**
![Screenshot](https://raw.githubusercontent.com/alzneo/86box-word-bug/main/before.png)
![Screenshot](https://raw.githubusercontent.com/alzneo/86box-word-bug/main/after.png)

[Video](https://raw.githubusercontent.com/alzneo/86box-word-bug/main/video.mp4)

**Desktop**
 - OS: Windows 10 21H1
 - 86Box version: v3.2.1 build 3602
 - Build information: x86_64

**Additional context**
Tried changing settings: on/off sound, network, video adapter, bios; renderer

**Comment by TC1995** [comment]
the Over limit seems to be a x64 dynarec issue.

**Comment by OBattler** [comment]
This is now fixed.
