### ISSUE TITLE
Sony Vaio / ASUS P2B-AE BIOS Request

### ISSUE THREAD

**Issue by MatthewH12** [86Box/86Box#2206]
**Is your feature request related to a problem? Please describe.**
Not a problem, a BIOS request, for the Sony Vaio / ASUS P2B-AE.

**Describe the solution you'd like**
Add the Sony Vaio / ASUS P2B-AE Bios to 86box.

**Additional context**
I'd like to request to add the Sony Branded ASUS P2B-AE Motherboard, that was used in many Sony machines from around 1999-2000. It appears similar to other P2B boards, however it has onboard Vortex2 Audio, and the required Sony DMI code to allow for Sony OEM restores. It was sold at retail as the P3B-1394.

It's an Intel 440BX Chipset.
NorthBridge says FW82443bx AGPSet.
SouthBridge is an Intel FW82371EB/MB PIIX4E/M
ASUSTek (Winbond) AS99127F (appears to be an I2C chip - https://www.kernel.org/doc/html/latest/hwmon/w83781d.html)
Winbond W83977EF-AM
TexasInstruments TSB12LV22 IEEE 1394 Host Controller
Aureal AU8830 Vortex
Award BIOS

Bios (BIO05UXP - Self Extracting): https://rebyte.me/ru/sony/5466/file-9027/

https://i.ebayimg.com/images/g/A2AAAOSwbzhhXfKL/s-l1600.jpg
https://i.ebayimg.com/images/g/vfkAAOSwPkFhpjov/s-l1600.jpg
http://ftp.tekwind.co.jp/pub/asustw/mb/slot1/440bx/p3b-1394/1394-203.pdf

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
