### ISSUE TITLE
Packard Bell PB810 Motherboard BIOS Request

### ISSUE THREAD

**Issue by MatthewH12** [86Box/86Box#2207]
**Is your feature request related to a problem? Please describe.**
I'd like to request to add the Packard Bell PB810 Motherboard BIOS.

**Describe the solution you'd like**
Add the Packard Bell PB810 Motherboard BIOS.

**Additional context**
I'd like to request the PB810 to be added, as it was the last Socket 7 motherboard, Packard Bell produced. It was also known as the GVC/BCM FM530 board.

Chipset :
Intel® 82438VX Data Path (TDX).
Intel® 82437VX Triton system Controller (TVX).
Intel® 82371SB PCI Shipset (PIIX3).
Video : S3 Trio64V+ PCI 2d Accelerator.
Sound: Crystal CS4237B, Enhanced Audio

https://pb.retropc.se/810.html
http://www.uktsupport.co.uk/pb/mb/810.htm

BIOS: https://web.archive.org/web/20030205153029/http://www.uktechsupport.f9.co.uk/pb-810mb.exe
This is a self-extracting archive that contains the latest known G400 v1.25I bios revision.

**Comment by OBattler** [comment]
This gets interesting - the linked BIOS has a built-in video BIOS for the S3 Trio 64V2/DX, and not the Trio64V+, and there's two different schematics floating around - the more common one has the chip without explanation but says Trio64V+ below, while the other one, linked as a picture on TheRetroWeb, explains the chip as Trio64V2... were there multiple revisions of this board?

**Comment by MatthewH12** [comment]
To the best of my knowledge, having used multiple of these boards in person, I've only seen it with the trio64v2/dx. Maybe an earlier revision had the v+ but I've not seen it, so could be an error online?
