### ISSUE TITLE
Keyboard input doesn't handle modifiers correctly on macOS

### ISSUE THREAD

**Issue by emilazy** [86Box/86Box#2211]
**Describe the bug**
I built 86Box myself on an M1 Mac with the new Qt UI using Qt 6, but keyboard modifiers don't work correctly in the VM.

I realize the Qt port was only newly merged and I noticed some Windows-only raw input handling code, so I understand if this is a known bug, but I thought I should open an issue as I didn't see any existing one. (I also didn't test to see if this happens with Qt 5 as well yet; I went for Qt 6 since I get the impression it works better on Apple Silicon.)

**To Reproduce**

1. Set up a DEC DECpc LPV machine with video
2. Enter the BIOS settings with F1
3. Try to adjust Diskette A settings: <kbd>-</kbd> works but <kbd>Shift</kbd>+<kbd>=</kbd> (for <kbd>+</kbd>) just produces two beeps (one for the <kbd>Shift</kbd>, one for the <kbd>=</kbd>)

or

1. Set up a DOS machine (HP Vectra 486VL with MS-DOS 5.0 in my case)
2. Run `edit`
3. Try to type in uppercase; <kbd>Shift</kbd> just produces `a` in the editing window on keydown and doesn't modify the next key
4. Try to access the menu; <kbd>Alt</kbd> also just produces `a`

or

1. Capture the mouse
2. Press <kbd>Ctrl</kbd>+<kbd>Fn</kbd>+<kbd>→</kbd> (for <kbd>Ctrl</kbd>+<kbd>End</kbd>) to release the mouse; nothing happens

(not sure if that last one is the same bug or not)

**Expected behavior**
Keyboard input is processed in the raw, modifier keys work correctly, exiting mouse capture works, etc.

**Desktop (please complete the following information):**
 - OS: macOS 12
 - 86Box version: commit fd53393686979732cfd79cf0b935fbc648b119dc (with `-march=native -mtune=native` patched out of `cmake/flags-gcc.cmake` as it doesn't work with Apple's clang on Apple Silicon)
 - Build information: built with `cmake -S . -B build --preset optimizedndr --toolchain cmake/llvm-macos-aarch64.cmake -DNEW_DYNAREC=ON -DUSE_QT6=ON -DQt6_DIR=/opt/homebrew/Cellar/qt/6.2.2/lib/cmake/Qt6` on AArch64

**Comment by brunocastello** [comment]
@emilazy hi! Could you write a gist guide on how to build it for macOS 12? Me and some friends have an interest in trying it on our M1 Macs too

**Comment by BrandonChang89** [comment]
https://bugreports.qt.io/browse/QTBUG-69608

**Comment by emilazy** [comment]
Yeah, I found that bug later and wrote a patch to fix this and some other miscellaneous macOS/Apple Silicon things to make it easier to build. I'll try and clean it up and send a PR soon.

**Comment by Cacodemon345** [comment]
Wasn't this supposed to be fixed up at upstream Qt? Right now it doesn't look like this bug is really fully fixable from the application's side unless you managed to find a way to differentiate between left/right modifier keys as well.

**Comment by BrandonChang89** [comment]
Well, the nativeModifiers() can be abused to get more info. That's what I'm using locally as a workaround. But unfortunately I can't contribute open source stuffs per my company's policies...

**Comment by Cacodemon345** [comment]
So reading the modifiers directly is the option the.

**Comment by BrandonChang89** [comment]
Not sure how @emilazy is resolving the problem though. I'm curious to see when the PR's up. I'm not at all familiar with QT so maybe there is a much cleaner solution.

**Comment by emilazy** [comment]
Although the issue is marked as fixed upstream, per the last comment on it and my experiences with the official binaries of the latest Qt release it's not actually (maybe they fixed it and then it regressed again somehow). My patch uses `QKeyEvent::nativeModifiers()` and processes it like a native macOS application as @BrandonChang89 says, so it handles left and right modifiers correctly; it's not many lines of code (especially compared to the existing platform-specific keycode translation tables) and I think it's an adequate solution until the Qt bug is fixed. There's some fiddliness to make sure the <kbd>A</kbd> key and modifiers aren't confused (because `kVK_ANSI_A` is 0, which Qt uses as a sentinel value for this...) and to handle Caps Lock but it's not too bad. I've been busy lately but I'll try and get a PR sent off within the next week.

Cross-platform Qt components/applications that handle raw key events like Qt WebEngine already have to handle the whole keycode translation and modifier processing mess themselves; in the longer run it may be a good idea to switch to using something like [qkeycode](https://github.com/nyanpasu64/qkeycode) that has the logic from those extracted out and abstracted away so the platform-specific input handling code and tables aren't required. That library doesn't currently use `QKeyEvent::nativeModifiers()` to be able to get all the information on macOS, though; maybe I'll try to upstream the technique there too sometime.

**Comment by mgatto** [comment]
> Press Ctrl+Fn+→ (for Ctrl+End) to release the mouse; nothing happens

Is this key combo the definitive way to release the mouse on MacOS? Should I add it to the docs?

**Comment by DenisSergeevitch** [comment]
> > Press Ctrl+Fn+→ (for Ctrl+End) to release the mouse; nothing happens
> 
> I've found that this key combo is the only workable way to release the mouse on MacOS (86Box 3.7.1). Should I add it to the docs?

Please do, I am struggling to find a way to release the mouse. The same goes with 'Del' button

**Comment by cold-brewed** [comment]
@DenisSergeevitch If you are having a problem please open a separate issue rather than adding on to a closed issue. Be sure to include the issue template.

On macOS you can release the mouse with Crtl+End which is Ctrl+Fn+Right Arrow on the laptop keyboard.
