### ISSUE TITLE
Vendex 888-XT always detects the hard disk  drive letter as "E"

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2213]
**Describe the bug**

The machine always detects the hard disk as drive E. The C and D seems to be non-existen drives. the FORMAT DOS command detects 
the drive C as floppy drive. it says "Insert floppy drive C".

**To Reproduce**
1. Create the Vencex 888-XT VM 
2. Select WD-MFM hard disk controller
3. Start the machine.
4. The HD is always the "E" drive.

**Expected behavior**
The hard disk drive should use the "C" drive letter.

Vendex HD:
[8088 Vendex 888-XT WD-MFM 733-5-17.zip](https://github.com/86Box/86Box/files/8228579/8088.Vendex.888-XT.WD-MFM.733-5-17.zip)

Floppy disks with software:
[Vendex Turbo-XT-888 Disks.zip](https://github.com/86Box/86Box/files/8228620/Vendex.Turbo-XT-888.Disks.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 21H2
 - 86Box version: 3.3.0.3657
 - Build information: old dynarec standard build

**Additional context**
The machine supports 768kb, but as other XT machines I think the extra 128kb of memory cannot be implemented without specific documentation.

**Comment by OBattler** [comment]
This means it always thinks there's 4 floppy drives, which means there's a bad jumper readout.

**Comment by jriwanek** [comment]
Initial code review shows the FDC is added twice, currently testing changes.
