### ISSUE TITLE
MSYS2 refuses to change directory

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#2220]
**Describe the bug**
On step five of building 86Box, when I type "cd path/to/86Box/src", I get "-bash: cd: path/to/86Box/src: No such file or directory". What am I doing wrong?

**To Reproduce**
1. Have steps 1-4 already completed
2. Open MSYS2
3. Type cd path/to/86Box/src

**Expected behavior**
MSYS2 is supposed to change the directory to the listed path.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x86_64 20H2
 
**Additional context**
Remind me if I am posting in the wrong area

**Comment by OBattler** [comment]
You're meant to replace that example path with the actual path to your src folder.

**Comment by jadasse** [comment]
> You're meant to replace that example path with the actual path to your src folder.

Oh ok
