### ISSUE TITLE
ESC/P emulation not working

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#2221]
**Describe the bug**
Although freetype.dll is present in the 86Box directory, 86Box would refuse to emulate printing.

**To Reproduce**
1. Go to Tools
2. Click on Settings
3. Click on 'Ports'
4. Select 'Generic ESC/P Printer' on any port
5. Save settings
6. See error

**Expected behavior**
PNG files are supposed to show up in the printer directory.

**Screenshots**
![freetype error](https://user-images.githubusercontent.com/71288109/158056722-9a879cab-1bfc-4f22-bc20-ecc83d581458.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x86_64 20H2
 - 86Box version: v3.3 build 3664
 - Build information: old dynarec, 32-bit, regular

**Comment by jadasse** [comment]
Continuing the legacy of https://github.com/86Box/86Box/issues/1842#issue-1058485552

**Comment by jadasse** [comment]
Tried the latest version (3667) and it works again for some reason

**Comment by jadasse** [comment]
it's back (3700)

**Comment by OBattler** [comment]
Yes, this is strange. Some people have the bug, but not on all versions, some of us for some reason do not. I have no idea why it happens.

**Comment by jadasse** [comment]
Great.
> Yes, this is strange. Some people have the bug, but not on all versions, some of us for some reason do not. I have no idea why it happens.

**Comment by jadasse** [comment]
esc/p works again in version 3710

**Comment by jadasse** [comment]
(3712) the problem is back again

**Comment by OBattler** [comment]
Try the FreeType DLL from this build: https://ci.86box.net/job/86Box/2950/ .

**Comment by jadasse** [comment]
it works.

**Comment by jadasse** [comment]
Was your plan to use my feedback to verify whether to reimplement the dll from the link to replace the current one?

**Comment by Cacodemon345** [comment]
> Was your plan to use my feedback to verify whether to reimplement the dll from the link to replace the current one?

Yes.

**Comment by jadasse** [comment]
> > Was your plan to use my feedback to verify whether to reimplement the dll from the link to replace the current one?
> 
> 
> 
> Yes.

Cool

**Comment by jadasse** [comment]
Once the dll is implemented, this issue is to be closed.

**Comment by OBattler** [comment]
I'm going to be attempting to use statically linked libfreetype instead of the .dll.
