### ISSUE TITLE
Add Pentium 3/4 machines

### ISSUE THREAD

**Issue by randomsomeone69** [86Box/86Box#2240]
**Is your feature request related to a problem? Please describe.**
No thanks for asking me. ^^

**Describe the solution you'd like**
That would be cool if Pentium 3/4 machines can be emulated. 

**Describe alternatives you've considered**
If these CPUs are supported, more OS can be supported, as Pentium II (Xeon) and Celeron can go up to Windows 7, why not go up to Windows 10 for the future with Pentium 3/4 machines?

**Additional context**
For example, the recommanded CPU for Windows Vista is a Pentium 3 processor and for Windows 7, it's a Pentium 4. Like that,more guests OS can be working under 86Box.

**Comment by TC1995** [comment]
not gonna happen for a while.

**Comment by dhrdlicka** [comment]
That's totally beyond the capabilities of current hardware.
