### ISSUE TITLE
The Sims 1 crash

### ISSUE THREAD

**Issue by AITUS95** [86Box/86Box#2246]
**Describe the bug**

When i run The Sims 1 on 86box it crashes returning the error in the screenshot.

**To Reproduce**

1. Start Windows 98
2. Click play game with any resolution
5. Press ok
6. The emulator closes

**Screenshots**
![Cattura](https://user-images.githubusercontent.com/48457684/160015697-525fbda7-d498-4575-baa0-e15f637d3956.PNG)

**Desktop**
 - OS: Windows 10 
 - 86Box version: v3.3 build 3707 x86 (32-bit)
 
 **Build information**
![Cattura2](https://user-images.githubusercontent.com/48457684/160016333-be2d8dd1-6167-4ef8-9094-243222a87580.PNG)

**Additional context**
I tried with the NDR version but the same

**Comment by cold-brewed** [comment]
Looking in `vid_voodoo_banshee_blitter.c`, the above value (`0x00080500 & SRC_FORMAT_COL_MASK` ) would evaluate to `SRC_FORMAT_COL_YUYV` which is currently unimplemented.
