### ISSUE TITLE
C-Media CMI 8338 Wav sound bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2249]
**Describe the bug**
I installed Windows 95 with the C-Media CMI 8338 sound card and it get stuck in a loop when loading the Win 95 startup wav file.

**To Reproduce**
1. Start the VM
2. Wait the machine to load Win 95
3. Listen the sound bug

Here are the HD and CFG file
Hard disk:
[https://drive.google.com/file/d/1uZZBEZntQWdNxOte2OD58vWDwv3T8pvK/view?usp=sharing](url)

CFG file
[86box.zip](https://github.com/86Box/86Box/files/8357000/86box.zip)

Device drivers I used:
[C-MEDIA CMI 8338.zip](https://github.com/86Box/86Box/files/8357006/C-MEDIA.CMI.8338.zip)

**Expected behavior**
This should not happen

**Screenshots**
Here is a short recording of the bug.
[Windows 95 CMI 3878 - 86Box 3.3 [build 3707] 2022-03-25 17-26-20.mp4.zip](https://github.com/86Box/86Box/files/8357004/Windows.95.CMI.3878.-.86Box.3.3.build.3707.2022-03-25.17-26-20.mp4.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - 86Box version: 3.3.0.3707
 - Build information: old dynarec, Win 32

**Comment by Fenix770** [comment]
The sound card seems to work fine the 420EX chipset and 486 DX/4 75 Mhz. I don't know if the problem was related to mainboard or CPU

**Comment by richardg867** [comment]
Known issue with IRQ routing on the OPTi 82C822 PCI bridge, affecting not just the CMI8338 but also other PCI cards on machines that use this bridge. A fix is planned, but you should use another machine in the meantime.

**Comment by OBattler** [comment]
This can now be closed as the OPTi 82C822 has been rewritten and now works correctly.
