### ISSUE TITLE
Inter-VM networking

### ISSUE THREAD

**Issue by planetbrian** [86Box/86Box#2252]
**Is your feature request related to a problem? Please describe.**
Using SLiRP to connect VMs to the Internet is certainly fun, but inter-VM communication would be even better. I'm exploring p2p networking with NetWare Lite 1.1/Personal Netware, and it would be pointless to have p2p with one node.

**Describe the solution you'd like**
There are many aspects to inter-VM communication. From serial-serial connections with something like Laplink, or virtualized networks for local LAN games, there are many ways to tackle this issue. However, as NetWare is IPX, which necessitates PCap (Npcap), I could predict it to be difficult. Serial-serial seems manageable, however.

**Describe alternatives you've considered**
I've tried PCap-ing VMs to VMware NAT Adapter, which still doesn't solve the issue of IPX support.
I could always mount .VHDs for file transfer, but that defeats the point.

**Additional context**
OS: Windows 11

**Comment by OBattler** [comment]
Serial passthrough is in the works, once that is done, serial to serial between two VM's should be possible.

**Comment by cold-brewed** [comment]
FYI, some fixes just went in for ne2000/dp8390 and IPX should work fine now. See [this comment](https://github.com/86Box/86Box/issues/2389#issuecomment-1585748346) for more details.

I've personally been able to verify Novell Netware and Doom over IPX. In your case you should be able to use PCAP and vmnet8 / vmnet1 to network the systems together with IPX.
