### ISSUE TITLE
Amstrad Crash

### ISSUE THREAD

**Issue by Alejo808** [86Box/86Box#2254]
**Describe the bug**
Amstrad 1512 computer crash without reaching boot.

**To Reproduce**
1. Go to 'Amstrad 1512, configuration: All default'
2. Click on 'start'
86box starts, a few seconds on black screen. crash without error.

**Expected behavior**
no crash...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - 86Box version: v3.30 build 3700.
 - Build information: "last stable"

**Additional context**
I do not test if other machines crash, the Amstrad 1512 works very well with compilation 3602 (version 3.2.1) and earlier.

**Comment by telanus** [comment]
It's working here on Linux

**Comment by Alejo808** [comment]
sorry. works, it seems that the 86box does not like that I change the configuration of the machines very often
