### ISSUE TITLE
IBM PC AT "ERROR -SYSTEM BOARD" on Diagnostics Disk

### ISSUE THREAD

**Issue by Dizzy611** [86Box/86Box#2258]
**Describe the bug**
IBM PC AT fails to load IBM PC AT Diagnostics Disk 2.07, crashing with "0152 ERROR - SYSTEM BOARD". This seems to be a regression as I recall being able to run the diagnostics disk and use it to set configuration options around the time 3.0 was released.

**To Reproduce**
1. Set up an IBM PC/AT (my config file will be included below)
2. Boot the IBM PC AT Diagnostics Disk v2.07
3. Hit "N" and then enter when asked if you've run this program since the battery was installed.
4. Receive "0152 ERROR - SYSTEM BOARD"

**Expected behavior**
Program continues on to a menu that allows you to specify things like the number and type of floppy drives installed, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/301699/161419182-c690eb24-e129-4c84-8e36-c8f5273ebb34.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.3 Build 3681
 - Build information: old dynarec, Windows 32-bit

**Additional context**
Config file below:

[Hercules]
rgb_type = 2
blend = 1

[General]
vid_renderer = qt_software

[Machine]
machine = ibmat
cpu_family = 286
cpu_speed = 8000000
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = local
cpu = 1
mem_size = 640

[Video]
gfxcard = hercules

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sb

[Storage controllers]
hdc = none
cassette_enabled = 0
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_fn = Z:/Software Preservation/IBM - Diagnostics for IBM Personal Computer AT 2.07 (5.25-360k)/ATDG207.IMG

**Comment by thecheese2022** [comment]
this error can be fixed by disabling time synchronization in 86box and deleting nvr files

**Comment by OBattler** [comment]
Yes, I confirm. Disable time sync, clear the NVR file, and restart the machine.

Hence I'm closing this with NOTABUG.
