### ISSUE TITLE
Some keyboard shortcuts aren't working in fullscreen mode

### ISSUE THREAD

**Issue by Anamon** [86Box/86Box#2263]
**Summary**

Some of the keyboard hotkeys don't work when in fullscreen mode. The affected shortcuts are _Ctrl+F11_ for taking screenshots and _Ctrl+F12_ for sending Ctrl+Alt+Del to the machine. _Ctrl+Alt+PgDn_ to return to windowed mode, and _F8+F12_ to release mouse capture, work fine. Tested on a Windows host.

**Steps to reproduce**

1. Start a machine in windowed mode.
2. Press _Ctrl+F11_ to take a screenshot.
3. Switch to fullscreen by using the menu or pressing _Ctrl+Alt+PgUp_
4. Press _Ctrl+F11_ to take a screenshot.

**Expected behaviour**

Two screenshots are taken, one while 86Box was in windowed mode, and another one while it was in fullscreen mode.

**Actual behaviour**

Only the first screenshot is taken. The hotkey combination doesn't work in fullscreen mode.

**Test environment**

86Box v3.3.0.3710 (prebuilt, binary from Jenkins)
Windows 10 Pro v10.0.19044
Emulated system tested on: [8088] IBM PC (1981)

**Comment by OBattler** [comment]
Ctrl+F11 and Ctrl+F12 are handled as accelerator resources that activate menu items. When the menu is not present, they do nothing. They will have to be redone so they're handled the same way as Ctrl+Alt+PgDn and F8+F12 instead.

**Comment by OBattler** [comment]
This is now fixed.
