### ISSUE TITLE
Quadtel 286 errors at POST if FPU is installed

### ISSUE THREAD

**Issue by maxdlpee** [86Box/86Box#2274]
**Describe the bug**
The machine "Quadtel 286 clone" throws the error "80287 internal register error" during POST if an FPU is added to it. 

**To Reproduce**
1. Click on Tools-Settings
2. On "Machine type" select 286, and on "Machine" select the before-mentioned machine.
3. On "FPU" select either 287 or 287XL (both behave the same)
4. Click "Ok"
5. See error

**Expected behavior**
The non-existance of this message.

**Screenshots**
![20220409-201456-061061](https://user-images.githubusercontent.com/77379259/162596254-4cefe07e-a4b8-47b7-891f-b505ed9009e7.png)
**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.3 (build 3722)
 - Build information: Old Dynarec, 32-bit

**Additional info**
Figured out that this occurs in real hardware with the 287XL, but is not supposed to happen on the regular 287, so fix that ig?

**Comment by Cacodemon345** [comment]
Our FPU emulation isn't bit-accurate at the moment.

**Comment by OBattler** [comment]
It appears enabling SoftFlaot makes this error go away.
