### ISSUE TITLE
86box crashes with FIC VA-503A after soft shutdown.

### ISSUE THREAD

**Issue by Spicytin** [86Box/86Box#2275]
**Describe the bug**
86Box crashes at startup if FIC VA-503A is used then soft shutdown the machine from any OSes (e.g: Win98)

**To Reproduce**
1. Select FIC VA-503A on Super Socket 7 menu.
2. Install an operating system or ignore this if you have already preinstall OS on current virtual drive.
3. Soft (ACPI) shutdown the machine
4. Start 86box again

**Expected behavior**
86Box should start normally after soft shutdown.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.3 Compiled from Github (March 31 2022)
 - Build information: Old dynarec, stable.

**Additional context**
To avoid this bug temporarily, remove its nvr file from nvr folder. You need to do this everytime you soft shutdown the machine.

**Comment by OBattler** [comment]
I have no idea what this board does and would need a proper schematic.

**Comment by OBattler** [comment]
Closing this until it is established that it is in fact an 86Box bug and not a BIOS bug (yes, buggy BIOS'es were unfortunately a thing, well, still are really, I've heard horror stories of buggy UEFI's).
