### ISSUE TITLE
ASUS P3V4X shutdown bug

### ISSUE THREAD

**Issue by Spicytin** [86Box/86Box#2276]
**Describe the bug**
ASUS P3V4X doesn't shutdown correctly and instead hard resets after.

**To Reproduce**
1. Start the machine with an operating system
2. Soft shutdown the machine

**Expected behavior**
86box should close after its shutdown.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.3 Compiled from Github (March 31 2022)
 - Build information: Old dynarec, stable.

**Additional context**
Reproduced this bug on clean install windows 98, no switching hardware is done. I also tried VIA 4 In 1 driver and it doesn't solve the issue.

**Comment by Spicytin** [comment]
Issue still exists. Using 3772.

**Comment by OBattler** [comment]
This is not fixable. RichardG probed the real hardware and ran into the same problem.
