### ISSUE TITLE
Serial Mouse problem on VIA MVP3.

### ISSUE THREAD

**Issue by Spicytin** [86Box/86Box#2277]
**Describe the bug**
Serial Mouse froze after unpausing 86box during standby state on VIA MVP3 chipsets. Thankfully, the keyboard is still fine.

**To Reproduce**
1. Start any mvp3 machine with Windows 98.
2. Standby the machine on shutdown menu.
3. After its on black screen, unpause 86box.

**Expected behavior**
Mouse would not froze after unpausing 86box on standby state.

**Screenshots**
None. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.3 Compiled from Github (March 31 2022)
 - Build information: Old dynarec, Stable.

**Additional context**
Done on FIC VA-503A and Soyo 5EMA PRO.

**Comment by OBattler** [comment]
It appears to be a BIOS bug - the handler of returning from standby doesn't turn the serial ports back on.
