### ISSUE TITLE
Can't detect BIOS files, even if these files are present

### ISSUE THREAD

**Issue by randomsomeone69** [86Box/86Box#2280]
**Describe the bug**
I can't use the software becaue an error says that I hadn't any BIOS files, even if the files are present

**To Reproduce**
1. Start the program (I know it's dumb, but this is real)
2. See error

**Expected behavior**
The program should start.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - 86Box version: any
 - Build information: any
 
**Additional context**
I haven't manage to reproduce this error except on a Dell Inspiron 1720, and the error cannot appear if the program is executed from an external device, such as an USB key or extrenal HDD. The language of the main OS is French, but takes note that I'm FRench and a French PC can execute 86Box normally. This bug also occur with PCem.

**Comment by dhrdlicka** [comment]
Where did you put the ROMs?

**Comment by randomsomeone69** [comment]
In the "roms" folder

**Comment by dhrdlicka** [comment]
Could you open a command prompt in the directory where the 86Box executable is located, run the `tree` command and post its output here?

**Comment by randomsomeone69** [comment]
I can't do that now because the Dell Inspiron 1720 that I've tell is at my grandma's house. When I'll go there, I will do the ### tree command.

**Comment by randomsomeone69** [comment]
So I've done the "tree" command on cmd AND PowerShell and all roms are here. Just 86Box doesn't wank to work with for whatever reasons.

**Comment by dhrdlicka** [comment]
Again, can you post its output here so we can determine the issue?

**Comment by randomsomeone69** [comment]
I can do that later this week or Tuesday.

**Comment by dhrdlicka** [comment]
You don't seem to have extracted the ROM set correctly.

The ROM set should be extracted to the `roms` folder _as is_, preserving the `machines`, `video` and other directories.

**Comment by randomsomeone69** [comment]
I swear I've had extracted the files in the good folder. I will upload tomorow the roms structure folder.

**Comment by randomsomeone69** [comment]
Here's the 86Box structure rom files outputted on a log files
[roms output.log](https://github.com/86Box/86Box/files/8621005/roms.output.log)
.

**Comment by randomsomeone69** [comment]
Here's the 86Box structure rom files outputted on a log files.
[roms output.log](https://github.com/86Box/86Box/files/8654819/roms.output.log)

**Comment by dhrdlicka** [comment]
86Box is in what directory? `D:\Documents`?

**Comment by randomsomeone69** [comment]
no it is on a winbox directory

**Comment by dhrdlicka** [comment]
86Box needs to be in the same location as the `roms` directory.
```
some folder
|
+- 86Box.exe
|
+- roms
   |
   +- machines
   |
   +- video
   |
   +- etc..
```
