### ISSUE TITLE
compaq deskpro 386 1986 and Samsung SPC-6000A not working

### ISSUE THREAD

**Issue by thecheese2022** [86Box/86Box#2285]
**Describe the bug**
The machine "Compaq Deskpro 386" and "Samsung SPC-6000A" doesn't seem to work
**To Reproduce**
1. Go to Tools Settings
2. Select Machine Compaq Deskpro 386 or Samsung SPC-6000A 
3. Click  'OK'

**Expected behavior**
Deskpro 386 1986 stuck in 10 --
SPC-6000A  stuck in  03 02
**Screenshots**
![deskpro386](https://user-images.githubusercontent.com/102922015/163073020-28a4e889-bd65-407a-be3b-b992eb0af278.PNG)
![SPC6000A](https://user-images.githubusercontent.com/102922015/163073046-f1a83538-2f04-4d10-bef6-e9dd343ba1f8.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - 86Box version: [v3.3 build 3724 cc666e6c
 - Build information: old Dynarec, 64-bit]

**Comment by jadasse** [comment]
Have you tried 32-bit 86Box?

**Comment by thecheese2022** [comment]
yes but still the same problem in Samsung SPC-6000A that does not working.
the compaq deskpro 386 is now in dev branch

**Comment by Fenix770** [comment]
The Samsung SPC-6000A does not work on my end either.

**Comment by thecheese2022** [comment]
the Samsung SPC-6000A works in build 3774

**Comment by OBattler** [comment]
Then I guess this can be closed.
