### ISSUE TITLE
Keyboard lockup with Acorp 6VIA90AP

### ISSUE THREAD

**Issue by Spicytin** [86Box/86Box#2286]
**Describe the bug**
Keyboard lockups with Acorp 6VIA90AP when pressing anything during post screen before hard disk detection. Serial mouse is still fine but i dunno if the lockup also affects PS/2 mouse.

**To Reproduce**
1. Boot the 6VIA90AP
2. Try to press anything on ur keyboard during post screen just before it detects hard disks.

**Expected behavior**
Keyboard won't lockup during the post screen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.3 Compiled from Github (March 31 2022)
 - Build information: Old dynarec, stable.

**Additional context**
None.

**Comment by OBattler** [comment]
PSA: Closing these keyboard PS/2 issues and mentioning them in the issue opened for the keyboard controller rewrite as that's poised to fix them.
