### ISSUE TITLE
Window issues

### ISSUE THREAD

**Issue by Dinis1979** [86Box/86Box#2287]
Window doesn't obey window commands. It's now like this:
![image](https://user-images.githubusercontent.com/42978106/163230471-d2289a8a-4887-4f83-a5b4-626534b05d8b.png)

**Comment by OBattler** [comment]
Did you set the window to resizable?

Also, the issue template is mandatory.

**Comment by OBattler** [comment]
I'm closing this because the issue hasn't been filled out properly, and the user hasn't even replied to the post above.
