### ISSUE TITLE
A bit of the frame buffer is missing

### ISSUE THREAD

**Issue by rhaleblian** [86Box/86Box#2290]
**Describe the bug**

See screenshot, bottom of display frame.

**To Reproduce**

1. Run.

But seriously, there may be an interaction between display drivers and emulated hardware.
Have only tried two drivers so far, Stealth 3D 2000 and VGA, both manifest the issue.

I tried this on other os/arch combos and saw it again, need to review notes.  Definitely happens on macOS aarch64 and x64/Rosetta2.  Maybe not on Windows.

Would be nice if I could pack up the machine to make it easy to repro.
[86box.cfg.log](https://github.com/86Box/86Box/files/8490001/86box.cfg.log)
[nvr.zip](https://github.com/86Box/86Box/files/8490103/nvr.zip)

**Expected behavior**
The black rect at screen bottom has desktop in it.

**Screenshots**
<img width="912" alt="Screen Shot 2022-04-14 at 10 21 30 AM" src="https://user-images.githubusercontent.com/94912/163410767-aabdd44e-503c-497a-b19b-cbfeee689e6d.png">

**Desktop (please complete the following information):**

 - OS: macOS 12.3 M1 Pro
 - 86Box version: ci-3273 x64, git-13f2 aarch64
 - Build information: aarch64 with new dynarec (mandatory?)

**Additional context**

Surely, ask.

**Comment by rhaleblian** [comment]
The artifact appears even in BIOS screens.  Another machine config doesn't manifest.
Time permitting i'll try to see what in the hardware combo here triggers this.

**Comment by rhaleblian** [comment]
now at
git-e73cf017

**Comment by rhaleblian** [comment]
This doesn't happen for at least one other hardware config, which i'll post when i find it again.

**Comment by OBattler** [comment]
This has since been fixed.
