### ISSUE TITLE
Middle-click does not release mouse

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#2298]
**Describe the bug**
When emulating a 2-button mouse, the middle-click button does not release the mouse cursor from the emulated machine.

**To Reproduce**
1. Click in the window of an emulated machine to capture the mouse. Mouse must be set to 2-button.
2. Click the middle button on your physical mouse.
3. The mouse cursor is still inside the emulated machine.

**Expected behavior**
The cursor should release upon pressing the middle mouse button. The status bar should say "Click to capture mouse".

**Desktop (please complete the following information):**
 - OS: Windows 10 build 21H1
 - 86Box version: 3.4 build 3737
 - Build information: Windows 32-bit (EDIT: Also affects the 64-bit build)

**Additional context**
This is not a problem with my mouse itself; the first thing I did when I encountered this was to check whether my middle mouse button worked outside of 86Box, which it does.

**Comment by nicocarbone** [comment]
Sorry If I hijack the issue with a different one, but I think they may be related: for me the mouse clicks doesn't work in general. The mouse pointer moves, but the VM doesn't register clicks at all.

OS: Ubuntu 22.04 Wayland Session
86Box version 3.4, amd64

**Comment by MrPepka** [comment]
I also noticed this problem. I thought something broke in my config but it's probably a bug in this version. Interestingly, 86box still claims that you can release the mouse with the middle button, even though it doesn't work

**Comment by thecheese2022** [comment]
this bug was fixed in the build 3738

**Comment by dhrdlicka** [comment]
Fixed in https://github.com/86Box/86Box/commit/bfde3e4867e4935c41b364023cd3f497c07c44a6.
