### ISSUE TITLE
Emulator crashes on BPS Business Graphics 2.61 tutorial, but only with CGA card

### ISSUE THREAD

**Issue by Exemptus** [86Box/86Box#2301]
**Describe the bug**
The emulator crashes to desktop while executing the BPS Business Graphics 2.61 tutorial, as a plan IBM PC configured with a standard CGA card. However, it does not crash with a Plantronics ColorPlus card is selected.

**To Reproduce**
1. Configure an IBM PC (1982) machine with 256 K RAM and CGA, default settings.
2. Boot the machine with image "BPS Business Graphics 2.61 disk 1 - Master" on drive A and "BPS Business Graphics 2.61 disk 3 - Demo" on drive B.
3. Enter date end time. The program autoboots and displays a prompt. Enter DEMO B:
4. Select Option 1 (RGB color monitor).
5. Select Option 1 (Tutorial Introduction)
6. Press Enter in subsequent screens until the demo graph appears. Wait a few seconds. The emulator silently crashes to desktop.

**Expected behavior**
The program clears the screen and continues the tutorial. This behavious is observed OK if instead of a CGA card we configure a Plantronics ColorPlus card, which is CGA compatible.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 build 19044.1645
 - 86Box version: v3.4.1 build 3738
 - Build information: standard 32-bit build

**Additional context**
Using Qt (Software) rendering and overscan option enabled.
[Images.zip](https://github.com/86Box/86Box/files/8549655/Images.zip)

**Comment by Exemptus** [comment]
I have done some more checks. If I disable the option "CGA/PCjr/Tandy/EGA/(S)VGA overscan", the crash does not happen. With it enabled, the emulator crashes, regardless of the graphic card configured and also regardless of renderer. So the ColorPlus change might be a red herring, but it is still true that with the ColorPlus, the crash does not happen even with the overscan enabled. The crash is reproducible when the CGA is selected *and* the overscan is enabled.

**Comment by OBattler** [comment]
I believe this has been fixed now because I remember fixing a crash when using CGA with overscan enabled. It was due to a sanity check being present in the Win32 executable but not in the QT one.
