### ISSUE TITLE
Allow custom option rom

### ISSUE THREAD

**Issue by korneliuszo** [86Box/86Box#2312]
I develop https://github.com/korneliuszo/ne2000xt and I want to check it using 86Box

Can be added functionality to add custom option roms to virtual machine?

**Comment by dhrdlicka** [comment]
For your use case I think it might be the easiest to just replace the default option ROM in `roms\network\ne2000` with your own image.

**Comment by korneliuszo** [comment]
I also want to test it on XT machine with NE1000

**Comment by dhrdlicka** [comment]
Then you'd replace the NE1000 counterpart (`roms/network/ne1000/ne1000.rom`).

**Comment by korneliuszo** [comment]
I've tried to change files, but they don't boot

**Comment by dhrdlicka** [comment]
Are you sure that your images are valid option ROMs?

**Comment by korneliuszo** [comment]
Yes, they run under qemu.

**Comment by dhrdlicka** [comment]
Make sure you enabled the BIOS under the network adapter's settings. Could you also upload your images so we could take a closer look at what goes wrong,

**Comment by korneliuszo** [comment]
NE1000 cannot,
NE2000 can,
RTL8109 cannot into ROM

I've somehow managed to setup my workflow
