### ISSUE TITLE
Can you please Add The dell optiplex gx150

### ISSUE THREAD

**Issue by Hunterrules0-0** [86Box/86Box#2313]
Alright Ive been trying to get the dell optiplex gx150 working in a vm for months. Can you please add the gx150 to x86box.

**Comment by randomsomeone69** [comment]
Did you put the same request in the roms branch?

**Comment by Hunterrules0-0** [comment]
I may be wrong but I dont recall doing that.

**Comment by OBattler** [comment]
Board with i815 with on-chip graphics... not doable, sorry.
