### ISSUE TITLE
Segmentation fault when trying to enter fullscreen on Linux

### ISSUE THREAD

**Issue by bugnano** [86Box/86Box#2321]
**Describe the bug**
I'm using 86Box (versions 3.2, 3.3 and 3.4.1) on EndeavourOS using the AUR packages.
When I try to enter fullscreen mode by selecting Fullscreen from the menu, 86Box crashes with a SIGSEGV with an address boundary error.

**To Reproduce**
1. Go to View
2. Click on Fullscreen

**Expected behavior**
86Box goes to fullscreen mode

**Screenshots**
![Istantanea_2022-04-28_09-23-41](https://user-images.githubusercontent.com/299634/165699674-45fe371b-af49-48bd-ac1e-f0044a1f2c98.png)

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - 86Box version: 3.4.1 (but 3.2 and 3.3 have the exact same problem)
 - Build information: Built from the AUR

**Additional context**
I made no customizations on CFLAGS or the like, so everything is built with the EndeavourOS defaults (which I believe are the same as vanilla Arch)

**Comment by mariuszkurek** [comment]
The fully updated Endeavour live disk on QEMU makes gcc(!) segfault when I try to compile 86Box, followed by completely crashing my entire VM. As I release new 86box-git versions using this host and I never had such problems, I'm going to believe it isn't really 86Box's problem.

**Comment by dhrdlicka** [comment]
Could you try running 86Box under GDB, reproduce the crash and then post the output of the `bt` command to see where exactly it crashes?

**Comment by bugnano** [comment]
[backtrace.log](https://github.com/86Box/86Box/files/8588455/backtrace.log)

**Comment by OBattler** [comment]
OK, I have now committed a tentative fix. See if it's fixed now.

**Comment by OBattler** [comment]
I am going to assume it is fixed now. The issue can be re-opened if it's not.
