### ISSUE TITLE
Add 16 bit color support to Realtek RTG 3106

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2323]
**Is your feature request related to a problem? Please describe.**
Yes, the the 640x480 and 800x600  64k video modes of the Realtek VGA card show the wrong colors or they video modes are not implemented.

**Describe the solution you'd like**
There are other high end VGA card emulated. But this one is one of the few that supports 64k on Windows 3.0.

Here is the hard disk image and drivers:

[Phoenix IBM AT 286 Raltek VGA.zip](https://github.com/86Box/86Box/files/8583699/Phoenix.IBM.AT.286.Raltek.VGA.zip)

[Realtek_VGA_3106_From_exe_file.zip](https://github.com/86Box/86Box/files/8583707/Realtek_VGA_3106_From_exe_file.zip)

![Realtek VGA 800x600 64k](https://user-images.githubusercontent.com/31600563/165777326-d88dd567-3d63-4f57-a58b-b1d3109ff891.png)

**Comment by TC1995** [comment]
Already aware, need to find what ramdac the realtek 3106 uses.

**Comment by OBattler** [comment]
Another uses the UM70C171-66 which is an IMMOS 171 clone, just like the ADV476.

**Comment by OBattler** [comment]
Also with the Samsung KD0476 - same limtiations, but adds a hardware cursor / overlay.

**Comment by OBattler** [comment]
And with the MUSIC TR9C1710 - same limitations.

**Comment by Fenix770** [comment]
That's strange. If the high color DAC is not present, then Windows should not start, ilke what happens with Paradise 30-LR.
Here is a proof that the drivers supports 64kb, and Windows start normally except for the wrong colors.

![RTVGA 64k](https://user-images.githubusercontent.com/31600563/165815341-f23d92eb-a483-4dbc-802a-2e97a5ebf8fd.png)

**Comment by TC1995** [comment]
Well, the bios of this card I got (vgamuseum) is from vlask whom showed the main chips of the card, but the screenshots show a music ramdac.

**Comment by OBattler** [comment]
The specific Music RAMDAC is a simple standard (S)VGA RAMDAC that can do 256 colors at most.

And I suspect the driver could have support for a later Realtek card as well. Unfortunately, these cards are very poorly documented.
