### ISSUE TITLE
Win98SE ACPI shutdown hangs 86Box instance

### ISSUE THREAD

**Issue by JGHBone** [86Box/86Box#2327]
Host: Windows 7 Pro

Guest Virtual Machine:
Windows 98 SE
Gigabyte GA-686BX with Pentium II 200 MHz
128 MB RAM
S3 ViRGE/DX (375) display
Sound Blaster 16
1023 MB IDE hard disk
2 x 3.5" floppy drives
ATAPI CD-ROM drive

ACPI shutdown from within the guest worked as expected up to and including 86Box build 3740. From build 3741 on up to current build 3760, the 86Box instance hangs (fails to close) with guest shutdown and must be terminated with task manager.

**Comment by dhrdlicka** [comment]
What renderer are you using?

**Comment by JGHBone** [comment]
Qt.  Problem occurs with both Qt (software) and Qt (OpenGL).  With those renderers, after guest shutdown, the emulation window goes black (doesn't automatically close like before).  When I manually close that window, the 86Box process instance is still running.

**Comment by JGHBone** [comment]
Fixed in 3766
