### ISSUE TITLE
Rayman intro video is extremely slow

### ISSUE THREAD

**Issue by TedByDawn** [86Box/86Box#2330]
**Describe the bug**
The intro video for Rayman is extremely slow with crackling audio and it takes a few keystrokes to skip it, rest of the game runs fine though. The emulator speed also drops to the low 20's.

**To Reproduce**
Install with intro video included and start a new game.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.4.1
 - Build information: Stable Release

**Comment by OBattler** [comment]
Does this still happen?

**Comment by eddmanx** [comment]
You didn't provide any host and guest specs. We can't tell if the host CPU is good enough for the guest specs. I also can't do an exact test without guest specs. However, the videos play fine with the following:

Build 5434 32-bit NDR and ODR
Windows 98 SE
Asus P55T2P4
Mobile P MMX 120
Voodoo 3 3000
SB16 Non-PNP

**Comment by OBattler** [comment]
It makes sense. Video decoding is very CPU-intensive if you don't have a hardware accelerator, so as such, it hammering the host CPU more than the main game, is to be expected. As such, this can be closed.
