### ISSUE TITLE
Voodoo 2 Missing Textures (Moto Racer)

### ISSUE THREAD

**Issue by TedByDawn** [86Box/86Box#2332]
![20220506-174303-408408](https://user-images.githubusercontent.com/105026406/167220905-41751968-c6d3-4bf8-a84d-bf9c8ee68b21.png)

**Describe the bug**
Missing textures are observed in Moto Racer for all but one of the bikes in both the bike select screen and gameplay. This only occurs when a Voodoo 2 card is connected, otherwise the textures display properly. I have DirectX 7.a and the final Voodoo 2 driver installed (V3.02.02). Another oddity is that the emulator slows to 20% in the Options menu while the gameplay is perfectly smooth.

Virtual PC: 
OS: Windows 95
Machine Type: Socket 7 (Dual Voltage)
Machine: i430HX Intel TC430HX
CPU type: Intel Pentium MMX 166 MHz 
RAM: 48 MB
Video: S3 Trio 64V+ Phoenix 2MB
with Voodoo 2 all 2MB options selected except SLI

**To Reproduce**
Run the game with a Voodoo 2 card attached.

**Expected behavior**
Textures should display properly.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.4.1 
 - Build information: 3738

**Comment by AITUS95** [comment]
Try to install voodoo 2 directx 5.0 drivers, I tested it on my machine and the textures are displayed correctly, I confirm the slowdown of the menu and start the race I think it is a regression of the dynarec.

**Comment by OBattler** [comment]
I believe this can be closed now since it has been reported as fixed.
