### ISSUE TITLE
Unable to click and drag within VM

### ISSUE THREAD

**Issue by dunestorm333** [86Box/86Box#2333]
**Describe the bug**
When inside a VM; I would expect to be able to hold the left or right mouse buttons down and move the mouse simultaneously, but am unable to do so. I can either click or move the mouse, I cannot do both at once. Holding either mouse button blocks the pointer from being able to move, this only happens inside 86Box, making emulating any Windows 9.x VM unusable.

**To Reproduce**
1. Start a fully setup VM such as Windows 95 or Windows 98.
2. From the desktop, hold the left or right mouse button down and move it.

**Expected behavior**
I should be able to drag and drop or click and move the mouse with either button.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux (5.17.5-arch1-1)
 - Desktop Environment: KDE Plasma 5.24.5
 - 86Box version: 3.4.1
 - Build information: Don't know, obtained from AUR

**Comment by telanus** [comment]
Works for me. Using a self-compiled version from https://github.com/86Box/86Box/commit/b0b5d135ccb7d1ee066d3bec5bb39009480fc5bd


https://user-images.githubusercontent.com/19357986/167270502-ade11753-5e5d-4113-9442-c5df4f7be158.mp4

I'm using Kubuntu 20.02 With KDE 5.18.8

**Comment by dunestorm333** [comment]
Very strange, I just tried the AppImage version and it's magically working as intended! Thanks for verifying.

**Comment by telanus** [comment]
@chungy did you try the appimage? Or building the latest git? I know there was a fix for the mouse a while back, and might be that the aur might not be updated to include this fix, as both you and the OP is using arch, so that's why I'm thinking this

**Comment by chungy** [comment]
Didn't try the appimage, but indeed the latest commit on Git works

**Comment by chungy** [comment]
After more experimentation, it seems a Qt5 build works in 3.4.1 for mouse dragging, but Qt 6 does not. Git HEAD doesn't suffer the issue with Qt 6.
