### ISSUE TITLE
Add a combo graphics card with support for both CGA & Hercules 

### ISSUE THREAD

**Issue by Xuser641** [86Box/86Box#2347]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a graphics card option that is both period accurate to the XT era and supports both CGA and Hercules because its annoying that you need two different XT configs to use both graphics modes.

**Describe the solution you'd like**
Emulation of a 1980's combo graphics card (era appropriate to an XT class machine) with full support for the MDA, CGA & Hercules display adapters.

**Describe alternatives you've considered**
The only alternative solution would be to setup two machines but this is annoying and overly complicated.

**Comment by Cacodemon345** [comment]
Does such a graphics card exist?

**Comment by Fenix770** [comment]
I think that card may be the AT Small Wonder, which support both Hercules and CGA. But it is complex to emulate because, (if I recall correctly) it changed the screen refresh frequency from 50hz to 60hz to simulate the 4 color of CGA.

Here is some info, (but I don't know if documentation exist)
https://en.wikipedia.org/wiki/ATI_Wonder_series

**Comment by JimboMumbo** [comment]
combo graphic cards sounds real fun to me, but what's the catch?

**Comment by Xuser641** [comment]
There were many graphics cards from the late 80's that simply had the hardware from a Hercules and CGA card on the same board and could be configured with switches to change what they outputted. I imagine that could be difficult to emulate though now that I think about it. The monitor emulation change required would be difficult too.

See:
https://www.youtube.com/watch?v=Zp71oY1RFGk&t=337s

**Comment by jriwanek** [comment]
We now have support for installing a MDA, Hercules or Hercules plus card at the same time as a CGA, this can likely be closed now.

**Comment by OBattler** [comment]
Yes, I agree.
