### ISSUE TITLE
Feature request: Uncapped speed

### ISSUE THREAD

**Issue by chungy** [86Box/86Box#2348]
It seems that the fastest 86Box allows a VM to run is at 100% speed (occasionally, I see 101 or 102% before it corrects itself), while there are circumstances (long installation procedures, for example) where it would be nice to uncap the emulation speed and allow it to run through as fast as possible.

**Comment by JimboMumbo** [comment]
> It seems that the fastest 86Box allows a VM to run is at 100% speed (occasionally, I see 101 or 102% before it corrects itself), while there are circumstances (long installation procedures, for example) where it would be nice to uncap the emulation speed and allow it to run through as fast as possible.

If there were any socket motherboards like these, you have speed history. But creating the option to check the uncapped speed idea sounds a little bit interesting. it needs a little tweak to run everything faster than usual.

**Comment by DDXofficial** [comment]
> while there are circumstances (long installation procedures, for example) where it would be nice to uncap the emulation speed and allow it to run through as fast as possible.

While I personally understand how appealing this feature may be as it saves users considerable amounts of time during certain operations, it unfortunately goes against 86Box's core principle of emulation accuracy. In the context of OS installations or other related operations, the time it takes to complete these operations is merely indicative of the emulated processor's speed and what you would expect using such a physical computer with such a processor.

As per the dev team's numerous discussions about this, they have concluded that it falls out of the project's scope; therefore, this will not be implemented.
