### ISSUE TITLE
486 DECpc LPV issues

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2349]
**Describe the bug**
1. I installed DOS 6.22 and Windows 3.11 and the S3 928 video card on this machine but the mouse do not work even on standard VGA mode. (The mouse work with DOS edit *before* starting Win 3.11 but after exiting windows it does not work either under DOS)
2. It says there is a conflict with an external IDE controller even if there is no external controller.

**Edit:** As a third bug, I found that the inernal VGA controller does not work. Only a black screen can be seen at boot time.

**Edit 2: I also found that the mouse only works, with 256 colors resolution and the 32-bit disk and file access disabled. The mouse is present on high color modes 32k/64k but the pointer is not visible.** I tried the SiS 471 Abit AB-AH4 and have the same issues.

**To Reproduce**
1. Boot the machine
2. type Win at DOS prompt
3. Try to use the mouse

Hard disk image
[486 DEC LVP.zip](https://github.com/86Box/86Box/files/8712321/486.DEC.LVP.zip)

CFG y NVR file:
[CFG & NVR.zip](https://github.com/86Box/86Box/files/8712334/CFG.NVR.zip)

**Expected behavior**
The internal IDE controller should be recognized and the mouse should work.

**Screenshots**
![486 DEC](https://user-images.githubusercontent.com/31600563/168933753-e582577a-be63-43f4-bd10-591b13bed68c.png)

**Desktop (please complete the following information):**
 - OS: Win 10 21H2
 - 86Box version: 3.5.0.3770
 - Build information: Win 32 old recompiler

**Comment by OBattler** [comment]
And I tested mouse in Windows 3.1 and it works on my end now.
