### ISSUE TITLE
Left mouse button acts as right button until the real right button is used

### ISSUE THREAD

**Issue by chungy** [86Box/86Box#2351]
**Describe the bug**
When booting up a VM, the left mouse button behaves as the right mouse button, until the real right mouse button is clicked.

Same config and operating system as in #2350 

**To Reproduce**
1. Boot VM (Windows 95 on a Shuttle HOT-7 for me)
2. Click the desktop
3. Context menu appears
4. Right click desktop
5. Left click to close, works normally now

**Expected behavior**
For the left mouse button to always act as the left mouse button.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - 86Box version: 3.4.1 and 180ceba8262fd75f884c0f0aaca827e6929a3c82
 - Build information: GCC 12.1, Qt 5

**Comment by Cacodemon345** [comment]
I think it's also a Qt bug.

**Comment by chungy** [comment]
I haven't been affected by this for a while, closing issue.
