### ISSUE TITLE
Right Shift Key and Middle mouse button (to unhook mouse from emulator) don't work

### ISSUE THREAD

**Issue by Xuser641** [86Box/86Box#2362]
**Describe the bug**
If you press the right shift button it is ignored and you get the un-shifted result (e.g. pressing RIGHT SHIFT + 4 gets you 4 instead of $). Also pressing the middle mouse button to unhook the mouse does not work.

**To Reproduce**
*Right Shift*
1. Attempt to type something on the keyboard with right shift
2. You will get the un-shifted result.

*Middle mouse button*
1. Setup a Microsoft serial mouse with two buttons on COM1
2.  Capture the mouse
3.  Attempt to unhook the mouse
4.  Mouse remains captured and you have to use F8 + F12

**Expected behavior**
Right Shift should work and the middle mouse button should work.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit (Version 21H2)
 - 86Box version: 3.4 (Build 3737)
 - Build information: Standard X64 Build

**VM Config**
[SCAT] KMX-C-02
i386SX @ 16MHz
2560KB RAM
VGA Graphics
Microsoft serial mouse on COM1
Sound Blaster Pro V2
PC/AT IDE Controller
2 Floppy Drives

**Comment by OBattler** [comment]
Then I guess this can be closed now.
