### ISSUE TITLE
CHD format support (for CDs, and maybe hard disks?)

### ISSUE THREAD

**Issue by chungy** [86Box/86Box#2368]
The CHD format from the MAME project can compress and represent many kinds of storage devices, of particular note for 86Box, for CDs. It offers both compressed images, and a single-file alternative to a bin/cue pair of files.

CHD also supports hard disk images, with metadata relating to the disk's C/H/S structure. Might also be useful when sharing hard disk images between VMs and people.

**Comment by Cacodemon345** [comment]
We still need to look for a library able to read from CHD files though, since the documentation on it is really scarce.

**Comment by notBald** [comment]
There's a Rust implementation written for the purpose of documenting the format: https://github.com/SnowflakePowered/chd-rs

**Comment by telanus** [comment]
> We still need to look for a library able to read from CHD files though, since the documentation on it is really scarce.

There is Libchd: https://github.com/rtissera/libchdr

**Comment by OBattler** [comment]
The author of the issue says this can be closed.
