### ISSUE TITLE
Fullscreen switch bug

### ISSUE THREAD

**Issue by TedByDawn** [86Box/86Box#2369]
**Describe the bug**
I am stuck in fullscreen mode once inside the Windows 95 desktop and am unable to switch to windowed. If I am inside windowed mode when starting up the machine, it switches to fullscreen automatically once it reaches the desktop. EDIT: The bug is only present when using Open GL renderer 3.0 Core

**To Reproduce**
1. Boot Win 95 machine to desktop

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.5.0
 - Build information: 3.777
 - Using Open GL renderer 3.0 Core

**Comment by ts-korhonen** [comment]
What resolutions do you have
* on host?
* on guest?

Can you also please upload 86box.cfg of the vm.

**Comment by OBattler** [comment]
Closing because of no feedback.
