### ISSUE TITLE
The Micronics 386 DX cannot create a DOS partition under DOS 4.01

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2372]
**Describe the bug**
The ADI 386 DX cannot create the HDD partition under the MS-DOS 4.01 Select program. It just freezes 
Same happens when I attempt to run FDISK from DOS prompt. It freezes when I type 1 to create the partition.
The HDD has a size C/H/S 1024/15/17 (127 mb). The ECS/32 work just fine with this configuration.

**To Reproduce**
1. Create the VM
2. Configure the HDD as MFM/RLL ISA 16
3. Create the HDD image
4. Start the machine with MS-DOS 4.01 setup disks.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 21H2
 - 86Box version: 3.0.5.3755
 - Build information: old dynarec

**Comment by KeishiX** [comment]
Have you set the correct disk settings (MFM or RLL) and type in BIOS? In your case it should be MFM, type 46.

**Comment by ppgrainbow** [comment]
The Micronics 386 I-Cache has 46 MFM and RLL drive types. This means that the highest MFM/RLL hard drive capacity that you'll be allowed to use is Type 46 - 1,024 cylinders, 15 heads and 17 sectors per track for a total of 127.5 MB for MFM drives and 1,024 cylinders, 15 heads and 26 sectors per track for a total of 195 MB for RLL drives.

To get around this limitation, your option would be to use a SCSI hard disk controller. :)

**Comment by Fenix770** [comment]
I used GSETUP to determine the HDD type.

**Comment by ppgrainbow** [comment]
The Micronics 386 I-CACHE has a internal CMOS setup. Generic SETUP should only be used for PCs that do not have a internal CMOS setup. I'll have a look at the 86Box.cfg file to see what I can find. :)

**Comment by Fenix770** [comment]
I used that to see what geometry support this machine, since it has no information the BIOS about the supported disk geometries.
By the way, I used VHD dynamic file format.

**Comment by ppgrainbow** [comment]
If you have used RAW disk image file format, then the CMOS setup wouldn't have this problem. I'll let someone look into this issue regarding dynamic VHDs and partitioning hard disks, because it seems that MS-DOS 4.01 doesn't like having to deal with dynamic VHDs. :(

**Comment by Fenix770** [comment]
The ECS/32, with a 1989 BIOS, works flawlessly with that same image file.

**Comment by Fenix770** [comment]
I tried a type 9 HDD C/H/S 900/15/17 IMG raw format, but I find the same issue. The machine freezes with the HDD indicator active.

![DOS 401 Select freeze](https://user-images.githubusercontent.com/31600563/170893657-ee40cd8e-a43e-4b77-a2da-8099449ee3c6.png)

**Comment by ppgrainbow** [comment]
One of the workarounds is to use FDISK to partition a hard disk, reboot the VM and format the disk.

I'm wondering what could be causing SELECT (the setup utility for MS-DOS 4.01) to hang...

**Comment by Fenix770** [comment]
Now the HD creation seems to work however I found a mouse bug with this machine. It does not detect the serial mouse, even when is enabled. I also replaced the Win 2.11/286 HIMEM.SYS with one from DOS 6.22, because it seems to have a non standard way to enable the A20 line.

Here is the HDD image file and CFG:
[Micronics DOS 4.01.zip](https://github.com/86Box/86Box/files/8798417/Micronics.DOS.4.01.zip)
[86box.zip](https://github.com/86Box/86Box/files/8798428/86box.zip)

**Comment by ppgrainbow** [comment]
Good to hear that the HDD creation is working for you. :)

I'm wondering what could be the problem that is causing the serial mouse to not work correctly...

**Comment by Fenix770** [comment]
PD: The machine with HDD problem was the Micronics, The HDD bug was fixed *but* now the mouse does not works.
The had problems with the HDD as well.

**Comment by OBattler** [comment]
THe mouse problem is most likely a BIOS bug, because if I replace the BIOS with the Phoenix BIOS from Ultimate Retro, serial mouse works without problems.
