### ISSUE TITLE
Mouse acceleration is very sluggish and difficult to use in 3.5

### ISSUE THREAD

**Issue by chungy** [86Box/86Box#2374]
**Describe the bug**
In 3.4.1, moving the mouse felt natural like on my host system; could make small movements easily, could make large movements easily.

As of 3.5, the mouse behavior is very sluggish, trying to move it slowly feels like I have to push the physical device a foot just to move a few pixels. I can move it around the screen with rapid movements, but slow movements are practically unbearable... makes playing games completely unfun.

**To Reproduce**
1. Run 3.4.1, feel how the mouse behaves
2. Run 3.5, feel how the mouse behaves
3. Notice the difference

**Expected behavior**
Mouse movement to be smooth, predictable, and much more like the host mouse behavior, which it already was in 3.4.1.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - 86Box version: 3.5
 - Build information: GCC 12.1

**Comment by ArnoldUK** [comment]
I've found a fix for the slow jerky mouse issues with Build 3.x when using the Logitech/MS Bus mouse.
The problem is with the default Hz setting. Changing the value to non-timed (original) gives very smooth mouse control and very good response. Not sure if this is your issue though ?

**Comment by OBattler** [comment]
There's a workaround now in the form fo the mouse sensisitivity stuff.

**Comment by OBattler** [comment]
I'm going to consider this fixed by the workaround. It can be re-opened if it's not.

**Comment by chungy** [comment]
Is it supposed to be fixed in 3.7? I'd have to say it very much is not.

**Comment by Cacodemon345** [comment]
Look in the Preferences. You should find a Mouse Sensitivity slider there.

**Comment by chungy** [comment]
Fixed in #2609
