### ISSUE TITLE
Intemittent keyboard lockup

### ISSUE THREAD

**Issue by Carmina16** [86Box/86Box#2375]
**Describe the bug**
Holding down keyboard keys sometimes causes PS/2 keyboard/mouse to lock up. The machine seems to continue to work, but even Ctrl-Alt-Del doesn't work.

**To Reproduce**
1. Create a Pentium-class machine
2. Install Windows 95 or run DOOM
3. Play around with controls for some time

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - 86Box version: e.g. v3.3 build 3700
 - Build information: 32-bit

**Comment by Carmina16** [comment]
It keeps locking in 3777.

**Comment by Gogo268** [comment]
this is a known keyboard controller bug, use the serial mouse for now and that should resolve the issue.
it's currently being worked on and will be merged (maybe soon? i don't know) into the main branch of the emulator.

**Comment by OBattler** [comment]
PSA: Closing these keyboard PS/2 issues and mentioning them in the issue opened for the keyboard controller rewrite as that's poised to fix them.
