### ISSUE TITLE
K6-2+ and 6x86MX missing instructions

### ISSUE THREAD

**Issue by Torinde** [86Box/86Box#2377]
K6-2+, K6-III+ and 6x86MX are listed cpu.h, but I don't see the extra instructions added by those CPUs in the code

K6-2+ : PF2IW, PFNACC, PFPNACC, PI2FW, PSWAPD
6x86MX : PAVEB, PADDSIW, PMAGW, PDISTIB, PSUBSIW, PMVZB, PMVNZB, PMVLZB, PMVGEZB, PMULHRIW, PMACHRIW; FTSTP, FRINT2, FRICHOP, FRINEAR

Of course, I couldn't find also the 3DNow! Pro from [Geode GX/LX](http://hackipedia.org/browse.cgi/Hardware/CPU/x86/Geode/AMD%20Geode%20LX%20Processors%20Data%20Book%20(2007-02).pdf)) : PFRSQRTV, PFRCPV - but those CPUs aren't listed, so that's as expected.

Related to joncampbell123/dosbox-x#3217, sarah-walker-pcem/pcem#85, PCBox/PCBox#39

**Comment by OBattler** [comment]
Added the K6-2+/K6-III+ 3DNow! Extensions.

The Cyrixes, on the other hand, have many problems than just this and are currently very partial implementation. There's a reason why we moved them to the Dev branch to hide them from regular users.

As such, I am closing this, but am going to take in mind the missing Cyrix instructions.
