### ISSUE TITLE
800x600 16 color video mode does not works on the OTI-037C video card.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2379]
**Describe the bug**
I found the device driver to what seems to be the OTI-37C, it includes the only SVGA mode supported (800x600 16 color video mode.) The OTI-37C crash with the 800x600 16 color driver installed on Win 2.11/386 but works just fine with OTI-67. 

**To Reproduce**
1. Start the VM
2. Type Win86 or Win386 and press enter
3. The machine crash with the OTI-37C

Here are the floppy disk with EMS driver (if someone want to test it) and the VGA drivers
[EMER_EMS.zip](https://github.com/86Box/86Box/files/8839124/EMER_EMS.zip)
[EMER_VGA.zip](https://github.com/86Box/86Box/files/8839125/EMER_VGA.zip)

Here is the CFG and NVR files:
[386 SX Win 2.11-386 OTI-37C.zip](https://github.com/86Box/86Box/files/8839130/386.SX.Win.2.11-386.OTI-37C.zip)
[Windows 386 OTI-37.zip](https://github.com/86Box/86Box/files/8839131/Windows.386.OTI-37.zip)

**Expected behavior**

**Screenshots**
This is the Ramtest utility
![VGA RAM utility](https://user-images.githubusercontent.com/31600563/172030168-4995d09c-09f8-43a9-8f00-3c37bbb1aabc.png)

**Desktop (please complete the following information):**
 - OS: Win 10 21H2
 - 86Box version: 3.5.0.3790
 - Build information: old dynarec

**Comment by Fenix770** [comment]
Update: I  also found a Bug on the on-board OAK video chip of the AMA-932J 386 SX
![AMA-932J OTI onboard ](https://user-images.githubusercontent.com/31600563/172030993-b57a13a1-de6d-4054-8285-dfd06c094865.png)

**Comment by OBattler** [comment]
The driver requires interlace which, according to the datasheet, is not supported by the OTI-037. So that behavior is NOTABUG.

As for the on-board OTI-067, that must be the video BIOS not enabling interlace for some reason. Nothing I can do about that.

As such, I'm closing this issue.
