### ISSUE TITLE
Trident TGUI 9400CXI crashes the program

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [86Box/86Box#2381]
**Describe the bug**
The video card [VLB] Trident TGUI 9400CXI just crashes 86Box with error message. Other video cards are just fine.

**To Reproduce**
1. Go to machine settings.
2. Go to video card settings.
3. Choose "[VLB] Trident TGUI 9400CXI"
4. Click OK. It hard resets the machine.
5. Hard reset again (or just close the program), and it crashes!

**Expected behavior**
It should not crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7 Service Park 1 build 7601
 - 86Box version: Version 3.5, master, dev-branch
 - Build information: New Dynamic Recompiler.

**Additional context**
They should fix that video card as it bugs severely. If not, it should be dev-branched.

**Comment by Fenix770** [comment]
I have the same problem with Windows 3.11. It starts DOS fine, but 86boxe automatically closes after typing "WIN" and Windows screen logo.

**Comment by TC1995** [comment]
This card has literally no information about its specific stuff on the web.

**Comment by NanaMizukiAnother7** [comment]
The Tseng Labs ET4000/w32 video card also crashes, but that code needs to be fixed too.

**Comment by Gogo268** [comment]
> The Tseng Labs ET4000/w32 video card also crashes, but that code needs to be fixed too.

![image](https://user-images.githubusercontent.com/37984199/173239270-193f2160-cd5a-4d8c-97ae-4fd49a018aae.png)
i can't reproduce that crash, what configuration are you using?

**Comment by NanaMizukiAnother7** [comment]
> > The Tseng Labs ET4000/w32 video card also crashes, but that code needs to be fixed too.
> 
> I can't reproduce that crash, what configuration are you using?
Nevermind. I normally use ET4000AX and ET4000/w32i instead of the normal "ET4000/w32".

**Comment by Fenix770** [comment]
The ET4000/W32 works on my end. I'm using 800x600 64k video mode. Note that the drivers for W32, W32i and W32p are the same, but some video modes may work only on W32i/p or W32p only. Also, you should try old dynamic recompiler  with regular branch to see if works.

I have Win 10 21H2, and using a 486 DX/33, ABIT AV4 mainboard (SiS 460), regular branch old dynamic recompiler.

![ET4000 W32](https://user-images.githubusercontent.com/31600563/173445672-6e1e8045-687a-47d5-b368-2bfe4d72b471.png)

**Comment by NanaMizukiAnother7** [comment]
It works! Thanks, Fenix! I can now use that video card. I thought it was a BusLogic bug which caused 86Box to crash.

**Comment by NanaMizukiAnother7** [comment]
I will close this for now until someone looks for it!

**Comment by NanaMizukiAnother7** [comment]
Reopening since this latest build does not fix it.

**Comment by OBattler** [comment]
If someone was able to provide a GDB backtrace of this problem, it would help fix it.

**Comment by NanaMizukiAnother7** [comment]
I have a Windows Event Logger crash log and configuration:

Machine&KB Log:
```
Faulting application name: 86Box.exe, version: 3.6.0.0, time stamp: 0x62daddb3
Faulting module name: 86Box.exe, version: 3.6.0.0, time stamp: 0x62daddb3
Exception code: 0xc0000005
Fault offset: 0x00000000001af5b6
Faulting process id: 0x13b8
Faulting application start time: 0x01d89e2606e92fff
Faulting application path: C:\Users\User\Desktop\86Box\86Box.exe
Faulting module path: C:\Users\User\Desktop\86Box\86Box.exe
Report Id: 8fe32b5c-0a19-11ed-bb70-b8975a5afd94
```

Stable/Git-Master Log:
```
Faulting application name: 86Box-Stable.exe, version: 3.6.0.3955, time stamp: 0x00000000
Faulting module name: 86Box-Stable.exe, version: 3.6.0.3955, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000001c8f50
Faulting process id: 0x2220
Faulting application start time: 0x01d89e26c8ce45fd
Faulting application path: C:\Users\User\Desktop\86Box\86Box-Stable.exe
Faulting module path: C:\Users\User\Desktop\86Box\86Box-Stable.exe
Report Id: 09020a10-0a1a-11ed-bb70-b8975a5afd94
```

Config:
```
[Machine]
machine = 403tg
cpu_family = cx486s
cpu_speed = 33333333
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = utc
cpu_manufacturer = 2
cpu = 1
mem_size = 8192

[Video]
gfxcard = tgui9400cxi_vlb

[Input devices]
mouse_type = none

[Storage controllers]
hdc = none
cassette_enabled = 0
cassette_mode = load
```

**Comment by jriwanek** [comment]
Doesn't occur in 2.07, occurs reliably in 3.0 and later, only appears to occur on hard reset.

**Comment by jriwanek** [comment]
Backtrace:
```
Thread 42 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 22348.0x1068]
i2c_eeprom_close (dev_handle=dev_handle@entry=0x0) at D:/a/86Box/86Box/src/mem/i2c_eeprom.c:169
169     D:/a/86Box/86Box/src/mem/i2c_eeprom.c: No such file or directory.
(gdb) backtrace
#0  i2c_eeprom_close (dev_handle=dev_handle@entry=0x0)
    at D:/a/86Box/86Box/src/mem/i2c_eeprom.c:169
#1  0x0122855f in ddc_close (eeprom=0x0)
    at D:/a/86Box/86Box/src/video/vid_ddc.c:232
#2  0x012595ba in tgui_close (p=0x14744cc8)
    at D:/a/86Box/86Box/src/video/vid_tgui9440.c:3157
#3  0x01321d4f in device_close_all () at D:/a/86Box/86Box/src/device.c:277
#4  0x0130a4ad in pc_reset_hard_close () at D:/a/86Box/86Box/src/86box.c:955
#5  0x0130a911 in pc_run () at D:/a/86Box/86Box/src/86box.c:1222
#6  0x012c3e2e in main_thread (param=<optimized out>)
    at D:/a/86Box/86Box/src/win/win.c:546
#7  0x01324a0c in operator() (__closure=<optimized out>)
    at D:/a/86Box/86Box/src/thread.cpp:21
#8  std::__invoke_impl<void, thread_create(void (*)(void*), void*)::<lambda()> > (__f=...) at D:/a/_temp/msys64/mingw32/include/c++/12.1.0/bits/invoke.h:61
#9  std::__invoke<thread_create(void (*)(void*), void*)::<lambda()> > (
    __fn=...) at D:/a/_temp/msys64/mingw32/include/c++/12.1.0/bits/invoke.h:96
#10 std::thread::_Invoker<std::tuple<thread_create(void (*)(void*), void*)::<lambda()> > >::_M_invoke<0> (this=<optimized out>)
    at D:/a/_temp/msys64/mingw32/include/c++/12.1.0/bits/std_thread.h:252
#11 std::thread::_Invoker<std::tuple<thread_create(void (*)(void*), void*)::<lambda()> > >::operator() (this=<optimized out>)
    at D:/a/_temp/msys64/mingw32/include/c++/12.1.0/bits/std_thread.h:259
#12 std::thread::_State_impl<std::thread::_Invoker<std::tuple<thread_create(void (*)(void*), void*)::<lambda()> > > >::_M_run(void) (this=<optimized out>)
    at D:/a/_temp/msys64/mingw32/include/c++/12.1.0/bits/std_thread.h:210
#13 0x01631830 in execute_native_thread_routine ()
#14 0x015837fd in pthread_create_wrapper ()
#15 0x76e66cff in msvcrt!_beginthreadex () from C:\Windows\SysWOW64\msvcrt.dll
#16 0x76e66dc1 in msvcrt!_endthreadex () from C:\Windows\SysWOW64\msvcrt.dll
#17 0x7689fa29 in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\SysWOW64\kernel32.dll
#18 0x771c7a9e in ntdll!RtlGetAppContainerNamedObjectPath ()
   from C:\Windows\SysWOW64\ntdll.dll
#19 0x771c7a6e in ntdll!RtlGetAppContainerNamedObjectPath ()
   from C:\Windows\SysWOW64\ntdll.dll
#20 0x00000000 in ?? ()
```

**Comment by NanaMizukiAnother7** [comment]
Thank you for fixing that issue, jriwanek! That crashing issue is no more!
