### ISSUE TITLE
Sound Blaster Pro 1.0 only plays MIDI on the left speaker

### ISSUE THREAD

**Issue by JamieDoesStuff** [86Box/86Box#2382]
**Describe the bug**
Title.

**To Reproduce**
1. Choose the SB Pro v1 in the machine configuration options
2. Play a MIDI
3. Encounter bug

**Expected behavior**
The MIDI plays on both channels.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - 86Box version: 3.5 build 3792
 - Build information: old dynarec, x86, dunno, dev I guess? Got it from the AUR.

**Additional context**
Only happens with MIDI.

**Comment by OBattler** [comment]
> The MIDI plays on both channels.

Is that actually confirmed behavior from the real card?

**Comment by JamieDoesStuff** [comment]
Don't have the card, but I doubt it, pretty sure is should play on both channels. By the way, I'm talking about left and right speakers.

**Comment by JamieDoesStuff** [comment]
*it

**Comment by OBattler** [comment]
From what I know, the card has two OPL2's - one for the left speaker, one for the right. But I have seen video evidence proving it indeed does mono on both speakers. So I now need to figure out under what condition does the second OPL2 take over the right speaker.

**Comment by JamieDoesStuff** [comment]
Don't know if this is of any help, but here's the emulated machine's configuration:

AOpen Vi15G;
AMD 486DX2@66;
ET4000AX;
MS Serial Mouse;
The Sound Blaster.

**Comment by OBattler** [comment]
Your configuration isn't going to help me figure out how exactly the hardware works. But, I'm thinking of just reverting to old behavior that seemed to be closer to correct.
