### ISSUE TITLE
compaq  quickrestore issue

### ISSUE THREAD

**Issue by dskiller** [86Box/86Box#2384]
**Describe the bug**
was trying to create system using my old compaq quickrestore cd for 7360 model. so I used the compaq 4500 board with amd k6 , the cd runs , creates both partitions and copyies files the extended partition. and it ask for 2 cd and it finishes. and then asks to reinsert 1st disk. I do and hit enter . it starts reading cd and gives error 154 and contact customer service.  I reboot with a windows 98 disk and check the c: partition and it all corrupted files. but yet the extend partition is fine. I fdisk the drive and formate and restart the process and it does the same thing every time.  I tried using other board with amd cpu but the quick restore gui is corrupted.

UPDATE: just notices it only shows corrupted when using the 4500 board. other boards the files are fine.

 - OS: [windows 98]
 - 86Box version :latest version
 - Build information: compaq 4500 

edit switched to build 3333 and smaller harddisk size around 7gb.  now it finishes the first stage and tries to boot the process to installing software and such. but it shows the windows 98 bootscreen and then dos/4g error 2001.

UPDATE:  got it working with presetup compaq 4500 and increased disk size to 4gb and using build 3795 and it actually working. its treating it like a compaq 7360 but with a petium processor. the cds are  going through the whole restore process, creating a new system image with it.
ah the memorys .......................:)

**Comment by OBattler** [comment]
Since you got it working in the end, I can close this issue.
