### ISSUE TITLE
Novell Netware 3.12 IPX packets are malformed

### ISSUE THREAD

**Issue by techpost79** [86Box/86Box#2389]
**Describe the bug**
I have built a Netware 3.12 server using the following emulator configuration:
* System: Socket 7 / [i430HX] Asus P/I-P55T2P4
* CPU: Intel Pentium 133
* RAM: 24MB
* Video: [PCI] S3 Trio 32 (Phoenix)
* Sound: none
* Network: Pcap / Virtualbox Host-Only Ethernet Adapter / [PCI] AMD PC net-Fast III
* Storage controller: [PCI] IDE Controller (Dual-Channel)

When I load the Netware client from another 86Box machine, the NW server responds to the broadcast request with a malformed packet so the client fails to locate a server.

Wireshark shows the following exchange (0e093c is the client, 2702ac is the server):
1. 0.266617	00000000.0000d80e093c	00000000.ffffffffffff	                IPX SAP	60	Nearest Query
2. 0.279693	Amd_27:02:ac	                         OldNovel_0e:09:3c	                IPX	        209	[Malformed Packet]

My initial thought is the virtual NIC is not passing IPX RIP packets so the router discovery fails.

**To Reproduce**
1. Setup NW 3.12 machine (I can provide config and virtual HDD)
2. Build MS-DOS client with NW Client installed (can also provide this image)
3. Run packet capture on Pcap interface to verify exchange between hosts

**Expected behavior**
A correct exchange should look like this in Wireshark (reproduced by hosting the server with identical OS config on a virtualbox vm)
1. 6.111306	00000000.0000d80e093c	00000000.ffffffffffff	                IPX SAP	  60	       Nearest Query
2. 6.146575	00000002.080027cd20ca	00000002.0000d80e093c	IPX RIP	  57	       Response
3. 6.181583	00000002.0000d80e093c	12345678.000000000001	NCP	          60	       C Create Connection Service
4. 6.181735	12345678.000000000001	00000002.0000d80e093c	NCP	          55	       R OK
5. 6.205063	00000002.0000d80e093c	12345678.000000000001	NCP	          60	        C Get File Server Information
6. 7.205254	12345678.000000000001	00000002.0000d80e093c	NCP	          183	R OK
7. 6.240183	00000002.0000d80e093c	12345678.000000000001	NCP	           72	        C Packet Burst Connection Request
8. 6.240408	12345678.000000000001	00000002.0000d80e093c	NCP	           63	        R OK
9. 6.275352	00000002.0000d80e093c	12345678.000000000001	NCP	           60	        C Get Big Max Packet Size - 1496
10. 6.275568	12345678.000000000001	00000002.0000d80e093c	NCP	           60	        R OK
11. 6.324143	00000002.0000d80e093c	12345678.000000000001	NCP	           1513	Unknown type (0x0100)
12. 6.324569	12345678.000000000001	00000002.0000d80e093c	NCP	           1513	Unknown type (0x0100)
13. 6.347538	00000002.0000d80e093c	12345678.000000000001	NCP	           1449	Unknown type (0x0200)
14. 6.347709	12345678.000000000001	00000002.0000d80e093c	NCP	           1449	Unknown type (0x0200)
15. 6.417883	00000002.0000d80e093c	12345678.000000000001	NCP	            60	C Get File Server Date And Time
16. 6.418069	12345678.000000000001	00000002.0000d80e093c	NCP	            62	R OK
17. 7.239153	00000002.0000d80e093c	12345678.000000000001	NCP	            60	C End of Job
18. 7.239295	12345678.000000000001	00000002.0000d80e093c	NCP	            55	R OK
19. 7.449115	00000002.0000d80e093c	12345678.000000000001	NCP	            60	C End of Job
20. 7.449380	12345678.000000000001	00000002.0000d80e093c	NCP	            55	R OK
21. 7.496305	00000002.0000d80e093c	12345678.000000000001	NCP	            60	C End of Job
22. 7.496503	12345678.000000000001	00000002.0000d80e093c	NCP	            55	R OK

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.50 build 3795
 - Build information: [i.e. new/old dynarec, architecture and build type]

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by Gogo268** [comment]
Can you try to reproduce the bug with another NIC such as the NE2000 ISA? I think the pcnet doesn't work properly as it causes issues even in NT 4.0.

**Comment by techpost79** [comment]
Interestingly, different symptoms with the NE2000 ISA NIC: the emulator produces responses with fake MAC addresses and the data is encapsulated within an unknown protocol as below:
1	0.000000	00000002.00:00:D8:0E:09:3C (client)	        00000002.ffffffffffff (broadcast)	        IPX SAP	60	Nearest Query
2	0.032235	00:00:E0:FA:43:9E	(should end 1C:D5) 00:FA:43:9E:B8:01 (should be client MAC)	0xb801 (should be IPX RIP)	113	Ethernet II

**Comment by vbdasc2** [comment]
What I'm going to write might be relevant to this problem or not, but... I was playing recently with various versions of Netware 286 2.x, and I noticed that the only emulated network adapters which worked (meaning: were able to connect to other machines) were 3c503 (3Com Etherlink II) and the various Western Digital ones (WD8003EB seems the most stable of these). Try these. NE2000 and the AMD PCNet variants did NOT work for me, although they were recognized by the OS.

**Comment by vbdasc2** [comment]
> NE2000 didn't work though I didn't look into why - IIRC the driver loaded, it just couldn't see any servers.

Yes, I tested the ODI drivers too, and this was exactly my experience with NE2000, under both 86Box and PCem. Again, Etherlink II worked.

**Comment by davidrg** [comment]
Did some testing with 86Box 3.6, some ODI drivers, the old 16bit VLM 1.21 client, and four NIC options:

Novell NE2000 Ethernet MLID v2.10 (960401)
Refuses to load - "The hardware configuration conflicts". I tried a few IRQ and port combinations with no effect.

AMD PCNTNW Ethernet MLID v4.01 (990513)
AMD PCnet ISA worked - attaches to my NetWare 4.11 server and I can login
AMD PCnet-PCI II, PCnet-FAST III - fails to load (the adapter did not initialize)

Realtek RTL8019 PnP Ethernet MLID v3.10 (980703)
Fails to start. The cursor just moves around the screen until you reboot.

Realtek 8029 PCI Ethernet MLID v6.40 (990421)
Refuses to load - "The hardware configuration conflicts"

I also gave the latest NetWare client for DOS (Client32 2.71 for DOS/16bit Windows) and some 32bit ODI drivers a go as these are pretty similar to (and sometimes, like for the two Realtek cards, the same as) what NetWare server uses.

AMD PCNTNW v4.14 (980626)
PCnet ISA - driver refuses to load, complains "Device NOT at this Slot"
PCnet PCI-II - driver loads fine (slot=10002) but client32 can't find any servers

Realtek PCI Ethernet Turbo Driver v7.50 (980311)
Realtek RTL8029AS - driver loads fine but client32 can't find any servers

Realtek Plug-and-Play ethernet Driver v3.50 (991013)
Realtek RTL8019AS - driver fails to load: "The board did not respond to the initialization command"

**Comment by techpost79** [comment]
Thanks for the above, really useful insight. Strangely I have no problem connecting to a NW 3.12 server running on VirtualBox (same host, using PCap networking) from a 86Box client with either NE2000 or 3c503 NIC.

The problem I see is when I try and run NW3.12 from 86Box (same config as the VirtualBox guest as I have cloned the storage) with either NE2000 or 3c503 NIC, the same client that connects to the VirtualBox hosted NW guest fails to connect to the 86Box guest.

I power the VB Guest down to prevent the NW servers appearing on the same network but whilst the VB Guest clearly broadcasts to show it's presence the 86Box Guest doesn't.

I will also track down a WD8003EB NW driver to try with that too

**Comment by OBattler** [comment]
Does this still occur? The old network stack had a problem of improperly locking the network mutex, so packet corruption was occurring (which is also why there were random stalls occurring when attempting to download files over the Internet, for example). The network stack has been rewritten by elyosh in early August, so this should be retested.

**Comment by techpost79** [comment]
Hey – yes it does unfortunately and bizarrely seems to be a problem for Netware running the IP stack as well. I’ve tested with NW 4.11 and configured both IPX and IP, the problem occurs with both protocols. I can troubleshoot IP better and can see from my packet captures that even sending a ping to the NW4.11 host fails, the source instance sends an arp request and the NW4.11 host returns a corrupt packet so the arp entry isn’t added to the table. If I lift n’shift the instance from 86Box into VirtualBox (and configure the PCnet NIC in the latter), all works as expected on both protocols.

**Comment by cold-brewed** [comment]
Good news on the Netware / IPX front!

I was able to track down the issue causing these malformed packets in Netware (See #3389 for more info). I can confirm that the ne2000 now works with Netware 3.12 and the Novell drivers. I haven’t yet tested any other Netware versions, but I am fairly certain they should all work as well.

The fix should also apply to any cards that are based on the dp8390. For my testing I used base 0x300 and IRQ 10 but any valid combination should work.

As a bonus I also tested:

* ne2k with Novell 2.71 drivers and doom IPX multiplayer: Worked
* Netware 3.12 Server in 86Box. All of the following were also run in 86Box and attached to the Netware server:
	* Novell Netware client DOS drivers
	* Novell DOS 7 with built-in Netware client
	* Windows for Workgroups 3.11 Netware client login
	* Windows 98SE with native IPX and Netware client (this was with the rtl8029as)

I encourage everyone interested to download the [latest CI release](https://ci.86box.net/job/86Box/) and retest.

Screenshots:

Netware console
![console](https://github.com/86Box/86Box/assets/47337035/26be32fc-0b22-4b13-b847-ce0177c0ec20)

WFW 3.11
![Monitor_1_20230603-094523-33033](https://github.com/86Box/86Box/assets/47337035/6a27a63f-1537-48ad-a41a-fc07560f7ecb)

Win98SE
![Monitor_1_20230604-135318-026026](https://github.com/86Box/86Box/assets/47337035/d01ab281-69ed-4193-a106-2bf8b0f8788d)

DOS 6.22
![Monitor_1_20230601-182217-015015](https://github.com/86Box/86Box/assets/47337035/2820e523-0a2e-4c2e-8e5f-327ac55d1a77)
