### ISSUE TITLE
[Feature]IBM Aptiva, ThinkPad & ThinkCentre ROMs on 86Box?

### ISSUE THREAD

**Issue by sanchitabhang14** [86Box/86Box#2398]
If I expect some more ROMs made by IBM & Lenovo, What about IBM Aptiva, ThinkPad & ThinkCentre ROMs on 86Box?

**Comment by OBattler** [comment]
This is the textbook example of how *NOT* to do a feature request - originally posted on the wrong repository, no details provided (which IBM machines should we add exactly?), no information provided for the feature requested, and not even the template was followed. I'm closing this.
