### ISSUE TITLE
[Feature] Remove unused configs in the config file

### ISSUE THREAD

**Issue by piegit** [86Box/86Box#2400]
**Is your feature request related to a problem? Please describe.**
If I have to edit my config manually I don't like that there's multiple entries for some devices because I edited them a lot.

**Describe the solution you'd like**
I want there to be a button in the settings that removes unused entries.

**Describe alternatives you've considered**
Make a script to do the same thing.

**Comment by dhrdlicka** [comment]
Aside from taking up space, these sections do not really break anything. I don't think that adding the ability to clean them up is really worth the effort, sorry.

If you really mind your configuration file having these unused device sections, then you can just remove them manually in your favorite text editor.

**Comment by OBattler** [comment]
I agree with dhrlicka there. Therefore, issue closed.
