### ISSUE TITLE
Add Three Open-Soruce Motherboard BIOSes

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [86Box/86Box#2401]
**Is your feature request related to a problem? Please describe.**
The Micro 8088, Sergey's XT 8088, and Alexandru Groza's ISA 80386DX Singleboard Microcomputer are open-source motherboard BIOSes. You can read these documentations.

https://github.com/skiselev/8088_bios
https://github.com/skiselev/micro_8088
http://www.alexandrugroza.ro/microelectronics/system-design/isa-80386dx-sbmc/index.html

**Describe the solution you'd like**
Add Micro 8088, Sergey's XT 8088, and Alexandru Groza's ISA 80386DX Singleboard Microcomputer.

**Additional context**
Also update Xi8088 BIOS.

**Comment by OBattler** [comment]
Groza's 386DX uses an AMI BIOS.

**Comment by NanaMizukiAnother7** [comment]
So Alexandru Groza's ISA 386DX uses an AMIKey BIOS clone, huh? Even it is a open-source motherboard, I guess it has an AMIKey BIOS clone, but modified.

**Comment by OBattler** [comment]
The first two are one and the same (XT 8088 is the BIOS for the Micro 8088) and the board is a less capable variant of the Xi8088. I think it's pointless to add this.
