### ISSUE TITLE
Thrustmaster T-Flight Stick X joystick integrated throttle not working

### ISSUE THREAD

**Issue by MX9000** [86Box/86Box#2403]
**Describe the bug**
In the 86Box documentation it is explained that the "3-axis, 2-button joystick" and "3-axis, 4-button joystick" types should support throttle input. But the Terminal Velocity DOS game calibration screen does not detect throttle input with any of the joysticks available in the 86Box drop-down menu.

**To Reproduce**
1. Install Terminal Velocity DOS game
2. Enter in the menu Options > Control Options
3. Choose Control = Joy/Throt or CH Flight Pro
4. Choose Calibrate and try to see if the throttle lever movements are detected

**Expected behavior**
The third value in the calibration screen should change from 0 to 128 (MIN/MAX throttle as tested in DOSBox-X)

**Screenshots**
![Terminal Velocity Joystick Calibration](https://user-images.githubusercontent.com/58113425/174771910-d642743c-4377-4d4b-8ab1-23a78c3df63e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - 86Box version: 3.5 build 3777
 - Build information: 86Box-Windows-64-b3777.zip

**Additional context**
86Box configuration: Pentium 166, 32 MB RAM, S3 Trio 64, SB16, MS-DOS 6.22

**Comment by OBattler** [comment]
Does this still occur?

**Comment by OBattler** [comment]
Try the latest build of 86Box - there's been quite a few Joystick fixes then.

**Comment by MX9000** [comment]
I retested the latest version (4.1 build 5555, i386, old dynarec) but the issue with the third axis is still the same.
I will soon buy a new joystick with integrated throttle and update this bug report.
Thanks for your attention.

**Comment by MX9000** [comment]
@OBattler I bought a new joystick with built-in throttle: VKB Gladiator NXT EVO "Space Combat Edition".
I repeated the tests with the latest builds of 86Box (86Box-Qt-ODR-Dev-Windows-MINGW64-gha1472.zip and 86Box-Qt-NDR-Dev-Windows-MINGW64-gha1472.zip) and the throttle is recognized as Z-axis only by selecting the joystick type CH Flightstick Pro.

![Joystick Conf](https://github.com/86Box/86Box/assets/58113425/679390cd-d098-427c-98bb-212a040b1051)

**Comment by OBattler** [comment]
That is, in fact, correct. The standard 3-axis joysticks support 3 standard axes, not 2 standard axes and throttle. So this can be closed as NOTABUG.
