### ISSUE TITLE
[Bug] Renderer doesn't switch properly and screen goes black

### ISSUE THREAD

**Issue by piegit** [86Box/86Box#2410]
**Describe the bug**
When I change renderers the screen blacks out sometimes

**To Reproduce**
1. Change renderer
2. Sometimes the renderer doesn't switch fully

**Expected behavior**
Renderer should change completely

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.5 [build 3806] [68853511]

**Comment by Cacodemon345** [comment]
Test with build 3807. The 1-second black screen that will happen if this case is encountered is intentional.
