### ISSUE TITLE
Crash after loading OS/2 1.2 DOS console with the 8514 card.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2414]
**Describe the bug**
The machine crash after I try to load the DOS windows on a full screen under OS/2 1.2 with 8514 graphics card.

HDD, CFG nd NVR files:
[IBM PS-2 70 OS-2 12.zip](https://github.com/86Box/86Box/files/8987648/IBM.PS-2.70.OS-2.12.zip)
[IBM PS-2 Model 70 OS-2 1.2.zip](https://github.com/86Box/86Box/files/8987649/IBM.PS-2.Model.70.OS-2.1.2.zip)

**To Reproduce**
1. Start the machine
2. On the "Main window" do double click on "OS/2 DOS full screen"
3. The screen turns green and freezes

**Expected behavior**
This should not happen

**Screenshots**

Normal screen after startup and loading Word for OS/2 ver 1.1:

![OS-2 12 IBM 8514](https://user-images.githubusercontent.com/31600563/175836504-44a75ee2-7755-4734-a1c2-1d80c1d3b859.png)

After  the crash:

![Full screen crash](https://user-images.githubusercontent.com/31600563/175836523-a114dc5f-673b-4ae2-84c3-d37e22da1e7f.png)

**Desktop (please complete the following information):**
 - OS: Win 10 21H2
 - 86Box version: 3.5.0.3805
 - Build information: old dynarec, regular Win 32

**Comment by NanaMizukiAnother7** [comment]
This should be fixed by #2413.

**Comment by TC1995** [comment]
I see you're using ESDI MCA. It might be that.

**Comment by TC1995** [comment]
> This should be fixed by #2413.

It's not, but I'm currently working on it.

**Comment by TC1995** [comment]
Also, it doesn't crash, it just doesn't load the vga text mode and the passthrough values of the 8514/A card remain unchanged when switching from 8514/A to VGA Text mode, I don't know why, let me test it with the ESDI controller using the 50 or 70-80.

**Comment by TC1995** [comment]
Situation is normal, it's a wrong setting in config.sys.
Make sure the following lines are there and only these for 8514/A/VGA.
SET VIDEO_DEVICES=VIO_IBM8514A
SET VIO_IBM8514A=DEVICE(BVHVGA,BVH8514A)

**Comment by OBattler** [comment]
Then this can be closed with NOTABUG.
