### ISSUE TITLE
Install Windows98SE failed

### ISSUE THREAD

**Issue by songday** [86Box/86Box#2420]
**Describe the bug**
Install `Windows98SE (Simplified Chinese)` failed  
I tried 2 times, but both stuck at 70%

**To Reproduce**
None, since this may be an issue with a particular ISO file

**Expected behavior**
Install Windows98 SE successfully.  
I tested `PCem V18` `VMWare player 16` and `VirtualBox 6` with the same ISO file, all good.

**Screenshots**
![20220702-171746-659659](https://user-images.githubusercontent.com/209001/176994714-e01b675b-f2e5-4a85-a788-baf84f98e194.png)  
Errors in Chinese, translated to English were:
The setup program can not read from Windows 98 CD file, please take a look at setup.txt for more details  
( I don't know how to copy files from 86box VM to my desktop )

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - 86Box version: v3.60 build 3850
 - ROM version: 20220701 ROM Set (86Box 3.6 release)

`Host informations`:
1. CPU: Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz   2.53 GHz
2. RAM:8G
3. HardDisk: 500G

`Guest config`:
```
[General]
vid_renderer = qt_software

[Machine]
machine = 430vx
cpu_family = pentium_p55c
cpu_speed = 166666666
cpu_multi = 2.5
fpu_type = internal
cpu_use_dynarec = 1
time_sync = local
cpu = 10
mem_size = 131072

[Video]
gfxcard = trio64v2dx_pci
voodoo = 1

[Input devices]
mouse_type = logibus

[Sound]
sndcard = sb16

[Storage controllers]
hdc = ide_pci
cassette_enabled = 0
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 6221, 0, ide
hdd_01_fn = win98
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_check_bpb = 0
fdd_02_type = none
cdrom_01_speed = 72
cdrom_01_parameters = 0, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = D:/retro/Windows98se.iso
```

**Additional context**
None

**Comment by songday** [comment]
Tried reducing emulated CD-ROM speech to 32 and 8, but still got the same error as above.

**Comment by hyanggi** [comment]
I found this after searching the web (for reference):
http://www.helpwithwindows.com/windows98/troub-081.html

**Comment by OBattler** [comment]
Can you upload the exact ISO somewhere?

**Comment by songday** [comment]
I uploaded it here:  
https://www.filehosting.org/file/details/9445359/Windows98se.iso

you can use this SN `QY7TT-VJ7VG-7QPHY-QXHD3-B838Q` for installation

**Comment by jriwanek** [comment]
@songday don't post links to iso's or CD keys thanks.

**Comment by songday** [comment]
> @songday don't post links to iso's or CD keys thanks.

Got it.  
How can I provide my ISO to `OBattler`?

**Comment by jriwanek** [comment]
I suggest coming to our discord

**Comment by OBattler** [comment]
- jriwanek: How do you suggest they do that when they are most likely from China where Discord is banned?

Also, posting links to ISO's was never a problem here, why has this rule suddenly been imposed without even consulting with me first?

**Comment by OBattler** [comment]
- songday: It is perfectly fine to post a link to the ISO here, just don't post serial numbers.

**Comment by songday** [comment]
Hi, OBattler. Here's the link to the ISO:  
https://www.filehosting.org/file/details/9445359/Windows98se.iso

**Comment by OBattler** [comment]
Does the problem still happen? TC1995 told me he could not reproduce it.

**Comment by OBattler** [comment]
@songday - What boot disk did you use?

**Comment by OBattler** [comment]
In any case, I suggest retesting since there has been hard disk timing changes since then which may have affected this.

**Comment by songday** [comment]
Sure, I'll test again later on by using 3.7 version, and give a feedback
