### ISSUE TITLE
SHUTTLE HOT 557 MOTHERBOARD PERFORMANCE ISSUE

### ISSUE THREAD

**Issue by TheNoob1703** [86Box/86Box#2421]
**Performance issue using the SHuttle HOT-557**
I'm using the Old and the new (beta) recompiler version of 86Box, and testing using 2 equal computers (i7-7700k) i've found that using the mentioned motherboard (Socket 7 Dual Voltage) with an MMX 200Mhz and 64mb of Ram causes this:

- using Vulkan: between 65-91%
- using qt's renderer: 55-60%
- using the new direct 3d 9: the same % as above

the expected performance using the version 3.0 was 100% including  heavy games for the general specs i've specified above

 - OS: Windows 10 Pro  21h2 x64
 - 86Box version: 3.6 Build 3852
 - Build information: old recompiler, x64 bit architecture build 3852

**Comment by TC1995** [comment]
Use the x86 one.

**Comment by JimboMumbo** [comment]
I guess I'll test shuttle hot 557 when i finished creating the machine.

**Comment by OBattler** [comment]
- TheNoob1703: Can you try all the release from v3.0 to v3.6 and see which one specifically worsened the performance?

**Comment by TheNoob1703** [comment]
I've tried the following versions without issues:

- v3.0 -> OK
- v3.1 -> OK
- v3.2 -> OK
- v3.3 -> OK, but sometimes a little buggy
- v3.4 -> OK
- v3.5 -> OK
- v3.6 -> Stable

Conclusion? I couldn't find the issue, maybe some outdated GPU drivers and an unstable build of WIndows 11?

**Comment by JimboMumbo** [comment]
> maybe some outdated GPU drivers and an unstable build of WIndows 11?

try updating them
