### ISSUE TITLE
Black screen on Olivetti M21/24/24SP with external video

### ISSUE THREAD

**Issue by KeishiX** [86Box/86Box#2422]
**Describe the bug**
VM shows black screen upon startup if configured with any external video controller. Tried EGA, ATI EGA Wonder 800+, some VGA cards.

**To Reproduce**

**Expected behavior**
It should display POST messages and then DOS command prompt, as it did on previous builds, or as it does with internal video controller.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.60 build 3852
 - Build information: x86, old recompiler

**Additional context**
VM seem to be working fine, i.e. it beeps normally on startup, just doesn't display anything.
On build 3851 and older it worked fine with any external video controllers I tried.
[vm_cfg.zip](https://github.com/86Box/86Box/files/9033077/vm_cfg.zip)

**Comment by dhrdlicka** [comment]
I reverted the changes from build 3852.
