### ISSUE TITLE
Add Settings for Crystal CS4235 and CS4236B

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [86Box/86Box#2423]
**Is your feature request related to a problem? Please describe.**
When I install the Crystal CS4235 sound driver on Windows 3.1, an error occurs that the settings are not invaild and the driver is not present.

**Describe the solution you'd like**
Please add the sound settings for Crystal CS4235 and CS 4236B.

**Additional context**
When exiting Windows 3.1, the machine hangs with a DOS blinking line.

**Comment by TC1995** [comment]
I believe ISA PNP sound cards don't have those settings you're talking about.

**Comment by NanaMizukiAnother7** [comment]
I see. Closing this until someone looks for its behavior.

**Comment by JimboMumbo** [comment]
Not so fast! Here's the latest dos drives but it's only for windows 98 sadly. https://www.philscomputerlab.com/crystal-cx4235.html
