### ISSUE TITLE
[Feature] Pixel-Perfect Scaling for Fullscreen and Windowed

### ISSUE THREAD

**Issue by nickkeane** [86Box/86Box#2429]
A pixel-perfect centered scaling mode with adjustable scaling percentages would be much appreciated, for both Fullscreen and Windowed modes.

Also, Windowed Mode seems to be missing a way to have the correct. My other PCem box allows for the correct aspect ratio when the windowed mode is maximized (86Box stretches the entire image across the screen), so i'm not sure if that functionality being missing is a regression, or if it was added after the fork from PCem, or i'm just missing the settings for that.

**Comment by JimboMumbo** [comment]
maybe exit and reopen your Virtual Machine? IDK if I'm wrong here, someone should tweak some full-screen/windows resolutions to feel better. And as for pixel-perfect centered scaling mode with adjustable scaling percentages, I thought 86box has a option for CGA/VGA, but oh well.

**Comment by OBattler** [comment]
I believe these features were added to PCem in their WxWidgets port which occurred after we forked.

**Comment by dhrdlicka** [comment]
There already is #1783 for resizable windows with a centered screen view, so adding scaling to that would be a pretty natural extension to that.

**Comment by OBattler** [comment]
I guess this can be closed then in favor of the issue mentioned where the discussion can be continued.
