### ISSUE TITLE
[bug] black string on bottom in opengl mode

### ISSUE THREAD

**Issue by yarik303** [86Box/86Box#2430]
**Describe the bug**
when i set render to opengl on bottom of a screen something black line appears
on qt its not happening

**To Reproduce**
1. Go to 'Rendering'
2. Click on 'Opengl'
3. See error

**Expected behavior**
i wanna to bug to be fixed cuz some parts can't be seen cuz of this bug

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
no screenshot video in link (https://streamable.com/bbx89f)
**Desktop (please complete the following information):**
 - OS: Windows 7
 - 86Box version: v3.6 [build 3858]
 -  Build information: [i.e. new/old dynarec, architecture and build type]
 - .. what do u mean its microsoft virtual pc 2007

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by OBattler** [comment]
This appears to be a known bug that, however, us developers seem to be unable to reproduce, for some reason. It seems to only appen with Intel HD graphics.

**Comment by OBattler** [comment]
This has since been fixed.
