### ISSUE TITLE
Emulation of the Diamond Edge 3D (nVidia NV1) graphics card.

### ISSUE THREAD

**Issue by Winins0** [86Box/86Box#2431]
**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem.

**Describe the solution you'd like**
The nVidia NV1 is a pretty interesting GPU, released in 1995. It had 3D graphics with quadratic texture mapping, an integrated 32 channel sound card and even a Sega Saturn compatible game port. While it flopped in the market, it is still very interesting in my opinion and is worthy of emulation. 

However, I believe it would be a pain in the ass to emulate, and I don't think it will be ready until 2035 or something. Still, I will try to provide as much info as I can here.

**Describe alternatives you've considered**
None.

**Additional context**
[Here](https://github.com/86Box/86Box/files/9054050/VIDBIOS.zip)  is the BIOS for the Diamond Edge 3D 2000 series. It should work with the 2120 and 2200.
[stg2000.pdf](https://github.com/86Box/86Box/files/9054055/stg2000.pdf)
[stg2000_sep96.pdf](https://github.com/86Box/86Box/files/9054056/stg2000_sep96.pdf)
[stg2000rev_c_preliminary_apr96.pdf](https://github.com/86Box/86Box/files/9054057/stg2000rev_c_preliminary_apr96.pdf)
These are 3 datasheets I found for the NV1 chip. It was manufactured by ST as STG-2000, but it should be identical.

**Comment by Cacodemon345** [comment]
Not possible.

**Comment by jmredfern** [comment]
I discussed this with the 86box developers previously, there's a lack of technical schematics for the nv1 which would be needed, iirc.

**Comment by Winins0** [comment]
> Not possible.

Too bad.

**Comment by JimboMumbo** [comment]
Maybe next year, buddy.

**Comment by Winins0** [comment]
> Maybe next year, buddy.

The way they worded it sounds like it won't happen at all. Like, not even in 50 years.

**Comment by JimboMumbo** [comment]
Very well. LGR did a thing on that card: https://www.youtube.com/watch?v=jChtlWNIAL4
