### ISSUE TITLE
Taking a screenshot causes a speed drop

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [86Box/86Box#2444]
**Describe the bug**
When the multi-monitor support is added, when you take a screenshot, the speed half-drops into 50%. Also creates a bunch of screenshot duplicates.

**To Reproduce**

**Expected behavior**
It should not drop speed into 50%.

**Screenshots**
![Capture-86Box-July-11-2022--10-38-00AM-NMA07](https://user-images.githubusercontent.com/78664512/178184177-c3685cc5-ca01-4e66-8d72-f8f5e96a1251.png)

**Desktop (please complete the following information):**
 - OS: Windows 7. build 7601 (Service Pack 1)
 - 86Box version: v3.6 GIT-master
 - Build information: ODR

**Comment by Cacodemon345** [comment]
Does it stay that way after the screenshots are taken?

**Comment by NanaMizukiAnother7** [comment]
Fixed by 30479fc3b916e38ceadcadc228cfc9a9549db9a4, closing.
