### ISSUE TITLE
XGA-1 glitches

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2458]
**Describe the bug**
I found some glitches with XGA-1 emulation with Windows 2.11/286. The XGA-1 emulation with HIMEM.SYS loaded.

Bugs:

- There is some garbage when I exit Windoes 2.11/286.
- There is some strange behaviour with Quadtel RAM Utilities. It has a 386 Expanded memory manager, but when I try to load Windows 2.11/286 on DOS 3.3x It crashes the emulator. On DOS 4.0 it reports some kind of V86 violation at DOS boot.

PD: But I'm not sure if it is an 86box bug or a Quadtel driver limitation. I found also, that the Quadtel EMS driver for the Headland hardware chipset G103/118 on 286/386sx, is not compatible with HIMEM.SYS except when shadows RAM and Video are enabled on the Trigem 286 machine.

**Screenshots**

![XGA-1 config sys](https://user-images.githubusercontent.com/31600563/179098604-82a0dc8f-db74-4796-8925-eb87557e08a6.png)
![XGA-1 with 8515 fonts](https://user-images.githubusercontent.com/31600563/179098624-348ed6dc-767e-4331-bd31-c28f60741cdf.png)
![strange characters after exiting windows](https://user-images.githubusercontent.com/31600563/179098637-a55e60c8-90c6-4b4e-bd96-da8e0ea826f8.png)

The CHKMEM utility crash if the MM.SYS (386 memory manager)  is not installed.
![CHKMEM crash if](https://user-images.githubusercontent.com/31600563/179098812-6f90530d-7883-453f-bfbd-f3d069126f7b.png)

**To Reproduce**
1. Modifify the CONFIG.SYS to load the MM.SYS driver
2. Type Win at DOS prompt
3. The machine crash.

HDD, CFG and NVR files: 
[386 DX XGA-1 win 211 DOS 331.zip](https://github.com/86Box/86Box/files/9115959/386.DX.XGA-1.win.211.DOS.331.zip)

[386 DX XGA-1 Win 211 experiment.zip](https://github.com/86Box/86Box/files/9115960/386.DX.XGA-1.Win.211.experiment.zip)

**Desktop (please complete the following information):**
 - OS: Win 10 21H1
 - 86Box version: 3.6.0.3901
 - Build information: old dynarec

**Comment by Fenix770** [comment]
After installing QEMM 6.02 I get a black screen  with the mouse cursor after loading WIN.COM. 
PD: I don't know if I should add some exclusion on the upper memory area.
![black screen with QEMM 6 02](https://user-images.githubusercontent.com/31600563/179100502-644dd4f6-7bb4-486d-a9c4-63b95bd54497.png)

**Comment by TC1995** [comment]
Well, not sure about solving the garbage one in the code.

**Comment by TC1995** [comment]
What's weird the garbage upon exiting Windows doesn't happen on win3.x, granted they are different drivers, but still.

**Comment by Fenix770** [comment]
I also found that the XGA-1 does not works on Win 3.0 Multimedia for some reason. I tested both, the  version 1.20 of the drivers and 1.26. Also the AI DOS drivers does not detect the XGA. When loading DOS, throws the "-XGA" message that means it were not detected.

Here are the HDD,CFG and NVR files with the driver disks to test.

HDD:
[IBM PS-2 Model 80 Ultimedia XGA.zip](https://github.com/86Box/86Box/files/9126710/IBM.PS-2.Model.80.Ultimedia.XGA.zip)

CFG+NVR: 
[IBM PS-2 Model 80  XGA.zip](https://github.com/86Box/86Box/files/9126716/IBM.PS-2.Model.80.XGA.zip)

Driver disks:
 
For Win 3.0 Ver 1.20+ Win 2.11
[XGA Win 21-30.zip](https://github.com/86Box/86Box/files/9126718/XGA.Win.21-30.zip)

For Win 3.0 Ver 1.26
[XGA WIN 30.zip](https://github.com/86Box/86Box/files/9126719/XGA.WIN.30.zip)

Configuration:

OS: Win 10 21H1
86Box version: 3.6.0.3906
Build information: old dynare

**Comment by TC1995** [comment]
first, for the win3.0 multimedia one, you need to use the 4MB aperture, which is what it needs even if memory is lower than 16mb.

**Comment by TC1995** [comment]
As for the AI interface, I had to change one thing to make it not throw "-XGA".

**Comment by Fenix770** [comment]
I found that the aperture size options go from 7 mb to 15 mb, on the setup disk, also I changed the memory region from C000 to D000 in both the setup disk and 86box configuration but still no avail.

**Comment by TC1995** [comment]
Ergo, disable the 1mb aperture.

**Comment by OBattler** [comment]
Does this issue still persist?

**Comment by TC1995** [comment]
Well, on my end it worked.

**Comment by OBattler** [comment]
Well, I'm going to assume that that this is NOTABUG then and Fenix just needs to disable that 1 MB VRAM aperture.
