### ISSUE TITLE
Use standard config file location on Linux

### ISSUE THREAD

**Issue by AsciiWolf** [86Box/86Box#2477]
Currently, the 86box.cfg config file seems to get created directly in the user's home (`~/`) directory. This is incorrect and incompatible for example with Flatpak. Please, consider using standard XDG directories (`~/.config`, `~/.local/share` ...) or at least an own directory inside home (`~/.86box`) to store the config file into. The same thing would be ideal for the roms directory as well. Thanks!

**Comment by OBattler** [comment]
The configuration file is part of the virtual machine. You can choose your own path for it with -P a.k.a. --vmpath. This is going to be properly addressed when we split global settings from per-VM settings and implement the planned built-in manager which is going to appear when you start 86Box without -P / --vmpath.

**Comment by dhrdlicka** [comment]
To be more exact, the config file gets created in the current directory since that is the default path for the virtual machine files.

**Comment by dhrdlicka** [comment]
Also, could you be more specific about the ROMs directory issues you've encountered? These should respect the standard XDG paths already.

**Comment by AsciiWolf** [comment]
They did not. I think I already mentioned the issues in https://github.com/flathub/flathub/pull/3337, but I don't remember exactly what the problem was, sorry. Anyway, I was able to workaround it, 86Box is now available on Flathub and works great.

**Comment by OBattler** [comment]
Then I guess this can be closed.
