### ISSUE TITLE
Emulate the Two Promise Controllers

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [86Box/86Box#2479]
**Is your feature request related to a problem? Please describe.**
When I was looking for Kugee's videos, I already noticed that one of his computers using the Promise ULTRA33 controller (from 1997) of its internal ones. I also found that there is also controller called the EIDE 4030+, made by Promise Technologies itself.

**Describe the solution you'd like**
Please add and emulate the Promise EIDE 4030+ and ULTRA33 controllers.

**Additional context**
EIDE 4030+ Manual: http://www.outfoxed.net/4030_plus/EIDE-4030-Plus-Manual.rar
EIDE 4030+ Datasheet: not found yet
EIDE 4030+ BIOS: https://www.vogons.org/download/file.php?id=82982
ULTRA33 Manual: https://www.manualslib.com/manual/1810149/Promise-Ultra33.html
ULTRA33 Datasheet: https://www.datasheetarchive.com/Ultra33%20-datasheet.html
ULTRA33 BIOS: not found yet

**Comment by OBattler** [comment]
There is no datasheet of the ULTRA33 there, the only datasheets are for a completely unrelated Cypress chip.

Closing this with "Can't add, no documentation".

**Comment by NanaMizukiAnother7** [comment]
I have removed the datasheet for ULTRA33 because that IDE controller has no datasheet.

**Comment by NanaMizukiAnother7** [comment]
Reopen this, OBattler. These controllers do not have its datasheets. They got its manuals instead. I hope they will be added soon. :)

**Comment by NanaMizukiAnother7** [comment]
You may add three of them. I had to remove datasheets for them because these do not have datasheets...

**Comment by NanaMizukiAnother7** [comment]
> There is no datasheet of the ULTRA33 there, the only datasheets are for a completely unrelated Cypress chip.
> 
> Closing this with "Can't add, no documentation".

I have removed the datasheets because these do not have any datasheet. They have its manuals instead.

**Comment by NanaMizukiAnother7** [comment]
@OBattler Reopen this, because these controllers do not have any datasheets, they only have manuals. I hope these will be added soon.
