### ISSUE TITLE
Flathub build

### ISSUE THREAD

**Issue by AsciiWolf** [86Box/86Box#2483]
I am working on a 86Box Flatpak and want to publish it on [Flathub](https://flathub.org/). Please, let me know whether you are interested in co-maintaining the Flatpak. Thanks! :-)

**Comment by dhrdlicka** [comment]
Hi, I noticed that you ran into the `Dynarec is incompatible with target platform arm64` configure error. This is because ARMv7 and ARMv8 dynarec implementations are only available with `NEW_DYNAREC=ON`, so you might want to enable that for the ARM builds.

**Comment by rderooy** [comment]
I considered creating one some time ago. I also maintain the flatpak for dosbox-x and co-maintain it for dosbox-staging.

- The issue I faced was:
- ROM directory is hardcoded to be a subdirectory where the executable is located.
- multiple config files for machines are not handled, which complicates launching from a desktop icon
- Possible copyright issue with bundling ROMs with the flatpak, so ROMs would have to be user supplied

**Comment by dhrdlicka** [comment]
> ROM directory is hardcoded to be a subdirectory where the executable is located.

This was actually improved in 3.4, see the [documentation](https://86box.readthedocs.io/en/latest/usage/roms.html)

**Comment by AsciiWolf** [comment]
> Hi, I noticed that you ran into the `Dynarec is incompatible with target platform arm64` configure error. This is because ARMv7 and ARMv8 dynarec implementations are only available with `NEW_DYNAREC=ON`, so you might want to enable that for the ARM builds.

Thanks! I will try that.

>Possible copyright issue with bundling ROMs with the flatpak, so ROMs would have to be user supplied

The ROMs are not a part of the Flatpak. The 86Box Flatpak uses an extension that can be installed along with the base Flatpak application and actually downloads the ROMs from GitHub during its installation - so the ROMs are not even bundled as a part of the extension.

**Comment by rderooy** [comment]
> > ROM directory is hardcoded to be a subdirectory where the executable is located.
> 
> This was actually improved in 3.4, see the [documentation](https://86box.readthedocs.io/en/latest/usage/roms.html)

Thanks for that, I had missed that change. I have created a MR to remove the symlink hack from the RPM spec file, which is no longer needed.

**Comment by AsciiWolf** [comment]
@dhrdlicka The ARM64 build now fails on `error: ‘PFNGLBUFFERSTORAGEPROC’ does not name a type; did you mean ‘PFNGLBUFFERSTORAGEEXTPROC’?`, see the [full log](https://github.com/flathub/net._86box._86Box/pull/2#issuecomment-1200424942).

**Comment by Cacodemon345** [comment]
That latter one is an alternate typedef apparently only available in GLES2 headers.

**Comment by Cacodemon345** [comment]
@AsciiWolf Try again if possible with latest commit.

**Comment by AsciiWolf** [comment]
@Cacodemon345 It seems to build fine now, thanks! :-) I will enable the ARM64 build when new 86Box release with the fix included is tagged. :-)

**Comment by OBattler** [comment]
I guess this can be closed now.
