### ISSUE TITLE
IBM PS/2 model 70 type 3 mca device does not appear

### ISSUE THREAD

**Issue by thecheese2022** [86Box/86Box#2493]
**Describe the bug**
While checking internal graphics card if fail or not to report issues I  discovered that non mca device appear 
**To Reproduce**
1. Go to Tools Settings
2. view Display Sound Network SLiRP Storage Controller HD and SCSI
![captura188](https://user-images.githubusercontent.com/102922015/180471317-9af8b10e-e166-4510-8343-6c074b6b20c8.PNG)

**Expected behavior**
no internal graphics appear
non mca device appears 
**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10 2004
 - 86Box version:  v3.6 build 3953 a11b7318
 - Build information: old dynarec Win 32

**Comment by TC1995** [comment]
This MCA model doesn't allow non-MCA devices.

**Comment by TC1995** [comment]
Wait, I can confirm this bug, let me check the source.
