### ISSUE TITLE
CD-ROM music tracks cannot be heard under DOS/Windows 3.11 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2502]
**Describe the bug**
Either DOS or Windows 3.11 detects the music tracks of the GTA and GTA London 1969 expansion, but nothing can be heard.
The MIDI files and sound efects works just fine. The Creative CD utility to play CD music tracks included on SB16 drivers for Win 3.1 detects the track number correctly and plays the tracks, but nothing can be heard. I ruled out a volume problem because I put the CD volume at maximum on both Windows 3.11 and in DOS using MIXERSET utility before starting GTA under DOS.

I tried different mainboards and device drivers. For example I tested VIDE-CDD.SYS with MSCDEX, and XCDROM.SYS with SUSHCDEX

PD:
1. I tested the image file with Daemon Tools under native Win 10 player and VLC detects the tracks just fine, also Win 95 can detect play the tracks flawlessly
2. link to GTA and GTA London 1969 expansion both in BIN/CUE format:
3. 
https://archive.org/details/GrandTheftAuto_201903
https://archive.org/download/GTALONDON

HDD,NVR and CFG files 
link to the HDD
https://drive.google.com/file/d/18BXUy6WW9loz67z176mEFPpZhgNxCn0C/view?usp=sharing

CFG and NVR file
[Pentium 60 S3 Trio 3D.zip](https://github.com/86Box/86Box/files/9173652/Pentium.60.S3.Trio.3D.zip)

**To Reproduce**
1. Start the VM
2. Run GTA 3DFX for DOS. (Shell C:\GTA\GTADOS\GTAFX.EXE file)
4. The game runs fine, (except for a small black line on the top of the screen) but no music track can be heard

**Expected behavior**

**Screenshots**
![Music tracks](https://user-images.githubusercontent.com/31600563/180603535-f26c3511-9694-455c-8a94-27e4431b5bb8.png)

**Desktop (please complete the following information):**
 - OS: Win 10 21H2
 - 86Box version: 3.6.0.3960
 - Build information: old dynarec, Win 32

**Comment by TC1995** [comment]
Have you tried using mscdex with oakcdrom?
I might investigate it with your configuration.

**Comment by Fenix770** [comment]
I tested under Win 95, and pure DOS mode under Win 95. The sound track works fine, both on Win 95 player and the DOS version of MPXPLAY. However, The game seems to support the 3DFX card only under DOS, so I created a Win95 boot disk with the CD-ROM drivers (XCDROM.SYS + MSCDEX 2.25) and installed the SB16 driver for Windows Win 95. For the games the SET BLASTER variable is enough to detect the card. 
The only issue, (*related to the OS, not 86box*) is if I add the CD-ROM DOS drivers to Win 95 CONFIG.SYS and AUTOEXEC.BAT it will start in 16-bit compatibIlity mode.

PD: About the issue with DOS 6.x/Win 3.1 I'm not sure if it is a game bug, a 86Box bug or a DOS limitation. Back in the day I tested a game called Time Commando, the music tracks worked fine under Win 95 version and DOS version. The game claimed to be compatible with DOS 6.22. 
The machine had two CONFIG.SYS and AUTOEXEC.BAT versions, one for Windows and another that was loaded when I chose MS-DOS mode on the "turn off the system menu".

![GTA Win95](https://user-images.githubusercontent.com/31600563/180629111-edbcdbfa-4ae5-489a-b237-6fa00532e9b6.png)

**Comment by silverlays** [comment]
Is every other audio discs work ? I faced the same issue days ago. I had to try many cdrom drivers before finding a good one.

I've uploaded a floppy with many drivers (found in <atapi> folder) here: [CDROM and SCSI.IMA](https://www.mediafire.com/file/7ckqf7x2fmow8vm/CDROM+and+SCSI.IMA/file)

Give the <gscdrom.sys> and <cdrom.sys> a try. For me, the <gscdrom.sys> fixed all my audio tracks problems.

Good luck 😊

**Comment by Fenix770** [comment]
I tried different drivers. It seems to affect DOS/WIN 3.1. The only strange thing on the CD is the track 1 contains data. So only track 2 onwards can be played. Win 95 and pure DOS mode under it (DOS 7.1) detects the tracks right.

**Comment by silverlays** [comment]
> I tried different drivers. It seems to affect DOS/WIN 3.1. The only strange thing on the CD is the track 1 contains data. So only track 2 onwards can be played. Win 95 and pure DOS mode under it (DOS 7.1) detects the tracks right.

It's a DOS drivers limitation with the CDROM format ISO9660 and Joliet. on a real CD, the track 1 is always the data track, and the next ones are the audio tracks.

For example, with a real audio CD (only) on Win95+, you can see the tracksXX.cda on the disc with the explorer, but on DOS/Win3x, the CD cannot be detected at all. That's the reason why i had to look for differents drivers to find the one who can detect the CD on DOS & Win3x.

One last thing, DON'T use the 32bits disk access in Win3x or it will simply crash.

**Comment by OBattler** [comment]
- Fenix770: OAKCDROM.SYS and VIDE-CDD.SYS version 2.15 should work fine. If you switched to anything with an Intel chipset that's 430FX or later, you could also use the Triones PIIX DMA drivers for both DOS and Windows 3.11 that also support mixed-mode CD's fine, or least the 3.20 drivers do, I belive I had a bug with 3.70.

**Comment by silverlays** [comment]
i make a small correction, it wasn't the <gscdrom.sys> who works fine, it was <actcd.sys>. But of course, you can test the @OBattler solution 😊

**Comment by Fenix770** [comment]
Yes, I used VIDE-CDD.SYS and MSCDEX. VIDE-CDD uses only 5kb of low RAM.  I found something strange. MPXPLAY for DOS plays the tracks right on DOS 6.22, but Creative CD under Win 3.1 cannot. May be some kind of software incompatibility.
I think MPXPLAY requires MSCDEX (stop responding with SHSUCDX) but does not cares about the CD-ROM driver type.

**Comment by OBattler** [comment]
I used to use SHSUCDX but I went back to MSCDEX because SHSUCDX was not as compatible.

Can you upload the VM?

**Comment by OBattler** [comment]
I guess this can be closed since it turned to be a driver incompatibility.
