### ISSUE TITLE
[Feature] Open-Source Multi-Floppy BIOS Support?

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [86Box/86Box#2507]
**Is your feature request related to a problem? Please describe.**
I have looked for a 8088 Domination video, I noticed that he is using an open-source Multi-Floppy BIOS made by Sergey Kiselev.

**Describe the solution you'd like**
Add the open-source Multi-Floppy BIOS to the floppy disk setting selection.

**Additional context**
Link for the Multi-Floppy BIOS: https://github.com/skiselev/floppy_bios

**Comment by OBattler** [comment]
Closing since we have no binary of this BIOS.

**Comment by jriwanek** [comment]
The BIOS is linked under additional context, [floppy_bios.bin](https://github.com/skiselev/floppy_bios/blob/master/floppy_bios.bin), source is in that repo
