### ISSUE TITLE
libfreetype  on macOS

### ISSUE THREAD

**Issue by startmenu** [86Box/86Box#2516]
**Describe the bug**
libfreetype.6.dylib is bundled with 86Box.app but it still says "libfreetype is required for ESC/P printer emulation." 
and the same thing happens with libfluidsynth and libgs when builded from source with dependencies installed.

**Comment by jriwanek** [comment]
Is this on M1 mac or x86 mac, or both?

**Comment by startmenu** [comment]
> Is this on M1 mac or x86 mac, or both?

I use MacBook M1, but I tried both native and Rosetta, with the same result.

**Comment by jriwanek** [comment]
Okies, we'll have someone looking into it soon, thankies.

**Comment by cold-brewed** [comment]
I'm looking into this. It appears to be an issue with runtime loading of bundled dynamic libraries.
