### ISSUE TITLE
Emulation speed issues between two similarly clocked cpu

### ISSUE THREAD

**Issue by dfgdgdgfd** [86Box/86Box#252]
I'm trying to run dos doom (it's a long story why, want to see how old mods run on older hardware) and I the highest emulated cpu I can get running at 100% if about a 486dx25, on an i7-870.  On my 4690k at 4.2ghz overclocked cpu's all the way up to a pentium 200mmx run flawlessly at 100% emulation speed.  Is there really such a huge performance difference with my two systems or should I be looking into something else causing the problem?

**Comment by eton975** [comment]
I would see if your CPU is overheating or downclocking itself - a properly running i7-870 should be able to do at least a Pentium-90 rig at full speed under most applications (barring those that hammer memory in strange ways/self-modifying code).

Task manager, Speccy, HWInfo, CPU-Z can tell you clocks and temp info.

**Comment by dfgdgdgfd** [comment]
> a properly running i7-870 should be able to do at least a Pentium-90 rig at full speed under most applications (barring those that hammer memory in strange ways/self-modifying code).I

 had to change cpu_use_dynarec to 1, and I'm getting around pentium 90 speed fine.  Is there any reason why this was set to zero in the first place?

**Comment by OBattler** [comment]
The emulator by default sets cpu_use_dynarec to 1 for Pentiums and does not even allow turning it off. So it's rather weird that it was set to 0.

**Comment by dfgdgdgfd** [comment]
> The emulator by default sets cpu_use_dynarec to 1 for Pentiums and does not even allow turning it off. So it's rather weird that it was set to 0.

Thanks, I just have a couple more questions:

1) is there any way to get the emulator, in fullscreen, at the same resolution I'd get booting to a dos command prompt on a real machine?  I have a video card and monitor capable of it, just thought I'd ask before trying that all out.

2) Is there any way to up the refresh rate in fullscreen with my crt?

**Comment by OBattler** [comment]
1. No way, not in 86Box v2.00, since the fullscreen mode right now uses whatever resolution you have set on the host side.
2. There's no way to do that. You might be able to up the host refresh rate, but the emulated refresh rate is that provided by the emulated graphics card.

**Comment by dfgdgdgfd** [comment]
> No way, not in 86Box v2.00, since the fullscreen mode right now uses whatever resolution you have set on the host side.

Is there any way to get an older version without having to compile it myself?

**Comment by dfgdgdgfd** [comment]
> No way, not in 86Box v2.00, since the fullscreen mode right now uses whatever resolution you have set on the host side.

Is there any way to get an older version without having to compile it myself?

And is there any way to manage multiple systems, like PCem does with asking you which one to choose upon startup?

**Comment by dhrdlicka** [comment]
>Is there any way to get an older version without having to compile it myself?

Older versions employ the same behavior.

>is there any way to get the emulator, in fullscreen, at the same resolution I'd get booting to a dos command prompt on a real machine? I have a video card and monitor capable of it, just thought I'd ask before trying that all out.

Changing the resolution on the fly is not really possible. You need consider the fact that 86Box emulates some graphic cards with nonstandard graphic modes, where it would have to stretch the VM display anyway. That would pretty much negate the effect. I personally don't think it's worth the effort.

>And is there any way to manage multiple systems, like PCem does with asking you which one to choose upon startup?

Use the `-P` switch to point 86Box to a specific directory with config files, e.g.
`86Box -P C:\configs\win95` tells the emulator to load `86box.cfg` and NVR files from `C:\configs\win95`

**Comment by dfgdgdgfd** [comment]
> Use the -P switch to point 86Box to a specific directory with config files, e.g.
86Box -P C:\configs\win95 tells the emulator to load 86box.cfg and NVR files from C:\configs\win95

I'm now curious about something since I read that this is only a single core application, will using, say, a 3ghz late-model dual core (socket 775) be slower than a 3ghz i5?  How about a 3.4ghz pentium 4?  

Does amount of ram matter (say, 2-4ghz) if running nothing else in windows?  How about ddr2 vs 3 ram?  Will that make a difference?

Sorry about all the questions, just want to pick the best system that will be dedicated to running the emulator with the most choice of cpu's.

**Comment by OBattler** [comment]
A Pentium Dual-Core will always be slower than an i5. A Pentium 4 is going to be even slower.

The amount of ram matters less (but get at least 4 GB) and of course, DDR 3 RAM is faster (and DDR 4 RAM is the fastest).

**Comment by MoochMcGee** [comment]
TBH, all these questions sound like someone who doesn't know much about computers, and I gotta say, 86Box is not for the faint of heart. To use it, you should probably be pretty decent with computers.

**Comment by MoochMcGee** [comment]
But yes, you're going to want the newest processor you can find. Also, 86Box is not a single-core application. It can spin up to 10 threads at a time, so you're going to want a processor that has the most threads possible, for maximum performance.

**Comment by dfgdgdgfd** [comment]
> TBH, all these questions sound like someone who doesn't know much about computers, and I gotta say, 86Box is not for the faint of heart. To use it, you should probably be pretty decent with computers.

I'm reasonably knowledgeable but started to think that only raw cpu speed and not cores was relevant due to this statement about pcem:

"It isn't possible to spread out emulation of a single processor over multiple cores. Flat out impossible. So no, that won't happen in V12."

**Comment by OBattler** [comment]
Raw CPU speed is not just clock speed, though. Instructions per clock (IPC) is just as important, and you'll find that a first or second generation i5/i7 has a higher IPC than a Pentium Dual-Core (which in turn has a higher IPC than a Pentium 4), and a later i5/i7 has an even higher IPC than that.
And since the emulator does use a fair number of core, a fairly recent i5 (or even better, i7), or Ryzen r5/r7, would be the best solution.

**Comment by dfgdgdgfd** [comment]
Would it be possible to change cpu speed without restarting, like in PCem?

**Comment by OBattler** [comment]
I have no idea what effect that would have on the software running inside the emulator (and an absence of visible problems does not equal a complete absence of problems) and in any case, you can't do that on real hardware, so I can't see the point of allowing that in an emulator.

**Comment by dfgdgdgfd** [comment]
Can I get a definitive answer on whether hyperthreading should be enabled?  Someone said to disable it but they may have meant PCem.

**Comment by OBattler** [comment]
Hyperthreading could help if you're using something like network or Voodoo which use their own threads. So yes, I'd definitely enable it.

With that said, I'm closing this issue since it's been inactive since february. I can reopen it on request. :p
