### ISSUE TITLE
Matrox Millenium glitches in NASCAR Racing

### ISSUE THREAD

**Issue by Dizzy611** [86Box/86Box#2528]
The Matrox Millenium runs the only known released game for its 3D api, NASCAR Racing, perfectly fine... except that the framebuffer bounces around the screen making it nauseating and unplayable. 

But the actual 3D seems to be rendering ok! So, progress.

I shared a video on discord, https://cdn.discordapp.com/attachments/266245173036449794/1002434143856107651/2022-07-29_00-31-32.mkv

OS: Windows 10 x64
Build: 86Box Dev 3982, Win32 UI

**Comment by Cacodemon345** [comment]
This should be fixed by now.

**Comment by OBattler** [comment]
Therefore, this can now be closed.
