### ISSUE TITLE
Checkboxes "Сassette", "Tertiary IDE Controller", "Quaternary IDE Controller" are not saved

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2535]
**Describe the bug**
Starting with build 3388, the "Cassette" checkbox is not saved in 8088 machines. After applying the settings in 8088 machines, if you check the "Cassette" checkbox, then the next time you open the settings window, this checkbox is no longer there.

Starting from build 3501, "Tertiary IDE Controller", "Quaternary IDE Controller" checkboxes are not saved in Slot1 machines. After applying the settings in Slot1 machines (and maybe in some others), if you check the "Tertiary IDE Controller", "Quaternary IDE Controller" checkboxes, then the next time you open the settings window, these checkboxes are gone.

**To Reproduce**
1. Set the checkboxes "Сassette", "Tertiary IDE Controller", "Quaternary IDE Controller" in the corresponding 86Box machines
2. Apply settings
3. Open the settings window again

**Expected behavior**
The checkboxes "Сassette", "Tertiary IDE Controller", "Quaternary IDE Controller" must be saved after applying the settings in the corresponding 86Box machines.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.6 x64 Build 3994
 - Build type: regular, old recompiler.

**Comment by Cacodemon345** [comment]
I am unable to reproduce the Cassette bug.

**Comment by maximus105** [comment]
In build 3387 in machine 8088, the checkbox "Cassette" is saved normally after applying the settings (when the checkbox is unchecked, the line cassette_enabled = 0 appears in the 86Box.cfg file, when the checkbox is checked, this line disappears). In build 3388 in machine 8088, the checkbox "Cassette" is not saved after applying the settings (in the 86Box.cfg file, the line cassette_enabled = 0 does not appear at all when checking / unchecking the checkbox).
