### ISSUE TITLE
Gravis Ultrasound and SBOS/MEGAEM Sound Blaster emulator.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#254]
Hello.

I know this is not top priority, and in fact it's emulation inside emulation.
I have a question about the Gravis Ultrasound card and it's Sound Blaster emulator, SBOS and Megaem.

I use the GUS floppy drivers ver 4.11 and i have two issues

1. The executable SBOS driver crashes the emulation (at DOS prompt)  if EMM386 is loaded (I read SBOS 3.82 will try to load itself in UMB memory if avaiable)
2. The Setup utlity will crash too in the SB and Roland screen check, if EMM386 is loaded.
3. The LOADSBOS.SYS  (is ver 3.81) when added in CONFIG.SYS  says "GUS not detected".
4. There is an standalone MEGAEM ver 3 which merges Ultramid, SBOS and old MEGAEM, this crach the emulation too. (the ver 2.07 included in the disk works) 
5. Some games may work and other will crash.

6. Megaem works (Is very close to real MT-32 in The Incredible Machine 2) but with some games sound exactly like playing MT-32 games directly with Graneral MIDI or MUNT without the proper ROM files.

7. Some games like The Incredible Machine 1 will crash either with SBOS or Megaem.
I don't know if it can be fixed. I'm just curious about this issue.

Thanks in advance!

**Comment by OBattler** [comment]
1. EMM386 is buggy and some things do not like running under it (XPACK is another such case - it will hang when run under EMM386 but works fine under eg. JEMM), however I'd need you to upload the GUS floppy drivers somewhere so I can test them to see if it's an EMM386 bug or something else;
2. Same as for 1.;
3. That sounds like a GUS emulation bug, from what I know, the emulated GUS still has some rough edges;
4. Same as for 1., I'd need you to upload it somewhere so I can see where the emulator crashes;
5. Which games crash to be specific?
6. Sounds like another GUS emulation bug;
7. Could be another GUS emulation bug or a bug with something else, it should be checked if they also crash on real hardware or not.

**Comment by Fenix770** [comment]
The game that lock up is Prince of Persia v1.3.

This game support a lot of sound cards including MT-32, PS/1 an even Disney Sound Source.
I  use this for testing purporses 
PD: Any of the games tested has native GUS support, the native GUS games work flawlessly.

1. i boot MS-DOS 6.22 with AMI Win bios 486, (without EMM386).
2. I load SBOS and I select Sound Blaster for music and sound.
3. I set the emulated  port as Blaster=240 in autoexec.bat  same as the GUS because otherwise the sound is  wrong
4. I start Prince of Persia the game run ok, and the sound are exactly the same as Sound Blaster, but when I open the door to level two, the game crashes with the open door and the "opening sound" reproduces forever like a "loop".

The other game is The Incredible Machine I, it will crash with a black screen immediately after running the exe file at the DOS prompt, with either SBOS or MegaEM.
( I will upload it later if you need it)
TIM 2 with, work with MegaEM without any issue, and the music quality is near, but no the same, as MT-32. (very few Sierra games support GUS natively and standalone GUs drivers were developed for 32 bits protected mode games only)

Here  I have a text file of an user who tested the games and recomended SBOS, MegaEM or Ultramid for earch game.
[https://drive.google.com/file/d/1tFL0pdVcCUCQtZSN8s47wMi2LFIja8G0/view?usp=sharing](url).

It's strange to me, that he advised the use of MegaEM for Prince of Persia 1.3 but I always have the wrong sound effects with it.

Here are the GUS drivers ver 4.11 they work in DOS and Win 3.1 : [https://drive.google.com/file/d/1xQ46IGkSdzrZDV85GYLStCezEtC-m619/view?usp=sharing](url).

Here it's the site with all PoP versions. The 1.3 has support for SB and MT-32.
[http://popuw.com/download.html](url) Includes the cracked and unckracke version.
Also the uncracked version can be cracked with NeverLock Bussines.

**Comment by Fenix770** [comment]
Update:
I recently discovred that SBOS "works" only with a specfic BLASTER and ULTRASND variable. However it will crash with EMM386 enabled, PoP still has the same problems.
Here I attach my autoexec.bat
With the default configuration, the sound efects in the emulated gamesare wrong. But with this in PoP i can arrive up to the first door (later it crash) but, belive or not, the sound are the same that the "real" Sound Blaster.   

@REM ===== Gravis initialization (4.00) =====
@SET ULTRASND=240,3,3,5,7
@SET ULTRADIR=C:\ULTRASND
@SET BLASTER=A240 I7 D1 T1
@C:\ULTRASND\ULTRINIT.EXE -dj
@REM ===== Gravis initialization ends =====
@REM ===== PPLT INITIALIZATION ==========
@SET PROPATS=C:\PPATS
@REM ===== PPLT INITIALIZATION ENDS =====
