### ISSUE TITLE
[Feature] AMD CPUs

### ISSUE THREAD

**Issue by Rowan-Bird** [86Box/86Box#2547]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem

**Describe the solution you'd like**
Add support for emulating AMD CPUs using AMD specific sockets (e.g. Socket 462/AMD Athlon)

**Additional context**
Currently, the only AMD CPUs available are the AmX86 CPUs, and all sockets are intel-designed

**Comment by OBattler** [comment]
This is not going to happen, because the Athlons have even higher IPC than Intel i686, therefore, they aren't going to run at 100% on any current PC, and are therefore, out of scope.

**Comment by jadasse** [comment]
> This is not going to happen, because the Athlons have even higher IPC than Intel i686, therefore, they aren't going to run at 100% on any current PC, and are therefore, out of scope.

Like the Pentium III.
