### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Rowan-Bird** [86Box/86Box#2548]
**Is your feature request related to a problem? Please describe.**
I find it hard to run Linux for disk partitioning

**Describe the solution you'd like**
This is probably stupid, but it would be cool/handy to have a SATA/AGP/PCIe based PC (2002-2004 era PC)
It would probably run like shit though

**Additional context**

**Comment by headsetguy37** [comment]
I'm sure this is not possible at this point; I wouldn't expect any hardware newer than the year 2000 for many years (and even 2000 is pushing it currently; the ICH2 chipset is in its own feature branch).

**Comment by Cacodemon345** [comment]
Hard cutoff date is 2001 like PCem.

**Comment by OBattler** [comment]
That stuff is out of scope, so I'm closing this issue.

**Comment by Rowan-Bird** [comment]
I'm aware of the fact that AGP hardware is somewhat supported (under "Video", at the bottom), but an late Pentium 2 - early Pentium 3 era system is what I was thinking of, like a 500MHz Pentium 3 with 256 MB of RAM or so, and that's about where it ends
