### ISSUE TITLE
Graphic\corruption issue on a game that in pcem shows fine while on 86box doesn't

### ISSUE THREAD

**Issue by Solstar** [86Box/86Box#255]
It happened again. game is Sensible Soccer 98, a 3d game which doesn't have any 3d settings, nor any glide\3dfx support. On pcem it run and shows fine, while on 86box there are some strange corruption issues

game on pcem

https://imgur.com/a/oCffk

game on 86box

https://imgur.com/a/h4PqZ

**Comment by OBattler** [comment]
The latest commit fixes this.
