### ISSUE TITLE
Won't start after last update.

### ISSUE THREAD

**Issue by Cereal-Killa** [86Box/86Box#2550]
After the last update, 3,7, x86box would not start, had to kill it from the task manager, tried many times.

**To Reproduce**
1. Update from version pre 3.7.
2. Try to start it.

**Expected behavior**
Window should appear.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: 3.7

**Additional context**
I found the culprit, deleting the config file fixed it, so restored my 86box.cfg and did some experiments, the offending line was:

`window_remember = 1`

Whatever happened there made 3.7 broken when that line was set, in my case, I just removed it and it's working fine now.

Fixed config:
`[Machine]
machine = 686bx
cpu_use_dynarec = 1
time_sync = local
cpu_enable_fpu = 1
cpu_family = celeron_mendocino
cpu_speed = 166666666
cpu_multi = 2.5
fpu_type = internal
cpu_manufacturer = 1
cpu = 3
mem_size = 65536

[Video]
gfxcard = voodoo3_3k_agp
voodoo = 1

[Input devices]
mouse_type = ps2

[General]
vid_resize = 1
video_fullscreen_scale = 3
vid_renderer = qt_opengl3
rctrl_is_lalt = 1
video_fullscreen_first = 0
language = system
iconset = legacy
confirm_exit = 0

[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dacfilter = 0
render_threads = 4
sli = 0
recompiler = 1
dithersub = 1

[Sound]
sndcard = sb16_pnp
fm_driver = nuked

[Storage controllers]
hdc = ide_pci_2ch

[3dfx Voodoo3 3000]
bilinear = 1
dacfilter = 0
render_threads = 4
recompiler = 1

[Sound Blaster AWE32 PnP]
onboard_ram = 28672
receive_input = 1
receive_input401 = 0

[Realtek RTL8029AS]
mac = 7c:b8:98
bios = 0

[Network]
net_type = slirp
net_card = ne2kpci

[Ports (COM & LPT)]
serial1_enabled = 0
serial2_enabled = 0
lpt1_enabled = 0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_image_path = D:\ISO\Windows98\windows98se.iso

[Standard PS/2 Mouse]
buttons = 4

[Other removable devices]
mo_01_parameters = 0, atapi
mo_01_ide_channel = 1:0

[Sound Blaster 16 PnP]
receive_input = 1
receive_input401 = 0

[Hard disks]
hdd_01_parameters = 63, 16, 1054, 0, ide
hdd_01_fn = systems/Windows 98/hdd.img
hdd_01_speed = 1997_5400rpm
hdd_01_ide_channel = 0:0

[Monitor #1]
`

**Comment by OBattler** [comment]
This was the result of Cacodemon345 doing the migration code for the old window_coordinates variable wrong. This is now fixed.
