### ISSUE TITLE
Ability to enable SLI on Voodoo and Obsidian SB50 + Amethyst (2 TMUs)

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2555]
**Describe the bug**
On a real PC, Voodoo and Obsidian SB50 + Amethyst (2 TMUs) do not support SLI, so it makes sense to remove the ability to enable SLI in 86Box on these video cards.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.7 x64 Build 4011
 - Build type: regular, old recompiler.

**Comment by OBattler** [comment]
[Then why the fuck don't you move your fat ass for once and actually contribute the change you want?](https://www.vogons.org/viewtopic.php?t=73217&start=20)

```
Obsidian 100DB is a very peculiar graphics card sold by Quantum3D. It is connected by two Obsidian pro SB50-2440 SLI and is called Obsidian 100DB-4440. In fact, it should be called Obsidian 100DB-2440. It may be displayed as Obsidian after loading the driver. This is the case with 100DB-4440.
```

As such, I'm closing this request.

**Comment by jriwanek** [comment]
Cite: http://www.thedodgegarage.com/3dfx/q3d_obsidian.htm
It's specifically called the Obsidian 100DB-2440 when two SB50's are SLI.

**Comment by OBattler** [comment]
I apologize for my little outburst above that got accidentally posted. I wrote it in a moment of irritation and then intended to replace it with the link, but GitHub instead simply added it to the link.

**Comment by maximus105** [comment]
Regular Voodoo1 does not support SLI. Why is it possible to enable SLI in 86Box for it? When SLI is enabled in the 86Box on a regular Voodoo1, you cannot set the resolution to 1024x768 in Quake1 and Quake2. Is this a bug?

**Comment by jriwanek** [comment]
Actually it *does*: https://www.voodooalert.de/board/forum/index.php?thread/24336-stoned-shaman-20mb-voodoo-graphics-sli-review/
