### ISSUE TITLE
86box build for weak machines

### ISSUE THREAD

**Issue by Farooq87** [86Box/86Box#2559]
Please make 86box version which would be not demanding for processor power, could allocate cycles directly from the host. Something like Virtual machines (Virtualbox and VMware), but with feature to attach emulated video/audio cards.

**Comment by AstralStorm** [comment]
I think you want DosBox for that.

86Box is meant to be close to timing accurate and accurate.
If you don't have a strong enough machine to run a particular CPU or cards, pick something slower instead.

**Comment by dhrdlicka** [comment]
This is pretty much incompatible with our project goals as well as not really viable due to the large effort required to accomplish this.
