### ISSUE TITLE
Debug Status register DR6 not properly emulated

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [86Box/86Box#2561]
**Describe the bug**
Reading this register may return 00000000 in 86Box. According to docs, bits 4-11 and bits 16-31 should be "read as 1"
More important, however, is that bit 14 (BS, breakpoint single-step ) is not set when the trace flag (TF) causes an exception 01.
It makes debugging in protected-mode impossible if the HX DOS DPMI host ( HDPMI ) is used, because this software checks bits 0-3 and 12-15 - if all are zero, it assumes no exception 01 is to be generated and "runs an int 01" instead ( there is a subtle difference in DPMI between exceptions and interrupts ).

**To Reproduce**
Ok, a true "debugger testcase" seems a bit too complex. I wrote a little test app (DOS). It should display "exc 01 occured" ( does so in Qemu ), but in 86Box it displays "int 01 occured".

**Expected behavior**
Proper setting of all DR6 bits.

[TF.EXE.zip](https://github.com/86Box/86Box/files/9245115/TF.EXE.zip)

**Comment by Cacodemon345** [comment]
Debug x86 registers aren't emulated in 86Box for performance reasons.

**Comment by Baron-von-Riedesel** [comment]
> Debug x86 registers aren't emulated in 86Box for performance reasons.

Ok, I can circumvent that bug in the application.

But I have to ask: are all flaws concerning "debugging" of minor interest?
Because there's another bug I found: a RETF that causes both a debug exception and an "segment not present" exception is somehow "skipped" ( although both exceptions are generated ). I really want to spare me the time to tinker a test case or even a test app if such errors are to be tolerated "by design".

**Comment by OBattler** [comment]
Debug registers are eventually planned to be emulated at least for 386. We in fact have an earlier open issue for ths here: https://github.com/86Box/86Box/issues/509 .

@Cacodemon345 - Yes, they are currently not emulated, but at least for 386, they are eventually planned as the 386 is slow enough that any loss of performance due to debug registers wouldn't really be noticable.

**Comment by Baron-von-Riedesel** [comment]
> Debug registers are eventually planned to be emulated at least for 386.

I fully understand that supporting debug registers DR0-DR3 ( so-called "watchpoints" ) is rejected due to performance reasons.

However, debug register DR6, bits 13-15 are not related to those watchpoints. Particularly supporting bit 14 should be almost trivial to implement: it's set whenever an int 01h is to be generated because of TF=1 ( TF= trace flag in the flags register ).

**Comment by Cacodemon345** [comment]
That part now should be emulated properly.

**Comment by OBattler** [comment]
Yes, I just merged the pull request that implemented this.
