### ISSUE TITLE
OTI-67 issues after build  #4014

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2565]
**Describe the bug**
I'm using a 286 with the OTI-67 VGA.

Bugs on build 4015 and latter: 

1. The DOS cursor latency is too fast.
2. The game Arkanoid 2 freezes after selecting the music, and video mode options on the configuration.

The game and DOS cursor works just fine on build #4014

HDD:
[286 Goldstar HDD type 9.zip](https://github.com/86Box/86Box/files/9246112/286.Goldstar.HDD.type.9.zip)

Floppy image file of the game: 
[Arkanoid 2 Gblaster.zip](https://github.com/86Box/86Box/files/9246130/Arkanoid.2.Gblaster.zip)

NVR and CFG:
[286 Goldastar NVR.zip](https://github.com/86Box/86Box/files/9246113/286.Goldastar.NVR.zip)

**To Reproduce**
1. Start the VM
4. But the Arkanoid game disk on drive B
5. Type DOH /R to enter the graphics/music configuration.

**Desktop (please complete the following information):**
 - OS: Win 10 21H2
 - 86Box version: 4015, 
 - Build information: Win32 old dynarec

**Comment by OBattler** [comment]
This is now also fixed.
