### ISSUE TITLE
If exception occurs while trace flag is set, strange things may happen...

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [86Box/86Box#2577]
**Describe the bug**
This is rather technical and low level. Since the trace flag is involved, it's more or less a debugging issue, but the underlying flaw might cause funny effects in other contexts as well.

If the trace flag is set by a POPF instruction, and a RETF follows that causes an exception 0B ( not present ), the RETF is (partially) "skipped" ( CS and SP remain unchanged, IP is incremented ) - hence the code following the RETF is executed.

```
	push bx          ; contains selector of a descriptor with attr NP
	push offset cont1
	pushf
	mov bp, sp
	or word ptr [bp], 100h
	popf
	retf
;--- this code should NOT run!
	mov dx, offset text5	; display "invalid code location..."
	mov ah, 9
	int 21h
cont1:
```

**To Reproduce**

A rather artificial test case is attached. Currently the output is:
exc 0B occured
exc 01 occured
invalid code location reached
back in track

[retf.zip](https://github.com/86Box/86Box/files/9270318/retf.zip)

**Expected behavior**
If everythings works as expected, the test case should display:
exc 0B occured
exc 01 occured
back in track

**Additional context**
It's not a problem of the hdpmi host - the bug also happens if the test program is run in a Win3X DOS box.
Other emulations, btw, also have problems with that code: DosBox, DosBox-X.
It works correctly in Qemu and DosEmu.

**Comment by OBattler** [comment]
While that happens on the recompiler, on the interpreter it's even worse:
![imagem](https://user-images.githubusercontent.com/10365853/198434009-67eae468-b888-4a7a-abbe-87480986d49c.png)

**Comment by OBattler** [comment]
By my logic - the RETF should be skipped if it causes an exception, since that means it hasn't been able to fetch the return pointer. Unless the correct behavior is to return to the RETF instruction, ie. undo the RETF entirely.

**Comment by Baron-von-Riedesel** [comment]
> By my logic - the RETF should be skipped if it causes an exception,

No, the cause of the exception is cured by the exception 0Bh handler, of course. When the exception handler routine returns, the RETF is again executed and this time it runs without exception.
If the exception handler does NOT cure the cause of the exception and returns, the RETF will again cause exc 0Bh and the program is in an infinite loop.

**Comment by Cacodemon345** [comment]
It appears to be now fixed either way.

**Comment by Baron-von-Riedesel** [comment]
I can confirm that the bug is fixed.
