### ISSUE TITLE
Memory test on PS/2 type machines not finishing and failing with 162 and 163 codes (Machine has 4MB of RAM)

### ISSUE THREAD

**Issue by Rowan-Bird** [86Box/86Box#2584]
![Monitor_1_20220806-153711-759759](https://user-images.githubusercontent.com/43280679/183263946-555e5a72-0569-40f2-a77c-56943d7978a3.png)
![Monitor_1_20220806-153737-948948](https://user-images.githubusercontent.com/43280679/183263947-3c314ea9-b490-45d2-b7b1-f701a5d90270.png)
 This only occurs when using PS/2 machines, with a 386SX/DX/486SX/DX
 PS/1 machines are unaffected
 EDIT: I think it's only MCA machines

**Comment by Rowan-Bird** [comment]
![Monitor_1_20220806-155148-791791](https://user-images.githubusercontent.com/43280679/183264183-35b2c0b1-4870-4097-8745-f126d9aaacc2.png)
Another error screen

**Comment by TC1995** [comment]
You need the reference disk for these.

**Comment by OBattler** [comment]
Then I'm closing this with NOTABUG.
