### ISSUE TITLE
Unable to select more than one shader

### ISSUE THREAD

**Issue by PF94** [86Box/86Box#2590]
**Describe the bug**
Selecting a new shader replaces the currently used shader, which makes it impossible to use multiple-pass(?) shaders on 86box.

**To Reproduce**
1. Go to OpenGL 3.0 render options
2. Click on Browse
3. Select shader
4. Click on Browse again
5. Select another shader
6. The new shader replaces the old shader on the list. 

**Expected behavior**
The new shader should be added to a list of used shaders.

**Screenshots**
https://user-images.githubusercontent.com/45898787/183315841-972c6eb8-b6f6-42ef-a080-bb4f42b2b567.mp4

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - 86Box version: 3.7.1 build 4038
 - Build information: Old dynamic recompiler? 32-bits. Basically what Laci ba's WinBox downloads.

**Comment by Gogo268** [comment]
Using multiple shaders on the OpenGL 3.0 renderer is currently not supported.

**Comment by OBattler** [comment]
Closing this because shader development is being tracked in #1407.

**Comment by PF94** [comment]
That issue seems completely different than mine.

Mine was about not being able to select more than one shader.
Their issue seems to be related to "configuration options", and Intel HD 4400 compatibility.

Although, I might be wrong.
