### ISSUE TITLE
Prehistorik 2 freezes when using up key or hitting an enemy

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#2594]
**Describe the bug**
Game freezes and glitches when using up key or hitting an enemy
**To Reproduce**
Go in-game. Press the up key or run into an enemy

**Expected behavior**
For the character to jump instead of the game to freeze

**Screenshots**
![Monitor_1_20220808-235715-245245](https://user-images.githubusercontent.com/68984176/183584381-d2b460ab-97d5-4b05-aa65-1240677c3ad4.png)

**Desktop (please complete the following information):**
Windows 10 x64 3.7.1.4032

**Additional context**
Using 420TX with Soundblaster AWE32
[86box.zip](https://github.com/86Box/86Box/files/9287770/86box.zip) - Config file

**Comment by TC1995** [comment]
Could you send us the vhd (if possible) and nvr?

**Comment by ualaa1** [comment]
Nvr:
[nvr.zip](https://github.com/86Box/86Box/files/9296035/nvr.zip)

HD:  https://www.mediafire.com/file/efyrxlw3oapy52b/Doshd.img/file

The game is in directory prehis2 and the game exe is pre2

**Comment by TC1995** [comment]
I think you either have a bad copy of it. Because one over at https://cdromance.com/msdos/prehistorik-2-dos/ works fine, no crashes with jumping or being hit by an enemy.

**Comment by TC1995** [comment]
Try re-creating the hdd (IDE), install DOS 5 and the game too, without anything else besides sb16, it should work now.

**Comment by ualaa1** [comment]
I use the download from https://www.old-games.ru/game/download/get.php?fileid=12268&modal=1 so that might be the problem, but I'll try your suggestion as well

**Comment by OBattler** [comment]
Yes, whatever they patched for DOSBox, likely breaks it on 86Box.

**Comment by Gogo268** [comment]
> Yes, whatever they patched for DOSBox, likely breaks it on 86Box.

the binary on old-games.ru is the hybrid cracked release.

**Comment by ualaa1** [comment]
Game works normally now using a different release and reinstalled HD. No glitches from what I can see

**Comment by OBattler** [comment]
Then I guess this can be closed.
