### ISSUE TITLE
Blend patch for the Hercules monochrome card.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#260]
Hello.

I don't know if it's possible to add this patch to 86box, but it would be a nice addition.
I have an old patch designed for the Hercules monochrome graphics  to make  the graphics closer to the original  of the Monitor. Unfortunately the patch was made for dosbox in 2010, (it's not mine) and it was never  merged in the official dosbox build, it was in Dosbox Daum branch which is no longer under development.

Here is the pacth (designed for dosbox)
[hercules_blend.zip](https://github.com/86Box/86Box/files/1708849/hercules_blend.zip).

Goblins 1 in Hercules mode without the patch.
![image 001](https://user-images.githubusercontent.com/31600563/35999182-bbfc49d2-0cfd-11e8-999b-cf9217885b0d.png).

And here with the patch.
![image 002](https://user-images.githubusercontent.com/31600563/35999184-bc33119c-0cfd-11e8-82b8-df9f13ef3dec.png)

**Comment by OBattler** [comment]
Where can I get Goblins 1 for the Hercules? I've looked everywhere and all I can find is the EGA/VGA version. I need this because I just implemented the blending, and I'd like to test it.

**Comment by Fenix770** [comment]
I tested, Outrun and Tetris and Gooblins. The blend works flawlessly.
The hercules graphics looks much closer to real hardware.

Thanks!
