### ISSUE TITLE
Fullscreen stretch mode 4:3 not working after build 4045

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2606]
**Describe the bug**
Fullscreen stretch mode 4:3 not working after build 4045. The image in fullscreen mode is still stretched horizontally in fullscreen stretch mode 4:3 (regardless of enabling/disabling the option "Apply fullscreen stretch mode when maximized"). In build 4044 everything works fine. It is not clear why the "Apply fullscreen stretch mode when maximized" mode was added, because it completely duplicates the "Fullscreen stretch" mode, which previously worked fine.

**Screenshots**
Build 4044 in fullscreen mode 4:3
![86Box_2022_08_10_23_19_49_347](https://user-images.githubusercontent.com/58270614/184012725-c1711b9a-728a-4364-9772-340b858fe69e.png)

Build 4045 in fullscreen mode 4:3
![86Box_2022_08_10_23_20_15_707](https://user-images.githubusercontent.com/58270614/184012744-6ab27114-697a-4c99-89ee-3e7cfeeb7009.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.7.1 x64 Build 4048
 - Build type: regular, old recompiler.

**Comment by OBattler** [comment]
Which renderer are you using?

**Comment by maximus105** [comment]
I am using Qt (OpenGL) renderer. The bug is also present on other renderers: Qt (Software), OpenGL 3.0 Core, Vulkan, Direct3D 9.

**Comment by OBattler** [comment]
Fix committed, build #4050 is going to contain it.

**Comment by maximus105** [comment]
Check also Fullscreen stretch mode Integer scale also not working after build 4045.
