### ISSUE TITLE
[Feature] Support of a custom frequency for CPU when configuring Machine hardware 

### ISSUE THREAD

**Issue by ohault** [86Box/86Box#2612]
**Is your feature request related to a problem? Please describe.**
In the current implementation, CPU frequencies are predefined. To set a custom frequency, source code should be modified and recompiled. 

**Describe the solution you'd like**
The user should be able to select between a set of predefined CPU frequencies, but also to configure a custom CPU frequency as  an input on the Machine configuration screen.

**Comment by OBattler** [comment]
I don't think real CPU's could be set to an arbitrary speed, except for maybe changing the bus speed (that the CPU then multiplies to get the proper speed) to another of the supporter speeds, but I think we cover all the options for that, anyway.

**Comment by OBattler** [comment]
As such, I'm closing this with not doable.

**Comment by ohault** [comment]
@OBattler, it has been already be done. e.g. https://www.youtube.com/watch?v=xyfscz3v7Iw

**Comment by ohault** [comment]
Does it possible to move this Issue as a Discussion ?
