### ISSUE TITLE
[SiS 501] BCM SQ-588 does not detect third and fourth HDD

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2616]
**Describe the bug**
[SiS 501] BCM SQ-588 does not detect third and fourth HDD in BIOS. When you press ENTER in the BIOS settings, HDD auto-detection does not occur (as in the screenshot below).
![2022-08-13_133532](https://user-images.githubusercontent.com/58270614/184479954-171897b2-b455-44d8-bf59-44f274a07b6b.png)
![2022-08-13_133247](https://user-images.githubusercontent.com/58270614/184479879-eedbf40e-1fd9-41e7-b022-247e354b5376.png)

**To Reproduce**
1. Create machine [SiS 501] BCM SQ-588
2. C/H/S Parameters: 1054/16/63 (518MiB)
3. Connect a system HDD with DOS 6.22 and three more IDE HDDs to the built-in IDE controller
4. Start the machine, you will see that the third and fourth HDD are not defined (as in the screenshot below)
![2022-08-13_132257](https://user-images.githubusercontent.com/58270614/184479832-ec707031-4ec3-4f15-9949-68824c9400d3.png)

**Expected behavior**
All four HDDs should be detected normally in the BIOS.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.7.1 x64 Build 4055
 - Build type: regular, old recompiler.

**Comment by TC1995** [comment]
I think the secondary drives require the "Integrated IDE adapter" set to "Secondary" while keeping Local Bus IDE adapter set to enabled.

**Comment by maximus105** [comment]
Thanks! Now all four HDDs are detected normally in the BIOS.
