### ISSUE TITLE
[SiS 496] Crash with Sound Blaster 2.0

### ISSUE THREAD

**Issue by dominic-03** [86Box/86Box#2623]
**Describe the bug**
In 86Box 3.5, I had a machine with an SiS 496 motherboard and a Sound Blaster 2.0 that ran Windows XP. Upon launching the same machine in 86Box 3.7.1, the machine crashes on the POST screen. Switching from a Sound Blaster 2.0 to a Sound Blaster 16 PnP resolves this problem. The configuration file for the machine with the Sound Blaster 2.0 is available [here](https://pastebin.com/hnma4H2Q).

**To Reproduce**
1. Configure a machine with the attached configuration file
2. Power on the machine
3. Wait for crash

**Expected behavior**
The machine should continue to function normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/47524785/184780285-97ccf860-ec33-4ab3-9352-77a7fc1053bb.png)
This is what the display looks like just before the crash occurs.

**Desktop:**
 - OS: Windows 10 Pro 21H2 (x64)
 - 86Box version: 3.7.1, build 4032
 - Build information: N/A - downloaded from GitHub Releases section

**Additional context**
If it would be helpful, I can also attempt to run the machine in 86Box 3.6 and 86Box 3.7, to see if the bug was introduced in a later version.

**Comment by TC1995** [comment]
It's fixed already in the newer builds.

**Comment by Gogo268** [comment]
Fixed in #4056.
