### ISSUE TITLE
IBM/Microsoft XENIX 1.0 fails to boot on IBM PC AT

### ISSUE THREAD

**Issue by thunderbird32** [86Box/86Box#2627]
**Describe the bug**
I am attempting to install IBM XENIX 1.0 for the AT on an emulated PC AT. Instead of booting off the installation floppy, I get a constant tone from the PC speaker, and a blinking cursor on the  right side of the screen. It never goes any further. I have also tried the Microsoft branded release of this version of XENIX, and get the same results.

**To Reproduce**
1. Boot off of installation floppy
2. At ':' prompt type "fd /xenix.fd" (to boot off of floppy as described in the Installation Guide)
3. When the system says "Loaded, press Enter to start" press enter
4. Machine will play steady tone from PC speaker and display blinking cursor. Goes no further from this point.

**Expected behavior**
The computer should boot into XENIX. You should get a "Entering System Maintenance Mode" banner and then a '#' prompt.

**Screenshots**
![Monitor_1_20220817-150022-591591](https://user-images.githubusercontent.com/35811767/185234123-875535fb-5ded-4ed7-9652-984c672575b4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Education 21H1
 - 86Box version: 3.7.1 build 4032
 - Build information: Stable

**Additional Information**
IBM XENIX disk images and documentation can be found on Bitsavers

**Comment by thunderbird32** [comment]
Note: I can get further than this using the "NCR PC8/810/710/3390/3392" machine. On that system I can install what I guess is the boostrap/bootloader to the hard drive. You are then supposed to boot off the hard disk and install the base system. When booting off the hard disk it brings up the boot prompt correctly, but after entering "hd /xenix" the system sits for a second and then restarts.

**Comment by jaylogue** [comment]
I ran into the same problem.  I was able to resolve the it by switching the display type to MDA.

**Comment by thunderbird32** [comment]
This seems fixed now. I can boot to XENIX from the floppy disk.
