### ISSUE TITLE
S3D emulation for S3 Virge/DX (375) results in a black screen in Minecraft.

### ISSUE THREAD

**Issue by TheMajorTechie** [86Box/86Box#2628]
**Describe the bug**
Using Brian Paul's OpenGL to S3D wrapper on real hardware, I was able to get Minecraft Classic version 0.31 to load into a world, albeit with plenty of rendering errors. However, in 86Box with the exact same hardware configuration, I only get a black screen.

UPDATE: 86Box also crashes when exiting Minecraft by closing the black-screened window.

**To Reproduce**
1. Setup 86Box with an Asus P5A, an Intel Pentium at 90MHz, and 768MB of RAM. The video card is an S3 ViRGE/DX (375) on the PCI bus with 4MB of VRAM. Use a standard PS/2 mouse, no sound card, and no network.
2. Install Windows 98, the S3 Virge unified driver kernelEX (plus the unicows.dll file it'll ask for), the Windows Installer 2.0 framework, and Java 6, in that order.
3. Copy a .minecraft folder with a valid lastlogin file (I can't share mine since it contains emails and passwords) and the Minecraft Classic 0.31 minecraft.jar file into C:\windows\
4. Copy the Minecraft pre-1.6 launcher (use the .exe version!) to desktop (it will be operating in offline mode thanks to the existence of the lastlogin file, eliminating the need for a network connection)
5. Copy Brian Paul's S3D Mesa implementation to desktop alongside the launcher exe file
6. Start the game and select "play offline" when the launcher complains about not being able to reach minecraft.net
7. Witness a black screen instead of the glitchy pile of pixels that is the S3 Virge trying to render Minecraft through the OpenGL to S3D wrapper

**Expected behavior**
Rather than a black screen, the game should start up with a very glitched rendered output that vertically tiles two identical renders of the game display. An image of what it looks like on real hardware (with the EXACT same configuration as what was described for 86box) is attached below.

**Screenshots**
![20220816_163648](https://user-images.githubusercontent.com/29270676/185505649-bf8b3559-6371-4b4e-92ff-774bece998e7.jpg)
![20220816_185330](https://user-images.githubusercontent.com/29270676/185505673-437a8471-5dd0-494b-9e9c-ddc930c0c5a6.jpg)
![image](https://user-images.githubusercontent.com/29270676/185505721-8ca7266e-006e-46a9-9536-02e6fed2d8f4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Version 21H2, OS build 19044.1889
 - 86Box version: 86Box 3.7.1 [build 4032]
 - Build information: Version 3.7.1 Stable from https://github.com/86Box/86Box/releases/tag/v3.7.1

**Additional context**
I will be uploading a full video on Youtube showing detailed steps on running Minecraft on the actual hardware hopefully within the next few days. Included below are two "status update" type videos demonstrating the game running on real hardware, and what it should be expected to look like.
https://youtube.com/v/zu4DlGwlKFg
https://www.youtube.com/watch?v=XAAUznMu7PE

The full video including all the steps starting from Windows 98 installation:
https://www.youtube.com/watch?v=9ghnfSWKOgY

**Comment by OBattler** [comment]
I don't think this is fixable, and it affects other things as well - eg. Tomb Raider II white screens. I know that adding a few pclog()'s into the 3D accelerator code fixed that so I assume the 3D accelerator thread is getting out of sync with the CPU thread. Since the only way to fix it is to unthread it, which would destroy performance, I'm closing this with CANTFIX.
