### ISSUE TITLE
Serial Mouse not working in RedHat 5.2

### ISSUE THREAD

**Issue by thunderbird32** [86Box/86Box#2634]
**Describe the bug**
When in RedHat 5.2 the mouse does not work. The mouse cursor "sticks" to the left-hand side of the screen. If I move the mouse it only moves on the vertical axis, but doesn't move away from the left-hand side. If I really fling the mouse to the right it will move out off the side of the screen briefly, but with the next movement I make it goes back to the left-hand side. The emulated hardware is "Microsoft Serial Mouse" and the driver selected in Linux is "Microsoft compatible (serial)" (see screenshot).

This has been an issue for a while. While I haven't tried using a Logitech serial mouse recently, I believe that was exhibiting the same behavior.

**To Reproduce**
1. Install RedHat 5.2
2. Select "Microsoft compatible (serial)" as mouse in installer
3. Boot into GUI and try to move mouse

**Expected behavior**
The mouse should move as expected.

**Screenshots**
![Monitor_1_20220822-112207-521521](https://user-images.githubusercontent.com/35811767/185976193-4495b05d-83b9-4f6c-ae8d-dd56fe8ada17.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Education 21H1
 - 86Box version: 3.7.1 build 4032
 - Build information: stable

**Comment by thunderbird32** [comment]
As discussed on the Discord server, I have tested PS/2 mouse support. This also doesn't work, but for a different reason. When a PS/2 mouse is configured, the "mouseconfig" tool locks up when it returns the results of scanning for the mouse. It locks up here:
![Monitor_1_20220822-161852-863863](https://user-images.githubusercontent.com/35811767/186020998-5d14fc72-37c3-41b5-8184-b6006665003e.png)

When I say "locks up" I mean that you can't select the "Ok" button. The cursor continues to blink, so it's not fully locked up, but you can't get any further.

**Comment by thunderbird32** [comment]
VM and config uploaded to the FTP (RedHat Linux 5.2.7z). This VM demonstrates the serial mouse issues. Root password is "toor".

Steps to reproduce:
1. Login as root
2. Run "startx"

Mouse issues will be immediately apparent.

**Comment by ThatsItForTheOtherOne** [comment]
I am not sure if this should be in a different bug, but it's closely related so I'm putting it here.
The same issue happens on my ARM macbook _with busmouse too_, I tested with thunderbird's VM so I know it wasn't just my install. 
I'm not sure if this is an extension of this issue or a new issue altogether.

**Comment by cold-brewed** [comment]
Some serial fixes were added today. Anyone who was affected by this serial mouse issue should grab the latest CI build from jenkins and re-test.

I have an old linux 2.0 kernel system that was affected by the serial mouse bug. I tested with the fixes today and can confirm it did fix my issue.

**Comment by win2kgamer** [comment]
Just tested RedHat 5.2 with a serial mouse on build 4449 and I can confirm the mouse works correctly now.

**Comment by OBattler** [comment]
Then I'm closing this.

**Comment by ThatsItForTheOtherOne** [comment]
Very late to this one but I can confirm that mouse is also fixed on ARM Macbooks. Thanks for the hard work!
