### ISSUE TITLE
Add installer

### ISSUE THREAD

**Issue by 0xC4aE1e5** [86Box/86Box#2637]
**Is your feature request related to a problem? Please describe.**

I'm annoyed because every time I reset or get a new PC, 86box is a pain in the butt to get. I have to download 86box, manager, and the roms, place them in the right location, and change manager's default location

**Describe the solution you'd like**

A simple installer (made with Inno Setup or something).

**Describe alternatives you've considered**

- Maybe a portable ZIP that contains what I listed above?

**Additional context**

I did all the leg work for you, it's just over here: https://github.com/0xC4aE1e5/86boxInstallers

(You will think I am a new account as a spammer, but I needed a new account anyway and that account was FULL of repos. I primarily host code on Codeberg.)

**Comment by Diicorp95** [comment]
> A simple installer (made with Inno Setup or something).

Maybe just an (SFX) archive? An uninstaller formed by Inno Setup installer can remove the user configuration, NVRs and storage images, unless otherwise specified in the source `.iss` file. In addition, it's also a set of registry entries. More importantly, it's not available for Linux and Mac.

**Comment by 0xC4aE1e5** [comment]
That could work, but you can't uninstall (without deleting files weirdly)

**Comment by Diicorp95** [comment]
> That could work, but you can't uninstall (without deleting files weirdly)

a. You can simply use a file structure where user data will be stored in its root and program files in a subfolder.
b. You can include the program files remover written in Bash (Linux, Mac) and one in Batch (Windows).

Additionally, you need to set configuration of 86Manager for it to work.

**Comment by OBattler** [comment]
We can not bundle the ROM's together with 86Box - I'm quite that would violate the GPL.

And there are three managers in existence, so we'd have to include all three.

**Comment by JimboMumbo** [comment]
Three managers. sounds good idea.

**Comment by ts-korhonen** [comment]
With installer in this kind of form you are bundling GPL licensed software with binaries. You would need to include only GPL-compliantly licensed binaries, or else publishing such installer would be directly against GPL. Keep the separated.

**Comment by 0xC4aE1e5** [comment]
This is just getting into legal problems. Closing.
