### ISSUE TITLE
Processor clock speed is modifed after soft reboot

### ISSUE THREAD

**Issue by silverlays** [86Box/86Box#2642]
**Links**
- [86box.cfg](https://pastebin.com/m3ddFNaj)
- [C.img](https://mega.nz/file/GpIR0AIZ#7xkyrrd7J0nTvawEKSXDqtZCWuJcZQY8YXOn6sTrWPQ)

**Describe the bug**
The base clock is 66Mhz, but when i do a soft reboot, the clock change from 66Mhz to 32Mhz.

**To Reproduce**
1. Launch VM and wait prompt
2. press CTRL+F12 (or soft reset in the menu)
3. See the clock speed on the POST-BIOS screen.

**Screenshots**
![screenshot of the problem](https://i.imgur.com/zADZjy8.png)

**Desktop**
 - OS: Windows 10
 - 86Box version: v3.7.1.4065
 - Build information: new dynarec, Windows x86

**Comment by TC1995** [comment]
known problem.

**Comment by OBattler** [comment]
A problem I can't fix other than by reverting to the more accurate PIT implementation which is, however, slower. So I'm unfortunately closing this with CANTFIX.

**Comment by silverlays** [comment]
@OBattler One last little question: Is the clock speed divided by 2 for real or it's just a number display bug ?
