### ISSUE TITLE
nvr.c include does not match

### ISSUE THREAD

**Issue by CartridgeGen** [86Box/86Box#265]
While compiling on linux I ran into this error either typo or mistake.
In nvr.c at the very top include 86Box.h should be 86box.h to reflect sources filename.
It's a mere 2 seconds to fix it myself but I just wanted to point it out. Case sensitive

**Comment by MoochMcGee** [comment]
86Box doesn't work on Linux anyway, so...

**Comment by OBattler** [comment]
I fixed that now.

**Comment by MoochMcGee** [comment]
Can we close this PR if it's fixed?
