### ISSUE TITLE
Mouse not moving on SteamOS 3.3.1 / SteamDeck

### ISSUE THREAD

**Issue by iokaravas** [86Box/86Box#2666]
**The bug**
Mouse will not move on the screen (when captured). I can left and right click fine. 

**To Reproduce**
1. Create a Socket 7 (Single Voltage), i430FX Intel Pentium 75 machine
2. Select any mouse type in inputs (PS2 for sure)
3. Boot to FreeDOS, test with mousetst.com, no location is registered only clicks
4. Boot to Windows 98, mouse will not move, right and left click work as expected

**OS/System**
86Box Version: v3.7.1
Operating System: SteamOS 3.3.1
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 (64-bit)
Graphics Platform: X11

**Additional context**
I am using a USB mouse for testing, not the touch controls of the SteamDeck.

**Comment by EnderIce2** [comment]
Same issue here, but on Ubuntu 22.04. Looks like it's an issue with Linux version of the 86Box.

**Comment by alpacalife** [comment]
I actually seem to have this same issue on a slightly different setup:

OS/System
86Box Version: v3.7.1
Operating System: Arch Linux - Kernel linux 6.0.6
WM: Sway
Qt Version: 5.15.7
Kernel Version: 6.0.6-arch1-1
Graphics Platform: wayland

Emulating Windows 95. Mouse clicks are registering as expected, but I get no movement. 86Box registers that I am clicked in the window.

While I was writing this, I quickly wanted to test out builds from git. The AUR has 86box-git (https://aur.archlinux.org/packages/86box-git) and now I get mouse movements as expected.

So this might be resolved by something else from 3.7.1 and 3.7.1.r590.gfbc08ef96-1 (at the time I did the build).

**Comment by OBattler** [comment]
Then I'm going to consider this fixed.

**Comment by mikedebian** [comment]
Same issue here with 86box-git  v3.7.r34.g9b29ab4-1 from the AUR, running Plasma Wayland session

**Comment by iokaravas** [comment]
Can confirm I'm running the flathub 3.7.1 version which seems to still exhibit the same issues.

**Comment by mikedebian** [comment]
Qt: version 6.4.1, platform "wayland"

Seems it was always running in wayland mode, unless I'm missing something @Cacodemon345

**Comment by mikedebian** [comment]
I see, so it is up to the package maintainer?

**Comment by Cacodemon345** [comment]
> I see, so it is up to the package maintainer?

Yes.

**Comment by mikedebian** [comment]
The package maintainer in the Aur updated the package as of now by adding a dependency. If your package manager does not show it for update, please just rebuild the package. All is well in arch now.
