### ISSUE TITLE
MS-DOS games run in W98 crash 86Box in Dev build

### ISSUE THREAD

**Issue by IDeletedSystem64** [86Box/86Box#2669]
**Describe the bug**
When running QUAKE.EXE, 86Box crashes with "Segmentation Fault"

**To Reproduce**
1. Run "QUAKE.EXE"

**Expected behavior**
Quake opens and starts up

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - 86Box version: v3.8, Unsure as to what build 
 - Build information: Old Dynarec, x64, Built from source ( as of commit https://github.com/86Box/86Box/commit/7935baf89a5f2cb46b248d8b8e174e87aab24ff8)

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by TC1995** [comment]
Does it happen in the x86 build with old dynarec as well?

**Comment by IDeletedSystem64** [comment]
Wasn't aware there was an x86 build, I figured it was x86_64. What's the option to compile for x86? (unless that's the default)

After poking around further, it seems to be MS-DOS games when ran from the executable in 98, works fine when run in MS-DOS Prompt and MS-DOS mode but not when run directly under 98

**Comment by TC1995** [comment]
I believe to compile the x86 (32-bit) one, you need to have a 32-bit environment (even if the host is 64-bit).

**Comment by IDeletedSystem64** [comment]
@Drakknar Sorry for the late response. It crashes intermittently

**Comment by AITUS95** [comment]
@IDeletedSystem64 can you try with this build?  https://ci.86box.net/job/86Box/2633/

**Comment by OBattler** [comment]
Closing because this now appears to be fixed.
