### ISSUE TITLE
VMware Workstation Ubuntu Vulkan problem

### ISSUE THREAD

**Issue by Slo2018** [86Box/86Box#2676]
I'm running Ubuntu (Guest) in VMware Workstation and 86Box not working because Vulkan missing. The same problem in Oracle VM VirtualBox.

**Comment by OBattler** [comment]
Why not just run 86Box directly on the host?

**Comment by planetbrian** [comment]
This isn't 86Box's fault, nor Ubuntu's fault. VMware Workstation only provides OpenGL 3.3 and DirectX11 support for guests, and VirtualBox only has OpenGL 3.1 support (VBoxSVGA). If you really had to run 86Box in a guest, just stick with software rendering.
