### ISSUE TITLE
PS/2 mouse and Microsoft Serial Mouse don't work on some machines

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2680]
**Describe the bug**
1. When installing PS/2 mouse in machine configuration [i430FX] ASUS P/I-P54TP4XE (MR BIOS), mouse does not work (CuteMouse driver does not see PS/2 mouse). In this case, the Serial Mouse works fine.
2. When installing Microsoft Serial Mouse or PS/2 mouse in machine configuration [i430FX] Intel Advanced/ATX (MR BIOS), mouse does not work (CuteMouse driver does not see Microsoft Serial Mouse or PS/2 mouse).
3. When installing PS/2 mouse in machine configuration [i430FX] QDI FMB, mouse does not work (CuteMouse driver does not see PS/2 mouse). In this case, the Serial Mouse works fine.

**Expected behavior**
PS/2 mouse and Microsoft Serial Mouse should work fine.

**Screenshots**
![2022-09-17_154133](https://user-images.githubusercontent.com/58270614/190858033-da55d497-a0c5-4165-a656-5049c10e197e.png)

**Desktop (please complete the following information):**

OS: Windows 10 Pro x64 v21H2
86Box v3.8.0 x64 Build 4090
Build type: regular, old recompiler.

**Comment by OBattler** [comment]
The QDI should not have a PS/2 mouse at all.

**Comment by OBattler** [comment]
For the P54TP4XE - the board only came with a PS/2 mouse header. The Award BIOS tests for a PS/2 mouse and enables it if it finds one, but I suspect the MR BIOS does not - it was likely written with the assumption of no PS/2 mouse. There's nothing I can do about that.

**Comment by OBattler** [comment]
For the Intel Advanced/ATX - it again seems the MR BIOS disables the PS/2 mouse (or probably never even enables it), and has broken serial port support. There's nothing I can do about that.

Since I've fixed the only part that can be fixed, I'm closing this.
