### ISSUE TITLE
On some machines won't boot DOS 6.22 with four IDE HDDs

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2681]
**Describe the bug**
[i430FX] QDI FMB does not boot DOS 6.22 with three or four IDE HDDs. With one, two IDE HDDs, DOS 6.22 boots fine.

**To Reproduce**
1. Create machine [i430FX] QDI FMB
2. C/H/S Parameters: 4161/16/63 (2047MiB)
3. Connect a system HDD with DOS 6.22 and three more IDE HDDs to the built-in IDE controller
4. Set the BIOS parameters HDD Type: Auto Detect Hard Disk Parameters (as in the screenshot below)
![2022-09-17_180811](https://user-images.githubusercontent.com/58270614/190863738-d8cb5adc-799f-49fa-8322-79fdc7c77a0c.png)
6. Start the machine, about 96 seconds after the HDD is detected, you will see the message "Sec Master HDD Error, Sec Slave HDD Error" (as in the screenshot below)
![2022-09-17_181003](https://user-images.githubusercontent.com/58270614/190863780-e4e8e96c-f916-4bcd-a003-7900c9a1e398.png)

**Expected behavior**
DOS 6.22 should boot normally with four IDE HDDs

[i430VX] ECS P5VX-B does not boot DOS 6.22 with four IDE HDDs. With one, two or three IDE HDDs, DOS 6.22 boots fine.

**To Reproduce**
1. Create machine [i430VX] ECS P5VX-B
2. C/H/S Parameters: 4161/16/63 (2047MiB)
3. Connect a system HDD with DOS 6.22 and three more IDE HDDs to the built-in IDE controller
4. Set the BIOS parameters HDD Type: AUTO, Mode: AUTO (as in the screenshot below)
![2022-09-17_170408](https://user-images.githubusercontent.com/58270614/190861544-ac63a67b-153f-4ba7-9411-74de6260bc67.png)
6. Start the machine, about 30 seconds after the HDD is detected, you will see the message "Hard disk(s) fail (80)" (as in the screenshot below)
![2022-09-17_170555](https://user-images.githubusercontent.com/58270614/190861559-4b6ee754-c0e9-470e-8759-583bd8bf20f6.png)

**Expected behavior**
DOS 6.22 should boot normally with four IDE HDDs

[SiS 5511] MSI MS-5124 does not boot DOS 6.22 with three or four IDE HDDs. With one, two IDE HDDs, DOS 6.22 boots fine.

**To Reproduce**
1. Create machine [SiS 5511] MSI MS-5124
2. C/H/S Parameters: 4161/16/63 (2047MiB)
3. Connect a system HDD with DOS 6.22 and three more IDE HDDs to the built-in IDE controller
4. Set the BIOS parameters HDD Type: Auto Detect Hard Disk Parameters (as in the screenshot below)
![2022-09-17_175637](https://user-images.githubusercontent.com/58270614/190863382-97442ba3-c4e8-46c9-8e64-3304e5c071c8.png)
6. Start the machine, about 18 seconds after the HDD is detected, you will see the message "Secondary HDC Failure" (as in the screenshot below)
![2022-09-17_175709](https://user-images.githubusercontent.com/58270614/190863386-7ddda574-653b-4606-a1f2-13a222b03d86.png)

**Expected behavior**
DOS 6.22 should boot normally with four IDE HDDs

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.8.0 x64 Build 4090
 - Build type: regular, old recompiler.

**Comment by OBattler** [comment]
Going to close this - #1 is now fixed, #2 I can't fix (it's a BIOS bug), and #3 needs my SiS 551x rewrite to be finished - it's currently implemented improperly.
