### ISSUE TITLE
Compaq Portable doesn't recognize the second diskette drive.

### ISSUE THREAD

**Issue by lautis0503** [86Box/86Box#2688]
**Describe the bug**
Compaq Portable doesn't recognize the second diskette drive.

**To Reproduce**
1. Create machine: Compaq Portable, 128K RAM, Compaq CGA, two 5.25" 360K diskette drive.
2. Download Compaq OEM MS-DOS 2.12 from [WinWorld](https://winworldpc.com/product/ms-dos/2x). (In additional, Compaq OEM MS-DOS 2.11 and 3.0 are also tried, and they produced the same result.)
3. Prepare another diskette image that is confirmed to work.
4. Insert MS-DOS diskette in drive A, and another diskette in drive B, then boot the system.
5. Try the following commands: `DIR B:`, `FORMAT B:`, `DISKCOPY A: B:`.
6. All these commands show that this is a single drive system, and they operate on drive A.

**Expected behavior**
All these commands should operate on the drive B.

**Desktop:**
 - OS: Windows 7 SP1 x64
 - 86Box version: 3.7.1 from Github release

**Additional context**
- When follow these steps in PCem V17, the MS-DOS doesn't even boot.
- When boot PC-DOS 2.10 in IBM PC (1982), 128K RAM, CGA, two 5.25" 360K diskette drive, everything works fine.
- When boot Compaq MS-DOS 2.12 in IBM PC (1982), 128K RAM, CGA, two 5.25" 360K diskette drive, everything works fine.

**Comment by thunderbird32** [comment]
Unless this has changed since I asked @TC1995  in 2018, this isn't a bug per se. 86box is actually emulating the Portable _Plus_ which only had one disk drive. I'm not sure the Plus supported a second floppy instead of the hard disk.

**Comment by lautis0503** [comment]
Thanks for your reply.
The model name is `[8088] Compaq Portable`. Then I expect that to be the Compaq Portable, not _Plus_, as I thought the model name should be _exact_.

And according to [COMPAQ Portable Computer ROMs](https://www.pcjs.org/machines/pcx86/compaq/portable/rom/):
> NOTE: minuszerodegrees.net claims that its ROM dump was from a “Portable Plus”, but the Rev C ROM BIOS was an update used in both the COMPAQ Portable _and_ the COMPAQ Plus, so strictly speaking, that revision is not _just_ a “Portable Plus” ROM.

While Compaq Portable could have the second diskette drive.

**Comment by OBattler** [comment]
Closed the wrong issue.
