### ISSUE TITLE
When I play games like half life, at random times all input just stops working.

### ISSUE THREAD

**Issue by TmanGamer** [86Box/86Box#2696]
**Describe the bug**
When I play games like half life, at random times all input just stops working. Nothing works, any input; mouse stops; ctrl+alt+del doesn't work; literally all input stops. I have had this problem for a while and no matter what settings and configurations i use it happens with full

**To Reproduce**
1. Run a fullscreen game that is first person, (Particularly half-life)
2. Play it for a bit.
3. It should just lock up.

**Expected behavior**
Input should not lock up

**Desktop (please complete the following information):**
 - OS: Windows 10/11
 - 86Box version: any version.
 - Build information: Windows 64x

**Comment by TmanGamer** [comment]
[Here is a video of it.](https://gofile.io/d/7QKLL7)

**Comment by TC1995** [comment]
known issue, a rework of the PS/2 kbd controller is in the works.

**Comment by TmanGamer** [comment]
Also I noticed if I use Chrome Remote Desktop it works without freezing if that add any new information for you.
