### ISSUE TITLE
S3 924 high color modes bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2699]
**Describe the bug**
The S3 924 have distorted screen and colors under high color (32k/64k) modes. The card supports 640x480 at that resulutions.

**To Reproduce**
1. boot the machine
2. Type Win ad DOS prompt
3. See the error

**Expected behavior**

**Screenshots**
Windoes 3.1 at 640x480 32k color mode
![S3 924 Bug](https://user-images.githubusercontent.com/31600563/192549697-014d0bb0-880c-43f5-900c-983e34afc717.png)

CFG and  NVR files;
[386 SX-33 Xtradrive.zip](https://github.com/86Box/86Box/files/9656722/386.SX-33.Xtradrive.zip)

HDD File
[386 SX- Xtradrive.zip](https://github.com/86Box/86Box/files/9656734/386.SX-.Xtradrive.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 
 - 86Box version: 3.8.0.9094
 - Build information: Old dynarec, Win 32

**Additional context**
-I disabled the DOSMAX programs because it have conflicts with Xtradrive 3.0
-I excluded, the B000-B800 memory area, as requested by the S3 924 Win 3.x drivers, otherwise it does not start.

**Comment by TC1995** [comment]
known issue.

**Comment by iamgreaser** [comment]
Something to run in `debug` to test 640x480x16bpp mode:

```
a100
mov ax,4f02
mov bx,0111
int 10
mov ax,a000
mov es,ax
mov ax,0000
xor di, di
stosw
add ax,0002
jnc 112
mov ah,00
int 16
mov ax,0003
int 10
int 3

g=100

```

Press a key to return to the normal `debug` prompt.

Currently, this happens:

![image](https://github.com/86Box/86Box/assets/138113/25e302d6-e732-41e0-9547-b305f0747dc1)

If one doesn't write to video memory, then the green lines will extend to the top of the screen.

There is a chance that fixing this properly will involve diving into the acceleration engine and seeing what's going on there.

**Comment by OBattler** [comment]
I suspect a vid_svga.c bug actually, because this has been attested on a Cirrus Logic as well: https://github.com/86Box/86Box/issues/1452 .

**Comment by OBattler** [comment]
Closing this as a CANTFIX until the S3 924 documentation is found.

**Comment by TC1995** [comment]
Actually, this is mostly fixed.
