### ISSUE TITLE
Blood crash on Windows 98

### ISSUE THREAD

**Issue by AITUS95** [86Box/86Box#2700]
**Describe the bug**
When i try to run blood on windows 98 i get this message

![Monitor_1_20220927-191131-873873](https://user-images.githubusercontent.com/48457684/192592738-6f58bfed-cb8c-4c55-8af8-ae22aa7db859.png)

**To Reproduce**
1. Go to Blood
2. Click on play
3. See error

**Desktop**
 - OS: Windows 10
 - 86Box version:. v3.8 build 4095
 - Build information: old dynarec

**Additional context**
I have a real windows 98 system and this does not happen when I launch the game, in MS-DOS mode it starts without problems but the scenes are cut. this also happens on PCEM.

**Comment by AITUS95** [comment]
i tried, i also disabled the sound card, but it doesn't work

**Comment by toddfraser88** [comment]
I'm unable to reproduce this error -

![blood_working_Screenshot 2022-10-01 163044](https://user-images.githubusercontent.com/9592379/193400710-8ff3018d-29c0-4ac9-8f7a-2b30781371e9.png)

**Comment by AITUS95** [comment]
> I'm unable to reproduce this error -
> 
> ![blood_working_Screenshot 2022-10-01 163044](https://user-images.githubusercontent.com/9592379/193400710-8ff3018d-29c0-4ac9-8f7a-2b30781371e9.png)

what version of the game are you playing?  mine is 1.0.

**Comment by toddfraser88** [comment]
I'm on One Unit Whole Blood which I think is 1.21? not sure.

**Comment by AITUS95** [comment]
> I'm on One Unit Whole Blood which I think is 1.21? not sure.

I have the CD which is a version 1.0, corresponding to the same crc of redump, the problem occurs with this version and on my real vintage pc this does not happen.

**Comment by toddfraser88** [comment]
It might be your VM config, try a different Motherboard/CPU combo.

**Comment by AITUS95** [comment]
Tried with many machines but without success.

**Comment by AITUS95** [comment]
@OBattler I did some tests with old versions and came to the conclusion that the problem occurs after build v3.0 2633, after this version Blood 1997 1.0 returns the following problem.

**Comment by OBattler** [comment]
This is strange - I see no change in either 2633 or 2634 that could have introduced this problem.

**Comment by OBattler** [comment]
> this also happens on PCEM.

It just so happens that most CPU changes in 2634 were ported from PCem. So PCem introduced the regression and 2634 ported it to 86Box.

Can you upload the whole VM somewhere so I can reproduce the bug and therefore, attempt to fix the problem?

**Comment by AITUS95** [comment]
This is the machine I am using:

https://www.dropbox.com/s/qw3j452brfmor7m/Win98VM.7z?dl=0

sorry for the excessive size of the VM, so the regression is part of PCEM v17, v15 and v16 do not have this bug.

**Comment by AITUS95** [comment]
> I attached your HDD img file to my VM and encountered the same bug on my end.

the bug occurs only after version 2633.

**Comment by AITUS95** [comment]
**UPDATE: The game finally works, so problem solved !**

![Monitor_1_20221031-002029-619619](https://user-images.githubusercontent.com/48457684/198906950-d1b0ff74-5f8a-4299-85b2-a96545feec4a.png)

**small clarification, on SLOT 1 machine with Gigabyte GA-686BX the game only displays the intro but then returns to the desktop without error messages, but it could also be a real problem with the machine:**

![Monitor_1_20221030-235703-224224](https://user-images.githubusercontent.com/48457684/198907109-83f0e573-39e4-4ce5-83b7-bd10ac4198d5.png)

![Monitor_1_20221030-235750-522522](https://user-images.githubusercontent.com/48457684/198907116-b25602fd-e065-451c-9839-c500e3f9a414.png)

I am attaching the VM: https://drive.google.com/file/d/1SeqWrKNVFswY7B9zHhZSQuWUQ3FFU9Qz/view?usp=share_link
