### ISSUE TITLE
Midisoft crashes 86Box with dynarec

### ISSUE THREAD

**Issue by OlivierDoriath** [86Box/86Box#2705]
**Describe the bug**
86Box (both Stable and Experimental) crashes completely when trying to run Midisoft Recording Session 1.12 in Windows 95 with dynarec enabled. It gives an "Over Limit!" message box, and upon clicking 'OK', closes.

**To Reproduce**
1. Try to open Midisoft Recording Session 1.12 on a Windows 95 machine with dynarec enabled (see specs below).
2. The software may rarely open without any issues. If that happens, close and reopen it.

**Expected behavior**
Maybe a blue screen, but definitely not a crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/45044707/193483771-e5c4853f-0f6a-45de-b7fc-b778c72c6e84.png)

**Desktop (please complete the following information):**
 - Host OS: Windows 11 x64
 - Guest: Windows 95 OEM Service Release 2.5, A-Trend ATC-1415, Cyrix Cx486DX4 @100Mhz, 16MB RAM, Cirrus Logic GD5436, Microsoft Serial Mouse, Sound Blaster Pro v1 (FluidSynth out)
 - 86Box version: Both Stable and build 4096
 - Build information: Old dynarec

**Comment by englebert3rd** [comment]
I'm getting the same error when playing SimTower after a few minutes with the Steam Deck.

86Box v3.7.1
Machine Type: Socket 4
Machine: [i430LX] Intel Premiere/PCI
CPU type: Intel Pentium/ Speed 66
Memory: 64 MB
Display: [PCI] S3 Virge/GX2 + Voodoo 2 (non-SLI)
Soundcard: [ISA] Sound Blaster 16
HD Controller: [PCI] IDE Controller
SCSI Controllwe: [ISA16] Adaptec AHA-154xA

**Comment by OBattler** [comment]
This is now fixed.
