### ISSUE TITLE
IBM PCjr throws an ERROR D when doing a hard reset of the emulator

### ISSUE THREAD

**Issue by Digitoxin1** [86Box/86Box#2707]
**Describe the bug**
After launching 86Box while emulating the IBM PCjr, if you perform a Hard Reset, on the subsequent reboot, the PCjr boot screen will display ERROR D.

**To Reproduce**
Create an IBM PCjr virtual machine with default settings.
Start the virtual machine and let it step through the memory test and boot to Basic.
Perform a Hard Reset
After the memory test, the PCjr boot screen will display ERROR D under the memory counter.

![image](https://user-images.githubusercontent.com/5696659/193498727-e8a8ab52-4dba-4883-b19c-5a2071a233c4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.7,1
 - Build information: 86box-windows-64-b4032.zip

**Comment by OBattler** [comment]
This is now fixed. I had to reset the next serial instance to 0 in pc_reset_hard_close() - it was not being reset at all, so on hard reset, the PCjr serial was not being added.
