### ISSUE TITLE
Audio stuttering in every 86box VM

### ISSUE THREAD

**Issue by Rasthro** [86Box/86Box#2709]
When i started my Windows 3.1 86box VM with SoundBlaster 16 drivers, Audio started to stutter a lot and it was very annoying since this never happened before, When i created a new one with freshly windows 95 and SoundBlaster AWE64 Gold Drivers installed, Audio was still stuttering and mouse was very laggy, What's wrong with 86box?

I use Intel Core i7-10510U with 1.8gHz clock speed and 4 cores (8GB VRAM)

PLEASE TELL ME WHAT IS WRONG I SWEAR THIS NEVER EVER EVER EVER HAPPENED BEFORE

UPDATE: I setted up a Windows NT 3.5 VM with SoundBlaster 16 drivers and i did not see this audio stuttering problem, But still, Why such problem on my other VMs

**Comment by TC1995** [comment]
Calm down please.

**Comment by OBattler** [comment]
Are they running at 100%? If they go below 100% in the title bar, reduce the speed of the emulated CPU.

**Comment by OBattler** [comment]
Closing this as NOTABUG.
