### ISSUE TITLE
Add Tandy 2000 and VooDoo 4 and VooDoo 5

### ISSUE THREAD

**Issue by Rasthro** [86Box/86Box#2710]
Did you forget that Tandy 2000 even existed?

Well, I request you to add Tandy 2000 machine to 86Box

Also, Another great idea: Add VooDoo 4 and VooDoo 5 Video/Graphics cards to 86Box!

**Comment by MrPepka** [comment]
If you have information on the hardware documentation of Voodoo 4/5 graphics cards and Tandy 2000 machine and you know someone who would have knowledge about the operation of 3D graphics cards in hardware, maybe these devices will be implemented one day

**Comment by TC1995** [comment]
The Tandy 2000 is not PC compatible and has a number of proprietary features and Voodoo4-5 are possibly too powerful.

**Comment by JimboMumbo** [comment]
[voodoo45_spec.pdf](https://github.com/86Box/86Box/files/9740186/voodoo45_spec.pdf) I'm sure this would be impossible for one day.

**Comment by Rasthro** [comment]
> [voodoo45_spec.pdf](https://github.com/86Box/86Box/files/9740186/voodoo45_spec.pdf) I'm sure this would be impossible for one day.

oh really? well, my cpu is much more powerful than voodoo 4/5, so it's a complete nonsense if my pc, which uses cpu much more powerful than voodoo 4/5, can't even emulate voodoo 4/5

**Comment by TC1995** [comment]
It's about the resources...

**Comment by sskras** [comment]
@Rasthro commented [3 hours ago](#issuecomment-1279670701):

> oh really? well, my cpu is much more powerful than voodoo 4/5, so it's a complete nonsense if my pc, which uses cpu much more powerful than voodoo 4/5, can't even emulate voodoo 4/5

@TC1995 commented [10 minutes ago](#issuecomment-1279693956):

> It's about the resources...

Well, it's more about the type of work it has to do.  In this case one CPU must emulate the different nature of another CPU.
This reminded me of emulation of the Alpha CPU by DEC.

Although its last version (Alpha 21364 | EV7) was designed in 1998, running at 1.2 GHz and discontinued in 2004, to emulate it using x86-64 architecture takes a lot of the modern CPU power:

Quoting [vtAlpha: x86 host sizing](https://www.avtware.com/vtalpha-x86#:~:text=Alpha%20CPUs%20%2B%2050%25%20%2B%20QBBs&text=requires%20quite%20some%20X86%20CPU%2Dpower&text=the%20latest%20generations%20of%20Intel%20Xeon%20(v3%20or%20v4)%20processors%20with%20a%20CPU%2Dfrequency%20of%203%20GHz%20or%20better):

> **requires quite some X86 CPU-power to match the performance of the original system**. We therefore **recommend the latest generations of Intel Xeon (v3 or v4)** processors with a CPU-**frequency of 3 GHz** or better.

... and a many software optimizations / innovations / tricks too:

Quoting [AVTware is hiring! - SW Developer C/C++ - Linux expert](https://www.avtware.com/hiring#:~:text=Sometimes%20the%20gap%20between%20old%20and%20new%20computers%20is%2030%2B%20years%2C%20so%20we%20need%20to%20be%20very%20inventive%20to%20close%20this%20generation%20gap%20without%20the%20users%20noticing.%20We%20therefore%20look%20for%20people%20who%20enjoy%20tackling%20quite%20complex%20problems.):

> Sometimes the gap between old and new computers is 30+ years, so we need to be very inventive to close this generation gap without the users noticing. We therefore look for people who enjoy tackling quite complex problems.

**Comment by OBattler** [comment]
I think this can be closed for being a feature request that's out of scope.

**Comment by LeoKids** [comment]
https://vgamuseum.info/images/doc/3dfx/voodoo45_databook.pdf

https://vgamuseum.info/images/doc/3dfx/voodoo45_spec.doc

**Comment by TC1995** [comment]
Not now.

**Comment by TC1995** [comment]
Currently not for the time being.

**Comment by cartifanwlr** [comment]
There are two problems with the VSA-100:
1. It's out of scope for 86Box currently as it falls into the Pentium 3 era,
2. We don't have anyone that deals with 3D.

**Comment by cartifanwlr** [comment]
No host on earth can emulate the P2 @ 450.

**Comment by cold-brewed** [comment]
As already stated, this is not in scope for 86Box.
