### ISSUE TITLE
When playing Full Tilt! or the standalone Space Cadet Pinball table under 86Box 3.7.1 on Linux, you are unable to launch the ball using SPACE.

### ISSUE THREAD

**Issue by Greenfly39** [86Box/86Box#2712]
I am encountering an issue with the 86Box 3.7.1 Stable build, Whenever you try to launch the ball with the spacebar, the plunger doesn't go down and the push sound loops, check the videos attached.

Expected behaviour:

https://user-images.githubusercontent.com/107608947/194747208-855a9802-0682-4185-a5c3-4b10dda971c0.mp4

Result in 86Box:

https://user-images.githubusercontent.com/107608947/194747391-0100ec07-7581-4689-ba8d-d0e4a1132771.mp4

I am unsure whether this occurs in the Windows or Mac builds as of yet.

This also occurs on multiple Windows guest operating systems as well so this isn't just a Windows 98 thing.

**Comment by Gogo268** [comment]
can't reproduce, build 4096. ball launches correctly while holding space

**Comment by Greenfly39** [comment]
Odd, FYI, I'm using Linux Mint 21 with the X11 version of KDE Plasma.

**Comment by chungy** [comment]
I can reproduce on e950ebae171d43cb5785be56d1130b23cd9af631 with a Windows Me guest (Pentium II 233MHz emulated).

**Comment by chungy** [comment]
Confirmed to still be an issue on b1027c7c5c87cea45a60873ae4b6cce2d3c20abb
