### ISSUE TITLE
Network is literally very very very very very very very very very very slow!!!

### ISSUE THREAD

**Issue by Rasthro** [86Box/86Box#2714]
Okay, So I have a WFW 3.11 machine with the right network drivers installed, I installed IE 3.0 and the internet worked fine and all, BUT...

...THE INTERNET IS SOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO SLOW!!!!!!!!!!!!!!!!!!!!!!!

You heard me! Most websites, Even google search results, TAKE FOREVER TO LOAD!

I tried to go to http://razorback95.com/ and IT TOOK FOREVER TO LOAD
http://google.com/ didn't take long to load but when i search something in google, The results take forever to load

ANYWAY TO MAKE THE INTERNET FASTER OR WHAT?

[INTERNET CONFIGURATION]

(CARD 1)

Mode: SLiRP

Interface: None

Adapter Type: PCI

Adapter: Realtek RT8029AS (BIOS Enabled)

**Comment by TC1995** [comment]
Calm down again.

**Comment by OBattler** [comment]
Already fixed on Jenkins builds, but it was done by elyosh after the release of the last stable.
