### ISSUE TITLE
Appimage doesn't open with cfg file settings

### ISSUE THREAD

**Issue by austeregrim** [86Box/86Box#2719]
**Describe the bug**
Appimage doesn't run by default with cfg file settings... and no way to import settings from the cfg file after starting.

**To Reproduce**
Double click the stupid appimage file from a caja window.. observe defaulted config.

**Expected behavior**
Maybe the app should always check for a cfg file and open it?
Maybe there should be a way to import the config after starting the app?

v3.7.1

**Comment by austeregrim** [comment]
Sorry, I was frustrated when I wrote this... and appimage bundles irritate me a bit. (everyone is doing them, and it's ruining the installation and management of software.)

**Comment by cold-brewed** [comment]
As far as I know, the appimage by default will look in the current directory for a configuration file. If you are double clicking on the appimage then it should look in whatever directory it resides in. If there is no config file it will load a default config. Are you observing a different behavior?

If you are looking to have it use a specific file or directory you'll need to either put the executable in that directory or run with the `-P <directory>` argument.

There is currently no way to load a config file after the app is started.

**Comment by austeregrim** [comment]
The issue was with the file explorer/manager (I forget which) I was using, I had opened the 86box sub folder through the tree view and it ran the appimage at the root folder that was opened... not at the directory the file existed.

So no, it's not looking where it resides, which is what I expected. But appears to be looking at where the executable is called from?

I guess what you're saying is I'm looking for is a gui wrapper to handle 86box

**Comment by OBattler** [comment]
The GUI manager is being worked on.

**Comment by cold-brewed** [comment]
Keep in mind that the launcher (in this case the file explorer / manager you mention) sets the working directory when it launches a program (the appimage). 86Box just looks in the current working directory as set by the launcher or shell.

In other words, I think everything appears to be working as designed here unless I'm missing something.

**Comment by OBattler** [comment]
Then this can be closed.
