### ISSUE TITLE
Pravetz DOS-16 external commands freeze the VM.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2727]
I tested the Pravetz DOS-16 ver 3.10 on the Pravetz 8088 machine. The DOS commands I tested FDISK CHKDSK, DEBUG and EDLIN crash the machine. I created the a 10mb partition using the standard MS-DOS 3.21 with its FDISK command with no issue.
The DOS-16 FORMAT command works right. Also DOS-16 boots right.
So, I think these, DOS-16 external commands, expects some behaviour not emulated.

Here is the CFG and HDD image file:
[8088 Pravetz.zip](https://github.com/86Box/86Box/files/9843121/8088.Pravetz.zip)
[Pravetz 8088.zip](https://github.com/86Box/86Box/files/9843122/Pravetz.8088.zip)

**Comment by OBattler** [comment]
Are you sure the DOS you installed isn't for the 80186-using Pravetz-16ES?

**Comment by OBattler** [comment]
What floppy image did you copy the files from? DEBUG.COM, for example, is corrupt - the first 512 or so bytes are from another floppy sector.

**Comment by OBattler** [comment]
I found the floppy image and it's strange - it appears someone inserted one sector full of 0xF6's into each track, causing them to shift, and part of the data to be outright missing.

**Comment by OBattler** [comment]
As such, I'm closing this with NOTABUG - floppy image is corrupted, old-dos.ru also provides a ZIP with proper copies of the same files, replace the files with those from the ZIP.
