### ISSUE TITLE
Acer IDE CD-ROM driver does not work properly

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#2728]
**Describe the bug**
The Acer IDE CD-ROM driver (ACER215H.SYS) included with some HP Pavilion systems causes DOS to throw a CDR103 ("CDROM not High Sierra or ISO-9660 format reading drive G") message when attempting a directory listing and causes DOS to become non-responsive for a long time if Retry is chosen at the prompt.

**To Reproduce**
1. Boot from the attached floppy image
2. Close the recovery utility when it errors out (press Enter)
3. Type "G:" and then "dir" with any CD-ROM image attached
4. Notice the CDR103 error
5. Press "R" to retry
6. Notice that DOS becomes non-responsive and the CD-ROM status indicator is lit
7. If you wait long enough another CDR103 error appears

**Expected behavior**
The directory listing should appear

**Screenshots**
![Monitor_1_20221022-193300-165165](https://user-images.githubusercontent.com/47463859/197367802-6427f4a3-760d-4716-9db0-813800116057.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1
 - 86Box version: 3.7.1 stable and 3.8 build 4114
 - Build information: x86 old dynarec

**Additional context**
This CD-ROM driver does function properly on real hardware (A Pentium system with an HP CD Writer Plus 7200).

Boot diskette used: 
[CDBOOT.zip](https://github.com/86Box/86Box/files/9845567/CDBOOT.zip)

Config file:
[86box.zip](https://github.com/86Box/86Box/files/9845568/86box.zip)

**Comment by OBattler** [comment]
I suspect thiss is a driver for specific CD-ROM drives.

**Comment by TC1995** [comment]
It might be using vendor specific commands.

**Comment by win2kgamer** [comment]
I have performed some additional testing on real hardware: On both a Pentium III system with a Liteon LTD-163 DVD-ROM and a Toshiba Satellite 305CDS with a Toshiba XM-1602BV CD-ROM the same failure behavior noticed in 86Box occurs.

I am starting to wonder if this driver is depending on an ATAPI implementation quirk of some older drives. The HP systems that included this driver could have either Acer or Mitsumi CD-ROM drives installed at the factory but always used the Acer driver file. The HP CD Writer+ 7200 drive from my initial real hardware test is from a couple of years after this driver was created and does not identify itself as an Acer drive.

I built a version of 86Box with CDROM and IDE logging enabled and attached the output shown between when I press enter on the "DIR" command and when the CDR103 message appears: 
[86box_idelog.txt](https://github.com/86Box/86Box/files/9848076/86box_idelog.txt)

**Comment by headsetguy37** [comment]
Hmm... Seems similar to the issue I have with the Mitsumi IDE CD-ROM driver (see Issue/Feature Request #2383).

**Comment by OBattler** [comment]
- win2kgamer: What's missing is the log output of scsi_cdrom.c as that's also used by ATAPI (which is basically SCSI over IDE). That would show what's going on.

**Comment by win2kgamer** [comment]
I rebuilt 86Box with scsi_cdrom.c's logging enabled as well as the IDE and CDROM logging from before and the new log file is attached: 
[86box-cdrom-log.txt](https://github.com/86Box/86Box/files/9856367/86box-cdrom-log.txt)

**Comment by OBattler** [comment]
I got the driver to work - it expects the ATAPI phase to change immediately upon command execution. I need to look at the ATAPI specification to see what it's supposed to do.

**Comment by OBattler** [comment]
The ATAPI specification indicates the phase register (I/O and CoD) is supposed to be set when data is ready, so clearly these Acer drives are not fully compliant. However, it does not prohibit setting it earlier.

**Comment by OBattler** [comment]
Fix committed, so this cann ow be closed.
