### ISSUE TITLE
Port the Ricoh/JVC hard disk interface to the Toshiba T1200

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2735]
**Is your feature request related to a problem? Please describe.**

No. But the addition of the Ricoh/JVC controller to the Toshiba T1200, (Since it uses the same hard disk interface than the Victor VP86) will allow to have the HDD and Hard-RAM (battery backed RAM drive supported by this machine) to coexist simultaneously. Now whit the external MFM controller the setup utility assigns the drive C letter to the RAM disk, but since it is already used by the MFM controller it cannot be accessed.

**Describe the solution you'd like**
Port the Ricoh/JVC contoller code to the Toshiba T1200

Here is the a web page that shows the machines that have the Rico/JVC controller.

https://knm.org.uk/blog/2017/04/the-jvc-26-pin-hard-disk-interface-part-1

And  I opened an issue back in 2018 ( Number #330)

**Comment by OBattler** [comment]
Update the ROM set, go to the hard disk controllers menu, and set to the V86P controller, then your Toshiba T1200 is going to use that. But I do admit that it should be doable as an Internal option as well.

**Comment by OBattler** [comment]
This is now done.
