### ISSUE TITLE
Ricoh/JVC controller bugs with the Toshiba T1200

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2738]
**Describe the bug**
I found that the FDISK utility included with Toshiba DOS 3.30 does not recognize the the HDD (says "no fixed disk present). The regular MS-DOS 3.30 detects it correctly. I tried to use the FORMAT and SYS DOS utilities included with Toshiba DOS (after using the FDISK from regular MS-DOS), but I get a "Disk boot failure" error.
I don't know what is different from the Victor V86P machine. On the V86P works just fine. However the machine detects correctly the HDD presence in the SETUP1.EXE configuration utility. (I know that because it the detects the machine as 1 Floppy model, with external controller I always change to 2 floppy drive configuration) and the C drive can be accessed if I boot from a floppy drive, also CHKDSK does not find any error. 

**To Reproduce**
1. Create a type 3. C/H/S 615/4/17, and use the inernal controller
2. Boot from Toshiba DOS 3.30
3. Try to run FDISK from command prompt
4. Do the same with regular MS-DOS 3.30

Here is the HDD and FDD image files:

HDD:
[Toshiba T1200 Ricoh-JVC.zip](https://github.com/86Box/86Box/files/9856228/Toshiba.T1200.Ricoh-JVC.zip)

FDD:
[Microsoft DOS 3.30 [Toshiba OEM] (3.5).zip](https://github.com/86Box/86Box/files/9856224/Microsoft.DOS.3.30.Toshiba.OEM.3.5.zip)
[Microsoft MS-DOS 3.30 (5.25).zip](https://github.com/86Box/86Box/files/9856225/Microsoft.MS-DOS.3.30.5.25.zip)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Win 10 x64
 - 86Box version: 3.0.8.4124
 - Build information: old dynarec x32

**Comment by OBattler** [comment]
Do we have any dump of the T1200 hard disk controller BIOS? Perhaps that would solve the problem.

**Comment by Fenix770** [comment]
Here is the HDD BIOS uploaded by THS2022. 
[t1200.zip](https://github.com/86Box/86Box/files/9874414/t1200.zip)

John Elliott, the person that implemented the Toshiba laptops, sent to him via e-mail.

**Comment by thecheese2022** [comment]
IC15 is the BIOS. 
IC2 is the Z80 firmware from the hard drive controller.

**Comment by OBattler** [comment]
IC15 is the machine BIOS, I already had that file. I guess I could try loading the internal controller BIOS-less and see if it works.

**Comment by OBattler** [comment]
I need the configuration file to know the CHS.
