### ISSUE TITLE
LibPNG Dependencies Missing

### ISSUE THREAD

**Issue by PeladoFeo** [86Box/86Box#274]
86Box compilation failed for me with the following error:
png.h: No such file or directory

It's time to update the development environment!

**Comment by OBattler** [comment]
I'm going to update it. For time being, just run this:
pacman -S mingw-w64-i686-libpng
That should install libpng.

**Comment by dhrdlicka** [comment]
I think it should be documented how to construct the development environment on the user's own, i.e. write down all software components required to successfully build 86Box along with a link to the already prepared development environment.

**Comment by OBattler** [comment]
The pre-made development environment as such is going away. Eventually there are going to be instruction on how to prepare your own.
