### ISSUE TITLE
Slow Emulation

### ISSUE THREAD

**Issue by Jimbo7136** [86Box/86Box#2742]
Hi,

Thanks for making this emulator happen. It's something that has been sorely needed for awhile IMHO.

That being said, why is it that I can barely emulate a 100MHz CPU on a Ryzen 5900X?

Is there some way to take advantage of more than one core for emulation? I apologize for my ignorance, perhaps what I'm asking is impossible, thank you for all your hard work.

**Comment by OBattler** [comment]
It should definitely go faster than that. What build of 86Box are you using? And is it 32-bit or 64-bit? If it's 64-bit, get the 32-bit build instead as that performs better. What renderer are you using? Try the various renderers to see which performs better.

**Comment by Jimbo7136** [comment]
I don't know, I've already deleted it. Too many issues.

I think it was 64 bit. I'll try again after a year or two, let the bugs be worked out.

**Comment by OBattler** [comment]
Well, if you don't report the issues, how am I supposed to even know what issues you're talking about?

**Comment by Jimbo7136** [comment]
Someone with  more patience than me will report them, I presume.

One of them was that I changed the CPU type from celeron to pentium II hoping it would be easier to emulate and the machine refused to boot, saying to put a disk in A:. (It has previously been booting windows 98 se, which I had installed.)

The other was that I tried to create a new hard disk and try again (re-install OS), and every time I tried to change the settings of the machine the program complained that the hard disk file was missing. I had just created a new hard disk file twice.

I signed up to be a user of the software, not a beta tester. It's clearly not ready for use, which is understandable, but not interesting to me. I'd rather use physical hardware to run windows 98 until the emulation is perfected.

**Comment by jriwanek** [comment]
Pentium IIs are heavier on the host than Celerons, the issue is not that it's beta software, but rather that you have expectations of emulation which don't hold true in reality, It's very likely that you were using a very old build as performance was *massively* increased in 3.7.1. There's also little to no point opening issues if you're not prepared to actually tell us anything of use to fix the issues you're experiencing.

**Comment by jriwanek** [comment]
Also, for reference, the 64 bit builds are infact *slower* than the 32 bit builds for technical reasons which arn't of major note, but unless you're wanting to emulate a system with a very large amount of RAM (>1GB) offer no advantage either.

**Comment by Jimbo7136** [comment]
I downloaded the software, frontend and the underlying emulator a few days ago, so unless the authors posted old versions to be downloaded, I don't see why they would be outdated.

Maybe it would work better with the 32 bit version, but that's not the only issue.

**Comment by OBattler** [comment]
> Pentium IIs are heavier on the host than Celerons,

Actually, with the current code, they're the same since they both use P6 timings.

> One of them was that I changed the CPU type from celeron to pentium II hoping it would be easier to emulate and the machine refused to boot, saying to put a disk in A:. (It has previously been booting windows 98 se, which I had installed.)

I'm not even sure how simply changing the CPU can cause that, except if you changed from a lower-clocked celeron to a higher-clocker P2 and with that, caused the emulator to run so much below 100% that all the timings broke down. If that's so, just switch to a slower emulated CPU.

> The other was that I tried to create a new hard disk and try again (re-install OS), and every time I tried to change the settings of the machine the program complained that the hard disk file was missing. I had just created a new hard disk file twice.

That means you created the hard disk image in a place that's not writable.

**Comment by dhrdlicka** [comment]
> I signed up to be a user of the software, not a beta tester. It's clearly not ready for use, which is understandable, but not interesting to me. I'd rather use physical hardware to run windows 98 until the emulation is perfected.

I hope you understand that you can't expect an open source project to improve if you don't do the bare minimum of providing relevant information about the issues you were experiencing.

**Comment by Jimbo7136** [comment]
I was using winbox front-end for 86box, so perhaps it downloaded an older version of 86box. Not sure.

I am in the process of re-downloading the emulator, I will try your suggestions and report back.

**Comment by OBattler** [comment]
Winbox is itself very outdated, because its author has long stopped developing it for personal reasons, so it's not even guaranteed to be properly compatible with recent 86Box versions. I recommend using Overdoze's 86Box Manager until the currently in development built-in manager is complete.

**Comment by Jimbo7136** [comment]
I think I found the issue with the missing hard disk image file.

I "created" an image that was 128GB in size. Perhaps this is larger than allowable and that would explain why it was "missing"?

**Comment by Jimbo7136** [comment]
I took your suggestions and downloaded Overdoze's 86Box Manager and 86box 3.7.1 [build 4032].

I'm currently copying files to the virtual hard disk from the virtual cd-rom (image on pci-e 4.0 SSD).

The processor is showing 60%. That's something to do with the emulation cycles, correct?

**Comment by OBattler** [comment]
If you mean the percentage in the toolbar - that number indicates how many emulated CPU frame were executed in the time in which 100 were expected. So your emulated CPU is not achieving its full speed - change to a slower one.

**Comment by Jimbo7136** [comment]
I do mean the percentage next to "- click to capture mouse".

Not to be rude. but why offer the option of an emulated CPU that can't be emulated on a top of the line physical CPU?

Can it be emulated on some CPU I'm not aware of?

**Comment by jriwanek** [comment]
My Alder Lake i7-12700k can manage 233-266 on a pentium 2 mostly at 100%, other systems of same era can do similar, newer 13th gen's can likely do better. as to why, completeness.

**Comment by Jimbo7136** [comment]
Yes, well I'm running a Ryzen 5900x. True the the newer generation just became available, but it should be equivalent to your 12700k, so what's the issue?

**Comment by jriwanek** [comment]
In my experiance, the Ryzen's run hotter and slower than the Intels (As per *direct* comparisons between my intel and my partner's AMD)), what kind of temps are you getting, as if they're high then you could be experiancing thermal throttling.

**Comment by Jimbo7136** [comment]
> My Alder Lake i7-12700k can manage 233-266 on a pentium 2 mostly at 100%, other systems of same era can do similar, newer 13th gen's can likely do better. as to why: completeness.

Completeness. You're inviting people to attempt to emulate CPUs that will run poorly, thus generating unhappy users and poor impressions.

CPU is running at 47 C.

**Comment by Jimbo7136** [comment]
I am running the 32 bit version at this time, by the way.

**Comment by jriwanek** [comment]
47 sounds alright for what's being done.

P2's were implemented very early on in 86box, and while you're correct, most are reasonable and understand their computers limitations. Removing them now would be far worse. We've had this same conversation with many people and that's how we made the decision to leave them in.

**Comment by Jimbo7136** [comment]
Might I suggest you implement a way to determine the limitations? I could try 15 CPUs until I find one that will run, but it would be a better user experience if I didn't have to.

**Comment by jriwanek** [comment]
if you have ideas, we're all ears, but we have limited time and resources, and you're the *only* person who's asked. Bear in mind that most all of the developers do this in their spare time, and give said time *for free*.

**Comment by Jimbo7136** [comment]
I understand that. It's just a suggestion.

I did start this thread by expressing my gratitude for the existence of this application more than one way.

**Comment by jriwanek** [comment]
Yeah, I get that, but the whole flow has taken a lot more time than it needed to. This is why we have issue templates which ask for certain information so we can help *better*.
