### ISSUE TITLE
39 Minutes to copy a CD image over the network?

### ISSUE THREAD

**Issue by Jimbo7136** [86Box/86Box#2744]
**Is your feature request related to a problem? Please describe.**

I was emulating an RTL8029AS. This is the fastest network card you offer as far as I know. Windows 98 SE estimated 39 minutes to copy a CD Image over the network. I presume this is because the RTL8029AS is a 10 Megabit/s ethernet adapter.

**Describe the solution you'd like**

Please offer emulation of a gigabit ethernet adapter at minimum. This is silly slow.

**Describe alternatives you've considered**

I could copy it on my host machine and put it into an ISO image and copy it that way. It needs to reside on the guest as a bin/cue for emulation in daemon tools.

**Additional context**

**Comment by OBattler** [comment]
1. We also emulate the AMD PCnet series, which are per se faster than the RTL8029AS, though we do also cap the network speed in order not to slow down the emulator too much;

2. An alternative would be to mount the folder where the CUE+BIN resides to the emulated CD-ROM drive (ie. using the VISO feature) and copy the image that way.

**Comment by Jimbo7136** [comment]
I appreciate the suggestions.

Is there a reason emulation is so slow?

**Comment by OBattler** [comment]
Already emulating the CPU is taxing to the host CPU, but so is network, as it runs in the CPU thread so if it has to process a lot of packets per second, that consumes a lot of the time that would otherwise be used to emulate the CPU.

**Comment by Jimbo7136** [comment]
Yes, of course.

My question is why does emulating such an ancient CPU/network take so much horsepower on the host?

**Comment by OBattler** [comment]
- Jimbo7136: Which reminds me - get the latest nightly build from our Jenkins, that should have the network improvements in, so network should be quite a bit faster now. I completely forgot that the network stack rewrite happened after the releast of 3.7.1 stable.

**Comment by Jimbo7136** [comment]
Thanks for your answers and suggestions.
