### ISSUE TITLE
Netscape doesn't work

### ISSUE THREAD

**Issue by guest123guest** [86Box/86Box#2748]
**Describe the bug**
When you try to use Netscape 4.08, the emulator crashes most of the time.

**To Reproduce**
1. Install Netscape Communicator 4.08
2. Open any of the Netscape applications.
3. Create a profile
4. See "Over limit!" error, and the emulator crashes.

**Expected behavior**
Netscape Communicator should open as normal.

**Screenshots**
No screenshots, sorry!

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - 86Box version: v3.7.1 [4032]
 - Build information: IDK

**Additional context**
I got the Netscape communicator copy from winworldpc.com.

**Comment by Gogo268** [comment]
Update to the latest nightly build from jenkins, this got fixed recently.
