### ISSUE TITLE
Errors 162 and 163

### ISSUE THREAD

**Issue by ArtiomWin** [86Box/86Box#275]
There's issue with 32-bit IBM PS/2 models: after configuration they give errors 162 and 163 (486 models also give an error 12903).
![20180319_222601](https://user-images.githubusercontent.com/31134876/37617637-c07723f2-2bc4-11e8-8610-618b65d59d1d.png)
![20180319_222454](https://user-images.githubusercontent.com/31134876/37617638-c0a8eeb4-2bc4-11e8-9776-b07f564cbe39.png)

**Comment by TheMadLynx** [comment]
IBM PS/2 isn't like a convenient PC. I think you need to get some knowledge about this platform before trying to use it. You can look for error codes meaning here: http://ps-2.kev009.com/pcpartnerinfo/ctstips/49fe.htm

Then read the user manual and configure this machine properly.

**Comment by MoochMcGee** [comment]
12903 is Coprocessor Error. Is there something wrong with our FPU emulation?

**Comment by TheMadLynx** [comment]
My guess is that topic starter forgot to uncheck the "Enable time sync" option.

**Comment by OBattler** [comment]
MoochMcGee> There is nothing wrong with it, the user probably just chose a 486 without FPU, ie. a 486SX.

**Comment by ArtiomWin** [comment]
Actually PS2 gives error 12903 (co-processor error) here even with 486DX.

**Comment by TC1995** [comment]
well, I've corrected the battery power data error, it was a ram count mistake by me (the model 70, regardless if 386 or 486, supports only up to 16MB)

**Comment by ArtiomWin** [comment]
I've tried recent build. New error was introduced: after configuration booting with reference disk gives this message (and after pressing Enter model reboots with running automatic configuration anew).
![20180322_221823](https://user-images.githubusercontent.com/31134876/37793246-2349ffc0-2e1f-11e8-96a7-c7b8cbed83e4.png)

**Comment by ArtiomWin** [comment]
8 MB.

**Comment by TC1995** [comment]
see if it also happens with 6MB.

**Comment by ArtiomWin** [comment]
With 6MB emulator crashes.

**Comment by ArtiomWin** [comment]
My fault (emulator crashes when I switch to another app during launching). But issue I've described yesterday doesn't depend on RAM (same at 4, 6 or 8 MB).

**Comment by OBattler** [comment]
Error 162 is caused by error 12903, and error 12903 is caused by the fact the emulated FPU is not bit-accurate.

**Comment by OBattler** [comment]
I guess this can be closed since the Model 70/486 has been moved to the Dev branch.
