### ISSUE TITLE
cd-rom drive not found

### ISSUE THREAD

**Issue by CyberNine5** [86Box/86Box#2759]
I wanted to install Quake on 86BOX but when I was setting up my CD-ROM Drive it said that the device was not found and the device name is MSCD001 and model name was OTI-011.

Setup

System:
AOpen Vi15g, Intel 486DX2 66, 16MB Ram, No DR, Local Time

Display:
[VLB] Cirrus Logic GD5428 (Diamond Speedstar Pro Rev. B1) Mem. 2MB, No Voodoo, 8514/A or XGA.

Input:
MS Serial Mouse COM1 2 Buttons

Sound:
SBAWE32, Float32, Nuked, Normal Settings.

No Network

Ports:
2 Serial 1 Parallel not connected.

Storage
HD Internal
FD Internal
QIDE
TIDE

HD:
1GB

2 Floppy (3.5 1.44 5.25 360kb)
1 CD-ROM 2x ATAPI

No removable devices or other peripherals

**To Reproduce**
1. Start 86BOX and set up the specs above.
2. Setup MS-DOS 6.22
3. Setup the CD-ROM driver with the disk down below.
4. When you boot up it should say "Device not found, aborting installation"

**Expected behavior**
I expected it to say 1 device(s).

**Screenshots**
![Monitor_1_20221029-105253-271271](https://user-images.githubusercontent.com/116925716/198752915-3760ef7a-95f6-4dd2-a35a-e62072234c5f.png)
![Monitor_1_20221029-105305-928928](https://user-images.githubusercontent.com/116925716/198752919-2b9b882b-e60d-4eb0-961e-58ff001fdc24.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 64bit
 - 86Box version: v3.7.1
 - Build information: New regular I believe

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by OBattler** [comment]
Can I have that driver please? So I can implement a "NEC CDR-260" option that would emulate the early ATAPI behavior needed by this driver.

**Comment by MX9000** [comment]
Hi @OBattler, If it helps you I downloaded the driver from here (version 2.14 and 2.15 in the "xtra" directory): https://archive.org/details/mscdex-2.23-installer-incl.-vide-cdd
Here they also mention a patched version (2.14a) that works with new IDE interfaces: https://pcdosretro.github.io/vide-cdd.htm
Thank you.

**Comment by OBattler** [comment]
OK, that driver should work now if you go to Settings and check the "Early drive" check box for the CD-ROM drive. It will then emulate a NEC CDR-260 that these early drivers should like.

**Comment by OBattler** [comment]
Yes, confirmed, this driver now works when emulating the NEC CDR-260. Therefore, this can now be closed.
