### ISSUE TITLE
Cropped info text

### ISSUE THREAD

**Issue by TheMadLynx** [86Box/86Box#276]
Hello. 
Info text is cropped here and there in 86Box GUI. Could you add tooltips on such occasions?

![vc_select](https://user-images.githubusercontent.com/30351464/37736255-7a5cfb46-2d61-11e8-91ca-c96322c7e52f.png)

**Comment by OBattler** [comment]
To be fair, these device selection combo boxes should be made a bit wider, then there should be no problem.
