### ISSUE TITLE
[Feature]PCjr Hard drive

### ISSUE THREAD

**Issue by telanus** [86Box/86Box#2768]
**Describe the solution you'd like**
To add hdd capability to the PCjr. Currently afaik the PCjr emulation in 86Box does not support hdds. 

**Describe alternatives you've considered**
The emulation/support for this would be useful: https://www.retrotronics.org/home-page/jride/

**Comment by OBattler** [comment]
How am I supposed to add that when the author doesn't make his changed BIOS available?

**Comment by lemondrops** [comment]
What changed BIOS? I see a download link for some kind of a jr-IDE BIOS here: https://www.retrotronics.org/download/jr-ide-bios-2012-08-29/ , or is this not what is needed?
