### ISSUE TITLE
Things 86Box could have.

### ISSUE THREAD

**Issue by CyberNine5** [86Box/86Box#2769]
Things 86Box could have
Support for more pre-built machines (Gateway Essential 450, Emachines tower 566ir, Acer Aspire 1280/2280 etc.)
Have specific CD-ROM drives like a OTI-011, Sierra SQ3485, etc.
More sound cards like the Audician 32, etc.
Roland SC-55 support and other midi devices.

**Describe the solution you'd like**
I want at least half of the things I mentioned on top to be included in 86Box

**Describe alternatives you've considered**
I could have built them on my own but I would have to find what the specs are.

**Additional context**
You could go to some sites to find some pc specs.

**Comment by telanus** [comment]
Good luck on this.

To answer your feature request: http://86box.net/2022/03/21/why-not-p3.html reasons on why not

**Comment by CyberNine5** [comment]
Ok so what about the other things?

**Comment by telanus** [comment]
There is work being done on the CD-ROMs, but what it means I'm not sure, and for the Soundcards, someone need to write the code, and the datasheets needs to be publicly available.

**Comment by OBattler** [comment]
> Have specific CD-ROM drives like a OTI-011

We emulate the NEC CDR-260 which ues the OTI-011 chip. So that's already done. The rest has been answered.
