### ISSUE TITLE
Custom IDE disk not detected 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#277]
Hello!

I Tested the KMS-C-02 and SPC-4216P, and It does not recognizes an IDE hard disk that uses a custom geometry of 63 cylinders, 16 heads and 63 sectors. However, it recognises a type 35 Hard Disk i created with PCEM.
I cannot use  XTIDE AT either.

Thanks!

**Comment by OBattler** [comment]
I don't think those machines supported custom hard disk types at all.

**Comment by Fenix770** [comment]
The custom IDE disk is supported in the same machines with Pcem.

**Comment by OBattler** [comment]
See if this still happens on the latest builds of 86Box.

**Comment by Fenix770** [comment]
The hard disk image works with the latest build. 

Thanks!

**Comment by OBattler** [comment]
Good to know. I can close this issue then. :p
