### ISSUE TITLE
Olivetti OGC (GO708) blank screen

### ISSUE THREAD

**Issue by javi-s** [86Box/86Box#2776]
**Describe the bug**
The screen is blank on the Olivetti M240 when the Olivetti OGC (GO708) ISA board after commit 8fa09b318d181bb48877a83a35dfa2bb3fb76aa8.  If the machine is configured with another compatible ISA board, such as the MDA or CGA ISA boards, the display is correct.

**To Reproduce**
1. Configure a Olivetti M240 machine
2. Go to Display and Select [ISA] Olivetti OGC (GO708) as Video
3. The screen is blank

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 86Box-Windows-64-b4189

**Comment by OBattler** [comment]
I can reproduce the issue, though I can in fact very faintly see the text.
