### ISSUE TITLE
Amstrad PC1640 Issue

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#278]
Hello

Have somme issue with PC1640 Emulation:
- Even if I choose "PC1640", only show Amstrad PC 512K at boot. Only 512kb of RAM
- There is no way to change DIP settings for the Amstrad (to choos elanguage, for example)
- had issue with HD initialization: FDISK report and show 1 HD, create a partition, but nothing was writen on disque. Had to use another machine type to initialize the disk
- wich mouse setup work with Amstrad Mouse driver ? Tried none and Internal, no way. Had to choose Microsoft/Logitech Serial Mouse and install Microsoft Mouse to get it working.
- sometimes, GEM only detect MONO EGA mode, not ECD350 Mode, and start in B&W. Can't really reproduce when.

**Comment by OBattler** [comment]
> Even if I choose "PC1640", only show Amstrad PC 512K at boot. Only 512kb of RAM

This seems to be gone now.

> There is no way to change DIP settings for the Amstrad (to choos elanguage, for example)

Fixed.

> had issue with HD initialization: FDISK report and show 1 HD, create a partition, but nothing was writen on disque. Had to use another machine type to initialize the disk

Will look into this.

> wich mouse setup work with Amstrad Mouse driver ? Tried none and Internal, no way. Had to choose Microsoft/Logitech Serial Mouse and install Microsoft Mouse to get it working.

Fixed.

> sometimes, GEM only detect MONO EGA mode, not ECD350 Mode, and start in B&W. Can't really reproduce when.

Will look into this.
