### ISSUE TITLE
no rtc found on Vendex headstart turbo 888-xt

### ISSUE THREAD

**Issue by thecheese2022** [86Box/86Box#2783]
**Describe the bug**
RTC not found appears in RTC rev 2.00 when I try to set date and time
seem to uses MM58167AN in backplane not yet implemented
src
https://forum.vcfed.org/index.php?threads/headstart-vendex-turbo-888-xt-switch-settings.47907/#post-618075
**To Reproduce**
1.  select to Vendex headstart turbo 888-x 
2. start the machine then insert the vendex software disk 1  https://archive.org/details/vendex-headstart-bundle
3. Select Setup Change System configuration then Set or Change time and or date Then Set the System clock

**Expected behavior**
does not detect rtc

**Screenshots**
![Monitor_1_20221101-003339-296296](https://user-images.githubusercontent.com/102922015/199166824-4614a22d-03e4-4b9c-bacd-9c58a87d74fe.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro 2004]
 - 86Box version: v3.8  build 4204 x64 1bb1bb9f4
 - Build information: old dynarec

**Comment by Cacodemon345** [comment]
https://www.futurlec.com/Others/MM58167AN.shtml
