### ISSUE TITLE
Mitsumi IDE CD-ROM driver still does not work

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#2788]
**Describe the bug**
During Acer CPR setup, I am still seeing a "CDR101: Not ready reading Drive E. Abort, retry, fail?" error when it comes time to extract the files from the CD-ROM. This is the same error that occurred before the fix was added to scsi_cd.c.

**To Reproduce**
1. Create a machine based on the Acer V30 motherboard, internal IDE controller, hard disk drive, and ATAP CD-ROM drive.
2. Boot from the Acer CPR v1.2 floppy, with the Acer CPR v1.2 CD-ROM inserted in the virtual CD-ROM drive.
3. When prompted, enter "DS.AA600.001" for the image.
4. Allow Acer CPR to (re-)format the hard drive and reboot.
5. See error.

**Expected behavior**
Instead of "Not ready reading Drive E", it should show PKUnzip inflating (extracting) files from the CD-ROM drive to the hard drive.

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 21H2
 - 86Box version: v3.8, Build 4206
 - Build information: old dynarec, 32-bit, regular build

**Additional context**
This error does not occur when using a "hacked" floppy containing the generic Oak driver; however, once setup is complete, Windows won't be able to access the CD-ROM drive either, instead throwing an error about there not being enough memory. None of this occurs on real hardware.

Config file: [86box-change-to-cfg.txt](https://github.com/86Box/86Box/files/9914052/86box-change-to-cfg.txt)
Acer CPR v1.2: https://archive.org/details/acercprharddriverecoverycdversion1.21995
MTMCDAI.SYS: https://www.dropbox.com/s/v5inbd8lma9km2x/MTMCDAI.SYS?dl=0

**Comment by headsetguy37** [comment]
Apologies, the version on the Internet Archive uses MDF/MDS files, which 86Box does not currently support. I have a copy as CUE/BIN which I am uploading to my Dropbox right now; I will share them here once they're done uploading.

**Comment by headsetguy37** [comment]
BIN: https://www.dropbox.com/s/hwluodm85ebxj2c/ACER_CPR%20V1.2%20CD.BIN?dl=0
CUE: https://www.dropbox.com/s/802aot2knf8vqpa/ACER_CPR%20V1.2%20CD.CUE?dl=0

**Comment by OBattler** [comment]
But I tested it and it did work after my fix, PKUNZIP launched fine.

**Comment by OBattler** [comment]
I see what must be going on now - I have an uncommitted fix in that causes a DRQ interrupt every sector. I originally did that to make the OTI-011 Atapi 1.7 driver work on the NEC CDR-260, but it appears this needs it as well.
