### ISSUE TITLE
HWiNFO16 hangs on 808x machines

### ISSUE THREAD

**Issue by lemondrops** [86Box/86Box#2790]
**Describe the bug**
The system information utility [HWiNFO16](https://www.vogons.org/viewtopic.php?f=46&t=84804) for 808x/286 systems seems to hang on any 8088 or 8086 machine (80286 machines are not affected).

After bisecting, I have found that this issue started happening after the introduction of NEC V20/V30 CPUs with builds 4121/4122.

**To Reproduce**
1. Run HWINFO16.EXE
2. Press OK (or Enter) after the initial dialog box appears
3. HWiNFO16 hangs indefinitely; the only way out is Ctrl+Alt+Del or a hard reset

**Expected behavior**
A menu should pop up in the top left corner after pressing OK.

**Screenshots**
IBM PC XT (1986), Intel 8088 @ 4.77 MHz, 640 KB RAM, PC DOS 3.30:

![image](https://user-images.githubusercontent.com/2708460/199462790-5dbfe938-f769-414b-ac59-965d9b8fc566.png)

Victor V86P, Intel 8086 @ 10 MHz, 1 MB RAM, MS-DOS 4.01:

![image](https://user-images.githubusercontent.com/2708460/199463878-02188bed-e303-497d-aec4-6fa28ad839d6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.8 builds from 4122 onward; tested on build 4214
 - Build information: 32-bit, old dynarec, regular

**Additional context**
To aid in reproducing the bug, attached below is a zip file containing a sample machine configuration and a bootable PC DOS 3.30 360K floppy disk image containing the program; just type `HWINFO16` after going through the date/time prompts.

[86box.zip](https://github.com/86Box/86Box/files/9919352/86box.zip)

**Comment by OBattler** [comment]
This is now fixed.
