### ISSUE TITLE
Error loading libfluidsynth.dll

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2791]
**Describe the bug**
When starting any machine with MIDI Out Device: Fluidsynth, a screenshot of an error loading the libfluidsynth.dll file appears. In the folder with 86Box, the libfluidsynth64.dll file is present from the downloaded 86Box build. This bug was introduced in build 4212 and persists until the latest build. In build 4211 everything is fine.

**To Reproduce**
1. Create a machine in 86Box
2. Select your Sound Blaster sound card.
3. Select in MIDI Out Device: Fluidsynth and click OK.

**Expected behavior**
There should be no error loading libfluidsynth.dll.

**Screenshots**
![2022-11-02_143248](https://user-images.githubusercontent.com/58270614/199492841-eecedefe-2950-4c2f-85f9-1f931a86aa26.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.8.0 x64 Build 4214
Build type: regular, old recompiler.

**Comment by OBattler** [comment]
Fix committed.
