### ISSUE TITLE
Add Voodoo 8MB texture support

### ISSUE THREAD

**Issue by shitsux420** [86Box/86Box#2793]
**Is your feature request related to a problem? Please describe.**
Currently 4MB is the max texture memory (or any memory...) for Voodoo cards.

**Describe the solution you'd like**
Add support for the extra 4MB for texture memory. The 12MB V2 cards had 4MB framebuffer + 8MB texture.

**Describe alternatives you've considered**
Just being content with 8MB.

**Additional context**
Possible higher system requirements due to V2 emulation already being rather taxing even with recompiler and full render threads.

**Comment by OBattler** [comment]
This is already in - just multiply the selected texture memory times the number of TMU's. So if you select 4 MB texture memory and have two TMU's, that's going to be 8 MB texture memory total.

As such, I'm closing this with already done.
