### ISSUE TITLE
Cirrus Logic graphics card issues

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#2800]
**Describe the bug**
When emulating a machine with a Cirrus Logic graphics card, some weird graphical glitches can occur.

**To Reproduce**
1. Create a machine with a Cirrus Logic graphics card.
2. Install MS-DOS 6.22 and Windows 3.1x. Use the generic SVGA drivers (any resolution, any font size).
3. Scrolling will cause the menu in which you are scrolling to turn black, except for the very last option.
4. Moving the Program Manager windows around while there is a pattern set will cause the pattern to disappear, and will also sometimes cause the Program Manager windows themselves to turn black. You can still use it if you know where everything is, but it will be difficult.

**Expected behavior**
These graphical glitches should not occur. They do not occur on real hardware (at least not the 5434) or other brands of graphics card when using the generic SVGA drivers.

**Screenshots**
Disappearing icons:
![clgd5430_weirdness01](https://user-images.githubusercontent.com/9204574/199814822-3c223fb2-bf3b-49d0-95ee-9577c2f37ffe.JPG)

Scrolling:
![clgd5430_weirdness02](https://user-images.githubusercontent.com/9204574/199814673-ef035c4c-05d7-4034-8ac2-6c740e642eb2.JPG)

Invisible Program Manager and disappearing wallpaper:
![clgd5430_weirdness03](https://user-images.githubusercontent.com/9204574/199814927-2f1f616a-0462-41b3-b710-517edf73f695.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - 86Box version: 3.8 build 4215
 - Build information: 32-bit, old dynarec, regular build

**Additional context**
"Why don't you install the Cirrus Logic drivers?", you may ask. Because their drivers are inherently buggy and cause programs to run faster than they should (this is not an 86Box issue); plus, there's one card for which I have the drivers, but they suddenly cause the mouse to not work (probably not an 86Box issue either, but can neither confirm nor disprove because I don't have actual hardware--RYC Leopard and 5420 ISA--to test).

**Comment by TC1995** [comment]
what cirrus card is in the screenshots?

**Comment by headsetguy37** [comment]
The CL-GD5430.

**Comment by TC1995** [comment]
drivers are super vga right (from windows' setup)?

**Comment by headsetguy37** [comment]
Correct. The screenshots are Super VGA 800x600 Large Fonts, but it has happened on every Super VGA driver I've tested.

**Comment by TC1995** [comment]
256 colors?

**Comment by headsetguy37** [comment]
Yes.

**Comment by OBattler** [comment]
I actually confirm these bugs are not present on the real hardware - my real Pentium 100 back in the day had a CL-GD 5446 PCI and the Windows for Workgroups 3.11 SVGA 256 color drivers worked without problems.

**Comment by TC1995** [comment]
Ok so, this is a cpu issue because I've checked that it happens on Pentium+ cpus but not on anything earlier (be it dynarec or interpreter).
