### ISSUE TITLE
(FEATURE REQUEST) Wave Blaster-compatible Daughterboard Emulation

### ISSUE THREAD

**Issue by PeladoFeo** [86Box/86Box#282]
The most interesting devices in the title category would be:
- The original Wave Blaster.
- The Wave Blaster II.
- The Roland SCB-55.
- The Roland SCB-7.

**Comment by CRTRevivalDreamer** [comment]
There must be a way to obtain the ROMs from those modules!

**Comment by CRTRevivalDreamer** [comment]
Please don't forget the Yamaha DB50XG...

**Comment by OBattler** [comment]
I'm closing this, We have an OPL 4-based daughterboard in the 4.1 branch, the E-MU 8000 one might be do able (we already emulate that as part of the AWE32), we just need to figure out what the 68000 actually does.
