### ISSUE TITLE
IBM Xebec controller and HDD not detected on the Olivetti M24 machine

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2821]
**Describe the bug**
I created a 20MB MFM C/H/S 615/4/17 and used the Xebec controller, on the build 4231 it works fine, but on the build 4139 the MFM Xebec controller and the internal the HDD is not detected. I tried to create a new HDD but the FDISK utility included on The Olivetti DOS 3.20 and 3.30, throws an error saying "No fixed disk present"

Here is the HDD and CFG files:
HDD:
[Olivetti M24 Clock- Win103.zip](https://github.com/86Box/86Box/files/9947251/Olivetti.M24.Clock-.Win103.zip)
[Olivetti M24.zip](https://github.com/86Box/86Box/files/9947255/Olivetti.M24.zip)

**To Reproduce**
1.Boot the machine with the Xebec controler and the 20mb HDD
2. On build 4231 it works fine but on the build 4239 does not.

**Screenshots**
![Olivetti M24 HDD 002](https://user-images.githubusercontent.com/31600563/200205003-94b3878a-bea9-4caf-a36b-142d6f220ae1.png)
![Olivetti M24 HDD 001](https://user-images.githubusercontent.com/31600563/200205006-d1efd751-0b31-475a-aa16-daa5313eda0b.png)

**Desktop (please complete the following information):**
 - OS: Win 10 21H2
 - 86Box version: 3.8.04239
 - Build information: old dynarec, Win 32

**Comment by OBattler** [comment]
Yes, set the hard disk controller to Internal, as Olivetti M24 now initializes it by itself.

**Comment by Fenix770** [comment]
I have tried to create a new partition and I've done a low level format to the HDD drive C/H/S 615/4/17 with the Xebec controller using the DOS debug command. It finishes right, but for some reason it only recognizes 305 cylinders of the 615.

here is the screenshot:
![IBM Xebec partition bug 2](https://user-images.githubusercontent.com/31600563/200710530-575f3b0d-f409-4c5e-b0ce-3d3a036588b3.png)
![IBM Xebec partition bug](https://user-images.githubusercontent.com/31600563/200710541-25022b9e-e4f0-43eb-b458-51b569126589.png)

Another issue, is FDISK crash when attempting to use the WD1004A-WX1 MFM controller. And with the "internal controller" FDISK does not detect the HDD presence.

**Comment by OBattler** [comment]
You can't use an add-on hard disk controller with the M24 anymore as it conflicts with the internal one.

**Comment by OBattler** [comment]
I made the mistake - M240 was the one supposed to have the internal HDC, not M24. This is now fixed.
