### ISSUE TITLE
ATAPI HDD emulation not working properly.

### ISSUE THREAD

**Issue by kzmidze** [86Box/86Box#2826]
**Describe the bug**
ATAPI HDD emulation not working properly.
Platform: Socket 370
IDE controller: Internal controller

**To Reproduce**

**Expected behavior**

**Screenshots**
![1](https://user-images.githubusercontent.com/117635969/200328428-df7c7d4e-6eb0-45dc-b825-cd1d231e0060.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: v3.7.1 build 4032
 - Build information:

**Additional context**

**Comment by TC1995** [comment]
known issue.

**Comment by OBattler** [comment]
It's not even implemented yet. Closing with NOTABUG.
