### ISSUE TITLE
Screamer Rally crash with latest driver voodoo 2

### ISSUE THREAD

**Issue by AITUS95** [86Box/86Box#2837]
**Describe the bug**

When I try to run screamer rally with the latest voodoo 2 driver ["Voodoo 2 30202"](https://www.philscomputerlab.com/uploads/3/7/2/3/37231621/voodoo2-30202.exe) , during the intro, the emulator stops without showing any error message, I attach the video:

**To Reproduce**

https://user-images.githubusercontent.com/48457684/200939728-4c83efc4-902f-4bb8-ae3e-3499b1904e9a.mp4

**Desktop (please complete the following information):**
 - OS Windows 10
 - 86Box version 3.8 build 4253 ODR 32 bit

**Additional context**

I was able to generate a backtrace with gdb via MSYS2 at the point where it stops:

> [Thread 6548.0xdbc exited with code 0]
[New Thread 6548.0x192c]
[New Thread 6548.0x2428]
[Thread 6548.0x15ac exited with code 0]
[Thread 6548.0x213c exited with code 0]
[Thread 6548.0x1ffc exited with code 4294967295]
[Thread 6548.0x2a5c exited with code 4294967295]
[Thread 6548.0x844 exited with code 4294967295]
[Thread 6548.0x84c exited with code 4294967295]
[Thread 6548.0x6d4 exited with code 4294967295]
[Thread 6548.0x24e0 exited with code 4294967295]
[Thread 6548.0x124c exited with code 4294967295]
[Thread 6548.0x1468 exited with code 4294967295]
[Thread 6548.0x25b8 exited with code 4294967295]
[Thread 6548.0x192c exited with code 4294967295]
[Thread 6548.0x2428 exited with code 4294967295]
[Thread 6548.0x8a4 exited with code 4294967295]
[Thread 6548.0x20e8 exited with code 4294967295]
[Thread 6548.0xbdc exited with code 4294967295]
[Thread 6548.0x628 exited with code 4294967295]
[Thread 6548.0xbc4 exited with code 4294967295]
[Thread 6548.0x23e4 exited with code 4294967295]
[Thread 6548.0xa84 exited with code 4294967295]
[Thread 6548.0x22a0 exited with code 4294967295]
[Thread 6548.0x1a0 exited with code 4294967295]
[Thread 6548.0x291c exited with code 4294967295]
[Thread 6548.0x1e88 exited with code 4294967295]
[Thread 6548.0x10f4 exited with code 4294967295]
[Thread 6548.0x1640 exited with code 4294967295]
[Thread 6548.0x1234 exited with code 4294967295]
[Thread 6548.0x20c8 exited with code 4294967295]
warning: QObject::killTimer: Timers cannot be stopped from another thread
warning: QObject::~QObject: Timers cannot be stopped from another thread
[Inferior 1 (process 6548) exited with code 037777777777]

**Comment by Cacodemon345** [comment]
Could you give us the VM?

**Comment by AITUS95** [comment]
[WIN98VM](https://drive.google.com/file/d/1n66paqEtnjNGjhdIRaxI3OM4GZG5J3Cm/view?usp=share_link)

**Comment by Kappa971** [comment]
https://github.com/86Box/86Box/issues/1575#issuecomment-1692040868

**Comment by OBattler** [comment]
Closing so all the Screamer Rally issues can be tracked here: https://github.com/86Box/86Box/issues/1575 .
