### ISSUE TITLE
"Force 4:3 display ratio" is buggy

### ISSUE THREAD

**Issue by aybe** [86Box/86Box#2839]
**Describe the bug**

When you check "Force 4:3 display ratio", the output becomes stretched and only the upper half of the screen can be seen.

Setting the window scale factor back to 2x restores the display as it was previously.

**Screenshots**

Before checking "Force 4:3 display ratio":

![86Box_yXARG8eYIT](https://user-images.githubusercontent.com/1537591/201037297-acd67274-da09-4689-9be6-19c0c960e4eb.png)

After checking "Force 4:3 display ratio":

![86Box_HsVkTLv4Ig](https://user-images.githubusercontent.com/1537591/201037459-f3fbe798-9651-4c78-baae-cf873ad69b2c.png)

**Desktop:**
 - OS: Windows 10.0.19044.2130
 - 86Box version: v3.7.1 build 4032; [730af4dd5]
 - Build information: [86Box-Windows-64-b4032.zip](https://github.com/86Box/86Box/releases/download/v3.7.1/86Box-Windows-64-b4032.zip)

**Additional context**

Windows DPI setting is set to 150%.

**Comment by Cacodemon345** [comment]
Fixed.

**Comment by aybe** [comment]
Thanks! 😀
