### ISSUE TITLE
Olivetti M24 internal mouse bug.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2842]
**Describe the bug**
The internal mouse of the Olivetti M24 machine has issues under DOS. The mouse may randomly generate sounds when moved and generates characters at DOS prompt. Under Geoworks 1.2 it also emits sound at the first time configuration screen, the pointer moves slowly, and the keyboard stops responding (for example when I try to exit to DOS with the F3 key).
The mouse behaves as if it was generating keyboard signals.

**To Reproduce**
1. Start the machine.
2. At DOS prompt type GEOS
3. Follow the screen configurations until the mouse selection.

**Screenshots**
For some strange reason, the image files is 15GB in size. but the file should be 20mb only.
![Olivetti m24 mouse bug](https://user-images.githubusercontent.com/31600563/201212256-711a877a-8813-4751-b025-0d27e9d519ff.png)

CFG and HDD files:
[86box Oli-M24.zip](https://github.com/86Box/86Box/files/9984827/86box.Oli-M24.zip)

The file compressed have a size of 22mb only.
[Ollivetti M24 Clock+original HDD.zip](https://github.com/86Box/86Box/files/9984843/Ollivetti.M24.Clock%2Boriginal.HDD.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.8.0.4253
 - Build information:old dynarec, Win32

**Comment by OBattler** [comment]
That's because it does generate keyboard signals. Plus, currently, the Olivetti M24 has the wrong keyboard controller as well. I'm currently working on getting the M24 and M240 in order.

**Comment by OBattler** [comment]
Geoworks 1.2 isn't even showing the Olivetti mouse as an option.

**Comment by OBattler** [comment]
I'm closing this now as CANTFIX since I have determined that Geoworks 1.2 is simply not compatible with the Olivetti M24 - has no mouse driver of its own for it, and if using MOUSE.COM, the mouse sending keyboard scan codes confuses it, to the point that it keeps some of the scan codes queued and then output to DOS as NumPad numbers. The mouse works without problems in DW.EXE included with MOUSE.COM.
