### ISSUE TITLE
VirtualBox Ubuntu Guest mouse problem

### ISSUE THREAD

**Issue by Slo2018** [86Box/86Box#2856]
Mouse not working in Ubuntu Guest in VirtualBox but keyboard working (Intel Pentium MMX 233, Windows 95). The same problem with other machines.

**Comment by TC1995** [comment]
Are you using the PS/2 mouse?

**Comment by jriwanek** [comment]
This sounds like a problem with Virtualbox, as covered in previous issues, try running 86Box natively.

Also, in future, please fill in the template, it's there for a reason.
