### ISSUE TITLE
I have No Mouth and I must Scream no graphics

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#2857]
**Describe the bug**
Game flashes on this screen.
![Monitor_1_20221112-232513-069069](https://user-images.githubusercontent.com/68984176/201511035-d778a299-4f50-4281-abda-941a1d5e8b08.png)
Eventually in-game sound works, but didn't get very far cause no graphics other than this screen was being rendered.
**To Reproduce**
Installed from CD, used full install option. Used trio 3D/2X graphics card

**Expected behavior**
Game should start

**Desktop (please complete the following information):**
Windows 10 3.7.1 build 4032

**Additional context**
If needed, I can provide NVRAM, config and HD image

**Comment by OBattler** [comment]
I think the Trio 3D/2X may be too new for that game. Try another graphics card.

**Comment by ualaa1** [comment]
Thanks, seemed to work using a Trio64 card
