### ISSUE TITLE
(Feature Request) PB640 Motherboard Support

### ISSUE THREAD

**Issue by madonak** [86Box/86Box#287]
I'd really love to see support for this motherboard in the future, as this made up my first PC and I don't know how long the one I still have will survive - obviously if it's too much of a pain to do then don't worry about it (and if you do add it, please don't rush), but I figured "If you don't ask, you don't get!"

The best info online I've found about the board is http://www.uktsupport.co.uk/pb/mb/640.htm, but if you do need any more info, or pictures of anything specific on the board I can provide those as I have a working board here, and the last released BIOS is available for download from Vogons file library (I believe it's AMI based, with some extra OEM fields used by the system restore disks)

Thanks in advance,
Mark

**Comment by OBattler** [comment]
Unfortunately, I am unable to find the datasheets of any of those VL chips anywhere so the emulation of this motherboard is currently impossible. I'm going to post an update here if I anything turns up in the future.

**Comment by OBattler** [comment]
Looking a bit more at it, it appears to be a standard Intel Triton FX + PIIX board with PC87306 Super I/O chip and optional on-board CL-GD 5430 or 5440, with up to 2 MB video RAM. So it should be pretty easy to emulate. I'll see what I can do.

**Comment by madonak** [comment]
That's fantastic news, thank you! :)

If you need anything from the actual board (more photos/files etc) let me know and I'll grab them for you

**Comment by OBattler** [comment]
Some high-quality photos (from which I can read the writings on all the chips) would be nice so I can identify all the chips on the board with certainty, to make sure I am emulating the correct ones.
Also, if you have the files of the BIOS that comes with your specific board, or a compatible BIOS, those would be nice as well so I know I'm using the correct BIOS.

**Comment by madonak** [comment]
I'm just heading to sleep now, so I'll crack the machine open first thing in the morning and photo the entire board.

The BIOS I flashed to my physical board is here: http://vogonsdrivers.com/getfile.php?fileid=1226&menustate=0 which is the very last version that Packard Bell released

**Comment by madonak** [comment]
Pictures uploaded to https://www.dropbox.com/sh/mf00yygsvc6h7j5/AACxJ1NP2WzylUso2tnNSrD4a?dl=0

The (almost unreadable) number on the BIOS chip is PC87306-IBE/VUL with an American Megatrends copyright on it. I've also taken a photo of the ISA/PCI riser card

**Comment by OBattler** [comment]
Well, the PB640 is there now.

**Comment by madonak** [comment]
Download the latest development build and it should be in there.
