### ISSUE TITLE
An i486 (Socket 3) [OPTI 802G] IBM PC 330 (type 6573)  motherboard CMOS battery issue

### ISSUE THREAD

**Issue by TheNoob1703** [86Box/86Box#2877]
![imagen](https://user-images.githubusercontent.com/94466502/202857098-ed07100d-4741-4716-a88b-4e66e7831dd8.png)
![imagen](https://user-images.githubusercontent.com/94466502/202857119-624f055b-c5f8-440d-b45f-14694006a6cf.png)

****

Hello, when using an i486 (Socket 3) [OPTI 802G] IBM PC 330 (type 6573)  motherboard, it shows a CMOS battery problem, how can I solve it? It's still usable, but you need to skip every startup the error and it's kinda annoying

Anyway, I attach 2 screenshots for more info

Anyway, I'm using the x32 version 3.11 [build 4283] and WinBox For 86Box Launcher

**Comment by TC1995** [comment]
known issue.

**Comment by TheNoob1703** [comment]
> known issue.

Ok, if I find the thread, I'll try to find a solution
