### ISSUE TITLE
(Feature Request) VLB bus support for some 386 machines

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#288]
Hello.
I would be interesting to have some 80386 machines with VLB bus support.
I know these cards works faster with 80486 machines. 

I know the AMI 386 DX BIOS emulates an OPTI-425SX board wich supports 386DX ,486 SX, DX and DX/2 CPUs. Theoretically this board can use a 386DX +VLB video card.
Here I found a web site with information about that board.

[ http://stason.org/TULARC/pc/motherboards/D/DATAEXPERT-CORPORATION-486-OPTI-495SX.html](url)

But in a game I tested (Hocus Pocusfrom 1994, it uses a 320x200x256 resolution)  in PCEM, I discovered that Trident 8900 ISA is too slow when there are several enemies and takes several secons to load each level.
On the other hand the ATI mach 64 on ISA takes much less to load and there is no slowdowns during gameplay.
With S3 Qvision864 VLB each level load instantly.

**Comment by OBattler** [comment]
This has been done for some time now. I think it's time to close this issue.
