### ISSUE TITLE
The mouse type is not detected  correctly on the Olivetti M240 under MS-DOS

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2880]
**Describe the bug**
I created a fresh installation on the M240 machine, all seems to work fine but, the standard serial mouse is not detected by microsoft Mouse driver ver 7.04. The Naksha mouse driver detects a several mouse types and detects it as Mouse System Mouse, but it does not work under Norton Commander 2.0.
In this new virtual machine I installed DOS 4.01 and created a 76mb HDD with the internal controller.

Here is the CFG and HDD image file:
The HDD has DOS 4.01, Norton Commander 2.0 on the NC directory and the Naksha Mouse driver (MOUSE.COM) on the root directory.
[Olivetti M240 DOS 401.zip](https://github.com/86Box/86Box/files/10048108/Olivetti.M240.DOS.401.zip)
[Olivetti M240 DOS 4.01.zip](https://github.com/86Box/86Box/files/10048110/Olivetti.M240.DOS.4.01.zip)

**To Reproduce**
1. Configure the machine with a standard microsoft serial mouse
2. Boot DOS and type MOUSE at DOS prompt
3. The mouse is incorrectly detected as Mouse System Mouse
4. change directory to NC, type NC to start Norton commander
5. The Mouse cursor is present but does not responds

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - 86Box version: 3.11.0.4282
 - Build informationold dynarec, Win32

**Comment by Fenix770** [comment]
PD: I installed Windows 2.03. I configured it to use the microsoft serial mouse, but does not work either.

**Comment by jester-xbmc** [comment]
Hi, suggestion, the M240 came with a bus mouse, if you set it to logitec/microsoft bus mouse it works fine

**Comment by Fenix770** [comment]
The Logitec/Microsoft bus seems to work, but I must load the mouse driver *after* starting Norton Commander 2.0 otherwise the machine crash.

**Comment by Fenix770** [comment]
PD: I found another bug, the machine  throws an error reading drive C. I suspect it got confused whn I created the extended partitions on Olivetti DOs 3.30
![Error reading drive C ](https://user-images.githubusercontent.com/31600563/202911587-cf77d02c-cc87-4a01-ba79-c2ba0557d53a.png)

**Comment by jester-xbmc** [comment]
Try changing the IRQ of the mouse to 2

**Comment by Fenix770** [comment]
I tried with IRQ 2 the mouse pointer can be seen. The drive C error maybe  because  the HDD controller uses the IRQ 5. But before the recent changes the standard Microsoft serial mouse worked just fine.

**Comment by OBattler** [comment]
> But before the recent changes the standard Microsoft serial mouse worked just fine.

But I haven't changed anything regarding serial, so I'm not exactly sure how that broke. Or wait... I did make one change that I forgot to revert, I believe let me check.

**Comment by OBattler** [comment]
The Logitech MOUSE.COM driver detects the Microsoft Serial Mouse just fine on the M240, and it even works in Norton Commander. The mouse is on COM1.

**Comment by OBattler** [comment]
On the specific VM uploaded, I can't boot from the hard disk - despite the fact it's mounted, it's not seen at all by the BIOS.

**Comment by OBattler** [comment]
Well, it turns out I've been using the wrong executable.

**Comment by Fenix770** [comment]
Can upload that mouse driver. Mine as issues.

**Comment by Fenix770** [comment]
I can confirm that works with Logitec BUS Mouse and Logitec 4.0 DOS driver. So is working now, I think it may br not compatible with the serial mouse, because if I use the Logictec serial mouse the driver complains that the mouse does not responds.

**Comment by OBattler** [comment]
I found the real why the serial mouse doesn't work - internal mouse was always overriding it.
