### ISSUE TITLE
Please consider adding a "use folder" feature to the 86box zip drive

### ISSUE THREAD

**Issue by HanHeld** [86Box/86Box#2888]
**Is your feature request related to a problem? Please describe.**
The problem this is related to is this: copying data in and out of 86box virtual machines. 

Currently most of the solutions currently require a network and due to protocol drift (eg modern ftp vs 90's ftp, samba v1 being disabled on modern clients) are not tenable. Alternate ones I'm aware of (mounting a local folder as an iso) only work one-way.

**Describe the solution you'd like**
I would like to be able mount a folder read-write as an zip drive and have 86box see it as a zip 100 disk I can then copy items back and forth to/from.
(NT 4.0 can see iomega zip 100 drives, but doesn't appear to be able to see 250 drives.)

Zip is standard (enough), DOS (with drivers) and NT can both see them. I'm not sure what operating systems can see MO drives natively so it wouldn't be my first choice.

Of course if you can add this feature

**Describe alternatives you've considered**
Alternate workarounds I've considered and tried to address data transfer are:
1)creating and storing zdi (zip drive) archives for different configurations
2)using iso files to copy data into 86box
3)setting up ftp and SMB servers to copy data in and out -I have not had success with that to any degree.

**Additional context**
Do you mean complications?

- A downside may be that people will want this feature added to MO drives as well. I'm not aware of any problems with that but that doesn't mean there would be no problems.
- I don't program so I don't know if there would be any "gotchas" to making the host folder read/write or not. That should probably be looked for and explored. 
- You might want to check to see if the folder is in use by another instance of 86box or not. I'm not sure what the standard way to do that programmatically would be.
- If an instance locks/claims a host folder and then crashes that may cause a problem for later 86box instances when they try to read it. If possible, a way to check for other running 86box instances and then clear the folder when none are found would be a good thing.

**I'm on discord and happy to answer developer questions in the 86box or 86box-support channels**

**Comment by OBattler** [comment]
This is another "can't implement" since, as RichardG explained last night, there's too many complications when it comes to a writable file system. Even QEMU's VVFAT has problems.
