### ISSUE TITLE
86Box won't recognize hard disk. HELP!

### ISSUE THREAD

**Issue by turboboy215** [86Box/86Box#289]
With a previous build of 86Box, I was able to install Windows 98 SE on it (with some issues). But now I can't even get past the start. It just won't recognize my hard disk (when I try to use a boot disk, it says "No fixed disks present."). 
I've tried messing around with the settings, and I've tried using IDE and SCSI, but neither work. I've even tried changing the settings with the hard disk controller to no avail.

I checked my settings against the previous version of 86Box I was using and found that I was using IDE(PIO+DMA), which works, but there's no option for it in the latest version. I've tried every single type of bus and channel in the current version, and it still won't work.

 What is the equivalent to using IDE(PIO+DMA) in the latest version, and more importantly, how can I get this thing to actually RECOGNIZE my hard disk?

I have attached my configuration below.
[86box.zip](https://github.com/86Box/86Box/files/2065508/86box.zip)

**Comment by OBattler** [comment]
The equivalent in the current version of 86Box is simply IDE.

**Comment by OBattler** [comment]
Looking at your config, you have the XTIDE controller set on the 430VX PCI which already has integrated IDE, and the hard disk type is set to ESDI. Set the controller to None (which will make it use the integrated PIIX3 PCI IDE controller) and the hard disk type to IDE.

**Comment by OBattler** [comment]
This should work: https://pastebin.com/c7rVK57g .

**Comment by OBattler** [comment]
Edit: Fixed the CD-ROM IDE channel: https://pastebin.com/63qUtNVK . Channel 2:0 is tertiary master, so it won't work unless you enable the tertiary IDE controller and configure Windows 98 SE to use it.

**Comment by OBattler** [comment]
Oh, you actually do have the tertiary IDE controller configured. Then my first link will do.

**Comment by OBattler** [comment]
I'm going to close this issue because I haven't heard from the user since June. If the user comes back, I will reopen this.
