### ISSUE TITLE
Slot 1 3DMark 99 Max emulator crash

### ISSUE THREAD

**Issue by Slo2018** [86Box/86Box#2891]
![Posnetek zaslona 2022-11-23 042544](https://user-images.githubusercontent.com/45156187/203463897-68ef165d-7a80-4824-868e-808513d9cdb6.png)
Emulator always crash when i start 3DMark 99 Max on Slot 1 Intel Celeron (ABIT BF6).

**Comment by TC1995** [comment]
more details please?

**Comment by Slo2018** [comment]
I got this error then 86Box crash.

**Comment by jriwanek** [comment]
What TC means, is things like what version of 86box, what host system, and... well, all the other things we asked for in the template which you removed.

**Comment by Slo2018** [comment]
I'm using latest 86Box in WinBox for 86Box.

Host:

Windows 11
Intel 13th Gen Raptor Lake

**Comment by jriwanek** [comment]
Latest stable, latest development?

**Comment by Slo2018** [comment]
v3.11.0.4300

**Comment by jriwanek** [comment]
Do you get the same issue with other Voodoo 3 3500's?

**Comment by Slo2018** [comment]
Yes.

**Comment by jriwanek** [comment]
Alrighties, thankies, looks like we've got even more work to do on the Voodoo 3.

**Comment by Cacodemon345** [comment]
That register is undocumented.

**Comment by JimboMumbo** [comment]
It was surprisingly identified as Intel Celeron instead of Pentium II. 😞

**Comment by Korkman** [comment]
Can confirm the crash. I guess the register access is already pointing straight to the problem, but I'll add my details anyways:

* host AMD 5900X with Windows 10
* guest Slot 1 PII Klamath @ 166 MHz and Voodoo3 3500 SE
* emu build 4311

Log says:
`Bad CMDFIFO packet 0000011e 0002f320
`

**Comment by Korkman** [comment]
The Voodoo3 3000 PCI does not crash, but produces this:
![grafik](https://user-images.githubusercontent.com/3186931/204331853-757f5970-049d-4ebf-bc32-78df189fea28.png)

**Comment by JimboMumbo** [comment]
> The Voodoo3 3000 PCI does not crash, but produces this: ![grafik](https://user-images.githubusercontent.com/3186931/204331853-757f5970-049d-4ebf-bc32-78df189fea28.png)

This is terribly worse than textures not being colored correctly at Final Reality.

**Comment by Korkman** [comment]
I'll retest with some alternative drivers. The initial result is with Voodoolizer, I'll try official drivers next

**Comment by Korkman** [comment]
Same with official driver (this is the first test in 3DMark 99 Max)
![grafik](https://user-images.githubusercontent.com/3186931/204340164-bd9634a7-241b-4fd7-ac44-1fd576ad6c8d.png)

Disabling recompiler fixed the issue
![grafik](https://user-images.githubusercontent.com/3186931/204340586-242ac77e-15d5-45fb-9f08-5e70e88afcdf.png)

**Comment by JimboMumbo** [comment]
Oh. I'll disable recompiler for new 98 machine right after that

**Comment by Korkman** [comment]
The visual corruption with enabled recompiler was caused by the 64-bit release of 86box. 32-bit runs fine. This was mentioned in a [different issue](https://github.com/86Box/86Box/issues/1137#issuecomment-1312584076). I'll formalize the graphics corruption in a new issue so it is easier to track and reference. It is not related to the crash which this issue should be about.

**Comment by Korkman** [comment]
I cannot reproduce the crash anymore. My guest setup now is:
- Build 4311 x86 (32 bit)
- Voodoo 3 2000 AGP, Slot 1 PII Klamath @ 233 MHz
- Windows 98 SE, Voodoolizer 1.05 / Amigamerlin 2.9 drivers
(I have been switching Voodoo cards and drivers all day, so I can't tell what exactly in my guest caused the crash, but a driver component might be the culprit - I'll try grab a VM image from my backups)

**Comment by Flo9696** [comment]
For me it works when I set Voodoo 3 3000 PCI, but when I set it to AGP, 86Box crash when I start 3DMark 99 - 2001

This happens both on Win 98 and ME

**Comment by Korkman** [comment]
OK I can reproduce now by using the original 3dfx drivers (dll files from 1999-11-23). Unfortunately I have no original hardware anymore to tell, but a real system might have crashed as well in 3DMark 99 Max.

Here's the workaround / fix. _**Properly**_ install either Voodoolizer or Amigamerlin patched drivers (I tested those), both of which can be obtained at the excellent [Vogons Vintage Driver Library](http://vogonsdrivers.com/index.php?catid=12).

Properly installing means either starting from a fresh Windows install or - when in doubt - using the device manager to replace the original driver (read the dialogues carefully, you _don't want to keep_ any glide or 3dfx dlls, but you do want to keep msvcrt dlls, or other unrelated dlls).

I guess my initial install was incomplete (I didn't replace the driver with device manager).

And don't forget to install the included 3dfx tools as well :-)

**Comment by Korkman** [comment]
The Voodoo3 3500TV AGP with the original drivers 1.07 (DLL files as recent as 2000-10-31), available from the Vogons, doesn't crash either. So it boils down to old drivers having bugs, I guess.

**Comment by JimboMumbo** [comment]
![image](https://user-images.githubusercontent.com/96022772/207957747-a26b3c12-862e-4b37-a496-6c97995d9f29.png)
Ack! here goes white textures just like Laguna3D 😞

**Comment by OBattler** [comment]
I guess this can be closed since it has been determined to be buggy drivers.
