### ISSUE TITLE
Add the "Pivot" feature

### ISSUE THREAD

**Issue by Egg-Of-Glory999** [86Box/86Box#2894]
I have a virtual machine using the Radius SVGA Multiview video card and Windows 3.0. The video card combined with the monitor can "pivot," for example, Windows 3.1 with 800x600 w/ 32,768 colors using the Radius SVGA Multiview. When you "pivot" the monitor, now it becomes 600x800 w/ 32,768 colors. I think this would be useful for the Radius SVGA Multiview.

One solution could be when using the Radius SVGA Multiview, it could simulate the use of the Radius Pivot display, and there would be an option to pivot the display when using that card. It would most likely be in the tools drop down menu, below "Sound gain," but also above "Preferences..."

Screenshot is just below...

![Screenshot_20221125_115407](https://user-images.githubusercontent.com/114437933/204049991-18b028d8-0126-491c-9647-bc6645ab50e4.png)
86Box with the pivoted display, supposed to be 768x1024 w/ 256 colors, but it's just a weird sideways 1024x768.

**Comment by dhrdlicka** [comment]
Is there any documentation for the pivoting feature regarding how the display communicated with the adapter?

**Comment by Egg-Of-Glory999** [comment]
I mean, this could explain it well...
https://youtu.be/CKf7Oc60fVM?t=900

**Comment by dhrdlicka** [comment]
No, I mean an actual datasheet that shows how this works on the driver/electrical level.

**Comment by Egg-Of-Glory999** [comment]
I mean, I am trying to find something related to that, but with essentially
nothing other than that video, although the best piece of information I can
tell you is that both the graphics card and the monitor worked together in
a way with some kind of mercury switch that would send a signal back to the
computer, telling it to flip the entire screen to portrait mode or back to
landscape mode, at which point, would fade out, then when it fades back in,
shows the pivoted screen, which works fine on real hardware, but well...I
think we all know what happens on 86Box. Its refresh rates are Horizontal -
107Hz & Vertical - 75Hz. To be honest, I could find essentially nothing on
Bing. Results were *slightly* better with Google, but still essentially
nothing.

**Comment by OBattler** [comment]
Closing with a "Can't do" because I have no way of knowing which register is responsible for the pivot mode.
