### ISSUE TITLE
Darwin/x86 1.41 doesn't boot on 440BX or any other motherboard.

### ISSUE THREAD

**Issue by Gogo268** [86Box/86Box#2897]
**Describe the bug**
The screenshot is pretty much self explanatory, it looks for the files to boot to which is on the CD, and never does resulting in this loop.

**To Reproduce**
1. Start 86Box and configure a 440BX motherboard.
2. Boot to the CD

**Expected behavior**
Darwin to boot to the installer.

**Screenshots**
![Monitor_1_20221126-154618-676676](https://user-images.githubusercontent.com/37984199/204108867-8c232bd9-670e-47e5-9031-32bc3da2384b.png)

**Desktop (please complete the following information):**
 - OS: Win10 21H2 x64
 - 86Box Ver: 3.11 Build 4294, old dynarec x86

**Additional context**
the 440BX chipset was officially tested and documented to work according to the install notes txt file on the CD.
This can also be reproduced in PCem.

**Comment by OBattler** [comment]
The chipset may have been tested, but have ATA-3 and ATA-4 drives (which we emulate) been tested as well? It is very likely they have only tested it on more recent drives. RichardG went and debugged this issue and it behaves strangely - I suspect it may require support for overlapping commands or something. In any case, it's a CANTFIX.
