### ISSUE TITLE
86Box crashes when BeOS 4.0 attempts to restart

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#2903]
**Describe the bug**
86Box crashes when BeOS 4.0 attempts to restart the computer

**To Reproduce**
1. Boot BeOS 4.0 from the installation media
2. Install BeOS 4.0
3. BeOS will try to reboot the computer after the installation completes
4. Notice that 86Box crashes ("86Box has stopped working" on Windows, segmentation fault on Linux)

**Expected behavior**
The emulated machine should reboot successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1 (also tested on Gentoo Linux)
 - 86Box version: v3.11 build 4311
 - Build information: Stable x86 - old dynarec

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

BeOS 3.1 is also affected by this bug. The OS will boot up successfully when 86Box is started again and only a reboot causes this (shutting down from within the OS doesn't cause this unless you click on the "reboot" button on the shutdown dialog.)

Config file: 
[86box_config.zip](https://github.com/86Box/86Box/files/10117642/86box_config.zip)

**Comment by cold-brewed** [comment]
I was unable to reproduce this on macOS arm64 which uses the new dynarec. It's possible that this is an old dynarec issue.

Could you retry with a new dynarec build?

**Comment by win2kgamer** [comment]
Just tried with a new dynarec build of 4311 and the crash does not occur.

**Comment by OBattler** [comment]
Try old dynarec again on the latest 86Box build and see if it still happens.

**Comment by win2kgamer** [comment]
The crash still occurs in build 4663.

**Comment by OBattler** [comment]
Try and see if this still happens.

**Comment by win2kgamer** [comment]
The crash still occurs in build 4929.

**Comment by OBattler** [comment]
Try again on the latest build please.

**Comment by win2kgamer** [comment]
Still occurs in build 5573 when using the old recompiler. When using the new recompiler the machine reboots without crashing 86Box.

**Comment by OBattler** [comment]
Can you upload the VM?

**Comment by win2kgamer** [comment]
Uploaded my current test VM to the FTP

**Comment by OBattler** [comment]
I see it doing a TRC reset and then it goes awry somewhere in between.

**Comment by OBattler** [comment]
So if I restart with the dynamic recompiler forced disabled by manually setting cpu_use_dynarec to 0 in the configuration file, I get this:
![imagem](https://github.com/86Box/86Box/assets/10365853/d2b13d14-bccd-4c21-a0a4-1f6a878bd26c)
.
So something is clearly being reset incorrectly.
