### ISSUE TITLE
4:3 Aspect Ratio is not preserved when the 86Box window is initially maximized

### ISSUE THREAD

**Issue by Agetian** [86Box/86Box#2921]
**Describe the bug**
If the Force 4:3 display ratio mode is set and "Apply fullscreen stretch when maximized" option is enabled, if the 86Box window is configured to be maximized at start (e.g. "Remember Size & Position" is on and the window is maximized), once you restart 86Box, the screen will be stretched instead of forced to 4:3.

**To Reproduce**
1. Enable "Force 4:3 Display Ratio", "Apply fullscreen stretch when maximized" and "Remember size & position" options, set fullscreen stretch to 4:3.
2. Maximize the 86Box window. Make sure the 4:3 display ratio is correct (it will be).
3. Restart 86Box.
4. All the options are still enabled, but fullscreen stretch will not be obeyed until you re-maximize the window manually.

**Expected behavior**
4:3 display ratio should be preserved across restarts.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.0
 - 86Box version: v3.11
 - Build information: x86-64, the official build.

**Comment by dhrdlicka** [comment]
The issue there appears to be that 86Box does not actually save the window state, so it sets up a window that does indeed have the dimensions of a maximized window, but is not actually maximized.

**Comment by nickkeane** [comment]
I'm getting the same issue, except using Square Pixel instead of 4:3.

**Comment by OBattler** [comment]
@nickkeane The latter is not a bug - when the window is in resizable mode, guest-triggered resizes are ignored.

**Comment by OBattler** [comment]
OK, it actually no longer seems to happen.
