### ISSUE TITLE
Voodoo 2/3: glitches at 4 render threads

### ISSUE THREAD

**Issue by Korkman** [86Box/86Box#2924]
With 4 render threads, glitches will occur in some 3D accelerated applications. With the default 2 render threads, these were not observed. Disabling the Voodoo recompiler at 4 threads reduces the artifacts, but they are still present.

**To Reproduce**
For example, Need for Speed 3 & 4 show artifacts in their menus and in-game.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3186931/205077456-4b0f6bf6-d80b-4e88-ab1b-75b2b090d7b0.png)

**Host**
 - Windows 10, 11
 - 86Box build 4311, 5605
 - Build information: Tested with 32 bit and 64 bit releases
 - AMD 5900X

**Guest**
 - Slot 1, i440BX ASUS P3B-F
 - PII Klamath, 233 MHz / Cyrix III 450 MHz
 - Tested with Voodoo2 and Voodoo3 2000

**Comment by JimboMumbo** [comment]
Maybe disabling recompiler would solve the artifacts problem?

**Comment by Korkman** [comment]
@JimboMumbo That's why the issue says "recompiler glitches" 😉

**Comment by Korkman** [comment]
Update: I have only observed these glitches in NFS titles, and they are subtle in-game, so much so that I'd still recommend using 4 render threads over 2 for the performance benefit outweighs the glitch. This may actually be a game engine bug only observable when performance exceeds a certain limit. No idea if this occurred on real hardware.

**Comment by wishusknight** [comment]
this doesnt seem to happen on my p2 450 that has voodoo2 sli and dell branded Seattle BX mainboard. At least not that i noticed. But oddly it has an issue with my P3S 1400 and v3-2000 but the glitching is slightly different. Video card is pci and mainboard is using the 815ept chipset. 

This is real hardware btw.

**Comment by OBattler** [comment]
Does this still occur?

**Comment by Korkman** [comment]
Yes, with build 5605 in both 64 and 32 bit. While testing I noticed the artifacts also occur with recompiler disabled. So it really boils down to 4 threads vs. 2 threads. I'll edit the issue accordingly.

**Comment by Korkman** [comment]
Here's NFS3. The comb artifact flickers on specific surfaces. As before, with 2 render threads, no artifacts.
![grafik](https://github.com/86Box/86Box/assets/3186931/4346ee4d-37a4-4584-a5d3-cee62e67b683)

**Comment by NightSprinter** [comment]
I can say I notice this on real Voodoo2 hardware as well.  Usually reducing the overall gamma of the V2 can make that go away.  See if changing that in the card's control panel has any effect.  If 86box is that accurate, it may also be emulating the high gamma artifacting as well.

**Comment by OBattler** [comment]
Closing because it's being tracked in #4483 .
