### ISSUE TITLE
BIOS POST screen and speaker beeps too fast

### ISSUE THREAD

**Issue by MX9000** [86Box/86Box#2928]
**Describe the bug**
I tested some 486 and Pentium configurations and it seems that the BIOS POST is displayed too quickly and the start-up beep is too short: the issue is more noticeable as the CPU speed increases. With a 486 processor up to 33 or 66 Mhz the issue only occurs during boot and in DOS the beeps are audible (e.g. floppy change request message during MS-DOS 6 installation or BEEP Basic command in QBasic). With a 486 processor at 75/100 Mhz or Pentium the speaker emits only a faint pop.
Is this related to the issues 'PIT: add alternative faster PIT #2501' or 'Processor clock speed is modifed after soft reboot #2642'?

**To Reproduce**
Test a slow machine (486 up to 33 Mhz) and then compare with a faster one (486 100 Mhz or Pentium).
I tried both with the dynamic recompiler on and off.

**Expected behavior**
If I remember correctly, the POST phase on real hardware was slower especially the ticking during the RAM check.
The duration of the beeps emitted by the speaker should not be affected by the speed of the CPU.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - 86Box version: v3.11 build 4311
 - Build information: 32 bit (86Box-Windows-32-b4311.zip)

**Comment by OBattler** [comment]
I'm closing this with CANTFIX - it would require a complete rethink of the dynamic recompiler, which is currently not feasible.
