### ISSUE TITLE
Fonts render incorrectly in XFree86 3.1.x when an S3 Trio or Vision864 is selected

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#2932]
**Describe the bug**
When using XFree86 3.1.1 or 3.1.2 with an emulated system that uses an S3 Trio or Vision864 for graphics some fonts are rendered incorrectly

**To Reproduce**
1. Set up a machine using an S3 Vision864 or Trio64 for graphics
2. Install a Linux distro that uses XFree86 3.1.1 or 3.1.2 (I used Red Hat Linux 2.1 for this)
3. Start X11
4. Notice that some fonts are rendered incorrectly

**Expected behavior**
Fonts should render correctly

**Screenshots**
![Monitor_1_20221203-151142-433433](https://user-images.githubusercontent.com/47463859/205462469-ee2ab5be-11de-4206-b0c6-2c27f826f30e.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 x64 SP1
 - 86Box version: 3.11 build 4319
 - Build information: Stable x86 - old dynarec

**Additional context**
Does not occur in PCem v17.
[86box-config.zip](https://github.com/86Box/86Box/files/10147397/86box-config.zip)
VM hard disk has been uploaded to the 86Box FTP

To reproduce using the VM log in as root (no password) and run "startx"

**Comment by TC1995** [comment]
nvr of this?

**Comment by win2kgamer** [comment]
nvr files: 
[nvr.zip](https://github.com/86Box/86Box/files/10148912/nvr.zip)

**Comment by TC1995** [comment]
anyway, I've fixed this in time.
