### ISSUE TITLE
Buttons and virtual screen off to the right in GNOME

### ISSUE THREAD

**Issue by IDeletedSystem64** [86Box/86Box#2933]
**Describe the bug**
On GNOME (and maybe other GTK based DE's?) the buttons and virtual screen are shifting to the right, and items in menus are barely displayed 

**To Reproduce**
1. Run 86Box on GNOME (affects both X11 and Wayland)
2. The screen, menu items and button icons are shifting to the right
 
**Expected behavior**
Items and screen display correctly 

**Screenshots**
![image](https://user-images.githubusercontent.com/47640864/205463691-ea03d686-8a02-4900-8c9c-8095db31a66f.png)
![image](https://user-images.githubusercontent.com/47640864/205463696-e10121a4-aa1d-4e50-9e34-a0d6751894a7.png)
![image](https://user-images.githubusercontent.com/47640864/205463704-bc7e3774-a6a4-461c-9dc6-02ca898dae1b.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - 86Box version: v3.11 Build 4311
 - Build information: old dynarec, x86, stable

**Comment by Cacodemon345** [comment]
This appears to be a Qt bug more than anything else.

**Comment by OBattler** [comment]
You can always install a VM with Arch Linux and Gnome to reproduce it.

**Comment by OBattler** [comment]
It appears to be a Qt bug. Try compiling with Qt 6 instead of Qt 5 to see if that also has the bug. Other than that, this is a CANTFIX because it's not a bug on our side.
