### ISSUE TITLE
Compaq Portable Memory Error

### ISSUE THREAD

**Issue by PechayClub** [86Box/86Box#2935]
**Describe the bug**
When you use Compaq Diagnostics to setup a Compaq Portable III VM. It shows a memory error.

**To Reproduce**
1. Boot up MS-DOS
2. Insert the disk with Compaq Diagnostics.
3. Run Compaq Diagnostics.
4. See error.

**Expected behavior**
There should not be a memory error.

**Screenshots**
![Screenshot_20221204_042915](https://user-images.githubusercontent.com/65995040/205481326-62be5968-4a5e-4283-a65d-cc797d111d39.png)

**Desktop (please complete the following information):**
 - Windows 11 Insider Dev
 - 86Box version: 3.11.0 Build 4319
 - Build information: New NDR x64

**Comment by TC1995** [comment]
Well, how much memory have you set?

**Comment by planetbrian** [comment]
According to the PCem > 86Box porting guide, the Compaq Portable 386 is currently being emulated as a Compaq Deskpro 386/20 (evident using the archive.org diagnostic disk). Both models utilize a unique 32-bit bus for memory, which probably isn't implemented in the codebase yet. There might be schematics for that bus in a PDF somewhere, but the memory should work nonetheless in the VM.

**Comment by OBattler** [comment]
If this was with the Compaq Portable III 386 - I have recently implemented the Compaq Deskpro/Portable memory control, so this should now work.
