### ISSUE TITLE
XTIDE fails to boot from HDD on XT-class machines with NEC V20/V30

### ISSUE THREAD

**Issue by lemondrops** [86Box/86Box#2939]
**Describe the bug**
XTIDE fails to boot from the hard drive on any 8088/8086 machine with the NEC V20/V30 selected. Only booting is affected - using the disk after booting from floppy works perfectly.

Reproducible with both r622 (current in the ROM set) and r624 (latest) versions of the XTIDE BIOS; both the regular XT and the V20/V30/80186/80188-specific version (ide_xtp.bin) are affected.

Bisecting has shown that this issue has first appeared in the **build 4147** with the commit e6321d952a77162daedc059f250cb461b780466d.

Tested with:
* IBM XT (1986) - **Error 40h**;
* AMI XT clone - **Error 40h**;
* Compaq Portable - **no error displayed, just skips**;
* Super PC/Turbo XT - **no error displayed, just skips**;
* Xi8088 - **Error 1h**;
* Amstrad PC1512 - **Error 1h**;
* Olivetti M24 - **Error 1h**.

**To Reproduce**
1. Select any 8088 or 8086 machine;
2. Select *PC/XT XTIDE* as the hard drive controller;
3. Attach a HDD with an OS installed to IDE (0:0);
4. Start the machine, wait for XTIDE and observe the error

**Expected behavior**
XTIDE successfully booting off a HDD.

**Screenshots**
![image](https://user-images.githubusercontent.com/2708460/205501988-dedcb05e-227e-4a9d-a346-cf36f3a60751.png)

![build4562](https://user-images.githubusercontent.com/2708460/233272399-4caf242e-2816-4ee7-a826-cd92aa5340f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.11 builds 4311 and 4320
 - Build information: old dynarec, 32-bit, regular

**Additional context**
To help reproduce the problem, a config file (using the IBM XT 1986), a bootable HDD, and prepared ROMs of the r624 version of the XTIDE BIOS are included in the archive below: 

[xtide.zip](https://github.com/86Box/86Box/files/10148985/xtide.zip)

**Comment by OBattler** [comment]
Are we sure it's even supposed to work?

**Comment by lemondrops** [comment]
Why wouldn't it? Besides, the project even provides a special version of the ROM that explicitly targets V20/V30, which also fails.

**Comment by jvernet** [comment]
Yes, it work on my real 1512 (V20) and Tandy1000 (V30)

**Comment by lemondrops** [comment]
Okay, I've managed to "fix" it myself by reverting the change to the AAM (and only AAM) opcode implementation in the commit e6321d952, reintroducing Intel 808x's (undocumented) behavior on NEC CPUs. This allows both for XTIDE to boot from HDDs *and* for the Xi8088 to recognize the CPU as V20, since it only checks the AAD opcode's behavior to determine the CPU.

However, I fully admit that this is probably just a hack not representative of real hardware, so I think verification of how these instructions behave on a real NEC CPU is warranted.

**Comment by OBattler** [comment]
I only just noticed this... I'm going to have to look at AAM here.

**Comment by OBattler** [comment]
I found this interesting file: https://gist.github.com/TomHarte/f9c89349f676ebbe5bc92e52af77b0a1 that documents x86 instruction bugs and quirks. It has the "variant does not work on NEC's V series" note for AAD but not AAM, which implies NEC implemented the variant for AAM but not AAD, matching your observation, as well as jvernet's of XTIDE working fine on a real Vx0.
