### ISSUE TITLE
OpenBSD 2.3 fails to boot when an ATAPI CD-ROM is present

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#2942]
**Describe the bug**
OpenBSD 2.3 detects a phantom ST-506 hard disk during boot and gets stuck in a loop attempting to reset it.

**To Reproduce**
1. Create a machine with an ATAPI CD-ROM as secondary master (1:0)
2. Attempt to boot OpenBSD 2.3 from the boot floppy
3. Notice that a nonexistent ST-506 disk is detected (wd1 at wdc1 drive 0)
4. Notice that repeated "wd1: wdccontrol: recal failed" messages are printed to the console and the OS never finishes booting

**Expected behavior**
The phantom disk shouldn't be detected and the OS should boot

**Screenshots**
![Monitor_1_20221204-140128-275275](https://user-images.githubusercontent.com/47463859/205512842-104e3acd-98b7-493f-aff5-721bd51d1068.png)
![Monitor_1_20221204-140354-069069](https://user-images.githubusercontent.com/47463859/205512847-68133275-3ab5-4f9f-901c-c44088ee98a5.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 x64 SP1
 - 86Box version: v3.11 build 4319
 - Build information: x86 - old dynarec

**Additional context**
I tested this disk on a real Pentium system and the issue does not occur. Removing the ATAPI CD-ROM prevents this issue from occurring in 86Box.
86Box config file: [86box-config.zip](https://github.com/86Box/86Box/files/10149360/86box-config.zip)
Boot floppy used: [FLOPPY23.zip](https://github.com/86Box/86Box/files/10149361/FLOPPY23.zip)
nvr files: [nvr.zip](https://github.com/86Box/86Box/files/10149364/nvr.zip)

**Comment by TC1995** [comment]
Did this happen before my atapi fix?

**Comment by win2kgamer** [comment]
@TC1995 I tried 86Box 3.11 (build 4311) and 3.7.1 (build 4032)  - it occurs in both prior stable releases.

**Comment by TC1995** [comment]
Hmm, check if it happens on pcem or on even earlier builds of 86box.

**Comment by win2kgamer** [comment]
The same issue occurs in PCem v17 and 86Box 3.0 and I've tried the following other Pentium boards in 86Box build 4319:
- [VIA VPX] FIC VA-502 (Socket 7 dual voltage)
- [i430FX] Acer V30 (Socket 5)
- [SiS 501] ASUS PCI/I-P54SP4 (Socket 5)
- [SiS 471] ASUS VL/I-486SV2G (i486 Socket 3)

**Comment by OBattler** [comment]
WD1 on WDC1 appears to be secondary slave - for some reason, OpenBSD thinks that's present even though it's not.

**Comment by OBattler** [comment]
This is now fixed: 
![imagem](https://github.com/86Box/86Box/assets/10365853/422381b5-fe35-4dbb-852f-7b8ea96ffe2e)
. Therefore, this can be now be closed.
