### ISSUE TITLE
Brazilian keyboard with wrong mappings on Linux build

### ISSUE THREAD

**Issue by rmorette** [86Box/86Box#2945]
**Describe the bug**
The Brazilian ABNT2 keyboard is not being mapped correctly on AT machines under 86Box 3.11 build 4311 for Linux. I confirmed that is working properly on the Windows version.

**To Reproduce**
Boot an Award 486 clone with MS-DOS 6.22 (tried with Mylex MVI486 and MR BIOS 286 clone as well).

-Backslash key will be mapped as Slash
-Slash key is mapped as Backslash
-Dot key on the numeric keyboard is not mapped

Now load the keyboard driver:
C:\> keyb br,,c:\dos\keybrd2.sys /id:275

-Backslash key get remapped to Semicolon
-Slash key keeps mapped to Backslash
-Numeric Dot key still not mapped

**Expected behavior**
-Backslash key not mapped as slash without a keyboard driver, neither remapped after loading it.
-Slash and numeric Dot keys are not be mapped until KEYB is loaded since they are extra keys specific of the ABNT2 layout.

**Desktop (please complete the following information):**
 - OS: Debian 11 GNOME/X11 (host) / Windows 10 (under VirtualBox 7)
 - 86Box version: 3.11 build 4311
 - Build information: The official release builds available to download on github

**Additional context**
I initially suspected that could be related to QT mapping something wrong, but the keyboard is proper mapped on the settings window.
I also tried to run it on a Fedora 37 VM and build the sources locally on my host but had the same problem.

**Comment by OBattler** [comment]
I"m afraid this is a CANTFIX - on Linux, we use X11 input for Keyboard, which does not give us scan codes but ASCII codes of the character produced by the key, and there's no way to accurately infer the actual key from that. Our current mapping are based on the English (US) keyboard layout. The only solution would be to switch to evdev input but I heard that's a security risk on Linux, unlike the raw input API we use on Windows.

**Comment by richardg867** [comment]
For the record, this was fixed by the recent xkbcommon keyboard overhaul.
