### ISSUE TITLE
Windows nt 3.51 and 4.0 Mouse bug

### ISSUE THREAD

**Issue by NitwitVillager** [86Box/86Box#2948]
**Describe the bug*
Cannot left click on a program,file and shortcut, instead it will show the properties window

**To Reproduce**
1.Turn on the vm
2. And Try to left click a program/shortcut/file
3. See properties window instead of opening it

**Expected behavior**
Open the program/file

**Screenshots**
![image](https://user-images.githubusercontent.com/83435691/205856777-9c59a825-7c55-41bb-9109-949c58ebfe19.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 22H2
 - 86Box version: version 3.11 {build 4311)
 - Build information: x64, regular build

**Additional context**
This for some reason only happens in Windows NT systems
The Mouse i'm Using is : Microsoft Serial Mouse

**Comment by TC1995** [comment]
Press ctrl-alt to workaround it.

**Comment by NitwitVillager** [comment]
> Press ctrl-alt to workaround it.

thanks
