### ISSUE TITLE
Legend of Heroes 3 is off-key

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#2963]
**Describe the bug**
Sound is off-key.

**To Reproduce**
I used the Korean DOS CD version on https://archive.org/details/ed-3_20221001
After installing the game using setup.exe in the CD, I then started the game using play.bat
I am using a Sound Blaster AW-32

**Expected behavior**
Should have the same pitch as the original PC-98 version

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 3.7.1

**Additional context**
On 86-Box (wrong behavior)

https://user-images.githubusercontent.com/68984176/207252327-09c0006b-1b58-4fa0-8703-c7369676a45e.mp4

Using a different DOS emulator (Dosbox-X, correct behavior)

https://user-images.githubusercontent.com/68984176/207252511-d53bd11a-56d9-45d8-8acf-f33ef598b395.mp4

PC-98 original
https://youtu.be/SQvh7ZbO6eI?t=5

**Comment by TC1995** [comment]
try using nukedopl.

**Comment by ualaa1** [comment]
Happens on both nuked and ymfm

**Comment by OBattler** [comment]
It doesn't sound off-key to me, if anything, it just sounds different because a different chip is being used. If anything, I notice a slight different in speed. But without the 86box.cfg file, I can't really tell what could be wrong.

**Comment by ualaa1** [comment]
Uploaded:
[86box.zip](https://github.com/86Box/86Box/files/10496171/86box.zip)

**Comment by OBattler** [comment]
Try switching to something like Sound Blaster 2 with OPL2 and see if it sounds correctly there.

**Comment by ualaa1** [comment]
Sound Blaster 2 sounds the same as the 86Box SBAWE32

https://user-images.githubusercontent.com/68984176/216891323-4a66b7d3-12e2-4596-8bbe-47ee054d194a.mp4

Config: 
[86box.zip](https://github.com/86Box/86Box/files/10659992/86box.zip)

**Comment by OBattler** [comment]
See if this still happens now that I made OPL output at the correct 49716 Hz.

**Comment by OBattler** [comment]
I just tested it and it appears fixed to me now. This can be reopened if I turn out to be wrong.
