### ISSUE TITLE
When HiDPI scaling is disabled, vertical stretching can ocurr.

### ISSUE THREAD

**Issue by FavoritoHJS** [86Box/86Box#2965]
**Describe the bug**
When HiDPI scaling is disabled (probably only on a HiDPI display), vertical stretching can ocurr. This seems to happen whenever the window would have been resized.

**To Reproduce**
1. Set Display Scaling to a value other than 100%
2. Disable the HiDPI scaling in the View menu.
![imagen](https://user-images.githubusercontent.com/69703458/207509945-7befd17e-b4d9-4236-957c-5eb50d8b630a.png)
3. Toggle Force 4:3 Display Ratio on and off.
4. Stretched display.
![imagen](https://user-images.githubusercontent.com/69703458/207509976-8eac0656-bfa4-42f6-8704-9df24dd647e4.png)

**Expected behavior**
A display that wasn't stretched.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - 86Box version: 3.11b4335
 - Build information: x64, Old Dynrec (not that that matters as I think an 8088 is only interpreted)

**Comment by OBattler** [comment]
This should be fixed now.

**Comment by FavoritoHJS** [comment]
Bad news, it still ocurrs in b4341 which should have fixed the issue.
I suspect there's something wrong when calculating what size the window should be.
If it help, disabling "Lock to this size" when specifing dimensions seems to work around this.

**Comment by FavoritoHJS** [comment]
Good news, it appears like this finally got fixed by 4344 -- instead of the display being stretched and clipped, it just alternates between a small and large size, much less annoying.
Thus, this issue can remain closed
