### ISSUE TITLE
Trident 9440 AGi VLB does not work on Windows 3.1 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2966]
**Describe the bug**
I tested an old VM with the recent builds of 86box. I found that the TGUI 9440 AGi VLB presents a black screen at Windows 3.1 startup, but the PCI version works just fine.

HDD and NVR/CFG files:
[486 Trident 9440.zip](https://github.com/86Box/86Box/files/10227959/486.Trident.9440.zip)
[486 Win 311 Trident 9440.zip](https://github.com/86Box/86Box/files/10227960/486.Win.311.Trident.9440.zip)

**To Reproduce**
1. Start the VM
2. Type Win at DOS prompt
3. Test the VLB and PCI cards
4. On VLB a  black screnappears.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - 86Box version: 3.11.0.4335
 - Build information: Win32 old dynarec

**Additional context**
I suspect the changes made to the TGUI 9440 AGi are the cause of this. But I don't know why affects only the VLB variant of the card.

**Comment by TC1995** [comment]
Let's see.

**Comment by TC1995** [comment]
Well, reconfigure the trident display from vga to tgui9440 when you are in progman (when in vga) using its Windows display utilities.

**Comment by Fenix770** [comment]
Now works! Thanks!
