### ISSUE TITLE
CL-GD5430/5434 render fonts improperly on Windows 95 (Retail)

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#2970]
**Describe the bug**
The builtin driver for the Cirrus Logic CL-GD5430/5434 renders fonts improperly (wrong colors)

**To Reproduce**
1. Configure a machine with a Cirrus Logic CL-GD5430 or CL-GD5434
2. Install Windows 95 (original/retail)
3. Notice fonts are sometimes rendered with incorrect colors

**Expected behavior**
Fonts should render properly with the correct colors

**Screenshots**
![Monitor_1_20221217-153452-556556](https://user-images.githubusercontent.com/47463859/208266947-02262b3f-c83e-4e85-86aa-27dd8165f207.png)
![Monitor_1_20221217-153505-35035](https://user-images.githubusercontent.com/47463859/208266954-a41f7565-5851-484d-9522-bdafe90c5ac5.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 x64 SP1
 - 86Box version: 3.11 build 4329
 - Build information: x86 old dynarec

**Additional context**
This does not affect the builtin driver on Windows 95 OSR2.
Config and NVR files: 
[Config and NVRAM.zip](https://github.com/86Box/86Box/files/10252782/Config.and.NVRAM.zip)

**Comment by TC1995** [comment]
I think it's some transparency issue, does it occur on earlier 86box builds? I mean, those that don't have newer cirrus fixes.

**Comment by win2kgamer** [comment]
The issue does not occur in 86Box 3.7.1 (build 4032)

**Comment by TC1995** [comment]
well, try to bisect which exact build broke so.

**Comment by win2kgamer** [comment]
The issue was introduced in build 4232.

**Comment by Cacodemon345** [comment]
This should be fixed now.

**Comment by win2kgamer** [comment]
Just tested build 4352 and the issue is resolved.

**Comment by OBattler** [comment]
Then this can be closed.
