### ISSUE TITLE
Activision Shangahi game issues on Tandy 1000/PCjr

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2974]
**Describe the bug**
I tested a game called Shanghai, the game has two executable files one is for "PC" and uses CGA 4-color graphics. The second is for Tandy 1000/PCjr. The game was launched in 1986.

The Tandy 1000/PCjr versions has the following issues:

1. On the IBM PCjr the game refuses to start saying memory is not enogh despite having 640kb of RAM. I tested with DOS 2.11 and DOS 3.20  boot disk and I get the same error.
2. On the Tandy 1000 original and SL/2, the game starts, but the keyboard does not respond, so is unplayable.

Here is the image file of the floppy disk:
[Shangai 1.zip](https://github.com/86Box/86Box/files/10258929/Shangai.1.zip)

**To Reproduce**
1. Simply type "SHANGJR" at DOS prompt to start the 16-color version.
2. You'll find one of the errors mentioned above. 

**Screenshots**
Here are the Tandy/PCjr 16 color and CGA 4 color captures:
![Shnghai 1 CGA](https://user-images.githubusercontent.com/31600563/208418646-10023ab5-501d-4cde-be32-7f1bd44fbca8.png)
![Shanghai 1 Tandy](https://user-images.githubusercontent.com/31600563/208418651-8205f965-0de2-4f4a-8a1a-0561066fcab8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - 86Box version: 3.11.0.4339
 - Build information: Win32 old dynarec.

**Comment by OBattler** [comment]
> On the IBM PCjr the game refuses to start saying memory is not enogh despite having 640kb of RAM. I tested with DOS 2.11 and DOS 3.20 boot disk and I get the same error.

On the IBM PCjr, anything will officially see a maximum of 128 kB of RAM, for more, we would need to properly emulate the expansion board which we do not.

> On the Tandy 1000 original and SL/2, the game starts, but the keyboard does not respond, so is unplayable.

This needs to be looked into.

**Comment by OBattler** [comment]
Said Tandy keyboard issue now appears to have been fixed, therefore, I'm closing this.
