### ISSUE TITLE
GD-5422 issues

### ISSUE THREAD

**Issue by Carmina16** [86Box/86Box#2976]
With Windows for Workgroups:

* With the [1.3 drivers](https://archive.org/details/5426DR13_ZIP), the 1024x768x8 mode doesn't work properly: the screen takes the 1024x768 dimension, but is black.
* With the WWG 3.11 SVGA driver, in all 256-color modes scrolling of windows is broken, as the scrolled area becomes black.
* Additionally, in build 4342, the mouse cursor is invisible.

**Comment by TC1995** [comment]
For the first, you're using the 5426 drivers on the 5422, which is not valid.
I'd suggest you use the 1.50e drivers for 5422 (not for 5426).

**Comment by OBattler** [comment]
I believe these has since been fixed by Cacodemon345's commits.
