### ISSUE TITLE
Acer V35N will not POST

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#2979]
**Describe the bug**
When I try to run a machine based on the Acer V35N, it shows a glowing Acer logo, beeps, and won't go any further.

**To Reproduce**
1. Create a machine based on an Acer V35N.
2. Insert any bootable media.
3. Wait for machine to boot; it won't.

**Expected behavior**
Machine should boot from any bootable media. I have tried a boot floppy, a CD-ROM drive (with CD Booting enabled in CMOS), and a hard drive that has been formatted.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - 86Box version: v3.11 Build 4344
 - Build information: Windows 32-bit, old dynarec

**Additional context**
86Box.cfg is attached.
[86box.cfg.txt](https://github.com/86Box/86Box/files/10269963/86box.cfg.txt)

**Comment by TC1995** [comment]
Known issue.

**Comment by OBattler** [comment]
This is now fixed. Clear the NVR and reconfigure it.
