### ISSUE TITLE
Build info in Help>About

### ISSUE THREAD

**Issue by orcutt989** [86Box/86Box#2991]
It would be nice to see what the build ix (x86 vs x64, dynamic recomplier, vs, non, etc) when trying out different builds. I'm using WinBox which automatically downloads a Jenkins build. Trying out different builds its hard to see which build of x86 box I am using at a given time.  
![image](https://user-images.githubusercontent.com/5608027/209216494-a4b57b5e-5f59-4caa-9b12-282425fe62c1.png)

**Comment by OBattler** [comment]
I'm quite sure the build number is in the emulator's title bar.

**Comment by orcutt989** [comment]
Yes and its also in the screenshot I posted. My request is not for the build number- its to add the arch (x86/x64) and whether the build is the dynamic recompiler or not. The build number is the same across all configurations and so is only helpful for knowing if you're up-to-date.
