### ISSUE TITLE
2.88MB Floppy not working

### ISSUE THREAD

**Issue by kzmidze** [86Box/86Box#2995]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
2.88MB floppy
![86box-1](https://user-images.githubusercontent.com/117635969/209548708-2dee72a0-857d-4105-a2a8-cfa082ccf5aa.png)
1.44MB floppy
![86box-2](https://user-images.githubusercontent.com/117635969/209549176-00e5d7d7-bd1e-40c2-84d7-9c2d81b7bd5b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: v3.11 build 4311

**Additional context**

**Comment by TC1995** [comment]
Erm, have you configured the cmos to identify it as a 2.88MB floppy as well as the emulator settings?

**Comment by TC1995** [comment]
motherboard?

**Comment by TC1995** [comment]
it might be sio (super I/O) issue.

**Comment by OBattler** [comment]
No, it's the known Windows 9x floppy bug on the recompiler. Closing with CANTFIX as it's unfixable due to how the recompiler works.
