### ISSUE TITLE
x64 build crashes during Windows 2000 GUI setup

### ISSUE THREAD

**Issue by B-F-1-0** [86Box/86Box#2998]
**Describe the bug**
86Box crashes during the final portion of Windows 2000's setup, usually during "Registering components" or "Saving settings". Occasionally also happens with Windows XP (regardless of SP or edition), but happens more frequently on Windows 2000. This is being done with a Socket 7 (Dual Voltage) configuration with a vanilla Pentium processor.

Replicated on Windows 2000 build 2031, SP4, and Windows XP RTM and Starter Edition. Issue does not appear to occur on PCem v15 with same config.

**To Reproduce**

1. Start Windows 2000's setup from any source, such as winnt /b or booting to disk.
2. Get past the text setup as normal and get past the user identification portion of GUI setup as normal.
3. 86Box crashes around the same portion as seen below.

- 86Box also has a decent chance of crashing even before getting to the final stage, such as during the "Setup is restarting..." screen, during the hardware detection, or during file copying.

**Additional Files**
[cfg file and nvr](https://github.com/86Box/86Box/files/10309683/cfg.and.nvr.zip)

**Screenshots**
Approximate location where setup crashes.
![Monitor_1_20221227-112542-452452](https://user-images.githubusercontent.com/115908504/209694954-efc97b4b-f2f6-4ef1-b08d-e9fbb196408d.png)

**Expected behavior**
Setup completes and boots to the desktop.

**Desktop**
- **OS**: Windows 11 Enterprise (x64)
- **86Box version**: 86Box v3.11 [[`fd82e52`](https://github.com/86Box/86Box/commit/fd82e523a0cecdc841664b60412e561c8c365563), build 4359] x64 (also tested with 86Box v3.8 [[`de6a690`](https://github.com/86Box/86Box/commit/de6a6909e59d558d47454f7d8f77d42093f8c717), build 4208] x64) 
- **Build type**: Old Dynamic Recompiler Win64

**Comment by TC1995** [comment]
use the Win32 binary.

**Comment by B-F-1-0** [comment]
Now works with the Win32 binary, but largely needs to be looked into for the Win64 binary as it appears to have problems with this machine.

**Comment by OBattler** [comment]
Does it still happen on the 64-bit binary?

**Comment by OBattler** [comment]
I'm going to close this as fixed.
