### ISSUE TITLE
Modem Emulation

### ISSUE THREAD

**Issue by ToasterGithubUser** [86Box/86Box#3005]
Im want use web in windows 95

**Comment by TC1995** [comment]
For now you can use ethernet emulation.

**Comment by ToasterGithubUser** [comment]
So how to do it? Im have only Wi-fi

**Comment by TC1995** [comment]
Well, use slirp and configure the nic you want to use.

**Comment by ToasterGithubUser** [comment]
can slirp connect to internet without port forwarding?

**Comment by TC1995** [comment]
It can, you just need to use 10.0.2.15 as the ip address, gateway 10.0.2.2, dns server 10.0.2.3, subnet you know it.

**Comment by ToasterGithubUser** [comment]
thanks

**Comment by ToasterGithubUser** [comment]
For windows 95/98, DNS host can be anyone? (like, just type your name in host section and it will be able to browse web?)

**Comment by ToasterGithubUser** [comment]
dang it
![Win95 - 86Box 3 11  build 4365  02 01 2023 1_15_37](https://user-images.githubusercontent.com/73711167/210186114-d474d451-9f26-451e-8917-9c34cfbd1ab0.png)

**Comment by TC1995** [comment]
make sure the nic drivers are installed.

**Comment by ToasterGithubUser** [comment]
Do you have any NE 2000 or NE1000 drivers? The links that showed me first, just installing scam driver updating apps

**Comment by ToasterGithubUser** [comment]
Ok so now internet is loading, im just typed wrong IRQ

**Comment by ToasterGithubUser** [comment]
ok now internet is working, but some sites giving an error
![Win95 - 86Box 3 11  build 4366  02 01 2023 13_02_05](https://user-images.githubusercontent.com/73711167/210216937-3717a11a-e088-49d1-9e7b-0681431e51c8.png)

**Comment by BomberBlur07** [comment]
The site is too new for old IE.

**Comment by ToasterGithubUser** [comment]
Is there any ways to solve it? Im using now Outlook too

**Comment by TC1995** [comment]
Nope, unless you're willing to have updates to IE.

**Comment by ToasterGithubUser** [comment]
I hope it will change, im updating system to Windows 2000.

**Comment by jriwanek** [comment]
We can't magically make an old web browser support new websites, and they're not gonna regress support for retro users either.
That said, there's many web proxies one can find which allow you to connect to new sites in old browsers, they won't however regress the site so the pages look right, or even load properly.

**Comment by OBattler** [comment]
At this point, the user's main problem (getting the Internet in 86Box) has been solved, the websites problem is not our fault and we can't do anything about it.

**Comment by ToasterGithubUser** [comment]
Anyone knows how to edit DNS and other options in WIndows 2000?

**Comment by jhstatewide** [comment]
> Anyone knows how to edit DNS and other options in WIndows 2000?

Yes, no problem
