### ISSUE TITLE
SLiRP Port Forwarding instructions are wrong in the docs

### ISSUE THREAD

**Issue by bertrandom** [86Box/86Box#3015]
**Describe the bug**
With [3.11](https://github.com/86Box/86Box/pull/2645/files), the NIC # must be specified in the header, like this:

```
[SLiRP Port Forwarding #1]
```

but the [docs](https://86box.readthedocs.io/en/latest/hardware/network.html#slirp-port-forwarding) do not reference the NIC # at all. Using the header specified in the docs:
```
[SLiRP Port Forwarding]
```

doesn't do anything.

**To Reproduce**

Add a section called
```
[SLiRP Port Forwarding]
```
using 3.11. It does not actually forward ports.

**Expected behavior**
Docs describe how to specify the network card.

**Desktop (please complete the following information):**
 - OS: OS X 12.6
 - 86Box version: 3.11
 - Build information: M1 Mac

**Comment by OBattler** [comment]
This is now fixed.
