### ISSUE TITLE
Support for TI486SXLC2-G50-PQ and CX486SLC2-50 CPUs on 386SX motherboards

### ISSUE THREAD

**Issue by DamienC666** [86Box/86Box#3016]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Interested in seeing support for TI486SXLC2-G50-PQ and CX486SLC2-50 CPUs on 386SX motherboards in 86Box.

**Describe alternatives you've considered**
The Cx486SRx2 upgrade chip that is already supported is very similar to the Cyrix 486SLC2-50 (if not identical). Only difference being the SRx2 is a clip-on upgrade and the SLC2 is a QFP. I don't know if adding support is simply a matter of nomenclature or if there's significant enough differences in the chips to warrant another entry.

The TI chip is unique however in that it has a larger L1 cache and appears to be able to either be clock-doubled to 50MHz with a 25MHz bus speed or ran at roughly ~40MHz with no clock-doubling.

**Additional context**
Youtube video of someone modding a TI 486SXLC2-50 onto a Sarc RC2016A based 386SX board:
[https://www.youtube.com/watch?v=sgXdiCPwGUA&t=1](url)

TI datasheet attached for reference.
[1994_TI486SXLC_and_TI486SXL_Microprocessors_Reference_Guide.pdf](https://github.com/86Box/86Box/files/10355195/1994_TI486SXLC_and_TI486SXL_Microprocessors_Reference_Guide.pdf)

**Comment by OBattler** [comment]
From what I know, the timings and the instruction set would be pretty much the same, and that's the only thing thatm atters for emulation. So it would be a pretty pointless addition as it'd basically be copies of the existing Cx486SRx2 with new names.

And we don't emulate the cache at all, only the cache timings (and they don't take cache size into account at all, that I know of).

As such, I'm closing this for the time being, but it may be reopened in the future if anything changes that would warrant doing so.
