### ISSUE TITLE
Any chance of a Linux port?

### ISSUE THREAD

**Issue by SeanRamey** [86Box/86Box#302]
Building 86Box under linux almost seems to work, until it starts compiling the network source files, starting with net_pcap.c

**Comment by dhrdlicka** [comment]
A Linux port was underway, but the person working on it left the project a few months ago. There still are some remnants of a WxWidgets frontend in the makefile. The core should be compilable on other platforms than Windows, if it's not, then it's a bug which should be fixed :)

**Comment by waltje** [comment]
The Linux port is fine, but put on hold while I work on other parts of the system.

**Comment by OBattler** [comment]
This conversation can continue in the other, older issue about the same thing.
