### ISSUE TITLE
SB16 stuttering and playing too fast on Apple M1

### ISSUE THREAD

**Issue by jeroenjacobs79** [86Box/86Box#3029]
**Describe the bug**
I'm emulating a 486DX2-66 based machine with SB16. It seems that the sound seems to stutter and playing too fast. 

**To Reproduce**
Seems to be the case every time it tries to play digital audio. FM synth doesn't seem to be affected at first glance. Emulated MT-32 doesn't seem to be affected either.

**Expected behavior**
Play sound correct

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Ventura 13.1 (Apple M1 Pro)
 - 86Box version: v3.11 build 4311
 - Build information: ?
 
**Additional context**

config file:

```
[General]
vid_renderer = qt_software
scale = 2

[Machine]
machine = vi15g
cpu_family = i486dx2
cpu_speed = 66666666
cpu_multi = 2
cpu_use_dynarec = 0
time_sync = disabled
fpu_type = internal
cpu = 11
mem_size = 8192

[Video]
gfxcard = cl_gd5428_vlb

[Input devices]
mouse_type = logibus

[Sound]
fm_driver = nuked
sndcard = sb16
midi_device = mt32

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa_2ch
cassette_mode = load

[Sound Blaster 16]
base = 0220
base401 = 0330
irq = 5
dma = 1
dma16 = 5
opl = 1
receive_input = 1
receive_input401 = 0

[Hard disks]
hdd_01_parameters = 63, 10, 1013, 0, ide
hdd_01_fn = /Users/jeroenjacobs/486main.img
hdd_01_speed = 1996_5400rpm
hdd_02_parameters = 63, 16, 1054, 0, ide
hdd_02_fn = /Users/jeroenjacobs/486data.img
hdd_02_speed = 1996_5400rpm
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_parameters = 0, atapi
cdrom_01_ide_channel = 1:1
cdrom_01_image_history_01 = /Users/jeroenjacobs/486-emu/dos_iso
cdrom_01_image_history_02 = /Users/jeroenjacobs/retro_games
cdrom_01_host_drive = 200
cdrom_01_image_path = /Users/jeroenjacobs/hell/iso/HELL.iso
fdd_01_image_history_01 = /Users/jeroenjacobs/486-emu/dos_iso/QEMM 7.5/QEMM 7.5 - Disk 2.IMA
fdd_01_image_history_02 = /Users/jeroenjacobs/486-emu/dos_iso/QEMM 7.5/QEMM 7.5 - Disk 1.IMA

[Roland MT-32 (New) Emulation]
output_gain = 100
reverb = 1
reverb_output_gain = 100
reversed_stereo = 0
nice_ramp = 1
```

**Comment by OBattler** [comment]
Try enabling the dynamic recompiler.

**Comment by jeroenjacobs79** [comment]
Hi,

That didn't solve the issue. However, it seems that changing the mouse type seems to solve it! When I change the mouse type to "Microsoft Bus Mouse (InPort)", the problem goes away. But this type of mouse doesn't seem to work in all games.

Going to do some more experimenting...

**Comment by jeroenjacobs79** [comment]
The solution is to set the type to "Microsoft Serial Mouse". 

The issue seems only to occur if type is set to "Logitech/Microsoft Bus Mouse", which is weird as this has nothing to with sound.

Does this type use the same IRQ as my SB16 maybe? (IRQ 5)

**Comment by TC1995** [comment]
it usually does, so change the irq of the sb16 or of the mouse.

**Comment by jeroenjacobs79** [comment]
Closed ticket as suitable workaround is available (= using serial mouse emulation)
