### ISSUE TITLE
Trio3D on Win98, no 3D output

### ISSUE THREAD

**Issue by startmenu** [86Box/86Box#3030]
**Describe the bug**
On Windows 98/Me, Trio3D shows only black screen when I run dxdiag to test D3D. Only 3.5MB VRAM is reported when 8MB is selected. The driver is v2.61.06 from Vogons Drivers.  However it works on WinXP with driver 5.30.05 Engineering Release. 

Machine: ASUS P3V4X(Apollo Pro 133A)
CPU: Klamath PII 233MHz
Display: S3 Trio3D/2X (362) both AGP and PCI

**Desktop (please complete the following information):**
 - OS: macOS 13 ARM64
 - 86Box version: 3.11 build 4377
 - Build information: NDR Regular

**Comment by OBattler** [comment]
This is a CANTFIX due to a lack of datasheet.
