### ISSUE TITLE
IBM PC 5150 Color Displays Not Working

### ISSUE THREAD

**Issue by pgalbraith** [86Box/86Box#3032]
**Describe the bug**
Can only get amber monochrome video for IBM PC 5150

**To Reproduce**
Create an IBM PC 5150 VM (1981 or 1982), select MDA video and configure for green monochrome display -- always displays amber.  Same if you pick CGA with RGB or composite output -- always displays monochrome amber.

**Expected behavior**
Should be able to get color CGA output or green monochrome.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: 3.11
 - Build information: 64-bit

**Additional context**

**Comment by OBattler** [comment]
Seems like the cards are not having their palette rebuilt on hard reset after changing display type.

**Comment by OBattler** [comment]
Related issue: https://github.com/86Box/86Box/issues/3043 .

**Comment by OBattler** [comment]
This appears to be fixed now, or at least, I can no longer reproduce it.
