### ISSUE TITLE
Per-Config BIOS Option

### ISSUE THREAD

**Issue by nickkeane** [86Box/86Box#3037]
**Is your feature request related to a problem? Please describe.**
Yes, I'm using multiple different .cfg files to represent *entirely* different machines for various games, apps, and purposes. However, for a machine with the same chipset, but different CPUs, the BIOS throws an error that needs to be passed through whenever I switch between machines.

**Describe the solution you'd like**
There should be a setting that allows BIOS settings to be saved per-config instead of per-chipset.

**Comment by OBattler** [comment]
CMOS and BIOS flash are saved per selected machine. The only solution is to use -P / --vmpath to specify a new VM path, which would therefore, have its own folder for CMOS and BIOS flash.
