### ISSUE TITLE
Acer V35N won't POST with CD-ROM booting enabled

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#3039]
**Describe the bug**
Build 4384 has mostly fixed the issue of the Acer V35N not POSTing. Unfortunately, when CD-ROM booting is enabled, it still will not POST.

**To Reproduce**
1. Create and start a machine with an Acer V35N motherboard.
2. Enter CMOS settings when prompted (Actions > Ctrl+Alt+Esc).
3. Go to System Security > Boot from CD-ROM and change to [Enabled].
4. Reboot saving settings.
5. Machine only displays the Acer logo.

**Expected behavior**
Machine should attempt to boot from any device, including a bootable CD-ROM.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - 86Box version: v3.11 build 4384
 - Build information: old dynarec, 32-bit Windows

**Additional context**
When CD-ROM booting is disabled, it does attempt to boot from any device except for the CD-ROM. This happens both with my existing machine from the original bug report (using the "wipe" option in 86Manager), and with a fresh machine.

**Comment by OBattler** [comment]
Closing this with a CANTFIX - I've done extensive io.c logging on this, and I have no idea what's wrong. Perhaps the CD-ROM booting mode is intended to only be used with the Acer recovery CD? I don't know.
