### ISSUE TITLE
Windows NT Workstation 4.0 crashes 86box

### ISSUE THREAD

**Issue by Xuser641** [86Box/86Box#3040]
**Describe the bug**
Windows NT Workstation 4.0 crashes 86box sometimes, it seems to happen when Internet Explorer 2 starts (like when trying to view the readme for SP6a) or when trying to run the setup for Internet Explorer 5 (which I did in case IE2 was causing the problem). Strangely, running the setup program again after restarting 86box worked but then it crashed at some point during the install process. After restarting 86box and running the setup program again, it completed normally.

**To Reproduce**
1. Install Windows NT Workstation 4.0 and start it.
2. Do something that causes internet explorer to open (like inserting the SP6a install disk), or try to run the setup for IE5 off the same disk. (there could be other causes as well)
3. Maybe see crash / Maybe see it work

**Expected behavior**
86box should not crash

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - 86box 3.7.1 Build 4032
 - Build information: Stable Build, 64 bit architecture

**Comment by TC1995** [comment]
Just use the 32-bit binary as the x64 binary is somewhat broken.

**Comment by OBattler** [comment]
I think this is fixed now - there were x64 recompiler bugs back then that have since been fixed.
