### ISSUE TITLE
Does SDL renderer still works? How to activate VNC if compiled in?

### ISSUE THREAD

**Issue by Randrianasulu** [86Box/86Box#3041]
**Describe the bug**
I compiled 86box on termux/aarch64 by selecting new dynrec and disabling rtmidi/faudio + selecting vnc in ccmake menu.

![Screenshot_20230120-043341](https://user-images.githubusercontent.com/40185805/213599106-fd9f501c-3d21-494f-b322-cfc88103e8bf.png)

it compiles and links fine, just after startup I see SDL window with correct default machine title, hear beep, but apparently nothing rendered inside window?

**To Reproduce**
just download romset and start 86Box build (in termux) with SDL renderer only

**Expected behavior**
I hoped to  see at least BIOS screen!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: termux aarch64
 - 86Box version: b875e8518d2857469ae00473744bcd50cb0feeb0
 - Build information: 

CMAKE_BUILD_TYPE                 RelWithDebInfo
 CMAKE_INSTALL_PREFIX             /usr/local
 CPPTHREADS                       ON
 DEV_BRANCH                       OFF
 DINPUT                           OFF
 DYNAREC                          OFF
 FAUDIO_INCLUDE_DIR               FAUDIO_INCLUDE_DIR-NOTFOUND
 FAUDIO_LIBRARY                   FAUDIO_LIBRARY-NOTFOUND
 FLUIDSYNTH                       OFF
 Freetype_DIR                     Freetype_DIR-NOTFOUND
 GDBSTUB                          OFF
 LibVNCServer_DIR                 /data/data/com.termux/files/usr/lib/cmake/LibVNCServer
 MINITRACE                        OFF
 MUNT                             OFF
 NEW_DYNAREC                      ON
 OPENAL                           ON
 OpenAL_DIR                       /data/data/com.termux/files/usr/lib/cmake/OpenAL
 PNG_DIR                          PNG_DIR-NOTFOUND
 PkgConfig_DIR                    PkgConfig_DIR-NOTFOUND
 QT                               OFF
 Qt5Core_DIR                      /data/data/com.termux/files/usr/lib/cmake/Qt5Core
 Qt5Gui_DIR                       /data/data/com.termux/files/usr/lib/cmake/Qt5Gui
 Qt5Network_DIR                   /data/data/com.termux/files/usr/lib/cmake/Qt5Network
 Qt5OpenGL_DIR                    Qt5OpenGL_DIR-NOTFOUND
 Qt5Widgets_DIR                   /data/data/com.termux/files/usr/lib/cmake/Qt5Widgets
 Qt5_DIR                          /data/data/com.termux/files/usr/lib/cmake/Qt5
 RELEASE                          OFF
 RTMIDI                           OFF
SLIRP_TINYGLIB                   ON
 STATIC_BUILD                     OFF
 Threads_DIR                      Threads_DIR-NOTFOUND
 USE_QT6                          OFF
 VNC                              ON
 ZLIB_DIR                         ZLIB_DIR-NOTFOUND

+++++

despite few notfound it builds and links ok, just qt5 termux files does not have gl subsystem ...

**Additional context**
with clang 15 there were two errors, I silenced them like this

```
~/86Box $ git diff
diff --git a/src/include/86box/plat_dir.h b/src/include/86box/plat_dir.h
index f6c135001..dd66b1214 100644
--- a/src/include/86box/plat_dir.h
+++ b/src/include/86box/plat_dir.h
@@ -19,7 +19,7 @@
 #define PLAT_DIR_H

 /* Windows needs the POSIX re-implementations */
-#if defined(_WIN32)
+#if defined(_WIN32) || defined(__TERMUX__)
 #    ifdef _MAX_FNAME
 #        define MAXNAMLEN _MAX_FNAME
 #    else
diff --git a/src/unix/unix.c b/src/unix/unix.c
index 296da5e14..851c460ee 100644
--- a/src/unix/unix.c
+++ b/src/unix/unix.c
@@ -626,9 +626,9 @@ ui_msgbox_header(int flags, void *header, void *message)
     if (!header)
         header = (flags & MBX_ANSI) ? "86Box" : L"86Box";
     if (header <= (void *) 7168)
-        header = plat_get_string(header);
+        header = plat_get_string((int ) header);
     if (message <= (void *) 7168)
-        message = plat_get_string(message);
+        message = plat_get_string((int ) message);
     msgbtn.buttonid = 1;
     msgbtn.text     = "OK";
     msgbtn.flags    = 0;
~/86Box $
```

**Comment by dhrdlicka** [comment]
Is there any particular reason why you wouldn't use the AppImage distribution?

**Comment by Randrianasulu** [comment]
@dhrdlicka I compile qt5 version on Slackware, where it works. This specific bug surfaced when I try to compile 86box inside termux, on android tablet.

**Comment by dhrdlicka** [comment]
The reason why I suggested using our official AppImage builds is that they are more or less self-contained, which helps when avoiding issues with distribution packages being weird.

The thing with our non-Qt *nix platform module is that it is essentially unmaintained ever since the Qt module was introduced. It is possible that it had already bitrotten enough for this bug to happen.

One thing I noticed is that you don't seem to use our toolchain files in `/cmake`, which might also affect things. Please try again with `/cmake/flags-gcc-aarch64.cmake`, this sets up the expected compiler flags.

**Comment by Randrianasulu** [comment]
@dhrdlicka Hm, I do not know how to use those files with cmake :( Note, termux uses clang and some things reside in unusual locations

**Comment by dhrdlicka** [comment]
This is explained in our [build guide](https://86box.readthedocs.io/en/latest/dev/buildguide.html).

Clang is GCC-compatible, so the toolchain files will work with that too.

**Comment by Randrianasulu** [comment]
@dhrdlicka I tried it like this (my local hack still needed)

~/86Box $ cmake . -DCMAKE_TOOLCHAIN_FILE=./cmake/flags-gcc-aarch64.cmake

and sadly bug still around
