### ISSUE TITLE
Incorrect Defaults for FluidSynth

### ISSUE THREAD

**Issue by nickkeane** [86Box/86Box#3049]
**Describe the bug**
The defaults for FluidSynth don't match the spec in the official documentation. Also, Reverb Width is not the correct data type or value.

https://www.fluidsynth.org/api/settings_synth.html

Looking at the code in src/sound/midi_fluidsynth.c:

- Default Chorus Level should be 20, not 100, in order to produce a default of 2.0 (Scale: 0.0 - 10.0).
- Default Reverb Width should be 0.5, and also a double - not an int - to produce a default of 0.5 (Scale: 0.0 - 100.0).

**To Reproduce**
1. Create a fresh 86Box machine.
2. Create an i486 Machine and enable FluidSynth. Click Configure for FluidSynth.

**Expected behavior**
86Box Defaults should be in-line with the FluidSynth defaults.

**Screenshots**

**Desktop (please complete the following information):**
- Windows 10
- Stable v3.11 build 4311 x86_64

**Additional context**

**Comment by OBattler** [comment]
On Windows, we currently use a custom FluidSynth 1.x to avoid DLL/Dependency Hell. Is it certain that those defaults also apply to that?
