### ISSUE TITLE
OTI-037/067 VGA bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#305]
Hello!

I believe i found  a bug with OTI-037/067 video cards. The OTI-037 does not work, the screen remains dark, and several "beeps" that seems to be an error code can be heard.

The OTI-067 works, but with the 077 bios it always report 1MB RAM. And the OTI-067 internal video chip  on the AMA932J 386 SX machine, does not work  and either the external OTI-067 video card in this machine  (nothing can be seen, but the memory count can be heard).

Thanks for your effort!

**Comment by TC1995** [comment]
I believe it's a speed issue.

**Comment by OBattler** [comment]
Some card-BIOS combinations hang, that's because the cards are not really emulated *that* well, and the conversion of timers to 64-bit (which is needed to avoid overflow and distortion on faster emulated CPU's) caused them to stop working. We are still investigating where exactly the problem is.
