### ISSUE TITLE
ASUS P55T2P4 fails with older BIOS versions

### ISSUE THREAD

**Issue by oerg866** [86Box/86Box#3063]
**Describe the bug**
ASUS P55T2P4 machine with an older BIOS fails to POST.

The emulated POST card shows code 0xC3 which indicates a problem with RTC emulation for this board?

**To Reproduce**
1. Make a VM with an ASUS P/I-P55T2P4 machine (under Socket 7 (Dual Voltage)
2. Replace the BIOS ROM in "roms\machines\p55t2p4" with an older version, such as ([0108](https://theretroweb.com/motherboard/bios/t25i0108-5eebd4fedc380162226763.zip))
3. Observe the failed POST

**Expected behavior**
The emulated machine boots.

**Screenshots**
None, sorry

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - 86Box version: 3.11 Build 4311
 - Build information: 32-Bit release build

**Additional context**
I was trying to debug a real P55T2P4 erroring out with a boot loader I wrote. The latest BIOS version does not exhibit this problem.

**Comment by dhrdlicka** [comment]
Using custom BIOS files is not officially supported.

**Comment by TheVirtualComputer** [comment]
But if the original board supported the earlier BIOS, and the emulated board doesn't work correctly with it as an original board would have, then the board is not being emulated correctly. Most likely, an emulator bug occurs that is triggered with certain BIOS versions but not with other versions, and it should be investigated as such.

**Comment by OBattler** [comment]
I have just tested the specific BIOS linked here, and it appears to now works correctly. As such, I'm closing this.
