### ISSUE TITLE
Incorrect keyboard scancodes in TSX-32

### ISSUE THREAD

**Issue by waltje** [86Box/86Box#307]
Installing TSX-32 on any machine >= 386SX.  Used v6.34a, but also happens with 4.11.

System does start up, but the keyboard mappings are a mess.  The exact same setup (same disk
image, same machine) does seem to work OK in PCem V14 - config included.

See debug.log for output.

ZIP file with all needed files is at http://waltje.varcem.com/tsx32.zip

**Comment by OBattler** [comment]
I have fixed this by now. :p

**Comment by waltje** [comment]
Confirmed, disabling Mode1 does fix it, but this is a workaround.

**Comment by OBattler** [comment]
TSX-32 needs to be tested on a real keyboard that can be software-switched to mode 1. More detailed logging should also be done on the keyboard controller, and every thing command it issues, examined, since maybe some command should be turning translation off but does not.
