### ISSUE TITLE
Gigabyte GA-5AX serial not working

### ISSUE THREAD

**Issue by PentiumMMX166** [86Box/86Box#3070]
**Describe the bug**
Serial just does not work on there, i see Serial Ports: None after POST when i boot it and i can't get the serial mouse working as a result

**To Reproduce**
1. Boot the GA-5AX and wait for it to POST
2. Make sure to use serial mouse, and try running something that uses mouse like boot to DOS with CuteMouse driver loaded
3. See error

**Expected behavior**
Serial is supposed to be detected, the BIOS settings have serial enabled by default.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: 3.11 Build 4397
 - Build information: old dynarec, x86_32, regular build

**Additional context**
N/A

**Comment by TC1995** [comment]
Most likely a SIO bug on our end.
