### ISSUE TITLE
Mouse pointer is too fast when 86box is launched in a remote session.

### ISSUE THREAD

**Issue by pglizniewicz** [86Box/86Box#308]
I often use my virtual machines from remote computer via Remote Desktop. When I launch 86box with Windows 95 installed and use it via RDP, the mouse pointer is too fast - it jumps from one side of the window to another. This doesn't happen, when I use it locally. 

I'm using build 1636, but tested also older builds with same effects.

My VM configuration is:

    [Machine]
    machine = p55t2p4
    mem_size = 65536
    cpu_use_dynarec = 1
    time_sync = local
    cpu = 2
    cpu_enable_fpu = 1

    [Video]
    gfxcard = n9_9fx_pci
    video_speed = -1

    [Input devices]
    mouse_type = ps2

    [Other peripherals]
    hdc = none

    [Sound]
    sndcard = sb16

    [Network]
    net_card = ne2k

    [Novell NE2000]
    mac = b7:4a:c8

    [Hard disks]
    hdd_01_parameters = 63, 16, 4096, 0, ide
    hdd_01_fn = Y:\payload\2GB.img
    hdd_01_ide_channel = 0:0

    [Floppy drives]
    fdd_01_type = 35_2hd
    fdd_02_type = none

    [Other removable devices]
    cdrom_01_parameters = 0, atapi
    cdrom_01_ide_channel = 0:1

    [Standard PS/2 Mouse]
    buttons = 2

**Comment by OBattler** [comment]
Known problem. It's because mouse works entirely differently in a RDP session compared to directly on physical hardware. A lot of games have the same issue. I'm still looking for a way to fix this.

**Comment by OBattler** [comment]
This is fixed int he current builds - fixed by the switching to Raw Input (I need to update the auto-build file for that).
