### ISSUE TITLE
New Dynarec not recognized Microsoft Sidewinder Pad

### ISSUE THREAD

**Issue by AITUS95** [86Box/86Box#3082]
I've installed all the drivers needed to recognize the Microsoft Sidewinder Pad, on the latest 86box 32bit ODR is recognized without problems by Windows 98 while on NDR it complains that the device is not plugged in, meanwhile I'll look for some old 86box builds for understand if something has been broken, below I leave you the following attachments:

**ODR**

![ODR](https://user-images.githubusercontent.com/48457684/216774962-9b4eaaf2-1d69-4de6-9a21-154a8ee16700.PNG)

**NDR**

![NDR](https://user-images.githubusercontent.com/48457684/216774995-591b5fa8-f849-48c9-bce9-b2a348b30c0a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - 86Box version: v3.11 build 4412 "Latest from Jenkins"
 

**Additional context**

Used VM:  https://drive.google.com/file/d/1kBQw_0UVctqWwMiGt1PUWVGuq3MRJeKW/view?usp=share_link

**Comment by OBattler** [comment]
Does this still happen?

**Comment by AITUS95** [comment]
yes, unfortunately it still is

![pic](https://github.com/86Box/86Box/assets/48457684/dacdaf1b-eb2a-4689-be42-33bc2c29569c)

**Comment by OBattler** [comment]
The Microsoft SideWinder pad is very timings-sensitive so this is unfortunately impossible to fix.
