### ISSUE TITLE
Running the display adapter test on an MDA monitor fails on an IBM PC or IBM PC XT

### ISSUE THREAD

**Issue by StrangerCoug** [86Box/86Box#3083]
**Describe the bug**
Running the display adapter test on an MDA monitor fails on an IBM PC or IBM PC XT

**To Reproduce**
1. Make a VM and configure it to either [8088] IBM PC (1982) or [8088] IBM PC XT (1986). (The bug might also be reproducible with the [8088] IBM PC (1981) or [8088] IBM PC XT (1982) machines, but I haven't tried it.) If it matters, my IBM PC setup has the 8088 running at 4.77 MHz and has 256 KB of memory, my XT setup has a 7.16 MHz 8088 and 640 KB of memory, and both are set to use the 8087 math co-processor in them. (_Update_: See [this comment of mine](https://github.com/86Box/86Box/issues/3083#issuecomment-1420051163).)
2. Select [ISA] MDA for one of the displays (it doesn't matter which—I first saw it when I had [ISA] CGA as my primary display and [ISA] MDA as my secondary display, but the bug is also reproducible with only the MDA).
3. The other settings can be left at the defaults.
4. Start the machine and have it boot from the IBM PC Advance Diagnostics floppy (the version I'm using is 2.25).
5. Select `0 - SYSTEM CHECKOUT`.
6. If you have both the CGA and the MDA on the same machine, it should ask you `IS A MONITOR ATTACHED TO EVERY DISPLAY  ADAPTER (Y/N) ?` Answer yes.
7. It should list all the connected devices; answer yes if everything is correct.
8. Select `0 - RUN TESTS ONE TIME`.
9. Select the `MONOCHROME & PRINTER ADAPTER` to test.
10. Select either `0 - DISPLAY ADAPTER TEST` or `10 - RUN ALL ABOVE TESTS`.

**Expected behavior**
Either some sort of indication of a passing test or a prompt asking me whether the test passed.

**Actual behavior**
The primary monitor instead displays:
```
ERROR -
MONOCHROME & PRINTER ADAPTER     401 S
 0 - DISPLAY ADAPTER TEST
 
PRESS ENTER TO CONTINUE
?
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: v3.7.1 build 4032

**Comment by OBattler** [comment]
The IBM 5150 Hardware Maintenance and Service manual says to replace the MDA if you get 401 in Advanced Diagnostics. This means I'm going to have to do io.c logging on this and figure out what on Earth is wrong.

Though, I recommend enabling LPT3 and retrying the test - perhaps it's trying to test the parallel port on ports 3BC-3BF that would be included on the MDA and erroring out because it doesn't see it?

**Comment by einstein95** [comment]
> Though, I recommend enabling LPT3 and retrying the test - perhaps it's trying to test the parallel port on ports 3BC-3BF that would be included on the MDA and erroring out because it doesn't see it?

After enabling all the LPT ports (even attaching a generic text printer to them), the error is still present

**Comment by einstein95** [comment]
As MAME's ibm5150 driver with `-isa1 mda` has the same issue, I was able to track it down to the diagnostics program trying to set register 8 ("Interlace & Skew") of the MC6845 to $02 (see [src/devices/video/mc6845.cpp](https://github.com/mamedev/mame/blob/7d9ccfa4261a4a836890b9aac9fa81109fd68598/src/devices/video/mc6845.cpp#L230) in their code)

From [the 6545 datasheet](http://web.archive.org/web/20050223185352id_/http://www.surffi.net/~allu/shared/files/resources/crtc6545.pdf#page=10), this appears to be changing the "Video Display RAM Addressing" from "straight binary" to "Row/Column"

```
Bit 0: INTERLACE MODE CONTROL
		0 - Non Interlace
		1 - Invalid (Do Not Use)
Bit 1: ignored
Bit 2: VIDEO DISPLAY RAM ADDRESSING
		0 - straight binary
		1 - Row/Column
Bit 3: MUST PROGRAM TO "0"
Bit 4: DISPLAY ENABLE SKEW
		0 - no delay
		1 - delay Display Enable one character time
Bit 5: CURSOR SKEW
		0 - no delay
		1 - delay Cursor one character time
Bit 6: NOT USED
Bit 7: NOT USED
```

**Comment by StrangerCoug** [comment]
I also get the same error as @einstein95 even after enabling all the LPT ports and attaching generic text printers to them on my 1982 IBM PC config.

**Comment by StrangerCoug** [comment]
> (The bug might also be reproducible with the [8088] IBM PC (1981) or [8088] IBM PC XT (1982) machines, but I haven't tried it.)
I now have with the default settings for each on the Machine tab (4.77 MHz 8088, 64 KB, no FPU) and LPT3 enabled for each machine. Both of them are affected as well.

**Comment by OBattler** [comment]
> 

Actually, it is setting bit 1, which... what does it even do? The datasheet says it's ignored.

**Comment by OBattler** [comment]
OK, reading the MC6845 datasheet again, it says that Interlace mode register Bit 1 set, bit 0 clear = Normal Sync Mode (Non-Interlace), which means refersh every 60 Hz or so.

**Comment by OBattler** [comment]
I suspect bit 3 of the status register (B/W video signal) is basically dot on/off status... I guess I need to implement the same thing here I did for the Compaq EGA.

**Comment by OBattler** [comment]
I was right but not even that did much to help this. As such, I'm closing this with CANTFIX until I some day figure out what may fix it.
