### ISSUE TITLE
[Feature Request] Add MO Drives support

### ISSUE THREAD

**Issue by Altheos** [86Box/86Box#310]
Hi

I dumped Magnetic Optical medias using DiscImageChef and I would like to know if it's possible to add MO-drive support in 86Box ?
As a temporary fix, I used to use "Removable drive" option from 86Box but it got removed.
MO drive I used is connected to a SCSI card but IDE drives exists.

Regards.

**Comment by OBattler** [comment]
I'd need a data dump from such a drive, of the INQUIRY command, MODE SENSE stuff, etc. If you could provide that, then yes, I could do this.

**Comment by claunia** [comment]
You can get all of that in an xml file using discimagechef device-report with the -d parameter and following the instructions on screen. Then you can attach that xml in this issue and @obattler will have the information he needs

**Comment by Altheos** [comment]
Thanks for the tip Claunia.
Obattler : please find attached the device report from DiscImageChef that may help you.
[device_report.zip](https://github.com/86Box/86Box/files/2313267/device_report.zip)



Regards.

**Comment by claunia** [comment]
@OBattler please note that contrary to ZIP, MO is a standard, so you do not need to copy the manufacturer and model from inquiry, you can put 86Box MO and it will work everywhere. However, I'm not sure in OS/2, where there are two drivers, one from IBM and one from Fujitsu, if those drivers follow the standard or expect their vendors drives. So it should be tested. If the case is they expect their vendors, you only need the manufaturer and model, the rest is the same between @Altheos ' IBM drive and my Fujitsu drive (that I would gladly give you the manufacturer and model strings).

**Comment by OBattler** [comment]
@Altheos Thanks, I'll look at this.
@claunia I see. I'll test this with OS/2 then to see just how tolerant its drivers are.

**Comment by claunia** [comment]
Oh also fujitsu has drivers for DOS, I have not tested them at all, and dunno if Adaptec ASPI works with MO (it should).

**Comment by Altheos** [comment]
There's a DOS driver for this drive too. And it needs an 16 bit AT SCSI Card (5 Mb/s)

**Comment by Altheos** [comment]
Hello,

is there any progress on this ?

Regards.

**Comment by ppgrainbow** [comment]
I have to agree. Is there any progress on magnetic optical drive support?

**Comment by Winins0** [comment]
Hasn't MO drive support added recently?

**Comment by Altheos** [comment]
Can be closed.
