### ISSUE TITLE
Inherit the Earth: Quest for the Orb freezes in the intro

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#3101]
**Describe the bug**
Game freezes on intro. Similar errors occur on PCEM as well..

**To Reproduce**
I used sf2 midi for sound and sb 16 for voices and played on the CD version with everything installed onto the HD

**Expected behavior**
Game to not freeze

**Screenshots**
![Monitor_1_20230210-200758-708708](https://user-images.githubusercontent.com/68984176/218238471-3b806e80-d186-41e8-a205-9f685894e9dd.png)
Where game freezes

**Desktop (please complete the following information):**
Windows 10 3.11

**Comment by Fenix770** [comment]
I can confirm the bug happens on the CD-ROM, version. I use two 486 DX/2 66 mhz machines. One with QEMM and Aztech Clinton and the other with 386MAX and SB AWE 32. On the Aztech configured as SB PRO, freezes on the other machine I use the AWE 32 sound option.. In this last case, the voices run to fast, like it was put in fast forward, nad the game works after that but without the voices and the music shutters.

On the other hand, the floppy disk version works just fine but only include voices at the beginnig of the game. I used the CD-ROM version I found in archive.org. The floppy disk version I  tested is included in Total DOS Collection #20.

Here is the zip file of the floppy version if you want to test it :
It contains 6x 1.44mb Floppy images. The INSTALL.EXE program uncompress the files on the HDD.
[Inherit the earth.zip](https://github.com/86Box/86Box/files/10733413/Inherit.the.earth.zip)

**Comment by ualaa1** [comment]
I was figure out a way to get speech working. You will need to enable "Windows Sound System" as the second soundcard in the soundcard settings. While installing the game, configure Windows Sound System for sound effects.
Sound blaster for sound effects is still broken and causes freezes as of version 4.0

**Comment by ualaa1** [comment]
@Fenix770 By running it with Dynamic Recomplier turned off and the workaround in my previous comment, game works normally, but the soundblaster bug still exist

**Comment by eddmanx** [comment]
Considering that the game has issues with Gravis (per the readme), maybe it also has issues with some Sound Blaster cards?
I tested with a Sound Blaster Pro v2 and speech plays and the game works fine.

As for stuttering and speed issues, it's a sort of demanding game. Select a higher clocked 486 and it should run fine.

As for dynarec related issues, I didn't really notice anything different.

**Comment by OBattler** [comment]
Try changing the Sound Blaster 16 IRQ to 7 - on some machines, IRQ 5 is used by LPT1, and there have been other similar freezes reported because of that, eg. with the Windows 3.1x driver that were solved by changing the IRQ.

**Comment by eddmanx** [comment]
Here's the full machine with the HDD and CD images included: https://drive.google.com/file/d/1_ru1S3cAwh3ZaRaCTZryIKyEMDOOg8u9/view?usp=sharing

**Comment by OBattler** [comment]
Try the latest build - I have since made a fix for the Souund Blaster reset procedure which fixed similar behaivor in an earlier game.

**Comment by eddmanx** [comment]
Tried build 5759; still no speech when using the SB16/AWE option. Actually, now even the SB Pro option doesn't work. The game throws this error: "Speech Error: Detection System Failed to Find Hardware".

Older builds work fine.

**Comment by OBattler** [comment]
How can a build which didn't change a single sound-related piece of code have broken SB Pro detection?

**Comment by eddmanx** [comment]
I didn't say that build broke it. You said to test the latest and see what happens; 5759 was at the time.

I bisected and the last working build for SB Pro is 5727. The next available build, 5734, doesn't work. There are no builds in-between those, so I can't test.

**Comment by OBattler** [comment]
Test the latest build, SB Pro should now be fixed (the code wasn't clearlying DRQ after setting it, now it does).

**Comment by eddmanx** [comment]
Tried build 5773; same error.
