### ISSUE TITLE
Beneath a Steel Sky Buzzing Sound in background

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#3102]
**Describe the bug**
Some kind of soft buzzing sound occurs when starting the game, which keeps on going. Not sure if this is correct behavior. I tested it on another DOS emulator and it didn't have it.

**To Reproduce**
Used SB 16 and CD version of game.

**Expected behavior**
Probably not humming.

**Screenshots**
86-box (If you can't hear the humming, turn up the volume)
https://user-images.githubusercontent.com/68984176/218241138-22161da0-037e-43aa-a7d3-1aa2df8af571.mp4

On other DOS emulator (Dosbox-X)

https://user-images.githubusercontent.com/68984176/218241161-5739b7e6-a934-461b-b712-ad091955bf3b.mp4

**Desktop (please complete the following information):**
Windows 10 version 3.11

**Additional context**
If testing the game on 86Box, turning up the sound gain might help hear the buzzing sound clearer

**Comment by OBattler** [comment]
Does this still happen?

**Comment by eddmanx** [comment]
I don't hear any buzzing sound.

**Comment by OBattler** [comment]
I don't here any even in the 86Box video posted above.

**Comment by OBattler** [comment]
OK, I do hear it now. It may be that DOSBox-X has better filtering or something. In any case, while annoying, this is not a bug.
