### ISSUE TITLE
Jane's F-15 graphic glitches in 3dfx

### ISSUE THREAD

**Issue by amalahama** [86Box/86Box#3104]
Version used: 86box 3.11. Similar glitches also happen in PCEM.

Jane's F-15 shows graphic glitches (repetitive patterns) when using 3dfx emulation. In-game software rendered seems to work fine. I've tried:
* Switching from Voodoo 2 to Banshee
* Changing the 2D Card 
* Unchecking all options in the Voodoo configuration dialoge box
The results in all cases are always the same graphical glitches.

**Comment by eddmanx** [comment]
What kind of glitches exactly? Post screenshots or better yet, a video. Also upload the cfg, nvr and if possible, the HDD file.

**Comment by OBattler** [comment]
Closing this because not enough details given and no further feedback from the reporter.
