### ISSUE TITLE
Add new CGA monitors or D3D shaders

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3105]
**Is your feature request related to a problem? Please describe.**

No. I recently found, DOSBox-X that some color games look more accurate with a specific D3D shader (cga_colors_dga16.fx)
Whith the filter, the red color looks like orange, and seems to be more accurate for the games Prince of Persia 1, and sokoban. But other games like Outrun looks better without this filters because changes the red color of the car to orange.

A. Game that looks better:

1. On PoP 1, looks more natural with the filter, and the prince hair looks more like dark brown instead of blood-red, and the fire is more orange than red.

2. On the Sokoban game, the brick wall is orange like should be, instead of red.

With the filter:
![PoP Orange](https://user-images.githubusercontent.com/31600563/218895807-0cfcb78c-fcb3-4a10-9a3e-7680ba78524c.png)

![Sokoban orange](https://user-images.githubusercontent.com/31600563/218895863-ef5acc8d-4ed2-41e0-b5e4-daa2847fa37a.png)

Without:

![PoP default](https://user-images.githubusercontent.com/31600563/218896736-95028e25-6b4e-4583-b5c2-aabfb53e692d.png)

![Outrun Red](https://user-images.githubusercontent.com/31600563/218895917-a638e130-c3ca-438e-8934-359718a5a9a1.png)

![Sokoban default](https://user-images.githubusercontent.com/31600563/218895932-df4ddc52-aadf-44c4-a6d4-c9e9d00693f4.png)

B. Games that do not:

1. On Outrun the car should be red, so in this case, is better to play the game without the filter.

With the filter:

![Outrun Orange](https://user-images.githubusercontent.com/31600563/218896015-c6479aa7-e441-4ef8-bff4-05927d697669.png)

Without:

![Outrun Red](https://user-images.githubusercontent.com/31600563/218896117-2d5c9fe7-f2e1-41c7-b381-118f1ac86ca0.png)

**Describe the solution you'd like**

May be one of the following:

1.Add Pixel shaders to the D3D render (thought it may be the more complex)
3. Add the emulation of new CGA monitors, with the filter for  CGA,EGA and Tandy 1000 graphics chips. The only limitation is that CGA monitors support up to 640x200 only, so on the real hardware the EGA 640x350 video mode won't work

**Comment by OBattler** [comment]
Scali, or who it was, calculated the more correct color values for CGA, I need to make 86Box's values match those.

**Comment by dhrdlicka** [comment]
Agreed, this should be a separate option. There are displays that also use this palette even when connected to actual CGA video (not an EGA card in a CGA mode), e.g. the original EGA display.

> **5154 Enhanced Color Display**: this is the original EGA monitor, and as already noted, EGA gave us the "canonical" CGA palette by adapting those 16 colors to its 6-bit RGB color model.  However the 5154 can also handle RGBI video directly, either from a CGA card or from EGA in 200-line (15.7 KHz) mode.
> 
> You might suppose that its RGBI signal processing would follow the 5153's, but no: the 4 input bits are internally translated to the 6-bit RGB model, giving exactly the same 16 values we get with native EGA video; this mapping is performed by a ROM chip in the input stage. So on the 5154, even true CGA video yields the 16 EGA-like canonical colors.
