### ISSUE TITLE
Right Mouse button does not work at all in NeXTSTEP 3.3

### ISSUE THREAD

**Issue by tschak909** [86Box/86Box#3112]
**Describe the bug**
When using NeXTSTEP applications (such as DoomEd 0.91) which have right mouse button actions, pressing the right mouse button acts as if the left mouse button were pressed.

**To Reproduce**
1. Get the NeXTSTEP 3.3 archive here: https://archive.org/details/nextstep.tar
2. Unpack.
3. Run 86box appimage.
4. Open DoomEd from the dock
5. Open Project, /LocalId/DoomMaps/project.dpr
6. Select e1m1 from the project inspector
7. Select the Zoom tool
8. Press left mouse button inside map window (should zoom in)
9. Press right mouse button inside map window (should zoom back out)

**Expected behavior**
The window should have zoomed in, then zoomed out. Another example is sector get/fill, which should commit new values for a sector when the right mouse button is pressed.

**Screenshots**
![image](https://user-images.githubusercontent.com/2759782/219516401-7b214df3-91ac-43d5-8637-b503394577d0.png)
![image](https://user-images.githubusercontent.com/2759782/219516471-aef62130-f726-4984-8bd0-abf30369b3e0.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 22.04)
 - 86Box version: Released version of 86Box 3.11 [build 4311]
 - Build information: ^^

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by tschak909** [comment]
Same behavior on build 4445.

**Comment by TC1995** [comment]
Are you using the PS/2 mouse?

**Comment by tschak909** [comment]
Tried both ps2 and serial.

**Comment by OBattler** [comment]
Does it still happen?

**Comment by OBattler** [comment]
This is not an 86Box bug as the mouse buttons are fine in basically everything else, plus it's quite unlikely that both our serial *and* PS/2 mouse emulation would be broken in the same way, therefore, I'm closing this with NOTABUG - likely, NextStep 3.3 may not support right clicking at all.
