### ISSUE TITLE
Hercules graphics card not detected on Treasure Trap game

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3118]
**Describe the bug**
The game Treasure Trap does not detect the Hercules graphics card. This game has Hercules support, but may be the game is using some routine for the detect the Hercules card that is not emulated.
I used the Micoms XT with the high density controller, because the  3 360kb floppy disks are in one 1.44mb floppy.

However, I don't have the real hardware to test if it is an emulator error or the game developers didn't add the Hercules mode.

As a workaround, to use the Hercules card, Is possible to use to use a CGA emulator, (like MGA or RMONO) and force the CGA  mode executing "TT C"at the DOS prompt

Here is the floppy disk image file of the game:

[Treasure Trap.zip](https://github.com/86Box/86Box/files/10774219/Treasure.Trap.zip)

**To Reproduce**
1. Boot any 808x or 286 computer with the Hercules card
2. Run TT
3. The game says that the graphics card is not detected but there  is an Hercules option
4. It gives the parameters to force the video mode and icludes "/H" for Hercules

**Screenshots**
![Treasure Tram Hercules card not detected](https://user-images.githubusercontent.com/31600563/219866536-f5a6631d-6e24-417b-8b39-57f98036dbd5.png)

**Desktop (please complete the following information):**
 - OS:Win 10 21H2
 - 86Box version: 3.11.0.4449
 - Build information: old dynarec Win32.

**Comment by Fenix770** [comment]
Update: Another game that does not detect the Hercules graphics card is the game "Escape fom Hell". But the Hercules mode works if I add the "/H" parameter at DOS prompt.

![Escape from Hell](https://user-images.githubusercontent.com/31600563/220101526-904116f8-3b26-4574-aa19-28d98a7103da.png)

Floppy disk:
[Escape From Hell.zip](https://github.com/86Box/86Box/files/10784197/Escape.From.Hell.zip)

**Comment by TheBombSquad** [comment]
I tested both of the example programs on real hardware, an XT clone using a Hercules-compatible card, also running MS-DOS 3.20. 

'Treasure Trap' is also unable to detect the graphics card on real hardware. Running it with the argument `h` causes the computer to hang with a flashing cursor, and trying to use a CGA emulator (in my case I'm using HGCIBM) causes the machine to hang as well, with a completely blank screen.

'Escape From Hell' also behaves exactly like you describe on real hardware. It fails to launch with no arguments provided, and runs perfectly fine with the `/h` argument provided.

So, at least in the case of my machine, there don't appear to be any differences between the behavior on actual hardware and 86Box.

**Comment by eddmanx** [comment]
@TheBombSquad 

Any chance you could check these too? https://github.com/86Box/86Box/issues/4485

**Comment by OBattler** [comment]
Then this can be closed as NOTABUG.
