### ISSUE TITLE
86Box closing himself after changing config in virtual PC.

### ISSUE THREAD

**Issue by randomsomeone69** [86Box/86Box#3119]
**Describe the bug**
After changing any parameter on the PC emulated by 86BOX, the config is not saved and the app closes

**To Reproduce**
1. Go to settings
2. Change any paramatter (eg. 5,25 floppy -> 3,5 floppy)
3. Click OK at everything
4. Wathes the app closes by himself (or not).

**Expected behavior**
It should save the config and hard reboot the virtual machine.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - 86Box version: v3.11.0.4311
 - Build information: x64

**Additional context**
Maybe running it after hours by upgrading Windows isn't a good idea, because that in the middle of what I was doing. Maybe the old versions of Windows messed on with something or it is because I've modified a file in the hard disk file? I don't know.

**Comment by daviunic** [comment]
This sounds like it's crashing when saving settings. Can you try the 32-bit build with the same settings to see if it works?

**Comment by randomsomeone69** [comment]
By testing with the x86 version, I can tell that the bug doen't happen. That's weird.

**Comment by randomsomeone69** [comment]
After adding a hard drive with the same VM I've flagged the problem, this happened again. And with the x86 version.

**Comment by OBattler** [comment]
Does still happen on the latest build of 86Box?

**Comment by OBattler** [comment]
Closing due to no feedback. When any feedback comes, it can be reopened.
