### ISSUE TITLE
upstream xi8088 BIOS is only 128k

### ISSUE THREAD

**Issue by sharkcz** [86Box/86Box#3125]
**Describe the bug**
The upstream xi8088 BIOS project is building only 128k images (with and without XT IDE BIOS) for some time, but 86Box expects both 128k and 64k variants. Please see https://github.com/skiselev/8088_bios/blob/master/Makefile for details.

**To Reproduce**
N/A

**Expected behavior**
Offer only one xi8088 variant with 128k BIOS, or perhaps a variant with/without the bundled XT IDE BIOS.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
It might make sense to also update the BIOS images to the latest 0.9.9 release. It works fine for me.

**Comment by sharkcz** [comment]
see https://github.com/sharkcz/86Box/commit/aff2c7490e19ae860f21cf0adf968d34b4f40499 for the implementation

**Comment by OBattler** [comment]
I updated Xi8088 to the latest BIOS, and despite the fact the image is 128 kB, the BIOS itself is smaller than 64 kB, so I was easily able to make a 64 kB image as well.

So as such, I'm closing this with NONEEDTOFIX.

**Comment by sharkcz** [comment]
works for me, but can't we "swap" the filenames? So the upstream built `bios-xi8088.bin` will be the 128k variant and `bios-xi8088-64k.bin` the stripped one?
