### ISSUE TITLE
Roms not found no matter where I put them

### ISSUE THREAD

**Issue by dfgdgdgfd** [86Box/86Box#3127]
I've put them in the relevant appdata folder and tried the -r and --roms switch to point them to where they are, but they're still not found.  I got them from the github repository.  Are they meant to not be unzipped or something?

**Comment by Flo9696** [comment]
If you use the beta version, it should be put in:

C:\Users\USER-NAME\AppData\Local\86box\roms

**Comment by dfgdgdgfd** [comment]
I do have them in there, lots of folders such as floppy, hdd, etc.  But I'm not running the beta.

**Comment by dhrdlicka** [comment]
Please make sure that the `roms` folder has the expected structure, i.e. it has `machines`, `video` and other subfolders.

**Comment by dfgdgdgfd** [comment]
It does: 
![fddfdd](https://user-images.githubusercontent.com/26144011/220597845-dbc2dfc9-81fe-45c1-87af-773dd95400c1.png)

**Comment by dhrdlicka** [comment]
What build are you using?

(Please fill out the provided bug report template in the future, it's there for a reason.)

**Comment by dfgdgdgfd** [comment]
x64 b4311

**Comment by Flo9696** [comment]
Under b4311, I have my roms in the same folder as 86Box

Like: 
C:\86Box\roms

**Comment by dfgdgdgfd** [comment]
I have them in the same folder also.  I tried deleting the ones in appdata/local, but the program still can't see the ones in the same folder as the exe.

**Comment by dhrdlicka** [comment]
Looking at your screenshots, it now hit me that your ROM set does not contain the `machines` folder.

**Comment by dfgdgdgfd** [comment]
The roms package on github doesn't appear to have a machines folder and adding one myself doesn't seem to do anything.

**Comment by lemondrops** [comment]
Except the `machines` folder *is* present in the [ROM set for v3.11](https://github.com/86Box/roms/archive/refs/tags/v3.11.zip) that the releases section links to:

![image](https://user-images.githubusercontent.com/2708460/220753139-49e2cf34-4b30-4cfd-80e5-dce2c966bb7f.png)

So, what *exact* link have you downloaded the ROM set from?

**Comment by dfgdgdgfd** [comment]
I was using these: https://github.com/86Box/roms/releases/tag/v3.11

I'm finding that 320x200 is displayed in the wrong aspect ratio but 640x400 is correct.  Is this something to do with the video card being used?

**Comment by jriwanek** [comment]
> If you use the beta version, it should be put in:
> 
> C:\Users\USER-NAME\AppData\Local\86box\roms

I *actively* use the beta version, and just like release, the roms folder goes in the same dir as the 86box executable.

**Comment by dfgdgdgfd** [comment]
I must have been using the 3.7 roms.  I have no idea what's going on with 320x200 basically looking like a portrait oriented window.  tried two different video cards
