### ISSUE TITLE
S3 86c911 (Orchid Fahrenheit 1280) not properly rendering gradients under Windows NT 3.5x

### ISSUE THREAD

**Issue by B-F-1-0** [86Box/86Box#3139]
**Describe the bug**
When using the S3 86c911 (Orchid Fahrenheit 1280) display adapter (with the S3 Compatible driver in Windows installed) on Windows NT 3.5x, the gradients don't appear to render properly, leaving black marks on the test display. As a result, applications like FreeCell experiences display problems. Both Windows NT 3.50 and NT 3.51 are affected. This doesn't affect Windows NT 3.1, so unsure if this is a bug with 86Box, display adapter, or NT 3.5x.

This was tested under a dual boot machine of the config file below, with all three NT 3.x versions running under the same virtual hard drive.

**To Reproduce**
1. Create a virtual machine using a config that uses S3 86c911 (Orchid Fahrenheit 1280), I used the config provided in the cfg file below.
2. Install Windows NT 3.50/3.51 as normal.
3. When you reach display settings during set, run test. First symptoms of problems occur, where black marks are over the gradients.
4. Main symptoms also occur if you open FreeCell, where window background is transparent; see NT 3.5x screenshots below.

**Expected behavior**
Gradients are rendered properly; see NT 3.1 screenshots below.

**Additional Files**
[cfg file and nvr](https://github.com/86Box/86Box/files/10834381/issuefiles.zip)

**Screenshots**
- **Windows NT 3.51** (bugged)
![Monitor_1_20230226-125706-033033](https://user-images.githubusercontent.com/115908504/221428769-24b21d0e-0a03-491c-b2c6-5794b8ba976e.png)
![Monitor_1_20230226-125821-189189](https://user-images.githubusercontent.com/115908504/221428770-2cfa53ec-2f3c-46e7-9433-7f45a1399576.png)
- **Windows NT 3.50** (bugged)
![Monitor_1_20230226-125940-548548](https://user-images.githubusercontent.com/115908504/221428771-46d0517a-0c9f-4412-ab29-aa3f795cce5f.png)
![Monitor_1_20230226-130003-173173](https://user-images.githubusercontent.com/115908504/221428772-67be28ed-7396-4861-b7a2-1e0ac548c7ca.png)
- **Windows NT 3.1** (correct)
![Monitor_1_20230226-130152-942942](https://user-images.githubusercontent.com/115908504/221428774-50b6e9ae-e79d-499d-968d-e38f5d3397ca.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 v22H2 Enterprise (x64)
 - 86Box version: 86Box v3.11 [[b8bfaa9](https://github.com/86Box/86Box/commit/b8bfaa926937d38ffa0f8a1fcf685312bfb038b5), build 4451] x86
 - Build information: Old Dynamic Recompiler Win32

**Comment by TC1995** [comment]
I think this is a driver bug, as the IBM/WD 8514/A driver does the same in terms of code, just corrected.

**Comment by OBattler** [comment]
Then I'm closing this for driver bug.

**Comment by TC1995** [comment]
Actually, turns out this is fixed even without driver patching.
