### ISSUE TITLE
Add Packard Bell PB930 and Packard Bell PB950

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3142]
Can you please add support for the Packard Bell PB930 and Packard Bell PB950 in 86Box?

The BIOS Images can be found here: https://theretroweb.com/motherboards/s/bcm-fr510#downloads
More specs here: http://www.uktsupport.co.uk/pb/mb/930.htm

Chipset: ALi Aladdin V M1541/M1543C AGP/PCI/ISA Chipset
Video: ATI 3D RAGE IIC AGP 3D Accelerator
Audio: Cirrus Logic CS4235 Audio Chipset

**Comment by pankoza-pl** [comment]
the onboard Video is not emulated yet, but we can ignore it just like on the 486 STPC's

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
