### ISSUE TITLE
Add Packard Bell PB600

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3145]
Add Packard Bell PB600 in 86Box please. Thank you.

The BIOS Images can be found here: https://theretroweb.com/motherboards/s/packard-bell-pb600#downloads
More specs here: http://www.uktsupport.co.uk/pb/mb/600.htm

Chipset: PCI064B Super I/O controller
VL82C593 controller
Video: Built-in, Cirrus Logic Alpine GD5430 2D Accelerator

**Comment by OBattler** [comment]
I'm sorry but I'm closing this because the VLSI northbridge and southbridge are completely undocumented and, due to their complexity, not feasible to reverse engineer.

**Comment by TheDell1998** [comment]
> I'm sorry but I'm closing this because the VLSI northbridge and southbridge are completely undocumented and, due to their complexity, not feasible to reverse engineer.

Oh really? I'm using the BCM SQ-588 Machine with SiS 501 Chipset that supports PhoenixBIOS Version 4.04 and Packard Bell Machines support VLSI chipsets as well.

**Comment by TheDell1998** [comment]
Oh really? I'm using the BCM SQ-588 Machine that supports PhoenixBIOS machine with SiS 501 chipset and Packard Bell Machines with VLSI chipset as well.
