### ISSUE TITLE
Add Packard Bell Machines

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3146]
**Is your feature request related to a problem? Please describe.**
I want some Packard Bell systems to be added like the PB930/950, PB600, PB860, PB980, PB992, OEM machines, etc. in 86Box.

**Describe the solution you'd like**
I have usually seen Compaq, IBM, Gateway 2000, etc. on this emulator, but why not some Packard Bell systems.

**Describe alternatives you've considered**
Some Packard Bell systems use the on-board video and audio whatsoever.

**Additional context**

**Comment by TC1995** [comment]
It all depends on what they have documented and what not (SIO, chipset, if with on-board video, etc).

**Comment by OBattler** [comment]
We currently emulate the PB410, PB520R, PB640, PB810, and Bora Pro, and PB300SX and PB450 are on the to do list, and I'm looking into somehow getting the PB570's built-in CL-GD 5430 vieo BIOS to work as well so that can also be added.

PB600 uses an undocumented VLSI chipset. Of the rest mentioned, PB980 and PB992 are not at all feasible as they use SiS chipsets with on-chip graphics. PB930/950 are feasible, but they seem to be just run of the mill Award BIOS machiens with ALi Aladdin V chipset.

**Comment by TheDell1998** [comment]
> We currently emulate the PB410, PB520R, PB640, PB810, and Bora Pro, and PB300SX and PB450 are on the to do list, and I'm looking into somehow getting the PB570's built-in CL-GD 5430 vieo BIOS to work as well so that can also be added.
> 
> PB600 uses an undocumented VLSI chipset. Of the rest mentioned, PB980 and PB992 are not at all feasible as they use SiS chipsets with on-chip graphics. PB930/950 are feasible, but they seem to be just run of the mill Award BIOS machiens with ALi Aladdin V chipset.

Oh yeah? Are you adding the Packard Bell PB570 ROM from PCem to 86Box?

**Comment by TheDell1998** [comment]
And also, Can you add the Packard Bell PB930 or PB950 ROM with ATI 3D Rage IIC onboard video to the 86Box please? Because they uses the ALi Aladdin V chipset on Super Socket 7 in 86Box as well.

**Comment by pankoza-pl** [comment]
i would like the Via Apollo Pro 133-based Slot 1 Packard Bell Phoenix (MSI MS-6199VA) as it has no onboard video and a emulated onboard audio, and it has a AwardBios with Packard Bell Splash Screen, and working ACPI unlike the Bora Pro
That Packard Bell should be easiest to add

**Comment by TheDell1998** [comment]
I would like the Intel 430NX-based Socket 5 Packard Bell PB570/580/590/620/630/650 (Intel Advanced/HL Hillary) as it has both Cirrus Logic GD5430/5434 onboard video, and it has a AMI BIOS with Packard Bell Logo, and working APM. That Packard Bell should be easiest to add.

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
