### ISSUE TITLE
Add NVIDIA Video Cards

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3150]
Attention developers,
Please add the following NVIDIA Video Cards except the GeForce in 86Box including:
NVIDIA RIVA 128
NVIDIA Vanta
NVIDIA RIVA TNT
NVIDIA RIVA TNT2
NVIDIA RIVA TNT2 M64
NVIDIA RIVA TNT2 Pro
NVIDIA RIVA TNT2 Ultra
Thank you.

**Comment by OBattler** [comment]
Sorry, but this is not feasible, at all, due to a complete lack of documentation.

**Comment by LeoKids** [comment]
Sorry OBattler,but there isn't lack of documentation.

I'll show the specs here

https://vgamuseum.info/images/doc/nvidia/rivatnt2_specs.pdf
https://vgamuseum.info/images/doc/nvidia/riva128_specs.pdf
https://vgamuseum.info/images/doc/nvidia/vanta_specs.pdf
https://vgamuseum.info/images/doc/nvidia/rivatnt_specs.pdf

**Comment by TC1995** [comment]
We mean register level documentation as well as accelerator/blits documentation, which there's none of.

**Comment by CheeseWedgeYT1** [comment]
I found out this would be legit impossible
[nvidia_docu_level_specs.pdf](https://github.com/86Box/86Box/files/14859471/nvidia_docu_level_specs.pdf)

**Comment by cartifanwlr** [comment]
We're aware of the third party documentation, but it just isn't enough, and even if it is we don't have anyone who deals with 3D (which is an entirely different complex beast than 2D)

**Comment by cold-brewed** [comment]
These cards are not in scope for 86Box.
