### ISSUE TITLE
Add Compaq Presario 2200 ROM

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3158]
**Is your feature request related to a problem? Please describe.**
Not a problem; just a new machine.

**Describe the solution you'd like**
The Compaq Presario 2200 series was a commonplace computer in the late 90s. It featured:

A Socket 7 motherboard with an Cyrix chipset
An Cyrix MediaGX GXI-180BP 180 MHz CPU (66MHz Bus Speed)
An on-board Cyrix CX 5510 graphics chipset
An on-board Cyrix XpressAUDIO audio chipset (not yet implemented, doesn't necessarily have to be at this time)
An on-board IDE and floppy controller

I would very much like to see this machine be implemented. Please let me know if there is any additional detail needed for the motherboard.

**Describe alternatives you've considered**
It's very exciting to see the 4500 series; this is what inspired me to request the 2200 series in the first place. For now, if I want my retro Compaq fix, I can easily emulate a 4500 series.

**Additional context**
Datasheet for the Cyrix (optional) is attached.
Link to PDF file: http://datasheets.chipdb.org/Cyrix/MediaGX/gxmdb_v20.pdf

**Comment by pankoza-pl** [comment]
> Not doable because of the on-chip graphics card.

but we can ignore it just like on the STPC
