### ISSUE TITLE
Add Crystal CS4280-CM, CS4281-CM, CS4614-CM Support

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3159]
**Is your feature request related to a problem? Please describe.**
"Best" soundcard available currently is the Crystal CS4235/4236, a quite similar card.

**Describe the solution you'd like**
Add support for CS4280-CM, CS4281-CM, CS4614-CM card. Has better drivers and DOS compatibility than Crystal CS4235/4236's card.

**Describe alternatives you've considered**
Stick to Crystal CS4235/4236.

**Additional context**
Maybe the "highest end" soundcard the emulator could/should support since the cut-off point for other features is around the same timeframe the card came out, eg. circa 1999. Actual 5.1 support is probably not needed.

**Comment by OBattler** [comment]
Not feasible because no documentation.
