### ISSUE TITLE
Multiple EMS boards bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#316]
Hello

Beforehand thanks for adding these last boards and machines!
 
I tested the Micro mainframe 5150T. It works when only when 1ISA slot is selected. 
I configured the ISA slot 1 with "board 1" with 2048 kb. and ISA slot 2 with 1024kb  and "board 2"

The problem begins when I return to ISA slot 1 configuration and find the configuration is overwrritten with the ones of slot 2 .
So, in short, I can only use 1 board. 
I tested with the latest commint of Varcem and it works, and also tested with the memory map information utilities of the 5150T board.

Thanks!

**Comment by OBattler** [comment]
I fixed this yesterday, now it works just like it does in VARCem. :p

**Comment by Fenix770** [comment]
Now it works!

Thanks!
