### ISSUE TITLE
Add additional Aztech Labs' ISA Sound Cards

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3160]
Add Sound Galaxy BXII, NXII, NXPRO, NXPRO16, BASIC16, PRO16L, Extra, Basic AUDIO16, Pro 16 II, Orion16, Waverider 32+, Nova 16 Extra II-3D, Waverider Pro 32-3D, Pro16III-3D PnP, Waverider Pro 32-3D (I) PnP, Waverider Platinum-3D PnP, SC16-3D, and SC16-3D(W) support for this card. Except the Pro 16 AB, and Nova 16 Extra. Because they already exists with Aztech Sound Galaxy Washington/Clinton sound cards. Thank you.

**Comment by OBattler** [comment]
Not feasible because no documentation,
