### ISSUE TITLE
Add Compaq Presario 2200 ROM Support (without Cyrix onboard video and audio)

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3161]
I would like the Intel-based Socket 7 Compaq Presario 2200 without Cyrix onboard video and audio, and it has a PhoenixBIOS with Compaq Splash Screen, and working APM unlike the Presario 4500 That Compaq should be easiest to add in 86Box.

**Comment by TheVirtualComputer** [comment]
Adding this system would require support for the MediaGX's built-in chipset though.

**Comment by TheDell1998** [comment]
Also, there's a datasheet for Cyrix MediaGX built-in chipset for the link:
Link for the datasheet: http://datasheets.chipdb.org/Cyrix/MediaGX/gxmdb_v20.pdf

**Comment by OBattler** [comment]
That thing can't be implement without its on-chip graphics, so not.
