### ISSUE TITLE
Add Packard Bell PB570

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3162]
I would like the Intel 430FX-based Socket 5 Packard Bell PB570 (Intel Advanced/HL Hillary) as it has both Cirrus Logic GD5430/5434 onboard video, and it has a AMI BIOS with Packard Bell Logo, and working APM. That Packard Bell should be easiest to add.

**Comment by OBattler** [comment]
Closing for duplicate, it's already part of the other request issue.
