### ISSUE TITLE
Add Compaq Presario CDS Machines (with onboard video and without onboard audio)

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3165]
**Is your feature request related to a problem? Please describe.**
I want some Compaq systems to be added like the CDS Machines, OEM machines, etc. in 86Box.

**Describe the solution you'd like**
I have usually seen Packard Bell, IBM, Gateway 2000, etc. on this emulator, but why not some Compaq systems.

**Describe alternatives you've considered**
Most Compaq systems use the on-board video and audio whatsoever.

**Additional context**
In 86Box, Only Compaq Presario 2240, and 4500 are still there on both Compaq Machines.

**Comment by pankoza-pl** [comment]
Intel PhoenixBIOS doesn't like 86Box, so no
the Via Apollo Pro 133-based Packard Bell Phoenix is a better candidate, as it has a emulated Ensoniq AudioPCI Audio, and it's AwardBios works on 86Box

**Comment by dhrdlicka** [comment]
> For a machine to be added, the BIOS files must be extracted from the computer in question. Then, it must be programmed into 86Box by way of adding several lines of code to ensure the machine functions properly.

That is assuming that all the onboard components are already emulated. If they're not, that opens a whole other can of worms.

**Comment by OBattler** [comment]
I think this can closed anyway for being too vague.
