### ISSUE TITLE
Right shift key

### ISSUE THREAD

**Issue by ericdestefano** [86Box/86Box#3169]
Hello, 

I saw an earlier report that the right shift was not working, but was corrected back in August or so.  Version 3.11 on Windows appears to have the same issue.

**Comment by OBattler** [comment]
See if the latest build of 86Box still has the same problem.

**Comment by ericdestefano** [comment]
I can confirm in build b4673 the issue is still present (Windows x64)

**Comment by OBattler** [comment]
I can not confirm this at all. I literally just tested and right shift is working just fine.

**Comment by OBattler** [comment]
I'm closing this because I can't reproduce this at all, which indicates a problem with the user's host system rather than with 86Box.
