### ISSUE TITLE
Compiliation fails on tag: v3.7.1

### ISSUE THREAD

**Issue by crim491** [86Box/86Box#3178]
**Describe the bug**
Compile of branch tag v3.7.1 fails.

**To Reproduce**
1. Clone repository
2. Change into clone repository
3. git checkout v3.7.1 -b 371
4. cmake ./
5. make

**Expected behavior**
A clean, operational binary.

**Screenshots**
/home/crim491/86Box/src/include/86box/bswap.h:76:43: error: missing binary operator before token "("
   76 | #if defined __has_builtin && __has_builtin(__builtin_bswap16)
      |                                           ^
/home/crim491/86Box/src/include/86box/bswap.h:85:43: error: missing binary operator before token "("
   85 | #if defined __has_builtin && __has_builtin(__builtin_bswap32)
      |                                           ^
/home/crim491/86Box/src/include/86box/bswap.h:94:43: error: missing binary operator before token "("
   94 | #if defined __has_builtin && __has_builtin(__builtin_bswap64)

**Desktop (please complete the following information):**
 - OS: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

 - 86Box version: Tag v3.7.1
 - Build information: Default build of v3.7.1 from the repository.
 - Built with gcc:
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Additional context**
Nothing special about the build.

**Comment by jriwanek** [comment]
Is there a particular reason you're using such an old version?

**Comment by crim491** [comment]
I didn't know it was an old version. That was the the largest version tag in the `git tag` output. I do think though the earlier versions would have the same issue.

**Comment by jriwanek** [comment]
https://github.com/86Box/86Box/releases/tag/v3.11

**Comment by jriwanek** [comment]
For reference 3.11 > 3.7 (It's not 3.1.1)

**Comment by crim491** [comment]
Oh there it is.
v2.00
v2.02
v2.03
v2.04
v2.05
v2.06
v2.07
v3.0
v3.1
v3.11 <-------
v3.2
v3.2.1
v3.3
v3.4
v3.4.1
v3.5
v3.6
v3.7
v3.7.1

**Comment by jriwanek** [comment]
Yup, unfortunately, there's nothing we can do about the sort order git itself uses.

**Comment by crim491** [comment]
Ok, it looks like you guys fixed the problem. I did fix it on my side but no need to submit a PR!

**Comment by jriwanek** [comment]
I reccomend using latest master btw, unless you have specific reason to use a versioned snapshot.

**Comment by crim491** [comment]
On a personal level, I like to use a tagged version or a version branch because at some point it was decided the code was good enough to mark it. No active development is being done at that specific point in time.
