### ISSUE TITLE
Tandy 1000 SL/2 bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#318]
Hello

1. I tested the game Bubble Bobble in Tandy 1000 SL/2 machine (I'm not sure about 1000/HX). The game starts but the music is too slow and when start the game on "round 1" the bubble of the dragon never blasts and the enemies fall from  the top to the bottom of the screen until they disappears.
On the Laser XT with 8086/10 and EGA graphics and card works with some slowdown but it's playable.
The same happens with Pcem. But it Works on dosbox.

btw: I don't know if it is a problem with CGA emualtion, because it works with CGA graphics but with severe slowdowns.

2. I also tested PC Paintbrush 1.22 for Windows in Windows 2.03 and the monochrome PCX files opens correctly but the color ones appears duplicated. I am using the Tandy 640x200x4 video driver.

![20180913_225525](https://user-images.githubusercontent.com/31600563/45525236-81827780-b7a8-11e8-9b5c-35bf3b861f22.png)

**Comment by OBattler** [comment]
For #1, see if it also happens on PCem as our Tandy emulation is pretty much unchanged from there.
For #2, .PCX bitmaps are device-dependent, so what you're seeing is probably normal.

**Comment by OBattler** [comment]
For #1, see if my 808x changes fix it after I commit them.
For #2, now that I think of it, is *IS* normal - as I said above, .PCX bitmaps are device-dependent, so in this case PC Paintbrush is interpreting each two 2 bpp lines as one 4 bpp line, resulting in what you see.

**Comment by Fenix770** [comment]
Hello.

Thanks for the reply. I'll test it. Also I found another bug related to Tandy 1000 machines.
The 10h 640x200 4 colors video mode have inverted colors. In Deskamte 2 the white and yellow colors are  inverted as well as green and red in Windows 2.0.  I created a thread in PCem with details for this bug here is [https://pcem-emulator.co.uk/phpBB3/viewtopic.php?f=2&t=3105&p=11248&hilit=deskmate#p11248](url).

Thanks!

**Comment by OBattler** [comment]
The latest commit fixes the colors in the 640x200x4bpp modes. The two bits were being in the wrong order, resulting in colors 1 (binary 01) and 2 (binary 10) being swapped. Colors 0 (binary 00) and 3 (binary 11) were unaffected because the two bits had identical values.

**Comment by Dizzy611** [comment]
Can confirm this bug still exists in 3.4.1 (build 3738, Windows x64, Old Dynarec build with dynarec off)

**Comment by OBattler** [comment]
I'm closing this because it's mostly fixed, except for the Bubble Bobble stuff which is already being tracked elsewhere.
