### ISSUE TITLE
cppcheck log

### ISSUE THREAD

**Issue by Randrianasulu** [86Box/86Box#3184]
**Describe the bug**
I just run cppcheck -j 8 -x c++ * > ../cppcheck.log 2>&1

**To Reproduce**
1. install cppcheck
2. git clone 86box git
3. cd 86Box/src
4. run cppcheck

**Expected behavior**
no errors

**Screenshots**
no screenshot

**Desktop (please complete the following information):**
 - OS: Termux/Android
 - 86Box version: 1484a70ebb6d272511c7a160a3d951490fcb7d65
 - Build information: cppcheck run after I get new dynarec build

**Additional context**
Some errors might be false positive.

[cppcheck.log](https://github.com/86Box/86Box/files/10914006/cppcheck.log)

**Comment by OBattler** [comment]
This can now be closed.
