### ISSUE TITLE
Mouse wheel won't work right

### ISSUE THREAD

**Issue by mishiro1** [86Box/86Box#3187]
Hi, congrats on the project! 

So, i have an issue with the mouse wheel, i can't get it to work.
My machine is a Super Socket 7, (Via MVP3) SEMA PRO, and a Pentium 100, with Windows 98 Se.
I tried the input setting with Standard PS/2 mouse with the wheel.
Tried other mice, including installing the Intellimouse driver, but to no avail.
The wheel responds, but it bounces up and down haphazardly, or do nothing at all.
Hope this helps! 

Host Machine: i5 4430 with Lubuntu 22.04

**Comment by OBattler** [comment]
Does this work now?

**Comment by mishiro1** [comment]
> Does this work now?

I didn't tested again.

**Comment by OBattler** [comment]
Then please do.

**Comment by OBattler** [comment]
Closing this due to Efflixi later reporting the wheel working fine.
