### ISSUE TITLE
cdrom eject locks removable media on macOS 13 Ventura until exit 86box

### ISSUE THREAD

**Issue by Joel-Mckay** [86Box/86Box#3194]
cdrom eject locks removable media on macOS 13 Ventura until emulator is shutdown

**To Reproduce**
Using 86Box-macOS-x86_64+arm64-b4311.zip of 86box release
1. Go to CD icon and mount removable USB drive/folder as emulator virtual CD
2. Click on emulator "pause" icon in upper left, minimize 86box, than maximize  
3. Eject virtual CD   
4. A program using USB drive error occurs when try to unmount host MacOS USB drive.
5. Click on emulator "play" icon in upper left
6. still cannot safely remove host's OS previously in-use USB drive
7.  shutdown guest OS in VM
8. Host macOS can now unmount/eject USB drive
 
**Expected behavior**
A use case where removable host media is removable when no longer in use.

**Additional context**
Running 86box direct from Terminal.app shell

**Comment by cold-brewed** [comment]
I can confirm this issue on macOS. However, I don't think it is specific to macOS and will likely happen on other platforms as well.

I have an idea of what may be causing this. Let me take a look.
