### ISSUE TITLE
Add Shuttle HOT-597

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3198]
VIA Apollo MVP3 Chipset
AwardBIOS
Super Socket 7

I would like a Shuttle HOT-597 board to be added to 86box.

**Comment by pankoza-pl** [comment]
we already have AwardBIOS Super Socket 7 boards, but this one seems nice to add, because it doesn't have a onboard video or audio

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
