### ISSUE TITLE
Slirp: Long TCP/IP transfers lose FIN packet

### ISSUE THREAD

**Issue by Carmina16** [86Box/86Box#3199]
**Describe the bug**
When a TCP/IP data transfer to the 86box client tooks longer than a certain time, it never completes, as the FIN packet is never received after last data packet.

**To Reproduce**
1. Setup a network card connected via slirp.
2. Download a large (500kB+) file from a server on the host computer, monitoring the incoming packets.
3. Notice the short `PSH` packet being the last portion of the file.
4. Observe transfer stalling.

**Expected behavior**
A short `PSH` packet is received, followed by `FIN PSH` packet from the server going to `FIN_WAIT_2` stage.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - 86Box version: 4384
 - Build information: old dynarec, i386

**Comment by OBattler** [comment]
Makes me wonder if this is a host problem, since I noticed the same kind of thing happened with FileZilla for FTP downloads - the packet to finish them is never sent, so they get stuck at 100%.

**Comment by OBattler** [comment]
I'm closing this for host problem (though it may also have been fixed by us now using proper, statically linked libslirp).
