### ISSUE TITLE
Toshiba T1200 floppy issues

### ISSUE THREAD

**Issue by waltje** [86Box/86Box#320]
The T1200 uses a custom floppy drive (3.5" 720K) with their own TC8565 controller, which does not seem to be 100% compatible.  Effectively, you have to set the drive type to 5.25/360K in the emulator to make it work at all (it will boot then), but of course it then errors out at the upper half (tracks 40+) of the disk...

The 8565 datasheet and T1200 maint manual have info on this.

**Comment by OBattler** [comment]
The latest commit fixes the issue - the change line port (port 3F7) was missing, but the T1200 (and probably also the T1000) expects it.

**Comment by waltje** [comment]
Confirmed. Does not seen to be needed by T100, only the T1200.
