### ISSUE TITLE
IBM PS/2 model 60 configuration error

### ISSUE THREAD

**Issue by Computerboi13** [86Box/86Box#3202]
I know errors 162 and 163 appears because the machine isn't configured; the real problem is, when i boot the reference disk and start automatic configuration, when it ends, errors 162 and 163 reappears.
I tried deleting the nvr file, disabling time synchronization and adding 2mb but nothing worked.

Host system is Windows 10 x64, 86box 3.11 build 4311 x64

Files:
[cfg and nvr files.zip](https://github.com/86Box/86Box/files/10951873/cfg.and.nvr.files.zip)

**Comment by Computerboi13** [comment]
It clearly says im using the latest build.

**Comment by Computerboi13** [comment]
now errors 16000 fff4 201 and 164 appears, but changing the memory size above 1mb seems to fix it,
There isn't a way to go with 1mb for now?, just asking i don't have a problem going with 2mb.

**Comment by OBattler** [comment]
See if this works now.

**Comment by Computerboi13** [comment]
The main problem if this issue was resolved i guess. The error 160000 FFF4 201 and memory size error 164 keeps appearing but like i said before, this isn't really a problem for me, i don't know if it might be a problem for others.

**Comment by neozeed** [comment]
I'mn getting the 164 errors with build 4634..
[rf5060a.img-model60.zip](https://github.com/86Box/86Box/files/12244997/rf5060a.img-model60.zip)

I attached my reference disk.  Going to try 4755

![image](https://github.com/86Box/86Box/assets/9031439/b4e2ebb5-b80f-4ca9-bb9a-d42ef7bd86e4)

**Comment by neozeed** [comment]
booted up, got the 164, ran the reference disk version 1.08  got 

![image](https://github.com/86Box/86Box/assets/9031439/2ae89dcf-fc33-4487-8565-6ba2204b1c8d)

dropping to 2mb of ram shows only one board, the 0xddff

with 4mb it shows 2 cards.. .maybe they are stomping on eachother by default?

**Comment by TC1995** [comment]
Use a newer ADF for the ESDI one.

**Comment by neozeed** [comment]
I knocked the ram down to 2mb and it didn't complain... 

![image](https://github.com/86Box/86Box/assets/9031439/4efb84eb-1f63-4bd8-98ed-cff98035252b)


Ill update the adf for sure!  is there a known good checksum or filesize?

**Comment by TC1995** [comment]
Just use the one from 80 or something, for the ESDI ADF that is.

**Comment by neozeed** [comment]
![image](https://github.com/86Box/86Box/assets/9031439/5de1bf37-0fcc-4ae5-8c7f-1b604e4f7928)
so it turns out im already using the esdi one from the ps/2 80... let me check its settings  then

**Comment by neozeed** [comment]
![image](https://github.com/86Box/86Box/assets/9031439/a4bdc0e6-ae2c-4686-b8bb-837eee9f6b82)
80 and 60 have the same ESDI parameters..

**Comment by neozeed** [comment]
![image](https://github.com/86Box/86Box/assets/9031439/7f12bc53-7a1c-45d0-a6af-508a5db27eff)
just noticed the rom isn't being mapped....

**Comment by neozeed** [comment]
For any future time travelers, the updated DDFF driver sure helped as you can map the BIOS into the UMB where it belongs.  I copied the settings from the ps/2 model 80 above, and I was able to get a working system

[rf5060a.zip](https://github.com/86Box/86Box/files/12245376/rf5060a.zip)
[DDFF.zip](https://github.com/86Box/86Box/files/12245377/DDFF.zip)

Further, I dropped from 2mb of ram, got that working, tried 4mb, and then 6mb.
![image](https://github.com/86Box/86Box/assets/9031439/4b9e94d7-0a5e-4a69-b2f5-736fcee402fa)
