### ISSUE TITLE
Add ASUS SP97-V and Jetway J-TX98B Support

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3204]
It would be great  if 86Box would support emulating a ASUS SP97-V and Jetway J-TX98B motherboard. Both these motherboards are Socket 7 boards with an SiS 5597/5598 chipset. They don't support AGP slot, 2-4 PCI slots and 2-3 ISA slots depending on revision. RAM type is SDRAM.

**Comment by pankoza-pl** [comment]
we don't have that chipset emulated yet

**Comment by OBattler** [comment]
- TheDell1998: I already told you those SiS chipsets are not doable because on the on-chip graphics.
