### ISSUE TITLE
ROMs located on a network share - some optimization needed

### ISSUE THREAD

**Issue by Torinde** [86Box/86Box#3208]
**Is your feature request related to a problem? Please describe.**
I want to run 86box with the ROMs folder at a SMB network share, e.g.: 
`86box.exe -R "\\NetworkShare\Folder1\Folder2\FolderX\ROMs\"`

Currently, it needs a LOT of time to start and when I clicked Settings, then the UI again became unresponsive... haven't waited AGAIN a lot - maybe eventually it'll open, but if that wait will happen on every click it's too much.

Maybe my WiFi is too slow (although having the HDD.IMG on the network share is no problem at all).

PS. To complicate further - one of the network paths that I want to use starts with "_" and has a space in the network share name:
`86box.exe -R "\\_Network Share\Folder1\Folder2\FolderX\ROMs\"`

**Describe the solution you'd like**
Some way of caching or partial-loading, e.g. at startup of 86box.exe read the list of ROMs available from the network share and at Guest machine (re-)start temporary copy/cache only the ones used by the current configuration?

**Describe alternatives you've considered**
Obviously having the ROMs locally works.

**Additional context**

**Comment by OBattler** [comment]
I don't think I can fix this - I'd need a platform-agnostic way to check if a file is present without actually opening it, and I'm not sure that exists.

**Comment by Torinde** [comment]
It's OK to open them, but it seems currently that happens too often and with more files than actually utilized. My question is if some of that can be reduced:

What about opening ONLY the files needed for the current configuration (or those for the default "IBM PC first model" when starting for the first time/without a user configuration)? 

As for the Settings menu (if it needs to "know" what ROMs are available) - "open" all files, but only once, then save the list of files locally, so that next time 86box runs there is no need to open all files again, but only the actually used ones.
Alternatively: Settings menu to assume all ROMs are available - and ONLY the selected ones to be opened at machine (re)start.
- for both cases: if at some moment it's discovered some "expected" file isn't present (anymore) - throw the current "missing ROMs" error message - even better if the specific missing file/path is mentioned.

If some of the above is not optimal for other uses - then making it a command line/.cfg option?

Finally, it'll help if there is some progress indicator, so that user can see that 86box is working properly and hasn't crashed, but just the ROMs are located at a "slow place" - maybe a "opening ROMs....5% ready" text in the title bar?

**Comment by Torinde** [comment]
I understand. What I suggest is to change the procedure, so that the check happens less often (and/or for less files).

>Copying or caching the files elsewhere would actually decrease efficiency
OK, what about caching only the list of files (after a single slow check) - on the first launch of 86box.exe and from then onwards _assuming_ they're still there? If a file gets missing - at that point throw show the error message currently shown when run without any ROMs.

**Comment by cold-brewed** [comment]
The rom checks performed at startup and when opening settings are essentially the same check. Introducing a cache would involve a fair amount of change and additional complexity to the existing implementation for little gain. 

The problem you mention is an edge case that is easily mitigated by storing the roms locally or only copying the ones you need. Therefore the changes you're requesting are unlikely to get implemented. 

In addition, as @OBattler mentioned above, anything that is implemented must also work in a cross-platform manner.

On the topic of caching, I am reminded of the famous quote by Phil Karlton:

> There are only two hard things in Computer Science: cache invalidation and naming things.

**Comment by dhrdlicka** [comment]
> I don't think I can fix this - I'd need a platform-agnostic way to check if a file is present without actually opening it, and I'm not sure that exists.

Technically a platform function could be added for this, but I am not sure if this edge case is really worth the effort.

**Comment by OBattler** [comment]
Closing this with CANTFIX.

**Comment by Torinde** [comment]
Related:
- https://github.com/86Box/86Box/discussions/5641
