### ISSUE TITLE
COM Ports Present even if disabled in Settings

### ISSUE THREAD

**Issue by nt4boy** [86Box/86Box#3209]
86Box Version 3.11. build 4311
Manager 1.7.4
Host machine is Windows 10 Quite old i7 that is capable of running VMWARE Workstation.

Machine [i440BX]Microsoft Virtual PC 2007
 in the Manager settings, I have selected zero COM ports and zero LPT ports.

In Win 98 FE, in Device manager, it reports  COM1 and COM 2, all working.
Also a LPT1 port that is broken

In W98, I have removed all these devices from device manager, but on the next boot, they are reinstalled.
How and why?

The host machine does have an actual PCI card COM port (registered as COM3) that I want to connect to, but I don't understand how that port should be selected so it can be used by the W98 VM in 86 Box.

Can someone clarify how this should work please or what I may be doing wrong.

Thanks

**Comment by TC1995** [comment]
Most likely a sio or motherboard bios issue.

**Comment by nt4boy** [comment]
Ok, is that something I can fix, or should I try another board perhaps?

**Comment by TC1995** [comment]
For now, just use another board.

**Comment by nt4boy** [comment]
Ah, found the BIOS. Didn't see how to open it, but changing the mother board forced that, so may be able to sort it.
Thanks

**Comment by nt4boy** [comment]
Yes, sorted now. Thing I think I get now is that the BIOS takes priority over what the local hardware is, and the Setting page is additional, like maybe adding a USB based item.
I have specified a single port in the BIOS and nothing in the settings, and I have just the COM1 one in Device Manager.
Will that get piped directly through to the COM3 hardware  on the host without any direction from me?

**Comment by nt4boy** [comment]
Using Socket 370 [i440LX] SuperMicro 370SLM with Intel Celeron at 166 as my 86Box machine.
Have a single COM3 port installed in the BIOS, and this is enabled in the 86Box Settings.
Loaded up Putty with a cable in the real COM3 port on the host. pins 2-3 connected, and the loopback test isn't echoing back onto the terminal. Putty finds the port and all looks good, but not working.
I have done this same test with nominally the same machine in VMWare, and Putty will echo text if the pins are connected and not if they are not, so that's working as I would expect, ie I am happy the W10 side of things is working. 

Any suggestions please of what else I could try?

**Comment by nt4boy** [comment]
Also tried the Socket 8 Gigabyte GA-686NX and Pentium II mother board now, and its the same.
COM port is to be present, the application finds it and happy to use it, but no data is transmitted and returned.
