### ISSUE TITLE
COM Port not working. Cannot even get Loopback test to work.

### ISSUE THREAD

**Issue by nt4boy** [86Box/86Box#3211]
Host PC has COM Port card and registered in W10 as COM1.
Guest Machine Bios 
![image](https://user-images.githubusercontent.com/113193761/226101367-466a51fb-0c28-4aa8-bec2-6eb516ec615e.png)

Guest Machine is W98FE has COM1 and I have physical loopback cable pins 2 and 3 connected to host.
Guest Machine settings also has serial port 1 enabled.
If I run Putty on VM, Putty is OK with this port and doesn't error I can connect to COM1 at the default condition and open a terminal window. I would expect that with the 2-3 link in place that any typed text would echo to the terminal, ie be visible and that with the link off, the echo would be inhibited., ie not visible. But I cannot get any text to appear in the terminal window, so its failing this basic test.
( I have tested this on the W10 side and this loopback test works as I expect. Can see the text with the link between 2-3.)

I've tried a number of different Motherboards for the 86Box machine, Including:-
Socket 370 [i440LX] SuperMicro 370SLM with Intel Celeron at 166.
Socket 8 Gigabyte GA-686NX and Pentium II at 166.

86Box Version 3.11. build 4311
Manager 1.7.4
Host machine is Windows 10 Pro 10.0.19044
i7-3770@3.4Ghz
Is this a bug?

**Comment by nt4boy** [comment]
Also tested this with Jenkins builds 4449 and 4481. Still no loopback.

**Comment by Xuser641** [comment]
I don't think 86box currently supports a pass-through to a host serial port. In fact I think the only thing it supports is an emulated serial mouse on the emulated serial port. I think a serial port pass-through is being worked on for a future release.

**Comment by nt4boy** [comment]
Ah well that would explain it. When it is released it'll be a life saver.
Is that likely to be weeks, months or years?

(I can confirm that Network pass through via NetBEUI to a NIC port with TCP/IP disabled on the Host does work.)

**Comment by jriwanek** [comment]
@Xuser641 That would be incorrect, 86box has had serial passthrough since [pr#3106]<https://github.com/86Box/86Box/commit/071ecea6a01a6a35bb008bb61468f728a3a71306>, (That's build 4435 on the ci) there may however still be bugs present.

**Comment by nt4boy** [comment]
Thanks you so much. Loopback does work.
![image](https://user-images.githubusercontent.com/113193761/226165468-64446ef2-b698-4b73-b965-2ec6f80dcbf8.png)
What I hadn't noticed was that with the enabled versions, there are additional tick boxes in manager.
![image](https://user-images.githubusercontent.com/113193761/226165545-4f159ce3-a408-4ba8-91a6-c02180baa5ad.png)
Configured like this
![image](https://user-images.githubusercontent.com/113193761/226165619-39be9cc9-80ff-4f5c-8dcd-3705dea217e7.png)
(Using the 4449 build here, but will test with later version as well)
Just for the record, I'm trying to use this VM in place of a dying laptop to make control box setting changes on a 1990's race car, may be in with a chance now.

**Comment by Xuser641** [comment]
I assume then that the serial port pass-through feature has not made it into a release version then because I am running the latest released version on github (3.11) and that option is not available. Am I right with this assumption?

**Comment by nt4boy** [comment]
Yes. It isn't in 4311, but Its definitely on 4449 and later.
