### ISSUE TITLE
Uncle Henry's Playhouse is severely corrupted

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#3212]
**Describe the bug**
Game is corrupted. 

**To Reproduce**
Install game. Say no to installing directdraw when asked. Run game. See glitches

**Expected behavior**
To look normal

**Screenshots**
![Monitor_1_20230318-225201-9009](https://user-images.githubusercontent.com/68984176/226156467-3c0fd9c0-b50e-4f01-8498-f0759eb69ec8.png)

**Desktop (please complete the following information):**
 Windows 10 3.11 x64

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by jriwanek** [comment]
Now please fill in your 86box version and information about your guest setup

**Comment by ualaa1** [comment]
86 Box x64 Version 3.11 with Voodoo 3500 SE and Intel Celeron at 100Mhz
Config:
[86box.zip](https://github.com/86Box/86Box/files/11010350/86box.zip)

NVR:
[nvr.zip](https://github.com/86Box/86Box/files/11010351/nvr.zip)

**Comment by OBattler** [comment]
Try using a different emulated graphics card.

**Comment by ArnoldUK** [comment]
I misinterpreted the title of this post and was expecting some front page news story :)

**Comment by OBattler** [comment]
Closing this because the user hasn't provided any further feedback.
