### ISSUE TITLE
Add IBM PC Convertible to 86Box

### ISSUE THREAD

**Issue by PechayClub** [86Box/86Box#3214]
**Is your feature request related to a problem? Please describe.**
When you tried to boot the IBM PC Convertible Start-Up Disk in another PC that is not the IBM PC Convertible, but some features are unavailable to access. This makes the disk useless to emulators and MAME has very little support for the IBM PC Convertible.
![Screenshot 2023-03-20 014829](https://user-images.githubusercontent.com/65995040/226196419-9417a588-1c05-48c5-a11f-c4ede0f9c92d.png)

**Describe the solution you'd like**
Add the IBM PC Convertible to the 86Box for the use of the IBM PC Convertible Start-Up Disk.

**Describe alternatives you've considered**
There is MAME that has the IBM PC Convertible, but it does not boot up and shows only a black screen.

**Comment by ArnoldUK** [comment]
Not quite sure what you are requesting here but have you checked the emulator settings for the floppy drive to make sure the drive is correctly setup for the disk format used by IBM Convertable ?

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
