### ISSUE TITLE
Phoenix XT clone machine memory error.

### ISSUE THREAD

**Issue by Xuser641** [86Box/86Box#3219]
**Describe the bug**
When setting the memory to 256k only 64k is detected, other amounts, like 128k and 384k are detected correctly.

**To Reproduce**
Setup a Phoenix XT clone machine and set the memory to 256k, observe POST only detecting 64k

**Expected behavior**
Correct memory amount should be detected.

**Desktop (please complete the following information):**
 - Windows 10
 - 86Box 3.11 build 4311
 - Build information: Windows 32 bit

**Additional context**
I don't think this was a problem in earlier versions but I can't remember.

**Comment by Fenix770** [comment]
I found a similar  issue on Tandy 1000S L/2 and HX machines. Memory is detected correctly only if I set to the maximum supported, 768k and 640k respectively, but if I, for example, configure the machine to 512kb only 384kb are detected at startup.

**Comment by OBattler** [comment]
I confirm the Phoenix XT clone issue, but the Tandy 1000 SL2 issue appears to be fixed. I can, however, reproduce the Tandy 1000 HX issue.
