### ISSUE TITLE
IBM PC XT 286 and IBM PC AT Disk controller failure 1782

### ISSUE THREAD

**Issue by FlameShinobi97** [86Box/86Box#3223]
Hi i was trying to set up either a XT286 or a AT with OS/2 1.0, but ran into the issue that prevents me from installing even dos. No matter what hardware setup i do i keep getting this error that if i have the IBM MFM card in it, then it locks up, if i have another MFM controller card, like the Seagate ST-11M, then it assigns the HD to position 2 and i cannot boot into that. Every time i boot up it shows that error. When i try a different floppy card it gives error 601 and the floppy drives don't work. The set up i want to run is a PC XT 286, 287XL, 2mb ram, ATI wonder 800+, adlib, ST-11M, don't care which floppy controller, ST-138 type 3 30mb hard drive, one 1.2mb 5.25 floppy, and a 720k 3.5 floppy. 
I tried making an AT machine and it did the same thing. It always happens after i run the advanced diagnostic disk v2.07 for the AT or gsetup. 

![Monitor_1_20230323-190514-035035](https://user-images.githubusercontent.com/128755838/227383811-a2dc95de-b1b3-4b4b-99c0-46f3e03dc5ed.png)

I made this machine on pcem17 ran the diagnostic and it worked fine, so I think this is an emulation bug that has developed recently for 86box. Any help on this matter will be greatly appreciated because i have spent way too much time on this trying to figure out why this error is happening.

**Comment by TC1995** [comment]
I don't think the st11 is supported on the AT or XT 286.
Either use the WD1007 ESDI or WD1003 MFM/RLL controllers, or SCSI.
