### ISSUE TITLE
Issue setting system options for PC/AT

### ISSUE THREAD

**Issue by thunderbird32** [86Box/86Box#323]
I'm attempting to set the System Options on an emulated PC/AT. I am using the "IBM Personal Computer ADVANCED DIAGNOSTICS" disk, version 2.07 specifically. This issue does not occur when using version 1.00, however, as that version doesn't support 3.5" floppy drives, that doesn't solve my issue. 

Both of the below are the **Skylake Optimized** versions of said builds.

In the most recent build (#f1796e8d - 1699) this is what happens: upon loading the disk, I get the message: 
```
SYSTEM OPTIONS NOT SET
Press "ENTER" to continue ...
```
I press enter, and get the "SELECT AN OPTION" menu, and so I select "SETUP". Upon selecting "SETUP" I get this message:
```
0152 ERROR - SYSTEM BOARD
```
And the emulated system restarts.

In build #bf46638, however, it works correctly. Upon loading the Diagnostic disk I get this message instead:
```
Have you completed running this
program since connecting the 
battery (Y/N).

Type Y or N, then press "ENTER".
```
If I type "N" and enter, I get the expected configuration prompts, at the end of which, I have a working system.

To rule out any lingering settings, I've deleted both the "nvr" folder, and the 86box.cfg file for both builds and tried the process over again. Same results.

Attached:
[f1796e8d.zip](https://github.com/86Box/86Box/files/2430256/f1796e8d.zip) - Contains the 86box.cfg file and "nvr" file from the "f1796e8d" build
[bf46638.zip](https://github.com/86Box/86Box/files/2430259/bf46638.zip) - Contains the 86box.cfg file and "nvr" file from the "bf46638" build
[ATDIAG2.zip](https://github.com/86Box/86Box/files/2430260/ATDIAG2.zip) - Contains the AT Diagnostic Disk I'm attempting to use

**Comment by OBattler** [comment]
What build exactly is the one that breaks it? I've been investigating this before (someone else already reported the same bug), and knowing which exact build breaks it, would be very helpful.

**Comment by OBattler** [comment]
Oh wait, disable time sync - the IBM AT doesn't like the century register being set to 0x20 (signifying the 21st century).

**Comment by thunderbird32** [comment]
So it does. It's odd that the message that comes up first is still different between the two versions. Well, at least now I know that turning off time sync is the first bit of troubleshooting I should do. It makes sense too, I'm always surprised that DOS is okay with dates post-1999, and I suppose I should have guessed that the setup software might have trouble with it. Weird that it's just the setup disk (and only that one, not the earlier one) that has the problem.

**Comment by OBattler** [comment]
>> So it does. It's odd that the message that comes up first is still different between the two versions
I fixed that now, the IBM AT's NVRAM with new NVR now correctly initializes with 0xFF's, so you get error 161 instead of 162, and SETUP asks you if you've run SETUP before, like it should.

>> Not sure how you could stop that from happening on the software side. It's non-obvious for the average user that it needs to be done that way.
Yeah, a way to fix that would be good. Unfortunately, I'm out of ideas.

>> By the way, is there a good place to ask why certain configurations aren't working (i.e. the PS/2 Model 50 setup not working with 1MB of RAM, and only working with 2MB)?
You can ask either here or on the IRC channel (irc.ringoflightning.net / #softhistory).

**Comment by thunderbird32** [comment]
> You can ask either here or on the IRC channel (irc.ringoflightning.net / #softhistory).
Ah, cool. Didn't want to clutter up your bug tracker with things that may be my fault. I'll submit a bug report for it later then, once I document the issue.

**Comment by OBattler** [comment]
Closing this because this issue has been fixed.
