### ISSUE TITLE
Princess Maker 2 MT32 or GM sound causes game to go to black screen

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#3233]
**Describe the bug**
On Princess Maker 2, if the sound is selected to be MT-32 or GM the game goes to black screen. It works fine when selecting SB sound.
**To Reproduce**
Go to DOSINST and configure the sound to be GM or be MT-32. then launch PM2

**Expected behavior**
Game to work

**Desktop (please complete the following information):**
Windows 10 3.11 x64

**Additional context**
Config: 
[86box.zip](https://github.com/86Box/86Box/files/11131371/86box.zip)

**Comment by OBattler** [comment]
Disable the Sound Blaster's MPU-401 and enable the standalone one. Princess Maker 2 requires intelligent mode which only the standalone MPU-401 supports.

**Comment by ualaa1** [comment]
It did go in-game when I used the standalone option when configuring in GM mode, but now there is no sound

**Comment by OBattler** [comment]
Disable the Sound Blaster's MPU-401 entirely. You need to set the Sound Blaster's MPU-401 Address to disabled.

**Comment by ualaa1** [comment]
Still get no sound
![Capture](https://user-images.githubusercontent.com/68984176/230279449-66dd6f5b-6516-4e6a-ae4a-b2a88eaf56ae.PNG)
![Capture1](https://user-images.githubusercontent.com/68984176/230279453-35cbd9af-adf4-4914-ab3e-6bf48e44fe78.PNG)

**Comment by OBattler** [comment]
Try changing the volume of FluidSynth - I believe it sometimes sets it to so low that you can't hear anything.

**Comment by OBattler** [comment]
OK, so it works on the latest 32-bit 86Box but not 64-bit. Let me see why.
