### ISSUE TITLE
OS/2 2.1 not loading correctly

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#324]
Okay, I managed to install OS/2 2.1 in a dual-boot configuration using the OS/2 Boot Manager.

The installation of OS/2 2.1 was a success. However, when I rebooted the emulated generic AMI-based 486 machine, OS/2 2.1 wouldn't load correctly, if not at all. And then after I installed the super VGA drivers for the emulated Tseng ET4000AX graphics card, OS/2 2.1 wouldn't start at all.

I'm running MS-DOS 5.0 on drive C in a dual-boot configuration with OS/2 2.1 located on drive I.

Here's a screenshot of this bug: ![20180928_223856](https://user-images.githubusercontent.com/32658796/46241755-24272280-c373-11e8-9d42-0d21a4502c57.png)

Specs for the generic AMI-based 486 machine:
* 6 x 1,000 MB SCSI hard disks + 7.8 GB SCSI hard disk image on SCSI ID 6
* 32 MB memory
* Tseng ET4000AX graphics card with 1 MB display VRAM
* 5.25" + 3.25" floppy drives
* IDE CD-ROM on IDE channel 0 + Iomega ZIP-100 on IDE channel 1
* Novell NE2000 network card
* Sound Blaster 16 sound card

I've even disabled dynarec, but unfortunately it made no difference. :(

Here is the 86Box configuration file that is used for the emulated machine.

[f1796e8d.zip.zip](https://github.com/86Box/86Box/files/2430338/f1796e8d.zip.zip) - Contains 86Box.cfg file and NVR files for the AMI486 and AHA1542C ROMs. Configuration is from build 1699.

Has anyone tried to install OS/2 2.0 or OS/2 2.1x under 86Box and encountered this problem? It seems that 32-bit versions of OS/2 2.0 and up is almost unusable under 86Box. :(

**Comment by ppgrainbow** [comment]
**Update:** I can install OS/2 Warp Version 3 on the AMI486 machine and it works without any problems.

However, for some reason when I installed OS/2 2.1, OS/2 wouldn't even load the IDE CD-ROM driver, so I had to add BASEDEV=IBM1S506.SYS /V in the CONFIG.SYS file on drive I (located on SCSI ID 6).

I might have to run a re-install of OS/2 2.1 on SCSI ID 6 and insert BASEDEV=OBM1S506.SYS /V in the CONFIG.SYS file to see if this solves the problem. :)

**Comment by TC1995** [comment]
OS/2 2.1 doesn't ship with IDE CD drivers, you'll need a third party driver for it plus an updated IBM1S506 driver.

**Comment by ppgrainbow** [comment]
Thank you for the heads up.

I went for OS/2 Warp 3 and it does work. Are there any updated IBM1S506 drivers for OS/2 2.1?

**Comment by TC1995** [comment]
there are.
I think those labeled as "IDE/ATAPI drivers for OS/2 2.x" or something similar.

**Comment by ppgrainbow** [comment]
Here is the latest configuration that I used:

* DataExpert OPTi-495SX (AMI BIOS running on Intel 486 processor running at 33 MHz), dynarec disabled
* 8 MB RAM (7,808 KB usable, 640 KB base, 7,168 KB extended)
* Tseng ET400AX display card with 1 MB display RAM
* Logitech Serial Mouse on COM port 1 with two buttons
* Sound Blaster 16 ISA card (address: 0x220, MPU-401: 0x330, IRQ: 5, Low DMA channel: 1, High DMA channel: 5, OPL enabled, Roland MT-32 emulation)
* no network
* Parallel port and serial port, all LPT devices disabled
* Adaptec AHA-1542C SCSI Adapter (address: 0x334, IRQ: 9, DMA channel 6, BIOS address: D000H), hard disk controller disabled
* 200 MB SCSI hard disk on ID 0 (800 cylinders, 16 heads, 32 sectors per track)
* 1.44 MB 3.5" floppy drive.

I suspect that there is a 486 CPU emulation bug that causes OS/2 2.1 to not load correctly with the DISKCACHE parameter enabled in the CONFIG.SYS file.

**Comment by OBattler** [comment]
This appears to be fixed on my end.

**Comment by ppgrainbow** [comment]
OBat, so how did you manage to fix the problem that caused OS/2 2.1 to not work correctly with DISKCACHE enabled on a 486-based emulated machine?

**Comment by OBattler** [comment]
I have no idea what fixed it, but it disappeared. As such, I am closing this issue.

**Comment by OBattler** [comment]
Issue re-opened, seems it's not fixed yet.
