### ISSUE TITLE
Japanese 106-key keyboard mapping swaps yen and backslash

### ISSUE THREAD

**Issue by iamgreaser** [86Box/86Box#3241]
I am filing this bug to see if this issue is X11-specific. **UPDATE: After looking through the code and doing a preliminary fix on my end, it is X11-specific.**

**Describe the bug**
When using a Japanese keyboard in Japanese Windows 95 OSR 2.1, or Japanese DOS/V 6.2, the yen key and the backslash key are swapped. This means that when one holds shift on one key, they get the opposite result.

* Shift+yen should map to vertical bar.
* Shift+backslash should map to underscore.

In both cases, pressing either key gives a yen symbol, but this is not a bug, this is a limitation of both OSes. But holding Shift when pressing one key gives the character you should get when you press the other key.

**To Reproduce**
You will need a Japanese OADG109A keyboard or similar. Both the yen and backslash keys use scancodes which don't exist on a US keyboard.

The quickest way to reproduce this is to use the first Japanese MS-DOS 6.2 Upgrade install disk. From there:

1. Press 半角/全角 (zenkaku/hankaku, same position as the tilde key on a US layout) to select a JP 106-key layout.
2. Press F3 twice to exit setup.
3. Type Shift+backslash. It ideally should produce an underscore. (It currently produces a vertical bar.)
4. Type Shift+yen. It ideally should produce a vertical bar. (It currently produces a yen symbol.)

**Desktop (please complete the following information):**
 - OS: Void Linux, x86_64
 - 86Box version: Commit 542f8477e7f998423089c74c6d8e79c3004dbba5 (2023-03-30T23:50:14+0200, "Fully cleaned up the AT keyboard controller add data mess.")
 - Build information: Old dynarec, Discord integration disabled

**Additional context**
I am trying to work out an easy way to test some of the other issues I'm seeing (notably the 無変換 (muhenkan), 変換 (henkan), and カタカナ/ひらがな/ローマ字 (katakana/hiragana/roumaji, AKA "kana") keys seem to be missing from the mapping), but that is probably best tested with a custom boot sector program.

I am willing to fix this bug myself, but there is a chance that it'll break it for Windows users and/or Mac users. Probably won't affect *BSD users as they're using X11, but it may affect Linux users using Wayland.

**UPDATE:** The simplest fix will conflict with some of the mapping changes in commit 99b72cd7 .

**Comment by iamgreaser** [comment]
Alright, following up with more info and a 360 KB 5.25in floppy bootloader program. Press ESC to reboot - Ctrl-Alt-Del is just too hard to track considering how primitive the program is. Also, this seems to work fine in a 3.5in drive in 86Box.

[keytest.zip](https://github.com/86Box/86Box/files/11174677/keytest.zip)

And here's the mapping results for me:

* yen: 73 (should be 7D, ends up being backslash)
* backslash: 56 (should be 73, ends up being the weird unlabelled key on non-US keyboards)
* muhenkan: 7E (should be 7B, ends up being a non-JP key)
* henkan: 7D (should be 79, ends up being yen)
* kana: 2B (should be 70, ends up being close square bracket)

Everything else I've tested appears to be normal.

Holding Shift, Alt, and/or Ctrl does not appear to affect the scancode. Phew.

Here's the JP-specific part of that one really good website that really deserves to be at the top of every search result that even hints at anything remotely to do with a keyboard, which shows what the scancodes are: https://www.win.tue.nl/~aeb/linux/kbd/scancodes-8.html

If you have a JP keyboard and you are NOT using X11, then please boot the program on an 86Box VM and give results. (I've only tested this with an AT-style controller, but it might work on XT.)

**Comment by iamgreaser** [comment]
And here's the correct mappings for a JP keyboard, which can be applied to `qt/qt_mainwindow.cpp` in the `x11_to_xt_2` array:

* 97/0x61: Change from 0x56 to 0x73 - backslash
* 100/0x64: Change from 0x7D to 0x79 - henkan
* 101/0x65: Change from 0x2B to 0x70 - kana
* 102/0x66: Change from 0x7E to 0x7B - muhenkan
* 132/0x84: Change from 0x73 to 0x7D - yen

The above mapping has been tested and it Works On My Machine™. But I wonder what layouts that would break...

**Comment by OBattler** [comment]
From what I know, RichardG (who is Brazilian) filled in those values based on tests with his ABNT2 keyboard, and for some reason, X11 can't keep things consistent, since the exact same key (0x7D, next to right shift) uses entirely different X11 codes on the two.

**Comment by iamgreaser** [comment]
This issue appears to have been fixed as of e492640d65611b0b587cfe638445649ed35129b2 , as I am able to use my JP keyboard without needing any patches.
