### ISSUE TITLE
BUG: Acer V30 crash when loading  the DOS PS/2 mouse driver.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3242]
Hello!
I recently tested The changes to the keyboard on build 4.0.0.4400. The machine works just fine with it. But on build  4.0.0.4502 the machine crash when loading the Mitsumi mouse driver configured as PS/2. I also tested the DOS CTMOUSE driver and the machine freeze just after HIMEM.SYS test the XMS memory, but I suspect is trying to load the CTMOUSE.

Here is the HDD image  and CFG/NVR files:

HDD:

[Pentium Acer V30-001.zip](https://github.com/86Box/86Box/files/11175820/Pentium.Acer.V30-001.zip)
[Pentium Acer V30-002.zip](https://github.com/86Box/86Box/files/11175822/Pentium.Acer.V30-002.zip)

NOTE: The image file was split in two parts because is bigger than 27mb, rename  "Pentium.Acer.V30-001.zip" to "Pentium.Acer.V30.zip.001 and do the same for the file 002.

Here is the NVR/CFG:
[Pentium ACER V30.zip](https://github.com/86Box/86Box/files/11175839/Pentium.ACER.V30.zip)

86box Build: Windows x32, ODR build 4.0.0.4502

**Comment by OBattler** [comment]
I cannot reproduce this at all. Make sure it still occurs on the latest build of 86Box.

**Comment by OBattler** [comment]
Closing this since there has been no response since that would indicate the continued presence of the problem.
