### ISSUE TITLE
build fail on Slackware, patch

### ISSUE THREAD

**Issue by Randrianasulu** [86Box/86Box#3246]
**Describe the bug**
Build started to fail recently

**To Reproduce**
1. download git up to https://github.com/86Box/86Box/commit/18ee7f70804d0b00c56588b6f3e7dac5fe5e8832
2. try to build on Slackware 15.0 install

**Expected behavior**
Build finishes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Slackware 15.0 i586
 - 86Box version: 18ee7f70804d0b00c56588b6f3e7dac5fe5e8832

**Additional context**
Using https://stackoverflow.com/questions/15432432/qt5-qplatformnativeinterface-and-hwnd

I "fixed" build failure by adding

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8070ff263..c83e4f427 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -124,6 +124,10 @@ set(CMAKE_C_STANDARD 11)
 set(CMAKE_CXX_STANDARD 14)
 set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)

+find_package(Qt5Gui)
+include_directories(${Qt5Gui_PRIVATE_INCLUDE_DIRS})
+
+
 # Optional features
```

but you probably want to put it under ifdefs (due to qt6)

**Comment by richardg867** [comment]
Hopefully fixed by 0763475, which patched a similar issue in our Actions environment.
