### ISSUE TITLE
The Tale of Peter Rabbit (DOS) CD-ROM Version Crashes

### ISSUE THREAD

**Issue by NopaWax** [86Box/86Box#3249]
**Describe the bug**
This very obscure DOS program/audiobook has a very high tendency to crash the system while the mouse is moving. The audio will continue to play, but the VM will not respond to any input and the video is frozen. If QEMM is running, an illegal instruction error will be shown. If CTRL+ALT+DEL is used to reboot instead of a hard reset, the last music note will continue playing.

**To Reproduce**
1. Launch the program.
2. Allow the intro to play out or press the ESC key to skip it.
3. When you're allowed to use the mouse, start moving it back and forth at a fast speed.
4. The system will eventually crash. It sometimes happens immediately, and other times it takes a few seconds.

**Expected behavior**
The program should continue running regardless of how much the mouse is moved.

**Screenshots**
Illegal instruction error given by QEMM if it is active:
![Monitor_1_20230412-150515-209209](https://user-images.githubusercontent.com/122238513/231559595-13e961a5-2500-47fe-a369-874041e46b04.png)

If QEMM is not running, the system simply freezes.

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - 86Box version: v4.0.0 build 4542
 - Build information: Win32, both dynarecs are affected.

**Additional context**
I have been troubleshooting this program across several emulators for several months now, as I have been wanting to find the ideal solution for launching my DOS/Early Windows collection through LaunchBox. I have been testing this and a large number of other games from Knowledge Adventure through 86Box, PCem, vanilla DOSBox, and various forks of DOSBox. From what I've tried so far, vanilla DOSBox and PCem appear to run this program flawlessly, while 86Box and SVN-based DOSBox forks (e.g., DOSBox-X) are problematic. While other Knowledge Adventure games (e.g., 3-D Dinosaur Adventure, SPEED) also have inconsistent mouse tracking and other game-breaking bugs in different places, this is the only one I've found where the system crashes simply by moving the mouse.

Video clip without QEMM:
https://user-images.githubusercontent.com/122238513/231564137-880ee6a0-c74a-4362-8cdd-cc80248eccb7.mp4

Video clip with QEMM:
https://user-images.githubusercontent.com/122238513/231564476-c0468b5b-e5b1-4418-b86f-db3662e2f452.mp4

**Comment by 80486DX2-66** [comment]
Did you mean "QEMM" (Quarterdeck Expanded Memory Manager) instead of "QEMU" (Quick EMUlator)? The screenshot mentions "QEMM". It also mentions turning the machine off and on again, which means it is not QEMU.

**Comment by NopaWax** [comment]
Yes, I did mean QEMM. My mistake.

**Comment by Fenix770** [comment]
Hello! 

I recently tested that game. (I used the Installer version included in Total DOS Collection #20. The game works fine on my end.
I tested with the Opti-291 386 SX machine with Cyrix 486 SLC/33 CPU and SB. It has installed DOS 5.0 and QEMM 7.04.
The games work flawlessly, however I had issues with QEMM before. 

Make sure:

1. QEMM is not using the Stealth feature (This feature move part of the disk/video ROM BIOS data outside the upper memory  640kb-1024kb area to get more low RAM) but almost all DOS software needs these information in the upper memory.
2. Try to exclude the B000-B800 or any F region if QEMM uses it, even if QEMM reports as "free" it may be used by the VGA video card. To do this add for example X=B000-B800 to QEMM386.SYS line in CONFIG.SYS

Also here are the Installer for the game  (they are two 1.44mb floppy disks):
[Tales of Peter Rabbit.zip](https://github.com/86Box/86Box/files/11245015/Tales.of.Peter.Rabbit.zip)

Here is a screen capture of my VM configuration:
![QEMM 704](https://user-images.githubusercontent.com/31600563/232351889-a8883da0-7b0a-45c1-b53c-67b5192ff33b.png)

**Comment by NopaWax** [comment]
> Hello!
> 
> I recently tested that game. (I used the Installer version included in Total DOS Collection #20. The game works fine on my end. I tested with the Opti-291 386 SX machine with Cyrix 486 SLC/33 CPU and SB. It has installed DOS 5.0 and QEMM 7.04. The games work flawlessly, however I had issues with QEMM before.
> 
> Make sure:
> 
>     1. QEMM is not using the Stealth feature (This feature move part of the disk/video ROM BIOS data outside the upper memory  640kb-1024kb area to get more low RAM) but almost all DOS software needs these information in the upper memory.
> 
>     2. Try to exclude the B000-B800 or any F region if QEMM uses it, even if QEMM reports as "free" it may be used by the VGA video card. To do this add for example X=B000-B800 to QEMM386.SYS line in CONFIG.SYS
> 
> 
> Also here are the Installer for the game (they are two 1.44mb floppy disks): [Tales of Peter Rabbit.zip](https://github.com/86Box/86Box/files/11245015/Tales.of.Peter.Rabbit.zip)
> 
> Here is a screen capture of my VM configuration: ![QEMM 704](https://user-images.githubusercontent.com/31600563/232351889-a8883da0-7b0a-45c1-b53c-67b5192ff33b.png)

As I've noted with DOSBox-X, the floppy disk version does not seem to be affected by this issue. I have been testing the CD-ROM version, which nobody seems to have uploaded anywhere. Through DOSBox-X, I now know that this program violates the default 64KB segment limit. This can be bypassed by disabling segment limit violation, therefore replicating "flat real mode" or "unreal mode". This fixed the crashes.

In the case of 86Box, the theoretical solution would be to run the game with just HIMEM.SYS and no EMS emulator, such as QEMM, running. On PCem, this seems to work, but on 86Box, no matter what machine or processor I use, what mouse or CD driver I use, whether or not the dynarec is enabled, whether it's the old or new dynarec, or whether I run the program off the CD or off the hard drive, it always crashes. I've ruled as many things out as I can think of.

**Comment by OBattler** [comment]
The offending instruction REP MOVSW - I believe PCem doesn't do segment limit checks at all there, which is flat out wrong. 86Box does. The question is, what is the game trying to do here.

Can you guys try the latest build of 86Box since I did some changes with regards to that stuff precisely to REP MOVS* among other things?

**Comment by OBattler** [comment]
- NopaWax: I would need the VM to try to reproduce the bug.

**Comment by NopaWax** [comment]
> The offending instruction REP MOVSW - I believe PCem doesn't do segment limit checks at all there, which is flat out wrong. 86Box does. The question is, what is the game trying to do here.
> 
> Can you guys try the latest build of 86Box since I did some changes with regards to that stuff precisely to REP MOVS* among other things?

I just tried again with the latest Jenkins build, and the crashes still occur.

> - NopaWax: I would need the VM to try to reproduce the bug.

[Peter Test.zip](https://github.com/86Box/86Box/files/11568032/Peter.Test.zip)

Here's a basic install of the game as well as the disc image. As I previously stated, the configuration of the VM doesn't seem to matter from what I've tested, so I'm interested to see what you find.

**Comment by OBattler** [comment]
The VM provided does not include QEMM, that the crash was reported to occur with.

**Comment by NopaWax** [comment]
> Nevermind, it was also crashing without QEMM, but it no longer does on my end, perhaps the instruction GPF fix added for Jane's F-16, fixed this as well.

The issue is still occurring for me on the most recent Jenkins build, but it's fine if you don't want to keep investigating this. If this program is just going to be a case of illegal instruction whack-a-mole, I'm fine with letting it go.
