### ISSUE TITLE
While using on-screen keyboard

### ISSUE THREAD

**Issue by muffenme** [86Box/86Box#3253]
The following keys don't work while using the on-screen keyboard: del, page up, page down, arrow up, arrow down, arrow left, arrow right, home, and end.  Number lock key has no effects.

I pick the following:
Machine types: i486 (socket 2), i486 (Socket 168 and 1), i386SX
[ALi M14296] Kaimei SA-486 VL-BUS MLB, [ACC 2168] Packard Bell PB410A, [ALi M1429G] Acer A1G, [ALi M1429] Olystar LIL 1429, Intel i386SX
CPU type;
all
Speed:
all
Memory:
all

Boot into MS-DOS V6.22 and type edit and hit enter and proceed to use these keys and these keys either don't work or doesn't give the right actions when it comes number key pad. 

![image](https://user-images.githubusercontent.com/9914938/231940767-df8076f5-daea-42b5-b023-8bebb73c4097.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Lenovo ThinkPad T420 Laptop
 - RAM: 8 GB
 - CPU: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz   2.80 GHz
 - 86Box: v 3.6 [build 3850] [ad8ea20e]
 - 
 - Build information: [i.e. new/old dynarec, architecture and build type

**Comment by OBattler** [comment]
Since we use raw keyboard input, the only explanation for this is that the on-screen keyboard sends the wrong scan codes for these. As a result, this is a CANTFIX.
