### ISSUE TITLE
8088 system locking up after a few seconds

### ISSUE THREAD

**Issue by telanus** [86Box/86Box#3256]
**Describe the bug**
When running generic XT and NCR PC4i it'll lockup after a few seconds of use

**To Reproduce**
1. start either of the systems, boot into something like Ally Cat and start to play, 86Box will lock up after 5-20 seconds

**Expected behavior**
that it works

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - 86Box version:4.0 (4dbc4a0)
 - Build information: new, 64-86 and GCC 11.1.0

**Comment by randomsomeone69** [comment]
Did it throws out an error code? Because sometimes, bugs aren't from the emulator, but the software.

**Comment by telanus** [comment]
I'm suspecing it might be something todo with the size of the disk. Seems the some of the 180kb disk images, that I have, is the problem. They will locku, an other size seems to work correctly
