### ISSUE TITLE
Support for SDL_SCANCODE_NONUSBACKSLASH

### ISSUE THREAD

**Issue by degaart** [86Box/86Box#3259]
**Describe the bug**

On my non-US (french) keyboard, there's a key to the right of LShift, corresponding to "<" and ">".

The SDL scancode for this key is SDL_SCANCODE_NONUSBACKSLASH (0x64).

On the QT frontend to 86Box, this key is wrongly handled the same as SDL_SCANCODE_GRAVE.

On the SDL frontend to 86Box, it isn't handled at all. I've tried adding SDL_SCANCODE_NONUSBACKSLASH to the `sdl_to_xt` array in src/unix/unix.c; it should translate to the XT keyboard code 0x64 per this [link](https://deskthority.net/wiki/Scancode), but it was still not handled.

**To Reproduce**
1. Have a non-US keyboard
2. Run 86Box SDL frontend
3. Hit the key to the right of LShift
4. Nothing happens

**Expected behavior**
The key works and is separate as SDL_SCANCODE_GRAVE.

**Desktop (please complete the following information):**
 - OS: macOS 12
 - 86Box version: 3.11

**Additional context**

**Comment by cold-brewed** [comment]
There were numerous keyboard improvements added in the past few weeks. Could you download the latest CI build and see if the problem is fixed?

https://ci.86box.net/job/86Box/

**Comment by degaart** [comment]
Fixed in nightly b4562
