### ISSUE TITLE
Hercules emulation bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#326]
Hello!

I have been testing XT machines with Hercules graphics card. I tested 86box and Varcem (commit 262)
 I found the following issues:

1. The game Outrun and Pictionary does not work in Hercules mode. But works in Varcem
2. Road Runner,in Hercules mode, and works, but the graphics are duplicated for some reason. (Workaround: In Varcem I use a CGA emulator and run the CGA mode of the game and it works. I do not know if it is a problem with the game itself.)
3. I have a small collection of CGA emulators for Hercules card and all of them seems to work in Varcem ( and the prompt does not disappears, I can see the text mode change to CGA emulation in some of them)

PD: The  only problem in Varcem is it has emulation problems with other machines.

Thanks for your effort! 

Both emulators are becoming more accurate every day!

**Comment by OBattler** [comment]
I'll compare VARCem's Hercules emulation with 86Box's, chances are they have some bug fixes in that we don't.
