### ISSUE TITLE
Intel Advanced/ATX (MR BIOS) doesn't proper start when a Intel Pentium superior to 100 MHz is installed.

### ISSUE THREAD

**Issue by randomsomeone69** [86Box/86Box#3260]
**Describe the bug**
When setup a machine with this motherboard and an Intel Pentium superior to 100 MHz, the BIOS dosen't proprely detect the CPU.

**To Reproduce**
1. Select the motherboard "Intel Advanced/ATX (MR BIOS)"
2. Select any Intel Pentium superior to 100/66 Mhz.
3. Start the machine
4. Be greeted by 4 beeps on which their pitch is higher depeing of the nearest speed of the processor.

**Expected behavior**
Should boot normally.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - 86Box version: v3.11 build 4311
 - Build information: x86

**Additional context**
This doesn't occur on the AMI version of the BIOS, curiously.

**Comment by pankoza-pl** [comment]
it's a bug in the dynamic recompiler: MR BIOS. doesn't like faster CPU's with the dynamic recompiler

**Comment by OBattler** [comment]
This can't be fixed, it has to do with how the dynamic recompiler runs the timers. So I'm closing this with CANTFIX.
