### ISSUE TITLE
DVD Rom Support

### ISSUE THREAD

**Issue by Dungeonseeker** [86Box/86Box#3264]
**Is your feature request related to a problem? Please describe.**
With systems as powerful as Pentium 2s having a 700mb limit is a PITA, it would be nice to have the ability to add a DVD drive for 4.7gb.

**Describe the solution you'd like**
A DVD-ROM module that allows us to add DVD drives to virtual machines.

**Describe alternatives you've considered**
The only alternative is to use SMB, on older OSes this is a huge security risk and support for legacy SMB implementations is disabled in pretty much all modern OSes.

**Additional context**
It used to be possible to mount DVD ISOs using the virtual CD ROM until it was patched.

**Comment by cold-brewed** [comment]
There is no 700mb size limit on the iso that is mounted. You can mount images of a larger size. The guest will still see it as a CD-ROM but it can be larger than 700. For example, I was able to mount a 2.5G windows 7 install iso in windows 98.

You can also use virtual iso to mount directories.

**Comment by Dungeonseeker** [comment]
> There is no 700mb size limit on the iso that is mounted. You can mount images of a larger size. The guest will still see it as a CD-ROM but it can be larger than 700. For example, I was able to mount a 2.5G windows 7 install iso in windows 98.
> 
> You can also use virtual iso to mount directories.

Fair enough, I swear at one point it was removed and honestly I haven't tried it recently.

Would still be nice to get DVD support added though. Would it be incorrect to assume its just a case of editing the cdrom module and adjusting its limits for tracks, sectors and other geometry? ISO9660 doesn't change as the disc size increases, right?

**Comment by cold-brewed** [comment]
You can mount any ISO9660 image today in 86Box, any size, there really is no specific need for DVD (drive) hardware emulation. They weren't even really available until the very tail end of the era that 86Box targets.

> Would it be incorrect to assume its just a case of editing the cdrom module and adjusting its limits for tracks, sectors and other geometry?

86Box emulates the actual drive at the hardware level, so it's definitely a bit more complicated than this 😄

**Comment by OBattler** [comment]
Not only we do not limit the geometry at all - we outright the return the media type as DVD if the mounted image is over a certain size and even implement all the DVD-specific commands. So the request is already fulfilled.
