### ISSUE TITLE
Divide overflow error at boot time with Qualitas 386Max v7

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3269]
I recently tested the 486 Siemens Nixdorf VM machine that I created the last year with the last build of 86Box and get a "divide overflow" error and the  machine crash. I tried to boot from a DOS 6.2 floppy and run the Maximize program but the machine does not reboot as it should, It just freezes.

Here is a screenshot:
![486 Siemens](https://user-images.githubusercontent.com/31600563/233812936-d4bc926b-71cf-4f65-90b9-50ddc8fed977.png)

Here is the VM and CFG and NVR files:
CFG/NVR
[486 Siemens Nixdorff.zip](https://github.com/86Box/86Box/files/11302571/486.Siemens.Nixdorff.zip)
HDD:
[486 Siemes Nixdorf.zip](https://github.com/86Box/86Box/files/11302575/486.Siemes.Nixdorf.zip)

I tested the VM with 86box build 4.0.0.4568 Win32 old dynarec.

**Comment by pankoza-pl** [comment]
Your vm seems to work for me, but I had to reboot the vm manually when it told me that it will reboot itself
Try updating 86Box to the latest build and see if the vm works there

**Comment by OBattler** [comment]
I'm not quite sure what's causing these divide overflows - 386BSD also causes one which ends up resulting in a triple fault reset.

**Comment by lgj1107** [comment]
You need to manually adjust the parameters for 386max use, adjusting them according to the BIOS shadow.

device=386max.sys use=d000 - dfff  use=e000-efff

It works normally in my configuration


<img width="673" alt="biso11AD36B77BCFE827EDA59657D701639" src="https://github.com/86Box/86Box/assets/3366897/ca353fc0-5061-493d-9851-d8a8d317c2fb">

<img width="667" alt="222220C12E3CFEC2F64537D400F987D1F15" src="https://github.com/86Box/86Box/assets/3366897/0ddec344-10b8-4243-9154-eba265a5233b">

<img width="666" alt="33333333F894E1863DF4C10514F54B56CDFE9" src="https://github.com/86Box/86Box/assets/3366897/279fa5a4-0b7d-43a3-a789-af46cb6354ea">

**Comment by OBattler** [comment]
Then this can be closed as NOTABUG.
