### ISSUE TITLE
Uplink Freezes

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#3275]
**Describe the bug**
Uplink freezes at the beginning. The music keeps on going, but the game just freezes. This game has very simplistic graphics so I don't think the problem is with the graphics card. Using Windows 98 SE with a Voodoo 3.
Config:
[86box.zip](https://github.com/86Box/86Box/files/11316778/86box.zip)

**To Reproduce**
Install Uplink. Open up the game. Freezes. I opened the normal version, not the safe mode version

**Expected behavior**
Game to work

**Screenshots**
Where it freezes: 
![Monitor_1_20230424-210106-07007](https://user-images.githubusercontent.com/68984176/234173418-f1f97beb-9248-4b2f-9c0d-2ab3072529c0.png)

**Desktop (please complete the following information):**
 Windows 10 x64 3.11

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by OBattler** [comment]
This game is outside his emulator's scope.

**Comment by borchy** [comment]
> This game is outside this emulator's scope.

I have no stake in this, but I'm just curious as to why the game is outside the emulator's scope? Windows 98 SE with a Voodoo 3 is a classic config for 86Box, shouldn't it work? I mean if it's a game bug I understand, but if it's an emulation bug wouldn't that be a problem?

**Comment by Cacodemon345** [comment]
Uplink was a 2001 title, meaning it was released in a post-Pentium III era.

**Comment by borchy** [comment]
> Uplink was a 2001 title, meaning it was released in a post-Pentium III era.

I understand 86Box doesn't support Pentium III but according to [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Uplink:_Hacker_Elite#System_requirements) Uplink should run on a Pentium II.

**Comment by eddmanx** [comment]
Ignore the P3 part. The game uses OpenGL and voodoo cards don't have the best implementation of it. The game does seem to work in windowed mode; check the readme for details. Can't tell if the fullscreen problem is an 86box bug or related to voodoo itself.
