### ISSUE TITLE
Super socket 7 Asus Windows 98 Installation Problem related to MS-DOS Extender

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#3278]
**Describe the bug**
I received an error when installing Windows 98 SE. It was after I formatted the HD for large file support. I did use the boot disk initially.

**To Reproduce**
Install Windows 98 SE by using the boot disk. Then, put in the CD. Follow a few steps and then the crash
Config: 
[86box (2).zip](https://github.com/86Box/86Box/files/11329479/86box.2.zip)

**Expected behavior**
For Windows 98 SE to install.

**Screenshots**

PCI listings

![Monitor_1_20230425-225108-047047](https://user-images.githubusercontent.com/68984176/234482217-dad58acc-67e4-4776-9c8f-bca21fba84af.png)
Error screen

![Monitor_1_20230425-225054-527527](https://user-images.githubusercontent.com/68984176/234482365-641ae1dc-f69d-45b5-8ed8-1290103e5337.png)

**Desktop (please complete the following information):**
Windows 10 x64 3.11

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by pankoza-pl** [comment]
try the Gigabyte GA-5AX instead, Asus P5A is currently buggy
