### ISSUE TITLE
Keyboard hang up since keyboard rework code

### ISSUE THREAD

**Issue by silverlays** [86Box/86Box#3280]
**Describe the bug**
Since release ~4560 (since the keyboard rework), my keyboard hang up when I launch Win31. I have to hard reset the VM to be able to use it again.

**To Reproduce**
1) Start DOS 6.22
2) Type WIN (at this time, keyboard work)
3) When Win31 start, the keyboard stop functioning even if I quit Win31 and tried to type something back to DOS. Hard reset is the only way to fix it.

**Expected behavior**
The keyboard worked fine until then.

**Desktop (please complete the following information):**
 - OS: Win11 fully updated
 - 86Box version: 86Box v4.0.0.4573
 - Build information: NDR

**Additional context**
[86Box.cfg](https://pastebin.com/4dCk7BNt)

**Comment by telanus** [comment]
I can confirm, This happens with my tests as well

**Comment by OBattler** [comment]
Use the old dynarec build. I'm using the exact same machine and it works.

**Comment by silverlays** [comment]
> Use the old dynarec build. I'm using the exact same machine and it works.

I just tried with the ODR build but it doesn't work either :(

I have to mention that I'm on a French Windows with belgian Keyboard, maybe it matter ? 🤔

**Comment by OBattler** [comment]
Yes, please do.

**Comment by silverlays** [comment]
> Yes, please do.

There it is : https://mega.nz/file/jsw0wALI#80fwRxp0FkHf1_xfgkOaiCtY0si2NI-d2C-aZdAvPAg

It is the full VM folder. Hope this helps

**Comment by OBattler** [comment]
OK, this one is interesting - it's an ISA/VLB machine so it should need the IRQ 1 and IRQ 12 latches, but the boot loader seems to install keyboard handling code that requires such latches. Now I'd love some tests from real hardware to verify this.

**Comment by silverlays** [comment]
> OK, this one is interesting - it's an ISA/VLB machine so it should need the IRQ 1 and IRQ 12 latches, but the boot loader seems to install keyboard handling code that requires such latches. Now I'd love some tests from real hardware to verify this.

Unfortunaly, I cannot help with real hardware, i don't have it anymore, but i had this exact machine back in the days (in early 90')

**Comment by OBattler** [comment]
Fix committed.

**Comment by silverlays** [comment]
> Fix committed.

That was really quick ! 😮 Thanks you for your great work 🙏

**Comment by Leonw43** [comment]
I'm having the same issue even on build 4639. However it initially worked ok, then broke out of nowhere and only works in DOS before booting windows. Ctrl + Alt + Del from the 86Box menu doesn't do anything either (unless in DOS before running win)
