### ISSUE TITLE
IBM PS/2 Model 80 can't boot into the reference diskette.

### ISSUE THREAD

**Issue by AshUosis** [86Box/86Box#3281]
When I choose the IBM PS/2 Model 80 and insert the ref diskette it does nothing. (And yes, I changed the floppy drive to be a 3.5" 1.44M drive.) (And yes, I pressed F1 (For some reason after some presses it starts to beep))

**Comment by TC1995** [comment]
type 2 or type 3?.

**Comment by AshUosis** [comment]
> Type 2 or type 3?

Type 2

**Comment by AshUosis** [comment]
Nevermind, Found the solution on an another issue and I set the wrong type of floppy drive.
