### ISSUE TITLE
DR-DOS 6 crash after typing the enter key at DOS prompt

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3287]
**Describe the bug**
I installed the Spanish version of DR-DOS 6 (dated as January 1992).
 The VM works fine during the installation but after booting the machine stop responding after I press the enter key.
I suspect is something related to the DR-DOS KEYB function because it seems to work fine during the setup and fails after configuring the DOS keyboard country, I tested the 83/84 and 102 enhanced keyboard configurations and both fail.
I also tested two 386 SX machines The Opti 291 and 386SX MR BIOS.

Here are the CFG, NVR and HD image files:
[386 SX DR-DOS 6 Español HDD.zip](https://github.com/86Box/86Box/files/11360300/386.SX.DR-DOS.6.Espanol.HDD.zip)
[386 SX DR-DOS 6 Español.zip](https://github.com/86Box/86Box/files/11360301/386.SX.DR-DOS.6.Espanol.zip)

**To Reproduce**

1. Start the VM
2. Type ENTER  at DOS prompt
3. The VM stop responding

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 22H1
 - 86Box version: 4.0.0.4584
 - Build information: old dynarec, Win32

**Comment by Fenix770** [comment]
UPDATE: The issue exist, with the Paradise WD90C30-LR VGA card. I changed it to Orchid Farenheit 1280, and the keyboard seems to work fine.

**Comment by OBattler** [comment]
Closing this then - it's most likely a video BIOS incompatibility with DR-DOS 6.
