### ISSUE TITLE
OS/2 Warp 4 - ISA Cirrus GL-CD 5428 display issues

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#329]
I would like to report a bug involving using any sort of display driver such as the ISA-based Cirrus GL-CD 5428 display driver with 2 MB display memory installed.

I managed to install OS/2 Warp 4 on the President-based emulated machine with the Award 430FX PCI chipset along with Fix Pack 15 and it was successful.

However, when I managed to install the built in display drivers for the Cirrus GL-CD 542x series located on the OS/2 Warp 4 ISO, I'm running into display corruption issues even though the OS works properly.

I have attached the screenshot of the display corruption issue using the 1024 x 768 16-bit colour driver:

![20181023_170652](https://user-images.githubusercontent.com/32658796/47398323-7c3e1400-d6e8-11e8-9258-4c4bab4bb19a.png)

On the bright side, the Win-OS/2 subsystem under Warp 4 works with the Cirrus GL-CD 5428 display.

 I have backed up the 2 GB hard disk image where OS/2 Warp 4 is installed incase something goes wrong when using a VESA-based display driver. Can anyone look into this issue to see what might be causing display issues when using a VESA-based display driver under OS/2 Warp 4?

Thank you. :)

Emulated machine specs:
* President-based generic motherboard with the Award 430FX PCI chipset, 75 MHz Pentium
* 2 x 2 GB IDE hard drives, CD-ROM, Iomega ZIP100 drive on the ISA dual channel IDE controller
* 3.25" 1.44 MB and 5.25" 1.2 MB floppies
* 64 MB RAM
* ISA-based Cirrus GL-CD 5248 graphics card with 2 MB display RAM
* Sound Blaster 16 ISA card
* Novell NE2000 ISA card

No PCI devices are emulated on the machine at this time.

**Comment by ppgrainbow** [comment]
I've been told that some of the features on the Cirrus Logic video cards aren't implemented at this time and are pending tests of the real Cirrus Logic cards.

In order to solve this, I had to switch to the S3 Trio64 with 4 MB display RAM.

**Comment by TC1995** [comment]
This is once and for all solved, it was mem sys dest being unimplemented, now it is :).
