### ISSUE TITLE
[Color400] cursor sometimes disappears

### ISSUE THREAD

**Issue by waltje** [86Box/86Box#331]
On (at least) the AMI 286 Clone machine, in (standard) text80 mode,
the cursor sometimes seems to disappear after the DOS prompt is
displayed.

Typing a(ny) character will show it again.

Oh. I just noticed its every other character, really.  Something to do with that comment about
'half the size' ?

**Comment by OBattler** [comment]
It could be, I have no idea. I'm still waiting for someone to compile me a build of PCem with the Sigma in so I can see if such issues occur there are as well or are caused by my adaptation to 86Box.

**Comment by OBattler** [comment]
OK, this is now fixed in the latest commit.

**Comment by waltje** [comment]
Confirmed.

--------------------------------------------
On Sat, 11/3/18, OBattler <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] [Color400] cursor sometimes disappears (#331)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Saturday, November 3, 2018, 7:47 AM
 
 OK, this is now fixed in the
 latest commit.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
