### ISSUE TITLE
Please add support for Compaq Prolinea MT in 86box

### ISSUE THREAD

**Issue by saipan7** [86Box/86Box#3325]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
86box support Compaq Prolinea MT.

**Additional context**
Mainboard Info:

- https://theretroweb.com/motherboards/s/compaq-prolinea-mt

- https://stason.org/TULARC/pc/motherboards/C/COMPAQ-COMPUTER-CORPORATION-486-PROLINEA-MT.html

![image](https://user-images.githubusercontent.com/127716019/236888250-f55c8812-0e92-4bb1-9831-ebb7ecfb9e07.png)

![image](https://github.com/86Box/86Box/assets/127716019/291c4398-726e-4df2-94f4-06d906e734ef)

![image](https://github.com/86Box/86Box/assets/127716019/1276c9a1-882e-420c-a987-e502568fd066)

![image](https://github.com/86Box/86Box/assets/127716019/acffa505-c40d-4f7e-8ece-a86de7048d05)

![image](https://github.com/86Box/86Box/assets/127716019/13a49fe6-34ff-4e1f-b6a7-bb6534b651b3)

![image](https://github.com/86Box/86Box/assets/127716019/e50a4126-6ab5-455c-999f-bafb872730d9)

![image](https://github.com/86Box/86Box/assets/127716019/8c2f56d3-b96b-444c-af27-924131e11bbc)

Mainboard BIOS download:
https://theretroweb.com/motherboards/s/compaq-prolinea-mt#downloads
![image](https://github.com/86Box/86Box/assets/127716019/819d3530-a72d-45a3-a4ed-03007b76d777)

Mainboard Chipset Info:
- https://theretroweb.com/chipsets/570

- [VLSI VL82C481 datasheet.pdf](https://github.com/86Box/86Box/files/11443952/VLSI.VL82C481.datasheet.pdf)
![image](https://github.com/86Box/86Box/assets/127716019/88e5dd1f-81c0-4840-a65a-9b6d29445743)

- [VL82C114_Combination_IO_199303.pdf](https://github.com/86Box/86Box/files/11447494/VL82C114_Combination_IO_199303.pdf)
![image](https://github.com/86Box/86Box/assets/127716019/68cbfdad-ba88-4f84-b7e0-d6cd9c6e3330)

- [CL-GD542x datasheet.pdf](https://github.com/86Box/86Box/files/11444025/CL-GD542x.datasheet.pdf)
![image](https://github.com/86Box/86Box/assets/127716019/e76b2bd1-edfa-44a8-881a-b75b85e0d97e)

- [CL-GD542x Technical Reference Manual.pdf](https://github.com/86Box/86Box/files/11444035/CL-GD542x.Technical.Reference.Manual.pdf)
![image](https://github.com/86Box/86Box/assets/127716019/a76ed6b2-87c4-4039-b52a-fd56580680aa)

- [SMC FDC37C6XX datasheet.pdf](https://github.com/86Box/86Box/files/11444513/SMC.FDC37C6XX.datasheet.pdf)
![image](https://github.com/86Box/86Box/assets/127716019/edb4e660-7826-4047-95fa-4742d8bbee2b)

- youtube video link how to create F10 setup partition in Compaq Prolinea
https://www.youtube.com/watch?v=c63ZSKAahR0

- dropbox.com Compaq Prolinea MT disks provided from youtube link above:
https://www.dropbox.com/sh/02i1tlfzyvvjcok/AAC3Bvf2rLZmHP3S_T-dViH9a?dl=0

![image](https://github.com/86Box/86Box/assets/127716019/e2364f4d-38ad-447d-9711-e333ee57b4d7)

      sp1363.img  = setup disk to create f10 partition 
      sp16085.img = diagnostic disk

- screenshot of Compaq Prolinea MT running on 86box using the d824 machine config:

![image](https://github.com/86Box/86Box/assets/127716019/c929d6f9-9a89-4047-a725-ea946601b666)

![image](https://github.com/86Box/86Box/assets/127716019/c583e702-1998-4761-a0ec-ee35d006bbd6)

![image](https://github.com/86Box/86Box/assets/127716019/b6be8deb-8f91-4e62-9fd1-39254242a715)

![image](https://github.com/86Box/86Box/assets/127716019/d47dd27b-caf3-4e6f-9dd2-059ebaeeb75b)

![image](https://github.com/86Box/86Box/assets/127716019/441af8fd-ab16-447d-acb4-0dd87c2fe646)

![image](https://github.com/86Box/86Box/assets/127716019/97cc5617-ce78-4cfa-871f-e3554331b05f)

![image](https://github.com/86Box/86Box/assets/127716019/e17ce618-2f41-4b25-a730-72b06612a402)

![image](https://github.com/86Box/86Box/assets/127716019/e75bbf2c-0487-49bb-bf3a-2d6465c55277)

- Compaq INSPECT report output running from 86box:  [INSPECT.TXT](https://github.com/86Box/86Box/files/11444201/INSPECT.TXT)

- Harddisk image with only F10 Setup partition created using 86box: [s527mb,c1022,h16,63,type65.zip](https://github.com/86Box/86Box/files/11444387/s527mb.c1022.h16.63.type65.zip)
![image](https://github.com/86Box/86Box/assets/127716019/7f57c691-feff-4f18-81d6-713d3e0573b6)

- Harddisk image with minimal DOS 6.22 + NC5 partition and F10 Setup partition created using 86box: [s527mb,c1022,h16,63,type65 - MSDOS622 + NC5.zip](https://github.com/86Box/86Box/files/11447505/s527mb.c1022.h16.63.type65.-.MSDOS622.%2B.NC5.zip)
![image](https://github.com/86Box/86Box/assets/127716019/16e8ebe8-9ffc-4cd2-9cd7-c17cb540cec3)

- 86box CFG & NVR files:
[86box cfg & nvr.zip](https://github.com/86Box/86Box/files/11447508/86box.cfg.nvr.zip)

Thank you.

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
