### ISSUE TITLE
Add Support for Symmetric Multiprocessing (SMP)

### ISSUE THREAD

**Issue by mmoeller86** [86Box/86Box#3330]
**Is your feature request related to a problem? Please describe.**
Please add support for SMP.

**Describe the solution you'd like**
Add support for SMP to 86Box.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by TC1995** [comment]
Please...

**Comment by OBattler** [comment]
Not going to happen, sorry.
