### ISSUE TITLE
Add Support For The IBM PC Server 720

### ISSUE THREAD

**Issue by mmoeller86** [86Box/86Box#3331]
**Is your feature request related to a problem? Please describe.**
Add Support for the IBM PC Server 720 Computer.

**Describe the solution you'd like**
Add Support To 86Box. This machine supports upto 6 Intel Pentium Processors
interconnected by the Corollary C-BUS.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by OBattler** [comment]
Not going to happen.
