### ISSUE TITLE
add MSI MS-6199VA (retail and Packard Bell OEM)

### ISSUE THREAD

**Issue by pankoza2-pl** [86Box/86Box#3338]
**Is your feature request related to a problem? Please describe.**
No, I just want this Via Apollo Pro 133-based Slot 1 Board to be added to 86Box (especially the Packard Bell variant, as it would be our first Packard Bell AwardBIOS with a Working ACPI)

**Additional context**
https://theretroweb.com/motherboards/s/msi-ms-6199va
This board has no onboard video and a onboard Ensoniq/Creative AudioPCI sound
retail BIOS link: https://theretroweb.com/motherboard/bios/w6199vav35-60659bdd4ee86351532618.exe
Packard Bell OEM BIOS Link: https://theretroweb.com/motherboard/bios/phoen37-63654f773ea85920188014.exe

**Comment by cartifanwlr** [comment]
This would also benefit from the planned BIOS chooser feature.

**Comment by pankoza-pl** [comment]
> This would also benefit from the planned BIOS chooser feature.

I would prefer it being 2 separate machines tho "MSI MS-6199VA" and "Packard Bell Phoenix"

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.

Also, the whole point of the BIOS selection feature is to declutter the list, so these two machiness will be added using that.

**Comment by pankoza2-pl** [comment]
> Also, the whole point of the BIOS selection feature is to declutter the list, so these two machiness will be added using that.

does that mean that (for example) the 386sx Chaintech 325AX will be changed to use that feature rather than separate machines?

**Comment by cartifanwlr** [comment]
> > Also, the whole point of the BIOS selection feature is to declutter the list, so these two machiness will be added using that.
> 
> does that mean that (for example) the 386sx Chaintech 325AX will be changed to use that feature rather than separate machines as it is now?

Exactly.

**Comment by pankoza2-pl** [comment]
In addition, please add the Compaq OEM variant as well in addition to retail and PB OEM

**Comment by OBattler** [comment]
Don't we already emulate the MSI MS-6168 / Packard Bell Bora Pro which is very similar?

**Comment by pankoza2-pl** [comment]
But the Packard Bell Bora Pro BIOS has broken ACPI
And now this MS-6199VA is added
