### ISSUE TITLE
ISA RTC year rollover incorrect in DCB mode

### ISSUE THREAD

**Issue by 640-KB** [86Box/86Box#3346]
**Describe the bug**
Using ISA RTC SixPakPlus,  EV-170 or 5-PAK devices when rolling over to a new year (ex: 2023-12-31 23:59:50 -> 2024-01-01 00:00:00) the year register value is updated incorrectly.  On these devices the low two digit year is stored as a byte value, whereas on the PII-147 Hexa I/O Plus device it is stored as BCD which increments correctly.  The issue only appears to be related to storing/converting the year as byte (DCB).

**To Reproduce**

1. Use "Generic XT", with ISA RTC "SixPakPlus". Occurs regardless of local synchronization setting.
2. Run DOS DEBUG
3. Read Year register (`i 2ce`) which for 2023 should be `0x2B` (`23 + 20 = 2B`).
4. Set the date/time to 2023-12-31 23:59:50 (see screenshot 1).
5. Wait 10 seconds
6. Read Year register again (`i 2ce`) which now shows `0x20`, representing 2012.  Expected result is `0x2C`, representing 2024.

**Expected behavior**
On SixPakPlus, EV-170 or 5-PAK, expected result after year rollover from 2023 is `0x2C`, representing 2024.

On PII-147 Hexa I/O Plus device, year register `0x2E` correctly increments from `23` BCD to `24` BCD.

#### Screenshot 1 - ISA RTC SixPakPlus year rollover (incorrect):
<img width="481" alt="86b_ast_1" src="https://github.com/86Box/86Box/assets/23486433/73414d8c-3912-42a0-819c-504e4c8deebc">

#### Screenshot 2 - ISA RTC PII-147 Hexa I/O Plus (correct):
<img width="481" alt="86b_hexa_1" src="https://github.com/86Box/86Box/assets/23486433/e475ef06-8e1d-4d20-9295-5773bdd551ce">

**Desktop (please complete the following information):**
 - OS: Windows 10, 11
 - 86Box version: v3.1.1 Windows-64-build 4311 and v4.0 Windows-32-build 4625
 - Build information: Stable and latest Experimental

**Comment by OBattler** [comment]
See if the latest commit fixes this.

**Comment by 640-KB** [comment]
Yes, it seems to be working correctly in build 4630.  Thanks!
