### ISSUE TITLE
Application WindSock.EXE gives an error

### ISSUE THREAD

**Issue by Klemen75** [86Box/86Box#3354]
The problem is, that this specific windows benchmark application named WindSock always gives an error "Divide by zero or Overflow Error". I know for sure it did work in some previous version some time ago.

**To Reproduce**
I have attached an RAR archive with this application. So you can test it and reproduce the error. Just run it in the emulator under Windows 3.1 or 3.11.

**Expected behavior**
The application should have run without problems.

**Screenshots**
<img width="872" alt="image" src="https://github.com/86Box/86Box/assets/133699729/cc4f9b7c-0f1d-4579-aff2-006a186220ca">.

**Desktop (please complete the following information):**
 - OS: Windows 3.11 on DOS 6.22
 - 86Box version: 4.0 build 4626
 - Build information: x86_64, new dynarec

**Additional context**
Not really much to add. As already mentioned, this application used to run on some previous build. Sadly I don't recall the build.
But can say, that it runs under windows 95 in the emluatior tough it still gives an error when ran, but if you click ignore, it then runs just fine,
[WINDSOCK.zip](https://github.com/86Box/86Box/files/11481084/WINDSOCK.zip)

**Comment by OBattler** [comment]
Please bisect and find which 86Box build broke it.

**Comment by Klemen75** [comment]
> Please bisect and find which 86Box build broke it.

Hello,

OK, I've bisected the versions and found out, that build 3961 broke the thing. With build 3960, the app runs fine.

Hope that'll help you.

Regards,
Klemen

**Comment by OBattler** [comment]
So apparently, the faster (but less accurate) PIT emulation is the cause. I think we should add some way to force one PIT more or the other.

**Comment by Klemen75** [comment]
Hello,

indeed that's the problem. As soon as I put the variable pit_mode=0 in the config file, the app runs OK.

Hope you'll put that setting in the GUI config - and make 3 choices (OFF, ON, ON SLOW)... :)

Regards,
Klemen

**Comment by OBattler** [comment]
Well, OFF would make no sense - the PIT is needed for the basic functionality of the machine (DRAM refresh, PC speakers, etc.). But a PIT mode toggle (Auto - Slow - Fast) would make sense.
