### ISSUE TITLE
Shift + F10 produces unexpected behavior.

### ISSUE THREAD

**Issue by Bloodbat** [86Box/86Box#3355]
**Describe the bug**
When the Shift + F10 combination is pressed and 86Box is fullscreen the screen fades to black briefly and then returns to whatever program is running inside the VM. When the VM is windowed no black screen occurs but input is suspended until another key is pressed and a Windows error bell plays in the host OS. The shift is left in a stuck state in the guest. This makes certain programs unusable or unplayable (such as X-Wing and Tie Fighter).

**To Reproduce**
Version 1:
-Start an 86Box VM under a Windows host.
-Press Shift+F10.
-Try to type something.
-Get error bell in host and stuck shift in guest.

Version 2:
-Start an 86Box VM under a Windows host.
-Put 86Box in fullscreen mode.
-Press Shift+F10.
-Notice the screen flashes black and then returns to the 86Box guest.
-Try to type something.
-Get error bell in host and stuck shift in guest.

**Expected behavior**
The VM should send this key to the guest OS.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: 3.11 Build 4311
 - Build information:  86Box-Windows-32-b4311.zip  from Releases.

**Additional context**
I tested this problem with both FreeDOS and MS-DOS guest OSs.
I don't know if this is an internal 86Box hotkey: it isn't listed anywhere I checked. I do know, however, that Windows uses that key combination to display a context menu and maybe that's what's happening, even if 86Box doesn't have such a menu. I don't know if it affects other OSs.

**Comment by OBattler** [comment]
Try the latest Jenkins build, there have been a lot of keyboard-related fixes since build 4311.

**Comment by Bloodbat** [comment]
Tried with 86Box 4.0 build 4626: the latest I found in Jenkins. The screen no longer blackens with Shift+F10 in fullscreen mode but the Windows error bell is still present and input is still lost.

**Comment by Bloodbat** [comment]
I tried 86Box-ODR-Dev-Windows-MINGW32-gha5926 and the issues are no longer present. Though, sadly, it's missing some of the QT perks. Maybe QT is at the core of the problem, though.
