### ISSUE TITLE
With a Gravis Ultrasound sound card, the Impulse Tracker freezes

### ISSUE THREAD

**Issue by DroidU** [86Box/86Box#3362]
**Describe the bug**
With a Gravis Ultrasound sound card, the Impulse Tracker freezes.

**To Reproduce**
1. Start Impulse Tracker (The GUS sound card will be detected automatically).
2. Press F9 to browse the modules, then select the music to load.
3. Instant freezing.

**Expected behavior**
It should load the music, after which it can be played with F5.

**Screenshots**
![it](https://github.com/86Box/86Box/assets/67386933/3d00649c-9bed-42c9-9f71-e86784b44c8a)

**Desktop (please complete the following information):**
 - OS: MX Linux 21
 - 86Box version: build 4631

**Comment by mfmcosta** [comment]
As for build 5416 (Old Recompiler - 32-bits) - it works.
![image](https://github.com/86Box/86Box/assets/136728257/cae2defa-3584-4afe-b5d2-edc9a23c9c27)
but I've to install the [Gravis Ultrasound drivers](http://www.dosdays.co.uk/topics/Manufacturers/gravis.php)
without them, it hangs the emulation

**Comment by OBattler** [comment]
Then I guess it's NOTABUG - just install the drivers first. The card likely needs some configuration first for this to work.
