### ISSUE TITLE
Ctrl+Alt+PgUp/PgDown not working to go fullscreen or back in Linux  

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#3363]
Using the latest 4631 linux appimgae.

Unable to use shortcut Ctrl+Alt+PgUp or PgDown to go fullscreen or revert back.

Using HP Pavilion Gaming 15 Laptop with Nvidia GTX1650. Running Arch Linux with KDE.

Running under OpenGL 3.0 core. 

EDIT : After pressing CTRL+ALT+PgUP, (release) and THEN pressing NumLock works. To go back to normal window, need to press CTRL+ALT+PgDOWN (release) and THEN press NumLock.

**Comment by parkerlreed** [comment]
Just tried 4704 and the toggle is working without using numlock.

**Comment by Mal752** [comment]
> Just tried 4704 and the toggle is working without using numlock.

Yes, I confirm this issue is resolved in 4704.
