### ISSUE TITLE
86box crashing on startup

### ISSUE THREAD

**Issue by BreadTeleporter** [86Box/86Box#3364]
**Describe the bug**
86Box crashes on startup, this is a fresh install and does happen on normal 86box too (edit: non-winbox 86box).
For some reason the configuration screen:

![csafuyhis](https://github.com/86Box/86Box/assets/103989916/4d8ccf33-5870-40e3-8765-55b6d2659ec5)

Works fine.

**To Reproduce**
Not sure what to put here, as it crashes no matter what I do.

**Expected behavior**
Have 86box start and run.

**Screenshots**
See included video

**Desktop**
 - OS: Windows 10 21H2
 - 86Box version: v3.11

**Additional context**
This also happens on any other build I tried

https://github.com/86Box/86Box/assets/103989916/509c2a22-22ca-4c89-831b-df3a1e865be2

**Comment by TC1995** [comment]
Most likely some library or something you haven't set up.

**Comment by richardg867** [comment]
Please attach your 86box.cfg file for this machine, so we can at least try to reproduce this issue.

**Comment by BreadTeleporter** [comment]
This happens even if I don't have an 86box.cfg

**Comment by BreadTeleporter** [comment]
Update: For some reason opening an item in the menu bar will allow the emulator to start, but as soon as you close it, the emulator will crash

![what](https://github.com/86Box/86Box/assets/103989916/359a23b3-b11d-4292-b48b-920025689bc6)

**Comment by BreadTeleporter** [comment]
> Are you using:
> 
> win32 or qt version? 32 or 64 bit version? New dynarec or old dynarec version?
> 
> It would also help if you would attach your 86box.cfg so we can try to reproduce.

Not sure for the one provided in Winbox for 86box, as it is automaticly downloaded, however for the manually downloaded copy I have (which has the same behavior) I am using this download from the releases page (v3.11), 86Box-Windows-64-b4311.zip

I am also using the x64 version and, because I am on windows ( :-( ), I am fairly sure I am using the win32 version.

Not sure on the dynarec version, but I think that is linux only (please correct me if I am wrong though, because I have not use 86box on linux much)

**Comment by cold-brewed** [comment]
You still haven't provided the configuration file. We'll need that before going any further.

Dynarec type applies to all platforms (old or new). 

Since you're using the win32 version, please try the qt version. Grab the latest CI build from https://ci.86box.net/job/86Box/ (*not* the github release)

Choose: New Recompiler -> Windows x64 -> `86Box-NDR-Windows-64-b4638.zip` (just an example, actual version number may vary)

**Comment by BreadTeleporter** [comment]
> You still haven't provided the configuration file. We'll need that before going any further.
> 
> Dynarec type applies to all platforms (old or new).
> 
> Since you're using the win32 version, please try the qt version. Grab the latest CI build from https://ci.86box.net/job/86Box/ (_not_ the github release)
> 
> Choose: New Recompiler -> Windows x64 -> `86Box-NDR-Windows-64-b4638.zip` (just an example, actual version number may vary)

Thanks for the clarification. Still kind of a noob with 86box :p.
Gave the NDR build a try, but still shows the same behavior.

Also turns out I was using the qt build. Sorry!
Thought: Windows = win32 = I'm using the win32 build :p


Here is my auto generated (by 86box) 86box.cfg


[General]
vid_renderer = qt_software

[Machine]
machine = ibmpc
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 64

[Video]
gfxcard = cga

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

**Comment by cold-brewed** [comment]
In the video you are using WinBox, which may be related to your crashes. WinBox is no longer updated or supported.

I can't reproduce any of the issues you are mentioning.

Download the latest CI build from the links above, extract into its *own* separate directory, and directly launch `86Box.exe` from there - no managers. See if the problem still occurs.

**Comment by BreadTeleporter** [comment]
>Download the latest CI build from the links above, extract into its own separate directory, and directly launch 86Box.exe from
there - no managers. See if the problem still occurs.

Still happens even with every build of winbox on the jenkins page and the github.

**Comment by cold-brewed** [comment]
I'm asking you to *not* use winbox. Just use execute 86box directly.

**Comment by BreadTeleporter** [comment]
I am executing 86box directly though...

**Comment by jriwanek** [comment]
You literally said above that it happens with every build of *winbox* though.

**Comment by BreadTeleporter** [comment]
Oof, typo, sorry about that

**Comment by segadude** [comment]
I have been having a similar issue. No build of 86Box works on my computer. It doesn't matter if I run 86Box through WinBox or run the 86Box executable directly. 86Box crashes shortly after start-up. Sometimes 86Box will get partway through the BIOS POST process before it crashes, but most of the time it just runs for a few seconds and then closes. The configuration screen also works fine for me. I started having this issue a little over a week ago. The same builds work fine on another computer I tried running the same version of Windows 10. I made a [post](https://discord.com/channels/262614059009048590/1113243340801048586) on the 86Box Discord that has more information.

**Comment by ksio89** [comment]
Same issue, 86Box crashes on startup, no matter the hardware or operating system being emulated or version, be it either stable or experimental. New dynamic recompiler builds also crash during boot.

**Comment by segadude** [comment]
> Same issue, 86Box crashes on startup, no matter the hardware or operating system being emulated or 86Box version, be it either stable or experimental. New dynamic recompiler builds also crash during boot.

Do you have vJoy installed by chance? That's what was causing the issue for me, specifically vJoy 2.0.5. When I disabled the vJoy device in Device Manager 86Box started working again. A mitigation was added to prevent this crash in build #4657 so that build and newer should work if vJoy is what is causing the issue for you.

**Comment by ksio89** [comment]
> > Same issue, 86Box crashes on startup, no matter the hardware or operating system being emulated or 86Box version, be it either stable or experimental. New dynamic recompiler builds also crash during boot.
> 
> Do you have vJoy installed by chance? That's what was causing the issue for me, specifically vJoy 2.0.5. When I disabled the vJoy device in Device Manager 86Box started working again. A mitigation was added to prevent this crash in build #4657 so that build and newer should work if vJoy is what is causing the issue for you.

No, I don't even know what vJoy is.

**Comment by cold-brewed** [comment]
> Same issue, 86Box crashes on startup, no matter the hardware or operating system being emulated or 86Box version, be it either stable or experimental. New dynamic recompiler builds also crash during boot.

@ksio89 Please open a separate issue and fill out the issue template so it can be tracked independently.

**Comment by OBattler** [comment]
I believe this can now be closed since I believe this has turned out to have been caused by the vJoy initialization, which has since been fixed.
