### ISSUE TITLE
Please add support for AST Advantage! Adventure 4066d in 86box

### ISSUE THREAD

**Issue by saipan7** [86Box/86Box#3366]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
86box support AST Advantage! Adventure 4066d.

**Additional context**

Mainboard Info:
https://stason.org/TULARC/pc/motherboards/A/AST-RESEARCH-INC-486-ADVANTAGE-4000-SERIES-486-234.html

Mainboard bios download:
Advantage! Adventure 4066d BIOS 05560031.exe
http://www.sandyflat.net/digerati/ast486/drivers/d-bios/05560031.exe

[05560031 -- Advantage Adventure 4066 bios unpacked](https://github.com/86Box/86Box/files/11547480/05560031.--.Advantage.Adventure.4066.bios.zip)
![image](https://github.com/86Box/86Box/assets/127716019/0c434a5c-070f-4c2b-9a36-bc91ff16ad6e)

Mainboard Chipset Info:
SiS 85C471
https://archive.org/download/SiS-85C471-datasheet/SiS-85C471-datasheet_text.pdf
![image](https://github.com/86Box/86Box/assets/127716019/02d6222f-7453-4584-b49d-fb8c64190464)

CL-GD542x datasheet:
https://wolumen53.com/pdf/CL-GD542x_CirrusLogic.pdf
![image](https://github.com/86Box/86Box/assets/127716019/5a6ad5d8-d262-489c-9198-09ae8501bc05)

CL-GD542X Technical Reference Manual Jan1994:
https://archive.org/download/bitsavers_cirrusLogichnicalReferenceManualJan1994_24841698/CL-GD542X_Technical_Reference_Manual_Jan1994.pdf
![image](https://github.com/86Box/86Box/assets/127716019/a73786cc-3a54-4da8-8021-a913a1f07a7c)

Computer Screenshot:
![image](https://github.com/86Box/86Box/assets/127716019/43b8ef16-e537-4204-8860-843836097ffa)

![image](https://github.com/86Box/86Box/assets/127716019/3940decb-9a56-4e98-a16f-00b405806e2c)

![image](https://github.com/86Box/86Box/assets/127716019/c3c4eb05-96fb-4877-b05f-a2266cd85566)

![4066d8](https://github.com/86Box/86Box/assets/127716019/ae6842ee-1a41-401e-9913-9e344b0e9e3e)

![image](https://github.com/86Box/86Box/assets/127716019/a77fd7e2-5b4a-45ba-9d3a-04f12b35ea3c)

![image](https://github.com/86Box/86Box/assets/127716019/21a027cc-62fd-4c56-a27c-314cd3ff8fe4)

Screenshot of AST Advantage! Adventure 4066d running on 86box using  [SiS 461] Acer v10 machine config:
![image](https://github.com/86Box/86Box/assets/127716019/af14eed2-347c-4d2f-926f-75cdbbdfb30e)

![image](https://github.com/86Box/86Box/assets/127716019/2a52a9db-0401-4bba-8e80-d6c9520beaa7)

![image](https://github.com/86Box/86Box/assets/127716019/650d5dcb-d0bd-42f8-a22c-6ee15dc1c1bd)

![image](https://github.com/86Box/86Box/assets/127716019/346a87de-63c3-469a-bcae-ad90541cf30f)

86box CFG & NVR file: 
[86box cfg + nvr.zip](https://github.com/86Box/86Box/files/11547509/86box.cfg.%2B.nvr.zip)

Youtube video:
AST ADVENTURE 4066d Cyrix 486 DX2 All-In-One Demo
https://www.youtube.com/watch?v=trFXOMVNtiA

Thank you.

**Comment by TC1995** [comment]
Well, components documentation if any?

**Comment by OBattler** [comment]
It's SiS 471 + on-board Cirrus Logic video, we already emulate both.

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.

**Comment by Paatuska** [comment]
how did you flash ast bios to this " [SiS 461] Acer v10 machine" ?

**Comment by jriwanek** [comment]
You can clearly see the computer itself in the pictures.
