### ISSUE TITLE
Degraded performance compared to PCem (same specs)

### ISSUE THREAD

**Issue by Cereal-Killa** [86Box/86Box#3369]
I have a Slot 1 Celeron machine that I can't seem to get good multimedia performance, if I move any window around the audio gets choppy. I recreated the machine from the scratch and it didn't help, the very same config I have on a PCem machine and it runs flawlessly.

Please feel free to close this if inadequate, I'm posting here because 86Box is based on PCem and I am curious to know what deviates from it that could be affecting the audio/multimedia performance so bad

**To Reproduce**
1. Create a Celeron Mendocino 266 machine with a voodoo 3 + awe32
2. Play a midi file
3. Move any window around
4. Audio is choppy

**Expected behavior**
Due to the host machine being an Intel Core i7 11th gen (desktop) paired with a RTX2060 and 32gb of ram we expect that moving windows around will not affect the audio playback like it does on 86Box.

**Screenshots**
![config_cpu](https://github.com/86Box/86Box/assets/25939765/7f1bb22e-e514-4b9d-8aa6-1edb7a5b88d9)
![config_vga](https://github.com/86Box/86Box/assets/25939765/be2f8059-5c54-4661-a6a7-6fb4c4876d23)
![config_audio](https://github.com/86Box/86Box/assets/25939765/b5ecb1b9-6e12-4c40-9810-dbb11b1e621e)

PCEm
https://github.com/86Box/86Box/assets/25939765/4a31d1bb-0733-495a-ad65-77fa36e6479d

86Box
https://github.com/86Box/86Box/assets/25939765/1c77725b-3558-47cf-b86b-be87c7faf85d

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: 3.11 4311
 - Build information: x64

**Comment by OBattler** [comment]
PCem uses the new recompiler which is faster in some cases but slower in others, and is also quite a bit buggier. That's the biggest reason for the performance difference.

**Comment by Cereal-Killa** [comment]
Gotcha, thank you for explaining and for the hard work put on 86box, it's coming out great!
