### ISSUE TITLE
Nicktoons Basketball visual glitch

### ISSUE THREAD

**Issue by MInecrafterPictures** [86Box/86Box#3373]
When I tried playing Nicktoons Basketball on 86Box version 4.0 build 4633 and I noticed a lot of flickering that are absent on real hardware. I tried taht on a real Windows XP machine, no problem.
It was still playable but still flashy and slow.

Here are some of the emulated specs.
Motherboard: ASUS P/I-P65UP5 (C-P6ND)
CPU: Intel Pentium OverDrive @ 200 MHz
GPU: ATI Mach64GX 4MB + Voodoo2 4MB
OS: Windows 98 SE

![image](https://github.com/86Box/86Box/assets/67380524/bbf46ca1-10bb-4c13-9878-ce85ccd3e396)

**Comment by pankoza-pl** [comment]
Can you show the screen shot or video of the game glitching?

**Comment by MInecrafterPictures** [comment]
It's mostly in the menu, and sometimes in the in-game itself, that has random flashes.
Looks mostly normal, but it still flashes, especially in the title menu.
It's completely absent when I try using my real Windows XP PC.
Another problem I noticed is that the videos the game plays display the wrong colors and it runs slower than the audio like it's having a delay or something. It videos don't play correctly.

Here's a screenshot regarding one of the issues:
![Corrupted 86Box 1](https://github.com/86Box/86Box/assets/67380524/cdae9bf3-7ea6-43af-9c18-8a9602de5d2b)

And here's a video regarding a different issue:

https://github.com/86Box/86Box/assets/67380524/df1d3a0b-7a50-47a8-bd76-4533f89f55b8

I hope this helps you troubleshoot the glitches.

**Comment by MInecrafterPictures** [comment]
As I said, I can play just fine despite the graphical glitches

**Comment by MInecrafterPictures** [comment]
Mind the bad framerate

**Comment by cold-brewed** [comment]
Try changing the Render Threads to 2 instead of 4. 4 is more demanding on the host system and can result in visual artifacts.

The flashing in the video is something commonly seen when the Render Threads option is set too high.

**Comment by MInecrafterPictures** [comment]
https://github.com/86Box/86Box/assets/67380524/50bd02d7-4b16-459e-a9e3-5c384db7a7e5

No change. Also, the videos are still bugged up.
Video playback outside of the game (more specifically from a Powerpuff Girls DVD) worked fine even with 4 except from some frame skipping and low quality audio (I think the latter is normal, but I have no confirmation)

**Comment by MInecrafterPictures** [comment]
Don't mind the audio change. It's from my host PC with an equalizer used for my speakers.

**Comment by MInecrafterPictures** [comment]
The Powerpuff Girls DVD I used works fine on my host PC, except partially for some extras. The DVD part plays fine.

**Comment by MInecrafterPictures** [comment]
The issue I want to address is with Nicktoons Basketball. The Powerpuff Girls DVD is minor due to the DVD part working perfectly on real hardware.

**Comment by cold-brewed** [comment]
Nicktoons Basketball was released in September 2004, well into the XP era. 86Box targets the 95/98 era and before. 

Moby Games lists the minimum specs as a PIII with DX9. There are no video cards in 86Box that support DX9 (nor is there a PIII).

You'll have better luck running a game from this era on a physical windows system with compatibility tweaks / options applied.

**Comment by MInecrafterPictures** [comment]
But I know it doesn't work well enough on a modern PC.
And it's compatible with at least Windows 98.

2 other XP era games that I know they don't work quite well on a modern Windows 10/11 PC (and by that I meant not working at all IIRC) is Neighbours from Hell (with minimum OS support being Windows 95 with DirectX 8) and its sequel, which supports at least Windows 2000 and also DirectX 8, but I don't think they're the odds of it being working and I haven't tested the 2 games yet.

Also, I'm not knowledgeable enough to know which Win98 compatible GPU supports DirectX 8 or 9 or not. Or there's none from Win9x era that supports them.
I heard that DirectX 9.0c is the latest supported by Windows 98 btw.

**Comment by cold-brewed** [comment]
The game is too new for 86Box for the reasons mentioned above. I suggest looking into compatibility tweaks on a physical system.

**Comment by MInecrafterPictures** [comment]
Maybe they're undumped so far? I just don't know, even physically, if they're Win9x compatible DirectX 9 or 8 GPUs.

**Comment by MInecrafterPictures** [comment]
Like I said, my emulated CPU is a Intel Pentium OverDrive clocked at 200MHz.
However, by that, I mean Pentium II OverDrive. Forgot to add the II.

**Comment by MInecrafterPictures** [comment]
Not sure what is the minimum HTz required, but, bugs asid, it seems to work fine except for maybe minor slowdowns

**Comment by OBattler** [comment]
Well, if it works (despite the emulated hardware not meeting its minimum requirements), then this can be closed.
