### ISSUE TITLE
How to enable 8514/A?

### ISSUE THREAD

**Issue by AshUosis** [86Box/86Box#3375]
I'm having problems enabling 8514/A

**Comment by cold-brewed** [comment]
Please use the issue template. It is there for a reason. 

To enable: Settings -> Display -> 8514/A

**Comment by AshUosis** [comment]
> Please use the issue template. It is there for a reason.
> 
> To enable: Settings -> Display -> 8514/A

when i run windows 2.11 it exits ot although that may be a problem with windows bc i tried installing windows 2.11 on vmware it also exits and only runs when i run win86

**Comment by AshUosis** [comment]
> > Please use the issue template. It is there for a reason.
> > To enable: Settings -> Display -> 8514/A
> 
> when i run windows 2.11 it exits ot although that may be a problem with windows bc i tried installing windows 2.11 on vmware it also exits and only runs when i run win86

yep it's windows
