### ISSUE TITLE
XGA 1 and 2 video bugs

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3382]
**Describe the bug**
I tested Windows 3.1 on IBM PS/2 model 80 386, with Windows 3.1 and XGA 1and 2 Video adapter. I usedthe default Win 3.1 drivers with XGA-1 and installedXGA 2.10 video drivers for the model 2, I found random bugs at startup on 256 color modes on both video cards (black screen with the mouse pointer only or buttons without any Window) and also that the 640x480x64k color mode has the wrong colors on XGA-2. 

**To Reproduce**
1. Start the VM
2. type "WIN" at DOS prompt

Here are NVR/CFG and HDD files:

HDD:
[IBM 386 ESDI Type 9 drive.zip](https://github.com/86Box/86Box/files/11644553/IBM.386.ESDI.Type.9.drive.zip)

CFG+NVR
[IBM PS-2 386.zip](https://github.com/86Box/86Box/files/11644563/IBM.PS-2.386.zip)

**Screenshots**
This happens on boyh 64k and 256 colors video mode
![XGA-2 Bug002](https://github.com/86Box/86Box/assets/31600563/a2633426-3d02-482f-88f4-d76f571af748)

![XGA-2 Bug001](https://github.com/86Box/86Box/assets/31600563/ade7f932-dcc5-4b90-9543-bfa5313fd625)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 4.0.0.4639
 - Build information: old dynarec, Win 32

**Comment by TC1995** [comment]
I partially fixed the color one, and again, don't use the 1mb vram addressing, win3.x expects the 4mb one.
