### ISSUE TITLE
EGA incorrectly implements split screen

### ISSUE THREAD

**Issue by cons-cinnabar** [86Box/86Box#3386]
86Box's 'EGA' card seems to incorrectly handle 'split screen' (line compare) feature.

When vid_ega.c finds the split screen line is matching it resets ega->ma and ega->maback to the EGA's start address.  This is incorrect.  The split window is independent of start address.  

```
if (ega->interlace && ega->oddeven)
                ega->ma = ega->maback = ega->ma_latch + (ega->rowoffset << 1);
            else
                ega->ma = ega->maback = ega->ma_latch;
```

now as:

```
        if (ega->vc == ega->split) {
            if (ega->interlace && ega->oddeven)
                ega->ma = ega->maback = (ega->rowoffset << 1);
            else
                ega->ma = ega->maback = 0;
```

I don't really know about how to do pull requests or whether I've got this correct, but it improved the behavior for me.

**Comment by iamgreaser** [comment]
Had to read it a few times as I was skeptical at first... and yes that does appear to be incorrect, whoops.

That also reminds me that according to Michael Abrash's Graphics Programming Black Book, chapter 30, the original EGA has a bug where the address 0 scanline is rendered twice. I don't think we're emulating that yet. But that's technically another issue.

I'll get onto this.
