### ISSUE TITLE
glsl shaders are applied in incorrect order

### ISSUE THREAD

**Issue by KristopherTadlock** [86Box/86Box#3392]
Opengl 3.0 renderer applies glsl shaders before other screen effects are applied. 

In particular this effects the "Force 4:3 display ratio".  The shader is applied first, and then the aspect ratio is corrected, causing uneven application of the shader effects. 

This namely effects things like scanline generation. 

As most software (even the command prompt) will need adjustment to reflect the intended aspect, this means that shaders are only applied correctly in the minority of use cases - largely high resolution SVGA modes which use square pixels.  

Incorrect application of the shader causes uneven scanlines
![incorrect](https://github.com/86Box/86Box/assets/6538032/71493ae8-0da9-45f6-be87-8e527872dcf7)
[86box_incorrect.cfg.txt](https://github.com/86Box/86Box/files/11713111/86box_incorrect.cfg.txt)

Removing other render effects fixes the issue, but now the aspect ratio is no longer correct
![correct](https://github.com/86Box/86Box/assets/6538032/875928ba-3f77-40b8-817c-88d9592ee36f)
[86box_correct_wrong_aspect.cfg.txt](https://github.com/86Box/86Box/files/11713116/86box_correct_wrong_aspect.cfg.txt)

Shader used
[shader.zip](https://github.com/86Box/86Box/files/11713128/shader.zip)

**Comment by OBattler** [comment]
Because the shader is applied to the renderer surface, which is then stretched to 4:3. To do as you suggest, we would have to somehow manually stretch to 4:3 (which would be very slow) and then apply the shader to it.

**Comment by OBattler** [comment]
So I guess this can be closed as CANTFIX, at least without destroying performance.
