### ISSUE TITLE
IDT Winchip CPU does  not work under Socket 5 430FX chipsets

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3394]
**Describe the bug**
I've  created a VM Windows 95 machine, The machine starts normally with Pentium CPUs but with the IDT chipsets the machine don't even post. Only a black screen can be seen. No matter if the dynarec is enabled or disabled with the ID Winchip. 
The IDT Winchips works fine on Socket 7 machines.

Here is the CFG/NVR file:
[Windows 95 OSR 2 Gravis Ultrasound Español.zip](https://github.com/86Box/86Box/files/11713490/Windows.95.OSR.2.Gravis.Ultrasound.Espanol.zip)

The HDD image is not necessary since it does not reach to boot the SO.

**To Reproduce**
1. import the CFG/NVR file
2. Start the VM

**Desktop (please complete the following information):**
 - OS: [. Windows 10
 - 86Box version: 4.0.0.4649
 - Build information: old dynarec, Win32

**Comment by OBattler** [comment]
This is normal, not every machine works with every CPU.

**Comment by OBattler** [comment]
So I'm closing this then.
