### ISSUE TITLE
[BUG] Sound Blaster Pro v2 mono sound bug

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#340]
Issue : No stereo sound using Sound Blaster v2. Sound is only left mono.

Tested with TEST-SBP.EXE which comes with the installation disks.

86Box versions tested on : 1624, 1811, 1820, all in 430VX and ASUS P54TP4XE configs.

Hosts : (1) Win10 x64, Dell Inspiron 7559 Laptop, Core i7 6700HQ, 8GB RAM, (2) Win7 x86, Lenovo Thinkpad X230, Core i7 3520m, 8GB RAM.

**Comment by OBattler** [comment]
Which is it? Sound Blaster Pro v2 or Sound Blaster v2? They are two different cards.

**Comment by Mal752** [comment]
It's Sound Blaster Pro v2.
