### ISSUE TITLE
Incorrectness on some models

### ISSUE THREAD

**Issue by mfmcosta** [86Box/86Box#3408]
Hi,
This is my first post.

All [8086] Amstrad shows the message: ERROR! FAULTY INTERVAL TIMER if speed above 10Mhz
Amstrad PPC512 / PPC640 / PC3086 supports 102-key AT Keyboard
source: http://oldcomputer.info/portables/ppc512/index.htm
source: http://oldcomputermuseum.com/amstrad_ppc640.html
source: https://oldcrap.org/wp-content/uploads/2023/04/amstrad-pc-pc3086-pc3286-pc3386sx-user-manual.pdf

IBM PS/ValuePoint 433DX/Si has integrated graphics (ET4000/W32)
source: https://ardent-tool.com/docs/pdf/vpbook.pdf

[286] Siemens PCD-2L not working - the graphics loads and then stops.
Tried with another ROM from VOGONS (https://www.vogons.org/viewtopic.php?f=46&t=60389&start=55) but the same happens.
The ROMS are spltted (double the size) but the same thing happens.

**Comment by pankoza-pl** [comment]
The IBM PS/ValuePoint 433DX/Si's integrated graphics is already implemented
I don't know about the rest tho

**Comment by OBattler** [comment]
102-key doesn't automatically mean AT, and I believe we do support Amstrad's proprietary arrow keys, etc.

**Comment by mfmcosta** [comment]
Sorry for the delay to answer...
1.- apologize for the IBM PS/ValuePoint 433DX/Si - I was expecting to see the "configure" button enabled on the machine tab and didn't realize it has internal controller in the display tab.
2.- about the Amstrads:
Perhaps I should talk about those models uses the IBM Model M keyboard and not the Model F (XT or AT).
Am changing the ROM of those PCs to use the portuguese keyboard layout instead the US keyboard layout and those ROM has 
In this image you an see the diference in code between the Model M (the current layout) and the Model F (older layout)
![image](https://github.com/86Box/86Box/assets/136728257/63d80a68-e698-4078-8088-67c1fb71eb4e)
In the left is the Amstrad PC2086 BIOS (keyboard code)

**Comment by mfmcosta** [comment]
Tandy 1000SL/2
This PC also supportes the Model M (Enhanced AT) Keyboard Layout
In the BIOS ROM you can see the location of 2 x "|" & "\" which indicates Enhanced AT aupport.
![image](https://github.com/86Box/86Box/assets/136728257/4f243426-ff25-4ee1-93ad-ffb3796d3355)
This page is from the Tandy 1000 SL manual
![image](https://github.com/86Box/86Box/assets/136728257/a1660232-0dca-4ac4-b96a-0e58da1ad844)
source: http://ftp.oldskool.org/pub/tvdog/tandy1000/documents/sltech.zip (page 241)

This means that many 8086 machines that came out after 1985 may support the Model M (Enhanced AT) keyboard

**Comment by OBattler** [comment]
Does the Model M keyboard even support the XT protocol required by these machines?

**Comment by mfmcosta** [comment]
I mix thing up about keyboard models and what I really try to explain.
When I saw the 86Box source code, I see some models with keyboard_xt... and keyboard_at... and that lead me to talk about the models M or F and to the confusion.

What I try to explain is here:
![image](https://github.com/86Box/86Box/assets/136728257/4748e1a6-e340-4f07-8d16-01bb2c3d28f0)
source: https://www.w3.org/TR/uievents-code/

These BIOS has support for the international backslash key as shown in the picture from my prevous comment:
[8086] Amstrad PPC512/640
[8086] Amstrad PC20(0)
[8086] Amstrad PC2086
[8086] Tandy 1000SL/2
[8086] Amstrad PC3086

In the other way, the BIOS of these NCR models:
[286] [ISA] NCR PC8/810/710/3390/3392
[286] [NEAT] NCR 3302
[386] [ISA] NCR PC916SX
don't support the International Backslash key.
If you press that key, you get "Q" and with shift you get no char on the screen.

I hope this helps you more than my prevous posts.

**Comment by OBattler** [comment]
The speed thing is now rectified - I have limited them to a maximum of 10 MHz.

And I confirm the 102-key keyboard: https://www.win.tue.nl/~aeb/linux/kbd/scancodes-3.html#ss3.1 . But it is a 102-key XT keyboard (same keys as the Model M, but XT protocol), not an actual Model M.

**Comment by OBattler** [comment]
The Amstrad keyboards are now rectified, which leaves the Siemens PCD-2L.

**Comment by OBattler** [comment]
And I just remembered that the Siemens PCD-2L was indeed broken and I have long since fixed it. Therefore, I am now closing this issue.
