### ISSUE TITLE
Missing DLLs

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [86Box/86Box#341]
Tested on 773b8bfd (32bit, regular build).
If you set LPT-port with Generic ESC/P Dot-Matrix, 86box shows warning popup window:
![image](https://user-images.githubusercontent.com/24764335/48200437-9595c000-e378-11e8-860b-f6a6fa49d4a3.png)

**Comment by OBattler** [comment]
You need the FreeType 2 .DLL. I'm going to change this message soon to be more accurate.

**Comment by jvernet** [comment]
Where can we dl those library ? tried different location without sucess...

**Comment by OBattler** [comment]
Download the official FreeType DLL and rename it to libfreetype-6.dll.

**Comment by jvernet** [comment]
Doesn't worked..
I try the first link from here: Windows DLL, not working. Second link to Mingw is dead.
https://www.freetype.org/download.html

Any working link ?

**Comment by daviunic** [comment]
Try using freetype.dll from win32 folder from here: https://github.com/ubawurinna/freetype-windows-binaries/releases/download/v2.9.1/freetype-2.9.1.zip

And of course rename it as OBattler said.
