### ISSUE TITLE
Missing INS key on macOS

### ISSUE THREAD

**Issue by step76** [86Box/86Box#3410]
Hello,

I'm using 86Box on Apple Silicon and everything is smooth, but I have some problems with the keyboard: on the Mac there is no INS key and so there is no way to map it inside 86Box. Would be nice to have a keyboard configurator to map keys.

Thank you.

**Comment by Cacodemon345** [comment]
Use Fn+Enter for Insert.

**Comment by step76** [comment]
I've already tried, but it doesn't work, Fn+Enter seems to be the numeric keypad enter key.
