### ISSUE TITLE
[Bug] MS-DOS 5.0 1.44 mb disk installer not recognized

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#342]
Hello
 
I tried to install MS-DOS 5.0 on 386 system with an 76mb hard disk. The DOS 5.0 1.44 mb installation disk seem not to work in 86box, but it works under DosBox ( at least the Daum version from 2015).
However the DOS 5.0 disk installation on 720kb and 360kb format works perfectly in 86box as well as MS-DOS 6.22 on 1.44mb format.
So I think there is something different with this file image.
Here is the link [https://drive.google.com/file/d/1o9zC0-uoJ7SVyjLMO4M5y5-hVls1Twjn/view?usp=sharing](url)

**Comment by OBattler** [comment]
Is the floppy drive configured correctly in both 86Box Settings and CMOS Setup?
Also, what machine are you emulating? It is running at 100%?

**Comment by OBattler** [comment]
OK, this floppy image appears to be the known weird copy. The files seem to be of the 720k version, put onto 1.44 MB images, with plenty of weird FAT entires. It might be simply be that real period BIOS'es refuse to boot it becasue they perform stricter checks than DOSBox.

**Comment by OBattler** [comment]
OK, this is either fixed or the user had something misconfigured, becaue I just tested this image and it works fine now. As such, I'm closing this issue.
