### ISSUE TITLE
Oak OTI 67/77 video  emulation of 8514 chip bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3420]
**Describe the bug**
I recently discovered on the OAK OTI-67 floppy disk drivers; drivers to emulte the 8514 chip under MS-DOS.
I tested both the OTI-67 with 512Kb VRAM and the OTI-77 with 1Mb of VRAM, both have the same screen bugs.
RIXAI4 have the wrong colors and RIXAI8 generates a wrong aspect ratio. 

CFG and NVR files:
[386 SX Headland Chipset DR-DOS 5.zip](https://github.com/86Box/86Box/files/11826711/386.SX.Headland.Chipset.DR-DOS.5.zip)

HDD image file:
[286-386SX-Headland.zip](https://github.com/86Box/86Box/files/11826718/286-386SX-Headland.zip)

OTI-67 driver disks:
[OAK 67 driver 1.zip](https://github.com/86Box/86Box/files/11826776/OAK.67.driver.1.zip)
[OAK 67 driver 2.zip](https://github.com/86Box/86Box/files/11826779/OAK.67.driver.2.zip)

**To Reproduce**
1. Start the VM
2. type cd rixai and execute the rixai4.exe file
3. To run the test program AITEST.EXE
4. To run the Majjong game that uses the 8514 1024x768 256 colors video mode. Type CD mj8514 and run mj8514.exe

**Expected behavior**

**Screenshots**
With RIXAI 8 driver:
![RIXAI 8](https://github.com/86Box/86Box/assets/31600563/5743c2e9-b7b5-4f3f-b00d-d334e9947ca4)

With RIXAI 4 driver:
![RIXAI 4 color screen bug](https://github.com/86Box/86Box/assets/31600563/6702e040-eaf0-4b4d-83e6-8ffc9c6ffd48)

RIXAI test utility
![RIXAI 4](https://github.com/86Box/86Box/assets/31600563/01f2dab9-bd65-4c30-b27a-797799953b32)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 4.0.0.4662
 - Build information: old dynarec Win32

**Comment by TC1995** [comment]
Does this happen on real hardware either?

**Comment by OBattler** [comment]
Closing this because it's stale and we have been unable to verify the behavior of the real hardware, also the documentation is not complete enough.
