### ISSUE TITLE
Windows NT 3.1 crashes with INACCESSIBLE_BOOT_DEVICE during setup

### ISSUE THREAD

**Issue by AshUosis** [86Box/86Box#3426]
**Describe the bug**
Alright, I know that this is probably just me being stupid but i don't know where else to talk about it. When i try to install windows nt 3.1, the first stage goes alright, but the second stage crashes with inaccessible_boot_device.

**To Reproduce**
1. Use Windows NT 3.1 floppy images from WinWorldPC.
2. Follow Setup Instructions.
3. Restart when it asks to.
4. See BSOD.

**Expected behavior**
It should've continued into the second setup stage.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - 86Box version: v3.11.0 build 4311
 - Build information: idk what that means
**Additional context**
Configuration:
Machine: i430VX AOpen AP5VM
CPU: Intel Pentium MMX (Speed:200)
Memory: 64MB
Display: VGA with XGA checked (Initial MCA BIOS Address: C000H, XGA type: XGA-1)
Mouse: Standard PS/2 Mouse (Buttons: Two)
Sound card: SoundBlaster 16 (Address: 0x220, MPU-401 Address: 0x330, IRQ: 5, Low DMA: 1, High DMA: 5, Enable OPL and Receive Input (SB MIDI) checked)
Use FLOAT32 sound checked
FM Synth driver: Nuked selected
Network card: Mode: SLiRP, Adapter: ISA16 Novell NE2000 (Address: 0x300, IRQ: 10, Bios address disabled
LPT1 Device: None
Serial port 1, Serial port 2, Parallel port 1 checked
HD controller: None, FD controller: Internal, SCSI controller 1: Adaptec AHA-154xC (Address: 0x334, IRQ: 11, DMA: 6, Bios address disabled)
SCSI hard disk (ID: 0:00, C: 1224, H:15, S:17, MiB: 152, RAM Disk)
3.5" 2.88M floppy drive, Check BPB checked
SCSI CD drive, Channel: 1:00, Speed: x8

**Comment by TC1995** [comment]
Well duh you need the Aha154xC SCSI bios enabled.

**Comment by OBattler** [comment]
Closing this with NOTABUG - enable the SCSI controller's BIOS.

**Comment by AshUosis** [comment]
> Well duh you need the Aha154xC SCSI bios enabled.

how am i supposed to know ok?

**Comment by sskras** [comment]
(on a related note)

@TC1995, @OBattler: folks, there are chances you know – what SCSI (or ATA) controller was supported by most versions of Windows installers out of the box?  

At least by older Windows version.  Or at least which two models could that be?

**Comment by AshUosis** [comment]
Still doesn't work

**Comment by TC1995** [comment]
The HDD should be at ID 0 with bios enabled, and the CD at ID 2.

**Comment by AshUosis** [comment]
> The HDD should be at ID 0 with bios enabled, and the CD at ID 2.

the hdd was already at 0 and i was installing from floppies
