### ISSUE TITLE
Olivetti M19 Display Error

### ISSUE THREAD

**Issue by mfmcosta** [86Box/86Box#3431]
Hi,
**Describe the bug**
The is problems with the Olivetti M19 display internal controller
If you try to use chars above 127 you get double bytes printed in place of one

**To Reproduce**
1. Create a Olivetti M19 machine
2. use a floppy or HDD to start DOS
3. Type at the prompt: <ALT>+201, <ALT>+205,...<ALT>+187
![M19](https://github.com/86Box/86Box/assets/136728257/94692e4e-3c1c-42ed-a22a-e1320be3da9a)

**Expected behavior**
If you use a diferent machine (e.g. Amstrad PC3086)
![PC3086](https://github.com/86Box/86Box/assets/136728257/7fbb434a-7384-4827-8cb1-3d0c41555511)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bits)
 - 86Box v4.0.build 44657
 - Build information: old dynarec 32-bits

**Additional context**
Searching 86Box issues, I've found this:
Fixed Olivetti M19 display bug #1886 (Dec 2, 2021 by EngiNerd89)
I don't know if there's a relation between the Fix and this bug.
Looking inside the BIOS ROM there is:
- The EGA charset has only 128 chars (0...127) - offset 0x005A to 0x0859
- The CGA charset is splitted as follows:
   128 chars in 8x8 (128...255) - offset 0x085A to 0x0C59
   128 chars in 8x8 (0...127) - offset 0x3A6E to 0x3E6D
What's shown in the first picture is BIOS code.

If you write ALT+201 it shows 2 chars in the place of one.
There's a file at archives.org with the name: MBM2764-30 8514 107 AB PCF3.BIN
This file contains the full 8x14 & 8x16 charsets
[MBM2764-30 8514 107 AB PCF3.zip](https://github.com/86Box/86Box/files/11896187/MBM2764-30.8514.107.AB.PCF3.zip)

**Comment by OBattler** [comment]
I don't see 8x14 there, just 8x8 (+ 8 zero bytes for each character) and 8x16.
