### ISSUE TITLE
Update Graphic Card category

### ISSUE THREAD

**Issue by mfmcosta** [86Box/86Box#3433]
**Is your feature request related to a problem? Please describe.**
I own a Trident TVGA 8900D and I remmember it is a 16-bit card but 86Box catalogue it as a 8-bit
Só I decide to search the web for the ISA cards 86Box support and check if they are ISA or ISA16 

**Describe the solution you'd like**
The following Graphic Cards are ISA 16 bits:
- ATI Korean VGA (based on 28800 chipset)
- ATI 28800-5 (ATI VGA Charger)
- ATI 28800-6 (ATI VGA Wonder XL) - it says 28800-5 but it's a 28800-6 chipset
- Cirrus Logic GD5401 (ACUMOS AVGA1)
- Cirrus Logic GD5402 (ACUMOS AVGA2)
- NEC SV9000 (Trident TVGA9000B)
- OAK OTI-067
- OAK OTI-077 
- Paradise WD90C30-LR
- Paradise WD90C11-LR
- Trident TVGA9000B
- Trident TVGA8900D
- Trident TVGA8900CL
- Tseng Labs ET3000AX
- Tseng Labs ET4000AX
- Video 7 VGA 1024i (HT208)

source: https://www.dosdays.co.uk/
source: https://www.vgamuseum.info/

**Comment by OBattler** [comment]
Closing this as NOTABUG.
