### ISSUE TITLE
Switching to full screen mode (Ctrl+Alt+PgUp) does not work on any machine

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#3434]
**Describe the bug**
Switching to full screen mode (Ctrl+Alt+PgUp) does not work on any machine. This bug was introduced in build 4668 and persists until the latest build. In build 4667 everything works fine.

**To Reproduce**
1. Run any machine in 86Box
2. Press Ctrl+Alt+PgUp to switch to full screen mode
3. See error

**Expected behavior**
Switching to full screen mode Ctrl+Alt+PgUp and back Ctrl+Alt+PgDn should work fine.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v22H2
 - 86Box v4.0.0 x86 Build 4673
 - Build type: regular, old recompiler

**Comment by Zack13358** [comment]
If you switch to full screen mode using the graphical menus, you can't switch back out of full screen mode. (I learned that the hard way :P)

**Comment by Mal752** [comment]
For me, I need to press Numlock after doing the Ctrl+Alt+PgUp or Ctrl+Alt+PgDown to make it fullscreen and back.

**Comment by AshUosis** [comment]
for me you have to hold it for a few seconds and it then works
