### ISSUE TITLE
Bad attention request 03 error during Windows NT 3.1 installation

### ISSUE THREAD

**Issue by Computerboi13** [86Box/86Box#3435]
When i try to install Windows NT 3.1 in an IBM PS/2 model 80, after the optional components part in the Windows graphical setup, an error window appears saying "Bad attention request 03". Clicking the X closes the emulator.

![Bad attention request 03](https://github.com/86Box/86Box/assets/127628245/dfc5b9e9-80c8-4743-b38c-5792b17d3312)

I tested this in both 86Box version 3.11 build 4311 and Jenkins version 4.0 build 4673.
Host OS is Windows 10.

Here is the nvr and cfg files, i also added the bootdisk i made incase it has something to do.
[Files.zip](https://github.com/86Box/86Box/files/11910024/Files.zip)

**Comment by TC1995** [comment]
Set a proper speed of the MCA ESDI controller, like, 1994-1996 period speed as ram disk speeds are problematic with the ESDI MCA controller.

**Comment by Computerboi13** [comment]
It works

**Comment by Computerboi13** [comment]
In version 3.11 when i put 1994 it seemed to work but then...
![Bad attention request 03 #2](https://github.com/86Box/86Box/assets/127628245/7aa039cc-ef73-4368-8de8-d3fb6f7f54f0)
With 1992 it was at half but the same error reappeared.

In Jenkins version 4.0 with 1994 the same error appeared.
![Bad attention request Jenkins](https://github.com/86Box/86Box/assets/127628245/80e80fd3-972a-4b91-84cf-9eb57f8380cd)

**Comment by TC1995** [comment]
try using the nightly builds or a lower speed.

**Comment by TC1995** [comment]
Also, are you using the QT win32 or just win32 without QT? There might be that the hdd speed side on 3.11 wasn't available.

**Comment by Computerboi13** [comment]
Idk what is a QT win32.

**Comment by TC1995** [comment]
QT win32 = the Windows binary you're using with the QT UI.

**Comment by Computerboi13** [comment]
Wait with QT you mean the renderer right?, because i think i found it.

**Comment by TC1995** [comment]
Yes, and try the nightly builds (based on 4.0).

**Comment by Computerboi13** [comment]
Im using the nightly build rn, also im using the "Qt (Software)" one.

**Comment by Computerboi13** [comment]
I dont really think the ESDI and the SCSI Controllers are conficting, there isn't an asterisk in the upper right corner.
![Configuration](https://github.com/86Box/86Box/assets/127628245/be1fa85e-74a5-40bf-849a-01990e10ceb0)

**Comment by TC1995** [comment]
They use the same irqs, so use one but not both.

**Comment by Computerboi13** [comment]
I gave it another irq, but the error still appears.

**Comment by TC1995** [comment]
No, their irq's are hardcoded to 14, either use the ESDI or SCSI.

**Comment by Computerboi13** [comment]
If i don't use the SCSI i will be stuck in the part where i need to use the CD.

**Comment by TC1995** [comment]
Use SCSI then, but remember that you need to have set the HDD to SCSI as well, and on ID 6.

**Comment by Computerboi13** [comment]
I can't give it a different ID, it doesn't let me do it.

**Comment by Computerboi13** [comment]
I managed to end the installation, but i mistyped my password so im stuck xD.

**Comment by Computerboi13** [comment]
I tried reinstalling it because for some reason there was another 5 drives from D: to H: and because i mistyped my password, in the part where it copies files to the C: drive in the graphical part of the setup, the setup its frozen. The only thing i can do is move the cursor.
![Setup Frozen](https://github.com/86Box/86Box/assets/127628245/8e89b26e-3a1f-44cf-af62-4f7c5abb7d68)

**Comment by TC1995** [comment]
where's the CD located at? ID 2 or?

**Comment by Computerboi13** [comment]
CD is ID 7, hard disk is ID 6
their device addresses are 0,0 and 1,0

**Comment by TC1995** [comment]
CD should be on ID 2 on both ends as well as the HDD on ID 6.
Basically, ID 6 on both the machine bios and 86box settings, same goes to CD's id.

**Comment by Computerboi13** [comment]
Did you meant the adapter address ID?, because as far i know it can only be changed in the bios.
Btw i changed the device address to the ones you said and is still frozen.

**Comment by TC1995** [comment]
The adapter address ID should be always be 7 unless specified elsewhere.

**Comment by Computerboi13** [comment]
Its normal i get another 5 drives from D to H, because when i installed it with SCSI i got them and i was able to complete the installation.

**Comment by Computerboi13** [comment]
Now i only get only C and it freezes

**Comment by TC1995** [comment]
Are you using the 4.0 builds?

**Comment by Computerboi13** [comment]
Yes

**Comment by TC1995** [comment]
MCA settings tend to be painful sometimes.

**Comment by Computerboi13** [comment]
I haven't got those additional drives since, even creating another hard disk.

**Comment by Computerboi13** [comment]
I have formatted it as NTFS all this time, should i try FAT?

**Comment by TC1995** [comment]
try so.

**Comment by Computerboi13** [comment]
Its copying the files!

**Comment by Computerboi13** [comment]
So this means NTFS is broken.

**Comment by Computerboi13** [comment]
I have noticed some things, when i install it, the machine somehow forgets my password adn when i try to reinstall it i get stuck on the same part, even using the FAT formatting.

**Comment by OBattler** [comment]
I guess this can be closed since it was an (emulated) hardware conflict.
