### ISSUE TITLE
Missing vJoy joystick axes in Joystick Configuration

### ISSUE THREAD

**Issue by NoelShourai** [86Box/86Box#3436]
**Describe the bug**
Cannot bind the regular joystick axes of a vJoy device to the emulator joystick, they do not appear to be detected. Only the buttons and POV axes are visible.

**To Reproduce**
1. Install latest version of vJoy (2.1.9?) in the host system
2. Under _Hardware Settings_, go to _Input devices_ and select any joystick type
3. Select _Joystick 1_ or _Joystick 2_ and select _vJoy - Virtual Joystick_ as the Device
4. Attempt to bind controls to the X, Y, Z or zX axes, or Throttle on a CH Flightstick Pro

**Expected behavior**
vJoy axes should also be visible, not just the POV axes.

**Screenshots**
![image](https://github.com/86Box/86Box/assets/19917103/f187f37f-4af1-4719-a531-008215c88563)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v4.0.0.4674
 - Build information: New Dynamic Recompiler, 64-bit

**Additional context**
vJoy axes are visible and usable in other software, i.e. they will show up correctly in PCem, Joystick Gremlin, etc.. XInput controller also appears to be working correctly.

As a side issue, I have a WINWING ORION HOTAS (joystick and throttle are separate controllers) and MFG Crosswind V2 pedals. They are not picked up by 86Box at all, so I cannot use any of them.

**Comment by richardg867** [comment]
Fixed by fb6851a86564ac8ebbf9db92d42dac91c0d3698c
