### ISSUE TITLE
Going to full screen does not work when Force 4:3 is on

### ISSUE THREAD

**Issue by OBattler** [86Box/86Box#3445]
**Describe the bug**
If you have Force 4:3 on and set to a certain window size and resize turned off, the shortcut for going to fullscreen doesn't work but you can force it by using the menu option once in fullscreen you can't exit with anything except ALT-TABbing out and killing it externally.

Originally reported by Efflixi on the Discord server.

**To Reproduce**
1. Enable Force 4:3
2. Set a window to a certain size
3. Try going to full-screen
4. It does not enter full-screen, or leave if forced to enter through the menu

**Expected behavior**
It should enter and leave full-screen normally.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - 86Box version: v4.0 build 4673
 - Build information: Build with QT, 32-bit old dynarec

**Additional context**
N/A.

**Comment by richardg867** [comment]
Reported fixed by Qt fullscreen hotkey fixes.
