### ISSUE TITLE
[BUG] ATI video card VESA video mode (higher than 640x480) not detected

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#345]
Hello

I recently tested the ATI video cards. The problem is that even with 1MB of vram, graphics modes higher than 640x480 are not supported.

I know an 800x600 driver for win 3.0 exist, but until now I only tested the card in DOS mode with the Vesatest utility and the VESA driver for ATI (vvesa.exe).

![20181111_214241](https://user-images.githubusercontent.com/31600563/48320741-c6395c00-e5fb-11e8-97c1-a74ae05c79e2.png)

BTW:  

1 I know a bug existed in Pcem in 2015, but I don't know if it's the same bug. [https://pcem-emulator.co.uk/phpBB3/viewtopic.php?f=2&t=304&p=1871&hilit=ati+800x600#p1871](url)

2 It seem to be a  bug with ATI cards because I tested Vesatest with Tseng ET4000 and the Tlivesa dos driver and worked correctly

**Comment by TC1995** [comment]
This seems to be a bios limitation, we are looking for a more capable 28800-5/6 bios.

**Comment by OBattler** [comment]
Since this is a BIOS limitation, it's not a bug and the issue is being closed.
