### ISSUE TITLE
Keyboard is broken on the Socket 3 Samsung SPC7700P-LW Machine

### ISSUE THREAD

**Issue by pankoza2-pl** [86Box/86Box#3453]
**Describe the bug**
the keyboard keys on the Samsung SPC7700P-LW 486 Machine are completely messed up after booting DOS
The bug does not appear in the BIOS Setup

**To Reproduce**
1. Try to run a machine using the 486 Socket 3 [UMC 8881] Samsung SPC7700P-LW Machine
2. Boot MS-DOS 6.22 on it
3. Try to use the keyboard
4. The keys are completely mismatched

**Expected behavior**
The keyboard works correctly

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - 86Box version: v4.0 build 4694
 - Build information: new dynarec, i386 (happens also with dynarec off)

**Additional context**
Here is the Config, NVR and the HDD Image
[Windows 3.1 Samsung OEM.zip](https://github.com/86Box/86Box/files/11989497/Windows.3.1.Samsung.OEM.zip)

**Comment by UnbojihSkid** [comment]
power supply doesnt even work
