### ISSUE TITLE
86Box is crashing on startup

### ISSUE THREAD

**Issue by ksio89** [86Box/86Box#3454]
**Describe the bug**
Identical issue to #3364: 86Box is crashing on startup, usually after POST screen, no matter the hardware or operating system being emulated and 86Box build, either stable or experimental or old/new dynamic recompiler.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single Language Version 22H2
 - 86Box version: v4.0.0 build 4694
 - Build information: both new and old dynarec, x86, 64-bit

**Additional context**
I set up logging in one virtual machine running OS/2 Warp 4.52, and after crashing this error message is generated:

`[1200:00006315] Illegal instruction 000090CA (A6)`

Here's 86box.cfg of this machine:

[86box.txt](https://github.com/86Box/86Box/files/12017618/86box.txt)

**Comment by OBattler** [comment]
I can't reproduce this at all. Make sure you have exempted 86Box from memory exeution protection in Windows.

**Comment by ksio89** [comment]
> I can't reproduce this at all. Make sure you have exempted 86Box from memory exeution protection in Windows.

And where do I check that?
