### ISSUE TITLE
The Hercules specific HBASIC doesn't work.

### ISSUE THREAD

**Issue by coolhaken** [86Box/86Box#346]
Hi,

I tried HBASIC (a very old basic interpreter) under 86Box but it doesn't work,
I got a blank screen only. It is for Hercules only and works fine with PCE.
Maybe there is an issue of Hercules emulation in 86Box.
Download it here : https://drive.google.com/file/d/1F2b3h4Opre0KJTetUIz-fQACZhxJjjeT

**Comment by waltje** [comment]
Seems to work OK here.  86Box uses our Hercules driver I believe, so unclear why it does not work on 86Box... but probably a little typo somewhere: easy to fix.

Were these versions of BASIC sent out by IBM after the Hercules came out?  One of these seems to be running in graphics mode, that is kinda neat...

--waltje
![herc-2](https://user-images.githubusercontent.com/28492024/48668647-d4d2b800-eac0-11e8-8605-b2250877cccc.png)
![herc-3](https://user-images.githubusercontent.com/28492024/48668648-d56b4e80-eac0-11e8-810c-d5ab1ca6bbd7.png)
![herc-1](https://user-images.githubusercontent.com/28492024/48668649-d56b4e80-eac0-11e8-91b6-af14ae0be986.png)

**Comment by OBattler** [comment]
@coolhaken Make sure you're using the latest build of 86Box. If you're still using the build from around when I fixed the Cirrus bug you reported before, then that was I think before I replaced the Hercules emulation with that from Varcem. I just tested both BASICH and HBASIC on the latest build of 86Box and they work fine.

**Comment by OBattler** [comment]
Just for the reference, the fix committed by waltje to VARCem this morning for this, was actually found by me. I have similar sixes for a number of other graphics cards in store, they will be committed in the next 86Box commit.
