### ISSUE TITLE
No joystick input but the joystick is detected (4-axis, 4-button joystick)

### ISSUE THREAD

**Issue by NoelShourai** [86Box/86Box#3460]
**Describe the bug**
The virtual machine OS does not receive joystick input, even if the joystick is detected properly. The controller is detected both by 86Box and by the virtual machine, but does not respond to input.

**To Reproduce**
1. Connect a controller that is detected by 86Box.
2. Set the joystick to a 4-axis, 4-button joystick in 86Box's hardware settings and map the host game controller to that joystick.
3. Under 86Box's OS, go to Control Panel / Game Controllers and add the corresponding joystick to the list.
4. Select the new joystick. Verify that the connection is OK, then click Properties.
5. Test joystick input.

**Expected behavior**
Joystick input should resemble the host OS' controller input.

**Screenshots**
![image](https://github.com/86Box/86Box/assets/19917103/c3cf35ec-f2ee-4be4-a2c1-7340df70752b)
![image](https://github.com/86Box/86Box/assets/19917103/5542b60a-ec11-40bb-b106-70b7b3faa0bb)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Build 19045
 - 86Box version: v.4.0.0.4704
 - Build information: Old Dynamic Recompiler, 32-bit

**Additional context**
- Tested on a Windows 98SE virtual machine.
- An Xbox One controller was used in the above screenshots, but it appears to be a general joystick input problem as this issue was encountered with multiple other controllers i.e. VJoy, emulated 360 controller via x360ce or DS4Windows, etc.
- Edit: I thought this was an issue that applied to all joystick types, my mistake. The other joystick types work fine, just the 4-axis, 4-button one specifically has this issue.
- Edit 2: Based on the above, the workaround I discovered was to configure two 2-axis 2-button joysticks in 86box bound to the same host controller, then installing a 4-axis 4-button joystick in Windows. This probably works for Windows 95/98 specifically, but may not be as cooperative with DOS specific games that support a 4-axis controller or non-Windows OSes.

**Comment by richardg867** [comment]
Fixed by 8585e04be5cc06b2f96f5ffdaa55f0e693eb9157
