### ISSUE TITLE
[Ask] implement of fuction keys for the Toshiba T1000/T1200/T3100

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#348]
Hello.

The Toshiba machines lacks of the fuctions keys it has in PCem. 

Taken from Readme.txt of PCem

"PCem maps [Fn] to right-Ctrl and right-Alt. The following functions are supported :
        Fn + Num Lock  - toggle numpad
	Fn + Home      - Internal LCD display
	Fn + Page Down - Turbo on
	Fn + Right     - Toggle LCD font
	Fn + End       - External CRT display
	Fn + SysRQ     - Toggle window"

Thanks in advance!

**Comment by OBattler** [comment]
I"ll look into that.

**Comment by Fenix770** [comment]
I don't know. In Pcem the function key was the right control key. Although I don't know which key is SysRQ in Pcem either.

**Comment by OBattler** [comment]
Yeah, this is implemented, works with both right Alt and right Ctrl. As such, I'm closing this issue.
