### ISSUE TITLE
86Box randomly crashes

### ISSUE THREAD

**Issue by AshUosis** [86Box/86Box#3480]
**Describe the bug**
After I installed Windows 95 on 86Box, it started crashing when I went into fullscreen mode.

**To Reproduce**
1. Enter fullscreen mode.
2. Do something resource demanding.
3. See crash.

**Expected behavior**
86Box shouldn't crash.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - 86Box version: v4.0 build 4704
 - Build information: x86_64, old dynarec

**Comment by OBattler** [comment]
What exactly do you mean by something resource demanding?

**Comment by Tuxrug** [comment]
I'm not sure my issue is related as I'm on 3.11 build 4311 and I don't know if this is tied to anything "resource demanding" in my case, and I'm seeing it in Windowed mode. But since it's occuring in Win95 while the OS is already running, maybe it is? 

https://github.com/86Box/86Box/issues/3481

**Comment by AshUosis** [comment]
> What exactly do you mean by something resource demanding?

Sometimes when I played a sound, sometimes when I chose a theme, and so on

**Comment by AshUosis** [comment]
> I'm not sure my issue is related as I'm on 3.11 build 4311 and I don't know if this is tied to anything "resource demanding" in my case, and I'm seeing it in Windowed mode. But since it's occuring in Win95 while the OS is already running, maybe it is?
> 
> #3481

Other than the fact that it doesn't happen in windowed mode, everything is spot on

**Comment by AshUosis** [comment]
And also, it happens way more on a socket 8 cpu than a socket 7 cpu, and doesn't happen on the 32-bit 86box version

**Comment by OBattler** [comment]
This should now be fixed, it turns out that the old recompiler in both its 32-bit and 64-bit versions, sometimes accidentally accesses a few bytes beyond the edge of the emulated RAM because it does not split accesses. Since I cannot make it do split accesses without negatively affected performance, I have decided to always allocate 16 extra bytes of RAM precisely to mitigate this.

**Comment by AshUosis** [comment]
> * AshUosis: What emulated graphics card are you using?

I think I used the S3 ViRGE.

**Comment by AshUosis** [comment]
> This should now be fixed, it turns out that the old recompiler in both its 32-bit and 64-bit versions, sometimes accidentally accesses a few bytes beyond the edge of the emulated RAM because it does not split accesses. Since I cannot make it do split accesses without negatively affected performance, I have decided to always allocate 16 extra bytes of RAM precisely to mitigate this.

Yeah, maybe the problem was the recompiler, as before I used the old recompiler, but for the 32-bit I used the new one.
