### ISSUE TITLE
Random abrupt close/crash in Windows 95

### ISSUE THREAD

**Issue by Tuxrug** [86Box/86Box#3481]
**Describe the bug**
86Box crashes and closes without an error message seemingly randomly, however I have noticed it happens very often when installing Internet Explorer 5.5 in Windows 95. It crashes at different points of setup, such as when loading the installer, when the installer connects to the internet, or during the installation or configuration phases. This happens with Windows 95 RTM, OSR2, and a Packard Bell OEM restore disk version. 

Crashes are not exclusive to the Internet Explorer 5.5 installation process; it has happened during Windows installation or opening the D: CD drive in Windows Explorer, however trying to install IE5.5 is very consistent.

This happens both with and without a separate frontend. At first it seemed more frequently in other actions such as installing Windows when the hard drive was set to RAM Disk, but I am not 100% sure as it does happen reliably with the steps below at slower HDD speeds. 

**To Reproduce**
1. Download an Internet Explorer 5.5 installer (I used http://www.download.windowsupdate.com/msdownload/update/v3/static/ie55/x86/en/ie5setup.exe)
2. Mount the folder containing the installer as a CD drive or mount an ISO containing the installer.
3. Run the installer (this occurs whether the installer is run directly from the CD or copied to the hard drive first)
4. Proceed with setup.

**Expected behavior**
If the error is due to a known real quirk of the emulated hardware, emulate what would happen with the error in real life (device behaves in way OS does not expect). Otherwise, emulation should continue. If the error is due to a bug in 86box where 86box itself cannot continue, show an error message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 (22621.1992)
 - 86Box version: 3.11 build 4311
 - Build information: x64

**Additional context**
86box.cfg is attached as TXT due to file formats allowed. Although I currently have OpenGL with a shader set and fluidsynth, I have also seen this behavior with using System MIDI output and different renderers (Qt - software, Qt - openGL, Vulkan)
I am not sure if this happens yet with other motherboards, etc, as I'm currently trying to emulate the Packard Bell Legend 2440 as closely as I can.

[86box.txt](https://github.com/86Box/86Box/files/12115452/86box.txt)

**Comment by Tuxrug** [comment]
I tried using 4.0 build 4717 (Same OS, x86_64, old dynarec) and it still occurrs. I then noticed I had a similar video card to the built-in one on the motherboard and remembered reading somewhere that people have trouble with add-on graphics on some real Pentium-era Packard Bell hardware so I changed the add-on video to Integrated, same issue. 

It does look like it has been solved with 4.0 build 4718 (Same OS, x86_64, new dynarec), as I was able to fully install IE5.5 without any errors on the first attempt with it.

**Comment by OBattler** [comment]
So it wasn't 4718 that solved it but the switch to new dynarec. So there's a bug with the old dynarec. This makes more sense since all 4718 changed was the ES1371 emulation and that card is not present in your configuration file.

**Comment by OBattler** [comment]
This should now be fixed, it turns out that the old recompiler in both its 32-bit and 64-bit versions, sometimes accidentally accesses a few bytes beyond the edge of the emulated RAM because it does not split accesses. Since I cannot make it do split accesses without negatively affected performance, I have decided to always allocate 16 extra bytes of RAM precisely to mitigate this.
