### ISSUE TITLE
Can we add Pentium 3/4 and 775 Socket CPU?

### ISSUE THREAD

**Issue by NgoccVN5400** [86Box/86Box#3482]
Since AMD K6, Intel Celeron can boot into Windows 7, what if you put the CPU socket Pentium 3/4 and 775? Supporting more operating systems, users can install more operating systems Windows 7 (Windows 8.10, Ubuntu 20.04) and more browsers, all new browsers are required SSE2 to use

I wish and wait for a day when we can put the Pentium 3/4 and 775 Socket CPUs in the 86Box :D

**Comment by OBattler** [comment]
We have already explained why that's not going to happen.

**Comment by NgoccVN5400** [comment]
"That's totally beyond the capabilities of current hardware." cre:dhrdlicka
This?

**Comment by daviunic** [comment]
This: https://86box.net/2022/03/21/why-not-p3.html
