### ISSUE TITLE
Each time you start the machine immediately in full screen mode, the window coordinates are reduced by 2

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#3485]
**Describe the bug**
Each time you start the machine immediately in full screen mode (86Box.exe -f), the window coordinates decrease by 2. For example, initially in the 86Box.cfg file there is a line: window_coordinates = 412, 31, 1736, 1292. After starting the machine immediately in full screen mode, the window coordinates decrease by 2: window_coordinates = 412, 31, 1736, 1290. That is, the number 1292 became 1290, the next time the machine is started immediately in full screen mode 1288, the next time the machine is started immediately in full screen mode 1286, the next time the machine is started immediately in full screen mode 1284, etc. That is, the window coordinates are not saved when the machine is started immediately in full screen mode, and each time the machine is started immediately in full screen mode, they are reduced by 2. This bug appeared in build 4202 and persists until the last build. In build 4201 everything works fine.

**Expected behavior**
Each time you start the machine immediately in full screen mode, the coordinates of the window should be saved.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v22H2
 - 86Box v4.0.0 x86 Build 4737
 - Build type: qt, regular, old recompiler

**Additional context**
Attached configuration file:
[86Box.zip](https://github.com/86Box/86Box/files/12138230/86Box.zip)

**Comment by OBattler** [comment]
There is no way this bug appeared in 4202 since neither of the two commits in that build changed anythingthat could have caused this.

**Comment by maximus105** [comment]
Issue not fixed. Use the attached settings file 86Box.cfg.
1. Start the machine immediately in full screen mode (86Box.exe -f).
2. Completely close 86Box.exe.
3. Open the 86Box.cfg file. In the line: window_coordinates, the number 1292 became 1290.
4. The next time you start the machine immediately in full screen mode, the number will become 1288.
Checked again: This bug appeared in build 4202 and persists until the latest build. In build 4201 everything works fine.

**Comment by maximus105** [comment]
I managed to fix this bug. It is necessary to undo the changes in the src/qt/qt_mainwindow.cpp file in commit 65f6f45 from build 4202.
