### ISSUE TITLE
[bug] c: drive failure

### ISSUE THREAD

**Issue by drfrag666** [86Box/86Box#349]
Machine: unknown ami 386sx. I created a 504 mb hdd (i picked that type from the list) and it's detected in bios setup but then hangs at the wait message for a while and gives that c: drive failure error.
 Choosing in other peripherals internal controller or none as hdd controller makes no difference.
 It's build 1830.

 That image works with PCem but while creating it first i selected the proposed location at Documents and then when i selected a different folder i got an error saying that the file could not be opened for writing and an empty file was created at the original location so i had to close the dialog (this is an unrelated bug).
 BTW i expected to find more machines but there are actually less, where's the mr bios 386dx?

**Comment by drfrag666** [comment]
And i cannot edit the previous post, it's build 1830.

**Comment by OBattler** [comment]
Try hard resetting the machine - I noticed that pretty much every machine on 86Box gives a HDD controller failure error after soft reset, no idea why, but I'm going to look into it.

>> where's the mr bios 386dx?

I need to update the ROM set. Rename the ami386dx folder to ami495 and the mr386dx folder to mr495, then it should see those machines.

**Comment by ppgrainbow** [comment]
Sounds to me that this might be a bug in build 1830 of 86Box as there has been no new commits in 86box since November 9.

Now, using the latest 86box binary (build timestamp: 2018-11-19 14:00:06), I've created two type 4 hard disks (940 cylinders, 8 heads and 17 sectors per track ~ 62 MB) and it's working. I've tested this on the emulated unknown motherboard with the AMI BIOS and a 386SX processor as well as the OPTI495SX chipset-based 386SX emulated machine and it can detect both type 4 hard drives. :)

For now, until the bug gets fixes in the next committed, I recommend that you use SCSI controllers such as the Adaptec AHA-1540B or AHA-1542C adapter. :)

**Comment by drfrag666** [comment]
Thanks, it was not the controller failure error but another drive failure one after the hard reset.
I've also tried with that 62 mb drive and i get the same error with 1830.

 True the ami 386dx is missing as well.
 Also i've noticed that some machines crash the emulator inmediatly, such as the DTK and KMX 386sx ones.

**Comment by drfrag666** [comment]
Thanks, it was not the controller failure error but another drive failure one after the hard reset.
I've also tried with that 62 mb drive and i get the same error with 1830.

 True the ami 386dx is missing as well.
 Also i've noticed that some machines crash the emulator inmediatly, such as the DTK and KMX 386sx ones.

**Comment by OBattler** [comment]
I don't exclude bugs in IDE emulation. I need to look into it.

**Comment by drfrag666** [comment]
After renaming the rom folders a new machine has appeared: ami 386sx clone (opti-495sx) and that one works well. It's the unknown ami 386sx the one with the bad hard disk.

**Comment by OBattler** [comment]
I'm tempted to remove that BIOS altogether, as noone even knows what chipset it's for, so it's useless to have it in.

**Comment by ppgrainbow** [comment]
Using the latest 86Box binary built on Sunday, November 25, 2018 at 1:02:21 PM, the hard disk is detected on the AMI386SX with the unknown chipset.

Running MS-DOS 4.01 and by using NSSI, the utility obviously identities the chipset as a "386SX" by default when it is unknown chipset:
![20181201_122702](https://user-images.githubusercontent.com/32658796/49332639-97ad0200-f565-11e8-9d4b-ad6774c257c2.png)

Even if the AMI386SX machine with the unknown chipset is dev-brached, it's obviously useless to use it altogether.
