### ISSUE TITLE
Win98/2000 startup/shutdown sound weird/buggy when Win98/2000 is startup/shutdown/logoff.

### ISSUE THREAD

**Issue by kzmidze** [86Box/86Box#3491]
**Describe the bug**
Install Win98/2000 in 86Box.
Win98/2000 startup/shutdown sound weird/buggy when Win98/2000 is startup/shutdown/logoff.
After login Win98/2000, try play WAV/MP3 has no this issue.
After login Win98/2000, try play WAV/MP3 the CPU Usage is not high.
Try turn off hardware acceleration for sound card in Win98/2000, has no effect.
I think it's bug of 86Box sound card.

**Screenshots**
Win98
![1](https://github.com/86Box/86Box/assets/117635969/abcecc67-7b13-4162-bbb8-9f7ad6ad1c82)

![2](https://github.com/86Box/86Box/assets/117635969/047f9c0a-f655-473c-a169-a63ed6f905fe)

[86box.cfg.zip](https://github.com/86Box/86Box/files/12172256/86box.cfg.zip)
Win2000
![1](https://github.com/86Box/86Box/assets/117635969/67aa620b-39b1-4b2b-8951-470746e9cc56)

[86box.cfg.zip](https://github.com/86Box/86Box/files/12172652/86box.cfg.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v4.0 build 4739

**Comment by jriwanek** [comment]
What's your host system?

**Comment by OBattler** [comment]
VirtualBox does not emulate the CPU. 86Box does and you have selected literally the fastest possible emulated CPU, which I seriously doubt your host machine is able to emulate at 100%. So, NOTABUG - change the emulated CPU to something slower.
