### ISSUE TITLE
ACPI issue with Gigabyte GA-5AX

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3497]
**Describe the bug**
When you shutdown Windows 9x, with the Super Socket 7 Gigabyte GA-5AX motherboard, the system will hang in the shutdown screen.

**To Reproduce**
1. Install a Windows 9x-based system on the Super Socket 7 Gigabyte GA-5AX motherboard.
2. Shut down the system.

**Expected behavior**
The system performs the ACPI shutdown.

**Screenshots**
_No screenshots_

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Preview (Build 25905: Canary Channel)
 - 86Box version: 3.11 (build 4311)
 - Build information: `10.0.25905.1000.amd64fre.rs_prerelease.230707-1739`

**Additional context**
_No additional context_

**Comment by OBattler** [comment]
This was fixed in build 4461. Update to the latest Jenkins build.
