### ISSUE TITLE
amstrad megapc has a bios pasword

### ISSUE THREAD

**Issue by FINK89i** [86Box/86Box#3499]
hello i was trying 86box because pcem has some problems so isetted up a i386SX amstrad megapc whit a i386SX st 33mh for tryng to install like windows 3.11 so i boot it end i went to the bios/cmos settings but afther i push F2 it say to me security check enter pasword end idk what to enter like can some one help me?

**Comment by OBattler** [comment]
Known bug. Until it's fixed, please open the megapc.nvr file and set it to all 0x00's.

Also, closing because we already have an open issue due to this machine needing rewrite in its entirety.
