### ISSUE TITLE
Compaq Deskpro 386 (1986-09) - no HDD

### ISSUE THREAD

**Issue by mfmcosta** [86Box/86Box#3502]
**Describe the bug**
There's no HDD support for this model.
In the sources, no hdd device was attached as in the 1988-01 model
![image](https://github.com/86Box/86Box/assets/136728257/90cc98a9-4b12-4159-bf92-2af8f0f3e199)

**To Reproduce**
1. Create a machine and set any type of HDD: Internal Controller or ESDI (WD1007V) or IDE
2. Do not use Compaq EGA since it loops (between those values) after starting reading the floppy 
![image](https://github.com/86Box/86Box/assets/136728257/dd70268c-9d05-41af-94dd-5c6d862c1f0f)
3. Create or use an existing HDD
4. Start the machine
5. Try to use FDISK

**Expected behavior**
FDISK create a partition to format.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 4.00 build 4748
 - Build information: x86 (old recompiler)

**Comment by pankoza2-pl** [comment]
you need to configure the HDD with a setup floppy first

**Comment by mfmcosta** [comment]
? how do you do that when DISKINIT says it will install on a floppy?
I grab the floppies from winworldpc & pcjs.org - all of them says the same

**Comment by TC1995** [comment]
You need the relevant reference disk for said Compaq machine.
