### ISSUE TITLE
Add Packard Bell Legend 300sx (port it from PCem)

### ISSUE THREAD

**Issue by pankoza2-pl** [86Box/86Box#3503]
**Is your feature request related to a problem? Please describe.**
No, I just want the Packard Bell 300sx added

**Describe the solution you'd like**
Add the Packard Bell Legend 300sx 386sx machine, because PCem has that and 86Box doesn't, I think it should be easy to port it to 86Box

**Additional context**
BIOS ROM for Packard Bell Legend 300sx: https://github.com/BaRRaKudaRain/PCem-ROMs/tree/master/pb_l300sx

**Comment by OBattler** [comment]
Already requested here: https://github.com/86Box/86Box/issues/505 , so duplicate.

Also, PCem's emulation is incomplete - they do not emulate the UMC UM82C862F Super I/O chip.
