### ISSUE TITLE
Add 1MB VRAM for Video 7 VGA (1024i)

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3506]
**Is your feature request related to a problem? Please describe.**
No. I want to use 1MB of video memory (VRAM) with Video 7 VGA 1024i.

**Describe the solution you'd like**
You can only use 256KB or 512KB of VRAM with Video 7 VGA 1024i. I want to be able to use 1MB of VRAM with Video 7 VGA.

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**Comment by TC1995** [comment]
That card can only use up to 512KB, not 1MB.

**Comment by cigaryno** [comment]
I will close it.
