### ISSUE TITLE
[BUG/WORKAROUND] Windows NT recognises newly created Iomega ZIP disk images as RAW file system type.

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#351]
I just found out about this when I'm using a emulated Iomega ZIP drive under Windows NT.

I have the Iomega ZIP drive attached to SCSI Port 6 on the Datatech OPTI-495SX-based 486 machine with the AMIBIOS (AMI486) and I found that when I create a new 100 MB Iomega ZIP disk image by selecting New Image when clicking on the ZIP drive icon, DOS and OS/2 immediately recognises the Iomega ZIP drive when inserted as a FAT16 filesystem.

That's not the case when running an operating system such as Windows NT 3.51. When I create a new Iomega ZIP disk image (using the New Image creation tool) and when I check the disk drive for any errors, this error message occurs:

> The type of the file system is RAW.
> CHKDSK is not available for RAW drives.

Here's a screenshot for proof:
![20181205_003101](https://user-images.githubusercontent.com/32658796/49500809-631b9d80-f826-11e8-80cf-db8b469cc323.png)

To workaround this issue, you have to format the Iomega ZIP drive as the FAT file system by typing this command:

`FORMAT x: /FS:FAT`

For example _x:_ would be drive K: set in my emulated machine on SCSI Port 6.

I hope that there is some sort of a solution to find a way how to fix this issue that causes Windows NT to misidentify the file system for Iomega ZIP drives as RAW when using CHKDSK.

**Comment by daviunic** [comment]
Windows doesn't recognize the file system in this case, which could be due to the FAT16 parameters that 86Box uses when creating the image. Would be interesting to observe the FAT16 partition created by NT 3.51. See if it's in any way different from the one 86Box creates.

**Comment by ppgrainbow** [comment]
I agree. 86Box already observes the FAT16 partition upon creating floppy diskette images.

It would be definitely nice to see 86Box observe the FAT16 partition for Iomega 100 MB and 250 MB ZIP disk images as well! :D

**Comment by ppgrainbow** [comment]
Okay. I formatted the 100 MB ZIP disk image using the format x: /FS:FAT command and this is the output that I received:

```
100235264 bytes total disk space
100235264 bytes available on disk

     2048 bytes in each allocation unit
    48943 allocation units available on disk
```

Under MS-DOS (and OS/2) when the Iomega ZIP disk image gets created this is the output that I received when using CHKDSK:

```
100431872 bytes total disk space
100431872 bytes available on disk

     2048 bytes in each allocation unit
    49039 total allocation units on disk
    49039 available allocation units on disk
```

So, in this case as opposed to DOS and OS/2 after formatting a ZIP disk image, Windows NT 3.51 reports that there is 192 KB less disk space available for a 100 MB ZIP drive which is the correct size for a FAT formatted ZIP disk image.


As for 250 MB ZIP drives, this is what CHKDSK reports under MS-DOS, Windows NT and OS/2:

```
250331136 bytes total disk space
250331136 bytes available on disk

     4096 bytes in each allocation unit
    61116 total allocation units on disk
    61116 available allocation units on disk
```

Hmm...it seems that a 250 MB ZIP disk image gets formatted and recognised right out of box under these OSes, but that's not the case for the 100 MB ZIP disk image where Windows NT reports the file system as RAW if there are 49,039 clusters when the 100 MBZIP disk is created. After formatting the 100 MB ZIP disk, the number of clusters gets reduces to 48,943.

So, something appears to be wrong with the size of the 100 MB ZIP disk image. :|

**Comment by ppgrainbow** [comment]
Okay, I got the two 100 MB ZIP disk images that waltje provided. I'm only able to test the second ZIP drive. 

Here is the Windows NT CHKDSK output of the ZIP100 disk:
![20181207_134535](https://user-images.githubusercontent.com/32658796/49674663-9ed18580-fa27-11e8-8eb9-f944413596e0.png)

When a 100 MB ZIP disk is created, it's suppose to report 49,038 clusters, **NOT** 49,039. When a 100 MB disk images gets created using the New Image tool (when you click on the ZIP drive on), the drive reports having 49,039 clusters. As such, Windows NT ends up reporting the ZIP disk as RAW even though the two other OSes, DOS and OS/2 work fine.

As far as I know, the image that Claunia sent to OBat obviously had one cluster too many for Windows NT to handle! Let's hope that this bug gets fixed.

**Comment by OBattler** [comment]
This is now fixed, so I am closing this issue.
