### ISSUE TITLE
Wetlands and Soldier boyz tearing issues

### ISSUE THREAD

**Issue by juan200213** [86Box/86Box#3515]
**Describe the bug**
the video games Wetlands and Soldier Boyz have some tearing issues.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: 4.0 
 - Build information: old dynarect, x64, build 4721

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by OBattler** [comment]
Closing the issue for not having filled the mandatory form at all basically.
