### ISSUE TITLE
ATI VGA Charger vram not detected

### ISSUE THREAD

**Issue by Carmina16** [86Box/86Box#3517]
**Describe the bug**
If an ATI VGA Charger is configured with 1MB of VRAM, only 512 k is detected (and 1MB modes are missing)

**To Reproduce**
1. Add `ATI 28800-5` videocard and set its RAM to 1MB
2. Run `VINSTALL` to configure the card
3. Run the test; note that 1024x768x16 is the max available mode.

**Expected behavior**
1024x768x256 mode is available in the driver.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 4754
 - Build information: 32bit old dynarec

**Additional context**
Does that card even support 1MB configuration?

**Comment by TC1995** [comment]
It does support 1MB, but not 256 color mode in 1024x768.

**Comment by pankoza2-pl** [comment]
So similar to the Video 7 VGA 1024i which supports 512KB, but not 256 color mode in 800x600.

**Comment by Fenix770** [comment]
I could not get any resolution above 640x480 on any ATI Wonder card on Windows 3.0, even when I select the Multisync monitor option on the ATI DOS setup utility. However, the 640x480 15-bit high color mode works fine on the ATI XL on Win.30

**Comment by TC1995** [comment]
If anyone has a 1024x768x256 VGA Wonder BIOS sans Mach32's VGA Wonder compatible mode it would be greatly appreciated.

**Comment by OBattler** [comment]
I guess I can close this then as NOTABUG.
