### ISSUE TITLE
Windows 98 SE Joystick connected to game port.

### ISSUE THREAD

**Issue by GLwd40** [86Box/86Box#3519]
**Describe the bug**
After installing Windows 98 SE, checking in the device manager, next to the item "Joystick connected to game port" there is an exclamation. There is no possibility to install or update drivers, because the message says "no free resources".

The interesting thing is that when I install the NE2000 network card I immediately have a resource conflict with the COM port and I can't set another free interrupt.

I did so that in the configuration I turned off all COM and LPT ports, but it did not solve the problem.

**To Reproduce**
1. Install Win98 SE 
2. Go to device manager.

  - OS: Windows 11
 - 86Box version: 4.0.0.4758

VM:
Shuttle HOT-557
Pentium 150
16MB
S3 Virge 325
SB16 PnP
Novell NE2000

![Monitor_1_20230805-200506-164](https://github.com/86Box/86Box/assets/118068422/ddcc25e4-f14e-48c2-bccb-70cf1fab0eac)
![Monitor_1_20230805-200518-475](https://github.com/86Box/86Box/assets/118068422/c364b256-61e6-4f8a-83cf-b21c421aba61)

**Comment by OBattler** [comment]
Change the Network driver to NE2000-compatible instead of Novel NE2000, then change the IRQ to IRQ 10. Also make sure it's set to that in 86Box settings as well.

**Comment by OBattler** [comment]
As for the second gameport joystick with the yellow ! - go to CMOS Setup, disable it there, then remove it from Windows.

**Comment by OBattler** [comment]
Closing because NOTABUG.
