### ISSUE TITLE
Cirrus CL-GD5429: graphics corruption in DOS after loading windows 95

### ISSUE THREAD

**Issue by drfrag666** [86Box/86Box#352]
Latest Jenkins devbuild 1830, same in last pcem. MR 386DX machine, but happens on all of them.
With PCem in win95 wrong colors with the included driver and much worse in 16 bits.
 On both emulators (256 color mode) launching a fullscreen dos box or restarting in ms-dos mode you get wrong characters in text mode and no Doom startup banner. Doom 2 doesn't work, you get vertical lines with graphics junk.

**Comment by TC1995** [comment]
well, for a quick comparison, try it with a newer machine, if the same happens, I'll check.

**Comment by drfrag666** [comment]
Really? You mean that card should not work on that machine? Why?
 I also tried on the ali1429.

**Comment by TC1995** [comment]
No, I don't mean that, what I mean is that try it on another machine like a 486 or a Pentium-based machine for a quick comparison to the 386 machines. Also, what version of the CL5429? VLB or ISA?

**Comment by drfrag666** [comment]
800x600.

**Comment by TC1995** [comment]
hmm, what happens with 640x480 and 1024x768?

**Comment by TC1995** [comment]
And hmm, I think I've already heard this issue.
I thought it was already fixed time ago.

**Comment by drfrag666** [comment]
Most likely the same. I've selected a different graphics card.

**Comment by TC1995** [comment]
Verified, it happens.

**Comment by TC1995** [comment]
Might be a bios bug, but I'm not fully sure, because with the ISA/VLB/PCI 5430/5434 this doesn't happen, with the same driver.

**Comment by drfrag666** [comment]
I know the other cards work. Can't be a bios bug i think, too severe. MS tested the board and it's not a known issue AFAIK.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by sskras** [comment]
I am new to this project. So:

> Might be a bios bug, but I'm not fully sure, because with the ISA/VLB/PCI 5430/5434 this doesn't happen, with the same driver.

... do you speak about a real hardware or about an emulated one?
