### ISSUE TITLE
Ramfonts does not works on the Hercules Plus.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3529]
**Describe the bug**
I tested the Hercules Plus card and installed the Software utilities for it. I found that when I run the ramfont program I only can see the DOS cursor with a black screen.

Here is the HDD image file:
[8088 Micoms XL-7.zip](https://github.com/86Box/86Box/files/12296632/8088.Micoms.XL-7.zip)

CFG+NVR file:
[8088 Micoms XL-7.zip](https://github.com/86Box/86Box/files/12296635/8088.Micoms.XL-7.zip)

Hercules Plus drivers:
[Hercules Graphics Plus Drivers and RAMFont (1986).zip](https://github.com/86Box/86Box/files/12296642/Hercules.Graphics.Plus.Drivers.and.RAMFont.1986.zip)

**To Reproduce**
1. Configure the Vm with Hercules Plus video card
2. Go to HERCPLUS\RAMFONT subirectory
3. Run the ramfont utility and choose a font like lcd.fnt

**Expected behavior**

**Screenshots**

![Hercules Plus 1](https://github.com/86Box/86Box/assets/31600563/b59b69d2-4c6b-4a93-9f89-6466baac71ef)

Hercules Plus with ramfont loaded
![Hercules Plus 2](https://github.com/86Box/86Box/assets/31600563/5ab0fc49-350d-4976-8e32-67a771f9ca64)

Same ramfonts (LCD.FNT) with the Hercules In-Color card
![Hercules In-Color LCD ramfont](https://github.com/86Box/86Box/assets/31600563/e1fcd606-41f5-422a-bdc6-caa54ceff625)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - 86Box version: 4.0.0.4795
 - Build information: old dynarec, Win 32

**Comment by Torinde** [comment]
FYI, Ramfonts were recently implemented in DOSbox-X: joncampbell123/dosbox-x/issues/4139

**Comment by OBattler** [comment]
It turns out this was already implemented, just incorrectly (the former developer who implemented the Hercules ColorPlus didn't really understand what was supposed to be done), I have now tentatively fixed this now, see if it now works correctly.

**Comment by Fenix770** [comment]
The ramfonts now works!. But I found some bugs

Example:
![HERCULES PLUS RAMFONT](https://github.com/86Box/86Box/assets/31600563/89247f28-d005-4071-8641-0c134d638c1d)

Distorted images on Hercules Plus:

![HERCULES PLUS distorted image](https://github.com/86Box/86Box/assets/31600563/1dca99bc-408c-4638-9efc-0229f873e5da)

The SETMODE.COM utility, which is inside the RAMFONT folder have several options, but it creates a distorted image:

![HERCULES UTILITIES](https://github.com/86Box/86Box/assets/31600563/a9fffb65-0a9c-4b24-becf-b6d6d9afac85)

![Hercules Plus distorted 2](https://github.com/86Box/86Box/assets/31600563/738ce2be-d6e7-4d6d-a5ba-a6f4eb6dd270)

**Comment by TC1995** [comment]
Most likely text mode wraparound issues like when it was in the InColor one.

**Comment by OBattler** [comment]
Fix committed.

**Comment by Fenix770** [comment]
I tested The Hercules Plus again. The chess demo program looks right, but the text cannot be seen. The SETMODE.COM utility still has issues; it creates a distorted text screen.

![Hercules Plus](https://github.com/86Box/86Box/assets/31600563/5bc2104d-4fff-411c-9e56-238ecee1f60a)

Here I used the SETMODE.COM program and used 8x8 text mode with the 4k ramfont option.
![Hercules Plus 8x8 4k Ramfont](https://github.com/86Box/86Box/assets/31600563/25e58a4c-516c-434c-bb42-46b11929a7e9)

**Comment by Fenix770** [comment]
I also found that  if :
1. I load Norton Commander
2. I load a Ramfont program and 
3. Then run the diagnostic utility (TEST.BAT), 
4. When I return to DOS prompt the text cannot be seen. 

Here is screenshot
![Hercules plus NC](https://github.com/86Box/86Box/assets/31600563/03f7929a-4501-41f3-b0e9-5e2dd5a5695a)

**Comment by OBattler** [comment]
I'm quite sure Norton Commander is hardcoded to use 80 columns, so that's not our bug.

As for the fonts disappearing, are you sure that program is for the Hercules Plus and not the Hercules InColor?

**Comment by Fenix770** [comment]
I'm almost sure, because  the Hercules Plus disk:

1 The timestamp of its files is 1986,  
2. Included the  Hercules RAM font mode options program.
3. Lacks the specific software included on the In-color disks, They are the PALETTE.COM  to change the text/graphics colors of the monochrome attributes (2 color for graphics and 4 color for text). and the Write-On utility.

The Hercules In-color card disks:

1. The timestamp of its files is 1987
2. Included specific drivers to get 720x348 at 16 colors, (Windows  1.04 and others)
3. Does not include the Hercules RAM font mode options program.

I downloaded the Hercules Plus drivers from here:
https://winworldpc.com/product/hercules-graphics-plus-drivers-and-ramfont/1986.

An the Hercules In-Color from here: http://www.dosdays.co.uk/media/hercules/incolor/hercules_incolor.zip
