### ISSUE TITLE
LIM EMS Emulation

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#353]
Hello,

I'm trying to add to a 8086 system the LIMEMS card Micro Mainframe EMS 5150T. But the card is not recognized by the Tandy LIMEMS driver... It say no card installed...

**Comment by OBattler** [comment]
The Tandy LIMEMS driver is most likely for some Tandy LIMEMS card. You can't use all drivers with all cards. You need to find the right drivers for the card you're using.

**Comment by jvernet** [comment]
The EMS 5150T is the Tandy Card.

**Comment by OBattler** [comment]
Make sure you add it to the right ports.

**Comment by jvernet** [comment]
Ok so I made some further tests:
Any RAM value other than 1024 or 2048 and the board is not recognized by the driver.
You have to set the board number, not let it to undefined. But in the GUI, you set it as Board 1, and the Driver say Board 0. Do not yet test with more than 1 board.

You need to add /C to EMS41.BIN in config.sys, if not, EMS is not recognized.

Then I tried some software that should use EMS memory. Borland C doesn't recognize it. QRAM said that the board is limited to 64k frame windows and can use it

I will investigate more. Do not tried in 286 mode, only 8088 or 8086 mode.

Can't find driver for the other board emulated.

**Comment by jvernet** [comment]
You can close the issue. It's working now, with good parameters/configurations
