### ISSUE TITLE
Cirrus Logic 5446 work in Win98, but not work in Win2000.

### ISSUE THREAD

**Issue by kzmidze** [86Box/86Box#3537]
**Describe the bug**
Cirrus Logic 5446 work in Win98, but not work in Win2000.

**Screenshots**
![win98](https://github.com/86Box/86Box/assets/117635969/77557c09-b8fa-4282-b293-e3b85f1ab7a8)
[86box-win98.cfg.txt](https://github.com/86Box/86Box/files/12316613/86box-win98.cfg.txt)
![win2000](https://github.com/86Box/86Box/assets/117635969/2acb2d7a-2538-4354-b0d1-3d95aae4034f)
[86box-win2000.cfg.txt](https://github.com/86Box/86Box/files/12316615/86box-win2000.cfg.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v4.0 build 4739

**Comment by TC1995** [comment]
Could you try using the latest build to see if the same thing happens?

**Comment by TC1995** [comment]
Well, to be fair the multiple displays configuration will be reworked in the future.

**Comment by OBattler** [comment]
Closing this with NOTABUG - this specific configuration (the 5446 as the secondary card) is simply not supported by Windows 2000.

**Comment by sskras** [comment]
> Closing this with NOTABUG - this specific configuration (the 5446 as the secondary card) is simply not supported by Windows 2000.

Wow! @OBattler: do you have any ideas why so?
