### ISSUE TITLE
Build 86Box

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#354]
Hello,

I tried, following given instructions to build my own version of 86Box, failed....

> $ make -f Makefile.local
> printer/png.c
> printer/png.c:54:10: fatal error: png.h: No such file or directory
>  #include <png.h>
>           ^~~~~~~
> compilation terminated.
> make: *** [win/Makefile.mingw:608: png.o] Error 1

Tried without success to  install/build libpng, no way...

Is there an updated/complet Build Env available ?

**Comment by vmp32k** [comment]
Did you install `mingw32/mingw-w64-i686-libpng` and/or `mingw64/mingw-w64-x86_64-libpng` (depending on your target architecture)?

**Comment by jvernet** [comment]
tried without success. If you have any instruction how can I install the missing libs in mingw, please help.

**Comment by vmp32k** [comment]
`pacman -S --needed mingw32/mingw-w64-i686-libpng mingw64/mingw-w64-x86_64-libpngv`  
that's all there is to it. What does it print when you do that?
Does anything like png.a exist in /mingw32/lib mingw64/lib ?  
` find /mingw*/lib | grep png`

**Comment by jvernet** [comment]
Ok, it's gooing a little bit further:

`printer/prt_escp.c:57:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [win/Makefile.mingw:607: prt_escp.o] Error 1
make: *** Attente des tâches non terminées....
`

Installed freetype with ` pacman -S --needed mingw32/mingw-w64-i686-freetype mingw64/mingw-w64-x86_64-freetype
`
No luck.

More over, there is no makefilemingw file in src, so build start with `make -j4 -fMakefile.local`

**Comment by dhrdlicka** [comment]
there is `Makefile.mingw` in `src\win`...

**Comment by jvernet** [comment]
Ok. Copied Makefile.mingw in src.
Added -I/mingw32/include/freetype2/  to CFLAGS
Everythings work now.

You may add these steps to the README and close issue.
