### ISSUE TITLE
86Box crashes when installing Windows 2000 (Beta & RTM) on Pentium machines

### ISSUE THREAD

**Issue by OldMadMan** [86Box/86Box#3548]
**Describe the bug**
86Box crashes when installing Windows 2000 (Beta & RTM). The crash usually occurs during the GUI-based installation of Windows 2000. Setup also didn't display any visible error messages or blue screens.

**To Reproduce**
Here are my config and machine nvr. [Windows 2000.zip](https://github.com/86Box/86Box/files/12327248/Windows.2000.zip)
I installed Windows 2000 on a Socket 8 GA-686NX motherboard. 

**Expected behavior**
Windows 2000 completes the installation normally.

**Screenshots**
Sorry, no screenshots as 86Box can crash without warning, and Windows 
Windows 2000 Setup also didn't display any visible error messages or blue screens.

**Desktop:**
 - OS: Windows 11, build 22631
 - 86Box version: v4.0 build 4838
 - Build information: Old Recompiler, Windows, x64

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by TC1995** [comment]
Try the x86 build of 86box at the moment.

**Comment by cold-brewed** [comment]
I couldn't reproduce this with the 64-bit version (macOS) and new dynarec. I used the same config/nvr and installed with 2000 Professional SP4 (`EN_WIN2000_PRO_SP4.ISO`).

Could you try the install again with the new dynarec?

**Comment by OBattler** [comment]
- OldMadMan: What emulated graphics card are you using?

**Comment by OBattler** [comment]
This should now be fixed, it turns out that the old recompiler in both its 32-bit and 64-bit versions, sometimes accidentally accesses a few bytes beyond the edge of the emulated RAM because it does not split accesses. Since I cannot make it do split accesses without negatively affected performance, I have decided to always allocate 16 extra bytes of RAM precisely to mitigate this.
