### ISSUE TITLE
Crystal Caves from Apogee seems to crash on start and corrupt the normal DOS text mode

### ISSUE THREAD

**Issue by Thraka** [86Box/86Box#3555]
**Describe the bug**
I was running with 486 66 PCI motherboard and noticed that all of the 3 crystal cave episodes crash when booting. Each game crashes with the error `RUNTIME ERROR 002 AT 0FC5:B54F`

So I swapped down the intel shuttle 386 board and still same errors. It always crashes. I tried a basic VGA adapter the stealth 2000 card, etc.

**Desktop (please complete the following information):**
 - OS: Win11
 - 86Box version: 3.11 [4311]

**Comment by Thraka** [comment]
I thought I had done so before, but I just got around to playing this on my physical 486 and it indeed crashes just like in 86box. Darn!

**Comment by Thraka** [comment]
Just in case anyone else happens to run into this... It turns out that the CDROM spec doesn't include `-`. When you mount a shared folder CDROM in 86box all of the `-` characters in file names are transformed into `_` characters. This was causing my game to think it was corrupted.

**Comment by OBattler** [comment]
I have now added support for the full DOS character set to VISO as I've seen legitimate CD with such in the wild before. Shift-JIS / code page 932, common on Japanese CD's, is not yet supported, would require UTF-8 to Shift-JIS conversion.

**Comment by Thraka** [comment]
Awesome @OBattler glad to hear it. I followed up in case that information would be useful to anyone else 😁
