### ISSUE TITLE
None of the Socket 3 SiS 496 Chipset machines boot with a Cyrix CPU

### ISSUE THREAD

**Issue by Zack13358** [86Box/86Box#3559]
**Describe the bug**
None of the Socket 3 SiS 496 Chipset machines boot using a Cyrix CPU, giving a POST code of 0A 09. Video card does not POST either (on cards that do POST, like the Voodoo3 3000)

**To Reproduce**
1. Select any Socket 3 SiS 496 Chipset machine
2. Select any Cyrix CPU
3. Click 'OK'
4. Machine does not boot, showing a POST code of 0A 09, and showing either a blank screen or the last thing that was on screen before reset

**Expected behavior**
Video card and motherboard BIOS should POST and boot normally.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 22H2 Build 19045.3324
 - 86Box version: 4.0 build 4856
 - Build information: i386, old dynarec

**Additional context**
Not applicable

**Comment by OBattler** [comment]
I cannot reproduce at all. Can you please post your 86box.cfg?

**Comment by Zack13358** [comment]
[86box.zip](https://github.com/86Box/86Box/files/12340250/86box.zip)

the cfg is inside the zip, I was using a cyrix CPU, just tried using a regular intel CPU and it worked

**Comment by OBattler** [comment]
I believe this is NOTABUG - those BIOS'es do not support Cyrix's version of the SMM save state structure.
