### ISSUE TITLE
Resident Evil 1 voodoo graphics corruption

### ISSUE THREAD

**Issue by deividxyz** [86Box/86Box#3561]
**Describe the bug**
Playing Resident Evil 1 with Voodoo graphics shows some graphical artifacts in some scenes. 
See attached screenshots for more detail.

**To Reproduce**
1. Install the game from [archive.org](https://archive.org/details/residentevil-pc-redump), Resident Evil (USA).zip
2. Playing the game shows visual artifacts

**Expected behavior**
Playing the game without artifacts

**Screenshots**

![Monitor_1_20230813-234823-105](https://github.com/86Box/86Box/assets/6402770/a416d4d3-bd3f-49e5-b6f0-a337b6bf9785)
![Monitor_1_20230813-234903-859](https://github.com/86Box/86Box/assets/6402770/326a87b3-e8ef-4d5e-b043-b150a933fb19)
![Monitor_1_20230813-234938-951](https://github.com/86Box/86Box/assets/6402770/ad7e46f9-50bd-4af1-bee6-1a748d891b73)
![Monitor_1_20230813-235018-320](https://github.com/86Box/86Box/assets/6402770/5f0d3752-772b-4ead-94d8-2af8fafdae46)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed, 20230814 snapshot
 - 86Box version: v4.0, commit f230507, compiled from git repo
 - Build information: x86_64

**Additional context**

Emulated PC:
i440FX ASUS P/I-P65UP5.
Intel Pentium Pro 166 Mhz
128 MB RAM
S3 Trio64V2/DX
Voodoo 2 4MB FB / 4 MB Texture, 4 Render Threads, no SLI, recompiler on.
Ensoniq AudioPCI

Windows 98 SE

**Comment by cold-brewed** [comment]
We've noticed that some games have an issue with the voodoo recompiler on the 64-bit version. Could you try again with the 32-bit version of 86Box?

**Comment by deividxyz** [comment]
> We've noticed that some games have an issue with the voodoo recompiler on the 64-bit version. Could you try again with the 32-bit version of 86Box?

I've tested the x86 version using 86Box-Linux-x86-b4869.AppImage and the issue persists.

![Captura desde 2023-08-14 19-27-33_x86](https://github.com/86Box/86Box/assets/6402770/b286fe68-80f3-49c2-8821-cb1989b6c7c3)
![Captura desde 2023-08-14 19-28-34_x86](https://github.com/86Box/86Box/assets/6402770/69b5273b-f0dd-4728-975d-fd1e0bc9370e)

Also in other test I disabled the Voodoo 2 recompiler in the settings but the issue is still there.

![Captura desde 2023-08-14 19-32-43_x86_norecomp](https://github.com/86Box/86Box/assets/6402770/08da08cb-8940-4f4f-b8ad-45ca980e843a)

**Comment by cold-brewed** [comment]
One other thing to try: Set the render threads to 2 instead of 4. Some games display artifacts when render threads are set to 4. 

What is your host CPU? What drivers are you using in the vm? Some glide games are *very* picky about drivers.

Would you be able to upload this vm somewhere? The whole directory that contains config, nvr and disk image.

**Comment by deividxyz** [comment]
Here are the results using 2 render threads. Notice the same artifacts in the same game map location.

![imagen](https://github.com/86Box/86Box/assets/6402770/8d256c60-b4b5-49d6-b5f9-543ad0003f78)

My host CPU is a Ryzen 9 5900X. I´m using the Creative 3D Blaster Voodoo 2 drivers from vogons, http://vogonsdrivers.com/getfile.php?fileid=132&menustate=0.

I've uploaded the vm in Drive https://drive.google.com/file/d/1q6C2PKw40C-PhhMYxCtoDalk8z5VLUAN/view?usp=sharing

Thanks in advance

**Comment by eddmanx** [comment]
That's the oldest Voodoo2 driver. I just tested it with the latest 3.02.02 driver from falconfly and the game works fine.

**Comment by OBattler** [comment]
Then this can be closed as NOTABUG, at least, not on our side.
