### ISSUE TITLE
ATi Mach32 is unstable in 86Box 4.0

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3564]
**Describe the bug**
In most cases, the screen is blank when using ATi Mach32. The emulated motherboard may beep 3 times.

**To Reproduce**
1. Set the video card to ATi Mach32 with an 80386/80486 motherboard.
2. Start the VM
3. Blank screen

**Expected behavior**
The screen appears.

**Screenshots**
_None_

**Desktop (please complete the following information):**
 - OS: Windows 11 Canary
 - 86Box version: 4.0.4839 (Old recompiler)
 - Build information: `10.0.25926.1000.amd64fre.rs_prerelease.230804-1441`

**Additional context**
_None_

**Comment by TC1995** [comment]
I have a new batch of fixes coming.

**Comment by TC1995** [comment]
Also, if this is the ISA one, it may be incompatible with BIOSes, as they make it hang at POST 71 70.

**Comment by cigaryno** [comment]
The VLB one also suffers from the same issue. This issue also occurs with many PCI motherboards too. The one using the Award BIOS works partially fine with the PCI variant and the one using the AMI BIOS is broken. All VLB and ISA-based motherboards suffers from this issue.

**Comment by OBattler** [comment]
It turns out to be a CPU bug, also affecting the PB570's Cirrus Logic CL-GD 543x's BIOS (which is why we do not emulate the PB570 yet).

**Comment by OBattler** [comment]
It turns out I was wrong and we were simply using a strange Mach32 ISA BIOS. We have now found a good one and both this and ROM's repositories have been updated accordingly. Therefore, I'm closing this.
