### ISSUE TITLE
Please add support for Dell OptiPlex GN+ in 86box

### ISSUE THREAD

**Issue by saipan7** [86Box/86Box#3565]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
86box support Dell OptiPlex GN+

**Additional context**

Mainboard Info:
https://theretroweb.com/motherboards/s/dell-optiplex-gn,-optiplex-gn

![image](https://github.com/86Box/86Box/assets/127716019/8424dafc-f4f7-4719-8b73-f48f91c5f452)

Mainboard bios download:
[Gn_a11.zip](https://github.com/86Box/86Box/files/12333280/Gn_a11.zip)

Mainboard Chipset Info:
- Intel 430TX (PCIset TX Triton II)
https://theretroweb.com/chip/documentation/297738-64af150218d36851840959.pdf
https://theretroweb.com/chipset/documentation/29773901-649d9a7dd13f0398505276.pdf
https://theretroweb.com/chipset/documentation/82439tx-61f86713c31d1819447673.pdf
https://theretroweb.com/chipset/documentation/29061301-649d9a7dd02fa942915375.pdf

- S3 86C775
http://old.vgamuseum.info/images/stories/doc/s3/trio64v2.pdf
![image](https://github.com/86Box/86Box/assets/127716019/87e0c0e4-2f01-46ea-82ff-4505b3266695)

- Creative CT2510 (Vibra 16X) 

- 3Com 3C905B Integrated Network Card
https://www.artisantg.com/info/HP_3Com_3C905_TX_Manual_2018813133359.pdf
![image](https://github.com/86Box/86Box/assets/127716019/94753607-d5d7-40c4-b34e-ce1acdf3a377)

Computer Photo:
![1](https://github.com/86Box/86Box/assets/127716019/24ee6269-11d4-491a-aa7c-571d30aa69e3)

![2](https://github.com/86Box/86Box/assets/127716019/232b799d-57d0-4146-a552-5fc17dc984b3)

![3](https://github.com/86Box/86Box/assets/127716019/48c65652-aee3-478f-9ba4-158ee7804841)

![4](https://github.com/86Box/86Box/assets/127716019/3964203e-d19e-415d-9f3d-f822db48501b)

Screenshot of Dell OptiPlex GN+ running in 86box using [i430TX] ADLink NuPRO-592 machine config:
![Dell OptiPlex GN Plus BIOS -- nupro592 - 1](https://github.com/86Box/86Box/assets/127716019/aa385593-b2db-4324-ac5c-491a341945a6)

![Dell OptiPlex GN Plus BIOS -- nupro592 - 2](https://github.com/86Box/86Box/assets/127716019/a19c1fb1-602b-48f4-893d-ca8ac1fe0ae8)

![Dell OptiPlex GN Plus BIOS -- nupro592 - 3](https://github.com/86Box/86Box/assets/127716019/fb6a04b2-a5ec-4ecb-ae5f-33221f4b2f42)

![Dell OptiPlex GN Plus BIOS -- nupro592 - 4](https://github.com/86Box/86Box/assets/127716019/15442116-8021-40bf-9c6b-782772f42640)

![Dell OptiPlex GN Plus BIOS -- nupro592 - 5](https://github.com/86Box/86Box/assets/127716019/61e774b9-2725-4a51-b315-b2bc822981fc)

86box CFG & NVR file:
[CFG & NVR.zip](https://github.com/86Box/86Box/files/12333266/cfg.nvr.zip)

Youtube video:
https://www.youtube.com/watch?v=0R2UZvv-ZtQ
![Screenshot 2023-08-14 130439](https://github.com/86Box/86Box/assets/127716019/b575a95d-cbb2-458e-98fb-e09b9ee0ad24)

thank you.

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
