### ISSUE TITLE
[Bug - regression] Joystick configuration : bad buttons

### ISSUE THREAD

**Issue by Altheos** [86Box/86Box#357]
On latest build, joysticks buttons appears to be incorrect 
![1834](https://user-images.githubusercontent.com/29195397/52525823-9e679c00-2caf-11e9-9623-34b375b5e95c.JPG)

Reverted  back to 1830 and it's fine
![1830](https://user-images.githubusercontent.com/29195397/52525833-bfc88800-2caf-11e9-8a66-e2c2253de9d9.JPG)

**Comment by OBattler** [comment]
That was my messup - I converted some strncpy()"s to memcpy()'s, the wrong way. I fixed this now, will be committed in the next commit.

**Comment by Altheos** [comment]
Problem fixed in build 1837. Thanks !
