### ISSUE TITLE
Please add support for Acer AcerMate 600 in 86box

### ISSUE THREAD

**Issue by saipan7** [86Box/86Box#3576]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
86box support Acer AcerMate 600

**Additional context**

Mainboard Info:
https://theretroweb.com/motherboards/s/acer-p3
![image](https://github.com/86Box/86Box/assets/127716019/7513632d-2e62-45d9-afac-96d9aa35f9b7)
![6](https://github.com/86Box/86Box/assets/127716019/90fdbfed-d048-4f68-8a45-e39cdd2cb738)

Mainboard bios download:
[acer-mate-600-p3-bios-u13-v2-0r02-j3-acr8de00-s00-950911-r02-j3-6431aa12d56e5655421877.zip](https://theretroweb.com/motherboard/bios/acer-mate-600-p3-bios-u13-v2-0r02-j3-acr8de00-s00-950911-r02-j3-6431aa12d56e5655421877.zip)

Mainboard Chipset Info:
- SiS 85C496/497 (486-VIP 486 Green PC VESA/ISA/PCI Chipset)
[SiS 496 & 497 Datasheet v3.0 improved with revised text visible(English).pdf](https://github.com/86Box/86Box/files/12341073/SiS.496.497.Datasheet.v3.0.improved.with.revised.text.visible.English.pdf)

- Cirrus Logic GD5434
[cl-gd543-4x_databook.pdf](https://github.com/86Box/86Box/files/12341079/cl-gd543-4x_databook.pdf)
[cl-gd543-4x_technical_ref.pdf](https://www.vgamuseum.info/index.php/companies/item/download/1330_a6d67b2ab41f1663f52232a86798dc90)

Computer Photo:
![1](https://github.com/86Box/86Box/assets/127716019/2aa3f798-38ca-4b1b-b204-c00a6c53af0d)
![2](https://github.com/86Box/86Box/assets/127716019/1ba9b27c-c39b-46a4-b606-d171be3f2715)
![3](https://github.com/86Box/86Box/assets/127716019/4b2647a8-1e9a-4732-ad98-4275ae0a433b)
![4](https://github.com/86Box/86Box/assets/127716019/a8cd6571-8e6c-4fc9-a213-ad048dde80fb)
![5](https://github.com/86Box/86Box/assets/127716019/8033a78a-1e50-4747-8a97-10413c1f0286)

Screenshot of Acer AcerMate 600 running in 86box using [i430FX] Acer V30 machine config:
![1](https://github.com/86Box/86Box/assets/127716019/da6ced04-1cb9-400a-ba2b-e943c656e0a7)
![3](https://github.com/86Box/86Box/assets/127716019/2109112f-1e4a-4f0e-a2ef-3e1f0eb28d47)
![5](https://github.com/86Box/86Box/assets/127716019/a5dcc9f3-efd1-40ce-8bb5-07828b2c7e5f)
![6](https://github.com/86Box/86Box/assets/127716019/3f94111a-6960-4c91-8946-600b8f2ff0a1)

86box CFG & NVR file:
[cfg & nvr.zip](https://github.com/86Box/86Box/files/12341088/cfg.nvr.zip)

thank you.

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.

**Comment by OBattler** [comment]
Completed it indeed is now, it seems someone PR'd it in 5.0.

**Comment by OBattler** [comment]
Or was it in 4.1?

**Comment by OBattler** [comment]
April 18th, 2025 by toggo9, so 5.0.
