### ISSUE TITLE
Please add support for Gateway 2000 P55C-233 in 86box

### ISSUE THREAD

**Issue by saipan7** [86Box/86Box#3578]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
86box support Gateway 2000 P55C-233

**Additional context**

Mainboard Info:
https://theretroweb.com/motherboards/s/anigma-sci-586-pci
![image](https://github.com/86Box/86Box/assets/127716019/8593a182-0331-40b1-be83-b56ab4c92376)
![mb](https://github.com/86Box/86Box/assets/127716019/c7e57018-db90-421c-acc2-af2d04e4789e)

Mainboard bios download:
[0AAES054.zip](https://github.com/86Box/86Box/files/12341352/0AAES054.zip)

Mainboard Chipset Info:

- Intel 430TX (PCIset TX Triton II)
https://theretroweb.com/chip/documentation/297738-64af150218d36851840959.pdf
https://theretroweb.com/chipset/documentation/29773901-649d9a7dd13f0398505276.pdf
https://theretroweb.com/chipset/documentation/82439tx-61f86713c31d1819447673.pdf
https://theretroweb.com/chipset/documentation/29061301-649d9a7dd02fa942915375.pdf

Computer Photo:
![1](https://github.com/86Box/86Box/assets/127716019/f0222376-61cb-4670-ae51-feacc93aaaa1)
![2](https://github.com/86Box/86Box/assets/127716019/8b5c7a4b-a392-42c3-b6b9-00f1044ebdfb)
![3](https://github.com/86Box/86Box/assets/127716019/22c93e3c-d985-4875-b829-8c0a66c9a19b)
![4](https://github.com/86Box/86Box/assets/127716019/04857b6b-3562-45c1-b24e-fc11b1c26eef)

Screenshot of Gateway 2000 P55C-233 running in 86box using [i430TXX] ADLink NuPRO-592 machine config:
![1](https://github.com/86Box/86Box/assets/127716019/93acc07d-d518-4c80-a490-df228aeb3fdb)
![2](https://github.com/86Box/86Box/assets/127716019/2bf29cfa-9b84-425d-9836-dae95cb69a17)
![3](https://github.com/86Box/86Box/assets/127716019/de247232-0146-4d5c-be90-a818b42ad4f6)
![4](https://github.com/86Box/86Box/assets/127716019/a0748909-c196-496e-82c2-a03bdabd4c1d)
![5](https://github.com/86Box/86Box/assets/127716019/6274d88e-8f70-48fe-8583-3bc0fb615e2e)

86box CFG & NVR file:
[cfg & nvr.zip](https://github.com/86Box/86Box/files/12341373/cfg.nvr.zip)

thank you.

**Comment by jriwanek** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server and issue #3577
