### ISSUE TITLE
Trindent 8900/9000 system reboot bug

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3591]
**Describe the bug**

I tested the Trident 8900B, 8900D and 9000. And found that the machine rebootS after loading HIMEM.SYS device driver.
I tested on 3 different buildS. On 286 machines, for some reason, the HDD is not recognized by the VM with the Trident video card but works fine with the Sigma Color 400.

NVR+CFG:
[386 DX trident 8900D.zip](https://github.com/86Box/86Box/files/12363193/386.DX.trident.8900D.zip)

HDD:
[386 Win 31 Trident 8900D.zip](https://github.com/86Box/86Box/files/12363198/386.Win.31.Trident.8900D.zip)

**To Reproduce**
1. Start the VM
2. Boot the machine
3. The VM restarts after loading HIMEM.SYS

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - 86Box version: 4.0.0.4892
 - Build information: old dynarec Win 32

**Additional context**
Worked fine on build 4.0.0.4849

**Comment by pankoza2-pl** [comment]
I think this actually has to do with EMM386.EXE as I encountered a bug where EMM386 will reboot the VM on 386 machines too
see issue: #3587

**Comment by OBattler** [comment]
This is now fixed.
