### ISSUE TITLE
[Feature request] Emulation of RAM banks

### ISSUE THREAD

**Issue by ohault** [86Box/86Box#3596]
In the current version, it would not be possible to configure RAM modules in banks like on real hardware.

I would be interesting to have in 86Box a memory-backend abstraction and providers for using either or both
- host based RAM
- file based RAM (with a cache) 
and expose memory objects into the guest as memory banks. 

https://github.com/qemu/qemu/blob/master/docs/memory-hotplug.txt

**Comment by jriwanek** [comment]
memory hotplugging is not something any board we emulate supports, and it's not likely to be supported by any board we're likely to emulate either.

**Comment by ohault** [comment]
> memory hotplugging is not something any board we emulate supports, and it's not likely to be supported by any board we're likely to emulate either.

This feature request does not require to support hotplugging.

**Comment by OBattler** [comment]
This is not doable, at least not without severely impacting performance.

**Comment by ohault** [comment]
It is not necessary always the case. e.g using NVDIMM and upcoming hardware.

**Comment by ohault** [comment]
> Operating systems have swap, and if you don't have enough memory will use it, ergo by _design_, so by all rights, your request is already implemented as reasonably as possible, as swap is ram stored on a disk.

I agree in the case of file based RAM, as it is somehow similar to OS swap file, but with two major differences:
- swap files are used when there is not enough physical memory, here the OS should see more physical memory provided by the emulated hardware.
- the implementation should be OS agnostic

For host based RAM, the implementation of emulated BANK, DIMM type, .... meanwhile somehow mapped to the BIOS.

**Comment by ohault** [comment]
Does it possible to move this Issue as a Discussion ?
