### ISSUE TITLE
Regression in ASUS P5A: dir | more crashes

### ISSUE THREAD

**Issue by Korkman** [86Box/86Box#3597]
**Describe the bug**
Recent builds (for example 4901) crash, release 3.11 doesn't.

**To Reproduce**
1. Setup machine with Super Socket 7, 8 MB RAM, 1.44 & 360K floppies, ASUS P5A mainboard
1. Install MS DOS 6.22 on 100 MB vhd
1. `cd DOS`
1. `dir | more`
1. guest hangs, outputs garbage, reboots, "Divide overflow" or similar random behavior

**Desktop:**
 - OS: Windows 11
 - 86Box version: b4901 32-bit

**Additional context**
Maybe related to #3278 ?

**Comment by OBattler** [comment]
On MS-DOS 5.00, I do not get the gabrage but I do get the hang.
