### ISSUE TITLE
[BUG] IBM PC not available

### ISSUE THREAD

**Issue by shinkarom** [86Box/86Box#360]
I downloaded build a3fb51ac and required roms as of October 8 2018.
After starting it the program says "Configured ROM set not available". (IBM PC apparently).
In the machine list in the settings there are only 71 items compared to 82 subfolders in the "machines" folder. And IBM PC the original is not on the list.
I have Windows 7 32 bit.

**Comment by daviunic** [comment]
You need to download the latest romset.

**Comment by shinkarom** [comment]
Where is the romset?

**Comment by daviunic** [comment]
https://tinyurl.com/rs20190213 (readme.md needs to be updated)

**Comment by shinkarom** [comment]
I found the link to that one on the Emulation General. The page there also needs to be updated.

**Comment by shinkarom** [comment]
Fixed. Thank you.

**Comment by daviunic** [comment]
Link in readme has been updated.
