### ISSUE TITLE
Unfortunately, the problem from #3563 wasn't fixed by the latest version.

### ISSUE THREAD

**Issue by Hornet512** [86Box/86Box#3600]
**Describe the bug**
I downloaded the recent version after seeing that you fixed it, and when attempting to upgrade to Windows 98, it crashed again. This time, I saw a error dialog pop up for like, 1 frame then closed with the window. I enabled logging and tried to get the crash again. Here's the log:

#
# 86Box v4.0 [build 4905] logfile, created 2023/08/19 11:19:13
#
# VM: Windows 95
#
# Emulator path: C:/Users/Hornet/Downloads/86BoxManager_1.7.4/
# Userfiles path: C:/Users/Hornet/86Box VMs/Windows 95/
# ROM path: C:/Users/Hornet/86Box VMs/Windows 95/roms/
# ROM path: C:/Users/Hornet/Downloads/86BoxManager_1.7.4/roms/
# ROM path: C:/Users/Hornet/AppData/Local/86Box/roms/
# ROM path: C:/ProgramData/86Box/roms/
# Configuration file: C:/Users/Hornet/86Box VMs/Windows 95/86box.cfg
#

Loading config file 'C:/Users/Hornet/86Box VMs/Windows 95/86box.cfg'..
Config loaded.

Loaded GPL Ghostscript, rev 9550 (20210927)
[0117:0000B991] Illegal instruction 00008B55 (FF)
timer_disable - !timer->next

It looks like its an illegal instruction error. Is that on the emulated machine, or on the host program?

**To Reproduce**
Could happen at anytime, mostly during the Windows 98 upgrade setup.

**Expected behavior**
To not crash.

**Screenshots**
It closes with a error dialog that closes after 1 single frame.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v4.0 build 4905
 - Build information: x64, old dynarec

**Additional context**
It seems like lowering the MHz on the processor prevents the crash, but how is an illegal instruction error being caused by a higher MHz processor? Is Windows 95 not capable of handling 120 MHz Pentium or above? Or is it just a classic case of my PC being crap?

**Comment by OBattler** [comment]
Then that's a completely different crash. The timer line from the log was not provided before.

**Comment by OBattler** [comment]
The illegal instruction is normal and is now what's crashing this. I would need your 86box.cfg to see what devices you may be using.

**Comment by Hornet512** [comment]
File type issues forced me to upload it as a TXT file.
[86box.txt](https://github.com/86Box/86Box/files/12384826/86box.txt)

**Comment by OBattler** [comment]
I have just committed some timer changes. See if that fixes this crash.

**Comment by Hornet512** [comment]
The bugs been fixed, but now the emulation is really laggy.

**Comment by Hornet512** [comment]
I mean if I'm not doing anything but moving the cursor, its fine, but when I move a window or prepare for setup, the lag becomes extremely noticeable, when I only bumped up the MHz from 100/60 to 120. It wasn't this laggy before the bug was fixed.

**Comment by Hornet512** [comment]
lmao it turns out the lag was because I had too many Firefox tabs open, oops!
