### ISSUE TITLE
Compaq Deskpro 386 (1988) reboots automatically after detecting RAM

### ISSUE THREAD

**Issue by borisvolk117** [86Box/86Box#3606]
**Describe the bug**
During recent builds, Compaq Deskpro 386 (1988) cannot boot at all: it just reboot after detecting RAM during POST.

**To Reproduce**
1. Create a "Compaq Deskpro 386 (January 1988)" machine (using any video card)
2. Start this machine
3. See error: it cannot boot into operating system or show Compaq error code,  just reboot after detecting RAM, again and again

**Expected behavior**
It should boot normally like build 4849.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11 pro x64 build 22H2]
 - 86Box version: [v4.0.0 build 4912]
 - Build information: [old dynarec, win-x86]

**Additional context**

[{68E9C767-378F-4B83-BD5A-A23147DEBFA8}.zip](https://github.com/86Box/86Box/files/12387175/68E9C767-378F-4B83-BD5A-A23147DEBFA8.zip)

**Comment by Fenix770** [comment]
I have the same issue. I tested several video cards.

**Comment by cigaryno** [comment]
I have the same problem with the AMD64 version of 86Box.

**Comment by OBattler** [comment]
After spending almost the entire day investigating, we are now suspecting the 1988 BIOS may be a bad dump.
