### ISSUE TITLE
With phys Numlock on, Shift doubles Numpad arrowkey inputs

### ISSUE THREAD

**Issue by Korkman** [86Box/86Box#3607]
**Describe the bug**
When the physical Numlock is ON, Shift+Numpad combinations cause duplicate arrowkey inputs. This is independent from the logical Numlock state. In `edit`, both physical and logical ON, Shift+Numpad2 will move down two lines. Physical ON and logical OFF, Shift+Numpad2 will select two lines. The dedicated arrowkeys on the other hand work fine.

**To Reproduce**
MS-DOS 6.22 on about any system 386 and up, toy around with `edit`
(also affects Windows 95 notepad.exe)

**Desktop:**
 - OS: Windows 11
 - 86Box version: tested release 3.11 and b4913
 - Build information: 32-bit

**Comment by OBattler** [comment]
This is a CANTFIX - on Windows, we pass the raw keyboard input to the guest and the guest clearly isn't handling it correctly.
