### ISSUE TITLE
fdd_load Error

### ISSUE THREAD

**Issue by telanus** [86Box/86Box#3610]
**Describe the bug**
Cstarting with https://github.com/86Box/86Box/commit/daa702c1b6e745fcd78c72b4e4b6539f2cda7434 when 86Box start it claims "Error seeking end of the file" does not happen with : https://github.com/86Box/86Box/commit/975ae1f0057e2e133ef632ac584715c8f3ecf47b

**Expected behavior**
To load without problems

**Screenshots**
![Screenshot_20230821_070725](https://github.com/86Box/86Box/assets/19357986/1bf7bac6-b58a-4de2-ac66-34451a9c9d30)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04.6
 - 86Box version: https://github.com/86Box/86Box/commit/daa702c1b6e745fcd78c72b4e4b6539f2cda7434
 - Build information: [i.e. new/old dynarec, architecture and build type]

**Comment by telanus** [comment]
Hi. Just had a test. When I create a new config, it'll work. Bu as soon as I save and exit, We have a 20% chance it'll throw the error. But if we add a floppy, and remove it, the error always happen.
But if I remove this the error goes away:

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
fdd_01_fn = 
fdd_02_fn = 
fdd_03_fn = 
fdd_04_fn =

**Comment by OBattler** [comment]
I believe this is now fixed.
