### ISSUE TITLE
SafeDisc-protected games crash and won't launch

### ISSUE THREAD

**Issue by mrmaller1905** [86Box/86Box#3611]
**Describe the bug**
Playing SafeDisc-protected games, including the retail copy of Carmageddon II: Carpocalypse now get a crash

**To Reproduce**
1. Install the game from [archive.org](https://archive.org/details/20230723_20230723_0858), Carmageddon II - Carpocalypse Now (USA)

**Expected behavior**
Play SafeDisc-protected games

**Screenshots**
![safediscerror](https://github.com/86Box/86Box/assets/126508232/1519f951-d55a-4dd4-bbd0-06281ac1083d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v4.0, commit 1ace98f656abbdd9e84fe92e26fd985f4961ed5b(https://github.com/86Box/86Box/commit/1ace98f656abbdd9e84fe92e26fd985f4961ed5b)
 - Build information: x86_64

**Additional context**
Emulated PC:
i440FX ASUS P/I-P65UP5.
Intel Pentium Pro 166 Mhz
128 MB RAM
S3 Trio64V2/DX
Voodoo 2 4MB FB / 4 MB Texture, 4 Render Threads, no SLI, recompiler on.
Ensoniq AudioPCI

Windows 98 SE

**Comment by OBattler** [comment]
Closing this as NOTABUG as other people have these same games working correctly. Either bad rips are floating around or some driver or something is not compatible with these games.
