### ISSUE TITLE
BeOS 4.0 bootloader fails to detect CD-ROM

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#3615]
**Describe the bug**
When attempting to boot BeOS 4.0's installation CD the boot diskette will not detect the BeOS boot volume on the CD-ROM and will ask to rescan devices.

**To Reproduce**
1. Attempt to boot BeOS 4.0 using the boot floppy and install CD
2. Notice that instead of detecting the boot volume on the CD-ROM an option appears to rescan devices

**Expected behavior**
The boot floppy should detect the install CD's boot volume and start the BeOS 4.0 installer

**Screenshots**
![Monitor_1_20230821-175609-660](https://github.com/86Box/86Box/assets/47463859/73e8f516-4900-4357-b38f-ed05f0cb341d)

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1
 - 86Box version: 4.0 build 4921
 - Build information: i386 old dynarec

**Additional context**
BeOS 4.0 boots correctly in build 4760 but build 4761 and later exhibit this behavior.
Config and NVR: 
[86Box-BeOSv4-config.zip](https://github.com/86Box/86Box/files/12403402/86Box-BeOSv4-config.zip)

**Comment by claunia** [comment]
Does your BeOS disc image contain the three separate tracks?

**Comment by win2kgamer** [comment]
It's a BIN/CUE with three tracks. The full VM including the install media I used is on the FTP.

**Comment by claunia** [comment]
Have you tried with the CD in `0:1` channel? BeOS can get very picky with drives in the secondary controller.

**Comment by win2kgamer** [comment]
Putting the CD-ROM drive on 0:1 instead of 1:0 gets the CD-ROM detected by the bootloader but the guest hangs after a bit of CD-ROM access. Build 4760 will completely boot the OS while build 4761 and 4921 hang.

**Comment by claunia** [comment]
So to get it clear.

Builds 4760, 4761 and 4921 see no bootable volume in 1:0.
Build 4760 boots perfectly in 0:1.
Builds 4761 and 4921 hang in 0:1.

Is that right?

**Comment by win2kgamer** [comment]
4760 boots correctly in both configurations (1:0 and 0:1)

**Comment by claunia** [comment]
Thanks for the clarification.
