### ISSUE TITLE
PCI Trident Cards are broken under Windows 98 FE

### ISSUE THREAD

**Issue by pankoza2-pl** [86Box/86Box#3616]
**Describe the bug**
When trying to use the Trident PCI Graphics cards, the display output is glitched out on Windows 98 FE
This happens on all video modes on the TGUI 9660XGi and the 9680XGi, but only in the 256 Color modes on the 9440AGi

**To Reproduce**
1. Install Windows 98 FE with a Trident PCI Graphics card
2. Wait for it to install the Trident Graphics drivers
3. After driver is installed, the display output is broken

**Expected behavior**
The display output is correct in all modes on Trident PCI Cards

**Screenshots**
![Monitor_1_20230822-080737-356](https://github.com/86Box/86Box/assets/77279607/4ccc8586-1012-408a-b560-4ff855816fd8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: v4.0 build 4921
 - Build information: new and old dynarec, i386

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!
config and nvr, can't upload the VHD because it's too big
[cfg & nvr.zip](https://github.com/86Box/86Box/files/12405429/cfg.nvr.zip)

**Comment by TC1995** [comment]
Great... more pitch issues...
