### ISSUE TITLE
ACPI shutdown issue with ASUS P3V133

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3618]
**Describe the bug**
When you do an ACPI shutdown with the ASUS P3V133 motherboard, it does not shut down but instead reboots.

**To Reproduce**
1. Install an OS that supports ACPI with the aforementioned motherboard
2. Shut down
3. The system reboots

**Expected behavior**
The motherboard shuts down.

**Screenshots**
_None_

**Desktop (please complete the following information):**
 - OS: Windows 11 Canary (`25931.1000.amd64fre.rs_prerelease.230811-1316`)
 - 86Box version: 4.0 (from Jenkins)
 - Build information: 4.0.4921 (AMD64, new recompiler)

**Additional context**
I've made some changes in the BIOS (i.e. I enabled the PnP OS option).

**Comment by OBattler** [comment]
This is a CANTDIX, we emulate the chipset I/O traps and if it still doesn't work correctly, the BIOS is buggy.
