### ISSUE TITLE
CD, Floppy, HDD, etc. sounds

### ISSUE THREAD

**Issue by NikNikovsky** [86Box/86Box#3619]
**Is your feature request related to a problem? Please describe.**
I honestly do not like when I only hear like, POST beeps, and nothing during setup.

**Describe the solution you'd like**
The solution I think would be correct is to record the sounds for all the CD, Floppy, Hard drives, etc. and make the emulator play those sounds accordingly.

**Describe alternatives you've considered**
I honestly didn't think of anythinf else

**Additional context**
None.

**Comment by cold-brewed** [comment]
https://github.com/86Box/86Box/discussions/2920
