### ISSUE TITLE
Random stuttering then host freeze during 86box win98se guest execution

### ISSUE THREAD

**Issue by necros2k7** [86Box/86Box#3632]
**Describe the bug**
Random stuttering then host freeze during 86box win98se guest execution

**To Reproduce**
1. Run win98 guest for 15-20~ min

**Expected behavior**
No host freezing

**Desktop (please complete the following information):**
 - OS: Win11
 - 86Box version: 3.11(x64,x32) , 4.1dev (x64.x32)
 - Build information: old and new dynarec
 - host specs cpu Xeon vid Nvidia GTX1660 drv 4**,5**
 - guest socket 7 ASUS 470 mb, Intel P120/Celeron 500 64/128gb ram, Voodoo3/S3Trio/S3Virge tried , Vulkan/Auto renderer tried, SB16/SBAWE32 tried, no serial / lpt / other controllers xept standart IDE, MSIntellimouse
 - mingw builds
 - P.S. same config in PCEM v17 is OK

**Comment by OBattler** [comment]
Try using the latest 4.0 from Jenkins, I haven't sync'ed the 4.1 branch to master in well over a week.

**Comment by OBattler** [comment]
Closing because of no feedback and it was likely also fixed with the PIC commit.
