### ISSUE TITLE
Mouse speed incontrollable PCBOX (any OS) 

### ISSUE THREAD

**Issue by KoghaandSooga** [86Box/86Box#3634]
**Describe the bug**
Mouse jumps all over the place in VM on any mouse that is detected

**To Reproduce**
Select a mouse from input:
Once mouse is detected in VM just move the mouse a tiny tiny bit and watch it fly to the other side of the screen. Not an issue in 86bx OR PCEM.
**Expected behavior**
Mouse to be normal or near normal speeds similar to 86box and PCEM's mouse speeds.

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10:
PCBOX NDR Windows 4.0.

**Additional context**
I'm using this build:https://github.com/PCBox/PCBox/actions/runs/5957366210 the latest one as of this post.

**Comment by KoghaandSooga** [comment]
How do I close this? I thought I was on the PCBOX and somehow stumbled upon the wrong thing.  86BOX has no mouse problem.

**Comment by Torinde** [comment]
@qeeg
