### ISSUE TITLE
CHD support 

### ISSUE THREAD

**Issue by solskogen** [86Box/86Box#3636]
For some reason I don't understand https://github.com/86Box/86Box/issues/2368 was closed. This is pretty much the same request.

**Comment by OBattler** [comment]
I looked at the library - there is no Msys2 package for it, and their CMake is Linux-only. Until someone makes a proper, cross-platform library we can actually use without having to build it ourselves, this will be a "Can't implement".

**Comment by solskogen** [comment]
Did you check [libchdr](https://github.com/rtissera/libchdr)? I was at least able to cross compile it from Linux to Windows. I have no clue if it works or not.
