### ISSUE TITLE
Invoking "86box --help" produces no output on console

### ISSUE THREAD

**Issue by nelsonhef** [86Box/86Box#3637]
**Describe the bug**
Command line help doesn't appear in Windows build

**To Reproduce**
1. Open the command prompt
2. Enter 86box --help or any other invalid parameter combination
3. The command prompt returns without printing the usage help parameters

**Expected behavior**
86Box should display usage help when invoking with --help or -?

**Screenshots**
![Clipboard01](https://github.com/86Box/86Box/assets/87081197/0161c487-720b-479f-a650-5fd5fd822645)
![Clipboard01](https://github.com/86Box/86Box/assets/87081197/109d0e89-135d-4f30-83b3-a051d650b718)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - 86Box version: 4.0.0.4943
 - Build information: old dynarec, win32

**Additional context**
The latest version that shows the help was the old 2.07, after the 3.0 the help no longer shows
The Linux builds shows the help usage with no problems.
![Clipboard01](https://github.com/86Box/86Box/assets/87081197/ba2de462-4fce-450d-b1c8-d86071f6e63f)

**Comment by OBattler** [comment]
I can't fix that. Windows does not allow console output for GUI applications.
