### ISSUE TITLE
ATi Mach32 causes abhorrent slowdowns in 8514/A mode on Windows 3.11 (ATi Mach32 in 8514/A mode is using more CPU than supposed to)

### ISSUE THREAD

**Issue by pankoza2-pl** [86Box/86Box#3642]
**Describe the bug**
When using the ATi Mach32 with the 8514/A driver on Windows 3.11, the emulation speed drops down from 100% to the likes of 60-70% (80-95% when my host CPU is undervolted)
**To Reproduce**
1. Install Windows 3.11 for Workgroups on the config provided in this report using the 8514/A driver (or just run Windows from the premade VHD also included in the ZIP file)
2. If your CPU is slow enough (but fast enough to emulate a P60 normally) you will see unexpected slowdowns

**Expected behavior**
The emulation speeds stays at 100%, as my i5-9300H can emulate a Pentium 60 well

**Screenshots**
![Zrzut ekranu 2023-08-25 112224](https://github.com/86Box/86Box/assets/77279607/0e13dc37-07f4-41ba-bfe7-ed561a68d4fd)

**Desktop (please complete the following information):**
 - OS: Windows 11 (obviously x64)
 - 86Box version: v4.0 build 4951
 - Build information: both new and old dynarec, i386

**Additional context**
This bug may not appear on users of faster CPUs, still I don't believe my CPU can't handle a 2D card from 1993
here is my vm, incase the bug is specific to my config
[1993_P60_PCI.zip](https://github.com/86Box/86Box/files/12437525/1993_P60_PCI.zip)

**Comment by pankoza2-pl** [comment]
also, slowdown doesn't happen with the ATi Mach32-specific driver on my IBM PS/ValuePoint P60 Config running Windows 3.10
[IBM PSValuePoint P60.zip](https://github.com/86Box/86Box/files/12437645/IBM.PSValuePoint.P60.zip)

**Comment by TC1995** [comment]
It seems to be related to how the clock is initialized without setting the card's eeprom.
Configuring the card's eeprom solved this, I mean, I get the interlacing at 1024x768 and speed is 100% after the eeprom configuration from DOS.

**Comment by OBattler** [comment]
Then I'm closing this as NOTABUG.

**Comment by pankoza2-pl** [comment]
setting up the EEPROM indeed fixed the slowdown
