### ISSUE TITLE
Paste from local machine clipboard to emulated machine

### ISSUE THREAD

**Issue by Zack13358** [86Box/86Box#3643]
**Describe the solution you'd like**
A window with a text box that you can type in/paste from your local clipboard that, once you press 'OK', will be typed in the machine

**Describe alternatives you've considered**
WebMSX has a similar feature, but that's just for MSX emulation

**Additional context**
![Screenshot 2023-08-26 103601](https://github.com/86Box/86Box/assets/94722680/d71cfb4d-a78f-40b4-b54e-57dde2f64941)
(WebMSX Paste feature. https://webmsx.org/ (Press Alt+B to activate))

**Comment by Torinde** [comment]
[DOSbox-X supports](https://github.com/joncampbell123/dosbox-x/issues/897) "pasting from clipboard" directly via its menu, without dialog box:
![image](https://github.com/86Box/86Box/assets/97228894/88ee6c82-1abc-4ca5-82f5-7a6293de7cf8)

If the guest OS in 86Box is Windows, then bi-directional shared clipboard like in VirtualBox/VMware would also be nice.

Note that for text you need to take modern hosts use the wide Unicode character set and it has to be mapped into the various guest codepages, which are more limited.

Similar request: dosbox-staging/dosbox-staging/issues/1864

**Comment by OBattler** [comment]
This is not really feasible. I would have to convert any text in the clipboard to keyboard scan codes, which then also means having to know what keyboard layout the guest has set, etc., which is doable in DOSBox-X as it emulates DOS itself in addition to the hardware, but 86Box doesn't do that. And copying from the guest would be even more involved - we would need to either have a copy function that can support all the emulated graphics cards (we're not VirtualBox or VMware that only emulate (S)VGA), write our own driver for such for every single guest platform, or outright build a full on OCR into the emulator.

So I'm closing this as unfeasible.
