### ISSUE TITLE
Kaypro PC doesn't work

### ISSUE THREAD

**Issue by lautis0503** [86Box/86Box#3648]
**Describe the bug**
The "[8088] Kaypro PC" machine does not boot. Only a blinking cursor and one beep.
According to [jriwanek](https://github.com/jriwanek)'s comment in the [PR](https://github.com/86Box/86Box/pull/2291), it behaved the same at the beginning.

**To Reproduce**
1. Create a new "[8088] Kaypro PC" machine.
2. Use CPU 8088/4.77 with 8087, 640KB memory, with time synchronization disabled.
3. Use CGA video, floppy 3.5" 720k, internal floppy controller, no hard disk.
4. Start the machine and insert Kaypro OEM MS-DOS 2.11 boot floppy from WinWorldPC.

**Expected behavior**
Show BIOS information, test memory, then boot into MS-DOS.

**Actual behavior**
It displays a blinking cursor, and give me one beep. Nothing else. No BIOS and no boot.

**Desktop:**
 - OS: Windows 7 x64 SP1
 - 86Box version: 3.11.0.4311 from release of this repository.
 - Build information: Official build

**Additional context**
If I use the rom file downloaded from [ROM Images for Various IBM PC Family Devices](https://www.minuszerodegrees.net/rom/rom.htm), then the BIOS works, MS-DOS boots, but the keyboard doesn't work. (This is the same situation I got in Hampa's PCE)
I think maybe the rom file is broken, and the Kaypro keyboard need extra work to emulate.

PS: I found 86Box 4.0 is just released several hours ago. I will check if it works.

**Comment by lautis0503** [comment]
I've checked 86Box version 4.0 [build 5000] downloaded from release here. The same situation.

**Comment by telanus** [comment]
@lautis0503 can you try this? https://workupload.com/file/BH4XNJfRaU3

or this one:
[86box.cfg.zip](https://github.com/86Box/86Box/files/12447448/86box.cfg.zip)

I can't reproduce this :(

**Comment by lautis0503** [comment]
@telanus Thanks for your two configs. They all work for me.
After check every differences between your configs and mine, I found the reason why it didn't work for me.

My thought was: one 3.5" 720KB floppy plus one hard drive is enough, so I change the second floppy drive to None. (After that I remove the hard drive to test)
The operation deleting the second floppy, that I never thought will matter, is one of the reasons why I only saw cursor blinking.

The second reason is the CGA. Your first config, with EGA video, won't care about how many floppies available.

**Conclusion: "[8088] Kaypro PC" machine, with CGA video, need at least two floppy drives to work, no matter enough or not.**

Maybe related to ROM. Whatever, I can run it now. Thanks.

**Comment by Fenix770** [comment]
I tested the Kaypiro MS-DOS 2.11 the machine only starts with 2 floppy drives. I created the partition with the MS-DOS 2.11 FDISK, but FOTMAT thinks the drive C is a floppy drive and not the hard disk. I think this machine may jumpers to configure the hardware or a proprietary HD controller.

Here is the systems disk I use:
https://winworldpc.com/product/kaypro-16-system-disks/1

**Comment by telanus** [comment]
@Fenix770 what hdd controller are you using? 

This one work for me: hdc = st506_xt_dtc5150x
