### ISSUE TITLE
Microsoft Sidewinder Pad port conflict in Windows 98 Device Manager

### ISSUE THREAD

**Issue by zltbugs** [86Box/86Box#3652]
**Describe the bug**
After updating to 86Box 4.0 build 5000, starting up a previously created Windows 98 SE virtual machine is now showing two joystick game ports.  Whenever the game port is viewed from the controller configuration in Windows, the configuration tool is slow and multiple controllers appear.  Attempting to verify the configuration does not work, none of the buttons or joysticks work.
After further investigation, the problem seems to be more with using the Microsoft Sidewinder Pad setting.

**To Reproduce**
1. Create a Windows 98 SE virtual machine that includes a Sound Blaster 16 PnP (See desktop section for machine details).
2. Start up the virtual machine.
3. The Sound Blaster 16 PnP drivers will automatically install (be sure to have the 98 SE CD ready).  The game port will install twice.
4. Once the drivers have been installed, check the Device Manager.  Two game ports will appear within the multimedia and sound devices section.

**Expected behavior**
This should work the way the joystick game port worked in 86Box 3.11.  In the older version adding a game port only showed one game port listed in Windows 98 SE.  Also the game port should function correctly when using a controller.

**Screenshots**
![Screenshot from 2023-08-29 08-21-08](https://github.com/86Box/86Box/assets/143510280/33fa2239-dc04-4eb2-b939-0da5d567f90c)
![Screenshot from 2023-08-29 08-21-41](https://github.com/86Box/86Box/assets/143510280/c433108c-68c2-4cb5-9b1a-8356085336d8)
![Screenshot from 2023-08-29 08-22-01](https://github.com/86Box/86Box/assets/143510280/2f93510e-1185-4f28-a36e-34b5e48aa1ff)
![Screenshot from 2023-08-29 08-22-31](https://github.com/86Box/86Box/assets/143510280/37236c8d-f0de-4284-a9c2-8046e0f87f12)

**Desktop (please complete the following information):**
 - OS: Windows 98 SE
 - 86Box version: 4.0 build 5000
 - Build information: 86Box-Windows-64-b5000.zip
 - Configure the machine with the following:
 - Super Socket 7, Gigabyte GA-5AX, Pentium MMX 166, 64MB RAM, AGP Voodoo3 3000, Joystick - Microsoft SideWinder Pad, Sound - Sound Blaster 16 PnP, Hard Drive should be large enough to support Windows 98 SE (6.4GB was used) and a CD ROM installed

**Additional context**
Removing or disabling the game port in Windows 98 does not resolve this.
An additional IDE port is also discovered with the Sound Blaster 16 PnP, this does not appear to cause any issues.
Moving back to 86Box 3.11 seems to resolve this issue.
Changing to the 2 axis 4 button controller will resolve this.  Issue is more with the Microsoft Sidewinder Pad setting.

**Comment by GLwd40** [comment]
I reported the same problem:
https://github.com/86Box/86Box/issues/3519

**Comment by zltbugs** [comment]
@GLwd40 I don't believe the Gigabyte GA-5AX motherboard has a game port.  There was nothing in the BIOS referring a game port.  I believe it's picking up the Sound Blaster 16's game port and the added game port from the 86Box configuration.

**Comment by GLwd40** [comment]
I see you have a network card. See if it has any conflict with any device. Because I'm curious.

**Comment by zltbugs** [comment]
@GLwd40 Actually, after adding the Sidewinder Pad a second time it appears to be working.  I removed the CH Flightstick Pro, restarted Windows then added the Sidewinder Pad.  I was able to calibrate in Windows and all inputs worked.  Maybe this happens on the initial setup of Windows.  I did have a network card added also, I didn't remove it since the Sidewinder Pad was working on the second try.

**Comment by OBattler** [comment]
This is NOTABUG - it's the Sound Blaster 16 PnP gameport being added on top of the standalone one.
