### ISSUE TITLE
timer_disable - !timer-> next

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3673]
**Describe the bug**
When I was using my WfW 3.11 VM, 86Box crashed with this text:
`timer_disable - !timer-> next`

**To Reproduce**
_None_

**Expected behavior**
_None_

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Canary (AMD64)
 - 86Box version: 4.0 (from Jenkins)
 - Build information: 4.0.5005 (AMD64, new recompiler)

**Additional context**
**VM config**:
**Motherboard**: Intel Advanced/ZP
**Processor**: Pentium (original) 100MHz (P54C, 50MT/S)
**Memory**: 64MB
**PIT mode**: Auto
**Display**: [PCI] S3 Vision964 (Diamond Stealth 64 VRAM) (4MB VRAM)
**Mouse**: PS/2 mouse
**Sound card**: Sound Blaster 16 (I/O 0x220, IRQ 7, DMA 1, DMA 5, MPU-401 on (I/O 0x330))
**MIDI output**: System MIDI
**Network type**: PCap
**Network card**: Realtek RTL8029AS (BIOS off)
**LPT1 device**: Generic PostScript printer
**Serial ports**: COM1 and COM2 enabled with not passthrough

**Comment by OBattler** [comment]
Can not reproduce.

**Comment by cigaryno** [comment]
> Can not reproduce.

That's normal. There are extremely rare bugs in the new recompiler and this was one of them.
