### ISSUE TITLE
Secondary video Bug

### ISSUE THREAD

**Issue by TechGuyC** [86Box/86Box#3674]
Describe the bug

The "Video 2" Function has 2 bugs

1-When i use for example,AGP S3 Virge/GX2 (Diamond Stealth 3D 4000) (Video 1)
and PCI ATI Mach32 (Video 2) the Secondary monitor does not appear

2-When i use any graphics card for video 1 and use MDA graphics card for Video 2
The VM freezes and when i close it stops responding

For Problem Number 1-Go to Tools, then Settings then Display,chose any graphics card 
for video 1 and any graphics card for video 2 then click ok

For Problem Number 1-Go to Tools, then Settings then Display,chose any graphics card 
for video 1 and MDA graphics card for video 2 then click ok

Expected behavior

The secondary monitor should appear and also the VM should not Freeze when using 
MDA for Video 2

Screenshots
None.

Desktop (please complete the following information):

OS: Windows 11

86box version 4.0

Build information: [x86_64, New Dynarec]

Additional context:
None

**Comment by DDXofficial** [comment]
The developers are aware of this issue - please be patient as there are many other bugs to fix that have a much higher priority. Adding a "help wanted" label is not exactly going to push this up their list, believe me.

**Comment by OBattler** [comment]
It appears the first issue has already been fixed by removing the Mach32 from the secondary video list, and I can no longer reproduce the second issue. Therefore, I'm closing this as fixed.
