### ISSUE TITLE
On the PCjr, floppy drive B: reads A:

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#3675]
**Describe the bug**
On the PCjr, floppy drive B: reads A:

**To Reproduce**
1. Connect two 360Kb or 720Kb floppy drives to your PCjr
2. Connect the IMG floppy image with DOS 3.3 to drive A:
3. Connect the IMG floppy image with other files to drive B:
4. Run PCjr and boot DOS 3.3
5. Switch to drive B:
6. Run the DIR command and you will see that floppy drive B: shows the files from drive A:

**Expected behavior**
Floppy drive B: should display files from drive B:

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v22H2
 - 86Box v4.0 x86 Build 5006
 - Build type: qt, regular, old recompiler

**Comment by OBattler** [comment]
The internal controller only supports one drive, it has no drive select.
