### ISSUE TITLE
Add more video cards

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3678]
List of video cards to add:
- [ ] [Video 7 VRAM II](http://www.dosdays.co.uk/topics/Manufacturers/video7.php) (not the same as HT208)
- [ ] Compaq AVGA
- [ ] ATI Rage (original version)
- [ ] ATI Rage II
- [ ] S3 Aurora64V+

**Comment by pankoza2-pl** [comment]
the Voodoo 5500 is out of the scope for 86Box, and only the very first ATi Rage is in scope, but the others can be possibly implemented if we find their VBIOSes
