### ISSUE TITLE
Tandy Models

### ISSUE THREAD

**Issue by mfmcosta** [86Box/86Box#3679]
**What's up with them?**
[8088] Tandy 1000 - The BIOS is the v1.02.00 which belongs to the Tandy 1000EX (or Tandy 1000SX)
[8088] Tandy 1000HX - Supports VGA
[8086] Tandy 1000SL/2 - Supports VGA

**Where did you get that info?**
The info was obtained from the [Tech Notes](https://www.lo-tech.co.uk/downloads/manuals/tandy/Tandy_1000_Tech_Notes_and_Jumper_Manual-vol-1.pdf)
on page 8 the list of the BIOS version per model
on page 22:
> You can install VGA in all of the 1000's, except the 1000, 1000A and 1000HD. The built-in CGA in these systems cannot be disabled.

And inside the TANDY1T1.020 says:
![image](https://github.com/86Box/86Box/assets/136728257/e2ff69d1-9632-42cf-a371-fa0f485ea8b2)
And the filename says "1.020"

**Do you have a Tandy 1000 ROM?**
I've found none on internet but I've found the version 1.010 (for Tandy 1000A or Tandy 1000HD)
[TANDY1T1.ZIP](https://github.com/86Box/86Box/files/12524529/TANDY1T1.ZIP)

**We will see what can be done**
Thank you!

**Comment by OBattler** [comment]
I'd like to see some some hard evidence that they only used one single BIOS version of each machine. Even IBM didn't do that. So this argument by version sounds to me a bit like arguing that the IBM PC 1982 BIOS must be the XT BIOS because of the date.
