### ISSUE TITLE
[Feature] Porting 86Box to Windows ARM

### ISSUE THREAD

**Issue by driver1998** [86Box/86Box#368]
I am porting 86Box to Windows ARM platforms, I made some success and posted some screenshots in the discord server.

I am not going to enable dynarec on ARM, but if there is some work on it, I'll try to port it.

And here are some updates:

# ARM64 (Windows 10)
- [x] Find a suitable toolchain (aarch64-w64-mingw32 at https://github.com/mstorsjo/llvm-mingw)
- [x] Build dependency: OpenAL (built with MSVC but it seems to work)
- [x] Build dependency: SDL2 (built with MSVC but it seems to work)
- [x] Build dependency: zlib
- [x] Build dependency: libpng
- [x] Build dependency: freetype
- [ ] Build dependency: pcap (But it doesn't seem to be needed for 86Box.exe?)
- [ ] Figure out a way to take screenshot in Direct3D without D3DX (not available for ARM)
- [x] Make the appropriate changes to Makefile.mingw
- [x] Build 86Box and do simple tests (MS-DOS 6.22 and Windows 3.1 on AMI 386 clone)

# ARM32 (jailbroken Windows RT)
- [x] Find a suitable toolchain (armv7-w64-mingw32 at https://github.com/mstorsjo/llvm-mingw)
- [x] Build dependency: OpenAL
- [x] Build dependency: SDL2
- [x] Build dependency: zlib
- [x] Build dependency: libpng
- [x] Build dependency: freetype
- [ ] Build dependency: pcap (But it doesn't seem to be needed for 86Box.exe?)
- [ ] Figure out a way to take screenshot in Direct3D without D3DX (not available for ARM)
- [x] Remove DirectInput dependency (Not available in ARM32)
- [x] Remove DirectInput dependency: win_mouse (Use RawInput instead, when DINPUT=n)
- [x] Remove DirectInput dependency: win_joystick (Use Xinput instead, when DINPUT=n)
- [x] Make the appropriate changes to Makefile.mingw
- [x] Build 86Box and do simple tests

**Comment by daviunic** [comment]
Very nice, keep up the good work. :)

PCap is an optional component for networking AFAIK, so it's not absolutely required for now in my opinion.

Not sure what the situation with Direct3D is on ARM, but if no alternative or workaround is found, the only option may be to simply ditch the D3D renderer for ARM.

I would be interested in what  OBattler has to say about this, though.

**Comment by driver1998** [comment]
@daviunic Direct3D works, but just no D3DX libraries (which is deprecated in Windows 8 IIRC).

**Comment by driver1998** [comment]
Working on Xinput support.
![TIM图片20190318200715](https://user-images.githubusercontent.com/22699485/54528940-73145300-49b9-11e9-92b7-8aa2f0940e45.png)

**Comment by OBattler** [comment]
That is very nice!

**Comment by driver1998** [comment]
- make -f win/Makefile.mingw ARM=y compiles the ARM32 version.
- make -f win/Makefile.mingw ARM64=y compiles the ARM64 version.
