### ISSUE TITLE
An "Integer scale + 4:3" option

### ISSUE THREAD

**Issue by eddmanx** [86Box/86Box#3687]
The current "Integer scale" option always does square-pixels. It's not possible to combine it with 4:3.

**Comment by OBattler** [comment]
Will look into this.

**Comment by OBattler** [comment]
This is now implemented.

**Comment by eddmanx** [comment]
Thanks. It has an issue which I posted about on the discord server. I'll post it here too for better visibility.
The image is too wide to be 4:3.

![320x240(480)-4 3 integer](https://github.com/86Box/86Box/assets/13473205/e7e79cb4-ac84-4b0b-afe7-c82945f43f34)
![320x240(480)-integer](https://github.com/86Box/86Box/assets/13473205/aebb84d5-596e-4e84-942f-2ef6d74741cd)
![640x480-integer](https://github.com/86Box/86Box/assets/13473205/1ba9a99d-693e-4578-b1ca-80c1b563446b)
