### ISSUE TITLE
Add Video 7 VRAM II

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3688]
Currently, only Video 7 VRAM I (HT208) is present in 86Box. If someone the VBIOS for the Video 7 VRAM II, please try to port it to 86Box.

**Comment by pankoza2-pl** [comment]
The Radius SVGA Multiview uses the same HT209 SVGA Chipset as Video 7 VRAM II, and will work with the Video 7 VGA 800x600 256 Color driver in Windows 3.1x

**Comment by cigaryno** [comment]
Closing as not planned for now.
