### ISSUE TITLE
Onboard audio option missing on Asus P5A and Pcchips M579

### ISSUE THREAD

**Issue by TechGuyC** [86Box/86Box#3690]
**Is your feature request related to a problem? Please describe.**
Yes,there is no "internal controller" option in the audio settings of the PCbox emulator (P5A and M579 config)

**Describe the solution you'd like**
Add the "internal controller" option in the audio settings of the PCbox emulator (P5A and M579 config)

**Describe alternatives you've considered**
SoundBlaster 16 PnP

**Additional context**
Asus P5A and Pcchips m579 has onboard audio

**Comment by pankoza2-pl** [comment]
it's 86Box not PCBox
also, the Asus P5A has no onboard Audio, but the PCChips has it as well as a different variant of the Asus called P5A-B

**Comment by OBattler** [comment]
Closing this with CANTFIX - the only board photo has a sticker on top of the sound chip, and the manual is vague about it as well, only claling it "3D Sound Pro".

**Comment by lemondrops** [comment]
@OBattler [Ultimate Retro claims the M579 has the HT1869V+, a C-Media CMI8330 rebrand](https://theretroweb.com/motherboards/s/pcchips-m579#expchips), however, we don't emulate the CMI8330.
