### ISSUE TITLE
IBM PS/2 model 30 286 POST error 162 even after configuring BIOS

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3693]
After configuring the BIOS of the IBM PS/2 model 30 286, the POST error 163 (system options not set) persists.
Host OS: Windows 11 Canary (AMD64)
86Box version: 4.0.5008 (AMD64, new recompiler)

**VM configuration**:
- **Processor**: Intel 80286, 10MHz
- **FPU**: Intel 80287
- **Wait states**: Default
- **PIT mode**: Auto
- **Softfloat FPU**: Off
- **Mouse**: Standard PS/2 mouse (works in system checkout)
- **Ports**: Three serial and parallel ports
- **Hard disk controller**: Internal controller
- **Hard disk**: One 32MB (CHS: 963-6-17) XTA hard disk
- **Floppy disk drive**: One 1.44MB PS/2 FDD

**Comment by TC1995** [comment]
Configure it again with the IBM PS/2 model 30 286 reference disk.

**Comment by cigaryno** [comment]
I did that many times with both auto and manual configuration but to no avail. I tried to:
- Remove the hard disk from the VM.
- Not installing a math coprocessor.
- Changing the "Parallel Port" value to `PARALLEL_3`.

**Comment by lemondrops** [comment]
Which error exactly do you get, 162 or 163? If it's the latter, go to "Set features" → "Set date and time", then press Enter to save (no need to change anything).

**Comment by cigaryno** [comment]
I don't get POST error 163 as I have already configured the date and time. Instead, I get POST error 162.

**Comment by cigaryno** [comment]
The integrated hard disk controller that 86Box emulates is the problem. By switching to an MFM controller, the POST error 162 is gone. PC DOS 3.30 recognizes the hard drive, but the advanced diagnostics disk does not. The system will also boot fine.
As a result, the problem is with 86Box. The "internal HD controller" emulated is actually an XTA controller which causes the POST error 162.
