### ISSUE TITLE
Crash when use this config

### ISSUE THREAD

**Issue by mckuhei** [86Box/86Box#3696]
**Describe the bug**
Crash when use this config

**To Reproduce**
Use this config

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 22h2 
 - 86Box version: 4.0 b5010

**Additional context**
[86box.cfg.gz](https://github.com/86Box/86Box/files/12659013/86box.cfg.gz)

**Comment by cold-brewed** [comment]
Could you be more specific? "Use this config" tells us nothing about how to reproduce or what the issue is.

I used the attached config and it worked fine for me.

**Comment by mckuhei** [comment]
Here is system log:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-09-21T07:26:38.0943556Z" />
    <EventRecordID>58841</EventRecordID>
    <Correlation />
    <Execution ProcessID="11908" ThreadID="23100" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-ICC291H</Computer>
    <Security UserID="S-1-5-21-161827674-1417004213-107667202-500" />
  </System>
  <EventData>
    <Data Name="AppName">86Box.exe</Data>
    <Data Name="AppVersion">4.0.0.5000</Data>
    <Data Name="AppTimeStamp">64ea78de</Data>
    <Data Name="ModuleName">86Box.exe</Data>
    <Data Name="ModuleVersion">4.0.0.5000</Data>
    <Data Name="ModuleTimeStamp">64ea78de</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">000000000058c926</Data>
    <Data Name="ProcessId">0x51e4</Data>
    <Data Name="ProcessCreationTime">0x1d9ec5cf4d078f1</Data>
    <Data Name="AppPath">D:\86Box-Windows-64-b5000\86Box.exe</Data>
    <Data Name="ModulePath">D:\86Box-Windows-64-b5000\86Box.exe</Data>
    <Data Name="IntegratorReportId">f514eacb-0165-458b-873b-855908f651e7</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

**Comment by cigaryno** [comment]
I downloaded the config file from your link, and it seems like I can reproduce your problem. 86Box crashes in many cases with configs similar to yours.

**Comment by cold-brewed** [comment]
@mckuhei The information you provided still does not tell us:

* What you were doing at the time of the crash
* How to reproduce
* Guest OS

Additionally, it would help to know if you were using:
* 32 or 64 bit 86Box
* New or Old Dynarec

**Comment by mckuhei** [comment]
I just downloaded the latest 86Box and configured it. When I pressed 'save,' it crashed. Then I tried to restart it, and it crashed again. I didn't install any guest OS in 86Box; I didn't even create a hard drive. This configuration works on 86Box 3.11.

**Comment by cold-brewed** [comment]
Thank you, that was very helpful. Unfortunately, it doesn't yet give us any clues on the cause.

It looks like you're using the 64-bit version with the old dynarec. To rule a few things out, I'd like you to download the latest CI version from [here](https://ci.86box.net/job/86Box/) and try again. Extract to a different directory from the one you are using.

First, try the version under New Recompiler -> Windows x64. It will be something like `86Box-NDR-Windows-64-bXXXX.zip
` where `XXXX` is the current build number.

If that still crashes, I'd like you to try the 32-bit version of the old recompiler at Old Recompiler -> Windows x86. The filename will be something like `86Box-Windows-32-bXXXX.zip`. Make sure to also extract this to a different directory.

Whether or not these other builds crash could give us some clues.

**Comment by mckuhei** [comment]
It seems works on 86Box-Windows-32-b5020

**Comment by OBattler** [comment]
I can't reproduce this. Try on the latest build.

**Comment by OBattler** [comment]
OK, I can reproduce it now.
