### ISSUE TITLE
Trying to compile in Haiku Os

### ISSUE THREAD

**Issue by johna23-lab** [86Box/86Box#3697]
Hi! i'm trying to compile the source code in Haiku Os, but i get this error

[ 84%] Building C object src/video/CMakeFiles/vid.dir/vid_ht216.c.o
In file included from /boot/system/develop/headers/os/app/Application.h:10,
                 from /boot/system/develop/headers/os/AppKit.h:6,
                 from /boot/home/86Box-version-4.1/src/qt/qt_mainwindow.cpp:130:
/boot/system/develop/headers/os/interface/InterfaceDefs.h:469:36: error: 'mode_mouse mouse_mode()' redeclared as different kind of entity
  469 | mode_mouse              mouse_mode();

Any solution?
Thanks

**Comment by johna23-lab** [comment]
After a while i found a possible solution, is change the name mouse_mouse for mode_muse with this command

cd src
grep -rl mouse_mode . | xargs sed -i 's/mouse_mode/muse_mode/g'

It works, but then i found an error at src/ini.c:351

ini_fgetws(buff, sizeof_w(buff), f);

changed for 

ini_fgetws(buff, sizeof_w(buff), fp);

Then the program compiles perfect and runs, but i have a small problem, i have no mouse working, but this "issue" can be "solved", if i disable the QT in the compilation then 86box runs in SDL mode and the mouse works, looks the qt conflicts with the Haiku render but not with the SDL?

I hope this problem can be solved in a better way and get mouse working with the QT in Haiku_Os

Thanks!

**Comment by jriwanek** [comment]
Bug in ini.c fixed in commit 07af166.

**Comment by OBattler** [comment]
Does Haiku OS use Wayland, Xinput2, or evdev?

**Comment by johna23-lab** [comment]
> Does Haiku OS use Wayland, Xinput2, or evdev?

According to wikipedia it have 
Xlib (X11) and [Wayland](https://en.wikipedia.org/wiki/Wayland_(protocol)) compatibility layers.

**Comment by OBattler** [comment]
This is now closed. The Wayland mouse breakage has an issue open already - Haiku OS most likely sets the mouse to absolute mode which then breaks.
