### ISSUE TITLE
I can't use IDE channel 1 within 86Box release 1838.

### ISSUE THREAD

**Issue by coolhaken** [86Box/86Box#370]
Hi,
I think there may have some issue in IDE emulation.
When I use only one HD (IDE 0:0) and a CD-ROM (IDE 0:1) or just use 2 HD (IDE 0:0 and IDE 0:1),
everything is O.K.
But if I want to use 2 HD (IDE 0:0 and IDE 0:1) and a CD-ROM (IDE 1:0), the CD-ROM drive can't detect my CD-ROM.
I also tried 2 HD (IDE 0:0 and IDE 1:0) and a CD-ROM (IDE 0:1), then the BIOS hangs at "wait ......" and can't boot.
I use "[386DX ISA] AMI 386DX clone", and got the same problem while using "[486 ISA] AMI 486 clone".

**Comment by ppgrainbow** [comment]
These emulated machines which use the DataExpert OPTi-495SX motherboard (386 and 486 ISA) don't natively support more than one IDE controller and must be used on IDE channel 0.

You can have up to either two IDE hard drives or one IDE hard drive and one CD-ROM.

To get around this, you can use an Adaptec or BusLogic compatible SCSI adapter to overcome this limitation or you can use a 486 PCI-baed Rise Computer R418 machine which can use up to four IDE hard disks.

On my test machine, I'm using the CD-ROM on IDE channel 0 master and you have to use a CD-ROM driver and MSCDEX under MS-DOS to detect it.

Anyways, what hard disk controller are you trying to use on these emulated machines?

**Comment by coolhaken** [comment]
Thanks for your reply. :)
There is nothing special, I use the internal HD controller.
Since this is the native limitation of OPTi-495SX motherboard, I have no more questions about the IDE problem.

**Comment by ppgrainbow** [comment]
> 
> 
> Thanks for your reply. :)
> There is nothing special, I use the internal HD controller.
> Since this is the native limitation of OPTi-495SX motherboard, I have no more questions about the IDE problem.

The internal hard disk controller can only provide support for one IDE hard disk controller for up to two hard disks. Again, I would suggest the following:

1. Use a 486 PCI-based Rise Computer R418 where you can have the ability to use either a VLB or a PCI Dual  IDE controller.
2. Use a Adaptec or BusLogic ISA SCSI controller.

**Comment by OBattler** [comment]
This is actually fixed now on my end - dual-channel IDE controller can now be properly used with all AT+ machines.
