### ISSUE TITLE
IBM PS/1 not recognizing floppy disks

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3703]
The IBM PS/1 does not recognize floppy disk drives at all. It throws a general failure reading drive A:. I only tested model 2121, and I don't think the PS/1 model 2011 can recognize floppy disks. I use a 1.44MB FDD in my VM.

**Desktop:**
 - OS: Windows 11 Canary (AMD64)
 - 86Box version: 4.0.5011 (AMD64, new recompiler)

**Comment by TC1995** [comment]
You need to use the PS/2 floppy drives (1.44M or 1.2M), as in, select "1.44M PS/2" or "1.2M PS/2"

**Comment by cigaryno** [comment]
Thank you! I did not know that the IBM PS/1 also requires a PS/2 FDD.
**Note:** Only the ISA PS/2s requires PS/2 type FDDs. MCA PS/2s can use standard FDDs

**Comment by TC1995** [comment]
yes, but the PS/1 2011 and 2121 require the PS/2 floppy drives too.
