### ISSUE TITLE
Auto-Pause when window inactive.

### ISSUE THREAD

**Issue by raszpl** [86Box/86Box#3704]
**Is your feature request related to a problem? Please describe.**
Modern games offer auto-pause when game not in focus. Useful when alt-tabbing to read something (documentation/walkthroughs) or when some notification steals your focus away at critical moment.

**Describe the solution you'd like**
Optional Autopause when inactive.
WM_PAUSE looks promising. WM_KILLFOCUS/WM_SETFOCUS messages would be a good spot to put a check if optional auto-pause is enabled
https://github.com/86Box/86Box/blob/491cdda4582effd772221609b993318ed1e80b8f/src/win/win_ui.c#L460
https://github.com/86Box/86Box/blob/491cdda4582effd772221609b993318ed1e80b8f/src/win/win_ui.c#L456
https://github.com/86Box/86Box/blob/491cdda4582effd772221609b993318ed1e80b8f/src/win/win_ui.c#L1110
https://github.com/86Box/86Box/blob/491cdda4582effd772221609b993318ed1e80b8f/src/win/win_ui.c#L1106

would something as simple as adding IDM_AUTO_PAUSE/auto_pause and:
```
if (auto_pause && dopause)
    PostMessage(hwndMain, WM_PAUSE, 0, 0);
```
```
if (auto_pause && !dopause)
    PostMessage(hwndMain, WM_PAUSE, 0, 0);
```
do the trick here?

**Describe alternatives you've considered**
ahk script, but Pause is not bound to any key input and
`PostMessage, 0x8890,,,, 86Box`
didnt work for me, even if it did it would be one more program for something that is simple to implement inside 86Box.

**Additional context**
Potential logical bug:
WM_KILLFOCUS pops out mouse focus with plat_mouse_capture(0)
https://github.com/86Box/86Box/blob/491cdda4582effd772221609b993318ed1e80b8f/src/win/win_ui.c#L460C1-L462C35
but if you first manually Pause and then click into the window 86Box will grab mouse focus anyway despite emulator being Paused with no way to Unpause without working mouse outside and UI is being frozen so toolbar "press F9+F12 or middle .." info doesnt show.

Two alternative proposals for maybe a more logical behavior:
- mouse click does capture focus like right now and in addition unPauses if 86Box was Paused.
- mouse click is ignored with some kind of UI hint letting the user know 86Box is currently Paused.

**Comment by OBattler** [comment]
The Win32 UI is deprecated, you need to make the changes to the QT UI instead.

**Comment by OBattler** [comment]
This is now implemented.
