### ISSUE TITLE
IBM PC 330 POST error 129

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3705]
**Describe the bug**
In my config, the IBM PC 330 displays POST error 129 (system board failure) and I am redirected to the CMOS Setup. Selecting "Exit Setup" will let the system boot. but on **every reboot**, I am once again redirected to the CMOS Setup.

**To Reproduce**
1. Make a VM with the IBM PC 330.
2. Configure the BIOS.
3. Get the POST error 129. You will be redirected to the CMOS Setup.

**Expected behavior**
The computer boots.

**Screenshots**
_None_

**Desktop:**
 - OS: Windows 11 Canary (AMD64, multiprocessor free)
 - 86Box version: 4.0.5011
 - Build information: AMD64, new recompiler

**Additional context**
_None_

**Comment by TC1995** [comment]
Most likely the 8514/a timings or the new recompiler (if enabled).

**Comment by cigaryno** [comment]
I use the machine's integrated Cirrus Logic GD5430 video card and 8514/A disabled. I will try something.

**Comment by cigaryno** [comment]
I can't believe! Setting the CPU to the Intel Overdrive (DX4) fixed this error.
