### ISSUE TITLE
IBM PCjr not booting

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3707]
The IBM PCjr refuses to boot. It beeps twice and remains stuck in a black screen with a cursor.

**Desktop:**
 - OS: Windows 11 Canary (AMD64, Multiprocessor Free)
 - 86Box version: 4.0.5011
 - Build information: AMD64, new recompiler

**Comment by mfmcosta** [comment]
It works upto release 4.0.5006 (old recompiler) after that release, at boot gives two short beeps = display

**Comment by OBattler** [comment]
Does it work on the latest build?

**Comment by cigaryno** [comment]
No, still not booting in build 4.0.5020 (AMD64, new recompiler).

**Comment by borisvolk117** [comment]
It cannot boot in build 5020 (x86, old recompiler), either.

**Comment by OBattler** [comment]
Wait for the next build and see if it boots now.

**Comment by borisvolk117** [comment]
Still not booting in build 5027 (x86, old or new recomplier). :(
