### ISSUE TITLE
Compaq Portable III 386 not showing cursor

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3708]
This bug is not severe, but the cursor does not show up in the Compaq Portable III 386's integrated plasma display.

**Desktop:**
 - OS: Windows 11 Canary (AMD64, Multiprocessor Free)
 - 86Box version: 4.0.5020
 - Build information: AMD64, new recompiler (regular)

**Comment by OBattler** [comment]
The cursor doesn't show where? In DOS? Windows?

**Comment by cigaryno** [comment]
In text-based parts (POST, DOS and so on). To be exact, I am talking about the blinking cursor.
