### ISSUE TITLE
IBM PS/2 model 60 ESDI controller conflict

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3711]
**Describe the bug**
I've set up an IBM PS/2 model 60 VM, configured it with the reference disk and the ESDI hard drive controller conflicts with the ROM address (set to enabled).

**To Reproduce**
1. Set up a VM with the configuration in "Additional context"
2. Configure the system with its reference disk
3. Go to Set Configuration
4. Select View Configuration or Change Configuration

**Expected behavior**
The HD controller works.

**Screenshots**

**Desktop:**
 - OS: Windows 11 Canary (AMD64, new recompiler)
 - 86Box version: 4.0.5020 (regular)
 - Build information: AMD64, new recompiler

**Additional context**
VM config:
**Machine**: [80286 MCA] IBM PS/2 model 60
**CPU**: Intel 80286 (10MHz)
**Wait states**: Zero wait state
**FPU**: 287
**Memory**: 2MB
**Video**: Internal
**Mouse**: Standard PS/2 mouse
**Ports (COM & LPT)**: Two serial ports and one parallel port
**HD controller**: IBM PS/2 ESDI Fixed Disk Adapter

**Comment by TC1995** [comment]
Use updated @ddff.adf and cddff.adf files for it and inject it to the reference disk (look over at ardent ps/2)

**Comment by cigaryno** [comment]
I tried that but it didn't work. I even tried `@ddff.adf` and `cddff.adf` from model 80's reference disk.

**Comment by TC1995** [comment]
I mean, not necessarily model 80's, but updated Phoenix ones from said site.

**Comment by cigaryno** [comment]
Thank you! Using the Phoenix/NCR ADF file fixes the conflict.
