### ISSUE TITLE
Dos sound is softer compared to Windows 9x

### ISSUE THREAD

**Issue by mvgian** [86Box/86Box#3717]
**Describe the bug**
When playing games in DOS, the sound is barely audible unless I set the speaker volume to the max which still the volume level is decent at best. I’ve tried various sound cards: Sound Blaster 16 and Pro and setting the volume to the max with their respective mixer applications but it doesn’t help. However when running Windows 9x, the volume is audible without the need to set my speaker volume to the max

**To Reproduce**
1. Run DOS games with sound configured
2. Run Windows 9x media or games

**Expected behavior**
Sound volume when playing games in DOS should be audible or somewhere near as loud as with Windows 9x

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 11 and Mac OS Sonoma
 - 86Box version: 4.0
 - Build information: x86_64 and arm64

**Additional context**
None

**Comment by Flo9696** [comment]
There should be utility in the dos driver for the volume setting for the SB card.

**Comment by mvgian** [comment]
I’ve already tried that but there’s no improvement

**Comment by OBattler** [comment]
This is NOTABUG - you need to set both the master and wave volumes.

Also, it's not true that the volume is not low when using Windows - I literally just had to set it to maximum in Windows 95 on a Sound Blaster 16.

It's also CANTFIX - increasing the volume would cause clipping with the current code.

**Comment by mvgian** [comment]
@OBattler I did mentioned that in Windows 9x (Win95/98), the audio volume is fine. The problem ONLY happens for audio in DOS mode (eg. running DOS games). Why is Windows 9x sound volume is much more audible compared to pure DOS mode? Is this a limitation for 86Box that can't be solved?
