### ISSUE TITLE
286 MCA IBM PS/2 models using only 512KB of memory and POST error 164

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3726]
**Describe the bug**
As of the latest builds, 286 MCA IBM PS/2s will use only 512KB of memory and throw POST error 164, Running automatic configuration from the reference disk in not helpful. 386 IBM PS/2s are not affected.

**Desktop:**
 - OS: Windows 11 22H2 Moment 4 update (Multiprocessor Free, AMD64)
 - 86Box version: 4.0.5033
 - Build information: AMD64, new recompiler

**Comment by TC1995** [comment]
Well, model 60 apparently requires an updated sc.exe (found over at ardent PS/2 as part of this https://www.ardent-tool.com/memory/IBM_Expansion.html#BOPT103).

**Comment by cigaryno** [comment]
This bug arose in the build 503x range. Build 5029 hasn't this bug.

**Comment by TC1995** [comment]
Again, that's because, for the model 60, I was incorrectly giving it the 50 id and thus the bug wasn't there, just use bopt13.img, apply it to the 50/60 reference disk.

**Comment by cigaryno** [comment]
Updating the reference disk with `bopt13.img` partially fixed the 512KB memory problem, but POST error 164 persists.

**Comment by TC1995** [comment]
it persists because you don't have the memory expansion adf.

**Comment by cigaryno** [comment]
86Box is not emulating any memory expansion card to the system. Opening MCA Devices lists what devices are used in the VM and there is only the ESDI hard disk controller. For your reference, the VM has 2MB of memory and I was not prompted to insert a diskette with an ADF.

**Comment by TC1995** [comment]
Just use this reference disk and keep it as well.
https://www.mediafire.com/file/0feklehnqh588zc/rf5060a.img/file

**Comment by cigaryno** [comment]
Thank you for this reference disk. It does not show me the POST error 164.
