### ISSUE TITLE
SIS graphics card

### ISSUE THREAD

**Issue by TechGuyC** [86Box/86Box#3727]
### Discussed in https://github.com/86Box/86Box/discussions/3709

<div type='discussions-op-text'>

<sup>Originally posted by **TechGuyC** September 29, 2023</sup>
Add SIS 6326 AGP 

SIS 6326 AGP doucmentation:
[SIS 6326.pdf](https://github.com/86Box/86Box/files/12765629/SIS.6326.pdf)

SIS 6326 AGP bios
[OEMROM.zip](https://github.com/86Box/86Box/files/12765726/OEMROM.zip)

</div>

**Comment by jriwanek** [comment]
That's the userguide, not the datasheet, and is entirely worthless for implementing the card, as such, closing.

**Comment by senseab** [comment]
please check these 2 documents. Is the datasheet that you want?

[6326.documentation.pdf](https://github.com/user-attachments/files/16901808/6326.documentation.pdf)
[393_sis6326.pdf](https://github.com/user-attachments/files/16901809/393_sis6326.pdf)
