### ISSUE TITLE
Garbled display with Red Hat 9 guest and a Trident  GPU

### ISSUE THREAD

**Issue by renanbirck** [86Box/86Box#3728]
**Describe the bug**
When booting Red Hat Linux 9 (the 2003 one, not RHEL) having selected a Trident TGUI 9680XGi video card,  I get a garbled screen as can be seen on the screenshots:

![rh9_garbled_screen_1](https://github.com/86Box/86Box/assets/553325/b2178c22-443b-4e32-93f1-b50d6109dfdc)

![rh9_garbled_screen_2](https://github.com/86Box/86Box/assets/553325/220bf7f6-9071-4bc0-a52d-ea1fea3b87d9)

Machine is a Pentium II on an ASUS P/I-P65UP5 motherboard. The cfg + image file I am using is at https://drive.google.com/file/d/1ydbK6TvON97oI_FdJj9xtqFSGMMpECgv/view?usp=sharing (note, expands to a ~4GB file, the root password is 'root')

**Desktop (please complete the following information):**
 - OS: Fedora 38 x86_64
 - 86Box version: build 5017, but also happens with 5044
 - Build information: old dynarec, x86_64

**Comment by TC1995** [comment]
Great, more pitch issues on the undocumented TGUI...

**Comment by TC1995** [comment]
Ok, there's still something deeper than the pitch now.
