### ISSUE TITLE
[Feature request] Real Floppy Drive Support

### ISSUE THREAD

**Issue by retrorepair** [86Box/86Box#373]
I understand why a lot of emulators such as Amiga don't support real floppy controllers (I think with the exception of UAE and the catweasel?), usb or otherwise but I would have thought being a pc emulator it would be more likely that 86Box can support them? Would the emulator still require low level access?

I imagine I'm not the only one with a large stack of disks and a floppy drive to hand. I love hearing it step away whilst reading too. Sad as that may be!

**Comment by OBattler** [comment]
Yes, it would require low level access.

**Comment by OBattler** [comment]
This is not doable at all without a requiring a 3rd party driver.

**Comment by retrorepair** [comment]
What about greaseweazle? It's pretty widely used these days
