### ISSUE TITLE
Screen tearing in every game

### ISSUE THREAD

**Issue by juan200213** [86Box/86Box#3732]
**Describe the bug**
Hello every game I played has some screen tearing whenever I choose a fast components and vsync

**To Reproduce**

**Expected behavior**
Some screen tearing in the games

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - 86Box version: 4.0
 - Build information: stable

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by cold-brewed** [comment]
This is completely missing the required information and still contains mostly placeholder text. If you'd like to report an issue, please properly fill out the issue template.
