### ISSUE TITLE
Dos games has some screen tearing

### ISSUE THREAD

**Issue by juan200213** [86Box/86Box#3736]
**Describe the bug**
Hello some dos games like kingdom the far reach or wetlands has some screen tearing even if I have vsync enabled and have fast components configured

**Expected behavior**
See the screen tearing in the games

**Desktop (please complete the following information):**
 - OS: windows 11
 - 86Box version: 5.0 build 5065
 - Build information: old dynarec x64 build 5065

**Comment by cold-brewed** [comment]
This is nearly identical to your issue from yesterday (#3732). You have provided almost no additional information *and* did not include reproductions steps. Those steps are included in the template.

* What OS are you running in the vm?
* What is your full guest machine configuration?
* What hardware are you using?
* How do we reproduce this?
* What games and versions show this issue?
* Have you enabled vsync in the guest game or video drivers? Does the option even exist?
* What have you tried?

Note that the vsync option in 86Box **only** affects the rendering of the emulated video to your screen. If the guest system does not have vsync enabled, you may / will still see screen tearing regardless of the 86box setting. This is not a problem with 86Box, but something that has to be addressed in the guest OS. 86Box is presenting the emulated screen to you - that screen may include the tearing from the guest OS.

Opening issues without providing the required information is not respectful of anyone's time. Please do not open any further issues unless you have, at a minimum, the issue template *plus* the above information.
