### ISSUE TITLE
Toshiba T1200 - Format gives only 360KB free space on a 720KB diskette

### ISSUE THREAD

**Issue by mfmcosta** [86Box/86Box#3737]
**Describe the bug**
The T1200 supports 3.5FDD 720KB.
A 720KB diskette can be read and written without problem, but if you format a diskette only 40 cylinders are recognized (360KB)

**To Reproduce**
1. Create a Toshiba T1200 with the NVR & HDD attached in the Toshiba T1200 zip
2. Start the machine
3. Create a new Floppy 720KB
4. Format the diskette as usual
5. See error

**Expected behavior**
The diskette have 720KB free space

**Screenshots**
![image](https://github.com/86Box/86Box/assets/136728257/7fe54db2-3048-4a16-87e6-8c799b8afe48)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 4.00 [build 5055]
 - Build information: 32-bits old dynarec

**Additional context**
This doesn't happens with the Toshiba T1000.

Using FDFMT.EXE from the Toshiba CE Diagnostics Diskette results in failure.
![image](https://github.com/86Box/86Box/assets/136728257/cfed9849-8a3c-4cff-913b-1dfcd55be890)

If you force the format:
![image](https://github.com/86Box/86Box/assets/136728257/6c2ff491-6f0f-4442-904a-35591f1c4f05)

[Toshiba T1200.zip](https://github.com/86Box/86Box/files/12859434/Toshiba.T1200.zip)
[Toshiba CE Diagnostics.zip](https://github.com/86Box/86Box/files/12859497/Toshiba.CE.Diagnostics.zip)

**Comment by OBattler** [comment]
Are you sure this version of FORMAT.COM supports 720k disks?

**Comment by mfmcosta** [comment]
It happens even with MS-DOS v6.22
![image](https://github.com/86Box/86Box/assets/136728257/a10f8d74-2bea-44a0-a1b2-2dec47ca1244)

Tryed with older builds (3.11 b4311) and the problems happens too.

**Comment by Fenix770** [comment]
It also happens on Toshiba DOS 3.30. Also if the image is created with 86box *and* is in IMG format it is not recognized as present.
The Toshiba DOS versions can manage the Hard-RAM (battery-backed) partitions, supported by the Toshiba T1x00 models.

![Toshiba T1200 720 FDD 2](https://github.com/86Box/86Box/assets/31600563/376ad644-cfb8-48d8-a593-5fb2985e29b1)

![Toshiba T1200 720 FDD 1](https://github.com/86Box/86Box/assets/31600563/19fa0338-dcae-4944-bda1-d68ac20f9587)

**Comment by OBattler** [comment]
I can not reproduce, with IMG file: 
![imagem](https://github.com/86Box/86Box/assets/10365853/d81d8682-901a-4738-b142-f49375639acb)

**Comment by OBattler** [comment]
NOTE: The floppy image must be created as 720k.

**Comment by Fenix770** [comment]
Hello!

Questions

1 Which DOS version are you using?
2. The parameters are required when formatting a 720k disk on a 1.44mb floppy, not when both floppy and drive are 720kb.

The only exception is when upgrading to a non-OEM DOS version. (For example, when upgrading Tandy DOS 3.20 on Tandy 1000 SX/TX to a generic Tandy DOS 3.30, in that case drivparm parameter was used in config.sys)

**Comment by Fenix770** [comment]
Also I found that if I use the drivparm parameter on config.sys, the FORMAT program is unable to format the disk with or without parameters.

![T1200 drivparm error](https://github.com/86Box/86Box/assets/31600563/25abb18d-d2de-4c9e-b837-154800345d4a)

D:0 is drive A and F:2 the 720kb format

**Comment by OBattler** [comment]
> Hello!
> 
> Questions
> 
> 1 Which DOS version are you using? 2. The parameters are required when formatting a 720k disk on a 1.44mb floppy, not when both floppy and drive are 720kb.
> 
> The only exception is when upgrading to a non-OEM DOS version. (For example, when upgrading Tandy DOS 3.20 on Tandy 1000 SX/TX to a generic Tandy DOS 3.30, in that case drivparm parameter was used in config.sys, The Tandy 1000 SX/TX had the same issue on MS-DOS 3.30)
> 
> PD: It says 40 cylinders so the FORMAT program is a little confused anyway, even if is formatted correctly.

I'm using the exact VM provided above, with the Toshiba MS-DOS 3.30. Also, FORMAT.COM sometimes does assume inappropriate parameters, in fact, these old versions basically tend to assume always 360k, there's even a thread on the PCem forum about FORMAT.COM woes on a regular PC/XT when trying to format a 160k or 180k disk.

Also, remember that this machine does not have an AT-compatible CMOS (NVR) where you'd have the floppy disk type, so FORMAT.COM may be unable to automatically detect it.

**Comment by Fenix770** [comment]
So, this may be a particularity of the Toshiba T1200 machine. For example, the Tandy 1000 SL/2 format correctly a 720kb floppy on a 720kb drive with the OEM DOS 3.30. The only exception is when formatting a 720kb floppy with a 1.44mb drive with an external controller.

**Comment by OBattler** [comment]
Well, I'm closing this as NOTABUG - even the SETUP program doesn't offer any floppy drive type configuration.
