### ISSUE TITLE
[BUG] Can't print files to PNG output under OS/2 2.0

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#374]
I believe that I found an issue when I try to print the OS/2 CONFIG.SYS file located on the root of drive C: using the Enhanced System Editor, the printer tries to print fine, but when it tries to do so moments from now, this error pop-ups up:

![Printer error](https://user-images.githubusercontent.com/32658796/56012725-9d002300-5ca2-11e9-9bf1-da082014b3f8.png)

The driver used is the Epson LQ-510 using the EPSON.DRV driver. In the 86Box settings under Ports (COM & LPT), "Serial Port 1: and "Parallel Port" are checked, "Serial Port 2" is not checked.

Under the LPT1 Device drop down box, I select Generic ESC/P Dot-Matrix.

I can print files under MS-DOS, Windows 3.0, Windows 3.1 and the Win-OS/2 subsystem. Just not under OS/2 2.0.

Can someone look into this issue to see why I can't print anything to a PNG file on the host under OS/2 2.0?

Thank you for your time.

**Comment by ppgrainbow** [comment]
I just learned that the ESC/P2 emulation might not be compatible with OS/2 2.1 or earlier. :(

**Comment by ppgrainbow** [comment]
Here's what I found about the printer emulation to PNG output when trying to print under OS/2 2.x. The drivers required for the printer fail to work properly under OS/2, because they expect it to be a interrupt-driven port.

One character gets printed and then it waits for the ACK interrupt that never arrives. When it doesn't, the error above returns.

More information will follow soon.

**Comment by OBattler** [comment]
I just committed a fix for printer IRQ's, waiting for test results to see if printing in OS/2 2.x now works.
