### ISSUE TITLE
IBM PS/ValuePoint P60: Wrong integrated graphics

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3740]
**Is your feature request related to a problem? Please describe.**
Yes, 86Box does not emulate the exact integrated graphics of the IBM PS/ValuePoint P60.

**Describe the solution you'd like**
The actual integrated graphics card of the IBM PS/ValuePoint P60 is the Tseng ET4000/w32. The 'integrated' graphics card of the IBM PS/ValuePoint P60 that 86Box emulates is the ATI Graphics Ultra Pro PCI.

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**Comment by TC1995** [comment]
Actually, it's the correct integrated graphics, since the main IBM P60 bios has that Mach32 (ATI Ultra Pro PCI) bios embedded in.

**Comment by OBattler** [comment]
Yeah, it's the 486-based PS/ValuePoint that has the Tseng. Therefore, closing with NOTABUG.
