### ISSUE TITLE
IBM PC 330 cannot boot

### ISSUE THREAD

**Issue by sasamiya-bios** [86Box/86Box#3743]
### What happened?

IBM PC 330 cannot boot, press F1/Esc has no response.
![Monitor_1_20231011-180658-403](https://github.com/86Box/86Box/assets/117635969/160089a5-a775-4743-afae-78cd3062d287)

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = pc330_6573
cpu_family = i486dx2_pc330
cpu_speed = 66666666
cpu_multi = 2
cpu_use_dynarec = 1
fpu_softfloat = 1
time_sync = local
fpu_type = internal
mem_size = 65536

[Video]
gfxcard = cl_gd5480_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Standard PS/2 Mouse]
buttons = 4
```

### Operating system

Windows 11

### 86Box version

v4.0 build 5066

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by mfmcosta** [comment]
It works for me
![image](https://github.com/86Box/86Box/assets/136728257/1f39b11b-6d69-4cb3-b354-1ca493d2ef2f)

The error 129 is a constant...
![image](https://github.com/86Box/86Box/assets/136728257/656d40db-3862-4546-94a7-5b6845014d29)
...that leads you to the BIOS setup page. Just "continue" and it works:
![image](https://github.com/86Box/86Box/assets/136728257/c9fe6887-c302-4578-bfdc-09a2dff92d2d)

My CFG...
[IBM_PC330.zip](https://github.com/86Box/86Box/files/12868633/IBM_PC330.zip)

**Comment by borisvolk117** [comment]
I use "slow" PIT mode and it works.

**Comment by cigaryno** [comment]
For me, I get POST error 129 when using the i486DX2 but not when using the i486DX4. I don't hqve the POST error 162 and F1 works.

**Comment by OBattler** [comment]
I just remembered there's a weird thing going on - the specific 486 DX2 models we give this machine tend to raise POST error 129 but if I force the normal 486 DX2 onto this machine, the error does not appear.

**Comment by OBattler** [comment]
I guess this can be closed now since I have rectified the 486 DX2 WB situation.
