### ISSUE TITLE
Request for add support for some few 80286 machines

### ISSUE THREAD

**Issue by guestuser0001** [86Box/86Box#3748]
**Is your feature request related to a problem? Please describe.**
No problems that went with this feature, I was asking for some few 80286 machines in 86Box.

**Describe the solution you'd like**

Since I've been using 86Box for months, I just wanted to add some few 80286 machines in 86Box.

There are 3 BIOS files in the zip file. Some 3 BIOS files include a readme file before you check at the BIOS files.
List of machines that needs to be added:
1. Sanyo MBC-25 PLUS
    Uses (Chips & Technologies 82C230 (Single Chip Model 30)) chipset,
    Internal video controller was an Western Digital WD90C00-JK.
    It has included an internal HDD controller BIOS.
    Maximum RAM of the Sanyo MBC-25 PLUS is 8MB.
    PS/2 mouse was supported
    Only has 3x 8-bit ISA slots, I think you can have support for 16-bit ISA cards.
    BIOS type: Phoenix Technologies
2. Schneider System 240
    Uses (Headland GC101,GC102 (12/16MHz PC/AT Compatible Chip Set)) chipset,
    It has an included internal video controller (low/high)
    Maximum RAM of the Schneider System 240 is 4MB.
    PS/2 mouse not supported
    BIOS type: Phoenix Technologies
3. Zenith Data Systems Z-248
    Uses (ZyMOS/Appian POACH) chipset,
    No internal video controller
    Maximum RAM of the Zenith Data Systems Z-248 is 6MB.
    PS/2 mouse not supported
    BIOS type: Zenith Data Systems
NOTE: BIOS files are found on TheRetroWeb.

BIOS files are here:
[80286 BIOS images (or files).zip](https://github.com/86Box/86Box/files/12879954/80286.BIOS.images.or.files.zip)
Before using the zip file, don't forget to use the readme file.
(If the BIOS files can be emulated, please let me know.)

**Additional context**
No additional context.

**Comment by borisvolk117** [comment]
Sanyo MBC-25 PLUS looks like a pseudo-XT for its function. Maybe Citygate D30 is a C&T 82C230 clone?

**Comment by OBattler** [comment]
Closing, added it to this list of requested machines: https://github.com/86Box/86Box/issues/3577 .
