### ISSUE TITLE
Is Japanese supported?

### ISSUE THREAD

**Issue by Ileca** [86Box/86Box#3749]
### What happened?

I am not talking about the interface.
When I tried to install windows 98, I got garbled text.
![Screenshot from 2023-10-12 16-26-00](https://github.com/86Box/86Box/assets/17970230/72f5af92-0c49-4542-b033-a45a463d359a)

I am sure the image is working as I just used it with KVM before I reached an infamous error for Ryzen owners. Tho I don't remember this blue screen.

### Configuration file

```ini
[General]
vid_renderer = qt_software
language = ja-JP

[Machine]
machine = zappa
cpu_family = pentium_p55c_od
cpu_speed = 166000000
cpu_multi = 2,5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
cpu = 12
mem_size = 131072

[Video]
gfxcard = trio64v2dx_pci
voodoo = 1

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = sb16
midi_device = fluidsynth

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_pci
cassette_mode = load

[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 2
texture_memory = 2
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[Microsoft Serial Mouse]
port = 0
buttons = 4

[FluidSynth]
sound_font = /path/soundfont/Roland_SC-88.sf2
output_gain = 100
chorus = 1
chorus_voices = 3
chorus_level = 20
chorus_speed = 30
chorus_depth = 80
chorus_waveform = 0
reverb = 1
reverb_room_size = 20
reverb_damping = 0
reverb_width = 5
reverb_level = 90
interpolation = 2

[Hard disks]
hdd_01_parameters = 63, 16, 10158, 0, ide
hdd_01_fn = /path/storage_5G
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
fdd_01_fn = /path/Windows 98 Second Edition Boot.img
cdrom_01_host_drive = 200
cdrom_01_image_path = /path/win98se_jp.iso
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Ubuntu

### CPU

AMD Ryzen 5 5600G

### 86Box version

v4.0 build 5000

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by cold-brewed** [comment]
Yes. Note that this is dependent upon the operating system in use, not 86box itself.

Here are some examples from Windows 3.11 with DOS/V:

![Monitor_1_20230424-145058-291291](https://github.com/86Box/86Box/assets/47337035/e58a6d08-b12f-414a-811a-324869c67971)
![Monitor_1_20230424-200010-35035](https://github.com/86Box/86Box/assets/47337035/5562c0ea-4c52-449f-a884-9e2b4800dba3)

**Comment by Ileca** [comment]
Ok. I followed a different video tuto about 86Box instead of KVM and the instructions were different and got me this blue screen with garbled text for some reason. I confirm Japanese is supported now that I installed the OS properly.

Probably fastest issue solved ever.
Sorry for the waste of time.

**Comment by OBattler** [comment]
Once I have created Windows 95 boot disks for all languages, I'm going to share those, then proceed to 95 OSR 2.x, 98 FE, and then, finally, 98 SE. Then the above Windows 95 Setup should look properly as the Japanese boot disk would have the appropriate display drivers.
