### ISSUE TITLE
[BUG] CH Flightstick Pro issues

### ISSUE THREAD

**Issue by SomeRandomGuyIdk** [86Box/86Box#375]
Tested with PCem, works there
Joystick used: Logitech Extreme 3D Pro

1. The stick doesn't center properly in the Win95 joystick calibratoin, it centers slightly to the bottom right
2. The throttle doesn't work. I selected the slider axis for it, but it just seems to use the X axis instead

**Comment by OBattler** [comment]
I have marked this as help wanted and future version because I don't have a joystick, so I can't really test this.

**Comment by horkthane** [comment]
I believe the joystick work I did recently fixed the slider issue you were having.  I tested it with the exact same joystick.

**Comment by OBattler** [comment]
Well, then I guess this can be closed.
