### ISSUE TITLE
Add support for the Commodore C286-LT laptop computer in 86Box

### ISSUE THREAD

**Issue by guestuser0001** [86Box/86Box#3751]
**Is your feature request related to a problem? Please describe.**
No problems.

**Describe the solution you'd like**
Add support for Commodore C286-LT computer on 86Box

**Additional context**

Since I only seen 1 Commodore 286 machine in 86Box, I just want to add support for the Commodore C286-LT computer in 86Box.

BIOS/ZIP file (including a readme file):
[Commodore C286-LT ROMs.zip](https://github.com/86Box/86Box/files/12892517/Commodore.C286-LT.ROMs.zip)
(NOTE): Some ZIP BIOS files include a readme file before you check the BIOS ROMs.

Laptop computer information can be found on 2 websites:
https://www.c64-wiki.de/wiki/Commodore-Laptop_C286LT
https://oldcrap.org/2020/02/24/commodore-c286-lt/

**Comment by OBattler** [comment]
Closing, added it to this list of requested machines: https://github.com/86Box/86Box/issues/3577 .
