### ISSUE TITLE
Windows 2000 text setup fails on AX59 Pro

### ISSUE THREAD

**Issue by igbecerra** [86Box/86Box#3759]
### What happened?

Trying to boot the Windows 2000 SP4 english retail text setup phase from the ISO on the AOpen AX59 Pro motherboard fails with:
`*** STOP: 0x0000007B (0xFDC63848,0xC0000034,0x00000000,0x00000000)
INACCESSIBLE_BOOT_DEVICE`
during the "Setup is starting Windows 2000" phase.

The expected result with this configuration would be that the setup advances to the next phases, then complains that this computer doesn't have enough RAM.

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = ax59pro
cpu_family = winchip
cpu_speed = 100000000
cpu_multi = 1,5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
cpu_manufacturer = 1
cpu = 2
mem_size = 16384

[Video]
gfxcard = mach64gx_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:0
cdrom_01_host_drive = 200
cdrom_01_image_path = /somepath/EN_WIN2000_PRO_SP4.ISO
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Linux x86_64 (EndeavourOS)

### CPU

Intel G860 (Sandy Bridge 2C2T)

### 86Box version

v4.0 build 5096 AppImage

### Build architecture

Linux - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

This config is my attempt at a minimal reproduction test case.
Same config but with any other SS7 motherboard gives the expected result.

Also tested:
* Changing IDE controller to Internal
* Dynarec on/off
* Different CPUs
* Different GPUs
* Adding a hard drive
* Changing renderers
* x86 official release build v5000

BTW, I marked debug build because I'm using the Jenkins AppImage, not sure if that counts as Debug build or not...

**Comment by dhrdlicka** [comment]
> BTW, I marked debug build because I'm using the Jenkins AppImage, not sure if that counts as Debug build or not...

The AppImage is not a debug build.

**Comment by OBattler** [comment]
Closing this with NOTABUG - the BIOS has a bad ACPI table, press F7 to tell Windows 2000 Setup to load the non-ACPI HAL.
