### ISSUE TITLE
Tandy 1000 HX 256K hangs on start

### ISSUE THREAD

**Issue by Tape-Worm** [86Box/86Box#3767]
### What happened?

When I started up a new Tandy 1000 HX machine with a default memory size of 256KB, it just hangs at the "Memory Size = 256k" portion of the boot process.

When I change the memory size to 384KB or higher, it boots just fine.

### Configuration file

```ini
[Machine]
machine = tandy1000hx
cpu_family = 8088_europc
cpu_speed = 7159092
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = disabled
fpu_softfloat = 0
cpu = 1
mem_size = 256

[Video]
video_fullscreen_scale_maximized = 1
gfxcard = internal

[Input devices]
mouse_type = none

[Storage controllers]
hdc = none

[Floppy and CD-ROM drives]
fdd_01_type = 35_2dd
fdd_01_image_history_01 =
fdd_02_type = none
fdd_01_fn = 

[WinBox]
window_fixed_res = 960x720

[General]
video_filter_method = 0
vid_cga_contrast = 1
confirm_exit = 0
language = system
vid_renderer = qt_vulkan
video_fullscreen_scale = 3
scale = 3
confirm_reset = 0
confirm_save = 0
enable_overscan = 1
window_remember = 1

[Sound]
fm_driver = nuked

[Monitor #1]
window_coordinates = 735, 259, 1312, 932

[Monitor #2]
window_coordinates = 0, 0, 0, 0

[Tandy 1000 HX]
display_type = 0

[Ports (COM & LPT)]
serial2_enabled = 0
```

### Operating system

Windows 11

### CPU

AMD Ryzen 7950x

### 86Box version

4.0.2 Build 5116

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Manager auto-update

### Additional context

This is using the v4.0.2 Build 5116 of the emulator, I'm running it through a program called WinBox which pulls down the latest Jenkins build.  As of this writing, this version was current.

I tried PCEm and when I set it to 256KB for the machine, it booted with 384k... almost like it forced it to 384.

**Comment by OBattler** [comment]
This means we have the wrong minimum RAM amount set for that machine.

**Comment by EriolGaurhoth** [comment]
I know this is a "closed issue", but _shouldn't_ the Tandy 1000 HX be able to boot properly with just 256KB of RAM? Every piece of documentation I've ever found on this machine and every Radio Shack catalog entry from the time states that this came stock with 256KB so the fact that this cannot boot without 384KB of RAM is...inaccurate. Perhaps there's some issue with the ROM, maybe a newer variant that needed a full 384KB?

**Comment by Dudejo** [comment]
To be exact, the Tandy 1000 HX fails to boot with both 256kb AND 512kb, specifically. The 384kb and 640kb loadouts work just fine.

**Comment by EriolGaurhoth** [comment]
> To be exact, the Tandy 1000 HX fails to boot with both 256kb AND 512kb, specifically. The 384kb and 640kb loadouts work just fine.

Do you know why this is? Because an original HX absolutely boots with 256 (never tested it with 512).

**Comment by jznomoney** [comment]
I had a tandy 1000 hx back in the day.  It came with 256kb, and I know it boots with 256kb.  I had done the upgrade as well to make it 640kb.  But I know it originally came with 256kb.  I had to beg my mother to get me the upgrade module lol.

**Comment by OBattler** [comment]
The problem is that the technical reference is unclear about some aspects of the RAM mapping handling, so even MartyPC has run into the same problem.
