### ISSUE TITLE
Amstrad MegaPC machine not entering BIOS setup

### ISSUE THREAD

**Issue by guestuser0001** [86Box/86Box#3775]
### What happened?

When I'm first booting the Amstrad MegaPC machine while the memory/RAM test is complete, it hangs with the (F1 to continue, F2 to run SETUP) screen, after a hard-reset, skipping the memory/RAM test, and pressed F2 when it says (System CMOS checksum bad - Run SETUP), I was in the BIOS setup password screen. This issue does not occurred in PCem v17.

(NOTE: I updated my 86Box to (build 5125)

### Configuration file

```ini
[General]
vid_renderer = qt_software
dpi_scale = 0
confirm_exit = 0

[Machine]
machine = megapc
cpu_family = cx486srx2
cpu_speed = 50000000
cpu_multi = 2
cpu_use_dynarec = 0
fpu_softfloat = 1
time_sync = local
fpu_type = 387
cpu_manufacturer = 2
cpu = 5
mem_size = 16384

[Video]
gfxcard = internal

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
midi_device = system_midi
mpu401_standalone = 1

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = xtide_at_386
cassette_mode = load

[CGA]
display_type = 0
composite_type = 1
rgb_type = 0
snow_enabled = 1

[Other peripherals]
postcard_enabled = 1

[3dfx Voodoo3 2000]
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
recompiler = 1

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 35_2hd

[Standard PS/2 Mouse]
buttons = 2
```

### Operating system

Windows 11 (home version)

### CPU

AMD Ryzen 5 5600H

### 86Box version

v4.02 build 5125

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Screenshots:

![Amstrad MegaPC (after the memory test is complete)](https://github.com/86Box/86Box/assets/147709293/f6b59f2e-4908-439b-85b1-7e76a781f5f0)
![Amstrad MegaPC (hangs with this screen after pressing F2)](https://github.com/86Box/86Box/assets/147709293/eb714f7b-2586-478b-9d91-785e2abf7115)
![Amstrad MegaPC (after a hard-reset) (1)](https://github.com/86Box/86Box/assets/147709293/7664058b-e822-42bf-946b-320da91159db)
![Amstrad MegaPC (after a hard-reset) (2)](https://github.com/86Box/86Box/assets/147709293/b04d25ca-eb03-43da-b7e5-878a22a67ea8)
![Amstrad MegaPC (after entering the BIOS setup)](https://github.com/86Box/86Box/assets/147709293/a0e549c7-3a00-4793-8945-5b8fd44df9a7)
![After entering the BIOS setup, I granted with this password screen](https://github.com/86Box/86Box/assets/147709293/35355b81-cbbe-4f51-8b84-f36bde6c68ba)

Configuration/NVR image/Screenshots ZIP file:
[Amstrad MegaPC files.zip](https://github.com/86Box/86Box/files/13059585/Amstrad.MegaPC.files.zip)
Screenshots went included in the ZIP file, some 1 NVR image and configuration files are included.

If this bug can be fixed, please let me know in the comments.

**Comment by OBattler** [comment]
Known issue. Being resolved as part of this bigger goal: https://github.com/86Box/86Box/issues/238 (finishing the chipset used by this machine as that's the real issue).
