### ISSUE TITLE
Zenith Data Systems Z-159 CPU clock problem

### ISSUE THREAD

**Issue by guestuser0001** [86Box/86Box#3776]
### What happened?

When I was booting up the Zenith Data Systems, got passed in the XTIDE screen and pressed the (CTRL+ALT+DEL) button (or soft reset), I just got an error saying (ERROR: +++ Timer Interrupt failure! +++) when doing a soft reset. (Only at 8/10MHZ CPU clocks)

(NOTE: I updated my 86Box to (build 5127), depends on the Jenkins website.

### Configuration file

```ini
[General]
vid_renderer = qt_software
dpi_scale = 0
confirm_exit = 0

[Machine]
machine = zdsz159
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 1
time_sync = local
fpu_type = 8087
mem_size = 640

[Video]
gfxcard = cga

[Input devices]
mouse_type = msbus

[Sound]
fm_driver = nuked
midi_device = system_midi
mpu401_standalone = 1

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = xtide
cassette_mode = load

[ATI Mach32 (ISA)]
memory = 1024

[Floppy and CD-ROM drives]
fdd_01_type = 35_2dd
fdd_02_type = 35_2dd

[Other peripherals]
postcard_enabled = 1

[ATI EGA Wonder 800+]
memory = 256
monitor_type = 9
```

### Operating system

Windows 11 (home version)

### CPU

AMD Ryzen 5 5600H

### 86Box version

v4.02 build 5127

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Screenshots:

![Zenith Data Systems Z-159 after starting the machine](https://github.com/86Box/86Box/assets/147709293/35eeb764-5d3f-498d-8ed0-9413afbd9538)
![Zenith Data Systems Z-159 after XTIDE screen](https://github.com/86Box/86Box/assets/147709293/558c137b-90a2-46fc-b016-a6b78d2db5f5)
After the XTIDE screen appeared...
![Zenith Data Systems Z-159 after a soft reset](https://github.com/86Box/86Box/assets/147709293/cb78b227-bddb-4463-8d12-db1e82ad0770)
I granted with this screen:

Configuration/Screenshots ZIP file:
[Zenith Data Systems Z-159 files.zip](https://github.com/86Box/86Box/files/13059975/Zenith.Data.Systems.Z-159.files.zip)
Screenshots went included in the ZIP file, some 1 NVR image and configuration files are included.

If this bug can be fixed, please let me know in the comments.
And if this bug is NOTABUG, please close this issue as not planned, since it booted at 8/10MHz CPU clocks. while 4.77/7.16MHz CPU clocks doesn't show up the timer interrupt failure error.

**Comment by borisvolk117** [comment]
I found some thread that Z-159's CPU frequency is 4.77/8 MHz.

**Comment by guestuser0001** [comment]
It runs fine at 8MHz and boots off to XTIDE, but after a soft reset (or CTRL+ALT+DEL), it still shows the same problem.
![Zenith Data Systems Z-159 at 8MHz](https://github.com/86Box/86Box/assets/147709293/d8c84091-4979-41b4-8b40-ab8329a11076)
This is how the Z-159 machine runs at 8MHz:

Plus, the Zenith Data Systems Z-159 machine (maximum RAM) was 1.25MB, according to TheRetroWeb:
https://theretroweb.com/motherboards/s/zenith-data-syst-z-159
And the screenshot:
![image](https://github.com/86Box/86Box/assets/147709293/76d5883f-b0c2-4301-b0c7-f63549960442)

**Comment by OBattler** [comment]
Try changing the PIT to fast and see if this still occurrs.

**Comment by guestuser0001** [comment]
> Try changing the PIT to fast and see if this still occurrs.

Nope, I did a soft reset, change the PIT mode to FAST, then the problem did not occurred.
Screenshot:
![Zenith Data Systems Z-159 (8MHz) in (FAST PIT mode)](https://github.com/86Box/86Box/assets/147709293/9332123a-d456-401e-a52a-c60aef8fd6b9)
(NOTE: I'm on a different computer, so this is how the screenshot look like):

**Comment by guestuser0001** [comment]
Maybe this bug needs to be closed.

**Comment by guestuser0001** [comment]
Upon booting the Z-159 machine to 12MHz, it doesn't show the timer interrupt failure error after doing a soft reset multiple times.
