### ISSUE TITLE
[BUG] Resizable Window issues

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#381]
I would like to report a couple things when it comes to making a window in 86Box resizable.

1. When I make the 86Box window resizable (select View > Resizable Window) from fixed, the menu options (Action, View, Tools and Help) appear to be overlapped by the window itself, thus messing up the menu.

This happens upon start up as well. Here's a screenshot for clarification:

![bug1](https://user-images.githubusercontent.com/32658796/56856314-b6dd6f00-690c-11e9-92d8-1a2a939060fb.png)

2. When the Resizable Window feature is enabled (selected under View > Resizable Windows), when I try to resize the 86Box window, 86Box crashes. Here's a screenshot for proof:

![bug2](https://user-images.githubusercontent.com/32658796/56856317-c3fa5e00-690c-11e9-98bf-c37b07c09262.png)

The crashing bug can only be produced when I have set the render to SDL and that I resize the window. I found no problems with resizing the window when the DirectDraw and Direct3D 9 render is enabled.

Please consider fixing the bugs that I provided. Thanks. :)

Until the bug is fixed, I would avoid using the SDL render to resize the window.

**Comment by ppgrainbow** [comment]
The SDL render resize bug has been fixed and I'm waiting for it to be ported to the Jenkins build. Until then, I'll leave this bug opne.

**Comment by driver1998** [comment]
Issue 1 is related to https://github.com/86Box/86Box/commit/2da25c0a29aa574a2d1ea752c6ef844758de5404

This is for fixing a window-border related bug in clang/llvm-mingw (and mingw 6.0 I guess), where the mouse cursor can get out of the window when it is locked.
But it does cause the problem you mentioned.
