### ISSUE TITLE
Tseng Labs ET4000/w32p Rev. B (VideoMagic) PCI video card problem on some few Socket 7 motherboards

### ISSUE THREAD

**Issue by guestuser0001** [86Box/86Box#3813]
### What happened?

In 86Box, if you select the Tseng Labs ET4000/w32p Rev. B (VideoMagic) PCI video card option in any Socket 7 machine, it has some video text problems (the text is showing in the right), (except on the splash screen) after starting up the machine with some Intel AMI BIOSes and a few other Phoenix BIOS boards.

List of Socket 7 (Dual Voltage) machines that I tested with the Tseng Labs ET4000/w32p Rev. B (VideoMagic) PCI video card:
(Only 1 AwardBIOS board was tested in this bug)

Acer V35N:
(gets no display after startup, so no screenshot)

Compaq Presario 2240/4500:
![Monitor_1_20231108-145531-212](https://github.com/86Box/86Box/assets/147709293/c2ff561c-5bf5-429b-a6c1-65eebe062ba9)
![Monitor_1_20231108-145543-261](https://github.com/86Box/86Box/assets/147709293/2e3b348c-d3a7-48d0-aba3-02e1b103f8cc)

HP Brio 80xx:
![Monitor_1_20231108-145126-306](https://github.com/86Box/86Box/assets/147709293/08a08ce5-b1b4-407a-9d1a-9c50bb733734)

Micronics M7S-Hi:
![Monitor_1_20231108-144854-229](https://github.com/86Box/86Box/assets/147709293/38c77f24-6768-4838-8053-7d7e9dd9267f)

Intel CU430HX:
![Monitor_1_20231108-144814-806](https://github.com/86Box/86Box/assets/147709293/6cff16f5-f380-4140-92b8-6b988519d420)

Intel TC430HX:
![Monitor_1_20231108-144656-572](https://github.com/86Box/86Box/assets/147709293/d83aa88e-8f80-42a0-aaca-a0949225bc85)

PC Partner MB540N:
![Monitor_1_20231108-145631-728](https://github.com/86Box/86Box/assets/147709293/a1efa6be-0ce5-4a47-af5a-4d33e4fae182)

Sony Vaio PCV-90:
![Monitor_1_20231108-145032-384](https://github.com/86Box/86Box/assets/147709293/9958566d-42d9-45b1-ba0f-84bbbdb12b01)

Toshiba Equium 5200D:
![Monitor_1_20231108-145335-758](https://github.com/86Box/86Box/assets/147709293/a66c5004-ab70-46de-b2b1-22df2d47ba47)

Toshiba Infinia 7200:
![Monitor_1_20231108-145240-650](https://github.com/86Box/86Box/assets/147709293/46960e59-60ec-454d-b942-449b6020fd39)

### Configuration file

```ini
[General]
vid_renderer = qt_software
dpi_scale = 0
video_filter_method = 0
confirm_exit = 0

[Machine]
machine = mb540n
cpu_family = pentium_p54c
cpu_speed = 200000000
cpu_multi = 3
cpu_use_dynarec = 1
fpu_softfloat = 1
time_sync = local
fpu_type = internal
pit_mode = 1
cpu = 9
mem_size = 131072

[Video]
gfxcard = et4000w32p_videomagic_revb_pci

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Other peripherals]
postcard_enabled = 1

[Ports (COM & LPT)]
lpt1_device = postscript

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 35_2hd

[Tseng Labs ET4000/w32p Rev. B PCI (VideoMagic)]
memory = 1
```

### Operating system

Windows 11 (home version)

### CPU

Intel Core i5-11300H

### 86Box version

v4.02 build ver. 5186

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

No additional context, no configuration files yet.

**Comment by OBattler** [comment]
Known bug - skew problem, we already have an issue about skew problems on these cards, so I'm closing this as a duplicate.
