### ISSUE TITLE
Philips P3105/NMS9100 and P3120 detects only 640KB memory when using 768KB of memory in the machine settings

### ISSUE THREAD

**Issue by guestuser0001** [86Box/86Box#3817]
### What happened?

In 86Box, the 2 Philips 8088 machines, the P3105/NMS9100 and the P3120 detects only 640KB system memory when using the 768KB option in the machine settings:
![image](https://github.com/86Box/86Box/assets/147709293/24401202-3257-46ed-8c78-7d1e0c1c59c5)
![image](https://github.com/86Box/86Box/assets/147709293/90f45528-c40f-471a-aba3-17aa24d8c19c)
This is how the system memory detects in the BIOS startup screens (the P3105/NMS9100 and the P3120):
![Philips P3105_NMS9100](https://github.com/86Box/86Box/assets/147709293/fbacff46-d4a3-4e86-b77b-a73314a62c9e)
![Philips P3120](https://github.com/86Box/86Box/assets/147709293/d52e9ba8-45b3-4c99-b7c0-327aa048bb5f)
The configuration file was here:
[86Box Configuration Files.zip](https://github.com/86Box/86Box/files/13315930/86Box.Configuration.Files.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
dpi_scale = 0
confirm_exit = 0

[Machine]
machine = p3120
cpu_family = 8088
cpu_speed = 8000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 1
time_sync = local
fpu_type = 8087
mem_size = 768

[Video]
gfxcard = cga

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked
midi_device = system_midi
mpu401_standalone = 1

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_02_type = 35_2dd
fdd_01_image_history_01 = Floppy Diskette drives/Microsoft MS-DOS 6.22 Plus Enhanced Tools (3.5)/Disk1.img

[Other peripherals]
postcard_enabled = 1

[CGA]
display_type = 0
composite_type = 1
rgb_type = 0
snow_enabled = 1

[Ports (COM & LPT)]
lpt1_device = text_prt
```

### Operating system

Windows 11 (home version) (version 22H2, OS build 22621.2428)

### CPU

Intel Core i5-11300H

### 86Box version

v4.02 build ver. 5194

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

No additional context, the 86Box configuration files were at the top.

**Comment by borisvolk117** [comment]
I remember these Philips machines only detect 640KB, the other 128KB needs their special driver to become EMS memory.

**Comment by OBattler** [comment]
Yeah, this is NOTABUG.

**Comment by borisvolk117** [comment]
> Yeah, this is NOTABUG.

Oh, my mistake. The problem is Philips' unknown menory mechanism, like https://github.com/86Box/86Box/issues/1549#issue-942561943
