### ISSUE TITLE
Bubble Bobble Hercules issues

### ISSUE THREAD

**Issue by daviunic** [86Box/86Box#382]
I tried the Bubble Bobble with DosBox-X.

The game seems to work in Hercules mode after loading BBSIMCGA.COM.
I found an strange behevior on the game.
I have three differents copies of the game that are almost identical but:

I  found that one copy of the game works but has no text and no score/credit during game play, and the other works ok without any issue. 

On 86box both copies of the game has the text and the issue of the bubble that does not blast.

Here I attach the copy that worked in Dosbox-X. ( I created it with Winimage)

[bubble bobble herc.zip](https://github.com/86Box/86Box/files/2849228/bubble.bobble.herc.zip)

PD: About the CGA detection under CGA emulation: 
I also tried arkanoid 1, which has no native Hercules support, with CGA emulators SIMCGA, MONO and Magic Key. The game refuses to work saying a CGA/EGA/VGA or Tandy is required.
I suppose that the game, if has a detection routine, must recognize the Hercules as CGA when emulation is enabled.

For example: Jetsons (1990) supports CGA and EGA graphics.On Hercules it reports "Card not active!" or simply return to dos prompt unless simcga is loaded first.

_Originally posted by @Fenix770 in https://github.com/86Box/86Box/issues/355#issuecomment-462160228_

**Comment by OBattler** [comment]
I really don't know why it's not working. I tried to make the Hercules emulation as close as possible to DOSBox-X, and I can't seem to make it work. I have no idea what made it work on the emulated CGA.

**Comment by OBattler** [comment]
It indeed works on the CGA. Could it be the IBM XT BIOS not doing something right on the Hercules? The one person that reported it working on real hardware, used an IBM AT it seems. Let me try that.

**Comment by OBattler** [comment]
OK, same problem on the AT. At this point, I have no idea.

**Comment by OBattler** [comment]
I'm going to resume working on this after v2.00.

**Comment by Dizzy611** [comment]
Confirmed at least part of this bug is still a thing on 3.4.1 (build 3738, Windows x64, Old Dynarec build with dynarec off)
Specifically, for Bubble Bobble, the graphics and text seem to render fine in SIMCGA but the Bubble never blasts at the beginning of the stage.

**Comment by Fenix770** [comment]
I think I posted a similar issue. This problem happens on Tandy video mode on Tandy 1000 machines and with Hercules emulation using BBSIMCGA or MONO. I'm not sure if it is a video bug or related to 808x CPU emulation.
This worked fine on a real XT class machine that I had back in the day, and saw some screenshots of the game on Vogoons of the people with XT machines and Hercules card and the game seems to work.

The problem of the bubble never blasting happens of fast CPUs, 386 or faster even with VGA.
I found a pirate version with a BBFAST.COM file that solves the problem on 386/33 but not 486. 
I tested this game on real 486 DX/4 100 Mhz back in 1997 and the game has this issue.

**Comment by OBattler** [comment]
My hypothesis is that BBSIMCGA loops on a port, probably port 3BAh (status), and fails if it does not detect the required change. This can happen either if the CPU is too fast (the loop finishes before the change happens) or the required change happens too fast (so that BBSIMCGA pretty much sees no change).

**Comment by OBattler** [comment]
This is now fixed.
