### ISSUE TITLE
Сheckbox "Show status icons in fullscreen" is not saved when exiting 86Box and then starting again 86Box

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#3824]
### What happened?

1. At the same time, some artifacts are created in the 86Box.cfg file in the words of this setting, and the number of these settings lines increases each time in the 86Box.cfg file when the Show status icons in fullscreen checkbox is checked:

[8# General]
status_icons_fullscreen = 1

[é General]
status_icons_fullscreen = 1

[ØÞ General]
status_icons_fullscreen = 1

2. Status icons in full screen mode are only displayed on the QT Software render. In OpenGL 3.0, Vulkan, Direct3D 9 renderers, status icons are not displayed in full screen mode. In the Qt (OpenGL) renderer in full-screen mode, there are artifacts in the form of screen shift when the "Show status icons in fullscreen" option is enabled.

### Configuration file

```ini
[Machine]
machine = ibmpcjr
cpu_use_dynarec = 0
time_sync = local
cpu_enable_fpu = 1
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
fpu_type = 8087
fpu_softfloat = 0
mem_size = 640

[Video]
video_fullscreen_scale_maximized = 1
gfxcard = internal

[Input devices]
mouse_type = msserial
joystick_type = 2axis_2button
joystick_0_nr = 0
joystick_1_nr = 0
joystick_0_axis_0 = 1
joystick_0_axis_1 = 0
joystick_0_button_0 = 0
joystick_0_button_1 = 1
joystick_0_button_2 = 0
joystick_0_button_3 = 0
joystick_0_pov_0 = 0, 0

[Sound]
midi_device = fluidsynth
sndcard = sbprov2
fm_driver = nuked

[Other peripherals]
postcard_enabled = 1
hdc = st506_xt_dtc5150x

[General]
confirm_exit = 0
confirm_reset = 0
confirm_save = 0
vid_resize = 1
video_fullscreen_first = 0
window_remember = 1
video_gl_vsync = 1
iconset = legacy
vid_renderer = qt_opengl
do_auto_pause = 1
vid_cga_contrast = 1
language = system

[CGA]
display_type = 0
composite_type = 1
rgb_type = 3
snow_enabled = 0

[Microsoft Serial Mouse]
port = 0
buttons = 4

[Floppy and CD-ROM drives]
fdd_01_fn = E:/Games/Games1/86Box/images/Floppy 720 KB DOS 3 Games 3.img

[IBM PCjr]
display_type = 0

[Sound Blaster Pro v2]
base = 0220
irq = 5
dma = 1
opl = 1
receive_input = 1

[Storage controllers]
hdc = none

[Monitor #1]
window_coordinates = 412, 31, 1736, 1292

[Monitor #2]
window_coordinates = 412, 31, 1736, 1292

[8#General]
status_icons_fullscreen = 1

[é General]
status_icons_fullscreen = 1

[ØÞGeneral]
status_icons_fullscreen = 1
```

### Operating system

Windows 10 Pro x64 v22H2

### CPU

Core i9-10900K

### 86Box version

v4.1 Build 5206

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
I have just tested it and it's fixed.

**Comment by maximus105** [comment]
The second bug is not fixed.

**Comment by OBattler** [comment]
I'm aware of it.
