### ISSUE TITLE
Protected mode violation error on 286 machines with Windows 3.0 and 3.0a

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3827]
### What happened?

I installed Windows 3.0 and then 3.0a with both versions I found a strange error about a protected mode violation. 
Windows 3.0a does not works in real mode either. Also I tested EGA and VGA video modes and several ISA 286 machines
Windows 3.0 starts but some apps may have strange issues about a protection violation.

This screen is from EGA black and white configuration but affects other video modes too.
![Monitor_1_20231114-191224-041](https://github.com/86Box/86Box/assets/31600563/e3bbba0a-4b44-4b27-ae04-94aa84cd1046)
![Monitor_1_20231111-230226-787](https://github.com/86Box/86Box/assets/31600563/28f434bb-4818-408a-9fc1-38ff71eb96fd)

Here is the HDD a file
[Hyundai 286C.zip](https://github.com/86Box/86Box/files/13357878/Hyundai.286C.zip)

### Configuration file

```ini
[Paradise PVGA1A]
memory = 512

[IBM PC/AT Memory Expansion #1]
size = 1024
start = 1024

[General]
vid_renderer = qt_software
rctrl_is_lalt = 1
vid_resize = 1
dpi_scale = 0
video_fullscreen_scale = 2
video_gl_shader = 
window_remember = 1
video_gl_vsync = 1

[Machine]
machine = ibmatquadtel
cpu_family = 286
cpu_speed = 8000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu = 1
mem_size = 2048

[Video]
gfxcard = ega
video_fullscreen_scale_maximized = 1

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = adlib

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_fn = 
hdd_01_speed = 1989_3500rpm
hdd_01_vhd_blocksize = 1024
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd

[Everex EV-159 RAM 3000 Deluxe #1]
size = 2048
start = 0
length = 0
width = 1
speed = 1
ems = 1
base = 0258

[SuperEGA]
memory = 256
monitor_type = 9

[Sound Blaster v1.0]
base = 0220
irq = 7
dma = 1
opl = 1
receive_input = 1

[Monitor #1]
window_coordinates = 0, 23, 1366, 636
window_maximized = 1

[Monitor #2]
window_coordinates = 0, 0, 0, 0

[EGA]
memory = 256
monitor_type = 9
```

### Operating system

Windows 10

### CPU

i5 4210U

### 86Box version

4.1.0.5206

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
SuperEGA is a bit broken.

**Comment by TC1995** [comment]
Wait, are you able to run Win3.0 on a standard EGA color configuration (not b&w)?

**Comment by Fenix770** [comment]
But, I suspect is related to 286 protected mode emulaton, since it happens on VGA video mode too.

**Comment by Fenix770** [comment]
I tried to install Win 3.0a on the ADI 386 SX/20 and color EGA it have the same issue.

**Comment by Fenix770** [comment]
PD: The install program of Win 3.0a exists to DOS when reach the graphical part on ADI 386 SX/20 with AVGA-1 (Acumos).

![Monitor_1_20231114-213804-038](https://github.com/86Box/86Box/assets/31600563/8c4a5d85-947c-4bae-8177-968fc565cff4)

**Comment by Fenix770** [comment]
PD: Same on build 5979

**Comment by Fenix770** [comment]
I installed Windows 3.0a on ADI 386 SX, and Windows freezes at the startup screen in standard (Win /S) and enhanced modes (WIN /3) only real modes works I tried the standard VGA video mode with different VGA video cards. I happen since at least the build 4.0.0.4640 Win x32
[Hyundai 286C.zip](https://github.com/86Box/86Box/files/13369778/Hyundai.286C.zip)

**Comment by Fenix770** [comment]
I just tested other machines and even the 486 SX is affected by this bug.

**Comment by TC1995** [comment]
for the AVGA one, I think it's a win3.1 only driver.

**Comment by TC1995** [comment]
I think the EGA B/W driver requires at least 2MB of ram.

**Comment by OBattler** [comment]
> I installed Windows 3.0a on ADI 386 SX, and Windows freezes at the startup screen in standard (Win /S) and enhanced modes (WIN /3) only real modes works I tried the standard VGA video mode with different VGA video cards. It happen since at least the build 4.0.0.4640 Win x32 [Hyundai 286C.zip](https://github.com/86Box/86Box/files/13369778/Hyundai.286C.zip)

That can't possibly be the build that introduced it because there's no CPU changes in that build.

**Comment by Fenix770** [comment]
PD: I found some interesting!. Windows 3.0 (non "a") does not throw the "unrecoverable application error" on MS-DOS 4.00.
The problem seems to be with the MS-DOS version 5.0.  I found is also affected an old VM I have with SCAT 286, MS-DOS 5.0 and QRAM 2.02. Maybe it is related to the management of the HMA (fist 64kb of extended memory)

**Comment by Fenix770** [comment]
I installed MS-DOS 4.01 on Shuttle 386 SX/20 with MS-DOS 4.01 and monochrome EGA card and monitor an works just fine. The issue happens on MS-DOS 5.0 but I don't know why.

![DOS 4 01 Win 3 0a](https://github.com/86Box/86Box/assets/31600563/f70c6dfe-bf42-461f-bb53-16fbcac55fec)

**Comment by Fenix770** [comment]
I installed MS-DOS 5.0 upgrade version, it seems to work fine. The files are dated as April 1991. The version that has issues is dated as February, 1992.

![MS-DOS 5 0 upgrade](https://github.com/86Box/86Box/assets/31600563/85e581e0-7aec-452b-a78a-835614e8f7d9)
![MS-DOs 5 0 2-92 version](https://github.com/86Box/86Box/assets/31600563/6bd862fc-4c95-43c5-9e45-6ca7392f4c7c)

**Comment by OBattler** [comment]
Link to that February 1992 version?

**Comment by OBattler** [comment]
Try using the HIMEM.SYS that comes with the DOS version instead of the one from 1990.

**Comment by Fenix770** [comment]
I already tried, the version  of DOS 5.0 released in 1992 includes a HIMEM.SYS  dated as September, 1991.

**Comment by OBattler** [comment]
Can you link me to that february 1992 version?

And can you upload your VM that uses the normal April 1991 MS-DOS 5.00?

**Comment by Fenix770** [comment]
Here is the 1992 version of MS-DOS 5.0
[MS-DOS 5.00.ver.5.00.02.English.zip](https://github.com/86Box/86Box/files/13401546/MS-DOS.5.00.ver.5.00.02.English.zip)

The July,1991 version is in Spanish languague. (Other versions exist and are dated as April, 1991 and a version 5.00a dated as November 1991)
[Microsoft MS-DOS 5.00 [Spanish] (3.5).zip](https://github.com/86Box/86Box/files/13401559/Microsoft.MS-DOS.5.00.Spanish.3.5.zip)

**Comment by Fenix770** [comment]
PD: here is the Goldstar 286 VM with DOS 5.0 (july, 1991) and QRAM installed

[286 Goldstar.zip](https://github.com/86Box/86Box/files/13401563/286.Goldstar.zip)
[SCAT type 4 hd.zip](https://github.com/86Box/86Box/files/13401564/SCAT.type.4.hd.zip)

**Comment by Fenix770** [comment]
The bug seems to be fixed now!. The protection error was triggered, before, by the Windows alc utility.

**Comment by OBattler** [comment]
Well then, this can be closed as well.
