### ISSUE TITLE
SuperEGA graphics card does not display CGA graphics

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#3829]
### What happened?

On the SuperEGA video card, when launching any CGA game, a black screen or enlarged characters on a black screen are displayed. This bug appeared in build 3795 and persists until the latest build. Build 3794 runs CGA games but displays distorted images.
Screenshot:
![2023-11-15_125508](https://github.com/86Box/86Box/assets/58270614/6bb4dc68-deee-411e-abcc-a2ede6ef21c6)

While a regular EGA video card displays any CGA game correctly.
Screenshot:
![2023-11-15_125536](https://github.com/86Box/86Box/assets/58270614/ad404084-7d3f-4aab-8691-6784e4b9d80f)

### Configuration file

```ini
[Machine]
machine = jukopc
cpu_use_dynarec = 0
time_sync = local
cpu_enable_fpu = 1
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
fpu_type = 8087
fpu_softfloat = 0
mem_size = 640

[CGA]
display_type = 0
composite_type = 0
rgb_type = 0
snow_enabled = 0

[General]
vid_renderer = qt_opengl
window_remember = 1
vid_resize = 1
force_43 = 1
vid_cga_contrast = 1
confirm_exit = 0
video_fullscreen_first = 0
confirm_reset = 0
confirm_save = 0

[Video]
gfxcard = superega

[Input devices]
mouse_type = msserial
joystick_type = 2axis_2button
joystick_0_nr = 0
joystick_1_nr = 0

[Sound]
fm_driver = nuked

[Hard disks]
hdd_01_parameters = 17, 4, 306, 0, ide
hdd_01_fn = images/DOS.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Storage controllers]
hdc = xtide_acculogic
cartridge_01_fn = G:/Temp/86Box/
cartridge_02_fn = G:/Temp/86Box/

[Other peripherals]
postcard_enabled = 1

[Monitor #1]
window_coordinates = 412, 31, 1736, 1292

[Monitor #2]
window_coordinates = 412, 31, 1736, 1292

[Floppy and CD-ROM drives]
fdd_02_type = none

[Microsoft Serial Mouse]
port = 0
buttons = 4
```

### Operating system

Windows 10 Pro x64 v22H2

### CPU

Core i9-10900K

### 86Box version

v4.1 Build 5207

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
Already known.

**Comment by OBattler** [comment]
I'm closing this because this is part of the SuperEGA implementation being crap in general and is pending a rewrite.
