### ISSUE TITLE
IBM PS/2 model 70 type 4 error 103

### ISSUE THREAD

**Issue by jaroslavl1** [86Box/86Box#3833]
### What happened?

Steps to reproduce:

1. Create new machine of type i486 (socket 168 and 1)
2. Select machine [MCA] IBM PS/2 model 70 type 4
3. Select CPU Intel 486 DX 25Mhz
4. Select Display - Internal Controller
5. Select HD Controller - [MCA] IBM PS/2 ESDI Fixed Disk Adapter
6. Add historical ESDI HDD e.g 228 C, 16 H, 63 S (112MiB, IBM 0669 ESDI drive)

Booting fails immediately with error 103 - Basic ROM checksum error.

### Configuration file

```ini
[General]
video_fullscreen_first = 0
dpi_scale = 0
vid_renderer = qt_software

[Machine]
machine = ibmps2_m70_type4
cpu_family = i486dx
cpu_speed = 25000000
cpu_multi = 1
fpu_type = internal
cpu_use_dynarec = 1
time_sync = disabled
fpu_softfloat = 1
cpu = 6
mem_size = 2048

[Video]
gfxcard = internal

[Input devices]
mouse_type = ps2

[Storage controllers]
hdc = esdi_mca

[Hard disks]
hdd_01_parameters = 63, 16, 228, 0, esdi
hdd_01_fn = hdd1.img
hdd_01_speed = 1992_3600rpm
hdd_01_esdi_channel = 0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
fdd_01_turbo = 1
fdd_02_turbo = 1
fdd_01_image_history_01 = F:/ibm/ps2 model80/rf7080a.img
fdd_01_image_history_02 = F:/ibm/ps2 model70/rf70486a.img

[Cirrus Logic CL-GD 5430 (VLB)]
memory = 1

[Phoenix S3 86c805 VLB]
memory = 1

[Trident TGUI 9440 VLB]
memory = 1

[Sound]
fm_driver = nuked

[Metheus Premier 928 (S3 86c928) ISA]
memory = 1

[S3 86c928 ISA (Metheus Premier 928)]
memory = 1
```

### Operating system

Windows 7

### CPU

Intel Core i7 920XM

### 86Box version

v4.1 build 5207

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Manager auto-update

**Comment by guestuser0001** [comment]
Are you using old recompiler or new recompiler one? And try it on build 5210 (old recompiler)

**Comment by jaroslavl1** [comment]
After unchecking dynamic recompiler the problem is gone. This is a dynamic recompiler problem.
