### ISSUE TITLE
[8088] Philips P3105/NMS9100 detects processor frequency only 4.77MHz

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#3837]
### What happened?

On this machine, when installing an 8088 or NEC V20 processor, the processor frequency always remains 4.77MHz, even if you select other frequencies in the 86Box menu: 7.16MHz, 8MHz, 10MHz, 12MHz, 16MHz.
How to reproduce this bug:
1. Select machine [8088] Philips P3105/NMS9100
2. Select 8088 or NEC V20 processor
3. For 8088, set the processor frequency to 7.16MHz or 8MHz or 10MHz or 12MHz or 16MHz
4. For NEC V20, set the processor frequency to 7.16MHz or 10MHz or 12MHz or 16MHz
5. Boot into MS-DOS and launch System Information (Benchmarks tab) from Norton Utilities v6.0

You will see that the frequency shows 4.77MHz, despite the fact that the frequencies selected in the 86Box menu are 7.16MHz or 8MHz or 10MHz or 12MHz or 16MHz:
![Monitor_1_20231120-125502-745](https://github.com/86Box/86Box/assets/58270614/1293963d-fb43-4714-81f1-e4349309eca9)

This is what the Benchmarks tab should look like if the processor frequency was, for example, 16MHz. (Tested on other 8088 machines with the processor frequency set to 16MHz):
![Monitor_1_20231120-125238-807](https://github.com/86Box/86Box/assets/58270614/6f2708cc-9e46-4167-ac1a-d233705c6468)

You can also run any game (for example Digger) that depends on the speed of the processor, and you will see that the game runs normally (slowly, as it should run at 4.77MHz). And it should work faster if for the machine [8088] Philips P3105/NMS9100 you select other frequencies in the 86Box menu: 7.16MHz, 8MHz, 10MHz, 12MHz, 16MHz.

### Configuration file

```ini
[Machine]
machine = p3105
cpu_use_dynarec = 0
time_sync = local
cpu_enable_fpu = 1
cpu_family = 8088
cpu_speed = 7159092
cpu_multi = 1
fpu_type = 8087
fpu_softfloat = 0
mem_size = 512

[CGA]
display_type = 0
composite_type = 0
rgb_type = 0
snow_enabled = 0

[General]
vid_renderer = qt_opengl
window_remember = 1
vid_resize = 1
force_43 = 1
vid_cga_contrast = 1
confirm_exit = 0
video_fullscreen_first = 0
confirm_reset = 0
confirm_save = 0

[Video]
gfxcard = vga

[Input devices]
mouse_type = msserial
joystick_type = 2axis_2button
joystick_0_nr = 0
joystick_1_nr = 0

[Sound]
fm_driver = nuked

[Hard disks]
hdd_01_parameters = 17, 4, 306, 0, ide
hdd_01_fn = images/DOS.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Storage controllers]
hdc = xtide_acculogic

[Other peripherals]
postcard_enabled = 1

[Monitor #1]
window_coordinates = 412, 31, 1736, 1292

[Monitor #2]
window_coordinates = 412, 31, 1736, 1292

[Floppy and CD-ROM drives]
fdd_02_type = none

[Microsoft Serial Mouse]
port = 0
buttons = 4
```

### Operating system

Windows 10 Pro x64 v22H2

### CPU

Core i9-10900K

### 86Box version

v4.1 Build 5210

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by iamgreaser** [comment]
After a bit of digging through the source, it appears that this boots into non-turbo mode, thus being stuck on the 4.77 MHz clock. But don't worry, DEBUG is here to save the day! (as always)

Run `debug`, then type in the following - don't forget that a blank line basically means "press enter again"!

```
a100
in al, c0
xor al, 80
out c0, al
int 20

nturbo.com
rcx
8
w
q
```

Then run `turbo`. It should toggle the turbo mode on and off.

Running the benchmark in Norton Utilities 6.01 gives me this result once turbo mode is on when the clock speed is set to 16 MHz:

![image](https://github.com/86Box/86Box/assets/138113/afffbf56-7161-48e8-a912-cdf67e4b3cf2)

**Comment by iamgreaser** [comment]
Alright, I found the manual and found the key combo needed to toggle turbo mode.

While the CPU Speed benchmark is visible, hold ALT + LSHIFT + RSHIFT. And watch the speed change in front of your eyes :slightly_smiling_face:

**Comment by borisvolk117** [comment]
the Philips' original system disk has a SPEED.COM utility to change 4.77 MHz and turbo mode, which is mentioned in #1549.

**Comment by OBattler** [comment]
Well, then this is NOTABUG, so this can be closed. And yes, I have just verified in the code that turbo is indeed implemented for this machine.
