### ISSUE TITLE
[Bug]CD-ROM didn't work properly

### ISSUE THREAD

**Issue by bingohuaji** [86Box/86Box#386]
I was inserting CD in the virtual CD-ROM of 86box and then it crashed,no matter in the latest or the older build.On the latest ROM.
![OZB)_N6N}R58T687E$P_W@D](https://user-images.githubusercontent.com/35895452/57978396-cd747300-7a3f-11e9-8c54-ed4cc5e8a27c.png)

**Comment by daviunic** [comment]
Try to remove any non-ASCII characters from the path to the disc image.

**Comment by bingohuaji** [comment]
> Try to remove any non-ASCII characters from the path to the disc image.

I found some spaces in the path...
Thanks!

**Comment by dhrdlicka** [comment]
This is a duplicate of #365.
