### ISSUE TITLE
[ISA] Commodore PC 30 III machine not booting using any MDA video card

### ISSUE THREAD

**Issue by win98user** [86Box/86Box#3863]
### What happened?

Also, this is my 2nd bug issue, and this is the problem why this Commodore 286 machine called (PC 30 III) doesn't even boot using any MDA monochrome video card...
Every time I was booting this Commodore 286 machine, it didn't even POST, despite having a black screen when using the (MDA) video card option, and this problem also occurs on any Hercules video card.

### Configuration file

```ini
[General]
vid_renderer = qt_software
dpi_scale = 0

[Machine]
machine = cmdpc30
cpu_family = 286
cpu_speed = 12500000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 1
time_sync = local
fpu_type = 287xl
cpu = 3
mem_size = 1024

[Video]
gfxcard = hercules

[Input devices]
mouse_type = none

[Sound]
fm_driver = ymfm
midi_device = mt32

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Roland MT-32 Emulation]
output_gain = 100
reverb = 1
reverb_output_gain = 100
reversed_stereo = 1
nice_ramp = 1

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd

[Other peripherals]
postcard_enabled = 1
```

### Operating system

Windows 11

### CPU

Intel i5-11300H

### 86Box version

Build 5226

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

CFG/NVR ZIP file:
[files.zip](https://github.com/86Box/86Box/files/13598926/files.zip)

This is the result booting the Commodore 286 machine using an MDA video card:
![image](https://github.com/86Box/86Box/assets/152977043/09e68f1e-bbaa-4bec-bbc6-79ab4705f8b6)

**Comment by mfmcosta** [comment]
This PC is a cut-down version of the PC 40-III.
It came out in 1989 with an EGA graphics card (Paradise or ATI)
So use an EGA or VGA graphics card and you'll be fine.

**Comment by OBattler** [comment]
I'm closing this with NOTABUG then.
