### ISSUE TITLE
[BUG] OS/2 Warp 3 CD installation failure using IDE

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#388]
I'm currently using the Jenkins Build #1841 of 86Box to attempt to install OS/2 Warp 3 from the IDE CD-ROM located on IDE 0:1 (slave), the text portion of the OS/2 Warp 3 setup works successfully. However, upon entering the graphical portion of the OS/2 Warp 3 setup, when trying to proceed any further, I get this error message:

![20190525_152052](https://user-images.githubusercontent.com/32658796/58375370-e4b2d500-7f05-11e9-90a1-2f395f81808f.png)

As pointed by the error message shown alove, looking at line 10 of the CONFIG.SYS file, the, **SET RUNWORKPLACE** variable points to \OS2\PMSHELL.EXE.

I tested the OS/2 Warp 3 installation on PCem v15 (AMI386) and it works without problems. I can install OS/2 Warp 3 to a CD-ROM attached on a SCSI device and it works without problems. On 86Box, I used the 386 version of the processor and the error still occurs.

<b>MACHINE CONFIGURATION:</b> DataExpert OPTi-495SX (AMI486, 486DX2/66, AMI386 386/33), 16 MB RAM, Tseng ET4000AX card with 1 MB VRAM, 3 1/2" floppy, 504 MB hard disk on IDE 0:0 and IDE CD-ROM on IDE 0:1

Please investigate this issue and fix the bug that causes OS/2 Warp 3 to not install using a CD-ROM attached to a IDE device on 86Box.

Thanks. :)

**Comment by ppgrainbow** [comment]
I found that there is a bug in the IDE hard disk that causes this.

TC1995 reported that the bug also occurs when the combination is a IDE hard disk and a SCSI CD-ROM.

**Comment by TC1995** [comment]
Actually a IDE HDD problem.

**Comment by ppgrainbow** [comment]
> 
> 
> Actually a IDE HDD problem.

Thank you for the clarification! :)

I see that the bug has been fixed now and I can't wait for the next Jenkins build that corrects this error and any of the other bugs that I reported soon! :D
