### ISSUE TITLE
Amstrad 1640 localization issues

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#389]
Hello
Some issue with Amstrad PC 1640

- Boot screen incorrect
- only speak Danish ? =>make a Configure option to select DIP Swicth for laguage, monitor, etc, please !
- Crash when using GEM -same HD image work with PCEM or Varcem-

**Comment by dhrdlicka** [comment]
Could you please provide more information about the issues that you are experiencing and what is the expected behavior in each case?

It will also be useful if you upload your configuration, so we can reproduce the GEM crash.

**Comment by jvernet** [comment]
86Box:
![86boxpc1640](https://user-images.githubusercontent.com/16312616/58745977-16bdbd00-8459-11e9-8b22-6dbcb76e3826.PNG)

What it should be:
![pc1640ok](https://user-images.githubusercontent.com/16312616/58745981-25a46f80-8459-11e9-91bc-ff39331ea955.PNG)

**Comment by jvernet** [comment]
GEM installed from system disk display desktop then reboot or even crash 86Box
`[Machine]
machine = pc1640
mem_size = 640
cpu_use_dynarec = 0
time_sync = local
cpu = 1

[Video]
gfxcard = internal

[Input devices]
mouse_type = internal

[Other peripherals]
hdc = xtide

[Floppy drives]
fdd_01_fn = 
fdd_02_type = 35_2dd
fdd_01_turbo = 1
fdd_02_turbo = 1

[Sound]
sndcard = sb

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Hard disks]
hdd_01_parameters = 17, 6, 615, 0, ide
hdd_01_fn = C:\Users\Jerome\Desktop\86Box\PC1640\HD1640 - Drive C.ima
hdd_02_parameters = 17, 6, 615, 0, ide
hdd_02_fn = C:\Users\Jerome\Desktop\86Box\PC1640\HD1640 - Drive D.ima
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1
`

**Comment by dhrdlicka** [comment]
Considering this is two issues in one, I split the GEM crash to #391. This issue is solely for the Amstrad 1640 system language issue.

**Comment by TC1995** [comment]
I believe this was fixed in some uncommitted fix.

**Comment by OBattler** [comment]
Yes, this was fixed.
