### ISSUE TITLE
GEM crashes on the Amstrad 1640

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#391]
GEM installed from system disk display desktop then reboot or even crash 86Box
```ini
[Machine]
machine = pc1640
mem_size = 640
cpu_use_dynarec = 0
time_sync = local
cpu = 1

[Video]
gfxcard = internal

[Input devices]
mouse_type = internal

[Other peripherals]
hdc = xtide

[Floppy drives]
fdd_01_fn = 
fdd_02_type = 35_2dd
fdd_01_turbo = 1
fdd_02_turbo = 1

[Sound]
sndcard = sb

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Hard disks]
hdd_01_parameters = 17, 6, 615, 0, ide
hdd_01_fn = C:\Users\Jerome\Desktop\86Box\PC1640\HD1640 - Drive C.ima
hdd_02_parameters = 17, 6, 615, 0, ide
hdd_02_fn = C:\Users\Jerome\Desktop\86Box\PC1640\HD1640 - Drive D.ima
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1
```

_Originally posted by @jvernet in https://github.com/86Box/86Box/issues/389#issuecomment-497926239_

**Comment by dhrdlicka** [comment]
@jvernet, would you mind also uploading the disk images used in your configuration, so we can reproduce the issue?

**Comment by jvernet** [comment]
Here it is (french keyboard). Start with GEM.
[HD1640 - Drive C.zip](https://github.com/86Box/86Box/files/3244582/HD1640.-.Drive.C.zip)

**Comment by jvernet** [comment]
Another issue with 86Box and this image: if you try to use pctools (in c:\PCTOOLS), you will get a Packed File is Corrupt.
Same image in Varcem (and same config): no problem. PCem do not boot at all on the image (same config).

I think also that Amstrad Internal mouse do not work anymore (it was a few release back).

**Comment by OBattler** [comment]
On my end right now:
1. GEM starts up fine but I have no idea how to return to DOS;
2. PCSHELL of PC Tools works, but I'm not sure if that's the component that was giving you Packed File is Corrupt.

**Comment by OBattler** [comment]
OK, just fixed the Amstrad mouse (and this should also fix the Olivetti M24 mouse).

**Comment by jvernet** [comment]
Change are not commited ?
I have some more issue with Amstrad PC Emulation, like keyboard mapping, but it could be related to Amstrad Mouse (direction key displaying numbre, for example).
