### ISSUE TITLE
Windows 2.x crash with ATI EGA 800/ATI VGA 18800 with both EGA 800x600 and  standard VGA video modes

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3913]
### What happened?

Bugs: 

1. I installed Windows 2.1/286 with ATI EGA 800 drivers (for the 800x600 8 color video mode) after the installation when I start Windows the screen freezes at startup. 

2. Then I installed another copy of Windows 2.1/286 on C:\WINVGA directory with standard VGA (640x480 16 color) mode.
I this case all the video cards returns to the DOS prompt even with regular VGA video cards not only the ATI.

3. I tested a 1991 battleship game designed for 640x480x16 video mode. Works on regular VGA cards but throws an error on Super EGA and ATI EGA 800+ despite both cards claim to be compatible with the VGA 640x480X16 video mode

I don't know what cause this!

![Monitor_1_20231219-202224-778](https://github.com/86Box/86Box/assets/31600563/6ba55c60-22f8-4f1a-aa94-c3b2d461f84b)

configuration:

I tested the Trigem 286M with 4mb RAM. And tested the both ATI EGA 800 and ATI VGA 18800 for the EGA 800x600x8 video mode.

The strangest part is the standard VGA installation does not work, on the VGA cards I tested. (ISA VGA, ATI VGA 18800 and OTI-37C).

Here is the HDD image file: 
[286+ATI EGA 800.zip](https://github.com/86Box/86Box/files/13721197/286%2BATI.EGA.800.zip)

And the ATI EGA 800+ drivers:
[ATI 800 PLUS EXTRACTED.zip](https://github.com/86Box/86Box/files/13721200/ATI.800.PLUS.EXTRACTED.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
vid_resize = 1
rctrl_is_lalt = 1

[Machine]
machine = tg286m
cpu_family = 286
cpu_speed = 12500000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu = 3
mem_size = 4096

[Video]
gfxcard = oti037c

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = cms
gameblaster = 2

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Ports (COM & LPT)]
lpt1_device = postscript

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_fn =
hdd_01_speed = 1989_3500rpm
hdd_01_ide_channel = 0:0
hdd_01_vhd_blocksize = 1024

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd


[ATI EGA Wonder 800+]
memory = 256
monitor_type = 9
```

### Operating system

Windows 10

### CPU

i5 4210U

### 86Box version

4.1.0.5261

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
For the ATI one, configure the eeprom.

**Comment by Fenix770** [comment]
I configured the card with ESETUP.EXE program as EGA EC80 and Multisync.

Here is the NVR file:
[nvr.zip](https://github.com/86Box/86Box/files/13721562/nvr.zip)

However there is a bug with at least the VGA 640x480x16 mode, even with ISA 8-bit VGA cards.

**Comment by TC1995** [comment]
Did this happen before my VGA changes?

**Comment by OBattler** [comment]
What exactly is the bug with the VGA 640x480x16 mode?

**Comment by Fenix770** [comment]
The bug related to the VGA 640x480x16 mode are:

1. The standard VGA driver included on the Win 2.11/286 does not work even on 8-bit ISA VGA video cards.
2. An old DOS battleship game that uses 640x480x16 video mode, works on all VGAs, but not on Super EGA or ATI EGA 800+

[BatteleShip 1991 vga.zip](https://github.com/86Box/86Box/files/13732842/BatteleShip.1991.vga.zip)

3. The 800x600 video mode works fine when tested on ETEST.EXE program, but not with Windows. I tested the versions 1.04  2.10/286 and 2.11/286.

4. The regular EGA video mode (640x350x16) does not work on Windows 3.00 with the ATI EGA 800+. Only a blinking cursor can be seen when the SETUP program enters the graphics mode.

The other possible explanantions with the 800x600 video mode  can be an incorrect driver disk, desepite the readme file clearly says it is for EGA 800+ but the Windows startup screen after installation says "ATI VGA", I tested on ATI VGA 18800 but does not work with that card either.

**Comment by Fenix770** [comment]
The VGA, 640x480x16 mode of Windows 3.00 does not work even on AVGA1 card. I'll test older revision of 86box to find out on which build this bug appeared!

**Comment by Fenix770** [comment]
The older build I can download is 5258, for some reason Jenkins does not allow to dowload older commits anymore.

**Comment by Fenix770** [comment]
I  have no idea of what causes the bug with standard VGA mode on Windows 2.1/286 and 3.0 but it was present on build 5210, before the EGA/VGA changes.

**Comment by TC1995** [comment]
On my test build EGA and VGA work fine with the EGA Wonder 800+ as well as on 1.01.

**Comment by Fenix770** [comment]
So maybe my drivers are damaged in some way!. Could you send me the driver disk?

**Comment by OBattler** [comment]
Jenkins does allow downloading older builds.

**Comment by Fenix770** [comment]
I close this issue since it is not reated to the video card!.

**Comment by Fenix770** [comment]
I close this issue since it is not reated to the video card!.
