### ISSUE TITLE
Solaris 2.4 installation issue

### ISSUE THREAD

**Issue by ArtiomWin** [86Box/86Box#392]
Hello. I have problem with installation of Solaris 2.4  - after selection of Interactive installation system panics with bad trap like this:
![20190604_222340](https://user-images.githubusercontent.com/31134876/58907982-1272f780-8718-11e9-8f57-4b0443b85cde.png)

[nvr.zip](https://github.com/86Box/86Box/files/3254177/nvr.zip)
NVR is attached.

**Comment by ppgrainbow** [comment]
Attaching only the NVR is not enough. We need to know the 86Box configuration file that was used to install Solaris 2.4.

Otherwise, we won't be able to address this issue.

**Comment by ArtiomWin** [comment]
OK, here's config.
[cfg.zip](https://github.com/86Box/86Box/files/3258769/cfg.zip)

**Comment by ppgrainbow** [comment]
Thank you so much! :)

**Comment by ArtiomWin** [comment]
Hello again. Bad trap issue seems to be fixed, but there's another problem - this time with graphic. Installation programs fails to launch OpenWindows even when you choose basic VGA mode.
![20190922_111441](https://user-images.githubusercontent.com/31134876/65384510-d053dd00-dd2b-11e9-9e85-930ef398d5e9.png)

**Comment by MoochMcGee** [comment]
@ArtiomWin can you try using the S3 Virge VBE 2.0?

**Comment by ArtiomWin** [comment]
@MoochMcGee No, I've tried graphic cards that were available at installation menu (it's Solaris 2.4, so S3 Virge wasn't available)  and supported by 86box. All give the same result.

**Comment by OBattler** [comment]
This will probably require a major look at the (S)VGA code to see why it's not liking any emulated (S)VGA graphics card.

**Comment by qeeg** [comment]
The BAD TRAP issue is back.

**Comment by OBattler** [comment]
Closing this because I have a reported by thunderbird32 that Solaris 2.4 now works fine in 86Box.
