### ISSUE TITLE
PEL panning on EGA cards missing feature

### ISSUE THREAD

**Issue by mills32** [86Box/86Box#3922]
### What happened?

I recently discovered EGA cards update the PEL panning register (0x03C0  0x13) every scanline. This feature is not implemented on the last release (4.0.1).

You can use Beverly Hills Cop to test: 
https://youtu.be/QuzGlNWsLAA?t=63
Also I made this little program that loads an image and changes the PEL register every scanline:
[scanlines.zip](https://github.com/86Box/86Box/files/13752235/scanlines.zip)

This is implemented on Dosbox-x, also I read (at forum.vcfed.org) some VGA cards can do it, like Paradise PVGA1A.

### Configuration file

```ini
[General]
vid_renderer = qt_opengl3
video_fullscreen_scale = 2
video_gl_vsync = 1
window_remember = 1
dpi_scale = 0
video_filter_method = 0

[Machine]
machine = pc1640
cpu_family = 8086
cpu_speed = 8000000
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = local
fpu_softfloat = 0
cpu = 1
mem_size = 640

[Video]
gfxcard = ega

[Input devices]
mouse_type = none

[Sound]
sndcard = adlib
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = xtide
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 126, 0, ide
hdd_01_fn = C:/MISTER/PCXT_MiSTer-main/SW/PCXT_CGA_Tandy_2.4.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Oak OTI-077]
memory = 256

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd_ps2
fdd_01_fn = C:/Users/David/Desktop/DISK_144.img
fdd_02_fn = C:/Users/David/Desktop/DISK_320.IMG

[Monitor #1]
window_coordinates = 343, 214, 398, 249

[Monitor #2]
window_coordinates = 0, 0, 0, 0
```

### Operating system

Windows 10

### CPU

Intel i5-6500T  2.50GHz

### 86Box version

4.0.1

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
Try the nightly builds.

**Comment by mills32** [comment]
> Try the nightly builds.

Thanks, I tried and it did not work

**Comment by mills32** [comment]
I'm sorry for my dumb question, I'm not used to github. Is this already working on the last nightly build?. (I tested and it did not).  Thanks a lot for this great emulator!.
