### ISSUE TITLE
Possible regression with Mach32 on Windows NT 4 since commit cd7264dd (build 5273)

### ISSUE THREAD

**Issue by thedax** [86Box/86Box#3933]
### What happened?

Under NT 4, using the ATi Mach32 with the default built-in driver has an extended 'mirrored' display, as well as a corrupted black bar at the bottom of the screen regardless of colour depth and resolution. The most recent known good build is 5272 (tested builds 5230, 5232, 5272, 5284). PCI vs ISA seems to make no difference. The mouse cursor stays within the correct bounds of the display and does not interact with or show on the extra mirrored graphics on the right.

![Monitor_1_20231224-193047-250](https://github.com/86Box/86Box/assets/4482745/d4710237-8310-4f9a-9bba-0d5c8a43a0f4)

Guest specs:
Mainboard: Soyo 4SAW2
CPU: Intel i486DX2 WB 66MHz
RAM: 32MB
Video: ATi Mach32 PCI
Mouse: Standard PS/2
Sound: None
Network: None
Ports: Default
Storage controllers: Internal
Hard disk: IDE 0:0 768MB (1560, 16, 63), RAM disk speed
CD-ROM: ATAPI 0:1, 8x
Floppy drives: default 360k 5.25" (didn't use these for the test at all, this mainboard can boot from CD directly)

Steps to reproduce:
1. Install NT4 (the ISO I used has SP1 integrated, but it doesn't seem to matter, SP6a also exhibits the issue).
2. Boot to the login screen and/or desktop.
3. Observe the visual bug.

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = 4saw2
cpu_family = i486dx2_pc330
cpu_speed = 66666666
cpu_multi = 2
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 32768

[Video]
gfxcard = mach32_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 1560, 0, ide
hdd_01_fn = /path/to/nt4-with-mach32.IMG
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Fedora Linux 39

### CPU

AMD Ryzen 5 5560U

### 86Box version

5273, but multiple were tested

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

I do not have real ATi Mach32 hardware to test with, so if this is now accurate to real hardware, please disregard this.

**Comment by OBattler** [comment]
This can now be closed as it is now fixed.

**Comment by thedax** [comment]
Indeed it is, thank you.
