### ISSUE TITLE
Windows 98 SE Mouse Buttons Randomly Stop Working

### ISSUE THREAD

**Issue by SavantSusi** [86Box/86Box#3937]
### What happened?

After a few clicks the mouse buttons stop working in the VM essentially rendering it completely if not mostly unusable. I need to reset and change the mouse type which often causes it to need to scan the disk or boot in safe mode.

### Configuration file

```ini
[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 4
sli = 0
recompiler = 1

[Microsoft Serial Mouse]
port = 2
buttons = 4

[General]
vid_renderer = qt_opengl3
force_43 = 1
confirm_reset = 0
vid_resize = 2
window_fixed_res = 1280x960

[Machine]
machine = zappa
cpu_family = pentium_p55c_od
cpu_speed = 200000000
cpu_multi = 3
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
cpu = 14
mem_size = 131072

[Video]
gfxcard = voodoo3_3k_pci
voodoo = 1

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb_vibra16s
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_pci
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 16449, 0, ide
hdd_01_fn = /home/susiterry/win98se
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 35_2hd
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
fdd_01_image_history_01 = /home/susiterry/Pictures/Microsoft Windows 98 Second Edition - Boot Disk (3.5-1.44mb)/Windows 98 Second Edition Boot.img
cdrom_01_image_history_01 = /home/susiterry/Pictures/Microsoft Windows 98 Second Edition (4.10.2222) (Retail Full)/Windows 98 SE (101 - Retail Full).iso
cdrom_01_host_drive = 200
cdrom_01_image_path = /home/susiterry/Pictures/cdrom.iso
cdrom_01_type = 86BOX_CD-ROM_1.00

[Standard PS/2 Mouse]
buttons = 4

[3dfx Voodoo3 3000]
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 4
recompiler = 1

[Logitech Serial Mouse]
port = 0
buttons = 2
revision = 3
rts_toggle = 0

[Mouse Systems Serial Mouse]
port = 1
buttons = 2
rts_toggle = 0
```

### Operating system

Manjaro Linux

### CPU

AMD Ryzen 7 3800x

### 86Box version

4.0.1

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

I got 86Box from a third party repository (please tell us where)

### Additional context

I got it from the arch user repository.

**Comment by SavantSusi** [comment]
Update. It appears the keyboard also registers me pressing the up arrow when I'm not.

**Comment by OBattler** [comment]
Use our provided AppImage instead.

**Comment by OBattler** [comment]
Closing due to it being tracked in the common issue #4239.

**Comment by OBattler** [comment]
From what I now know, people have also reported it on Windows hosts, and it's due to the emulated keyboard controller being cloogged, so it's a CANTFIX util someone disassembles and dumps the AMI, Phoenix, etc. keyboard controller firmware dumps so I can imlement their logic as well - our current logic is based on the documented disassembly of the IBM AT and PS/2 controllers.
