### ISSUE TITLE
Bug in some video modes on ATI-28800

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3941]
### What happened?

I found a bug on the 1024x768x16 packed pixel video mode the 4-planar mode works just fine.

Here is some screenshots:
The test program utility:

![Monitor_1_20231225-201905-808](https://github.com/86Box/86Box/assets/31600563/706c5611-29b9-452b-b316-fcb491e8f01c)

1024x768x16 Packed pixel modes:

Taken from the ATI setup disk:
![Monitor_1_20231224-101102-092](https://github.com/86Box/86Box/assets/31600563/e58d1c31-01b3-47b7-b4a7-1b4530a73566)

Windows 2.11/286 with the 1024x768 16 colors. Here the screen is distorted like the in the setup test program:

![Monitor_1_20231224-101920-216](https://github.com/86Box/86Box/assets/31600563/f9a85b05-2625-42c3-9d43-2869bb57054f).

On the other hand, the 1024x768 16 colors work just fine on Windows 3.1, but maybe is using the 4-planar video mode:
![ATI 28800 MODE 55](https://github.com/86Box/86Box/assets/31600563/c24960a2-bfeb-4ad4-a8af-85aac7c5ea69)

Also according this site: https://en.wikipedia.org/wiki/ATI_Wonder_series#VGA_cards. 

1. The ATI EDGE-16 is limited to 256kb of VRAM, the Wonder 16 is the only 18800 chip based card that support 512 Kb.
2. The ATI Charger 28800-5 supports up to 512 Kb, only the XL/XL-24 supports 1 Mb.

The XL-24 Win 3.1 drivers works fine on the Charger but of course the higer resolution modes are not supported.

### Configuration file

```ini
[ATI 28800-5 (ATI VGA Charger)]
memory = 1024

[Sound Blaster v2.0]
base = 0220
mixaddr = 0000
irq = 5
dma = 1
opl = 1
cms = 0
receive_input = 1

[General]
vid_renderer = qt_software
vid_resize = 1
enable_overscan = 1
rctrl_is_lalt = 1

[Machine]
machine = spc6000a
cpu_family = i386dx
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = ati28800

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sb2.0
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_fn = 
hdd_01_vhd_blocksize = 1024
hdd_01_speed = 1992_3600rpm
hdd_01_ide_channel = 0:0
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.0.5290

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Please upload the VM.

**Comment by Fenix770** [comment]
Here are the files:

[86box-cfg.zip](https://github.com/86Box/86Box/files/13771040/86box-cfg.zip)
[nvr.zip](https://github.com/86Box/86Box/files/13771041/nvr.zip)
[Type 9 HDD experiment.zip](https://github.com/86Box/86Box/files/13771042/Type.9.HDD.experiment.zip)

**Comment by Fenix770** [comment]
And here the Driver 

[ATI Wonder XL v2.zip](https://github.com/86Box/86Box/files/13771054/ATI.Wonder.XL.v2.zip)
[ATI mach XL 24 Win 3.1.IMA.zip](https://github.com/86Box/86Box/files/13771055/ATI.mach.XL.24.Win.3.1.IMA.zip)

The "XL v2" disk contains the setup utility  on Tools folder. (This disk contains drivers for Win 3.0)
The XL 24 contains drivers that works on all 28800 based chips, if they have enough VRAM.
