### ISSUE TITLE
XDG_DATA_DIRS not corrently parsed for roms

### ISSUE THREAD

**Issue by ConiKost** [86Box/86Box#3946]
### What happened?

When XDG_DATA_DIRS is being set, 86Box wrongly ready multiple paths for roms.

Example: ```XDG_DATA_DIRS=/usr/local/share:/usr/share```

Using strace, I can see, that it's actually using the whole value of XDG_DATA_DIRS and has not splitted.

```
openat(AT_FDCWD, "/usr/local/share:/usr/share/86Box/roms/machines/vpc2007/13500.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
```

The issue seems be in this function:
https://github.com/86Box/86Box/blob/1e0368dba5f4a294d3d433c5398629495b96ed9e/src/unix/unix.c#L810

If I do correctly understand that code, it only removes the ```:``` at the end, but does not split correctly multiple paths?

### Configuration file

```ini
I don't have any config.
```

### Operating system

Gentoo Linux

### CPU

Core i7-6600U

### 86Box version

4.0.1

### Build architecture

Linux - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
I would be surprised if this is implemented incorrectly.

Though, is that stuff even used? The code actually used should be somewhere in QT.

**Comment by OBattler** [comment]
OK, it turns out the stuff in unix/ is in fact still used.

Also, it seems to be assuming ; as the separator.

**Comment by ConiKost** [comment]
Yes, but only at the end, not for the whole variable, AFAICS. I may be wrong.

**Comment by ConiKost** [comment]
Thanks! Just tested, you patch fixed it.
