### ISSUE TITLE
86Box --help causes rom missing message

### ISSUE THREAD

**Issue by ConiKost** [86Box/86Box#3948]
### What happened?

Running ```86Box --help``` from CLI causes to complain, that no roms cannot be found and also displays all supported command line options. But I run directly ```86Box``` everything works and all roms are loaded.

I think, this is a bug somehow, since roms are present and do work. This message should not be shown, when using ```--help```.

Strace clearly shows, that the whole prefix in path is missing.
```
openat(AT_FDCWD, "/machines/apas3/V0218SAG.BIN", O_RDONLY) = -1 ENOENT (No such file or directory)
```

### Configuration file

```ini
None
```

### Operating system

Gentoo Linux

### CPU

Core i7-6600U

### 86Box version

4.0.1

### Build architecture

Linux - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by lemondrops** [comment]
Where did you obtain 86Box from?

**Comment by ConiKost** [comment]
4.0.1 Source from Github. Compiled by myself, since Gentoo Linux is a source based distribution.

**Comment by lemondrops** [comment]
Have you built 86Box with the Qt UI (`-D QT=ON`) or the SDL UI?

**Comment by ConiKost** [comment]
With disabled ```-D QT=ON``` option.

**Comment by lemondrops** [comment]
This should be now fixed. Next time, please select the "I built 86Box myself" option in the "Download source" dropdown and, if possible, provide your build configuration.

**Comment by ConiKost** [comment]
Thanks, patch fixed it!
