### ISSUE TITLE
--settings switch only works in Qt, but not SDL

### ISSUE THREAD

**Issue by ConiKost** [86Box/86Box#3950]
### What happened?

If 86Box is started with ```--settings``` switch, it should not start any VM, but show instead settings.

If 86Box is being compied with ```-DQT=ON```, it works fine.
But if 86Box is being compiled with ```-DQT-OFF```, it does not work. Instead of showing settings, it starts directly a machine.

### Configuration file

```ini
None
```

### Operating system

Gentoo Linux

### CPU

Core i7-6600U

### 86Box version

4.0.1

### Build architecture

Linux - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

```
cmake -C /var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCPPTHREADS=yes -DDEV_BRANCH=yes -DDINPUT=yes -DDYNAREC=ON -DMUNT_EXTERNAL=yes -DFLUIDSYNTH=yes -DMINITRACE=OFF -DMUNT=yes -DNEW_DYNAREC=yes -DOPENAL=yes -DPREFER_STATIC=OFF -DRTMIDI=ON -DQT=no -DRELEASE=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1_build/gentoo_toolchain.cmake /var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1
```

**Comment by Cacodemon345** [comment]
There is absolutely no settings UI implemented in the SDL backend and there aren't any plans to implement one because it would increase maintenance burden a lot.

**Comment by ConiKost** [comment]
> There is absolutely no settings UI implemented in the SDL backend and there aren't any plans to implement one because it would increase maintenance burden a lot.

In this case, I would suggest to remove "--settings" shown with ```86Box --help```, when compiled with SDL.
