### ISSUE TITLE
Emulation of IBM 8514/A does not works with DOS applicatios even with the HDPCDOS driver loaded

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3952]
### What happened?

I installed the DOS device driver on the ATI Mach 8. I also installed the Adapter Interphase to be able to emulate the 8514/A 1024x768x256 video mode. But after the apps attempt to load that video mode the VM freezes.

Beforehand, I don't know if there are different AI drivers for the Mach 8 Ultra and non-Ultra, I think they should be the same because the normal, non accelerated VGA part of the card does support up to 800x600 with 256 colors only.

Here are the screenshots:

Here are the drivers loaded:
![ATI Mach 8 AI](https://github.com/86Box/86Box/assets/31600563/5036ab5e-00c4-4eab-b5b8-78d70a293746).

Here is the bug after loading a Majjong version for the 8514/A 
![ATI Mach 8 crash](https://github.com/86Box/86Box/assets/31600563/5ae944f3-75f6-42d9-993a-06aa01edb73b)
This also happens with PC Paintbrush IV when configured for 8514/A 1t 1024x768x256.

Also there is a bug when testing the 8514/A with the setup disk
![Mach 8 failure](https://github.com/86Box/86Box/assets/31600563/69c349f0-4726-4459-a8bf-ef56f52c5120)

After this screen the VM frezzes with a red screen.

The Win 3.1 driver seems to works fine however
![ATI Mach 8 driver seems to work right on Win 31](https://github.com/86Box/86Box/assets/31600563/b676cdab-ab5f-4840-898e-59c40e4db7c9)

The regular VGA part of the card seems to work fine too, on Neopaint
![Neopaint](https://github.com/86Box/86Box/assets/31600563/a564e9f0-e24a-48ef-8e1b-80e22f295f90)

Here is the HDD file:

[386 DX ATI Mach 8 v5.zip](https://github.com/86Box/86Box/files/13781948/386.DX.ATI.Mach.8.v5.zip)

Here the NVR:
[nvr-386-MAch 8.zip](https://github.com/86Box/86Box/files/13781951/nvr-386-MAch.8.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
vid_resize = 1
enable_overscan = 1

[Machine]
machine = asus386
cpu_family = i386dx
cpu_speed = 33333333
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu = 3
mem_size = 4096

[Video]
gfxcard = mach8_isa

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 10, 1024, 0, ide
hdd_01_fn = 
hdd_01_speed = 1994_4500rpm
hdd_01_vhd_blocksize = 1024
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.0.5300

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Fenix770** [comment]
I forgot to upload the EEPROM driver disk:
[ATI Mach 8 DOS drivers.zip](https://github.com/86Box/86Box/files/13781985/ATI.Mach.8.DOS.drivers.zip)

**Comment by TC1995** [comment]
And PC Paintbrush IV too.

**Comment by Fenix770** [comment]
Ok. Sorry here are the apps.

PC Paintbrush IV on (720kb abd 360k formats):
[PC Paintbrush IV Plus.zip](https://github.com/86Box/86Box/files/13781998/PC.Paintbrush.IV.Plus.zip)

And the Majjong game that uses the 8514/A 1024x768x256
[Majong 8514.zip](https://github.com/86Box/86Box/files/13782001/Majong.8514.zip)

**Comment by Fenix770** [comment]
PD: The PC Paintbrush is already installed on the virtual HDD!.
