### ISSUE TITLE
[BUG] MS-DOS CHKDSK randomly throws errors when run inside Windows 3.1

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#396]
Okay, I managed to set up MS-DOS 6.22 and Windows 3.1, the installation of these OSes went smoothly without any major problems.

When I run CHKDSK inside the MS-DOS prompt under Windows 3.1, I end up getting errors thrown at me at random. The CHKDSK.TXT logfile displays the list of errors and crossed links files:

[CHKDSK.TXT](https://github.com/86Box/86Box/files/3388572/CHKDSK.TXT)

Obviously, this error mostly occurs on IDE hard disks. As more files are installed on the hard disk, you can expect potential data corruption to increase when attempting to run CHKDSK in DOS prompt inside Windows 3.1

Here are the specs:
* U-BOARD (214UEUBRD, Award 486 with OPTi-495SX chipset)
* Internal IDE controller
* Adaptec AHA-1542C SCSI card
* 2 x 504 MB IDE hard disks
* 6 x 1 GB SCSI hard disks (not used at this time)
* 32 MB RAM (maximum that the motherboard and chipset can support)
* Trident TVGA 8900D graphics card with 1 MB video RAM
* Sound Blaster 16 card
* Logitech Serial Mouse
* 3.5" 1.44 MB, 5.25" 1.2 MB floppy disks
* MS-DOS 6.22 and Windows 3.11

I don't know if this problem is occurring on real hardware or not and I'm really positive that this error doesn't occur when running MS-DOS 6.22 and Windows 3.1x on VirtualPC 2007.

This error also doesn't occur if I use the DR-DOS 6 version of CHKDSK, because it's version will not check the disk for errors while it's running a DOS prompt under Windows 3.x.

Can anyone look into the bug to see what is causing the errors found by CHKDSK to occur?

Thank you for your time. :)

**Comment by dhrdlicka** [comment]
`chkdsk` is known to malfunction under Windows 3.1. This is not an 86Box bug,
