### ISSUE TITLE
Confirmation dialogs for hard reset, window close

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#397]
Earlier this morning in the #softhistory IRC, I've talked about my suggestion on how 86Box can be improved and this is what I want to suggest.

In the current Jenkin and FTP builds of of 86Box, there is no warning given regarding exiting or hard-resetting 86Box, so I would like to put this suggestion to perspective.

Upon closing the 86Box window, when you click on the red X button, a pop-up warning dialog needs to be displayed:

"Are you sure you want to close 86Box?"

If you select Yes, then 86Box will close. If you select No, the 86Box window will stay open

Upon performing a hard reset, a pop-up warning dialog needs to be played:

"Are you sure you want to perform a hard reset of the VM?

Use this feature only as a last resort if the emulated machine stops responding and pressing CTRL-ALT-DELETE doesn't work."

If you select Yes, then the emulated machine will perform a cold reboot. If you select No, then the emulated machine will be untouched.

**NOTE:** Involving CTRL-ALT-DELETE can be done by pressing CTRL + F12 key.

I'm suggesting this feature in hopes that it will prevent accidentally closing of the 86Box window, incase you have to do something else.

What you think? :D

**Comment by daviunic** [comment]
I support this. A step further would to add a "do not show this again" option to such dialogs for those that don't wish to be asked every time.

**Comment by ppgrainbow** [comment]
I support this idea too! :D

**Comment by ppgrainbow** [comment]
The confirmation dialogs on hard reset and exit have been added in Jenkins build #1848.

I'm going to close this issue now. :)
