### ISSUE TITLE
640x400x256 video mode does not works on ATI VGA-88

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3974]
### What happened?

I created a  NEC V20 VM with the ATI VGA 88. Both 800x600x8 video mode on Windows 1.04 and 800x600x16 on PC Paintbrush IV works just fine.
I discovered after running the VVESA utility that this card is also capable of supporting 640x400x256. Then I changed the configuration of PC Paintbrush IV to that resolution. And I get a distorted screen. As the XT machine is rather slow, (as it should be with this app) I can see the program loading the icons and color palette, but in the wrong places.

Screenshots:

PC Paintbrush at 640x400x256 video mode
![ATI VGA 88 screen bug](https://github.com/86Box/86Box/assets/31600563/acf46cb1-48c4-4568-9990-e5489441191f)

VESATEST utility:
![VESATEST](https://github.com/86Box/86Box/assets/31600563/1b61093f-dc53-45a8-907e-bccd456abfb2)

VESALIST utility
![VESALIST](https://github.com/86Box/86Box/assets/31600563/691185f3-1530-411d-9bd7-22f6e42faa5f)

Note: I copied the VESA utilities to the C:\ATI folder. I don't know if it also affects the EDGE-16 model. Since both cards are similar except by the 16-bit bus of the EDGE

Here is the NVR file:
[nvr-VGA-88.zip](https://github.com/86Box/86Box/files/13800050/nvr-VGA-88.zip)

HDD file:
[8088-XT-VGA-88-WD-MFM.zip](https://github.com/86Box/86Box/files/13800052/8088-XT-VGA-88-WD-MFM.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
vid_resize = 1
enable_overscan = 1

[Machine]
machine = dtk
cpu_family = necv20
cpu_speed = 10000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 1
time_sync = local
fpu_type = 8087
mem_size = 640

[Video]
gfxcard = ati18800v

[Input devices]
mouse_type = msserial

[Sound]
sndcard = cms
gameblaster = 2
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = st506_xt_wd1002a_wx1
cassette_mode = load
fdc = b215

[Hard disks]
hdd_01_parameters = 17, 5, 733, 0, mfm
hdd_01_fn =
hdd_01_vhd_blocksize = 1024
hdd_01_mfm_channel = 0

[Floppy and CD-ROM drives]

fdd_02_type = 35_2hd

[WD1002A-WX1 MFM Fixed Disk Adapter]
bios_addr = C8000
base = 0320
irq = 5

[AST SixPakPlus]
irq = 2

[Other peripherals]
isartc_type = a6pak
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.0.5323

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
Did it work before my ATI 18800 changes?

**Comment by Fenix770** [comment]
About the same happens on build 5000 Win x32, but only half of the screen was used.

![ATI VGA 88 Build 5000](https://github.com/86Box/86Box/assets/31600563/ed17e577-56b6-47fe-a0f5-33c8b6344069)

**Comment by Fenix770** [comment]
This also affects the 640x400x256 video mode on Windows 3.0
![Uploading ATI VGA-88 Win 30.png…]()

**Comment by TC1995** [comment]
Just share everything you have provided within the screenshots.

**Comment by Fenix770** [comment]
The Windows 3.0 drivers are on C:\ATIWIN. Windows 3.0 is installed with the 800x600 16 color driver mode. PC Paintbrush is in the C:\PBRUSH folder (I tested the 640x400x256, so I think you can change to that with the PBSETUP program at the DOS prompt).

Here is the updated HDD file:
[8088-XT-VGA-88-WD-MFM.zip](https://github.com/86Box/86Box/files/13824504/8088-XT-VGA-88-WD-MFM.zip)

**Comment by OBattler** [comment]
To quote from this:
> This ATI enhanced resolution mode uses a plane memory system unique to AT!. The memory is organized into contiguous 64K blocks located at AOOOOH to AFFFFH.
> VGAWONDER must be equipped with 512K of RAM to operate in this mode. Mode 61 uses 4 pages. The video data in this mode should only be updated during monitor retrace periods.

This means this mode is not going to work on the ATI VGA-88. Therefore, I'm closing this as NOTABUG.
