### ISSUE TITLE
MS-DOS cannot boot on Tandy SL with MFM

### ISSUE THREAD

**Issue by doomgod** [86Box/86Box#3982]
### What happened?

After FDD code update in 5285, there are following symptoms:
- I had MS-DOS 3.31 installed and it doesn't boot anymore (I get to A> prompt instead)
- Tried unbranded MS-DOS versions 3.21, 3.30, 3.31, 5.0 on a clean disk - they don't boot as well
- Only the Tandy OEM version 3.30.22 works, but it remains even if I try to overwrite it with format c: /s or sys c: from other versions

### Configuration file

```ini
[General]
enable_discord = 1
window_remember = 1
sound_gain = 8
confirm_save = 0
confirm_reset = 0
confirm_exit = 0
vid_renderer = qt_software
iconset = legacy
scale = 2
video_fullscreen_first = 0
mouse_sensitivity = 0.33

[Machine]
machine = tandy1000sl2
cpu_use_dynarec = 0
cpu_enable_fpu = 1
time_sync = local
cpu_family = necv30
cpu_speed = 16000000
cpu_multi = 1
fpu_type = 80187
fpu_softfloat = 0
mem_size = 768

[Video]
gfxcard = internal

[Input devices]
mouse_type = msserial

[Sound]
sound_type = int16
fm_driver = nuked
sndcard = sb

[Ports (COM & LPT)]
serial2_enabled = 0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2dd

[Storage controllers]
hdc = st506_xt_dtc5150x

[Micro Mainframe EMS-5150(T) #1]
size = 1024
base = 0208

[Monitor #1]
window_coordinates = 215, 52, 960, 675

[Monitor #2]
window_coordinates = 0, 0, 0, 0

[Microsoft Serial Mouse]
port = 0
buttons = 2

[DTC 5150X MFM Fixed Disk Adapter]
bios_addr = F4000

[Other peripherals]
isamem0_type = ems5150

[Sound Blaster v1.0]
base = 0220
irq = 7
dma = 1
opl = 1
receive_input = 0

[Hard disks]
hdd_01_parameters = 17, 8, 940, 0, mfm
hdd_01_fn = test.img
hdd_01_mfm_channel = 0
```

### Operating system

Windows 10

### CPU

Core i9-10980HK

### 86Box version

v4.1 build 5285 and above

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
How exactly would the updated FDD code have affected the hard disk?

**Comment by mfmcosta** [comment]
Am using build 5335 and it boots OK using my 10MB MFM (ST-11R or ST-11M controoler) with Olivetti MS-DOS 3.20

I've tried the DTC 5150X controller and it looks like it has some DOS 3.30 boot:
![image](https://github.com/86Box/86Box/assets/136728257/ed0e6f06-89e9-48bc-84fa-c4210c3110b7)

**Comment by OBattler** [comment]
This is now also fixed.
