### ISSUE TITLE
unix.c: error: pointer type mismatch in conditional expression [-Wincompatible-pointer-types] Title

### ISSUE THREAD

**Issue by ConiKost** [86Box/86Box#3994]
### What happened?

If 86Box is being compiled with ```-Werror=incompatible-pointer-types```, the build will fail. In Gentoo, we are testing all eBuilds towards "Modern C". The background here is, that ```clang``` and ```gcc``` will in future enable ```-Werror=incompatible-pointer-types```. This needs to be fixed for future versions, as it won't be able to build with newer compiler versions.

```
FAILED: src/unix/CMakeFiles/plat.dir/unix.c.o 
/usr/bin/x86_64-pc-linux-gnu-gcc -DCMAKE -DDISCORD -DRELEASE_BUILD -DUSE_DYNAREC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -D_LARGEFILE_SOURCE=1 -I/usr/include/freetype2 -I/usr/include/SDL2 -I/var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1_build/src/include -I/var/tmp/portage/app-em
/var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1/src/unix/unix.c: In function ui_msgbox_header:
/var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1/src/unix/unix.c:638:18: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  638 |         header = (void *) (flags & MBX_ANSI) ? "86Box" : L"86Box";
      |                  ^
/var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1/src/unix/unix.c:638:56: error: pointer type mismatch in conditional expression [-Wincompatible-pointer-types]
  638 |         header = (void *) (flags & MBX_ANSI) ? "86Box" : L"86Box";
      |                                                        ^
```

### Configuration file

```ini
Configuration file is not relevant, this affects the build process.
```

### Operating system

Gentoo Linux

### CPU

Core i7-6600U

### 86Box version

4.0.1 (Tried newest from Git too)

### Build architecture

Linux - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

For more information, visit:
https://wiki.gentoo.org/wiki/Modern_C_porting#-Wincompatible-pointer-types
https://bugs.gentoo.org/919343

**Comment by OBattler** [comment]
This, if anything, looks like missing parentheses, because I'm quite sure it's supposed to be casting the final result.

**Comment by OBattler** [comment]
OK, newest from git appers to have the offending line #if 0'd out, so it shouldn't compile at all.
