### ISSUE TITLE
S3 Trio broken on Solaris 2.5.1

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#4008]
### What happened?

When running Solaris 2.5.1 on a machine with an S3 Trio64 the top third of the framebuffer is repeatedly displayed in the 1024x768x256 mode:
![Monitor_1_20240107-094404-322](https://github.com/86Box/86Box/assets/47463859/7597105b-7158-44e5-9b84-516dad853269)

The expected behavior is for the entire framebuffer to be displayed

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = p55t2p4
cpu_family = pentium_p54c
cpu_speed = 166666666
cpu_multi = 2.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
cpu = 8
mem_size = 65536

[Video]
gfxcard = px_trio64_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Matrox Millennium]
memory = 8

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = Solaris25Test.img
hdd_01_speed = 1996_5400rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 16
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
fdd_01_fn = C:/Emulators/86Box/testing/Solaris25/DU11BT3.img
cdrom_01_host_drive = 200
cdrom_01_image_path = C:/Emulators/86Box/testing/Solaris25/solaris-2.5.1_x86.iso
fdd_01_image_history_01 = C:/Emulators/86Box/testing/Solaris25/DU11BT2.img
fdd_01_image_history_02 = C:/Emulators/86Box/testing/Solaris25/DU11BT1.img
cdrom_01_type = 86BOX_CD-ROM_1.00

[Other peripherals]
postcard_enabled = 1

[S3 Trio64 PCI (Phoenix)]
memory = 2
```

### Operating system

Windows 7 SP1

### CPU

Intel Core i7-9700K

### 86Box version

4.1 build 5349

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

I performed a bisect and found that the issue started occurring in build 5249. In build 5248 the framebuffer is displayed correctly:
![Monitor_1_20240107-102510-862](https://github.com/86Box/86Box/assets/47463859/96190dc8-45ed-4668-b268-3fb143164ce7)

NVR and config: 
[86Box-Solaris251.zip](https://github.com/86Box/86Box/files/13854328/86Box-Solaris251.zip)

**Comment by TC1995** [comment]
most likely the wraparound not being enabled properly.

**Comment by TC1995** [comment]
Wait, it enables the wraparound even though it shouldn't...
