### ISSUE TITLE
[SUGGESTION] Make MCA-based SCSI and network cards configurable

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#401]
Long story short, I've been using the emulated IBM PS/2 Model 80 (Intel 80386 processor running at 20 MHz with 12 MB RAM) and I'm starting to run into issue with the Micro-Channel Architecture-based SCSI and network cards.

The screenshot that I provided below is from the View Configuration settings of the PS/2 Model 70/80 reference diskette image::
![20190813_011519](https://user-images.githubusercontent.com/32658796/63559793-39b3b680-c508-11e9-9757-11ece3652bb8.png)

In the settings for slot #3, Adaptec AHA-1640 MCA SCSI host adapter, the adapter BIOS is located at DC00h, the I/O port address is located at 330hm the arbitration level is set to level 5, the interrupt (IRQ) level is set to 15 and the SCSI address is set to 7.

In the settings for slot #4, that is the Western Digital EtherCard PLUS/A (WD8003/A or WD8003ET/A), the Adapter I/O speace is 280h, the shared RAM space (16 KB) is located at D800h and the interrupt (IRQ) level is set at 3.

Secondly the configuration settings. The settings for the Adaptec AHA-1640 MCA and BusLogic BT-640A adapters found in 86Box Settings > Other peripherals are not configurable...grayed out.

I have found an issue when attempting to configure either the NetWorth Ethernet/MC, Western Digital WD8003E/A or the Western Digital WD8003ET/A, when clicking on Configure found in 86Box Settings > Network, the device configuration is blank and mentioned in this screencap:
![Blank Device Configuration](https://user-images.githubusercontent.com/32658796/63560199-ffe3af80-c509-11e9-810e-3f1a827570a1.png)
Clicking on OK or Cancel has no effect at all.

And lastly when trying to get the Western WD8003ET/A packet driver to work, I type in following at the DOS prompt below:
`smc_wd 0x60 -o 0x3 280 0xD800`

The result is the following in this screenshot below:
![20190822_182644](https://user-images.githubusercontent.com/32658796/63560337-784a7080-c50a-11e9-9ccc-b7902fd05522.png)

Either I didn't configure the packet driver correctly or something appears to be amiss.

We need to find a way how to improve configuration for MCA-based SCSI and network adapters that are currently emulated in 86Box.

Also, look into the issue for the reason why one of the emulated MCA-based network cards that I'm trying to use isn't working right.

Here is the current 86Box.cfg file for the PS/2 Model 80 enclosed in a ZIP file:
[86box.cfg.zip](https://github.com/86Box/86Box/files/3532503/86box.cfg.zip)

Thanks. :)

**Comment by TC1995** [comment]
Well, MCA is like that, there's no need to make it configurable like ISA.

**Comment by ppgrainbow** [comment]
TC1995, if you look at the example documentation for the MCA-based Adaptec AHA-1640 and Western Digital WD8003ET/a the adapters are configurable. Here are the links:

1. http://ohlandl.ipv7.net/SCSI/AHA-1640.html
2. http://www.stack.nl/~marcolz/network/wd80x3.html

If the jumper settings on these MCA adapters were changed, then they would have to changed to match the new jumper settings in the BIOS setup.

**Comment by waltje** [comment]
Correct. Not all MCA boards were fully software-configurable; many had jumpers or switches to
set things, and the system config software had to 'follow' that in those cases.

EISA, on the other hand, was fully software-set, as their I/O addresses were slot-based.

--Fred


     On Friday, August 23, 2019, 1:33:23 PM EDT, ppgrainbow <notifications@github.com> wrote:  
 
 
TC1995, if you look at the example documentation for the MCA-based Adaptec AHA-1640 and Western Digital WD8003ET/a the adapters are configurable. Here are the links:
   
   - http://ohlandl.ipv7.net/SCSI/AHA-1640.html
   - http://www.stack.nl/~marcolz/network/wd80x3.html

If the jumper settings on these MCA adapters were changed, then they would have to changed to match the new jumper settings in the BIOS setup.

**Comment by OBattler** [comment]
I have since fixed the AHA-1640 MCA write handler bugs. And the BIOS does not support x34 addresses, only x30.
