### ISSUE TITLE
Issues creating bootable IDE drives in DOS

### ISSUE THREAD

**Issue by Teppic1** [86Box/86Box#4012]
### What happened?

When formatting an IDE drive under DOS, I'm no longer able to boot. It just hangs. Existing drive images work. I tried different machines with the same result. BIOS settings are correct.

To reproduce:

Fdisk on a drive image.
Make it bootable (e.g. format c: s/)
Reboot

There's no issue in b5111.

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = ibmatami
cpu_family = 286
cpu_speed = 12500000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 512

[Video]
gfxcard = ega

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_ide_channel = 0:0
hdd_01_fn = hdd-900-15-17.img
hdd_01_speed = ramdisk

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
```

### Operating system

Windows 11

### CPU

7800x3d

### 86Box version

5356

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
A BIOS that old isn't going to support IDE. You need to use a MFM or ESDI controller (or AT XTIDE).

**Comment by Teppic1** [comment]
It'll work with an IDE controller added (as I did). The drive can be accessed fine, it just won't boot any more.

However, the exact same problem occurs with newer machines that have internal IDE controllers.

**Comment by Fenix770** [comment]
I had the same issue even on MFM/RLL controller on several machines from XT to 386, with type 9 HDD 1024/15/17. I sems the issue happen on 1024/10/17 HDD (102 mb) and, larger  but only with 17 sectors. HDDs with larger number of sectors (30 to 63)  seems  to work fine on latter machines. I could create a type 9 HDD without issues on build 5000 Win x32.

**Comment by OBattler** [comment]
But I haven't touched any MFM/RLL controller since build 5000 so I have no idea what exactly could have broken it.

**Comment by OBattler** [comment]
Wait... I remember lemondrops made the Settings dialog create hard disk images based on the size in MB rather than the CHS values at some point in 4.0.1, that could have messed it up.

**Comment by lemondrops** [comment]
> Wait... I remember lemondrops made the Settings dialog create hard disk images based on the size in MB rather than the CHS values at some point in 4.0.1, that could have messed it up.

That change actually predates 4.0.1 (build 5111) and 4.0 (build 5000), both of which are confirmed working, so it's unlikely to be the cause.

**Comment by OBattler** [comment]
Can someone please bisect and see which exact build caused this?

**Comment by Teppic1** [comment]
Build 5165 broke things.

https://github.com/86Box/86Box/commit/058391e1485346f70d982d8e6cb585162aa8d47e

**Comment by OBattler** [comment]
If that's the build that introduced it, then it's an IDE bug, and Fenix just used a hard disk image formatted on IDE with the bug, on an XT MFM/RLL controller. Since the bug is when formatting or writing, it would explain why the resulting image then doesn't boot on anything.

**Comment by Teppic1** [comment]
I just tried an image on 5165 with a different sector count (type 17 - 977/5/17) and that did boot ok, while another (non standard) 1023/5/17 didn't.

**Comment by Teppic1** [comment]
Can confirm that if I use the WD1003 AT MFM/RLL controller (with an MFM/RLL drive) there are no problems creating and booting type 9 disks on the current build. It's definitely introduced with the IDE changes in that commit.

**Comment by OBattler** [comment]
Can you upload the NVR folder for the above config, please?

**Comment by Teppic1** [comment]
For the not working IDE or the working MFM/RLL?

**Comment by OBattler** [comment]
For the not working IDE.

**Comment by Teppic1** [comment]
Ok, this is the nvr for config file from the original post (I get the same results with all machines I tried though).

[nvr.zip](https://github.com/86Box/86Box/files/13877769/nvr.zip)
