### ISSUE TITLE
Cursor keys in Rhide (DJGPP C/C++ IDE) causing numeric characters to appear.

### ISSUE THREAD

**Issue by Tape-Worm** [86Box/86Box#4013]
### What happened?

When I press the up arrow several times, eventually the number '8' will appear on the screen. Pressing the down arrow several times also produces the number '2'.  It's almost like it's getting confused with the num pad or something.

### Configuration file

```ini
[WinBox]
window_fixed_res = 960x720

[General]
video_filter_method = 0
vid_cga_contrast = 1
confirm_exit = 0
language = system
vid_renderer = qt_vulkan
confirm_save = 0
confirm_reset = 0
vid_resize = 1
force_43 = 1
window_remember = 1

[Paradise WD90C30-LR]
memory = 1024

[Machine]
machine = px471
cpu_family = i486sx
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
cpu = 2
mem_size = 8192

[Video]
gfxcard = stealth32_vlb
video_fullscreen_scale_maximized = 1

[Input devices]
mouse_type = msserial
joystick_type = 2axis_4button
joystick_0_nr = 1
joystick_0_axis_0 = 1
joystick_0_axis_1 = 0
joystick_0_button_0 = 0
joystick_0_button_1 = 1
joystick_0_button_2 = 2
joystick_0_button_3 = 3

[Sound]
sndcard = sb16
fm_driver = nuked

[Storage controllers]
hdc = ide_vlb_2ch

[Hard disks]
hdd_01_speed = ramdisk
hdd_02_parameters = 63, 16, 1024, 0, ide
hdd_02_fn = 
hdd_02_speed = ramdisk
hdd_01_parameters = 63, 16, 1024, 0, ide
hdd_01_fn = 
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 16
cdrom_01_parameters = 0, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_image_history_01 = 
fdd_01_image_history_01 = D
cdrom_01_image_history_02 = 
cdrom_01_image_history_04 = 
fdd_01_image_history_02 = 
cdrom_01_type = 86BOX_CD-ROM_1.00

[Microsoft Serial Mouse]
port = 0
buttons = 4

[Tseng Labs ET4000/w32p Rev. D VLB]
memory = 1

[Monitor #1]
window_coordinates = 0, 23, 2560, 1299
window_maximized = 1

[Monitor #2]
window_coordinates = 0, 0, 0, 0
```

### Operating system

Windows 11

### CPU

AMD Ryzen 7950x

### 86Box version

4.1.0.5348

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context
This started happening after updating to 86box version 4.1.0.5348.  I've tried with the latest version (4.1.0.5358), and the problem persists.

I tried version 4.1.0.5347 and the 4.0 version here on the github release page and I was not able to reproduce the problem in those versions.

Screenshot of issue
![image](https://github.com/86Box/86Box/assets/9710137/2ebad3d3-0ed8-4872-bc54-c3a6502ce86f)

**Comment by Tape-Worm** [comment]
Just to confirm, I'm only seeing this in this specific application. I tried Turbo Pascal 6, and edit.com (same as qbasic editor), and neither of these applications exhibited the issue.

**Comment by OBattler** [comment]
I can't reproduce this at all.

**Comment by Tape-Worm** [comment]
Just tested it with 5360 and the SiS chipset, works perfectly now.
