### ISSUE TITLE
Sony ATAPI CD-ROM driver v2.19c hangs on Intel Advanced/ZP

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#4014]
### What happened?

When loading the v2.19c Sony ATAPI CD-ROM driver (for instance booting the HP Multimedia 6100 recovery boot disk) on a machine using the Intel Advanced/ZP the system hangs
![Monitor_1_20240108-201017-143](https://github.com/86Box/86Box/assets/47463859/d9b6bc43-4e6a-4900-90fc-b91ce373028b)

Expected behavior is for the driver to load and the system to continue booting

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = zappa
cpu_family = pentium_p54c
cpu_speed = 90000000
cpu_multi = 1.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
cpu = 2
mem_size = 8192

[Video]
gfxcard = px_trio32_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[S3 Trio32 PCI (Phoenix)]
memory = 1

[Hard disks]
hdd_01_parameters = 63, 16, 1726, 0, ide
hdd_01_ide_channel = 0:0
hdd_01_fn = HPMultimedia6100Test.img
hdd_01_speed = 1994_4500rpm

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_type = 86BOX_CD-ROM_1.00
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
fdd_01_fn = C:/Emulators/pcemv16/testing/HPMultimedia6100/HP_REVIVE.img

[Other peripherals]
postcard_enabled = 1
```

### Operating system

Windows 7 SP1

### CPU

Intel Core i7-9700K

### 86Box version

v4.1 build 5359

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

CFG, NVR and boot disk: 
[SonyATAPI.zip](https://github.com/86Box/86Box/files/13868253/SonyATAPI.zip)

Adding a second CD-ROM drive on channel 1:1 works around the issue. Performed a bisect and found the behavior started with build 5143.

**Comment by TC1995** [comment]
Try the latest build, because here it doesn't get stuck using your configuration.
