### ISSUE TITLE
Windows 98 freezes upon attempting to restart it

### ISSUE THREAD

**Issue by BlastBlaster17** [86Box/86Box#4028]
### What happened?

Windows 98 froze on the shutdown screen when I attempted to restart it. After installing Age of Empires, I pressed the Restart button, and when I got to the shutdown screen with the Windows 98 logo on it, it froze.

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = 430vx
cpu_family = pentium_p54c
cpu_speed = 200000000
cpu_multi = 3
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
cpu = 9
mem_size = 131072

[Video]
gfxcard = virge385_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sb16

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0
net_01_card = ne2k
net_01_net_type = slirp

[Storage controllers]
hdc = internal
cassette_mode = load

[Standard PS/2 Mouse]
buttons = 4

[Hard disks]
hdd_01_parameters = 63, 16, 4161, 0, ide
hdd_01_fn = WIN98.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_type = 86BOX_CD-ROM_1.00
fdd_01_image_history_01 = C:/Users/robot/Downloads/Windows98_SE.img
cdrom_01_host_drive = 200
cdrom_01_image_path = C:/Users/robot/OneDrive/Desktop/AOE2AOK
cdrom_01_image_history_01 = C:/Users/robot/Downloads/Windows 98 SE (101 - Retail Full).iso

[Novell NE2000 #1]
mac = d8:6f:bc
```

### Operating system

Windows 11

### CPU

Intel Core i7-1360P

### 86Box version

v4.0.1 Build 5111

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

I've had this problem before.

**Comment by BlastBlaster17** [comment]
By the way, I'm on Windows 98 SE.

**Comment by OBattler** [comment]
This can happen if some driver isn't shutting itself down properly. It's not an 86Box bug.

**Comment by BlastBlaster17** [comment]
Thanks for telling me. I'll investigate this further.
