### ISSUE TITLE
Adaptec AHA-1542 BIOS doesn't detect floppy

### ISSUE THREAD

**Issue by Winins** [86Box/86Box#403]
The Adaptec AHA-1542 BIOS doesn't detect my MS-DOS 6.22 boot disk, any disk in fact.
Here is the image:
![Ek Açıklama 2019-09-03 103637](https://user-images.githubusercontent.com/50794573/64153105-c62e7500-ce36-11e9-8624-ebe689dea87f.png)
Here is the 86Box.cfg file:
[86box.txt](https://github.com/86Box/86Box/files/3568323/86box.txt)

**Comment by daviunic** [comment]
By "MS-DOS 6.22 boot disk", I assume you mean the floppy disk image? In that case, the SCSI controller has nothing to do with it. I see you don't have a floppy drive configured in the system BIOS, so naturally it can't boot from something it doesn't know is there in the first place.

**Comment by Winins** [comment]
But I configured a floppy drive.

**Comment by TC1995** [comment]
You need to configure the floppy drive in the cmos too, not only in the 86box settings.

**Comment by daviunic** [comment]
Not in the Award BIOS, as it clearly says "Diskette Drive A : None", meaning no drive is set. You have to enter the BIOS configuration, set the floppy type, and then save your changes.

**Comment by Winins** [comment]
How can I enter the BIOS config?

**Comment by daviunic** [comment]
> How can I enter the BIOS config?

Read what the screen say during boot.

**Comment by Winins** [comment]
What config should I use for the hard drive?

**Comment by dhrdlicka** [comment]
If it's a SCSI disk, then leave the setting alone. This is for on-board IDE.

**Comment by TC1995** [comment]
The cmos hard disk configuration is only for IDE hdd's, SCSI hard disks have the configuration through the bios of the SCSI adapter.

**Comment by waltje** [comment]
The 1542 series controllers have their own FDC onboard. The 86Box implementation of these cards
ONLY implements the SCSI part, so, even if a 1542 is selected, user still has to configure an FDC of
sorts, and drives.

--Fred


     On Tuesday, September 3, 2019, 4:51:13 AM EDT, David Simunič <notifications@github.com> wrote:  
 
 
By "MS-DOS 6.22 boot disk", I assume you mean the floppy disk image? In that case, the SCSI controller has nothing to do with it. I see you don't have a floppy drive configured in the system BIOS, so naturally it can't boot from something it doesn't know is there in the first place.
