### ISSUE TITLE
SPC-4200P issues

### ISSUE THREAD

**Issue by win3200** [86Box/86Box#405]
I'm using SPC-4200P in 80Box.
SPC-4200P has 82C235 Chipset.
and I have been using UMB_DRVR.SYS 
(UMB_DRVR.SYS converts unused video memory into UPPER memory) 
It does not pass to next step while loading in config.sys
In the past it was available

![image](https://user-images.githubusercontent.com/8305524/64943295-555f7200-d8a6-11e9-91af-7e1fc2414891.png)

and Second Question
in 86Box. I try to launch Borland C++ 3.1 for DOS. But It was failed...

DPMI server initialization error->machine not in database

![image](https://user-images.githubusercontent.com/8305524/64948337-d112ec00-d8b1-11e9-9d90-2aea20c87039.png)

**Comment by dhrdlicka** [comment]
>In the past it was available
Would you mind going through past 86Box builds to see which one broke the UMB driver?

**Comment by win3200** [comment]
Thanks
I don't know past version 
because It's up to date 8 days ago (overwrite)
I understand that UMB_DRVR.sys converts unused Videoram to Upper.
If you want IMG file, I'll send to you with UMB_DRVR.sys  & Config.sys

Model : SPC-4200
Max RAM : 2MB
Video : Hercules Green

**Comment by OBattler** [comment]
Yes, could you please upload the IMG file, as well as the NVR folder and 86box.cfg? That way I can test this and look into what could be going on.

**Comment by win3200** [comment]
Oh Chang Kwon 님이 OneDrive 파일을 공유했습니다. 해당 파일을 보려면 아래의 링크를 클릭하세요.
<https://1drv.ms/u/s!AvhWkQoQMY3rjmQPU1XvMJ9x1CUB>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://1drv.ms/u/s!AvhWkQoQMY3rjmQPU1XvMJ9x1CUB>
86Box_SPC4200.rar<https://1drv.ms/u/s!AvhWkQoQMY3rjmQPU1XvMJ9x1CUB>

Hi~
I send to you my SPC4200 Hard Disk Image in NVR Folder

SPC4200P_C.img : Hard Disk C                       CHS 683/16/38     202MB
SPC4200P_D.img : Hard Disk D, D Drive is empty   CHS 683/16/38     202MB


Machine : Samsung SPC-4200P
Memory : 2048MB (with Base Ram 640KB)
Video   : Hercules (Green) or CGA (Green)


UMB_DRIVER's Chipset Number
82C235 is /c=05


config.sys
set path=c:\;c:\dos;c:\utilitys;c:\utilitys\nc55;c:\utilitys\simcga;c:\v3;c:\zip
devicehigh=c:\utilitys\umb_drvr.sys /C=05
devicehigh=c:\dos\himem.sys /hmamin=64 /numhandles=128 /a20control:on
dos=high,umb
rem devicehigh=c:\utilitys\hecon.sys
files=80


I have a Real Machine Samsung SPC-4200P
Real Machine pass all step on Booting and Video RAM 192KB change Upper Memory

Thanks VERY VERY VERY !!! much~

(^______________^)b












________________________________
보낸 사람: OBattler <notifications@github.com>
보낸 날짜: 2019년 9월 24일 화요일 오후 4:01
받는 사람: 86Box/86Box <86Box@noreply.github.com>
참조: win3200 <win3200@hotmail.com>; Author <author@noreply.github.com>
제목: Re: [86Box/86Box] SPC-4200P issues (#405)


Yes, could you please upload the IMG file, as well as the NVR folder and 86box.cfg? That way I can test this and look into what could be going on.

**Comment by ppgrainbow** [comment]
Have you updated to Jenkins build #1870 to see if the issue persists?

**Comment by OBattler** [comment]
I can now confirm it persists even all the way to the latest build. I have no idea what's going on so far - the driver enables shadow RAM for all the shadow BIOS and UMB areas, which basically makes all those areas writable, but then it's stuck there with blinking cursor.
