### ISSUE TITLE
Trident 8900D 8514A small emulation glitch

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4056]
### What happened?

I found a 8514/A AI driver for the Trident 8900 cards with 1mb from 86box FTP (ppgrainbow). The driver is on "1991" folder.

I tested the mahjong game and Deluxe Paint IV, (because very few DOS apps support the 8514/A mode)

1. The mahjong  game causes a crash when I click on "Special/K" area with CTMOUSE v1.9 but Microsft Mouse v7.04 doesn't have this issue
2. When I do a right click on a tile the background of the menu is always transparent.

![Monitor_1_20240116-112722-361](https://github.com/86Box/86Box/assets/31600563/15f18f3a-d581-4366-a91f-456d6781038e)

On the other hand Paint Deluxe seems to work fine:

![Monitor_1_20240116-112458-537](https://github.com/86Box/86Box/assets/31600563/afd3b1ee-c37f-4cf1-b60b-5140674ddd88)

Here is the CFG ,NVR and HDD file in a single folder:
[386 DX Trident 8900.zip](https://github.com/86Box/86Box/files/13951612/386.DX.Trident.8900.zip)

### Configuration file

```ini
[Trident TVGA 8900D]
memory = 1024

[General]
vid_renderer = qt_software
vid_resize = 1

[Machine]
machine = asus386
cpu_family = i386dx
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu = 2
mem_size = 4096

[Video]
gfxcard = tvga8900d

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 15, 1020, 0, ide
hdd_01_fn = 
hdd_01_speed = ramdisk
hdd_01_vhd_blocksize = 1024
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.0.5399

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Fenix770** [comment]
I know, But PC Paintbrush only include a 1024x768x256 driver for the 8514/A and also the author of the mahjong game, according the readme file, used emulation too, because he argued that the 8514/A card was expensive even in 1991.

**Comment by TC1995** [comment]
But probably didn't use the TVGA8900D.

**Comment by Fenix770** [comment]
He does not say what video card he was using, but he asked to the  possible 8514/A users to report any issue with the game.

**Comment by Fenix770** [comment]
This game works flawlessly on with ET-4000 with RIXAI8 driver. It's only a bit slow.

**Comment by OBattler** [comment]
Closing because #1 is a mouse driver bug and #2 we have no idea if it's even a bug, we'd need some sort of TVGA8900D documentation or a real such card to test.
