### ISSUE TITLE
Many 486 boards allow configuration with internal IDE controller that doesn't exist

### ISSUE THREAD

**Issue by Teppic1** [86Box/86Box#4060]
### What happened?

Almost all of the 486 machines give the option of an internal IDE controller in the emulator settings. Early boards don't have any. Some later models came with a single controller on board, with generally only the last 486 boards having dual controllers.

Looking at the socket 3 machines, the following are incorrect and have no onboard controllers in reality:

AOpen Vi15G
ASUS 486SV2G (GX4)
DTK PKM-0038S E-2
Epox 486SX/DX Green
MSI MS-4134
J-Bond PCI400C-B
Tekram G486IP

And these machines should only have a single IDE controller on board:

ASUS PVI-486AP4
Intel Classic/PCI ED
ASUS PCI/I-486SP3
ASUS PCI/I-486SP3G

I haven't looked at the earlier socket boards.

### Configuration file

```ini
N/A
```

### Operating system

N/A

### CPU

N/A

### 86Box version

5403

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Example, this ASUS board clearly has no IDE controllers. The manual tells you you have to install an IDE controller into a slot to use IDE. The emulator however allows you to invent an internal controller.

https://theretroweb.com/motherboards/s/asus-vl-i-486sv2gx4

**Comment by TC1995** [comment]
Depends on the bios used.

**Comment by Teppic1** [comment]
The machines physically don't have on board IDE controllers, so how can it depend on the BIOS?

**Comment by OBattler** [comment]
I actually agree TC1995's answer here is wrong. The fact is, a lot of these machines were added before the advent of TheRetroWeb and their plethora of board pictures. I'm going to go through this later tonight and fix them.

**Comment by Teppic1** [comment]
> 
> Fact is... 86Box is an emulator not the physical machine per se, if the BIOS has support for the feature, then, that feature could be emulated.

86Box is aiming (in general) to emulate specific machines along with their limitations though. A bit of a side point but every 286 or later PC supports IDE in the BIOS, as it was designed to be software compatible with the IBM AT. So there's support for it in the BIOS before it existed - and that wouldn't make sense to emulate (unless you add on the necessary card).

**Comment by OBattler** [comment]
Actually, what those old BIOS'es tend to support is the AT MFM/RLL interface which happens to be reasonably compatible with IDE since IDE is, through ESDI, descended from it.

**Comment by Teppic1** [comment]
That's basically what I meant - because IDE was originally designed to be software compatible with the AT interface, the older BIOSes work with it directly meaning you can use an IDE interface card in an ancient 286 and it'll work without any added BIOS etc.
