### ISSUE TITLE
Windows 3.0 Crash with IBM 8514/a adapter

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4066]
### What happened?

I did a clean installation of  DOS 5.0 with Windows 3.0 and the 8514/a driver. The setup crash during installation with the 8514/a driver. I had the same issue with other VM with PC-DOS 4.0. I also happens if I change from VGA to 8514/a driver once Windows is installed.

NOTE: I did the installation with standard VGA driver

CFG,NVR and HDD image file:
[386 - Win 3.0 -IBM 8514.zip](https://github.com/86Box/86Box/files/13982519/386.-.Win.3.0.-IBM.8514.zip)

### Configuration file

```ini
[Standard PS/2 Mouse]
buttons = 2

[General]
vid_renderer = qt_software
vid_resize = 1
enable_overscan = 1
rctrl_is_lalt = 1

[Machine]
machine = spc6033p
cpu_family = i386sx
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = internal
8514a = 1

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 26, 7, 1024, 0, ide
hdd_01_fn = 
hdd_01_speed = 1992_3600rpm
hdd_01_vhd_blocksize = 1024
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.0.5402

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
Screenshot of the crash?

**Comment by Fenix770** [comment]
It shows only a gray line on the upper part of the screen
![Monitor_1_20240118-202404-876](https://github.com/86Box/86Box/assets/31600563/38f606de-ec06-401b-9a8a-1378b2bbee94)

**Comment by Fenix770** [comment]
PD: Is the first Windows 3.0 (not 3.0a)

**Comment by Fenix770** [comment]
This screenshot was taken after load HDILOAD and then HDIDEMO there are two color cycling lines:
![Monitor_1_20240118-203424-093](https://github.com/86Box/86Box/assets/31600563/db9bcaae-4613-47d8-a8d3-ab6d212e0a88)

**Comment by Fenix770** [comment]
Wait: The HDIDEMO works fine if I instalad and load it from the HDD.

Question the HDILOAD is now required to use the Windows 8514/a driver?

Now Windows 3.0 works, but only with the HDILOAD driver loaded.
![Monitor_1_20240118-204258-529](https://github.com/86Box/86Box/assets/31600563/3b28af48-8d18-4d64-aa88-d83946dbddf6)

**Comment by TC1995** [comment]
It's a mistake of mine when it's with HDILOAD disabled.

**Comment by Fenix770** [comment]
Now the Mahjong 8514 game does not work.
![Monitor_1_20240118-205324-327](https://github.com/86Box/86Box/assets/31600563/ebe47ba4-d457-4896-bd9e-62b44bdc871b)

**Comment by TC1995** [comment]
I've told you it's a mistake of mine and will be fixed...
