### ISSUE TITLE
MSD (MSDOS 6 utility) causes crash with IBM XT (1986)

### ISSUE THREAD

**Issue by Teppic1** [86Box/86Box#4069]
### What happened?

When choosing IRQ status the computer freezes.

This doesn't happen with any of the other XT clones I tried.

There's also no problem with the IBM XT (1982) with a memory card added (which is needed as you can't run msd in 256kb), so perhaps the issue is related to how motherboard memory is configured on the 1986 XT.

### Configuration file

```ini
[General]
vid_renderer = qt_software
force_43 = 1

[Machine]
machine = ibmxt86
cpu_family = 8088
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu = 5
mem_size = 640

[Video]
gfxcard = cga

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 35_2dd
fdd_01_turbo = 1
fdd_01_fn = boot-dos6.img
fdd_01_writeprot = 1
```

### Operating system

Windows 11

### CPU

7800x3d

### 86Box version

5405

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Bootable DOS floppy with MSD included

[boot-dos6.zip](https://github.com/86Box/86Box/files/13999128/boot-dos6.zip)

**Comment by TC1995** [comment]
Why are you using the speed of 16Mhz anyway, just use anything at 10Mhz or lower.

**Comment by TC1995** [comment]
Anyway, bisect if it worked previously.

**Comment by Teppic1** [comment]
Because it's faster to test things. The problem happens at 4.77MHz as well.

**Comment by TC1995** [comment]
> Because it's faster to test things. The problem happens at 4.77MHz as well.

Except 16Mhz might be unreliable on XT's, don't believe too much on it.

**Comment by Teppic1** [comment]
> Anyway, bisect if it worked previously.

I don't know if it worked before and I don't have time. I've confirmed the bug and I've already spent a couple of hours today tracking down a different issue.

**Comment by TC1995** [comment]
> > Anyway, bisect if it worked previously.
> 
> I don't know if it worked before and I don't have time. I've confirmed the bug and I've already spent a couple of hours today tracking down a different issue.

Just bisect when you can.

**Comment by Teppic1** [comment]
I tried on 86Box 2.0 and it crashes there too.

I don't have pcem installed so I can't test that.

**Comment by TC1995** [comment]
Does it work on real hardware as well?

**Comment by OBattler** [comment]
PCem doesn't emulate the 1986 XT.

**Comment by Teppic1** [comment]
> Does it work on real hardware as well?

I don't have an XT to try it on but I tried googling and couldn't find anything at all about crashes with MSD on an XT.

I tried it on the emulated original PC too and it works fine there (as well as the 1982 XT).

**Comment by Teppic1** [comment]
I don't know if this is related, but vdisk.sys from IBM DOS 3.3 is failing on the machine too with this error

"Extender card switches do not match the system memory size"

Explanation: VDISK. The extender card switch settings
do not reflect the total amount of memory in the system
unit. Although the extender card switch settings may be
set correctly for your system, VDISK does not support
memory in an expansion unit. 

It works fine on XT clones.

**Comment by waltje** [comment]
It does on mine, but that has a V20, not an 8088.

    On Saturday, January 20, 2024 at 03:50:13 PM EST, TC1995 ***@***.***> wrote:  
 
 


Does it work on real hardware as well?

**Comment by dbalsom** [comment]
Tested MSD 2.21 and 3.01 on martypc's IBM5160, looks to me like a BIOS compatibility issue. It works with GLaBIOS on the same hardware profile, works with the '82 BIOS, but fails with the 5/9/86 IBM BIOS, just as reported.

Also works on a real 5150, in both DOS 3.30 and 6.22 (I don't think DOS version matters)

all CPUs involved are 8088 at 4.77Mhz

looking at how it freezes, it's stuck doing recursive calls somewhere in int 10h, which certainly adds weight to the BIOS issue.  There's no real difference to how memory is configured between the BIOS revisions. The main thing added in '86 was support for IBM's extended keyboard. 

Most XT clones would have based their ROMS off the '82 version , so probably didn't "acquire" whatever bug IBM introduced in '86.

**Comment by OBattler** [comment]
@waltje Does your XT have the 1986 BIOS? If yes, then perhaps IBM added some V20 instructions.

**Comment by waltje** [comment]
No, but its based on that.  One of the better "brand" clones (DTK) at 10MHz with a V20.  BIOS i think is 187-ish.

   On Saturday, January 20, 2024 at 08:00:55 PM EST, Miran Grča ***@***.***> wrote:  
 
 


@waltje Does your XT have the 1986 BIOS? If yes, then perhaps IBM added some V20 instructions.

**Comment by OBattler** [comment]
It appears that the problem is specific to the IBM XT 1986 BIOS (MSD hangs on it regardless of CPU), though it also affects Sergey Kiselev's Book8088. Definitely a BIOS bug then.

**Comment by Teppic1** [comment]
Ok, the vdisk bug is unrelated then - I'll make a separate report on that.
