### ISSUE TITLE
The image on SuperEGA and EGA video cards is even more damaged

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#4072]
### What happened?

Compared to problem #3829, the image on SuperEGA and EGA video cards is even more damaged.

1. On the SuperEGA video card, when starting the machine during a memory test and then, distortion of the image on the text is noticeable, as if the monitor was damaged by interference.

![Monitor_1_20240121-131159-886](https://github.com/86Box/86Box/assets/58270614/d0b84a0e-2028-4049-92a4-f336cf0a9de2)

2. When launching Prince of Persia, artifacts are noticeable in the form of a vertical line on the right of the screen and the image is cut off to one vertical line on the left of the screen.

Build 5363 (There is a bug):
![Monitor_1_20240121-134049-074](https://github.com/86Box/86Box/assets/58270614/a8539029-77c2-40ce-ada5-f1c725526951)

Build 5360 (There is no bug):
![Monitor_1_20240121-134008-658](https://github.com/86Box/86Box/assets/58270614/639d5723-8c0f-4f54-8938-e66b92ccd890)

3. On the EGA video card, when launching CGA games, artifacts are noticeable in the form of a vertical line on the right of the screen and the image is cut off by one vertical line on the left of the screen:

![Monitor_1_20240121-134818-997](https://github.com/86Box/86Box/assets/58270614/aab7d19b-f067-44f5-9b12-436e01214d63)
![Monitor_1_20240121-134828-402](https://github.com/86Box/86Box/assets/58270614/45906f94-f3d9-4913-a45f-036653879334)
![Monitor_1_20240121-134840-606](https://github.com/86Box/86Box/assets/58270614/966979a0-4122-4932-abff-531b250736bb)

This bug appeared in build 5363 and persists until the latest build. In build 5360 everything works fine.

### Configuration file

```ini
[Machine]
machine = jukopc
cpu_use_dynarec = 0
time_sync = local
cpu_enable_fpu = 1
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
fpu_type = 8087
fpu_softfloat = 0
mem_size = 640

[CGA]
display_type = 0
composite_type = 0
rgb_type = 0
snow_enabled = 0

[General]
vid_renderer = qt_opengl
window_remember = 1
vid_resize = 1
force_43 = 1
vid_cga_contrast = 1
confirm_exit = 0
video_fullscreen_first = 0
confirm_reset = 0
confirm_save = 0

[Video]
gfxcard = superega

[Input devices]
mouse_type = msserial
joystick_type = 2axis_2button
joystick_0_nr = 0
joystick_1_nr = 0

[Sound]
fm_driver = nuked

[Hard disks]
hdd_01_parameters = 17, 4, 306, 0, ide
hdd_01_fn = images/DOS.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Storage controllers]
hdc = xtide_acculogic
cartridge_01_fn = G:/Temp/86Box/
cartridge_02_fn = G:/Temp/86Box/

[Other peripherals]
postcard_enabled = 1

[Monitor #1]
window_coordinates = 412, 31, 1736, 1292

[Monitor #2]
window_coordinates = 412, 31, 1736, 1292

[Floppy and CD-ROM drives]
fdd_02_type = none

[Microsoft Serial Mouse]
port = 0
buttons = 4
```

### Operating system

Windows 10 Pro x64 v22H2

### CPU

Core i9-10900K

### 86Box version

v4.1 Build 5407

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Teppic1** [comment]
> 1. On the SuperEGA video card, when starting the machine during a memory test and then, distortion of the image on the text is noticeable, as if the monitor was damaged by interference.
> 
This happens with the setup screen with the regular EGA card as well. It looks normal on the post screen.

![H0z1KRd](https://github.com/86Box/86Box/assets/32468801/35695821-1f39-4228-802c-838c42ba392d)

**Comment by OBattler** [comment]
It works fine in 5360... what about 5361 and 5362?

**Comment by maximus105** [comment]
Builds 5361 and 5362: The machine with an EGA or SuperEGA video card does not start (crashes) at all.

**Comment by OBattler** [comment]
What version of Prince of Persia is that? 1.4 doesn't support EGA.

**Comment by iamgreaser** [comment]
The extra column on the right was due to me correcting how horizontal fine scroll works but forgetting to get it fully sorted out for graphics modes. In theory, text modes should be fine. I can at least sort that part out.

**Comment by iamgreaser** [comment]
OK, the wobbling was actually due to that particular BIOS spamming the CRTC to change the cursor settings constantly, which called `ega_recalctimings()` a lot, which kept resetting `x_add` to something which didn't factor in `scrollcache`, so you'd have scanlines which were treating `scrollcache` as if AR13 were set to `0x08`.

**Comment by maximus105** [comment]
> What version of Prince of Persia is that? 1.4 doesn't support EGA.

v1.0
