### ISSUE TITLE
Build 1845: Amstrad PC ISSUES

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#408]
A great job have been done with the last commit, but somes issue remains:

PC1512: do not show in configuration. Tried different set of ROMS,no way
PC1640: 
POST screen do not show (Please WAIT..... do no show, only, black screen) so that user can think that it's not working
Mouse is tooo fast with the latest AMOUSE.COM 7.0.4 driver  from Amstrad
Mouse not working at all with GEM3 with latest driver AMOUSE.COM 7.0.4

Ctrl-Alt-Del not working, even auto reboot like at the end of fdisk,windows installation,  etc, so that i need to use Hard Reset

Looks like the HD Activity LED do not work anymore in XT-IDE emulation (HD icon is grayed). Not always ??

No PPC emulation ?

**Comment by OBattler** [comment]
PC1512: Look at the source code (machine/m_amstrad.c) to see how the BIOS files are supposed to be named.
PC1640: It used to work, I'll look into it.
Mouse: Can you upload the GEM VM so I can test this?
Ctrl+Alt+Del: I believe these are 808x'es, so the only way to soft reset would be to jump to to the correct BIOS address, but I'll look into why that happens.
HD Activity LED with XT-IDE: I'll look into that, the bug is probably in ide.c because it always assumes AT IDE for the icon.
PPC: It's there, again look at the source code (machine/m_amstrad.c) to see how the BIOS files are supposed to be named.

**Comment by jvernet** [comment]
For the ROM jnaming, it's OK, I managed to get the correct name, it's working for PC1512 and PPC1512

**Comment by jvernet** [comment]
Link to the GEM 3 VM (PC1640)
[https://1drv.ms/u/s!AqJtoKddDxv2q0nyD7j6tSQWydAf?e=VBxPCL](url)

**Comment by OBattler** [comment]
Would be be possing to have 86box.cfg and the nvr folder as well?

**Comment by jvernet** [comment]
Here is the link:
[https://1drv.ms/u/s!AqJtoKddDxv2q0t2qUtwFd-fZ-2F?e=0O04xj](url)

At least , it do not crash anymore with GEM.

One more issue: PPC1512 and PPC1640 are not the same machine. one have a CGA monitor while the other have an EGA monitor. ROMS aren't the same.

**Comment by OBattler** [comment]
They do not use the same ROM's. I am going to provide an updated ROM set soon with all the required files.

**Comment by Altheos** [comment]
> 
> 
> Here is the link:
> [https://1drv.ms/u/s!AqJtoKddDxv2q0t2qUtwFd-fZ-2F?e=0O04xj](url)
> 
> At least , it do not crash anymore with GEM.
> 
> One more issue: PPC1512 and PPC1640 are not the same machine. one have a CGA monitor while the other have an EGA monitor. ROMS aren't the same.

I think there's confusion between PP512/PP640 and PC1512 and PC1640. PPC512/640 are "portable" computers with CGA monochrome LCD display (one with 512 Kb RAM, the other 640 Kb).
PC1512 was the entry-level computer equipped with CGA graphics card, EGA for PC1640.

**Comment by OBattler** [comment]
Altheos> That makes sense. Yeah, the PPC's are portable, so I don't even see how one of them would have an EGA monitor. :p

Also, the PC1640 seems to work fine on my end, at least with my test VM (haven't tried the one given here yet).

**Comment by OBattler** [comment]
OK, I indeed get black screen now if the graphics card is set to Internet. I'm now looking at what that is.

**Comment by OBattler** [comment]
Display on POST fixed and committed, now to see why the mouse is having problems.

**Comment by OBattler** [comment]
The mouse has the same behavior on VARCem and I have no idea on how to fix that (is there any documentation for the Amstrad mouse?), and I don't think it works even on PCem (as the mouse code is the exact same).

As for CTRL+ALT+DEL / soft reset, I have no idea how to fix that, either, or even what's causing the problem.

**Comment by TC1995** [comment]
Hmmm, a fresh GEM 3.0 installation on a PC1640 with mouse.com 5.00 or 7.04 works here, but the 7.04 driver from amstrad is a bit jumpy.

**Comment by jvernet** [comment]
Yes, latest build make GEM 3 work. But the mouse pointer is too fast, even if you set accel parms via NVR.

**Comment by TC1995** [comment]
This issue doesn't happen on amstrad mouse.com driver 5.00, just only on 7.04, and yes, need to see what it expects.

**Comment by OBattler** [comment]
Could it be a raw input problem? I believe PCem now uses SDL Input for mouse which might use DirectInput as the backend. 86Box and maybe VARCem use raw input.
