### ISSUE TITLE
Olivetti M21/24/24 SP issues

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4086]
### What happened?

I tested the Olivetti M21/24/24 SP. I found two main problems.

1. The keyboard seems to have issues with the keys convinations. (keys are not correct) SHIFT+ a letter behaves as CONTROL+ a letter 

2. The machine supported 1 HD floppy drive and a second double density, but only detects the floppy drives as 360kb even the 3.5 720kb. (btw Tested the 5,25 1.2 Mb format; the 3.5 1.44 format is not supported o DOS 3.20) 

3. There is a fixed space, on the  keyboard cursor, after the DOS prompt.

I managed to install Windows 1.03 from 360kb floppy disks

Here is, CFG, VM and HDD image file:
[Olivetti M-240  2024.zip](https://github.com/86Box/86Box/files/14069261/Olivetti.M-240.2024.zip)

### Configuration file

```ini
[Olivetti M21/M24/M28 (GO317/318/380/709) video card]
rgb_type = 1
snow_enabled = 0

[General]
vid_renderer = qt_software
vid_resize = 1
rctrl_is_lalt = 1
enable_overscan = 1

[Machine]
machine = m24
cpu_family = 8086
cpu_speed = 8000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu = 1
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = internal

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = text_prt

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 4, 612, 0, mfm
hdd_01_fn = 
hdd_01_vhd_blocksize = 4096
hdd_01_mfm_channel = 0

[Floppy and CD-ROM drives]
fdd_02_type = none
fdd_01_check_bpb = 0
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.0.5422

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
The emulated keyboard is an Olivetti 102-key keyboard which is very different from the standard one.

As for the floppy drives - the M24 only supports 360 kB and 720 kB, and both drives must be of the same type - the switches do not support type mixing.

**Comment by OBattler** [comment]
The extra space is because you put an extra space after PROMPT $P$G.

**Comment by OBattler** [comment]
Also, Norton Safe Format may not be Olivetti-compatible. I remember from my tests that auto-detection doesn't work on those BIOS'es at all, and you have to manually tell even DOS FORMAT to format 720k.
