### ISSUE TITLE
[Question] MFM and RLL controllers

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#410]
¡Hello!

Thanks for the latest improvement and fixes.

In the latest commit The Xebec and DTC MFM controllors does not appears anymore.
a generic MFM/RLL  controller appear on AT and later machines .
I don't know if new roms are required for these controllers. Also the image files created for MFM have different geometry than the IDE.

Thanks!

**Comment by TC1995** [comment]
Most likely the rom path has changed, they still appear on my end (latest build).

**Comment by OBattler** [comment]
Yes, the ROM paths have changed from the last Jenkins builds. I am going to provide an updated ROM set soon.

**Comment by daviunic** [comment]
Not an issue with the emulator itself, so closing.
