### ISSUE TITLE
Some 486 EIDE board don't support the second IDE channel

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4107]
### What happened?

I installed Windows 3.1 and tried the SiS 497 chipset with SiS bus mastering drivers for DOS and Windows 3.x

Issues I found:

1. The machine recognize the HDD drive always as "Mode 0" (PIO 0) but the chip support up to PIO 4 on BIOS setup utulity
The SiS IDE driver also recognizes it "as mode 0"

2. The driver  utility program does not recongnize the second IDE channel.

3. I added a CD-ROM drive as primary slave, and a IOMEGA ZIP drive. The ZIP drive is not recognozed either as seconary master o secondary slave. I tried two different versions of IOMEGA GUEST utility (v 3.02 and 4.12).

The machines I tested and the seconf IDE channel do not work are:

1.The ASUS PVI-486PSP3C (SiS 496) bot with and Without the IDE drivers.
2. Epson Action PC 2600 (UMC 8881) (without drivers since is a different chipset)

Works:
1. Epson Action Tower 8400 with Windows 95 (it seems to support some kind of bus mastering since Win 95 has a IDE/ESDI device recongnized)

Screenshot:
![Monitor_1_20240201-113943-364](https://github.com/86Box/86Box/assets/31600563/4821e8aa-3425-44f4-b845-e53bb5687377)

Here is the CFG,VM and HDD image file:
[486 SiS 496-97.zip](https://github.com/86Box/86Box/files/14127779/486.SiS.496-97.zip)

Here is the SiS device driver:
[SiS 496-7 IDE driver.zip](https://github.com/86Box/86Box/files/14126955/SiS.496-7.IDE.driver.zip)

Here is the IOMEGA Win 3.x driver:
[Zip Install 3.02.img.zip](https://github.com/86Box/86Box/files/14126975/Zip.Install.3.02.img.zip)

### Configuration file

```ini
[S3 Trio32 VLB (Phoenix)]
memory = 2

[Sound Blaster ViBRA 16S]
base = 0220
base401 = 0330
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[General]
vid_renderer = qt_software
vid_resize = 1
rctrl_is_lalt = 1

[Machine]
machine = 486sp3c
cpu_family = am486dx2
cpu_speed = 50000000
cpu_multi = 2
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 16384

[Video]
gfxcard = stealthse_pci

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sb_vibra16s
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = text_prt

[Storage controllers]
hdc = internal
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_speed = 4
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200

[Other removable devices]
zip_01_parameters = 0, atapi
zip_01_ide_channel = 1:0

[Hard disks]
hdd_01_parameters = 63, 16, 1024, 0, ide
hdd_01_fn = 
hdd_01_speed = 1996_5400rpm
hdd_01_ide_channel = 0:0

[Standard PS/2 Mouse]
buttons = 3

[S3 Trio32 PCI (Phoenix)]
memory = 2

[S3 Trio32 VLB (Diamond Stealth SE)]
memory = 2
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.0.5437

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Teppic1** [comment]
https://github.com/86Box/86Box/issues/4099

Possibly related?

**Comment by OBattler** [comment]
The 888x stuff I'm already looking it (there's also IDE weirdness with the Samsung SPC 7700 LP-W), as for the SiS 496/497 - try a non-PnP Sound Blaster 16, perhaps the board is erroneously making the PnP's IDE controller collide with the secondary IDE controller.

**Comment by Fenix770** [comment]
This version has issues with EMM386. GUEST freezes with it installed. I think some kind of bug exists.

The GUEST utility v 4.12 seems to work fine under MS-DOS mode on Windows 95. But Win 9x is a  Plug & Play OS.

![Monitor_1_20240202-225829-943](https://github.com/86Box/86Box/assets/31600563/c4d49742-07e8-42cf-82ca-b58529b36bf1)

**Comment by Fenix770** [comment]
Also the Windows 3.1 driver for the SiS 496/7 IDE ports, also, crash with EMM386 installed or with CD-ROM driver for that reason I unistalled the driver.

**Comment by OBattler** [comment]
I believe earlier versions of IOMEGA Guest Tools only recognize non-ATAPI IDE ZIP (yes, that was a thing!) and not ATAPI ZIP.

**Comment by OBattler** [comment]
Also, the hard disk you chose fits within the CHS parameters, so it gets presented as an ATA-3 non-LBA drive that maxes out at PIO 0, so that's not a bug, either.

**Comment by OBattler** [comment]
On the Epson Action Tower 2600, you need to go to Adv. HDD and specify the number of hard disks attached to secondary IDE. Without that, it will keep secondary IDE deactivated.

**Comment by OBattler** [comment]
On the ASUS, go to Chipset Feature Setup, and make sure Onboard Local Bus IDE is set to Both.

**Comment by OBattler** [comment]
Also, in Standard CMOS Setup, make sure none of the IDE devices is set to None.

**Comment by Fenix770** [comment]
Well, The CD-ROM driver is correctly recognized as secondary master, and the ATAPI ZIP, as primary slave it is only recognized with ver 5.5. So maybe you are right!

So the only issue  maybe the Win 3.1 IDE driver for the SIS 496/7.

**Comment by OBattler** [comment]
I don't think Windows 3.1 drivers recognize ZIP drives.

**Comment by Fenix770** [comment]
PD: There are Win 3.x driver for IOMEGA ZIP but maybe they are only for SCSI. On Windows 3.x,the GUEST.EXE utility must be loaded from DOS before loading Windows.

**Comment by Fenix770** [comment]
I found a version that works!
The drivers launched in 1997 works fine on Windows 3.1 with ATAPI drives!. It includes a DOS GUEST utility that is version 4.12, like the included in the 1996 driver set but this works!
![Monitor_1_20240203-011135-189](https://github.com/86Box/86Box/assets/31600563/85f9fce1-2f60-466d-b214-9d89a2d88d0a)

**Comment by Fenix770** [comment]
PD: This 1997 version, also works with EMM386 installed!
![Monitor_1_20240203-011511-831](https://github.com/86Box/86Box/assets/31600563/1a832872-32e0-4093-95d3-48ce9ffcc003)

**Comment by OBattler** [comment]
@Fenix770 Can you post the working drivers here, please?

Also, I think this can be closed then.
