### ISSUE TITLE
86Box doesn't work under WindowsXP SP3 version.

### ISSUE THREAD

**Issue by coolhaken** [86Box/86Box#412]
Hi,
I am still using WindowsXP SP3, so I wish 86Box will continue work under it.
However, when I launched 86Box(1847) under my WindowsXP Chinese version,
I got an system error message and 86Box didn't start.
It says "Unable to find program entry point GetTickCount64( in dynamic link library KERNEL32.dll)"
Please help me to see what the problem is, thank you.

**Comment by TC1995** [comment]
I believe WinXP host support has been dropped.

**Comment by dhrdlicka** [comment]
Indeed, the consensus for Windows XP host support was 86Box would remain compatible at a best-effort basis. This use case isn't officially supported nor encouraged.

**Comment by OBattler** [comment]
It's caused by the upgrade of GCC to 9.2.0-2, it seems GCC 9.x defaults to the Vista and later API, and no longer to the XP API. I can provide Windows XP binaries for a while, but there will be no official support for Windows XP.

**Comment by ACompExp** [comment]
Well, it worked for me though on Home Edition. Except that the machine doesn't automatically shut down (most probably for the lack of ACPI) + there are some lags.

**Comment by c0deHunters** [comment]
> It's caused by the upgrade of GCC to 9.2.0-2, it seems GCC 9.x defaults to the Vista and later API, and no longer to the XP API. I can provide Windows XP binaries for a while, but there will be no official support for Windows XP.

Dear OBattler,
Would you kindly provide Windows XP binaries? The reason that I am asking for the XP is the fact that I would like to run 86Box in 640x480 resolution, and create older DOS bases virtual machines, and my Samsung SyncMaster MB1763 CRT monitor can produce nice looking scanlines under this resolution. 
I really appreciate it!

**Comment by OBattler** [comment]
Unfortunately, we are not able to do that - we use Qt, versio 5.x at minimum, which does not support Windows XP hosts.

**Comment by c0deHunters** [comment]
Thanks for your comment, but I meant to post links to the older versions that *did* support for XP. I am not asking for latest builds with XP support. Many thanks in advance!

**Comment by OBattler** [comment]
The last time we supported XP host, was at some point in 2017, I believe by the first build currently available on our Jenkins, ie. 885 (the rest unfortunately got lost in the Great Journal Mess-up(TM) of 2017, caused by me), while it still runs on XP, it has a problem with configuration files because they're UTF-16 which XP does not support.
