### ISSUE TITLE
Problems with SGDT LGDT instructions

### ISSUE THREAD

**Issue by lgj1107** [86Box/86Box#4121]
### What happened?

According to Intel's manual, lgdt ax, lgdt cx, etc. are UD, but 86box can execute normally.

In addition, the 86box is configured with 386dx and can execute 486 instructions, such as xadd wbinvd and other instructions

<img width="636" alt="73E5CC7F7A6741D7FF523F139568CB75" src="https://github.com/86Box/86Box/assets/3366897/6e66cb79-2ac7-4470-b02e-a029659bd399">

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
language = system
vid_resize = 2
window_fixed_res = 1024x768
force_43 = 1

[Machine]
machine = acc386
cpu_family = i386dx
cpu_speed = 40000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 8192

[Video]
gfxcard = cl_gd5420_isa

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 853, 0, ide
hdd_01_fn = D:/image/dos.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
fdd_01_image_history_01 = D:/image/386bsd00.img
```

### Operating system

window 10

### CPU

R7-5700G

### 86Box version

v4.1 build 5455

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Which manual states that's UD#? This implies it's not: https://www.felixcloutier.com/x86/sgdt .

**Comment by OBattler** [comment]
And this, too: https://www.felixcloutier.com/x86/lgdt:lidt .

**Comment by lemondrops** [comment]
<http://bitsavers.org/components/intel/80386/230985-003_386DX_Microprocessor_Programmers_Reference_Manual_1990.pdf>, page 480:

> Interrupt 6 if the destination operand is a register
