### ISSUE TITLE
SOYO 4SAW2 CPU options incorrect

### ISSUE THREAD

**Issue by Teppic1** [86Box/86Box#4122]
### What happened?

The machine has removed most of the compatible processors for no apparent reason.

Also should be called SY-4SAW2.

https://theretroweb.com/motherboards/s/soyo-sy-4saw

(Same board as -2)

### Configuration file

```ini
N/A
```

### Operating system

Windows 10

### CPU

i7 7500

### 86Box version

5461

### Build architecture

Windows 64 bit

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by lemondrops** [comment]
The CPUs were removed because the BIOS refuses to POST with them selected.

**Comment by Teppic1** [comment]
Buggy BIOS maybe? The board definitely supports them.

**Comment by Teppic1** [comment]
According to the notes on retroweb

BIOS version WA0911 might not work properly with certain revisions of the board, causing the boot to hang at "Updating ESCD", "Building ESCD" or "Verifying DMI Pool Data". In this case, use version WA53.

This is the BIOS version that 86Box is using.

**Comment by cartifanwlr** [comment]
If it's not the BIOS, then it's either;
* The board really doesn't support these CPUs.
* There is an emulation inaccuracy on our end that breaks the detection of these CPUs. (less likely)
Either way, I think this should be tested on real hardware if the BIOS isn't the culprit.

**Comment by OBattler** [comment]
The latest commit fixes and re-enables the Cyrix'es on this machine. As for the non-SMM cpu's - that's going to have to wait for 4.2, when we're goijng to be more thoroughly adding support for machine BIOS selection, so we can allow selecting an earlier BIOS revision.

**Comment by Teppic1** [comment]
Wouldn't it be better to switch to the non-buggy BIOS as default?

Or in the meantime allow selection of all the CPUs the board supports even if the default BIOS has issues with some of them.

**Comment by cartifanwlr** [comment]
> Wouldn't it be better to switch to the non-buggy BIOS as default?
> 
> Or in the meantime allow selection of all the CPUs the board supports even if the default BIOS has issues with some of them.

The WA0911 revision, buggy as it is, **actually supports CD boot.** It's why we use this specific revision by default.
