### ISSUE TITLE
LOCK Prefix is incorrect in 386 protected mode

### ISSUE THREAD

**Issue by lgj1107** [86Box/86Box#4132]
### What happened?

<img width="609" alt="7B2F813E0E05DDFB2223004DB730316D" src="https://github.com/86Box/86Box/assets/3366897/acdde8d6-f455-4423-a746-d5c8fe5c6bd4">

> An exception 6 will be generated if a LOCK prefix is
placed before any instruction form or opcode not
listed above. The LOCK prefix allows indivisible
read/modify/write operations on memory operands
using the instructions above.

86box can use the lock prefix in most instructions(Protection mode). For example:
lock mov eax，1
lock mov eax,cr0
lock mov eax,tr3
, etc.

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
language = system
vid_resize = 2
window_fixed_res = 1024x768
force_43 = 1

[Machine]
machine = acc386
cpu_family = i386dx
cpu_speed = 40000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 8192

[Video]
gfxcard = cl_gd5422_isa

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 853, 0, ide
hdd_01_fn = D:/image/dos.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
fdd_01_fn = D:/image/a.img
fdd_01_image_history_01 = D:/image/386bsd00.img
```

### Operating system

window 10

### CPU

R7-5700G

### 86Box version

v4.1 build 5470

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
I believe right now, we treat it as a simple prefix.

**Comment by OBattler** [comment]
Which instrunctions exactly are meant by BIT Test and SET/RESET/COMPLEMENT ?

**Comment by OBattler** [comment]
OK, found another table here: https://pdos.csail.mit.edu/6.828/2008/readings/i386/LOCK.htm .
