### ISSUE TITLE
IBM AT Issue (ERROR with AT Diag SETUP)

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#414]
Never tried before with 86Box, but IBM AT SETUP Disk (version 1, 2,00, 2.02, 2.07) crash. Cannot configure IBM AT so unusable.

BATTERY ERROR, MAINBORAD ERROR, etc...

**Comment by OBattler** [comment]
Could you upload these SETUP Disks, so I can debug the issue?

**Comment by jvernet** [comment]
You can find them here:
[https://winworldpc.com/product/ibm-pc-diagnostics/at-2x](url)

> [Machine]
machine = ibmat
cpu = 1
mem_size = 1024
cpu_use_dynarec = 0
cpu_enable_fpu = 1
time_sync = local

[Video]
gfxcard = ega

[Input devices]
mouse_type = msbus

[Sound]
sndcard = sb1.5

[Other peripherals]
hdc = st506_at

[Floppy drives]
fdd_01_type = 525_2hd
fdd_02_type = 35_2hd
fdd_01_turbo = 1
fdd_02_turbo = 1
fdd_01_fn = C:\Users\Jerome\Desktop\Disks\IBM - Diagnostics for IBM Personal Computer AT 2.07 (5.25-360k)\ATDiags102.img

[General]
force_43 = 1

[Hard disks]
hdd_01_parameters = 17, 15, 1023, 0, mfm
hdd_01_fn = C:\Users\Jerome\Desktop\86Box-32-d5f8fe3e\IBMAT\AT127Mo.img
hdd_01_mfm_channel = 0

**Comment by OBattler** [comment]
Try disabling the time sync - the AT diagnostics disks hate it - specifically, they hate it when they see 0x20 (the 20 of 2019 in BCD) in the century register.

**Comment by OBattler** [comment]
This seems to be the same problem as #323 which was indeed caused by time sync.

**Comment by OBattler** [comment]
Doing some tests now, with time sync disabled (because at I stated above and in #323, the AT diagnostics disks hate time sync).
AT diagnostics v2.00 works without problems.

**Comment by OBattler** [comment]
AT diagnostics v2.07 now issues ERROR 152 - SYTEM BOARD. I need to see why that happens.

**Comment by OBattler** [comment]
OK, AT diagnostic v2.07 error is caused by the MFM controller. I'm going to see why.

**Comment by OBattler** [comment]
Fixed that, the AT MFM controller was issuing a wrong cylinder error when it shouldn't have been.

Next, AT diagnostics v1.02. Let's see if it works.
