### ISSUE TITLE
Re-Volt v1.10: graphical issue with 3dfx Voodoo 3000

### ISSUE THREAD

**Issue by Xario123** [86Box/86Box#4157]
### What happened?

I was using PCem with Windows 98 to play my games.
I migrated to 86box using similar settings. No problems when starting 86box, all devices were detected.

Without any modifications, I launched Re-Volt and many visual glitches appeared.

On PCem, with the 3dfx Voodoo 3000 card, there is no display problem.

 Screenshots and video will be more expressive:
- PCem & 86box config:
![config PCem & 86box](https://github.com/86Box/86Box/assets/72191694/c81e2f99-fee7-4949-a16a-1f6aa9562b39)

- PCem:
![PCem: Re-Volt main menu](https://github.com/86Box/86Box/assets/72191694/a7f36f98-9f75-4d87-a300-cb76a373ec42)

- 86box:
![86box: Re-Volt main menu](https://github.com/86Box/86Box/assets/72191694/fa59004f-1738-4beb-b573-353dcae8328f)

- PCem:
![PCem: Ingame](https://github.com/86Box/86Box/assets/72191694/12a6f441-e3b8-47fb-afad-e369fdaac4fd)

- 86box:
![86box: Ingame](https://github.com/86Box/86Box/assets/72191694/a6c512a7-3db7-4418-93ce-c7b305773c14)

Video: https://www.youtube.com/watch?v=VuISiQ9PJ8k

### Configuration file

```ini
[General]
vid_renderer = qt_vulkan
confirm_exit = 0
update_icons = 0
dpi_scale = 0
kbd_req_capture = 1

[Machine]
machine = 686bx
cpu_family = pentium2_klamath
cpu_speed = 233333333
cpu_multi = 3.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
cpu = 4
mem_size = 524288

[Video]
gfxcard = voodoo3_3k_pci
voodoo = 1
show_second_monitors = 0

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sbawe32

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_pci
cassette_mode = load

[3dfx Voodoo3 3000]
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
recompiler = 1

[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[Sound Blaster AWE32]
base = 0220
emu_base = 0620
base401 = 0330
irq = 5
dma = 1
dma16 = 5
onboard_ram = 512
opl = 1
receive_input = 1
receive_input401 = 0

[Hard disks]
hdd_01_parameters = 63, 16, 101589, 0, ide
hdd_01_fn = WIN98-DISK
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
cdrom_01_speed = 24
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_type = 86BOX_CD-ROM_1.00

[Ports (COM & LPT)]
serial1_enabled = 0
serial2_enabled = 0
lpt1_enabled = 0

[Logitech/Microsoft Bus Mouse]
base = 023C
irq = 5
hz = 45
buttons = 2

[Sound Blaster AWE64 Gold]
onboard_ram = 4096
receive_input = 1
receive_input401 = 0

[Standard PS/2 Mouse]
buttons = 2
```

### Operating system

Windows 11 (build 22631)

### CPU

Intel Core i7-10870H

### 86Box version

v4.0.1 build 5111

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by cartifanwlr** [comment]
The 64-bit Voodoo recompiler has some issues, use the 32-bit 86Box build for the time being.

**Comment by Xario123** [comment]
Indeed, I tried with the 32-bit version and there is no problem, it works perfectly.
Thank you for this quick and efficient response! :)
