### ISSUE TITLE
[Question] Schneider Europc

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#416]
Hello.

I've been testing this machine, it works and the internal hard disk emulation too, but it has only two issues. The internal mouse is detected now  by CTMOUSE  1.9 as "mouse system mode" in these last releases,(in earlier releases was not detected) but in the BIOS when I configure the port to mouse is only enabled after the first reboot, later is disabled, and the mouse does not work at least in PCglobe 4.0 and 5.0. Also the Schneider ms-dos 3.30 has no mouse driver included.
Also I don't know if an specefic mouse driver exist for this machine.
 However, if I select the serial mouse in the 86box options instead of "internal" it is detected and works.

The other is the monitor option in the BIOS is always disabled. So I use the Hercules video card for this machine. I read the real machine has an built-in video chipset, that merged both CGA and Hercules video modes and supports both CGA and Monochrome monitors. Then the BIOS selects the compatible video modes supported by the monitor

**Comment by TC1995** [comment]
What mouse does the europc have as internal mouse? Bus Mouse?

**Comment by Fenix770** [comment]
Actually, I don't know. I found a site with pics of the ports (https://retroordenadoresorty.blogspot.com/2018/06/ordenador-schneider-euro-pc-1988.html). The mouse port seems to be identical that serial but I don't know if it's compatible with standard mouse and its driver.

**Comment by OBattler** [comment]
The mouse is basically a Logitech bus mouse. That is now correctly implemented in the latest commit.

As for on-board video, I don't think it's currently emulated. I'm going to look into it for v2.10, but no promises.

**Comment by Fenix770** [comment]
I tested the last commit. Now the BIOS detects it correctly, and the Logitech mouse driver detects it correctly as bus mouse, but it still does not work with Pc Globe and on FreeDOS EDIT the cursor appears on the center of the screen but it does not move.

**Comment by OBattler** [comment]
The Logitech mouse driver is hardcoded to IRQ 5, as far as I know, while the EuroPC internal mouse ises IRQ 2.

**Comment by OBattler** [comment]
This is a question that has been anwered, I'm closing this.
