### ISSUE TITLE
dev version cannot boot minix 1.5 correctly

### ISSUE THREAD

**Issue by shooter556** [86Box/86Box#4170]
### What happened?

The issue is quite easy to be reproduced.
Stable version can boot minix 1.5 normally.
But dev version will be stuck at black screen on booting.
The 1st floppy disk is working goodly, while inserting 2nd one, and try to boot afterwards, it will be stuck.
They are using the same config file.

### Configuration file

```ini
[General]
vid_renderer = qt_software
force_43 = 1

[Machine]
machine = asus386
cpu_family = i386dx
cpu_speed = 40000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = disabled
fpu_type = 387
cpu = 4
mem_size = 4096

[Video]
gfxcard = cl_gd5420_isa

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 8, 1024, 0, ide
hdd_01_fn = 86box
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_check_bpb = 0
fdd_02_check_bpb = 0
fdd_01_image_history_01 = F:/ISO/minix/1.5.10/disk04.flp
fdd_01_image_history_02 = F:/ISO/minix/1.5/univ_boot.flp
fdd_01_image_history_03 = F:/ISO/minix/1.5.10/disk02.flp
fdd_02_type = none
fdd_02_image_history_01 = F:/ISO/minix/1.5.10/shoelace.flp
fdd_02_image_history_02 = F:/ISO/minix/1.5.10/minix-386.img
fdd_02_image_history_03 = F:/ISO/minix/1.5.10/repo.flp
fdd_02_image_history_04 = Z:/minix/1.5/repo.flp
fdd_01_image_history_04 = F:/ISO/minix/1.5.10/disk01.flp
fdd_01_fn = F:/ISO/minix/1.5.10/disk05.flp

[Serial Passthrough Device #1]
mode = 0
named_pipe = \\.\pipe\86box
data_bits = 8
stop_bits = 1
baudrate = 9600

[Ports (COM & LPT)]
serial1_passthrough_enabled = 1
```

### Operating system

Windows 10

### CPU

AMD Ryzen 9 5900x

### 86Box version

4.1 build 5500

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
bisect to know what build broke it.

**Comment by TC1995** [comment]
Where do I get the minix 1.5.10 media for x86?

**Comment by OBattler** [comment]
Try the latest build of 86Box.

**Comment by Cacodemon345** [comment]
@TC1995 http://download.minix3.org/previous-versions/Intel-1.5

**Comment by TC1995** [comment]
already tried that, they are not in the correct format.

**Comment by shooter556** [comment]
> @TC1995 http://download.minix3.org/previous-versions/Intel-1.5

If you want to use this repo, disk01-04 are not in correct image size.
They are using 360KB 5.25" low density format.
`dd if=/dev/zero of=disk0x.flp bs=1k count=360
dd if=disk.0x of=disk0x.flp conv=notrunc`
can help.

Some where else stores the correct formatted floppy images, but I cannot recall where suddenly.

**Comment by TC1995** [comment]
and I'm using Windows as the host.

**Comment by lemondrops** [comment]
These commands work in the MSYS2 shell.

**Comment by Cacodemon345** [comment]
If I remember correctly, the `dd` command should be available in MSYS2.

**Comment by shooter556** [comment]
> Try the latest build of 86Box.

Alright, thanks. I confirmed that today's build works fine.

![image](https://github.com/86Box/86Box/assets/8454529/e86dcc38-4415-47a4-976c-894fb956b4e6)

**Comment by shooter556** [comment]
Latest build 5512 can boot minix 1.5 normally. Thank you guys for your help. I will close this issue.
