### ISSUE TITLE
Microsoft Plus! 98 build 1700 causes BSODs at end of setup on dynamic VHD

### ISSUE THREAD

**Issue by B-F-1-0** [86Box/86Box#4183]
### Describe the bug
When attempting to set up Microsoft Plus! 98 build 1700, at the end of copying files, the system BSODs or Setup, Rundll32, or Runonce crashes. Program start menu shortcuts aren't set up and various components don't work as a result. Have tried various machines in Socket 7 and Slot 1 categories with all ending in a crash and BSOD.

When a BSOD does happen, it often takes down Explorer and processes one by one with it until a BSOD loop is reached.

This was tested on Shuttle-HOT 557, ASUS P/I-P55T2P4, and ASUS P/I-P65UP5, and on top of Windows 98 builds 1650.8, 1691.3, and 1998.6. Appears to not occur on older 86Box builds such as 86Box build 5111.

### To Reproduce

1. Create virtual machine provided in config file using one of the machines listed above.
2. Install Windows 98 as normal.
3. Set up Plus! 98 build 1700, doesn't matter what you do, just reach file copying.
4. At end of file copying, the system/setup will crash.

### Expected behavior
Plus! setup finishes normally and the shortcuts are properly added in the Start Menu.

### Screenshots
![Monitor_1_20240220-085517-348](https://github.com/86Box/86Box/assets/115908504/c293c6b2-56c3-479e-97e8-195edd4e96f7)
![Monitor_1_20240220-124833-476](https://github.com/86Box/86Box/assets/115908504/c1c6d02c-b26d-4517-a099-37901350e3fd)
![Monitor_1_20240220-085507-134](https://github.com/86Box/86Box/assets/115908504/bdd4b467-4290-47f9-96b7-3b7190316fc7)
![Monitor_1_20240220-142829-990](https://github.com/86Box/86Box/assets/115908504/87d5fbc7-c084-4daf-9ad6-63379771ce55)
![Monitor_1_20240220-144022-178](https://github.com/86Box/86Box/assets/115908504/99c70a2e-ccf3-475c-bc8d-28701c7a72eb)

### Configuration file

```ini
[General]
vid_renderer = qt_software
sound_gain = 18
confirm_exit = 0

[Machine]
machine = 430vx
cpu_family = pentium_p55c
cpu_speed = 233333333
cpu_multi = 3.5
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
mem_size = 131072

[Video]
gfxcard = virge375_pci

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sbawe64_gold
fm_driver = nuked

[Network]
net_01_card = pcnetpci
net_01_net_type = slirp
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = text_prt

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 16383, 0, ide
hdd_01_speed = ramdisk
hdd_01_vhd_blocksize = 4096
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_02_type = 525_2hd
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_type = 86BOX_CD-ROM_1.00

[AMD PCnet-PCI II #1]
mac = 8b:ca:a3
```

### Operating system

Windows 11 v23H2 Enterprise (x64)

### CPU

11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

### 86Box version

v4.1 [78dd603, build 5512]

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Appears to install properly in other virtualizers and on older 86Box builds, with build 5111 confirmed working.

**Comment by B-F-1-0** [comment]
Tested using a raw image HDD type and setup completes normally. Thus, this appears to be a problem with the expanding VHD type and will be reported as such.
![Monitor_1_20240221-111526-955](https://github.com/86Box/86Box/assets/115908504/aa2cfc6a-ac20-49a3-9f2e-fa0d63ba21b5)

**Comment by Cacodemon345** [comment]
Does this happen with fixed-size VHD?

**Comment by OBattler** [comment]
Can you upload the VM immediately before Plus! is installed?

**Comment by eddmanx** [comment]
It started with build 5143; doesn't happen since 5517.

Machine files for testing: https://drive.google.com/file/d/1RJfyl6PcgNaqbNob0K_nUD_ERcHd2E13/view

**Comment by OBattler** [comment]
Then this can be closed.
