### ISSUE TITLE
Screen in Hercules Green Mode is twinkling

### ISSUE THREAD

**Issue by leesa49** [86Box/86Box#419]
I was executed game program that made by hercules mode.
and I'm using SPC-4200, too
It's occurred blinking..
but not occured DOSBOX or Real PC.
please, Could you check Something?
If I could, I'll upload Capture screen to Youtube

[http://blog.daum.net/neosf2/2](http://blog.daum.net/neosf2/2)

first & second clip is dosbox

third clip is 86box and Blinking

**Comment by OBattler** [comment]
Could you upload the entire virtual machine (86box.cfg, NVR folder, and hard disk image) so I can attempt to reproduce this issue?

**Comment by OBattler** [comment]
Also, what build of 86Box are you using?

**Comment by TC1995** [comment]
Could you upload your Street Fighter files?
