### ISSUE TITLE
SB16/CS4236 PnP cards are erroneously assigned IRQ 9 by default under Windows 98 in VPC2007

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#4191]
### What happened?

In the Virtual PC 2007 machine, if a Sound Blaster 16 or Crystal CS4236 PnP card is selected, the card will be automatically assigned IRQ 9 instead of IRQ 5 by default, causing a conflict with the ACPI hardware in Windows 98. This does not happen on other machines. Also, during startup, if the SB16 PnP is used, the BIOS will stay on the "checking NVRAM" screen for longer than usual, though it does eventually boot after a while.
![Monitor_1_20240222-210258-578](https://github.com/86Box/86Box/assets/29031916/71d83bc8-3c97-4b16-92d9-892e293d7df8)
![Monitor_1_20240222-212627-552](https://github.com/86Box/86Box/assets/29031916/9fb68b2e-4200-407a-a6ad-a39565a7f4fc)

### Configuration file

```ini
[General]
vid_renderer = qt_opengl3
hide_status_bar = 1
hide_tool_bar = 1
rctrl_is_lalt = 1
confirm_exit = 0

[Machine]
machine = vpc2007
cpu_family = pentium2_od
cpu_speed = 66666666
cpu_multi = 1
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 65536

[Video]
gfxcard = millennium

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sb_vibra16c

[Storage controllers]
hdc = internal

[AMD PCnet-FAST III #1]
mac = cf:17:eb

[Network]
net_01_card = pcnetfast
net_01_net_type = slirp

[Hard disks]
hdd_01_parameters = 63, 16, 1024, 0, ide
hdd_01_fn = vibra16_2.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_01_check_bpb = 0
fdd_02_type = none
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Fedora 39

### CPU

AMD Ryzen 9 7950X

### 86Box version

2fe92a2f26a5d176bc21395b2885fed48af563f8

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [X] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

The cards can be made to work again by simply disabling the "use automatic settings" checkbox and manually setting the card IRQ and IO address in Windows.

**Comment by OBattler** [comment]
That's a BIOS bug that we have no way of fixing. As such, I'm closing this.
