### ISSUE TITLE
Some of the newly added machines exhibit abnormal behavior

### ISSUE THREAD

**Issue by cartifanwlr** [86Box/86Box#4192]
### What happened?

The following machines, which were added in commit [https://github.com/86Box/86Box/commit/58a0c840c1d18845e8a7b71439bcaca4408491f8](https://github.com/86Box/86Box/commit/58a0c840c1d18845e8a7b71439bcaca4408491f8) exhibit issues that are likely not intended:

[Socket 5 UMC 8890] Shuttle HOT-539: Gets stuck on POST 91 for a long time until it spits out "Primary HDC failure".
![image](https://github.com/86Box/86Box/assets/109605173/8f3d708d-3a96-4896-954c-867b318e43d9)
![image](https://github.com/86Box/86Box/assets/109605173/4f2ac066-4bb9-4347-9e65-fe9708b84a3e)

[Socket 7SV SiS 5501] Chaintech 5SBM2 (M103): Does not recognise boot disks.
![image](https://github.com/86Box/86Box/assets/109605173/bb700076-bdfb-46e1-bc59-d7d93058ae36)

[Socket 7DV SiS 5591] MSI MS-5172: Does not show the correct speed of the processor. This is also an issue with the AOpen AP61.
![image](https://github.com/86Box/86Box/assets/109605173/b40122ec-e426-437b-83fe-26ad48c365a1)

### Configuration file

```ini
[General]
vid_renderer = qt_software
dpi_scale = 0
confirm_save = 0
confirm_reset = 0
video_fullscreen_scale = 3
video_fullscreen_first = 0
confirm_exit = 0

[Machine]
machine = ms5172
cpu_family = pentium_p54c
cpu_speed = 75000000
cpu_multi = 1.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 32768

[Video]
gfxcard = vga

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[IBM CGA]
display_type = 0
composite_type = 0
rgb_type = 5
double_type = 1
snow_enabled = 1

[Floppy and CD-ROM drives]
fdd_01_image_history_03 = C:/Users/ucuca/Documents/86Box/img/pcireg.ima
fdd_02_check_bpb = 0
fdd_02_image_history_01 = C:/Users/ucuca/Documents/86Box/img/pcireg.ima
fdd_01_type = 35_2hd
fdd_02_type = none
fdd_01_fn = C:/Users/ucuca/Documents/86Box/img/PCDOS71.img
fdd_01_image_history_01 = C:/Users/ucuca/Documents/86Box/img/Windows 98 Second Edition Boot.img
fdd_01_image_history_04 = C:/Users/ucuca/Documents/86Box/img/msnc/disk1.img
cdrom_01_image_history_01 = C:/Users/ucuca/Downloads/rtl8139c
cdrom_01_image_history_02 = C:/Users/ucuca/Downloads/msnc
cdrom_01_image_history_03 = C:/Users/ucuca/Documents/86Box/img/compaqPresario4500Seriesrestoredisc.iso

[PS/1 2011]
bios_language = english_us

[Novell NE2000 #1]
mac = 91:c3:cb

[Standard PS/2 Mouse]
buttons = 2

[Other peripherals]
postcard_enabled = 1

[Realtek RTL8139C+ (onboard)]
mac = fb:53:b4
```

### Operating system

Windows 11 v23H2

### CPU

Intel Core i5-1235U

### 86Box version

4.1 build 5557

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

There are some other machine quirks reported by @luennix , these are:
[Socket 7DV SiS 5591] Gigabyte GA-5SG100: This is a Super 7 motherboard with AGP and a 100MHz FSB.
[Slot 1 SiS 5600] Freetech/Flexus P6F99: This machine supports AGP.
[Socket 7DV SiS 5591] MSI MS-5172: This machine supports AGP but is not Super 7 unlike the Gigabyte.

**Comment by OBattler** [comment]
The WAIT stuckage and Primary HDC failure is NOTABUG - you have to go to CMOS Setup and do IDE auto-detection there so the BIOS knows there's no devices, because the BIOS is pretty dumb at POST.

**Comment by OBattler** [comment]
I can now also confirm that upon doing that, it also boots from a floppy at a reasonable speed.

**Comment by OBattler** [comment]
The CPU speed reporting is a CANTFIX - it's an artifact of the dynamic recompiler running all the times only after every block of instructions.
