### ISSUE TITLE
[BUG] FreeBSD 12.0 i586 hangs when attempting to boot the kernel.

### ISSUE THREAD

**Issue by qeeg** [86Box/86Box#421]
It just stays at a static screen for what seems like forever.

**Comment by MoochMcGee** [comment]
Here's my VM. https://1drv.ms/u/s!ArK74gCEh03CnCbGTsdHC_-8ownV?e=ftu5Mo

**Comment by MoochMcGee** [comment]
Issue occurs with the Epox P55-VA, but not with the ASUS P55T2P4

**Comment by OBattler** [comment]
Could be the Epox P55-VA having worse CD-ROM boot support, it was all over the place back then even on real hardware.

**Comment by OBattler** [comment]
Since this is most likely not an emulator bug, I'm closing this with NOTABUG.
