### ISSUE TITLE
86Box fatals when running Solaris on a machine with Matrox graphics

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#4212]
### What happened?

When starting OpenWindows on Solaris 2.6 during the install process 86Box fatals with a "BITBLT DWGCTRL_ATYPE_RPL unknown BLTMOD 02000000 020c0008" message written to the logfile. This occurs on both the Matrox Millennium and Matrox Mystique.

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = p55t2p4
cpu_family = pentium_p54c
cpu_speed = 166666666
cpu_multi = 2.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
mem_size = 65536

[Video]
gfxcard = millennium

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Matrox Mystique]
memory = 8

[Standard PS/2 Mouse]
buttons = 2

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = MatroxTest-Solaris.img
hdd_01_speed = 1997_5400rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 24
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_host_drive = 200
cdrom_01_image_path = C:/Emulators/86Box/testing/Solaris26/software.iso
fdd_01_fn = C:/Emulators/86Box/testing/Solaris26/boot.img
cdrom_01_type = 86BOX_CD-ROM_1.00

[Other peripherals]
postcard_enabled = 1

[Matrox Millennium]
memory = 8
```

### Operating system

Windows 7 SP1

### CPU

Intel Core i7-9700K

### 86Box version

v4.1.1 build 5576

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

The fatal occurs after the solid color desktop background is drawn but before any GUI windows appear.

CFG and NVR: 
[MatroxSolaris.zip](https://github.com/86Box/86Box/files/14414074/MatroxSolaris.zip)

**Comment by Cacodemon345** [comment]
Try build 5577 and see if this still persists.

**Comment by win2kgamer** [comment]
The issue persists in build 5577.

**Comment by Cacodemon345** [comment]
From where did you get your ISO of Solaris 2.6?

**Comment by Cacodemon345** [comment]
Anyways, try build 5578 and see if this issue still persists.

**Comment by win2kgamer** [comment]
@Cacodemon345 
Build 5578 resolves the fatal and I was able to successfully install Solaris 2.6 and run CDE without issues.

My ISO is from old-dos.ru.

**Comment by win2kgamer** [comment]
No fatal anymore on the Mystique 220 as well but the cursor's missing.

**Comment by win2kgamer** [comment]
Just tested build 5583 and the cursor is working properly now on the Mystique 220.

**Comment by OBattler** [comment]
Then this can be closed.
