### ISSUE TITLE
Windows 2.11/386 WIN386.EXE does not works

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4232]
### What happened?

The IBM PS/2 model 55SX and 80 I tested does not starts with the WIN386.EXE, but WIN86.COM works. I'm also using the IBM 8514/A display adapter.

What happens:
1. The machine may either, return to DOS screen or frezee on startup screen if SMARTDRV.SYS program is installed.
2. If I type WIN386 /N to start without EMS memory I get a I get en error saying "high memory area is in use" on 55SX model and an error 113 on Model 80.

Screenshot:

Error 113 on Model 80:
![Monitor_1_20240301-195637-084](https://github.com/86Box/86Box/assets/31600563/02dd6a3d-08ea-4133-9e2f-8a89fb841972)

HDD,NVR and CFG file:
[IBM PS-2 Model 55SX Windows 2.11+ 71mb HDD.zip](https://github.com/86Box/86Box/files/14466785/IBM.PS-2.Model.55SX.Windows.2.11%2B.71mb.HDD.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
vid_resize = 1
rctrl_is_lalt = 1

[Machine]
machine = ibmps2_m80
cpu_family = i386dx
cpu_speed = 16000000
cpu_multi = 1
fpu_type = 387
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu_waitstates = 8
pit_mode = 1
mem_size = 4096

[Video]
gfxcard = internal
8514a = 1

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = esdi_mca
cassette_mode = load

[Hard disks]
hdd_01_parameters = 36, 7, 583, 0, esdi
hdd_01_esdi_channel = 0
hdd_01_fn = 
hdd_01_speed = 1989_3500rpm

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none


[Ports (COM & LPT)]
lpt1_device = text_prt
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.1.5596

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Fenix770** [comment]
Note: I get the same issue with MS-DOS 3.31 and  standartd VGA mode.

**Comment by OBattler** [comment]
Please bisect and see which build broke it.

**Comment by Fenix770** [comment]
I' have no time right now but the issue is present on build 4500 too. So this bug may be very old.

**Comment by OBattler** [comment]
It turns out it is NOTABUG - it also happens on real hardware: https://comp.sys.ibm.ps2.hardware.narkive.com/WlXMJPBc/model-8580-081-windows-2-11-386 . And INSTDBUF alone doesn't solved it, which means the mysterious update is needed which... good luck finding it.
