### ISSUE TITLE
Middle mouse button won't work in VM.

### ISSUE THREAD

**Issue by gbpi** [86Box/86Box#4236]
### What happened?

When I try to use a 3 button mouse the VM will not receive a middle mouse event.  It stops releasing capture when a 3 button mouse is selected, as expected, but the VM will not respond to it.

I normally use Wayland, but I tried X11 as well. Tried various serial, PS/2 and bus mouse options on a wide range of motherboards.  The config included is just a simple one I used for testing with DSL.

### Configuration file

```ini
[Machine]
machine = awo671r
cpu_family = celeron_mendocino
cpu_speed = 66666666
cpu_multi = 1
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 131072

[Video]
gfxcard = stealth64v_pci

[Input devices]
mouse_type = ps2

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0
net_01_card = pcnetpci
net_01_net_type = slirp

[Storage controllers]
hdc = internal
cassette_mode = load

[ATI Mach64VT2]
memory = 4

[Standard PS/2 Mouse]
buttons = 3

[Floppy and CD-ROM drives]
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = dsl-4.11.rc2.iso
fdd_01_type = 35_2hd
fdd_02_type = 35_2hd
cdrom_01_type = 86BOX_CD-ROM_1.00

[AMD PCnet-PCI II #1]
mac = 81:17:90
```

### Operating system

Arch Linux

### CPU

Intel i7 3615QM

### 86Box version

4.1.1

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

Built from the 86Box-git PKGBUILD on AUR. Didn't work in 4.0 or the 4.1 release either. Same behavior with the AppImage.

**Comment by OBattler** [comment]
Closing due to it being tracked in the common issue #4239.

**Comment by gbpi** [comment]
Could this be reopened since I discovered the cause or should I create a new issue?

It has to do with TrackPoint scrolling, if I disable on-button scrolling it works fine. I guess I never tried using a regular mouse before.

**Comment by OBattler** [comment]
If it breaks with on-button scrolling enabled, then the mouse is not sending middle button events in that case, nothing we can do about that.

**Comment by gbpi** [comment]
Every other application receives it just fine, including other Qt 5/6 stuff. 

Using middle mouse to release the mouse works perfectly fine too, so 86Box is receiving it.

**Comment by OBattler** [comment]
Are you using Xinput2, Wayland input, or evdev?

**Comment by gbpi** [comment]
Wayland.

I'd tested this on X11 when I first reported and behavior was the same, pretty sure that was using libinput.
