### ISSUE TITLE
Compaq Portable III 386  issue with CEMM v4.01

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4237]
### What happened?

The recent changes made to Compaq Portable III 386 fixed the errors found on Windows 2.01/386, now is possible to launch DOS apps from Windows in 386 mode.

1. But the issue with CEMM 4.01 is still present. It freezes the VM when loaded from CONFIG.SYS. I used the install program utility included on Compaq DOS 3.31.

CEMM v4.01 worsk just fine with Compaq Deskpro 386:
![Monitor_1_20240304-193039-451](https://github.com/86Box/86Box/assets/31600563/20928fea-2c51-4765-9d75-0758d41d858e)

Here is the CFG,HDD, and NVR files:
[Compaq Portable 386.zip](https://github.com/86Box/86Box/files/14487993/Compaq.Portable.386.zip)

### Configuration file

```ini
[Machine]
machine = portableiii386
cpu_use_dynarec = 0
cpu_enable_fpu = 1
time_sync = local
cpu_family = i386dx
cpu_speed = 20000000
cpu_multi = 1
fpu_softfloat = 0
mem_size = 4096

[Video]
gfxcard = internal

[Input devices]
mouse_type = msserial

[General]
vid_resize = 1
vid_renderer = qt_software

[Hard disks]
hdd_01_parameters = 17, 5, 977, 0, esdi
hdd_01_fn =
hdd_01_esdi_channel = 0
hdd_01_speed = 1997_5400rpm

[Storage controllers]
hdc = esdi_at

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd

[Sound]
fm_driver = nuked
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.1.5604

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Do you have any evidence CEMM v4.01 runs on the real Portable III 386?

**Comment by OBattler** [comment]
Since right now, the only difference between this and the Deskpro 386 is the BIOS, I'm going to assume it's a BIOS incompatibility.

**Comment by indrekis** [comment]
> Do you have any evidence CEMM v4.01 runs on the real Portable III 386?

I have tested CEMM 4.01 (1989) on a real Portable III 386; it basically worked (as an EMS emulator). However, it fared badly with HIMEM.SYS -- for example, MEM utility hanged then. (CheckIt 4.1 says "A20 Hardware error" -- looks like it is caused because the CEMM does not support VCPI, whatever).

![image](https://github.com/user-attachments/assets/c6d4601d-87b9-431b-b89c-7e89ab842ecb)

**Comment by indrekis** [comment]
> Compaq Portable III 386

Could you share some details on the BIOS you have used? The machines/portableiii386 folder is absent in the [roms](https://github.com/86Box/roms) repo. (Or am I missing something?)

**Comment by Fenix770** [comment]
I think the ROM folder has changed. The HIMEM.SYS issue may be normal, since the XMS spec  was launched after the LIM EMS.
As far as I know, only Windows 2.11/286 and /386 uses HIMEM to map the 64kb HMA memory.
386Max v4 and later  manages both XMS (HMA) and EMS memory.
