### ISSUE TITLE
WD1002A Fixed Disk emulation not working

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#424]
Regardless of the geometry of the created disk image, fdisk always report a 1023 cylinders disk.
tried low level format (debug/g=C800:5 with manual correct CHS params, same thing).

A previously WORKING disk image with WD1002A emulation do not work anymore (so it may be a recent bug).

**Comment by OBattler** [comment]
What machine is this one? Someone else reported the same bug last night but it was on the Toshiba machines.

**Comment by TC1995** [comment]
I think any XT.

**Comment by jvernet** [comment]
I’m the one who reported this on Discord.
Tried on different xt config, same.



Envoyé de mon iPhone

Le 2 oct. 2019 à 10:46, OBattler <notifications@github.com> a écrit :

﻿

What machine is this one? Someone else reported the same bug last night but it was on the Toshiba machines.

**Comment by Altheos** [comment]
Tested on 1844 build (the very first that bring WD1002A MFM controller emulation), IBM XT (1982), 8088 4,77 Mhz, 640 ko, WD1002A-WX1 ISA controller, 20 Mb MFM HDD, DOS 3.3 :
FDISK reports HDD size is 1024 cylinder.
