### ISSUE TITLE
A strange error when there is a Title coprocessor in the configuration

### ISSUE THREAD

**Issue by IvanLever** [86Box/86Box#4245]
Hello! I have been using the 86Box emulator for more than three years. And all three years I've noticed one strange moment. I take the old Turbo Basic 1.0 from 1987 from Borland. I run it in a configuration without a mathematical coprocessor - everything works fine. I add a coprocessor to the configuration and - 86box behaves strangely, a simple program from one line (print 1/3) gives either division by zero or another error. A strange reaction to the coprocessor also occurs in other software, for example, in early versions of MS Excel 2.x, when the simplest arithmetic calculations give a completely strange result. 
[Lx286.zip](https://github.com/86Box/86Box/files/14598053/Lx286.zip)
![изображение_2024-03-14_095903366](https://github.com/86Box/86Box/assets/163040530/2a1a2911-1fec-40ed-97ea-4db9de3db70d)

**Comment by PolyglotCow** [comment]
Are you using the softfloat FPU? I think it's more accurate than the hardware one.

**Comment by OBattler** [comment]
Upload the VM please.

**Comment by OBattler** [comment]
This is now fixed as well.
