### ISSUE TITLE
[BUG] Tandy 1000 SL/2 DAC

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#426]
Hello

I tested the game Super Tetris. The installer does not detect automatically the DAC. Detects only The 3-voice speaker. I can change it from the options but when the install finish and run the game only the 3-vioce music plays correctly The DAC produces an indistinguishable white noise when clear lines or hit some of the items of the game. The sound effects should be different for clearing lines, destroying blocks or hit other bonus of the game, like it is with the standard pc speacker or sound blaster card.

Here is the link to the [disk](https://drive.google.com/open?id=1bDlphZBAjL2UVhJPZcrIzS8EH2CSuLwJ)

The installation can take up to 10 minutes on 8088/8086 machine.

**Comment by Fenix770** [comment]
I found another bug in the game. The high score table after finishing the game on the screen appears garbage colors and the game stops responding.

![20191004_001057](https://user-images.githubusercontent.com/31600563/66178629-58938580-e63c-11e9-9e4b-d37328998c10.png)
.

**Comment by OBattler** [comment]
Do these bugs occur on PCem?

**Comment by Fenix770** [comment]
The graphics issue is present in 86box only.

But the Tandy DAC bug exists also in PCem and DosBox. It's, in fact, a very old bug. It dates back from the time, the Tandy emulation, was implemented in DosBox. If, I recall correctly, These bugs were reported in the dosbox forum in that time, but as the game supports Sound Blaster and MT-32, it was not considered important. 

 For example  the 16 colors version of Battle Chess supports Tandy 3-voice speaker, and runs correctly in 86box/pcem but does not in Dosbox (altough I did not test any recent commit)

![imagen pcem](https://user-images.githubusercontent.com/31600563/66444577-21491e00-ea1a-11e9-8b67-e169df3bcc5d.png)

**Comment by OBattler** [comment]
OK, I just downloaded the image, I'm going to look at it later to see what can be done.

**Comment by OBattler** [comment]
I don't get graphics corruption, but I get an error after I go for OK - General error reading device AUX. And it hangs.

**Comment by OBattler** [comment]
The above was with the DTC hard disk controller. With the IBM PC Fixed Disk Controller it's fine.

**Comment by OBattler** [comment]
Now even with the DTC, it's OK, no idea how.

**Comment by Fenix770** [comment]
I used the Acculogic IDE XT controller with both PCEM v15 and 86box. I'm not sure if the real Tandy SL/2 machine used an XTA disk controller for hard disk, as some hardware parts were not standard.
I think the hard disk was optional because it include DOS 3.3 in ROM.

**Comment by OBattler** [comment]
The Acculogic is XT-IDE not XTA (a.k.a. IDE XT). And yes, it could be a memory overlap.

**Comment by OBattler** [comment]
I can't reproduce neither the white noise, nor the graphics glitch anymore. I think this can be closed now.
