### ISSUE TITLE
800x600 256 colors mode bug with ET-4000AX TC6058AF chip on Windows 3.0

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4265]
### What happened?

The ET-4000AX TC6058AF with 512kb display the screen size incorrectly with both versions of the VGA BIOS. The 800x600 16 color works fine.
Also 800x600 256 colors mode works fine with the regular E4000-AX. I'm not sure if it is a BIOS limitation or an emulation bug.

Screenshot:
![Monitor_1_20240314-105933-521](https://github.com/86Box/86Box/assets/31600563/113a658b-3890-4e2f-bbb5-909fa35c04a6)

Here is the NVR,CFG and HDD files: 
[386 SX ET4000-1990.zip](https://github.com/86Box/86Box/files/14603439/386.SX.ET4000-1990.zip)

### Configuration file

```ini
[Tseng Labs ET4000AX (TC6058AF) (ISA)]
memory = 512
bios_ver = v1_10

[General]
vid_renderer = qt_opengl3
vid_resize = 1
rctrl_is_lalt = 1
video_gl_shader =
video_gl_framerate = 35
dpi_scale = 0
enable_overscan = 1

[Machine]
machine = 325ax
cpu_family = i386sx
cpu_speed = 20000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu_waitstates = 8
pit_mode = 1
mem_size = 4096

[Video]
gfxcard = et4000ax_tc6058af

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sb
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = text_prt

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 11, 1024, 0, ide
hdd_01_fn = 
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0
hdd_01_vhd_blocksize = 4096

[Floppy and CD-ROM drives]
fdd_01_type = 525_2hd
fdd_02_type = 35_2hd

[Tseng Labs ET4000AX (ISA)]
memory = 1024
bios_ver = v8_06
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.1.5627

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
Might be really a bios limitation if the regular et4000ax renders fine with just 512k.

**Comment by Fenix770** [comment]
The 640x480 256 color mode and 1024x768 16 color mode works fine on ET-4000AX TC6058AF with 512kb VRAM.
Only the 800x600 256 color seems to be affected. I installed Sitech Display Doctor but it does not solve the issue.

**Comment by Fenix770** [comment]
Also the 800x600 256 colo mode works fine when tested with the Sitech VBETEST.

![Monitor_1_20240314-221309-244](https://github.com/86Box/86Box/assets/31600563/8fae1886-eb19-4547-9708-1cd02894ce22)

![Monitor_1_20240314-221317-790](https://github.com/86Box/86Box/assets/31600563/4772bf09-e775-48be-acf0-90bc873c86f3)

**Comment by OBattler** [comment]
This is most likely a BIOS bug, therefore, CANTFIX.
