### ISSUE TITLE
Commit 1dca23d breaks booting from floppy on the PCjr

### ISSUE THREAD

**Issue by Exemptus** [86Box/86Box#427]
The IBM PCjr VM boots correctly from floppy on build #1886 but not in build #1887 and later. This does not seem to affect other machines (e.g., the IBM PC 1982 boots OK from a PC-DOS 2.10 image but the IBM PCjr jumps to ROM BASIC instead).

**Comment by OBattler** [comment]
The latest commit fixes this.
