### ISSUE TITLE
wrong exception generated again

### ISSUE THREAD

**Issue by likearome** [86Box/86Box#4279]
### What happened?

https://github.com/86Box/86Box/issues/2583

It seems like this issue still exists in 86Box 4.1

![image](https://github.com/86Box/86Box/assets/39750066/5a84d12f-0f73-4f0b-8fce-3087068dd91f)

MS-DOS 6.22 fresh install
MS C/C++ 7.0 fresh install
run CodeView (4.01) and meet Exception.

![image](https://github.com/86Box/86Box/assets/39750066/d4da1fe5-741a-4f49-a2cb-500b492e64da)
EXC0D produced the output “exc 0D occurred.”

If there is a way to walk around this issue and run codeview, please let me know.

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = ax59pro
cpu_family = pentium_p55c
cpu_speed = 233333333
cpu_multi = 3.5
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 32768

[Video]
gfxcard = stealth3d_4000_agp

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sbawe64_gold
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 1024, 0, ide
hdd_01_fn = hdd1.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_02_type = none
cdrom_01_speed = 52
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Windows 10

### CPU

AMD Ryzen 9 5900X

### 86Box version

v4.1 build 5555

### Build architecture

Windows - x64 (64-bit)

### Build type
I used the release binary listed here.

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
I have no idea how to fix this.

**Comment by OBattler** [comment]
Closing because it's being tracked in #4447 .

**Comment by OBattler** [comment]
This is now fixed - apparently, x86 can execute data segments in some cases, and MS DPMI loves doing that. LINK suffered from similar problems a well.
