### ISSUE TITLE
Mouse click hangs 86Box while in full screen

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#429]
Host systems : (Various)

1. Desktop - i7-8700K, 16GB RAM, AMD 5700XT Win10x64
2. Laptop 1 - Dell 7559 i7-6700HQ, 8GB RAM, GTX960m/Intel HD Win10x64
3. Laptop 2 - Thinkpad x230 i7-3520m, 8GB RAM, Intel HD 4000 Win7x86

The configurations I use are : 286 Award BIOS clone, 386 DX Award BIOS, 486 DX2 AMI WinBIOS, Pentium using VX. for 386 and above, I am using Adaptec SCSI 1542xcf with the appropriate driver. In 286 only IDE. I have tried disabling adaptec and SCSI but problem persists.
Audio is SB 1.5 in 286, and SB16 in the others, using MIDI out to MUNT in 286 and 386 and Sound Canvas VA in the others.

Using Logitech Proteus Core mouse in the Desktop and Logitech M570 Wireless Trackball in my laptops.

Using CTMOUSE.EXE v2.0 driver. Tried using logitech's mouse driver and Microsoft mouse driver. Result is the same. 

All of these systems exhibit crash/hang of 86Box from version 1844 onwards upto the latest 1892. Game works fine until the mouse button is pressed. Until then, the cursor able to move and intro of games continue. Once the left mouse button is pressed, 86boix hangs. Music continues to play if playing game, but it's unresponsive and needed to close using task manager. This crash also occurs in other applications. Basically it just crashes the 86box when I press the mouse button.

Also hangs when I try with the touchpad buttons on the laptops. 

I am surprised why this has not reported before since 1844 itself. Or only I am the one experiencing this?

**Comment by OBattler** [comment]
Is this in full screen?

**Comment by MoochMcGee** [comment]
Can confirm this bug, though it only happens in fullscreen.

**Comment by Mal752** [comment]
Yes, in fullscreen.

**Comment by OBattler** [comment]
Then yes, this is fixed on my end. I had to make Direct3D switch the renderer to the full screen window like SDL does, as it seems Raw Input requires it, while DirectInput did not.
