### ISSUE TITLE
[Bug] Video 7 1024i video memory and detection

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#431]
I did not test this video card (1024i), but in the manual of the card states (on page 7) [http://toastytech.com/manuals/Video%207%20VGA%201024i.pdf](url) that only 256kb and 512kb configurations are supported. 86box allows 512kb and 1Mb configurations, but I think it may be not correct.

I tested the DOS drivers for the 1024i, but it does not dectect as a 1024i video card.
I think it's a bug.

![20191013_213715](https://user-images.githubusercontent.com/31600563/66724910-ef60fe80-ee01-11e9-87e4-c60fcf713af9.png)

Here is the diver disk for the 1024i. [https://drive.google.com/open?id=1bXWEMszqGdXRE47AM4pCOEvGq-SwNfk5](url)

Thanks!

**Comment by TC1995** [comment]
hmm, I'd have to check the id of the card.

**Comment by TC1995** [comment]
Looks like the desired id is 0x7140 and running v7diag with the id of 0x7140 makes it recognized.
