### ISSUE TITLE
Sound Bugs with Pro Audio Spectrum Plus/16

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4313]
### What happened?

1.The game Prince of Persia v1.3 have sound issues and crash at the end of level 1 when the door opens.

2. The game Hoyle Official Book of Games- Volume 3 does not detect the Pro Audio Spectrum on the install program, but i'm not sure if it is a bug or not because the game was launched in 1991, and maybe it spects to find the PAS 8 sound card. 
(This game had issues with other clone cards like the Aztech models that emulate the SB PRO, but the SB PRO driver is not compatible)
The game Hoyle Classic Card Games launched in 1993 works fine, with the Pro Audio drivers.

4.The canyon.mid sound file, when played from Windows 3.x, sound like some instuments are missing

Here is the NVR,CFG and HDD files:
[486 SX.zip](https://github.com/86Box/86Box/files/14789796/486.SX.zip)

Here is a short capture of PoP game behavior

https://github.com/86Box/86Box/assets/31600563/9e926d58-fa46-4da7-bf87-03997bd99ab8

### Configuration file

```ini
[Pro Audio Spectrum Plus]
receive_input401 = 1
receive_input = 1

[General]
vid_renderer = qt_software
vid_resize = 1
rctrl_is_lalt = 1

[Machine]
machine = exp4349
cpu_family = i486sx
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = et4000w32

[Input devices]
mouse_type = msserial

[Sound]
sndcard = pas16
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = text_prt

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 38, 16, 684, 0, ide
hdd_01_speed = 1992_3600rpm
hdd_01_ide_channel = 0:0
hdd_01_vhd_blocksize = 4096

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd


[Pro Audio Spectrum 16]
receive_input401 = 0
receive_input = 1
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.2.0.5652

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
floppy of PoP1 1.3?

**Comment by OBattler** [comment]
Prince of Persia I have fixed on my end now, I accidentally committed a buggy implementation of the timer gates.

For the MIDI, set a Midi Out device - the Pro Audio Spectrum MIDI driver uses both MIDI and OPL at the same time.
