### ISSUE TITLE
[Bug] Freeze with AMI WinBIOS SiS471 and the CPU

### ISSUE THREAD

**Issue by OltScript313** [86Box/86Box#432]
I tried AMI WinBIOS SiS 471 with a CPU i486SX2/50 but it freeze on the latest build of 86Box (Same with the 66 Mhz), but if I change the RAM to 1 MB, it crashes....
With other processors more slower, it works without problems apparently....

**Comment by OBattler** [comment]
I think the SX2's were production-only CPU's, and as such are not supported by many boards.
