### ISSUE TITLE
Freezes at the graphical part of setup!

### ISSUE THREAD

**Issue by smfthe1199** [86Box/86Box#4332]
### What happened?

I am trying to install Win95 HP Vectra OEM, and it literally freezes at the graphical part of setup, SO HARD that **the mouse doesn't move at all!** If you guys have any idea LMK!

### Configuration file

```ini
[General]
force_43 = 1
dpi_scale = 0
enable_discord = 1
vid_resize = 2
vid_renderer = qt_software
window_fixed_res = 800x600
language = system
window_remember = 1
video_fullscreen_first = 0
confirm_reset = 1
confirm_exit = 1

[Monitor #1]
window_coordinates = 274, 42, 800, 600

[Monitor #2]
window_coordinates = 0, 0, 0, 0

[Machine]
machine = vectra54
cpu_family = pentium_p54c
cpu_speed = 75000000
cpu_multi = 1.5
fpu_type = internal
mem_size = 16384
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
pit_mode = 1

[Video]
gfxcard = px_trio64_pci

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb16
fm_driver = nuked

[Network]
net_01_card = pcnetisaplus
net_01_net_type = slirp
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 4161, 0, ide
hdd_01_ide_channel = 0:0
hdd_01_fn = disk00
hdd_01_speed = ramdisk

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 35_2hd
cdrom_01_speed = 72
cdrom_01_type = 86BOX_CD-ROM_1.00
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
```

### Operating system

Windows 10

### CPU

Intel Core i5-4200 CPU @ 1.60 GHz

### 86Box version

v4.2 build 5656

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

I have got the Windows 95 HP Vectra Recovery CDs, don't forget to download only **2 files** as it's required! Download here: https://archive.org/details/hpvectrarecoverycracked_vei8-vei7
Also surprisingly the regular Phoenix S3trio64 and S3Trio64V+ has the issue too!

(Note: It also has Windows 98 option as well, as well as options of full and minimum installation (or recovery), choose Windows 95 full installation (recovery) best, or option 1)!

**Comment by smfthe1199** [comment]
Please fix this, or **investigate this** not immediately!

**Comment by cartifanwlr** [comment]
First of all, please calm down.

Second, your i5-4200U (assumed from clock speed) is just too slow for the Pentium 75. Are you sure the machine runs at 100% speed?

**Comment by smfthe1199** [comment]
First, I'm calm _remember how I said **not immediately!_**

Second, yes, the machine runs at **100%** the emulation speed, sometimes even less!

**Comment by smfthe1199** [comment]
This is before I upgraded to the build number I'm at rn!

**Comment by lemondrops** [comment]
> I'm calm

Then why do you put exclamation marks after every sentence?

**Comment by smfthe1199** [comment]
welp, just like others..

Anyway to serious topics

**Comment by smfthe1199** [comment]
Ctrl+Alt+Delete surprisingly doesn't even do anything!

**Comment by smfthe1199** [comment]
To test it, make sure to download these 2 files from the provided link, copy all of the _86box.cfg_ file, and install like normal!

**Comment by smfthe1199** [comment]
Any updates? (Reply if encountered or fixed, or any updates)

**Comment by OBattler** [comment]
Use the correct recovery disc for this machine.

**Comment by smfthe1199** [comment]
did you test it or sm?

**Comment by smfthe1199** [comment]
It turns out wrong video card, sorry for the inconvenience, I deeply apologize!
