### ISSUE TITLE
Windows for Workgroups 3.11 hard freezes when accessing an ATAPI CD-ROM

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#4348]
### What happened?

WfW 3.11 will randomly hard freeze when accessing an ATAPI CD-ROM, often when installing large programs (Office 4.3 Professional and Watcom C 10.6 are consistent in doing this.)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
emu_build_num = 5682
uuid = a302f197-b80c-5e1b-9621-4bf01fffa4db

[Machine]
machine = zappa
cpu_family = pentium_p54c
cpu_speed = 133333333
cpu_multi = 2
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
mem_size = 16384

[Video]
gfxcard = px_trio64_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sb16

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[S3 Trio64 PCI (Phoenix)]
memory = 2

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = ATAPITest.img
hdd_01_speed = 1994_4500rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_host_drive = 200
cdrom_01_image_path = C:/Emulators/86Box/testing/Compilers/WATCOM_C106.iso
cdrom_01_image_history_01 = C:/Emulators/pcemv16/testing/CDROMs/1994/MSO43/CD1.ISO
cdrom_01_type = 86BOX_CD-ROM_1.00

[Other peripherals]
postcard_enabled = 1
```

### Operating system

Windows 7 SP1

### CPU

Intel Core i7-9700K

### 86Box version

v4.2 build 5682

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

This issue does not occur on the WinChip interpreter and does not seem to occur when using OAKCDROM.SYS instead of VIDE-CDD.SYS or FDATACD.SYS as the CD-ROM driver. I also tested the ASUS PCI/I-P54SP4 and Soyo 4SAW2 (with a Pentium Overdrive CPU) boards with the same results.

Config, NVR and HDD image: 
[86Box-ATAPITesting.zip](https://github.com/86Box/86Box/files/14941450/86Box-ATAPITesting.zip)

The three tested CD-ROM drivers are in C:\DOS.

**Comment by OBattler** [comment]
What DOS CD-ROM driver are you using?

**Comment by win2kgamer** [comment]
VIDE-CDD.SYS version 2.15

**Comment by TC1995** [comment]
does it happen on other equal quality atapi dos drivers?

**Comment by win2kgamer** [comment]
Tested several ATAPI CD-ROM drivers on build 5739:
- VIDE-CDD.SYS (version 2.15): Hangs
- FDATACD.SYS (Future Domain PowerIDE v2.40): Hangs
- OAKCDROM.SYS: Doesn't hang
- NEC_IDE.SYS (OAK OTI-011 rev D011V110): Doesn't hang
- CPQIDECD.SYS (version 1.21c): Hangs
- ATAPI_CD.SYS (Sony ATAPI v2.19c): Doesn't hang
- ACER215H.SYS (Acer ATAPI v2.15H): Doesn't hang

Floppy image with the drivers used for testing: 
[CDROM_Drvs.zip](https://github.com/86Box/86Box/files/15256487/CDROM_Drvs.zip)

**Comment by OBattler** [comment]
According to jriwanek, this is known to happen on real hadware as well.

**Comment by OBattler** [comment]
Yeah, this can be closed as NOTABUG - I did extensive logging on this and 86Box is doing nothing wrong.
