### ISSUE TITLE
Above Disk Plus 4.0 hardware detection issue

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4355]
### What happened?

The Above Disk 4.0 software detects the SCAMPsx, 386 SX machine as NEAT. But on the Goldstar 286 with SCAT chipset it is not detected. So I'm not sure on which VM the detection is wrong.
Netroom v3.0, for example has a NEAT driver that works on SCAT  286 chipsets.

Here is the VM,CFG and NVR file:
[286 SCAT+ Above Disk 4.zip](https://github.com/86Box/86Box/files/14972203/286.SCAT%2B.Above.Disk.4.zip)

Above Disk 4.0 floppy disk:
[above-disc-v-4.0-above-software-1990.zip](https://github.com/86Box/86Box/files/14972216/above-disc-v-4.0-above-software-1990.zip)

Screenshot:
![Monitor_1_20240414-184504-797](https://github.com/86Box/86Box/assets/31600563/69ccfd0f-8a56-4198-92b8-d65c4fe324d5)

### Configuration file

```ini
[Tseng Labs ET3000AX (ISA)]
memory = 512

[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 5682
uuid = b8fe926a-8de7-5e6d-a0c6-5dd82e3adf8d
vid_resize = 1
rctrl_is_lalt = 1

[Machine]
machine = kmxc02
cpu_family = i386sx
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu_waitstates = 1
mem_size = 4096

[Video]
gfxcard = et3000ax

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 9, 1024, 0, ide
hdd_01_fn =
hdd_01_speed = 1992_3600rpm
hdd_01_ide_channel = 0:0
hdd_01_vhd_blocksize = 1024

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.2.0.5682

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
I wonder how it detects the chipset. It must be via some I/O port access.

**Comment by OBattler** [comment]
The machine in the config file provided has the SCAT SX chipset, not SCAMP. This explains why - the SCAT SX has some registers in the 6x range that overlap with NEAT, so the software is misdetecting the chipset. The 286 SCAT chipset does not have any registers in that range, hence why there's no misdetection.

**Comment by OBattler** [comment]
This should now be fixed.

**Comment by Fenix770** [comment]
Sorry, I should say SCATsx, since both chipsets 82C235 and 82C236 are similar, except the 236 removed the LPF support and can map only the D000-DFFF for the page frame.
