### ISSUE TITLE
86Box failed to recognize .mfm disk image with non-standard sector size protection.

### ISSUE THREAD

**Issue by nightson** [86Box/86Box#4357]
### What happened?

![DISK_Dummy_Disk_cr](https://github.com/86Box/86Box/assets/843241/b5170537-e3f1-427b-bf11-48373f1864f1)
I have an old disk that is protected with non-standard sector size (See track 18). I tried to mount the .mfm image in 86Box but it didn't work. 
![2024-04-15_172941](https://github.com/86Box/86Box/assets/843241/1e7ca2f0-26fb-4d53-9f94-3dc389c32668)

I tried mounting the same disk image in MAME. It worked.
![1111](https://github.com/86Box/86Box/assets/843241/3e79fa89-4205-4965-82a8-f213ef122781)
![22222](https://github.com/86Box/86Box/assets/843241/d6dc29ea-66d4-42c8-93a9-0413ad8bb0f4)

This is the disk in question: https://archive.org/details/snipes_1982

### Configuration file

```ini
[General]
vid_renderer = qt_vulkan
do_auto_pause = 1
window_remember = 1
force_43 = 1

[Machine]
machine = win486pci
cpu_family = am486dx2_slenh
cpu_speed = 66666666
cpu_multi = 2
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 16384

[Video]
gfxcard = stealth3d_2000pro_pci

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = sb16

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 4162, 0, ide
hdd_01_fn = D:/Emulator/PCem/hd/DOS_6.22.IMG
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd

[Monitor #1]
window_coordinates = 363, 222, 640, 480

[Monitor #2]
window_coordinates = 0, 0, 0, 0
```

### Operating system

Windows 11 Enterprise 23H2

### CPU

Intel i5-13600KF 

### 86Box version

4.1.1

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by sandritus** [comment]
It seems that the disk image works only if directly booted by floppy 5.25 from drive A and depends on the machine configuration choosed.

In my configuration, it works (set BIOS to boot from drive A)

[Machine]
machine = vli486sv2g
cpu_family = am486dx2_slenh
cpu_use_dynarec = 1
cpu_enable_fpu = 1
time_sync = disabled
cpu_speed = 66666666
cpu_multi = 2
fpu_softfloat = 0
pit_mode = 1
fpu_type = internal
mem_size = 16384

[Video]
gfxcard = tvga9000b

[Storage controllers]
hdc = none

[Other peripherals]
hdc = internal

[Floppy and CD-ROM drives]
fdd_01_type = 525_2hd
fdd_02_type = 525_2hd
fdd_01_fn = D:/DISK.mfm
fdd_01_writeprot = 1
