### ISSUE TITLE
[BUG] DTK PKM-0038S E-2 displays wrong CPU clock speed on soft reset

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#436]
We have a issue with one of the machines that are currently emulated under 86Box.

For instance, I currently emulate the DTK PKM-0038S E2 with a CPU clock speed of 66 MHz.

When starting to emulated DTK PKM-0038S E-2 for the first time or on hard reset, the clock speed is displayed correctly. However, upon doing a soft reset, the processor speed is displayed as 32 MHz. This issue also affcets DX4 processors.

For 486SX/DX speed selections between 20 MHz and 50 MHz, the processor speed is correct. However, when doing a soft reset of the machine, the clock speed gets lowered to 16 MHz.

Here are example screenshots that I provided.

1. 66 MHz 80486DX2 when starting up for the first time and on hard reset:
![20191016_221930](https://user-images.githubusercontent.com/32658796/66979627-1d914900-f063-11e9-9f36-1c180ac0210f.png)

2. 66 MHz 80486DX2 on soft reset:
![20191016_222000](https://user-images.githubusercontent.com/32658796/66979650-2eda5580-f063-11e9-81f6-9771eaca6195.png)

3. 33 MHz 80486 when starting up for the first time and on hard reset:
![20191016_222249](https://user-images.githubusercontent.com/32658796/66979761-84aefd80-f063-11e9-81f8-bc945b5b8a7b.png)

4. 33 MHz 80486 on soft reset:
![20191016_222322](https://user-images.githubusercontent.com/32658796/66979783-955f7380-f063-11e9-9ec0-54654a34d55c.png)

5. 20 MHz 80486SX on hard reset:
![20191016_222410](https://user-images.githubusercontent.com/32658796/66979812-b1631500-f063-11e9-8e76-9fb6cae5d219.png)

5. 20 MHz 80486SX on soft reset:
![20191016_222450](https://user-images.githubusercontent.com/32658796/66979838-c9d32f80-f063-11e9-93bb-7546393becc7.png)

6. 50 MHz 80486SX2:
![20191016_222533](https://user-images.githubusercontent.com/32658796/66979867-e53e3a80-f063-11e9-80b8-59a2cd2b6d44.png)

Please note that when using the 80486SX2 on the emulated DTK PKM-0038s E2, the CPU type will report as a 80486DX2, because realistically, the motherboard seems to not support 80486SX2 processors.

I'm sorry for having to post the system configuration so many time, but can anyone reproduce this issue and find out what could be causing the machine to not report the CPU clock speed correctly on soft reset?

Thanks. :)

**Comment by OBattler** [comment]
This seems to be fixed, so I'm closing this.

**Comment by MatthewRobertDunn** [comment]
I still get this on the i486DX4100, on soft reboot it appears as 32MHz 86Box V4.1

**Comment by cartifanwlr** [comment]
Is the dynamic recompiler enabled? If so, it's an issue relating to that and we sadly can't do anything about it.

**Comment by MatthewRobertDunn** [comment]
Yup, thanks.

**Comment by MatthewRobertDunn** [comment]
Turns out I get this whether dynamic recompilation is on on not

![image](https://github.com/86Box/86Box/assets/15967209/0ce09764-907d-4af6-a13a-1ceb8226f280)
