### ISSUE TITLE
UI bug: Hiding status bar or toolbar from view menu makes the window shrink

### ISSUE THREAD

**Issue by Sunspark-007** [86Box/86Box#4363]
### What happened?

Every time hide status bar or toolbar is checked or unchecked, the window continues to shrink to a smaller scale.

Requires resetting to normal 1x scaling by selecting it in window scale factor.

### Configuration file

```ini
n/a
```

### Operating system

Windows 10

### CPU

Core 2 Duo

### 86Box version

4.1.1 build 5634

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
I can't even reproduce this at all so it must have to do with your host hardware.

**Comment by Sunspark-007** [comment]
@OBattler Must be.. the issue doesn't happen with the Flatpak in Linux, only in Windows. It's not a priority issue, but it is a bug.

**Comment by Sunspark-007** [comment]
@OBattler I have identified a use-case where it does and doesn't trigger. If you HAVE HiDPI mode checked on in Windows (which is using scaling higher than 100%), then the window shrinking doesn't occur. But if you DO have HiDPI unchecked, then the window shrinking will occur when the bars are checked or unchecked.

**Comment by Sunspark-007** [comment]
@OBattler Another use case where it doesn't happen with HiDPI unchecked unlike the previous comment where it does happen, it's when you have 86Box set up to scale correctly. Apparently, when I figured out a fix for the fullscreen integer scaling issue (you should consider adding that as a switch so people can use it easily) it doesn't do the shrinking window on the hide/unhide. It's because of QT and a weird interaction with logical dpi.
