### ISSUE TITLE
Creating new drive images defaults to 0:1 IDE and 0:01 SCSI instead of 0:0 and 0:00

### ISSUE THREAD

**Issue by Sunspark-007** [86Box/86Box#4367]
### What happened?

I wonder if this is a default setting error.. manually changing it back up to 0:0 and 0:00 from the pre-populated section of 0:1 and 0:01.

This would be on a screen with all drives removed.

### Configuration file

```ini
n/a
```

### Operating system

Windows 10

### CPU

Core 2 Duo

### 86Box version

v4.1.1 build 5634

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by thedax** [comment]
I can't reproduce this with a completely fresh cfg file entering settings for the very first time. However, I can reproduce it if I've altered the hard drive list within the same settings "session" (i.e. haven't dismissed the settings window with OK or cancel) by either adding or removing another hard drive.

Steps to reproduce as far as I can tell:
1. Start a guest
2. Open the settings menu
3. If it's a new guest, add a hard drive (it'll default to 0:0 IDE or 0:00 SCSI correctly), then remove it and add another one, you'll see it defaults to 0:1/0:01 if it's an existing guest, remove all of the existing disk(s) (including CD-ROM drives) and try adding a hard drive, and the same thing should still occur

So it's incorrect that it sets the initial drive to 0:1/0:01 by default, but it doesn't seem to reset 100% correctly when you're changing the layout in the same 'session' (e.g., to fix a mistake you made in hard disk image creation, or something along those lines).

**Comment by cold-brewed** [comment]
Yes, there's a bug in the bus tracking that causes this to happen after you remove a drive and then add another drive.

I have an upcoming PR that will add some new bus tracking features and also fix this issue.
