### ISSUE TITLE
86Box doesn't sync the caps lock and num lock keys between Windows and the emulator

### ISSUE THREAD

**Issue by Sunspark-007** [86Box/86Box#4375]
### What happened?

If 86Box is running, it doesn't check what state the caps or num lock key in Windows is set to, so it's very easy to get out of sync between the two environments where you have to keep changing the keys when you switch between windows.

### Configuration file

```ini
n/a
```

### Operating system

Windows 10

### CPU

n/a

### 86Box version

v4.1.1 build 5634

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

It can even easily happen that you can have caps turned on in Windows, launch 86Box, and in the DOS window it'll be lowercase.

**Comment by cold-brewed** [comment]
This is CANTFIX. There is no reliable method to determine and/or set the lock states that works across all platforms.

Virtualization programs tend to accomplish this with kernel modules along with guest additions - neither of which are in scope for 86Box.

A lock indicator is planned for the future. But it will not sync the state with the host, only display that of the running system.
