### ISSUE TITLE
UI 4:3 integer scale fullscreen scaling is not integer scaled it is using hidpi scaling

### ISSUE THREAD

**Issue by Sunspark-007** [86Box/86Box#4379]
### What happened?

Look closely at the "e","m" and "o" letters in the examples.

In a window set to 1x 4:3 integer and nearest, this is what it looks like:

![image](https://github.com/86Box/86Box/assets/73711243/d07916ad-b551-45ce-aee4-40143318b66e)

In a window set to 1x 4:3 integer and hidpi scaling, this is what it looks like:

![image](https://github.com/86Box/86Box/assets/73711243/f194d521-c437-4c2f-a21b-d7b3f44f5d82)

So far it makes sense, because hidpi scaling is not integer scaling and you can see that the letters are shaped differently between the two scaling modes.

Now, in fullscreen 4:3 integer scale mode:

![image](https://github.com/86Box/86Box/assets/73711243/03836320-9647-4862-926e-cf2066e27355)

It is the same scaling as hidpi mode.

What should happen here in my opinion, is that if the hidpi is checked ON, then it can stay as it is, but if it OFF, then if the physical  resolution of the monitor is known and there is room to do 2x, 3x, etc. scaling, then go ahead and do so.. but if it cannot fit 2x without running out of black borders, then just do 1x.

### Configuration file

```ini
n/a
```

### Operating system

Windows 10

### CPU

Core 2 Duo

### 86Box version

v4.1.1 build 5634

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
NOTABUG. You're just not understanding what's going on. It appears you're using 200% HiDPI scalling, so in Windowed mode, in with 1x scaling + HiDPI on in 86Box, it's effectively being scaled to 2x. In full screen, HiDPI is completely ignored and it is being scaled as closely as possible to your physical resolution which turns out to produce the same 2x scale. Because yes, it is 2x relative to the actual 86Box buffer.

**Comment by Sunspark-007** [comment]
@OBattler I'm using 150% logical scaling. I figure the window when set to integer should only render in physical increments so it can snap to actual pixels, not logical. The resolution of my monitor is 2048x1152, a VGA window of 720x480 SHOULD be capable of 2x pixel-perfect. If I had a 1440 resolution, then 3x, but it is not even doing 2x here. It is scaling 1x to a fractional which isn't correct output so the letters are rendered differently on the same row (which is weird).

To prove it, here is 2x scale in a Window with bars hidden to make it fit properly.. so, I pose you this question. If the letters render like this in a Window why can't it ALSO render like this in fullscreen where there is plenty of space to fit 720x480 to 1440x1080 scaling?

Fullscreen does have a scaling issue.

![image](https://github.com/86Box/86Box/assets/73711243/8f60b856-5faa-46d2-a770-5fd9c2c57bd5)
