### ISSUE TITLE
BeOS 5.0 Professional cannot mount install CD

### ISSUE THREAD

**Issue by Lana-chan** [86Box/86Box#438]
Using the BeOS 5.0 Professional image available in WinWorldPC and a .CUE file properly indicating the three tracks present in the image, I'm able to boot the install CD and install BeOS onto a virtual hard drive using PCem. However, the following happens attempting the same on 86Box:

![image](https://user-images.githubusercontent.com/9155588/67151685-e065ca80-f29f-11e9-9429-7174dc6a7773.png)

Interestingly, if I use the virtual hard drive from the PCem where I did get the installation to work on 86Box with the same machine configuration, the OS starts up and works just fine. The reason I want to use 86Box instead of PCem is that I only got networking on BeOS to work on the former.

The exact same issue still happens if I try booting the BeOS CD from a SCSI-configured CD drive.

Here's a copy of my configuration file attached.

[86box.cfg.txt](https://github.com/86Box/86Box/files/3747205/86box.cfg.txt)

**Comment by Lana-chan** [comment]
I realize this issue is similar in nature to one already closed, #172, however given that the same files and settings work in PCem, this seems to indicate there might be a bug somewhere in 86Box. I'll be happy to help debug.

Here are the images and the .CUE file I'm using:
https://winworldpc.com/product/beos/5
https://learn.adafruit.com/build-a-bebox-with-beos-and-virtualbox/set-up-the-cd-image

**Comment by dhrdlicka** [comment]
I seem to get a bit further with BetaArchive's BeOS 5.0 Personal copy:
![](https://i.imgur.com/1fWS2iq.png)

I suspect that the provided cue-sheet might not match your disc image.

**Comment by dhrdlicka** [comment]
![](https://i.imgur.com/NMVpKiw.png)

After switching to SCSI (and finding out that the Jetway does not really like that), I finally booted into the installer. Seems it doesn't like something with 86Box's ATAPI stuff.

**Comment by dhrdlicka** [comment]
**_okay what_**

After some experimentation, I found out with `ccd2cue` that the cuesheet is in fact correct. 86Box seems to expect a trailing newline at the end of the file (which `ccd2cue` does add). Addding a blank line to the end of the file seems to fix the issue.

![](https://media.giphy.com/media/1X7lCRp8iE0yrdZvwd/giphy.gif)

**Comment by dhrdlicka** [comment]
Cue sheet parser bug was fixed in 93e6b9bc703af8f57f0ebd0d8686a892c0fa67e4, also created a new issue (#439) for the ATAPI trouble.
