### ISSUE TITLE
Machine is slower with dynamic recompiler on than when it is off

### ISSUE THREAD

**Issue by Sunspark-007** [86Box/86Box#4389]
### What happened?

This link at https://web.archive.org/web/20201112012244/https://www.alternatewars.com/Games/DOSBox/DOSBox.htm showing Norton SysInfo CPU performance on physical hardware with green bars and Dosbox cycle equivalents in yellow is interesting.

On a 486DX2-66 86Box machine I wanted to see how the CPU benchmark fared in sysinfo6.

A physical machine should score 141.7 according to the table.

I scored 126.9 with the dynamic recompiler turned ON, and when I turned it OFF I scored 137.9.

Pretty good! It's close to the performance of a real CPU (maybe cycle count could be adjusted a tad to inch it up to match?).

I didn't expect the dynamic recompiler to have worse performance though.. is this expected? It is a default setting.

### Configuration file

```ini
n/a
```

### Operating system

Windows 10

### CPU

Core 2 Duo

### 86Box version

v4.1.1 build 5634

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
What emulated CPU? We ask for the configuration for a reason.

**Comment by OBattler** [comment]
Ahhh, a 486. Yes, this is normal, the recompiler uses different timings from the interpreter.
