### ISSUE TITLE
BeOS crashes when booting off an ATAPI CD-ROM drive

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#439]
This is a spin-off of #438.

BeOS 5.0 seems to have problems trying to boot from an ATAPI CD-ROM drive. Works fine when I use a SCSI CD-ROM drive with the BusLogic BT-958D SCSI adapter.

![](https://i.imgur.com/1fWS2iq.png)

**Comment by OBattler** [comment]
This is fixed by the latest commit, therefore I am closing it now.
