### ISSUE TITLE
DR-DOS 6: EMM386 error with Diskopt defragment program

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4390]
### What happened?

I used the Diskopt program to defragment the compressed drive C, (I used the SuperStor v1.3 included on DR-DOS 6).
The program run too slow even when I use the RAM speed option for the HDD, with the compressed drive. The host drive D runs fast and fine.
I don't know what cause this.

Screenshot: 

![Monitor_1_20240421-210029-680](https://github.com/86Box/86Box/assets/31600563/3338af56-278d-4dba-a01a-bb5863d1f5c5)

NVR, HDD, and CFG files: 
https://drive.google.com/file/d/1xjtefVfrTcu0aK61hfo2Mtb1F6_mX8l_/view?usp=sharing

### Configuration file

```ini
[Sound Blaster v2.0]
base = 0220
mixaddr = 0240
irq = 5
dma = 1
opl = 1
cms = 0
receive_input = 1

[General]
vid_renderer = qt_software
rctrl_is_lalt = 1
enable_overscan = 1
sound_gain = 4
vid_resize = 1
video_gl_framerate = 30
video_fullscreen_scale = 2
dpi_scale = 0
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 5701
uuid = af72ab55-9689-5647-9c7c-5b2ca9112028
video_gl_vsync = 1

[Machine]
machine = awardsx
cpu_family = i386sx
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = local
fpu_softfloat = 0
cpu_waitstates = 8
mem_size = 8192

[Video]
gfxcard = orchid_s3_911
show_second_monitors = 0

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sbprov1
fm_driver = ymfm
mpu401_standalone = 1
sound_type = int16

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_fn = 
hdd_01_speed = ramdisk
hdd_01_vhd_blocksize = 1024
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd

[Paradise WD90C30-LR]
memory = 1024

[S3 86c911 ISA (Orchid Fahrenheit 1280)]
memory = 1

[Roland MT-32 (New) Emulation]
output_gain = 100
reverb = 1
reverb_output_gain = 100
reversed_stereo = 0
nice_ramp = 1

[Roland MPU-IPC-T]
base = 0330
irq = 2
receive_input = 1

[Sound Blaster Pro v1]
base = 0220
irq = 7
dma = 1
opl = 1
receive_input = 0
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.2.0.5701

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Fenix770** [comment]
Works without EMM386.SYS loaded, but still takes a lot of time. Also the SSTOR utility says there is 99% of space save when it is 25% due its 1.5:1 compression ratio.

![Monitor_1_20240422-185733-276](https://github.com/86Box/86Box/assets/31600563/c7bbe973-2c5e-4cda-96d4-38676ead3fbe)


![Monitor_1_20240422-185845-032](https://github.com/86Box/86Box/assets/31600563/d4a6047e-514b-4b58-a9c7-e607e19e74a4)

**Comment by OBattler** [comment]
NOTABUG.

First, yes, compressed drives are going to be slow because the compression/decompression is done entirely on the CPU and you're using a 386SX/25, which is very slow.

Second, free space on a compressed drive is always an estimate, as the actual amount of space depends on what kind of data you're going to put there, as not all kinds of data compress equally well.

**Comment by Fenix770** [comment]
Yes, but what about the EMM386 error?

**Comment by OBattler** [comment]
I'm not exactly sure why that happens, it could be a simple incompatibility.
