### ISSUE TITLE
Big emulation slowdown caused on 386 machines by EMM386

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4395]
### What happened?

For some reason I get a solid 100% in CPU emulation without EMM386 on 386 SX/DX machines. But with EMM386 enabled It fall to 67%-85% at DOS prompt only. This is present in almost all DOS versions, but is more noticeable on DR-DOS 6.

I created a clean install of DR-DOS 6 to test it.

Screenshots: (notice the drop from 99-100% to 67%)

Without EMM386:
![DR-DOS 6 Without EMM386 ](https://github.com/86Box/86Box/assets/31600563/0ff46819-fe82-489e-8dcf-461890c4472a)

With EMM386:
![DR-DOS 6 with EMM386](https://github.com/86Box/86Box/assets/31600563/a57df2f1-3a76-487f-94eb-02a32a1ef883)

HDD image file: 
[386 SX DR-DOS Español-Test.zip](https://github.com/86Box/86Box/files/15083073/386.SX.DR-DOS.Espanol-Test.zip)

### Configuration file

```ini
[Tseng Labs ET4000AX (TC6058AF) (ISA)]
memory = 1024
bios_ver = v1_10

[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 5701
uuid = 884c77d6-c51a-551b-9f6a-261604238c75

[Machine]
machine = 325ax
cpu_family = i386sx
cpu_speed = 25000000
cpu_multi = 1
mem_size = 4096
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local

[Video]
gfxcard = et4000ax_tc6058af

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sbprov1
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_ide_channel = 0:0
hdd_01_speed = ramdisk

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.2.0.5701

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Install an idle program such as IDLE.COM.

**Comment by OBattler** [comment]
This is now fixed - add cpu_override_interpreter=1 to the Machine section of 86box.cfg.
