### ISSUE TITLE
ALT+TAB pressed in Guest is always being send to Host aswell - despite cursor captured by guest. No way to change this behaviour. "Keyboard requires Capture" not working as explained in manual.

### ISSUE THREAD

**Issue by tokariu** [86Box/86Box#4399]
### What happened?

I have the following Situation:
Host: Windows 10
Guest: Windows 98

I want to switch between programs in my Guest using ALT+TAB key-combination.
Whenever I press ALT+TAB it does however also switch tasks simultaneously on the HOST OS.
There is obviously no way to change this behaviour.
The 86box manual mentions the "Keyboard requires capture"-option, this however seems to only affect the Guest OS when the Guest is not focus / mouse captured.
It is however not affecting the Host when pressing ALT+TAB inside the Guest.

Whatever option is selected - it is sending the ALT+TAB combination to the Host regardless, always opening the task switcher on both OS at the same time.

This is also happening in Guest-Fullscreen, with all Renderers (Qt, GL, Vulkan).

We need a way to block ALT+TAB key combination for the HOST when it is press in a CAPTURED GuestOS.

### Configuration file

```ini
[General]
vid_renderer = qt_vulkan
host_cpu = Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
emu_build_num = 5700
uuid = c69bbaea-bf7b-53ed-9aa3-4a5eda09a7b0
video_fullscreen_first = 0
mouse_sensitivity = 1.41
video_fullscreen_scale = 2
dpi_scale = 0

[Machine]
machine = p54tp4xe
cpu_family = pentium_p55c_od
cpu_speed = 166000000
cpu_multi = 2.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 131072

[Video]
gfxcard = mystique

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sbawe32_pnp

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_pci
cassette_mode = load

[Matrox Mystique]
memory = 4

[3Dfx Voodoo Graphics]
type = 0
framebuffer_memory = 2
texture_memory = 2
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[Standard PS/2 Mouse]
buttons = 5

[Sound Blaster AWE32 PnP]
onboard_ram = 28672
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[Hard disks]
hdd_01_parameters = 63, 16, 4111, 0, ide
hdd_01_fn = hd.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 1:1

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 32
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Windows 10

### CPU

Intel Core i7

### 86Box version

v4.2 b5700

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by tokariu** [comment]
> NOTABUG. Such system key combinations can not be blocked. Enable the "Right Ctrl is left Alt" option and use Right Ctrl + Tab to sent Alt + Tab to the guest.

if that is the best workaround, then please consider letting us choose custom key-bindings. Alt-Tab is a one-hander of the left hand, whereas RightCtrl-Tab is a two-hander particulary when you are using a mouse in the guest. The un-capture keycombination F8-F12 is also making trouble with various software I have tried to run in 86box so far.

**Comment by tokariu** [comment]
> Such system key combinations can not be blocked.

I'd also like to contradict that. Have you tried running a Fullscreen app in a VMware guest yet? in VMware hotkeys like ALT+TAB are then blocked towards the Host-OS.

**Comment by OBattler** [comment]
VMWare uses a kernel-mode driver so it can do that. 86Box does not and has to make do with whatever the OS allows a user-mode application to do.

**Comment by OBattler** [comment]
And we do ho have the configutation of keyboard shortcuts in the plans, there's an open issue about it, I believe.

**Comment by OBattler** [comment]
OK, apparently it's doable using low-level keyboard hooks but there's a problem - those don't really work when raw input is in use and we use raw input because Microsoft themselves recommend it due to both VK input and DirectInput reporting of non-alphanumeric key presses being inconsistent across keyboard layouts, as both VK codes and DirectInput key codes (which are basically identical to the VK codes) represent the character produced by the key instead of the actual key pressed. I believe the idea was so that shortcut keys would be consistent, ie. Ctrl+:, for example, would always be Ctrl+<whatever key produces or key combination :>, but this doesn't work well even for games, let alone for an emulator. Now, games usually don't have to block ALT+TAB, only emulators do, at that, only PC emulators do, and they'e still a very niche thing, so we're stuck in this mess.

**Comment by kkwpsv** [comment]
`RegisterRawInputDevices` with `RIDEV_INPUTSINK` can get these keys like `ALT+TAB`, but cannot handle them. Windows still respond to them.
So maybe the only way is low-level keyboard hooks. It can handle these keys. It has keyboard scancode and should be able to meet our needs?

**Comment by OBattler** [comment]
While it's a good idea, it has its own pitfall - it makes 86Box basically impossible to debug by causing keyboard input to become unusably slow in GDB when 86Box crashes.

**Comment by OBattler** [comment]
But I can solve that easily - keep raw input in but add a parameter to enable it (and disable the hook) which can be used when debugging.

**Comment by jonathanp12** [comment]
I know this issue is closed but I wanted to let people know.

I use this AutoHotkey script (I called 86Box.ahk) for a while now when I use 86Box, which software I love by the way, and it works perfectly.
```
#Requires AutoHotkey v2.0

; The option 'Right CTRL is left ALT' must be enabled.

#HotIf WinActive("ahk_exe 86Box.exe")
{
    LAlt::RCtrl
    RAlt::RCtrl    
    RCtrl::LCtrl
}
```

FYI Razer Synapse is able to block Alt+Tab properly when in gaming mode.
