### ISSUE TITLE
[BUG] Build 1898+ (commit A495FAEC) DESQView/X graphics window corruption; 86box.cfg bug

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#440]
I have a problem with 86Box Build 1898 (commit A495FAEC) and higher. In DESQView/X 2.1, I'm trying to run DOS and Windows 3.1 in a X window and everytime I try to move the window, the windows inside the screen is corrupt.

The graphics corruption wasn't present in build 1897. However, I suspect the changes to the Direct3D in full-screen mode transferring control of input to the full screen window as well as fixing numerous graphics-related bugs caused this.

Here are some screenshots of what I'm talking about in Build 1898 and higher

1. Windows 3.1 X Window:
![20191021-072201-797](https://user-images.githubusercontent.com/32658796/67185617-15a31300-f39b-11e9-9b9d-2a5d5a9d62ab.png)

2. Command Prompt X Window:
![20191021-072242-178](https://user-images.githubusercontent.com/32658796/67185646-294e7980-f39b-11e9-8413-1f37c173d777.png)

3. DESQView/X Help:
![20191021-072305-015](https://user-images.githubusercontent.com/32658796/67185673-38352c00-f39b-11e9-8c22-ef257b4a4f87.png)

Here are a couple of screenshots of what the DESQView/X window used to look like in Build 1897:
1. Windows 3.1 X Window:
![20191021_004237](https://user-images.githubusercontent.com/32658796/67186056-125c5700-f39c-11e9-831b-c0747c2b77d3.png)

2. Command Prompt X Window:
![20191021_004303](https://user-images.githubusercontent.com/32658796/67186068-19836500-f39c-11e9-89b2-ef2ff44e3b81.png)

The graphics card that was used was the Tseng ET4000AX graphics card with 1 MB of display memory on the MB-495SX with 32 MB of RAM.

I have posted the contents of the 86Box.cfg file on Pastebin.com: https://pastebin.com/qUteXt3K

Can anyone test this issue on the Tseng ET4000AX graphics card and possibly other graphics cards that might be affected by this bug? Let's hope that this bug gets fixed soon or I could be stuck on Build 1897 until this bug is fixed.

Also, in the [Other removable devices] section] of the 86Box.cfg file, the blank cdrom_xx_scsi_id parameter gets added when the 86Box.cfg file gets created. Here is an example:

[Other removable devices]
cdrom_01_scsi_id = 0
cdrom_02_scsi_id = 0
cdrom_03_scsi_id = 0
cdrom_04_scsi_id = 0

When there is no CD-ROM attached to the emulated 86Box VM, the cdrom_xx-scsi_id parameter shouldn't even be there.

Please correct this bug that causes this.

Thank you for your time.

**Comment by MoochMcGee** [comment]
@ppgrainbow Can you please upload your 86Box VM in its entirety so that @OBattler can debug this issue?

**Comment by ppgrainbow** [comment]
I'm working on it. I already created a test VM, "DESQVIEW_X .21", installed MS-DOS 5.0a, Windows 3.1 and currently installing DESQView/X.

When I'm all finished, I will upload the 86Box VM including the hard disk image, 86Box.cfg file and NVR in a ZIP file to the 86Box FTP. :)

I don't want to upload a ZIP file with 11.8 GB worth of hard disk images on my network connection since it would take too long.

**Comment by OBattler** [comment]
Oops, forgot to make the commit auto-close that. Closing this manually, then.
