### ISSUE TITLE
VFAT Device Initialization Failed (After Setup Phase installing Windows 98 Build 1411, and 1415)

### ISSUE THREAD

**Issue by kralouf** [86Box/86Box#4408]
### What happened?

I attempted to install both of these builds, I got through the setup phases, and right before booting, I get this error: 
![image](https://github.com/86Box/86Box/assets/114093052/73c30efd-936e-422d-ba70-ce0784758fe7)
I have attempted these troubleshooting Steps:
1. INITIALLY: Drive was a 2GB (4063c, 16h, 63s) Dynamic VHD, partitioned to FAT32 from a Win98 Boot Disk, got the error
2. Re-formatted the drive as a FAT16 Partition, got the same error.
3. Re-created the drive as a .img instead of a Dynamic VHD (Formatted as a FAT16 Partition) got the same error again.

NOTE: This error has happened every single time after the setup phase is complete.

I am at a loss, any documentation I find online refers to a file, but for the configuration, that file is nowhere to be found. Any advice/help is appreciated. Thank you!

### Configuration file

```ini
[General]
vid_renderer = qt_software

[Machine]
machine = thor
cpu_family = pentium_p54c
cpu_speed = 90000000
cpu_multi = 1.5
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
mem_size = 65536

[Video]
gfxcard = px_trio64_pci

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sb16
fm_driver = nuked

[Network]
net_01_card = novell_ne2k
net_01_net_type = slirp
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = 4.10.1415.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_02_type = 525_2hd
cdrom_01_speed = 48
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = 4.10.1415_x86fre_client_en-us-WIN98BETA2.iso
cdrom_01_type = 86BOX_CD-ROM_1.00
fdd_01_image_history_01 = E:/VM/Boot Disks/Windows98_SE_No_Ramdrive.img

[Novell NE2000 #1]
mac = 43:f7:73
```

### Operating system

Windows 10

### CPU

AMD Ryzen 5 2600

### 86Box version

v4.1.1 build 5634

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

If you would like to reach out directly, My discord username is Louis7864 (I am in the server if you need to ping me) Thank you!

**Comment by TC1995** [comment]
You can try the nightly builds.

**Comment by kralouf** [comment]
UPDATE:

Talked with TC1995 and OBattler and did the following troubleshooting steps:

1. Switched from 4.1.1.5634 --> 4.2.5720, formatted as FAT16, same size (.img) same error
2. Switched from Intel Advanced/ATX Machine --> ASUS P/I-P54TP4XE, formatted as FAT16, same size (.img) NO ISSUES! Boots up and no VFAT error comes up!

Updated .cfg:

`[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 5 2600 Six-Core Processor            
emu_build_num = 5720
uuid = b206a68a-4a60-5449-b2ee-5e3bc4219baf

[Machine]
machine = p54tp4xe
cpu_family = pentium_p54c
cpu_speed = 90000000
cpu_multi = 1.5
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
mem_size = 65536

[Video]
gfxcard = px_trio64_pci

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sb16
fm_driver = nuked

[Network]
net_01_card = novell_ne2k
net_01_net_type = slirp
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = 4.10.1415.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_02_type = 525_2hd
cdrom_01_speed = 48
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = 4.10.1415_x86fre_client_en-us-WIN98BETA2.iso
cdrom_01_type = 86BOX_CD-ROM_1.00
fdd_01_image_history_01 = E:/VM/Boot Disks/Windows98_SE_No_Ramdrive.img

[Novell NE2000 #1]
mac = 43:f7:73
`

**Comment by OBattler** [comment]
Also note that these are Beta's, so the driver itself my be buggy as well. As such, I'm closing this as NOTABUG. It can be reopened if it's ever confirmed not to occur on real hardware.
