### ISSUE TITLE
[BUG] No sound on Adlib Gold & MT-32

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#441]
Hello!

I found two sound bugs In the latest 2.0 commit):

1. I tested the AMI 386 DX with the Adlib Gold card and it does not reproduce any sound. I tested the same configuration in Pcem and it works.

2. I tested both native MT-32/CM-32 emulation and system MIDI with Munt MT-32 passtrought emulation. on both cases there is no sound. In Pcem I used SB16 and Munt MT-32 as  system MIDI and it works. Munt also works with dosbox. (I installed the 64-bit version of Munt)

Here is the hdd Image file with the drivers installed in DOS and Win 3.1. You can test the Jukebox in C:\gold.

[https://drive.google.com/open?id=1MvGpebcToTAmk9v0OapT4wxgMOFLlsEq](url)

**Comment by OBattler** [comment]
Did you try setting float to 16-bit integer (by making it not FLOAT32)? Because MIDI works fine on my end.

**Comment by TC1995** [comment]
I've tested everything, works fine on my end, maybe on the OPL side, the volume is too low.
MT32 works fine too.

**Comment by Fenix770** [comment]
I tested again. The MT-32/CM-32 works with the standalone MPU-401 option enabled.  But the Adlib Gold does not, with or without the Float32 option. I tested with 386DX and 486SX machines with no avail. I don't know if i'm doing something wrong.

PD: I noted, in the Jukebox, that the volume appear in the  minimum in 86box and in the maximum in PCem. (I use the same hard disk in both cases)
In 86box nothing can be heard even with the volume in the maximum. 

Thanks!

**Comment by TC1995** [comment]
Well, I still find no issues on my end, I mean, I can hear audio fine in the AdLib Gold, both wave and midi from it.

**Comment by dhrdlicka** [comment]
> The MT-32/CM-32 works with the standalone MPU-401 option enabled.

Yes, that's the expected behavior. You couldn't connect an MT-32 directly to the computer back in the day, either.

**Comment by OBattler** [comment]
He means that it works with standalone MPU-401 but not with Sound Blaster 16's MPU-401.

**Comment by OBattler** [comment]
> PD: I noted, in the Jukebox, that the volume appear in the minimum in 86box and in the maximum in PCem. (I use the same hard disk in both cases)
This would explain the difference, I need to see why that is, likely the default values are wrong in 86Box.

**Comment by Fenix770** [comment]
I tested it again. The MIDI files in Windows 3.1 plays correctly.the issue seems to ocur in DOS applications and games (I tested Lost Vikings).

**Comment by TC1995** [comment]
Well, jukegold plays fine on my end within DOS. And I can hear audio too.

**Comment by Fenix770** [comment]
I found the issue.  Aparently it was a configuratio issue. The DMA config must be 1 is for the sound card and 0 and 3 are for SCSI adapters.

**Comment by OBattler** [comment]
You should probably install a DOS driver for the card that would configure the mixer correctly.

**Comment by Fenix770** [comment]
As said before. The drivers are installed in both DOS and Windows 3.1. The jukegold.bat file launches these drivers automatically. And in Pcem can load the  jukebox.bat directly after booting DOS, and playing a midi/sound file in win 3.1 and exiting to DOS is not required to play the jukebox or game.

**Comment by OBattler** [comment]
Since this is a notabug, it can be closed.
