### ISSUE TITLE
[ENHANCEMENT] Cache Random Access Memory (RAM)

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#442]
Here's what I'm suggesting in future revisions of 86Box: Cache Random Access Memory (Cache RAM, cache memory or CPU memory)...is a high-speed static random access memory (or SRAM that a computer microprocessor can access more quickly than it can access regular RAM.

Here are a couple of familiar motherboards that are emulated under 86Box that have support for cache RAM:

1. DataExpert MB-495SX Rev 1.0: https://stason.org/TULARC/pc/motherboards/D/DATAEXPERT-CORPORATION-486-OPTI-495SX.html

The cache RAM configuration can be 64 KB, 128 KB or 256 KB.

2. DTK PKM-0038 E-2: https://stason.org/TULARC/pc/motherboards/D/DTK-COMPUTER-INC-486-PKM-0038S-VER-6-02.html

The cache RAM configuration can be 128 KB, 256 KB or 512 KB.

3. Packard Bell PB410A: https://stason.org/TULARC/pc/motherboards/P/PACKARD-BELL-486-PB410-PB420-420T-REVISION-B.html

The cache RAN configuration can be 32 KB, 128 KB or 512 KB.

We're gonna need to find out the real motherboard names of the "AMI ALi-1429", "AMI SiS-471", "AMI WinBIOS 486", "AMI SiS-471", "AMI WinBIOS Sis-471" as well as the "Award 386/486 clones" to determine the minimum and maximum cache RAM sizes. I'll probably ask about this in my next report.

If you believe that there is no need to implement cache RAM and it's useless, then the cache memory will need to be disabled in the CMOS setup.

**Comment by OBattler** [comment]
This would be very difficult to implement without destroying performance.

**Comment by ppgrainbow** [comment]
Thank you for the input. Any idea why cache RAM would be difficult to implement without destroying performance?

**Comment by CRTRevivalDreamer** [comment]
> Here's what I'm suggesting in future revisions of 86Box: Cache Random Access Memory (Cache RAM, cache memory or CPU memory)...is a high-speed static random access memory (or SRAM that a computer microprocessor can access more quickly than it can access regular RAM.
> 
> Here are a couple of familiar motherboards that are emulated under 86Box that have support for cache RAM:
> 
> 1. DataExpert MB-495SX Rev 1.0: https://stason.org/TULARC/pc/motherboards/D/DATAEXPERT-CORPORATION-486-OPTI-495SX.html
> 
> The cache RAM configuration can be 64 KB, 128 KB or 256 KB.
> 
> 1. DTK PKM-0038 E-2: https://stason.org/TULARC/pc/motherboards/D/DTK-COMPUTER-INC-486-PKM-0038S-VER-6-02.html
> 
> The cache RAM configuration can be 128 KB, 256 KB or 512 KB.
> 
> 1. Packard Bell PB410A: https://stason.org/TULARC/pc/motherboards/P/PACKARD-BELL-486-PB410-PB420-420T-REVISION-B.html
> 
> The cache RAN configuration can be 32 KB, 128 KB or 512 KB.
> 
> We're gonna need to find out the real motherboard names of the "AMI ALi-1429", "AMI SiS-471", "AMI WinBIOS 486", "AMI SiS-471", "AMI WinBIOS Sis-471" as well as the "Award 386/486 clones" to determine the minimum and maximum cache RAM sizes. I'll probably ask about this in my next report.
> 
> If you believe that there is no need to implement cache RAM and it's useless, then the cache memory will need to be disabled in the CMOS setup.

You forgot the Apollo by American Megatrends, which supports either 256 kB or 512 kB of external cache RAM:
https://stason.org/TULARC/pc/motherboards/A/AMERICAN-MEGATRENDS-INC-Pentium-APOLLO.html

**Comment by ppgrainbow** [comment]
Thank you for pointing that out. :)

**Comment by OBattler** [comment]
> If you believe that there is no need to implement cache RAM and it's useless, then the cache memory will need to be disabled in the CMOS setup.

We emulate the cache *timings*, so I'm not going to be disabling that.

Other than that, cache is impossible to implement without destroying performance, so as such, I'm closing this issue.
