### ISSUE TITLE
Bug in MIDI playback using Sound Blaster AWE32's built-in sound fonts (drums are not played)

### ISSUE THREAD

**Issue by nanitaro** [86Box/86Box#4428]
### What happened?

Hello.

Guest OS: WIndows98 SE(Jpn)
sbawe.vxd version 4.38.2 (probably the last official driver for 9x)
AWE Control Panel v2.05

Set the sound font to “Synthgm.sbk”. (This is the standard setting.)
This sound font uses AWE32's internal 1MB-ROM.
All voices except drums will play correctly.
Drums are rarely played back. (Only some hi-hats are played.)
Go to the Playback tab of the AWE Control Panel.
You can also easily check by clicking on the keyboard.

The same behavior is observed in Pcem v17.
Therefore, it is believed that this is a bug that has been ongoing since before the fork.

### Configuration file

```ini
[3Dfx Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 1
recompiler = 1

[Standard PS/2 Mouse]
buttons = 2

[General]
vid_renderer = qt_software
language = ja-JP
confirm_exit = 0
video_filter_method = 0
host_cpu = Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz
emu_build_num = 5727
uuid = e7fadc1f-d99d-5bbb-96d3-8a0ba5e13b06

[Machine]
machine = 5ax
cpu_family = k6_3p
cpu_speed = 100000000
cpu_multi = 1.5
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 524288

[Video]
gfxcard = virge357_agp
voodoo = 1

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sbawe32
fm_driver = nuked
midi_device = system_midi

[Network]
net_01_card = pcnetfast
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0
net_01_net_type = slirp

[Ports (COM & LPT)]
serial1_enabled = 0
serial2_enabled = 0
lpt1_enabled = 0
lpt1_device = postscript

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 4161, 0, ide
hdd_01_fn = D:/Virtual Machines/98-Ali.img
hdd_02_parameters = 63, 16, 4161, 0, ide
hdd_02_fn = D:/Virtual Machines/98-1.img
hdd_01_speed = ramdisk
hdd_02_speed = ramdisk
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_image_history_01 = R:/
fdd_01_image_history_01 = D:/emu/86BoxManager/ctcm7.86f
cdrom_01_image_history_02 = D:/Virtual Machines/files/Win98SE.iso
cdrom_01_type = 86BOX_CD-ROM_1.00

[AMD PCnet-FAST III #1]
mac = 67:84:12

[Sound Blaster AWE32]
base = 0220
emu_base = 0620
base401 = 0330
irq = 5
dma = 1
dma16 = 5
onboard_ram = 28672
opl = 1
receive_input = 1
receive_input401 = 0

[Matrox Productiva G100]
memory = 16

[S3 ViRGE/GX2 (357) AGP]
bilinear = 1
dithering = 1

[Matrox Millennium II]
memory = 8

[Matrox Mystique 220]
memory = 8

[MIDI Input Device]
midi_input = 0
realtime = 0
thruchan = 1
clockout = 1

[System MIDI]
midi = 1
```

### Operating system

Windows 11

### CPU

Intel Core i5-1035G4

### 86Box version

4.2.0.5727

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
I actually listened to a playthrough of canyon.mid on the emulated AWE32 - the drums are there, they are just very quiet so they barely come through.

**Comment by nanitaro** [comment]
[https://www.youtube.com/watch?v=W_T1zVUuwWE](url)
The first part of this video is the performance of “canyon.mid” by the actual AWE32 and its built-in ROM.
I can certainly hear the drums.

![awe32cpl](https://github.com/86Box/86Box/assets/50589546/86815d7e-4484-4a8f-9b25-a76d485688dc)
This is the AWE32 control panel application.
Clicking on the keyboard in this screen plays the corresponding sound, but only the drums (instrument set to 128-standard) are almost silent.

**Comment by OBattler** [comment]
I'm going to close this as CANTFIX since the E-MU 8000 emulation is as good as it can get (save for chorus and reverb) with the currently available documentation.
