### ISSUE TITLE
It occure several cursor in CGA mode

### ISSUE THREAD

**Issue by leesa49** [86Box/86Box#443]
I don't know if it's a problem with the SPC4200 or the whole.

Occurs when you press and hold the Enter key in CGA mode

I see several cursors

![4  It occure several cursor when Enter Key](https://user-images.githubusercontent.com/55971868/67649127-1deee580-f97b-11e9-8730-493688413ea7.png)

**Comment by dhrdlicka** [comment]
That seems to be CGA snow, a design flaw that affects the 80-column text mode on the original CGA. 

You can disable it in the CGA configuration if you consider it annoying.

**Comment by leesa49** [comment]
Oh Thank you VERY MUCH. 
I didn't know what snow-emulation funcion was doing.
