### ISSUE TITLE
[Feature Request] Allow the emulation of ESDI hard disks with more than 1023 cylinders

### ISSUE THREAD

**Issue by thunderbird32** [86Box/86Box#444]
I'm attempting to emulate an ESDI hard disk, and it appears that they often had more than 1023 cylinders. For instance, the [326MB Fujitsu M2261E](https://stason.org/TULARC/pc/hard-drives-hdd/fujitsu/M2261E-326MB-5-25-FH-ESDI.html) has the following geometry (C/H/S): 1658/8/53. As another example the [151MB Micropolis 1654-7](https://stason.org/TULARC/pc/hard-drives-hdd/micropolis/1654-7-151MB-5-25-HH-ESDI.html) (C/H/S): 1249/7/36. The "Add New Hard Disk" dialog _will_ allow SCSI disks to have those larger cylinder counts, but not ESDI.

**Comment by OBattler** [comment]
This is fixed in v2.05.

**Comment by OBattler** [comment]
This has been resolved.
