### ISSUE TITLE
[BUG] PC/AT ESDI Emulation Broken

### ISSUE THREAD

**Issue by thunderbird32** [86Box/86Box#445]
I'm having a problem setting up ESDI on an emulated PC/AT. I've set the "HD Controller" to "[ISA][ESDI] PC/AT ESDI Fixed Disk Adapter", and setup a hard disk with the geometry (C/H/S) 855/5/35. I then boot the emulated system and set the system options. Then I boot into DOS and invoke the ESDI controller firmware ("debug" followed by "G=C800:5"). In the firmware I select "Set Drive Type & Exit". I set the drive type to the autodetected geometry (855/5/36). Then I reboot the machine so I can do the low level format (option 2 in the controller's firmware). However, the machine crashes immediately after the RAM test. To get the machine to do anything after that, I need to delete the nvr file for the emulated machine.

Now I realize the geometry is off by one sector per track, but as the firmware doesn't allow you to set this manually (you can only pick from a set of pre-set options), I tried the closest option. I also tried to set the geometry of the emulated disk to match, but then the controller autodetects the drive as 855/5/35. So either it's supposed to be off by one, or there's an issue with the emulation. Regardless, the crash on boot is the primary problem.

I have attached the config file. This is on the most recent (as of 10/30) Skylake Optimized build.

[Config.zip](https://github.com/86Box/86Box/files/3791462/Config.zip)

**Comment by OBattler** [comment]
I got rid of the crash, but it's still insisting at misdetecting the drive for some reason. It detects 2 tracks less and 1 sector less, for some reason.

**Comment by OBattler** [comment]
OK, I now have it working. The tracks and sectors discrepancy remains, but at least it now formats and boots fine.

**Comment by OBattler** [comment]
This is fixed in v2.05.

**Comment by thunderbird32** [comment]
If I attempt to setup an ESDI drive on the "[386DX ISA] AMI 386DX clone" system (same controller as before), when go into the controller firmware and select the geometry it locks up the system. After rebooting it appears that it has entirely cleared my CMOS settings.

**Comment by OBattler** [comment]
The AMI 386DX clone has an on-board IDE controller on the same ports, so the ESDI controller won't work.

**Comment by OBattler** [comment]
This has been resolved.
