### ISSUE TITLE
Unable to move the mouse in Fedora 7

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#4451]
### What happened?

In Fedora 7, the mouse cursor is stuck and cannot be moved. This was not a problem previously, but the bug may have come about as a result of the PS/2 controller updates. Additionally, there was a GRUB "press any key to enter menu" prompt which is now gone and now automatically goes to the OS selection menu, as if a key was pressed.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 9 7950X 16-Core Processor
uuid = 34c21b37-6df1-5389-a1f8-9eb5c0c26f18
rctrl_is_lalt = 1
confirm_exit = 0
hide_status_bar = 1
hide_tool_bar = 1

[Machine]
machine = vpc2007
cpu_family = celeron_mendocino
cpu_speed = 400000000
cpu_multi = 6
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 524288

[Video]
gfxcard = millennium

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = es1371

[Storage controllers]
hdc = internal

[AMD PCnet-FAST III #1]
mac = 33:f8:81

[Network]
net_01_card = pcnetfast
net_01_net_type = slirp

[Hard disks]
hdd_01_parameters = 63, 16, 8320, 0, ide
hdd_01_fn = fedora7.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_01_check_bpb = 0
fdd_02_type = none
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_image_history_01 = /home/kelsey/isos/flac2.iso
cdrom_01_image_history_02 = /home/kelsey/isos/flac.iso
cdrom_01_image_history_03 = /home/kelsey/isos/F-7-i386-DVD.iso
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Fedora 39

### CPU

AMD Ryzen 9 7950X

### 86Box version

55e1ca7dc14a650d7997b727ed04807acfeb945f

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

Build script:
```sh
#!/bin/bash
HERE=$(pwd)
git pull
cd out
rm -r *
cmake -S .. -B . -DDEV_BRANCH=y -DCMAKE_BUILD_TYPE=RelWithDebInfo && make -j32
STATUS=$?
if [[ $STATUS == 0 ]]
then
	cp src/86Box ..
	echo $(git rev-parse HEAD) > ../commit.txt
	cd $HERE/roms
	git pull
fi

```

If you press a key while Windows 9x is booting (not Esc), the boot screen will disappear and show a blinking text cursor after a while, otherwise the boot screen will remain onscreen until the GUI loads. In this current commit, the blinking cursor shows up even when no keys are pressed, which is why I think GRUB thinks a key was pressed on boot.

**Comment by OBattler** [comment]
Can you upload the VM please?

**Comment by WinFutureX** [comment]
[Here.](https://mega.nz/file/ekpGgTYZ#sHicqBWWIj8VUgQu3kJUJD0dResXsd2uMeD_ckTB2bw)

**Comment by OBattler** [comment]
I can't even boot this - black screen.

**Comment by OBattler** [comment]
Nevermind, it turns out I had swapped the BIOS.

**Comment by WinFutureX** [comment]
While the mouse bug has been fixed, there is still the issue of the keyboard appearing to have pressed keys on startup. For example, this is DOS 5.0 right after boot, without me pressing any keys at all:
![Monitor_1_20240517-182159-922](https://github.com/86Box/86Box/assets/29031916/9b75acb1-8ddb-4683-8937-4f6982e314e0)
This is only a minor issue, since I can just press backspace, clearing the prompt and DOS still works fine.
