### ISSUE TITLE
[BUG] 86box stops responding when the GUS sound card is enabled.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#448]
Hello.

I tried a hard disk image with CD-ROM, mouse, and GUS sound card drivers. The machine stop responding when executing the drivers. At first it stopped when loading the mouse driver, so I disabled the mouse emulation. After the second  crash I removed also the mouse driver, and locked up after the cd-rom driver was loaded.

Finally the machine booted without any issue after I disabled the GUS emulation in the 86box sound configuration.

The machine configuration is AMI 486,  486 DX/33  16mb ram, Paradise Bahamas 64 VLB VGA 2 mb, Internal hdd controller.

**Comment by TC1995** [comment]
For the 486 machines, make sure the hdd controller is set to none as they have a built-in IDE controller.

**Comment by OBattler** [comment]
Can you upload the hard disk image, NVR folder, and 86box.cfg please?

**Comment by OBattler** [comment]
See if v2.05 fixes this.

**Comment by OBattler** [comment]
I'm going to close this since I'm not even sure if this bug still exists.
