### ISSUE TITLE
Generic ESC/P Dot-Matrix Printer does not print graphic screen in games

### ISSUE THREAD

**Issue by usergithub64** [86Box/86Box#4489]
### What happened?

When I connect this printer to LPT1 and download graphics.com to print the game's graphical screen in DOS 6.22, when I click on Print Screen, the in-game graphical screen does not print (the corresponding PNG file does not appear in the Printer folder). At the same time, the default parameters for the LPT port are set in the BIOS. The graphic screen does not print in the games: Digger, Eden, PoP1, PoP2, Wolf3D, Doom. The graphic screen prints normally in the games: Paratrooper, Buck Rogers, CD-MAN (Only support VGA). Moreover, regardless of whether the game only supports VGA, the printer does not print it, for some reason. But most often games that only support VGA are not printed, although PoP supports CGA, but it also does not print. A request to send a graphic screen to print when you click on Print Screen can be determined by the image freezing in the game for 5 seconds. In most games, this 5 second freeze does not occur when you press Print Screen, which means that the request to print the graphical screen in the game does not work.

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
confirm_save = 0
force_43 = 1
confirm_exit = 0
host_cpu = Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
emu_build_num = 5782
uuid = d80219a0-bfd6-5d64-88f3-d4062dd305ac

[Machine]
machine = ami495
cpu_family = i386dx
cpu_speed = 40000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 1
time_sync = local
fpu_type = 387
mem_size = 2048

[Video]
gfxcard = px_trio64_vlb

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = sbawe32

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_vlb_2ch
cassette_mode = load

[S3 Trio64 VLB (Phoenix)]
memory = 4

[Hard disks]
hdd_01_parameters = 63, 16, 987, 0, ide
hdd_01_fn = images/485 MB.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none

[Sound Blaster AWE32 #1]
base = 0220
emu_base = 0620
base401 = 0330
irq = 5
dma = 1
dma16 = 5
onboard_ram = 28672
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 1

[Microsoft Serial Mouse]
port = 0
buttons = 4
```

### Operating system

Windows 10 Pro x64 v22H2

### CPU

Core i9-10900K

### 86Box version

v4.2 Build 5795

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
I don't recall this working on real hardware, either. This can be reopened when it's proven to actually be an 86Box bug.
