### ISSUE TITLE
Various FPUs with softfloat enabled fail the Intel FPU Diagnostics (MCPDIAG, 188k version)

### ISSUE THREAD

**Issue by thedax** [86Box/86Box#4518]
### What happened?

If you run the Intel MCPDIAG application, you'll notice it fails during the Advanced Diagnostics, on the Transcendental Test (and, on the 8087 FPU, the Environment Test).

![image](https://github.com/86Box/86Box/assets/4482745/4abe9e1d-27b9-4905-9ec5-928f827f0fd9)

Steps for reproduction:
-Create any machine with an FPU enabled, and have softfloat enabled. 
-Boot this floppy image (it will autoexec the testing application): [mcpdiag.zip](https://github.com/user-attachments/files/15753124/mcpdiag.zip)
-Once at the main menu, enter the Run Diagnostics/Comprehensive Floating Point Conformance Test (name changes depending on the FPU detected) by pressing 2.
-Wait for the results.

From my testing, the 286 with 287 (**not** XL) is the only combo that passes all of the tests. All other CPU + FPU combos will likely fail. I tested 8088 + 8087, v20 + 8087, 286 + 287XL, 386 + 387, 486 + 487, Pentium 1 and Pentium 2, all of which fail.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 9 5900X 12-Core Processor
emu_build_num = 5828
uuid = c91ae18e-bc9e-5125-9c88-57a1875a9d4b

[Machine]
machine = 4saw2
cpu_family = i486dx2_pc330
cpu_speed = 66666666
cpu_multi = 2
cpu_use_dynarec = 1
fpu_softfloat = 1
time_sync = local
fpu_type = internal
mem_size = 16384

[Video]
gfxcard = mach64gx_pci

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
fdd_01_fn = mcpdiag.flp
fdd_01_writeprot = 1
```

### Operating system

Fedora Linux 40

### CPU

AMD Ryzen 9 5900X

### 86Box version

v4.2 build 5828

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Bisecting was fruitless, it's been this way since the introduction of softfloat. Dynarec has no impact/bearing from my testing.

**Comment by TC1995** [comment]
Been trying to figure out what instruction the Transcendental Test uses for like since I was porting softfloat to here.

**Comment by OBattler** [comment]
Transcendental fails on DOSBox-X, on older 86Box builds with SoftFloat 2, and on newer 86Box builds with SoftFloat 3e, and even a case on real hardware, so that's a clear CANTFIX - not our bug.

Which leaves the Environment test on 808x.

**Comment by OBattler** [comment]
The 8087 failing one of the tests (environment?) is also NOTABUG - MCPDIAG attempts to execute instruction DF E0 which is STSW AX, added on 287. If it doesn't fail on DOSBox-X, then DOSBox-X gives the 8087 that instruction when it shouldn't.

The transcendental test on 8087 involves ATAN - perhaps SoftFloat 3E's ATAN simply has the wrong value range?

**Comment by OBattler** [comment]
OK, so apparently (according to a book I found online in PDF), on 8087, FINIT leaves the C0-C3 flags in an indeterminate state.

**Comment by OBattler** [comment]
OK, it turns out F(N)INIT and F(N)SAVE both need to simply AND the status word for 0x4700 on a 8087, preserving the condition flags.
