### ISSUE TITLE
[Question] Some issues in my 86Box 

### ISSUE THREAD

**Issue by leesa49** [86Box/86Box#452]
I don't know if it's just me. I use SPC-4200P

1) Resetting or turning off the program and then turning it back on may corrupt the BIOS settings.
    Reset the hard settings in the BIOS and reboot. Then no problem
    It usually happens when you press close (X button) in the upper right of the 86box.
    
  Usually no problem
![20191105-022827-351](https://user-images.githubusercontent.com/55971868/68174080-21f4b600-ffc0-11e9-9524-d59785c77d9b.png)

Press the Close Program button to exit and run again
Like this for a while
![20191105-022852-395](https://user-images.githubusercontent.com/55971868/68174085-27ea9700-ffc0-11e9-82b1-fef738c02d31.png)
![20191105-022912-612](https://user-images.githubusercontent.com/55971868/68174088-2a4cf100-ffc0-11e9-8920-61bc50bc2cbf.png)

Controller error message
![20191105-022925-365](https://user-images.githubusercontent.com/55971868/68174093-2caf4b00-ffc0-11e9-9a40-4daced4f405f.png)

Press F2 to enter BIOS
and 
Hard setting No change Immediately press ESC to reboot
![20191105-022929-035](https://user-images.githubusercontent.com/55971868/68174094-2f11a500-ffc0-11e9-9fac-f0aae85cb31a.png)
![20191105-022937-801](https://user-images.githubusercontent.com/55971868/68174106-3c2e9400-ffc0-11e9-8373-61284db12abb.png)

no problem
![20191105-022951-534](https://user-images.githubusercontent.com/55971868/68174110-3fc21b00-ffc0-11e9-82dc-a025293aecb0.png)

2) After playing in CGA mode (simcga) in Hercules mode, I come back to DOS and leave for a long 
    time. Then the program stops responding.

3) Sometimes ctrl + alt + del  
    OR Hard Reset
    will not reboot (no response)

Thanks for EVERYONE.
Have a nice day ~

**Comment by daviunic** [comment]
#3 is likely a renderer hang.

**Comment by OBattler** [comment]
What build of 86Box is this on?

**Comment by OBattler** [comment]
OK, I confirm the hang with hard reset on IDE.

**Comment by leesa49** [comment]
I use [ISA][IDE] PC/AT IDE Adapter

**Comment by OBattler** [comment]
I think this has been resolved.
