### ISSUE TITLE
[ENHANCEMENT] Select ROM Language PS/1 Model 2011

### ISSUE THREAD

**Issue by Altheos** [86Box/86Box#454]
Default Rom for PS/1 Model 2011 seems to be in Italian Language.
![image](https://user-images.githubusercontent.com/29195397/68382191-7bd9b500-0153-11ea-804d-dfefc1ed95b2.png)

Could there be a "Select Language" Option for this model to change it ?

Regards.

**Comment by mfmcosta** [comment]
Hi,
This site [https://ps1stuff.wordpress.com/download/downloads-for-type-2011/](url) has diferents ROM which you can use to change the ones in 86box.
Tried with the portuguese version and works:
![image](https://github.com/86Box/86Box/assets/136728257/8fc7cf39-04bb-4545-be23-93cb5bf206ec)
