### ISSUE TITLE
Input issues under DR-DOS 3.41/5

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4540]
### What happened?

 I installed, on October 2023, DR-DOS 3.41, and Windows 2.11/386  on a 386 SX. The 3.40 version was not compatible, but the 3.41 worked just fine.

Issues:

On DR-DOS 3.41:

a. I now found that the Microsoft serial mouse is not recognized under DR-DOS by either Cutemouse v1.9 or Microsoft Mouse driver 7.04.

b.  Windows 2.11 does not start with WIN86.COM or WIN386.EXE.

c. The Chessmaster 2100 game, start without the mouse, but random crash may occur.

On DR-DOS 5:
The Chessmaster starts normally, but when I load a Classic game to see, after selecting Replay => Animate option, says "press space bar to start the animation" but when I press it, the game freezes.

The game seems to work just fine under MS-DOS.

HDD,CFG,NVR files of both machines:

[386 SX DR-DOS 3.41.zip](https://github.com/user-attachments/files/15844190/386.SX.DR-DOS.3.41.zip)

[386 SX DR-DOS 5 Spanish.zip](https://github.com/user-attachments/files/15844202/386.SX.DR-DOS.5.Spanish.zip)

The Floppy disk with the game:

[Fidelity Chess Master 2100 (Full).zip](https://github.com/user-attachments/files/15844205/Fidelity.Chess.Master.2100.Full.zip)

### Configuration file

```ini
[Oak OTI-077]
memory = 1024

[Microsoft Serial Mouse]
port = 0
buttons = 2

[General]
vid_renderer = qt_opengl3
vid_resize = 1
rctrl_is_lalt = 1
enable_overscan = 1
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 5856
uuid = 106f5aff-a0bf-50c8-8840-89fcfd7560f2


[Machine]
machine = arb1374
cpu_family = am386sx
cpu_speed = 25000000
cpu_multi = 1
fpu_type = 387
cpu_use_dynarec = 0
time_sync = local
fpu_softfloat = 0
cpu_waitstates = 6
pit_mode = 1
mem_size = 4096

[Video]
gfxcard = oti077

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sb
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 10, 1024, 0, ide
hdd_01_fn = 
hdd_01_speed = 1989_3500rpm
hdd_01_vhd_blocksize = 1024
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 525_2hd
fdd_02_type = 35_2hd
```

### Operating system

Windows 10 23H2

### CPU

i5 4210U

### 86Box version

4.2.0.5856

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
You know, not everything has to be compatible.

**Comment by Fenix770** [comment]
I did a clean install of Windows 2.11/386 with DR-DOS 3.41 and works fine.

**Comment by Fenix770** [comment]
The mouse works, and the game too, but this time I used the ADI 386 SX instead of the Acer T100 or the Chaintech 325AX with MR BIOS.

**Comment by Fenix770** [comment]
I also found, on some BIOS machines the COM/LPT ports must be disabled, because detects the enabled ports as external, (not on-board) ports.

**Comment by OBattler** [comment]
That's because on those early machines they are, in fact, external - on real hardware, they would be on an I/O card.

**Comment by OBattler** [comment]
Now, the ARB is a SBC with an on-board Super I/O chip, with two 16550-compatible serial ports with FIFO. I can see DR-DOS 3.41 not liking that, since it may well only support 8250 and 16450.

**Comment by Fenix770** [comment]
About the ports I mean, the on-board ports does not work. For example on the Acer T100, to make the serial/LPT work, I should disable the on-board ports and use the externals. 
That happens under MS-DOS 5.0

PD: I mean for:
internal => The serial/LPT options on the BIOS.
External => The configuration options on 86Box.

This happens with the on-board ports enabled and the externals disabled.
![Monitor_1_20240615-184430-104](https://github.com/86Box/86Box/assets/31600563/caa1a418-7103-4ae0-ae80-ed16300b1f0d).

This are the internal ports
![Internal ports](https://github.com/86Box/86Box/assets/31600563/0a73c255-d569-430e-bd65-918ae2154a8b)

**Comment by TC1995** [comment]
I think the Acer T100 is still incomplete.
