### ISSUE TITLE
OEMCD001 Windows 98 Error

### ISSUE THREAD

**Issue by Kuba843** [86Box/86Box#4542]
### What happened?

If I tried to install Windows 98, "OEMCD001" driver is missing and i can't enter into setup. I tried anything but it fails
![Zrzut ekranu (120)](https://github.com/86Box/86Box/assets/172935688/e7f423e3-3b0a-469e-af84-35e2f6c15092)

### Configuration file

```ini
C:\Users\Kubi\Documents\WinBox for 86Box\Virtual Machines\{D4F7773C-2E46-4162-8F5C-0001D424362C}\86box.cfg
```

### Operating system

Windows 10

### CPU

AMD Ryzen 5 3500U

### 86Box version

v4.1.1 [build 5624]

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
Most likely wrong mapping from autoexec.bat/config.sys and/or lack of suitable CD-ROM driver.

**Comment by TC1995** [comment]
And WinBox is no longer supported.

**Comment by OBattler** [comment]
And configure a CD-ROM drive in 86Box settings as well.
