### ISSUE TITLE
[ENHANCEMENT] PS/2 Model 30-286 improvements

### ISSUE THREAD

**Issue by Altheos** [86Box/86Box#455]
Current PS/2 Model 30-286 emulation needs a "third party" controller to works with a hard drive.
Using Internal Controller give "1701 - Controller Error".
PS/2 Model 30-286 uses a ST506 like proprietary controller  close to an IDE one and often paired with a Seagate ST-125L (20 Mb) or a ST-157L (40 Mb hard drive).

Serial port needs also improvements : current emulation throws 1101 error at boot (Asynchronous communications adapter test failure) cause serial port chips is VLSI 16C451.

At last, using a 1 Mb RAM machine gives errors 100000 FFFE 201 and 164 (memory error). Usable Memory using Starter Diskette shows only 640 Kb instead of 1 Mb.
it should be like this : 
![image](https://user-images.githubusercontent.com/29195397/68384826-c14cb100-0158-11ea-9d46-45dfb483734e.png)
PS/2 Model 30-286 uses a VLSI 82C102A as memory controller.

Thanks.

**Comment by TC1995** [comment]
I think, for the memory one, it's a remapping issue.

**Comment by OBattler** [comment]
It appears all three problems have been fixed now, as such, this can be closed.
