### ISSUE TITLE
Mouse pointer not visible on Sargon 4/5  with Tandy 1000 SL/2 machine

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4551]
### What happened?

I tested the chess game Sagon 4 and  5, both games seem to have an issue with the mouse which is not visible on the Tandy graphics mode.

Tested: 

* Tandy 1000 SL/2, 768kb RAM, Tandy DOS 3.30 Microsoft mouse driver and Cutemouse driver, I also tested bot Serial mouse with COM 1 and    COM 2 ports and also Microsoft Bus Mouse. 

What works:
* The mouse works fine under Windows 2.03 640x200x4 video mode, the Volkov commander text mode, and the 640x200x16 video mode used by Personal Deskmate included with SL/2 disks.

* The mouse works fine with Sargon 4 in CGA 4-color video mode  (The mouse pointer is smaller in CGA mode, tested on DosBox-x Win 64 bits, march 1, 2024 version)
  
Do not work:

* Sargon 4 with Tandy 320x200 16 color mode: the mouse is present but the pointer is not visible.
* Sargon 5 have the same issue with the 640x200x16 video mode on 86Box. (There is no CGA version on this version of the game
only supports VGA 320x200 256 colors EGA 640x200 and the Tandy 640x200 16 colors included on Tandy SL/TL/RL)

Both games works fine in Tandy mode under the  DosBox-x version launched on march 1, 2024. The mouse pointer, in Sargon 4, is the same size as the used in the EGA video mode (except for some blinking animation at start of the game).

One strange behaviour is that when I use the generic 1991, Naksha DOS mouse driver, the game starts in Tandy mode with the small CGA pointer but nothing can be selected).

NVR,CFG and HDD files:

[Tandy 1000 SL new.zip](https://github.com/user-attachments/files/15922818/Tandy.1000.SL.new.zip)

Sargon 5 floppy disk:
[Sargon V.zip](https://github.com/user-attachments/files/15922823/Sargon.V.zip)

Naksha DOS mouse driver:

[MOUSE NAKSHA 1991.zip](https://github.com/user-attachments/files/15922837/MOUSE.NAKSHA.1991.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 5862
uuid = ca61cce5-9699-55e0-a319-2769b5245f01
enable_overscan = 1
vid_resize = 1

[Machine]
machine = tandy1000sl2
cpu_family = 8086
cpu_speed = 8000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 8087
mem_size = 768

[Video]
gfxcard = internal

[Input devices]
mouse_type = logibus

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = st506_xt_wd1002a_wx1
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 4, 615, 0, mfm
hdd_01_fn = 
hdd_01_vhd_blocksize = 1024
hdd_01_mfm_channel = 0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2dd


[AST SixPakPlus #1]
irq = 3

[Other peripherals]
isartc_type = a6pak

[WD1002A-WX1 MFM Fixed Disk Adapter]
bios_addr = C8000
base = 0320
irq = 2

[Microsoft Serial Mouse]
port = 1
buttons = 2

[Logitech/Microsoft Bus Mouse]
base = 023C
irq = 3
hz = 60
buttons = 2
```

### Operating system

Windows 10 23H2

### CPU

i5 4210U

### 86Box version

4.2.0.5862

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
That Tandy MS-DOS 3.30 is from which Tandy machine exactly?

**Comment by Fenix770** [comment]
I downloaded from WinwordPC it seems to be the right OEM version for the SL/2 machine.
https://winworldpc.com/download/987859e6-7169-11ea-8c4a-fa163e9022f0

**Comment by OBattler** [comment]
I guess one question would be - is the problem limited to the SL/2?

**Comment by Digitoxin1** [comment]
Hmmm, I actually own a physical copy of Sargon 4 and cannot get it to work properly on my real Tandy 1000 SX.  It loads, but the colors are all messed up in game.  The mouse pointer does work though.

**Comment by Fenix770** [comment]
And the mouse pointer, on Sargon IV, can move the pieces? On the latter, Sargon V, it only supports 3 video modes VGA 320x200 256 colors, EGA 640x200 and the Tandy mode 11h 640x200 included on SL, TL and RL models.

**Comment by Digitoxin1** [comment]
When I try to launch Sargon 4 in 86Box while emulating a Tandy 1000 SL-2 with 768K of RAM, I get the following:

![image](https://github.com/user-attachments/assets/65450949-1e66-48a4-adab-a94cc44a00d1)

**Comment by Fenix770** [comment]
Did you boot from the floppy disk? There are 2 versions of the game: one launched in 1989, (version 1.00) that supports CGA, EGA and VGA. And the other launched on January 1990 (version 1.03 which added Tandy 16 color support)

**Comment by Digitoxin1** [comment]
The version I'm running is version 1.00.  That would explain the CGA, but not the memory allocation error.  I'm not loading anything else into memory so the maximum amount of available memory should be available to the game.

As far as the mouse issue and Tandy 16 color mode, I seem to vaguely recall some issue either mouse or joystick support in some games when running in Tandy 16 color mode, but I cannot seem to find any information on it.

**Comment by Digitoxin1** [comment]
Just tested version 1.03 on my Tandy 1000 SX and the mouse cursor is missing in Tandy graphics mode on a real Tandy 1000 so this does not appear to be a bug in 86Box.

**Comment by Fenix770** [comment]
If you have a real Tandy 1000 machines. Could you test this mouse driver?

On 86box, with this driver, I get the same mouse pointer as in CGA, but I cannot select anything, either on the menu or the pieces.
[MOUSE NAKSHA 1991.zip](https://github.com/user-attachments/files/16667490/MOUSE.NAKSHA.1991.zip)

At least on 86box, the mouse pointer size for CGA, is different from the EGA and VGA modes. I not sure what kind of cursor is the right for the Tandy 1000. Since is CGA, but have the same graphics as the EGA version, and different mouse drivers have different behaviors.

**Comment by Digitoxin1** [comment]
On a real Tandy 1000, I get different behavior with the CuteMouse driver, the Microsoft mouse driver, and the Naksha mouse driver.

With the CuteMouse driver, in Tandy graphics mode, you cannot see the mouse cursor but the mouse still works and registers movement and clicks.  The mouse cursor shows up and works when you switch to CGA mode.

With the Microsoft mouse driver, if you try to move the mouse in Tandy graphics mode, the game will freeze and sometimes show graphical corruption.  If you immediately switch the game to CGA mode without touching the mouse, it works fine in CGA mode.

With the Naksha mouse driver, the mouse does not work in either Tandy graphics or CGA mode.

**Comment by OBattler** [comment]
Since the Naksha driver has been established to be for Mouse Systems mice, it obviously isn't going to work on a Logitech serial mouse unless you find a may to set the Logitech serial mouse into the Mouse Systems mode first (yes, it supports that).

I guess this can be closed as NOTABUG then.
