### ISSUE TITLE
OS/2 prototype disk problem

### ISSUE THREAD

**Issue by WNT50** [86Box/86Box#4552]
### What happened?

The OS/2 Football prototype disk version 7.68.17 (from <a href="https://www.pcjs.org/software/pcx86/sys/os2/misc/87058/">pcjs.org</a>) failed to boot with an User Error message. From the <a href="https://www.os2museum.com/wp/playing-football/">OS/2 Museum</a> website, it seems that the build relies on special 386/486 cpu behavior (pushing a selector on a 32-bit stack only write the low 16-bit word and leave the high word unmodified) and it may be fixed.

Panic screen after getting past kernel debugger:
![panic](https://github.com/86Box/86Box/assets/173389620/d15ed240-419f-40e6-8a12-01ca8c10495e)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 7 5800H with Radeon Graphics         
uuid = 06e46d3e-9bfb-521c-a9b1-4e0171f243cb
language = system
scale = 2
emu_build_num = 5862
force_43 = 1

[Machine]
machine = deskpro386
cpu_family = i386dx_deskpro386
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = ega

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 525_2hd

[IBM EGA]
memory = 256
monitor_type = 9

[Serial Passthrough Device #2]
mode = 0
named_pipe = \\.\pipe\86Box\test
data_bits = 8
stop_bits = 1
baudrate = 115200

[Ports (COM & LPT)]
serial2_passthrough_enabled = 1
```

### Operating system

Windows 11

### CPU

AMD Ryzen 7 5800H

### 86Box version

v4.2 build 5862

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

[compaq.zip](https://github.com/user-attachments/files/15925542/compaq.zip)

To get past the kernel debugger, attach putty to COM2 and press "g" when debugger break in. SysRq key is scancode 0x54.

**Comment by WNT50** [comment]
Another problem happens with <a href="https://www.pcjs.org/software/pcx86/sys/os2/misc/87007/">SIZZLE</a> disk version 7.68.18. Shell crashes with Trap D when trying to use the Start A Program option. This problem occured from build 4880 already.

[pcat.zip](https://github.com/user-attachments/files/15928630/pcat.zip)

Panic with build 4880:
![Monitor_1_20240621-215100-166](https://github.com/86Box/86Box/assets/173389620/bc0018a1-3b84-4014-9e56-4e70d8cdb132)

**Comment by OBattler** [comment]
This may be a regression, I recall both of these working years ago for some reason.

**Comment by TC1995** [comment]
> This may be a regression, I recall both of these working years ago for some reason.

Actually, they never worked on our end.

**Comment by OBattler** [comment]
What instruction does the special behavior occur with?

**Comment by TC1995** [comment]
Are we even sure sizzle is able to not issue Trap D?

**Comment by OBattler** [comment]
Yes, we are, it works just fine on PCjs.
