### ISSUE TITLE
Matrox Mystique & 200 too

### ISSUE THREAD

**Issue by WhiteMagicRaven** [86Box/86Box#4554]
### What happened?

MSITUTOR from Matox Mystique SDK dos package can't draw dash lines "L" as on real hardware seen here 
and can't draw blend modes by pressing "T" it hang 86box without showing anything
https://youtu.be/o07uVlvAP5E?si=zkougvfNDJtE4KbE&t=99
![Monitor_1_20240622-025953-666](https://github.com/86Box/86Box/assets/876874/ba6012e4-ed48-4381-bf3f-29c427d7893b)

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
confirm_save = 0
video_fullscreen_first = 0
confirm_exit = 0
confirm_reset = 0
dpi_scale = 0
video_fullscreen_scale = 0

[Machine]
machine = p54tp4xe
cpu_family = pentium_p54c
cpu_speed = 200000000
cpu_multi = 3
cpu_use_dynarec = 1
fpu_softfloat = 1
time_sync = local
fpu_type = internal
pit_mode = 1
mem_size = 16384

[Video]
gfxcard = mystique
8514a = 1
xga = 1

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = adlib

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 2438, 0, ide
hdd_01_fn = images/Win98SE_P133.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = E:/New folder/Tomb_Raider_ISO/TOMBENG.cue
cdrom_01_image_history_01 = E:/New folder/Tomb_Raider_ISO/TOMB_MYS
cdrom_01_image_history_02 = C:/Users/Admin/Downloads/MSISDK-master/MSIDOS
cdrom_01_image_history_03 = E:/New folder/Screamer_Rally_ISO/srally.cue
cdrom_01_image_history_04 = C:/Users/Admin/Downloads/screamer_rally/sr
cdrom_01_type = PHILIPS_CD-ROM_PCA403CD_U31P

[Matrox Millennium]
memory = 8

[Standard PS/2 Mouse]
buttons = 2
```

### Operating system

Windows 7

### CPU

Pentium(R) Dual-Core CPU       T4500  @ 2.30GHz

### 86Box version

v4.1.1 build 5634

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by WhiteMagicRaven** [comment]
this is also causes to be all black text in Tomb Raider, while in real hardware should be gold textured.
![vlcsnap-2024-06-22-03h50m54s572](https://github.com/86Box/86Box/assets/876874/3cf0b6ed-59e4-487c-a868-c0c6d24295e8)
![Monitor_1_20240622-035018-576](https://github.com/86Box/86Box/assets/876874/0aa58c14-be83-47b7-8891-7bfe0884d8a0)

**Comment by TC1995** [comment]
Does it happen in the latest nightly builds?

**Comment by unreal9010** [comment]
Also: Fade to Black, Duke Nukem 3D and Shadow Warrior display a black screen if run in VESA mode (the latter two even in 320x240). DN3D returns an error, saying VESA driver was not found/supported.
The above happens not only with Mystique and Mystique 220 but Millennium II and G100 as well.
Furthermore, SVGA performance on pretty much all Matrox cards feels rather slow (especially in Screamer series). Not too long ago I ran Screamer 2 on an emulated Pentium II 350 and G100 and it felt as if it was running on P120.

**Comment by WhiteMagicRaven** [comment]
tried nightly build, yes happens the same
