### ISSUE TITLE
[Feature Request] Allow the emulation of MFM/RLL hard disks with more than 1,023 cylinders

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#456]
This is a followup feature request allowing the emulation of ESDI hard disks with more than 1,023 cylinder in bug https://github.com/86Box/86Box/issues/444.

If I wanted to emulate a MFM or RLL hard disk more than 1,023 cylinders, I found that few MFM/RLL-type drives had more than 1,023 cylinder.

For MFM hard drives, take the <a href="https://stason.org/TULARC/pc/hard-drives-hdd/atasi/519M-160MB-5-25-FH-MFM-ST506.html">ATASI 519M</a> as an example. It has a unformatted capacity of 191 MB and a formatted capacity of 160 MB with the following C/H/S geometry of 1224/15/17 for a total capacity of 159,805,440 bytes (152.4 MB).

For RLL hard drives, take the <a href="https://stason.org/TULARC/pc/hard-drives-hdd/atasi/519R-244MB-5-25-FH-RLL-ST506.html">ATASI 519R</a>. It has a formatted capacity of 244 MB with the following C/H/S geometry of 1224/15/26 for a total capacity of 244,408,320 (233.1 MB).

As such, the "Add New Hard Disk" dialog will allow SCSI and ESDI hard disks to have larger cylinder counts, but neither MFM nor RLL.

**Comment by OBattler** [comment]
I think this has been fulfilled by now.
