### ISSUE TITLE
Some PS/2 ESDI adapter commands didn't implement properly

### ISSUE THREAD

**Issue by WNT50** [86Box/86Box#4561]
### What happened?

When booting Xenix 2.3.4q from installation disk 1 on the IBM PS/2 model 80 with an ESDI hard disk, it
displays a message "esdi:ERROR:adapter reset failed-no status 01" then the disk is no longer being recognized.
![Monitor_1_20240623-012833-849](https://github.com/86Box/86Box/assets/173389620/1946c71a-f78d-40ae-8dc4-67eee0f80efb)
![Monitor_1_20240623-025342-224](https://github.com/86Box/86Box/assets/173389620/9e6b937f-357e-400d-8aa0-ed16618d0eb2)

In the <a href=https://www.ardent-tool.com/docs/pdf/ibm_esdi_trm.pdf>ESDI Technical Reference</a> I found the section about reset adapter, and it seems that Xenix is expecting the bit 4 is set to 1 but it doesn't.
![xenix](https://github.com/86Box/86Box/assets/173389620/e567be64-e80a-44a4-a978-7386ad17dd1e)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 7 5800H with Radeon Graphics         
uuid = bb6a8b3c-1dd2-58d7-b611-2f380a6173be
language = system
force_43 = 1

[Machine]
machine = ibmps2_m80
cpu_family = i386dx
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = esdi_mca
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_02_type = none
fdd_01_fn = C:/Users/Sysinternals/Desktop/SCO Xenix 386 2.3.4q (3.5)/Installation 1.img

[Hard disks]
hdd_01_parameters = 38, 2, 1120, 0, esdi
hdd_01_esdi_channel = 0
hdd_01_fn = vdisk00.img
hdd_01_speed = ramdisk
```

### Operating system

Windows 11

### CPU

AMD Ryzen 7 5800H

### 86Box version

v4.2 build 5869

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [X] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Xenix disks: [SCO Xenix 386 2.3.4q (3.5).zip](https://github.com/user-attachments/files/15942525/SCO.Xenix.386.2.3.4q.3.5.zip)
Machine: [xenix.zip](https://github.com/user-attachments/files/15942523/xenix.zip)

**Comment by WNT50** [comment]
The second problem is that when I use the "Move the machine" option in the reference disk menu from PS/2 model 50, the emulator hang up completely. After then I find a message "BAD COMMAND 06 0" in the logfile. Seems to be the same bug from #3939 but a different request.

[machine.zip](https://github.com/user-attachments/files/15942553/machine.zip)
[86Box.log](https://github.com/user-attachments/files/15942554/86Box.log)

**Comment by TC1995** [comment]
Does anyone have a disassembly of this (IBM ESDI MCA driver) extracted from the xenix boot disk? Because, in my logs, bit 4 is actually issued in the basic status register during the reset phase of the adapter (from Attention Code 4).

**Comment by OBattler** [comment]
@WNT50 That was the missing PARK HEADS command, I have now committed the implementation of that.

**Comment by WNT50** [comment]
I can confirm the refdisk works OK now, but for the xenix I found a [similar issue](https://www.pcjs.org/software/pcx86/sys/unix/sco/xenix/286/2.1.3/#sco-xenix-286-installation-and-emulation-notes) for the [IDE/ATA driver](https://www.os2museum.com/wp/oldest-surviving-386-pc-os/). Maybe the ESDI driver get confused because disk reset takes no time I think.

**Comment by WNT50** [comment]
I have extracted xenix ESDI driver from [xnx232b](https://ftp.sco.com/SLS/), which [added](https://ftp.sco.com/SLS/xnx232b.ltr) PS/2 ESDI disk support for earlier xenix versions. Reset routine is in the _esdireset symbol.

[esdi.zip](https://github.com/user-attachments/files/17026090/esdi.zip)

**Comment by OBattler** [comment]
This is now fixed.
