### ISSUE TITLE
Matrox Millenium 4/8mb bug

### ISSUE THREAD

**Issue by WhiteMagicRaven** [86Box/86Box#4563]
### What happened?

i found that 2mb millennium is ok, but using 4mb or 8mb causes distortion in image on game Nascar Racing which uses MGA 3D Acceleration capabilities of this video card.

i have 4mb millennium and i tested on real hardware its not happens here.

2mb ok
![Monitor_1_20240611-184631-274](https://github.com/86Box/86Box/assets/876874/d9b0371a-efdc-43b9-9063-8f1b24a4a7c8)
4mb bug / real hardware ok
![Monitor_1_20240611-185906-729](https://github.com/86Box/86Box/assets/876874/ee0451ef-fe90-4157-b4b7-c7ff98481dd5)

8mb bugged also. Can't say how it acts on real hardware, assuming should be also ok.

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
confirm_save = 0
video_fullscreen_first = 0
confirm_exit = 0
confirm_reset = 0
dpi_scale = 0
video_fullscreen_scale = 0

[Machine]
machine = p54tp4xe
cpu_family = pentium_p54c
cpu_speed = 200000000
cpu_multi = 3
cpu_use_dynarec = 1
fpu_softfloat = 1
time_sync = local
fpu_type = internal
pit_mode = 1
mem_size = 16384

[Video]
gfxcard = millennium

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = adlib

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 2438, 0, ide
hdd_01_fn = images/Win98SE_P133.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = E:/New folder/Tomb_Raider_ISO/TOMBENG.cue
cdrom_01_image_history_01 = E:/New folder/Tomb_Raider_ISO/TOMB_MYS
cdrom_01_image_history_02 = C:/Users/Admin/Downloads/MSISDK-master/MSIDOS
cdrom_01_image_history_03 = E:/New folder/Screamer_Rally_ISO/srally.cue
cdrom_01_image_history_04 = C:/Users/Admin/Downloads/screamer_rally/sr
cdrom_01_type = PHILIPS_CD-ROM_PCA403CD_U31P

[Matrox Millennium]
memory = 8

[Standard PS/2 Mouse]
buttons = 2
```

### Operating system

Windows 7

### CPU

Pentium(R) Dual-Core CPU       T4500  @ 2.30GHz

### 86Box version

v4.1.1 build 5634

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Happens on nightly build too.

**Comment by unreal9010** [comment]
Since you have a real Millennium card, could you test Duke Nukem 3D to see how it runs when using VESA mode? Under 86Box  (4 MB card, 4.12 drivers) it keeps returning the "VESA driver not found/supported error".
I also tested Screamer 2 and with Millennium I it ran beautifully in SVGA mode, whereas with Mystique 220 (using the same 4.12 drivers) it was barely playable even in VGA mode on an emulated Pentium II 350.

**Comment by WhiteMagicRaven** [comment]
currently not possible to test, since i moved out, and will arrive few months later, and than will have access to real hardware. Sorry

**Comment by unreal9010** [comment]
According to Mactar's tests, none of the Matrox cards are having issues with running Duke Nukem 1.3D in VESA mode, except for some screen tearing that apparently occurs with Mystique and the cards that were released after it (strangely, Parhelia, the latest from the bunch, seems to be fine).

**Comment by Dudejo** [comment]
According to the 3D Realms legacy website, the only issue that should be happening on a Matrox Millenium is a system crash when running Duke 3D in 800x600.

**Comment by OBattler** [comment]
Closing because it's being tracked in #4617 .
