### ISSUE TITLE
Wrong/mixed up textures with Voodoo 3 in some Microsoft / Terminal Reality Games

### ISSUE THREAD

**Issue by FredPJ** [86Box/86Box#4565]
### What happened?

Using any Voodoo 3 card with any driver version, this bug happens at least in the following  Terminal Reality games published by Microsoft:
CART Precision Racing
Monster Truck Madness 2

The textures will appear correct at first, but will show wrong textures after a second race or after alternating between software and hardware modes.

-> How to easily reproduce this bug in CART Precision Racing:  <-
1. At the main menu at the top left click on "Options" > "Graphics..." then at the Renderer select "Direct3D (Most hardware)" then click OK.
2. Click the "QUICK RACE" button to start a race, then press the F4 key continuously to alternate between software and hardware modes, and the textures will get increasingly mixed up.

This also happens in Monster Truck Madness 2, if you start a race, then quit the race, then start another race.

- This bug also happens in PCem. 
- It happens on both 86box old recompiler and new recompiler versions.

### Configuration file

```ini
[General]
vid_renderer = qt_vulkan
host_cpu = Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
emu_build_num = 5869
uuid = 7f3740bb-751e-5ed8-8c1a-3e4432aeb17e
scale = 2
video_gl_vsync = 1
dpi_scale = 0
force_43 = 1
vid_resize = 2
window_fixed_res = 959x719

[Machine]
machine = 430vx
cpu_family = pentium_p55c
cpu_speed = 166666666
cpu_multi = 2.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 65536

[Video]
gfxcard = voodoo3_1k_pci
show_second_monitors = 0

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = sb16

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0
net_01_card = ne2kpci
net_01_net_type = slirp

[Storage controllers]
hdc = internal
cassette_mode = load

[S3 Trio64 PCI (Phoenix)]
memory = 4

[Microsoft Serial Mouse]
port = 0
buttons = 4

[Sound Blaster 16 #1]
base = 0220
base401 = 0330
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[Realtek RTL8019AS #1]
mac = 93:70:f7

[Hard disks]
hdd_01_parameters = 63, 16, 1999, 0, ide
hdd_01_fn = D:/PCem/hdd/HDD_95_Updates_OSR2.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 72
cdrom_01_parameters = 0, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_image_history_01 = D:/Games/Monster Truck Madness 2.cue
cdrom_01_image_path = D:/Games/CART Precision Racing.cue
cdrom_01_image_history_02 = D:/comp/WINDOWS_95.iso
cdrom_01_type = 86BOX_CD-ROM_1.00

[Sound Blaster 16 PnP #1]
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[Realtek RTL8029AS #1]
mac = 50:62:54

[3Dfx Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 4
sli = 0
recompiler = 1
```

### Operating system

Windows 11

### CPU

Intel Core i7 6700K

### 86Box version

5869

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Closing because it's being tracked in #4483 .
