### ISSUE TITLE
Actua Soccer on Matrox Mystique , with mystique patch for game.

### ISSUE THREAD

**Issue by WhiteMagicRaven** [86Box/86Box#4567]
### What happened?

All Player textures is shifted on 86box
![Monitor_1_20240622-100656-218](https://github.com/86Box/86Box/assets/876874/3131940e-2b83-4bee-8256-326f2841529c)
While on real hardware its okay.
![vlcsnap-2024-06-23-18h06m14s672](https://github.com/86Box/86Box/assets/876874/72bfdfdd-7de9-415e-8f15-040012ae6551)
Unfortunately can't provide excellent screenshot , game and capture card can't sync, there is s-video capture, but i played the game and it don't have this texture shifts on players.

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
confirm_save = 0
video_fullscreen_first = 0
confirm_exit = 0
confirm_reset = 0
dpi_scale = 0
video_fullscreen_scale = 0

[Machine]
machine = p54tp4xe
cpu_family = pentium_p54c
cpu_speed = 200000000
cpu_multi = 3
cpu_use_dynarec = 1
fpu_softfloat = 1
time_sync = local
fpu_type = internal
pit_mode = 1
mem_size = 16384

[Video]
gfxcard = mystique
8514a = 1
xga = 1

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = adlib

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 2438, 0, ide
hdd_01_fn = images/Win98SE_P133.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = E:/New folder/Tomb_Raider_ISO/TOMBENG.cue
cdrom_01_image_history_01 = E:/New folder/Tomb_Raider_ISO/TOMB_MYS
cdrom_01_image_history_02 = C:/Users/Admin/Downloads/MSISDK-master/MSIDOS
cdrom_01_image_history_03 = E:/New folder/Screamer_Rally_ISO/srally.cue
cdrom_01_image_history_04 = C:/Users/Admin/Downloads/screamer_rally/sr
cdrom_01_type = PHILIPS_CD-ROM_PCA403CD_U31P

[Matrox Millennium]
memory = 8

[Standard PS/2 Mouse]
buttons = 2
```

### Operating system

Windows 7

### CPU

Pentium(R) Dual-Core CPU       T4500  @ 2.30GHz

### 86Box version

v4.1.1 build 5634

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Also happens on nightly build.

**Comment by OBattler** [comment]
Can you upload the VM please?

**Comment by WhiteMagicRaven** [comment]
did you mean harddrive image? or whole 86box with all the isos? and how i can send you privately? so it will not be public here , and don't violence any TOS.

**Comment by OBattler** [comment]
Closing because it's being tracked in #4617 .
