### ISSUE TITLE
[ASK] Machine name changes

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#457]
I have found information regarding renaming the currently emulated machine to the actual name of the motherboard, mostly based on the BIOS string found on the bottom of the BIOS post screen at start-up.

I would like to take this into suggestion here.

Take the "AMI386DX/AMI486" for example, the BIOS string is "40-0101-001107-00001111-060692-OPWB4SXB-0". Doing a search on Google leads to the following:

Revision F at the end of the BIOS string: DataExpert MB-495SX Rev1.1
Revision 0 or H at the end of the BIOS string: DataExpert SX495 Rev1.0

These motherboards are manufactured by Informatic Power Systems Corporation.

Since the boot screen shows "OPTI-495SX (471WB) BIOS VER 1.0", I suspect that the proper name would be "Dataexpert SX495 Rev 1.0".

For motherboards that emulate 386 and 486 processors we have to put either (386SX), (386DX) or (486) in parenthesis.

Another example would be the "AMI286" which as the BIOS string "ENET-1107-040990-K0". That machine is manufactured by Dataexpert Corporation and I would suggest that the machine would be renamed to "Dataexpert 286 clone" as we can't completely identify the actual name manufacuted by Dataexpert.

For the "DTK XT clone", it would be renamed to "DTK PIM-TB10-Z" containing the BIOS string "DTK Corp. COMPUTER '88 DTK/ERSO/BIOS 2.42 (C) 1986"

For the "Juko XT clone", the actual name is "Juko Baby XT BXM/12" or "Juko ST" and according to this YouTube video, the Juko ST can support up to 1 MB of RAM maximum: https://www.youtube.com/watch?v=ojSm4OK3PB8

The motherboard was made by Auva Computer, Inc. The company also made the Juko NEST which is an 8086 version of the motherboard.

This is something that I could take into consideration.

If anyone has found the actual motherboard names of the "DTK 386SX" as well as the "Award 386/486" clones, "AMI ALI-1429", "AMI SiS471" as well as the WinBIOS machines, please let me know. :)

**Comment by OBattler** [comment]
This has been resolved.
