### ISSUE TITLE
Battle Chess game has no PC speaker sound (CGA/TGA/EGA version)

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4581]
### What happened?

I tried on several VMs with 8088 and 286, The game does not reproduce any sound from the PC speaker.
I played this game on a 8088 with Hercules and SIMCGA V1.0 and woked just fine with PC speaker.

What do work:
The Tandy 3-voice speaker works fine on Tandy 1000 machines.
The VGA version of the game works just fine with the PC speaker.

Here is the VM 
[8088 Hyundai XT DOS 3.20.zip](https://github.com/user-attachments/files/16022235/8088.Hyundai.XT.DOS.3.20.zip)

And the game
[Battle Chess 1990 version.zip](https://github.com/user-attachments/files/16022244/Battle.Chess.1990.version.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
vid_resize = 1
rctrl_is_lalt = 1
enable_overscan = 1
video_gl_shader =
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 5873
uuid = 9f4475db-5ce5-523e-862d-72923243ad30
vid_cga_contrast = 1

[Machine]
machine = super16t
cpu_family = necv20
cpu_speed = 7159092
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = local
fpu_softfloat = 1
fpu_type = 8087
mem_size = 640

[Video]
gfxcard = cga

[Input devices]
mouse_type = mssystems

[Storage controllers]
hdc = st506_xt_gen
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_02_type = 35_2dd

[Sound]
fm_driver = nuked

[Hard disks]
hdd_01_parameters = 17, 4, 615, 0, mfm
hdd_01_fn = 
hdd_01_vhd_blocksize = 1024
hdd_01_mfm_channel = 0

[Hercules]
rgb_type = 2
blend = 1

[Mouse Systems Serial Mouse]
port = 0
buttons = 2
rts_toggle = 1

[DTK PII-147 Hexa I/O Plus]
base = 0240

[Other peripherals]
isartc_type = p5pak

[IBM CGA]
display_type = 0
composite_type = 1
rgb_type = 1
snow_enabled = 0
double_type = 3

[SuperEGA]
memory = 256
monitor_type = 9

[IBM EGA]
memory = 256
monitor_type = 9

[Tseng Labs ET2000]
memory = 256
monitor_type = 9
```

### Operating system

Windows 10 23H2

### CPU

i5 4210U

### 86Box version

4.2.5873

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Fenix770** [comment]
PD: I tested the game again on Tandy machines:
The game freezes on Tandy 1000 HX. Booted with the built-in ROM DOS 2.11.
On the Tandy 1000 SL/2 sound works only during the battle, but not during the movement of the pieces.

**Comment by Fenix770** [comment]
Update: The sound effects seems to work with the original Tandy 1000 using Tandy DOS 2.11 and 360kb floppies.
Anyway I suspect the sound effect should work on later Tandy models because the game was launched in 1989.

**Comment by dbalsom** [comment]
PC speaker sound works for me on an XT machine with DOS 3.30

**Comment by OBattler** [comment]
Then this can be closed.

**Comment by dbalsom** [comment]
I don't think there was sound on the non-enhanced version except during battles.  MartyPC, dosbox, and footage from youtube agree.

**Comment by Fenix770** [comment]
But The movements work on Original Tandy 1000 and, no the other Tandy models. Even when the latter model were more common. Unless a latter EGA/CGA version of the game were launched about the same time.
