### ISSUE TITLE
Flatpak Install Error on Linux Mint 21.2

### ISSUE THREAD

**Issue by mgrretro** [86Box/86Box#4595]
### What happened?

Flatpak Installation Error:

Key "runtime" is not in group "Runtime"  - Installation cancelled

So it can't be installed on Linux Mint 21.2. 

### Configuration file

```ini
None available
```

### Operating system

Linux Mint 21.2 Cinnamon

### CPU

Intel Celeron N4120 4 core

### 86Box version

4.1.1

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

I got 86Box from a third party repository (please tell us where)

### Additional context

Flatpak Repository on Linux Mint

**Comment by jriwanek** [comment]
Please report this issue to the ftatpak maintainers, we do not maintain the flatpak.
