### ISSUE TITLE
Matrox-related issues

### ISSUE THREAD

**Issue by OBattler** [86Box/86Box#4617]
Tracking them here so they'e all in one place:
- [ ] #4579 ;
- [ ] #4578 ;
- [ ] #4577 ;
- [ ] #4567 ;
- [ ] #4566 ;
- [ ] #4563 .

**Comment by Dudejo** [comment]
Also this issue with all Matrox cards
https://youtu.be/_aUYxLeIL1g

**Comment by OBattler** [comment]
Closing as a duplicate of #4558.

**Comment by unreal9010** [comment]
G100 update: Discworld and Fade to Black work now. Claw still runs at 35%, Screamer 2 is still slow as hell, Constructor crashes and Duke Nukem 3D still has issues.
