### ISSUE TITLE
Severe screen tearing / jagged horizontal scrolling observed in several games

### ISSUE THREAD

**Issue by Agetian** [86Box/86Box#462]
In the DOS game Supaplex (both the original version and the speed fix version 6.3), the horizontal scrolling is very jerky and jagged, with a lot of screen tearing-like effects.

**To Reproduce**
1. Obtain a copy of Supaplex Speedfix 6.3, e.g. legally available as a free download at https://www.elmerproductions.com/sp/dlinst.html
2. Start the game, start the first level.
3. Try to move left or right so that the screen starts scrolling horizontally.
4. Observe how the screen goes haywire, scrolling in jerky, torn segments.

It doesn't look like this is dependent on the video card selected or on the machine itself, I tried various 86Box builds ranging from 386DX-40 to Pentium I 100MHz, as well as different VGA video cards (both ISA and VLB, different brands; tried at least S3 Trio, S3 Virge, a couple different Tridents, and a Tseng ET4000). The behavior was the same, or at least very similar, in all cases.

Note that all the available scrolling methods (Supaplex original default, Supaplex Speedfix default, Supaplex Speedfix alternate, available by executing the executable with the "h" parameter, as in "spfix63.exe h") manifest the same erroneous behavior. The "h" mode is somewhat better since only the status bar and the immediate screen boundaries go haywire, while in the default mode the entire screen jerks back and forth continuously during scrolling.

**Expected behavior**
The screen should scroll smoothly. Tested both on the original hardware (Pentium I 100MHz with a S3 Trio64 V2 video card) and also tried this in a different emulator, PCem v15 (both native Linux version and the Windows version running in Wine). On the original hardware, the scrolling was smooth without any special action required. On PCem, the "h" parameter was necessary ("spfix63.exe h") in order to achieve smooth scrolling, otherwise scrolling was jerky, similar to 86Box. The expected behavior was observed at least when emulating Diamond Stealth 32 (Tseng ET4000-based) in PCem (which, however, is also confirmed not to work on 86Box).

**Screenshots**
It's somewhat difficult to capture it properly on screenshots since it's "dynamic". However, it's very noticeable and should be easily reproducible.

**Desktop (please complete the following information):**
Core i7-4770, 16 GB RAM, NVIDIA RTX 2070
OS Linux Mint 18.3 with Wine 4.4-staging.
86Box v2.06 with the supplied ROM set (but also tried the latest self cross-compiled git snapshot which identifies itself as v2.10).

**Additional context**
Supaplex may be one of the "trickier" or "more difficult" games to get the timings for correctly, it may be rather picky and sensitive when it comes to scrolling. I'm not sure about the cause of the issue, but it may be related to some kind of timing that is required by Supaplex, since e.g. Speedfix documents the necessity to use certain tricks to achieve smooth scrolling, and even introduces a special flag ("h") to mitigate potential scrolling issues on video cards which may turn out to be problematic (however, this flag doesn't fix scrolling on 86Box; it helps on PCem v15 though).

**Comment by ppgrainbow** [comment]
Installed Supaplex in G:\SUPAPLEX and although I can reproduce the jagged horizontal scrolling issue, the game is playable.

Let's hope that this bug gets fixed soon.

**Comment by Agetian** [comment]
This issue seems to affect other games which involve horizontal smooth scrolling, for example:
Golden Axe - horizontal scrolling also causes the HUD overlay elements (the magic bar, the health bar, etc.) to jump back and forth continuously (non-existent on real hardware, very rarely happens on e.g. DosBox).
Prehistorik 2 - when the game starts, the scrolling background before the level loads, as well as the map, also scroll in jagged steps and "sway" back and forth periodically.

**Comment by OBattler** [comment]
I have this fixed (but not yet committed), but it's still a bit rough-looking because of the refresh rate difference between guest and host. I don't think I can't do anything about that for time being, maybe in the future if/when better renderers are written. But I will commit the (S)VGA fix.

**Comment by Agetian** [comment]
Thanks a lot for your efforts, OBattler, they are very much appreciated! And yes, I don't think any other emulator, even in which it's very close to being non-noticeable (e.g. DosBox), have it perfect yet, but it's always good to have a temporary solution until better approaches can be implemented and researched. And btw, was about to write that this issue seems to be limited to (S?)VGA, but I guess it was established already :) Thank you very much again! :)

**Comment by OBattler** [comment]
Actually, the EGA would be affected as well, as it has the same bug with pel panning.

**Comment by Agetian** [comment]
Ah, makes sense. Thanks again for looking into it and considering a fix! :)

**Comment by Agetian** [comment]
I tested quite a lot of games with the new build (v2.07) and pretty much 99% of them seem to behave very well, no more shaking and tearing. The only odd case so far that still shakes seems to be the Prehistorik 2 scrolling screen before the level (with the difficulty indicator), which uses a rather crazy multi-way scrolling pattern. Not sure if it's worth looking into, I haven't found another game or program yet which would show this kind of behavior (or use this kind of scrolling, for that matter). Otherwise, I think this can be considered resolved :) Should I close the issue?

**Comment by vanfanel** [comment]
@OBattler I am seeing the exact same scrolling problems on physical hardware, using the Vortex86VGA and the SM750 video chips.
Can you please point me to the place where you fixed these problems so I can try to understand what causes this?
Please, feel free to explain what you fixed here, too, I am VERY intrigued.

**Comment by OBattler** [comment]
OK, I think it's this: https://github.com/86Box/86Box/commit/ac0a1ee327de845bcfe193778c24780839310b7f .

**Comment by vanfanel** [comment]
> OK, I think it's this: [ac0a1ee](https://github.com/86Box/86Box/commit/ac0a1ee327de845bcfe193778c24780839310b7f) .

Thanks a lot!
Those problems on real hardware... would they come from bad VGA BIOS or from bad physical hardware? Any clue on that?

**Comment by Cacodemon345** [comment]
It can be from the latter.

**Comment by vanfanel** [comment]
@OBattler I have just built 86Box from latest sources, ran several different machines with S3 Trio 32/64 video cards, and I am still seeing jerky scrolling, exactly the same problem described in the first message.
Maybe the commit didn't get into main branch?

**Comment by OBattler** [comment]
Let me check, because I'm quite sure Supaplex worked fine.

**Comment by LeoABELS121** [comment]
I have the same problem with horizontal scrolling while playing Supaplex. This happens with both Pentium MMX and Pentium II, with Voodoo3 3000 PCI card. I tested with all versions of Supaplex, it's the same. Running the game in EGA, DOS or Windows 98 mode does not solve the problem. The only way to eliminate the problem is to slow down the speed as much as possible with version 6.3 speedfix but the game becomes much too slow to be fun.

**Comment by vanfanel** [comment]
It's a problem with VGA scrolling.. this issue should be reopened, for sure it's still there, @OBattler

**Comment by OBattler** [comment]
Which version of Supaplex is this with and what parameter are you running it with?

**Comment by LeoABELS121** [comment]
I'm using the original version released in 1991 without parameter and SpeedFix 6.3 with this: "SPFIX63.EXE H *8 H"

Parameters have no influence on scrolling issues.

**Comment by LeoABELS121** [comment]
Hi, any updates on this? I've tested builds 8055 ODR and NDR, and the problem persists.

When testing with DOSBox to try and reproduce the issue, this problem only occurs in "ega" mode, not in "vgaonly" mode. Hope this helps.
