### ISSUE TITLE
Elan Sc400

### ISSUE THREAD

**Issue by crazzypol** [86Box/86Box#463]
Hello! You did not consider the possibility of adding emulation of the old system on the ELAN SC400 crystal. I think for developers of real-time systems a lot of help.

**Comment by crazzypol** [comment]
[elan_sc400_eval_board.pdf](https://github.com/86Box/86Box/files/4166922/elan_sc400_eval_board.pdf)
[elansc400_eval_b2.pdf](https://github.com/86Box/86Box/files/4166923/elansc400_eval_b2.pdf)
I found information on the platform, here are diagrams with data on components. 
[Am486_DX-DX2_Microprocessor_Hardware_Reference_Manual_(1993).pdf](https://github.com/86Box/86Box/files/4166952/Am486_DX-DX2_Microprocessor_Hardware_Reference_Manual_.1993.pdf)
[Am486_Microprocessor_Software_Users_Manual.pdf](https://github.com/86Box/86Box/files/4166953/Am486_Microprocessor_Software_Users_Manual.pdf)
[Assembling 16-Bit Code in a 32-Bit Code.pdf](https://github.com/86Box/86Box/files/4166954/Assembling.16-Bit.Code.in.a.32-Bit.Code.pdf)
[ROMCS0 Redirection.pdf](https://github.com/86Box/86Box/files/4166955/ROMCS0.Redirection.pdf)
[SC400 MicrocontrollerRegister Set(21032).pdf](https://github.com/86Box/86Box/files/4166956/SC400.MicrocontrollerRegister.Set.21032.pdf)
[sc400_Register Set Reference Manual(21032a1).pdf](https://github.com/86Box/86Box/files/4166957/sc400_Register.Set.Reference.Manual.21032a1.pdf)
[SC400_UserManual(21030).pdf](https://github.com/86Box/86Box/files/4166958/SC400_UserManual.21030.pdf)
[400eval_bios_gensw.zip](https://github.com/86Box/86Box/files/4166964/400eval_bios_gensw.zip)
[400eval_bios_syssoft.zip](https://github.com/86Box/86Box/files/4166965/400eval_bios_syssoft.zip)
[cexipsml.pdf](https://github.com/86Box/86Box/files/4166966/cexipsml.pdf)
[cexipx86.pdf](https://github.com/86Box/86Box/files/4166967/cexipx86.pdf)
[ck000602.zip](https://github.com/86Box/86Box/files/4166968/ck000602.zip)
[ck000901.zip](https://github.com/86Box/86Box/files/4166970/ck000901.zip)
[e86mon.pdf](https://github.com/86Box/86Box/files/4166973/e86mon.pdf)
[ebios41.pdf](https://github.com/86Box/86Box/files/4166975/ebios41.pdf)
[readme.pdf](https://github.com/86Box/86Box/files/4166976/readme.pdf)
[sdb.zip](https://github.com/86Box/86Box/files/4166977/sdb.zip)
[sete4ser.zip](https://github.com/86Box/86Box/files/4166978/sete4ser.zip)
[ssman.pdf](https://github.com/86Box/86Box/files/4166979/ssman.pdf)
Perhaps this information will be useful for this chipset.
Thank you for including this processor in future versions of the emulator.

**Comment by OBattler** [comment]
I'm going to close this since I'm not even sure a real-time system can be emulated properly without rewriting the entire emulator.
