### ISSUE TITLE
Quit/Close  86Box without confirmation.

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#464]
Feature request to quit/close 86Box window without confirmation.

Reason : Usually I close the window when I want to. I think others may also feel the same to go through the additional step to close 86Box.

Suggestion : Disable confirmation window or add an option to remove confirmation to close the window.

Thank you.

**Comment by MoochMcGee** [comment]
...You do realize that a lot of people accidentally close a window they want to keep open, right? I mean, this feature doesn't mess with your usage of 86Box. At most, it's a minor inconvenience, but for other users, this feature can be really useful.

**Comment by OBattler** [comment]
I could easily add a parameter to disable the confirmation window.

**Comment by Mal752** [comment]
> I could easily add a parameter to disable the confirmation window.

Yes, this will be helpful. Thank you.

**Comment by OBattler** [comment]
Well, I forgot to do this for v2.07. Ah well, it will be done in v2.10 for sure.

**Comment by Mal752** [comment]
Thank you.
