### ISSUE TITLE
OS/2 Warp isn't working

### ISSUE THREAD

**Issue by ArtiomWin** [86Box/86Box#465]
Hello. Recent builds of 86box have broken support of OS/2 Warp - system used to work well, but now it boots to Trap Number 13. Also there might be problems with Cirrus Logic cards.
![20191119-074748-697](https://user-images.githubusercontent.com/31134876/69157901-a7b34e00-0af6-11ea-8c02-abcf748ab2da.png)

OS: Windows 10 Pro x64
86box version: 2.06 (build 2007)
Config file and NVR folder is included.
[cfg+nvr.zip](https://github.com/86Box/86Box/files/3864427/cfg%2Bnvr.zip)

**Comment by OBattler** [comment]
Could you please upload the hard disk image as well?

**Comment by ArtiomWin** [comment]
Here it is. Screenshot of an error was made after installation FixPak 17, but system doesn't work either with or without FixPaks installed.
https://drive.google.com/open?id=1iYHrtLADsFXEO9d_MbYfA_HDaxOET2gI

**Comment by TC1995** [comment]
I suspect this IBM OEM version is strictly made for the IBM PC 330 and may not work on generic machines, but I might be wrong.

**Comment by ArtiomWin** [comment]
Of course, it works on Intel boards well. Here's screen on the very same configuration, but on earlier 86box builds:
![20191118_092809](https://user-images.githubusercontent.com/31134876/69179110-0808b680-0b1c-11ea-86cc-0d566f68c9aa.png)
![20191119_104918](https://user-images.githubusercontent.com/31134876/69179134-12c34b80-0b1c-11ea-9da2-444dda381012.png)

**Comment by TC1995** [comment]
What was the last time it was working on these earlier builds?

**Comment by ArtiomWin** [comment]
I can't say since what build it was broken since I'm comaring with one of 86box derivatives, but it doesn't have printer emulation added.

**Comment by OBattler** [comment]
What 86Box derivative? Because on 86Box itself, I just tried a build from the 159x range from April 26th, 2018, and got the same trap there.

**Comment by OBattler** [comment]
Went as far back as #1505, same trap.

**Comment by ArtiomWin** [comment]
It's Virtual Computer v1.01.

**Comment by OBattler** [comment]
86Box build 1293, November 28th, 2017 - same trap.

**Comment by ArtiomWin** [comment]
Well, I think so.

**Comment by OBattler** [comment]
I just tried it on Virtual Computer v1.01, and I get the same trap.

**Comment by OBattler** [comment]
OK, the IBM PC 330 P75 had a Matrox graphics card. I suspect OS/2 has a driver preinstalled for it. This trap is documented for graphics card errors:
> Issue 3: A Trap D occurs in device driver SINGLEQ$.
> Fix: Reboot the system. When the "OS/2" prompt appears in white text at the upper left portion
of the screen, press the Alt and F1 keys simultaneously. A screen of options appears. Press the
<v> key to reset the video to VGA mode. The system will reboot automatically.

**Comment by OBattler** [comment]
If I follow the instructions there, after the reboot, OS/2 Warp boots fine.

**Comment by ArtiomWin** [comment]
That installation is for 330/350 models with 486 processors, they had Cirrus Logic cards.
http://psref.lenovo.com/syspool/Sys/PDF/withdrawnbook/dwbook.pdf

**Comment by OBattler** [comment]
Then try running it with an ISA or VLB Cirrus Logic card.

**Comment by ArtiomWin** [comment]
Cirrus Logic 5434, both ISA and VLB:
![20191121-062356-797](https://user-images.githubusercontent.com/31134876/69312917-40ee7b80-0c41-11ea-81f5-8f26e0ff20c4.png)
Diamond Speedstar PRO SE (Cirrus Logic 5430), VLB:
![20191121-062553-389](https://user-images.githubusercontent.com/31134876/69312966-5b285980-0c41-11ea-8881-9e5bdbc495e5.png)

**Comment by OBattler** [comment]
Tried a CL-GD 542x?

**Comment by ArtiomWin** [comment]
I don't think so. Specs page notes that 5430 integrated in motherboard is VLB one.

**Comment by OBattler** [comment]
Well, then I'd like to know what 5430 BIOS IBM used there, as that might play a role.

**Comment by ArtiomWin** [comment]
Since graphics card is integrated here, I think it's firmware should be integrated to motherboard BIOS too (but I'm not certain
[6571-6573-6581-6583.zip](https://github.com/86Box/86Box/files/3881005/6571-6573-6581-6583.zip)
).

**Comment by Altheos** [comment]
There might be two problems : 
- Trap 000d when using GD5430 => perhaps related to Diamond BIOS
- graphical problem using 5434 for instance => related to Cirrus changes in build 1898 (commit  a495fae) as build 1897 shows OS/2 Warp Desktop correctly 
![image](https://user-images.githubusercontent.com/29195397/69543001-ed579700-0f8c-11ea-86bb-217fd8b1ff04.png)

**Comment by ArtiomWin** [comment]
> * graphical problem using 5434 for instance => related to Cirrus changes in build 1898 (commit  [a495fae](https://github.com/86Box/86Box/commit/a495faec59d893e1f27850e8937b214c239a0057)) as build 1897 shows OS/2 Warp Desktop correctly
>   ![image](https://user-images.githubusercontent.com/29195397/69543001-ed579700-0f8c-11ea-86bb-217fd8b1ff04.png)
I think that might be with generic 5430 either because in the beginning (first boots at build 2007, and before installation of FixPaks) system booted with similar errors, and then it started to fail to trap screen.

**Comment by OBattler** [comment]
The graphical problem on the 5434 is now fixed, as for the rest, it requires a non-Diamond 5430, while I'll be looking into in the future. As such, I'm closing this.
