### ISSUE TITLE
CTRL+F12 shortcut to reset the machines is not working. (Linux x64 Old Recompiler AppImage)

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#4679]
### What happened?

Pressing CTRL+F12 does not help to reset the machine. Need to go back to windowed mode and click on the reset icon to reset. Unable to reset either full screen or while in windowed mode.

Using Debian with XFCE. Default XFCE Keyboard shortcuts are removed.  

Doesn't work with any configurations.

Tried changing the render from Software to OpenGL and Vulkan - no changes.

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6021
uuid = f30330a7-fdbd-599e-a5e2-d241e2d3c051
force_43 = 1
video_fullscreen_first = 0
confirm_reset = 0

[Machine]
machine = px286
cpu_family = 286
cpu_speed = 12500000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 287
mem_size = 2048

[Video]
gfxcard = ega

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked
sndcard = sb1.5
midi_device = system_midi
mpu401_standalone = 1

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa_2ch
cassette_mode = load

[Everex EV-159 RAM 3000 Deluxe #1]
size = 1024
start = 0
length = 1024
width = 0
speed = 0
ems = 1
base = 0258
base2 = 0268

[Sound Blaster v1.5 #1]
base = 0220
irq = 7
dma = 1
opl = 1
cms = 1
receive_input = 1

[Roland MPU-IPC-T]
base = 0330
irq = 2
receive_input = 1

[System MIDI]
midi = 1

[IBM EGA]
memory = 256
monitor_type = 9

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_fn = /run/media/*user*/FILES/EMULATION/86Box/hdd/112MB_286.img
hdd_01_speed = ramdisk
hdd_02_parameters = 17, 15, 900, 0, ide
hdd_02_fn = /run/media/*user*/FILES/EMULATION/86Box/hdd/112MB_files.img
hdd_02_speed = ramdisk
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1

[Floppy and CD-ROM drives]
fdd_01_type = 525_2hd
fdd_02_type = 35_2hd

[Other peripherals]
isamem0_type = ev159
```

### Operating system

Debian x64

### CPU

i7-9750H

### 86Box version

6021

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
This has been discussed among the developers and we have determined it's a CANTFIX - your combination of Linux distribution and desktop environment appears to be blocking said combination. The only possible fix is configurable combinations, which is being tracked in a separate issue already.
