### ISSUE TITLE
Tennis Cup Tandy 1000 Broken Graphics

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4691]
### What happened?

Tested using a beta version that fixed the other Tandy bug.

Game was directly booted from floppy using a Tandy SL/2. Put Disk A/B on Drive A,  load QTENNIS.bat, choose Tandy Mode (TGA), then put Disk C/D on Drive A
and then put Disk A/B back on Drive A. 
Afterwards, it will load into title screen. Select play mode and opponent, then put in Disk C/D, then Disk A/B. 

For some reason, when doing the same on the Tandy 1000 HX, it complains of low memory even though it is directly loading off floppy after I selected my opponent and game mode. Not sure if game or emulator bug.
![Monitor_1_20240804-210709-659](https://github.com/user-attachments/assets/9b2a85f6-4fdc-4791-a2a3-8ebf87929dcf)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6033
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy1000sl2
cpu_family = necv30
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 80187
mem_size = 768

[Video]
gfxcard = internal

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = tndy

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 525_2qd
fdd_01_turbo = 1
fdd_02_type = 525_2qd
fdd_02_turbo = 1
fdd_02_image_history_01 = Tennis Cup Disk B.IMA
fdd_02_image_history_02 = DISK02.IMA
fdd_01_image_history_01 = Tennis Cup Disk A.IMG
fdd_01_image_history_02 = Tennis Cup Disk C & D.img
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2.1 6033

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Game is hard to find, so here are the disk images.
[Tennis Cup Disk A & B.zip](https://github.com/user-attachments/files/16490645/Tennis.Cup.Disk.A.B.zip)

And some more glitchy screenshots (on Tandy SL/2)
![Monitor_1_20240804-205444-518](https://github.com/user-attachments/assets/67cd0f63-a5be-4bf5-9550-12eeb9681f0d)
![Monitor_1_20240804-211200-629](https://github.com/user-attachments/assets/6831a6a3-2269-4b43-8f78-de7854769ef0)

**Comment by OBattler** [comment]
Could this be using a REP - segment prefix - string instruction and hitting the correctly emulated 808x erratum? Try switching to V20 (or V30 if on a 8086 Tandy) which lacks that erratum and see how the game looks like.

**Comment by OBattler** [comment]
Ah wait, you're already on the Vx0. Even stranger then.

**Comment by OBattler** [comment]
It appears to work fine on 86Box build 1830 which was the last build with the old (ie. PCem's) 808x emulation: 
![imagem](https://github.com/user-attachments/assets/be90c825-a396-43ab-b1ba-94c0c6a098df) .
Now to bisect and find out what actually caused the regression.

**Comment by OBattler** [comment]
![imagem](https://github.com/user-attachments/assets/016b1088-a238-4303-9f5b-8e2a347a4dad)
Works fine even on 4959 which is a 4.0 build from last year. Strange that you had it glitched in 2021.

**Comment by OBattler** [comment]
Current code:
![imagem](https://github.com/user-attachments/assets/85ef4de4-ab32-4938-bb20-ed17dbe200b5) .
But this is on 808x, let me try the NEC Vx0.

**Comment by OBattler** [comment]
On an 8 MHZ NEC Vx0:
![imagem](https://github.com/user-attachments/assets/3d76793b-ec88-44e2-a388-1b190a67f2c8) .
Let's keep increasing the speed.

**Comment by OBattler** [comment]
Works even with the V30 set to 16 MHz, so the CPU is ruled out. Could it be the TNDY sound card (which is unneccessary on a real Tandy which has the chip built-in)? Let's test!

**Comment by OBattler** [comment]
It's not that. Next test: the 768k of RAM.

**Comment by OBattler** [comment]
Aha, I was looking at the wrong screen.
