### ISSUE TITLE
Missing full screen shortcuts in 4.2? 

### ISSUE THREAD

**Issue by md0-code** [86Box/86Box#4697]
### What happened?

The Ctrl+Alt+PgDn / Ctrl+Alt+PgUp shortucts do not work anymore in version 4.2 (no mention of them in the menus also). Manually switching to full screen from the "View" menu works, but there's no way back.

### Configuration file

```ini
[General]
confirm_exit = 0
video_fullscreen_first = 0
confirm_save = 0
confirm_reset = 0
video_gl_vsync = 1
video_gl_shader = ./shaders/m-crt.retroarch.glsl
force_43 = 1
enable_overscan = 1
do_auto_pause = 1
host_cpu = Intel(R) Core(TM) Ultra 5 125H
uuid = 7ad3352a-1372-5d12-b7ee-8f42e5c85500
vid_renderer = qt_opengl3

[Machine]
machine = ambx133
cpu_family = celeron_mendocino
cpu_speed = 133333333
cpu_multi = 2
cpu_use_dynarec = 1
time_sync = local
fpu_softfloat = 0
fpu_type = internal
mem_size = 32768

[Video]
show_second_monitors = 0
gfxcard = cl_gd5422_isa

[Input devices]
mouse_type = msserial
joystick_type = 2axis_2button
joystick_0_nr = 1
joystick_1_nr = 0
joystick_0_axis_0 = -2147483648
joystick_0_axis_1 = 1073741824
joystick_0_button_0 = 0
joystick_0_button_1 = 1

[Storage controllers]
hdc = none
cassette_pcm = -1
cassette_writeprot = 1

[Gravis UltraSound]
type = 0
base = 0240
gus_ram = 0
receive_input = 1

[Novell NE2000 #1]
base = 0300
irq = 10
bios_addr = 00000
mac = 1e:63:7a

[Sound]
fm_driver = nuked
mpu401_standalone = 1

[Network]
net_01_link = 2

[Floppy and CD-ROM drives]
fdd_02_check_bpb = 0
fdd_02_type = none
fdd_01_check_bpb = 0

[FluidSynth]
sound_font = ./sf2/32MbGMStereo.sf2
output_gain = 100
chorus = 0
chorus_voices = 3
chorus_level = 100
chorus_speed = 30
chorus_depth = 80
chorus_waveform = 0
reverb = 0
reverb_room_size = 20
reverb_damping = 0
reverb_width = 1
reverb_level = 90
interpolation = 2

[Realtek RTL8019AS #1]
mac = da:27:91

[Realtek RTL8029AS #1]
bios = 0
mac = 70:b6:e3

[Ensoniq AudioPCI (ES1371)]
codec = 1414676739
receive_input = 1

[IBM MDA]
rgb_type = 2

[DTC 5150X MFM Fixed Disk Adapter]
bios_addr = C8000

[Hercules]
rgb_type = 2
blend = 1

[Hercules Plus]
rgb_type = 2
blend = 1

[IBM CGA]
display_type = 0
composite_type = 0
rgb_type = 0
snow_enabled = 1

[Compaq CGA 2]
display_type = 0
composite_type = 0
rgb_type = 0
snow_enabled = 1

[Windows Sound System]
base = 0530
opl = 1

[TNDY]
base = 00C0

[Novell NE1000 #1]
mac = 3e:63:5e

[PC/XT XTIDE]
bios = xt

[S3 ViRGE/GX2 (Diamond Stealth 3D 4000) AGP]
bilinear = 1
dithering = 1

[Standard PS/2 Mouse]
buttons = 2

[XGA (ISA)]
type = 0
instance = 6
ext_mem_addr = 00F0
dma = 7

[Ports (COM & LPT)]
lpt1_device = text_prt
```

### Operating system

Debian 12

### CPU

Intel Core Ultra 5 125H

### 86Box version

v4.2 build 6000

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by jriwanek** [comment]
I've validated on Windows, and gotten someone else to validate on Linux, and they work fine for us, what window manager are you using, and have you checked it's not grabbing those keys?

**Comment by md0-code** [comment]
I'm using Gnome 46 / Mutter on Wayland, kernel version 6.9.12. There are no shortcuts defined for Ctrl+Alt+PgDn / Ctrl+Alt+PgUp.
I can confirm that the shortcuts work on windows, even though they are no longer listed in the menu.

**Comment by OBattler** [comment]
Could you please bisect and see which exact build of 86Box introduced this regression?

**Comment by OBattler** [comment]
Ctrl+Alt+PgUp should now definitely work. No idea why Ctrl+Alt+PgDn is broken, though.

**Comment by OBattler** [comment]
OK, Ctrl+Alt+PgDn is broken if keyboard is set to require capture.

**Comment by usergithub64** [comment]
After these fixes, a regression occurred. When switching to fullscreen mode and then back to windowed mode, it switches the second time. (both with the option "Keyboard requires capture" enabled and disabled). How to reproduce the bug:
1. Switch to fullscreen mode Ctrl+Alt+PgUp.
2. Switch to windowed mode Ctrl+Alt+PgDn. Fullscreen mode will blink, but will remain fullscreen.
3. Press Ctrl+Alt+PgDn again. Now it switches to windowed mode normally.
Before these fixes, everything worked fine (with the option "Keyboard requires capture" disabled).

**Comment by usergithub64** [comment]
Please check and confirm the regression. The bug appears after the second switch to fullscreen mode and back.

**Comment by OBattler** [comment]
I can reproduce it - it appears CTRL and ALT are getting stuck.

**Comment by md0-code** [comment]
I can confirm that this is not the cause of my original problem - I've now isolated it to the use of the "Fn" key in combination with  PgUp/PgDn, which share the same physical keys with the up/down arrows. If I press Ctrl+Alt+Fn+PgUp/PgDn on my laptop's keyboard it doesn't work, if I do the same combo with a USB keyboard having similar Fn and keys disposition it works. It may be something specific to my particular laptop model (Lenovo Ideapad Slim 5), probably not easily fixable.

**Comment by OBattler** [comment]
@usergithub64 The regression is now fixed.
