### ISSUE TITLE
Trog Tandy 1000 Graphical glitches

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4698]
### What happened?

Game glitches at the developer logo. Other parts on the game are normal. For some reason, on Tandy 1000 HX, the arrow keys don't work, meaning that I can't really control the character when going in-game whereas they do on the Tandy 1000 SL/2. My laptop does not have a right numpad, so I can't verify whether it work using right numpad instead.

![Monitor_1_20240806-200830-829](https://github.com/user-attachments/assets/32a90965-bbce-4e8f-9c72-1d8c82cecac8)

![Monitor_1_20240806-200827-202](https://github.com/user-attachments/assets/ece11615-28d7-461b-91ab-b3686b084e0f)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6037
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy1000hx
cpu_family = necv20
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 8087
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 525_2qd
fdd_01_turbo = 1
fdd_02_type = 525_2qd
fdd_02_turbo = 1
fdd_01_image_history_01 = Tennis Cup Disk A & B.IMG
fdd_01_fn = trog.IMA
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2.1 6037

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

In order to test, boot up Tandy 1000 HX or SL/2, then insert this disk, and run TROG.bat . After selecting the tandy graphics mode, then the glitches can be seen
[trog.zip](https://github.com/user-attachments/files/16517767/trog.zip)

**Comment by OBattler** [comment]
For the arrow keys, turn on num lock.

**Comment by OBattler** [comment]
I suspect the copy of the game is back and missing the Tandy graphics, because it appears to be blitting 640x400 logo's.

**Comment by OBattler** [comment]
Yes, this is definitely a bad copy. I found the source floppy image - and it's 1.44 MB. A bit strange for a game that supports the CGA and Tandy. And it looks like it's an already installed copy. As such, I'm closing this as NOTABUG - this can be reopened if an actual, proper copy is found (I verified, not even BetaArchive has one) and verified to have the same problem.

**Comment by OBattler** [comment]
Reopening because apparently, this game requies a Tandy with Tandy Video II because it uses Mode E (640x200x16 colors) for the title screens, but we were using the wrong value to specify it.

**Comment by OBattler** [comment]
Gloriouscow is going to be verifying this on their real Tandy tomorrow.

**Comment by Fenix770** [comment]
I have the same issue with the Tandy SL/2 on 86box and the latest stable version of DosBox-X. I recreated the 720kb floppy disk from a copy included in TDC #21 Torrent.

[Trog TDC-21.zip](https://github.com/user-attachments/files/16605967/Trog.TDC-21.zip)

**Comment by dbalsom** [comment]
I loaded Trog on my Tandy 1000 and I see the same graphical corruption. 

I think it's just a bug in the game, or at least in the image. We'd have to find a flux dump of the original disk to know for sure.

**Comment by eddmanx** [comment]
There's no kfx image but there's an unveried .img on archive.org. All the files are the same except for HI.BIN. No idea what's that for.
[disk01.zip](https://github.com/user-attachments/files/16650494/disk01.zip)

**Comment by dbalsom** [comment]
Probably someone's saved high scores.

**Comment by OBattler** [comment]
At this point, this can be closed as NOTABUG.
