### ISSUE TITLE
Night Hunter PC speaker sounds not fully working correctly

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#4704]
### What happened?

Night Hunter (Ubisoft,1988) game, some sounds are not played correctly :

Picking up keys, while sucking blood are not played correctly.

The same installation directory when copied out from the hard disk image and played under Dosbox, the sounds are played normally. I tried to play on a lower speed configuration - XT 4.77MHz, but the same problems exist.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6021
uuid = f30330a7-fdbd-599e-a5e2-d241e2d3c051
force_43 = 1
video_fullscreen_first = 0
confirm_reset = 0
iconset = winbox
confirm_exit = 0

[Machine]
machine = gw286ct
cpu_family = 286
cpu_speed = 10000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu_waitstates = 2
fpu_type = 287
mem_size = 2048

[Video]
gfxcard = ega

[Input devices]
mouse_type = ltserial

[Sound]
fm_driver = nuked
sndcard = sb1.5
mpu401_standalone = 1
sound_type = int16

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Logitech Serial Mouse]
port = 0
buttons = 3
revision = 3
rts_toggle = 1

[Sound Blaster v1.5 #1]
base = 0220
irq = 7
dma = 1
opl = 1
cms = 1
receive_input = 1

[System MIDI]
midi = 1

[Roland MPU-IPC-T]
base = 0330
irq = 2
receive_input = 1

[Everex EV-159 RAM 3000 Deluxe #1]
size = 1024
start = 1024
length = 0
width = 0
speed = 1
ems = 1
base = 0258
base2 = 0268

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_fn = /run/media/**user**/FILES/EMULATION/86Box/hdd/112MB_286.img
hdd_01_speed = 1996_5400rpm
hdd_02_parameters = 17, 15, 900, 0, ide
hdd_02_fn = /home/**user**/EMULATION/86Box/hdd/112MB_files.img
hdd_02_speed = 1996_5400rpm
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1

[Floppy and CD-ROM drives]
fdd_01_type = 525_2hd
fdd_02_type = 35_2hd

[Other peripherals]
isamem0_type = ev159
```

### Operating system

Debian

### CPU

i7 9750H

### 86Box version

6021

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by eddmanx** [comment]
Can't be tested with the machine files (cfg, nvr, hdd).

**Comment by TC1995** [comment]
Does it this happen on mame too? (PC/XT configuration)

**Comment by Mal752** [comment]
> Does it this happen on mame too? (PC/XT configuration)

Sorry, I didn't quite get you.

**Comment by TC1995** [comment]
The bug in question.

**Comment by Mal752** [comment]
> The bug in question.

I'm not sure I understand you. What do you mean by "happen on mame too"? 

If anyone else understand that, kindly explain the meaning. Thank you.

**Comment by lemondrops** [comment]
He's asking you to try running the game in MAME's PC/XT emulation and see if the bug happens there.

**Comment by Mal752** [comment]
I don't use MAME for classic PC games. Only Dosbox, as I have mentioned above. In Dosbox, all sounds work normally. Using the same directory that I installed in 86Box. Using floppy images downloaded from Good Old Days in Internet Archive for the install.

**Comment by TC1995** [comment]
Again, test it on MAME to see if it happens there.

**Comment by Mal752** [comment]
How do I test a PC game in MAME? 
What has MAME got to do with 86Box? I don't understand.

Anyway, it is working in Dosbox. 

For further info, I tried the Tandy configuration and it works, with all sound effects.

**Comment by TC1995** [comment]
You test it through a DOS boot disk or whatever DOS media you have on MAME through its Tandy 1000 driver.
The thing is if MAME has the same bug as 86box so we can deduce if it's a bug on both.

**Comment by eddmanx** [comment]
Game files for testing: 
[Night Hunter.zip](https://github.com/user-attachments/files/16640996/Night.Hunter.zip)

**Comment by eddmanx** [comment]
Just tested in MartyPC and the sounds work properly. It does seem to be an 86box issue.

**Comment by Mal752** [comment]
Yes, it works in Dosbox too.

**Comment by dbalsom** [comment]
When I try in 86box i do hear some speaker 'pops' when sound effects are supposed to play, sounds like the speaker turning on but not playing the right sound.

**Comment by OBattler** [comment]
Closing because it's being tracked in #4765 .

**Comment by OBattler** [comment]
It works fine on the Tandy because it uses the fast PIT (because of timings stuff), and also works fine on a regular XT when using the fast PIT.

**Comment by OBattler** [comment]
This is now fixed.
