### ISSUE TITLE
Image corruption on S3 (ISA16, PCI, VLB) video cards

### ISSUE THREAD

**Issue by usergithub64** [86Box/86Box#4711]
### What happened?

In the game "TIM" there is image corruption on S3 video cards (ISA16, PCI, VLB):
![Monitor_1_20240812-112133-622](https://github.com/user-attachments/assets/832247f0-cfd2-42d7-9983-9897a5267ad3)
![Monitor_1_20240812-105121-155](https://github.com/user-attachments/assets/266dc046-f7be-4e2d-b928-0cdfcc8736fa)
![Monitor_1_20240812-105857-282](https://github.com/user-attachments/assets/bc39cdae-a16f-453d-b2e7-e7d0aeae8638)

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
confirm_save = 0
force_43 = 1
confirm_exit = 0
host_cpu = Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
emu_build_num = 6055
uuid = d80219a0-bfd6-5d64-88f3-d4062dd305ac

[Machine]
machine = ami495
cpu_family = i386dx
cpu_speed = 40000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 1
time_sync = local
fpu_type = 387
mem_size = 2048

[Video]
gfxcard = px_trio64_vlb

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = sbawe32

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_vlb_2ch
cassette_mode = load

[S3 Trio64 VLB (Phoenix)]
memory = 4

[Hard disks]
hdd_01_parameters = 63, 16, 987, 0, ide
hdd_01_fn = images/485 MB.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none

[Sound Blaster AWE32 #1]
base = 0220
emu_base = 0620
base401 = 0330
irq = 5
dma = 1
dma16 = 5
onboard_ram = 28672
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 1

[Microsoft Serial Mouse]
port = 0
```

### Operating system

Windows 10 Pro x64 v22H2

### CPU

Core i9-10900K

### 86Box version

v4.2.1 Build 6055

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
when did it work on these cards last time? Bisect if they did.

**Comment by usergithub64** [comment]
In build 5336 and until the last build, there is this bug. In build 5335 there is no this bug.
