### ISSUE TITLE
OPENGL 3 ?

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#473]
Did you plan to add OPENGL rederer in 86Box, as PCEM ?

Use of libretro shaders make things even more real, like phosphore emulation (persitence of pixels), scanlines, images CRT deformation, more real CRT pixel emulation, etc.

![Screenshot from 2019-11-29 17-03-17](https://user-images.githubusercontent.com/16312616/69880462-3f205a00-12ca-11ea-89b5-fc4e9e76bfdb.png)

**Comment by OBattler** [comment]
I believe Agetian is working on getting any sort of OpenGL renderer working on 86Box. Once that is done, I can try to add support for shaders.

**Comment by Agetian** [comment]
Yeah, I need to figure out how to write it so that OpenGL doesn't blackscreen on SDL hardware :/ Most likely needs a different implementation of texture handling, I'll try to research this some more on the weekend.

**Comment by dhrdlicka** [comment]
Added in #1382.
