### ISSUE TITLE
Ghostbusters Tandy 1000 sound missing and minor graphical glitches

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4731]
### What happened?

Sound is missing on Ghostbusters. Theme song is supposed to play on the title screen (on the screen where it says to press 1 or 2) but doesn't, and the in-game scrolling text also doesn't have any sound. I have tested on Dosbox-X and there is sound present

Also, on Tandy SL/2, there are missing graphics, which aren't missing on Tandy 1000 HX
![Monitor_1_20240818-104539-008](https://github.com/user-attachments/assets/c85cbcd7-b28d-47dc-b63b-43fccc1b4c86)

Here is what is supposed to look like using a Tandy 1000 HX
![Monitor_1_20240818-104642-317](https://github.com/user-attachments/assets/5f561532-7f47-4684-a780-174c9b60e7a7)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6037
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy1000sl2
cpu_family = necv30
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 80187
mem_size = 768

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 525_1dd
fdd_01_turbo = 1
fdd_02_type = 525_2qd
fdd_02_turbo = 1
fdd_01_image_history_01 = Tennis Cup Disk A & B.IMG
fdd_01_image_history_02 = Tennis Cup Disk C & D.IMG
fdd_01_fn = Ghostbusters.img
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2.1 6037

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Game download. https://archive.org/details/000229-Ghostbusters
This is a booter game. Make sure to set drive A to be 180kb

**Comment by eddmanx** [comment]
You should really source the games from different places, especially the Total DOS Collection, before opening issues. That image is tagged as [b1] (meaning "Bad version 1") on TDS.

I'm not saying that's necessarily the cause of those issues (I haven't tested it myself), but you should test with good files anyway to make sure first.

**Comment by ualaa1** [comment]
Thanks for telling me about the collection, I did see on https://archive.org/download/total-dos-collection-g
that there was the one you saw [Ghostbusters (PCjr, Tandy 1000) [h1][b1] (1985)(Activision, Inc.) [Action].img.zip](https://archive.org/download/total-dos-collection-g/Ghostbusters%20%28PCjr%2C%20Tandy%201000%29%20%5Bh1%5D%5Bb1%5D%20%281985%29%28Activision%2C%20Inc.%29%20%5BAction%5D.img.zip), then there is [Ghostbusters (PCjr, Tandy 1000) [DC] (1985)(Activision, Inc.) [Action].zip](https://archive.org/download/total-dos-collection-g/Ghostbusters%20%28PCjr%2C%20Tandy%201000%29%20%5BDC%5D%20%281985%29%28Activision%2C%20Inc.%29%20%5BAction%5D.zip) which appears to be an unofficial conversion to DOS (other than Tandy 1000 and PCjr)
and then there's [Ghostbusters (PCjr, Tandy 1000) (1985)(Activision, Inc.) [kfx][180k][cp][!].zip](https://archive.org/download/total-dos-collection-g/Ghostbusters%20%28PCjr%2C%20Tandy%201000%29%20%281985%29%28Activision%2C%20Inc.%29%20%5Bkfx%5D%5B180k%5D%5Bcp%5D%5B%21%5D.zip)
which seems to be a pure version but 86Box apparently doesn't support this format


Anyways, I tested the image I put on the first post on 86Box PCJr (with turbo floppy off as game refuses to boot with turbo floppy on in PCjr) and it works perfectly, sounds are present and no missing graphics

**Comment by dbalsom** [comment]
I noticed you have configured your Tandy for 768K of memory.

This is not great for compatibility with older titles. See:
https://nerdlypleasures.blogspot.com/2014/05/memory-in-tandy-1000-series-why-more-is.html?m=1

**Comment by Digitoxin1** [comment]
I have tested Ghostbusters on a real Tandy 1000 SX and in 86Box using the attached .86f image.  This image was made from a pristine Kryoflux dump of the game.  I made a floppy using the same dump to test on my Tandy 1000.

The game runs without issues on my Tandy 1000.
The game runs without issues in 86Box using PCjr emulation.
The game will not get past the Activision logo in 86Box using Tandy 1000 emulation.

I tested under build 6000 and build 6070.

[Ghostbusters (1985) (Tandy+PCjr) (160K) (Booter) [cp] [!].zip](https://github.com/user-attachments/files/16665109/Ghostbusters.1985.Tandy%2BPCjr.160K.Booter.cp.zip)

**Comment by Digitoxin1** [comment]
I just tested as far back as build 2008.  An uncracked copy of Ghostbusters will not get past the Activision logo when using Tandy 1000 emulation.

**Comment by dbalsom** [comment]
I can confirm that the originally posted IMG file does boot on my Tandy 1000. I hear the ghostbusters theme during the splash screen, and there's a 'brr' sound effect as the text writes out on the brown screen that follows.

**Comment by Digitoxin1** [comment]
Ghostbusters is a copy protected game.  If you are booting from an .img file, you are using a modified cracked image

**Comment by OBattler** [comment]
What kind of copy protection does it use?

**Comment by Digitoxin1** [comment]
Basic sector overlap.  Track 39.0 has sectors 1, 2, 3, 4, 5, 6, 23 ,24.    
Sector 23 has a size of 1024 bytes and overlaps with sector 24.

**Comment by dbalsom** [comment]
5 bytes are read from sector 23, at offsets > 512 so we need to read the whole thing.  The skip flag is true on the read operation, but it not a deleted data mark so we shouldn't skip the sector. 

The sector data is loaded at 0070:E180. The first byte read is @ 0EAC0 which should be 0x3C.
The bytes read are XOR'd together like so:
```
seg000:027B 26 8A A5 40 02                    mov     ah, es:[di+240h]
seg000:0280 26 8A 85 70 02                    mov     al, es:[di+270h]
seg000:0285 26 8B 95 A0 02                    mov     dx, es:[di+2A0h]
seg000:028A 26 8A 95 64 02                    mov     dl, es:[di+264h]
seg000:028F 59                                pop     cx              
seg000:0290 26 8A 8D 8E 02                    mov     cl, es:[di+28Eh]
seg000:0295 33 D1                             xor     dx, cx
seg000:0297 33 C2                             xor     ax, dx
seg000:0299 33 DB                             xor     bx, bx
```
AX is then checked for the following value:
```
seg000:005D 3D 6A DA                          cmp     ax, 0DA6Ah
```
if this check fails, the game erases segment 0 and halts (jump +0)

**Comment by Fenix770** [comment]
I don't know if this info is useful, but the SL/2, has a 8086 8 Mhz, and Tandy Video II chip, (Called back then Enhanced TGA).
If the game was launched in 1985, then expects an original Tandy 1000 graphics chip and a 8088 4.77 or 7.16 Mhz at best.

**Comment by dbalsom** [comment]
still works for me at 7.16Mhz

**Comment by OBattler** [comment]
On 86Box, after reading that sector, it calls INT 13h with AX=0000h which is reset the controller. I have no idea why that happens.

**Comment by RayGarrett** [comment]
Hmm, It works on a real Tandy 1000 SX which has DMA.

**Comment by Digitoxin1** [comment]
Hmm, It works on a real Tandy 1000 SX which has DMA.

**Comment by dbalsom** [comment]
> On 86Box, after reading that sector, it calls INT 13h with AX=0000h which is reset the controller. I have no idea why that happens. Perhaps the game is hardcoded for PIO?

It's using DMA in MartyPC when it loads

**Comment by OBattler** [comment]
OK, so it passes the copy protection check, reads all the way to sector 25 0 6 2, then freezes.

**Comment by OBattler** [comment]
It appears this game requires the vsync interrupt. With that, the copy protected version no longer freezes and I can even hear the music. This only leaves the glitching logo on the SL/2 which I'm going to fix later.

**Comment by OBattler** [comment]
Actually, this appears to have fixed the missing logo on the Tandy 1000 SL/2 as well! Therefore, this can now be closed.
