### ISSUE TITLE
Olivetti M19 640x400 mode does not work

### ISSUE THREAD

**Issue by goatM19** [86Box/86Box#4739]
### What happened?

The mode 40h switch isn't honored. The machine is left in 640x200

![86box-m19](https://github.com/user-attachments/assets/accd76f1-ac84-41f8-9b1a-8e589ab5f5bd)

Here is same software running on a real machine 

![m19-gem](https://github.com/user-attachments/assets/60827c4e-81ed-43c1-8b0c-bc207390dae5)

This is same hi-res mode as in M24, the GEM is working with M24 driver.
Here is an original publishing verifying the support for 640x400 mode

[Olivetti_M19_brochure.pdf](https://github.com/user-attachments/files/16701175/Olivetti_M19_brochure.pdf)

I apologize in advance if this is fixed in some newer version :) Switching the profile to M24 fixes the issue of course.

### Configuration file

```ini
[Trident TVGA 8900D]
memory = 512

[General]
vid_renderer = qt_software
force_43 = 1

[Machine]
machine = m19
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 512

[Video]
gfxcard = internal

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = xtide
cassette_mode = load

[Hard disks]
hdd_01_parameters = 33, 8, 776, 0, ide
hdd_01_fn = hdd0.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_02_image_history_01 = D:/pc_dsk_images/Intel iC-86 Compiler 4.5 for DOS (5.25-360K)/Images/Img/disk07.img
fdd_02_image_history_02 = D:/pc_dsk_images/Intel iC-86 Compiler 4.5 for DOS (5.25-360K)/Images/Img/disk06.img
fdd_02_image_history_03 = D:/pc_dsk_images/Intel iC-86 Compiler 4.5 for DOS (5.25-360K)/Images/Img/disk05.img
fdd_02_image_history_04 = D:/pc_dsk_images/Intel iC-86 Compiler 4.5 for DOS (5.25-360K)/Images/Img/disk04.img
fdd_02_type = none
fdd_01_image_history_01 = C:/Users/z/Downloads/Digital Research GEM Write 1.0 (5.25-360k)/Digital Research GEM Write 1.0 (5.25-360k)/disk01.img
fdd_01_image_history_02 = C:/Users/z/Downloads/Digital Research GEM Desktop 2.2 (5.25-360k)/Digital Research GEM Desktop 2.2 (5.25-360k)/Disk04 - Driver Disk 3.img
fdd_01_image_history_03 = C:/Users/z/Downloads/Digital Research GEM Desktop 2.2 (5.25-360k)/Digital Research GEM Desktop 2.2 (5.25-360k)/Disk02 - Driver Disk 1.img
fdd_01_fn = C:/Users/z/Downloads/Digital Research GEM Paint 1.0 (1985) (5.25-360k)/Digital Research GEM Paint 1.0 (1985) (5.25-360k)/disk01.img
fdd_01_image_history_04 = C:/Users/z/Downloads/Digital Research GEM Desktop 2.2 (5.25-360k)/Digital Research GEM Desktop 2.2 (5.25-360k)/Disk01 - System Master Disk.img

[Logitech Serial Mouse]
port = 0
buttons = 2
revision = 3
rts_toggle = 0

[PC/XT XTIDE]
bios = xt

[Hercules]
rgb_type = 0
blend = 1

[IBM CGA]
display_type = 0
composite_type = 0
rgb_type = 5
double_type = 0
snow_enabled = 0

[Olivetti M19 graphics card]
rgb_type = 1
snow_enabled = 0

[Longshine LCS-6821N #1]
bios_addr = D0000
irq = 5

[Trantor T130B #1]
bios_addr = D8000
base = 0350
irq = 5

[Microsoft Serial Mouse]
port = 0
buttons = 2

[Olivetti M21/M24/M28 (GO317/318/380/709) video card]
rgb_type = 1
snow_enabled = 0
```

### Operating system

Server 2022

### CPU

Xeon

### 86Box version

4.1.1 5634

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
The code calls the OGC code (used by M24 as well) directly, but also supports Plantronics ColorPlus emulation, and that may be interfering.

**Comment by goatM19** [comment]
I can also try to provide a code patch for this.
Also, the 640x400 should not be available if the machine is running in colour mode. I'm not sure whether the current code honours this. 

Check the monitors section on page 4

[APP086 (1st ed) - Acorn Personal Computer M19 (1986)-opt.pdf](https://github.com/user-attachments/files/16728680/APP086.1st.ed.-.Acorn.Personal.Computer.M19.1986.-opt.pdf)

M19 mono screen is analog and refreshed at 47Hz, so it and the videocard's internal pixel clock can cope with this mode. In colour RGBi operation refresh is standard 60Hz.

**Comment by OBattler** [comment]
At this point, I'm suspecting some jumper is not being read out correctly.

**Comment by jriwanek** [comment]
(A patch would be most welcome @goatM19)
