### ISSUE TITLE
The OEM Deskmate for Tandy 1000 SL/2 crash at launch

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4742]
### What happened?

I tested recently installed Tandy DOS 3.30 and the Deskmate 3.03 OEM for the Tandy 1000 SL/2. It crash after launching it at DOS prompt, (sometimes it also closes the 86box VM Window). For some reason, I have an old Tandy 1000 SL/2 VM, and it works. I don't know what is the cause of this behavior.

Pd: it also happens on build 4.2.1.6070, (before the recent vsync changes)

Here are the VM, CFG and NVR files:
[Tandy 1000 SL-2 new.zip](https://github.com/user-attachments/files/16734571/Tandy.1000.SL-2.new.zip).

This other Tandy 1000 SL/ have the same Deskmate and seems to work fine:
[Tandy 1000 SL (original nueva).zip](https://github.com/user-attachments/files/16734635/Tandy.1000.SL.original.nueva.zip)

 

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 6082
uuid = cf19d5a9-665b-5895-9874-cd2daca82fc4
enable_overscan = 1
vid_resize = 1


[Machine]
machine = tandy1000sl2
cpu_family = 8086
cpu_speed = 8000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 768

[Video]
gfxcard = internal

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = st506_xt_wd1004a_wx1
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 4, 615, 0, mfm
hdd_01_vhd_blocksize = 1024
hdd_01_mfm_channel = 0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2dd


[AST SixPakPlus #1]
irq = 3

[Other peripherals]
isartc_type = a6pak

[WD1002A-WX1 MFM Fixed Disk Adapter]
bios_addr = C8000
base = 0320
irq = 5

[Microsoft Serial Mouse]
port = 1
buttons = 2

[Logitech/Microsoft Bus Mouse]
base = 023C
irq = 3
hz = 60
buttons = 2

[AST SixPakPlus]
irq = 3

[WD1004A-WX1 MFM Fixed Disk Adapter]
bios_addr = C8000
base = 0320
irq = 5

[Magitronic B215]
bios_addr = CA000
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.2.1.6082

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Yes, you have your hard disk controller set to IRQ 5 which is used by the VSync interrupt. Move it to IRQ 2.

**Comment by OBattler** [comment]
OK, disc card that. And it's NOTABUG, let me quote from another issue:

> I find that this happens until default values are written to the emulated EEPROM.
Run SETUPSL2.EXE. This will report that it reads invalid values from the EEPROM. Press F10 to write factory settings.
Upon restart DeskMate should start.
Let me know if it is still not working for you.

This is confirmed by the fact that if I replace the .BIN of your bad machine with the one from your good machine, DeskMate works.

**Comment by Fenix770** [comment]
I tried to recreate the HDD, but on the IRQ 2 the HDD is not correctly recognized:

![Monitor_1_20240824-082238-923](https://github.com/user-attachments/assets/4aab6dfa-20d5-4920-b2ca-726f2c9c584b)

![Monitor_1_20240824-082350-940](https://github.com/user-attachments/assets/ca1e1b37-d32c-45d3-9018-35ff6b9c78d5)

**Comment by Fenix770** [comment]
Sorry, I did not test the last build!

**Comment by Fenix770** [comment]
Update: I recreated the hard disk image from scratch, using the IRQ 2, MS-DOS works fine now, but for some strange reason Deskmate works when loaded from the ROM drive when there is no HDD.

**Comment by Fenix770** [comment]
BTW: I copied the NVR from the other machine as you suggested, and Deskmate works now, I suspect there is some issue with 86Box when it creates the NVR BIN file
