### ISSUE TITLE
ScubaVenture PCjr misaligned graphics and function keys not working properly

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4743]
### What happened?

Game is misaligned. Also, when pressing the function key to try to play the game, it still remains on the title screen.
In this screen, the "C" in INC is cutoff
![Monitor_1_20240821-222524-377](https://github.com/user-attachments/assets/fa43e547-a2b0-4206-ac04-83e40a7287df)

Tried various CPU and memory configurations already. Game download. This is a PCjr cartridge game.

[SCUBAVNT.zip](https://github.com/user-attachments/files/16734794/SCUBAVNT.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6082
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = ibmpcjr
cpu_family = necv20
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 8087
mem_size = 64

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load
cartridge_01_fn = C:/Users/19099/Desktop/86Box-Windows-64-b6033/SCUBAVNT.JRC

[Floppy and CD-ROM drives]
fdd_02_type = 525_2qd
fdd_02_turbo = 1
fdd_01_image_history_01 = trog.IMA
fdd_01_image_history_02 = intro td demo.IMA
fdd_01_image_history_03 = Tennis Cup Disk A & B.IMG
fdd_01_type = 525_2qd
fdd_01_turbo = 1
fdd_01_image_history_04 = Tennis Cup Disk C & D.IMG
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2.1 6082

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
The misalignment is not a bug - the game programs the PCjr that way. Press Ctrl+Alt+Right Arrow to move the screen. Pressing it once should be enough.

**Comment by ualaa1** [comment]
On a real PCjr, it seems the screen doesn't start misaligned: https://youtu.be/s5a6jKUkjlA

**Comment by OBattler** [comment]
> On a real PCjr, it seems the screen doesn't start misaligned: https://youtu.be/s5a6jKUkjlA and https://youtu.be/o-v0Zbu8tX8?t=547

Yes it is, look very carefully - it's slightly to the right.

But I just added another workaround for that - wait for the next 86Box build to compile and go to Display in Settings and click Configure, and untick Apply overscan deltas.

**Comment by OBattler** [comment]
As for the function keys, perhaps we're using the wrong scan code set for PCjr.

**Comment by OBattler** [comment]
OK, the misalignment is now fully fixes, alst the function keys do work properly - the title screen gets replayed and then you enter the game. Therefore, this can be closed.
