### ISSUE TITLE
Aztech Sound Galaxy Pro 16 AB (Washington) not loading in Windows 3.11

### ISSUE THREAD

**Issue by twstokes** [86Box/86Box#4747]
### What happened?

Running 4.2 with the latest 4.2 ROM set, Windows 3.11 no longer plays audio and doesn't appear to communicate with the Aztech Washington card.

### Configuration file

```ini
[General]
vid_renderer = qt_vulkan
scale = 2
sound_gain = 7
host_cpu = Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
uuid = 86c41599-ac2d-5cf9-b83b-3bba9ea06fe3

[Machine]
machine = pb640
cpu_family = pentium_p54c
cpu_speed = 75000000
cpu_multi = 1.5
cpu_use_dynarec = 1
time_sync = local
fpu_type = internal
fpu_softfloat = 0
mem_size = 16384

[Video]
gfxcard = cl_gd5430_pci

[Input devices]
mouse_type = msserial

[Storage controllers]
hdc = internal
cassette_mode = load

[Microsoft Serial Mouse]
port = 0
buttons = 2

[Realtek RTL8029AS #1]
bios = 0
mac = 04:27:d6

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_speed = 12
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_type = 86BOX_CD-ROM_1.00

[Hard disks]
hdd_01_parameters = 63, 16, 5079, 0, ide
hdd_01_fn = pb_hd.IMG
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Sound]
fm_driver = nuked
sndcard = azt2316a
midi_device = mt32

[Aztech Sound Galaxy Pro 16 AB (Washington) #1]
codec = 2
wss_interrupt_after_config = 0
addr = 0220
wss_irq = 10
wss_dma = 0
opl = 1
receive_input = 1
receive_input401 = 1
```

### Operating system

Linux x86 + ARM / macOS / Windows

### CPU

i7-9700K

### 86Box version

v4.2

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [X] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

- The sound card always works in DOS.
- Downgrading to 86Box [4.1.1](https://github.com/86Box/86Box/releases/tag/v4.1.1) makes the audio work again.
- Building from source the audio quits working after `3f6126f72`. (possibly the culprit is in [this commit set](https://github.com/86Box/86Box/compare/3f6126...660a33f))
- The driver [mentioned here](https://github.com/86Box/86Box/issues/4433#issuecomment-2101346727) works in Windows. Reinstalling the original Packard Bell driver does not when running 4.2.
- Reproducible across different operating systems (Linux, Windows, macOS) and whether it was a release binary or built from source.

**Comment by TheDell1998** [comment]
Did you use the latest Aztech sound drivers for that one?

**Comment by twstokes** [comment]
> Did you use the latest Aztech sound drivers for that one?

Hi @TheDell1998 - [is it this one](https://github.com/86Box/86Box/issues/4433#issuecomment-2101346727) you're referring to? If so, yes - and they worked (as noted above). But this feels like a regression if the system worked with the previous set that came standard with the system. I also noticed that the MIDI output quality was a lot worse.

**Comment by TheDell1998** [comment]
What do you mean the MIDI output quality?

**Comment by TC1995** [comment]
Any link tot he PB specific Aztech drivers?

**Comment by OBattler** [comment]
Try the latest build from our Jenkins - we have since fixed some sound-related regressions.

**Comment by twstokes** [comment]
> Any link tot he PB specific Aztech drivers?

I'll grab them from the PB Master CD and provide a link.

> Try the latest build from our Jenkins - we have since fixed some sound-related regressions.

OK - will do - I'll report back. Thanks!

**Comment by twstokes** [comment]
[SOUND144.zip](https://github.com/user-attachments/files/16737831/SOUND144.zip)

Drivers supplied with PB Master CD 170263R1 for a PB 415CD. 

Just to add extra context: Before 4.2 I was able to take an HD image from a working PB 415CD and run it in 86Box with the config above and it worked perfectly other than needing to swap out the CD-ROM drivers. It was pretty amazing.

**Comment by twstokes** [comment]
> Try the latest build from our Jenkins - we have since fixed some sound-related regressions.

Build 6088 from Jenkins produced the same results for me - no audio.

When it works I can access the "Setup..." view.

<img width="743" alt="image" src="https://github.com/user-attachments/assets/1ef9ebcb-1bee-48e8-804f-4618ba48e63d">

**Comment by OBattler** [comment]
Can you upload the VM please?

**Comment by twstokes** [comment]
> Can you upload the VM please?

Email sent. 📧
