### ISSUE TITLE
Stunt Driver Tandy SL/2 DAC does not work

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4748]
### What happened?

I expected the sound to work and to hear digitalized effects

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6088
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy1000sl2
cpu_family = necv30
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 8087
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load
cartridge_01_fn = C:/Users/19099/Desktop/86Box-Windows-64-b6033/MOUSER.JRC

[Floppy and CD-ROM drives]
fdd_01_image_history_01 = disk01.img
fdd_01_image_history_02 = Battle Chese.img
fdd_01_image_history_03 = Loom (1990) (v1.1, Int. 3.5.37) (360K) (Disk 1).ima
fdd_02_image_history_01 = Disk01.img
fdd_02_image_history_02 = introjr.IMA
fdd_02_image_history_03 = Tennis Cup Disk A & B.IMG
fdd_01_type = 525_2qd
fdd_01_turbo = 1
fdd_01_fn = disk02.img
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2.1 6088

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

To Reproduce
Download game from https://archive.org/details/002052-StuntDriver and manual from https://oldgamesdownload.com/wp-content/uploads/Stunt_Driver_Manual_DOS_EN.pdf

After inserting disk 1 and starting the game using STUNT.exe, choose tandy graphics mode.
Next, there will be a speed setting screen
![Monitor_1_20240824-170515-328](https://github.com/user-attachments/assets/d597f442-59ab-4fa1-b72a-7639a0fbd6cb)
I chose the fast option
Afterwards, swap to disk 2
Then, a title screen will pop up. Press a button to proceed from the title screen. 
A copy protection question will then appear. Use the manual to answer
Then a menu will pop up.
Select sound, then options, then select Tandy DAC. 
Then select play
Buzzing sounds will be heard instead of digitalized sounds

Sound does work correctly when selecting Tandy 3 Voices, however it is not digitalized sound

**Comment by OBattler** [comment]
You chose the wrong option.

**Comment by ualaa1** [comment]
Happens even with the medium speed option. Only buzzing voices when choosing Tandy DAC

**Comment by OBattler** [comment]
According to this, the real Tandy 1000 SL/2 doesn't support more than 8 MHz: https://theretroweb.com/motherboard/manual/31681.pdf . This means that the game is quite assuredly designed to only support the DAC on something faster.

**Comment by OBattler** [comment]
The manual confirms it - the minimum requirement is an 8 MHz 286. For a Tandy, this means a Tandy 1000 TX or TL. As such, I'm closing this as NOTABUG.
