### ISSUE TITLE
PCjr. Composite Mode Broken

### ISSUE THREAD

**Issue by GreatHierophant** [86Box/86Box#4749]
### What happened?

The PCjr. machine type shows RGBI graphics regardless of whether the display type configuration is set to RGB or Composite.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 7 5800X 8-Core Processor             
emu_build_num = 6089
uuid = 9800801d-e0e3-5ff2-beca-0803e3909a2d
confirm_exit = 0
confirm_save = 0

[Machine]
machine = ibmpcjr
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 128

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_enabled = 1
cassette_mode = load

[IBM PCjr]
display_type = 1
apply_hd = 1
```

### Operating system

Windows 11 Home 23H2

### CPU

AMD Ryzen 7 5800X

### 86Box version

4.2.1 build 6809

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Seems to be a regression, PCjr. composite works with the same config in v4.0 build 5000. PC composite works in the current build.

**Comment by TC1995** [comment]
Bisect to know what exact build has broken it.
