### ISSUE TITLE
Jazz Jackrabbit graphics corruption on all video cards

### ISSUE THREAD

**Issue by Agetian** [86Box/86Box#477]
**Describe the bug**
In Jazz Jackrabbit 1, the in-game graphics during the actual gameplay are corrupt to the point that makes the game unplayable. A screenshot is attached to demonstrate the issue. The issue does not seem to be dependent on the video card chosen (tried several Trident, S3, Cirrus Logic cards, as well as ATI Mach64). Also doesn't seem to be dependent on the emulated machine type (tried 386, 486, Pentium builds).

**To Reproduce**
1. Start Jazz Jackrabbit 1 and then start the first level.
2. As soon as the actual gameplay starts, the screen will be corrupt, and it becomes progressively more corrupt as characters move.

**Expected behavior**
There should be no graphics corruption during the gameplay.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/24357441/69970766-df2aed00-152f-11ea-8a5d-71e7c8453ea3.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3 (running 86Box via Wine 4.21-staging), also tested on Win 8 VM.
 - Version 2.07 (also tested on the current upstream master).

**Additional context**
This issue may or may not be related to the fact that Jazz Jackrabbit 1 is somewhat unique in the video mode handling compared to other sidescrollers. It looks like it uses 320x200 for the menus and stuff, but ingame it uses a trick and switches to a mode which appears to be 320x199, which may confuse emulators. Some discussion of this VGA trick is available here: https://www.vogons.org/viewtopic.php?f=33&t=37821  and also in the video here at around 4:20  mark: https://www.pixelships.com/adg/ep0150.html 
Once again, not sure if this is related, but it's the only "quirky" part I could identify regarding this game and the way it displays graphics.
I tested this game in other contemporary emulators, including PCem v15, DOSBox 0.74-2, and DOSBox-X 0.82.23, and in all modern emulator builds the game behaved correctly, at least with no graphics corruption.

**Comment by OBattler** [comment]
This is fixed by the latest commit.
