### ISSUE TITLE
Windows 98 can be shut down directly, but once restarted it is stuck at the Windows 98 icon screen.

### ISSUE THREAD

**Issue by SeasonMemory** [86Box/86Box#4776]
### What happened?

The Windows 98 emulated by 86Box can be shut down directly, but once restarted it is stuck at the Windows 98 icon screen whenever if in or after the installation of system. 
![Monitor_1_20240830-232644-491](https://github.com/user-attachments/assets/58d7e308-e68e-471a-945b-10a36f9e23a3)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 7 4800H with Radeon Graphics         
emu_build_num = 6000
uuid = 4a802fbf-397f-5e85-a15c-e5d351cf84f8
language = zh-CN
dpi_scale = 0
confirm_exit = 0

[Machine]
machine = 686bx
cpu_family = pentium2_klamath
cpu_speed = 100000000
cpu_multi = 1.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 131072

[Video]
gfxcard = ctl3d_banshee_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sbawe32
midi_device = mt32_new

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0
net_01_card = ne2kpci
net_01_net_type = slirp

[Storage controllers]
hdc = internal
cassette_mode = load

[Creative 3D Blaster Banshee]
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 4
recompiler = 1

[Standard PS/2 Mouse]
buttons = 5

[Sound Blaster AWE32 #1]
base = 0220
emu_base = 0620
base401 = 0330
irq = 5
dma = 1
dma16 = 5
onboard_ram = 28672
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[Realtek RTL8029AS #1]
bios = 1
mac = f6:f7:3c

[Hard disks]
hdd_01_parameters = 63, 16, 10402, 0, ide
hdd_01_fn = Windows 98 SE x86_32
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
cdrom_02_parameters = 0, atapi
cdrom_02_ide_channel = 0:1
cdrom_02_type = 86BOX_CD-ROM_1.00
cdrom_02_image_path = D:/【Promise】/System/Images/Microsoft_Windows_98SE._ChineseS_GB.ISO
```

### Operating system

Windows 10 Pro 22H2

### CPU

AMD Ryzen 7 4800H

### 86Box version

v4.2 build 6000

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by eddmanx** [comment]
It's better to test the latest build from jenkins before opening an issue. This was just fixed in build 6116.

**Comment by SeasonMemory** [comment]
> It's better to test the latest build from jenkins before opening an issue. This was just fixed in build 6116.

Thanks a lot, so sorry for that, I just thought the GitHub version is latest.

**Comment by OBattler** [comment]
The nightly builds are on: https://ci.86box.net .

And yes, this has already been fixed - it's the Gigabyte GA-686BX soft reset bug, I fixed that last night.
