### ISSUE TITLE
Weird flickering artifacts on Olivetti M19

### ISSUE THREAD

**Issue by choas75** [86Box/86Box#4780]
### What happened?

I first want to say that you guys did an awesome job.
I really like to see my (dad's) first personal computer come to life.
However the strange flickering artifacts when printing to the screen is done or particularly when scrolling is annoying.
Is it possible to fix?

### Configuration file

```ini
[Machine]
machine = m19
cpu_family = 8088
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = local
cpu_speed = 4772728
fpu_softfloat = 0
mem_size = 640

[Storage controllers]
hdc = st506_xt_dtc5150x

[Video]
gfxcard = internal

[Olivetti M19 graphics card]
snow_enabled = 1
rgb_type = 3

[Hard disks]
hdd_01_parameters = 17, 4, 615, 0, mfm
hdd_01_fn = vdisk00.img
hdd_01_mfm_channel = 0

[WinBox]
window_fixed_res = 960x720

[General]
dpi_scale = 0
vid_resize = 2
window_fixed_res = 960x720
language = system
vid_renderer = qt_software

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Floppy and CD-ROM drives]
fdd_01_image_history_01 = C:/Users/erikv/Downloads/Microsoft MS-DOS 3.20 [Olivetti OEM] (3.5-720k)/Disk1.img
fdd_02_image_history_01 = C:/Users/erikv/Downloads/Microsoft MS-DOS 3.20 [Olivetti OEM] (3.5-720k)/Disk2.img
```

### Operating system

Windows 11

### CPU

Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz   2.19 GHz

### 86Box version

86Box v4.1.1 [build 5624]

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Same happens under Linux and it doesn't matter what is selected as a renderer.

**Comment by eddmanx** [comment]
Why such an old build. Try the latest build from jenkins and see if it makes a difference.

**Comment by OBattler** [comment]
This is snow emulation, go to the Video tab, click Configure there, and untick Snow emulation.

**Comment by choas75** [comment]
> This is snow emulation, go to the Video tab, click Configure there, and untick Snow emulation.

Thanks a lot. That worked.
