### ISSUE TITLE
PCjr: Save game function doesn't work in KQ1 since build 5574

### ISSUE THREAD

**Issue by pixel-jupiter** [86Box/86Box#4785]
### What happened?

King's Quest 1 (PCjr version) doesn't save a game on disk.

Steps to reproduce:
1) Boot [KQ1](https://archive.org/download/kings-quest-1-pcjr/KQ1PCJR.ZIP).
2) Press "3" (or type "save game") and type a letter (let's say, "A").
3) Press "5" (or type "restore game") and type a letter "A".

You'll see a message on the screen: "That version wasn't saved!".

![2024-09-02_102407](https://github.com/user-attachments/assets/40e6c3fa-cca7-4b67-9fa9-1be8f411c292)

It works as intended in build 5573,

Keep in mind that the game disk becomes unbootable after you save your game on it. You'll need to use a "clean" copy to boot the game again.

### Configuration file

```ini
[General]
vid_renderer = qt_software
dpi_scale = 0
force_43 = 1

[Machine]
machine = ibmpcjr
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 128

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_enabled = 1
cassette_mode = load
```

### Operating system

Windows 10 64-bit

### CPU

AMD Athlon II X4 645

### 86Box version

build 5574 / build 6130

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Digitoxin1** [comment]
I can confirm this happens on both the original 1984 PCjr release and the 1985 Tandy + PCjr release.  There are two issues occurring, most likely related.

1. When you use the "copy disk" command to make a play disk, the game freezes after it is done making the play disk.
2. When you boot the game and try to use the play disk you just created, it will act like it saved the game successfully, but when you load the game, you get the error message "That version wasn't saved!"

This does not happen when emulating a Tandy 1000, only the PCjr.

Using the 1985 Tandy + PCjr release, I am able to create a play disk on a Tandy 1000, save a game, and then successfully restore that game on a PCjr.   When saving a game to that same disk from the PCjr, I am unable to restore that game on either a PCjr or a Tandy 1000,

Whatever is broken is happening on writes, not reads.

**Comment by Digitoxin1** [comment]
This has nothing to do with King's Quest.  Writing to any disk on the PCjr is broken.  I booted a PC-DOS disk and tried to write a simple text file to the disk and it corrupted the disk image.
