### ISSUE TITLE
BeOS and Voodoo 3 or Banshee

### ISSUE THREAD

**Issue by Yaranga** [86Box/86Box#4794]
### What happened?

The problem is present in any possible configuration in BeOS when using any video cards Voodoo Banshee and 3

![beos-voodoo3](https://github.com/user-attachments/assets/56ce0cc9-acd0-4a64-aefe-937f99acffbd)

### Operating system

Windows 11

### CPU

Intel(R) Xeon(R) CPU E5-1650 v4

### 86Box version

86Box v4.2.1

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Yaranga** [comment]
https://file.io/fQnZpW14gowP - BeOS hdd image.

**Comment by OBattler** [comment]
It says that the transfer has been deleted.

**Comment by OBattler** [comment]
Also, what BeOS version did you use?

**Comment by OBattler** [comment]
Yaranga> The NVR and the hard disk image please.

**Comment by Yaranga** [comment]
Ah, I see. Translation difficulties. I'll re-upload it now.

**Comment by Yaranga** [comment]
https://file.io/tGoSGep60xcM

**Comment by Yaranga** [comment]
I have used several BeOS versions 5.x. However, if you select a video card, for example, Matrox Millennium 2, the system starts and works fine.

**Comment by Yaranga** [comment]
Interestingly, this version of beos works great with voodoo3/banshee
https://disk.yandex.ru/d/XXLmgOaBOsXvRg
![BeOSR503PE](https://github.com/user-attachments/assets/53f27dc4-9d75-4b19-9364-3e984a118165)

**Comment by Yaranga** [comment]
Very old build for those interested (doesn't work with voodoo3). I'll just leave it here.
https://disk.yandex.ru/d/zrzFcCZP3Ms6Mx

**Comment by Yaranga** [comment]
Odlično, Miran! Bravo!
