### ISSUE TITLE
Amstrad Mega-PC. Unable to specify conventional memory inside the BIOS Setup program.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4800]
### What happened?

I cannot set the conventional memory inside the BIOS Setup program. So the BIOS always complain after the memory count on hard reset.

I suspect this is causing a crash when the UMBPro software tries to load the device drivers high.
I used this software to test the EMS hardware chip. Otherwise, I would use the QMAPs which is a similar software but uses the
V86 mode on 386 and latter CPUs.

Also, I found strange that the machine supports 1,2 and 8mb (I did not test higher amounts of RAM), but throws an error "66"
With 3 to 7mb of RAM, but I don't know which RAM configurations are supported.

Screenshots:
![Monitor_1_20240904-200914-313](https://github.com/user-attachments/assets/c3c61b0c-56b5-4fa6-a4f5-6bd159cc1f2a)

VM:
[Amstrad Mega-PC 2.zip](https://github.com/user-attachments/files/16881938/Amstrad.Mega-PC.2.zip)

### Configuration file

```ini
[Sound Blaster v2.0 #1]
base = 0220
mixaddr = 0000
irq = 5
dma = 1
opl = 1
cms = 1
receive_input = 1

[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 6139
uuid = fed4ec80-eb29-59c9-8fd5-ffd31e07b121
vid_resize = 1
rctrl_is_lalt = 1

[Machine]
machine = megapc
cpu_family = i386sx
cpu_speed = 20000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 8192

[Video]
gfxcard = internal

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb2.0
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = text_prt

[Storage controllers]
fdc = none
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_fn = 
hdd_01_speed = 1992_3600rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1

cdrom_01_type = NEC_CD-ROM_DRIVE260_1.00

[Standard PS/2 Mouse]
buttons = 2
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.3.0.6139

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
NOTABUG - press F9 to set defaults first.
