### ISSUE TITLE
T3100e detects memory size incorrectly

### ISSUE THREAD

**Issue by dcoshea** [86Box/86Box#4809]
### What happened?

With the memory size set to 1024 KB in the Settings dialog box, when I delete `t3100e.nvr` so that I can enter BIOS setup (the usual key didn't work when I tried this - see issue #4808) and then start `86Box`, the memory test counts up to 1024KB, and then once I get into BIOS setup it shows:

System memory = 640KB
Extended memory = 0MB
Expanded memory = 0MB + 384KB

If I just hit F10 to save those settings, then after exiting settings, the system seems to boot up normally after that.

If however after starting up without an `.nvr` file I go to "Extended memory" and hit the right arrow so it shows this instead:

System memory = 640KB
Extended memory = 0MB + 384KB
Expanded memory = 0MB

then after I hit F10 to save and restart, the memory test only counts up to 640K, I get another error, and when I enter BIOS setup again it shows:

System memory = 640KB
Extended memory = 63.5MB + 384KB
Expanded memory = 63.5MB

I would have expected that after restarting, it would still count up to 1024 KB of memory, wouldn't have another error, and in the BIOS setup it wouldn't show an unexpected 63.5MB chunk of memory.   PCem v17 behaves the way I'd expect.

Just some pure uninformed speculation, don't feel the need to address this in any way: I noticed commit 231eaad, not sure if it could be related.  I think that's a change which PCem v17 doesn't have.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
uuid = 794cc269-030f-5b95-8cca-58e98efee2e8
scale = 2

[Machine]
machine = t3100e
cpu_family = 286
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 1024

[Video]
gfxcard = internal

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Microsoft Serial Mouse]
port = 0
buttons = 3

[Hard disks]
hdd_01_parameters = 17, 4, 615, 0, ide
hdd_01_fn = [REDACTED]/hda.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
```

### Operating system

Debian GNU/Linux 12

### CPU

Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

### 86Box version

v4.2.1 (built from Git tag)

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [X] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

Build configuration: `--preset dev_debug -D CMAKE_TOOLCHAIN_FILE=[...]/cmake/flags-gcc-x86_64.cmake`

**Comment by Fenix770** [comment]
I have the same issue. To change the memory sizes, I use the SETUP3.EXE program included in the utility disk. 
Use the option "0" to enter setup from there.

**Comment by Fenix770** [comment]
I tested again, the utility file is called TEST3.EXE

**Comment by Fenix770** [comment]
I changed the configuration with TEST3 program and now the machine freezes before reaching the DOS prompt. 
I suspect there is an issue with the creation of the NVR file, since It has a similar crash issue with Tandy 1000 SL/2, and worked after I overwrote the NVR with one on the other Tandy VM.

**Comment by Fenix770** [comment]
Now works again after copied the NVR from the other Toshiba T3100e with Toshiba DOS 5.0.
Try overwriting the NVR file with this one on \NVR file.
[Toshiba t3100 experiment.zip](https://github.com/user-attachments/files/16922372/Toshiba.t3100.experiment.zip)

NOTE: I'm using the 40mb (type 12 HDD).

**Comment by dcoshea** [comment]
> Now works again after copied the NVR from the other Toshiba T3100e with Toshiba DOS 5.0. Try overwriting the NVR file with this one on \NVR file. [Toshiba t3100 experiment.zip](https://github.com/user-attachments/files/16922372/Toshiba.t3100.experiment.zip)
> 
> NOTE: I'm using the 40mb (type 12 HDD).

I changed many of my settings to match yours and was able to use your .NVR file, but your emulated machine has 3MB of RAM, with the BIOS set to allocate 1MB as extended and 1MB + 384KB as expanded.  When I used TEST3 to change it all to extended (i.e. 2MB + 384KB), on boot it only counted up to 2688 KB and I got a "Bad memory size" error.  After that, BIOS setup showed only 1.5MB + 384KB extended.  I saved those settings and it booted okay.  I used TEST3 to change it all to expanded, then it counted up to 3072 KB again, I got another "Bad memory size" error, allocated 2MB + 384KB to expanded, then it seemed to be happy again.  When I say it boots up okay, in this case I'm not trying to load any EMS or XMS driver, so all I'm saying is the BIOS was happy with whatever happened, not that the memory worked.

It seems then that somehow when extended memory is selected, the memory test shows less memory and the amount of memory shown in BIOS setup decreases by 0.5MB (wrapping around to 63.5MB), so whenever you switch between just extended and just expanded you get a memory error due to the amount of memory changing.

I expect to switch between 384KB of extended memory and 384KB of expanded memory fairly often :(

**Comment by Fenix770** [comment]
Actually the "+384kb" option is always expanded memory (LIM EMS), unless when the machine has only 1mb of ram, in that case the "+384kb" can be either extended or expanded. The supported memory sizes are 1,2,3 and 5mb.
Another thing is the 86box shouldn't allow any other memory size since is not supported by the real hardware.

**Comment by dcoshea** [comment]
> Actually the "+384kb" option is always expanded memory (LIM EMS), unless when the machine has only 1mb of ram, in that case the "+384kb" can be either extended or expanded. The supported memory sizes are 1,2,3 and 5mb.

Thanks for the info, I'm not familiar with any configurations other than 1MB.

**Comment by dcoshea** [comment]
Thanks, verified in ea10ce5e.
