### ISSUE TITLE
Eye of Horus (Tandy) -Elevator Screen renders weird

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4811]
### What happened?

Elevator screen renders weird as seen on https://imgur.com/a/Mxpo3Se
Compared to the EGA version as seen on https://youtu.be/MUobc8wNTfY?t=111

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6130
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy1000hx
cpu_family = necv20
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 8087
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_turbo = 1
fdd_02_turbo = 1
fdd_01_fn = disk5.img
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2.1

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

In order to test game, I used floppy versions found on https://archive.org/details/001152-EyeOfHorus
Insert disk 4 (not 1), run horus.bat, then swap to disk 5 once prompted
Next use https://www.old-games.ru/game/download/get.php?fileid=25276&modal=1 to answer copy protection
Then choose keyboard or joystick mode. If chosen keyboard, game then requires key configuration.
Afterwards, enter the game and see the glitchy screen

**Comment by MX9000** [comment]
@ualaa1 A little while ago I played this game and noticed that the elevator weirdness in Tandy mode also shows up in DOSBox and DOSBox-X.

**Comment by OBattler** [comment]
I asked @dbalsom to test it on their real Tandy, to see if it happens on real hardware not, because already had one example of a game that was glitching on the Tandy and it turned out to happen on real hardware as well.

**Comment by dbalsom** [comment]
It does this on an actual Tandy, too.

**Comment by OBattler** [comment]
Then this can be closed as NOTABUG.

**Comment by dbalsom** [comment]
for a possible explanation: EGA has a line compare register which allows the screen to scroll while keeping the status bar at the bottom of the screen.   Tandy lacks this register, so the screen can't be scrolled by conventional means.  So the game switches screens in video memory immediately upon activating the lift, that does some fancy stuff to distract you from the transition.
