### ISSUE TITLE
S.T.U.N Runner Tandy glitch on title screen

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4812]
### What happened?

![Monitor_1_20240910-175836-912](https://github.com/user-attachments/assets/70e729c5-e4f5-4424-8e59-ef9bf6b2f219)
Glitch is on upper left of screen. Can be seen after selecting Tandy graphics mode
Disk File: 
[STUN Runner.zip](https://github.com/user-attachments/files/16956512/STUN.Runner.zip)

Run Stun.exe, select Tandy graphics, then proceed to see glitch

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6130
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy1000sl2
cpu_family = necv30
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 80187
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_02_turbo = 1
fdd_01_image_history_01 = disk1.img
fdd_01_image_history_02 = disk2.img
fdd_01_image_history_03 = Maniac Mansion (1988) (360K) [!].ima
fdd_01_type = 525_2qd
fdd_01_turbo = 1
fdd_01_fn = Stun Runner.IMA
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2.1

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Those are ANSI escape codes - do you have ANSI.SYS loaded?

**Comment by dbalsom** [comment]
Same appears on a real tandy.

**Comment by dbalsom** [comment]
![image](https://github.com/user-attachments/assets/f63afa2e-ff58-403c-ac9d-3290bf1c44ed)

**Comment by OBattler** [comment]
Then this is another case of NOTABUG.

**Comment by joncampbell123** [comment]
Hello. The codes shown on screen correspond exactly to the ANSI codes the game wrote to the console output.

CON log output according to DOSBox-X:

\<esc\>[s
\<esc\>[2;2f

If you didn't load ANSI.SYS, then of course the escape codes will appear as-is on the screen.
If you do load ANSI.SYS, or emulate it as DOSBox-X does, the console output will parse the ANSI codes and you won't see them on screen.
