### ISSUE TITLE
ATI Mach64 cards do not work properly in Solaris

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#4813]
### What happened?

1. When using an ATI Mach64GX video card Solaris 2.5.1 and 2.6 (when using the ATI Graphics Pro Turbo or ATI Graphics Pro Turbo 1600 driver) display unreadable text after OpenWindows starts up:
![Monitor_1_20240911-170932-995](https://github.com/user-attachments/assets/e612cb4c-b440-498d-a384-fad6be48eb5d)

2. When using an ATI Mach64VT2 video card Solaris 2.6 (when using the ATI Mach64VT driver in 256-color mode) displays nothing but a mouse cursor after OpenWindows starts up:
![Monitor_1_20240911-173641-657](https://github.com/user-attachments/assets/3a5e5cac-a5f9-4c3e-a396-c8b80e7adb2a)

When using the Mach64VT2 in 16 million color mode the behavior is the same as the Mach64GX

I also tested 86Box 4.0 build 5000 and saw the same font behavior with the Mach64GX.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
emu_build_num = 6148
uuid = a302f197-b80c-5e1b-9621-4bf01fffa4db

[Machine]
machine = p55t2p4
cpu_family = pentium_p54c
cpu_speed = 166666666
cpu_multi = 2.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
mem_size = 65536

[Video]
gfxcard = mach64gx_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[ATI Mach32 (PCI)]
ramdac = 0
memory = 2048

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = Solaris26Test.img
hdd_01_speed = 1996_5400rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 24
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_image_path = C:/Emulators/86Box/testing/Solaris26/software.iso
fdd_01_fn = C:/Emulators/86Box/testing/Solaris26/boot.img
cdrom_01_image_history_01 = C:/Emulators/86Box/testing/Solaris25/solaris-2.5.1_x86.iso
cdrom_01_type = 86BOX_CD-ROM_1.00
fdd_01_image_history_01 = C:/Emulators/86Box/testing/Solaris25/DU11BT3.img
fdd_01_image_history_02 = C:/Emulators/86Box/testing/Solaris25/DU11BT2.img
fdd_01_image_history_03 = C:/Emulators/86Box/testing/Solaris25/DU11BT1.img

[Other peripherals]
postcard_enabled = 1

[ATI Mach64GX PCI]
memory = 4

[ATI Mach64VT2]
memory = 2
```

### Operating system

Windows 7 SP1

### CPU

Intel Core i7-9700K

### 86Box version

v4.3 build 6148

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Config, NVR and HDD image: 
[86Box-SolarisTest.zip](https://github.com/user-attachments/files/16971124/86Box-SolarisTest.zip)

**Comment by TC1995** [comment]
Also post the installation files in a package.

**Comment by win2kgamer** [comment]
The Solaris 2.5.1 and 2.6 installers I used are on the FTP under /Uploads from read-only user/win2kgamer
