### ISSUE TITLE
Outrun causes 86-Box to freeze on Tandy Sl/2, works fine on the Tandy 1000 HX

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4821]
### What happened?

Load either one of the two disk images uploaded. The US variant is a later revision compared to the European one. On both, select Tandy mode, then select music. Afterwards, it will load and then causes 86-Box to freeze. Game loads fine on the Tandy 1000 HX configuration.
[Outrun.zip](https://github.com/user-attachments/files/16997905/Outrun.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6130
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy1000sl2
cpu_family = necv30
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 80187
mem_size = 768

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_02_turbo = 1
fdd_01_image_history_01 = Outrun Male.IMA
fdd_01_image_history_02 = disk1.img
fdd_01_image_history_03 = rings.IMA
fdd_01_turbo = 1
fdd_01_type = 525_2qd
fdd_01_image_history_04 = Pete Rose Cracked.IMA
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2.1

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Fenix770** [comment]
I don't know if it is related to the Tandy DAC. Old versions of DOSBox (more than 10 years ago), had the same issue. 
The HX and other "X" models have no DAC.

**Comment by eddmanx** [comment]
You guys ought to do some bisecting before opening issues.

The freezing started with build 6017.

**Comment by TC1995** [comment]
Was this actually SL2 compatible?

**Comment by Fenix770** [comment]
I think that yes, is compatible the game was launched in 1989, and have Tandy DAC support with autodetection.

**Comment by Fenix770** [comment]
It seems that the freeze happens when the game starts, and is when the car uses the DAC for the sound effects.

**Comment by Fenix770** [comment]
I found an earlier version without Tandy 3-voice or DAC support, and also the "music sound shower" have a different melody with PC speaker. This version works on Tandy 1000 SL/2 using Tandy graphics but with PC speaker of course.

Here is the image file:
[Outrun Original Version.zip](https://github.com/user-attachments/files/17004035/Outrun.Original.Version.zip)

So I suspect it something related with the DAC.
I also forced a 286/8 on the SL/2 and the issue persist.

**Comment by Froakiein2022** [comment]
I've experienced that kind of issue when emulating Tandy 1000 SL/2 on version 5.1 build 7706, except instead of 86Box freezing, the game stops working right after selecting the music; the only thing I can do was exit the game using Ctrl+X.

**Comment by NightSprinter** [comment]
Are any of you enabling joysticks at all?  Bear in mind the Tandy 1000 RL/SL/TL's DAC shares the same address as the joystick ports.

**Comment by Froakiein2022** [comment]
> Are any of you enabling joysticks at all? Bear in mind the Tandy 1000 RL/SL/TL's DAC shares the same address as the joystick ports.

I've also tested without enabling joysticks. Same result.
