### ISSUE TITLE
Bugs with Zool and Zool 2 games.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4822]
### What happened?

The game Zool 2 have no sound at all (music or sound effects) and also it is not detected (options grayed out).
The Zool game just freeze after the title screen that says "Gremling"

I tested 3 different VMs:

-a 486 DX/2 66 Mhz with Aztech Clinton
-a Pentium 66 machine with SB AWE 32
-a 386 DX/40 with SB 2.0.
All VMs have its own DOS/Windows sound drivers installed.

The games work fine on the latest release of DOSBox-X:

Here I upload the 386 DX/40 VM and the games:
[386 DX.zip](https://github.com/user-attachments/files/16999758/386.DX.zip)

Zool 1-2:
[Zool 1-2.zip](https://github.com/user-attachments/files/16999775/Zool.1-2.zip)

Note: to start Zool 2 run ZOOL2_K.EXE and use any number code then press enter.

### Configuration file

```ini
[Cirrus Logic GD5422 (ISA)]
memory = 1024

[Sound Blaster v2.0 #1]
base = 0220
mixaddr = 0000
irq = 5
dma = 1
opl = 1
cms = 1
receive_input = 0

[General]
vid_renderer = qt_software
vid_resize = 1
rctrl_is_lalt = 1
video_gl_shader = 
enable_overscan = 1
dpi_scale = 0
video_gl_framerate = 35
video_gl_vsync = 1
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 6148
uuid = d88ef1f9-0c15-53fb-bfaf-9a5c353214aa

[Machine]
machine = award495
cpu_family = am386dx
cpu_speed = 40000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = cl_gd5422_isa
show_second_monitors = 0

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sb2.0
fm_driver = nuked
mpu401_standalone = 1

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 702, 0, ide
hdd_01_fn = 
hdd_01_speed = 1992_3600rpm
hdd_01_vhd_blocksize = 4096
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_speed = 4
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_type = AZT_CDA46802I_1.15

[Cirrus Logic GD5424 (VLB)]
memory = 1024

[Roland MT-32 (New) Emulation]
output_gain = 100
reverb = 1
reverb_output_gain = 100
reversed_stereo = 0
nice_ramp = 1

[Roland MPU-IPC-T]
base = 0330
irq = 2
receive_input = 1

[Roland MT-32 Emulation]
output_gain = 100
reverb = 1
reverb_output_gain = 100
reversed_stereo = 0
nice_ramp = 1

[SuperEGA]
memory = 256
monitor_type = 9

[Realtek RTG3105 (ISA)]
memory = 512
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.3..6148

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by eddmanx** [comment]
Not a good idea to combine two different issues from two different software. I used my own machine and Zool works; set the PIT mode to Fast.

Zool 2 doesn't detect any sound though. Can't figure out if it's an 86box problem or not.
