### ISSUE TITLE
Machine frequencies for AMD K6/K6-II/K6-III are not correct always

### ISSUE THREAD

**Issue by f1nalspace** [86Box/86Box#4827]
### What happened?

A lot of CPU configurations reports the wrong CPU frequency, even though i selecting a different configuration.
For example you select an AMD K6-II with 450 MHz and you get a K6-II 375 MHz instead.
This happens for Pentium II CPU's as well. Please double check and fix the configurations, that uses the wrong processor speed. Maybe a wrong FSB or multiplier is used?

### Operating system

Windows 11 Pro

### CPU

AMD Ryzen 7950X

### 86Box version

v4.2.1 Build 6130

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
This is a CANTFIX - the reason for this is that the BIOS uses the PIT to determine the CPU speed and on the dynamic recompiler, timers only run after every block of instructions, causing the PIT to read out incorrectly. It's a long known bug that unfortunately can't be fixed.
