### ISSUE TITLE
ATI Mach64VT2 flickering between palettes on Windows 3.1x

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#4833]
### What happened?

When running Windows for Workgroups 3.11 with the ATI Mach64VT2 in a 256-color mode the display quickly cycles between two incorrect palettes:
![Monitor_1_20240915-220347-293](https://github.com/user-attachments/assets/71604b06-c838-45b5-a00d-fe4fd65c7549)
![Monitor_1_20240915-220347-439](https://github.com/user-attachments/assets/c6ba911c-5626-477c-9ddb-a79c2ba5e0ef)

The expected behavior is a stable display with a correct palette.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
emu_build_num = 6153
uuid = a302f197-b80c-5e1b-9621-4bf01fffa4db

[Machine]
machine = p54tp4xe
cpu_family = pentium_p54c
cpu_speed = 100000000
cpu_multi = 1.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
mem_size = 16384

[Video]
gfxcard = mach64vt2

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 2031, 0, ide
hdd_01_fn = VideoTestW31.img
hdd_01_speed = 1994_4500rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
fdd_01_image_history_01 = C:/Emulators/86Box/testing/CDROM_Drvs.img
cdrom_01_type = 86BOX_CD-ROM_1.00

[Other peripherals]
postcard_enabled = 1

[ATI Mach64VT2]
memory = 4
```

### Operating system

Windows 7 SP1

### CPU

Intel Core i7-9700K

### 86Box version

v4.3 build 6153

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

I performed a bisect and found that this issue started occurring in build 5211.

Config/NVR/HDD image: 
[86Box-VideoTestW31-Mach64VT2.zip](https://github.com/user-attachments/files/17008624/86Box-VideoTestW31-Mach64VT2.zip)

**Comment by TC1995** [comment]
Most likely the same bug that formerly affected the Mach64GX in terms of rendering.
