### ISSUE TITLE
Paradise PVGA1A, memory detection error and unsupported video modes

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4840]
### What happened?

I found two bugs:

1. Windows 3.0 seems to work fine with 640x480 256 colors and 800x600 16 colors, but not in 1024x768 16 colors. 
2. Both Neopaint built-in Paradise drivers and the VESA PVGA1A1B detects only 256kb RAM even with 512kb.

Note:(I checked the drivers are for this card, these drivers supports 640x480x256, 800x600x16 and 1024x768x16  
There are other drivers for the PVGA-11L that support for 800x600 256 colors and 1024x768 2 colors). 
In fact, only the 640x480x256 and 1024x768x16 uses 512kb.

Screenshot:
![PVGA1A1B](https://github.com/user-attachments/assets/ee8c2e4c-4570-4e9f-a8d6-7a1a9e749286)

VM:
[386 SX PVGA1A.zip](https://github.com/user-attachments/files/17081462/386.SX.PVGA1A.zip)

### Configuration file

```ini
[Paradise PVGA1A]
memory = 512

[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 6169
uuid = a3b06e4a-34f3-528a-84ab-019e90294c72
vid_resize = 1
rctrl_is_lalt = 1

[Machine]
machine = 325ax
cpu_family = cx486slc
cpu_speed = 20000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = pvga1a

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sbprov1
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = text_prt

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 10, 980, 0, ide
hdd_01_fn = 
hdd_01_speed = 1992_3600rpm
hdd_01_ide_channel = 0:0
hdd_01_vhd_blocksize = 1024

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_speed = 2
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_type = NEC_CD-ROM_DRIVE273_4.20
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.3.0.6169

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Yes, the chip supports those modes, but does the specific combination of chip, RAM DAC, and clock chip support them?

**Comment by Fenix770** [comment]
After doing some test:

I can confirm that 640x480 256 colors works fine with 512kb of VRAM
It supports 640x400 256 colors on Windows 2.x with only 256kb of RAM
it also supports 800x600 16 colors under Windows 3.0.
 
About Neopaint: 

It only detects the chip correctly after loading the NEOPAIN.EXE with /C2,x,512. Then it detects the card with 512kb and can do 640x480 256 colors. It, however, do not show the 102x768 16 colors, I'm not sure if the card does not support it or Neopaint does not support the mode.

The VESA1A1B (1991) and VESAX (1990) detects only 256kb of VRAM even with 512kb.

There is a screen corruption when I attempt to load Windows 3.0 with 640x480 256 colors with 256kb of VRAM, but it should refuse to start instead, since it requires 512kb.
  #897
NEOPAINT:

![Monitor_1_20240921-200014-641](https://github.com/user-attachments/assets/f59a6aba-5a50-42ea-895b-cffa2d660652)
![Monitor_1_20240921-200014-641](https://github.com/user-attachments/assets/89972b81-40c2-4842-af85-2f7ca47caba3)


Windows 3.0 640x480 256 colors with 512kb (correct) and 256kb.

Correct
![Monitor_1_20240921-193517-160](https://github.com/user-attachments/assets/0f116554-628a-496a-adf2-22ee5463a708)
 
Not correct
![Monitor_1_20240921-193935-223](https://github.com/user-attachments/assets/753c6ecb-01a9-4aac-898e-3f9908f51628)

**Comment by Fenix770** [comment]
PD: I'm not sure about the 1024x768 16 colors video mode, but the Sitech Display Doctor 5.3 have the same issue, about the VRAM; I forced the 512kb of RAM with /M512 parameter. After that, the 640x480x256 also works, but there is no 1024x768 mode on the 4 bit (16 color mode). So maybe this BIOS not supports that video mode, but the software should, at least, detect the 512kb VRAM  size

**Comment by OBattler** [comment]
This is the information I just found on the VGA Museum:
> Prices: Paradise VGA Plus 16 (256kB) - $499, Paradise VGA Professional (512kB) - $799.
So what we need is a BIOS of the professional version that came with 512 kB.

**Comment by OBattler** [comment]
Can you upload that 16TEST.EXE somewhere?

**Comment by Fenix770** [comment]
Here are the drivers 
[Paradise Win 2.zip](https://github.com/user-attachments/files/17088191/Paradise.Win.2.zip)

Looks like the 1024x768x16 mode is for the "1B" card, since these drivers includes video modes up to 800x600.
The Win 3.0 drivers I found works fine with the "1A" card with 640x480x256 and 800x600x16
