### ISSUE TITLE
ATI Mach32 not working on NeXTSTEP 3.1

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#4845]
### What happened?

When running NeXTSTEP 3.1 with a Mach32 card and the ATI Ultra Pro driver selected the OS will switch display modes but will not display the desktop (only displaying the last console messages in the upper-left of the screen):
![Monitor_1_20240921-175859-061](https://github.com/user-attachments/assets/1219e74d-7d92-42dc-8091-0d314512a7f8)

I performed a bisect and found that this behavior started in build 5770.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
emu_build_num = 6173
uuid = a302f197-b80c-5e1b-9621-4bf01fffa4db

[Machine]
machine = 4saw2
cpu_family = idx4
cpu_speed = 100000000
cpu_multi = 3
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
mem_size = 12288

[Video]
gfxcard = mach32_vlb

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load
scsicard_1 = aha154xc

[ATI Mach32 (VLB)]
memory = 2048

[Adaptec AHA-154xC #1]
base = 0330
irq = 11
dma = 5
bios_addr = C8000

[Hard disks]
hdd_01_parameters = 63, 16, 1024, 0, scsi
hdd_01_scsi_location = 0:00
hdd_01_fn = NS31Test.img
hdd_01_speed = 1994_4500rpm

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_parameters = 1, scsi
cdrom_01_scsi_location = 0:01
cdrom_01_type = 86BOX_CD-ROM_1.00
cdrom_01_image_history_01 = C:/Emulators/86Box/testing/NextStep31/ns31_i386_install.iso

[Other peripherals]
postcard_enabled = 1
```

### Operating system

Windows 7 SP1

### CPU

Intel Core i7-9700K

### 86Box version

v4.3 build 6173

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Config, NVR and HDD image are on the FTP (86Box-NS31Test.zip under /Uploads from read-only user/win2kgamer)

**Comment by TC1995** [comment]
Try running the eeprom first.

**Comment by win2kgamer** [comment]
I did run the EEPROM config before but just tried running it again and tried it with the memory aperture disabled (had it enabled before) with no change.

**Comment by TC1995** [comment]
Did it show the proper display before 5770?

**Comment by win2kgamer** [comment]
Build 5769 did show the proper display:
![Monitor_1_20240921-200413-896](https://github.com/user-attachments/assets/77d6f1ea-d7aa-4aeb-b057-28d3e7a1166e)
