### ISSUE TITLE
Jungle Hunt Freezing on Title Screen with Tandy 1000 SX

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4856]
### What happened?

Per https://forum.vcfed.org/index.php?threads/gaming-on-the-tandy-1000-sx.16947/ game should be playable albeit with the wrong palette. However, on 86box, when pressing F1 key to proceed from the title screen, game freezes.

Game from https://archive.org/details/20240818_20240818_0632 using 86F file

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6187
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_02_turbo = 1
fdd_01_image_history_01 = 8088mph.360
fdd_01_image_history_02 = Outrun (US, Female Voice).IMA
fdd_01_image_history_03 = Impossible Mission II (1989) (360K) (Disk 2) [!].ima
fdd_01_fn = Jungle Hunt (1984) (160K) (Booter) [cp] [!].86f

[DTK PII-158B (MiniMicro4) Floppy Drive Controller]
bios_addr = CE000

[S3 Trio3D/2X (362) AGP]
memory = 8
bilinear = 1
dithering = 1
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.3.0 6187

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by ualaa1** [comment]
As of build 6192, game now works when using CGA on 8088 machines other than Tandy but still freezes on Tandy when testing with a Tandy 1000 SX

**Comment by OBattler** [comment]
More like, the freeze on Tandy has been reintroduced. Let me see why.

**Comment by OBattler** [comment]
Fix committed.
