### ISSUE TITLE
Preferences box UI problems

### ISSUE THREAD

**Issue by jernejs** [86Box/86Box#4860]
### What happened?

In high DPI mode, the Mouse sensitivity slider is too thin:
![image](https://github.com/user-attachments/assets/223cf7ea-9d70-4776-b452-e86823b3d536)

Additionally, tab order seems completely random (the Settings dialog has the same problem).

### Configuration file

```ini
# N/A
```

### Operating system

Windows 11

### CPU

AMD Ryzen 9 5900X

### 86Box version

4.2.1 build 6130

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
This is a known bug, I can try to make the slider a bit bigger but no promises.
