### ISSUE TITLE
Digger Remastered - Freeze when running on Tandy 1000 SX and HX

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4863]
### What happened?

This is a hack of the game called Digger that adds various features including VGA mode. In order to set CGA mode, digger /c needs to be ran as running digger.exe by itself defaults to VGA mode. Right now, I have tested the booter image on the IBM XT using CGA graphics card and it works fine running the above command, but when testing on a Tandy 1000 SX with the booter image and the Tandy 1000 HX with both the booter image and non booter image, it causes the system to freeze.
Two disk images of the hack are attached, one is a MS Dos booter version and another is the non booter version, for use on the Tandy 1000 HX
The booter defaults to msdos, so you will need to load digger /c after entering DOS

The original unhacked game works perfectly fine on Tandy 1000 (all machines) using CGA mode as neither game nor hack support Tandy graphics

[Digger Remastered Images.zip](https://github.com/user-attachments/files/17159561/Digger.Remastered.Images.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6193
uuid = b3013b68-9fce-5b63-b7f2-0ea9a0dcc618

[Machine]
machine = tandy
cpu_family = necv20
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 8087
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_image_history_01 = digger.IMA
fdd_01_fn = MSDOS330+digger.img

[IBM CGA]
display_type = 0
composite_type = 0
rgb_type = 5
double_type = 1
snow_enabled = 1
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.3.0 6193

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
NOTABUG:
> [20:11]gloriouscow: i actually know about that.  reenigne looked at it, there's a bug.  it initializes vga mode before it checks the command line arguments , then switches to CGA
> [20:11]gloriouscow: this likely makes tandy unhappy

As such, this can be closed.
