### ISSUE TITLE
Cirrus CL-GD5436/46/80 displays some fonts incorrectly in Solaris 2.6

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#4868]
### What happened?

When running Solaris 2.6 using a Cirrus Logic CL-GD5436/5446/5480 OpenWindows will render some fonts incorrectly (titlebar, console window) while other fonts render fine (kdmconfig test screen, main installer window.)
![Monitor_1_20240928-164830-718](https://github.com/user-attachments/assets/39a359e9-73be-41d8-8fb9-7106fc105bd5)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
emu_build_num = 6199
uuid = a302f197-b80c-5e1b-9621-4bf01fffa4db

[Machine]
machine = p55t2p4
cpu_family = pentium_p54c
cpu_speed = 166666666
cpu_multi = 2.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
mem_size = 65536

[Video]
gfxcard = cl_gd5480_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Cirrus Logic GD5436 (PCI)]
memory = 4

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = Solaris26Testing.img
hdd_01_speed = 1996_5400rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 16
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_image_path = C:/Emulators/86Box/testing/Solaris26/software.iso
fdd_01_fn = C:/Emulators/86Box/testing/Solaris26/boot.img
cdrom_01_type = 86BOX_CD-ROM_1.00

[Other peripherals]
postcard_enabled = 1

[Cirrus Logic GD5446 (PCI)]
memory = 4

[Cirrus Logic GD5480 (PCI)]
memory = 4
```

### Operating system

Windows 7 SP1

### CPU

Intel Core i7-9700K

### 86Box version

v4.2.2 build 6199

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

I also tested 86Box 4.0 build 5000 and saw the same font rendering behavior.

Config, NVR and HDD image: 
[Cirrus54x6SolarisTest.zip](https://github.com/user-attachments/files/17176737/Cirrus54x6SolarisTest.zip)

The Solaris 2.6 install media I used is on the FTP under /Uploads from read-only user/win2kgamer

**Comment by TC1995** [comment]
Hmm, does it happen before 5000?

**Comment by win2kgamer** [comment]
Just tested several builds between 4317 and 5000: 4317-4400 display a blank screen while 4500-4761 have the same font rendering issue as 4.0 build 5000 and later

**Comment by win2kgamer** [comment]
The black screen in older builds was actually PS/2 mouse-related. Retested 4317 with a serial mouse and see the same font issue.
