### ISSUE TITLE
Speed/performance accuracy

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#487]
I have a real 486dx266, side to side to an emulated 486dx2 (sharing files thru the network, thats great).
But I found that the emulated 486 is always faster than the real one. Same memory amount (32 Mb), same video card (GD-5429), VLB IDE adapter, a Compact Flash as IDE drive in the real 486.

I made some tests with various test tools like PCTOOLS, SYSINFO and Checkit.

Checkit always report a superior cpu (40mhz vs 33mhz in config, 33 for 25, 100 for 66), and report an higher performance index also (about 20% too high).

HD Throughput is also a little bit too high, but it's OK in 486/VLB mode (2,2Mb/s vs 1.9 on real hardware). It's far higher in 386 mode (report 1Mb/s with an ISA IDE board, vs less than 500kb/s in real).
Even with a PC XTIDE emulation, HD troughput is far too high.

**Comment by ppgrainbow** [comment]
I also found that Snooper v3.44 reports the emulated 66 MHz 486DX2 at 75 MHz...so something doesn't appear to be 100% correct:

![20191205-230202-555](https://user-images.githubusercontent.com/32658796/70281729-9d3cb980-1770-11ea-818c-1dfe913bfbc4.png)

Do you have any screenshots of what the bugs regarding the speed and performance accuracy of these system diagnostics utilities look like?

**Comment by OBattler** [comment]
The emulated 286+ CPU's are only kind of sort of approximately cycle-accurate, so this kind of difference is to be effective, and should get even worse on 486 or Pentium with the recompiler enabled.

Right now, the only emulated CPU's that approaches any sort of real cycle accuracy, are the 8088 and 8086, and even those still have their issues (there's some simplifications done, and DMA refresh is heavily inaccurate).

**Comment by OBattler** [comment]
I will also add that we do not emulate chipset latencies at all, so it's always going to be faster than the real thing. As such, this is a CANTFIX.
