### ISSUE TITLE
INMOS XGA still have issues

### ISSUE THREAD

**Issue by WNT50** [86Box/86Box#4879]
### What happened?

The generic ISA XGA adapter causes machine to hang at startup, and INMOS XGA adapter causes machines with MR BIOS to display message "Adapter ROM checksum failure at Address 0C8000H" which is the adapter's MMIO address.

![Monitor_1_20241004-231536-150](https://github.com/user-attachments/assets/68643bc2-41b8-4132-a4b7-a13fab33df1a)

### Configuration file

```ini
[Microsoft Serial Mouse]
port = 0
buttons = 2

[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 7 5800H with Radeon Graphics         
uuid = caf5d46d-be56-59ea-99b7-1ef57ddc156f
force_43 = 1
language = system
emu_build_num = 6208

[Machine]
machine = mr495
cpu_family = i486dx2
cpu_speed = 66666666
cpu_multi = 2
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 8192

[Video]
gfxcard = inmos_xga_isa

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = sb16

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Storage controllers]
hdc = ide_vlb
cassette_mode = load

[Hard disks]
hdd_01_parameters = 26, 8, 776, 0, ide
hdd_01_fn = os2.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_02_type = none

[INMOS XGA (ISA)]
type = 1
instance = 6
ext_mem_addr = 0040
dma = 7

[XGA (ISA)]
type = 1
instance = 6
ext_mem_addr = 0040
dma = 7
```

### Operating system

Windows 11

### CPU

AMD Ryzen 7 5800H

### 86Box version

v4.3 build 6208

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
1. It doesn't have hang the machine, you need to wait a while for it to initialize.
2. Does it happen with other memory addresses?

**Comment by WNT50** [comment]
This happens on both 4 memory address after testing.

**Comment by TC1995** [comment]
I don't know about the INMOS XGA one, I'm afraid, might be an issue with MR BIOSes, I need real hardware to be fully sure.

**Comment by WNT50** [comment]
Maybe something is incorrectly mapped into C8000H? I use debug and find this:
![Monitor_1_20241004-235257-134](https://github.com/user-attachments/assets/590796c6-7594-4064-88f6-f6e915b984fe)

**Comment by TC1995** [comment]
Both are mapped correctly.

**Comment by WNT50** [comment]
I don't think this is the right mapping, as I found this in the INMOS G201 manual:
![Screenshot 2024-10-05 003756](https://github.com/user-attachments/assets/d41a8e7c-5b4a-4846-aae2-f4b45f7e823b)
![Screenshot 2024-10-05 003553](https://github.com/user-attachments/assets/7bc5ae20-1679-4841-b463-2129fcdbe64e)

**Comment by borisvolk117** [comment]
I use the AMI version of this machine, finding it works normally without ROM checksum failure.

**Comment by OBattler** [comment]
This should be fixed now.
