### ISSUE TITLE
XGA-2 800x600 video mode issues

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4882]
### What happened?

Under Windows 3.1, and using XGA 2.12 drivers on IBM PS/2 with MCA XGA-2 drivers, the 800x600 video modes does not work.
However, the 640x480 both 256-color and 64kb works fine and the 1024x768 works fine too.

The Neopaint software detects the cards as an XGA-1, (only the 640x480 and 1024x768 256 colors are detected.

A corrupted screen on Windows 3.1 can be seen if I select the 800x600 64k video mode. 
If I select the 800x600 256 colors, it loads the 1024x768 mode instead.

Corrupted 800x600 64kb screenunder Windows 3.1:
![Monitor_1_20241005-092027-787](https://github.com/user-attachments/assets/2a9b957c-5197-48ac-877f-dc3153d26f6d)

VM:
[IBM PS-2 Model 70 XGA-2 10-24.zip](https://github.com/user-attachments/files/17266515/IBM.PS-2.Model.70.XGA-2.10-24.zip)

There are two VESA drivers on C:\VESA directory SVGAVESA.COM and XGAVESA.COM. if I load these NEOPAINT dtectes the card correctly as XGA-2 but only a corrupted screen can be seen on the 800x600 64kb video mode.

### Configuration file

```ini
[XGA (MCA)]
type = 1

[Sound Blaster Pro MCV #1]
receive_input = 1

[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
emu_build_num = 6208
uuid = 8a5c8816-8ed9-5f10-9307-622524e6138d
vid_resize = 1

[Machine]
machine = ibmps2_m80
cpu_family = i386dx
cpu_speed = 20000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu_waitstates = 6
pit_mode = 0
mem_size = 4096

[Video]
gfxcard = internal
xga = 1

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sbpromcv
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Storage controllers]
hdc = esdi_mca
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, esdi
hdd_01_esdi_channel = 0
hdd_01_fn = 
hdd_01_speed = ramdisk
hdd_01_vhd_blocksize = 4096

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.2.2.6208

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
Probably a fault in the XGA-2 MCA BIOS.

**Comment by Fenix770** [comment]
Update: the 800x600 video mode issue happens on both INMOS XGA/2 and MCA XGA/2 on PS/2 models 70 and 80.
Either, both cards use the same BIOS or there is a bug in the IBM XGA drivers for Windows 3.x. 
But I tested 2.10 and 2.12 versions of the drivers.
However, the 800x600 256 colors mode works fine on INMOS XGA/2 under Windows 95. The 800x600 64kb is not listed, so maybe is not supported.

Screenshot:
![Monitor_1_20241012-190255-280](https://github.com/user-attachments/assets/8fb14b3f-4931-41fe-8065-1dd52127b8a0)

**Comment by TC1995** [comment]
The INMOS XGA and IBM XGA-2 don't use the same bios.

**Comment by OBattler** [comment]
The 800x600x64bpp corruption is due to it also going into 1024x768 but wrapping the video memory around somewhere.
