### ISSUE TITLE
ATI Mach32 renders fonts incorrectly in XFree86 2.x

### ISSUE THREAD

**Issue by win2kgamer** [86Box/86Box#4888]
### What happened?

When running XFree86 2.x (using the XF86_Mach32 server) on a Mach32 none of the fonts render correctly:
![Monitor_1_20241006-121428-193](https://github.com/user-attachments/assets/e852dc8e-1854-48e9-bf9b-21e00fb35805)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
emu_build_num = 6208
uuid = a302f197-b80c-5e1b-9621-4bf01fffa4db

[Machine]
machine = 4saw2
cpu_family = idx4
cpu_speed = 100000000
cpu_multi = 3
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
mem_size = 12288

[Video]
gfxcard = mach32_vlb

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load
scsicard_1 = aha154xc

[ATI Mach32 (VLB)]
memory = 2048

[Adaptec AHA-154xC #1]
base = 0330
irq = 11
dma = 5
bios_addr = C8000

[Hard disks]
hdd_01_parameters = 63, 16, 1024, 0, scsi
hdd_01_scsi_location = 0:00
hdd_01_fn = Mach32LinuxTest.img
hdd_01_speed = 1994_4500rpm

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_type = 86BOX_CD-ROM_1.00
cdrom_01_parameters = 1, scsi
cdrom_01_scsi_location = 0:02
cdrom_01_image_path = C:/Emulators/86Box/testing/Slack20/slackware20_1.iso

[Other peripherals]
postcard_enabled = 1
```

### Operating system

Windows 7 SP1

### CPU

Intel Core i7-9700K

### 86Box version

v4.2.2 build 6208

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

I tested builds back to 4711 (the build that added the Mach32) and see the same behavior. I have run the EEPROM config.

Config, NVR and HDD image are on the FTP in 86Box-testing-Mach32XFree86v211.zip under /Uploads from read-only user/win2kgamer

**Comment by TC1995** [comment]
Could you also upload the install media of this distro? (on the FTP)

**Comment by win2kgamer** [comment]
I have uploaded the Slackware 2.0.1 install media I used to the Slackware_2.0 directory under /Uploads from read-only user/win2kgamer.
