### ISSUE TITLE
More INMOS XGA bugs

### ISSUE THREAD

**Issue by WNT50** [86Box/86Box#4890]
### What happened?

INMOS XGA emulation is broken again in build 6209 in Windows 3.1, while generic ISA XGA adapter works fine (although initialization takes more than 2 minutes).
![Monitor_1_20241008-124943-223](https://github.com/user-attachments/assets/fbf9e896-d9fc-47d0-be17-b255de46d501)

### Configuration file

```ini
[INMOS XGA (ISA)]
type = 1
dma = 7

[Microsoft Serial Mouse]
port = 0
buttons = 2

[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 7 5800H with Radeon Graphics         
uuid = caf5d46d-be56-59ea-99b7-1ef57ddc156f
force_43 = 1
language = system

[Machine]
machine = acc386
cpu_family = i386dx
cpu_speed = 40000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 8192

[Video]
gfxcard = inmos_xga_isa

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Storage controllers]
hdc = st506_at
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 7, 855, 0, mfm
hdd_01_fn = disk.img
hdd_01_mfm_channel = 0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_02_type = 525_2hd
fdd_02_turbo = 1
```

### Operating system

Windows 11

### CPU

AMD Ryzen 7 5800H

### 86Box version

v4.3 build 6209

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Use disk image uploaded in #4870

**Comment by Fenix770** [comment]
Hello!
Which resolution are you using?. The XGA-1 video modes seems to work fine. I have issues with XGA-2 modes. 
(800x600 256 and 64k) 640x480 64k seems to work fine under Windows 3.1, but it has distorted colors under Win 3.0.
On Neopaint 3.2d works fine except when I try to exit to DOS or change the video resolution, on that situation it freezes the VM

**Comment by TC1995** [comment]
You most likely need to disable video bios shadowing in cmos.

**Comment by OBattler** [comment]
This is NOTABUG - disables shadow RAM because the XGA BIOS is writable (has MMIO in the BIOS area).
