### ISSUE TITLE
Windows 95 can't read floppy disk first time

### ISSUE THREAD

**Issue by mcihelka** [86Box/86Box#4891]
### What happened?

**The bug**

Windows 95 (OSR1) can't read a floppy disk the first time you insert it. After failure, ejecting and re-inserting the disk makes it work.

Probably similar/same issue as #3427 but in my case dynamic recompiler is *disabled*.

**Steps to reproduce**

1. Start Windows
2. Insert floppy disk
3. Try to access floppy disk
4. After long delay Windows pops up an error dialog box
5. Eject the disk, then re-insert
6. Again try to access floppy disk
7. Now floppy disk can be accessed just fine

Note: The issue exists on all 4.x builds of 86Box that I have tried. I didn't try any 3.x builds.

**Expected behavior**

Floppy disk should be accessible without error on first insert.

**Emulated machine**

- Soyo 4SAW2
- Intel iDX4 @ 100 MHz
- 64 MB RAM
- 1.44M floppy drive, correctly configured in machine's BIOS setup
- Dynamic Recompiler: Disabled
- PIT mode: Slow

Note: The issue also exists on other 486 motherboards and various RAM/video/storage configurations. Changing PIT mode makes no difference. I can't seem to find a suitable 486 configuration that fixes the issue.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = 12th Gen Intel(R) Core(TM) i7-12700
emu_build_num = 6208
uuid = 012e486f-3643-52e4-877e-0de8d490ea74
dpi_scale = 0
vid_resize = 2
window_fixed_res = 1600x1200

[Machine]
machine = 4saw2
cpu_family = idx4
cpu_speed = 100000000
cpu_multi = 3
cpu_use_dynarec = 0
fpu_softfloat = 1
time_sync = local
fpu_type = internal
pit_mode = 0
mem_size = 65536

[Video]
gfxcard = stealth64v_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sb16
midi_device = system_midi
midi_in_device = midi_in

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[S3 Vision964 PCI (Diamond Stealth64 VRAM)]
memory = 4

[Standard PS/2 Mouse]
buttons = 2

[Sound Blaster 16 #1]
base = 0220
base401 = 0330
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[System MIDI]
midi = 0

[MIDI Input Device]
midi_input = 0
realtime = 0
thruchan = 0
clockout = 0

[Ports (COM & LPT)]
lpt1_device = postscript

[Hard disks]
hdd_01_parameters = 63, 16, 4092, 0, ide
hdd_01_fn = hdd_c.img
hdd_01_speed = ramdisk
hdd_02_parameters = 63, 16, 4092, 0, ide
hdd_02_fn = hdd_d.img
hdd_02_speed = ramdisk
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_type = 86BOX_CD-ROM_1.00
fdd_01_fn = X:/Workshop/LPC Workbench/NOARUN.img

[Other removable devices]
zip_01_parameters = 1, atapi
zip_01_ide_channel = 1:1
```

### Operating system

Windows 11

### CPU

Intel i7-12700

### 86Box version

4.2.2 Build 6208

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
This is a known bug and a CANTFIX right now.

**Comment by OBattler** [comment]
Actually, this was FDC resetting the change line on controller reset, which was known bug, indeed, but actually fixable, and has since been fixed.
