### ISSUE TITLE
Keyboard not in pheripherals

### ISSUE THREAD

**Issue by Bubulledu34** [86Box/86Box#4892]
### What happened?

Hello ! I'm not used to programming but I tried installing an old game and running it on 86box, and it works but I just don't have access to the keyboard. When i try to capture it nothing happens, and it doesn't appear in the list of my peripherals.. I don't know what to do to fix the issue :(

### Configuration file

```ini
﻿[WinBox]
window_fixed_res = 960x720

[General]
dpi_scale = 0
vid_resize = 2
window_fixed_res = 960x720
iconset = winbox
vid_renderer = qt_software
confirm_reset = 0
video_fullscreen_first = 0
language = fr-FR
hide_status_bar = 1
confirm_exit = 0
window_remember = 1
kbd_req_capture = 1
mouse_sensitivity = 0.69

[Cirrus Logic GD5434 (ISA)]
memory = 4

[Microsoft Serial Mouse]
port = 0
buttons = 2

[Machine]
machine = 430vx
cpu_family = pentium_p54c
cpu_speed = 120000000
cpu_multi = 2
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 1
time_sync = local
cpu = 5
mem_size = 32768

[Video]
gfxcard = stealth3d_2000_pci
voodoo = 1

[Input devices]
mouse_type = msserial
joystick_type = 4axis_4button
joystick_0_nr = 1
joystick_0_axis_0 = 1
joystick_0_axis_1 = 0
joystick_0_axis_2 = 4
joystick_0_axis_3 = 0
joystick_0_button_0 = 0
joystick_0_button_1 = 1
joystick_0_button_2 = 2
joystick_0_button_3 = 3

[Sound]
sndcard = sb16
fm_driver = nuked

[Storage controllers]
hdc = ide_pci

[Hard disks]
hdd_01_parameters = 63, 16, 1054, 0, ide
hdd_01_fn = C.img
hdd_01_speed = 2000_7200rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 24
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = ./Alice.cue
cdrom_01_type = MITSUMI_CRMC-FX4820T_D02A

[3DFX Voodoo Graphics]
type = 0
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[Monitor #1]
window_coordinates = 109, 149, 960, 720

[Monitor #2]
window_coordinates = 0, 0, 0, 0
```

### Operating system

Ubuntu 18.04.6 LTS

### CPU

Intel Core i5-8250U

### 86Box version

v4.0

### Build architecture

Linux - ARM (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

I got 86Box from a third party repository (please tell us where)

### Additional context

I got 86box from the website Abandonware where you can download old games, and it installed the game already mounted in 86box.

**Comment by jriwanek** [comment]
Get 86box from the official download link (https://github.com/86Box/86Box/releases/tag/v4.2.1), update to latest roms (https://github.com/86Box/roms/releases/tag/v4.2.1).

You're clearly not using the Linux ARM 32 build, considering your stated CPU, so in future please fill out the form correctly.

**Comment by OBattler** [comment]
Closing this  we do not support third party releases.

**Comment by Bubulledu34** [comment]
I'm sorry as I said I'm not used to programming I don't even know what half of this means. I tried copy-pasting what I could find but didn't know where to find the build so I kept Linux ARM 32 as it was the default option.
Sorry for the inconvenience
