### ISSUE TITLE
[BUG] Sound popping/crackling issues; Direct Access: CPU drops to 80% on menu selection display

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#491]
Okay, first of all, is anyone experiencing some sound popping issues after playing a game that uses the sound card such as the Sound Blaster 16?

For me, off and on I'm starting to experience issues having to deal with sound popping and crackling after playing a game that utilises the use of the Sound Blaster 16 card under DOS 5.0a?

The pops and crackles of sound usually gets annoying enough that I have to close the 86Box window and restart the emulator.

Has any tested this issue on both emulated and on real hardware though?

My latest 86Box.cfg file can be found on Pastebin: https://pastebin.com/bKxc87Ce

Also, if you're using a MS-DOS menuing utility such as Fifth Generation Systems Direct Access, you'll notice that the speed of the emulated CPU drops to as low at 60%, but no higher than 80% for a 80486-based CPU faster than 33 MHz.

Here's a screenshot of what the emulator looks like with the reduction of the CPU speed:

![CPU speed](https://user-images.githubusercontent.com/32658796/70301655-d5afb800-17af-11ea-8435-4abbf04cc314.png)

Would it be possible to introduce frame skipping that could improve the emulated CPU speed and/or having a option to set the fixed emulated CPU speed in order to try to utilitise more of the host CPU power?

Thank you for your time. ^^

**Comment by ppgrainbow** [comment]
By the way, from now one, I'll be filing a single bug report for each issue in the foreseeable future rather than filing multiple bug reports in a single post.

**Comment by OBattler** [comment]
This is not a bug, I think it just hits a weak spot in the emulator.
