### ISSUE TITLE
86Box crashes due to MirillisActionVulkanLayer.dll

### ISSUE THREAD

**Issue by jester-xbmc** [86Box/86Box#4915]
### What happened?

It seems that 86Box crashes when the Action! screencapture software is installed.

Below the windows log:

Faulting application name: 86Box.exe, version: 4.2.1.6130, time stamp: 0x66d473dd
Faulting module name: MirillisActionVulkanLayer.dll, version: 0.0.0.0, time stamp: 0x65c372fb
Exception code: 0xc0000005
Fault offset: 0x0001db3e
Faulting process id: 0x1950
Faulting application start time: 0x01db279761fd6443
Faulting application path: \86box\86Box.exe
Faulting module path: C:\Program Files (x86)\Mirillis\Action!\vulkan_x86\MirillisActionVulkanLayer.dll

What is confusion to me, (but I'm not a Vulkan dev person) is why on a portable 86box install the above .dll comes into play ? 
Looking at the windows crash report it seems that MirillisActionVulkanLayer.dll is loaded as a module

I can fix it by removing the app, however it would be good if both can co-exist.

### Configuration file

```ini
no impact, can be any config file, even without one
```

### Operating system

Windows 10

### CPU

Intel

### 86Box version

4.2.1 or latest from main

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
NOTOURBUG. The screen capture application is simply buggy - Googling reveals it has problems with quite a few AAA games as well.

**Comment by jester-xbmc** [comment]
> NOTOURBUG. The screen capture application is simply buggy - Googling reveals it has problems with quite a few AAA games as well.

I appreciate that its "not our bug" however my question however remains, it seems 86Box uses (or tries to) use this file, if I rename just the .dll file 86Box starts fine, so is this due to a path statement being read by 86box ? if so, can this be stopped so 86box doesn't care if this is installed or not ?

**Comment by lemondrops** [comment]
> so is this due to a path statement being read by 86box ?
Yes, it's how Vulkan implicit layers work.

> can this be stopped so 86box doesn't care if this is installed or not ?
Other than uninstalling the affected software, I don't know of such a method.

**Comment by OBattler** [comment]
Vulkan is calling that .dll, we do not control that in any way.
