### ISSUE TITLE
Unable to set speed (RPM) on MFM drives

### ISSUE THREAD

**Issue by jester-xbmc** [86Box/86Box#4916]
### What happened?

While duplicating my real hardware as close as possible I wanted to add an MFM drive (trying to emulate a Miniscribe MFM drive on an Olivetti M240) I noticed that one can only select Ram disk as the speed, and not RPM, in my case 3600 RPM, like you can for IDE, manually adding the speed line into the cfg line doesn't work either, was this by design ?

It would be nice to be able to emulate the correct speed for MFM drives.

![image](https://github.com/user-attachments/assets/419aed33-63a8-4de2-b6f1-f798a751d0cc)

### Configuration file

```ini
not linked
```

### Operating system

WIndows 10

### CPU

Intel

### 86Box version

4.2.1 or latest from main

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
NOTABUG, RPM selection is not yet implemented for those old drives.
