### ISSUE TITLE
Revoked/Expired Certificate

### ISSUE THREAD

**Issue by GoldFirey124YT** [86Box/86Box#4935]
### What happened?

When Starting X86Box im greeted with
![Screenshot 2024-11-02 162604](https://github.com/user-attachments/assets/5f91f4e9-2b4f-43bc-8a72-35cf569f92c4)

### Configuration file

```ini
no config
```

### Operating system

Windows 11

### CPU

Intel 6th gen Core i5

### 86Box version

4.2.1

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Yes, I accidentally messed up and the wrong certificate. 4.2.2 is going to rectify that.
