### ISSUE TITLE
Incorrect translation in some list entries (German)

### ISSUE THREAD

**Issue by Pellzi** [86Box/86Box#4948]
### What happened?

Incorrect translation in some list entries (German)

![Falsche Übersetzung-5](https://github.com/user-attachments/assets/04fbccef-94f0-4389-b533-d2702742b3ea)
![Falsche Übersetzung-1](https://github.com/user-attachments/assets/7ab647ba-09d2-4dcd-81cb-4c5c024f1095)
![Falsche Übersetzung-2](https://github.com/user-attachments/assets/08f857fb-4464-4757-abdb-c55cd3b20c28)
![Falsche Übersetzung-3](https://github.com/user-attachments/assets/f6c42898-8e71-4876-a596-1d114bf4f3d3)
![Falsche Übersetzung-4](https://github.com/user-attachments/assets/781e486d-4945-4ad4-9b09-935a6389c524)

### Configuration file

```ini
Not necessary, this “bug” is a translation error into the German language.
```

### Operating system

Windows 10

### CPU

Intel i7-3770K @ 3,5 GHz

### 86Box version

4.2.2 [6247]

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [X] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

This “bug” is a translation error into the German language.

**Comment by OBattler** [comment]
Why not submit a correction then? The translation files are the .po files inside the QT directory and they are plaintext, so easy to edit.

**Comment by Pellzi** [comment]
Why not submit a correction?
1- Until i found this .po File in the Source, it takes hours before i found this file. I don´t know the exact Source Code.
And this, because i read what i open. Normaly, i learned, has such files the ending .lng . But no file in the Source Code has such a ending.
With this short expanation, where to find this File, it tooks seconds for me to find it.
But i haven´t found this explanation somewhere on this side.

2- I registered me on Git Hub only, not because i want to publish my own programs. I can´t do programming work.
But there are no other solution on Git Hub then to register, if i want to add a comment.

3-  i am very New on Git Hub, and don´t know that i have to do?
There is no Button with the Name "Pull, to first control Addon to Project".
Which is first controlled by You, and after this, you add it to the Project?
I do not have push accessory to the project, and i don´t want such a privileg. 

4- In wich category should i post a from me corrected file for the Project?
This file will not be a bug report, not a request, and also not fits any categorie in the discussion tab.

**Comment by OBattler** [comment]
You can just post the .po file here, and I'm going to commit it to the repository.

**Comment by Pellzi** [comment]
I have edited the readme.md File, to implement the Documentation of the Language Files, and added more description, .
Feel free to edit like you want.
 
[README.md](https://github.com/user-attachments/files/17681026/README.md)

**Comment by Pellzi** [comment]
The from me edited German translation File for 86Box (German)
Feel free to edit it, like you want.

[de-DE.po.zip](https://github.com/user-attachments/files/17681791/de-DE.po.zip)

**Comment by darkstar** [comment]
"Strecken-Modus im Vollbildmodus"? really? Nobody in Germany will understand what "Strecken-Modus" is supposed to be.

If you're unhappy with "Stretch-Modus" because it's "Denglish", rewrite the entire sentence to make sense. Like "Anzeige im Vollbildmodus auf Monitor strecken" or similar

**Comment by darkstar** [comment]
I took the time and went through the patch and gave somespecific comments. Luckily I don't (have to) run the program in German because, honestly, it is a mess. Sometimes, simple terms are translated badly just to have something in German ("Verschachtelung" for "Interlace"), sometimes the grammar is plain wrong, and sometimes the english word is kept even though valid German words exist ("passthrough"->"Durchreichung", "durchreichen"). Oh and there are even texts in some eastern european language in there that were not translated at all (or just copy/pasted form somewhere else), and some letters have accents on them that don't exist in German.

**Comment by Pellzi** [comment]
Please correct the de-DE.po like you want, and post it here again.
By the Way, i, am a Swiss, and there, the writing of some German words differences to the original German. In Switzerland we never use the Character ß. I forgotten this, and i will excuse me.
"Anzeige im Vollbildmodus auf Monitor strecken" is really the better translation, than i does it.  
I have nowhere found a entry, to discus the best German translation for the Program.
Is this here the right place to do it?

Because, when i search Stretch Modus in the German Google, the answer is:
https://www.ibm.com/docs/de/storage-ceph/6?topic=storage-stretch-mode

Zum Konfigurieren von Streckclustern müssen Sie den Streckmodus aktivieren. Wenn der Stretch-Modus aktiviert ist, nehmen die Ceph-OSDs nur PGs als aktiv an, wenn sie über mehrere Data Centers oder einen anderen von Ihnen angegebenen CRUSH-Bucket-Typ als aktiv betrachtet werden, vorausgesetzt, beide sind aktiv. Die Größe von Pools wird von drei auf vier erhöht, wobei an jedem Standort zwei Kopien vorhanden sind.

Im Stretch-Modus dürfen Ceph-OSDs nur Verbindungen zu Monitoren innerhalb desselben Rechenzentrums herstellen. Neue Monitore dürfen ohne angegebene Position nicht in den Cluster aufgenommen werden.

Wenn auf alle OSDs und Monitore aus einem Rechenzentrum gleichzeitig nicht mehr zugegriffen werden kann, wird das noch aktive Rechenzentrum in den degraded -Dehnungsmodus versetzt. Dies gibt eine Warnung aus, reduziert die min_size auf 1und ermöglicht es dem Cluster, einen active -Status mit den Daten des verbleibenden Standorts zu erreichen.

Hinweis: Der Status degraded löst auch Warnungen aus, dass die Pools zu klein sind, da sich die Poolgröße nicht ändert. Ein spezielles Stretchmodusflag verhindert jedoch, dass die OSDs zusätzliche Kopien im verbleibenden Rechenzentrum erstellen, sodass es immer noch 2 Kopien aufbewahrt.
Wenn das fehlende Rechenzentrum wieder zugänglich wird, wechselt der Cluster in den recovery -Dehnungsmodus. Dies ändert die Warnung und lässt Peering zu, erfordert aber immer noch nur die OSDs aus dem Rechenzentrum, die die ganze Zeit aktiv waren.

Wenn sich alle PGs in einem bekannten Status befinden und nicht vermindert oder unvollständig sind, kehrt der Cluster in den regulären Dehnungsmodus zurück, beendet die Warnung und stellt den min_size Anfangswert 2wieder her. Der Cluster erfordert erneut beide Sites als Peer, nicht nur die Site, die die ganze Zeit über verblieben ist. Daher können Sie bei Bedarf von der anderen Site übernommen werden.
