### ISSUE TITLE
PostScript PDF convertion

### ISSUE THREAD

**Issue by ArtiomWin** [86Box/86Box#495]
Recently added PostScript support has some issues for me: despite having needed gsdll32.dll files supposed to be "printed" are saved in .ps format and don't convert to .pdf

 - OS: Windows 10
 - 86box build 2023

**Comment by dhrdlicka** [comment]
That means the Ghostscript couldn't process the PostScript output. Make sure that you set the printer correctly.

**Comment by ArtiomWin** [comment]
Here's config. Guest OS is Windows 3.1, printer is configured as HP LaserJet Series II.
[Packard Bell Legend 1910 Supreme.zip](https://github.com/86Box/86Box/files/3948698/Packard.Bell.Legend.1910.Supreme.zip)

**Comment by dhrdlicka** [comment]
Of course, HP LaserJet Series II is not even a PostScript printer to begin with. Try one of the Apple LaserWriters.

**Comment by ArtiomWin** [comment]
I've tried with installed generic PostScript drivers, and it works. Thank you very much. 
P.S. Any possibilities of expanding printer emulation (i.e. adding support of PCL)?
