### ISSUE TITLE
VNC.c currently uncompilable 

### ISSUE THREAD

**Issue by un-simp** [86Box/86Box#4950]
### What happened?

Compiling with CMake flag VNC=ON causes vnc.c to fail due to `vnc_mouse_poll` not existing 

### Configuration file

```ini
N/A
```

### Operating system

Arch Linux

### CPU

AMD Ryzen 5 5625U

### 86Box version

Commit a3ad407

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

**Comment by Pellzi** [comment]
Tell us more about your build configuration is a wish, i can fully support. Especialy on GitHub.
My wish is here, and this goes to GitHub, that after the pressing the green button Code, in this little window, one more Tab is visible, with tha Name, "Compiler" or "Compiler Configuration". 
There is the Info to find, what compiler is to use, to compile the project, and what dependencies this compiler must have, that the build is sucessfully.

**Comment by jriwanek** [comment]
> > Tell us more about your build configuration
> > is a wish, i can fully support. Especialy on GitHub.
> > My wish is here, and this goes to GitHub, that after the pressing the green button Code, in this little window, one more Tab is visible, with tha Name, "Compiler" or "Compiler Configuration".
> > There is the Info to find, what compiler is to use, and what setup is to set, to compile the project, and what dependencies this compiler must have, that the build is sucessfully.

We have no way to customize what features github offers

**Comment by Pellzi** [comment]
I know Git Hub a very long time, but its new, that i have such a account.
Do you know, if GitHub itself has such a site like these, that i can upload my whis to update the code button?
Is the Side: https://github.com/orgs/community/discussions/  the right one for this?
Sorry for this Offtopic question. But i think, not only here the Question: Tell us more about your build configuration? is a big problem for GitHub Consumers.
I the past i tryed out approximative 20 projects, and folloed the instructions, but not one, i could compiled sucessfully.
So i gave it up.  (The last one was to build was the 86Box Manager with VS2022: Result: over 100 faults during compiling).

**Comment by jriwanek** [comment]
Please don't hijack other people's threads on our issue tracker.

**Comment by jriwanek** [comment]
> In other Forums, its usual, that such a post will be found as add in such a thread. 

Other people do it elsewhere is not an acceptable excuse, further messages from you in this thread will be marked as spam, and will remain unresponded to.

**Comment by jriwanek** [comment]
> hiya im just using the build guide. im not sure what you mean with the code menu as thats instructions for cloning or opening in codespaces

Sorry about the delayed response, a rather rude user decided to hijack your issue with unrelated questions, we'll be looking into your problem.

**Comment by un-simp** [comment]
Thank you
