### ISSUE TITLE
Xi8088 Machine blank screen

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4957]
### What happened?

I tried several 8088 machines. All seems to work except the Xi8088, no matter what video card I use I always get a blank screen at boot time, I also tried enabling and disabling all the UMB memory regions with no avail.
I interested in this machine because it can map UMB memory.

### Configuration file

```ini
[Xi8088]
turbo_setting = 1
bios_128kb = 1
umb_c0000h_c7fff = 0
umb_c8000h_cffff = 0
umb_d0000h_d7fff = 1
umb_d8000h_dffff = 1
umb_e0000h_e7fff = 0
umb_e8000h_effff = 0

[PC/XT XTIDE]
bios = xt_plus

[AST SixPakPlus]
irq = 2

[General]
dpi_scale = 0
emu_build_num = 6267
enable_overscan = 1
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
rctrl_is_lalt = 1
uuid = d725301d-3ffc-5962-936b-63f508b183d4
vid_renderer = qt_software
vid_resize = 1

[Machine]
cpu_family = necv20
cpu_multi = 1
cpu_speed = 10000000
cpu_use_dynarec = 0
machine = v20xt
mem_size = 640

[Video]
gfxcard = g2_gc205

[Input devices]
mouse_type = msserial

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = xtide

[Hard disks]
hdd_01_fn =
hdd_01_ide_channel = 0:0
hdd_01_parameters = 17, 11, 1024, 0, ide
hdd_01_speed = 1994_4500rpm
hdd_01_vhd_blocksize = 1024

[Floppy and CD-ROM drives]
cdrom_01_ide_channel = 0:1
cdrom_01_image_history_01 =(3.5)/Disk1.img
fdd_01_type = 35_2dd


[Ports (COM & LPT)]
lpt1_device = dot_matrix

[IBM MDA]
rgb_type = 2

[Other peripherals]
isartc_type = p5pak
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.2.2.6247 and  4.2.26267

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
I think you need to wait quite a while for it to probe the PS/2 mouse port.

**Comment by OBattler** [comment]
Yes, it's the mouse - changed it to PS/2 and it goes to POST instantly. Now I'm waiting to see if it ever makes it to POST with serial mouse.
