### ISSUE TITLE
AAEON SBC-350A cannot detect HDD

### ISSUE THREAD

**Issue by Carmina16** [86Box/86Box#4985]
### What happened?

This machine (`sbc350a`) can no longer autodetect or use the hard drive on the internal controller. It worked aroung October 2023.

### Configuration file

```ini
-
```

### Operating system

-

### CPU

-

### 86Box version

6239

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by eddmanx** [comment]
It would help if you could mention the working build you were using. It started in March 2024, or July 2024 if going by the stable releases.

The issue started with build 5636, where the on-chip IDE controller was removed. I suppose the devs simply forgot to remove "Internal device" from the list.

**Comment by OBattler** [comment]
Please fill out the form properly, with all the required data.

**Comment by borisvolk117** [comment]
This single-board computer has a SMC FDC37C665 super IO chip which has IDE interface, though ALi M1217 chipset has no IDE controller. The detail is in #5001
