### ISSUE TITLE
Into the Eagle's Nest - Surface Data clearing on write

### ISSUE THREAD

**Issue by Digitoxin1** [86Box/86Box#4999]
### What happened?

This image has weak bits set in the third sector of track 0.0.  Writing to the image zero's out the surface data removing the weak bits.

Copy protection is Mindscape DEM

The first three sectors of track 0.,0 are non-standard.  The first two sectors both have a sector id of 0 and do not contain a data address mark.  The third sector also has a sector id of 0.  This sector has weak bits and overlaps with the next sector which is sector id 1.  

Writing to the image within 86Box does not make any modifications to these sectors but does clear out the weak bits in the third sector.

I have checked other images with weak bits and have not experienced this issue, so this is not a global issue.

[EaglesNest.zip](https://github.com/user-attachments/files/17910633/EaglesNest.zip)

### Configuration file

```ini
[ST-11M MFM Fixed Disk Adapter]
base = 0320
irq = 2
bios_addr = C8000
revision = 5

[General]
emu_build_num = 6317
force_43 = 1
host_cpu = AMD Ryzen 9 3900X 12-Core Processor            
uuid = 1fdba0a9-a74a-5eeb-a7d8-0ed319cad922
vid_renderer = qt_opengl3
video_filter_method = 0

[Machine]
cpu_family = 8088
cpu_multi = 1
cpu_speed = 7159092
cpu_use_dynarec = 0
machine = tandy
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = st506_xt_st11_m

[Hard disks]
hdd_01_fn = hd.img
hdd_01_mfm_channel = 0
hdd_01_parameters = 17, 8, 462, 0, mfm

[Floppy and CD-ROM drives]

[IBM EGA]
memory = 256
monitor_type = 9
```

### Operating system

Windows 10

### CPU

AMD Ryzen 9 3900X

### 86Box version

v4.3 build 6317

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Digitoxin1** [comment]
I tested a couple other titles that use the exact same copy protection scheme with the same sector layout on track 0.0.  This issue only appears to occur on 360k disk images.  720k disk images that use the same protection scheme do not appear to be affected.

**Comment by OBattler** [comment]
Of course weak bits get cleared - they get overwritten, that's normal.

**Comment by Digitoxin1** [comment]
As soon as I write a file to the disk, the copy protection no longer works and the disk is no longer recognized as original.  This only happens with 360k images, not 720k images.  This doesn't seem normal.

**Comment by Digitoxin1** [comment]
Not sure if these are weak bits or holes.    The section of the track with surface data is highlighted in yellow and starts where the cursor is located.  This is in the third sector of track 0.0.  

![image](https://github.com/user-attachments/assets/11e585ee-da3c-4e9f-9116-3d64c425cc3b)

**Comment by OBattler** [comment]
They are marked as weak bits (otherwise, the bitstream would be 0's and not 1's), perhaps they're supposed to be holes instead? Because that would explain why the game attempts to write there.

**Comment by Digitoxin1** [comment]
If that is the case, why does 86Box preserve the surface area bits on titles using the exact same copy protection scheme on 720k media but not 360k media?  Also, why would writing a file to the disk which would never touch that area of the disk cause 86Box to clear out the surface area bits?

To clarify, I'm copying a small text file to the disk, not letting the game itself write to the disk.

**Comment by Digitoxin1** [comment]
Another update.  I created a 360K 86f image and a 720k 86f image from the exact same flux set for this title.  The only difference between these two images is 40 empty tracks at the end of the 720k 86f image.  If I copy a small text file to the 360K image, the weak bit data is zeroed out in the image.  If I do the exact same process on the 720k image, the weak bit data is left intact.

**Comment by OBattler** [comment]
The 360k image is wrong in the first place - 360k disks are thick track, so 86f stores them as two identical copies of the same track. Storing only one copy of each track is good enough for reading, but for writing.

**Comment by OBattler** [comment]
This is now fixed.
