### ISSUE TITLE
Floppy disk does not work perfectly when I install Windows 95 RTM

### ISSUE THREAD

**Issue by doutter** [86Box/86Box#5003]
### What happened?

Floppy disk does not work perfectly when I install Windows 95 RTM.

I tested it using Gigabyte GA-5AX, Asus P/I-P55TP4XE and Shuttle HOT-557

![86box_floppy](https://github.com/user-attachments/assets/1bf7d189-04e2-48c7-8a3a-5a710baeaa70)

### Configuration file

```ini
[S3 Vision964 PCI (Diamond Stealth64 VRAM)]
memory = 4

[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 5 5600G with Radeon Graphics         
emu_build_num = 6130
uuid = a7e09b76-3d03-5812-ba02-b7ed49dbd38a
force_43 = 1
vid_resize = 2
window_fixed_res = 1000x750
sound_gain = 10

[Machine]
machine = 5ax
cpu_family = pentium_p54c
cpu_speed = 133333333
cpu_multi = 2
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 131072

[Video]
gfxcard = stealth64v_pci

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb16
midi_device = system_midi
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = postscript

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 854, 0, ide
hdd_01_fn = Z:/86Box/hd420.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_type = HITACHI_CDR-8130_0020
cdrom_01_image_path = C:/Users/D/Downloads/Microsoft Windows 95 (OEM) (RTM)/Microsoft Windows 95 (OEM) (RTM).iso
fdd_01_fn = C:/Users/Douglas Ritter/Downloads/Windows 95 RTM Installation Bootdisk (TEAC CDI) (3.5).IMG
```

### Operating system

Windows 10

### CPU

AMD Ryzen 5600G

### 86Box version

4.2.1 (6130)

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by ppgrainbow** [comment]
Are the turbo timing enabled when running Windows 95?

If not, under Tools, go to **Settings > Floppy & CD-ROM drives** and select the **Turbo timings** checkbox next to each emulated floppy diskette drive. :)

**Comment by sainttheonly1** [comment]
Boot Floppy: Ensure that you're using a proper Windows 95 boot floppy. Windows 95 CDs are not bootable and require a boot floppy to start the installation process1.

Compatibility: Windows 95 RTM can be quite finicky with certain hardware configurations. Make sure that your emulated hardware closely matches the requirements of Windows 951.

Configuration Settings: Double-check your configuration settings in 86Box. Sometimes, small tweaks can make a big difference. For example, you might want to try different video modes or disable certain features that could be causing conflicts.

Patching: There are patches and fixes available for Windows 95 that can help with compatibility issues on modern systems. Consider applying these patches to see if they resolve the installation problems.

Logs and Debugging: Enable detailed logging in 86Box to capture more information about what's happening during the installation process. Reviewing these logs can provide clues about what's going wrong.

**Comment by jriwanek** [comment]
Comment marked as spam as it's blatantly AI generated.
