### ISSUE TITLE
Cirrus Logic 5429 and 5434 does not work under Windows 3.1

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#5004]
### What happened?

I tested both 486 machines with 5434 and 5429 video cards and they respective device drivers under Windows 3.1. but only a black screen can be seen after loading Windows 3.1 in both 256 and 64kb video modes.
At first, I thought that the 5434 drivers had issues, but I found the same behavior with the 5429 card with the 5429 drivers

Btw: the 5434 SpeedStar 64, that supports 4mb, says "PCI" at boot time but on 86box is defined as ISA. 

Here is the VM:
[486 SLC Leopard.zip](https://github.com/user-attachments/files/17967281/486.SLC.Leopard.zip)

### Configuration file

```ini
[Cirrus Logic GD5434 (ISA)]
memory = 4

[Pro Audio Spectrum 16 #1]
control_pc_speaker = 1
receive_input = 1
receive_input401 = 0

[General]
emu_build_num = 6320
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
uuid = 11bce565-3a19-5c10-a622-9b531335154a
vid_renderer = qt_software
vid_resize = 1

[Machine]
cpu_family = i486sx
cpu_multi = 1
cpu_speed = 33333333
cpu_use_dynarec = 1
machine = ami495
mem_size = 8192

[Video]
gfxcard = cl_gd5429_isa

[Input devices]
mouse_type = msserial

[Sound]
sndcard = pas16

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Storage controllers]
hdc = ide_isa

[Hard disks]
hdd_01_fn = 
hdd_01_ide_channel = 0:0
hdd_01_parameters = 17, 15, 1224, 0, ide
hdd_01_speed = 1992_3600rpm
hdd_01_vhd_blocksize = 1024

[Floppy and CD-ROM drives]
cdrom_01_ide_channel = 0:1
cdrom_01_parameters = 1, atapi
cdrom_01_speed = 4
cdrom_01_type = AZT_CDA46802I_1.15
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd

[Cirrus Logic GD5434 (ISA) (Diamond SpeedStar 64 Rev. A3)]
memory = 2

[Cirrus Logic GD5429 (ISA)]
memory = 2
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.3.0.6320

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by sainttheonly1** [comment]
Update 86Box:

Ensure you're using the latest version of 86Box, as newer versions may include bug fixes or improvements that could resolve your issue.

Video Card Configuration:

Try different combinations of video card settings in 86Box. Since you're using a GD5434 (ISA) defined as PCI in real hardware but ISA in 86Box, verify that the correct settings are applied. You might also want to test the GD5429 card with updated settings.

Driver Testing:

Experiment with different driver versions for the GD5434 and GD5429 cards. Sometimes older or alternative drivers can work better with certain configurations.

Graphics Renderer:

Consider changing the video renderer in 86Box. Since you're currently using qt_software, you might try other renderers like d3d, opengl, or gdi to see if it resolves the display issues.

Log Analysis:

Enable detailed logging in 86Box to capture more information about what's happening when you try to load Windows 3.1. Reviewing these logs may provide clues about what's going wrong.

**Comment by jriwanek** [comment]
Comment marked as spam as it's blatantly AI generated.

**Comment by TC1995** [comment]
Send me the package of this 5429 driver version (5434 too).

**Comment by Fenix770** [comment]
Here are the Win 3.x drivers for both cards
[Cirrus Logic 5429 Floppy Disk.zip](https://github.com/user-attachments/files/17975101/Cirrus.Logic.5429.Floppy.Disk.zip)
[Cirrus Logic 5434 Win31.zip](https://github.com/user-attachments/files/17975102/Cirrus.Logic.5434.Win31.zip)

**Comment by Fenix770** [comment]
Update: 
I tried the 6354  Windows build:

I get the following:

The  800x600 at 16 colors works fine:
![Monitor_1_20241218-185915-308](https://github.com/user-attachments/assets/54b33bb9-2bde-4277-9d99-b97b067cb5b5)


The 1024x768 at 16 colors have a minor glitch, a black line appears when I open the video setup utility.

![Monitor_1_20241218-185952-992](https://github.com/user-attachments/assets/805a0a28-dba3-4bd4-a69e-12345af15230)

The 8 and 16 bit video modes now works, but have screen text bug.

![Monitor_1_20241218-190026-723](https://github.com/user-attachments/assets/178eca11-6f8c-4bde-ae28-2c604565f03c)

**Comment by TC1995** [comment]
Known bug, it's the aperture for some stuff.

**Comment by OBattler** [comment]
This is now fixed.

**Comment by a-1103** [comment]
**CL-GD5422/24/26/28/29 ISA** and  **CL-GD5424/26/28/29 VLB** should use LFB in range below 16Mb according to SR7[7:4] register bits corresponding to A23-A20 address lines.  1 Mb and 2 Mb buffer programmed differently.  See SR7, GRB registers and Appendix D2 here
https://ardent-tool.com/datasheets/Cirrus_CL-GD542x.pdf

 **CL-GD5430/’34/’40 VLB** should use LFB at 32 Mbyte, 64 Mbyte or 2048 Mbyte according to board physical design - any value in SR7[7:4] bits enables LFB. Some early VLB motherboards only support LFB at 32Mb!
**CL-GD5434 ISA** should use LFB in range below 16Mb according to SR7[7:4] register bits corresponding to A23-A20 address lines. See SR7, GRB registers and Appendix D2.
https://archive.org/details/bitsavers_cirrusLogiD543X4XTechnicalReferenceManual4edFeb95_28352592

To test LFB address you can use UniVBE 5.x or 6.x:
uvconfig.exe -l<lfb_address_in_decimal> then run vbetest.exe
