### ISSUE TITLE
PS/2 mouse problem

### ISSUE THREAD

**Issue by gavrilovegor519** [86Box/86Box#5015]
### What happened?

While old Linux VMs (eg. Red Hat Linux (not RHEL) 6.x) access to /dev/psaux, VM is hangs.

### Configuration file

```ini
Any VMs with PS/2 mouse support.
```

### Operating system

Fedora 40/41

### CPU

AMD Ryzen 3 4300U

### 86Box version

Various versions - 4.2.x and previous

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
Please post the configuration file and, if possible, the entire VM so we can attempt to reproduce the bug.

**Comment by gavrilovegor519** [comment]
This problem is fixed in v4.2.1 (or may be earlier). Sorry to bother you.
