### ISSUE TITLE
86box does not save the configuration of the Grid 1520 machine

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#5019]
### What happened?

I tried to change the configuration with the SETUP.EXE utility. It detects the old configuration but does not change anything. 

VM:
[Grid 1512.zip](https://github.com/user-attachments/files/18035186/Grid.1512.zip)

SETUP utility: 
[Grid 1512.zip](https://github.com/user-attachments/files/18035221/Grid.1512.zip)

DOS:
[Microsoft MS-DOS 3.30 [GRiD OEM] (3.5-720k).zip](https://github.com/user-attachments/files/18035196/Microsoft.MS-DOS.3.30.GRiD.OEM.3.5-720k.zip)

### Configuration file

```ini
[General]
emu_build_num = 6329
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
uuid = e6f3a983-1ead-5e73-bfd5-a1936fc3835f
vid_renderer = qt_software
vid_resize = 1

[Machine]
cpu_family = 286
cpu_multi = 1
cpu_speed = 6000000
cpu_use_dynarec = 0
machine = grid1520
mem_size = 4096

[Video]
gfxcard = cga

[Input devices]
mouse_type = msserial

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[IBM CGA]
display_type = 0
composite_type = 0
rgb_type = 2
double_type = 0
snow_enabled = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Hard disks]
hdd_01_fn = 
hdd_01_ide_channel = 0:0
hdd_01_parameters = 17, 4, 615, 0, ide
hdd_01_speed = 1989_3500rpm
hdd_01_vhd_blocksize = 4096

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.3.0.6329

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by MaxwellS04** [comment]
Use GSETUP.exe

**Comment by Fenix770** [comment]
I tried it too. It has the same issue. I also had similar issue with some VMs like the Tandy 1000 SL/2.
However, most XTs lack any setup utility and newer 286s have a built-in setup BIOS that work fine.

**Comment by Fenix770** [comment]
Btw: The conf1520 utility to change memory type EMS/Extended and the Slow/fat mode works, but I cannot change the Floppy/HDD options with either the OEM SETUP.EXE utility or GSETUP generic software.

**Comment by Fenix770** [comment]
Sorry I found that the Specification for Conner hard disks were on the disk speed options. I suggest avoiding confusion by add a specific Conner internal IDE controller and reflect it on the speed options (I mean, do not show the generic speeds for this hdd controller)
