### ISSUE TITLE
Windows 95 (RTM) Booting problem

### ISSUE THREAD

**Issue by mrbigDev** [86Box/86Box#5020]
### What happened?

So basically if I try to load my Windows 95 (RTM) boot disk it just takes forever to load.
![Screenshot 2024-12-06 193628](https://github.com/user-attachments/assets/0942cf85-dca8-4a5c-8a92-acc4679d78c2)
The cursor will just keep blinking forever.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = 13th Gen Intel(R) Core(TM) i5-13400F
emu_build_num = 6130
uuid = 722fa4a8-5dff-5fb7-86fe-6b175ff5ea12
force_43 = 1

[Machine]
machine = ficva502
cpu_family = pentium_p55c
cpu_speed = 200000000
cpu_multi = 3
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
fpu_type = internal
mem_size = 131072

[Video]
gfxcard = stealth3d_4000_pci
voodoo = 1

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sbawe32

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[S3 ViRGE/GX2 (Diamond Stealth 3D 4000) PCI]
bilinear = 1
dithering = 1

[3Dfx Voodoo Graphics]
type = 0
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[Hard disks]
hdd_01_parameters = 63, 16, 8322, 0, ide
hdd_01_fn = hdd/Hard disk.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_02_type = 35_2ed
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
fdd_01_fn = C:/Users/Dylan Wilkoff/Downloads/Compressed/Microsoft Windows 95 (Retail Full) (3.5 DMF)/BOOTDISK.IMG
cdrom_01_type = 86BOX_CD-ROM_1.00
fdd_01_turbo = 1
fdd_02_turbo = 1
```

### Operating system

Windows 11 Pro

### CPU

Intel Core i5-13400f

### 86Box version

v4.2.1 6130

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

No.

**Comment by mrbigDev** [comment]
Literally tried everything :/

**Comment by thedax** [comment]
I can't seem to reproduce this on either 4.2.1 stable or build 6331, the latest Jenkins build. Using a freshly downloaded copy of 95 RTM (Retail Full) off winworld, it boots as I'd expect on this same machine.

I tested on both MacOS and Linux, with forced interpreter (via config file and also entering the cmos setup of this guest and disabling the CPU caches), old dynarec and new dynarec, turbo floppy timings on and off, and couldn't get this to happen.

 I'd double check you don't have a corrupted download and that your machine's floppy controller is set correctly in 86Box's settings.

**Comment by mrbigDev** [comment]
Did you use a 32 bit installation or a 64 bit.

**Comment by mrbigDev** [comment]
Because maybe 64 just won't work for me for some reason.

**Comment by thedax** [comment]
64-bit for all of my testing.

**Comment by mrbigDev** [comment]
Alright thanks, I mostly believe I might have a corrupted installation so I'm just going to have to figure it out on my own for now.

**Comment by mrbigDev** [comment]
Can you give me a direct download to your 86box installation with its roms? because maybe I am clicking somewhere I am not suppose to.

**Comment by OBattler** [comment]
Yes, it must be a corrupted installatio and therefore, NOTABUG, since all my installs and boot floppies work fine.
