### ISSUE TITLE
86Box 4.2.1 and 4.2 are unstable, 4.1.1 works

### ISSUE THREAD

**Issue by Liam314839** [86Box/86Box#5035]
### What happened?

4.2.1 won't boot 95 with basically any S3 card (haven't tried GD5446), and now it won't show a 86Box window when launching for some reason. This is the 2nd time I've had the window issue.

### Configuration file

```ini
[General]
vid_renderer = qt_vulkan
host_cpu = Apple M2
emu_build_num = 6130
uuid = aac6dc75-5832-5d10-b514-eb438ea52750
vid_resize = 1
video_filter_method = 0
window_remember = 1

[Machine]
machine = p55t2p4
cpu_family = pentium_p54c
cpu_speed = 75000000
cpu_multi = 1.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 262144

[Video]
gfxcard = stealth64v_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sb16

[Network]
net_01_link = 2
net_02_link = 0
net_03_link = 0
net_04_link = 0
net_01_card = pcnetpci

[Storage controllers]
hdc = internal
cassette_mode = load

[Realtek RTL8029AS #1]
mac = 3a:e9:44

[Hard disks]
hdd_01_parameters = 63, 16, 4161, 0, ide
hdd_01_fn = /Users/liamsims/Documents/win95.IMG
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_image_path = /Users/liamsims/Downloads/Win95_OSR25.iso
cdrom_01_image_history_01 = /Users/liamsims/Downloads/Lego Racers 2.iso
fdd_01_image_history_01 = /Users/liamsims/Downloads/Windows95b.img
fdd_01_image_history_02 = /Users/liamsims/Downloads/en_win95c_osr25_ebd.img
cdrom_01_type = 86BOX_CD-ROM_1.00

[S3 Trio64V+ PCI (Phoenix)]
memory = 2

[Sound Blaster 16 #1]
base = 0220
base401 = 0330
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[AMD PCnet-PCI II #1]
mac = d9:fe:9d

[Monitor #1]
window_coordinates = 0, 53, 1440, 734
window_maximized = 1

[Monitor #2]
window_coordinates = 0, 0, 0, 0

[S3 Trio64V2/DX PCI]
memory = 4

[S3 Trio64 PCI (Phoenix)]
memory = 4

[Cirrus Logic GD5446 (PCI)]
memory = 4

[S3 Vision968 PCI (Diamond Stealth64 Video VRAM)]
memory = 4

[S3 Vision964 PCI (Diamond Stealth64 VRAM)]
memory = 4
```

### Operating system

macOS Sonoma

### CPU

Apple M2

### 86Box version

v4.2.1

### Build architecture

macOS - Universal (Intel and Apple Silicon)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

![Screenshot 2024-12-10 at 7 33 55 PM](https://github.com/user-attachments/assets/1ec3d580-08f1-45d0-b665-805f671e87c4)

**Comment by OBattler** [comment]
86Box likely freezes because the second monitor's coordinates are set to 0, 0, 0, 0, so it attempts to display a second monitor of zero size. Try removing that from the configuration.

**Comment by OBattler** [comment]
I have just reproduced the bug on Windows - 86Box doesn't start if the window is set to maximized in the config.

**Comment by OBattler** [comment]
And I can no longer reproduce it for some reason.

**Comment by OBattler** [comment]
Can you please bisect using the builds on our Jenkins (https://ci.86box.net) and tell me which build exactly broke it? I can't do it myself since I'm on Windows.

**Comment by Liam314839** [comment]
Solved: change window_remember from 1 to 0 to fix crash
