### ISSUE TITLE
Olivetti GO708 corrupted fonts in the 640x400x2 video mode

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#5040]
### What happened?

I recently tested the Grid Machine with the Olivetti Go708 video card and 640x400x2 video mode. I foun the font are corrupted in both Windows 2.1 and Windows 3.0.

Screenshot:
![Monitor_1_20241211-185434-972](https://github.com/user-attachments/assets/85dd38ad-6b98-4e06-aa39-6f9c848c100d)

VM:
[Grid 1520 -2.zip](https://github.com/user-attachments/files/18102875/Grid.1520.-2.zip)

### Configuration file

```ini
[Olivetti OGC (GO708)]
display_type = 0
composite_type = 1
rgb_type = 2
double_type = 0
snow_enabled = 0

[General]
emu_build_num = 6341
host_cpu = Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
uuid = 74c446f1-3386-5212-8ca9-db3b94a39e6e
vid_renderer = qt_software
vid_resize = 1

[Machine]
cpu_family = 286
cpu_multi = 1
cpu_speed = 10000000
cpu_use_dynarec = 0
fpu_type = 287
machine = grid1520
mem_size = 4096

[Video]
gfxcard = ogc

[Input devices]
mouse_type = msserial

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Hard disks]
hdd_01_fn = 
hdd_01_ide_channel = 0:0
hdd_01_parameters = 17, 5, 981, 0, ide
hdd_01_speed = CP3044
hdd_01_vhd_blocksize = 1024

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd

[IBM CGA]
display_type = 0
composite_type = 0
rgb_type = 2
double_type = 0
snow_enabled = 0
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.3.0.6341

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
They are not corrupted, it's just rendering as 640x200x2 for some reason.
