### ISSUE TITLE
More 8086 systems

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#505]
**Is your feature request related to a problem? Please describe.**
Not really. 8086 systems present in 86Box are all special (Amstrad, Tandy, AT&T).

**Describe the solution you'd like**
More 8086 system, like the Deskpro 8086, PS/2 Model 25 or 30, and some other.

**Comment by jvernet** [comment]
More over, did you plan to add missing machine from pcem ?
I would like to help, but never succeeded to have a working build env....

**Comment by OBattler** [comment]
1. At the very least I do want to eventually add the PS/2 Models 25 and 30-86, but I'd need some proper documentation about them.

2. A development environment should be easy to setup: download MSYS2, run it in MINGW32 mode, do pacman -Syuu, after upgrading all the packages, restart and do pacman -Syuu again, then install mingw-gcc, I forgot which package for the Windows headers, freetype2 (you will have to move some include directories around because MSYS2 messes them up), libpcap, ghostscript, SDL2, and I believe the DirectX SDK, snd you should be good to go.

**Comment by jvernet** [comment]
Will try again MSYS2 stuff.
About missing models, at least in par with PCEM V14:

- [8088] ATARI PC3
- [8088]Compaq Portable Plus
- [8088]NCR PC4i
- [8088]VTEC Laser Turbo XT
- [8086]VTech Laser XT3
- [286]Bull Micral 45
- [286]COMPAQ Portable II
- [286]DELL SYSTEM 200
- [286] EPSON PC AX
- [286] EPSON PC AX2e
-  [286] TULIP AT Compact
- [386SX] ACER 386SX25/N
- [386SX] AMI 386sx Clone
- [386SX]Packard Bell Legend
- [386DX]Compaq Pro 386
- [386DX]EPSON PCAX3

**Comment by tiseno100** [comment]
Do we have documentation and ofc the ROMs for these machines? As i see these are from PCem. Some of these machines like the ACER 386SX25/N will require their chipset to be emulated.

**Comment by jvernet** [comment]
Yes, these system are present in PCem
About the dev MSYS2 env: no way. After installing everything, I'm facing error like "off64_t unknown type, do you mean _off64_t". I replaced off65_t by _off64_t, passing. I have bunch of warning like ftello64, fseek64, undeclared, and now
"
win/win.c:376:6: erreur: « source_hwnd » non déclaré (première utilisation dans cette fonction)
  376 |  if (source_hwnd)
      |      ^~~~~~~~~~~
win/win.c:383:11: erreur: « force_debug » non déclaré (première utilisation dans cette fonction)
  383 |     if (! force_debug)
      |           ^~~~~~~~~~~
win/win.c: Dans la fonction « do_stop »:
win/win.c:426:9: erreur: « source_hwnd » non déclaré (première utilisation dans cette fonction)
  426 |     if (source_hwnd)
      |         ^~~~~~~~~~~

win/win.c: Dans la fonction « plat_remove »:
win/win.c:497:5: attention: déclaration implicite de la fonction « _wremove »; vouliez-vous utiliser « remove » ? [-Wimplicit-function-declaration]
  497 |     _wremove(path);
      |     ^~~~~~~~
"

**Comment by OBattler** [comment]
The systems are present, but from what I have seen, PCem just merges them all without making sure the emulation is correct. I've had to Dev branch the two Laser XT machines already for such reasons. "It POST's without error" might be good enough for PCem, but for 86Box, i'd like proper emulation. :p

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
