### ISSUE TITLE
ISA16 ESDI issue and Mono+Color treatment

### ISSUE THREAD

**Issue by a-1103** [86Box/86Box#5059]
### What happened?

1. When I'm using external ISA16 Western Digital WD1007V-SE1 (ESDI) controller it is reported in IDENTIFY_DRIVE as DW0170-VES which is incorrect. It should be WD1007V-SE as in real physical ISA16 device.

2. When I'm selecting in 86box settings - Video any mono adapter (f.e. MDA, Hercules, etc..) in Video 2 it is None. I can't select anything. It should be color adapter as CGA, EGA, VGA etc. (using separate address 0x3Dx ports and text video buffer at 0xB8000:0). 
2a. However when primary video is color adapter there are some color PCI Cirrus Logic 5436/5446 ones in Video 2. What is it intended for?

2b. When I'm using emluated IBM PC, IBM XT or any other/similar one that has jumper-controlled primary mono/color setting (slightly newer emulated ASUS PVI-486SP3C also has such jumper in conjunction with BIOS setting for that) and it has color/mono video pair, how can I select which subsystem is primary? On real hardware it controlled over jumper blocks.

### Operating system

Windows Server 2008 R2

### 86Box version

4.3 build 6359

### Build architecture

Windows - x64 (64-bit)

**Comment by OBattler** [comment]
1. Was the same software used to read out the IDENTIFY string on both 86Box and real hardware?
2. Currently, the CGA family of adapters is not yet supported as secondary video.
3. The first video card is currently always considered primary.

**Comment by a-1103** [comment]
1. Here is report from real WD1007V ESDI Controller, report is made from this software: http://www.sysinfolab.com/ru/files/beta/astrabet.zip

  +------------------------------------------------------------------------+
  |    This report is created by ASTRA v.7b11  .  Compiled: 20-Dec-2024    |
  +------------------------------------------------------------------------+
                                       
    Version:                           ASTRA - Advanced Sysinfo Tool 7.11 beta
    License Type:                      FREE VERSION

                  +-----------------------------------------+
                  |                  Disk                   |
                  +-----------------------------------------+
  Primary/Master Drive
    Disk Model:                        WD1007V
    Disk Size:                         153 MB (0.15 GB)
    Interface Type:                    Parallel ATA
    Geometry:                          Heads: 7, Sectors: 36, Tracks: 1249
    Compatibility:                     Unknown
    Serial Number:                     00000000000000000000
    Controller Revision:               REV. A5
    Disk Marketing Size:               160 MB (0.16 GB)
    Buffer Size:                       32 kB
    Buffer Type:                       Dual ported multi-sector buffer with a read caching
    ECC bytes:                         4
    Security Erase Time:               None
    Enh. Security Erase:               None
    Current APM Value:                 None
    Acoustic Management:               None
    Device Location:                   Primary/Master
  Transfer Modes
    PIO Mode Support:                  1
    SW DMA Mode Support:               Not Supported
    MW DMA Mode Support:               Not Supported
    UDMA Mode Support:                 Not Supported
    Sectors per Interrupt:             Not Supported
  Disk Features
    SATA NCQ Command:                             [ ]
    SSD TRIM Command:                             [ ]
    DMA Transfer:                                 [ ]
    LBA Supported:                                [ ]
    Block Mode:                                   [ ]
    Double Word I/O:                              [ ]
    Standard Standby Timer:                       [ ]
    IORDY Supported:                              [ ]
    IORDY may be Disabled:                        [ ]

**Comment by a-1103** [comment]
1. Here is report from real WD1007V ISA16 controller (UMC491F 386dx ISA motherboard) from this software:
http://www.sysinfolab.com/ru/files/beta/astrabet.zip

  +------------------------------------------------------------------------+
  |    This report is created by ASTRA v.7b11  .  Compiled: 20-Dec-2024    |
  +------------------------------------------------------------------------+
                                       
    Version:                           ASTRA - Advanced Sysinfo Tool 7.11 beta
    License Type:                      FREE VERSION

                  +-----------------------------------------+
                  |                  Disk                   |
                  +-----------------------------------------+
  Primary/Master Drive
    Disk Model:                        WD1007V
    Disk Size:                         153 MB (0.15 GB)
    Interface Type:                    Parallel ATA
    Geometry:                          Heads: 7, Sectors: 36, Tracks: 1249
    Compatibility:                     Unknown
    Serial Number:                     00000000000000000000
    Controller Revision:               REV. A5
    Disk Marketing Size:               160 MB (0.16 GB)
    Buffer Size:                       32 kB
    Buffer Type:                       Dual ported multi-sector buffer with a read caching
    ECC bytes:                         4
    Security Erase Time:               None
    Enh. Security Erase:               None
    Current APM Value:                 None
    Acoustic Management:               None
    Device Location:                   Primary/Master
  Transfer Modes
    PIO Mode Support:                  1
    SW DMA Mode Support:               Not Supported
    MW DMA Mode Support:               Not Supported
    UDMA Mode Support:                 Not Supported
    Sectors per Interrupt:             Not Supported
  Disk Features
    SATA NCQ Command:                             [ ]
    SSD TRIM Command:                             [ ]
    DMA Transfer:                                 [ ]
    LBA Supported:                                [ ]
    Block Mode:                                   [ ]
    Double Word I/O:                              [ ]
    Standard Standby Timer:                       [ ]
    IORDY Supported:                              [ ]
    IORDY may be Disabled:                        [ ]

Below there is screenshot from 86box:

![Monitor_1_20241222-213704-142](https://github.com/user-attachments/assets/595637b6-4b48-4d19-9f50-4225c80ecddf)

**Comment by OBattler** [comment]
The controller name should now be fixed.

**Comment by a-1103** [comment]
According to attached photos WD1007V-SE1 and WD1007V-SE2 has 32K buffer SRAM.
SRM20256LM10 in WD1007V-SE1.
TC55257BFL-10 in WD1007V-SE2.
It is possible to implement it and report in IDENTIFY DRIVE block.
Also other fields - serial number, Buffer Type, ECC (boards has jumper for it)
My board is WD1007V-SE2 (bios is version 1.51) and it is reported as WD1007V,
SE1 differs from SE2 that it has no floppy, otherways it is the same.

https://www.minuszerodegrees.net/manuals/Western%20Digital/wdcontr.txt
https://www.minuszerodegrees.net/manuals/Western%20Digital/WD1007V-SE1%20and%20SE2.pdf

Here is description of IDENTIFY_DRIVE block
https://www.os2museum.com/wp/identify-esdi-drive/
HDD, of course, is different.
IDENTIFY_DRIVE dump from WD1007V-SE2 - https://www.os2museum.com/files/atadump/wd1007v.bin

![WD1007V-SE1](https://github.com/user-attachments/assets/4e414bc2-c8dc-456c-971c-a1beca67904f)
![WD1007V-SE1-label](https://github.com/user-attachments/assets/cdd2df73-36f7-453e-9f2f-69df093f68e7)

**Comment by a-1103** [comment]
According to attached photos WD1007V-SE1 and WD1007V-SE2 has 32K buffer SRAM.
SRM20256LM10 in WD1007V-SE1.
TC55257BFL-10 in WD1007V-SE2.
It is possible to implement it and report in IDENTIFY DRIVE block.
Also other fields - serial number, Buffer Type, ECC (boards has jumper for it)
My board is WD1007V-SE2 (bios is version 1.51) and it is reported as WD1007V,
SE1 differs from SE2 that it has no floppy, otherways it is the same.

https://www.minuszerodegrees.net/manuals/Western%20Digital/wdcontr.txt
https://www.minuszerodegrees.net/manuals/Western%20Digital/WD1007V-SE1%20and%20SE2.pdf

Here is description of IDENTIFY_DRIVE block
https://www.os2museum.com/wp/identify-esdi-drive/
HDD, of course, is different.
IDENTIFY_DRIVE dump from WD1007V-SE2 - https://www.os2museum.com/files/atadump/wd1007v.bin

![WD1007V-SE1](https://github.com/user-attachments/assets/4e414bc2-c8dc-456c-971c-a1beca67904f)
![WD1007V-SE1-label](https://github.com/user-attachments/assets/cdd2df73-36f7-453e-9f2f-69df093f68e7)
