### ISSUE TITLE
Incomplete x87 emulation

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#507]
More tests with MCPDIag.exe, an intel tool to test 387/467 accuracy. Well....
![20191222-084308-191](https://user-images.githubusercontent.com/16312616/71319531-d333aa80-249f-11ea-973d-34bb1846a905.png)

[Intel387SX.zip](https://github.com/86Box/86Box/files/3992287/Intel387SX.zip)

_Originally posted by @jvernet in https://github.com/86Box/86Box/issues/504#issuecomment-568243401_

**Comment by jvernet** [comment]
Note that DOSBOX make a better job (only fail for Scale test).

**Comment by jvernet** [comment]
8087 emulation code use the double type, I believe ? So that's only 64 Bits, but 8087 emulation need 80 bits isn't ? So long double shoudl be used? Can it be an explanation of the failed tests ?

**Comment by OBattler** [comment]
Yes, it is the explanation. Using 64-bit doubles causes the emulated FPU to be very imprecise.

The problem is that 80-bit is only available on x86 and maybe x64, so this would throw away portability. The other option is software FPU emulation, which I already have in my plans to do for 8087/287/387, but for 486 onwards it's not doable because the performance penalty would show.

**Comment by jvernet** [comment]
GCC can still use long double as 80bits data, therefore, use x87 and not SSE2 instructions when using long double.
MSVC do not, and force long double as double (64 bits) and use only SSE2 maths functions.
Only way: use asm directly, look like it's what DOSBOX do, but DOSBOX is a 32 bits app.
86Box is 32 or 64 bits ?
I never succeeded to set up a working mingw environnement to build 86box on my PC....

**Comment by jvernet** [comment]
Latest  build with new dynarec correct the font problem in OpentStep.

**Comment by rderooy** [comment]
FYI. DOSBox-X since the last few releases has a 100% score on this, at least when compiled with gcc or mingw.
https://github.com/joncampbell123/dosbox-x/pull/3415

**Comment by OBattler** [comment]
This has since been solved with SoftFloat.
