### ISSUE TITLE
Add support for 386 debug registers

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#509]
A Discord user has requested support for the 386 debug registers.

**Comment by MoochMcGee** [comment]
I wrote some code for MAME that implements this fairly decently, so its ideas could probably be adapted for 86box

**Comment by danrevella** [comment]
someone at Varcem told me that they have the ready code to implement in 86box.
An emulation without debug register support IMO is uncomplete...

**Comment by waltje** [comment]
Hi Dan,

That may have been me, a fairly long time ago.

The code I have is the old kernel debugger for (ancient...) Minix/386, which was
implemented as a separate task, next to the kernel itself. This is the "external"
part of the debugger (c.f. "debug.com" ;-), not the i386-internal(-registers) side
of it, though.

--Fred (waltje)


     On Saturday, March 7, 2020, 03:41:11 PM EST, danrevella <notifications@github.com> wrote:  
 
 
someone at Varcem told me that they have the ready code to implement in 86box.
An emulation without debug register support IMO is uncomplete...

**Comment by qeeg** [comment]
Either way, and I'd think @OBattler would agree, given the label he gave this issue, I think we should wait for the next release cycle to implement this, mainly to ensure stability, and also to make sure there isn't a significant performance impact. I also have no idea how exactly we'd implement this in the dynarecs.

**Comment by danrevella** [comment]
I understand.... :-(
My problem is that I live in Italy (C-19 Virus), so maybe that when 3.xx version will be released I just will be death.. :-(
Please excuse for my impulsivity.

**Comment by OBattler** [comment]
It will likely be for v2.20, unfortunately (v2.10 has accumulated enough large CPU changes already).

**Comment by leslietoo** [comment]
Expecting this feature very much, very useful when using debugger like SoftICE, DeGlucker, TurboDebugger

**Comment by danrevella** [comment]
IMO an emulation is not 100% if the processor does not permict use of 386 debug registers, expecially under dos when many old protected copy utilize this ........

**Comment by OBattler** [comment]
I'm sorry but I have a very long list of things to do, and so far, noone else has offered themselves up to actually implement this feature, so it's going to be done when it's done.

**Comment by danrevella** [comment]
I understand, and thank you, maybe in future..... ;-)
