### ISSUE TITLE
MIDI In support

### ISSUE THREAD

**Issue by FreeFull** [86Box/86Box#511]
The MPU-401 interface possesses ports for both MIDI Out and MIDI In. Currently, 86Box lets you direct the MIDI Out to some System MIDI device, but doesn't have option to do the same for MIDI In. This feature would be useful for controlling MS-DOS trackers/music software using a MIDI keyboard plugged into the host computer.

It's notable that besides MAME, I can't find a single PC emulator that supports MIDI In.

**Comment by OBattler** [comment]
Could you link me to the MAME code, please? That way I can see how they did it (and what host API they used).

**Comment by FreeFull** [comment]
https://github.com/mamedev/mame/blob/master/src/devices/bus/midi/midi.cpp
It seems like portmidi is used to handle the host side. https://github.com/mamedev/mame/blob/master/src/devices/bus/isa/sblaster.cpp contains the MIDI code for Soundblaster 16's UART emulation, but I really don't know much about how it's all actually implemented.

**Comment by OBattler** [comment]
Well, it looks like I would need a host MIDI keyboard or something (and a card that can take its input) to test this.

**Comment by FreeFull** [comment]
It should be possible to test this without a physical MIDI keyboard, using https://sourceforge.net/projects/vmpk/ or one of the MIDI keyboards in the Windows store.

**Comment by OBattler** [comment]
OK, thanks! Downloaded and installed this, now I can at least attempt to add MIDI input to 86Box and test it with this.

**Comment by MoochMcGee** [comment]
@FreeFull Hey, please let us know how the newly added MIDI in support works for you! If it's working well with your physical keyboard, we can close this issue.

**Comment by FreeFull** [comment]
It does seem to be working well with MPU-401 + Impulse Tracker. Seems to behave weirdly when testing with both Soundblaster 16 and MPU-401 enabled, four of the white keys in each octave end up getting mapped to the wrong keys somehow.

Also, it'd be nice if the list of MIDI in devices would get refreshed when the Device Configuration dialog gets opened, so 86box doesn't have to be restarted to change it to a freshly opened device.

**Comment by FreeFull** [comment]
Testing with the latest changes, everything I tried seems work well.

Sound Club works as expected with Soundblaster 16 + Standalone MPU-401
Impulse Tracker works with Soundblaster 16, and the MPU-401 midi in checkbox selected in the Soundblaster 16 settings.

Sound Club with Gravis Ultrasound seems to kinda work, but it's hard to test due to #568 

It'd just be nice if it was possible to plug in a MIDI device on the host and pick it for MIDI In without having to close and restart 86Box, but as it is the support definitely seems good enough.
