### ISSUE TITLE
[Question] about memory configuration of ATI VGA cards 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#515]
I write this because I found:

1. The ATI-Edge16 supports only 256kb of VRAM. This card is a low-end implementation of the Wonder 16 which supports 256kb and 512kb configurations. The ATI utility V-TEST.EXE detects 512kb of VRAM on this card. (maybe the  emulation of Wonder 16 can be added to support this amount of ram).

2. The ATI Charger (28800 chip) supports both 256kb and 512kb configurations. V-test.exe utility correctly detects 512kb of ram , but maybe 256kb memory configuration can be added.

3. I'm not sure if ATI VGA 88 supports 512kb of ram or not.

**Comment by OBattler** [comment]
Yes, the memory sizes are wrong - currently, the 18800 series is fixed to 512 kB, which needs to be changed. And I believe that we indeed do not support 256 kB on the 28800 series yet, but that can also be added.

**Comment by OBattler** [comment]
The ATi 28800's are are already configurable and have 256 kB memory as an option.
