### ISSUE TITLE
[Ask] Port the ATI EGA Wonder 800+ emulation from PCem

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#516]
Hello

I would like to ask if can be ported from PCem, the ATI EGA Wonder 800+ emulation. This card has the capability to support a maximum resolution of  800x600, and also supports the 16 color standard  VGA video modes. It is based on the 18800 chipset like VGA 88 and Edge-16.

Thanks!

**Comment by OBattler** [comment]
Yes, I already have it in my plans to port it.

**Comment by OBattler** [comment]
This is now done.
