### ISSUE TITLE
Disk differencing (snapshots)

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#517]
This is a feature supported by many hypervisors and comes in quite handy, when you want an easy way to return to a previous disk state.

The basic idea is that there is a base and a diff image, that are combined to a single emulated disk. All writes would be directed to the diff image, while reads would be done from either base or diff according to whether the requested sector is dirty or not.

Right now, this can be done with copying each "snapshot" to a separate disk image, but integrating it to the emulator would be a nice addition.

**Comment by dhrdlicka** [comment]
This is implemented by MiniVHD.

**Comment by wbolong** [comment]
> This is implemented by MiniVHD.

How to use this in 86Box v4?

**Comment by Thraka** [comment]
@dhrdlicka @OBattler was this closed by accident? I've not seen this feature in the UI nor the documentation.

**Comment by OBattler** [comment]
Create a differencing VHD file.

**Comment by Thraka** [comment]
OK thanks for clarifying. When I see the word "snapshot" I'm thinking of a UI related thing that lets you CREATE a snapshot (move yourself into a different differencing disk automatically)
