### ISSUE TITLE
CTRL key doesn't work

### ISSUE THREAD

**Issue by Dinis1979** [86Box/86Box#520]
**Describe the bug**
I can't fire with the CTRL key in Raptor and Astro Fire.

**To Reproduce**
Astro Fire doesn't allow to redefine keys. It should fire with CTRL, I can't fire.

**Expected behavior**
See above.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.07

**Comment by daviunic** [comment]
We'd need to see your config too, you can upload to it to a file sharing site or paste it on Pastebin.

Is the "Right CTRL is left ALT" option in the Action menu enabled by any chance?

**Comment by Dinis1979** [comment]
"Right CTRL is left ALT" is not enabled and it's the left CTRL that doesn't work.
https://pastebin.com/ChikW3Hz

**Comment by daviunic** [comment]
Thank you, we'll look into this.

**Comment by Dizzy611** [comment]
Unable to reproduce using this exact config in 3.4.1 due to the config being invalid (hard drive attached but no HDC, causes a freeze on boot)

Unable to reproduce with a fixed config (working HDD) either. Left CTRL does fire, even with Right CTRL is Left ALT turned on.

**Comment by OBattler** [comment]
Then this can be closed.
