### ISSUE TITLE
[Q&A] Is there 86Box for Android?

### ISSUE THREAD

**Issue by leesa49** [86Box/86Box#521]
Is there an Android version for 86Box ?

**Comment by daviunic** [comment]
No, at least not yet.

**Comment by nex86** [comment]
BUT!! 
There is Android on 86box 🙃

https://www.youtube.com/watch?v=uGp2ECm9WMk

**Comment by OzzyHelix** [comment]
having an Android port of the app for using old Windows and MS-DOS on an Android Phone would be cool

**Comment by OzzyHelix** [comment]
> having an Android port of the app for using old Windows and MS-DOS on an Android Phone would be cool

maybe it can be done by using FEX to translate some stuff about the current app to an android/arm system
