### ISSUE TITLE
ATT 6300/Olivetti M24

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#522]
**Describe the bug**
1-According to the documentation, M24 can use 720k drive bu also  HD (96TPI) drives, 1.2 or 1.44 Mb.
This do not work with curent version of 86Box -even 720k 3.5 drives do not work).ROM 1.43 wich we have is mandatory to use these drive (and a microswitch setting).
2- It seems that there is a 384k RAM extension board

**To Reproduce**
Add 720k/1.44/1.2 Mb drives: not working at all.

**Comment by daviunic** [comment]
I've tested this with both v2.07 and 2.10 build 2030 and in both cases, 3.5" 720kB drive worked fine (booted PC-DOS 3.30 and displayed contents and size correctly).

5.25" 1.2MB and 3.5" 1.4MB drives indeed don't work. Can you please provide your config so we can determine why 720kB drives wouldn't work for you either?

**Comment by jvernet** [comment]
Reading is working now, but I spent hours yesterday trying without success !
But formating do not work.
And sometime, change the floppy made the emulated system crash (hang and bips).

**Comment by daviunic** [comment]
Which DOS version are you using? Remember that DOS had to be updated too to support new disk formats.

**Comment by jvernet** [comment]
DOS 3.3. It is supposed to know about 720k drives

**Comment by OBattler** [comment]
Is it Olivetti OEM? Because otherwise, it may not be compatible.

**Comment by daviunic** [comment]
I can again confirm that 1.2MB and 1.44MB drives don't work in build 2703 (disk read error etc.). 720k drives seem to work though. According to the service manual (ftp://ftp.oldskool.org/pub/drivers/ATT/6300/AT%26T%20PC%206300%20Service%20Manual.pdf), switches on the mainboard control the number and types of floppy drives that are connected. I'm not sure we implement this correctly (if at all).

**Comment by OBattler** [comment]
The Olivetti M24 does not support 1.2 MB and 1.44 MB drives at all, you have to use the M240 for that.

**Comment by OBattler** [comment]
OK, I checked and it does not access port 3F7h at all. As such, I'm closing this with NOTABUG.
