### ISSUE TITLE
HDD Platter Speed Emulation

### ISSUE THREAD

**Issue by CRTRevivalDreamer** [86Box/86Box#524]
**Is your feature request related to a problem? Please describe.**
Hard disk timings are not emulated in 86Box, which may cause programs to run way too fast.

**Describe the solution you'd like!**
86Box should emulate HDD timings in order to solve this problem.
 
**Additional context**
The most common hard disk drive platter speeds are:

1. 3,600 RPM
2. 7,200 RPM
3. 10,000 RPM
4. 15,000 RPM

**Comment by CRTRevivalDreamer** [comment]
It seems that MAME already does this...

**Comment by OBattler** [comment]
This is now done.
