### ISSUE TITLE
Support for Pentium 2 class systems

### ISSUE THREAD

**Issue by ThePacificGamer** [86Box/86Box#525]
**Is your feature request related to a problem? Please describe.**
There's no support for Pentium 2 class systems so Windows XP or other machines that recommend these types of machines are somewhat slower than the normal speed. Also it doesn't support the Voodoo 2 cards, only 3, 4 or 5

**Describe the solution you'd like**
Support for Pentium 2 or later machines with possibly more newer graphics cards with Ati RAGE 128 cards, Voodoo 3/4/5 and Nvidia Riva cards and Geforce 256
**Describe alternatives you've considered**

**Additional context**

**Comment by tiseno100** [comment]
Problem is, lack of documentation and the complexity of the hardware makes it difficult for this tb achieved. The Pentium II code still exists but not used because its unstable and buggy. Mooch works on the Riva 128 emulation but there's no new progress report as of now.

**Comment by ThePacificGamer** [comment]
> Problem is, lack of documentation and the complexity of the hardware makes it difficult for this tb achieved. The Pentium II code still exists but not used because its unstable and buggy. Mooch works on the Riva 128 emulation but there's no new progress report as of now.

Ok, so that's why, I might be able to see K6 support instead then because the latest version of PCem now supports The K6 CPUs (I assume only the socket 7 ones currently)

**Comment by tiseno100** [comment]
> Ok, so that's why, I might be able to see K6 support instead then because the latest version of PCem now supports The K6 CPUs (I assume only the socket 7 ones currently)

K6 CPU's are available if you compile 86Box with the new dynarec. As far as i know, 86Box-dev builds are using the new dynarec. We don't emulate Super Socket 7 motherboards though as PCem's VIA MVP3 chipset emulation is incomplete(Incomplete IDE controller which causes Linux to kernel panic & other stuff).

**Comment by OBattler** [comment]
This is now marked as for v2.10 and is beign closed because it's done.
