### ISSUE TITLE
86Box Crashing

### ISSUE THREAD

**Issue by OltScript313** [86Box/86Box#537]
Hello, 

As soon as I start 86Box, it crashes... 
That's how it was since Build 2035 only... :/

Same with the optimized version.....

My PC : Windows 7, 32Gb RAM, AMD A10-7700K 3,40Ghz 4C

**Comment by dhrdlicka** [comment]
That's not quite helpful.

Do you see any error messages? Is there more information in the event log? Are you using 86Box with or without the manager?

**Comment by MoochMcGee** [comment]
@dhrdlicka My guess is that the distributed builds are currently missing the portmidi DLL it needs, since build 2035 is when MIDI in support was merged.

**Comment by MoochMcGee** [comment]
Never mind, when adding a sound card (I used the SB16) it crashes at reset...

**Comment by OltScript313** [comment]
Only : « 86Box has stopped working »
I am not using the manager

PS: Now it work, you only had to delete the CFG file, this kind of thing is rare but annoooying...

**Comment by MoochMcGee** [comment]
I tried deleting the configuration file, and the bug I found still persists...

**Comment by dhrdlicka** [comment]
@OltScript313 what config does cause crashes?

**Comment by MoochMcGee** [comment]
Here's the offending line of code for the crash I described

```Thread 1 received signal SIGSEGV, Segmentation fault.
0x0067eadc in midi_clear_buffer () at sound/midi.c:402
402             midi->midi_pos = 0;```

**Comment by OBattler** [comment]
It's fixed now.
