### ISSUE TITLE
Crash when adding a sound card

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#538]
Never mind, when adding a sound card (I used the SB16) it crashes at reset... Then when I restart the emulator, the Sound Blaster 16 is nowhere to be found.

_Originally posted by @MoochMcGee in https://github.com/86Box/86Box/issues/537#issuecomment-573448291_

**Comment by MoochMcGee** [comment]
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0067eadc in midi_clear_buffer () at sound/midi.c:402
402             midi->midi_pos = 0;
```
This is the offending line of code in this case. This function is called from sb_dsp_reset()

**Comment by MoochMcGee** [comment]
@dhrdlicka Please close this, it's fixed.

**Comment by dhrdlicka** [comment]
wish granted
