### ISSUE TITLE
Duke Nukem 3D crashes when launched from Windows 9x with General Midi/Sound Canvas music and Sound Blaster sound effects set

### ISSUE THREAD

**Issue by dgurney** [86Box/86Box#539]
**Describe the bug**
If you attempt to launch Duke Nukem 3D from Windows 9x with settings mentioned in the title, the game will crash. The game will not crash if you use a different combination, such as music on, sfx off, sfx on, music off, or sfx and music both set to Sound Blaster. The game will not crash if you launch it in DOS mode even with the problematic settings combination. Curiously, the crash reason is different on 95 and 98.

**To Reproduce**
As far as I can see, this happens with every Duke Nukem 3D version. I tested the original shareware release as well as Atomic Edition 1.5.
1. Set Duke Nukem 3D to use General MIDI or Sound Canvas for music and Sound Blaster for sound effects.
2. Launch the game
3. Crash!

**Expected behavior**
The game works.

**Screenshots**
![Crash on Windows 95](https://i.imgur.com/jH9THZQ.png) Crash on Windows 95.
![Different crash on Windows 98 SE](https://i.imgur.com/m0F8782.png) Different crash on Windows 98 SE.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box commit: f655585ad82f48ae6e8c246cf12c4401dfe68827

**Comment by MoochMcGee** [comment]
Try the latest commit once it finishes compiling to see if it works.

**Comment by dgurney** [comment]
Dumb or not, this still happens with the latest commit :/

**Comment by dgurney** [comment]
I did some further testing just now, and turns out this happens as far back as the 2.00 release.

**Comment by dgurney** [comment]
This commit seems to be the culprit: 0ea3a1307cf8501ff135e2c79ea93befd1980b5a. Build 1658, the one before this works, but 1659 breaks.

**Comment by OBattler** [comment]
It works now, so it was an emulator bug after all, it seems my redoing of the Sound Blaster IRQ handling fixed it.
