### ISSUE TITLE
Hardware SDL2 freezes if the host gets locked/suspended/hibernated

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#541]
**Describe the bug**
If the host computer gets locked, suspended or hibernated with an 86Box machine running using the SDL hardware renderer, and then gets restored, the machine seemingly freezes until the user switches the renderer.

**To Reproduce**
1. Press `Win`+`L` with a 86Box VM on top
2. Unlock the host PC
3. **The machine appears to be frozen.**
4. Try switching the renderer, the VM should return into fully working order

**Expected behavior**
Renderer survives host session events.

**Screenshots**
![OAuCKjQ3VX](https://user-images.githubusercontent.com/13226155/72225502-65523e80-3586-11ea-96a0-7b41ed328c3a.gif)

**Comment by MoochMcGee** [comment]
TBH, this sometimes happens even if you just alt-tab out of 86box

**Comment by OBattler** [comment]
Does it happen with the SDL Software renderer?

**Comment by dhrdlicka** [comment]
Doesn't seem so.

**Comment by OBattler** [comment]
Closing this because it has been fixed for a while now.
