### ISSUE TITLE
Roland CM-300 Emulation

### ISSUE THREAD

**Issue by CRTRevivalDreamer** [86Box/86Box#542]
**Is your feature request related to a problem? Please describe.**
86Box already has MT-32/CM-32L emulation, but that's not enough for games that could use General MIDI for music.

**Describe the solution you'd like:**
In order for this problem to be solved, we need to have the CM-300 emulated on 86Box.

**Comment by dhrdlicka** [comment]
Is there any library that emulates a CM-300, like there is munt/mt32emu for the MT-32?

**Comment by Mal752** [comment]
You need to use another midi driver like Coolsoft VirtualMIDI Synth or SoundCanvas VA or Yamaha XG Synth to use other Roland GS/GM / Yamaha sounds, and point the MIDI option in 86Box to this.

**Comment by CRTRevivalDreamer** [comment]
> Is there any library that emulates a CM-300, like there is munt/mt32emu for the MT-32?
No, so I suggest we start a sister project to Munt and name it Glim.

**Comment by CRTRevivalDreamer** [comment]
> Is there any library that emulates a CM-300, like there is munt/mt32emu for the MT-32?

No, so I suggest we start a sister project to Munt and name it Glim.

**Comment by MoochMcGee** [comment]
@CRTRevivalDreamer Please be joking.

**Comment by jriwanek** [comment]
There's now <https://github.com/skjelten/emusc> which emulates the SC-55, which the CM-300 is equivalent to.
Builds are available from <https://github.com/nmcgill/emusc/releases>

**Comment by OBattler** [comment]
EMUSC is currently in preliminary stages. But the requested feature is achieavable in 86Box already in two ways - either by loading a SC55 soundfont using FluidSynth or by uing System MIDI and SCVA through LoopMIDI. Therefore, I'm closing this.
