### ISSUE TITLE
ACPI issues on FIC VA503P

### ISSUE THREAD

**Issue by nerd73** [86Box/86Box#545]
**Describe the bug**
During startup, Windows Vista/Windows 7 will usually crash shortly after the bootscreen appears, showing STOP error 0xA5 (ACPI_BIOS_ERROR). Windows XP upgrade setup from 98 hung during startup at around the same point.

**To Reproduce**
1. Choose FIC VA503P
2. Load Vista/7 CD-ROM ISO
3. Wait for BSOD

**Expected behavior**
Windows Vista/7 should be able to at least get to the Preinstallation Environment on an FIC VA-503+.

**Screenshots**
![STOP error 0xA5](https://i.imgur.com/B7hhDdd.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1
 - Version v2.10 Build 2044

**Context**

In PCem's VA-503+, Windows Vista/7 do manage to get to the Preinstallation Environment.

**Comment by nerd73** [comment]
This bug was fixed in Build 2060.

**Comment by TechGuyC** [comment]
I thought this problem only happend on the pcchips m579
