### ISSUE TITLE
Latest Build broke anything below 486

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#546]
**Describe the bug**
Cannot launch 8086Box anymore with 8088/8086/286 Emulation: PC1512/1640 failed with message above, 8088 XT clone crashe, 286 Award ISa crashe

Message 
"rom-load-linear(): Error reading data"

486 Emulation failed with CDROM drivers not loading, it was loading previously?

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/16312616/72430566-01e92c00-3793-11ea-9ade-16e969ea60ca.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Latest build 2053 Regular

**Additional context**

**Comment by MoochMcGee** [comment]
You're missing ROM files in the directory you keep 86Box in. IBM PC (1981) loads fine for me.

**Comment by lemondrops** [comment]
It does crash when the graphics card is set to EGA or VGA.

**Comment by MoochMcGee** [comment]
Oof, it does.

**Comment by jvernet** [comment]
2052 build work, 2053 do not work.

i'm using the current set of ROM.

**Comment by MoochMcGee** [comment]
@jvernet I'm literally using the same build as you.

**Comment by MoochMcGee** [comment]
Ah, I see what the problem is... You're supposed to set the video card to Internal when using that machine.

**Comment by jvernet** [comment]
Build 2053: 
Amstrad PC1512 with this config: crash. Do not crash with previous. Same for 8088, 286 and so on

[Machine]
machine = pc1512
mem_size = 640
cpu_use_dynarec = 0
time_sync = local
cpu_enable_fpu = 1

[Video]
gfxcard = internal

[Input devices]
mouse_type = internal

[Other peripherals]
hdc = xtide
isamem0_type = ems5150

[Amstrad PC1512 (video)]
display_type = 0
codepage = 3
language = 5

[Sound]
sndcard = adlib

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Hard disks]
hdd_01_parameters = 17, 6, 615, 0, ide
hdd_01_fn = C:\Users\jvernet\Desktop\Oldies\PCem\PCEM-AMSTRAD-H6S17C615 30Mb - MSDOS3.30.img
hdd_02_parameters = 26, 4, 615, 0, ide
hdd_02_fn = C:\Users\jvernet\Desktop\Oldies\86Box\VMs\PC1512\pc1512games.img
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1

[Everex EV-159 RAM 3000 Deluxe #1]
size = 1024
start = 0
length = 0
width = 0
speed = 1
ems = 1
base = 0258

[Floppy drives]
fdd_01_turbo = 1
fdd_02_type = 35_2dd
fdd_02_turbo = 1

[Micro Mainframe EMS-5150(T) #1]
size = 1024
base = 0208

**Comment by MoochMcGee** [comment]
Ah, it's the XTIDE causing the issue.

**Comment by jvernet** [comment]
Looks like XTIDE is the issue.

**Comment by MoochMcGee** [comment]
@jvernet See if this fixes your issue https://github.com/86Box/86Box/pull/547

**Comment by ppgrainbow** [comment]
I'm on build 2055 (A575BD7E) and I can reproduce the issue. In the OUTPUT.LOG file, I'm getting a "rom_load_linear(): Error reading data" when attempting to switch to a VGA graphics card on a Dataexpert 286 emulated machine with a AMI BIOS.

Something appears to be wrong with the latest build.

**Comment by OBattler** [comment]
See if build 2056 fixes that.

**Comment by jvernet** [comment]
It's OK: it was a problem with XT/IDE.
Why my own build do not have any reference to the Build number ?
8BoxManager do not recognize my build.

**Comment by dhrdlicka** [comment]
The build number gets added by Jenkins. Adding it to local builds would be pointless, because the source code doesn't include any build number information anyway.

The 86Box Manager warning is just informative anyway.

**Comment by daviunic** [comment]
> It's OK: it was a problem with XT/IDE.
> Why my own build do not have any reference to the Build number ?
> 8BoxManager do not recognize my build.

86Box version detection in Manager is only for informational purposes, it doesn't affect the functionality in any way. It's just there to inform you that using unofficial builds can potentially result in issues I probably won't bother fixing.
