### ISSUE TITLE
Latest build: perofrmance issue

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#548]
**Describe the bug**
Another thing I noticed: last build have very HIGH demand in CPU/GPU.
On my laptop (Core i5 Skylake), fan goes crazy after few minutes.
486dx4 emulation doesn't achieve 100% (mostly 70/80%).
3D Process of GPU is more than 30%., CPU is about 40%.

Change from SDL Hardware to SDL Software let the emulation achieve 100% speed while GPU drop to 0 and CPu dropt to 25%

Nerver had this before.

**Comment by MoochMcGee** [comment]
Weird, because I haven't had this issue at all. Honestly sounds like a graphics driver issue to me. Try updating your GPU drivers.

**Comment by ppgrainbow** [comment]
That sounds weird.

I'm using a PC with a AMD FX-4300 quad-core processor and when emulating a 80486DX2 at 66 MHz, the CPU speed maxes out at close to 100% when in DOS. However, in Direct Access 5.19, the emulated CPU speed drops between 70% to 90%.

When the emulated CPU processor is dropped to a 50 MHz 80486 with single clocking, the emulated CPU speed maces out at 100%.

So, it might be either a graphics card issue or the speed of the CPU.

**Comment by OBattler** [comment]
I actually confirm that SDL Software renderer is faster now.

**Comment by jvernet** [comment]
Activate Dynamic Compiler help, but I do not have to actiovate it to achieve 100% in 486 mode.
GPU usage (GTX 960Ti) is about 50% in SDL Hardware and fan of the card goes crazy....

**Comment by OBattler** [comment]
SDL Hardware uses DirectX 11 if it is available, maybe the 960 Ti doesn't handle it well? Also make sure you are using the graphics drivers from the Nvidia site and not the ones Windows itself installs.

**Comment by OBattler** [comment]
I think this has been established as the SDL Hardware renderer not being accelerated or something on MacOS Wine. So this can be closed.
