### ISSUE TITLE
Implementing the Apollo VP3 chipset.

### ISSUE THREAD

**Issue by tiseno100** [86Box/86Box#549]
The Apollo VP3 is the predecessor of the already emulated VIA MVP3. It's addition will give us the capability to add AMI based Super 7 boards like the PC Partner ones(not that we can't use the already existing MVP3 chipset for that).

**Comment by MoochMcGee** [comment]
It does use the same southbridge, so it is likely quite possible.

**Comment by OBattler** [comment]
The VP3 is Socket 7, not Super Socket 7. The MVP3 is basically the Super Socket 7 upgrade of the VP3.

**Comment by dhrdlicka** [comment]
Added in b8b198a56a78d608a4df076ebde5cb81b23c67f2
