### ISSUE TITLE
Program does NOT compile under ANY circumstances

### ISSUE THREAD

**Issue by TheVirtualComputer** [86Box/86Box#554]
I followed the entire series of build instructions to the letter (at least I thought I did), yet trying to compile just gives me this:

```
$ make -j4 -f win/makefile.mingw
pc.c
config.c
io.c
apm_new.c
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
gcc.exe: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
gcc.exe: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
compilation terminated.
gcc.exe: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
make: *** [win/makefile.mingw:746: io.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [win/makefile.mingw:746: apm_new.o] Error 1
compilation terminated.
make: *** [win/makefile.mingw:746: config.o] Error 1
gcc.exe: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
make: *** [win/makefile.mingw:746: pc.o] Error 1

Firstname@WIN-M3O7UCP92QD MSYS ~/Documents/NProject/src
$

```
Why is this happening? I have ALL the required libraries installed as stated in the build instructions and yet it still doesn't work. Did whoever put those instructions up just assume that they worked because he/she put them together without actually testing them, or is it something else?

EDIT: I still can't get this to work. Why is it that people seem to always put in such instructions without actually TESTING them first? Either the person who put the instructions together didn't do it right or their development environment is not 100% identical to the one that users are being instructed to create.

I really don't want to sound like I'm flaming anyone (because that was not my intention), but it seems to me that people just slap a bunch of instructions/code together without testing it correctly. They just assume that "because I put it together and everything fits together therefore it works just fine", without actually testing it to see if it actually behaves as intended. At the very least that's what I would do if I was putting together anything as essential as a development environment.

**Comment by TheVirtualComputer** [comment]
I'm sorry if I came off as being a bit harsh in my previous message, though I did eventually get it to compile in the end, using an alternate development environment, available from the link below:

[](https://mega.nz/#!v193zSxa!kajn4FUE4TqQyPi_7JKrR-F_FGghbQDYlEdPq1AXMMc)

**Comment by TheVirtualComputer** [comment]
https://mega.nz/#!v193zSxa!kajn4FUE4TqQyPi_7JKrR-F_FGghbQDYlEdPq1AXMMc

**Comment by dhrdlicka** [comment]
Build instructions are correct, you are just using the wrong shell. Use the MinGW 32-bit shell (`mingw32.exe` in the MSYS root) as the guide tells you, not the MSYS one.
