### ISSUE TITLE
Windows 3.x functionality broken

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#560]
*** BUG DESCRIPTION ***
On the emulated Dataexpert SX495 rev 1.0 machine, I have managed to run Windows 3.0a on the Adaptec AHA-1542a for quite a while without problems.

However, since build 2066 (commit 4d7724d8), Windows 3.0a stops responding at the splash screen (hangs) and doesn't proceed any further:

![20200118-095432-961](https://user-images.githubusercontent.com/32658796/72662062-e9e1fa00-3996-11ea-8376-78665afc00e1.png)

Windows 3.0a in Standard and Real Mode and Windows 3.1 in Standard Mode are known to work without problems.

And when I attempted to load Windows 3.1x from the emulated 100 MB Iomega ZIP drive image on SCSI ID #6 on the Adaptec AHA-1542B, Windows 3.1 hangs with a blinking cursor:
![20200118-095519-552](https://user-images.githubusercontent.com/32658796/72662092-6f65aa00-3997-11ea-9fbb-a4353031d3c7.png)

Also on the U-BOARD 486 with Award BIOS, Windows 3.11 doesn't seem to load correctly:
![20200118-090946-939](https://user-images.githubusercontent.com/32658796/72662114-f9157780-3997-11ea-84fc-33d5c640c144.png)

Builds 2059 through 2065 were the recent versions that allowed Windows 3.x to work.

Current 86Box.cfg file for the SX495 can be found here: https://pastebin.com/EagZuaRK

Correct 86Box.cfg file for the U-BOARD 486 (Award BIOS can be found here as well: https://pastebin.com/Y5s1jpwv

Please investigate this issue what what could be causing this.

Thanks. ^^

**Comment by OBattler** [comment]
I ran your Windows 3.0a VM, exact same hang also on build 2065. Changed the IRQ of the SCSI controller from 9  to 11, and the hang is gone even on the latet build. IRQ 9 is known to be unstable and even Adaptec's official documentation advises against using it.

**Comment by ppgrainbow** [comment]
I selected IRQ 11 and it worked. I suspect that selecting IRQ 9 or IRQ 15 caused the hang and is known to be unstable.

**Comment by OBattler** [comment]
Using the AHA-1540B with memory managers is also not recommended, I recommend using the AHA-1542CF as it behaves much better. I've had problems with the AHA-1540B even with EMM386, and they are known, documented problems that also occur on real hardware.

**Comment by ppgrainbow** [comment]
Thank you for explaining this. Have you also had problems with the AHA-1542C as well? For some reason, I'm even having problems trying to move the mouse when exiting the MS-DOS prompt and have to reboot.

The IRQ setting is set to 11, BIOS address is D000h and DMA is set to 6. :(

Should I post the contents of the CONFIG.SYS and AUTOEXEC.BAT files?

**Comment by OBattler** [comment]
Look in the nvr folder and make sure you do not have a residual AHA-1542CF NVR there, I believe that if you do, that will override the IRQ etc. you have configured in Settings.

**Comment by ppgrainbow** [comment]
I don't think that I have a residual AHA-1542CF NVR located at the E:\214UEUBD\NVR directory, but in the settings, I had to remove the duplicate AHA-154xCF settings from the 86Box.cfg file.

I'll upload the contents of the IDE and SCSI hard disk images, 86Box.cfg file and NVR over to the 86Box FTP with a note describing the problem as much as possible and have you look at the issue.

**Comment by OBattler** [comment]
I think this can be closed now.
