### ISSUE TITLE
Matrox adapter STILL fails on VIA MVP3

### ISSUE THREAD

**Issue by TheVirtualComputer** [86Box/86Box#565]
I have some fatal issues to report here, so I'm going to make it as concise as possible. I know that I sound harsh, but it's because I'm the one person here who actually cares to TEST anything first before putting it into a release.

1. The so-called "fix" for the Matrox adapter DOES NOT fix the problems when running it on the VIA MVP3 as claimed. It still black screens. Did anyone here even TEST it before adding it into the latest releases?

2. On an even later build, the latest build just displays a black screen when selecting a VGA adapter, and when selecting any other type of adapter, the program crashes. This behavior occurs with the Intel Premiere/PCI and Intel Premiere/PCI II systems, but most likely affects other systems, especially given that the VGA now fails to run even on an IBM PC or PC/XT.

From what it looks like to me, this is yet another example of people throwing code together without actually testing it first. Just because something compiles doesn't mean that it actually works. At the very least I would test something thoroughly first before even considering it finished, let alone releasing it to the public. I really think that this repository needs stricter rules to make sure that things like this don't happen again in the future, like for example, testing every last commit to make sure that it runs (not just compiles, but is actually functional) before adding it into the repository.

I know that I sound harsh, but in my experience it is very poor coding practice to add something into a program without testing it first, and even worse when such code makes it to release. It's not that I don't care about the developers here, but rather is BECAUSE I care about them that I am reporting these issues as soon as possible. I have the greatest amount of respect for the developers here as anyone; if I didn't then I wouldn't be reporting these bugs to warn them that they're doing something wrong.

**Comment by dhrdlicka** [comment]
Your feedback is of course valuable, however, please understand that code committed to the `master` branch is **unfinished** by nature. It can, and does contain bugs. This is the rule in most open source projects, and complaining about poor coding practices won't achieve much.

**Comment by TheVirtualComputer** [comment]
I understand this, but people should at least still test things like this thoroughly anyway. If it was my repository (and I'm about to have one of my own soon but I'm still in the process of setting it up) then I would certainly test everything thoroughly inside the program itself before making it available. And I certainly wouldn't claim to have "fixed" something without actually testing it first - the whole point of testing such changes is to verify that such issues have actuallly been fixed.

**Comment by TheVirtualComputer** [comment]
Anyway, the main reason why I posted this was still because of the problems that I found, including the issues with the Matrox adapters, which by definition should run just fine on a machine with a VIA Apollo chipset especially when you consider that there were actually machines available that shipped with that combination, and that was the main reason for why I was testing that type of configuration in particular.

**Comment by MoochMcGee** [comment]
Listen, buddy, sometimes you need other people to test your code as well, before you're done with it, so you find bugs more quickly and easily. That's why they're called nightly builds, not stable builds, Karen.

**Comment by OBattler** [comment]
The Matrox'es POST just fine on the VIA machine on my end. I did test it before I committed it. But, one of today's commits might have broken it again, I need to see.

**Comment by tiseno100** [comment]
The Matrox MGA card & the VIA MVP3 upon all are unfinished & unstable. They are incomplete on PCem so imagine on 86Box. We thank you for noticing but still, try giving logs & other stuff needed to help.

**Comment by TheVirtualComputer** [comment]
OBattler: Was the build that you were using compiled from/identical to the code made available to the source repository, or is your emulator code different from what you made available to the public?

**Comment by MoochMcGee** [comment]
Mate, you do realize that these developers owe you nothing right? We work on this for free, in our spare time, and do not work on your schedule or pay.

**Comment by OBattler** [comment]
TheVirtualComputer, i found out it actually is my fault, I forgot to commit the actual file that fixed it. I committed it now. I sincerely apologize for it.

**Comment by TheVirtualComputer** [comment]
Thanks, I'll try that.

**Comment by TheVirtualComputer** [comment]
It actually appears to work now. Of course, I'll still need to finish testing it under Windows 95, but so far, everything seems to be going in the right direction.
