### ISSUE TITLE
Are BIOS setup disk needed for specific machines?

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#567]
Hello!

I recently tested the new Samsung Deskpro 286 and Goldstar 386SX, but both machines do not seem to have a setup option in the BIOS. Does anyone know where I could find these setup disks to configure these machines?

Thanks in advance!

**Comment by OBattler** [comment]
Yes, those need their SETUP diskettes. I'm going to ask Tiseno100 about them.

**Comment by tiseno100** [comment]
Goldstar 386 & Deskmaster 286 require SETUP diskettes yes. Try getting GSETUP. It's a common tool for setting up the BIOS of machines of that era and works extremely well for me.

**Comment by Fenix770** [comment]
Hello!

The utility has almost all options to configure the machines.  I know it is not top priority but I found a dumped Bios in vogons. I don't know if it is the same rom Bios, but it claims to be a SCAT chipset.
The only absent feature in gsetup program, is the ability to configure the SCAT 82C235 EMS chipset, which is already emulated in other 286 machines.

**Comment by tiseno100** [comment]
Yeah a big problem is that i don't have the exact DeskMaster 286 setup program sadly. The machine, even though was made by Samsung, it's very unknown unlike DeskMaster 386. Maybe you can configure SCAT's EMS under DOS, try looking for that.

**Comment by telanus** [comment]
I know it's a bit late but this one worked for me: http://s000.tinyupload.com/index.php?file_id=05728750818155245375.

It's handmade, The files originally comes from [here](http://edv-janssen.synology.me/ct_treiber_service/samsung/computer/files.htm) but it no longer host them, but was backed up on [vogons](https://www.vogons.org/viewtopic.php?p=854732#p854732) it's a elf-booting image.

**Comment by Fenix770** [comment]
Thanks for the response!

I found that disk image on vogons site some days ago. I tested the software, and works perfectly, including the SCAT EMS chipset emulation. The Setup BIOS is similar than the SPC-4200P. This machine, also supports 2Mb ram as maximum.
