### ISSUE TITLE
Gravis Ultrasound emulation does not work

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#568]
The bug:

The GUS Sound card reproduces the music and sound efects randomly at incorrect time and then no other sound can be heard.

To reproduce:

Tested with the lasted commit with the playmidi DOS music player and Windows 3.1 and the setup utility does not find any DMA/IRQ available.

It worked correctly in 86Box v2.07.

Also an old bug is still present, in all versions of 86box and also PCEM: 

If EMM386 or any other 386 memory manager is loaded then:

1. The setup utility will crash when testing the ports for SB emulation
2. The SBOS emulator will also crash the system if it is loaded at DOS prompt.

PD: Also Itried DosBox, but it does not emulate the NMI required by SBOS emulator, and also does not emulate the presence of VCPI required for Mega-EM emulator.  For this a real ms-dos must be booted from an image file.

**Comment by Altheos** [comment]
I confirm that this MIDI bug is present since build #2035 and the midi_in branch merge.
If you use build #2034 everything is fine.

For the "SBOS" bug it needs testing on real hardware.

**Comment by TC1995** [comment]
I've fixed this anyway.

**Comment by Fenix770** [comment]
PD: I confirm the MIDI bug is fixed now. I don't have the real sound card to test its behavior respects SB/Roland emulation, in spite of that, I suspect the presence of a 386 memory manager was expected because: 

1. The setup utility requires 550kb of conventional DOS ram memory, so it was a common practice for the 386/486 users to load the drivers high, with EMM386 or some other software. 

The only alternative is a clean bootdisk without any device driver loadad.

2. The Mega-em  driver/emulator was 3.0 launched late in 1995. It merges, the old Mega-em 2.0x, SBOS and Utramid in a unique device driver. However, as this software requires a VCPI capable EMS driver like the old Mega-em and also uses the SBOS routines is practically impossible to run, because, either, if there is no EMS driver refuses to run or if it is present it lock up the system.

**Comment by OBattler** [comment]
I think this can be closed.
