### ISSUE TITLE
"Fullscreen stretch mode" set to "Integer scale" doesn't seem to work

### ISSUE THREAD

**Issue by madswolff** [86Box/86Box#574]
When I choose *View > Fullscreen stretch mode > Integer scale* the behavior is similar to when I choose *View > Fullscreen stretch mode > Square pixels (Keep ratio)*. The view is simply scaled to fit the height of my display.

I would expect the *Integer scale* setting to scale the view by the largest possible integer resulting in every pixel having the exact same size. Possibly with a black margin around the view.

This feature works perfectly in PCEm. I want to switch from PCEm to 86Box for playing old DOS and Windows games, but for me nearest-neighbor integer scaling is a must. Otherwise I have to choose between blurry or uneven pixels in fullscreen. 

Is this a known bug or is there anything I can do to resolve the issue on my system?

*(I'm on a Windows 10 machine with an old Intel HD Graphics 3000 gpu, but I don't believe this has any significance.)*

**Comment by OBattler** [comment]
Integer cale should be siilar to Square pixels, just scaling to the largest possible resolution it can fit on the screen that is an integer multiply of the guest resolution. I need to look into why that does not occur.

**Comment by OBattler** [comment]
I did make it work, however with SDL (Hardware), it's still blurry, which makes sense since it's still upscaling a source image to an integer multiple of the source resolution. I have no idea how to make SDL (Hardware) not blur, since I believe that's done on the DirectX side (which what SDL ends up using as the backend) and I'm not sure it's even togglable, though on your side you could just switch the renderer to SDL (Software) and it won't blur.

**Comment by OBattler** [comment]
OK, it's committed. If it still blurs with SDL (Hardware), just switch to SDL (Software).

**Comment by madswolff** [comment]
Thanks, that was quick! It now works as expected (I can just use SDL (Software) for nearest-neighbor interpolation).

*But* the fix has exposed 2 tiny related bugs (in both SDL (Software) and SDL (Hardware) mode):

1. When the emulated machine changes resolution (for example when starting Windows at 1024x768 from DOS), the view doesn't update. It freezes until I leave fullscreen mode and enter it again.
2. After leaving fullscreen mode the mouse pointer is confined to the area where the fullscreen view was before. Switching focus to another application brings the mouse back to normal.

**Comment by OBattler** [comment]
Yes, I confirm both bugs. No idea why #1 happens, but last I remember, it was confided to SDL (Software). As for #2, I think I need to make it resize the SDL Window to full screen before releasing mouse to unclip the cursor.

**Comment by OBattler** [comment]
Since I can no longer reprouce either bug, I'm closing this.
