### ISSUE TITLE
ATI EGA 800+ 800x600 video mode does not work on windows 2.x

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#575]
**Describe the bug**

I followed the procedure to install the extended 800x600 video mode on Win 2.x. I tried Windows 2.11/286 and 2.03. 

There are basically two bugs. 

1. The installation disk say sthat a multisync monitor is not present, but this error can be ignored.
then the setup disk install the driver on the setup disk and start the Windows installer.

2. Windows freezes on the startup screen

The startup screen says ATI VGA Wonder, not EGA, but since this card uses the same 18800 chipset, it may not be an error, and the setup driver, disk seems to be genuine.

Procedure:

The EDRIVER.EXE file must be executed from dos prompt. 

**Note:** In DOS 5.0 and latter SETVER.EXE must be loaded in config.sys. (it uses the win200.bin entry). The disk must be in drive A. Can't install from B drive.

Driver disks:

[ATI EGA 800+ Drivers.zip](https://github.com/86Box/86Box/files/4087752/ATI.EGA.800%2B.Drivers.zip)

PD: I also found the drivers for 800, not the 800+. It has drivers for lower resolutions, like 720x410 and 800x560. But the files must be replaced manually as indicated in the readme file.

[ATI EGA 800 (NOT PLUS).zip](https://github.com/86Box/86Box/files/4087835/ATI.EGA.800.NOT.PLUS.zip)
 
**Screenshots**

![20200120-203104-215](https://user-images.githubusercontent.com/31600563/72755993-ad86e780-3baa-11ea-9049-bce0341d1844.png)

![20200120-202533-667](https://user-images.githubusercontent.com/31600563/72755898-61d43e00-3baa-11ea-8b72-76ab785f11f4.png)

Same  bug is present in Pcem.

Thanks!

**Comment by OBattler** [comment]
VGA Wonder is not EGA Wonder, they are two different cards.

**Comment by Fenix770** [comment]
I tested the setup disk drivers. I found that the monitor must be configured as multisync. Windows 2.03 starts, but part of the screen cannot be seen. I suspect the presence of multisync monitor is not emulated.
The EGA test utility included in the EGA wonder (not the plus) is unable to test the 800x560 screen resolution and say there is no multisync monitor.

Screenshots:

![20200121-022640-783](https://user-images.githubusercontent.com/31600563/72770673-56e6d100-3bdd-11ea-9c42-ebb9c5adc2d9.png)

![20200121-023329-354](https://user-images.githubusercontent.com/31600563/72770684-5fd7a280-3bdd-11ea-9d26-903b6874c225.png)

![20200121-023338-603](https://user-images.githubusercontent.com/31600563/72770697-6534ed00-3bdd-11ea-8d7e-60f068b29d69.png)

**Comment by Fenix770** [comment]
on the page 7 of the manual of the card, says t supports VGA mode 11 and 12. 
The manual of the ATI card is here
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwiR_O7MoKznAhVxBtQKHeuqBlwQFjAAegQIAhAB&url=http%3A%2F%2Fwww.vgamuseum.info%2Findex.php%2Fcomponent%2Fk2%2Fitem%2Fdownload%2F76_7950870e9059d41b323f7495017c9ba5&usg=AOvVaw0BRClMZ8u14adSaHknEaoV

**Comment by Dizzy611** [comment]
Was able to reproduce this bug on 3.4.1, running the Windows x64 build. Specifically, following the procedure given in the first post I got the same error about the mode not being supported and Windows 2.03 still crashes on the first screen where it mistakenly calls it a VGA Wonder.

I was not able to get Windows 2.03 to properly start, am not sure what's meant by "the monitor must be configured as multisync" (where?). EGATEST continues to say 800x560 is not supported with this monitor.

Suspect this might have something to do with the monitor type selection in 86box? The only monitors selectable are 515x monitors, none of which would likely count as multisync. If it was previously possible to attach a multisync monitor in 86box, it is not currently.
