### ISSUE TITLE
[Correction] The Micronics 09-00021 board is for 386 DX CPUs

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#580]
First, I got a 32-bit protected mode error when trying to run Win 3.1.  Later I found in vogons site that this board, Micronics 09-00021, has an Intel A82385 chipset, which, also, found this is a 386DX board. The latter number the serie 25 or 33  may be the clock frequency. 

[https://www.vogons.org/viewtopic.php?f=46&t=60356&p=674272&hilit=micronics%2009%2009-00021%2000021#p674272](url)

Also in e-bay i found a cpu  with a number A82385-25 , and says it socket is PGA-132, if recall correctly that is socket is for 386 DX cpus and PGA-100 is for SX cpus.

[https://www.ebay.com/c/1972887159](url)

1. I don't know if the bug is related or not to wrong CPU type identification.
2. The machine seems to have built-in support for MFM/RLL controllers and different hard disk number types (like the DTK 386-sx). But I just don´t know which geometry (C/H/S) they are, and if they are emulated either.
The geometry/number may be different in each board and if this is not emulated may be I can use one of the already implemented MFM/RLL controller instead.

**Comment by tiseno100** [comment]
Hmm i did a recheck and actually it is a 386DX board indeed!. Also the chipset of the Motherboard is NEAT, not the 82335.

Here's a pic of the board. https://www.vogons.org/download/file.php?id=69167&mode=view

**Comment by Fenix770** [comment]
The C&T NEAT chipset has a 82C212 chip and NEATsx has 82C812, according to UMB_DRVR utility.

Of the recently  added machines, none of them seems to have any of C&T NEAT, The Deskmaster has an C&T SCAT 82C235 chipset. 
However the emulation of NEAT chipset implemented in AMI 286 BIOS is not complete, and its configuration is complex because it has a lot of technical options and the BIOS was launched in 1987. 
Maybe the  latter NEAT 286 mainboard has an easier configuration of EMS memory, but will be only useful with a working emulation.   

Here I upload the Umbdrvr utility. It has de ability to load high device drivers on some of these chipsets and also has information of chipset numbers and their names the umb_drvr.doc file.

[UMBDR522.ZIP](https://github.com/86Box/86Box/files/4111112/UMBDR522.ZIP)

**Comment by tiseno100** [comment]
The C&T 82C206 is the NEAT chipset while there are clones of it (TACT82206, UMC 82C206L, OPTi 82C206). 82C212 is the EMS controller. Although 82C206 looks like an IPC controller to my eyes(Remember NEAT was a series of chips which were combined later by SCAT).

For the Headlands. There are the Phoenix 286 and Quadtel 286 clones in 86Box(their BIOS aren't included in the romset). Phoenix works flawlessly but Quadtel hates 86Box's FPU emulation and doesn't like HDD controllers that much. I had the Headland IQS too but removed it as yes the HT12 isn't emulated.

**Comment by tiseno100** [comment]
Apparently from what I've read on the NEAT datasheet, the 82C206 is the IPC controller(A VLSI implementation of common AT peripherals). So this board is just pure TTL logic. Anyways i'll make a new PR with the moved Micronics board.

Apparently this board's name is "I-Cache board" and comes under 2 revisions, 09-00010 and 09-00021.

http://www.elhvb.com/mobokive/Archive/Micronics/00021.txt

**Comment by Fenix770** [comment]
The 387 FPU is the same for 386 SX and the DX. (Like the 8087 FPU  for 8088 and 8086 machines).
The 386 SX has 32 bits internally and a 16 bit external bus. The 386 DX has 32 bits internally and externally.   

According to the book "DOS beyond 640 kb". In, Page 224 of the book, says, the 386 SX cpu has 100 pins and the 386 DX has 132 pins.

Here is the link
https://the-eye.eu/public/Site-Dumps/RemoteCPU_Archive/DOS_Beyond_640K_2nd_edition.pdf

A 386 DX motherboard cannot use a 386 SX cpu, because they have a different CPU amount. And, I believe, different memory controllers.

**Comment by ppgrainbow** [comment]
tiseno100, looking at information on the part number 09-00021, it's a **Micronics 386-I Cache rev 09-00021** motherboard with supports for up to 8 MB of RAM on the mainboard and up to 16 MB of RAM total using a memory expansion slot.

By the way, since the board has a on-board MFM/RLL controller with 32 hard drive types, does anyone know the full list of hard disk drive capacities and geometries that corresponds to the 32 hard drive types?

![20200126-023756-099](https://user-images.githubusercontent.com/32658796/73129860-d2f86480-3fa1-11ea-8254-27d4e668286c.png)

Obviously, this BIOS can take up to four MFM or RLL drives if I'm correct.

**Comment by Fenix770** [comment]
Hello.

I have the same question. I tested a 20mb (Type 13) MFM hard disk that used with Xebec controller and works with the internal controller in this machine. But I don't know about the other sizes. Type numbers and geometry of the disk may be different in each machine.

I found a 32 bit protected mode error  when I tried to run Win 3.1 with Aculogic IDE XT and PC/AT IDE XT.
The 20mb hard disk has Win 2.0 and it works in real mode only.

**Comment by ppgrainbow** [comment]
I have revealed the hard drive types for the Micronics 386-i CACHE emulated board and I'll upload it to the Pastebin shortly. :)

The hard drive types were revealed using a utility called System Snooper that I booted off of drive A. :)

**Comment by ppgrainbow** [comment]
Okay, here is the MFM/RLL hard disk drive table to set up the on-board MFM/RLL hard disk using the CMOS setup: https://pastebin.com/Piac4NRM

Do not use hard drive types 15, 24, 25 and 26 as they're reserved. Any attempts to set up a hard disk drive using these reserved drive types using FDISK will result in a Divide Overflow error.

Unless you intend to use a SCSI adapter, the largest drive that the emulated board will support is 127.5 MB for MFM and 195 MB for RLL.

**Comment by tiseno100** [comment]
I'll check stuff about this motherboard more. It looks and is very picky. I have also the Phoenix BIOS variant of it but it gives me memory issues.

**Comment by ppgrainbow** [comment]
That sounds good. As for the Phoenix BIOS version of the Micronics 386-I CACHE, getting  loads of memory issues doesn't sound too good.

I'm wondering what could be causing the memory issues?

**Comment by OBattler** [comment]
I'm closing this since this issue has been fixed, the other issues can be opened separately.
