### ISSUE TITLE
Micronics 386-I CACHE board issues

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#582]
I bet that this bug hasn't been reported yet, I think that I have a problem with the emulated Paradise PVGA1A when run on the Micronics 386-I CACHE 09-00021 emulated mainboard, the screen stretches wide when the 640 x 480 @ 8bpp driver is used under Windows 3.0:
![20200126-200935-754](https://user-images.githubusercontent.com/32658796/73141103-12bc5c00-4035-11ea-914d-8e1b468dbdf4.png)
I can't seem to remember which build caused this, but I don't know if this has been tested on PCem v15 or on DOXBox. Can anyone reproduce this issue using a real or emulated graphics driver?

With the 800 x 600 x 4bpp driver, it works without problems:
![20200126-201646-226](https://user-images.githubusercontent.com/32658796/73141170-bb6abb80-4035-11ea-9846-f769641ed0b7.png)

Other software that uses the 640 x 480 x 8bpp driver are affected by this bug. For example, NeoPaint for DOS using the 640 x 480 x 8bpp mode:
![20200126-201954-531](https://user-images.githubusercontent.com/32658796/73141195-2caa6e80-4036-11ea-93e6-0ca8e15862e0.png)

NeoPaint for DOS works in 800 x 600 x 8bpp mode:
![20200126-202050-538](https://user-images.githubusercontent.com/32658796/73141203-4c419700-4036-11ea-92f6-805bec8d4e7d.png)

To run NeoPaint with the Paradise driver, type NEOPAINT /C2,-1,1024

Here's the current 86box.cfg file if you're interested: https://pastebin.com/ZfPQZiH9

I eventually tested the Paradise PVGA1A display in Windows 3.0 when run on the Dataexpert SX495 r1.0 emulated board and it seems to work fine.

Also, I'm getting a black screen and blinking cursor when the Trident TVGA 8900B is used with the Micronics 386-I CACHE board.
![20200126-203354-397](https://user-images.githubusercontent.com/32658796/73141370-24533300-4038-11ea-8ab2-c06e8cae0701.png)

Since this board is new to 86Box, we should try to be aware of this and try to fix these bugs if we can.

Thanks. :)

**Comment by tiseno100** [comment]
Ill try doing some excessive testing on the Micronics i-Cache board surely. I haven't tested Windows in it. Only DOS 5.

**Comment by TC1995** [comment]
Windows 3.0 appears to run fine here on the Micronics i-Cache board.

**Comment by tiseno100** [comment]
> Windows 3.0 appears to run fine here on the Micronics i-Cache board.

According to his issue. It's caused on specific cards. Tandon BIOS are a bit picky ngl.

**Comment by TC1995** [comment]
Well, I've also tested the TVGA there, works fine, might need to try others.

**Comment by ppgrainbow** [comment]
> 
> 
> Well, I've also tested the TVGA there, works fine, might need to try others.

I see that you did test the Trident TVGA 8900D. Have you tied the Trident TVGA 8900B yet?

**Comment by ppgrainbow** [comment]
Well...as far as I know. I'm taking a good guess that the issue might be the fact that the Intel 82386 cache chip for the Micronics 386 I-CACHE is not implemented. According to the datasheet, the cache controller is entirely logic and has no registers. And since 86Box doesn't emulate cache, I suspect that this emulated motherboard may have to be dev-branched or replaced with a better working 386(DX) PC.

I just switched to the Paradise WD90C11-LR graphics card and the POST reports [60:00] Ex.p Adapter Installation Failure, but other than that, the machine boots and which the graphics card, I can run Windows 3.0 and NeoPaint in resolutions up to 800 x 600 @ 8bpp.

**Comment by OBattler** [comment]
Looking at the Paradise code - I think this has long since been fixed by TC1995's changes, so this can, therefore, be closed.
