### ISSUE TITLE
EMM386  errors on machines with RLL controller

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#583]
**Describe the bug**

1. I installed MS-DOS 4.01 and Windows 2.11/386.
Windows works fine, but there is a bug with the EMS memory. 

Explanation: The most strange about this bug is it also occurs in the DTK 386 SX, machine which has an integrated MFM/RLL controller like the recently added micronics.

I suspect that when the V86 mode is enabled by EMM386 to provide EMS memory, have a conflict with the integrated RLL controller in the use of the upper memory area. It may also explain why some VGA cards have problems with this machine. I am not sure about this or how to check this.

**To Reproduce**

I tried the EMS memory test utility, as Windows 2.11 supports the real mode only

Screenshot

![20200126-222917-533](https://user-images.githubusercontent.com/31600563/73142965-38685600-4073-11ea-93b8-8b1c68e766ac.png)

**Comment by OBattler** [comment]
I think this would also happen on real hardware, maybe there's a RLL BIOS at C8000 conflicting with EMM386?

**Comment by OBattler** [comment]
Closing this a NOTABUG - EMM386-BIOS incompatibility.
