### ISSUE TITLE
Full Screen always displayed offside to right. 4:3 mode does not work properly.

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#586]
v.2100

Going full screen displays the full screen offset to the right and remain stretched even under 4:3 mode. Tried all full screen options and tried force 4:3 on and off. 
![Untitled](https://user-images.githubusercontent.com/44859748/73419540-7eb30300-435a-11ea-83f9-123790a06779.png)
 

Host OS : 1. Windows10x64 Dell 7559 laptop, Windows7x86 Thinkpad X230. (same problem in both)

Original in-window 4:3 is okay:
![Untitled2](https://user-images.githubusercontent.com/44859748/73419761-4bbd3f00-435b-11ea-90ef-d1b47c01775f.png)

**Comment by Mal752** [comment]
Just found out the problem starts from Build 2095 onwards.

2094 is the last version which does not have this problem.

**Comment by maximus105** [comment]
In which build will this bug be fixed?

**Comment by OBattler** [comment]
I confirm this bug, I need to look at the code to see why this is happening.

**Comment by Mal752** [comment]
Begins from Build 2095 onwards.

**Comment by maximus105** [comment]
> I confirm this bug, I need to look at the code to see why this is happening.

It turned out to determine what is happening this bug?

**Comment by maximus105** [comment]
> I confirm this bug, I need to look at the code to see why this is happening.
Did you manage to determine the cause of this bug? In which build will it possibly be fixed?

**Comment by daviunic** [comment]
Asking every couple of days does not help with fixing it. When it's fixed, the issue will be closed.

**Comment by maximus105** [comment]
This is a very serious bug that does not allow playing in full-screen 4:3 mode and testing the latest builds of 86Box. Please fix this bug as soon as possible. In which assembly will this possibly be fixed?

**Comment by qeeg** [comment]
Stop being so entitled. We aren't your employees, we do not work for you. Asking over and over for a bug to be fixed just makes us want to fix it LESS, not more.

**Comment by OBattler** [comment]
It's on my to fix list, but no ETA since I have a *LOT* of work to do on the emulator.

**Comment by maximus105** [comment]
The bug was fixed in build 2494.

**Comment by Mal752** [comment]
Confirmed fixed when testing with 2509. 

Thank you.

Closing issue.
