### ISSUE TITLE
286 gate type set to 0x8e does not trigger exception。

### ISSUE THREAD

**Issue by lgj1107** [86Box/86Box#587]
**Describe the bug**
sorry,i english is poor!

The interrupt gate type of 80286 is 86h. Setting the type of interrupt gate to 8eh on 80286 will trigger GP exception, but 86box (ami286 clone) will not.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - 86box v2.10  3b6cc393 build 2100

**Additional context**
source code
[test.zip](https://github.com/86Box/86Box/files/4143729/test.zip)

**Comment by dhrdlicka** [comment]
Please fill out the bug report template. It's not just for looks ;)

**Comment by MoochMcGee** [comment]
They uh, might not speak English natively, from a look on their GitHub profile... It seems that their native language may be some sort of Chinese.

**Comment by tiseno100** [comment]
Respectful

**Comment by daviunic** [comment]
Well the template is there for a reason.

**Comment by OBattler** [comment]
I would need a detailed explanation of this stuff so I could add the required GPF.

**Comment by OBattler** [comment]
The ASM source code enlightened me on what this is about - the emulator was allowing 386 Interrupt and 386 Task gates on a 286, I have this now fixed on my end.
