### ISSUE TITLE
Error: VGA 16 color mode and EGA/ATI EGA 800+ card.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#588]
**Describe the bug**

**_In the standard EGA card:_**

This is not a bug, but an inaccuracy in EGA video card emulation. The 16-color standard VGA video modes should not be supported by standard EGA video card. However it should be supported by EGA Wonder 800+.

Bug:

1. I tested the game  Amazing Spiderman, and I selected the 16 color VGA mode. The normal EGA card should not support it.

**_In the ATI EGA 800+ Card:_**

**Bugs:**

2. The 16- color VGA mode is not supported in Win 3.0/3.1 when using the ATI EGA 800+. 

According the EGA Wonder 800+ manual unlike the standard EGA card. It should support the VGA modes 11  (640x480 2-colors) and mode 12 (640x480 16-color). 

I tested  an older commit of the EGA 800+ with standard VGA video driver under Win 3.0 and worked fine and also the Amazing Spiderman in 320x200 16-color VGA mode. 

_There is a important difference between EGA 800+ a real VGA card however._

A. Its only support 16-color standard VGA modes. Not 256-color or SVGA.

B.  **In the game: **The 256 color palette (16/256) used in 16-colors VGA 320x200 video mode is converted to EGA palette 16/16 colors. (I thinks it is the correct behavior in 320x200 VGA mode, a the game). And looks same as 16-color EGA video mode.

C. The 256 color pallete in 16-color  640x480 VGA video mode is converted to 64 color palette like the standard EGA 640x350. (This should happens on Windows 3.0/3.1 with standard VGA drivers) 
  
   
**Screenshots**
 
I found in Vogons forum that someone has used the VGA driver for Win 3.1 with the  Phoenix Super EGA card. The light/blue colors  of the Windows buttons seemed to be same that ATI EGA 800+ on older commits of PCEM and 86box. In the latest does not work, at least in the 800+.

https://www.vogons.org/viewtopic.php?f=63&t=55188&hilit=atus+ati+ega+800&start=60
![imagen](https://user-images.githubusercontent.com/31600563/73474659-95168a00-436d-11ea-8c0b-01b41b16a352.png)

I took a screenshot, of Win 3.0 with VGA mode and Phoenix Super EGA. Here seems to work correctly.

![20200130-174019-980](https://user-images.githubusercontent.com/31600563/73475243-bdeb4f00-436e-11ea-85ef-cd2e19a3df14.png)

**Comment by dhrdlicka** [comment]
VGA 640x480 "working" on a standard EGA card appears to be a flaw in the video BIOS, where it considers any modes higher than `0Fh` (640x350 at 16 colors) to be equivalent to this mode, which includes any VGA modes. This would probably need to be tested on real hardware.

**Comment by Fenix770** [comment]
On the page 7 of the manual of the card, says t supports VGA mode 11 and 12. But requires a Multi-Sync monitor to use these modes. Currently 86Box and  Pcem does not emulate the required monitor.

I suspect other "Super EGA" cards, like the emulated C&T, support these VGA modes too.
I  also found references about Video 7 super EGA cards. But I'm not sure about the special EGA video modes like 800x560.

Here is the manual
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwiR_O7MoKznAhVxBtQKHeuqBlwQFjAAegQIAhAB&url=http%3A%2F%2Fwww.vgamuseum.info%2Findex.php%2Fcomponent%2Fk2%2Fitem%2Fdownload%2F76_7950870e9059d41b323f7495017c9ba5&usg=AOvVaw0BRClMZ8u14adSaHknEaoV

**Comment by OBattler** [comment]
About the ATI card, I'm beginning to think that maybe it uses a custom monitor switch combination for multisync monitor.

**Comment by OBattler** [comment]
This should now be fixed.
