### ISSUE TITLE
Setting time on IBM XT fails with weird offsets

### ISSUE THREAD

**Issue by Korkman** [86Box/86Box#589]
Using IBM DOS 3.3, setting time with "time" does not properly set the time. It is set some tens of minutes into the future, pseudo-random (setting to 20:00 always results in 20:12)

To Reproduce:

- create an IBM XT machine
- insert IBM DOS 3.3 installer floppy
- boot
- set time with "time" to 20:00
- read time with "time"

Should read back 20:00, doesn't.

Bisecting shows build 1844 introduced the bug. Build 1843 works as expected.

**Comment by OBattler** [comment]
Closing this because build 2103 fixes this.
