### ISSUE TITLE
Unlock emulation speed holding a key

### ISSUE THREAD

**Issue by Korkman** [86Box/86Box#594]
Currently, emulation speed targets 100%. While holding a key, emulation speed would be maximized to speed up for example boot screens.

Opposed to the turbo button feature request, this would not require any specific multipliers as it would speed up the whole emulation (including floppy drive timings) with no specific handling of emulated CPU frequency. Sound might have to be muted during speed-up.

**Comment by OBattler** [comment]
That will be done in v2.20, once we have come up with a methods of making the keyboard bingings customizable (since different users have different preferences).

**Comment by DDXofficial** [comment]
This is quite a late response - regardless, we understand that many of our users prefer to skip through lengthy operations such as OS installations and whatnot. However, this feature would run counter to one of 86Box's core principles, that being emulation accuracy. The speed at which an operation is executed is indicative of the emulated processor.

The dev team has concluded that such a feature falls out of the project's scope and will therefore not be included.
