### ISSUE TITLE
Ensoniq AudioPCI (es1371) emulation doesn't work with Linux guest

### ISSUE THREAD

**Issue by FreeFull** [86Box/86Box#595]
When trying to use the Ensoniq AudioPCI (es1371) sound card with a Linux guest, the following error appears in dmesg:

```
snd_ens1371 0000:00:12.0: AC'97 0 access is not valid [0x0], removing mixer.
snd_ens1371: probe of 0000:00:12.0 failed with error -5
```

Looking it up on google, it seems like similar problems have been hit with PCem's es1371 emulation, so it's probably a shared inaccuracy/incompleteness.

**Comment by OBattler** [comment]
This appears to be the AC'97 part of the ES1371 being poorly emulated, something which is indeed shared with PCem.

**Comment by vadosnaprimer** [comment]
If this is resolved, it will be possible to run Java 8 (probably higher too) apps in a Linux guest. They already run, just without sound.

**Comment by FreeFull** [comment]
@vadosnaprimer As an aside, it's already possible to have sound in Linux guests using a sound blaster 16. The trick is, you have to put `options sb16 isapnp=0` inside /etc/modprobe.conf or /etc/modprobe.d/99-somefilename.conf

**Comment by vadosnaprimer** [comment]
Thanks!

**Comment by OBattler** [comment]
Changed the milestone since RichardG is currently in the process of fixing this.

**Comment by vadosnaprimer** [comment]
> @vadosnaprimer As an aside, it's already possible to have sound in Linux guests using a sound blaster 16. The trick is, you have to put `options snd_sb16 isapnp=0` inside /etc/modprobe.conf or /etc/modprobe.d/99-somefilename.conf

For the record, this let me find the solution that made sound work on linux guest (lubuntu 10).

1. Add following line to the `/etc/modules` file. This will make the driver to load at boot time.
```
snd-sb16
```
2. Add following line to the `/etc/modprobe.d/alsa_local` and `/etc/modutils/alsa_local` files.
```
options snd-sb16 isapnp=0 port=0x220 irq=5 dma8=1 dma16=5 mpu_port=0x330
```
(I added this to `/etc/modprobe.d/alsa-base.conf` instead, `/etc/modutils` doesn't exist)
`alsamixer` started displaying the sliders, `aplay -l` lists the card now
