### ISSUE TITLE
Emulating KENITEC 286-16

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#596]
**Is your feature request related to a problem? Please describe.**
Not a problem. I have the real machine.
CPU SIemens 286-26
Chipset:CS8121 NEAT
Onboard Serial (x2) and paralel conector
Video Card: ACUMOS AVGA 1 (CL-GD5201, same as CL-GD5402 but with only 256k)

**Comment by jvernet** [comment]
I tried myself to add them to 89Box without success (do not show up in the systeme selection). I missed something...

ROM:

[KENITEC.zip](https://github.com/86Box/86Box/files/4210527/KENITEC.zip)
[AVGA1.zip](https://github.com/86Box/86Box/files/4210529/AVGA1.zip)
[AVGA2.zip](https://github.com/86Box/86Box/files/4210532/AVGA2.zip)

**Comment by tiseno100** [comment]
![Capture](https://user-images.githubusercontent.com/58827426/74611796-0e510380-5108-11ea-8edc-575d9ec8fedf.PNG)

Is the AVGA card onboard or expansion?

**Comment by jvernet** [comment]
expansionboard. If you replace  the cl-g5402 with this rom it work (with a nice ACUMOS graphic logo at boot).

I tried to add it to video.c/video CG etc, but cannot make it shown in the config panel.

**Comment by jvernet** [comment]
There is also a ISA HD/FLOPPY controler, and a ESS 1868F sound card

**Comment by jvernet** [comment]
I managed to get the KENITEC ROM working and added the new system myself, along with the AVGA1 ACUMOS ROM.
Is there a way to know wich key I should use to access SETUP at boot ? Damn can find it even on real hardware !
And what emm.sys to use ? I tried NEATEMM.SYS, SCATEMM.SYS and as much as I can find without success, on the emulated or real system...

![image](https://user-images.githubusercontent.com/16312616/74875533-b9f59000-5362-11ea-9974-98aace798c89.png)

**Comment by tiseno100** [comment]
hmm we don't emulate the AVGA1 yet though

**Comment by jvernet** [comment]
AVGA1 is basically an AVGA2 with less memory (256k only, wich is weird). I've just used what is done for AVGA2. Seems to work basically,not sure for windows.

**Comment by jvernet** [comment]
Any chance to see the KENITEC ROM and emulation added soon ? I have my own build working, but it's better to see an official one !
Same for AVGA1 and the acumos Logo/ROM ?

**Comment by tiseno100** [comment]
We'll see about that. Looks like an interesting machine indeed but i don't know what we will do with the AVGA1 sadly

**Comment by tiseno100** [comment]
As of now https://github.com/86Box/86Box/pull/683

**Comment by tiseno100** [comment]
The Kenitec 286 Bios are now a replacement for the Phoenix 286 Clone due to their standardization.
https://github.com/tiseno100/86Box/commit/b23031fa65e19f38f16c89e5420a68b2de614453

**Comment by Fenix770** [comment]
Hello!

I tested this machine. I'm unable to get the EMS NEAT emulation working. The NEAT EMS driver throws an error indicating a wrong configuration.
Here I attach a floppy disk image with the NEAT EMS drivers including some utilities to configure the chipset as well as a driver to map UMB memory. 

[NEAT_.zip](https://github.com/86Box/86Box/files/4631717/NEAT_.zip)

The EMS drivers for NEAT are EMM.SYS (ver 1.5) and EMM152.SYS (Ver 1.52). The drivers EMM411.SYS and EMM411A.SYS does not indicate any model name, it detect the amount of EMS ram correctly but does not perform any test and it does not work. I suspect they are for an older 82C100 "Super XT" chipset.

**Comment by jvernet** [comment]
I'm using my own build with different params than the current 86Box Build.
EMM411.sys detect EMS at boot, but EMSTEST from BORLAND do not work.

![image](https://user-images.githubusercontent.com/16312616/82028710-48de2400-9696-11ea-8bbc-1bdf72ddb0b6.png)

**Comment by tiseno100** [comment]
This has to do i think with NEAT chipset emulation being kind of trash

**Comment by dhrdlicka** [comment]
Machine has been added, therefore I am closing this issue. Please create a new issue for any bugs related to it.
