### ISSUE TITLE
Drive B: not pointed [Amstrad PC-1512]

### ISSUE THREAD

**Issue by jalavera** [86Box/86Box#597]
If a second image drive is mounted, it is not attached as B:

My settings:
Tools > Settings
Machine: [8086] Amstrad PC1512
Floppy drives:
5.25" 360 Kb
5.25" 360 Kb
disabled
disabled

I boot from MD-DOS 3.20 (official for this machine). Drive A:
If I mount some image to second drive it's not recognized as drive 'B>'
Typing B:  [Intro]
B>DIR
It does not DIR ANYTHING in 2nd drive, otherwise waits for a key press  
(see screenshot)

My OS:  Windows 7
It happens on All 86Box versions since at least v2.00
![20200217-152155-749](https://user-images.githubusercontent.com/18722832/74666736-515fb500-51a2-11ea-8602-dbae3fb4992e.png)

**Comment by jvernet** [comment]
use NVR and set your system to 2 Drives

**Comment by jalavera** [comment]
Oh! Thanks I didn't remember the NVR... It works.
