### ISSUE TITLE
Amstrad PC-1512 mouse support killed from nightly builds since 2.0.7+

### ISSUE THREAD

**Issue by jalavera** [86Box/86Box#598]
Amstrad PC-1512 mouse support killed since nighly builds. Latest know build working is 2.0.7 build 2008.

My settings:
Tools > Settings
Input devices. [Internal mouse]

Tested simple after booting official MS-DOS 3.20 with Amstrad Mouse default driver by moving to right on a new commadn line after A>.

If driver is active and working moving the mouse to right tries to copy last entered line. Version 2.0.7 build 2008 do it! but newer nigthly builds does not.
 
My OS:  Windows 7

**Comment by jvernet** [comment]
It's working for me (Build 2098). 
But damn, the way mouse/keyboard work on the emulated system sucks : directionnal key that do anything else than move cursor (you HAVE to use numerical keyboard instead, NEVER TOUCH the tradional cursor key). 

I also noticed that PC2086 use the same emulated keyboard (and work with PC1512 mouse and KEYB.com): it's not the case. It should be a conventionnal AT keyboard.

**Comment by jalavera** [comment]
Perfect! It only works the numerical keyboard cursor key, not traditional!. Internal mouse emulation works too.
