### ISSUE TITLE
Tandy 1000 SL direct DAC

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#601]
Sorry,I reported this bug earlier, but I opened a new post because I found some info about the Tandy DAC.

On the Vogons site explains some games access the hardware directly instead of through DMA.

**Describe the solution you'd like**
Is possible to implement this patch in 86box? (if does not break any emulated device, of course)

Explanation: 
1. I found on the site, a compiled version of dosbox, that supports the Tandy 1000 DAC on The game Super Tetris, but in spite of that the 3-voice speaker does not work.  The 3-voice speaker does not work with this game in last Dosbox compilation. I belive something in the emulation is broken in Dosbox. Because the Tandy  3-voice works on 86box/PCEM.

**Other unrelated bug with the DAC:** 
2. Also exist a bug in the Outrun game with DAC, that crashes the system when reproducing the sound efects of the engine of the car. This particular bug existed in Dosbox some years ago and now is fixed.

**Additional context**

The patch also modified some frequencies for better accuracy with certain games.

[r4000-tandy_sound.zip](https://github.com/86Box/86Box/files/4242502/r4000-tandy_sound.zip)

And here is the web page:
https://www.vogons.org/viewtopic.php?f=41&t=51382&p=549202&hilit=tandy%20direct%20dac#p549202

**Comment by Fenix770** [comment]
PD:  I Tested again . Suprtetris works with 3-voce+DAC with that patched DOSbox commit  if the CPU  is configured as normal and cycles in 1000. The DAC is very sensitive in this games. With 1250 and the game has choppy sound and may fail.

**Comment by OBattler** [comment]
Closing this because we already do support direct DAC (I just checked the code).
