### ISSUE TITLE
NE2000 not recognized in Linux

### ISSUE THREAD

**Issue by SilverSzymonPL** [86Box/86Box#603]
I was installing Red Hat linux 5.2 and noticed that it couldn't recognize the NE2000 network card. Other pieces of hardware were recognized without issues. I also installed it in QEMU with the NE2000 chosen, and it was recognized without issues as well.

Red Hat 5.2 can be found here https://archive.org/details/RedHatLinux5.2

To reproduce:
1. Download Red Hat Linux 5.2
2. Install the system with the NE2000 chosen as the network card in the 86box options
3. During the initial configuration, configure the network and choose the NE2000 as the network device. It can't find it

**Comment by MoochMcGee** [comment]
Which network method were you using? SLiRP isn't as accurate as Pcap, nor is it as reliable :/ Though Pcap does require special drivers *and* using an ethernet cable.

**Comment by SilverSzymonPL** [comment]
I used Pcap. Although i'm not sure if it was set up properly to actually connect to the internet. Would that cause the device to not appear?

**Comment by MoochMcGee** [comment]
You need to install pcap drivers in order to use pcap.

**Comment by SilverSzymonPL** [comment]
I think my problem was that I didn't configure the pcap setting properly, choosing the wrong adapter.I also once ran 86box on a computer without sound hardware and it caused the emulated sound device to not show up either.
