### ISSUE TITLE
Overprinting characters on ESC/P

### ISSUE THREAD

**Issue by ArtiomWin** [86Box/86Box#606]
ESC/P emulation have issues with printing other characters over some ones (digits are mostly affected).
Here's how text looks like on screen:
![20200305-064800-353](https://user-images.githubusercontent.com/31134876/75955268-8d935500-5ec6-11ea-8763-42ac611f55a0.png)
And here's how it looks like on "printed" page:
![20200305-064359-371](https://user-images.githubusercontent.com/31134876/75955311-a865c980-5ec6-11ea-8ee5-3b6469b8d447.png)

 - Host OS: Windows 10
 - 86box version: v2.10 (Build 2100)
 - Emulated machine: IBM PC AT
 - Guest OS: IBM PC-DOS 3.00
 - Tested app: WordPerfect 4.1

**Comment by saipan7** [comment]
i think this issue is already fixed

![wp41 printscr 1](https://github.com/86Box/86Box/assets/127716019/967561a9-0973-4f10-8ac9-3d4a9b04d29b)

![wp41 printscr 2](https://github.com/86Box/86Box/assets/127716019/495bc7ae-8f5a-4a83-82a6-e66bfd7b2df1)

**Comment by OBattler** [comment]
Then this can be closed.
