### ISSUE TITLE
Illegal Function thrown on 86Box

### ISSUE THREAD

**Issue by Justinius** [86Box/86Box#649]
**Describe the bug**
While testing QB4.5  I found that it had an error running Gorilla.bas.  It did not error in the included QB interpreter under DOS 6.22. So I tested it under PCEM and it ran fine (slow and poor graphic update, but it ran)  One of the reported errors was an illegal function while calling the ATN function. I wrote the simple program "Print ATN(1)" and when run in QB4.5 it errored again. I compiled it and ran that. Received the same error. Ran executable under PCEM and it ran fine.

**To Reproduce**
Create new vm: Win486, i486DX2 66MHz, 32MB ram, S3virge 4MB
Load OS: DOS 6.22
Load Software: QB4.5 and sample programs (Gorillas, Nibbles, etc)
Run Gorillas in QBasic - works fine
Run Gorillas in QB4.5 - get error
Reduce to Print ATN(1) - get error
Compile program and run from DOS - get error
Load HD in PCEM with same basic machine - runs fine

**Expected behavior**
Able to run Gorillas or other programs as on PCEM

**Desktop (please complete the following information):**
 - OS: Host: Win10 17134, VM: DOS 6.22
 - Version: 2.10

**Comment by OBattler** [comment]
Try the latest build to see if it's now fixed.

**Comment by Justinius** [comment]
ATN issue fixed running #2200 nightly. Received new error. Will investigate more
