### ISSUE TITLE
Audio devices causes VM to crash

### ISSUE THREAD

**Issue by mishamosher** [86Box/86Box#657]
**Describe the bug**
I was using the automated build from March 10, 2020; e36f68a. Just updated to 85dc146 and the sound devices stopped working on my Windows 3.11 (Sound Blaster AWE32) and Windows 98 (Ensoniq ES1971) VMs. The VMs crash every now and then, and removing the audio device solves the problem.

**To Reproduce**
- Configure a VM with an audio card
- Install Windows 98 or Windows 3.11
- Install audio drivers

**Expected behavior**
Sound should work as previously, and the VMs should not crash because of the presence of an audio device.

**Screenshots**
Windows 98 presents me a BSOD when a sound tries to play:
![20200331-174844-537](https://user-images.githubusercontent.com/3683227/78058574-bed83700-7345-11ea-8f72-0a4ddd139878.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 64 bits
 - Version 85dc146

**Additional context**
Attached are the CFG files of my VMs.
[86Box VMs CFG.zip](https://github.com/86Box/86Box/files/4410701/86Box.VMs.CFG.zip)

**Comment by OBattler** [comment]
Does the latest build fix it?

**Comment by mishamosher** [comment]
@OBattler yes it does!
