### ISSUE TITLE
 [BUG] Floating Point Unit (FPU) emulation causes numerous issues

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#665]
I'm currently running Dashboard 1.01 for Windows as the shell for Windows 3.0 on the emulated Elitegroup Computer Systems 386/32 (Intel 80386/20) with 8 MB of RAM and a Trident 8900B graphics card with 512 KB of video RAM.

When running Dashboard 1.01 as the shell, the display prints out "cos: sin: cos: sin: cos: sin:" in a infinite loop while the shell is running. Here's a screenshot of the issue below:

![20200401-222215-723](https://user-images.githubusercontent.com/32658796/78192544-35039900-742d-11ea-8f7a-24f47e89ac71.png)
I have found that there is a bug in the 80x87 floating point unit (FPU math co-processor) that causes this.

Here are a couple of temporary workarounds to cure this issue:

1. Load the HIDE87 utility at startup.
2. Disable FPU emulation in the 86Box machine settings.

Here's the 86Box configuration file: https://pastebin.com/5ShM9aRM

Please investigate what is causing the FPU bug. Thanks.

**Comment by dhrdlicka** [comment]
Fixed in f29f6de245cdf9f1a87f89eb9ec006d5dc69f54a.
