### ISSUE TITLE
Fullscreen improvements

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#668]
Can you also add the following functions to the 86Box?
1. Set custom resolution
2. Full screen on input grab
3. Vsync
4. Fullscreen mode (Borderless/Exclusive)
5. Dim display on lost focus
6. Scale filtering (Nearest/Linear)

_Originally posted by @maximus105 in https://github.com/86Box/86Box/issues/666#issuecomment-607934844_

**Comment by Kappa971** [comment]
Vsync and Exclusive Fullscreen are important for Freesync/G-Sync screens, otherwise Freesync won't work. It's strange that no one ever mentioned it 🤔

**Comment by OBattler** [comment]
Closing as a duplicate of #395.
