### ISSUE TITLE
Packard Bell Bora Pro stuck i

### ISSUE THREAD

**Issue by windows-95-420** [86Box/86Box#690]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. v2.06]

**Additional context**

**Comment by Raulonthetest** [comment]
Unfilled

**Comment by windows-95-420** [comment]
> Unfilled

I closed it for that reason. I accidentally submitted this. No need to respond to it.

**Comment by Raulonthetest** [comment]
fine

**Comment by windows-95-420** [comment]
> fine

As i said, no need to respond. It was closed for a reason.
