### ISSUE TITLE
Packard Bell Bora Pro stuck in beep loop

### ISSUE THREAD

**Issue by windows-95-420** [86Box/86Box#691]
**Describe the bug**
When trying to use the specified motherboard, the system does not boot and just beeps.

**To Reproduce**
1. Create a new config
2. Select the Packard Bell Bora Pro mobo
3. Use a Pentium II
4. Any hardware configuration fails to boot with this mobo
5.beep beep beep beep

**Expected behavior**
I thought it would boot up so i could go into the system setup and boot from my cd.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSC 2019 (1809)
 - Version v2.10 Skylake

**Additional context**
From what i can tell, there are no AMIbios beep codes like this one. AFAIK it means a power supply failure.

**Comment by tiseno100** [comment]
The Bora Pro is unstable to use for now. The beep code is recognized by me and has to do with Memory.

**Comment by windows-95-420** [comment]
> The Bora Pro is unstable to use for now. The beep code is recognized by me and has to do with Memory.

It used to work fine.

**Comment by OBattler** [comment]
Closing this issue because the machine in question has been removed. It's going to be reopened, should the machine be readded in the future.
