### ISSUE TITLE
Voodoo/Voodoo2 Rendering error

### ISSUE THREAD

**Issue by greyhairedoldbadger** [86Box/86Box#692]
Rendering (colouring) errors in Voodoo / Voodoo2 generated graphics introduced in Build 2103

**To Reproduce**
[Machine]
machine = p55t2p4
mem_size = 32768
cpu_use_dynarec = 1
cpu_enable_fpu = 1
time_sync = local
cpu = 10

[Video]
gfxcard = virge375_pci
voodoo = 1

[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

**Expected behavior**
As in Build 2102

**Screenshots**
![2102](https://user-images.githubusercontent.com/63615420/79161135-e06c0080-7dd2-11ea-85fe-5e08debe4f8f.jpg)
![2103](https://user-images.githubusercontent.com/63615420/79161144-e3ff8780-7dd2-11ea-8e95-9bff75220249.jpg)

**Desktop (please complete the following information):**
 - VMware Windows 10 virtual machine

**Additional context**
Apologies if already reported. Please ask for any more information.

**Comment by maximus105** [comment]
I confirm this bug. I also have it. In which build will it possibly be fixed?

**Comment by OBattler** [comment]
Do recent builds of 86Box fix this?

**Comment by windows-95-420** [comment]
> Do recent builds of 86Box fix this?

They do, at least for me.

**Comment by greyhairedoldbadger** [comment]
I really should have said, sorry. the bug persists in all builds >2102 I have tried. This includes the latest 2183 build.
The colours can be altered (but not corrected) by adjusting the gamma setting in the 3dfx Display Properties Tab.

**Comment by windows-95-420** [comment]
> I really should have said, sorry. the bug persists in all builds >2102 I have tried. This includes the latest 2183 build.
> The colours can be altered (but not corrected) by adjusting the gamma setting in the 3dfx Display Properties Tab.
> Host OS is a virtual Windows 10 box, emulated OS is Windows 98SE, but I have also observed the bug in Windows ME.

I'll check Windows 2000 to see if NT fixes the issue.

**Comment by greyhairedoldbadger** [comment]
I installed Windows 98SE service pack 3, and the latest Voodoo2 reference driver, both from Phils Computer Lab. The bug is still present.

**Comment by windows-95-420** [comment]
> I installed Windows 98SE service pack 3, and the latest Voodoo2 reference driver, both from Phils Computer Lab. The bug is still present.

Did you use the Windows 98 AutoPatcher? I havent had time to try Win2k, so i recommend you try a NT based windows os.

**Comment by OBattler** [comment]
If you're using Optimized builds, try non-Optimized.
I tried Tomb Raider II on Voodoo 2 SLI on a recent build and it rendered fine.

**Comment by greyhairedoldbadger** [comment]
> If you're using Optimized builds, try non-Optimized.
I tried Tomb Raider II on Voodoo 2 SLI on a recent build and it rendered fine.

Thanks for the feeback. I have tried both optimized and non-optimised builds.
I will continue to experiment, and I will report back if I learn anything new.

**Comment by maximus105** [comment]
This bug with color distortion on Voodoo 2 appeared in build 2103 (both in regular and optimized builds). In build 2102, everything is working properly. I tested this on the following configuration 86Box:
[Super 7 MVP3] FIC VA-503+
Pentium MMX 166
256MB
[PCI] Phoenix S3 Trio64 4MB
Voodoo 2 SLI
Windows 98SE

And also, please correct if possible а bug https://github.com/86Box/86Box/issues/586(url)

**Comment by OBattler** [comment]
Could any of you upload their VM (hard disk image + NVR folder + 86box.cfg) so I can test this and see what's going on?

**Comment by greyhairedoldbadger** [comment]
> Could any of you upload their VM (hard disk image + NVR folder + 86box.cfg) so I can test this and see what's going on?

Happy to help, but the disk image is rather large at 2GiB. Will this be a problem?

**Comment by OBattler** [comment]
It's a not problem with me, I have enough space for that. Try uploading to Google Drive or Mega or something.

**Comment by greyhairedoldbadger** [comment]
> It's a not problem for me, I have enough space for that. Try uploading to Google Drive or Mega or something.

Google drive link:
https://drive.google.com/file/d/1oumRWmlviMIc6NCqDFjLhlW3qqUB-GhP/view?usp=sharing

**Comment by greyhairedoldbadger** [comment]
Confirm that this bug (and two others) fixed in build #2201.

With thanks.
