### ISSUE TITLE
[8088] Generic XT Clone Bug

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#695]
**Describe the bug**
[8088] Generic XT Clone generates an error on any [ISA] EGA and [ISA] VGA video card upon startup. While similar 8088 XTs start up normally with these video cards.
**Screenshots**
![20200415-055434-660](https://user-images.githubusercontent.com/58270614/79303742-50c07200-7ef8-11ea-9853-975541fbecc8.png)

**Comment by windows-95-420** [comment]
Can confirm, happening to me too.

**Comment by OBattler** [comment]
Are you sure it's supposed to work?

**Comment by windows-95-420** [comment]
> Are you sure it's supposed to work?

Some/most XTs ive seen use EGA... So yes?

**Comment by OBattler** [comment]
Yes but what about that specific BIOS? Is there even any real hardware that uses this BIOS?

**Comment by windows-95-420** [comment]
> Yes but what about that specific BIOS? Is there even any real hardware that uses this BIOS?

Yes, it was a drop in replacement bios for older IBM computers.

**Comment by maximus105** [comment]
If, after the appearance of this bug, click "continue", then the [8088] Generic XT Clone download happens normally and the games start without bugs. This indicates that [8088] Generic XT Clone works without bugs withany [ISA] EGA and [ISA] VGA video card. Maybe just some kind of bug is present when determining these video cards when starting the BIOS?

**Comment by windows-95-420** [comment]
> If, after the appearance of this bug, click "continue", then the [8088] Generic XT Clone download happens normally and MS-DOS and games start without bugs. This indicates that [8088] Generic XT Clone works without bugs with any [ISA] EGA and [ISA] VGA video card. Maybe just some kind of bug is present when determining these video cards when starting the BIOS?

Possibly, but it brings up error 2 as well, which indicates a memory count issue. The only way to fix this is to allocate less than 640k of ram, or remove any extended ram. These errors are not present on my IBM XT or XT  Clones using that bios and similar/comprable hardware.

**Comment by OBattler** [comment]
It could be an issue with timings, since I vaguely remember the IBM VGA BIOS making the IBM XT 1986 beep on 86Box, could be the bit it reads out on port 3DA not toggling at the correct rate.

**Comment by maximus105** [comment]
[8088] American XT Computer, which was recently added to 86Box, does not have the above bug when running with EGA and VGA graphics cards. The BIOS startup screen looks similar to [8088] Generic XT Clone:

![20200924-153806-613](https://user-images.githubusercontent.com/58270614/94168000-d9730f00-fe95-11ea-8e5f-0e45f6208e80.png)

![20200924-153823-566](https://user-images.githubusercontent.com/58270614/94168013-dd069600-fe95-11ea-8b07-747e2edf9225.png)

**Comment by tiseno100** [comment]
I guess the Generic XT clone was never intended to take EGA or VGA graphics cards. Remember these 8088 machines had their BIOS patched to support EGA & VGA graphics. Probably the Generic XT board isn't of that kind.

**Comment by OBattler** [comment]
System error #04 should be bad ram on video card, and it might either be an emulation bug (but then, it'd affect both vid_ega.c and vid_vga.c) or the BIOS probing the wrong segment (perhaps it thinks it's a MDA?).

**Comment by OBattler** [comment]
Found the page of an open BIOS derived from the 1987 Generic XT BIOS: https://sourceforge.net/projects/opensoc86/files/bios/pcxtbios25/ .

One of the changes the author of the derivative had to do was to make the video memory test option so EGA and VGA would work, which means that EGA and VGA will *NOT* work on the original 1987 BIOS as it always tests video memory and will therefore fail on an EGA or VGA. So the behavior seen on 86Box is true to real hardware and is therefore not a bug. Therefore, this is being closed.
