### ISSUE TITLE
Incorrect 8088 (4,77 MHz) emulation speed in games

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#705]
![20200420-044345-184](https://user-images.githubusercontent.com/58270614/79714897-d4a0a280-82da-11ea-8126-b24d2d9aa765.png)
In games such as Arkanoid, Buck Rogers (Planet of Zoom), Eden Blues, Flightmare, and others, there is an incorrect processor emulation speed of 8088 (4,77 MHz). This is especially noticeable in the game Arkanoid by the speed of music playback in the initial splash screen of the game. To understand how this music should sound (if there is no real PC 8088 (4,77 MHz), in DOSBox ECE or in DOSBox SVN-Daum you need to set cycles = 240 and run this game. I draw your attention to the fact that the Paratrooper (1982) game in 86Box at 8088 (4,77 MHz) now works correctly! You can hear PC Speaker sounds of flying helicopters and airplanes. Even in DOSBox these sounds are not heard with a value of cycles = 240.

**Comment by qeeg** [comment]
DOSBox is heavily inaccurate compared to 86box when it comes to 8088 timings, so of course there are going to be differences. :P

**Comment by dhrdlicka** [comment]
The fact 86Box runs the infamous [8088MPH](http://www.pouet.net/prod.php?which=65371) demo flawlessly proves quite the opposite.

**Comment by OBattler** [comment]
There are some problems remaning with 808x timings, mostly related to DMA refresh cycles for which currently, a crude approximation is used. Eventually they are going to be made more accurate.

**Comment by maximus105** [comment]
Initially the game Buck Rogers Planet Of Zoom (1984) runs too fast on the 8088 XT 4.77 MHz. Also in this game has new bugs: the in-game timer has speed up a lot. Life (in the form of a spaceship) is added very quickly.

**Comment by maximus105** [comment]
This new bug appeared in build 2580. In build 2579 everything was fine. Checked on [8088] American XT Computer and [8088] Generic XT clone. This is even noticeable on the initial BIOS screen: RAM Testing flashes too quickly (so you can't see the numbers from 0 to 640 KB). The test at the end shows 84 KB, although it should show 640 KB. Everything was fine in build 2579. Tested on an optimized Skylake build.

**Comment by maximus105** [comment]
It looks like this new bug is related to a fix in build 2580: "fixes to 808x emulation (MS Word 1.0 and 1.10 for DOS now work correctly from floppy)". Can you fix this somehow?

**Comment by OBattler** [comment]
I'm going to look into this.

**Comment by OBattler** [comment]
I confirm this and I suspect some 808x instruction (I believe that commit did change a few) is now misbehaving, causing this.

**Comment by maximus105** [comment]
[8088] American XT Computer disappeared from the machine selection list.

**Comment by Winins0** [comment]
What do you mean?
![bause](https://user-images.githubusercontent.com/65453129/98157464-70e26d80-1eea-11eb-9069-26f41f94a765.PNG)

**Comment by maximus105** [comment]
Restart the build. Everything works fine.

**Comment by OBattler** [comment]
Closing this as it's being tracked in #4044.

**Comment by usergithub64** [comment]
In the latest 86Box build, it was discovered that the 8088 4.77 MHz processor speed is correctly emulated on the PCjr. Is it possible to implement the same correct 8088 4.77 MHz processor speed emulation for other machines that support the 8088 4.77 MHz processor speed? This would automatically fix issue #738 and other issues related to incorrect 4.77 MHz emulation speed.

The music in Arkanoid sounds correct (closest to the music on the real machine, as linked at the beginning of the thread) on the 86Box on the PCjr:

[Arkanoid 8088 PCjr 4.77MHz.zip](https://github.com/user-attachments/files/22537053/Arkanoid.8088.PCjr.4.77MHz.zip)

The music in Arkanoid sounds incorrect (too fast) on the 86Box on the 8088 Juko ST 4.77 MHz:

[Arkanoid 8088 Juko ST 4.77MHz.zip](https://github.com/user-attachments/files/22537075/Arkanoid.8088.Juko.ST.4.77MHz.zip)

**Comment by OBattler** [comment]
I'm currently working on the complete 808x rewrite that's going to appear in 86Box 6.0.
