### ISSUE TITLE
It occured problem above 2194

### ISSUE THREAD

**Issue by leesa49** [86Box/86Box#706]
**Describe the bug**

2194 version is ok
after bios checking, "Starting MS-DOS" ... Booting is ok

from 2195 to recent version is not ok
after bios checking, some error message

**To Reproduce**

**Expected behavior**

**Screenshots**

**v2194**
![ok](https://user-images.githubusercontent.com/55971868/79705362-61099000-82f0-11ea-91cc-db5198360d40.png)

**contain 2195 and up to date**
![notok](https://user-images.githubusercontent.com/55971868/79705376-71216f80-82f0-11ea-9186-60f3b93fc409.png)

**Desktop (please complete the following information):**
 - OS: MS-DOS 
 - Version : v6.2

**Additional context**

**Comment by OBattler** [comment]
I see no way for 2195 to break that, given that it only does changes to two completely unrelated things (a Pentium 430TX machine and VNC).

I suspect your hard disk got corrupted and may need reformatting and reinstalling.
