### ISSUE TITLE
Machines will make 86Box close

### ISSUE THREAD

**Issue by Raulonthetest** [86Box/86Box#713]
**Describe the bug**
Sone boards, such as the TC430HX will make 86Box close.

**To Reproduce**
1. Open 86Box's settings.
2. Choose a machine from the list: TC430HX, GA-686-NX, MB600N, P6KFX-A
3. Save settings
4. 86Box will hang on a black screen and then close.

**Expected behavior**
There will be a POST screen, indicating BIOS version and type, CPU, memory etc.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v1903
 - Version 2.10, e3296f45

**Additional context**
No matter what configuration of CPU, memory, video etc. 86Box will close when running on the boards listed at Step 2.
and excuse me if it had the unedited template, it was my tablet's fault, as I am using a Surface Pro 4
.

**Comment by daviunic** [comment]
Hi, please fill out the template with information about this issue so we can actually help.

**Comment by Raulonthetest** [comment]
daviunic, i filled it now. Sorry, It way my tablet not letting me write the message :(

**Comment by daviunic** [comment]
Thank you, we'll look into it.

**Comment by Raulonthetest** [comment]
np, daviunic 😀
