### ISSUE TITLE
Add SE440BX to the machine list

### ISSUE THREAD

**Issue by raulmrio28-git** [86Box/86Box#714]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
I do like computers, but I was thinking now for something when my issue about the PIIX bug (which made the machines to crash 86Box) got fixed. That "something" was to add a board to 86Box. It is the Intel SE440BX, not SE440BX-2. This is what I was thinking 😊.

**Describe alternatives you've considered**
Nothing.
**Additional context**
BIOS: ftp://ftp.ioncomputer.com/HardWare/SYSTEMS/1990s/199xBIOS/4S4EB0X1.86A.0032.P12.EXE
Specs of motherboard: ftp://ftp.spez.com.ua/driver/mb/intel/se440bx/69114101.pdf

**Comment by tiseno100** [comment]
It's under consideration.

**Comment by Raulonthetest** [comment]
Okay 😏🤔

**Comment by OBattler** [comment]
Closing this because we don't even have a dump of its bootblock, so it's a "can't do".
