### ISSUE TITLE
Bug 713 fixed, TC430HX hangs at memory test

### ISSUE THREAD

**Issue by Raulonthetest** [86Box/86Box#716]
**Describe the bug**
After issue 713 got fixed, now TC430HX hangs at memory test screen

**To Reproduce**
1. Go to 86Box's settings
2. Select TC430HX from the system drop down list
3. Save settings
4. POST will hang during POST at "Keyboard.....Detected"

**Expected behavior**
POST will complete like normal.

**Screenshots**
![20200423-160409-702](https://user-images.githubusercontent.com/64203039/80122086-be723b00-8595-11ea-99b6-05e4cd184eb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v1903
 - Version 2.10 da9c5a5e

**Additional context**
Nothing

**Comment by amdk6** [comment]
Just try adding an MPU-401 at port 300.

**Comment by Raulonthetest** [comment]
No sound card added to test, but I will try

**Comment by Raulonthetest** [comment]
Nope amdk6, still stuck at "Kayboard.....Detected". (•_•)

**Comment by Raulonthetest** [comment]
Fixed now, deleted comment
