### ISSUE TITLE
86Box gets unresponsive sometimes.

### ISSUE THREAD

**Issue by kkwpsv** [86Box/86Box#722]
**Describe the bug**
86Box gets unresponsive and stuck in a deadlock.

**To Reproduce**
1:Open two 86box instance, then minimize and restore this two instances for some times, and the two 86box instances will both get unresponsive. When close one instance, the another will get responsive again.
2.Just open one 86box instance, minimize and restore it, it'll also get unresponsive in rare cases. And it won't get responsive anymore.

**Expected behavior**
Not get unresponsive .

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Latest

**Additional context**
The first kind of deadlock should be because the two instances use same mutex `86Box.BlitMutex`. We can fix it by not using same mutex, but I'm not sure if the name `86Box.BlitMutex` has other uses.

The second kind of deadlock may be because of some logical error of set and reset events.
I have investigated it with `Process Monitor`:
When 86box get deadlock, the mutex `86Box.BlitMutex` is owned, so the deadlock should happened between `startblit` and  `endblit`. And `blit_complete` event object is used there. Because the use of this event object is a little complicated, and it's anonymous event which cannot be monitored by `Process Monitor`, I haven't found out the specific reason. 
In addition, when I kill some threads of 86box with `Process Monitor`, the ui can restore responsive. So, this also confirms that 86box stuck in a deadlock by contention between threads.

**Comment by kkwpsv** [comment]
The stack when 86box gets unresponsive:
![F}R`U}3CHTXU$FA~)ORX~WV](https://user-images.githubusercontent.com/11524048/80273204-d2877b00-8702-11ea-90d6-eb976b7b0c7e.png)

`KeWaitForMutexObject` is a macro that converts to `KeWaitForSingleObject`.
So, the thread is waiting for something like mutex, event..

**Comment by dhrdlicka** [comment]
We probably shouldn't be using a named mutex there.

**Comment by dhrdlicka** [comment]
From what I see, the hang itself is probably another renderer hang. I fixed the mutex part, however, the hang itself still remains, it just doesn't affect other running VMs.

**Comment by kkwpsv** [comment]
Yes, the second kind of hang still remains, and we also should found out the reason. So maybe this issue shouldn't be closed now?

**Comment by dhrdlicka** [comment]
Filed a new bug for the hang itself.
