### ISSUE TITLE
Where can I select a physical CD drive?

### ISSUE THREAD

**Issue by NickTrapani** [86Box/86Box#730]
![image](https://user-images.githubusercontent.com/31448055/80335256-c1815b80-8821-11ea-9428-cf7dae0e091b.png)
Hello. I apologize if this is a dumb question, but I need to ask if there is an option for mounting a physical CD drive or one mounted using Daemon Tools. Being able to mount ISOs is nice and all, but not being able to use real drives is a bit of a deal breaker for me.

**Comment by nerd73** [comment]
There is no option to mount a virtual or physical drive. Could you please explain why it is a deal breaker for you? As far as I can remember IOCTL (the back-end for that option) was very slow.

**Comment by NickTrapani** [comment]
Ah. Well, thanks for letting me know. I primarily use Daemon Tools to mount MDF/MDS and BIN/CUE images for the games that I rip, and I know that MDF support has been brought up before, but using a virtual drive would eliminate any barriers set by the program in terms of image types.

**Comment by qeeg** [comment]
BIN/CUE already works AFAIK.

**Comment by maximus105** [comment]
And why is the "Mute" function needed in the CD-ROM tab in the top screenshot?

**Comment by tiseno100** [comment]
CD drives of that era and some late ones had Audio CD functionality. They had a cable were Audio CD data passed and were processed straight to the sound card. Some had volume control too allowing you to control well, volume.

**Comment by tiseno100** [comment]
> 
> 
> Ah. Well, thanks for letting me know. I primarily use Daemon Tools to mount MDF/MDS and BIN/CUE images for the games that I rip, and I know that MDF support has been brought up before, but using a virtual drive would eliminate any barriers set by the program in terms of image types.

Mount the *.cue image. It works.

**Comment by OBattler** [comment]
Yes, CUE/BIN images work. And I would love to add MDS/MDF support, but I've yet to find some human-readable specification for it. As for passing physical drives, I might look at it, though the best bet would be do them without all the fancy data type stuff, so I'm not sure how good that would be. It would also added more code needed to port when we get around to the Linux port some day.

**Comment by creopard** [comment]
Unfortunately, the specification for Daemon Tools file format MDS/MDF and MDX [does not seem to be an open standard](https://forum.daemon-tools.cc/showthread.php?t=27748). 

referenced for future use: #430
