### ISSUE TITLE
Adding support of dynamically expanding disk images

### ISSUE THREAD

**Issue by surrodox2001** [86Box/86Box#731]
^
Can we have dynamically expanding disk images in any format? (VHD images at least)
We can save space with these zeros gone (you can do that too with NTFS compression, but dynamic images is nice.)

**Comment by kkwpsv** [comment]
We can create disk image as NTFS Sparse File? It's simple, but only for windows.
And there's a patch for pcem to support dynamic vhd [here](https://pcem-emulator.co.uk/phpBB3/viewtopic.php?t=3056). Maybe we can use it.

**Comment by surrodox2001** [comment]
> We can create disk image as NTFS Sparse File? It's simple, but only for windows.
That seems like an API function.

> And there's a patch for pcem to support dynamic vhd here. Maybe we can use it.
Probably the best way, but implementing it another story.

**Comment by kkwpsv** [comment]
Using the patch for pcem may be not too hard. 86Box is based on pcem.....
