### ISSUE TITLE
Renderer freezes when the emulator is minimized

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#732]
**Describe the bug**
The blit thread is prone to a dead lock when the emulator window is minimized. This is a follow up to #722. 

**To Reproduce**
Minimize 86Box for a longer period of time.

**Comment by dhrdlicka** [comment]
Added a `fatal` in case we don't retrieve the blit mutex ownership within a second in 3b357348b02fd18a49bf60213171ddbf1a30fd65, though this better be fixed properly.

**Comment by dhrdlicka** [comment]
![image](https://user-images.githubusercontent.com/13226155/80375262-4a3ade80-8898-11ea-80d2-397ed9190ed3.png)
:facepalm:

**Comment by OBattler** [comment]
I was told that this seems to no longer happen, so I'm closing this.
