### ISSUE TITLE
Tandy 1000 machines HardDrive bug

### ISSUE THREAD

**Issue by ToMi8088** [86Box/86Box#734]
****
Hello.
I need report bug about the HardDrives on Tandy 1000 and 1000 HX machines.

When you start the Tandy 1000 machines with HardDrive, you get this:

![20200429-182855-055](https://user-images.githubusercontent.com/64270858/80633028-671e1000-8a58-11ea-9aec-d6a48b85b879.png)

HardDrive cofiguration is: 10MB (CHS 306/4/17) [MFM/RLL]

Thank you,
ToMi.

**Host OS:**
Windows 8.1 Pro
86Box v2.10 (latest build)

**Comment by TC1995** [comment]
I might be incorrect but it may be that the Tandy 1000 machines tend to be pickier about MFM/RLL and XTA.
