### ISSUE TITLE
Some 286 configuration do not detect memory correctly

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#735]
**Describe the bug**
Some 286 configuration do not detect memory correctly

**To Reproduce**
Samsung SPC-4216P: do not recognize 4 Mb and 1Mb
Samsung SPC-4200P: do not recognize 1 Mb, cannot go far 2048Kb

**Comment by OBattler** [comment]
Needs a SCAT chipset emulation rewrite so it unfortunately will not be done in v2.10.

**Comment by Fenix770** [comment]
Hello!

I found some info, about these machines. They were ported from Pcem According the author of the patch [https://pcem-emulator.co.uk/phpBB3/viewtopic.php?f=5&t=830&p=13388&hilit=SPC+4216P#p13388](url).
The Samsung SPC-4200P supports 512KB, 640KB, 1024KB, 1536KB, 2048KB memory sizes.
and the SPC-4216P, 1MB, 2MB, 3MB, 5MB.
Hence the only bug is when 1mb ram is configuration is used.

The real machines may have part of the ram memory soldered on the board (512kb or 1mb). In that case , for example, if 2mb ram is installed it will have 3mb. and with 4mb it will have 5mb.

**Comment by OBattler** [comment]
Changing the milestone to v3.0 because it's now part of v3.0 plans to go through all chipsets, and especially SCAT also has another issue reported by Fenix770 that needs fixing, so it's going to be looked at.

**Comment by OBattler** [comment]
I just noticed Fenix770's post - which means it's not an emulator bug at all, just the machines not supporting every possible amount of RAM, and there is currently no way to to further limit this. As such, I'm closing this.
