### ISSUE TITLE
Windows 98 halts on boot with Socket 8 CPUs

### ISSUE THREAD

**Issue by banks047** [86Box/86Box#736]
**Describe the bug**
Windows 98 halts on boot screen with Socket 8, Socket 370, Slot 1 Intel  and Socket 7 AMD CPUs

**To Reproduce**
1. Set machine as any of the socket 8 ones, and choose any CPU
2. Go through the first part of the Windows 98 setup
3. Try to boot Windows 98 for the first time after setting it up

**Expected behavior**
Expected behavior is successful boot of the OS.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/64637377/80797678-bec89280-8ba2-11ea-9e5e-1a9664c17d41.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Version 2.10 2246

**Additional context**
This issue is NOT present after changing the machine to socket 7 and using one of the Pentium MMX CPUs with the same configuration (GPU, audio etc). After additional testing, it seems that booting into safe mode works. Windows 98 BOOTLOG.TXT shows that TTF fonts failed to load (which could suggest that this might be a GPU incompatibility with the selected CPUs, since it works on older ones).

**Comment by dhrdlicka** [comment]
Could you provide your configuration?

**Comment by banks047** [comment]
Sure. Be advised that the halting happens with multiple configurations (in which GPU/Audio/Mouse/etc choice doesn't matter)
[86box-config.zip](https://github.com/86Box/86Box/files/4563970/86box-config.zip)

**Comment by OBattler** [comment]
I'm trying to reproduce this but instead, I'm getting a fatal exception 0E in VPICD.VXD for some reason.

**Comment by OBattler** [comment]
Fixed the VPICD.VXD error by doing so manual IRQ reconfiguration (apparently one of the drivers doesn't like its IRQ being shared with the (dummy) USB controller or something). Now Windows 98 SE works correctly.

Are you using Windows 98 SE or the first edition?

**Comment by banks047** [comment]
I was using the first edition OEM ISO from the Betaarchive FTP which was dated 11/05/1998.

**Comment by OBattler** [comment]
OK, I'll try installing first edition then and see what happens.

**Comment by OBattler** [comment]
Are you using the old or new recompiler?

**Comment by banks047** [comment]
I haven't changed any of the recompiler options from the default ones. How do i check which one i'm using? If it helps, i've been using the skylake optimized build on a coffee lake CPU.

**Comment by qeeg** [comment]
That's the old recompiler. Maybe try the stable builds? The optimized builds are known to be a bit buggy :p

**Comment by banks047** [comment]
I've just tried the non-optimized version and it hangs as well.

**Comment by tiseno100** [comment]
could you try to re-install Windows 98 FE freshly? Probably your installation, or even the ISO is bugged. Neither I can reproduce it.

**Comment by banks047** [comment]
I've just done that, hence why it took a bit of time to report back. I can try doing with another ISO, but i don't think it's the culprit, since the whole emulator hangs, not the Windows guest.
