### ISSUE TITLE
Title screen for Digger (1983) is glitched

### ISSUE THREAD

**Issue by daviunic** [86Box/86Box#737]
**Describe the bug**
The title screen for Digger (1983 version) is glitched.

**To Reproduce**
1. Configure an IBM XT with a 4.77 MHz 8088, 640k of RAM and CGA (either composite or RGB) and boot with DOS 2.00.
2. Download Digger [here](https://www.myabandonware.com/download/24-digger) and get the files into the VM.
3. Start DIGGER.COM.
4. See the glitched title screen.

**Expected behavior**
See the start of [this video](https://www.youtube.com/watch?v=OjDCOxvY80c) for how the title screen is supposed to look like.

**Screenshots**
![screnshot](https://imgur.com/suhSqzi.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - 86Box build 2253

**Additional context**
Similar glitch is also present on PCem using the same config.

**Comment by maximus105** [comment]
I confirm this bug on builds 2094, 2257. This bug appears on MS-DOS v2.00.
![86Box_2020_05_02_15_27_35_930](https://user-images.githubusercontent.com/58270614/80864251-26a5d880-8c8a-11ea-918c-6ce1e93b2f4e.png)
![86Box_2020_05_02_15_28_11_152](https://user-images.githubusercontent.com/58270614/80864255-29083280-8c8a-11ea-9115-5e287471cdad.png)
In MS-DOS v3.30, everything is working fine.

**Comment by OBattler** [comment]
It could be the game being incompatible with MS-DOS 2.x then.

**Comment by maximus105** [comment]
Perhaps this is due to the base memory of MS-DOS. The game depends on what address will be loaded into the base memory of MS-DOS. This error with image corruption can also be observed in DOSBox-X, depending on the parameters "minimum dos initial private segment", "minimum mcb free". The game Rollo and the brush bros (1984) has the same bugs with damaged images.

**Comment by OBattler** [comment]
Since this has been determined to be due to the game being loaded too low (and is by far not the only one, one of my Wolfenstein 3D total conversions outright hangs when starting a level when loaded too low), I am closing this as NOTABUG.
