### ISSUE TITLE
Constant beep in Microsoft Decathlon

### ISSUE THREAD

**Issue by daviunic** [86Box/86Box#738]
**Describe the bug**
After event announcement in Microsoft Decathlon, a constant beep often occurs right after the event announcement tune ends until another sound plays.

**To Reproduce**
1. Configure an IBM XT with a 4.77 MHz 8088, 640k of RAM and CGA (composite) and boot DOS 2.00.
2. Download Microsoft Decathlon from [here](https://www.myabandonware.com/download/8-olympic-decathlon) and get the files into the VM.
3. Start DECATHLN.EXE
4. Play through the events to hear the constant beep after event announcements.

**Expected behavior**
After the event announcement tune ends, no constant beep should play.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - 86Box build 2253

**Additional context**
The constant beep does not happen on PCem, however the announcement tune itself is somewhat glitched there.

**Comment by maximus105** [comment]
I confirm this bug on 86Box builds 2094, 2257. This bug appears on MS-DOS v2.00 and v3.30. It works fine only in DOSBox-ECE, DOSBox SVN-Daum, DOSBox-X with cycles=240.

**Comment by OBattler** [comment]
This must certainly be an 86Box bug, in either the PIT emulation or the PC Speaker emulation (though the former control the latter).

**Comment by qeeg** [comment]
@daviunic Does this still happen on the latest builds?

**Comment by maximus105** [comment]
Yes, this bug is still present in latest builds.

**Comment by daviunic** [comment]
This still happens on build 2703.

**Comment by OBattler** [comment]
Does this still happen on the latest builds?

**Comment by daviunic** [comment]
Yes

**Comment by maximus105** [comment]
Also "Panic" game freezes when launched in 86Box on 4.77 MHz XT machine. While in PCem v17 "Panic" game runs fine on a 4.77 MHz XT machine, and runs fine in DOSBox-ECE, DOSBox-X with cycles=240. Perhaps this is also related to this bug.
[PANIC.zip](https://github.com/86Box/86Box/files/8933952/PANIC.zip)

**Comment by maximus105** [comment]
Microsoft Decathlon already works fine in build 3901 (the bug with the constant beep is no longer there). Can someone take a look at the "Panic" game freezing bug? By the way, in the 86Box on the PCjr, the game "Panic" runs fine without any freezes. Maybe the PIT for this game is correctly emulated on the PCjr machine?

**Comment by maximus105** [comment]
"Panic" game freezes when launched in 86Box on these machines only: IBM XT (1986), American XT Computer, Columbia Data Products MPC-1600, Compaq Portable, Hyosung Topstar 88T, Multitech PC-500, Xi8088, Z-NIX PC- 1600, Zenith Data Systems Z-151/152/161, [GC100A] Philips P3120. On all other 8088 machines in the 86Box, "Panic" runs fine.

**Comment by OBattler** [comment]
I think this can be closed now.

**Comment by maximus105** [comment]
The constant beep is still present in Microsoft Decathlon in the latest build of 86Box. Looks like the issue needs to be reopened.
