### ISSUE TITLE
Support "network disconnected" state for NICs

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#741]
Currently, choosing the "None" option for network driver also removes the network adapter, which is pretty annoying when you start a VM that is set up for PCap on a host that does not have WinPCap installed.

If the emulated NIC could signal a disconnected state, it would be possible to disable network without removing the actual NIC from the config, which would be a much more graceful way of handling this.

Ideally, you'd be able to connect/disconnect the virtual cable without resetting the virtual machine, which could be quite useful in some scenarios.

**Comment by elyosh** [comment]
Done in #2648

**Comment by OBattler** [comment]
Closing this.
