### ISSUE TITLE
Zida Tomato 4DP not Posting

### ISSUE THREAD

**Issue by PentiumMMX166** [86Box/86Box#743]
**Describe the bug**
When i try to use the Zida Tomato 4DP, nothing, black screen, no beeps, nothing. It shows 0B 0A on the POST card on the bar on the bottom of 86Box

**To Reproduce**
Select (Zida Tomato 4DP) on Machines, Pick any CPU and Video Card, and start it up

**Expected behavior**
I expected it to show the BIOS and start to DOS or Windows

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version: v2.10 Build 2264
 - Build type: Regular

**Additional context**
None

**Comment by tiseno100** [comment]
I can confirm it. It happens on machines utilizing the Intel CPU. My AMD works just fine with it.

**Comment by PentiumMMX166** [comment]
i tried an AMD CPU and a Cyrix CPU, No Dice. still same 0B 0A POST Code,

**Comment by tiseno100** [comment]
No no i meant real hardware.

**Comment by PentiumMMX166** [comment]
oh, I have a AMD Phenom II X4 945 OC 3.2 GHz, 8 GB DDR3 RAM, GTX 960, Windows 7.

**Comment by nerd73** [comment]
You are probably using the wrong BIOS. Only the version v1.71 of the 4DPS BIOS works, not v1.72 or later.

**Comment by PentiumMMX166** [comment]
I downloaded the Romset from https://github.com/86Box/roms and used it. ill try googling for the 1.72 Tomato board 4DPS bios and try it out.

**Comment by PentiumMMX166** [comment]
Success, the older 1.71 BIOS works like a charm.

**Comment by banks047** [comment]
Maybe updating the romset with the older BIOS would be a good idea before the issue with new BIOS is fixed.

**Comment by OBattler** [comment]
This is now solved, later Zida Tomato 4DPS BIOS'es now work, and we now officially use the 1.72G BIOS.
