### ISSUE TITLE
86Box takes a screenshot practically every frame in the Skylake Optimized versiom

### ISSUE THREAD

**Issue by supern64** [86Box/86Box#744]
**Describe the bug**
86Box takes a screenshot on practically every frame in the Skylake Optimized version

**To Reproduce**
Launch 86Box Skylake Optimized version

**Expected behavior**
86Box not taking a screenshot every frame

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v2.07 build 2008
 - Build type: optimized-skylake

**Additional context**
Regular 86Box doesn't do this, the Skylake one does

**Comment by OBattler** [comment]
Does this still happen on build 2295?

**Comment by supern64** [comment]
It's fixed, thank you,
