### ISSUE TITLE
Mouse cursor leaves trails in FreePascal's fp.exe

### ISSUE THREAD

**Issue by FreeFull** [86Box/86Box#745]
**Describe the bug**
When running `fp.exe` from FreePascal under FreeDOS 1.2, moving the mouse cursor around leaves a trail of characters. This only happens with certain boards. The bug does not happen if a Microsoft Serial mouse is selected instead of a PS/2 mouse.

Boards which exhibited this bug when tested:
* [Socket 5 NX] Intel Premiere/PCI II
* [Socket 5 FX] Intel Advanced/ZP
* [Socket 7-3V FX] Packard Bell PB640
* [Socket 7-3V HX] AOpen AP53

Boards which do not exhibit the bug:
* [Slot 1 BX] ASUS P2B-LS (Pentium II Klamath 50)
* [Socket 7 VX] Shuttle HOT-557
* [Socket 4 LX] Intel Premiere/PCI (Pentium 60)
* [Socket 7 HX] ASUS P/I-P55T2P4

Config tested: Pentium 75
128MB RAM
311MB IDE HDD
[ISA] VGA
PS/2 Mouse

**To Reproduce**
1. Install FreeDOS 1.2 from https://freedos.org/
2. Install FreePascal using `fdimples` with the install CD, or `fdnpkg install fpc`
3. `cd c:\devel\fpc\bin\go32v2`
4. `fp`
5. Create a new file or open an existing one, and move the mouse about. The bug doesn't seem to happen if no file is open.

**Screenshots**
![20200507-090711-325](https://user-images.githubusercontent.com/1496908/81276264-aea12f00-904a-11ea-9df9-56d6d65439a2.png) (The ° symbols have the blink attribute set)

**Desktop:**
 - OS: Arch Linux, Wine 5.7
 - Version: v2.10, build 2264
 - Build type: regular

**Comment by qeeg** [comment]
Can you try this on MS-DOS 6.22? I'm thinking this might be a FreeDOS mouse driver bug of some sort.

**Comment by FreeFull** [comment]
MS-DOS 6.22 doesn't come with a mouse driver. Which one should I use?

**Comment by qeeg** [comment]
You could probably use a Windows mouse driver.

**Comment by FreeFull** [comment]
I've tried the lmouse.com driver from Windows 3.11 for Workgroups, and it doesn't exhibit the issue. Still, I don't know if this is a CuteMouse bug, FreePascal IDE bug or an 86box bug, and don't have a real board to test on.

**Comment by FreeFull** [comment]
I've tested this in the latest 86Box, and the four machines that were exhibiting this bug still seem to be misbehaving in various ways.. I couldn't even get FreeDOS 1.3 to install successfully with the Packard Bell PB640 (error while copying files). With the AOpen AP53 the installer seemed to glitch out visually, and the fp.exe mouse misbehaviour also still occurs (with ctmouse). It's really quite weird.

**Comment by OBattler** [comment]
This is NOTABUG, at least on our side - it has been verified by Efflixi to also occur on real hardware: 
![imagem](https://github.com/86Box/86Box/assets/10365853/c6f1d641-bb47-499a-aab0-2cb0a78aef11) .
