### ISSUE TITLE
Add 1Mb RAM support to the 286 XT HED-919 machine.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#747]
Hello!

Feature Request: **(only if real hardware supports it)**

1. Add 1mb support to Hedaka HED-919.

**Explanation:** I didn't find very much information about this machine exept it support a maximum of 1mb RAM on-board and the CPU is 80286. The emulator currently allows 640kb at maximum.
Some AT machines allow to use the last 384kb ram as XMS, but I'm not sure about this machine.

2. Add support for high density floppy drives. 

**Explanation:** I haven't test it yet, but most XT machines do not support 1.2/1.44mb drives.
But some examples exist like the Tandy 1000 RLX-HD, which has 80286 CPU, supports 384kb of XMS RAM and has built-in 1.44mb floppy drive, however the ISA slots are 8-bits, and the hard disk is XTA.
The Tandy 1000 TL/3 has not XMS memory support, but the 720kb floppy drive can be replaced with a 1.44mb one. (These drives were not IBM standards, however).

3. Question: Is possible to backfill XMS memory using the Everex RAM Deluxe 3000 (currently emulated) or there is a limit in this particular 80286 chipset?

3b. Can the Everex card backfill XMS memory using the 8-bit transfer mode only?

Here is the only reference that I could find: [https://arvutimuuseum.ee/th99/m/E-H/32252.htm](url)

**Comment by OBattler** [comment]
We don't emulate either the Tandy 1000 RLX-HD, nor the Tandy 1000 TL/3. Though support for high density floppy drives on XT is soon going to be achievable using external FDC's.

**Comment by OBattler** [comment]
> 3b. Can the Everex card backfill XMS memory using the 8-bit transfer mode only?
Yes, if you configure its width to 8-bit.

**Comment by OBattler** [comment]
Anyway, closing this now since #1 and #3 are pretty much solved, and #2 is soon going to be.
