### ISSUE TITLE
"ASUS 386DX ISA" name and memory limits

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#792]
I have a couple of questions to ask here.

As far I know, isn't the official motherboard name of the "ASUS 386DX ISA", the ASUS ISA-386C (BIOS string: 30-0105-001292-00101111-050591-SISDFC-386) believed to be released in 1991?

86Box emulating the ISA-386C is maxed out at 16 MB, Stason reports that the ISA-386C, which uses the SiS Rabbit chipset, the memory limit is 32 MB: https://stason.org/TULARC/pc/motherboards/A/ASUS-COMPUTER-INTERNATIONAL-386-ISA-386C.html

Would it be possible to correct these errors?

Thanks.

**Comment by ppgrainbow** [comment]
Edit. I have learned that the ISA-386C uses one of the four SiS Rabbit chipsets: 85C310, 85C320, 85C330 or 85C206 which creates a bit of confusion on the memory limits of each of the four SiS Rabbit chipsets.

**Comment by OBattler** [comment]
It's all the same chipset: SiS 85c310/320/330 (three chips), and the 82c206 (85c206 must be a typo, the 85c320 datasheet calls it 82c206) is an OPTi Super I/O chip.

**Comment by ppgrainbow** [comment]
> 
> 
> It's all the same chipset: SiS 85c310/320/330 (three chips), and the 82c206 (85c206 must be a typo, the 85c320 datasheet calls it 82c206) is an OPTi Super I/O chip.

Thank you for explaining this issue. I appreciate it. :)

Do all of the four chipsets that you mention have a 16 MB limit? Just wondering.

**Comment by OBattler** [comment]
It's not four chipsets, it's one chipset with four chips, so the limit is 16 MB.
