### ISSUE TITLE
CDDA won't play from CUE/BIN images

### ISSUE THREAD

**Issue by ZILtoid1991** [86Box/86Box#794]
Usually it results in games not having any audio, but also sometimes renders certain games unplayable (like Genocide 2) due to how it handles the CD drive. Opencubic Player sees all the tracks, but doesn't play them, and the hundredth seconds time counter constantly jumps between 00 and 10.

So far this only happens with CD audio being in the BIN file. Could not test it with ISOs or CUE/BIN images that has one or more additional files for CD-tracks.

I've tried to switch CD speeds, but it seems to not have an effect on this problem.

My test environment:

* Windows 10 with the latest updates.
* 86Box v2.07, Haswell optimized build.
* Tested images so far: Astrocounter of Crescents, Genocide 2, SAF.

**Comment by OBattler** [comment]
Did you click on the CD icon on the status bar, make sure it's not set to Mute, and restarted the emulator after that?

**Comment by ZILtoid1991** [comment]
Yes, that was the first thing I've checked.

**Comment by ZILtoid1991** [comment]
I've checked the mute button again just in case, and if checked it jumps between 00 and 05 instead in Opencubic Player, with no sound.

**Comment by ZILtoid1991** [comment]
I've changed the driver to BTC, it seems it solved the issue, but I'll conduct some further testing before closing the issue.

Might have been the case of a buggy driver.

**Comment by OBattler** [comment]
Well, this is why I asked you to upload the driver so I can do some logging and see if it's a driver bug or not.

**Comment by ZILtoid1991** [comment]
[cdrom.zip](https://github.com/86Box/86Box/files/4761657/cdrom.zip)

This contains most of the drivers I've tried.

In the end I've used the Acer driver, as the BTC caused other bugs in certain games.

**Comment by mgtroyas** [comment]
I experience the same problem running Carmageddon from a cue/bin image on Windows 98.

**Comment by NicknineTheEagle** [comment]
I have the exact same issue, using oakcdrom driver. Worth noting that CD Audio works fine under PCem from the same image.

**Comment by OBattler** [comment]
Try disabling FLOAT32 sound in Settings.

**Comment by NicknineTheEagle** [comment]
Nope, it still very quiet.

**Comment by OBattler** [comment]
What sound card are you emulating? If it's the Sound Blaster 16, you'll need to use its mixer to increase the CD Audio volume.

**Comment by NicknineTheEagle** [comment]
It's already at 9/10. Increasing it to 10 makes CD Audio more audible but it's still quieter than one would expect.

**Comment by OBattler** [comment]
What about the maste rvolume?

**Comment by NicknineTheEagle** [comment]
Master volume is at 9, too. That doesn't really matter, though, we're talking CD volume relative to other sounds.

**Comment by OBattler** [comment]
What CD is it? Because I don't have this problem, unless it's new one (I need to test).

**Comment by NicknineTheEagle** [comment]
I'm using Quake for testing (matches this: http://redump.org/disc/2251/).

**Comment by OBattler** [comment]
Wait for the latest commit to compile and then try that, CD volume should be about 4 times as high now.

**Comment by OBattler** [comment]
Also, that is a temporary fix, because I'm trying to bring back the sound card filters to the CD Audio (and I should also redo the ATAPI CD Audio volume steps according to the ATAPI specification).

**Comment by NicknineTheEagle** [comment]
Alright, the volume seems correct now.

**Comment by OBattler** [comment]
I just committed the proper improvement, now CD Audio attenuation is calculated per the ATAPI specification and proper sound card volume calculation and filtering is applied to CD Audio as well. See if it's correct now.

**Comment by NicknineTheEagle** [comment]
Now CD Audio is very loud, louder than on host. Then again, maybe it's supposed to be like that, I have a real machine with SB Live and, in DOS mode, CD Audio is super loud by default there, too, I had to reduce its volume to half the default in mixer settings.

**Comment by OBattler** [comment]
I just fixed that but now I'm having noticable clipping on CD Audio on the SB16, which I'm in the process of trying to fix now.

**Comment by OBattler** [comment]
I figured out why that was (it was the SB16 low-pass filter), but now I asked for more information on Vogons, so I can make sure I do this right.

**Comment by OBattler** [comment]
Status update: I have received no reply on Vogons, so I'm going to just apply bass and treble to it, and move the low-pass filtering to sound.c because mostly all drives low-pass filter the CD Audio.

**Comment by OBattler** [comment]
This is now committed, and as such, I'm now closing this.
