### ISSUE TITLE
Add Gateway 2000 machines

### ISSUE THREAD

**Issue by PentiumMMX166** [86Box/86Box#795]
**Is your feature request related to a problem? Please describe.**
I want some GW2K systems to be added like the 4DX2-66V, P5-75 (OEM Intel Zappa), etc.

**Describe the solution you'd like**
I have usually seen Compaq, IBM, Packard Bell, etc. on this emulator, but why not some Gateway 2000 systems.

**Describe alternatives you've considered**

**Additional context**

**Comment by OBattler** [comment]
I just merged that, though I need to go through it to make sure it works.

**Comment by anabate123** [comment]
@PentiumMMX166 I have another machine I might be able to help you out with... right here.

https://github.com/86Box/86Box/pull/805

**Comment by OBattler** [comment]
The 4DX2-66V is not feasible, because it uses a MIC 471 chipset, for which I can't find any datasheet. The Gateway 2000 versions of Zappa, Thor, and Venus have been added, however.

**Comment by OBattler** [comment]
Since the rest have been added, I'm closing this.
