### ISSUE TITLE
Screen configurations for  CGA LCD laptop machines

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#798]
Feature request:

Screen configuration options for CGA LCD laptop machines (not the T3100 which has an orange plasma screen)  
Add an option to enable/disable the Blue backlight and to invert black/white colors.

For Toshiba T1000/1200 (In some Youtube videos the Zenith Datasport also have a blue backlight screen).

1. Some machines with LCD screen have the option to disable the  blue backlight of the screen to save battery life or enable it to enhance the readability.
(with backlight disabled the screen should look gray/light green like the PPC/512/640)

For the mentioned machines, and also PPC 512/640

2. Also in some machines there is an option with jumpers or with a software to invert the CGA screen
(Dark background in the LCD screens). 

Example: The game Welltetris have an option for inverted CGA graphics mode that looks better than the native black text and blue background.

**Comment by OBattler** [comment]
#1 is doable, #2 not really as it would require hardware documentation which we currently do not have. Hence I'm only going to implement #1.
