### ISSUE TITLE
Gateway 2000 Zappa machine wrong CPUID

### ISSUE THREAD

**Issue by banks047** [86Box/86Box#804]
**Describe the bug**
CPU clock speed is inaccurate in BIOS

**To Reproduce**
1. Pick Gateway 2000 Zappa machine
2. Boot

**Expected behavior**
When choosing Pentium 75, to show Pentium 75MHz (instead of 100MHz as it does)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v2.10 2332
 - Build type : all

I'm attaching the config and nvr
[86boxconfig.zip](https://github.com/86Box/86Box/files/4772854/86boxconfig.zip)

**Comment by dhrdlicka** [comment]
This could be a BIOS bug, actually.

**Comment by banks047** [comment]
If it appears to be the case, please close the issue.
