### ISSUE TITLE
Sound Blaster 16 broken on Windows 98

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#806]
**Describe the bug**
Sound Blaster 16 wave audio does not play at all on Windows 98. MIDI and audio CD work fine, however.

**To Reproduce**
1. Play any kind of sampled audio like a wav file
2. Then play a MIDI file
3. Play an audio CD cue

**Expected behavior**
Wave audio should be working properly like MIDI and CD audio.

**Screenshots**
Playing a wav:
![86box_1](https://user-images.githubusercontent.com/29031916/84598816-fb74f280-ae9f-11ea-8254-8ec5aedac340.PNG)
Playing a MIDI:
![86box_2](https://user-images.githubusercontent.com/29031916/84598827-10518600-aea0-11ea-97bf-a51c34fb0ee8.PNG)
Playing an audio CD:
![86box_3](https://user-images.githubusercontent.com/29031916/84598882-6aeae200-aea0-11ea-84e1-9e78a1acde9b.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.900
 - Version v2.10 build 2342
 - Build type Skylake optimized

**Additional context**
Emulated machine is an ASUS P/I-P65UP5 with Pentium 2 Klamath 75MHz and 64MB RAM.

**Comment by dhrdlicka** [comment]
Could you check the device manager to see if the Sound Blaster 16 is configured properly?

**Comment by WinFutureX** [comment]
Win98 doesn't detect any problems.
![86box_8](https://user-images.githubusercontent.com/29031916/84599560-7391e700-aea5-11ea-99c0-7a88e0508b88.png)

**Comment by OBattler** [comment]
16-bit DMA reads were broken, that's now fixed. See if wave plays now.

**Comment by WinFutureX** [comment]
Yes, wave audio is working properly now.
