### ISSUE TITLE
S3 Trio64V+ emulation

### ISSUE THREAD

**Issue by anabate123** [86Box/86Box#807]
**Is your feature request related to a problem? Please describe.**
I've discovered that the Intel TE430VX has an optional onboard S3 Trio64V+

**Describe the solution you'd like**
I would like to see if I can emulate the S3 Trio64V+ family of graphics cards, including...
S3 Trio64V+ (Onboard)
Diamond Stealth 64 2001 (S3 Trio64V+)

**Describe alternatives you've considered**
I've considered using the Diamond Stealth 64 DRAM (S3 Trio64) but not 64V+

**Additional context**
Video BIOS: http://www.vgamuseum.info/index.php/component/k2/item/download/515_8b399cb384bc765c400ada31927f299d
Datasheet: http://www.vgamuseum.info/index.php/component/k2/item/download/516_2bbbf61d0bbde9fe22086633b5908851

**Comment by tiseno100** [comment]
It'll require it's MPEG accelerator emulated too. So it's kind of harsh for now.

**Comment by anabate123** [comment]
And here's the datasheet for that MPEG accelerator, the Scenic MX2.
http://www.bitsavers.org/components/s3/DB020-0.2_Scenic_MX2_MPEG-1_Audio_Video_Decoder_Jun1995.pdf

**Comment by anabate123** [comment]
If it's PCI, then here is this datasheet.
http://www.bitsavers.org/components/s3/DB017-0.2_Scenic_MX1_PCI_MPEG-1_Audio_Video_Decoder_Jun1995.pdf

**Comment by anabate123** [comment]
Never mind, it's been added.

**Comment by OBattler** [comment]
Closing this because it's already done now.
