### ISSUE TITLE
Full screen stretch modes leaves the host mouse in borders

### ISSUE THREAD

**Issue by Winins0** [86Box/86Box#812]
**Describe the bug**
When you exit a stretch mode in fullscreen, the mouse is kept in borders, mostly the current resolution of the machine. It is really painful in DOS windows, and it sometimes makes the host unusable.

**To Reproduce**
1. Click on "View"
2. Click on "Fullscreen stretch modes"
3. Select "Integer scale"
4. Go to fullscreen and exit

**Expected behavior**
The mouse should move freely after leaving fullscreen, similar to most emulators.

**Desktop (please complete the following information):**
 - OS: Windows 10 v1903
 - Version: 2.10 (nightly)
 - Build type:Regular

**Comment by Winins0** [comment]
Now that this issue has been fixed I am closing this.

**Comment by maximus105** [comment]
This bug has not been fully fixed. If full screen mode is set to 4:3 aspect, then when exiting full screen mode, the mouse gets stuck at the top of the screen and the mouse cannot be lowered down the screen. You have to click on another inactive window to unlock the mouse. The idea is that the mouse should immediately unlock if you exit full-screen mode.

**Comment by Winins0** [comment]
Please open a new issue for this, as the issue I am mentioning has been fixed.
