### ISSUE TITLE
FDC controller UI bugs

### ISSUE THREAD

**Issue by Winins0** [86Box/86Box#821]
**Describe the bug**
The FDC controller UI has several bugs, such as cutoff.

**To Reproduce**
1. Go to Settings
2. Click on Other Peripherals
3. Scroll down to FDC controller

**Expected behavior**
The FDC controller UI should be like all the other ones, like no cutoff.

**Screenshots**
![fd](https://user-images.githubusercontent.com/65453129/85014154-68bda780-b16e-11ea-958d-9fa831fb6be8.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.10 (nightly)
 - Build type Experimental

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by TC1995** [comment]
Eh, I know that, I'm not good with ui parts :p
