### ISSUE TITLE
Adding TX Pro II motherboard series

### ISSUE THREAD

**Issue by kyousif87** [86Box/86Box#823]
TX Pro II by PCChips

SiS 5598 chipset

Motherboards: M567, M571, M596

**Comment by tiseno100** [comment]
Due to the complexity of SiS chipsets it might not get thrown that quickly. Also it wouldn't be emulated fully like it's integrated video.

**Comment by kyousif87** [comment]
Is there any way I can help with that?
Sadly though, I am not a programmer.

**Comment by OBattler** [comment]
Just going to note that unfortunately, this is not feasible right now due to the SiS 5598 having on-chip graphics. Maybe in the future, though.
