### ISSUE TITLE
Add 8514/ATi Mach8/32 emulation

### ISSUE THREAD

**Issue by OBattler** [86Box/86Box#842]
Add 8514/ATi Mach8/32 emulation (http://www.mcamafia.de/mcapage0/adf/cef7f.adf, http://www.mcamafia.de/mcapage0/adf/@ef7f.adf) .

**Comment by OBattler** [comment]
I'm effectively going to consider this done. No Mach8 or Mach32 yet, but it's not that hard to add them.

**Comment by pankoza2-pl** [comment]
and now, Mach8 and Mach32 (as well as a standalone INMOS XGA) are done as well!
