### ISSUE TITLE
Implement 86S support

### ISSUE THREAD

**Issue by OBattler** [86Box/86Box#846]
Implement 86S support.

Tasks:
- [ ] Clean-up floppy/fdd_d86f.c;
- [ ] Add support for the 86S descriptor files.

**Comment by Flyers80** [comment]
Too bad, I've been waiting for this implementation for a long time :(

**Comment by OBattler** [comment]
Don't worry, it will come.

**Comment by OBattler** [comment]
Also add an instant access FDC to work around the FDC dynamic recompiler problems.

**Comment by OBattler** [comment]
I have made the decision to keep 86F as is and instead add a new 86R format based on modified MFM, because I already have the code for that for both 86Box and HxC.

**Comment by OBattler** [comment]
Actually, we have now made the decision to only keep 86F, since 86F basically supports everything needed. So I just need to write proper 86F support for HxC and that's it.

**Comment by OBattler** [comment]
I think this is pointless now - 86S was going to just be a kludge to run stuff like DBase III when there was no way to convert stuff to 86F, but since we now have dbalsom's Fluxfox and Digiton's convert to converrt stuff to 86F, it's no longer needed. As such, I'm closing this.
