### ISSUE TITLE
Configure button is not disabled when the graphics card is automatically set to "None" 

### ISSUE THREAD

**Issue by 128x16** [86Box/86Box#850]
**Describe the bug**
When the graphics card is automatically set to "None" when picking an incompatible board, the "Configure" button is not disabled.

**To Reproduce**
1. Select a PCI graphics card.
2. Select a motherboard that doesn't have PCI support.

**Expected behavior**
"Configure" should be disabled.

**Desktop (please complete the following information):**
 - OS: Wine 5.10
 - Version v2.10 build 2368
 - Build type: Dev

**Comment by 128x16** [comment]
Sorry, I accidentally submitted it while typing out the issue. I've edited it now.

**Comment by OBattler** [comment]
This is part of the wider problem that the Settings dialog makes no attempt at sanitizing the specified hardware on machine change, so the combo boxes will display something sane but the actual selection is going to be whatever it was before. I'm going to look at this for v3.0 already as this is the kind of bug we can't release with.

**Comment by OBattler** [comment]
Moved to v3.1 as that's going to be the version focused on the UI.
