### ISSUE TITLE
Add anti-aliasing

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#854]
Please add anti-aliasing to the 86Box similar to the DOSBox parameter: scaler = advinterp2x forced.

**Comment by OBattler** [comment]
This is going to require the renderer rewrite to be done first, before we are able to do any advanced stuff like this.

**Comment by OBattler** [comment]
Closing this because the shaders in the OpenGL 3.3 renderer might be able to do this.

**Comment by ts-korhonen** [comment]
There are indeed some shaders that do anti-aliasing. One that I believe is very similar is [advanded-aa](https://github.com/libretro/glsl-shaders/blob/master/anti-aliasing/shaders/advanced-aa.glsl).
