### ISSUE TITLE
x64 recompiler is broken

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#856]
**Describe the bug**
When I start a machine that uses a dynarec on x64 emulator builds, the emulator segfaults. It used to work in older versions/commits though.

**To Reproduce**
1. Set up the config so that the machine's CPU is using a dynarec
2. Save and reset
3. `Segmentation fault` during BIOS

**Expected behavior**
The machine should successfully boot.

**Screenshots**
![86box_dbg](https://user-images.githubusercontent.com/29031916/85208546-ff9f8500-b363-11ea-9814-a8f172517b6e.PNG)

**Desktop (please complete the following information):**
 - OS: Win10 2004 build 19041.329
 - Version v2.10
 - Build type dev (latest commit at this time of writing), custom-compiled with `X64=y DEV_BUILD=y DEBUG=y OPTIM=n DFLAGS="-g3 -ggdb -DDEBUG" COPTIM=-O0 VNC=n`

**Additional context**
![86box_dbgdump](https://user-images.githubusercontent.com/29031916/85208610-67ee6680-b364-11ea-8316-43fe6f23d385.PNG)

**Comment by tiseno100** [comment]
The x64 recompiler isn't even meant to be used officially yet. It's on early stages of development so most issues are things we are aware of.

**Comment by OBattler** [comment]
This doesn't even seem to be a recompile bug, since it appears to affect the interpreter.

**Comment by OBattler** [comment]
This bug is now fixed, so this can be closed.
