### ISSUE TITLE
AcerMagic S20 emulation

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#859]
**Is your feature request related to a problem? Please describe.**
A very specific situation: when setting up a system using the Acer V30 motherboard, and using the Acer CPR restore media for an OEM installation, it installs drivers for the AcerMagic S20 sound card, but the card is not emulated yet, so sound will not work.

**Describe the solution you'd like**
The AcerMagic S20 was a Sound Blaster Pro clone by Acer, featuring an OPTi 82C929A chip set for Sound Blaster compatibility, a Crystal CS4231A-KL codec for Windows Sound System compatibility, and a real Yamaha YMF-262M chip for true OPL3 FM synthesis. Certain revisions also feature interfaces for Mitsumi, Sony, Panasonic, and generic IDE CD-ROM drives.

**Describe alternatives you've considered**
Sound will not fully work under Acer OEM installations when any of the currently-supported sound cards are selected, but I've had the best results using a Windows Sound System, since the Sound Blaster cards are not compatible; selecting one will give a blue screen complaining the Windows Sound System was not found. Whatever is selected, Windows will complain of missing drivers, and FM synthesis will work in Windows, but PCM audio will not.

I have not done extensive testing with DOS, but when I selected a Sound Blaster 16, music worked in Epic Pinball--I didn't play any of it, so I don't know if sound effects worked. I also didn't test DOS games with WSS.

Of course, the best solution for now would be to install a generic copy of DOS and Windows (not using Acer CPR), or even Windows 95, and select a proper Sound Blaster card, but where's the fun in that? I find OEM installations oddly fascinating.

**Additional context**
Datasheets for the OPTi 82C929 and Crystal CS4231A are available online; not sure if linking them or attaching them is allowed.

**Comment by OBattler** [comment]
Feel free to link or attach them.

**Comment by OBattler** [comment]
Though, I found the 82C969 datasheet, and it mentions Windows Sound System compatibility in addition to Sound Blaster compatibility, so I'm not quire sure what the CS4231A is for.

**Comment by headsetguy37** [comment]
[cs4231a.pdf](https://github.com/86Box/86Box/files/4870538/cs4231a.pdf)
Here's the datasheet for the CS4231A.

**Comment by headsetguy37** [comment]
[82C929.pdf](https://github.com/86Box/86Box/files/4870550/82C929.pdf)
And here is the 82C929 datasheet, which says that it provides Windows Sound System compatibility _with_ a Crystal 4231.

**Comment by headsetguy37** [comment]
I was doing some experimentation... I discovered that if I set the sound card to either of the Aztech Sound Galaxy cards, it does play sound in Windows, but it skips. This is regardless of whether I set the codec to the CS4228 or the CS4231 (incidentally, the fact that they both have a CS4231 is why I decided to try those). I honestly wasn't expecting that selecting any sound card would give me sound.

**Comment by OBattler** [comment]
Asked RichardG if this is doable.

**Comment by headsetguy37** [comment]
If the 82C929 is implemented, just having a generic device based on that chipset would probably also work. I know Acer was not the only company to make a sound card with that chipset.

**Comment by headsetguy37** [comment]
If this card (or a generic "OPTi 82C929" or "OPTi MAD16 Pro") is implemented, there should also be a choice to use either a Crystal CS4231 (already implemented, which I did not realize when I originally opened this) or an Analog AD1848 (also already implemented) as the codec. The chipset was compatible with both, but one of the registers is different to address a timing issue with the CS4231.

**Comment by headsetguy37** [comment]
At the moment, using the Sound Galaxy, setting the chipset to a CS4231, and setting the WSS DMA to 1, will cause sound to play in Windows 3.11 with no skipping. However, I am leaving this request open for the time being.

**Comment by OBattler** [comment]
I guess this makes the AcerMagic S20 possible to add as a variant of the Sound Galaxy fixed to CS4231 and I guess also fixed to DMA 1.

**Comment by headsetguy37** [comment]
Hmm, maybe? The DOS driver (which, to be fair, is only the CD-ROM interface) says "Sound card not detected. CD-ROM interface aborted." if I select a Sound Galaxy, but other than that... I guess if it works, it works.

**Comment by TC1995** [comment]
Ok good, but which Sound Galaxy? We have two of them.

**Comment by headsetguy37** [comment]
> Ok good, but which Sound Galaxy? We have two of them.

I've had success with the Washington card. I haven't tested it with the Clinton card yet.

**Comment by rderooy** [comment]
Just to add some more details for future reference. There were apparently two variants of the AcerMagic S20:

- AcerMagic S20 94362-2 with IDE, Panasonic, Sony and Mitsumi CD-ROM interfaces
- AcerMagic S20 94362-4 without CD-ROM interfaces

The AcerMagic S20 was apparently based on the OPTi MAD16 Pro
http://dosdays.co.uk/topics/Manufacturers/opti.php

**Comment by headsetguy37** [comment]
@rderooy You are correct on both fronts.

**Comment by OBattler** [comment]
I could add the Mitsumi interface as a choice, as we do have a not-yet-hooked-up implementation of it already. And IDE can be added as well.

**Comment by headsetguy37** [comment]
Any thoughts on changing the chipset? I have the datasheet for the 82C929 here and in #2802.

**Comment by OBattler** [comment]
We do now emulate the OPTi 82c829.
