### ISSUE TITLE
Keyboard input doesn't work in fullscreen using Intel YM430TX

### ISSUE THREAD

**Issue by windows-95-420** [86Box/86Box#864]
Keyboard input doesn't work in fullscreen on the Intel YM430TX mobo, but it works fine in windowed mode

**To Reproduce**
I used the Intel YM430TX mobo and ran windows 95 setup and keyboard input didnt work in fullscreen. I believe this is the case with every other os, too. To reproduce, use the Intel YM430TX mobo, and go fullscreen. No keyboard input.

**Expected behavior**
I expected it to work like i did in windowed mode, with keyboard input.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004
 - Version v2.10 build 2376
 - Build type: Optimized (Skylake)

**Comment by windows-95-420** [comment]
It appears as if it thinks that the control key is being held down whilst in fullscreen.

**Comment by OBattler** [comment]
Press CTRL again, sometimes it gets stuck.

**Comment by windows-95-420** [comment]
> Press CTRL again, sometimes it gets stuck.

Tried that, no luck

**Comment by OBattler** [comment]
Try also pressing ALT again.

**Comment by OBattler** [comment]
Since this was just keys getting stuck (which should be fixed by the upcoming keyboard controller + keyboard rewrite, anyway), I'm closing this.

**Comment by madsboddum** [comment]
> Try also pressing ALT again.

Had this issue just now and after having used the CTRL+ALT+PGUP hotkey for fullscreen, pressing ALT did the trick. Thanks!
