### ISSUE TITLE
[BUG] Phoenix 80386 ROM BIOS (ADI 386SX and Goldstar 386SX) fail to detect hard drives using MFM/RLL controller 

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#865]
I would like to file a bug report regarding one of the 386SX-based machines that uses the Phoneix 80368x ROM BIOS PLUS since restoration in build 2386.

On the emulated ADI 386SX (running at 16 MHz with 2 MB of RAM), I have created two 40.8 MB MFM hard disk drives (820/6/17) using the IBM PC/AT Fixed Disk MFM/RLL adapter.

Here's a screenshot of what the CMOS setup looks like:

![20200624-082636-645](https://user-images.githubusercontent.com/32658796/85525119-9fa41b00-b5bd-11ea-85d1-3c6a6c19d01b.png)

Both of the hard drives use predefined type 44.

However when the Phoenix 80386 ROM BIOS PLUS tries to detect the hard drives on the MFM/RLL controller, I end up getting "Hard disk failure" x 2 error messages:

![20200624-083438-426](https://user-images.githubusercontent.com/32658796/85525363-e134c600-b5bd-11ea-879c-ab058ff276a7.png)

Upon pressing the F2 key to enter CMOS setup, I get a error:

![20200624-081211-832](https://user-images.githubusercontent.com/32658796/85525597-14775500-b5be-11ea-8f9a-ab0fc7c9d226.png)

Here is the current 86box.cfg file for the ADI 386SX emulated machine: https://pastebin.com/RzAR8kgz

Please investigate this issue on what could be causing the machine to not properly detect the hard drives when using the MFM/RLL controller.

Thank you for your time. :)

**Comment by ppgrainbow** [comment]
I also have a problem with the Goldstar 386SX machine as well. I'm getting a hard disk failure when the hard disk drives are plugged into the IBM PC/AT MFM/RLL fixed disk adapter:

![20200625-061224-269](https://user-images.githubusercontent.com/32658796/85665746-860fdb80-b670-11ea-90c3-6528743471c6.png)

It sounds to me that the problem involves the Phoenix 80386 ROM BIOS that doesn't seem to properly detect MFM/RLL hard disks or its controllers.

**Comment by tiseno100** [comment]
As they both work just fine with IDE, it's a BIOS issue than an emulator one. Considering also MFM was kind of fading at the time.

**Comment by ppgrainbow** [comment]
I didn't know that it was a issue with the BIOS not detecting MFM/RLL drives.

The bright part is that I'm really proud to see the ADI 386SX working again. :)
