### ISSUE TITLE
Toshiba T1000 failed to boot from the DOS system in the rom.

### ISSUE THREAD

**Issue by kkwpsv** [86Box/86Box#872]
**Describe the bug**
Toshiba T1000 failed to boot from the DOS system in the rom.

**To Reproduce**
Just create a new machine of Toshiba T1000 with 512KB ram and Internal video adapter, and run it.
It will complain 'No ROM DISK', but can boot from floppy.

**Expected behavior**
Not complain 'No ROM DISK' and boot from the DOS system in the rom.

**Screenshots**
![image](https://user-images.githubusercontent.com/11524048/85895392-37597180-b829-11ea-974e-a9cc9a1cb473.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: build 2396
 - Build type: optimized

**Additional context**
This bug happened in 86box and VARCem, not in pcem.
I have checked the rom image is the same.

**Comment by maximus105** [comment]
I confirm this bug. If you install [ISA] [MFM] DTC-5150 Fixed Disk Adapter with a connected image of 40 MB with MS-DOS v3.30, the system does not boot:

**Screenshots**
![20200627-113307-458](https://user-images.githubusercontent.com/58270614/85921282-d90dac80-b883-11ea-9c08-a05bfd9423fb.png)

In addition, a maximum of 1280 KB of memory can be set in the configuration menu, while 640 KB is still available at system startup.

**Comment by kkwpsv** [comment]
> I confirm this bug. If you install [ISA] [MFM] DTC-5150 Fixed Disk Adapter with a connected image of 40 MB with MS-DOS v3.30, the system does not boot:
> 
> **Screenshots**
> ![20200627-113307-458](https://user-images.githubusercontent.com/58270614/85921282-d90dac80-b883-11ea-9c08-a05bfd9423fb.png)
> 
> In addition, a maximum of 1280 KB of memory can be set in the configuration menu, while 640 KB is still available at system startup.


The T1000 bios may not support your Disk Adapter.
And the memory of this machine is special. Not all memory is used as ram.

You can see the comments of the [file](https://github.com/86Box/86Box/blob/master/src/machine/m_xt_t1000.c).

**Comment by kkwpsv** [comment]
@OBattler  why this is not a bug?
