### ISSUE TITLE
IBM PS/1 2121 Unable to boot from hard disk

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#874]
**Describe the bug**
I created a Hard Disk in IBMulator. The disk boot without any issue in that emulator, but does not boot on 86box.
(I used Internal IDE controller as HD controller)
However I found two strange behaviors in 86box.

1. If I boot from the floppy disk, the hard disk is recognized
2. After I use the "SYS C:" command the prompt says "System transferred", and both Winimange and 7-Zip shows the IBMBIO.COM and IBMDOS.COM files with Read only/Hidden/System attribute. But its only bootable on IBMulator

I tried to create the hard disk in 86box but its still unable to boot.
Here is the image file with DOS and Windows 3.0
[HDD2121.zip](https://github.com/86Box/86Box/files/4839692/HDD2121.zip)

PD: The SYS command copies the COMMAND.COM file, but 86box and also Winimage 10 can not see this file.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1909 
 - Build type: regular

**Comment by dhrdlicka** [comment]
What 86Box version/build does this happen on? I thought "[e.g. v2.06 build 2007]" would make it more than obvious that it's the emulator version we are interested in.

**Comment by Fenix770** [comment]
I use the latest commit of the version 2.10, but this bug is old.  I used IBMulator for this emulated machine because it has floppy and Hard disk sounds and PC speaker filters.

**Comment by OBattler** [comment]
What CHS parameters did you use for the hard disk?

**Comment by Fenix770** [comment]
The C/H/S parameter is 164/16/63. The PS/1 2121 has standard IDE controllers.

**Comment by OBattler** [comment]
That doesn't mean every geometry is going to be supported. Some machines have problems with 16 heads and cap them at 15 instead.

**Comment by Fenix770** [comment]
**Problem Solved:** 86box wrongly assumes that the IDE disk have 16 heads and 63 sectors. I configured the same disk as 
C/H/S 923/5/36, and works correctly in PCEM.

I Found the correct geometry in the IBMulator page. There are only two geometries for 81mb hard disks.
[https://barotto.github.io/IBMulator/](url)

**Comment by OBattler** [comment]
That's why 86Box gives you the option of manually specifying the CHS when you load a hard disk image, so you can correct the CHS if the emulator has made the wrong assumption.
