### ISSUE TITLE
[8086] Amstrad system does not boot

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#876]
**Describe the bug**
In configurations Amstrad PC2086, Amstrad PC3086, Amstrad PC20(0), Amstrad PPC512/640, if you install [ISA] [MFM] fixed disk adapter DTC-5150 with a connected image of 40 MB in MS-DOS v3.30, the system will not boot:

**Screenshots**
![20200627-115200-348](https://user-images.githubusercontent.com/58270614/85921719-f09a6480-b886-11ea-8a5e-57499b9c442b.png)
![20200627-115222-975](https://user-images.githubusercontent.com/58270614/85921720-f09a6480-b886-11ea-89dc-5c8f74ffd003.png)
![20200627-115245-081](https://user-images.githubusercontent.com/58270614/85921722-f132fb00-b886-11ea-9154-74a69b1f3318.png)
![20200627-115304-956](https://user-images.githubusercontent.com/58270614/85921721-f09a6480-b886-11ea-8539-21628d9ec312.png)

At the same time, in the configuration of Amstrad PC1640, the same [ISA] [MFM] fixed disk adapter DTC-5150 with a connected image of 40 MB in MS-DOS v3.30 is loaded without errors.

In addition, if you install the CPU Type 8086/12 MHz or 16 MHz, then all of the listed systems will not start:

**Screenshots**
![20200627-111645-317](https://user-images.githubusercontent.com/58270614/85922031-158fd700-b889-11ea-8327-1abea321b6ef.png)

In addition, does not start [8086] Olivetti M24 if you install the CPU Type 8086/16 MHz:

**Screenshots**
![20200627-112317-238](https://user-images.githubusercontent.com/58270614/85922139-b1214780-b889-11ea-8096-a5d20d969177.png)

**Desktop (please complete the following information):**
 - Windows 10 x64 2004
 - 86Box v2.10 Build 2399
 - Build type: [optimized]

**Comment by Fenix770** [comment]
Hello!.
I don't know if that bug you describe is related to 

1. The hard disk controller only supports disk models/geometry specified in the manual. 

Check in the (page 4 of the) manual if your emulated hard disk has the heads and cylinders configurations supported by the controller. Here is the manual.
http://www.minuszerodegrees.net/manuals/DTC/DTC%205150X%20-%20Installation%20Guide.pdf

The CPU clock

2. Most 8088/8086 cpu supports a maximum speed of 10 Mhz. Only some clones could reach 12 mhz. And, In theory some also rare NEC V30 CPUs (8068 clones with 286 real mode instruction support) can reach 16mhz. (If I recall correctly) The reason for this is 8-bit ISA bus is not stable beyond 10 mhz.

**Comment by maximus105** [comment]
@Fenix770 I use an HDD image with the following parameters:
![2020-06-28_135751](https://user-images.githubusercontent.com/58270614/85945623-c0ff6100-b947-11ea-8c5b-a14528ec0d3c.jpg)

**Comment by Fenix770** [comment]
Hello!

I didn't know the disk parameters, that corresponds to the diskST-4051, according the manual of the controller board. You are right, it should boot in all systems configured with that board.

**Comment by OBattler** [comment]
Are we sure the affected Amstrads even support option ROM's?

**Comment by maximus105** [comment]
I changed the MFM controller to Acculogic XT IDE and MS-DOS v3.30 boots fine on all Amstrad machines.

**Comment by OBattler** [comment]
I guess this can be closed then.
