### ISSUE TITLE
Hedaka HED-919 Crash with 1024kb of RAM

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#877]
**Describe the bug**

If the machine is configured with 1024kb 86box crashes and closes. The machine runs flawlessly if the RAM memory amount is configured in 640kb or less.

I believe this is a bug because the 1mb of RAM limit and the presence of an 80286 CPU, which in theory it should map the last 384kb as XMS, another explanation may be the board has no memory remap capabilities and the extra memory is used for a unknown hardware specific function. I could not find any manual or data sheet for this board.

**To Reproduce**
Just configure the board with 1024kb of RAM and run. 

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 1909
 - 86Box version: 2.10
 - Build type: regular (the last commit)

**Comment by OBattler** [comment]
Closing this as the machine is getting removed due to it using a completely undocumented chipset anyway.
