### ISSUE TITLE
WD1004A-27X Fixed Disk Adapter gets wrong disk geometry.

### ISSUE THREAD

**Issue by kkwpsv** [86Box/86Box#878]
**Describe the bug**
WD1004A-27X Fixed Disk Adapter gets wrong disk geometry.

**To Reproduce**
Use Amstrad PC2086 machine and WD1004A-27X Fixed Disk Adapter, which is the default disk adapter for this machine.
Use a disk with 615/4/26 (C/H/S). The geometry is for Western Digital WD383R, which is also the default disk for this machine.
Start the machine with MS-DOS 3.30 [Amstrad OEM].
Then run `device`, which report wrong disk geometry. So does `fdisk`.

**Expected behavior**
Report right disk geometry.

**Screenshots**
![image](https://user-images.githubusercontent.com/11524048/85939740-8ba84280-b94a-11ea-835e-692253cfb2a0.png)
![image](https://user-images.githubusercontent.com/11524048/85939789-d3c76500-b94a-11ea-8ad6-6f2eb872774e.png)
The reported disk geometry is 979/5/26.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: build2396
 - Build type: optimized

**Additional context**
Some information about WD1004A-27X and  Amstrad PC2086:
http://www.uncreativelabs.de/th99/c/U-Z/20223.htm
http://oldcomputer.info/pc/ams2086/index.htm

**Comment by OBattler** [comment]
This is the first time I hear of the WD1004A-27X... what we emulate is the WD1002-27X, which is different.

**Comment by kkwpsv** [comment]
They looks similarly, and I confused them by mistake. 😥
