### ISSUE TITLE
[SiS 471] AMI 486 Clone system does not boot

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#879]
**Describe the bug**
In configuration [SiS 471] AMI 486 Clone, if you install CPU type iDX4/100 or iDX4 OverDrive 100 or Pentium OverDrive 83, the system with MS-DOS v6.22 will not boot:

**Screenshots**
![20200628-172718-644](https://user-images.githubusercontent.com/58270614/85954241-d2179480-b97e-11ea-93a1-b854d5914af0.png)

**Desktop (please complete the following information):**
 - Windows 10 x64 2004
 - 86Box v2.10 Build 2403
 - Build type: [optimized]
 - HD controller type: [Internal IDE], C/H/S: 412/16/63 (202 MB)

When installing the remaining CPUs, the system with MS-DOS v6.22 boot without bugs.

**Comment by OBattler** [comment]
I don't think this is an emulator bug - it could well be that the BIOS simply is not compatible with those CPU's.

**Comment by OBattler** [comment]
It looks like a speed cap, seems the BIOS doesn't like CPU's faster than 75 MHz or so.

**Comment by OBattler** [comment]
Do the 75 MHz DX4's and the 63 MHz Pentium OverDrive work?

**Comment by maximus105** [comment]
> Do the 75 MHz DX4's and the 63 MHz Pentium OverDrive work?

Yes, they work. Only do not work:
iDX4 / 100
iDX4 OverDrive 100
Pentium OverDrive 83

**Comment by OBattler** [comment]
Do they break on both interpreter and recompiler?

**Comment by maximus105** [comment]
Yes, iDX4/75 works both when the "Dynamic Recompiler" option is on and off. Pentium OverDrive 63 also works when the "Dynamic Recompiler" option is on, but you cannot turn it off.

**Comment by OBattler** [comment]
I'm asking about the iDX4/100 and iDX4 OverDrive 100.

**Comment by maximus105** [comment]
> I'm asking about the iDX4/100 and iDX4 OverDrive 100.

Do not work:
iDX4/100
iDX4 OverDrive 100
Pentium OverDrive 83

**Comment by OBattler** [comment]
I'm asking if the iDX4/100 and iDX OverDrive 100 have problems on both interpreter and the recompiler.

**Comment by Fenix770** [comment]
I tested the Phoenix SiS 471. The 486 DX/4 100 mhz works both with interpreter and in dynamic recompiler.
 I tested the machine with PS/1 2133 hard disk image which includes software (DOS 5.0 + Win 3.1)

**Comment by maximus105** [comment]
> I'm asking if the iDX4/100 and iDX OverDrive 100 have problems on both interpreter and the recompiler.

Yes. They all do not work.

**Comment by OBattler** [comment]
It looks like it's a CPU speed cap on this particular BIOS. As such, I'm closing this with NOTABUG (though the CPU tables will be rectified in v2.20).
