### ISSUE TITLE
[i430VX] Epox P55-VA does not correctly detect the CPUs

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#884]
**Describe the bug**
[i430VX] Epox P55-VA does not correctly detect the CPUs Intel:
Mobile Pentium MMX 200
Mobile Pentium MMX 233
Mobile Pentium MMX 266
Mobile Pentium MMX 300

When passing POST to BIOS, they are defined as:
Am486DX4-S 198MHz
80486DX-S 16MHz
80486DX-S 33MHz

Also not correctly detected IDT WinChip CPUs and AMD CPUs:
K6 (model 7) 200
K6 (model 7) 233
K6 (model 7) 266
K6 (model 7) 300
K6-2/233
K6-2/266
K6-2/300 AFR-66
K6-2/366

**Screenshots**
![20200630-143420-644](https://user-images.githubusercontent.com/58270614/86140400-7faeb300-baf9-11ea-8da0-69c4f4a8ea26.png)
![20200630-143443-909](https://user-images.githubusercontent.com/58270614/86140411-82110d00-baf9-11ea-803b-dd7c2ef51eb7.png)
![20200630-143455-147](https://user-images.githubusercontent.com/58270614/86140417-83423a00-baf9-11ea-9003-db2ef76fc900.png)

**Desktop (please complete the following information):**
 - Windows 10 x64 2004
 - 86Box v2.10 Build 2416
 - Build type: [optimized]
 - HD controller type: [Internal IDE], C/H/S: 412/16/63 (202 MB)

**Comment by OBattler** [comment]
Not an emulator bug, not every BIOS supports every CPU. In the future (probably for v2.20), we're going to do an overhaul of the CPU table so we can better exclude non-supported CPU's.
