### ISSUE TITLE
Windows 95 setup crashes on PS/1 2133

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#885]
**Describe the bug**
On the IBM PS/1 2133, Windows 95 causes the emulator to segfault during the PnP device detection stage of setup.

**To Reproduce**
1. Config the machine with 486DX2/66 CPU and 8MB RAM
2. Install Win95 normally
3. Reboot after file copy stage
4. Sit back and wait for segfault

**Expected behavior**
Setup should complete properly without crashing 86Box.

**Screenshots**
![86box_9](https://user-images.githubusercontent.com/29031916/86312658-cf09f600-bc55-11ea-8c1f-05e39052e138.PNG)

**Desktop (please complete the following information):**
 - OS: Win10 2004 19041.329
 - 86Box version: v2.10 build 2417
 - Build type: Skylake optimised

**Additional context**
Even with the dynarec disabled, it still crashes:
![86box_10](https://user-images.githubusercontent.com/29031916/86314179-98ce7580-bc59-11ea-93fa-bc3297aa403d.PNG)
(above image is a custom build with debug on and all optimisations off)

**Comment by OBattler** [comment]
Does this still happen?

**Comment by WinFutureX** [comment]
It doesn't crash the emulator anymore, but instead the machine just reboots when getting to the GUI. Only booting in safe mode works.

**Comment by OBattler** [comment]
This is fixed now.
