### ISSUE TITLE
[QUESTION] Regarding the IBM PS/1 Model 2133

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#886]
I have found some information regarding the IBM PS/1 Model 2133. The ROM which is required to emulate the Model 2133 is PS1_2133_53G2974_ROM.bin dated April 26, 1993 and it attributes to the IBM PS/1 Model 2133-451, a machine with a 25 MHz 80486SX processor.

More information on to this page: https://www.old-computers.com/museum/doc.asp?c=1274

The Model 2133-451 comes with 2 MB of RAM standard and can max out at 32 MB. Only the higher-end PS/1 Model 2133-571 can go between 4 MB of RAM standard and can max out at 64 MB.

However, Stason disputes this claim and says that memory can range from 1 MB to 64 MB on all affected models: https://stason.org/TULARC/pc/motherboards/I/IBM-CORPORATION-486-PS-1-TYPE-2133-2155-2168-TYPE.html

Also, I found that four of the earlier PS/1 Model 2133 machines (711, 811, 13 and W13) had a 25 MHz Intel 80386SX processor.

Would it be possible to rename the machine "IBM PS/1 Model 2133-451" to indicate that is the exact model name of the machine and lower the RAM limit to 32 MB in 2 MB RAM increments?

Thank you for your time.

**Comment by TC1995** [comment]
Ok, will look into this. :)

**Comment by ppgrainbow** [comment]
Okie dokie! :D

**Comment by OBattler** [comment]
> Would it be possible to rename the machine "IBM PS/1 Model 2133-451" to indicate that is the exact model name of the machine
That would be possible, yes.

> and lower the RAM limit to 32 MB in 2 MB RAM increments?
Except that you said it yourself that not all sources agree on that. Until I see definitive proof of such limitations, I don't see a reason for making the change.

**Comment by ppgrainbow** [comment]
OBattler, okie dokie!

Here are some sources regarding memory limits on the PS/1 Model 2133-451:

**1.** https://www.memorystock.com/memory/IBMPS1WillowSeries2133451.html

Taken from the PS/1 Willow Series 2133-451 Memory upgrade page:

> **How much memory does the IBM PS/1 Willow Series 2133-451 Computer take?**
> 
> You can upgrade your IBM PS/1 Willow Series 2133-451 Computer to up to a maximum memory capacity of **32 MB Memory**.
> 

...and....

> **How many total memory slots to install memory?**
> 
> The Computer has 2 sockets to install memory, already with 2 MB (removable) standard memory installed. For best PS/1 Willow Series 2133-451 Computer performance use the maximum amount of 32 MB, fill all the slots with the max allowed memory per slot for your Computer.

**2.** https://www.pc-collection.com/gamme-ps1.php (information is in French)

**3.** http://www.computer-specifications.com/specifications/IBM-PS1WillowSeries2133451-Specs.html

That's all I can find. The PS/1 Model 2133-451 uses the Willow series motherboard. :)

**Comment by Fenix770** [comment]
I found a manual for 2133/2155/2168 models IBM PS/1 Resource Page:

https://ps1stuff.wordpress.com/download/downloads-for-type-2133/

I can deduce that there are two wrong statements in the **3.** site: 

**1.** It says only i486 SX/25 is supported: According to manual is true for 386SX and 486SX computers, which has 30-pin RAM modules on the mainboard. 486 SX/DX/DX2 with 72-pin modules on the motherboard have also a CPU upgrade socket.

**2.** It has 64kb of L1 cache: Standard 80486 CPUs have only 8kb of L1 cache. Except for some 486 DX4 100 Mhz and AMD 5x86 CPUs which has 16kb. 

**BTW:** I could not find any image of the 2133-451 mainboard. but I found a video in a Spanish blog that shows how to upgrade the system RAM in this model. _(He adds an 8mb module to the existing 2mb module to get 10mb in total)_

http://antoniortizcarrasco.blogspot.com/2014/09/8-mb-mas-para-mi-ibm-ps1-2133-451.html

The mainboard has only two slots of RAM. It can be deduced that the modules are 72 pin and 2 x 16mb should be used to get 32mb. 16mb 30 pin modules exist but are extremely rare, (maybe they were used in old servers machines) and in standard systems requires 8 x4mb 30 pin module to get 32mb.

**Comment by ppgrainbow** [comment]
Thank you for pointing this out. :) I really appreciate it.

So, is there any idea what is going to take to fix and mitigate the cache error (PS/1 129) even if I disabled cache in the CMOS setup and that 86Box doesn't emulate cache RAM at this time?

**Comment by OBattler** [comment]
I am afraid there is currently no way of getting rid of that error.
