### ISSUE TITLE
Chipset not recognized by TLB 2.52

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#895]
**Describe the bug**

I tried a software named The Last Byte Manager. This software can use the Shadow RAM of certain chipsets to map UMB memory.

The chipset OPTI-495 And the recently added 386SX OPTI-291 chipset are supported by the software but not detected.

**To Reproduce**

1. boot ms-dos from a Floppy or hard disk
2. Launch the file CHIPSET.EXE from DOS prompt
3. Answer yes, and the software start to check from a list of chipset.
4. The chipset is either not detected or detected as EFAR which is incorrect

**Expected behavior**
It is not a software problem because it detects correctly the SCATsx 82C236 chipset on the KMX-C-02, and the recently ported ECS 386/32 which has 82C302 chipset.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 1909
 - 86Box version: Last build
 - Build type: regular

Here is a copy of TLB 2.52
[Last byte manager 252.zip](https://github.com/86Box/86Box/files/4870503/Last.byte.manager.252.zip)

**Comment by OBattler** [comment]
For OPTi 495, if I specifically try the 495XLC test, the utility is writing to register 0x2D but said register does not appear at all in the 495XLC datasheet.

**Comment by OBattler** [comment]
It also doesn't find the OPTi 895 on the emulated OPTi 895, and that's also implemented in accordance with the datasheet, which makes me wonder if this thing is not simply buggy.

**Comment by OBattler** [comment]
On the OPTi 495, it doesn't even write to register 0x22 which also controls shadowing, it's as if it assumes the register to be in the correct state.

**Comment by Fenix770** [comment]
Hello!
I tested 386SX machine based on OPTI-291 chipset with the latest build:

A bug was fixed: HIMEM.SYS now detects the A20 line and loads.

A new bug I found is garbage on the screen after the TLBM loads and maps UMB memory.

PD: 
This also occurs with the Goldstar 286 (in PCEM) but not in the SPC-4216 which is based on the same SCAT 82C235 chipset, and using the same HD image file (also in PCEM).
I did not test these machines in 86box because cannot load the EMS/UMB drivers since the recent bug these chipsets.

Screenshots:

![20200709-212621-027](https://user-images.githubusercontent.com/31600563/87093825-31de2d00-c214-11ea-837a-87b19cfc4cd1.png)
![20200709-212749-724](https://user-images.githubusercontent.com/31600563/87093827-3276c380-c214-11ea-993f-2a7f1229c050.png)

**Comment by OBattler** [comment]
Could you upload the hard disk image, 86box.cfg, and nvr folder of that?

**Comment by Fenix770** [comment]
Here is the 86box.cfg and I don used a HD for this machine I only used a bootable floppy disk with MS-DOS 5.0 and the TLB drivers.

[86box.zip](https://github.com/86Box/86Box/files/4904157/86box.zip)
[DOS 5 boot.zip](https://github.com/86Box/86Box/files/4904162/DOS.5.boot.zip)

**Comment by OBattler** [comment]
Could you please upload the nvr folder as well?

**Comment by Fenix770** [comment]
Here is it: 
[nvr.zip](https://github.com/86Box/86Box/files/4906273/nvr.zip)

**Comment by Fenix770** [comment]
Today I tested the Mylex 486 with 82C895 chipset. The Las byte Manager cannot initialize it. Memmaker works and says there is about 70kb of UMB, but after a soft reset (CTRL+ALT+DEL) mem command shows no change and the upper memory is not used.
A hard reset is required to get the drivers loaded high.

**Comment by OBattler** [comment]
> For OPTi 495, if I specifically try the 495XLC test, the utility is writing to register 0x2D but said register does not appear at all in the 495XLC datasheet.

Perhaps it's making sure that register is not writable?

**Comment by OBattler** [comment]
The more I think of it, the more I think I was right above. I need to see what happens if I correctly make out of range registers non-writable and always return 0xFF.
