### ISSUE TITLE
[BUG] Paradise PVGA1A stretching issues

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#897]
There is a proble with the Paradise PVGA1A emulated graphics card involving having to display resolutions higher than 640 x 480 @ 4bpp or 800 x 600 @ 4bpp when 512 KB or 1 MB video RAM is selected in the configuration settings for the Paradise PVGA1A display adapter and it has nothing to do with the Micronics 386 I-CACHE machine.

When I attempt to use either 640 x 480 @ 8bpp, I encounter stretching issues when trying to use it.

Here are some example issues. First when using the Paradise VGA Windows 3.0 display driver disk:

![Windows 3 0](https://user-images.githubusercontent.com/32658796/86523270-c6185080-be1e-11ea-8d9f-00df4135d565.png)

When selecting 800x 600 @ 8bbps, Windows 3.0 exits back to the MS-DOS prompt.

Second, when attempting to run Neopaint with the /C2,-1,1024 switch:
![Neopaint stretch](https://user-images.githubusercontent.com/32658796/86523281-e9db9680-be1e-11ea-82f4-7cc26b744216.png)

Without the switch, Neopaint reports 256 KB of RAM instead of 512 KB or 1 MB if a higher video RAM count is selected for the Paradise PVGA1A:
![Neopaint VRAM Detection](https://user-images.githubusercontent.com/32658796/86523288-24453380-be1f-11ea-8593-c9a20db0f7b2.png)

Here's the information regarding the Paradise PVGA1A video card: http://www.vgamuseum.info/index.php/cpu/item/478-paradise-systems-pvga1a

The specs report that the graphics card has 256 KB of VRAM and can go to 1 MB maximum.

However, the Paradise VGA+ can only go to 256 KB of VRAM and can support up to 800 x 600 at 4bpp and the Paradise VGA Professional can go to 512 KB of VRAM and can support up to 800 x 600 @ 8bpp. Both of these cards use the WD PVGA1A video processor.

Here is some information about these cards.:

**1.** Paradise VGA Plus 16: https://stason.org/TULARC/pc/graphics-cards/P-R/WESTERN-DIGITAL-CORPORATION-VGA-PARADISE-VGA-PLUS.html
**2.** Paradise VGA Professional: https://stason.org/TULARC/pc/graphics-cards/U-Z/WESTERN-DIGITAL-CORPORATION-XVGA-PARADISE-VGA-PROF.html

There are two BIOS files dated February 26, 1988 at 10:45:40 AM, BIOS.BIN and paradisepvga1a.bin which is apparently the video processor.

Here is the 86Box.cfg file that I used: https://pastebin.com/8NsR6Bnp

Please correct these issues and find out what could be causing the stretching issue.

Thank you for your time and Happy Independence Day! :)

**Comment by OBattler** [comment]
This is now solved, so I'm closing this.
