### ISSUE TITLE
EMS memory chipset does not work on Headland 286/386sx machines

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#898]
**Describe the bug**

The MM.SYS device driver does not detect any expanded memory available on Trigem 286M and AMA-932J 386sx. 
This driver works correctly in PCEM v16 and provides EMS memory on the two machines.
Also at boot time appears an error saying "CMOS memory mismatch" each time the machine boots, not only when the ram size is changed in the 86box configuration. This error does not appear on PCEM.

**To Reproduce**
1. configure the hard disk in Setup  (IDE C/H/S 63/16/63)  
2. Simply boot the machine with the hard disk , it automatically loads the config.sys line with the EMS driver line (MM.SYS)  

Here is the hard disk image
[Headland 286 WIN 2.03.zip](https://github.com/86Box/86Box/files/4874286/Headland.286.WIN.2.03.zip)

**Screenshots**
![Headland Chipset EMS memory error 001](https://user-images.githubusercontent.com/31600563/86523788-e6103a00-be47-11ea-920e-8145b7b3282a.png)
![Headland Chipset EMS memory error 002](https://user-images.githubusercontent.com/31600563/86523789-e7416700-be47-11ea-8155-60a7081a93f0.png)
![Headland on PCEM v16](https://user-images.githubusercontent.com/31600563/86523790-e7d9fd80-be47-11ea-89e9-32eb1211a68d.png)

**Desktop (please complete the following information):**
 - OS: Win 10 ver 1909
 - 86Box version: Last commit
 - Build type: regular

**Comment by Fenix770** [comment]
PD: This also occurs with the SCAT chipsets. 

![SCAT](https://user-images.githubusercontent.com/31600563/86538141-7ee79980-beca-11ea-86cf-ed9d3d9be8ca.png)

**Comment by OBattler** [comment]
Fixed the Headland. The SCAT is next.

**Comment by OBattler** [comment]
Does EMS on the SCAT work on PCem?

**Comment by Fenix770** [comment]
Yes it works. Here is screenshot of QRAM's Manifest: I'm using DOS 5.0 +QRAM 2.02 +DOSMAX

![SCAT+QRAM](https://user-images.githubusercontent.com/31600563/87238002-5cc2af80-c3d3-11ea-8a85-05918f5558ec.png)

**Comment by Fenix770** [comment]
I tested the SCAT machines again. To my surprise the only SCAT machine that does not work on 86box is the Goldstar 286. But it works right in PCEM.

**Comment by Fenix770** [comment]
I found errors in the EMS memory in the Headland chipset: 
To test the EMS memory I used the programs utilities which are located in the C:\MEM directory.

The EMSTEST.COM file check if the data on EMS memory pages can be accesed. This does not work in 86box!

![HEADLAND 002](https://user-images.githubusercontent.com/31600563/87238726-98ae4280-c3dc-11ea-83d2-abb3be2d4a60.png)

In PCEM: 
![HEADLAND 006](https://user-images.githubusercontent.com/31600563/87238816-027b1c00-c3de-11ea-8ddf-96d68aa97ce5.png)


The MOVETEST.COM files works both 86box and  Pcem.

The OEMSTEST.COM check the LIM EMS fuctions. If I recall correctly Fuctions 1 to 16 correspons to the LIM 3.2 standard and it have to be supported in all EMS boards and chipsets. The remaining fuctions are LIM 4.0, some of them may or may not work depending on the hardware/software implementation. 
(example if the board is support LIM 3.2 at hardware level and have a LIM 4.0 device driver in this case some fuactions can not be emulated by software).

In 86box some LIM 3.2 fuctions are not suported.
![HEADLAND 003](https://user-images.githubusercontent.com/31600563/87238802-c5168e80-c3dd-11ea-8e37-2edfbd8b59b3.png).

Here is a screenshot in PCEM
![HEADLAND 005](https://user-images.githubusercontent.com/31600563/87238807-e7a8a780-c3dd-11ea-80f7-1f22b473b06b.png)

**Comment by OBattler** [comment]
EMSTEST works fine on the Trigem 286M on 86Box, let me try the AMA-932J.

**Comment by OBattler** [comment]
So the problem on the AMA-932J occurs when it's trying Disk I/O - this could also be an IDE bug.

**Comment by OBattler** [comment]
I have just noticed that the emulated Headland chipsets are a complete mess - the 286's are supposed to be GC101/102/103's (the 286 chipset), and the 386's HT18, but we give them all HT18.

**Comment by Fenix770** [comment]
I tested the AMA-932J on PCem as you suggested:

![EMS TEST 001](https://user-images.githubusercontent.com/31600563/87249798-a349f580-c437-11ea-9dca-caf83d90315c.png)

Also tested the AMA-932J on 86box with a DOS 5.0 boot disk with HIMEM.SYS and EMM386.EXE loaded.
The results are all fine. So I think the is problem in the EMS chipset emulation and not the IDE hard disk.

![EMS TEST 003](https://user-images.githubusercontent.com/31600563/87249857-fae86100-c437-11ea-8d79-e8a206df8173.png)

![EMS TEST 002](https://user-images.githubusercontent.com/31600563/87249866-03d93280-c438-11ea-87ad-8384b0ef0286.png)

![EMS TEST 004](https://user-images.githubusercontent.com/31600563/87249873-09cf1380-c438-11ea-8a1f-40d473019a98.png)

**Comment by Fenix770** [comment]
Thanks for this effort!

I tested the two machines and works right. The only thing left is the Trigem machine is defined as HT18 chipset but this is a GC103.

The TLBM detects the  GC103 as HT21, but it may be a TLBM bug since in its documentation says it can confuse sometimes the HT18 and HT21. 

And I tested this software in these chipset only to confirm if it works right, I'm not interested in using it with this particular chipset becuase it can create 128kb of UMB memory but in Headland chipset it disables the EMS page frame.

**Comment by OBattler** [comment]
I believe I changed the chipset name in the Trigem's description, but I'll look again. Also, the datasheet only mentions one register set (+ a series of register for shadow RAM EMS page, that I have no idea how they work, but the driver your VM uses definitely accesses them).

**Comment by Fenix770** [comment]
The bug with the Headland chipset is fixed. 
But There is a bug with SCAT chipset emulation. I don't know if I should open a new thread or not because is the same problem with a different chipset.
It's not only a bug with Goldstar 286. The rest of the SCAT machines have problems counting the correct amount of EMS memory and QRAM may, also, find an incorrect amount of high ram each boot. It should be 128kb (excluding the page frame at D000-DFFF), but may find 64/96 kb and the size may be different in each boot.
The implementation in Pcem works, it tested it on Windows 2.1 and Win 3.0 real mode. (both of the uses the EMS memory and the large page frame)
