### ISSUE TITLE
[OPTi 597] AMI Excalibur VLB do not start from under 86Box Manager v1.6.4

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#899]
**Describe the bug**
[OPTi 597] AMI Excalibur VLB do not start from under 86Box Manager v1.6.4. This bug appeared in build 2416. In build 2415 [OPTi 597] AMI Excalibur VLB starts without bugs from under 86Box Manager v1.6.4. Also freezes out and do not start from under 86Box Manager v1.6.4 [i430LX] Intel Premiere/PC on all builds. And even if you delete the previously created NVR and 86box.cfg and run 86Box Manager v1.6.4 again, these machines will freeze. If you do not use 86Box Manager v1.6.4, then these machines start up normally.

**Desktop (please complete the following information):**
 - Windows 10 x64 2004
 - 86Box v2.10 Build 2424
 - Build type: [Optimized Skylake]
 - HD controller type: [Internal IDE], C/H/S: 412/16/63 (202 MB)

**Comment by OBattler** [comment]
The machine has no problem without 86Box manager, so I have no idea why this happens.

**Comment by maximus105** [comment]
In the latest builds [OPTi 597] AMI Excalibur VLB is already started and works from under 86Box Manager v1.6.4. And [i430LX] Intel Premiere / PC still does not start and hangs from under 86Box Manager v1.6.4.

**Comment by maximus105** [comment]
[i430LX] Intel Premiere / PC is also already launched and works under 86Box Manager v1.6.4.

**Comment by OBattler** [comment]
Then this can be closed now.
