### ISSUE TITLE
Please implement compaq deskpro 386 (and earlier, if possible)

### ISSUE THREAD

**Issue by mph2016** [86Box/86Box#903]
**Is your feature request related to a problem? Please describe.**
Not per se, no.

**Describe the solution you'd like**

86Box provides several great implementations of the compaq portable computers. But, unless I'm overlooking something, there's no implementation of the Compaq desktop machines.  

PCJS implements several 386 models https://www.pcjs.org/machines/pcx86/compaq/deskpro386/ and links to rom files that 86Box could use to implement it's own version. 

They also have a section on the 286 model but I didn't find any roms or implementation; just documentation. 

**Describe alternatives you've considered**
I could simply use pcjs, but that would not be satisfactory as it isn't local, and it's not possible to change the hard disk size, number of hard disks, nor the amount of ram.

**Comment by OBattler** [comment]
We tried it and we had FPU errors, so it's going to have to wait for a FPU rewrite.

**Comment by OBattler** [comment]
This can be closed since these machines have long since been added (and it also turned out the FPU error was caused by a bit on the keyboard controller's input port (P1) being set wrong).
