### ISSUE TITLE
86Box stopped responding after window minimization

### ISSUE THREAD

**Issue by ToMi8088** [86Box/86Box#912]
Hello,
I recently managed to install Microsoft Excel on Windows 3.00a

During installation, I minimized the 86Box window, but when I maximized it back, 86Box stopped responding during the first phase of installation.

Do someone know how to fix it?

**Screenshots**
![1](https://user-images.githubusercontent.com/64270858/86899888-de33ec80-c10a-11ea-8af3-d92791bce4b2.PNG)

**Desktop:**
 - OS: Windows 7
 - 86Box version: v2.10 build 2435
 - Build type: Dev

**Comment by kkwpsv** [comment]
see #732 .

**Comment by dhrdlicka** [comment]
Duplicate of #732, closing.
