### ISSUE TITLE
Compaq Portable III 386 Error: "Unsupported intel 386 CPU version"

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#916]
**Describe the bug**
1. The TEST utility compaq diagnostic disk throws an error saying: "Unsupported intel 386 CPU version".
2.  installed Compaq DOS 3.31 successifully, but the CEMM and CACHE utilities lock up the machine.

I provide the HD image and the 86box.cfg and the Diagnostic floppy disk:
[86box.zip](https://github.com/86Box/86Box/files/4904255/86box.zip)
[Compaq Portable 386 - Hard Disk.zip](https://github.com/86Box/86Box/files/4904265/Compaq.Portable.386.-.Hard.Disk.zip)
[Compaq Portable Diagnostic Disk.zip](https://github.com/86Box/86Box/files/4904272/Compaq.Portable.Diagnostic.Disk.zip)

**Screenshots**
![20200710-030714-484](https://user-images.githubusercontent.com/31600563/87176071-f09b5b00-c2af-11ea-8da7-5a510606bb91.png)

**Desktop (please complete the following information):**
 - OS: Win 10 ver 1909
 - 86Box version: Last commit
 - Build type: regular and optimized

**Additional context**
I have the install floppies if are needed.

**Comment by OBattler** [comment]
It could be that the real Compaq Portable III 386 came with an earlier stepping of the 386. This is going to have to wait for v2.20 when I'm going to begin the work on the new 286/386/486 interpreter.

**Comment by OBattler** [comment]
I'm closing this as a CANTFIX - I have no idea what it wants and no way to figure it out.
