### ISSUE TITLE
[BUG] Trident TGUI9440 graphics issues

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#920]
There appears to be a graphics bug in Windows 3.1 when using the Trident TGUI9440 VLB/PCI emulated graphics card.

Although the drivers for the graphics card work, when the Clock app when using the analog format in the Settings menu, the hour, minute and second hand don't display at all.

Secondly in the Color settings of the Control Panel, the vertical black outlineon the basic and custom colour boxes don't appear, but the horizontal black lines do appear.

Here's a screenshot:
![20200712-072334-099](https://user-images.githubusercontent.com/32658796/87241306-ae206e00-c3d6-11ea-9f04-8826a4823e4d.png)

I got the drivers for the Trident 9440 emulated display adapter from the Metropolis BBS website: http://files.mpoli.fi/hardware/DISPLAY/TRIDENT/

Look for the file UX64_WIN.ZIP dated 1996-03-04. I'm wondering if any such issues are found on real physical hardware or not, but as far as I know, it appears to be a graphics card emulation bug.

The display resolution that I used was 1024 x 768 @ 256 colours, small fonts which is the maximum resolution for a graphics card with 1 MB of display RAM.

Here's the 86Box.cfg file: https://pastebin.com/9HQjrR6z

Please investigate what could be causing this bug. Thanks. ^^

**Comment by ppgrainbow** [comment]
As far as I know, there was an issue with the TGUI 9440 blitter. I can't seem to find a older issue regarding it. :(

Until this issue is fixed, either switch to a fully working emulated graphics card or use the generic SuperVGA drivers which came with Windows for Workgroups 3.11.

**Comment by OBattler** [comment]
Closing this since I got a report that it's now fixed.
