### ISSUE TITLE
APM/ACPI power off support + SB16 plug and play support

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#921]
**Is your feature request related to a problem? Please describe.**
No, it's more of a convenience thing.

**Describe the solution you'd like**
For the soft power off support, it should be supported in both the APM and ACPI BIOS. When the system is powered off, the emulator should not close in case the OS is shut down just to do hardware changes or something else.

For the Sound Blaster 16 PnP setting, the settings window should have an option that disables the IO address and IRQ settings and switches the sound card to ISA plug and play mode so Windows can auto-detect it. Windows XP's setup hardware detection process doesn't automatically pick up the SB16 until I manually install it via Control Panel.

**Describe alternatives you've considered**
No alternatives whatsoever.

**Additional context**
None.

**Comment by tiseno100** [comment]
ACPI soft power off works in some boards. Just it's in an early stage as of now. SB16 PnP might be a consideration, although you can work with SB PCI 128 too.

**Comment by OBattler** [comment]
I do have the Sound Blaster 16 PnP version on my plans for maybe v2.20, but I need to gather enough documentation and obtain a dump of the card's PnP data first.

**Comment by CRTRevivalDreamer** [comment]
[Here's the datasheet for the APM 1.1 specification](https://archive.org/download/Intel_Architecture_Labs_Software_Developer_CD_IAL_September_1995_Intel_1995/Intel%20Architecture%20Labs%20Software%20Developer%20CD%20%28IAL%29%28September%201995%29%28Intel%29%281995%29.ISO/FTP%2FIAL%2FPOWERMGM%2FAPMV11.PDF), and [here's the datasheet for the APM 1.2 specification](http://web.archive.org/web/19970104102315/http://www.intel.com/IAL/powermgm/apmv12.pdf).

**Comment by OBattler** [comment]
Sound Blaster 16 PnP is now emulated (has been added by RichardG some time ago), which leaves the soft power off.

APM soft power off is dependent on BIOS and the hardware, as APM is handled by the BIOS' SMI# handler in SMM, and most machines do not provide that capabilities.

ACPI soft power off is implemented, but for some strange reason, does not work on all boards, it's still being investigated but it's a separate (but known) issue.

As the issue has been, bugs notwithstanding, satisfied, I'm closing this.
