### ISSUE TITLE
Don't use TerminateThread

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#922]
The Windows implementation of `thread_kill` currently uses the `TerminateThread` Windows API:
https://github.com/86Box/86Box/blob/master/src/win/win_thread.c#L47-L53

The use of `TerminateThread` is actively discouraged by MSDN documentation:
>**TerminateThread** is a dangerous function that should only be used in the most extreme cases. You should call **TerminateThread** only if you know exactly what the target thread is doing, and you control all of the code that the target thread could possibly be running at the time of the termination. For example, **TerminateThread** can result in the following problems:
>
>* If the target thread owns a critical section, the critical section will not be released.
>* If the target thread is allocating memory from the heap, the heap lock will not be released.
>* If the target thread is executing certain kernel32 calls when it is terminated, the kernel32 state for the thread's process could be inconsistent.
>* If the target thread is manipulating the global state of a shared DLL, the state of the DLL could be destroyed, affecting other users of the DLL.

**Comment by OBattler** [comment]
This is now done.
