### ISSUE TITLE
86box crash and closes after playing the introduction music in Supertetris

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#923]
**Describe the bug**

At the startup of the game the music plays, but when it ends, 86box crash.

I tested different configurations:

A. This bug occurs in all 386 and 486 machines I tested on both 86box and Pcem, when I select Sound Blaster alone or SB+Roland MT-32.

B. I tested this game on the Goldstar 286 in PCem with SB and the game works. However, Pcem has not MT-32 emulation.

**To Reproduce**

1. Boot the hard disk with a 386 or a latter machine 
2. Type "CD SUPERTET" at C prompt
3. Delete the SUPERTET.CFG file ("DEL supertet.cfg")
4. Type Supertet at DOS prompt: Select VGA as graphics adapter and a sound card ( I tested SB and MT-32)
5. The game starts, but when the music finish, 86box closes automatically with an error.

**Screenshots**
![Image 1](https://user-images.githubusercontent.com/31600563/87266298-47b15380-c49b-11ea-9479-6566ef583766.png)

Here is the Hard disk file and the nvr files 
[311 mb DOS 6.0 update spanish.zip](https://github.com/86Box/86Box/files/4910377/311.mb.DOS.6.0.update.spanish.zip)
[nvr.zip](https://github.com/86Box/86Box/files/4910380/nvr.zip)

**Desktop (please complete the following information):**
 - OS: Win 10 ver 1909
 - 86Box version: Last commit
 - Build type: regular

**Additional context**
a. I tested  an old hard disk image with Adlib Gold software. 86box automatically closes  at startup if Adlib Gold is selected as sound card. I also created a new template with 86box manager 1.6.4 with the same result. I don't know if this behavior is caused by the same bug.

b.The game also works with DosBox.

c. I tested this game because it supports a wide variety of hardware  from Hercules/CGA with internal speaker, Tandy 16 color video mode with 3-voice speaker and DAC to EGA/VGA with SB and Roland MT-32.

**Comment by OBattler** [comment]
Committed fixes for both issues, make sure the remove AdLib Gold NVR before starting the emulator.
