### ISSUE TITLE
[QUESTION] Regarding "DTK Award 386SX"

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#928]
I found some information regarding the "DTK Award 386SX", it's official name is "**DTK PPM-333P**". The motherboard uses the OPTi-291 chipset and supports processor speeds between 16 MHz to 40 MHz using Intel, AMD or Cyrix 80386SX processors.

However, the BIOS doesn't seem to properly detect CPU speeds slower than 20 MHz in the POST diagnostics when running the emulated machine at 16 MHz:

![20200715-044124-784](https://user-images.githubusercontent.com/32658796/87504390-44dd6c80-c61b-11ea-918f-78186e58b665.png)

I have also found that according to this page below:

https://stason.org/TULARC/pc/motherboards/D/DTK-COMPUTER-INC-486-PPM-3333P.html

The minimum supported RAM is 1 MB and can max out at **16 MB** using two 4M x 9 DRAM modules on banks 0 and 1.

So, would it be possible to rename the machine "DTK PPM-3333P" and increase the RAM limit to 16 MB (in 1 MB increments)?

Thank you for your time.

**Comment by OBattler** [comment]
Closing because it's fixed.
