### ISSUE TITLE
MR BIOS no longer detects IDE disks after soft reset

### ISSUE THREAD

**Issue by richardg867** [86Box/86Box#929]
After a soft reset, MR BIOS (MR 430FX clone) reports an "ATA-Disc Configuration Change", and none of the attached IDE drives are detected anymore. Restarting the emulator results in another "ATA-Disc Configuration Change", with the drives showing up again.

**Comment by OBattler** [comment]
This was due to too long reset time (we had 5 ms while the ATA-3 specification says 1 ms + 400 ns).
