### ISSUE TITLE
Ensoniq Soundscape  emulation

### ISSUE THREAD

**Issue by anabate123** [86Box/86Box#933]
**Is your feature request related to a problem? Please describe.**
No, it's more of a convenience thing.

**Describe the solution you'd like**
I would like to see If anyone can emulate the Ensoniq Soundscape ISA family of sound cards.

**Describe alternatives you've considered**
I would just use Ensoniq AudioPCI ES1371 on 86Box for Windows 95+ or Sound Blaster 1.5 and VirtualMIDISoft with 2 MB patch set for Windows 3.1 or WFW 3.11

**Additional context**
http://pdf.datasheetcatalog.com/datasheet/motorola/M68000AD.pdf
https://pdf1.alldatasheet.com/datasheet-pdf/view/47932/AD/AD1848KP/+35844UNCZzE8zNwOU+/datasheet.pdf

**Comment by qeeg** [comment]
Neither of those PDFs are related in the slightest.

**Comment by OBattler** [comment]
Closing this because it's impossible due to a complete lack of documentation.

**Comment by CRTRevivalDreamer** [comment]
Here are the datasheet for the ["OTTO"](https://github.com/86Box/86Box/files/7627175/ES5506.pdf) and ["ESP"](https://github.com/86Box/86Box/files/7627176/ES5510.pdf) sound chips, which fueled the SoundScape series of ENSONIQ sound cards.

**Comment by Wohlstand** [comment]
In addition to specifications from above, I can hint to the example source code that can use SoundScape, just from Duke Nukem 3D:
- https://github.com/videogamepreservation/dukenukem3d/blob/master/audiolib/SOURCE/SNDSCAPE.C
- https://github.com/videogamepreservation/dukenukem3d/blob/master/audiolib/SOURCE/SNDSCAPE.H

I wanted to verify some, however bummer, it doesn't work, and existing "Ensoniq AudioPCI ES1371" seems is not that I needed, or... I should try another DOS driver to get it work? 🤔
