### ISSUE TITLE
Crash when moving from a high RAM amount to a higher one

### ISSUE THREAD

**Issue by richardg867** [86Box/86Box#934]
How to reproduce:

* Select a Slot 2 machine like the Gigabyte GA-6GXU
* Start it with 2032 MB RAM
* Increase the RAM to 2048 MB
* The emulator will crash without saving the new RAM amount

**Comment by Cacodemon345** [comment]
This does not happen with the new UI rewrite that uses Qt.

**Comment by OBattler** [comment]
That's because you're on Linux, using the 64-bit binary. This only affects 32-bit binaries.

**Comment by OBattler** [comment]
I can confirm that this now fixed.
