### ISSUE TITLE
OPL3 is not working in Stereo

### ISSUE THREAD

**Issue by James-F2** [86Box/86Box#945]
**Describe the bug**
OPL3 (SBPro2.0 and SB16) does not work in Stereo as it should.

**To Reproduce**
Enable this command in DOS:
`SET DMXOPTION=-OPL3-PHASE`
In autoexec.bat or at any time.
Run Doom1 E1M1 and listen to the music,, guitars should be panned hard left and right.

**Expected behavior**
https://www.youtube.com/watch?v=jFDKg7GHCnk
Guitar should start on Left channel.
Works in Dosbox (NukedOPL) and on my real Pentium machines with SBPro2 and SB16.

**Desktop (please complete the following information):**
 - OS: Windows 7, i7 3770k, 16GB, GTX660.
 - 86Box version: v2.10 build 2504
 - Build type: Development

**Comment by OBattler** [comment]
With Sound Blaster 16, I use the following line in AUTOEXEC.BAT:
SET BLASTER=A220 I5 D1 H5 P330 T6 E620
And DOOM configured appropriately as well. I do hear a noticable difference between with -phase and without -phase in DMXOPTION.

**Comment by James-F2** [comment]
Indeed.
The -PHASE command is for true stereo in Doom for PCM audio.
The -OPL3 command is for stereo OPL3 which doesn't work,, and it stays in OPL2 mono mode.

I have posted a youtube video of how OPL3 mode should sound in Doom.
First guitar sound should be on the LEFT speaker, but in 86Box (and PCem) everything remains in the center.

Nuked OPL obviously has full OPL3 (stereo) emulation since it works in DOSBox.

**Comment by OBattler** [comment]
Then this means NukedOPL has been ported incorrectly. I've begun comparing the DOSBox and 86Box code, though I'm going out now, so I'll continue when I'm back.

**Comment by OBattler** [comment]
Can you upload your build of DOSBox?

**Comment by James-F2** [comment]
https://dosboxece.yesterplay.net/

DOSBox ECE.
This is the best SVN of dosbox currently, everyone uses it.

Make sure you have this line in dosbox configuration:
`oplemu     = nuked`

**Comment by James-F2** [comment]
Fixed in build 2507.
Thank you very much!
