### ISSUE TITLE
Fullscreen notification does not turn off

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#948]
**Describe the bug**
After checking the "do not show this message again" checkbox, the notification about switching to fullscreen mode appears again after a complete exit from the created machine in 86Box and its subsequent start. Also, a notification about switching to fullscreen mode still appears if the created machine is immediately started in fullscreen mode via 86Box.exe -f
Please fix this or add the ability to completely disable these notifications. Also add the ability to completely disable the 86Box complete exit notification. Also add the ability to completely disable the notification about the complete reset of the 86Box and the confirmation about saving the changed settings in the 86Box. For example, there is no such thing in PCem: it immediately switches to fullscreen mode without notification, exits PCem immediately without notification, and a hard reset immediately works in PCem without notification.

**Comment by mph2016** [comment]
+1 

I can't get rid of the fullscreen notification too, and it would be nice to disable the exit notification

**Comment by richardg867** [comment]
The fullscreen notification was fixed, and a suppression checkbox was added to the reset and exit confirmations.

It's worth noting that these are saved in the config file, so the preference persists for a VM until the configuration file is deleted or manually edited.
