### ISSUE TITLE
AMSTRAD MEGACCD ISSUE

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#965]
**Describe the bug**
Amstrad MegaCD (PC part) issues:
- Memory amount not correctly recognized by BIOS: setting 1 MB, POST test see 1M, but BIOS report 32MB, thus not boot possible. Cannot adjust the memory amount in the BIOS (Ctral-Alt-S to access). Only working configuration so far possible is 32MB, wich is not good:
- Maximum amount of RAM for the MEGAPC: 16MB (4x4Mb, do not work with 16MB SIM), 86Box config panel let config up to 32 Mb.
- Internal IDE controller not recognized (even set to Internal): POST test give an Hadware Failure.

**To Reproduce**
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - 86Box version: latest regular build from gthub

**Comment by OBattler** [comment]
Its chipset's implementation is currently the same stub it is from PCem, I have it in my plans to properly reimplement it already for v2.10, as the machine is of especial importance to me as it was my first PC.

**Comment by Banjo-Oz** [comment]
Glad to see this is a known issue, I've had problems with this machine on PCEm and was turning to 86Box in the hopes it would work on this, only to have the exact same issues as the OP! :(

Very happy to hear it's in the cards to be fixed! My first PC was an Amstrad PC5286 (I really wish that could be emulated in 86Box) and I dreamed of owning a MegaPC!

**Comment by OBattler** [comment]
My first PC was wactually the MegaPC, which is why I have extra motivation to fix it.

**Comment by OBattler** [comment]
> Cannot adjust the memory amount in the BIOS (Ctral-Alt-S to access).

From what I see, I get the same thing on the other Quadtel 386SX machine I added on my WIP branch, and that has a chipset with no EMS, so I'm not even sure why there's EMS in CMOS Setup there. Perhaps a leftover?

Tiseno100 has reimplemented this machine's chipset, but even he hasn't implemented its EMS capability, which I have yet to do.

**Comment by OBattler** [comment]
Closing this as this is a part of the wider issue: https://github.com/86Box/86Box/issues/238 .
