### ISSUE TITLE
Emulate Victor V86P

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#966]
**Is your feature request related to a problem? Please describe.**
V86P is a ***8086*** dual freq (4,77/10Mhz) little portable. 640K of RAM, seems to have a CHIPS Technology chipset that let adding more memory used as EMS Memory.
One 720K drive and 1 20Mb hardrive (specific), or 2 720K drive.
CGA card with selectable gray level emulation (B&W LCD supertwist screen).

**Describe the solution you'd like**
I dumped the ROM. it's an Award BIOS
![image](https://user-images.githubusercontent.com/16312616/89739779-b62a0700-da83-11ea-8b6f-2b53baf82c46.png)

**Comment by Fenix770** [comment]
That´s a nice laptop!
Has blue backlight like the Toshiba T1000/T1200?

The only issue to implement it, is the EMS hardware works diferently than the Toshibas's. A data sheet and time implement it will be required.The hard disk interface is the same than the T1200 which consist in a JVC/Ricoh controller but datasheet does not exist. 

Here if found a site from someone that tried to reverse engineer it.
[https://knm.org.uk/blog/2017/04/the-jvc-26-pin-hard-disk-interface-part-1/](url)

Also there are mainboars with hardware EMS support in 86box like NEAT 286 and the DTK 386/SX, (this was inherited from PCEm)  which has a NEATsx board, but the EMS emulation has not implemented yet. 
Also the actual Zenith Datasport has propietary port for adding a 1mb EMS Ram board,

The Machines with hardware EMS support were implemeted by programmers that tested the actual hardware.
John Elliot, implemented the T1000/1200/3100, and had the real T1000 and T3100.
Great Psycho had a machine with the SCAT 82C235 chip, and implemented several 286 based on that chip.

**Comment by jvernet** [comment]
No backlight, but a relatively good B&W LCD SuperTwist.
Greyscales can be emulated trough "flickering" alternatively display black and white.

**Comment by jvernet** [comment]
V86P ROMS set
[VICTO V89P.zip](https://github.com/86Box/86Box/files/5058880/VICTO.V89P.zip)

**Comment by jvernet** [comment]
Chipset used: Chips Technology  Chips & Tech 82C100
Datasheet:
[https://knm.org.uk/datasheets/82c100.pdf](url)

**Comment by lkundrak** [comment]
@jvernet I've started looking into this and it looks plausible. There's a couple of things I'm missing though:

1.) Could you please dump the original font ROM? My machine had a bad character generator ROM and I had to replace it. It is the socketed chip to the right of the pair of BIOS ROMs. If you prefer to dump it in situ, please use "425 getfont font.rom" command with the utility I'm attaching.\

2.) My machine doesn't have a working LCD at the moment and I can't completely understand how is SMARTMAP (contrast enhancement) supposed to work. I'm wondering if you could help me figure that out?

In general, CTRL+ALT+F6 seems to choose between 9 different SMARTMAP configurations. Could you please try them all in sequence and take a picture of each step? The "425 colors" command (again, attached) draws a test picture with all combinations of foreground and background colors that could be useful as a test image.

I'm not sure if the smartmap takes the whole screen into account or not; it would be helpful if you could run some applications with known color sets and see what effect SMARTMAP has, ideally keeping trace of SMARTMAP setting and taking pictures along the way. No graphical apps/games though, SMARTMAP only works in text modes.

Thank you!

425.c and 425.com are here: [425.zip](https://github.com/86Box/86Box/files/6248950/425.zip)

**Comment by jvernet** [comment]
Here is the font dump. Smartmap pictures later.
[V86P font.zip](https://github.com/86Box/86Box/files/6252893/V86P.font.zip)

**Comment by jvernet** [comment]
Inside this archive, you will find some V86P utilities like GRAYSET.COM wich will change SMARTMAP from command line, and SXTEMM.SYS, the Chips&Technologies EMM drivers for the V86P.
[UTILS.zip](https://github.com/86Box/86Box/files/6258952/UTILS.zip)

**Comment by Fenix770** [comment]
Hello!
It's interesting.(Sorry for asking) Would be possible to emulate the JVC/Ricoh hard disk controller?. I would be a nice addition to the Toshiba T1200 which uses the same HD controller.

**Comment by waltje** [comment]
My teacher had one of these, way-back-when.  Fairly standardmachine, other than the hard disk interface it used (with the JVCdrive.)

--fred
    On Monday, April 5, 2021, 11:39:29 AM EDT, JVernet ***@***.***> wrote:  
 
 


Inside this archive, you will find some V86P utilities like GRAYSET.COM wich will change SMARTMAP from command line, and SXTEMM.SYS, the Chips&Technologies EMM drivers for the V86P.
UTILS.zip

**Comment by waltje** [comment]
Its a standard RLL2,7 drive with ST506 command set using non-balanced(just TTL) interface on a 26-pin connector.  The Victor macines used theOMTI chipset to drive it, can't remember for the Toshiba.
--Fred

    On Monday, April 5, 2021, 10:40:41 PM EDT, Fenix770 ***@***.***> wrote:  
 
 


Hello!
It's interesting.(Sorry for asking) Would be possible to emulate the JVC/Ricoh hard disk controller?. I would be a nice addition to the Toshiba T1200 which uses the same HD controller.
