### ISSUE TITLE
ACPI power button emulation

### ISSUE THREAD

**Issue by ghost** [86Box/86Box#973]
When will be ACPI power button emulated?
On some machines Windows 98 supports hibernation, but cannot be used, missing ACPI power button emulation, but system detect ACPI system button.
machines:
[i430TX] PC Partner MB540N
[VIA MVP3] AOpen AX59 Pro
[i440EX] QDI EXCELLENT II
[i440BX] ABIT BF6
[i440BX] AOpen AX6BC
[VIA Apollo Pro] PC Partner APAS3
On two machines emulator shutdown properly, PC Partner MB540N and QDI EXCELLENT II.

**Comment by daviunic** [comment]
Is there any particular reason why you closed, reopened and then again closed this issue?

**Comment by Bogus3** [comment]
I closed this issue, because no answer long time.
Windows 98 detect ACPI power button, but cannot be used in 86box.

**Comment by OBattler** [comment]
I can add this when I get around to adding the toolbar.

**Comment by Bogus3** [comment]
ok, thank you
