### ISSUE TITLE
[BUG] IBM PC 330 not posting

### ISSUE THREAD

**Issue by PentiumMMX166** [86Box/86Box#974]
**Describe the bug**
When I try to start the IBM PC 330, It won't post, no matter what video card I use, no matter how much ram I give it, no matter what CPU i pick, anything. nothing changes, still the same issue.

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Machine Type' and pick "i486" and then pick "IBM PC 330"
3. Pick the CPU (I picked 486DX2 66), and RAM (I picked 16 MB)
4. Pick the Graphics card (I picked Trident TVGA8900D)
5. Run it.

**Expected behavior**

**Screenshots**
I expect it to run and show the BIOS

**Desktop (please complete the following information):**
 - OS: Windows 7
 - 86Box version: 2.10 Build 2533
 - Build type: regular

**Additional context**
none

**Comment by amdk6** [comment]
bruv, don't you realise that it only works with the iDX4 or the Pentium OverDrive

**Comment by PentiumMMX166** [comment]
I should have googled that computer before posting this!
