### ISSUE TITLE
Micronics Spitfire doesn't start up properly

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#990]
**Describe the bug**
The Micronics Spitfire machine doesn't boot up properly. The display remains a constant black and only a short BIOS beep is heard.

**To Reproduce**
1. Set machine to Micronics Spitfire with any CPU and amount of RAM
2. Reset and insert bootable floppy (the BIOS will try to read the floppy)

**Expected behavior**
The machine should display something on screen.

**Screenshots**
![spitfire_fail](https://user-images.githubusercontent.com/29031916/92017508-76a2c200-ed86-11ea-927e-a2fde613955b.PNG)

**Desktop (please complete the following information):**
 - OS: Win10 2004 build 19041.450
 - 86Box version: Custom from source (167abff1f015df697157bccbf679a801436bd044)
 - Build type: Dev + `OPTIM=y`

**Additional context**
None.

**Comment by tiseno100** [comment]
Try to not put a PCI graphics card in it. This machine is fairly unstable and it's a matter of time to get dev branched.

**Comment by OBattler** [comment]
This machine has now been fixed.
