### ISSUE TITLE
IBM AT 301 Keyboard Error happens every single time 

### ISSUE THREAD

**Issue by benmalt277** [86Box/86Box#991]
Describe the bug
the bug is when i bootup the IBM AT in 86Box it tests the ram and then gives me 301 Keyboard Error every single time

To Reproduce
1. Go to 86Box
2. Start The IBM AT
3. Wait for ram test to finish

Expected behavior
i expected for the ibm at to boot past the ram test without any errors

OS And 86box Version
 - OS:  Windows 10
 - 86Box version: [v2.10 build 2540]
 - Build type:  Regular

**Comment by OBattler** [comment]
This is in the process of being fixed by the complete rewrite of keyboard and keyboard controller emulation.

**Comment by JoshuaMaitland** [comment]
Looks like it's being fixed!! Is it possible to close this issue please?

**Comment by qeeg** [comment]
Not until the fix is actually in Jenkins builds.

**Comment by JoshuaMaitland** [comment]
> Not until the fix is actually in Jenkins builds.

I've actually tested it in the latest jenkins build and it works like a charm.

**Comment by JoshuaMaitland** [comment]
> Not until the fix is actually in Jenkins builds.

I've actually tested it in the latest jenkins build and it looks like the keyboard error has gone.

**Comment by OBattler** [comment]
This is being closed because it no longer happens, on Jenkins builds.
