### ISSUE TITLE
Machine name in title or status area of window [Feature]

### ISSUE THREAD

**Issue by frankmcc** [86Box/86Box#994]
When running multiple systems, especially cloned systems, it is sometimes difficult to determine the system you are working in. If the machine name was in the title or status area of the window, it would be easier to discern which system is being worked with.

**Comment by Winins0** [comment]
That is stored in 86Box Manager rather then 86Box itself so I don't think its doable.

**Comment by dhrdlicka** [comment]
This could be done as a part of the suggested integration of Manager into 86Box itself.

**Comment by OBattler** [comment]
I think this can be closed now since it has been implemented alongside the toolbar.
