### ISSUE TITLE
input device joysticks do not map the axis properly

### ISSUE THREAD

**Issue by trs-eric** [86Box/86Box#997]
**Describe the bug**
The game axis, particularly HAT axis don't all seem to be mapping properly in 86box

**To Reproduce**
1. Get an xbox 360 controller (or other multi-axis controller)
2. Map the x and y axis as well as other axis such as rotation or POV hat
3. Try to use the controllers in a client VM like windows 98 and the wrong behavior occurs, for example, after mapping the x, y, z, rotation x and rotation y axis, the rotation axis and the x and y axis are correct but the rotation x and y (POV) axis sets off buttons 1,2,3 and 4 in a binary pattern. Pressing buttons 1-4 also set off buttons 1-4 in the client machine.

**Expected behavior**
All configured host axis should map to the client controller as intended and configured

**Screenshots**
Left side: Host (Windows 10) controller settings
Right side: 86box input settings, showing the correct buttons and axis are mapped
Middle: Client (Windows 98 SE) showing idle state of controller

![image](https://user-images.githubusercontent.com/7797277/92666910-21a80400-f2d0-11ea-8716-284176f0db69.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v2.07 [245af88d, build 2008]
 - Build type: optimized zen 32 and also normal build

**Additional context**
Controller settings:

[Input devices]
mouse_type = ps2
joystick_type = 4
joystick_0_nr = 2
joystick_0_axis_0 = 1
joystick_0_axis_1 = 0
joystick_0_button_0 = 0
joystick_0_button_1 = 1
joystick_0_button_2 = 2
joystick_0_button_3 = 3
joystick_0_button_4 = 5
joystick_0_button_5 = 6
joystick_0_button_6 = 7
joystick_0_button_7 = 8
joystick_0_button_8 = 9
joystick_0_button_9 = 10
joystick_1_nr = 2
joystick_1_axis_0 = 0
joystick_1_axis_1 = 3
joystick_1_button_0 = 2
joystick_1_button_1 = 3
joystick_1_button_2 = 13
joystick_1_button_3 = 14
joystick_1_button_4 = 15
joystick_1_button_5 = 16
joystick_1_button_6 = 17
joystick_1_button_7 = 18
joystick_1_button_8 = 19
joystick_1_button_9 = 20
joystick_2_nr = 2
joystick_2_axis_0 = -2147483648
joystick_2_axis_1 = 1073741824
joystick_2_button_0 = 21
joystick_2_button_1 = 22
joystick_2_button_2 = 23
joystick_2_button_3 = 24
joystick_2_button_4 = -1
joystick_2_button_5 = -1
joystick_2_button_6 = -1
joystick_2_button_7 = -1
joystick_2_button_8 = -1
joystick_2_button_9 = -1
joystick_3_nr = 0
joystick_0_pov_0 = 3, 2
joystick_0_axis_2 = 4

**Comment by OBattler** [comment]
Did you tell the guest OS to use a CH Flightstick?

**Comment by trs-eric** [comment]
Hi thank you for checking this out. Yes I configured the guest OS to use a CH Flightstick. The issue also seems to affect Thrustmaster Flight Control System. I was unable to get the sidewinder to register in the guest at all but that could potentially be a driver issue.

**Comment by sirius909** [comment]
Can confirm this issue, as of 3.11 POV still doesn't work no matter what buttons I map it to.

**Comment by OBattler** [comment]
Try now, I know a POV-related bug has since been fixed.

**Comment by OBattler** [comment]
Closing this because this should in fact be fixed now by lemondrops' PR that fixed POV configuration.
