### ISSUE TITLE
Freezing Problem.

### ISSUE THREAD

**Issue by leesa49** [86Box/86Box#999]
Can you heard Norton Commander (NC) ?

1. Launch NC
2. after several time, you can see Screen Saver.
3. No Touch PC...
4. after several time~ 86Box Freezing

**Comment by daviunic** [comment]
@leesa49 can you please try this again with the latest build (currently 2689) to see if the problem is still there?

**Comment by Diicorp95** [comment]
> 
> 
> Can you heard Norton Commander (NC) ?
> 
>     1. Launch NC
> 
>     2. after several time, you can see Screen Saver.
> 
>     3. No Touch PC...
> 
>     4. after several time~ 86Box Freezing

As far as I can know, it's a bug in NC. I've experienced it with NC in several emulators (DOSBox, Microsoft VPC 2007, 86Box).

**Comment by OBattler** [comment]
Since this is not an 86Box bug, I'm closing this.
